DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentStack.cpp File Reference
AlignmentStack.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Objects.h"
#include "DD4hep/Printout.h"
#include "DD4hep/InstanceCount.h"
#include "DDAlign/AlignmentStack.h"
Functions
static dd4hep_ptr< AlignmentStack > & _stack ()
static dd4hep_ptr< AlignmentStack > & _stack (AlignmentStack *obj)
Function Documentation
_stack() [1/2]
static dd4hep_ptr<AlignmentStack>& _stack () static
Definition at line 26 of file AlignmentStack.cpp.
References s.
Referenced by _stack(), DD4hep::Alignments::AlignmentStack::create(), DD4hep::Alignments::AlignmentStack::exists(), DD4hep::Alignments::AlignmentStack::get(), DD4hep::Layering::layer(), and DD4hep::Alignments::AlignmentStack::release().
_stack() [2/2]
static dd4hep_ptr<AlignmentStack>& _stack (AlignmentStack * obj) static
Definition at line 30 of file AlignmentStack.cpp.
References _stack(), DD4hep::dd4hep_ptr< T >::adopt(), and s.