DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentsManager.cpp File Reference
AlignmentsManager.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Handle.inl"
#include "DD4hep/Printout.h"
#include "DD4hep/InstanceCount.h"
#include "DD4hep/MatrixHelpers.h"
#include "DDCond/ConditionsPool.h"
#include "DDAlign/AlignmentsManager.h"
Classes
class DD4hep::Alignments::AlignContext
struct DD4hep::Alignments::AlignContext::Entry
struct DD4hep::Alignments::AlignContext::PathOrdering
Namespaces
DD4hep
Namespace for the AIDA detector description toolkit.
DD4hep::Alignments
Namespace for the alignment part of the AIDA detector description toolkit.
Typedefs
typedef Conditions::ConditionDependency DD4hep::Alignments::Dependency
Functions
DD4HEP_INSTANTIATE_HANDLE_NAMED (AlignmentsManagerObject)
void computeDelta (AlignmentCondition cond, TGeoHMatrix &tr_delta)
Compute the alignment delta for one detector element and it's alignment condition.
Function Documentation
computeDelta()
void computeDelta (AlignmentCondition cond, TGeoHMatrix & tr_delta)
Compute the alignment delta for one detector element and it's alignment condition.
Definition at line 176 of file AlignmentsManager.cpp.
References DD4hep::Geometry::_transform(), DD4hep::Alignments::AlignmentCondition::data(), DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::AlignmentData::detectorTrafo, DD4hep::Alignments::AlignmentData::detectorTransformation(), DD4hep::Alignments::Delta::flags, DD4hep::Alignments::Delta::HAVE_PIVOT, DD4hep::Alignments::Delta::HAVE_ROTATION, DD4hep::Alignments::Delta::HAVE_TRANSLATION, DD4hep::Alignments::Delta::pivot, DD4hep::Alignments::Delta::rotation, DD4hep::Alignments::Delta::translation, and DD4hep::Alignments::AlignmentData::worldTrafo.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute().
DD4HEP_INSTANTIATE_HANDLE_NAMED()
DD4HEP_INSTANTIATE_HANDLE_NAMED (AlignmentsManagerObject)
Referenced by DD4hep::Alignments::AlignmentsManager::from().