DD4hep: DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/BoxSegment_geo.cpp File Reference
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/BoxSegment_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
Functions
static Ref_t create_element (LCDD &lcdd, xml_h e, Ref_t sens)
Function Documentation
static Ref_t create_element (LCDD & lcdd, xml_h e, Ref_t sens) [static]
Definition at line 24 of file BoxSegment_geo.cpp.
References _U, DD4hep::Geometry::PlacedVolume::addPhysVolID(), DD4hep::XML::Element::child(), DD4hep::XML::Element::hasAttr(), DD4hep::XML::DetElement::id(), DD4hep::XML::DetElement::isSensitive(), DD4hep::XML::Dimension::limitsStr(), DD4hep::Geometry::LCDD::material(), DD4hep::XML::DetElement::materialStr(), DD4hep::XML::Dimension::nameStr(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::regionStr(), DD4hep::Geometry::SensitiveDetector::setType(), DD4hep::XML::Dimension::typeStr(), and DD4hep::XML::Dimension::visStr().