DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/CylinderShell_geo.cpp File Reference
CylinderShell_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
Functions
static Ref_t create_detector (LCDD &lcdd, xml_h e, SensitiveDetector sensitive)
Function Documentation
create_detector()
static Ref_t create_detector (LCDD & lcdd, xml_h e, SensitiveDetector sensitive) static
Definition at line 49 of file CylinderShell_geo.cpp.
References _U, DD4hep::Geometry::PlacedVolume::addPhysVolID(), DECLARE_DETELEMENT, e, DD4hep::XML::Dimension::id(), DD4hep::XML::DetElement::id(), m, M_PI, DD4hep::Geometry::LCDD::material(), DD4hep::XML::DetElement::materialStr(), DD4hep::XML::Dimension::nameStr(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::rmax(), DD4hep::XML::Dimension::rmin(), DD4hep::Geometry::Volume::setSensitiveDetector(), DD4hep::Geometry::SensitiveDetector::setType(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::XML::Dimension::visStr(), and DD4hep::XML::Dimension::z().