DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/CylindricalBarrelCalorimeter_geo.cpp File Reference
CylindricalBarrelCalorimeter_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
Functions
static Ref_t create_detector (LCDD &lcdd, xml_h e, SensitiveDetector sens)
Function Documentation
create_detector()
static Ref_t create_detector (LCDD & lcdd, xml_h e, SensitiveDetector sens) static
Definition at line 24 of file CylindricalBarrelCalorimeter_geo.cpp.
References DD4hep::Geometry::_toString(), _U, DD4hep::Geometry::PlacedVolume::addPhysVolID(), DD4hep::Geometry::LCDD::air(), DECLARE_DEPRECATED_DETELEMENT, DECLARE_DETELEMENT, DD4hep::XML::Dimension::dimensions(), e, DD4hep::XML::DetElement::id(), DD4hep::XML::Dimension::inner_r(), DD4hep::XML::Component::isSensitive(), DD4hep::XML::Dimension::limitsStr(), m, M_PI, DD4hep::Geometry::LCDD::material(), DD4hep::XML::Component::materialStr(), DD4hep::XML::Dimension::nameStr(), DD4hep::XML::Dimension::outer_z(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::regionStr(), DD4hep::XML::Dimension::repeat(), DD4hep::Geometry::Volume::setAttributes(), DD4hep::Geometry::Tube::setDimensions(), DD4hep::Geometry::Volume::setSensitiveDetector(), DD4hep::Geometry::SensitiveDetector::setType(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::XML::Dimension::thickness(), and DD4hep::XML::Dimension::visStr().