DD4hep: DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetectorTools.cpp File Reference
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetectorTools.cpp File Reference
#include "DD4hep/DetectorTools.h"
#include "DD4hep/Printout.h"
#include "DD4hep/LCDD.h"
#include "DD4hep/objects/DetectorInterna.h"
#include <stdexcept>
#include <memory>
#include "TGeoMatrix.h"
Namespaces
namespace DD4hep
Namespace for the AIDA detector description toolkit.
namespace DD4hep::Geometry
Namespace for the geometry part of the AIDA detector description toolkit.
namespace DD4hep::Geometry::DetectorTools
Helper namespace used to answer detector element specific questons.
Defines
#define DETECTORTOOLS_CPP
Functions
std::string DD4hep::Geometry::DetectorTools::elementPath (const PlacementPath &nodes, bool reverse)
Assemble the path of the PlacedVolume selection.
void DD4hep::Geometry::DetectorTools::elementPath (DetElement parent, DetElement elt, ElementPath &detectors)
Collect detector elements to any parent detector element.
void DD4hep::Geometry::DetectorTools::elementPath (DetElement elt, PlacementPath &nodes)
Collect detector elements placements to the top detector element (world) [fast, but may have holes!].
void DD4hep::Geometry::DetectorTools::elementPath (DetElement parent, DetElement element, PlacementPath &nodes)
Collect detector elements placements to the parent detector element [no holes!].
DetElement DD4hep::Geometry::DetectorTools::findElement (LCDD &lcdd, const std::string &path)
Find DetElement as child of the top level volume by it's absolute path.
bool DD4hep::Geometry::DetectorTools::findChild (PlacedVolume parent, PlacedVolume child, PlacementPath &path)
Find Child of PlacedVolume and assemble on the fly the path of PlacedVolumes.
static void DD4hep::Geometry::DetectorTools::makePlacementPath (PlacementPath det_nodes, PlacementPath &all_nodes)
static bool findChildByName (PlacedVolume parent, PlacedVolume child, DetectorTools::PlacementPath &path)
Find Child of PlacedVolume and assemble on the fly the path of PlacedVolumes.
Define Documentation
#define DETECTORTOOLS_CPP
Definition at line 16 of file DetectorTools.cpp.
Function Documentation
static bool findChildByName (PlacedVolume parent, PlacedVolume child, DetectorTools::PlacementPath & path) [static]
Find Child of PlacedVolume and assemble on the fly the path of PlacedVolumes.
Definition at line 108 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Geometry::DetectorTools::makePlacementPath().