DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/Display.cpp File Reference
Display.cpp File Reference
#include "DDEve/View.h"
#include "DDEve/Display.h"
#include "DDEve/ViewMenu.h"
#include "DDEve/DD4hepMenu.h"
#include "DDEve/ElementList.h"
#include "DDEve/GenericEventHandler.h"
#include "DDEve/EveShapeContextMenu.h"
#include "DDEve/EvePgonSetProjectedContextMenu.h"
#include "DDEve/Utilities.h"
#include "DDEve/DDEveEventData.h"
#include "DDEve/HitActors.h"
#include "DDEve/ParticleActors.h"
#include "DD4hep/LCDD.h"
#include "DD4hep/LCDDData.h"
#include "DD4hep/Printout.h"
#include "TH2.h"
#include "TFile.h"
#include "TSystem.h"
#include "TGTab.h"
#include "TGMsgBox.h"
#include "TGClient.h"
#include "TGFileDialog.h"
#include "TEveScene.h"
#include "TEveBrowser.h"
#include "TEveManager.h"
#include "TEveCaloData.h"
#include "TEveCalo.h"
#include "TEveViewer.h"
#include "TEveCompound.h"
#include "TEveBoxSet.h"
#include "TEvePointSet.h"
#include "TEveTrackPropagator.h"
#include "TGeoManager.h"
#include <stdexcept>
#include <climits>
Functions
ClassImp (Display) namespace DD4hep
Function Documentation
ClassImp()
ClassImp (Display)
Definition at line 62 of file Display.cpp.
References DD4hep::Display::ChooseGeometry(), DD4hep::EveDisplay(), DD4hep::Display::eventHandler(), DD4hep::Display::getEventHandlerName(), DD4hep::INFO, DD4hep::Display::LoadXML(), DD4hep::Display::MessageBox(), and DD4hep::GenericEventHandler::Open().