DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/DisplayConfigurationParser.cpp File Reference
DisplayConfigurationParser.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/LCDDLoad.h"
#include "DD4hep/Printout.h"
#include "XML/Conversions.h"
#include "XML/XMLElements.h"
#include "XML/DocumentHandler.h"
#include "DD4hep/DetFactoryHelper.h"
#include "DDEve/Display.h"
#include "DDEve/DisplayConfiguration.h"
#include <stdexcept>
#include "TEveProjections.h"
Namespaces
DD4hep
Namespace for the AIDA detector description toolkit.
Macros
#define DECL_TAG(x) XML::Strng_t u_##x(#x)
#define add_root_enum(x) XML::_toDictionary(XML::Strng_t(#x),int(x))
Typedefs
typedef DisplayConfiguration::Configurations DD4hep::Configurations
typedef DisplayConfiguration::ViewConfigurations DD4hep::ViewConfigurations
Functions
static void extract (DisplayConfiguration::Config &c, xml_h e, int typ)
static long setup_DDEve (lcdd_t &lcdd, const xml_h &e)
Macro Definition Documentation
add_root_enum
#define add_root_enum (x) XML::_toDictionary(XML::Strng_t(#x),int(x))
Referenced by setup_DDEve().
DECL_TAG
#define DECL_TAG (x) XML::Strng_t u_##x(#x)
Definition at line 64 of file DisplayConfigurationParser.cpp.
Function Documentation
extract()
static void extract (DisplayConfiguration::Config & c, xml_h e, int typ) static
Definition at line 84 of file DisplayConfigurationParser.cpp.
References _U, _Unicode, DD4hep::DisplayConfiguration::Defaults::alpha, DD4hep::XML::Handle_t::attr(), DD4hep::DisplayConfiguration::Config::Values::calo3d, DD4hep::DisplayConfiguration::Config::Values::calodata, DD4hep::DisplayConfiguration::calodata, DD4hep::DisplayConfiguration::collections, DD4hep::DisplayConfiguration::Defaults::color, DD4hep::DisplayConfiguration::Config::data, DD4hep::DisplayConfiguration::Config::Values::defaults, DD4hep::DisplayConfiguration::Calo3D::dz, DD4hep::DisplayConfiguration::Calodata::dz, e, DD4hep::DisplayConfiguration::Calo3D::emax, DD4hep::DisplayConfiguration::Calodata::emax, DD4hep::DisplayConfiguration::Hits::emax, DD4hep::DisplayConfiguration::Calodata::eta_max, DD4hep::DisplayConfiguration::Calodata::eta_min, DD4hep::XML::Collection_t::for_each(), DD4hep::XML::Handle_t::hasAttr(), DD4hep::DisplayConfiguration::Config::Values::hits, DD4hep::DisplayConfiguration::Config::hits, DD4hep::Display::ImportConfiguration(), DD4hep::INFO, load(), DD4hep::DisplayConfiguration::Defaults::load_geo, DD4hep::DisplayConfiguration::Calodata::n_eta, DD4hep::DisplayConfiguration::Calodata::n_phi, DD4hep::DisplayConfiguration::Config::name, DD4hep::DisplayConfiguration::Calodata::phi_max, DD4hep::DisplayConfiguration::Calodata::phi_min, DD4hep::printout(), DD4hep::LCDDLoad::processXML(), DD4hep::DisplayConfiguration::Calo3D::rmin, DD4hep::DisplayConfiguration::Calodata::rmin, DD4hep::Display::setEventHandlerName(), DD4hep::Display::setLoadLevel(), DD4hep::Display::setVisLevel(), DD4hep::DisplayConfiguration::Defaults::show_evt, DD4hep::DisplayConfiguration::ViewConfig::show_sensitive, DD4hep::DisplayConfiguration::ViewConfig::show_structure, DD4hep::DisplayConfiguration::Hits::size, DD4hep::DisplayConfiguration::ViewConfig::subdetectors, DD4hep::DisplayConfiguration::Calo3D::threshold, DD4hep::DisplayConfiguration::Calodata::threshold, DD4hep::DisplayConfiguration::Hits::threshold, DD4hep::DisplayConfiguration::Calo3D::towerH, DD4hep::DisplayConfiguration::Calodata::towerH, DD4hep::DisplayConfiguration::Hits::towerH, DD4hep::DisplayConfiguration::Hits::type, DD4hep::DisplayConfiguration::Config::type, DD4hep::DisplayConfiguration::ViewConfig::type, DD4hep::DisplayConfiguration::Config::use, DD4hep::DisplayConfiguration::views, and DD4hep::DisplayConfiguration::Hits::width.
setup_DDEve()
static long setup_DDEve (lcdd_t & lcdd, const xml_h & e) static
Basic entry point to read display configuration files
Author
M.Frank
Version
1.0
Date
01/06/2014
Definition at line 301 of file DisplayConfigurationParser.cpp.
References add_root_enum, DECLARE_XML_DOC_READER, e, and DD4hep::Geometry::LCDD::extension().