DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4ROOTDump.cpp File Reference
Geant4ROOTDump.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Factories.h"
#include "DD4hep/Primitives.h"
#include "DDG4/Geant4DataDump.h"
#include "DDG4/Geant4Particle.h"
#include "TInterpreter.h"
#include "TSystem.h"
#include "TFile.h"
#include "TTree.h"
#include "TROOT.h"
Typedefs
typedef Geant4DataDump::Particles Particles
typedef Geant4DataDump::TrackerHits TrackerHits
typedef Geant4DataDump::CalorimeterHits CalorimeterHits
Functions
static long usage ()
static pair< TClass *, void * > load (TBranch *branch, int entry)
static long dump_root (DD4hep::Geometry::LCDD &, int argc, char **argv)
Typedef Documentation
CalorimeterHits
typedef Geant4DataDump::CalorimeterHits CalorimeterHits
Definition at line 35 of file Geant4ROOTDump.cpp.
Particles
typedef Geant4DataDump::Particles Particles
Definition at line 33 of file Geant4ROOTDump.cpp.
TrackerHits
typedef Geant4DataDump::TrackerHits TrackerHits
Definition at line 34 of file Geant4ROOTDump.cpp.
Function Documentation
dump_root()
static long dump_root (DD4hep::Geometry::LCDD & , int argc, char ** argv) static
Definition at line 66 of file Geant4ROOTDump.cpp.
References DECLARE_APPLY, DD4hep::FATAL, DD4hep::INFO, load(), DD4hep::Simulation::Geant4DataDump::print(), DD4hep::printout(), and usage().
load()
static pair<TClass*,void*> load (TBranch * branch, int entry) static
Definition at line 50 of file Geant4ROOTDump.cpp.
Referenced by dump_root(), extract(), DD4hep::XML::DocumentHandler::load(), DD4hep::XML::DocumentHandler::output(), DD4hep::LCDDLoad::processXML(), DD4hep::XML::DocumentHandler::system_path(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
usage()
static long usage () static
Definition at line 37 of file Geant4ROOTDump.cpp.
References DD4hep::FATAL, and DD4hep::printout().
Referenced by dump_root().