DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4FieldTrackingSetup.cpp File Reference
Geant4FieldTrackingSetup.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DDG4/Geant4ActionPhase.h"
#include "DDG4/Geant4DetectorConstruction.h"
#include "DD4hep/Handle.h"
#include "DD4hep/Fields.h"
#include "DDG4/Factories.h"
#include "DDG4/Geant4Field.h"
#include "DDG4/Geant4Converter.h"
#include "G4TransportationManager.hh"
#include "G4MagIntegratorStepper.hh"
#include "G4Mag_EqRhs.hh"
#include "G4ChordFinder.hh"
#include "G4PropagatorInField.hh"
#include <limits>
Classes
struct DD4hep::Simulation::Geant4FieldTrackingSetup
Generic Setup component to perform the magnetic field tracking in Geant4.
class DD4hep::Simulation::Geant4FieldTrackingSetupAction
Phase action to perform the setup of the Geant4 tracking in magnetic fields.
class DD4hep::Simulation::Geant4FieldTrackingConstruction
Detector construction action to perform the setup of the Geant4 tracking in magnetic fields.
Namespaces
DD4hep
Namespace for the AIDA detector description toolkit.
DD4hep::Simulation
Namespace for the Geant4 based simulation part of the AIDA detector description toolkit.
Macros
#define DD4HEP_DDG4_GEANT4FIELDTRACKINGSETUP_H 1
Typedefs
typedef DD4hep::Geometry::LCDD lcdd_t
Functions
static long setup_fields (lcdd_t &lcdd, const DD4hep::Geometry::GeoHandler &, const map< string, string > &vals)
Macro Definition Documentation
DD4HEP_DDG4_GEANT4FIELDTRACKINGSETUP_H
#define DD4HEP_DDG4_GEANT4FIELDTRACKINGSETUP_H 1
Definition at line 16 of file Geant4FieldTrackingSetup.cpp.
Typedef Documentation
lcdd_t
typedef DD4hep::Geometry::LCDD lcdd_t
Definition at line 160 of file Geant4FieldTrackingSetup.cpp.
Function Documentation
setup_fields()
static long setup_fields (lcdd_t & lcdd, const DD4hep::Geometry::GeoHandler & , const map< string, string > & vals) static
Definition at line 232 of file Geant4FieldTrackingSetup.cpp.
References DD4hep::_toDouble(), DD4hep::Simulation::Geant4FieldTrackingSetup::delta_chord, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_intersection, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_one_step, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_max, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_min, DD4hep::Simulation::Geant4FieldTrackingSetup::eq_typ, DD4hep::Simulation::Geant4FieldTrackingSetup::Geant4FieldTrackingSetup(), DD4hep::Simulation::Geant4FieldTrackingSetup::largest_step, DD4hep::Simulation::Geant4FieldTrackingSetup::min_chord_step, and DD4hep::Simulation::Geant4FieldTrackingSetup::stepper_typ.
Referenced by DD4hep::Simulation::Geant4FieldTrackingConstruction::operator()().