DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Converter.cpp File Reference
Geant4Converter.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Plugins.h"
#include "DD4hep/Volumes.h"
#include "DD4hep/Printout.h"
#include "DD4hep/DD4hepUnits.h"
#include "DD4hep/objects/ObjectsInterna.h"
#include "DD4hep/objects/DetectorInterna.h"
#include "DDG4/Geant4Field.h"
#include "DDG4/Geant4Converter.h"
#include "DDG4/Geant4SensitiveDetector.h"
#include "TROOT.h"
#include "TColor.h"
#include "TGeoNode.h"
#include "TGeoShape.h"
#include "TGeoCone.h"
#include "TGeoHype.h"
#include "TGeoPcon.h"
#include "TGeoEltu.h"
#include "TGeoPgon.h"
#include "TGeoSphere.h"
#include "TGeoTorus.h"
#include "TGeoTrd1.h"
#include "TGeoTrd2.h"
#include "TGeoTube.h"
#include "TGeoArb8.h"
#include "TGeoMatrix.h"
#include "TGeoBoolNode.h"
#include "TGeoParaboloid.h"
#include "TGeoCompositeShape.h"
#include "TGeoShapeAssembly.h"
#include "TGeoScaledShape.h"
#include "TGeoManager.h"
#include "TClass.h"
#include "TMath.h"
#include "G4VisAttributes.hh"
#include "G4ProductionCuts.hh"
#include "G4VUserRegionInformation.hh"
#include "G4Element.hh"
#include "G4Box.hh"
#include "G4Trd.hh"
#include "G4Tubs.hh"
#include "G4Trap.hh"
#include "G4Cons.hh"
#include "G4Hype.hh"
#include "G4Torus.hh"
#include "G4Sphere.hh"
#include "G4Polycone.hh"
#include "G4Polyhedra.hh"
#include "G4UnionSolid.hh"
#include "G4Paraboloid.hh"
#include "G4Ellipsoid.hh"
#include "G4EllipticalTube.hh"
#include "G4SubtractionSolid.hh"
#include "G4IntersectionSolid.hh"
#include "G4Region.hh"
#include "G4UserLimits.hh"
#include "G4LogicalVolume.hh"
#include "G4Material.hh"
#include "G4Isotope.hh"
#include "G4Transform3D.hh"
#include "G4ThreeVector.hh"
#include "G4PVPlacement.hh"
#include "G4ElectroMagneticField.hh"
#include "G4FieldManager.hh"
#include "G4ReflectionFactory.hh"
#include "CLHEP/Units/SystemOfUnits.h"
#include <iostream>
#include <iomanip>
#include <sstream>
#include "DDG4/Geant4AssemblyVolume.h"
#include "DD4hep/DetectorTools.h"
#include "G4RotationMatrix.hh"
#include "G4AffineTransform.hh"
#include "G4VPhysicalVolume.hh"
Functions
string printSolid (G4VSolid *sol)
template<typename O , typename C , typename F >
void handleRefs (const O *o, const C &c, F pmf)
template<typename O , typename C , typename F >
void handle (const O *o, const C &c, F pmf)
template<typename O , typename C , typename F >
void handleMap (const O *o, const C &c, F pmf)
template<typename O , typename C , typename F >
void handleRMap (const O *o, const C &c, F pmf)
Function Documentation
handle()
template<typename O , typename C , typename F > void handle (const O * o, const C & c, F pmf)
Definition at line 984 of file Geant4Converter.cpp.
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_convertSensitive(), DD4hep::Converter< T, ARG >::Converter(), DD4hep::Simulation::Geant4Converter::create(), DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), handleRMap(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::XML::Element::operator=(), DD4hep::LCDDLoad::processXML(), DD4hep::LCDDLoad::processXMLElement(), and DD4hep::PluginService::setDebug().
handleMap()
template<typename O , typename C , typename F > void handleMap (const O * o, const C & c, F pmf)
Definition at line 990 of file Geant4Converter.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::create().
handleRefs()
template<typename O , typename C , typename F > void handleRefs (const O * o, const C & c, F pmf)
Definition at line 978 of file Geant4Converter.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::create().
handleRMap()
template<typename O , typename C , typename F > void handleRMap (const O * o, const C & c, F pmf)
Definition at line 995 of file Geant4Converter.cpp.
References handle().
Referenced by DD4hep::Simulation::Geant4Converter::create().
printSolid()
string printSolid (G4VSolid * sol)
Definition at line 933 of file Geant4Converter.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::printPlacement().