DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4InputHandling.cpp File Reference
Geant4InputHandling.cpp File Reference
#include "DDG4/Geant4InputHandling.h"
#include "DDG4/Geant4Primary.h"
#include "DDG4/Geant4Context.h"
#include "DDG4/Geant4Action.h"
#include "CLHEP/Units/SystemOfUnits.h"
#include "CLHEP/Units/PhysicalConstants.h"
#include "G4ParticleDefinition.hh"
#include "G4Event.hh"
#include "G4PrimaryVertex.hh"
#include "G4PrimaryParticle.hh"
#include <stdexcept>
#include <cmath>
Macros
#define SQR(x) (x*x)
Typedefs
typedef ReferenceBitMask< int > PropertyMask
Functions
static void collectPrimaries (Geant4PrimaryMap *pm, Geant4PrimaryInteraction *interaction, Geant4Vertex *particle_origine, G4PrimaryParticle *gp)
Helper to recursively build a DDG4 interaction from an existing G4 interaction (primary vertex)
static void appendInteraction (const Geant4Action *caller, Geant4PrimaryInteraction *output, Geant4PrimaryInteraction *input)
Append input interaction to global output.
static void rebaseParticles (Geant4PrimaryInteraction::ParticleMap &particles, int &offset)
static void rebaseVertices (Geant4PrimaryInteraction::VertexMap &vertices, int part_offset)
static G4PrimaryParticle * createG4Primary (const Geant4ParticleHandle p)
static vector< pair< Geant4Particle *, G4PrimaryParticle * > > getRelevant (set< int > &visited, map< int, G4PrimaryParticle *> &prim, Geant4PrimaryInteraction::ParticleMap &pm, const Geant4ParticleHandle p)
Macro Definition Documentation
SQR
#define SQR (x) (x*x)
Referenced by DD4hep::Simulation::boostInteraction().
Typedef Documentation
PropertyMask
typedef ReferenceBitMask<int> PropertyMask
Definition at line 37 of file Geant4InputHandling.cpp.
Function Documentation
appendInteraction()
static void appendInteraction (const Geant4Action * caller, Geant4PrimaryInteraction * output, Geant4PrimaryInteraction * input) static
Append input interaction to global output.
Definition at line 169 of file Geant4InputHandling.cpp.
References DD4hep::Simulation::Geant4Action::abortRun(), DD4hep::Simulation::Geant4Particle::addRef(), DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4PrimaryInteraction::particles, and DD4hep::Simulation::Geant4PrimaryInteraction::vertices.
Referenced by DD4hep::Simulation::mergeInteractions().
collectPrimaries()
static void collectPrimaries (Geant4PrimaryMap * pm, Geant4PrimaryInteraction * interaction, Geant4Vertex * particle_origine, G4PrimaryParticle * gp) static
Helper to recursively build a DDG4 interaction from an existing G4 interaction (primary vertex)
Definition at line 86 of file Geant4InputHandling.cpp.
References DD4hep::Simulation::createPrimary(), DD4hep::Simulation::G4PARTICLE_HAS_SECONDARIES, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::Geant4Vertex::in, DD4hep::Simulation::Geant4PrimaryMap::insert(), DD4hep::Simulation::Geant4Vertex::mask, DD4hep::Simulation::Geant4PrimaryInteraction::mask, DD4hep::Simulation::Geant4Vertex::out, DD4hep::Simulation::Geant4PrimaryInteraction::particles, DD4hep::ReferenceBitMask< T >::set(), and DD4hep::Simulation::Geant4PrimaryInteraction::vertices.
Referenced by DD4hep::Simulation::createPrimary().
createG4Primary()
static G4PrimaryParticle* createG4Primary (const Geant4ParticleHandle p) static
Definition at line 339 of file Geant4InputHandling.cpp.
References DD4hep::Simulation::Geant4ParticleHandle::charge(), DD4hep::Simulation::Geant4ParticleHandle::definition(), DD4hep::Simulation::Geant4Particle::mass, DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, and DD4hep::Simulation::Geant4Particle::psz.
Referenced by getRelevant().
getRelevant()
static vector< pair<Geant4Particle*,G4PrimaryParticle*> > getRelevant (set< int > & visited, map< int, G4PrimaryParticle *> & prim, Geant4PrimaryInteraction::ParticleMap & pm, const Geant4ParticleHandle p) static
Definition at line 354 of file Geant4InputHandling.cpp.
References createG4Primary(), DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4ParticleHandle::energy(), DD4hep::Simulation::G4PARTICLE_GEN_STABLE, DD4hep::Simulation::Geant4Particle::id, DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::Simulation::Geant4Particle::mass, DD4hep::Simulation::Geant4Particle::status, and DD4hep::Simulation::Geant4Particle::time.
Referenced by DD4hep::Simulation::generatePrimaries().
rebaseParticles()
static void rebaseParticles (Geant4PrimaryInteraction::ParticleMap & particles, int & offset) static
Definition at line 189 of file Geant4InputHandling.cpp.
References DD4hep::Simulation::Geant4Particle::id, and DD4hep::Simulation::Geant4ParticleHandle::offset().
Referenced by DD4hep::Simulation::mergeInteractions().
rebaseVertices()
static void rebaseVertices (Geant4PrimaryInteraction::VertexMap & vertices, int part_offset) static
Definition at line 201 of file Geant4InputHandling.cpp.
References DD4hep::Simulation::Geant4Vertex::in, DD4hep::Simulation::Geant4Vertex::out, and v.
Referenced by DD4hep::Simulation::mergeInteractions().