DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4HierarchyDump.cpp File Reference
Geant4HierarchyDump.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Plugins.h"
#include "DD4hep/Volumes.h"
#include "DD4hep/Printout.h"
#include "DDG4/Geant4HierarchyDump.h"
#include "G4Version.hh"
#include "G4VisAttributes.hh"
#include "G4ProductionCuts.hh"
#include "G4VUserRegionInformation.hh"
#include "G4Element.hh"
#include "G4SDManager.hh"
#include "G4AssemblyVolume.hh"
#include "G4Box.hh"
#include "G4Trd.hh"
#include "G4Tubs.hh"
#include "G4Cons.hh"
#include "G4Torus.hh"
#include "G4Sphere.hh"
#include "G4Polycone.hh"
#include "G4Polyhedra.hh"
#include "G4UnionSolid.hh"
#include "G4Paraboloid.hh"
#include "G4SubtractionSolid.hh"
#include "G4IntersectionSolid.hh"
#include "G4Region.hh"
#include "G4UserLimits.hh"
#include "G4VSensitiveDetector.hh"
#include "G4LogicalVolume.hh"
#include "G4Material.hh"
#include "G4Isotope.hh"
#include "G4Transform3D.hh"
#include "G4ThreeVector.hh"
#include "G4PVPlacement.hh"
#include "G4ElectroMagneticField.hh"
#include "G4FieldManager.hh"
#include <iostream>
#include <iomanip>
#include <sstream>
Enumerations
enum {
G4DUMP_ALL = 0xFFFFFFFF, G4DUMP_LOGVOL = 1 << 0, G4DUMP_SOLID = 1 << 1, G4DUMP_SENSDET = 1 << 2,
G4DUMP_LIMITS = 1 << 3, G4DUMP_REGION = 1 << 4, G4DUMP_LAST
}
Functions
static const char * _T (const std::string &s)
Variables
static unsigned long m_flags = ~0x0UL
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
G4DUMP_ALL
G4DUMP_LOGVOL
G4DUMP_SOLID
G4DUMP_SENSDET
G4DUMP_LIMITS
G4DUMP_REGION
G4DUMP_LAST
Definition at line 73 of file Geant4HierarchyDump.cpp.
Function Documentation
_T()
static const char* _T (const std::string & s) static
Definition at line 68 of file Geant4HierarchyDump.cpp.
Referenced by DD4hep::Conditions::Operators::collectAllConditions(), DD4hep::Simulation::Geant4HierarchyDump::dump(), DD4hep::Conditions::ConditionsTextRepository::save(), and DD4hep::Conditions::ConditionsRepository::save().
Variable Documentation
m_flags
unsigned long m_flags = ~0x0UL static
Definition at line 82 of file Geant4HierarchyDump.cpp.
Referenced by DD4hep::Simulation::Geant4HierarchyDump::dump(), and DD4hep::Simulation::Geant4HitCollection::findHit().