DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/GeometryTreeDump.cpp File Reference
GeometryTreeDump.cpp File Reference
#include "DD4hep/LCDD.h"
#include "GeometryTreeDump.h"
#include "TROOT.h"
#include "TColor.h"
#include "TGeoShape.h"
#include "TGeoCone.h"
#include "TGeoParaboloid.h"
#include "TGeoPcon.h"
#include "TGeoPgon.h"
#include "TGeoSphere.h"
#include "TGeoTorus.h"
#include "TGeoTube.h"
#include "TGeoTrd1.h"
#include "TGeoTrd2.h"
#include "TGeoArb8.h"
#include "TGeoMatrix.h"
#include "TGeoBoolNode.h"
#include "TGeoCompositeShape.h"
#include "TClass.h"
#include "TGeoManager.h"
#include "TMath.h"
#include <iostream>
Functions
static void dumpStructure (PlacedVolume pv, int level)
static void dumpDetectors (DetElement parent, int level)
Variables
static string _path = ""
Function Documentation
dumpDetectors()
static void dumpDetectors (DetElement parent, int level) static
Definition at line 275 of file GeometryTreeDump.cpp.
References DD4hep::Geometry::DetElement::children(), DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), and DD4hep::Geometry::DetElement::placementPath().
Referenced by DD4hep::Geometry::GeometryTreeDump::create().
dumpStructure()
static void dumpStructure (PlacedVolume pv, int level) static
Definition at line 253 of file GeometryTreeDump.cpp.
References DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Geometry::GeometryTreeDump::create().
Variable Documentation
_path
string _path = "" static
Definition at line 252 of file GeometryTreeDump.cpp.