DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/GlobalAlignmentCache.cpp File Reference
GlobalAlignmentCache.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Printout.h"
#include "DDAlign/GlobalAlignmentCache.h"
#include "DDAlign/AlignmentOperators.h"
#include "DD4hep/objects/DetectorInterna.h"
#include "TGeoManager.h"
Typedefs
typedef AlignmentStack::StackEntry Entry
Functions
DetElement _detector (DetElement child)
Typedef Documentation
Entry
typedef AlignmentStack::StackEntry Entry
Definition at line 29 of file GlobalAlignmentCache.cpp.
Function Documentation
_detector()
DetElement _detector (DetElement child)
Definition at line 31 of file GlobalAlignmentCache.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::DetElement::parent().
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply().