DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Handle.cpp File Reference
Handle.cpp File Reference
#include "DD4hep/InstanceCount.h"
#include "DD4hep/Printout.h"
#include "DD4hep/Handle.inl"
#include "XML/Evaluator.h"
#include <iostream>
#include <iomanip>
#include <climits>
#include <cstring>
#include <cstdio>
#include "cxxabi.h"
#include "DDSegmentation/Segmentation.h"
#include "DD4hep/LCDD.h"
#include "TMap.h"
#include "TColor.h"
#include "TGeoMedium.h"
#include "TGeoMaterial.h"
#include "TGeoElement.h"
#include "TGeoMatrix.h"
#include "TGeoNode.h"
#include "TGeoBBox.h"
#include "TGeoPcon.h"
#include "TGeoPgon.h"
#include "TGeoTube.h"
#include "TGeoCone.h"
#include "TGeoArb8.h"
#include "TGeoTrd1.h"
#include "TGeoTrd2.h"
#include "TGeoParaboloid.h"
#include "TGeoSphere.h"
#include "TGeoTorus.h"
#include "TGeoBoolNode.h"
#include "TGeoVolume.h"
#include "TGeoCompositeShape.h"
#include "TGeoShapeAssembly.h"
#include "TGeoPhysicalNode.h"
#include "TGeoPatternFinder.h"
Namespaces
DD4hep
Namespace for the AIDA detector description toolkit.
Typedefs
typedef DDSegmentation::Segmentation _Segmentation
Functions
XmlTools::Evaluator & DD4hep::evaluator ()
template<typename T >
static string __to_string (T value, const char *fmt)
long DD4hep::num_object_validations ()
void DD4hep::increment_object_validations ()
void DD4hep::warning_deprecated_xml_factory (const char *name)
Function tp print warning about deprecated factory usage. Used by Plugin mechanism.
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (LCDD)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TObject)
DD4HEP_INSTANTIATE_HANDLE (TNamed)
DD4HEP_INSTANTIATE_HANDLE (TGeoElement)
DD4HEP_INSTANTIATE_HANDLE (TGeoMaterial)
DD4HEP_INSTANTIATE_HANDLE (TGeoMedium)
DD4HEP_INSTANTIATE_HANDLE (TGeoMatrix)
DD4HEP_INSTANTIATE_HANDLE (TGeoRotation)
DD4HEP_INSTANTIATE_HANDLE (TGeoTranslation)
DD4HEP_INSTANTIATE_HANDLE (TGeoIdentity)
DD4HEP_INSTANTIATE_HANDLE (TGeoCombiTrans)
DD4HEP_INSTANTIATE_HANDLE (TGeoGenTrans)
DD4HEP_INSTANTIATE_HANDLE (TGeoNode)
DD4HEP_INSTANTIATE_HANDLE (TGeoNodeMatrix)
DD4HEP_INSTANTIATE_HANDLE (TGeoNodeOffset)
DD4HEP_INSTANTIATE_HANDLE (TGeoVolume)
DD4HEP_INSTANTIATE_HANDLE (TGeoBBox)
DD4HEP_INSTANTIATE_HANDLE (TGeoCone)
DD4HEP_INSTANTIATE_HANDLE (TGeoArb8)
DD4HEP_INSTANTIATE_HANDLE (TGeoConeSeg)
DD4HEP_INSTANTIATE_HANDLE (MyConeSeg)
DD4HEP_INSTANTIATE_HANDLE (TGeoParaboloid)
DD4HEP_INSTANTIATE_HANDLE (TGeoPcon)
DD4HEP_INSTANTIATE_HANDLE (TGeoHype)
DD4HEP_INSTANTIATE_HANDLE (TGeoPgon)
DD4HEP_INSTANTIATE_HANDLE (TGeoTube)
DD4HEP_INSTANTIATE_HANDLE (TGeoEltu)
DD4HEP_INSTANTIATE_HANDLE (TGeoTubeSeg)
DD4HEP_INSTANTIATE_HANDLE (TGeoTrap)
DD4HEP_INSTANTIATE_HANDLE (TGeoTrd1)
DD4HEP_INSTANTIATE_HANDLE (TGeoTrd2)
DD4HEP_INSTANTIATE_HANDLE (TGeoSphere)
DD4HEP_INSTANTIATE_HANDLE (TGeoTorus)
DD4HEP_INSTANTIATE_HANDLE (TGeoHalfSpace)
DD4HEP_INSTANTIATE_HANDLE (TGeoShape)
DD4HEP_INSTANTIATE_HANDLE (TGeoShapeAssembly)
DD4HEP_INSTANTIATE_HANDLE (TGeoCompositeShape)
DD4HEP_INSTANTIATE_HANDLE (TGeoPhysicalNode)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoUnion)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoIntersection)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoSubtraction)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternFinder)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternX)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternY)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternZ)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternParaX)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternParaY)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternParaZ)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternTrapZ)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternCylR)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternCylPhi)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternSphR)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternSphTheta)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternSphPhi)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternHoneycomb)
Variables
static long DD4hep::s_numVerifies = 0
Typedef Documentation
_Segmentation
typedef DDSegmentation::Segmentation _Segmentation
Definition at line 258 of file Handle.cpp.
Function Documentation
__to_string()
template<typename T > static string __to_string (T value, const char * fmt) inline static
Definition at line 207 of file Handle.cpp.
Referenced by DD4hep::_ptrToString(), and DD4hep::_toString().
DD4HEP_INSTANTIATE_HANDLE() [1/36]
DD4HEP_INSTANTIATE_HANDLE (TNamed)
Referenced by DD4hep::Handle< ReadoutObject >::name().
DD4HEP_INSTANTIATE_HANDLE() [2/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoElement)
DD4HEP_INSTANTIATE_HANDLE() [3/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoMaterial)
DD4HEP_INSTANTIATE_HANDLE() [4/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoMedium)
DD4HEP_INSTANTIATE_HANDLE() [5/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoMatrix)
DD4HEP_INSTANTIATE_HANDLE() [6/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoRotation)
DD4HEP_INSTANTIATE_HANDLE() [7/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTranslation)
DD4HEP_INSTANTIATE_HANDLE() [8/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoIdentity)
DD4HEP_INSTANTIATE_HANDLE() [9/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoCombiTrans)
DD4HEP_INSTANTIATE_HANDLE() [10/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoGenTrans)
DD4HEP_INSTANTIATE_HANDLE() [11/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoNode)
DD4HEP_INSTANTIATE_HANDLE() [12/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoNodeMatrix)
DD4HEP_INSTANTIATE_HANDLE() [13/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoNodeOffset)
DD4HEP_INSTANTIATE_HANDLE() [14/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoVolume)
DD4HEP_INSTANTIATE_HANDLE() [15/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoBBox)
DD4HEP_INSTANTIATE_HANDLE() [16/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoCone)
DD4HEP_INSTANTIATE_HANDLE() [17/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoArb8)
DD4HEP_INSTANTIATE_HANDLE() [18/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoConeSeg)
DD4HEP_INSTANTIATE_HANDLE() [19/36]
DD4HEP_INSTANTIATE_HANDLE (MyConeSeg)
DD4HEP_INSTANTIATE_HANDLE() [20/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoParaboloid)
DD4HEP_INSTANTIATE_HANDLE() [21/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoPcon)
DD4HEP_INSTANTIATE_HANDLE() [22/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoHype)
DD4HEP_INSTANTIATE_HANDLE() [23/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoPgon)
DD4HEP_INSTANTIATE_HANDLE() [24/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTube)
DD4HEP_INSTANTIATE_HANDLE() [25/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoEltu)
DD4HEP_INSTANTIATE_HANDLE() [26/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTubeSeg)
DD4HEP_INSTANTIATE_HANDLE() [27/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTrap)
DD4HEP_INSTANTIATE_HANDLE() [28/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTrd1)
DD4HEP_INSTANTIATE_HANDLE() [29/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTrd2)
DD4HEP_INSTANTIATE_HANDLE() [30/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoSphere)
DD4HEP_INSTANTIATE_HANDLE() [31/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoTorus)
DD4HEP_INSTANTIATE_HANDLE() [32/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoHalfSpace)
DD4HEP_INSTANTIATE_HANDLE() [33/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoShape)
DD4HEP_INSTANTIATE_HANDLE() [34/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoShapeAssembly)
DD4HEP_INSTANTIATE_HANDLE() [35/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoCompositeShape)
DD4HEP_INSTANTIATE_HANDLE() [36/36]
DD4HEP_INSTANTIATE_HANDLE (TGeoPhysicalNode)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [1/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (LCDD)
Referenced by DD4hep::Handle< ReadoutObject >::name().
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [2/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TObject)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [3/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoUnion)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [4/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoIntersection)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [5/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoSubtraction)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [6/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternFinder)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [7/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternX)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [8/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternY)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [9/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternZ)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [10/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternParaX)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [11/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternParaY)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [12/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternParaZ)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [13/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternTrapZ)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [14/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternCylR)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [15/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternCylPhi)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [16/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternSphR)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [17/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternSphTheta)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [18/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternSphPhi)
DD4HEP_INSTANTIATE_HANDLE_UNNAMED() [19/19]
DD4HEP_INSTANTIATE_HANDLE_UNNAMED (TGeoPatternHoneycomb)