DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/lcio/LCIOEventHandler.cpp File Reference
LCIOEventHandler.cpp File Reference
#include "LCIOEventHandler.h"
#include "DD4hep/Printout.h"
#include "DD4hep/Objects.h"
#include "DD4hep/Factories.h"
#include "IO/LCReader.h"
#include "EVENT/LCCollection.h"
#include "EVENT/SimCalorimeterHit.h"
#include "EVENT/SimTrackerHit.h"
#include "EVENT/MCParticle.h"
#include "TSystem.h"
#include "TGMsgBox.h"
#include <stdexcept>
#include <climits>
Functions
const void * _fill (const SimTrackerHit *s, DDEveHit *target)
const void * _fill (const SimCalorimeterHit *s, DDEveHit *target)
static const void * _convertHitFunc (const LCObject *source, DDEveHit *target)
static const void * _convertParticleFunc (const LCObject *source, DDEveParticle *target)
static void * _create (const char *)
Function Documentation
_convertHitFunc()
static const void* _convertHitFunc (const LCObject * source, DDEveHit * target) static
Definition at line 57 of file LCIOEventHandler.cpp.
References _fill().
Referenced by DD4hep::LCIOEventHandler::collectionLoop().
_convertParticleFunc()
static const void* _convertParticleFunc (const LCObject * source, DDEveParticle * target) static
Definition at line 64 of file LCIOEventHandler.cpp.
Referenced by DD4hep::LCIOEventHandler::collectionLoop().
_create()
static void* _create (const char *) static
Definition at line 69 of file LCIOEventHandler.cpp.
References DECLARE_CONSTRUCTOR.
Referenced by ClassImp(), and DD4hep::Geometry::PolyhedraRegular::PolyhedraRegular().
_fill() [1/2]
const void* _fill (const SimTrackerHit * s, DDEveHit * target)
Definition at line 40 of file LCIOEventHandler.cpp.
References DD4hep::DDEveHit::deposit, s, DD4hep::DDEveHit::x, DD4hep::DDEveHit::y, and DD4hep::DDEveHit::z.
Referenced by _convertHitFunc().
_fill() [2/2]
const void* _fill (const SimCalorimeterHit * s, DDEveHit * target)
Definition at line 48 of file LCIOEventHandler.cpp.
References DD4hep::DDEveHit::deposit, s, DD4hep::DDEveHit::x, DD4hep::DDEveHit::y, and DD4hep::DDEveHit::z.