DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ObjectsInterna.cpp File Reference
ObjectsInterna.cpp File Reference
#include "DD4hep/Handle.inl"
#include "DD4hep/InstanceCount.h"
#include "DD4hep/Objects.h"
#include "DD4hep/objects/ObjectsInterna.h"
#include "DD4hep/objects/SegmentationsInterna.h"
Functions
DD4HEP_INSTANTIATE_HANDLE_NAMED (VisAttrObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED (HeaderObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED (ConstantObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED (RegionObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED (LimitSetObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED (ReadoutObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED (IDDescriptorObject)
Function Documentation
DD4HEP_INSTANTIATE_HANDLE_NAMED() [1/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (VisAttrObject)
Referenced by DD4hep::Geometry::ConstantObject::~ConstantObject(), DD4hep::Geometry::HeaderObject::~HeaderObject(), DD4hep::Geometry::LimitSetObject::~LimitSetObject(), DD4hep::Geometry::ReadoutObject::~ReadoutObject(), DD4hep::Geometry::RegionObject::~RegionObject(), and DD4hep::Geometry::VisAttrObject::~VisAttrObject().
DD4HEP_INSTANTIATE_HANDLE_NAMED() [2/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (HeaderObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED() [3/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (ConstantObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED() [4/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (RegionObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED() [5/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (LimitSetObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED() [6/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (ReadoutObject)
DD4HEP_INSTANTIATE_HANDLE_NAMED() [7/7]
DD4HEP_INSTANTIATE_HANDLE_NAMED (IDDescriptorObject)