DD4hep: DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/PolyhedraEndcapCalorimeter2_geo.cpp File Reference
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/PolyhedraEndcapCalorimeter2_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
#include "XML/Layering.h"
Functions
static Ref_t create_detector (LCDD &lcdd, xml_h e, SensitiveDetector sens)
Function Documentation
static Ref_t create_detector (LCDD & lcdd, xml_h e, SensitiveDetector sens) [static]
Definition at line 25 of file PolyhedraEndcapCalorimeter2_geo.cpp.
References DD4hep::Geometry::_toString(), _U, DD4hep::Geometry::DetElement::add(), DD4hep::Geometry::PlacedVolume::addPhysVolID(), DD4hep::Geometry::LCDD::air(), DD4hep::Geometry::DetElement::clone(), DD4hep::XML::Dimension::dimensions(), DD4hep::XML::DetElement::id(), DD4hep::XML::Component::isSensitive(), DD4hep::Layering::layer(), DD4hep::XML::Dimension::limitsStr(), M_PI, DD4hep::Geometry::LCDD::material(), DD4hep::XML::Component::materialStr(), DD4hep::Handle< T >::name(), DD4hep::XML::Dimension::nameStr(), DD4hep::XML::Dimension::numsides(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::reflect(), DD4hep::XML::Dimension::regionStr(), DD4hep::XML::Dimension::repeat(), DD4hep::XML::Dimension::rmax(), DD4hep::XML::Dimension::rmin(), s, DD4hep::Geometry::Volume::setAttributes(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::Geometry::Volume::setSensitiveDetector(), DD4hep::Geometry::SensitiveDetector::setType(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::XML::Dimension::thickness(), DD4hep::Layer::thickness(), DD4hep::Layering::totalThickness(), DD4hep::Geometry::LCDD::visAttributes(), DD4hep::XML::Dimension::visStr(), DD4hep::Geometry::PlacedVolume::volume(), and DD4hep::XML::Dimension::zmin().