DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/SiTrackerEndcap2_geo.cpp File Reference
SiTrackerEndcap2_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
#include <map>
Functions
static Ref_t create_detector (LCDD &lcdd, xml_h e, SensitiveDetector sens)
Function Documentation
create_detector()
static Ref_t create_detector (LCDD & lcdd, xml_h e, SensitiveDetector sens) static
Definition at line 25 of file SiTrackerEndcap2_geo.cpp.
References DD4hep::Geometry::_toString(), _U, DD4hep::Geometry::PlacedVolume::addPhysVolID(), DD4hep::Geometry::DetElement::check(), DECLARE_DEPRECATED_DETELEMENT, DECLARE_DETELEMENT, DD4hep::XML::Dimension::dz(), e, DD4hep::XML::Dimension::id(), DD4hep::XML::DetElement::id(), DD4hep::Geometry::LCDD::invisible(), DD4hep::XML::Component::isSensitive(), M_PI, DD4hep::Geometry::LCDD::material(), DD4hep::XML::Component::materialStr(), DD4hep::XML::Dimension::moduleStr(), DD4hep::Handle< T >::name(), DD4hep::XML::Dimension::nameStr(), DD4hep::XML::Dimension::nmodules(), DD4hep::XML::Dimension::phi0(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::r(), DD4hep::XML::Dimension::reflect(), DD4hep::XML::Collection_t::reset(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::Geometry::Volume::setSensitiveDetector(), DD4hep::Geometry::SensitiveDetector::setType(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::XML::Dimension::thickness(), DD4hep::XML::Dimension::trd(), DD4hep::Geometry::LCDD::vacuum(), DD4hep::Geometry::LCDD::visAttributes(), DD4hep::XML::Dimension::visStr(), DD4hep::Geometry::PlacedVolume::volume(), DD4hep::XML::Dimension::x1(), DD4hep::XML::Dimension::x2(), DD4hep::XML::Dimension::z(), and DD4hep::XML::Dimension::zstart().