DD4hep: DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/SiTrackerBarrel_geo.cpp File Reference
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/SiTrackerBarrel_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
#include "DD4hep/Printout.h"
Functions
static Ref_t create_detector (LCDD &lcdd, xml_h e, SensitiveDetector sens)
Function Documentation
static Ref_t create_detector (LCDD & lcdd, xml_h e, SensitiveDetector sens) [static]
Increase counters etc.
Definition at line 25 of file SiTrackerBarrel_geo.cpp.
References DD4hep::Geometry::_toString(), _U, DD4hep::Geometry::PlacedVolume::addPhysVolID(), DD4hep::Geometry::LCDD::air(), DD4hep::XML::Element::child(), DD4hep::XML::Dimension::dr(), DD4hep::ERROR, DD4hep::XML::Dimension::id(), DD4hep::XML::DetElement::id(), DD4hep::XML::Dimension::inner_r(), DD4hep::Geometry::LCDD::invisible(), DD4hep::XML::Component::isSensitive(), DD4hep::XML::Dimension::length(), DD4hep::XML::Dimension::limitsStr(), M_PI, DD4hep::Geometry::LCDD::material(), DD4hep::XML::Component::materialStr(), DD4hep::XML::Dimension::moduleStr(), DD4hep::Handle< T >::name(), DD4hep::XML::Dimension::nameStr(), DD4hep::XML::Dimension::nphi(), DD4hep::XML::Dimension::nz(), DD4hep::XML::Dimension::outer_r(), DD4hep::XML::Dimension::phi0(), DD4hep::XML::Dimension::phi_tilt(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::position(), DD4hep::printout(), DD4hep::XML::Dimension::rc(), DD4hep::XML::Dimension::regionStr(), DD4hep::XML::Dimension::rotation(), DD4hep::Geometry::DetElement::setAttributes(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::Geometry::SensitiveDetector::setType(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::XML::Dimension::thickness(), DD4hep::Geometry::LCDD::visAttributes(), DD4hep::XML::Dimension::visStr(), DD4hep::Geometry::PlacedVolume::volume(), DD4hep::XML::Dimension::width(), DD4hep::XML::Dimension::x(), DD4hep::XML::Dimension::y(), DD4hep::XML::Dimension::z(), DD4hep::XML::Dimension::z0(), and DD4hep::XML::Dimension::z_length().