DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDDetectors/src/SubdetectorAssembly_geo.cpp File Reference
SubdetectorAssembly_geo.cpp File Reference
#include "DD4hep/DetFactoryHelper.h"
#include "DD4hep/Printout.h"
#include "XML/Utilities.h"
Functions
static Ref_t create_element (LCDD &lcdd, xml_h e, Ref_t)
Function Documentation
create_element()
static Ref_t create_element (LCDD & lcdd, xml_h e, Ref_t) static
Definition at line 26 of file SubdetectorAssembly_geo.cpp.
References _U, DD4hep::XML::Element::child(), DD4hep::component(), DD4hep::XML::createShape(), DEBUG, DECLARE_DETELEMENT, DD4hep::Geometry::LCDD::declareMotherVolume(), DD4hep::XML::Element::hasChild(), DD4hep::XML::DetElement::id(), DD4hep::XML::Dimension::limitsStr(), DD4hep::Geometry::LCDD::material(), DD4hep::XML::Component::materialStr(), DD4hep::XML::Dimension::nameStr(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::position(), DD4hep::printout(), DD4hep::XML::Dimension::regionStr(), DD4hep::XML::Dimension::rotation(), DD4hep::XML::setDetectorTypeFlag(), DD4hep::XML::Dimension::typeStr(), DD4hep::XML::Dimension::visStr(), DD4hep::XML::Dimension::x(), DD4hep::XML::Dimension::y(), and DD4hep::XML::Dimension::z().