DD4hep: DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/View.cpp File Reference
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/View.cpp File Reference
#include "DDEve/View.h"
#include "DDEve/Display.h"
#include "DDEve/ElementList.h"
#include "DDEve/Utilities.h"
#include "DDEve/Annotation.h"
#include "DD4hep/InstanceCount.h"
#include <TEveManager.h>
#include <TEveWindow.h>
#include <TEveCalo.h>
#include <TGLViewer.h>
Functions
template<typename T >
static T::const_iterator find (const T &c, const string &s)
Function Documentation
template<typename T > static T::const_iterator find (const T & c, const string & s) [inline, static]
Definition at line 34 of file View.cpp.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin(), DD4hep::Projection::ImportElement(), DD4hep::DDSegmentation::TiledLayerSegmentation::layerDimensions(), DD4hep::Simulation::Geant4ActionPhase::remove(), and DD4hep::DDSegmentation::TiledLayerSegmentation::setLayerDimensions().