DD4hep: DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Volumes.cpp File Reference
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Volumes.cpp File Reference
#include "DD4hep/LCDD.h"
#include "DD4hep/Printout.h"
#include "DD4hep/InstanceCount.h"
#include "DD4hep/MatrixHelpers.h"
#include "DD4hep/objects/ObjectsInterna.h"
#include "TColor.h"
#include "TGeoShape.h"
#include "TGeoVolume.h"
#include "TGeoNode.h"
#include "TGeoMatrix.h"
#include "TGeoMedium.h"
#include "TGeoVoxelFinder.h"
#include "TGeoShapeAssembly.h"
#include <climits>
#include <iostream>
#include <stdexcept>
#include <sstream>
#include "TROOT.h"
Typedefs
typedef TGeoNode geo_node_t
typedef TGeoVolume geo_volume_t
typedef TGeoVolumeAssembly geo_assembly_t
Functions
template<typename T >
static T::Object * _userExtension (const T &v)
ClassImp (PlacedVolumeExtension) static TGeoVolume *_createTGeoVolume(const string &name
magic (0)
refCount (0)
volIDs ()
static PlacedVolume::Object * _data (const PlacedVolume &v)
ClassImp (VolumeExtension) VolumeExtension
Enable ROOT persistency.
Volume::Object * _data (const Volume &v, bool throw_exception=true)
Accessor to the data part of the Volume.
static PlacedVolume _addNode (TGeoVolume *par, TGeoVolume *daughter, TGeoMatrix *transform)
Variables
TGeoShape * s
Typedef Documentation
typedef TGeoVolumeAssembly geo_assembly_t
Definition at line 286 of file Volumes.cpp.
typedef TGeoNode geo_node_t
Definition at line 284 of file Volumes.cpp.
typedef TGeoVolume geo_volume_t
Definition at line 285 of file Volumes.cpp.
Function Documentation
static PlacedVolume _addNode (TGeoVolume * par, TGeoVolume * daughter, TGeoMatrix * transform) [static]
Definition at line 491 of file Volumes.cpp.
References DD4hep::Geometry::identityTransform().
Referenced by DD4hep::Geometry::Volume::placeVolume().
Volume::Object* _data (const Volume & v, bool throw_exception = true)
Accessor to the data part of the Volume.
Definition at line 465 of file Volumes.cpp.
References _userExtension().
Referenced by DD4hep::Alignments::GlobalDetectorAlignment::volumeAlignments().
static PlacedVolume::Object* _data (const PlacedVolume & v) [static]
Definition at line 364 of file Volumes.cpp.
References _userExtension().
Referenced by DD4hep::Geometry::Volume::isSensitive(), DD4hep::Geometry::Volume::limitSet(), DD4hep::Geometry::Volume::region(), DD4hep::Geometry::Volume::sensitiveDetector(), DD4hep::Geometry::Volume::setLimitSet(), DD4hep::Geometry::Volume::setRegion(), DD4hep::Geometry::Volume::setSensitiveDetector(), DD4hep::Geometry::PlacedVolume::toString(), DD4hep::Geometry::Volume::visAttributes(), and DD4hep::Geometry::PlacedVolume::volIDs().
template<typename T > static T::Object* _userExtension (const T & v) [inline, static]
Definition at line 287 of file Volumes.cpp.
Referenced by _data(), DD4hep::Geometry::Volume::data(), DD4hep::Geometry::PlacedVolume::data(), and DD4hep::Geometry::Volume::setVisAttributes().
ClassImp (VolumeExtension)
Enable ROOT persistency.
Default constructor
Definition at line 417 of file Volumes.cpp.
References INCREMENT_COUNTER.
ClassImp (PlacedVolumeExtension) const
magic (0)
Type Constraints
Referenced by volIDs().
refCount (0)
volIDs ()
Definition at line 308 of file Volumes.cpp.
References INCREMENT_COUNTER, magic(), and DD4hep::magic_word().
Variable Documentation
TGeoShape* s
Definition at line 295 of file Volumes.cpp.
Referenced by _stack(), DD4hep::Layering::absorberThicknessInLayer(), DD4hep::DDSegmentation::BitField64::addField(), TiXmlElement::Attribute(), DD4hep::DDSegmentation::BitFieldValue::BitFieldValue(), ClassImp(), DD4hep::copyObject(), create_detector(), DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::invalid_detector_element::createMsg(), DD4hep::DDRec::invalid_position::createMsg(), DD4hep::DDRec::invalid_cell_id::createMsg(), DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >::defaultValue(), DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >::defaultValue(), DD4hep::Geometry::DetectorTools::elementPath(), DD4hep::XML::LayeringCnv::fromCompact(), DD4hep::View::ImportEventElement(), DD4hep::View::ImportGeoElement(), DD4hep::DDSegmentation::BitField64::init(), DD4hep::ElementListContextMenu::install(), DD4hep::PluginFactoryBase::make_return(), DD4hep::Utilities::MakeNodesVisible(), DD4hep::DDSegmentation::BitFieldValue::operator=(), DD4hep::DDSegmentation::Segmentation::parameter(), DD4hep::Path::Path(), DD4hep::Simulation::Geant4GeometryMaps::placementPath(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Simulation::Geant4SensDetActionSequence::process(), DD4hep::Simulation::Geant4StepHandler::sdName(), DD4hep::Layering::sensitivePositionsInLayer(), DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >::setValue(), DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >::setValue(), DD4hep::Layering::singleLayerThickness(), DD4hep::DDSegmentation::MultiSegmentation::subsegmentation(), DD4hep::DDSegmentation::SegmentationParameter::toString(), DD4hep::Geometry::PlacedVolume::toString(), DD4hep::Geometry::toStringSolid(), DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >::type(), DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >::value(), and DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >::value().