DD4hep: DD4hep::SurfaceInstaller Class Reference
DD4hep::SurfaceInstaller Class Reference
DD4hep classes and objects
#include <SurfaceInstaller.h>
Public Member Functions
SurfaceInstaller (LCDD &lcdd, int argc, char **argv)
Initializing constructor.
virtual ~SurfaceInstaller ()
Default destructor.
void stopScanning ()
Set flag to stop scanning volumes and detector elements.
void invalidInstaller (const std::string &msg) const
Indicate error message and throw exception.
Volume parentVolume (DetElement component) const
Shortcut to access the parent detectorelement's volume.
const double * placementTranslation (DetElement component) const
Shortcut to access the translation vector of a given component.
void scan ()
Scan through tree of detector elements.
virtual void install (DetElement e, PlacedVolume pv)
Install volume information. Default implementation only prints!
Static Public Member Functions
template<typename T >
static long run (LCDD &lcdd, int argc, char **argv)
Executor.
Protected Types
typedef Geometry::LCDD LCDD
typedef Geometry::DetElement DetElement
typedef Geometry::Volume Volume
typedef Geometry::PlacedVolume PlacedVolume
typedef Geometry::DetectorTools::ElementPath ElementPath
typedef Geometry::DetectorTools::PlacementPath PlacementPath
typedef DDRec::VolSurfaceBase SurfaceData
typedef DDSurfaces::SurfaceType SurfaceType
typedef std::map< TGeoVolume *, SurfaceData *> Surfaces
Protected Member Functions
void scan (DetElement de)
Scan through tree of detector elements.
Protected Attributes
LCDD & m_lcdd
Reference to the LCDD instance.
DetElement m_det
Reference to the detector element of the subdetector.
Surfaces m_surfaces
Map of surface instances keyed by the logical volume.
bool m_stopScanning
Flag to inhibit useless further scans.
Detailed Description
Base class to implement surface installers for known detector patterns
The class scans the geometry of a subdetector and gives callbacks to user classes, which then should install in the proper callback routines the surface instances to the detector elements.
Author
M.Frank
Version
1.0
Definition at line 51 of file SurfaceInstaller.h.
Member Typedef Documentation
DetElement
typedef Geometry::DetElement DD4hep::SurfaceInstaller::DetElement protected
Definition at line 54 of file SurfaceInstaller.h.
ElementPath
typedef Geometry::DetectorTools::ElementPath DD4hep::SurfaceInstaller::ElementPath protected
Definition at line 57 of file SurfaceInstaller.h.
LCDD
typedef Geometry::LCDD DD4hep::SurfaceInstaller::LCDD protected
Definition at line 53 of file SurfaceInstaller.h.
PlacedVolume
typedef Geometry::PlacedVolume DD4hep::SurfaceInstaller::PlacedVolume protected
Definition at line 56 of file SurfaceInstaller.h.
PlacementPath
typedef Geometry::DetectorTools::PlacementPath DD4hep::SurfaceInstaller::PlacementPath protected
Definition at line 58 of file SurfaceInstaller.h.
SurfaceData
typedef DDRec::VolSurfaceBase DD4hep::SurfaceInstaller::SurfaceData protected
Definition at line 59 of file SurfaceInstaller.h.
Surfaces
typedef std::map<TGeoVolume*, SurfaceData* > DD4hep::SurfaceInstaller::Surfaces protected
Definition at line 62 of file SurfaceInstaller.h.
SurfaceType
typedef DDSurfaces::SurfaceType DD4hep::SurfaceInstaller::SurfaceType protected
Definition at line 60 of file SurfaceInstaller.h.
Volume
typedef Geometry::Volume DD4hep::SurfaceInstaller::Volume protected
Definition at line 55 of file SurfaceInstaller.h.
Constructor & Destructor Documentation
SurfaceInstaller()
SurfaceInstaller::SurfaceInstaller (LCDD & lcdd, int argc, char ** argv)
Initializing constructor.
Definition at line 33 of file SurfaceInstaller.cpp.
References DD4hep::Geometry::LCDD::detector(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), m_det, DD4hep::Handle< T >::name(), and DD4hep::printout().
~SurfaceInstaller()
virtual DD4hep::SurfaceInstaller::~SurfaceInstaller () inline virtual
Default destructor.
Definition at line 78 of file SurfaceInstaller.h.
Member Function Documentation
install()
void SurfaceInstaller::install (DetElement e, PlacedVolume pv) virtual
Install volume information. Default implementation only prints!
Printout volume information.
Definition at line 80 of file SurfaceInstaller.cpp.
References DD4hep::Geometry::DetectorTools::elementPath(), DD4hep::INFO, DD4hep::Geometry::Volume::isSensitive(), m_det, DD4hep::Handle< T >::name(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::printout(), DD4hep::Handle< T >::ptr(), DD4hep::Geometry::Volume::solid(), DD4hep::Geometry::Solid_type< T >::toString(), DD4hep::Geometry::PlacedVolume::volIDs(), and DD4hep::Geometry::PlacedVolume::volume().
Referenced by scan().
invalidInstaller()
void SurfaceInstaller::invalidInstaller (const std::string & msg) const
Indicate error message and throw exception.
Definition at line 53 of file SurfaceInstaller.cpp.
References DD4hep::FATAL, DD4hep::Handle< T >::isValid(), m_det, DD4hep::Handle< T >::name(), DD4hep::printout(), and DD4hep::Geometry::DetElement::type().
parentVolume()
Volume SurfaceInstaller::parentVolume (DetElement component) const
Shortcut to access the parent detectorelement's volume.
Definition at line 64 of file SurfaceInstaller.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::parent(), DD4hep::Geometry::DetElement::placement(), and DD4hep::Geometry::PlacedVolume::volume().
placementTranslation()
const double * SurfaceInstaller::placementTranslation (DetElement component) const
Shortcut to access the translation vector of a given component.
Definition at line 73 of file SurfaceInstaller.cpp.
References DD4hep::Geometry::DetElement::placement().
run()
template<typename T > long DD4hep::SurfaceInstaller::run (Geometry::LCDD & lcdd, int argc, char ** argv) inline static
Executor.
Action routine to execute the test.
Definition at line 96 of file SurfaceInstaller.h.
scan() [1/2]
void SurfaceInstaller::scan (DetElement de) protected
Scan through tree of detector elements.
Scan through tree of volume placements.
Definition at line 124 of file SurfaceInstaller.cpp.
References DD4hep::Geometry::DetElement::children(), install(), m_stopScanning, DD4hep::Geometry::DetElement::placement(), and scan().
scan() [2/2]
void SurfaceInstaller::scan ()
Scan through tree of detector elements.
Scan through tree of volume placements.
Definition at line 132 of file SurfaceInstaller.cpp.
References m_det.
Referenced by scan().
stopScanning()
void DD4hep::SurfaceInstaller::stopScanning () inline
Set flag to stop scanning volumes and detector elements.
Definition at line 80 of file SurfaceInstaller.h.
References DD4hep::component(), and e.
Member Data Documentation
m_det
DetElement DD4hep::SurfaceInstaller::m_det protected
Reference to the detector element of the subdetector.
Definition at line 66 of file SurfaceInstaller.h.
Referenced by install(), invalidInstaller(), scan(), and SurfaceInstaller().
m_lcdd
LCDD& DD4hep::SurfaceInstaller::m_lcdd protected
Reference to the LCDD instance.
Definition at line 64 of file SurfaceInstaller.h.
m_stopScanning
bool DD4hep::SurfaceInstaller::m_stopScanning protected
Flag to inhibit useless further scans.
Definition at line 70 of file SurfaceInstaller.h.
Referenced by scan().
m_surfaces
Surfaces DD4hep::SurfaceInstaller::m_surfaces protected
Map of surface instances keyed by the logical volume.
Definition at line 68 of file SurfaceInstaller.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/SurfaceInstaller.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/SurfaceInstaller.cpp