DD4hep: DD4hep::XML::DocumentErrorHandler Class Reference
DD4hep::XML::DocumentErrorHandler Class Reference
XML-DOM ERror handler class for the XercesC document parser.
Public Member Functions
DocumentErrorHandler ()
Constructor.
virtual ~DocumentErrorHandler ()
Destructor.
void resetErrors ()
Reset errors (Noop)
void warning (const SAXParseException &)
Warnings callback. Ignore them.
void error (const SAXParseException &e)
Error handler.
void fatalError (const SAXParseException &e)
Fatal error handler.
virtual bool handleError (const DOMError &domError)
Dom Error handler callback.
Detailed Description
XML-DOM ERror handler class for the XercesC document parser.
Definition at line 62 of file DocumentHandler.cpp.
Constructor & Destructor Documentation
DocumentErrorHandler()
DD4hep::XML::DocumentErrorHandler::DocumentErrorHandler () inline
Constructor.
Definition at line 65 of file DocumentHandler.cpp.
~DocumentErrorHandler()
virtual DD4hep::XML::DocumentErrorHandler::~DocumentErrorHandler () inline virtual
Destructor.
Definition at line 68 of file DocumentHandler.cpp.
References DEBUG, and DD4hep::printout().
Member Function Documentation
error()
void DD4hep::XML::DocumentErrorHandler::error (const SAXParseException & e)
Error handler.
Definition at line 111 of file DocumentHandler.cpp.
References DD4hep::Geometry::_toString(), DD4hep::ERROR, m, and DD4hep::printout().
fatalError()
void DD4hep::XML::DocumentErrorHandler::fatalError (const SAXParseException & e)
Fatal error handler.
Definition at line 125 of file DocumentHandler.cpp.
References DD4hep::Geometry::_toString(), DD4hep::FATAL, m, and DD4hep::printout().
handleError()
bool DD4hep::XML::DocumentErrorHandler::handleError (const DOMError & domError) virtual
Dom Error handler callback.
Definition at line 86 of file DocumentHandler.cpp.
References DD4hep::Geometry::_toString(), DD4hep::FATAL, and DD4hep::printout().
resetErrors()
void DD4hep::XML::DocumentErrorHandler::resetErrors () inline
Reset errors (Noop)
Definition at line 72 of file DocumentHandler.cpp.
warning()
void DD4hep::XML::DocumentErrorHandler::warning (const SAXParseException &) inline
Warnings callback. Ignore them.
Definition at line 75 of file DocumentHandler.cpp.
References e.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/DocumentHandler.cpp