DD4hep: DD4hep::XML::DocumentHandler Class Reference
DD4hep::XML::DocumentHandler Class Reference
DD4hep::XML classes and objects
Class supporting to read and parse XML documents.
#include <DocumentHandler.h>
Public Member Functions
DocumentHandler ()
Default constructor.
virtual ~DocumentHandler ()
Default destructor.
Document create (const char *tag, const char *comment=0) const
Create new XML document by parsing empty xml buffer.
virtual Document load (const std::string &fname) const
Load XML file and parse it.
virtual Document load (const std::string &fname, UriReader *reader) const
Load XML file and parse it using URI resolver to read data.
virtual Document load (Handle_t base, const XmlChar *fname) const
Load secondary XML file with relative addressing with respect to handle.
virtual Document load (Handle_t base, const XmlChar *fname, UriReader *reader) const
Load secondary XML file with relative addressing with respect to handle.
virtual Document parse (const char *doc_string, size_t length) const
Parse a standalong XML string into a document.
virtual Document parse (const char *doc_string, size_t length, const char *sys_id, UriReader *reader) const
Parse a standalong XML string into a document using URI resolver to read data.
virtual int output (Document doc, const std::string &fname) const
Write xml document to output file (stdout if file name empty)
Static Public Member Functions
static std::string system_path (Handle_t base)
System ID of a given XML entity.
static std::string system_path (Handle_t base, const XmlChar *fname)
System ID of a new XML entity in the same directory as base.
static std::string system_path (Handle_t base, const std::string &fname)
System ID of a new XML entity in the same directory as base.
static std::string system_directory (Handle_t base)
System directory of a given XML entity.
static std::string system_directory (Handle_t base, const XmlChar *fname)
System directory of a new XML entity in the same directory as base.
Detailed Description
Class supporting to read and parse XML documents.
Wrapper object around the document parser. Supports both, XercesC and TiXml.
Author
M.Frank
Version
1.0
Definition at line 41 of file DocumentHandler.h.
Constructor & Destructor Documentation
DocumentHandler()
DocumentHandler::DocumentHandler ()
Default constructor.
Default constructor of a document handler using TiXml.
Definition at line 547 of file DocumentHandler.cpp.
~DocumentHandler()
DocumentHandler::~DocumentHandler () virtual
Default destructor.
Default destructor of a document handler using TiXml.
Definition at line 550 of file DocumentHandler.cpp.
Member Function Documentation
create()
Document DocumentHandler::create (const char * tag, const char * comment = 0) const
Create new XML document by parsing empty xml buffer.
Definition at line 588 of file DocumentHandler.cpp.
References DD4hep::XML::Element::addComment(), DD4hep::Parsers::parse(), and DD4hep::XML::Document::root().
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::dump(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
load() [1/4]
Document DocumentHandler::load (const std::string & fname) const virtual
Load XML file and parse it.
Definition at line 553 of file DocumentHandler.cpp.
References load().
load() [2/4]
Document DocumentHandler::load (const std::string & fname, UriReader * reader) const virtual
Load XML file and parse it using URI resolver to read data.
Definition at line 294 of file DocumentHandler.cpp.
References DD4hep::Geometry::_toString(), DEBUG, e, DD4hep::ERROR, DD4hep::FATAL, DD4hep::XML::UriReader::load(), parser, DD4hep::XML::UriReader::parserLoaded(), and DD4hep::printout().
load() [3/4]
Document DocumentHandler::load (Handle_t base, const XmlChar * fname) const virtual
Load secondary XML file with relative addressing with respect to handle.
Definition at line 558 of file DocumentHandler.cpp.
References load().
load() [4/4]
virtual Document DD4hep::XML::DocumentHandler::load (Handle_t base, const XmlChar * fname, UriReader * reader) const virtual
Load secondary XML file with relative addressing with respect to handle.
output()
int DocumentHandler::output (Document doc, const std::string & fname) const virtual
Write xml document to output file (stdout if file name empty)
Definition at line 350 of file DocumentHandler.cpp.
References TiXmlNode::Accept(), TiXmlDocument::Accept(), DD4hep::XML::Element::document(), DD4hep::XML::dump_tree(), e, DD4hep::ERROR, TiXmlDocument::Error(), TiXmlDocument::ErrorCol(), TiXmlDocument::ErrorDesc(), TiXmlDocument::ErrorRow(), DD4hep::FATAL, DD4hep::XML::getEnviron(), DD4hep::INFO, load(), TiXmlDocument::LoadFile(), DD4hep::Parsers::parse(), TiXmlDocument::Parse(), TiXmlDocument::Print(), DD4hep::printout(), DD4hep::XML::Handle_t::ptr(), DD4hep::XML::Document::ptr(), s, TiXmlPrinter::SetStreamPrinting(), TiXmlPrinter::Str(), TiXmlNode::Value(), and DD4hep::WARNING.
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::write(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
parse() [1/2]
Document DocumentHandler::parse (const char * doc_string, size_t length) const virtual
Parse a standalong XML string into a document.
Definition at line 563 of file DocumentHandler.cpp.
References DD4hep::Parsers::parse().
parse() [2/2]
Document DocumentHandler::parse (const char * doc_string, size_t length, const char * sys_id, UriReader * reader) const virtual
Parse a standalong XML string into a document using URI resolver to read data.
Parse a standalong XML string into a document.
Definition at line 339 of file DocumentHandler.cpp.
References parser.
system_directory() [1/2]
string DocumentHandler::system_directory (Handle_t base) static
System directory of a given XML entity.
Definition at line 581 of file DocumentHandler.cpp.
system_directory() [2/2]
string DocumentHandler::system_directory (Handle_t base, const XmlChar * fname) static
System directory of a new XML entity in the same directory as base.
System directory of a given XML entity.
Definition at line 574 of file DocumentHandler.cpp.
system_path() [1/3]
string DocumentHandler::system_path (Handle_t base) static
System ID of a given XML entity.
Definition at line 239 of file DocumentHandler.cpp.
References DD4hep::Geometry::_toString(), DEBUG, DD4hep::XML::dumpTree(), e, load(), DD4hep::XML::UriReader::load(), DD4hep::Parsers::parse(), DD4hep::printout(), and DD4hep::XML::Handle_t::ptr().
system_path() [2/3]
string DocumentHandler::system_path (Handle_t base, const XmlChar * fname) static
System ID of a new XML entity in the same directory as base.
System ID of a given XML entity.
Definition at line 568 of file DocumentHandler.cpp.
References DD4hep::Geometry::_toString().
system_path() [3/3]
string DocumentHandler::system_path (Handle_t base, const std::string & fname) static
System ID of a new XML entity in the same directory as base.
System ID of a given XML entity.
Definition at line 226 of file DocumentHandler.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/DocumentHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/DocumentHandler.cpp