DD4hep: DD4hep::Simulation::Geant4InputAction Class Reference
DD4hep::Simulation::Geant4InputAction Class Reference
DD4hep::Simulation components, classes and objects
Generic input action capable of using the Geant4EventReader class.
#include <Geant4InputAction.h>
Public Types
typedef Geant4Vertex Vertex
typedef Geant4Particle Particle
typedef std::vector< Particle * > Particles
Public Types inherited from DD4hep::Simulation::Geant4GeneratorAction
typedef Geant4SharedGeneratorAction shared_type
Public Member Functions
int readParticles (int event_number, Vertex &primary_vertex, Particles &particles)
Read an event and return a LCCollectionVec of MCParticles.
std::string issue (int i) const
helper to report Geant4 exceptions
Geant4InputAction (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4InputAction ()
Default destructor.
Particles * new_particles () const
Create particle vector.
virtual void operator() (G4Event *event)
Callback to generate primary particles.
Public Member Functions inherited from DD4hep::Simulation::Geant4GeneratorAction
Geant4GeneratorAction (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4GeneratorAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
std::string m_input
Property: input file.
int m_firstEvent
Property: SYNCEVT.
int m_mask
Property; interaction mask.
double m_momScale
Property: Momentum downscaler for debugging.
Geant4EventReader * m_reader
Event reader object.
int m_currentEventNumber
current event number without initially skipped events
bool m_abort
Flag to call abortEvent in case of failure (default: true)
Protected Attributes inherited from DD4hep::Simulation::Geant4GeneratorAction
Callback m_calls
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Generic input action capable of using the Geant4EventReader class.
Concrete implementation of the Geant4 generator action base class populating Geant4 primaries from Geant4 and HepStd files.
Author
P.Kostka (main author)
M.Frank (code reshuffeling into new DDG4 scheme)
Version
1.0
Definition at line 107 of file Geant4InputAction.h.
Member Typedef Documentation
Particle
typedef Geant4Particle DD4hep::Simulation::Geant4InputAction::Particle
Definition at line 111 of file Geant4InputAction.h.
Particles
typedef std::vector<Particle*> DD4hep::Simulation::Geant4InputAction::Particles
Definition at line 112 of file Geant4InputAction.h.
Vertex
typedef Geant4Vertex DD4hep::Simulation::Geant4InputAction::Vertex
Definition at line 110 of file Geant4InputAction.h.
Constructor & Destructor Documentation
Geant4InputAction()
Geant4InputAction::Geant4InputAction (Geant4Context * context, const std::string & name)
Standard constructor.
Definition at line 80 of file Geant4InputAction.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), m_abort, m_firstEvent, m_input, m_mask, m_momScale, and DD4hep::Simulation::Geant4Action::m_needsControl.
~Geant4InputAction()
Geant4InputAction::~Geant4InputAction () virtual
Default destructor.
Definition at line 92 of file Geant4InputAction.cpp.
Member Function Documentation
issue()
string Geant4InputAction::issue (int i) const
helper to report Geant4 exceptions
Definition at line 96 of file Geant4InputAction.cpp.
References DD4hep::Simulation::Geant4Action::name().
Referenced by readParticles().
new_particles()
Particles* DD4hep::Simulation::Geant4InputAction::new_particles () const inline
Create particle vector.
Definition at line 140 of file Geant4InputAction.h.
operator()()
void Geant4InputAction::operator() (G4Event * event) virtual
Callback to generate primary particles.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 158 of file Geant4InputAction.cpp.
References DD4hep::Simulation::Geant4PrimaryEvent::add(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4ParticleHandle::dumpWithMomentumAndVertex(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4Vertex::in, DD4hep::ReferenceBitMask< T >::isSet(), m_currentEventNumber, m_firstEvent, m_mask, m_momScale, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4Vertex::out, DD4hep::Simulation::Geant4Action::outputLevel(), DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4PrimaryInteraction::particles, DD4hep::Simulation::Geant4Action::print(), DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, readParticles(), DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::HepMC::vertex(), and DD4hep::Simulation::Geant4PrimaryInteraction::vertices.
readParticles()
int Geant4InputAction::readParticles (int event_number, Vertex & primary_vertex, Particles & particles)
Read an event and return a LCCollectionVec of MCParticles.
Read an event and return a LCCollection of MCParticles.
Definition at line 103 of file Geant4InputAction.cpp.
References DD4hep::Simulation::Geant4Action::abortRun(), e, DD4hep::Simulation::Geant4Action::error(), DD4hep::Simulation::Geant4EventReader::EVENT_READER_NO_FACTORY, DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::Simulation::Geant4Action::except(), issue(), m_abort, m_firstEvent, m_input, m_reader, DD4hep::Simulation::Geant4EventReader::moveToEvent(), DD4hep::Simulation::Geant4EventReader::readParticles(), and DD4hep::Simulation::TypeName::split().
Referenced by operator()().
Member Data Documentation
m_abort
bool DD4hep::Simulation::Geant4InputAction::m_abort protected
Flag to call abortEvent in case of failure (default: true)
Definition at line 127 of file Geant4InputAction.h.
Referenced by Geant4InputAction(), and readParticles().
m_currentEventNumber
int DD4hep::Simulation::Geant4InputAction::m_currentEventNumber protected
current event number without initially skipped events
Definition at line 125 of file Geant4InputAction.h.
Referenced by operator()().
m_firstEvent
int DD4hep::Simulation::Geant4InputAction::m_firstEvent protected
Property: SYNCEVT.
Definition at line 117 of file Geant4InputAction.h.
Referenced by Geant4InputAction(), operator()(), and readParticles().
m_input
std::string DD4hep::Simulation::Geant4InputAction::m_input protected
Property: input file.
Definition at line 115 of file Geant4InputAction.h.
Referenced by Geant4InputAction(), and readParticles().
m_mask
int DD4hep::Simulation::Geant4InputAction::m_mask protected
Property; interaction mask.
Definition at line 119 of file Geant4InputAction.h.
Referenced by Geant4InputAction(), and operator()().
m_momScale
double DD4hep::Simulation::Geant4InputAction::m_momScale protected
Property: Momentum downscaler for debugging.
Definition at line 121 of file Geant4InputAction.h.
Referenced by Geant4InputAction(), and operator()().
m_reader
Geant4EventReader* DD4hep::Simulation::Geant4InputAction::m_reader protected
Event reader object.
Definition at line 123 of file Geant4InputAction.h.
Referenced by readParticles().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4InputAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4InputAction.cpp