DD4hep: DD4hep: DD4hep::Geometry::CartesianGridXY Class Reference
DD4hep::Geometry::CartesianGridXY Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid XY segmentation.
#include <CartesianGridXY.h>
Public Types
typedef
CartesianGridXYHandle::Implementation Object
Defintiion of the basic handled object.
Public Member Functions
CartesianGridXY ()
Default constructor.
CartesianGridXY (const CartesianGridXY &e)
Copy constructor.
CartesianGridXY (const Segmentation &e)
Copy Constructor from segmentation base object.
CartesianGridXY (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
CartesianGridXY (const Handle< Q > &e)
Copy constructor from other equivalent handle.
CartesianGridXY & operator= (const CartesianGridXY &seg)
Assignment operator.
bool operator== (const CartesianGridXY &seg) const
Equality operator.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
double gridSizeX () const
access the grid size in X
double gridSizeY () const
access the grid size in Y
void setGridSizeX (double cellSize) const
set the grid size in X
void setGridSizeY (double cellSize) const
set the grid size in Y
double offsetX () const
access the coordinate offset in X
double offsetY () const
access the coordinate offset in Y
void setOffsetX (double offset) const
set the coordinate offset in X
void setOffsetY (double offset) const
set the coordinate offset in Y
const std::string & fieldNameX () const
access the field name used for X
const std::string & fieldNameY () const
access the field name used for Y
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid XY segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 58 of file CartesianGridXY.h.
Member Typedef Documentation
typedef CartesianGridXYHandle::Implementation DD4hep::Geometry::CartesianGridXY::Object
Defintiion of the basic handled object.
Definition at line 61 of file CartesianGridXY.h.
Constructor & Destructor Documentation
DD4hep::Geometry::CartesianGridXY::CartesianGridXY ()
Default constructor.
DD4hep::Geometry::CartesianGridXY::CartesianGridXY (const CartesianGridXY & e)
Copy constructor.
DD4hep::Geometry::CartesianGridXY::CartesianGridXY (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 69 of file CartesianGridXY.h.
DD4hep::Geometry::CartesianGridXY::CartesianGridXY (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 71 of file CartesianGridXY.h.
template<typename Q > DD4hep::Geometry::CartesianGridXY::CartesianGridXY (const Handle< Q > & e) [inline]
Copy constructor from other equivalent handle.
Definition at line 74 of file CartesianGridXY.h.
Member Function Documentation
vector< double > CartesianGridXY::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in x
size in y
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in x
size in y
Definition at line 96 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID CartesianGridXY::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 30 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
const string & CartesianGridXY::fieldNameX () const
access the field name used for X
Definition at line 78 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
const string & CartesianGridXY::fieldNameY () const
access the field name used for Y
Definition at line 83 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXY::gridSizeX () const
access the grid size in X
Definition at line 38 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXY::gridSizeY () const
access the grid size in Y
Definition at line 43 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXY::offsetX () const
access the coordinate offset in X
Definition at line 58 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXY::offsetY () const
access the coordinate offset in Y
Definition at line 63 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
CartesianGridXY& DD4hep::Geometry::CartesianGridXY::operator= (const CartesianGridXY & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::CartesianGridXY::operator== (const CartesianGridXY & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 78 of file CartesianGridXY.h.
References DD4hep::Handle< T >::m_element.
Position CartesianGridXY::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 25 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXY::setGridSizeX (double cellSize) const
set the grid size in X
Definition at line 48 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXY::setGridSizeY (double cellSize) const
set the grid size in Y
Definition at line 53 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXY::setOffsetX (double offset) const
set the coordinate offset in X
Definition at line 68 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXY::setOffsetY (double offset) const
set the coordinate offset in Y
Definition at line 73 of file CartesianGridXY.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/CartesianGridXY.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/CartesianGridXY.cpp