DD4hep: DD4hep::Simulation::Geant4TrackingActionSequence Class Reference
DD4hep::Simulation::Geant4TrackingActionSequence Class Reference
DD4hep::Simulation components, classes and objects
Concrete implementation of the Geant4 tracking action sequence.
#include <Geant4TrackingAction.h>
Public Member Functions
Geant4TrackingActionSequence (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4TrackingActionSequence ()
Default destructor.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
Geant4TrackingAction * get (const std::string &name) const
Get an action by name.
template<typename Q , typename T >
void callUpFront (Q *p, void(T::*f)(const G4Track *), CallbackSequence::Location where=CallbackSequence::END)
Register Pre-track action callback before anything else.
template<typename Q , typename T >
void callAtBegin (Q *p, void(T::*f)(const G4Track *), CallbackSequence::Location where=CallbackSequence::END)
Register Pre-track action callback.
template<typename Q , typename T >
void callAtEnd (Q *p, void(T::*f)(const G4Track *), CallbackSequence::Location where=CallbackSequence::END)
Register Post-track action callback.
template<typename Q , typename T >
void callAtFinal (Q *p, void(T::*f)(const G4Track *), CallbackSequence::Location where=CallbackSequence::END)
Register Post-track action callback.
void adopt (Geant4TrackingAction *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void begin (const G4Track *track)
Pre-tracking action callback.
virtual void end (const G4Track *track)
Post-tracking action callback.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
CallbackSequence m_front
Callback sequence for pre tracking action.
CallbackSequence m_begin
Callback sequence for pre tracking action.
CallbackSequence m_end
Callback sequence for post tracking action.
CallbackSequence m_final
Callback sequence for pre tracking action.
Actors< Geant4TrackingAction > m_actors
The list of action objects to be called.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Concrete implementation of the Geant4 tracking action sequence.
The sequence dispatches the callbacks for each tracking action to all registered Geant4SteppingAction members and all registered callbacks.
Note Multi-Threading issue: Neither callbacks not the action list is protected against multiple threads calling the Geant4 callbacks! These must be protected in the user actions themselves.
Author
M.Frank
Version
1.0
Definition at line 109 of file Geant4TrackingAction.h.
Constructor & Destructor Documentation
Geant4TrackingActionSequence()
Geant4TrackingActionSequence::Geant4TrackingActionSequence (Geant4Context * context, const std::string & name)
Standard constructor.
Definition at line 41 of file Geant4TrackingAction.cpp.
References DD4hep::InstanceCount::increment(), and DD4hep::Simulation::Geant4Action::m_needsControl.
~Geant4TrackingActionSequence()
Geant4TrackingActionSequence::~Geant4TrackingActionSequence () virtual
Default destructor.
Definition at line 48 of file Geant4TrackingAction.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_begin, m_end, m_final, m_front, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
adopt()
void Geant4TrackingActionSequence::adopt (Geant4TrackingAction * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 75 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by DD4hep::Converter< T, ARG >::operator()().
begin()
void Geant4TrackingActionSequence::begin (const G4Track * track) virtual
Pre-tracking action callback.
Pre-track action callback.
Definition at line 86 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4TrackingAction::begin(), m_actors, m_begin, and m_front.
callAtBegin()
template<typename Q , typename T > void DD4hep::Simulation::Geant4TrackingActionSequence::callAtBegin (Q * p, void(T::*)(const G4Track *) f, CallbackSequence::Location where = CallbackSequence::END) inline
Register Pre-track action callback.
Definition at line 140 of file Geant4TrackingAction.h.
References DD4hep::CallbackSequence::add().
Referenced by DD4hep::Simulation::Geant4MaterialScanner::Geant4MaterialScanner(), and DD4hep::Converter< T, ARG >::operator()().
callAtEnd()
template<typename Q , typename T > void DD4hep::Simulation::Geant4TrackingActionSequence::callAtEnd (Q * p, void(T::*)(const G4Track *) f, CallbackSequence::Location where = CallbackSequence::END) inline
Register Post-track action callback.
Definition at line 146 of file Geant4TrackingAction.h.
References DD4hep::CallbackSequence::add().
Referenced by DD4hep::Simulation::Geant4MaterialScanner::Geant4MaterialScanner(), and DD4hep::Converter< T, ARG >::operator()().
callAtFinal()
template<typename Q , typename T > void DD4hep::Simulation::Geant4TrackingActionSequence::callAtFinal (Q * p, void(T::*)(const G4Track *) f, CallbackSequence::Location where = CallbackSequence::END) inline
Register Post-track action callback.
Definition at line 152 of file Geant4TrackingAction.h.
References DD4hep::CallbackSequence::add(), DD4hep::Simulation::Geant4TrackingAction::begin(), and DD4hep::Simulation::Geant4TrackingAction::end().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler().
callUpFront()
template<typename Q , typename T > void DD4hep::Simulation::Geant4TrackingActionSequence::callUpFront (Q * p, void(T::*)(const G4Track *) f, CallbackSequence::Location where = CallbackSequence::END) inline
Register Pre-track action callback before anything else.
Definition at line 134 of file Geant4TrackingAction.h.
References DD4hep::CallbackSequence::add().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler().
configureFiber()
void Geant4TrackingActionSequence::configureFiber (Geant4Context * thread_context) virtual
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 65 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_actors.
end()
void Geant4TrackingActionSequence::end (const G4Track * track) virtual
Post-tracking action callback.
Post-track action callback.
Definition at line 93 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4TrackingAction::end(), m_actors, m_end, and m_final.
get()
Geant4TrackingAction * Geant4TrackingActionSequence::get (const std::string & name) const
Get an action by name.
Definition at line 70 of file Geant4TrackingAction.cpp.
References m_actors, dd4hep::second, and DD4hep::Simulation::TypeName::split().
updateContext()
void Geant4TrackingActionSequence::updateContext (Geant4Context * ctxt) virtual
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 59 of file Geant4TrackingAction.cpp.
References m_actors, and DD4hep::Simulation::Geant4Action::m_context.
Member Data Documentation
m_actors
Actors<Geant4TrackingAction> DD4hep::Simulation::Geant4TrackingActionSequence::m_actors protected
The list of action objects to be called.
Definition at line 120 of file Geant4TrackingAction.h.
Referenced by adopt(), begin(), configureFiber(), end(), get(), updateContext(), and ~Geant4TrackingActionSequence().
m_begin
CallbackSequence DD4hep::Simulation::Geant4TrackingActionSequence::m_begin protected
Callback sequence for pre tracking action.
Definition at line 114 of file Geant4TrackingAction.h.
Referenced by begin(), and ~Geant4TrackingActionSequence().
m_end
CallbackSequence DD4hep::Simulation::Geant4TrackingActionSequence::m_end protected
Callback sequence for post tracking action.
Definition at line 116 of file Geant4TrackingAction.h.
Referenced by end(), and ~Geant4TrackingActionSequence().
m_final
CallbackSequence DD4hep::Simulation::Geant4TrackingActionSequence::m_final protected
Callback sequence for pre tracking action.
Definition at line 118 of file Geant4TrackingAction.h.
Referenced by end(), and ~Geant4TrackingActionSequence().
m_front
CallbackSequence DD4hep::Simulation::Geant4TrackingActionSequence::m_front protected
Callback sequence for pre tracking action.
Definition at line 112 of file Geant4TrackingAction.h.
Referenced by begin(), and ~Geant4TrackingActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TrackingAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TrackingAction.cpp