DD4hep: DD4hep::GearHandle Class Reference
DD4hep::GearHandle Class Reference
#include <DDGear.h>
Public Member Functions
GearHandle ()
GearHandle (gear::GearParametersImpl *gearObj, const std::string &nam)
virtual ~GearHandle ()
const std::string & name ()
gear::GearParametersImpl * gearObject ()
gear::GearParametersImpl * takeGearObject ()
void addMaterial (const std::string nam, double A, double Z, double density, double radLen, double intLen)
add a SimpleMaterial object
const std::vector< gear::SimpleMaterialImpl > & materials ()
get all materials assigned to this wrapper
GearHandle (const Geometry::DetElement &)
GearHandle (const GearHandle &, const Geometry::DetElement &)
Protected Attributes
gear::GearParametersImpl * _gObj
std::string _name
std::vector< gear::SimpleMaterialImpl > _materials
Detailed Description
Simple wrapper class for objects of type GearParametersImpl that can be added to DetElements with the extension mechanism. There can only be one such object added to any given DetElement
Author
F.Gaede, DESY
Version
$Id$
Definition at line 26 of file DDGear.h.
Constructor & Destructor Documentation
GearHandle() [1/4]
DD4hep::GearHandle::GearHandle () inline
Default c'tor - only used by DD4hep extenbsion mechanism.
Definition at line 35 of file DDGear.h.
GearHandle() [2/4]
DD4hep::GearHandle::GearHandle (gear::GearParametersImpl * gearObj, const std::string & nam) inline
User c'tor - specify a name (should be the canonical name used in gear, eg. TPCParameters, SITParameters, etc.) and the GearParametersImpl object
Definition at line 39 of file DDGear.h.
~GearHandle()
virtual DD4hep::GearHandle::~GearHandle () inline virtual
D'tor deletes GearParametersImpl object if ownerhsip has not been taken away
Definition at line 42 of file DDGear.h.
GearHandle() [3/4]
DD4hep::GearHandle::GearHandle (const Geometry::DetElement &) inline
dummy implementation of required c'tors to allow using the extension mechanism
Definition at line 72 of file DDGear.h.
GearHandle() [4/4]
DD4hep::GearHandle::GearHandle (const GearHandle & , const Geometry::DetElement &) inline
Definition at line 73 of file DDGear.h.
References DD4hep::createGearMgr().
Member Function Documentation
addMaterial()
void DD4hep::GearHandle::addMaterial (const std::string nam, double A, double Z, double density, double radLen, double intLen) inline
add a SimpleMaterial object
Definition at line 62 of file DDGear.h.
Referenced by DD4hep::DDRec::createGearForCLIC(), and DD4hep::DDRec::createGearForILD().
gearObject()
gear::GearParametersImpl* DD4hep::GearHandle::gearObject () inline
Get GearParametersImpl object
Definition at line 51 of file DDGear.h.
materials()
const std::vector< gear::SimpleMaterialImpl >& DD4hep::GearHandle::materials () inline
get all materials assigned to this wrapper
Definition at line 68 of file DDGear.h.
Referenced by DD4hep::createGearMgr().
name()
const std::string& DD4hep::GearHandle::name () inline
Name of GearParametersImpl object - should be the canonical name used in gear, eg. TPCParameters, SITParameters, etc.
Definition at line 48 of file DDGear.h.
Referenced by DD4hep::createGearMgr().
takeGearObject()
gear::GearParametersImpl* DD4hep::GearHandle::takeGearObject () inline
Get GearParametersImpl object and transfer ownership
Definition at line 54 of file DDGear.h.
Referenced by DD4hep::createGearMgr().
Member Data Documentation
_gObj
gear::GearParametersImpl* DD4hep::GearHandle::_gObj protected
Definition at line 29 of file DDGear.h.
_materials
std::vector< gear::SimpleMaterialImpl > DD4hep::GearHandle::_materials protected
Definition at line 31 of file DDGear.h.
_name
std::string DD4hep::GearHandle::_name protected
Definition at line 30 of file DDGear.h.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/DDGear.h