DD4hep: DD4hep::DD4hepMenu Class Reference
DD4hep::DD4hepMenu Class Reference
DD4hep Menu for the ROOT browser.
#include <DD4hepMenu.h>
Public Member Functions
DD4hepMenu (Display *eve)
Standard constructor.
virtual ~DD4hepMenu ()
Default destructor.
virtual void Build (TGMenuBar *bar, int hints=kLHintsNormal)
Add the menu to the menu bar.
void OnLoadXML (TGMenuEntry *entry, void *ptr)
Callback when loading the configuration.
void OnLoadRootGeometry (TGMenuEntry *entry, void *ptr)
Callback when loading the configuration.
void OnCreateEventIO (TGMenuEntry *entry, void *ptr)
Callback to show the event I/O panel.
void OnOpenEventData (TGMenuEntry *entry, void *ptr)
Callback when loading a new event data file.
void OnNextEvent (TGMenuEntry *entry, void *ptr)
Callback when loading the next event.
void OnPreviousEvent (TGMenuEntry *entry, void *ptr)
Callback when loading the previous event.
void OnExit (TGMenuEntry *entry, void *ptr)
Callback when exiting the display.
void OnGeometryLoaded ()
Callback when the geometry was loaded.
ClassDef (DD4hepMenu, 0)
ROOT implementation macro.
Public Member Functions inherited from DD4hep::PopupMenu
PopupMenu (const TGWindow *parent)
Standard constructor.
virtual ~PopupMenu ()
Default destructor.
void HandleMenu (int id)
Handle menu items.
TGPopupMenu & menu ()
Access to implementation.
virtual void AddSeparator (TGMenuEntry *before=0)
Add a menu separator to the menu.
virtual void AddLabel (const char *s, const TGPicture *p=0, TGMenuEntry *before=0)
Add a menu label to the menu.
virtual void AddPopup (const char *s, TGPopupMenu *popup, TGMenuEntry *before=0, const TGPicture *p=0)
Add a (cascading) popup menu to a popup menu.
virtual int AddEntry (const char *name, Callback cb, void *ud=0, const TGPicture *p=0, TGMenuEntry *before=0)
Add a new popup menu entry with a callback.
template<typename T >
int AddEntry (const char *name, T *ptr, void(T::*pmf)(TGMenuEntry *, void *), void *ud=0, const TGPicture *p=0, TGMenuEntry *before=0)
Add a new popup menu entry with a callback.
void CheckEntry (int id)
Check menu entry.
void UnCheckEntry (int id)
Uncheck menu entry.
bool IsEntryChecked (int id)
Get check-value.
TGPopupMenu * operator-> ()
Public access to the popup menu using '->'.
operator TGPopupMenu * ()
Public access to the popup menu using '->'.
ClassDef (PopupMenu, 0)
Protected Attributes
Display * m_display
Reference to display manager.
EventControl * m_evtCtrl
Protected Attributes inherited from DD4hep::PopupMenu
Callbacks m_calls
Callback map.
TGPopupMenu m_popup
int m_cmd
Additional Inherited Members
Public Types inherited from DD4hep::PopupMenu
typedef std::map< int, Callback > Callbacks
Detailed Description
DD4hep Menu for the ROOT browser.
Definition at line 38 of file DD4hepMenu.h.
Constructor & Destructor Documentation
DD4hepMenu()
DD4hep::DD4hepMenu::DD4hepMenu (Display * eve)
Standard constructor.
~DD4hepMenu()
DD4hepMenu::~DD4hepMenu () virtual
Default destructor.
Definition at line 52 of file DD4hepMenu.cpp.
References DD4hep::deletePtr().
Member Function Documentation
Build()
void DD4hepMenu::Build (TGMenuBar * bar, int hints = kLHintsNormal) virtual
Add the menu to the menu bar.
Reimplemented from DD4hep::PopupMenu.
Definition at line 58 of file DD4hepMenu.cpp.
References DD4hep::PopupMenu::AddEntry(), m, and DD4hep::PopupMenu::menu().
ClassDef()
DD4hep::DD4hepMenu::ClassDef (DD4hepMenu , 0)
ROOT implementation macro.
OnCreateEventIO()
void DD4hepMenu::OnCreateEventIO (TGMenuEntry * entry, void * ptr)
Callback to show the event I/O panel.
Definition at line 103 of file DD4hepMenu.cpp.
OnExit()
void DD4hepMenu::OnExit (TGMenuEntry * entry, void * ptr)
Callback when exiting the display.
Definition at line 139 of file DD4hepMenu.cpp.
References DD4hep::INFO, and DD4hep::printout().
OnGeometryLoaded()
void DD4hepMenu::OnGeometryLoaded ()
Callback when the geometry was loaded.
Definition at line 76 of file DD4hepMenu.cpp.
References m.
Referenced by DD4hep::Display::LoadXML().
OnLoadRootGeometry()
void DD4hepMenu::OnLoadRootGeometry (TGMenuEntry * entry, void * ptr)
Callback when loading the configuration.
Definition at line 95 of file DD4hepMenu.cpp.
OnLoadXML()
void DD4hepMenu::OnLoadXML (TGMenuEntry * entry, void * ptr)
Callback when loading the configuration.
Definition at line 86 of file DD4hepMenu.cpp.
Referenced by DD4hep::Display::ChooseGeometry().
OnNextEvent()
void DD4hepMenu::OnNextEvent (TGMenuEntry * entry, void * ptr)
Callback when loading the next event.
Definition at line 129 of file DD4hepMenu.cpp.
OnOpenEventData()
void DD4hepMenu::OnOpenEventData (TGMenuEntry * entry, void * ptr)
Callback when loading a new event data file.
Definition at line 116 of file DD4hepMenu.cpp.
References m.
OnPreviousEvent()
void DD4hepMenu::OnPreviousEvent (TGMenuEntry * entry, void * ptr)
Callback when loading the previous event.
Definition at line 134 of file DD4hepMenu.cpp.
Member Data Documentation
m_display
Display* DD4hep::DD4hepMenu::m_display protected
Reference to display manager.
Definition at line 43 of file DD4hepMenu.h.
m_evtCtrl
EventControl* DD4hep::DD4hepMenu::m_evtCtrl protected
Definition at line 44 of file DD4hepMenu.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/DD4hepMenu.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/DD4hepMenu.cpp