DD4hep: DD4hep::Geometry::Volume Class Reference
DD4hep::Geometry::Volume Class Reference
DD4hep::Geometry components, classes and objects
Handle class holding a placed volume (also called physical volume)
#include <Volumes.h>
Public Types
typedef Handle< TGeoVolume > Base
typedef VolumeExtension Object
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Volume ()
Default constructor.
Volume (const TGeoVolume *v)
Copy from handle.
Volume (const Volume &v)
Copy from handle.
template<typename T >
Volume (const Handle< T > &v)
Copy from arbitrary Element.
Volume (const std::string &name)
Constructor to be used when creating a new geometry tree.
Volume (const std::string &name, const Solid &s, const Material &m)
Constructor to be used when creating a new geometry tree. Also sets materuial and solid attributes.
Volume & operator= (const Volume &a)
Assignment operator (must match copy constructor)
Object * data () const
Check if placement is properly instrumented.
PlacedVolume placeVolume (const Volume &vol) const
Place daughter volume. The position and rotation are the identity.
PlacedVolume placeVolume (const Volume &volume, const Transform3D &tr) const
Place daughter volume according to a generic Transform3D.
PlacedVolume placeVolume (const Volume &vol, const Position &pos) const
Place un-rotated daughter volume at the given position.
PlacedVolume placeVolume (const Volume &vol, const RotationZYX &rot) const
Place rotated daughter volume. The position is automatically the identity position.
PlacedVolume placeVolume (const Volume &vol, const Rotation3D &rot) const
Place rotated daughter volume. The position is automatically the identity position.
const Volume & setAttributes (const LCDD &lcdd, const std::string &region, const std::string &limits, const std::string &vis) const
Attach attributes to the volume.
const Volume & setRegion (const LCDD &lcdd, const std::string &name) const
Set the regional attributes to the volume. Note: If the name string is empty, the action is ignored.
const Volume & setRegion (const Region &obj) const
Set the regional attributes to the volume.
Region region () const
Access to the handle to the region structure.
const Volume & setLimitSet (const LCDD &lcdd, const std::string &name) const
Set the limits to the volume. Note: If the name string is empty, the action is ignored.
const Volume & setLimitSet (const LimitSet &obj) const
Set the limits to the volume.
LimitSet limitSet () const
Access to the limit set.
const Volume & setVisAttributes (const VisAttr &obj) const
Set Visualization attributes to the volume.
const Volume & setVisAttributes (const LCDD &lcdd, const std::string &name) const
Set Visualization attributes to the volume. Note: If the name string is empty, the action is ignored.
VisAttr visAttributes () const
Access the visualisation attributes.
const Volume & setSensitiveDetector (const SensitiveDetector &obj) const
Assign the sensitive detector structure.
Ref_t sensitiveDetector () const
Access to the handle to the sensitive detector.
bool isSensitive () const
Accessor if volume is sensitive (ie. is attached to a sensitive detector)
const Volume & setSolid (const Solid &s) const
Set the volume's solid shape.
Solid solid () const
Access to Solid (Shape)
const Volume & setMaterial (const Material &m) const
Set the volume's material.
Material material () const
Access to the Volume material.
operator TGeoVolume * () const
Auto conversion to underlying ROOT object.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class holding a placed volume (also called physical volume)
Handle describing a Volume
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoVolume.html
Author
M.Frank
Version
1.0
Definition at line 237 of file Volumes.h.
Member Typedef Documentation
Base
typedef Handle<TGeoVolume> DD4hep::Geometry::Volume::Base
Definition at line 240 of file Volumes.h.
Object
typedef VolumeExtension DD4hep::Geometry::Volume::Object
Definition at line 241 of file Volumes.h.
Constructor & Destructor Documentation
Volume() [1/6]
DD4hep::Geometry::Volume::Volume () inline
Default constructor.
Definition at line 245 of file Volumes.h.
Volume() [2/6]
DD4hep::Geometry::Volume::Volume (const TGeoVolume * v) inline
Copy from handle.
Definition at line 250 of file Volumes.h.
Volume() [3/6]
DD4hep::Geometry::Volume::Volume (const Volume & v) inline
Copy from handle.
Definition at line 255 of file Volumes.h.
Volume() [4/6]
template<typename T > DD4hep::Geometry::Volume::Volume (const Handle< T > & v) inline
Copy from arbitrary Element.
Definition at line 260 of file Volumes.h.
References m, and s.
Volume() [5/6]
Volume::Volume (const std::string & name)
Constructor to be used when creating a new geometry tree.
Definition at line 476 of file Volumes.cpp.
Volume() [6/6]
Volume::Volume (const std::string & name, const Solid & s, const Material & m)
Constructor to be used when creating a new geometry tree. Also sets materuial and solid attributes.
Definition at line 481 of file Volumes.cpp.
References DD4hep::Handle< T >::ptr().
Member Function Documentation
data()
Volume::Object * Volume::data () const
Check if placement is properly instrumented.
Definition at line 486 of file Volumes.cpp.
References _userExtension().
isSensitive()
bool Volume::isSensitive () const
Accessor if volume is sensitive (ie. is attached to a sensitive detector)
Definition at line 750 of file Volumes.cpp.
References _data().
Referenced by DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::DDRec::IDDecoder::findReadout(), and DD4hep::SurfaceInstaller::install().
limitSet()
LimitSet Volume::limitSet () const
Access to the limit set.
Definition at line 732 of file Volumes.cpp.
References _data().
Referenced by DD4hep::Simulation::Geant4Converter::collectVolume(), DD4hep::Simulation::Geant4Converter::handleVolume(), and DD4hep::Geometry::GeoHandler::i_collect().
material()
Material Volume::material () const
Access to the Volume material.
Definition at line 558 of file Volumes.cpp.
Referenced by DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), and DD4hep::Printer< T >::operator()().
operator TGeoVolume *()
DD4hep::Geometry::Volume::operator TGeoVolume * () const inline
Auto conversion to underlying ROOT object.
Definition at line 332 of file Volumes.h.
operator=()
Volume& DD4hep::Geometry::Volume::operator= (const Volume & a) inline
Assignment operator (must match copy constructor)
Definition at line 271 of file Volumes.h.
References DD4hep::Handle< T >::m_element.
placeVolume() [1/5]
PlacedVolume Volume::placeVolume (const Volume & vol) const
Place daughter volume. The position and rotation are the identity.
Definition at line 525 of file Volumes.cpp.
References _addNode(), and DD4hep::Geometry::identityTransform().
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), DD4hep::Geometry::LCDDImp::init(), and placeStaves().
placeVolume() [2/5]
PlacedVolume Volume::placeVolume (const Volume & volume, const Transform3D & tr) const
Place daughter volume according to a generic Transform3D.
Place daughter volume according to generic Transform3D.
Definition at line 520 of file Volumes.cpp.
References _addNode(), and DD4hep::Geometry::_transform().
placeVolume() [3/5]
PlacedVolume Volume::placeVolume (const Volume & vol, const Position & pos) const
Place un-rotated daughter volume at the given position.
Definition at line 530 of file Volumes.cpp.
References _addNode(), and DD4hep::Geometry::_translation().
placeVolume() [4/5]
PlacedVolume Volume::placeVolume (const Volume & vol, const RotationZYX & rot) const
Place rotated daughter volume. The position is automatically the identity position.
Definition at line 535 of file Volumes.cpp.
References _addNode(), and DD4hep::Geometry::_rotationZYX().
placeVolume() [5/5]
PlacedVolume Volume::placeVolume (const Volume & vol, const Rotation3D & rot) const
Place rotated daughter volume. The position is automatically the identity position.
Definition at line 540 of file Volumes.cpp.
References _addNode(), and DD4hep::Geometry::_rotation3D().
region()
Region Volume::region () const
Access to the handle to the region structure.
Definition at line 713 of file Volumes.cpp.
References _data().
Referenced by DD4hep::Simulation::Geant4Converter::collectVolume(), DD4hep::Simulation::Geant4Converter::handleVolume(), and DD4hep::Geometry::GeoHandler::i_collect().
sensitiveDetector()
Ref_t Volume::sensitiveDetector () const
Access to the handle to the sensitive detector.
Definition at line 744 of file Volumes.cpp.
References _data(), and DD4hep::Geometry::VolumeExtension::sens_det.
Referenced by DD4hep::Simulation::Geant4Converter::collectVolume(), DD4hep::Simulation::Geant4ConversionHelper::encoding(), DD4hep::DDRec::IDDecoder::findReadout(), and DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor().
setAttributes()
const Volume & Volume::setAttributes (const LCDD & lcdd, const std::string & region, const std::string & limits, const std::string & vis) const
Attach attributes to the volume.
Definition at line 670 of file Volumes.cpp.
References DD4hep::Geometry::LCDD::limitSet(), and DD4hep::Geometry::LCDD::region().
Referenced by create_detector().
setLimitSet() [1/2]
const Volume & Volume::setLimitSet (const LCDD & lcdd, const std::string & name) const
Set the limits to the volume. Note: If the name string is empty, the action is ignored.
Set the limits to the volume.
Definition at line 718 of file Volumes.cpp.
References DD4hep::Geometry::LCDD::limitSet().
Referenced by create_detector(), DD4hep::Geometry::GeoHandler::i_collect(), and DD4hep::Geometry::DetElement::setLimitSet().
setLimitSet() [2/2]
const Volume & Volume::setLimitSet (const LimitSet & obj) const
Set the limits to the volume.
Definition at line 726 of file Volumes.cpp.
References _data().
setMaterial()
const Volume & Volume::setMaterial (const Material & m) const
Set the volume's material.
Definition at line 545 of file Volumes.cpp.
References DD4hep::Handle< T >::_ptr(), DD4hep::Handle< T >::isValid(), and DD4hep::Handle< T >::name().
setRegion() [1/2]
const Volume & Volume::setRegion (const LCDD & lcdd, const std::string & name) const
Set the regional attributes to the volume. Note: If the name string is empty, the action is ignored.
Set the regional attributes to the volume.
Definition at line 699 of file Volumes.cpp.
References DD4hep::Geometry::LCDD::region().
Referenced by create_detector(), DD4hep::Geometry::LCDDImp::endDocument(), DD4hep::Geometry::GeoHandler::i_collect(), and DD4hep::Geometry::DetElement::setRegion().
setRegion() [2/2]
const Volume & Volume::setRegion (const Region & obj) const
Set the regional attributes to the volume.
Definition at line 707 of file Volumes.cpp.
References _data().
setSensitiveDetector()
const Volume & Volume::setSensitiveDetector (const SensitiveDetector & obj) const
Assign the sensitive detector structure.
Definition at line 737 of file Volumes.cpp.
References _data().
Referenced by create_detector().
setSolid()
const Volume & Volume::setSolid (const Solid & s) const
Set the volume's solid shape.
Definition at line 688 of file Volumes.cpp.
setVisAttributes() [1/2]
const Volume & Volume::setVisAttributes (const VisAttr & obj) const
Set Visualization attributes to the volume.
Definition at line 565 of file Volumes.cpp.
References _userExtension(), DD4hep::Geometry::VisAttrObject::alpha, DD4hep::Geometry::VisAttrObject::col, DD4hep::Geometry::VisAttrObject::color, DD4hep::Geometry::VisAttr::DASHED, DD4hep::Handle< T >::data(), DD4hep::DEBUG, DD4hep::Geometry::VisAttrObject::drawingStyle, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::VisAttrObject::lineStyle, DD4hep::printout(), DD4hep::Geometry::VisAttrObject::showDaughters, DD4hep::Geometry::VisAttr::SOLID, DD4hep::Geometry::VolumeExtension::vis, and DD4hep::Geometry::VisAttrObject::visible.
Referenced by create_detector(), DD4hep::Geometry::LCDDImp::endDocument(), and DD4hep::Geometry::DetElement::setVisAttributes().
setVisAttributes() [2/2]
const Volume & Volume::setVisAttributes (const LCDD & lcdd, const std::string & name) const
Set Visualization attributes to the volume. Note: If the name string is empty, the action is ignored.
Set Visualization attributes to the volume.
Definition at line 648 of file Volumes.cpp.
References DD4hep::Geometry::LCDD::visAttributes().
solid()
Solid Volume::solid () const
Access to Solid (Shape)
Definition at line 694 of file Volumes.cpp.
Referenced by DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::IDDecoder::getClosestDaughter(), DD4hep::DDRec::SubdetectorExtensionImpl::getNSides(), DD4hep::DDRec::SubdetectorExtensionImpl::getRMax(), DD4hep::DDRec::SubdetectorExtensionImpl::getRMin(), DD4hep::DDRec::SubdetectorExtensionImpl::getZMax(), DD4hep::DDRec::SubdetectorExtensionImpl::getZMin(), DD4hep::SurfaceInstaller::install(), and DD4hep::Printer< T >::operator()().
visAttributes()
VisAttr Volume::visAttributes () const
Access the visualisation attributes.
Definition at line 680 of file Volumes.cpp.
References _data(), and DD4hep::Geometry::VolumeExtension::vis.
Referenced by DD4hep::Geometry::GeometryTreeDump::handleVolume(), DD4hep::Geometry::SimpleGDMLWriter::handleVolume(), DD4hep::Simulation::Geant4Converter::handleVolume(), and DD4hep::Printer< T >::operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Volumes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Volumes.cpp