DD4hep: DD4hep: DD4hep::dd4hep_file_source< T > Class Template Reference
DD4hep::dd4hep_file_source< T > Class Template Reference
[DD4hep classes and objects]
DD4hep file source extension to boost::iostreams.
#include <IoStreams.h>
Classes
struct category
Public Types
typedef dd4hep_file< T > descriptor
typedef descriptor::handle_type handle_type
typedef descriptor::char_type char_type
Public Member Functions
dd4hep_file_source ()
Default Constructor.
dd4hep_file_source (const dd4hep_file_source< T > &other)
Copy constructor.
dd4hep_file_source (handle_type h, dd4hep_file_flags flags)
Constructors taking file desciptors.
dd4hep_file_source (const char *name, BOOST_IOS::openmode mode=BOOST_IOS::in)
Constructors taking file desciptors.
void open (handle_type h, dd4hep_file_flags flags)
open overload taking file desciptors
void open (const char *path, BOOST_IOS::openmode mode=BOOST_IOS::in)
open overload taking C-style string
void open (const std::string &path, BOOST_IOS::openmode mode=BOOST_IOS::in)
open overload taking a std::string
template<typename Path >
void open (const Path &path, BOOST_IOS::openmode mode=BOOST_IOS::in)
open overload taking a Boost.Filesystem path
Detailed Description
template<typename T = int>
class DD4hep::dd4hep_file_source< T >
DD4hep file source extension to boost::iostreams.
Basic data sources implementation. Please see boost::iostreams for details. This got inspired by boost::iostreams::device::file_descriptor
The final aim is to hide all this behind a TFile object, so that we get the entire network file handling for free!
Note: Credits go to a large extend to the authors of boost::iostreams. Without their work I could not have done this!
Author:
M.Frank
Version:
1.0
See also:
http://www.boost.org/libs/iostreams for further documentation.
Definition at line 127 of file IoStreams.h.
Member Typedef Documentation
template<typename T = int> typedef descriptor::char_type DD4hep::dd4hep_file_source< T >::char_type
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 134 of file IoStreams.h.
template<typename T = int> typedef dd4hep_file<T> DD4hep::dd4hep_file_source< T >::descriptor
Definition at line 129 of file IoStreams.h.
template<typename T = int> typedef descriptor::handle_type DD4hep::dd4hep_file_source< T >::handle_type
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 133 of file IoStreams.h.
Constructor & Destructor Documentation
template<typename T = int> DD4hep::dd4hep_file_source< T >::dd4hep_file_source () [inline]
Default Constructor.
Definition at line 142 of file IoStreams.h.
template<typename T = int> DD4hep::dd4hep_file_source< T >::dd4hep_file_source (const dd4hep_file_source< T > & other) [inline]
Copy constructor.
Definition at line 145 of file IoStreams.h.
template<typename T = int> DD4hep::dd4hep_file_source< T >::dd4hep_file_source (handle_type h, dd4hep_file_flags flags) [inline, explicit]
Constructors taking file desciptors.
Definition at line 149 of file IoStreams.h.
template<typename T = int> DD4hep::dd4hep_file_source< T >::dd4hep_file_source (const char * name, BOOST_IOS::openmode mode = BOOST_IOS::in) [inline, explicit]
Constructors taking file desciptors.
Definition at line 153 of file IoStreams.h.
Member Function Documentation
template<typename T = int> template<typename Path > void DD4hep::dd4hep_file_source< T >::open (const Path & path, BOOST_IOS::openmode mode = BOOST_IOS::in) [inline]
open overload taking a Boost.Filesystem path
Definition at line 169 of file IoStreams.h.
References DD4hep::dd4hep_file_source< T >::open().
Referenced by DD4hep::dd4hep_file_source< T >::open().
template<typename T = int> void DD4hep::dd4hep_file_source< T >::open (const std::string & path, BOOST_IOS::openmode mode = BOOST_IOS::in) [inline]
open overload taking a std::string
Definition at line 165 of file IoStreams.h.
References DD4hep::dd4hep_file_source< T >::open().
Referenced by DD4hep::dd4hep_file_source< T >::open().
template<typename T = int> void DD4hep::dd4hep_file_source< T >::open (const char * path, BOOST_IOS::openmode mode = BOOST_IOS::in) [inline]
open overload taking C-style string
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 161 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::open().
template<typename T = int> void DD4hep::dd4hep_file_source< T >::open (handle_type h, dd4hep_file_flags flags) [inline]
open overload taking file desciptors
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 157 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::open().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/IoStreams.h