DD4hep: DD4hep::Geometry::Segmentation Class Reference
DD4hep::Geometry::Segmentation Class Reference
DD4hep::Geometry components, classes and objects
Handle class supporting generic Segmentation of sensitive detectors.
#include <Segmentations.h>
Public Types
typedef SegmentationObject Object
typedef DDSegmentation::Segmentation BaseSegmentation
typedef DDSegmentation::Parameter Parameter
typedef DDSegmentation::Parameters Parameters
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Segmentation (const std::string &type, const std::string &name, BitField64 *decoder)
Initializing constructor creating a new object of the given DDSegmentation type.
Segmentation ()=default
Default constructor.
Segmentation (const Segmentation &e)
Copy Constructor from object.
Segmentation (const Handle< Object > &e)
Copy Constructor from handle.
template<typename Q >
Segmentation (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
Segmentation & operator= (const Segmentation &seg)=default
Assignment operator.
bool useForHitPosition () const
Access flag for hit positioning.
std::string type () const
Accessor: Segmentation type.
Parameters parameters () const
Access to the parameters.
Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
Handle< DetElementObject > detector () const
Access the main detector element using this segmetnation object.
Handle< SensitiveDetectorObject > sensitive () const
Access the sensitive detector using this segmetnation object.
BitField64 * decoder () const
Access the underlying decoder.
void setDecoder (BitField64 *decoder) const
Set the underlying decoder.
Position position (const long64 &cellID) const
determine the local position based on the cell ID
long64 cellID (const Position &localPosition, const Position &globalPosition, const long64 &volumeID) const
determine the cell ID based on the local position
VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
BaseSegmentation * segmentation () const
Access to the base DDSegmentation object. WARNING: Deprecated call!
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class supporting generic Segmentation of sensitive detectors.
Author
M.Frank
Version
1.0
Definition at line 43 of file Segmentations.h.
Member Typedef Documentation
BaseSegmentation
typedef DDSegmentation::Segmentation DD4hep::Geometry::Segmentation::BaseSegmentation
Definition at line 46 of file Segmentations.h.
Object
typedef SegmentationObject DD4hep::Geometry::Segmentation::Object
Definition at line 45 of file Segmentations.h.
Parameter
typedef DDSegmentation::Parameter DD4hep::Geometry::Segmentation::Parameter
Definition at line 47 of file Segmentations.h.
Parameters
typedef DDSegmentation::Parameters DD4hep::Geometry::Segmentation::Parameters
Definition at line 48 of file Segmentations.h.
Constructor & Destructor Documentation
Segmentation() [1/5]
Segmentation::Segmentation (const std::string & type, const std::string & name, BitField64 * decoder)
Initializing constructor creating a new object of the given DDSegmentation type.
Constructor to used when creating a new object.
Definition at line 33 of file Segmentations.cpp.
References DD4hep::Handle< T >::assign(), DD4hep::except(), and DD4hep::Geometry::SegmentationObject::setName().
Segmentation() [2/5]
DD4hep::Geometry::Segmentation::Segmentation () default
Default constructor.
Referenced by Segmentation().
Segmentation() [3/5]
DD4hep::Geometry::Segmentation::Segmentation (const Segmentation & e) inline
Copy Constructor from object.
Definition at line 56 of file Segmentations.h.
References e, and Segmentation().
Segmentation() [4/5]
DD4hep::Geometry::Segmentation::Segmentation (const Handle< Object > & e) inline
Copy Constructor from handle.
Definition at line 59 of file Segmentations.h.
Segmentation() [5/5]
template<typename Q > DD4hep::Geometry::Segmentation::Segmentation (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 63 of file Segmentations.h.
References cellDimensions(), cellID(), decoder(), detector(), neighbours(), operator=(), parameter(), parameters(), position(), segmentation(), sensitive(), setDecoder(), type(), useForHitPosition(), and volumeID().
Member Function Documentation
cellDimensions()
std::vector< double > Segmentation::cellDimensions (const CellID & cell) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Parameters
cellID cellID of the cell for which parameters are returned
Returns
vector<double> in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi
Definition at line 91 of file Segmentations.cpp.
References DD4hep::DDSegmentation::Segmentation::cellDimensions(), and segmentation().
Referenced by Segmentation().
cellID()
long64 Segmentation::cellID (const Position & localPosition, const Position & globalPosition, const long64 & volumeID) const
determine the cell ID based on the local position
Definition at line 71 of file Segmentations.cpp.
References DD4hep::DDSegmentation::Segmentation::cellID(), and segmentation().
Referenced by DD4hep::DDRec::IDDecoder::cellID(), DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::DDRec::IDDecoder::cellIDFromLocal(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), and Segmentation().
decoder()
BitField64 * Segmentation::decoder () const
Access the underlying decoder.
Definition at line 101 of file Segmentations.cpp.
References DD4hep::DDSegmentation::Segmentation::decoder(), and segmentation().
Referenced by Segmentation().
detector()
Handle< DetElementObject > Segmentation::detector () const
Access the main detector element using this segmetnation object.
Definition at line 111 of file Segmentations.cpp.
Referenced by Segmentation().
neighbours()
void Segmentation::neighbours (const CellID & cellID, std::set< CellID > & neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
Definition at line 81 of file Segmentations.cpp.
References DD4hep::DDSegmentation::Segmentation::neighbours(), and segmentation().
Referenced by DD4hep::DDRec::IDDecoder::areNeighbours(), DD4hep::DDRec::IDDecoder::neighbours(), and Segmentation().
operator=()
Segmentation& DD4hep::Geometry::Segmentation::operator= (const Segmentation & seg) default
Assignment operator.
Referenced by Segmentation().
parameter()
Segmentation::Parameter Segmentation::parameter (const std::string & parameterName) const
Access to parameter by name.
Definition at line 61 of file Segmentations.cpp.
Referenced by DD4hep::DDRec::createGearForILD(), and Segmentation().
parameters()
Segmentation::Parameters Segmentation::parameters () const
Access to the parameters.
Definition at line 56 of file Segmentations.cpp.
Referenced by Segmentation().
position()
Position Segmentation::position (const long64 & cellID) const
determine the local position based on the cell ID
Definition at line 66 of file Segmentations.cpp.
References DD4hep::DDSegmentation::Segmentation::position(), and segmentation().
Referenced by DD4hep::DDRec::IDDecoder::localPosition(), DD4hep::DDRec::IDDecoder::position(), and Segmentation().
segmentation()
Segmentation::BaseSegmentation * Segmentation::segmentation () const
Access to the base DDSegmentation object. WARNING: Deprecated call!
Definition at line 96 of file Segmentations.cpp.
Referenced by cellDimensions(), cellID(), decoder(), neighbours(), position(), Segmentation(), setDecoder(), and volumeID().
sensitive()
Handle< SensitiveDetectorObject > Segmentation::sensitive () const
Access the sensitive detector using this segmetnation object.
Definition at line 116 of file Segmentations.cpp.
Referenced by Segmentation().
setDecoder()
void Segmentation::setDecoder (BitField64 * decoder) const
Set the underlying decoder.
Definition at line 106 of file Segmentations.cpp.
References segmentation(), and DD4hep::DDSegmentation::Segmentation::setDecoder().
Referenced by Segmentation().
type()
std::string Segmentation::type () const
Accessor: Segmentation type.
Definition at line 47 of file Segmentations.cpp.
Referenced by Segmentation().
useForHitPosition()
bool Segmentation::useForHitPosition () const
Access flag for hit positioning.
Definition at line 51 of file Segmentations.cpp.
Referenced by Segmentation().
volumeID()
VolumeID Segmentation::volumeID (const CellID & cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
Definition at line 76 of file Segmentations.cpp.
References segmentation(), and DD4hep::DDSegmentation::Segmentation::volumeID().
Referenced by Segmentation(), and DD4hep::DDRec::IDDecoder::volumeID().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Segmentations.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Segmentations.cpp