DD4hep: DD4hep: DD4hep::Simulation::Geant4UserInitializationSequence Class Reference
DD4hep::Simulation::Geant4UserInitializationSequence Class Reference
[DD4hep::Simulation components, classes and objects]
Class to orchestrate a modular initializion of a multi- or single threaded Geant4 application.
#include <Geant4UserInitialization.h>
Public Member Functions
Geant4UserInitializationSequence (Geant4Context *c, const std::string &nam)
Standard constructor.
virtual ~Geant4UserInitializationSequence ()
Default destructor.
template<typename Q , typename T >
void build (Q *p, void(T::*f)())
Register callback to setup worker. Types Q and T must be polymorph!
template<typename Q , typename T >
void buildMaster (Q *p, void(T::*f)())
Register callback to setup master. Types Q and T must be polymorph!
void adopt (Geant4UserInitialization *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void updateContext (Geant4Context *ctxt)
Set client context.
virtual void build () const
Callback function to build setup for the MT worker thread.
virtual void buildMaster () const
Callback function to build setup for the MT master thread.
Protected Attributes
CallbackSequence m_masterCalls
Callback sequence to initialize the thread master.
CallbackSequence m_workerCalls
Callback sequence to initialize worker elements.
Actors< Geant4UserInitialization > m_actors
The list of action objects to be called.
Detailed Description
Class to orchestrate a modular initializion of a multi- or single threaded Geant4 application.
Author:
M.Frank
Version:
1.0
Definition at line 53 of file Geant4UserInitialization.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4UserInitializationSequence::Geant4UserInitializationSequence (Geant4Context * c, const std::string & nam)
Standard constructor.
Geant4UserInitializationSequence::~Geant4UserInitializationSequence () [virtual]
Default destructor.
Definition at line 53 of file Geant4UserInitialization.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_masterCalls, m_workerCalls, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
void Geant4UserInitializationSequence::adopt (Geant4UserInitialization * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 62 of file Geant4UserInitialization.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
void Geant4UserInitializationSequence::build () const [virtual]
Callback function to build setup for the MT worker thread.
Reimplemented from DD4hep::Simulation::Geant4UserInitialization.
Definition at line 72 of file Geant4UserInitialization.cpp.
References DD4hep::Simulation::Geant4UserInitialization::build(), m_actors, and m_workerCalls.
template<typename Q , typename T > void DD4hep::Simulation::Geant4UserInitializationSequence::build (Q * p, void(T::*)() f) [inline]
Register callback to setup worker. Types Q and T must be polymorph!
Definition at line 68 of file Geant4UserInitialization.h.
References DD4hep::CallbackSequence::add(), and m_workerCalls.
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build().
void Geant4UserInitializationSequence::buildMaster () const [virtual]
Callback function to build setup for the MT master thread.
Reimplemented from DD4hep::Simulation::Geant4UserInitialization.
Definition at line 78 of file Geant4UserInitialization.cpp.
References DD4hep::Simulation::Geant4UserInitialization::buildMaster(), m_actors, and m_masterCalls.
template<typename Q , typename T > void DD4hep::Simulation::Geant4UserInitializationSequence::buildMaster (Q * p, void(T::*)() f) [inline]
Register callback to setup master. Types Q and T must be polymorph!
Definition at line 72 of file Geant4UserInitialization.h.
References DD4hep::CallbackSequence::add(), and m_masterCalls.
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::BuildForMaster().
void Geant4UserInitializationSequence::updateContext (Geant4Context * ctxt) [virtual]
Set client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 84 of file Geant4UserInitialization.cpp.
References m_actors, and DD4hep::Simulation::Geant4Action::m_context.
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build().
Member Data Documentation
Actors<Geant4UserInitialization> DD4hep::Simulation::Geant4UserInitializationSequence::m_actors [protected]
The list of action objects to be called.
Definition at line 60 of file Geant4UserInitialization.h.
Referenced by adopt(), build(), buildMaster(), updateContext(), and ~Geant4UserInitializationSequence().
CallbackSequence DD4hep::Simulation::Geant4UserInitializationSequence::m_masterCalls [protected]
Callback sequence to initialize the thread master.
Definition at line 56 of file Geant4UserInitialization.h.
Referenced by buildMaster(), and ~Geant4UserInitializationSequence().
CallbackSequence DD4hep::Simulation::Geant4UserInitializationSequence::m_workerCalls [protected]
Callback sequence to initialize worker elements.
Definition at line 58 of file Geant4UserInitialization.h.
Referenced by build(), and ~Geant4UserInitializationSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4UserInitialization.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4UserInitialization.cpp