DD4hep: DD4hep::Simulation::Geant4UserRunAction Class Reference
DD4hep::Simulation::Geant4UserRunAction Class Reference
Concrete implementation of the Geant4 run action.
Public Member Functions
Geant4UserRunAction (Geant4Context *ctxt, Geant4RunActionSequence *seq)
Standard constructor.
virtual ~Geant4UserRunAction ()
Default destructor.
virtual void BeginOfRunAction (const G4Run *run)
Begin-of-run callback.
virtual void EndOfRunAction (const G4Run *run)
End-of-run callback.
Public Member Functions inherited from DD4hep::Simulation::SequenceHdl< Geant4RunActionSequence >
SequenceHdl ()
Default constructor.
SequenceHdl (Geant4Context *ctxt, Geant4RunActionSequence *seq)
virtual ~SequenceHdl ()
void _aquire (Geant4RunActionSequence *s)
void updateContext (Geant4Context *ctxt)
void _release ()
Geant4Context * context () const
Geant4Kernel & kernel () const
void configureFiber (Geant4Context *ctxt)
void createClientContext (const G4Run *run)
void createClientContext (const G4Event *evt)
void destroyClientContext (const G4Run *)
void destroyClientContext (const G4Event *)
Public Attributes
Geant4UserEventAction * eventAction
Public Attributes inherited from DD4hep::Simulation::SequenceHdl< Geant4RunActionSequence >
Geant4RunActionSequence * m_sequence
Geant4Context * m_activeContext
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::SequenceHdl< Geant4RunActionSequence >
typedef SequenceHdl< Geant4RunActionSequence > Base
Detailed Description
Concrete implementation of the Geant4 run action.
Author
M.Frank
Version
1.0
Definition at line 135 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
Geant4UserRunAction()
DD4hep::Simulation::Geant4UserRunAction::Geant4UserRunAction (Geant4Context * ctxt, Geant4RunActionSequence * seq) inline
Standard constructor.
Definition at line 142 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< T >::configureFiber(), and DD4hep::Simulation::SequenceHdl< T >::updateContext().
~Geant4UserRunAction()
virtual DD4hep::Simulation::Geant4UserRunAction::~Geant4UserRunAction () inline virtual
Default destructor.
Definition at line 148 of file Geant4Exec.cpp.
Member Function Documentation
BeginOfRunAction()
void DD4hep::Simulation::Geant4UserRunAction::BeginOfRunAction (const G4Run * run) virtual
Begin-of-run callback.
Definition at line 349 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< T >::createClientContext(), DD4hep::Simulation::Geant4Kernel::executePhase(), DD4hep::Simulation::SequenceHdl< T >::kernel(), and DD4hep::Simulation::SequenceHdl< T >::m_sequence.
EndOfRunAction()
void DD4hep::Simulation::Geant4UserRunAction::EndOfRunAction (const G4Run * run) virtual
End-of-run callback.
Definition at line 356 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< T >::destroyClientContext(), DD4hep::Simulation::Geant4Kernel::executePhase(), DD4hep::Simulation::SequenceHdl< T >::kernel(), and DD4hep::Simulation::SequenceHdl< T >::m_sequence.
Member Data Documentation
eventAction
Geant4UserEventAction* DD4hep::Simulation::Geant4UserRunAction::eventAction
Definition at line 140 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp