DD4hep: DD4hep: DD4hep::DDRec::VolPlaneImpl Class Reference
DD4hep::DDRec::VolPlaneImpl Class Reference
#include <Surface.h>
Public Member Functions
VolPlaneImpl ()
default c'tor
VolPlaneImpl (SurfaceType typ, double thickness_inner, double thickness_outer, Vector3D u_val, Vector3D v_val, Vector3D n_val, Vector3D o_val, Geometry::Volume vol, int id_val)
standard c'tor with all necessary arguments - origin is (0,0,0) if not given.
virtual double distance (const Vector3D &point) const
Detailed Description
Implementation of a planar surface attached to a volume
Author:
F.Gaede, DESY
Date:
Sep, 14 2014
Version:
$Id$
Definition at line 344 of file Surface.h.
Constructor & Destructor Documentation
DD4hep::DDRec::VolPlaneImpl::VolPlaneImpl () [inline]
default c'tor
Definition at line 349 of file Surface.h.
DD4hep::DDRec::VolPlaneImpl::VolPlaneImpl (SurfaceType typ, double thickness_inner, double thickness_outer, Vector3D u_val, Vector3D v_val, Vector3D n_val, Vector3D o_val, Geometry::Volume vol, int id_val) [inline]
standard c'tor with all necessary arguments - origin is (0,0,0) if not given.
Definition at line 352 of file Surface.h.
References DD4hep::DDRec::VolSurfaceBase::_type, DDSurfaces::SurfaceType::checkOrthogonalToZ(), DDSurfaces::SurfaceType::checkParallelToZ(), DDSurfaces::SurfaceType::Cone, DDSurfaces::SurfaceType::Cylinder, DDSurfaces::SurfaceType::Plane, and DDSurfaces::SurfaceType::setProperty().
Member Function Documentation
double DD4hep::DDRec::VolPlaneImpl::distance (const Vector3D & point) const [virtual]
Distance to surface
Distance to planar surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 252 of file Surface.cpp.
References DD4hep::DDRec::VolSurfaceBase::normal(), and DD4hep::DDRec::VolSurfaceBase::origin().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp