DD4hep: DD4hep: DDSurfaces::SurfaceType Class Reference
DDSurfaces::SurfaceType Class Reference
#include <ISurface.h>
Public Types
enum SurfaceTypes {
Cylinder = 0, Plane, Sensitive, Helper,
ParallelToZ, OrthogonalToZ, Invisible, Measurement1D,
Cone
}
enum for defining the bits used to decode the properties
Public Member Functions
SurfaceType ()
default c'tor
SurfaceType (unsigned prop0)
SurfaceType (unsigned prop0, unsigned prop1)
SurfaceType (unsigned prop0, unsigned prop1, unsigned prop2)
SurfaceType (unsigned prop0, unsigned prop1, unsigned prop2, unsigned prop3)
SurfaceType (unsigned prop0, unsigned prop1, unsigned prop2, unsigned prop3, unsigned prop4)
void setProperty (unsigned prop, bool val=true)
set the given peorperty
bool isSensitive () const
true if surface is sensitive
bool isHelper () const
true if surface is helper surface for navigation
bool isPlane () const
true if this a planar surface
bool isCylinder () const
true if this a cylindrical surface
bool isCone () const
true if this a conical surface
bool isParallelToZ () const
true if surface is parallel to Z
bool isOrthogonalToZ () const
true if surface is orthogonal to Z
bool isVisible () const
true if surface is not invisble - for drawing only
bool isZCylinder () const
true if this is a cylinder parallel to Z
bool isZCone () const
true if this is a cone parallel to Z
bool isZPlane () const
true if this is a plane parallel to Z
bool isZDisk () const
true if this is a plane orthogonal to Z
bool isMeasurement1D () const
true if the measurement is only 1D, i.e. the second direction v is not used
bool isSimilar (const SurfaceType &otherType) const
true if all properties of otherType are also true for this type.
bool checkParallelToZ (const ISurface &surf, double epsilon=1.e-6) const
bool checkOrthogonalToZ (const ISurface &surf, double epsilon=1.e-6) const
Protected Attributes
std::bitset< 32 > _bits
Detailed Description
Helper class for describing surface properties. Usage: SurfaceType type(SurfaceType::Plane, SurfaceType::Sensitive) ;
Author:
F. Gaede, DESY
Version:
$Id$
Date:
Apr 6 2014
Definition at line 128 of file ISurface.h.
Member Enumeration Documentation
enum DDSurfaces::SurfaceType::SurfaceTypes
enum for defining the bits used to decode the properties
Enumerator:
Cylinder
Plane
Sensitive
Helper
ParallelToZ
OrthogonalToZ
Invisible
Measurement1D
Cone
Definition at line 132 of file ISurface.h.
Constructor & Destructor Documentation
DDSurfaces::SurfaceType::SurfaceType () [inline]
default c'tor
Definition at line 145 of file ISurface.h.
DDSurfaces::SurfaceType::SurfaceType (unsigned prop0) [inline]
Definition at line 148 of file ISurface.h.
References _bits.
DDSurfaces::SurfaceType::SurfaceType (unsigned prop0, unsigned prop1) [inline]
Definition at line 153 of file ISurface.h.
References _bits.
DDSurfaces::SurfaceType::SurfaceType (unsigned prop0, unsigned prop1, unsigned prop2) [inline]
Definition at line 159 of file ISurface.h.
References _bits.
DDSurfaces::SurfaceType::SurfaceType (unsigned prop0, unsigned prop1, unsigned prop2, unsigned prop3) [inline]
Definition at line 166 of file ISurface.h.
References _bits.
DDSurfaces::SurfaceType::SurfaceType (unsigned prop0, unsigned prop1, unsigned prop2, unsigned prop3, unsigned prop4) [inline]
Definition at line 174 of file ISurface.h.
References _bits.
Member Function Documentation
bool DDSurfaces::SurfaceType::checkOrthogonalToZ (const ISurface & surf, double epsilon = 1.e-6) const [inline]
True if surface is orthogonal to Z with accuracy epsilon - result is cached in bit SurfaceType::OrthogonalToZ
Definition at line 253 of file ISurface.h.
References _bits, DDSurfaces::ISurface::normal(), and OrthogonalToZ.
Referenced by DD4hep::DDRec::Surface::initialize(), DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl(), and DD4hep::DDRec::VolPlaneImpl::VolPlaneImpl().
bool DDSurfaces::SurfaceType::checkParallelToZ (const ISurface & surf, double epsilon = 1.e-6) const [inline]
True if surface is parallel to Z with accuracy epsilon - result is cached in bit SurfaceType::ParallelToZ
Definition at line 236 of file ISurface.h.
References _bits, DDSurfaces::ISurface::normal(), and ParallelToZ.
Referenced by DD4hep::DDRec::Surface::initialize(), DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl(), and DD4hep::DDRec::VolPlaneImpl::VolPlaneImpl().
bool DDSurfaces::SurfaceType::isCone () const [inline]
true if this a conical surface
Definition at line 198 of file ISurface.h.
References _bits, and Cone.
Referenced by DD4hep::DDRec::Surface::initialize(), DD4hep::DDRec::DetectorSurfaces::initialize(), and DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isCylinder () const [inline]
true if this a cylindrical surface
Definition at line 195 of file ISurface.h.
References _bits, and Cylinder.
Referenced by DD4hep::DDRec::DetectorSurfaces::initialize(), and DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isHelper () const [inline]
true if surface is helper surface for navigation
Definition at line 189 of file ISurface.h.
References _bits, and Helper.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isMeasurement1D () const [inline]
true if the measurement is only 1D, i.e. the second direction v is not used
Definition at line 223 of file ISurface.h.
References _bits, and Measurement1D.
bool DDSurfaces::SurfaceType::isOrthogonalToZ () const [inline]
true if surface is orthogonal to Z
Definition at line 204 of file ISurface.h.
References _bits, and OrthogonalToZ.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isParallelToZ () const [inline]
true if surface is parallel to Z
Definition at line 201 of file ISurface.h.
References _bits, and ParallelToZ.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isPlane () const [inline]
true if this a planar surface
Definition at line 192 of file ISurface.h.
References _bits, and Plane.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isSensitive () const [inline]
true if surface is sensitive
Definition at line 186 of file ISurface.h.
References _bits, and Sensitive.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isSimilar (const SurfaceType & otherType) const [inline]
true if all properties of otherType are also true for this type.
Definition at line 227 of file ISurface.h.
References _bits.
bool DDSurfaces::SurfaceType::isVisible () const [inline]
true if surface is not invisble - for drawing only
Definition at line 207 of file ISurface.h.
References _bits, and Invisible.
bool DDSurfaces::SurfaceType::isZCone () const [inline]
true if this is a cone parallel to Z
Definition at line 213 of file ISurface.h.
References _bits, Cone, and ParallelToZ.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isZCylinder () const [inline]
true if this is a cylinder parallel to Z
Definition at line 210 of file ISurface.h.
References _bits, Cylinder, and ParallelToZ.
Referenced by DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isZDisk () const [inline]
true if this is a plane orthogonal to Z
Definition at line 220 of file ISurface.h.
References _bits, OrthogonalToZ, and Plane.
Referenced by DD4hep::DDRec::Surface::getLines(), and DDSurfaces::operator<<().
bool DDSurfaces::SurfaceType::isZPlane () const [inline]
true if this is a plane parallel to Z
Definition at line 216 of file ISurface.h.
References _bits, ParallelToZ, and Plane.
Referenced by DDSurfaces::operator<<().
void DDSurfaces::SurfaceType::setProperty (unsigned prop, bool val = true) [inline]
set the given peorperty
Definition at line 183 of file ISurface.h.
References _bits.
Referenced by DD4hep::DDRec::VolConeImpl::VolConeImpl(), DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl(), and DD4hep::DDRec::VolPlaneImpl::VolPlaneImpl().
Member Data Documentation
std::bitset<32> DDSurfaces::SurfaceType::_bits [mutable, protected]
Definition at line 273 of file ISurface.h.
Referenced by checkOrthogonalToZ(), checkParallelToZ(), isCone(), isCylinder(), isHelper(), isMeasurement1D(), isOrthogonalToZ(), isParallelToZ(), isPlane(), isSensitive(), isSimilar(), isVisible(), isZCone(), isZCylinder(), isZDisk(), isZPlane(), setProperty(), and SurfaceType().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSurfaces/include/DDSurfaces/ISurface.h