DD4hep: DD4hep::Conditions::UserPool Class Reference
DD4hep::Conditions::UserPool Class Reference abstract
Interface for conditions pool optimized to host conditions updates.
#include <ConditionsPool.h>
Public Types
typedef Condition::key_type key_type
Forward definition of the key type.
typedef ConditionsManager::ConditionKeys ConditionKeys
Forward definition of the condition keys container.
typedef ConditionsManager::Dependencies Dependencies
Forward definition of the dependency container.
Public Member Functions
UserPool (ConditionsManager mgr, ConditionsIOVPool *pool)
Default constructor.
virtual ~UserPool ()
Default destructor.
const IOV & validity () const
Access the interval of validity for this user pool.
const IOV * validityPtr () const
Access the interval of validity for this user pool.
virtual void print (const std::string &opt) const =0
Print pool content.
virtual size_t count () const =0
Total entry count.
virtual void clear ()=0
Full cleanup of all managed conditions.
virtual bool exists (key_type key) const =0
Check a condition for existence.
virtual bool exists (const ConditionKey &key) const =0
Check a condition for existence.
virtual Condition get (key_type key) const =0
Check if a condition exists in the pool and return it to the caller.
virtual Condition get (const ConditionKey &key) const =0
Check if a condition exists in the pool and return it to the caller.
virtual bool remove (key_type hash_key)=0
Remove condition by key from pool.
virtual bool remove (const ConditionKey &key)=0
Remove condition by key from pool.
virtual bool insert (Condition cond)=0
Register a new condition to this pool.
virtual long prepare (const IOV &required)=0
Prepare user pool for usage (load, fill etc.) according to required IOV.
virtual long prepare (const IOV &required, const ConditionKeys &keys)=0
Prepare user pool for usage (load, fill etc.) according to required IOV.
virtual long compute (const Dependencies &dependencies, void *user_param=0)=0
Evaluate and register all derived conditions from the dependency list.
Protected Attributes
IOV m_iov
The pool's interval of validity.
ConditionsManager m_manager
Handle to conditions manager object.
ConditionsIOVPool * m_iovPool
IOV Pool as data source.
Detailed Description
Interface for conditions pool optimized to host conditions updates.
Author
M.Frank
Version
1.0
Definition at line 133 of file ConditionsPool.h.
Member Typedef Documentation
ConditionKeys
typedef ConditionsManager::ConditionKeys DD4hep::Conditions::UserPool::ConditionKeys
Forward definition of the condition keys container.
Definition at line 138 of file ConditionsPool.h.
Dependencies
typedef ConditionsManager::Dependencies DD4hep::Conditions::UserPool::Dependencies
Forward definition of the dependency container.
Definition at line 140 of file ConditionsPool.h.
key_type
typedef Condition::key_type DD4hep::Conditions::UserPool::key_type
Forward definition of the key type.
Definition at line 136 of file ConditionsPool.h.
Constructor & Destructor Documentation
UserPool()
UserPool::UserPool (ConditionsManager mgr, ConditionsIOVPool * pool)
Default constructor.
Definition at line 67 of file ConditionsPool.cpp.
References DD4hep::InstanceCount::increment().
~UserPool()
UserPool::~UserPool () virtual
Default destructor.
Definition at line 74 of file ConditionsPool.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
clear()
virtual void DD4hep::Conditions::UserPool::clear () pure virtual
Full cleanup of all managed conditions.
Referenced by DD4hep::Conditions::ConditionsManagerObject::pushUpdates().
compute()
virtual long DD4hep::Conditions::UserPool::compute (const Dependencies & dependencies, void * user_param = 0) pure virtual
Evaluate and register all derived conditions from the dependency list.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute().
count()
virtual size_t DD4hep::Conditions::UserPool::count () const pure virtual
Total entry count.
exists() [1/2]
virtual bool DD4hep::Conditions::UserPool::exists (key_type key) const pure virtual
Check a condition for existence.
exists() [2/2]
virtual bool DD4hep::Conditions::UserPool::exists (const ConditionKey & key) const pure virtual
Check a condition for existence.
get() [1/2]
virtual Condition DD4hep::Conditions::UserPool::get (key_type key) const pure virtual
Check if a condition exists in the pool and return it to the caller.
Referenced by DD4hep::Conditions::ConditionsLoaderImp::get(), DD4hep::Conditions::AlignmentsLoaderImp::get(), DD4hep::Conditions::ConditionsDependencyHandler::get(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
get() [2/2]
virtual Condition DD4hep::Conditions::UserPool::get (const ConditionKey & key) const pure virtual
Check if a condition exists in the pool and return it to the caller.
insert()
virtual bool DD4hep::Conditions::UserPool::insert (Condition cond) pure virtual
Register a new condition to this pool.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), and DD4hep::Conditions::ConditionsManagerObject::pushUpdates().
prepare() [1/2]
virtual long DD4hep::Conditions::UserPool::prepare (const IOV & required) pure virtual
Prepare user pool for usage (load, fill etc.) according to required IOV.
prepare() [2/2]
virtual long DD4hep::Conditions::UserPool::prepare (const IOV & required, const ConditionKeys & keys) pure virtual
Prepare user pool for usage (load, fill etc.) according to required IOV.
print()
virtual void DD4hep::Conditions::UserPool::print (const std::string & opt) const pure virtual
Print pool content.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::do_callback().
remove() [1/2]
virtual bool DD4hep::Conditions::UserPool::remove (key_type hash_key) pure virtual
Remove condition by key from pool.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::get().
remove() [2/2]
virtual bool DD4hep::Conditions::UserPool::remove (const ConditionKey & key) pure virtual
Remove condition by key from pool.
validity()
const IOV& DD4hep::Conditions::UserPool::validity () const inline
Access the interval of validity for this user pool.
Definition at line 156 of file ConditionsPool.h.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), DD4hep::Conditions::ConditionsDependencyHandler::get(), and DD4hep::Conditions::ConditionsDependencyHandler::requiredValidity().
validityPtr()
const IOV* DD4hep::Conditions::UserPool::validityPtr () const inline
Access the interval of validity for this user pool.
Definition at line 158 of file ConditionsPool.h.
References DD4hep::Conditions::ConditionsPool::clear(), DD4hep::Conditions::ConditionsPool::count(), DD4hep::Conditions::ConditionsPool::exists(), DD4hep::Conditions::ConditionsPool::insert(), and DD4hep::Conditions::ConditionsPool::print().
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::do_callback().
Member Data Documentation
m_iov
IOV DD4hep::Conditions::UserPool::m_iov protected
The pool's interval of validity.
Definition at line 144 of file ConditionsPool.h.
m_iovPool
ConditionsIOVPool* DD4hep::Conditions::UserPool::m_iovPool protected
IOV Pool as data source.
Definition at line 148 of file ConditionsPool.h.
m_manager
ConditionsManager DD4hep::Conditions::UserPool::m_manager protected
Handle to conditions manager object.
Definition at line 146 of file ConditionsPool.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsPool.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsPool.cpp