DD4hep: DD4hep::Simulation::LCIOEventReader Class Reference
DD4hep::Simulation::LCIOEventReader Class Reference abstract
DD4hep::Simulation components, classes and objects
Base class to read lcio files.
#include <LCIOEventReader.h>
Public Member Functions
LCIOEventReader (const std::string &nam)
Initializing constructor.
virtual ~LCIOEventReader ()
Default destructor.
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, std::vector< Particle *> &particles)
Read an event and fill a vector of MCParticles.
virtual EventReaderStatus readParticleCollection (int event_number, EVENT::LCCollection **particles)=0
Read an event and return a LCCollectionVec of MCParticles.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventReader
Geant4EventReader (const std::string &nam)
Initializing constructor.
virtual ~Geant4EventReader ()
Default destructor.
const std::string & name () const
File name.
bool hasDirectAccess () const
Flag if direct event access (by event sequence number) is supported (Default: false)
int currentEventNumber () const
return current Event Number
virtual EventReaderStatus moveToEvent (int event_number)
Move to the indicated event number.
virtual EventReaderStatus skipEvent ()
Skip event. To be implemented for sequential sources.
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, Particles &particles)=0
Read an event and fill a vector of MCParticles.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4EventReader
enum EventReaderStatus {
EVENT_READER_ERROR =0, EVENT_READER_OK =1, EVENT_READER_NO_DIRECT =2, EVENT_READER_NO_PRIMARIES =4,
EVENT_READER_NO_FACTORY =6, EVENT_READER_IO_ERROR =8
}
Status codes of the event reader object. Anything with NOT low-bit set is an error.
typedef Geant4Vertex Vertex
typedef Geant4Particle Particle
typedef std::vector< Particle * > Particles
Protected Attributes inherited from DD4hep::Simulation::Geant4EventReader
std::string m_name
File name to be opened and read.
bool m_directAccess
Flag if direct event access is supported. To be explicitly set by subclass constructors.
int m_currEvent
Current event number.
Detailed Description
Base class to read lcio files.
Author
P.Kostka (main author)
M.Frank (code reshuffeling into new DDG4 scheme)
Version
1.0
Definition at line 36 of file LCIOEventReader.h.
Constructor & Destructor Documentation
LCIOEventReader()
LCIOEventReader::LCIOEventReader (const std::string & nam)
Initializing constructor.
Definition at line 51 of file LCIOEventReader.cpp.
~LCIOEventReader()
LCIOEventReader::~LCIOEventReader () virtual
Default destructor.
Definition at line 57 of file LCIOEventReader.cpp.
Member Function Documentation
readParticleCollection()
virtual EventReaderStatus DD4hep::Simulation::LCIOEventReader::readParticleCollection (int event_number, EVENT::LCCollection ** particles) pure virtual
Read an event and return a LCCollectionVec of MCParticles.
Implemented in DD4hep::Simulation::LCIOFileReader, and DD4hep::Simulation::LCIOStdHepReader.
Referenced by readParticles().
readParticles()
LCIOEventReader::EventReaderStatus LCIOEventReader::readParticles (int event_number, Vertex & primary_vertex, std::vector< Particle *> & particles) virtual
Read an event and fill a vector of MCParticles.
Definition at line 63 of file LCIOEventReader.cpp.
References DD4hep::Simulation::Geant4Particle::charge, DD4hep::Simulation::Geant4Particle::colorFlow, DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4EventReader::EVENT_READER_NO_PRIMARIES, DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, DD4hep::Simulation::G4PARTICLE_SIM_BACKSCATTER, DD4hep::Simulation::G4PARTICLE_SIM_CREATED, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_CALO, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_TRACKER, DD4hep::Simulation::G4PARTICLE_SIM_LEFT_DETECTOR, DD4hep::Simulation::G4PARTICLE_SIM_OVERLAY, DD4hep::Simulation::G4PARTICLE_SIM_PARENT_RADIATED, DD4hep::Simulation::G4PARTICLE_SIM_STOPPED, dd4hep::GeV, DD4hep::Simulation::Geant4Particle::mass, dd4hep::mm, dd4hep::ns, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::Simulation::Geant4Particle::process, DD4hep::Simulation::Geant4Particle::properTime, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, readParticleCollection(), DD4hep::ReferenceBitMask< T >::set(), DD4hep::Simulation::Geant4Particle::spin, DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::time, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/lcio/LCIOEventReader.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/lcio/LCIOEventReader.cpp