DD4hep: DD4hep::Geometry::Cone Class Reference
DD4hep::Geometry::Cone Class Reference
DD4hep::Geometry components, classes and objects
Class describing a cone shape.
#include <Shapes.h>
Public Member Functions
Cone ()=default
Default constructor.
Cone (const Cone &e)=default
Constructor to be used when passing an already created object.
template<typename Q >
Cone (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
Cone (const Handle< Q > &e)
Constructor to be used when passing an already created object.
Cone (double z, double rmin1, double rmax1, double rmin2, double rmax2)
Constructor to create a new anonymous object with attribute initialization.
template<typename Z , typename RMIN1 , typename RMAX1 , typename RMIN2 , typename RMAX2 >
Cone (const Z &z, const RMIN1 &rmin1, const RMAX1 &rmax1, const RMIN2 &rmin2, const RMAX2 &rmax2)
Cone & operator= (const Cone &copy)=default
Assignment operator.
Cone & setDimensions (double z, double rmin1, double rmax1, double rmin2, double rmax2)
Set the box dimensions.
Public Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoCone >
Solid_type ()=default
Default constructor for uninitialized object.
Solid_type (const Solid_type &e)=default
Constructor to be used when passing an already created object.
Solid_type (TGeoCone *p)
Direct assignment using the implementation pointer.
Solid_type (const Handle< TGeoCone > &e)
Constructor to be used when passing an already created object.
Solid_type (const Handle< Q > &e)
Constructor to be used when passing an already created object: need to check pointers.
Solid_type & operator= (const Solid_type &copy)=default
Assignment operator.
const char * name () const
Access to shape name.
operator TGeoCone * () const
Auto conversion to underlying ROOT object.
TGeoCone * operator-> () const
Overloaded operator -> to access underlying object.
std::string toString (int precision=2) const
Conversion to string for pretty print.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Protected Member Functions
void make (double z, double rmin1, double rmax1, double rmin2, double rmax2)
Internal helper method to support object construction.
Protected Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoCone >
void _setDimensions (double *param)
void _assign (TGeoCone *n, const std::string &nam, const std::string &tit, bool cbbox)
Assign pointrs and register solid to geometry.
Additional Inherited Members
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Protected Types inherited from DD4hep::Geometry::Solid_type< TGeoCone >
typedef TGeoCone Implementation
Detailed Description
Class describing a cone shape.
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoCone.html
Author
M.Frank
Version
1.0
Definition at line 361 of file Shapes.h.
Constructor & Destructor Documentation
Cone() [1/6]
DD4hep::Geometry::Cone::Cone () default
Default constructor.
Cone() [2/6]
DD4hep::Geometry::Cone::Cone (const Cone & e) default
Constructor to be used when passing an already created object.
Cone() [3/6]
template<typename Q > DD4hep::Geometry::Cone::Cone (const Q * p) inline
Constructor to be used with an existing object.
Definition at line 371 of file Shapes.h.
Cone() [4/6]
template<typename Q > DD4hep::Geometry::Cone::Cone (const Handle< Q > & e) inline
Constructor to be used when passing an already created object.
Definition at line 373 of file Shapes.h.
Cone() [5/6]
DD4hep::Geometry::Cone::Cone (double z, double rmin1, double rmax1, double rmin2, double rmax2) inline
Constructor to create a new anonymous object with attribute initialization.
Definition at line 375 of file Shapes.h.
Cone() [6/6]
template<typename Z , typename RMIN1 , typename RMAX1 , typename RMIN2 , typename RMAX2 > DD4hep::Geometry::Cone::Cone (const Z & z, const RMIN1 & rmin1, const RMAX1 & rmax1, const RMIN2 & rmin2, const RMAX2 & rmax2) inline
Definition at line 378 of file Shapes.h.
References DD4hep::_toDouble(), DD4hep::Alignments::AlignmentTools::copy(), and DD4hep::Geometry::Solid_type< T >::operator=().
Member Function Documentation
make()
void Cone::make (double z, double rmin1, double rmax1, double rmin2, double rmax2) protected
Internal helper method to support object construction.
Constructor to be used when creating a new object with attribute initialization.
Definition at line 301 of file Shapes.cpp.
operator=()
Cone& DD4hep::Geometry::Cone::operator= (const Cone & copy) default
Assignment operator.
setDimensions()
Cone & Cone::setDimensions (double z, double rmin1, double rmax1, double rmin2, double rmax2)
Set the box dimensions.
Definition at line 305 of file Shapes.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp