DD4hep: DD4hep::DDRec::CylinderSurface Class Reference
DD4hep::DDRec::CylinderSurface Class Reference
#include <Surface.h>
Public Member Functions
CylinderSurface (Geometry::DetElement det, VolSurface volSurf)
Standard c'tor.
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
virtual double radius () const
the radius of the cylinder (rho of the origin vector)
virtual Vector3D center () const
the center of the cylinder
Public Member Functions inherited from DD4hep::DDRec::Surface
virtual ~Surface ()
Surface (Geometry::DetElement det, VolSurface volSurf)
virtual long64 id () const
The id of this surface - corresponds to DetElement id.
virtual const SurfaceType & type () const
Geometry::Volume volume () const
The volume that has the surface attached.
VolSurface volSurface () const
The VolSurface attched to the volume.
virtual const Vector3D & origin () const
virtual double innerThickness () const
virtual double outerThickness () const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double distance (const Vector3D &point) const
virtual bool insideBounds (const Vector3D &point, double epsilon=1.e-4) const
Checks if the given point lies within the surface.
virtual Vector3D volumeOrigin () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual std::vector< std::pair< Vector3D, Vector3D > > getLines (unsigned nMax=100)
Public Member Functions inherited from DDSurfaces::ISurface
virtual ~ISurface ()
Destructor.
Public Member Functions inherited from DDSurfaces::ICylinder
virtual ~ICylinder ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDRec::Surface
Surface ()
default c'tor
void initialize ()
Protected Attributes inherited from DD4hep::DDRec::Surface
Geometry::DetElement _det
VolSurface _volSurf
TGeoMatrix * _wtM
long64 _id
SurfaceType _type
Vector3D _u
Vector3D _v
Vector3D _n
Vector3D _o
Detailed Description
Specialization of Surface for cylinders. Provides acces to the cylinder radius and implements the access to the rotated surface vectors for points on the cylinder.
Author
F.Gaede, DESY
Date
May, 10 2014
Definition at line 622 of file Surface.h.
Constructor & Destructor Documentation
CylinderSurface()
DD4hep::DDRec::CylinderSurface::CylinderSurface (Geometry::DetElement det, VolSurface volSurf) inline
Standard c'tor.
Definition at line 627 of file Surface.h.
References v.
Member Function Documentation
center()
Vector3D DD4hep::DDRec::CylinderSurface::center () const virtual
the center of the cylinder
Implements DDSurfaces::ICylinder.
Reimplemented in DD4hep::DDRec::ConeSurface.
Definition at line 1246 of file Surface.cpp.
References DD4hep::DDRec::Surface::volumeOrigin().
globalToLocal()
Vector2D DD4hep::DDRec::CylinderSurface::globalToLocal (const Vector3D & point) const virtual
Convert the global position to the local position (u,v) on the surface - u runs along the axis of the cylinder, v is r*phi
Reimplemented from DD4hep::DDRec::Surface.
Definition at line 1226 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::_wtM, DDSurfaces::Vector3D::array(), and DD4hep::DDRec::VolSurface::globalToLocal().
localToGlobal()
Vector3D DD4hep::DDRec::CylinderSurface::localToGlobal (const Vector2D & point) const virtual
Convert the local position (u,v) on the surface to the global position - u runs along the axis of the cylinder, v is r*phi
Reimplemented from DD4hep::DDRec::Surface.
Definition at line 1235 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::_wtM, DDSurfaces::Vector3D::array(), and DD4hep::DDRec::VolSurface::localToGlobal().
normal()
Vector3D DD4hep::DDRec::CylinderSurface::normal (const Vector3D & point = Vector3D()) const virtual
The normal direction at the given point - rotated to point projected onto the cylinder. No check is done whether the point actually is on the cylinder surface
Reimplemented from DD4hep::DDRec::Surface.
Definition at line 1218 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::_wtM, DDSurfaces::Vector3D::array(), and DD4hep::DDRec::VolSurface::normal().
radius()
double DD4hep::DDRec::CylinderSurface::radius () const virtual
the radius of the cylinder (rho of the origin vector)
Implements DDSurfaces::ICylinder.
Definition at line 1244 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::VolSurface::origin(), and DDSurfaces::Vector3D::rho().
u()
Vector3D DD4hep::DDRec::CylinderSurface::u (const Vector3D & point = Vector3D()) const virtual
First direction of measurement U - rotated to point projected onto the cylinder. No check is done whether the point actually is on the cylinder surface
Reimplemented from DD4hep::DDRec::Surface.
Definition at line 1201 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::_wtM, DDSurfaces::Vector3D::array(), and DD4hep::DDRec::VolSurface::u().
v()
Vector3D DD4hep::DDRec::CylinderSurface::v (const Vector3D & point = Vector3D()) const virtual
Second direction of measurement V - rotated to point projected onto the cylinder. No check is done whether the point actually is on the cylinder surface
Reimplemented from DD4hep::DDRec::Surface.
Definition at line 1210 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::_wtM, DDSurfaces::Vector3D::array(), and DD4hep::DDRec::VolSurface::v().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp