DD4hep: DD4hep: DD4hep::Simulation::Geant4EscapeCounter Class Reference
DD4hep::Simulation::Geant4EscapeCounter Class Reference
[DD4hep::Simulation components, classes and objects]
Class to measure the energy of escaping tracks.
Public Member Functions
Geant4EscapeCounter (Geant4Context *ctxt, const std::string &name, DetElement det, LCDD &lcdd)
Standard constructor.
virtual ~Geant4EscapeCounter ()
Default destructor.
virtual bool process (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
Private Attributes
size_t m_collectionID
Collection identifiers.
std::vector< std::string > m_detectorNames
Detailed Description
Class to measure the energy of escaping tracks.
Class to measure the energy of escaping tracks of a detector using Geant 4 Measure escaping energy....
Author:
M.Frank
Version:
1.0
Definition at line 36 of file Geant4EscapeCounter.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4EscapeCounter::Geant4EscapeCounter (Geant4Context * ctxt, const std::string & name, DetElement det, LCDD & lcdd)
Standard constructor.
Geant4EscapeCounter::~Geant4EscapeCounter () [virtual]
Default destructor.
Definition at line 90 of file Geant4EscapeCounter.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
bool Geant4EscapeCounter::process (G4Step * step, G4TouchableHistory * history) [virtual]
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 95 of file Geant4EscapeCounter.cpp.
References DD4hep::Simulation::Geant4HitCollection::add(), DD4hep::Simulation::Geant4HitData::cellID, DD4hep::Simulation::Geant4Sensitive::collection(), DD4hep::Simulation::Geant4TrackHandler::creatorName(), DD4hep::Simulation::Geant4StepHandler::deposit(), DD4hep::Simulation::Geant4TrackHandler::energy(), DD4hep::Simulation::Geant4Tracker::Hit::energyDeposit, DD4hep::Simulation::Geant4TrackHandler::id(), DD4hep::Simulation::Geant4Tracker::Hit::length, m_collectionID, DD4hep::Simulation::Geant4Sensitive::mark(), dd4hep::MeV, DD4hep::Simulation::Geant4Tracker::Hit::momentum, DD4hep::Simulation::Geant4TrackHandler::name(), DD4hep::Simulation::Geant4TouchableHandler::path(), DD4hep::Simulation::Geant4TrackHandler::pdgID(), DD4hep::Simulation::Geant4Tracker::Hit::position, DD4hep::Simulation::Geant4StepHandler::prePos(), DD4hep::Simulation::Geant4Action::print(), DD4hep::Simulation::Geant4TrackHandler::time(), DD4hep::Simulation::Geant4StepHandler::track, DD4hep::Simulation::Geant4StepHandler::trkEnergy(), DD4hep::Simulation::Geant4StepHandler::trkID(), DD4hep::Simulation::Geant4StepHandler::trkMom(), and DD4hep::Simulation::Geant4Sensitive::volumeID().
Member Data Documentation
size_t DD4hep::Simulation::Geant4EscapeCounter::m_collectionID [private]
Collection identifiers.
Definition at line 38 of file Geant4EscapeCounter.cpp.
Referenced by process().
std::vector<std::string> DD4hep::Simulation::Geant4EscapeCounter::m_detectorNames [private]
Definition at line 39 of file Geant4EscapeCounter.cpp.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4EscapeCounter.cpp