DD4hep: Geant4Compatibility Class Reference
Geant4Compatibility Class Reference
Public Member Functions
Geant4Compatibility ()
Geant4DetectorConstructionSequence * buildDefaultDetectorConstruction (Geant4Kernel &kernel)
Detailed Description
Definition at line 484 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
Geant4Compatibility()
Geant4Compatibility::Geant4Compatibility () inline
Definition at line 486 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< T >::kernel().
Member Function Documentation
buildDefaultDetectorConstruction()
Geant4DetectorConstructionSequence * Geant4Compatibility::buildDefaultDetectorConstruction (Geant4Kernel & kernel)
Definition at line 489 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4DetectorConstructionSequence::adopt(), DD4hep::Simulation::Geant4ActionContainer::detectorConstruction(), DD4hep::printout(), DD4hep::WARNING, and DD4hep::Simulation::Geant4ActionContainer::workerContext().
Referenced by DD4hep::Simulation::Geant4Exec::configure().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp