DD4hep: DD4hep: DD4hep::Simulation::Geant4TrackHandler Class Reference
DD4hep::Simulation::Geant4TrackHandler Class Reference
[DD4hep::Simulation components, classes and objects]
Helper class to ease the extraction of information from a G4Track object.
#include <Geant4TrackHandler.h>
Public Types
typedef G4VUserTrackInformation Info
typedef
G4ReferenceCountedHandle
< G4VTouchable > Touchable
Public Member Functions
Geant4TrackHandler (const G4Track *t)
Initializing constructor.
const char * statusName () const
operator const G4Track * () const
Conversion to G4Track.
int id () const
Track's identifier.
int parent () const
Track's parent identifier.
G4ParticleDefinition * trackDef () const
Track's particle definition.
const std::string & name () const
Track's particle name.
const std::string & type () const
Track's particle type.
const G4ThreeVector & position () const
Track's position.
const G4ThreeVector & vertex () const
Track's vertex position, where the track was created.
double globalTime () const
Track global time.
double properTime () const
Track proper time.
double energy () const
Track's energy.
double kineticEnergy () const
Track's kinetic energy.
double velocity () const
Track velocity.
double length () const
Track length.
double time () const
Track time.
G4VPhysicalVolume * vol () const
Physical (original) volume of the track.
G4ThreeVector momentum () const
G4VPhysicalVolume * nextVol () const
Next physical volume of the track.
const G4LogicalVolume * vertexVol () const
Logical volume of the origine vertex.
const Touchable & touchable () const
Touchable of the track.
const Touchable & nextTouchable () const
Next touchable of the track.
const G4VProcess * creatorProcess () const
Physical process of the track generation.
const std::string creatorName () const
Physical process of the track generation.
Info * userInfo () const
User information block.
template<typename T >
T * info () const
Specific user information block.
const G4Step * step () const
Step information.
G4int stepNumber () const
Step number.
int pdgID () const
Access the PDG particle identification.
const G4DynamicParticle * dynamic () const
Access the dynamic particle of the track object.
const G4PrimaryParticle * primary () const
Access the primary particle of the track object (if present).
Public Attributes
const G4Track * track
Reference to the track object.
Detailed Description
Helper class to ease the extraction of information from a G4Track object.
Tiny helper/utility class to easily access Geant4 track information. Born by lazyness: Avoid typing millions of statements!
Author:
M.Frank
Version:
1.0
Definition at line 53 of file Geant4TrackHandler.h.
Member Typedef Documentation
typedef G4VUserTrackInformation DD4hep::Simulation::Geant4TrackHandler::Info
Definition at line 55 of file Geant4TrackHandler.h.
typedef G4ReferenceCountedHandle<G4VTouchable> DD4hep::Simulation::Geant4TrackHandler::Touchable
Definition at line 56 of file Geant4TrackHandler.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4TrackHandler::Geant4TrackHandler (const G4Track * t) [inline]
Initializing constructor.
Should test here if the track pointer is valid to avoind any later trouble
Definition at line 60 of file Geant4TrackHandler.h.
Member Function Documentation
const std::string DD4hep::Simulation::Geant4TrackHandler::creatorName () const [inline]
Physical process of the track generation.
Definition at line 167 of file Geant4TrackHandler.h.
References creatorProcess().
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process().
const G4VProcess* DD4hep::Simulation::Geant4TrackHandler::creatorProcess () const [inline]
Physical process of the track generation.
Definition at line 163 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin(), creatorName(), and DD4hep::Simulation::Geant4TrackingPostAction::end().
const G4DynamicParticle* DD4hep::Simulation::Geant4TrackHandler::dynamic () const [inline]
Access the dynamic particle of the track object.
Definition at line 194 of file Geant4TrackHandler.h.
References track.
double DD4hep::Simulation::Geant4TrackHandler::energy () const [inline]
Track's energy.
Definition at line 120 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process().
double DD4hep::Simulation::Geant4TrackHandler::globalTime () const [inline]
Track global time.
Definition at line 112 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
int DD4hep::Simulation::Geant4TrackHandler::id () const [inline]
Track's identifier.
Definition at line 84 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin(), DD4hep::Simulation::Geant4ParticleHandler::end(), and DD4hep::Simulation::Geant4EscapeCounter::process().
template<typename T > T* DD4hep::Simulation::Geant4TrackHandler::info () const [inline]
Specific user information block.
Definition at line 177 of file Geant4TrackHandler.h.
References userInfo().
double DD4hep::Simulation::Geant4TrackHandler::kineticEnergy () const [inline]
Track's kinetic energy.
Definition at line 124 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
double DD4hep::Simulation::Geant4TrackHandler::length () const [inline]
Track length.
Definition at line 132 of file Geant4TrackHandler.h.
References track.
G4ThreeVector DD4hep::Simulation::Geant4TrackHandler::momentum () const [inline]
Definition at line 143 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
const std::string& DD4hep::Simulation::Geant4TrackHandler::name () const [inline]
Track's particle name.
Definition at line 96 of file Geant4TrackHandler.h.
References trackDef().
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process().
const Touchable& DD4hep::Simulation::Geant4TrackHandler::nextTouchable () const [inline]
Next touchable of the track.
Definition at line 159 of file Geant4TrackHandler.h.
References track.
G4VPhysicalVolume* DD4hep::Simulation::Geant4TrackHandler::nextVol () const [inline]
Next physical volume of the track.
Definition at line 147 of file Geant4TrackHandler.h.
References track.
DD4hep::Simulation::Geant4TrackHandler::operator const G4Track * () const [inline]
Conversion to G4Track.
Definition at line 80 of file Geant4TrackHandler.h.
References track.
int DD4hep::Simulation::Geant4TrackHandler::parent () const [inline]
Track's parent identifier.
Definition at line 88 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
int DD4hep::Simulation::Geant4TrackHandler::pdgID () const [inline]
Access the PDG particle identification.
Definition at line 189 of file Geant4TrackHandler.h.
References trackDef().
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process().
const G4ThreeVector& DD4hep::Simulation::Geant4TrackHandler::position () const [inline]
Track's position.
Definition at line 104 of file Geant4TrackHandler.h.
References track.
const G4PrimaryParticle* DD4hep::Simulation::Geant4TrackHandler::primary () const [inline]
Access the primary particle of the track object (if present).
Definition at line 198 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
double DD4hep::Simulation::Geant4TrackHandler::properTime () const [inline]
Track proper time.
Definition at line 116 of file Geant4TrackHandler.h.
References track.
const char* DD4hep::Simulation::Geant4TrackHandler::statusName () const [inline]
Definition at line 67 of file Geant4TrackHandler.h.
References track.
const G4Step* DD4hep::Simulation::Geant4TrackHandler::step () const [inline]
Step information.
Definition at line 181 of file Geant4TrackHandler.h.
References track.
G4int DD4hep::Simulation::Geant4TrackHandler::stepNumber () const [inline]
Step number.
Definition at line 185 of file Geant4TrackHandler.h.
References track.
double DD4hep::Simulation::Geant4TrackHandler::time () const [inline]
Track time.
Definition at line 136 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process().
const Touchable& DD4hep::Simulation::Geant4TrackHandler::touchable () const [inline]
Touchable of the track.
Definition at line 155 of file Geant4TrackHandler.h.
References track.
G4ParticleDefinition* DD4hep::Simulation::Geant4TrackHandler::trackDef () const [inline]
Track's particle definition.
Definition at line 92 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin(), name(), pdgID(), and type().
const std::string& DD4hep::Simulation::Geant4TrackHandler::type () const [inline]
Track's particle type.
Definition at line 100 of file Geant4TrackHandler.h.
References trackDef().
Info* DD4hep::Simulation::Geant4TrackHandler::userInfo () const [inline]
User information block.
Definition at line 173 of file Geant4TrackHandler.h.
References track.
Referenced by info().
double DD4hep::Simulation::Geant4TrackHandler::velocity () const [inline]
Track velocity.
Definition at line 128 of file Geant4TrackHandler.h.
References track.
const G4ThreeVector& DD4hep::Simulation::Geant4TrackHandler::vertex () const [inline]
Track's vertex position, where the track was created.
Definition at line 108 of file Geant4TrackHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
const G4LogicalVolume* DD4hep::Simulation::Geant4TrackHandler::vertexVol () const [inline]
Logical volume of the origine vertex.
Definition at line 151 of file Geant4TrackHandler.h.
References track.
G4VPhysicalVolume* DD4hep::Simulation::Geant4TrackHandler::vol () const [inline]
Physical (original) volume of the track.
Definition at line 140 of file Geant4TrackHandler.h.
References track.
Member Data Documentation
const G4Track* DD4hep::Simulation::Geant4TrackHandler::track
Reference to the track object.
Definition at line 58 of file Geant4TrackHandler.h.
Referenced by creatorProcess(), dynamic(), energy(), globalTime(), id(), kineticEnergy(), length(), momentum(), nextTouchable(), nextVol(), operator const G4Track *(), parent(), position(), primary(), properTime(), statusName(), step(), stepNumber(), time(), touchable(), trackDef(), userInfo(), velocity(), vertex(), vertexVol(), and vol().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TrackHandler.h