DD4hep: DD4hep: DD4hep::Simulation::Geant4DetectorConstruction Class Reference
DD4hep::Simulation::Geant4DetectorConstruction Class Reference
[DD4hep::Simulation components, classes and objects]
Basic implementation of the Geant4 detector construction action.
#include <Geant4DetectorConstruction.h>
Public Member Functions
Geant4DetectorConstruction (Geant4Context *context, const std::string &nam)
Standard Constructor.
virtual ~Geant4DetectorConstruction ()
Default destructor.
virtual void constructGeo (Geant4DetectorConstructionContext *ctxt)
Geometry construction callback. Called at "Construct()".
virtual void constructField (Geant4DetectorConstructionContext *ctxt)
Electromagnetic field construction callback. Called at "ConstructSDandField()".
virtual void constructSensitives (Geant4DetectorConstructionContext *ctxt)
Sensitive detector construction callback. Called at "ConstructSDandField()".
Detailed Description
Basic implementation of the Geant4 detector construction action.
Concrete implementation of the Geant4 detector construction action. The sequences as the object's master dispatches the callbacks for the "constructGeo()" method to create a detector geometry and the "constructSensitives()" call to create the sensitive detectors and the "constructField" to each worker subclassing Geant4DetectorConstruction.
Please note: constructField() and constructSensitives() are executed in a thread-local context. See the Geant4 documentation for details: https://twiki.cern.ch/twiki/bin/view/Geant4/QuickMigrationGuideForGeant4V10
Author:
M.Frank
Version:
1.0
Definition at line 103 of file Geant4DetectorConstruction.h.
Constructor & Destructor Documentation
Geant4DetectorConstruction::Geant4DetectorConstruction (Geant4Context * context, const std::string & nam)
Standard Constructor.
Definition at line 36 of file Geant4DetectorConstruction.cpp.
Geant4DetectorConstruction::~Geant4DetectorConstruction () [virtual]
Default destructor.
Definition at line 42 of file Geant4DetectorConstruction.cpp.
Member Function Documentation
void Geant4DetectorConstruction::constructField (Geant4DetectorConstructionContext * ctxt) [virtual]
Electromagnetic field construction callback. Called at "ConstructSDandField()".
Definition at line 50 of file Geant4DetectorConstruction.cpp.
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::constructField().
void Geant4DetectorConstruction::constructGeo (Geant4DetectorConstructionContext * ctxt) [virtual]
Geometry construction callback. Called at "Construct()".
Reimplemented in DD4hep::Simulation::Geant4DetectorGeometryConstruction.
Definition at line 46 of file Geant4DetectorConstruction.cpp.
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::constructGeo().
void Geant4DetectorConstruction::constructSensitives (Geant4DetectorConstructionContext * ctxt) [virtual]
Sensitive detector construction callback. Called at "ConstructSDandField()".
Reimplemented in DD4hep::Simulation::Geant4DetectorSensitivesConstruction.
Definition at line 54 of file Geant4DetectorConstruction.cpp.
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::constructSensitives().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4DetectorConstruction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4DetectorConstruction.cpp