DD4hep: DD4hep::Geometry::SegmentationObject Class Reference
DD4hep::Geometry::SegmentationObject Class Reference
DD4hep::Geometry components, classes and objects
Implementation class supporting generic Segmentation of sensitive detectors.
#include <SegmentationsInterna.h>
Public Types
typedef DDSegmentation::Segmentation BaseSegmentation
typedef DDSegmentation::Parameters Parameters
typedef DDSegmentation::Parameter Parameter
Public Member Functions
SegmentationObject (BaseSegmentation *s=0)
Standard constructor.
virtual ~SegmentationObject ()
Default destructor.
std::string fieldDescription () const
Access the encoding string.
const std::string & name () const
Access the segmentation name.
void setName (const std::string &value)
Set the segmentation name.
const std::string & type () const
Access the segmentation type.
const std::string & description () const
Access the description of the segmentation.
BitField64 * decoder () const
Access the underlying decoder.
void setDecoder (BitField64 *decoder) const
Set the underlying decoder.
Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
Parameters parameters () const
Access to all parameters.
void setParameters (const Parameters &parameters)
Set all parameters from an existing set of parameters.
Position position (const CellID &cellID) const
Determine the local position based on the cell ID.
CellID cellID (const Position &localPosition, const Position &globalPosition, const VolumeID &volumeID) const
Determine the cell ID based on the position.
VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
Public Attributes
unsigned long magic
Magic word to check object integrity.
unsigned char useForHitPosition
Flag to use segmentation for hit positioning.
Handle< DetElementObject > detector
Reference to hosting top level DetElement structure.
Handle< SensitiveDetectorObject > sensitive
Reference to hosting top level sensitve detector structure.
BaseSegmentation * segmentation
Reference to base segmentation.
Detailed Description
Implementation class supporting generic Segmentation of sensitive detectors.
The SegmentationObject wraps the functionality of the DDSegmentation base class.
Author
M.Frank
Version
1.0
Definition at line 42 of file SegmentationsInterna.h.
Member Typedef Documentation
BaseSegmentation
typedef DDSegmentation::Segmentation DD4hep::Geometry::SegmentationObject::BaseSegmentation
Definition at line 44 of file SegmentationsInterna.h.
Parameter
typedef DDSegmentation::Parameter DD4hep::Geometry::SegmentationObject::Parameter
Definition at line 46 of file SegmentationsInterna.h.
Parameters
typedef DDSegmentation::Parameters DD4hep::Geometry::SegmentationObject::Parameters
Definition at line 45 of file SegmentationsInterna.h.
Constructor & Destructor Documentation
SegmentationObject()
SegmentationObject::SegmentationObject (BaseSegmentation * s = 0)
Standard constructor.
Definition at line 29 of file SegmentationsInterna.cpp.
References DD4hep::InstanceCount::increment().
~SegmentationObject()
SegmentationObject::~SegmentationObject () virtual
Default destructor.
Definition at line 37 of file SegmentationsInterna.cpp.
References DD4hep::InstanceCount::decrement(), and segmentation.
Member Function Documentation
cellID()
CellID SegmentationObject::cellID (const Position & localPosition, const Position & globalPosition, const VolumeID & volumeID) const
Determine the cell ID based on the position.
Definition at line 99 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::cellID(), and segmentation.
decoder()
BitField64 * SegmentationObject::decoder () const
Access the underlying decoder.
Definition at line 69 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::decoder(), and segmentation.
description()
const string & SegmentationObject::description () const
Access the description of the segmentation.
Definition at line 64 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::description(), and segmentation.
fieldDescription()
string SegmentationObject::fieldDescription () const
Access the encoding string.
Definition at line 45 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::fieldDescription(), and segmentation.
name()
const string & SegmentationObject::name () const
Access the segmentation name.
Definition at line 50 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::name(), and segmentation.
neighbours()
void DD4hep::Geometry::SegmentationObject::neighbours (const CellID & cellID, std::set< CellID > & neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
parameter()
Parameter SegmentationObject::parameter (const std::string & parameterName) const
Access to parameter by name.
Definition at line 79 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::parameter(), and segmentation.
parameters()
Parameters SegmentationObject::parameters () const
Access to all parameters.
Definition at line 84 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::parameters(), and segmentation.
position()
Position SegmentationObject::position (const CellID & cellID) const
Determine the local position based on the cell ID.
Segmentation interface
Definition at line 94 of file SegmentationsInterna.cpp.
References DD4hep::DDSegmentation::Segmentation::position(), and segmentation.
setDecoder()
void SegmentationObject::setDecoder (BitField64 * decoder) const
Set the underlying decoder.
Definition at line 74 of file SegmentationsInterna.cpp.
References segmentation, and DD4hep::DDSegmentation::Segmentation::setDecoder().
setName()
void SegmentationObject::setName (const std::string & value)
Set the segmentation name.
Definition at line 54 of file SegmentationsInterna.cpp.
References segmentation, and DD4hep::DDSegmentation::Segmentation::setName().
Referenced by DD4hep::Geometry::Segmentation::Segmentation().
setParameters()
void SegmentationObject::setParameters (const Parameters & parameters)
Set all parameters from an existing set of parameters.
Definition at line 89 of file SegmentationsInterna.cpp.
References segmentation, and DD4hep::DDSegmentation::Segmentation::setParameters().
type()
const string & SegmentationObject::type () const
Access the segmentation type.
Definition at line 59 of file SegmentationsInterna.cpp.
References segmentation, and DD4hep::DDSegmentation::Segmentation::type().
volumeID()
VolumeID SegmentationObject::volumeID (const CellID & cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
Definition at line 106 of file SegmentationsInterna.cpp.
References segmentation, and DD4hep::DDSegmentation::Segmentation::volumeID().
Member Data Documentation
detector
Handle<DetElementObject> DD4hep::Geometry::SegmentationObject::detector
Reference to hosting top level DetElement structure.
Definition at line 93 of file SegmentationsInterna.h.
magic
unsigned long DD4hep::Geometry::SegmentationObject::magic
Magic word to check object integrity.
Data members.
Definition at line 89 of file SegmentationsInterna.h.
segmentation
BaseSegmentation* DD4hep::Geometry::SegmentationObject::segmentation
Reference to base segmentation.
Definition at line 97 of file SegmentationsInterna.h.
Referenced by cellID(), decoder(), description(), fieldDescription(), name(), parameter(), parameters(), position(), setDecoder(), setName(), setParameters(), type(), volumeID(), and ~SegmentationObject().
sensitive
Handle<SensitiveDetectorObject> DD4hep::Geometry::SegmentationObject::sensitive
Reference to hosting top level sensitve detector structure.
Definition at line 95 of file SegmentationsInterna.h.
useForHitPosition
unsigned char DD4hep::Geometry::SegmentationObject::useForHitPosition
Flag to use segmentation for hit positioning.
Definition at line 91 of file SegmentationsInterna.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/SegmentationsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/SegmentationsInterna.cpp