DD4hep: DDSurfaces::Vector2D Class Reference
DDSurfaces::Vector2D Class Reference
#include <Vector2D.h>
Public Member Functions
Vector2D ()
Vector2D (double u_val, double v_val)
double operator[] (unsigned i) const
double u () const
double v () const
double & u ()
double & v ()
Private Attributes
double _u
double _v
Detailed Description
Simple 2D vector helper class; moved out of ISurface definition.
Definition at line 10 of file Vector2D.h.
Constructor & Destructor Documentation
Vector2D() [1/2]
DDSurfaces::Vector2D::Vector2D () inline
Definition at line 13 of file Vector2D.h.
Vector2D() [2/2]
DDSurfaces::Vector2D::Vector2D (double u_val, double v_val) inline
Definition at line 14 of file Vector2D.h.
Member Function Documentation
operator[]()
double DDSurfaces::Vector2D::operator[] (unsigned i) const inline
Definition at line 16 of file Vector2D.h.
References _u, and _v.
u() [1/2]
double DDSurfaces::Vector2D::u () const inline
Definition at line 21 of file Vector2D.h.
References _u.
Referenced by DD4hep::DDRec::VolCylinderImpl::localToGlobal(), and DD4hep::DDRec::VolConeImpl::localToGlobal().
u() [2/2]
double& DDSurfaces::Vector2D::u () inline
Definition at line 25 of file Vector2D.h.
References _u.
v() [1/2]
double DDSurfaces::Vector2D::v () const inline
Definition at line 23 of file Vector2D.h.
References _v.
Referenced by DD4hep::DDRec::VolCylinderImpl::localToGlobal(), and DD4hep::DDRec::VolConeImpl::localToGlobal().
v() [2/2]
double& DDSurfaces::Vector2D::v () inline
Definition at line 26 of file Vector2D.h.
References _v.
Member Data Documentation
_u
double DDSurfaces::Vector2D::_u private
Definition at line 29 of file Vector2D.h.
Referenced by operator[](), and u().
_v
double DDSurfaces::Vector2D::_v private
Definition at line 29 of file Vector2D.h.
Referenced by operator[](), and v().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSurfaces/include/DDSurfaces/Vector2D.h