DD4hep: TGeoExtension Class Reference
TGeoExtension Class Reference abstract
Classes and namespaces from the ROOT project. See http://root.cern.ch
Class of the ROOT toolkit. See http://root.cern.ch/root/htmldoc/ClassIndex.html.
#include <Volumes.h>
Public Member Functions
virtual ~TGeoExtension ()
virtual TGeoExtension * Grab ()=0
TGeoExtension overload: Method called whenever requiring a pointer to the extension.
virtual void Release () const =0
TGeoExtension overload: Method called always when the pointer to the extension is not needed anymore.
Detailed Description
Class of the ROOT toolkit. See http://root.cern.ch/root/htmldoc/ClassIndex.html.
See also
http://root.cern.ch/root/htmldoc/ClassIndex.html
Definition at line 36 of file Volumes.h.
Constructor & Destructor Documentation
~TGeoExtension()
virtual TGeoExtension::~TGeoExtension () inline virtual
Definition at line 38 of file Volumes.h.
References Grab(), and Release().
Member Function Documentation
Grab()
virtual TGeoExtension* TGeoExtension::Grab () pure virtual
TGeoExtension overload: Method called whenever requiring a pointer to the extension.
Implemented in DD4hep::Geometry::VolumeExtension, and DD4hep::Geometry::PlacedVolumeExtension.
Referenced by DD4hep::Geometry::VolumeExtension::copy(), DD4hep::Geometry::PlacedVolumeExtension::operator=(), and ~TGeoExtension().
Release()
virtual void TGeoExtension::Release () const pure virtual
TGeoExtension overload: Method called always when the pointer to the extension is not needed anymore.
Implemented in DD4hep::Geometry::VolumeExtension, and DD4hep::Geometry::PlacedVolumeExtension.
Referenced by DD4hep::Geometry::VolumeExtension::copy(), DD4hep::Geometry::PlacedVolumeExtension::operator=(), and ~TGeoExtension().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Volumes.h