DD4hep: DD4hep::Conditions::AlignmentsLoaderImp Class Reference
DD4hep::Conditions::AlignmentsLoaderImp Class Reference
Concrete class to interface conditions loading from DetElements.
#include <AlignmentsLoaderImp.h>
Public Types
typedef Alignments::Alignment Alignment
Public Member Functions
AlignmentsLoaderImp (ConditionsManager mgr)
Default constructor.
virtual ~AlignmentsLoaderImp ()
Default destructor.
virtual void addRef ()
Addreference count. Use object.
virtual void release ()
Release object. The client may not use any reference any further.
virtual Alignment get (key_type key, const iov_type &iov)
Access the alignments loading mechanism.
virtual Alignment get (key_type key, const UserPool &pool)
Access the alignments loading mechanism. Only alignments in the user pool will be accessed.
Protected Attributes
ConditionsManager m_manager
Reference to conditions manager.
long m_refCount
Referenec count.
Additional Inherited Members
Protected Types inherited from DD4hep::Alignments::AlignmentsLoader
typedef Alignment::key_type key_type
Forward defintion of the key type.
typedef Alignment::iov_type iov_type
Forward definition of the iov type.
Protected Member Functions inherited from DD4hep::Alignments::AlignmentsLoader
virtual ~AlignmentsLoader ()
Protected destructor.
Detailed Description
Concrete class to interface conditions loading from DetElements.
Author
M.Frank
Version
1.0
Definition at line 33 of file AlignmentsLoaderImp.h.
Member Typedef Documentation
Alignment
typedef Alignments::Alignment DD4hep::Conditions::AlignmentsLoaderImp::Alignment
Definition at line 35 of file AlignmentsLoaderImp.h.
Constructor & Destructor Documentation
AlignmentsLoaderImp()
AlignmentsLoaderImp::AlignmentsLoaderImp (ConditionsManager mgr)
Default constructor.
Definition at line 25 of file AlignmentsLoaderImp.cpp.
~AlignmentsLoaderImp()
AlignmentsLoaderImp::~AlignmentsLoaderImp () virtual
Default destructor.
Definition at line 31 of file AlignmentsLoaderImp.cpp.
Member Function Documentation
addRef()
void AlignmentsLoaderImp::addRef () virtual
Addreference count. Use object.
Implements DD4hep::Alignments::AlignmentsLoader.
Definition at line 35 of file AlignmentsLoaderImp.cpp.
References m_refCount.
get() [1/2]
Alignment AlignmentsLoaderImp::get (key_type key, const iov_type & iov) virtual
Access the alignments loading mechanism.
Access the conditions loading mechanism.
Implements DD4hep::Alignments::AlignmentsLoader.
Definition at line 47 of file AlignmentsLoaderImp.cpp.
References DD4hep::Alignments::AlignmentCondition::data(), DD4hep::Conditions::ConditionsManagerObject::get(), m_manager, and DD4hep::Handle< T >::ptr().
get() [2/2]
Alignment AlignmentsLoaderImp::get (key_type key, const UserPool & pool) virtual
Access the alignments loading mechanism. Only alignments in the user pool will be accessed.
Access the conditions loading mechanism. Only conditions in the user pool will be accessed.
Implements DD4hep::Alignments::AlignmentsLoader.
Definition at line 53 of file AlignmentsLoaderImp.cpp.
References DD4hep::Alignments::AlignmentCondition::data(), and DD4hep::Conditions::UserPool::get().
release()
void AlignmentsLoaderImp::release () virtual
Release object. The client may not use any reference any further.
Implements DD4hep::Alignments::AlignmentsLoader.
Definition at line 40 of file AlignmentsLoaderImp.cpp.
References m_refCount.
Member Data Documentation
m_manager
ConditionsManager DD4hep::Conditions::AlignmentsLoaderImp::m_manager protected
Reference to conditions manager.
Definition at line 39 of file AlignmentsLoaderImp.h.
Referenced by get().
m_refCount
long DD4hep::Conditions::AlignmentsLoaderImp::m_refCount protected
Referenec count.
Definition at line 41 of file AlignmentsLoaderImp.h.
Referenced by addRef(), and release().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/AlignmentsLoaderImp.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/AlignmentsLoaderImp.cpp