DD4hep: DD4hep::OpaqueData Class Reference
DD4hep::OpaqueData Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Class describing an opaque data block.
#include <OpaqueData.h>
Public Member Functions
bool fromString (const std::string &rep)
Create data block from string representation.
std::string str () const
Create string representation of the data block.
const std::type_info & typeInfo () const
Access type id of the condition.
const std::string & dataType () const
Access type name of the condition data block.
bool is_bound () const
Check if object is already bound....
template<typename T >
T & get ()
Generic getter. Specify the exact type, not a polymorph type.
template<typename T >
const T & get () const
Generic getter (const version). Specify the exact type, not a polymorph type.
Public Attributes
const BasicGrammar * grammar
Data type.
Protected Member Functions
OpaqueData ()
Standard initializing constructor.
virtual ~OpaqueData ()
Standard Destructor.
OpaqueData (const OpaqueData &c)
Copy constructor.
OpaqueData & operator= (const OpaqueData &c)
Assignment operator.
Protected Attributes
void * pointer
Pointer to object data.
Detailed Description
Class describing an opaque data block.
Access methods are templated. Once the access is fixed on the first call, the data type may not be changed anymore.
Author
M.Frank
Version
1.0
Definition at line 36 of file OpaqueData.h.
Constructor & Destructor Documentation
OpaqueData() [1/2]
OpaqueData::OpaqueData () protected
Standard initializing constructor.
Definition at line 29 of file OpaqueData.cpp.
~OpaqueData()
OpaqueData::~OpaqueData () protected virtual
Standard Destructor.
Definition at line 37 of file OpaqueData.cpp.
OpaqueData() [2/2]
OpaqueData::OpaqueData (const OpaqueData & c) protected
Copy constructor.
Definition at line 33 of file OpaqueData.cpp.
Member Function Documentation
dataType()
const string & OpaqueData::dataType () const
Access type name of the condition data block.
Definition at line 74 of file OpaqueData.cpp.
References grammar, pointer, and DD4hep::BasicGrammar::type_name().
Referenced by DD4hep::Conditions::Condition::str().
fromString()
bool OpaqueData::fromString (const std::string & rep)
Create data block from string representation.
Definition at line 50 of file OpaqueData.cpp.
References DD4hep::BasicGrammar::fromString(), grammar, and pointer.
Referenced by DD4hep::Conditions::Condition::rebind(), and DD4hep::OpaqueDataBlock::set().
get() [1/2]
template<typename T > T & DD4hep::OpaqueData::get ()
Generic getter. Specify the exact type, not a polymorph type.
Definition at line 41 of file OpaqueData_inl.h.
References grammar, pointer, and DD4hep::BasicGrammar::type().
get() [2/2]
template<typename T > const T & DD4hep::OpaqueData::get () const
Generic getter (const version). Specify the exact type, not a polymorph type.
Definition at line 46 of file OpaqueData_inl.h.
References grammar, pointer, and DD4hep::BasicGrammar::type().
is_bound()
bool DD4hep::OpaqueData::is_bound () const inline
Check if object is already bound....
Definition at line 66 of file OpaqueData.h.
References pointer.
Referenced by DD4hep::Conditions::Interna::ConditionObject::is_bound(), DD4hep::Alignments::AlignmentCondition::is_bound(), and DD4hep::Conditions::Condition::is_bound().
operator=()
OpaqueData & OpaqueData::operator= (const OpaqueData & c) protected
Assignment operator.
Definition at line 41 of file OpaqueData.cpp.
References grammar, and pointer.
Referenced by DD4hep::OpaqueDataBlock::operator=().
str()
string OpaqueData::str () const
Create string representation of the data block.
Definition at line 58 of file OpaqueData.cpp.
References grammar, pointer, and DD4hep::BasicGrammar::str().
Referenced by DD4hep::Conditions::Test::__print_bound_container(), and DD4hep::Conditions::Condition::str().
typeInfo()
const type_info & OpaqueData::typeInfo () const
Access type id of the condition.
Definition at line 66 of file OpaqueData.cpp.
References grammar, pointer, and DD4hep::BasicGrammar::type().
Member Data Documentation
grammar
const BasicGrammar* DD4hep::OpaqueData::grammar
Data type.
Definition at line 50 of file OpaqueData.h.
Referenced by DD4hep::OpaqueDataBlock::assign(), DD4hep::OpaqueDataBlock::bind(), dataType(), DD4hep::Conditions::Condition::descriptor(), fromString(), get(), DD4hep::OpaqueDataBlock::move(), DD4hep::OpaqueDataBlock::OpaqueDataBlock(), operator=(), DD4hep::OpaqueDataBlock::operator=(), str(), typeInfo(), and DD4hep::OpaqueDataBlock::~OpaqueDataBlock().
pointer
void* DD4hep::OpaqueData::pointer protected
Pointer to object data.
Definition at line 54 of file OpaqueData.h.
Referenced by DD4hep::OpaqueDataBlock::assign(), DD4hep::OpaqueDataBlock::bind(), dataType(), fromString(), get(), is_bound(), DD4hep::OpaqueDataBlock::move(), DD4hep::OpaqueDataBlock::OpaqueDataBlock(), operator=(), DD4hep::OpaqueDataBlock::operator=(), str(), typeInfo(), and DD4hep::OpaqueDataBlock::~OpaqueDataBlock().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/OpaqueData.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/OpaqueData.cpp
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/OpaqueData_inl.h