DD4hep: DD4hep: DD4hep::XML::DocumentHolder Class Reference
DD4hep::XML::DocumentHolder Class Reference
[DD4hep::XML classes and objects]
Class supporting the basic functionality of an XML document including ownership.
#include <XMLElements.h>
Public Member Functions
DocumentHolder ()
Default Constructor.
DocumentHolder (DOC d)
Constructor.
DocumentHolder & assign (DOC d)
Assign new document. Old document is dropped.
virtual ~DocumentHolder ()
Standard destructor - releases the document.
Detailed Description
Class supporting the basic functionality of an XML document including ownership.
User class encapsulating a DOM document. Nothing special - normal handle around pointer. Contrary to the Document class, on destruction the XML document shall be destroyed and the corresponding resources released.
Author:
M.Frank
Version:
1.0
Definition at line 660 of file XMLElements.h.
Constructor & Destructor Documentation
DD4hep::XML::DocumentHolder::DocumentHolder () [inline]
Default Constructor.
Definition at line 663 of file XMLElements.h.
DD4hep::XML::DocumentHolder::DocumentHolder (DOC d) [inline]
Constructor.
Definition at line 666 of file XMLElements.h.
DocumentHolder::~DocumentHolder () [virtual]
Standard destructor - releases the document.
Definition at line 1062 of file XMLElements.cpp.
References assign().
Member Function Documentation
DocumentHolder & DocumentHolder::assign (DOC d)
Assign new document. Old document is dropped.
Definition at line 1048 of file XMLElements.cpp.
References _D, DD4hep::DEBUG, DD4hep::XML::Document::m_doc, and DD4hep::printout().
Referenced by ~DocumentHolder().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp