DD4hep: DD4hep: DD4hep::Simulation::Test::Geant4TestEventAction Class Reference
DD4hep::Simulation::Test::Geant4TestEventAction Class Reference
[DD4hep::Simulation components, classes and objects]
Example event action doing nothing, but print.
#include <Geant4TestActions.h>
Public Member Functions
Geant4TestEventAction (Geant4Context *c, const std::string &n)
Standard constructor with initializing arguments.
virtual ~Geant4TestEventAction ()
Default destructor.
virtual void begin (const G4Event *)
begin-of-event callback
virtual void end (const G4Event *)
End-of-event callback.
void beginRun (const G4Run *)
begin-of-run callback
void endRun (const G4Run *)
End-of-run callback.
Detailed Description
Example event action doing nothing, but print.
Author:
M.Frank
Version:
1.0
Definition at line 101 of file Geant4TestActions.h.
Constructor & Destructor Documentation
Geant4TestEventAction::Geant4TestEventAction (Geant4Context * c, const std::string & n)
Standard constructor with initializing arguments.
Definition at line 109 of file Geant4TestActions.cpp.
References DD4hep::InstanceCount::increment().
Geant4TestEventAction::~Geant4TestEventAction () [virtual]
Default destructor.
Definition at line 115 of file Geant4TestActions.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4TestEventAction::begin (const G4Event * evt) [virtual]
begin-of-event callback
Reimplemented from DD4hep::Simulation::Geant4EventAction.
Definition at line 119 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Event::event(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, DD4hep::Simulation::Geant4Run::run(), and DD4hep::Simulation::Geant4Context::run().
void Geant4TestEventAction::beginRun (const G4Run * run)
begin-of-run callback
Definition at line 135 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, and DD4hep::Simulation::Geant4Context::runPtr().
void Geant4TestEventAction::end (const G4Event * evt) [virtual]
End-of-event callback.
Reimplemented from DD4hep::Simulation::Geant4EventAction.
Definition at line 127 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Event::event(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, DD4hep::Simulation::Geant4Run::run(), and DD4hep::Simulation::Geant4Context::run().
void Geant4TestEventAction::endRun (const G4Run * run)
End-of-run callback.
Definition at line 142 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, and DD4hep::Simulation::Geant4Context::runPtr().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TestActions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TestActions.cpp