DD4hep: DD4hep::DDRec::IDDecoder Class Reference
DD4hep::DDRec::IDDecoder Class Reference
#include <IDDecoder.h>
Classes
class BarrelEndcapFlag
Public Member Functions
virtual ~IDDecoder ()
Destructor.
CellID cellIDFromLocal (const Geometry::Position &local, const VolumeID volumeID) const
Returns the cell ID from the local position in the given volume ID.
CellID cellID (const Geometry::Position &global) const
Returns the global cell ID from a given global position.
Geometry::Position position (const CellID &cellID) const
Returns the global position from a given cell ID.
Geometry::Position localPosition (const CellID &cellID) const
Returns the local position from a given cell ID.
VolumeID volumeID (const CellID &cellID) const
Returns the volume ID of a given cell ID.
VolumeID volumeID (const Geometry::Position &global) const
Returns the volume ID of a given global position.
Geometry::PlacedVolume placement (const CellID &cellID) const
Returns the placement for a given cell ID.
Geometry::PlacedVolume placement (const Geometry::Position &global) const
Returns the placement for a given global position.
Geometry::DetElement subDetector (const CellID &cellID) const
Returns the subdetector for a given cell ID.
Geometry::DetElement subDetector (const Geometry::Position &global) const
Returns the subdetector for a given global position.
Geometry::DetElement detectorElement (const CellID &cellID) const
Returns the closest detector element in the hierarchy for a given cell ID.
Geometry::DetElement detectorElement (const Geometry::Position &global) const
Returns the closest detector element in the hierarchy for a given global position.
Geometry::Readout readout (const CellID &cellID) const
Access to the Readout object for a given cell ID.
Geometry::Readout readout (const Geometry::Position &global) const
Access to the Readout object for a given global position.
void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
bool areNeighbours (const CellID &cellID, const CellID &otherCellID) const
Checks if the given cell IDs are neighbours.
BarrelEndcapFlag barrelEndcapFlag (const CellID &cellID) const
Access to the barrel-endcap flag.
long int layerIndex (const CellID &cellID) const
Access to the layer index.
long int systemIndex (const CellID &cellID) const
Access to the system index.
Static Public Member Functions
static IDDecoder & getInstance ()
Access to the global IDDecoder instance.
static std::string barrelIdentifier ()
static std::string layerIdentifier ()
static std::string systemIdentifier ()
Protected Member Functions
Geometry::Readout findReadout (const Geometry::DetElement &det) const
Helper method to find the corresponding Readout object to a DetElement.
Static Protected Member Functions
static Geometry::DetElement getClosestDaughter (const Geometry::DetElement &det, const Geometry::Position &position)
Helper method to get the closest daughter DetElement to the position starting from the given DetElement.
Protected Attributes
Geometry::VolumeManager _volumeManager
TGeoManager * _tgeoMgr
Private Member Functions
IDDecoder ()
Default constructor.
IDDecoder (const IDDecoder &)
Disable copy constructor.
void operator= (const IDDecoder &)
Disable assignment operator.
Detailed Description
Combines functionality of the VolumeManager and Segmentation classes to provide a high level interface for position to cell ID and cell ID to position conversions and related information.
Definition at line 32 of file IDDecoder.h.
Constructor & Destructor Documentation
~IDDecoder()
virtual DD4hep::DDRec::IDDecoder::~IDDecoder () inline virtual
Destructor.
Definition at line 75 of file IDDecoder.h.
References areNeighbours(), barrelEndcapFlag(), cellID(), cellIDFromLocal(), detectorElement(), layerIndex(), localPosition(), neighbours(), placement(), position(), readout(), subDetector(), systemIndex(), and volumeID().
IDDecoder() [1/2]
DD4hep::DDRec::IDDecoder::IDDecoder () private
Default constructor.
Definition at line 33 of file IDDecoder.cpp.
References _tgeoMgr, _volumeManager, DD4hep::Geometry::LCDD::getInstance(), DD4hep::Handle< T >::isValid(), DD4hep::Geometry::VolumeManager::TREE, DD4hep::Geometry::DetElement::volume(), DD4hep::Geometry::LCDD::volumeManager(), and DD4hep::Geometry::LCDD::world().
IDDecoder() [2/2]
DD4hep::DDRec::IDDecoder::IDDecoder (const IDDecoder &) private
Disable copy constructor.
Member Function Documentation
areNeighbours()
bool DD4hep::DDRec::IDDecoder::areNeighbours (const CellID & cellID, const CellID & otherCellID) const
Checks if the given cell IDs are neighbours.
Definition at line 186 of file IDDecoder.cpp.
References detectorElement(), findReadout(), DD4hep::Geometry::Segmentation::neighbours(), and DD4hep::Geometry::Readout::segmentation().
Referenced by ~IDDecoder().
barrelEndcapFlag()
IDDecoder::BarrelEndcapFlag DD4hep::DDRec::IDDecoder::barrelEndcapFlag (const CellID & cellID) const
Access to the barrel-endcap flag.
Definition at line 194 of file IDDecoder.cpp.
References barrelIdentifier(), DD4hep::Geometry::IDDescriptor::field(), DD4hep::Geometry::Readout::idSpec(), readout(), and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by ~IDDecoder().
barrelIdentifier()
static std::string DD4hep::DDRec::IDDecoder::barrelIdentifier () inline static
Definition at line 134 of file IDDecoder.h.
Referenced by barrelEndcapFlag().
cellID()
CellID DD4hep::DDRec::IDDecoder::cellID (const Geometry::Position & global) const
Returns the global cell ID from a given global position.
Returns the global cell ID from a given global position
Definition at line 61 of file IDDecoder.cpp.
References DD4hep::Geometry::Segmentation::cellID(), detectorElement(), findReadout(), dd4hep::g, DD4hep::Geometry::Readout::segmentation(), volumeID(), and DD4hep::Geometry::DetElement::worldTransformation().
Referenced by ~IDDecoder().
cellIDFromLocal()
CellID DD4hep::DDRec::IDDecoder::cellIDFromLocal (const Geometry::Position & local, const VolumeID volID) const
Returns the cell ID from the local position in the given volume ID.
Returns the cell ID from the local position in the given volume ID.
Definition at line 45 of file IDDecoder.cpp.
References DD4hep::Geometry::Segmentation::cellID(), detectorElement(), findReadout(), dd4hep::g, DD4hep::Geometry::Readout::segmentation(), and DD4hep::Geometry::DetElement::worldTransformation().
Referenced by ~IDDecoder().
detectorElement() [1/2]
DetElement DD4hep::DDRec::IDDecoder::detectorElement (const CellID & cellID) const
Returns the closest detector element in the hierarchy for a given cell ID.
Definition at line 146 of file IDDecoder.cpp.
References _volumeManager, and DD4hep::Geometry::VolumeManager::lookupDetElement().
Referenced by areNeighbours(), cellID(), cellIDFromLocal(), localPosition(), neighbours(), position(), readout(), volumeID(), and ~IDDecoder().
detectorElement() [2/2]
DetElement DD4hep::DDRec::IDDecoder::detectorElement (const Geometry::Position & global) const
Returns the closest detector element in the hierarchy for a given global position.
Definition at line 153 of file IDDecoder.cpp.
References getClosestDaughter(), DD4hep::Geometry::LCDD::getInstance(), DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), and DD4hep::Geometry::LCDD::world().
findReadout()
Readout DD4hep::DDRec::IDDecoder::findReadout (const Geometry::DetElement & det) const protected
Helper method to find the corresponding Readout object to a DetElement.
Definition at line 212 of file IDDecoder.cpp.
References DD4hep::Geometry::DetElement::children(), DD4hep::Geometry::Volume::isSensitive(), DD4hep::Handle< T >::isValid(), DD4hep::Geometry::SensitiveDetector::readout(), DD4hep::Geometry::Volume::sensitiveDetector(), and DD4hep::Geometry::DetElement::volume().
Referenced by areNeighbours(), cellID(), cellIDFromLocal(), localPosition(), neighbours(), position(), readout(), and volumeID().
getClosestDaughter()
DetElement DD4hep::DDRec::IDDecoder::getClosestDaughter (const Geometry::DetElement & det, const Geometry::Position & position) static protected
Helper method to get the closest daughter DetElement to the position starting from the given DetElement.
Definition at line 238 of file IDDecoder.cpp.
References DD4hep::Geometry::DetElement::children(), DD4hep::Handle< T >::isValid(), localPosition(), DD4hep::Geometry::Volume::solid(), DD4hep::Geometry::DetElement::volume(), and DD4hep::Geometry::DetElement::worldTransformation().
Referenced by detectorElement().
getInstance()
IDDecoder & DD4hep::DDRec::IDDecoder::getInstance (void) static
Access to the global IDDecoder instance.
Definition at line 27 of file IDDecoder.cpp.
Referenced by DD4hep::DDRec::SubdetectorExtensionImpl::isBarrel(), and DD4hep::DDRec::SubdetectorExtensionImpl::isEndcap().
layerIdentifier()
static std::string DD4hep::DDRec::IDDecoder::layerIdentifier () inline static
Definition at line 138 of file IDDecoder.h.
Referenced by layerIndex().
layerIndex()
long int DD4hep::DDRec::IDDecoder::layerIndex (const CellID & cellID) const
Access to the layer index.
Definition at line 200 of file IDDecoder.cpp.
References DD4hep::Geometry::IDDescriptor::field(), DD4hep::Geometry::Readout::idSpec(), layerIdentifier(), readout(), and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by ~IDDecoder().
localPosition()
Position DD4hep::DDRec::IDDecoder::localPosition (const CellID & cellID) const
Returns the local position from a given cell ID.
Definition at line 94 of file IDDecoder.cpp.
References detectorElement(), findReadout(), DD4hep::Geometry::Segmentation::position(), and DD4hep::Geometry::Readout::segmentation().
Referenced by getClosestDaughter(), and ~IDDecoder().
neighbours()
void DD4hep::DDRec::IDDecoder::neighbours (const CellID & cellID, std::set< CellID > & neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
Definition at line 178 of file IDDecoder.cpp.
References detectorElement(), findReadout(), DD4hep::Geometry::Segmentation::neighbours(), and DD4hep::Geometry::Readout::segmentation().
Referenced by ~IDDecoder().
operator=()
void DD4hep::DDRec::IDDecoder::operator= (const IDDecoder &) private
Disable assignment operator.
placement() [1/2]
PlacedVolume DD4hep::DDRec::IDDecoder::placement (const CellID & cellID) const
Returns the placement for a given cell ID.
Definition at line 118 of file IDDecoder.cpp.
References _volumeManager, and DD4hep::Geometry::VolumeManager::lookupPlacement().
Referenced by placement(), and ~IDDecoder().
placement() [2/2]
PlacedVolume DD4hep::DDRec::IDDecoder::placement (const Geometry::Position & global) const
Returns the placement for a given global position.
Definition at line 125 of file IDDecoder.cpp.
References placement(), and volumeID().
position()
Position DD4hep::DDRec::IDDecoder::position (const CellID & cell) const
Returns the global position from a given cell ID.
Returns the global position from a given cell ID
Definition at line 78 of file IDDecoder.cpp.
References detectorElement(), findReadout(), dd4hep::g, DD4hep::Geometry::Segmentation::position(), DD4hep::Geometry::Readout::segmentation(), and DD4hep::Geometry::DetElement::worldTransformation().
Referenced by ~IDDecoder().
readout() [1/2]
Geometry::Readout DD4hep::DDRec::IDDecoder::readout (const CellID & cellID) const
Access to the Readout object for a given cell ID.
Definition at line 164 of file IDDecoder.cpp.
References detectorElement(), and findReadout().
Referenced by barrelEndcapFlag(), layerIndex(), systemIndex(), and ~IDDecoder().
readout() [2/2]
Geometry::Readout DD4hep::DDRec::IDDecoder::readout (const Geometry::Position & global) const
Access to the Readout object for a given global position.
Definition at line 170 of file IDDecoder.cpp.
References detectorElement(), and findReadout().
subDetector() [1/2]
DetElement DD4hep::DDRec::IDDecoder::subDetector (const CellID & cellID) const
Returns the subdetector for a given cell ID.
Definition at line 132 of file IDDecoder.cpp.
References _volumeManager, and DD4hep::Geometry::VolumeManager::lookupDetector().
Referenced by subDetector(), and ~IDDecoder().
subDetector() [2/2]
DetElement DD4hep::DDRec::IDDecoder::subDetector (const Geometry::Position & global) const
Returns the subdetector for a given global position.
Definition at line 139 of file IDDecoder.cpp.
References subDetector(), and volumeID().
systemIdentifier()
static std::string DD4hep::DDRec::IDDecoder::systemIdentifier () inline static
Definition at line 142 of file IDDecoder.h.
Referenced by systemIndex().
systemIndex()
long int DD4hep::DDRec::IDDecoder::systemIndex (const CellID & cellID) const
Access to the system index.
Definition at line 206 of file IDDecoder.cpp.
References DD4hep::Geometry::IDDescriptor::field(), DD4hep::Geometry::Readout::idSpec(), readout(), systemIdentifier(), and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by ~IDDecoder().
volumeID() [1/2]
VolumeID DD4hep::DDRec::IDDecoder::volumeID (const CellID & cellID) const
Returns the volume ID of a given cell ID.
Definition at line 102 of file IDDecoder.cpp.
References detectorElement(), findReadout(), DD4hep::Geometry::Readout::segmentation(), and DD4hep::Geometry::Segmentation::volumeID().
Referenced by cellID(), placement(), subDetector(), and ~IDDecoder().
volumeID() [2/2]
VolumeID DD4hep::DDRec::IDDecoder::volumeID (const Geometry::Position & global) const
Returns the volume ID of a given global position.
Definition at line 110 of file IDDecoder.cpp.
References detectorElement(), and DD4hep::Geometry::DetElement::volumeID().
Member Data Documentation
_tgeoMgr
TGeoManager* DD4hep::DDRec::IDDecoder::_tgeoMgr protected
Definition at line 148 of file IDDecoder.h.
Referenced by IDDecoder().
_volumeManager
Geometry::VolumeManager DD4hep::DDRec::IDDecoder::_volumeManager protected
Definition at line 147 of file IDDecoder.h.
Referenced by detectorElement(), IDDecoder(), placement(), and subDetector().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/API/IDDecoder.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/IDDecoder.cpp