DD4hep: DD4hep::Simulation::Geant4SensDetSequences Class Reference
DD4hep::Simulation::Geant4SensDetSequences Class Reference
DD4hep::Simulation components, classes and objects
Geant4SensDetSequences: class to access groups of sensitive actions.
#include <Geant4SensDetAction.h>
Public Types
typedef std::map< std::string, Geant4SensDetActionSequence * > Members
Public Member Functions
Geant4SensDetSequences ()
Default constructor.
virtual ~Geant4SensDetSequences ()
Default destructor.
Geant4SensDetActionSequence * operator[] (const std::string &name) const
Access sequence member by name.
Geant4SensDetActionSequence * find (const std::string &name) const
Access sequence member by name.
Members & sequences ()
Access to the members.
const Members & sequences () const
Access to the members CONST.
void clear ()
Clear the sequence list.
Private Member Functions
void insert (const std::string &name, Geant4SensDetActionSequence *seq)
Insert sequence member.
Private Attributes
Members m_sequences
Friends
class Geant4ActionContainer
class Geant4SensDetActionSequence
Detailed Description
Geant4SensDetSequences: class to access groups of sensitive actions.
Concrete implementation of the sensitive detector action sequence
Note Multi-Threading issue: Neither callbacks not the action list is protected against multiple threads calling the Geant4 callbacks! These must be protected in the user actions themselves.
Author
M.Frank
Version
1.0
Definition at line 420 of file Geant4SensDetAction.h.
Member Typedef Documentation
Members
typedef std::map<std::string, Geant4SensDetActionSequence*> DD4hep::Simulation::Geant4SensDetSequences::Members
Definition at line 424 of file Geant4SensDetAction.h.
Constructor & Destructor Documentation
Geant4SensDetSequences()
Geant4SensDetSequences::Geant4SensDetSequences ()
Default constructor.
Definition at line 400 of file Geant4SensDetAction.cpp.
~Geant4SensDetSequences()
Geant4SensDetSequences::~Geant4SensDetSequences () virtual
Default destructor.
Definition at line 404 of file Geant4SensDetAction.cpp.
References DD4hep::releaseObjects().
Member Function Documentation
clear()
void Geant4SensDetSequences::clear ()
Clear the sequence list.
Definition at line 440 of file Geant4SensDetAction.cpp.
find()
Geant4SensDetActionSequence * Geant4SensDetSequences::find (const std::string & name) const
Access sequence member by name.
Definition at line 419 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::name().
Referenced by DD4hep::Simulation::Geant4ActionContainer::sensitiveAction().
insert()
void Geant4SensDetSequences::insert (const std::string & name, Geant4SensDetActionSequence * seq) private
Insert sequence member.
Definition at line 428 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::format(), and DD4hep::Simulation::Geant4Action::name().
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), and DD4hep::Simulation::Geant4ActionContainer::sensitiveAction().
operator[]()
Geant4SensDetActionSequence * Geant4SensDetSequences::operator[] (const std::string & name) const
Access sequence member by name.
Definition at line 410 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::name().
sequences() [1/2]
Members& DD4hep::Simulation::Geant4SensDetSequences::sequences () inline
Access to the members.
Definition at line 439 of file Geant4SensDetAction.h.
sequences() [2/2]
const Members& DD4hep::Simulation::Geant4SensDetSequences::sequences () const inline
Access to the members CONST.
Definition at line 443 of file Geant4SensDetAction.h.
Friends And Related Function Documentation
Geant4ActionContainer
friend class Geant4ActionContainer friend
Definition at line 422 of file Geant4SensDetAction.h.
Geant4SensDetActionSequence
friend class Geant4SensDetActionSequence friend
Definition at line 423 of file Geant4SensDetAction.h.
Member Data Documentation
m_sequences
Members DD4hep::Simulation::Geant4SensDetSequences::m_sequences private
Definition at line 426 of file Geant4SensDetAction.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensDetAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SensDetAction.cpp