DD4hep: DD4hep: DD4hep::Geometry::SubtractionSolid Class Reference
DD4hep::Geometry::SubtractionSolid Class Reference
[DD4hep::Geometry components, classes and objects]
Class describing boolean subtraction solid.
#include <Shapes.h>
Public Member Functions
SubtractionSolid ()
Default constructor.
SubtractionSolid (const SubtractionSolid &e)
Constructor to be used when passing an already created object.
template<typename Q >
SubtractionSolid (const Handle< Q > &e)
Constructor to be used when passing an already created object.
SubtractionSolid (const Solid &shape1, const Solid &shape2)
Constructor to create a new object. Position is identity, Rotation is identity-rotation!
SubtractionSolid (const Solid &shape1, const Solid &shape2, const Position &pos)
Constructor to create a new object. Placement by position, Rotation is identity-rotation!
SubtractionSolid (const Solid &shape1, const Solid &shape2, const RotationZYX &rot)
Constructor to create a new object. Placement by a RotationZYX within the mother.
SubtractionSolid (const Solid &shape1, const Solid &shape2, const Rotation3D &rot)
Constructor to create a new object. Placement by a generic rotoation within the mother.
SubtractionSolid (const Solid &shape1, const Solid &shape2, const Transform3D &pos)
Constructor to create a new object. Placement by a generic transformation within the mother.
SubtractionSolid & operator= (const SubtractionSolid &copy)
Assignment operator.
Detailed Description
Class describing boolean subtraction solid.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoCompositeShape.html
http://root.cern.ch/root/html/TGeoSubtraction.html
Author:
M.Frank
Version:
1.0
Definition at line 674 of file Shapes.h.
Constructor & Destructor Documentation
DD4hep::Geometry::SubtractionSolid::SubtractionSolid ()
Default constructor.
DD4hep::Geometry::SubtractionSolid::SubtractionSolid (const SubtractionSolid & e)
Constructor to be used when passing an already created object.
template<typename Q > DD4hep::Geometry::SubtractionSolid::SubtractionSolid (const Handle< Q > & e) [inline]
Constructor to be used when passing an already created object.
Definition at line 681 of file Shapes.h.
SubtractionSolid::SubtractionSolid (const Solid & shape1, const Solid & shape2)
Constructor to create a new object. Position is identity, Rotation is identity-rotation!
Constructor to be used when creating a new object. Position is identity, Rotation is the identity rotation.
Definition at line 434 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoCompositeShape >::_assign(), and DD4hep::Geometry::identityTransform().
SubtractionSolid::SubtractionSolid (const Solid & shape1, const Solid & shape2, const Position & pos)
Constructor to create a new object. Placement by position, Rotation is identity-rotation!
Constructor to be used when creating a new object. Rotation is the identity rotation.
Definition at line 446 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoCompositeShape >::_assign(), DD4hep::Geometry::_translation(), and DD4hep::Geometry::identityTransform().
SubtractionSolid::SubtractionSolid (const Solid & shape1, const Solid & shape2, const RotationZYX & rot)
Constructor to create a new object. Placement by a RotationZYX within the mother.
Constructor to be used when creating a new object.
Definition at line 452 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoCompositeShape >::_assign(), DD4hep::Geometry::_rotationZYX(), and DD4hep::Geometry::identityTransform().
SubtractionSolid::SubtractionSolid (const Solid & shape1, const Solid & shape2, const Rotation3D & rot)
Constructor to create a new object. Placement by a generic rotoation within the mother.
Constructor to be used when creating a new object.
Definition at line 458 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoCompositeShape >::_assign(), DD4hep::Geometry::_rotation3D(), and DD4hep::Geometry::identityTransform().
SubtractionSolid::SubtractionSolid (const Solid & shape1, const Solid & shape2, const Transform3D & pos)
Constructor to create a new object. Placement by a generic transformation within the mother.
Constructor to be used when creating a new object. Placement by a generic transformation within the mother.
Definition at line 440 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoCompositeShape >::_assign(), DD4hep::Geometry::_transform(), and DD4hep::Geometry::identityTransform().
Member Function Documentation
SubtractionSolid& DD4hep::Geometry::SubtractionSolid::operator= (const SubtractionSolid & copy)
Assignment operator.
Reimplemented from DD4hep::Geometry::BooleanSolid.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp