DD4hep: DD4hep::Geometry::LCDDHelper Class Reference
DD4hep::Geometry::LCDDHelper Class Reference
DD4hep::Geometry components, classes and objects
LCDDHelper: class to shortcut certain questions to the DD4hep detector description interface.
#include <LCDDHelper.h>
Public Member Functions
LCDDHelper ()=default
Default constructor.
LCDDHelper (const LCDDHelper &h)=default
Copy constructor.
LCDDHelper (LCDD *lcdd_ptr)
Initializing constructor from pointer.
LCDDHelper (LCDD &lcdd_ref)
Initializing constructor from pointer.
LCDDHelper (const handle_t &h)
Copy constructor.
~LCDDHelper ()=default
Default destructor.
LCDDHelper & operator= (const LCDDHelper &c)=default
Assignment operator.
SensitiveDetector sensitiveDetector (const std::string &detector) const
Access the sensitive detector of a given subdetector (if the sub-detector is sensitive!)
SensitiveDetector sensitiveDetector (DetElement detector) const
Given a detector element, access it's sensitive detector (if the sub-detector is sensitive!)
DetElement detectorByID (int id) const
Find a detector element by it's system ID.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
LCDDHelper: class to shortcut certain questions to the DD4hep detector description interface.
Note: This class may be extended with additional useful (generic) functionality, which requires the use of the main LCDD object.
Author
M.Frank
Version
1.0
Definition at line 34 of file LCDDHelper.h.
Constructor & Destructor Documentation
LCDDHelper() [1/5]
DD4hep::Geometry::LCDDHelper::LCDDHelper () default
Default constructor.
LCDDHelper() [2/5]
DD4hep::Geometry::LCDDHelper::LCDDHelper (const LCDDHelper & h) default
Copy constructor.
LCDDHelper() [3/5]
DD4hep::Geometry::LCDDHelper::LCDDHelper (LCDD * lcdd_ptr) inline
Initializing constructor from pointer.
Definition at line 41 of file LCDDHelper.h.
LCDDHelper() [4/5]
DD4hep::Geometry::LCDDHelper::LCDDHelper (LCDD & lcdd_ref) inline
Initializing constructor from pointer.
Definition at line 43 of file LCDDHelper.h.
LCDDHelper() [5/5]
DD4hep::Geometry::LCDDHelper::LCDDHelper (const handle_t & h) inline
Copy constructor.
Definition at line 45 of file LCDDHelper.h.
References detectorByID(), operator=(), sensitiveDetector(), and ~LCDDHelper().
~LCDDHelper()
DD4hep::Geometry::LCDDHelper::~LCDDHelper () default
Default destructor.
Referenced by LCDDHelper().
Member Function Documentation
detectorByID()
DetElement LCDDHelper::detectorByID (int id) const
Find a detector element by it's system ID.
Definition at line 46 of file LCDDHelper.cpp.
References DD4hep::Geometry::DetElement::id().
Referenced by DD4hep::Geometry::LCDDImp::addDetector(), and LCDDHelper().
operator=()
LCDDHelper& DD4hep::Geometry::LCDDHelper::operator= (const LCDDHelper & c) default
Assignment operator.
Referenced by LCDDHelper().
sensitiveDetector() [1/2]
SensitiveDetector LCDDHelper::sensitiveDetector (const std::string & detector) const
Access the sensitive detector of a given subdetector (if the sub-detector is sensitive!)
Definition at line 21 of file LCDDHelper.cpp.
Referenced by DD4hep::Geometry::LCDDImp::addDetector(), and LCDDHelper().
sensitiveDetector() [2/2]
SensitiveDetector LCDDHelper::sensitiveDetector (DetElement detector) const
Given a detector element, access it's sensitive detector (if the sub-detector is sensitive!)
Definition at line 28 of file LCDDHelper.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::PlacedVolume::volIDs().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/LCDDHelper.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/LCDDHelper.cpp