DD4hep: DD4hep::Simulation::Geant4Event Class Reference
DD4hep::Simulation::Geant4Event Class Reference
DD4hep::Simulation components, classes and objects
User event context for DDG4.
#include <Geant4Context.h>
Public Member Functions
Geant4Event (const G4Event *run, Geant4Random *rndm)
Intializing constructor.
virtual ~Geant4Event ()
Default destructor.
operator const G4Event & () const
Access the G4Event directly: Automatic type conversion.
const G4Event & event () const
Access the G4Event directly: Explicit G4Event accessor.
Geant4Random & random () const
Access the random number generator.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
template<typename T >
T * addExtension (T *ptr, bool take_ownership=true)
Add user extension object. Ownership is transferred and object deleted at the end of the event.
template<typename T >
T * extension (bool alert=true)
Access to type safe extension object. Exception is thrown if the object is invalid.
Public Member Functions inherited from DD4hep::ObjectExtensions
ObjectExtensions (const std::type_info &parent_type)
Default constructor.
ObjectExtensions (const ObjectExtensions &copy)=delete
Copy constructor.
virtual ~ObjectExtensions ()
Default destructor.
ObjectExtensions & operator= (const ObjectExtensions &copy)=delete
Assignment operator.
void move (ObjectExtensions &copy)
Move extensions to target object.
void clear (bool destroy=true)
Clear all extensions.
void copyFrom (const Extensions &ext, void *arg)
Copy object extensions from another object. Hosting type must be identical!
void * addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
void * removeExtension (const std::type_info &info, bool destroy)
Remove an existing extension object from the instance.
void * extension (const std::type_info &info, bool alert) const
Access an existing extension object from the detector element.
void * extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Private Attributes
const G4Event * m_event
Reference to the original Geant4 event object.
Geant4Random * m_random
Reference to the main random number generator.
Additional Inherited Members
Public Types inherited from DD4hep::ObjectExtensions
typedef std::map< const std::type_info *, void * > Extensions
Definition of the extension type.
typedef void *(* copy_t) (const void *, void *arg)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< const std::type_info *, Entry > ExtensionMap
Static Public Member Functions inherited from DD4hep::ObjectExtensions
static void _noDelete (void *)
Function to be passed as dtor if object should NOT be deleted!
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Public Attributes inherited from DD4hep::ObjectExtensions
Extensions extensions
The extensions object.
ExtensionMap * extensionMap
Pointer to the extension map.
Detailed Description
User event context for DDG4.
The context is accessible from the Geant4Context pointer, which is present in every Geant4Action. The event context is only valid however, if there is actually an event being procesed ie. only during the lifetime of the corresponding G4Event objects.
Please note: Extensions are only valid within the hosting event and are INVALID across different events. Hence: They are only useful to extend data of an event.
Any random numbers used to process one event should be accessed from this location. The framework ensures that the same seeded sequence is used throughout the processing of one single event.
Author
M.Frank
Version
1.0
Definition at line 125 of file Geant4Context.h.
Constructor & Destructor Documentation
Geant4Event()
Geant4Event::Geant4Event (const G4Event * run, Geant4Random * rndm)
Intializing constructor.
Definition at line 41 of file Geant4Context.cpp.
References DD4hep::InstanceCount::increment().
~Geant4Event()
Geant4Event::~Geant4Event () virtual
Default destructor.
Definition at line 48 of file Geant4Context.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
addExtension() [1/2]
void* DD4hep::Simulation::Geant4Event::addExtension (void * ptr, const std::type_info & info, destruct_t dtor) inline
Add an extension object to the detector element.
Note: To add an extension, which should NOT be deleted, set 'dtor' to ObjectExtensions::_noDelete or 0.
Definition at line 148 of file Geant4Context.h.
References DD4hep::ObjectExtensions::addExtension().
Referenced by DD4hep::Simulation::generationInitialization(), and DD4hep::Simulation::Geant4ParticleHandler::operator()().
addExtension() [2/2]
template<typename T > T* DD4hep::Simulation::Geant4Event::addExtension (T * ptr, bool take_ownership = true) inline
Add user extension object. Ownership is transferred and object deleted at the end of the event.
Definition at line 152 of file Geant4Context.h.
References DD4hep::ObjectExtensions::addExtension().
event()
const G4Event& DD4hep::Simulation::Geant4Event::event () const inline
Access the G4Event directly: Explicit G4Event accessor.
Definition at line 139 of file Geant4Context.h.
Referenced by DD4hep::Simulation::Test::Geant4TestEventAction::begin(), and DD4hep::Simulation::Test::Geant4TestEventAction::end().
extension()
template<typename T > T* DD4hep::Simulation::Geant4Event::extension (bool alert = true) inline
Access to type safe extension object. Exception is thrown if the object is invalid.
Definition at line 157 of file Geant4Context.h.
References DD4hep::ObjectExtensions::extension().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::beginEvent(), DD4hep::Simulation::Geant4OutputAction::end(), DD4hep::Simulation::Geant4ParticleHandler::endEvent(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), DD4hep::Simulation::Geant4TrackingAction::mark(), DD4hep::Simulation::Geant4Sensitive::mark(), DD4hep::Simulation::Geant4InteractionMerger::operator()(), DD4hep::Simulation::Geant4GeneratorWrapper::operator()(), DD4hep::Simulation::Geant4InteractionVertexBoost::operator()(), DD4hep::Simulation::Geant4InteractionVertexSmear::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::operator()(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::printInteraction(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), DD4hep::Simulation::Geant4ParticleHandler::rebaseSimulatedTracks(), and DD4hep::Simulation::Geant4Output2ROOT::saveEvent().
operator const G4Event &()
DD4hep::Simulation::Geant4Event::operator const G4Event & () const inline
Access the G4Event directly: Automatic type conversion.
Definition at line 137 of file Geant4Context.h.
random()
Geant4Random& DD4hep::Simulation::Geant4Event::random () const inline
Access the random number generator.
Definition at line 141 of file Geant4Context.h.
Referenced by DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionCosTheta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionEta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionFFbar(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionUniform(), and DD4hep::Simulation::Geant4InteractionVertexSmear::smear().
Member Data Documentation
m_event
const G4Event* DD4hep::Simulation::Geant4Event::m_event private
Reference to the original Geant4 event object.
Definition at line 127 of file Geant4Context.h.
m_random
Geant4Random* DD4hep::Simulation::Geant4Event::m_random private
Reference to the main random number generator.
Definition at line 129 of file Geant4Context.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Context.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Context.cpp