DD4hep: DD4hep: DD4hep::Simulation::Test::Geant4TestGeneratorAction Class Reference
DD4hep::Simulation::Test::Geant4TestGeneratorAction Class Reference
[DD4hep::Simulation components, classes and objects]
Example generator action doing nothing, but print.
#include <Geant4TestActions.h>
Public Member Functions
Geant4TestGeneratorAction (Geant4Context *c, const std::string &n)
Standard constructor with initializing arguments.
virtual ~Geant4TestGeneratorAction ()
Default destructor.
virtual void operator() (G4Event *)
Callback to generate primary particles.
Detailed Description
Example generator action doing nothing, but print.
Author:
M.Frank
Version:
1.0
Definition at line 63 of file Geant4TestActions.h.
Constructor & Destructor Documentation
Geant4TestGeneratorAction::Geant4TestGeneratorAction (Geant4Context * c, const std::string & n)
Standard constructor with initializing arguments.
Definition at line 57 of file Geant4TestActions.cpp.
References DD4hep::InstanceCount::increment().
Geant4TestGeneratorAction::~Geant4TestGeneratorAction () [virtual]
Default destructor.
Definition at line 63 of file Geant4TestActions.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4TestGeneratorAction::operator() (G4Event * evt) [virtual]
Callback to generate primary particles.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 68 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::eventPtr(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, and DD4hep::Simulation::Geant4Context::runPtr().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TestActions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TestActions.cpp