DD4hep: DD4hep::DDG4EventHandler Class Reference
DD4hep::DDG4EventHandler Class Reference
DDEve: DD4hep event display components, classes and objects
#include <DDG4EventHandler.h>
Public Types
typedef std::map< std::string, std::pair< TBranch *, void * > > Branches
typedef void *(* ParticleAccessor_t) (void *, DDEveParticle *)
typedef void *(* HitAccessor_t) (void *, DDEveHit *)
Public Types inherited from DD4hep::EventHandler
enum CollectionType {
NO_COLLECTION =1<<0, PARTICLE_COLLECTION =1<<1, TRACK_COLLECTION =1<<2, CALO_HIT_COLLECTION =1<<3,
TRACKER_HIT_COLLECTION =1<<4, HIT_COLLECTION =CALO_HIT_COLLECTION|TRACKER_HIT_COLLECTION
}
typedef std::pair< const char *, size_t > Collection
Collection definition: name, size.
typedef std::map< std::string, std::vector< Collection > > TypedEventCollections
Types collection: collections are grouped by type (class name)
Public Member Functions
DDG4EventHandler ()
Standard constructor.
virtual ~DDG4EventHandler ()
Default destructor.
virtual const TypedEventCollections & data () const
Access the map of simulation data collections.
virtual long numEvents () const
Access the number of events on the current input data source (-1 if no data source connected)
std::string datasourceName () const
Access the data source name.
virtual CollectionType collectionType (const std::string &collection) const
Access to the collection type by name.
virtual size_t collectionLoop (const std::string &collection, DDEveHitActor &actor)
Call functor on hit collection.
virtual size_t collectionLoop (const std::string &collection, DDEveParticleActor &actor)
Loop over collection and extract particle data.
virtual bool Open (const std::string &type, const std::string &file_name)
Open new data file.
virtual bool NextEvent ()
User overloadable function: Load the next event.
virtual bool PreviousEvent ()
User overloadable function: Load the previous event.
virtual bool GotoEvent (long event_number)
Goto a specified event in the file.
Int_t ReadEvent (Long64_t n)
Load the specified event.
ClassDef (DDG4EventHandler, 0)
Public Member Functions inherited from DD4hep::EventHandler
EventHandler ()
Standard constructor.
virtual ~EventHandler ()
Default destructor.
virtual bool hasEvent () const
Check if an event is present in memory.
virtual bool hasFile () const
Check if a data file is connected to the handler.
ClassDef (EventHandler, 0)
Protected Attributes
std::pair< TFile *, TTree * > m_file
Reference to data file.
Branches m_branches
Branch map.
Long64_t m_entry
File entry number.
HitAccessor_t m_simhitConverter
Function pointer to interprete hits.
ParticleAccessor_t m_particleConverter
Function pointer to interprete particles.
TypedEventCollections m_data
Data collection map.
Protected Attributes inherited from DD4hep::EventHandler
bool m_hasFile
Flag to indicate that a file is opened.
bool m_hasEvent
Flag to indicate that an event is loaded.
Detailed Description
Event I/O handler class for the DD4hep event display
Author
M.Frank
Version
1.0
Definition at line 38 of file DDG4EventHandler.h.
Member Typedef Documentation
Branches
typedef std::map<std::string,std::pair<TBranch*,void*> > DD4hep::DDG4EventHandler::Branches
Definition at line 40 of file DDG4EventHandler.h.
HitAccessor_t
typedef void*(* DD4hep::DDG4EventHandler::HitAccessor_t) (void *, DDEveHit *)
Definition at line 42 of file DDG4EventHandler.h.
ParticleAccessor_t
typedef void*(* DD4hep::DDG4EventHandler::ParticleAccessor_t) (void *, DDEveParticle *)
Definition at line 41 of file DDG4EventHandler.h.
Constructor & Destructor Documentation
DDG4EventHandler()
DDG4EventHandler::DDG4EventHandler ()
Standard constructor.
Definition at line 49 of file DDG4EventHandler.cpp.
~DDG4EventHandler()
DDG4EventHandler::~DDG4EventHandler () virtual
Default destructor.
Definition at line 63 of file DDG4EventHandler.cpp.
Member Function Documentation
ClassDef()
DD4hep::DDG4EventHandler::ClassDef (DDG4EventHandler , 0)
Referenced by data().
collectionLoop() [1/2]
size_t DDG4EventHandler::collectionLoop (const std::string & collection, DDEveHitActor & actor) virtual
Call functor on hit collection.
Implements DD4hep::EventHandler.
Definition at line 120 of file DDG4EventHandler.cpp.
References DD4hep::DDEveHitActor::setSize().
Referenced by data().
collectionLoop() [2/2]
size_t DDG4EventHandler::collectionLoop (const std::string & collection, DDEveParticleActor & actor) virtual
Loop over collection and extract particle data.
Implements DD4hep::EventHandler.
Definition at line 140 of file DDG4EventHandler.cpp.
References DD4hep::DDEveParticleActor::setSize().
collectionType()
EventHandler::CollectionType DDG4EventHandler::collectionType (const std::string & collection) const virtual
Access to the collection type by name.
Implements DD4hep::EventHandler.
Definition at line 104 of file DDG4EventHandler.cpp.
Referenced by data().
data()
virtual const TypedEventCollections& DD4hep::DDG4EventHandler::data () const inline virtual
Access the map of simulation data collections.
Implements DD4hep::EventHandler.
Definition at line 63 of file DDG4EventHandler.h.
References ClassDef(), collectionLoop(), collectionType(), datasourceName(), GotoEvent(), m_data, NextEvent(), numEvents(), Open(), PreviousEvent(), and ReadEvent().
datasourceName()
std::string DDG4EventHandler::datasourceName () const virtual
Access the data source name.
Implements DD4hep::EventHandler.
Definition at line 96 of file DDG4EventHandler.cpp.
Referenced by data().
GotoEvent()
bool DDG4EventHandler::GotoEvent (long event_number) virtual
Goto a specified event in the file.
Implements DD4hep::EventHandler.
Definition at line 83 of file DDG4EventHandler.cpp.
Referenced by data().
NextEvent()
bool DDG4EventHandler::NextEvent () virtual
User overloadable function: Load the next event.
Load the next event.
Implements DD4hep::EventHandler.
Definition at line 73 of file DDG4EventHandler.cpp.
Referenced by data().
numEvents()
long DDG4EventHandler::numEvents () const virtual
Access the number of events on the current input data source (-1 if no data source connected)
Implements DD4hep::EventHandler.
Definition at line 88 of file DDG4EventHandler.cpp.
Referenced by data().
Open()
bool DDG4EventHandler::Open (const std::string & type, const std::string & file_name) virtual
Open new data file.
Implements DD4hep::EventHandler.
Definition at line 191 of file DDG4EventHandler.cpp.
References DD4hep::INFO, and DD4hep::printout().
Referenced by data().
PreviousEvent()
bool DDG4EventHandler::PreviousEvent () virtual
User overloadable function: Load the previous event.
Load the previous event.
Implements DD4hep::EventHandler.
Definition at line 78 of file DDG4EventHandler.cpp.
Referenced by data().
ReadEvent()
Int_t DDG4EventHandler::ReadEvent (Long64_t n)
Load the specified event.
Definition at line 160 of file DDG4EventHandler.cpp.
References DD4hep::ERROR, and DD4hep::printout().
Referenced by data().
Member Data Documentation
m_branches
Branches DD4hep::DDG4EventHandler::m_branches protected
Branch map.
Definition at line 47 of file DDG4EventHandler.h.
m_data
TypedEventCollections DD4hep::DDG4EventHandler::m_data protected
Data collection map.
Definition at line 55 of file DDG4EventHandler.h.
Referenced by data().
m_entry
Long64_t DD4hep::DDG4EventHandler::m_entry protected
File entry number.
Definition at line 49 of file DDG4EventHandler.h.
m_file
std::pair<TFile*,TTree*> DD4hep::DDG4EventHandler::m_file protected
Reference to data file.
Definition at line 45 of file DDG4EventHandler.h.
m_particleConverter
ParticleAccessor_t DD4hep::DDG4EventHandler::m_particleConverter protected
Function pointer to interprete particles.
Definition at line 53 of file DDG4EventHandler.h.
m_simhitConverter
HitAccessor_t DD4hep::DDG4EventHandler::m_simhitConverter protected
Function pointer to interprete hits.
Definition at line 51 of file DDG4EventHandler.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/DDG4EventHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/DDG4EventHandler.cpp