DD4hep: DD4hep: DD4hep::Simulation::Geant4PhysicsConstructor Class Reference
DD4hep::Simulation::Geant4PhysicsConstructor Class Reference
[DD4hep::Simulation components, classes and objects]
Implementation base of a Geant4 physics constructor.
#include <Geant4PhysicsConstructor.h>
Classes
class Constructor
Helper class to be used by cleints, by NOT overloaded!
Public Member Functions
Geant4PhysicsConstructor (Geant4Context *context, const std::string &nam)
Standard constructor with initailization parameters.
virtual ~Geant4PhysicsConstructor ()
Default destructor.
virtual void constructPhysics (G4VModularPhysicsList *physics)
constructPhysics callback
virtual void constructProcess (Constructor &ctor)
Callback to construct processes (uses the G4 particle table).
virtual void constructParticle (Constructor &ctor)
Callback to construct particles.
Protected Attributes
int m_type
Physics type (Default: 0).
Detailed Description
Implementation base of a Geant4 physics constructor.
Concrete base of a Geant4 physics constructor. This class is only useful for constructors, which require initialization (and hence instantiation) by the user BEFORE the G4 physics list is instantiated.
The instantiation of the physics list is delayed, because Geant4 does not like the G4VPhysicsConstructor constructor to be called before a physics list is attached to the G4RunManager. We overcome this problem through the delayed instantiation of a helper object made availible to the client.
Author:
M.Frank
Version:
1.0
Definition at line 49 of file Geant4PhysicsConstructor.h.
Constructor & Destructor Documentation
Geant4PhysicsConstructor::Geant4PhysicsConstructor (Geant4Context * context, const std::string & nam)
Standard constructor with initailization parameters.
Standard action constructor.
Definition at line 70 of file Geant4PhysicsConstructor.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), and m_type.
Geant4PhysicsConstructor::~Geant4PhysicsConstructor () [virtual]
Default destructor.
Definition at line 78 of file Geant4PhysicsConstructor.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4PhysicsConstructor::constructParticle (Constructor & ctor) [virtual]
Callback to construct particles.
Reimplemented in DD4hep::Simulation::Geant4ExtraParticles.
Definition at line 94 of file Geant4PhysicsConstructor.cpp.
void Geant4PhysicsConstructor::constructPhysics (G4VModularPhysicsList * physics) [virtual]
constructPhysics callback
Reimplemented from DD4hep::Simulation::Geant4PhysicsList.
Definition at line 84 of file Geant4PhysicsConstructor.cpp.
References m_type.
void Geant4PhysicsConstructor::constructProcess (Constructor & ctor) [virtual]
Callback to construct processes (uses the G4 particle table).
Reimplemented in DD4hep::Simulation::Geant4ExtraParticles.
Definition at line 90 of file Geant4PhysicsConstructor.cpp.
Member Data Documentation
int DD4hep::Simulation::Geant4PhysicsConstructor::m_type [protected]
Physics type (Default: 0).
Definition at line 74 of file Geant4PhysicsConstructor.h.
Referenced by constructPhysics(), and Geant4PhysicsConstructor().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4PhysicsConstructor.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4PhysicsConstructor.cpp