DD4hep: DD4hep::Geometry::Torus Class Reference
DD4hep::Geometry::Torus Class Reference
DD4hep::Geometry components, classes and objects
Class describing a Torus shape.
#include <Shapes.h>
Public Member Functions
Torus ()=default
Default constructor.
Torus (const Torus &e)=default
Constructor to be used when passing an already created object.
template<typename Q >
Torus (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
Torus (const Handle< Q > &e)
Constructor to be used when passing an already created object.
template<typename R , typename RMIN , typename RMAX , typename PHI , typename DELTA_PHI >
Torus (R r, RMIN rmin, RMAX rmax, PHI phi=M_PI, DELTA_PHI delta_phi=2.*M_PI)
Constructor to create a new anonymous object with attribute initialization.
Torus (double r, double rmin, double rmax, double phi=M_PI, double delta_phi=2.*M_PI)
Constructor to create a new anonymous object with attribute initialization.
Torus & operator= (const Torus &copy)=default
Assignment operator.
Torus & setDimensions (double r, double rmin, double rmax, double phi, double delta_phi)
Set the Torus dimensions.
Public Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoTorus >
Solid_type ()=default
Default constructor for uninitialized object.
Solid_type (const Solid_type &e)=default
Constructor to be used when passing an already created object.
Solid_type (TGeoTorus *p)
Direct assignment using the implementation pointer.
Solid_type (const Handle< TGeoTorus > &e)
Constructor to be used when passing an already created object.
Solid_type (const Handle< Q > &e)
Constructor to be used when passing an already created object: need to check pointers.
Solid_type & operator= (const Solid_type &copy)=default
Assignment operator.
const char * name () const
Access to shape name.
operator TGeoTorus * () const
Auto conversion to underlying ROOT object.
TGeoTorus * operator-> () const
Overloaded operator -> to access underlying object.
std::string toString (int precision=2) const
Conversion to string for pretty print.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Private Member Functions
void make (double r, double rmin, double rmax, double phi, double delta_phi)
Internal helper method to support object construction.
Additional Inherited Members
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Protected Types inherited from DD4hep::Geometry::Solid_type< TGeoTorus >
typedef TGeoTorus Implementation
Protected Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoTorus >
void _setDimensions (double *param)
void _assign (TGeoTorus *n, const std::string &nam, const std::string &tit, bool cbbox)
Assign pointrs and register solid to geometry.
Detailed Description
Class describing a Torus shape.
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoTorus.html
Author
M.Frank
Version
1.0
Definition at line 470 of file Shapes.h.
Constructor & Destructor Documentation
Torus() [1/6]
DD4hep::Geometry::Torus::Torus () default
Default constructor.
Torus() [2/6]
DD4hep::Geometry::Torus::Torus (const Torus & e) default
Constructor to be used when passing an already created object.
Torus() [3/6]
template<typename Q > DD4hep::Geometry::Torus::Torus (const Q * p) inline
Constructor to be used with an existing object.
Definition at line 480 of file Shapes.h.
Torus() [4/6]
template<typename Q > DD4hep::Geometry::Torus::Torus (const Handle< Q > & e) inline
Constructor to be used when passing an already created object.
Definition at line 482 of file Shapes.h.
Torus() [5/6]
template<typename R , typename RMIN , typename RMAX , typename PHI , typename DELTA_PHI > DD4hep::Geometry::Torus::Torus (R r, RMIN rmin, RMAX rmax, PHI phi = M_PI, DELTA_PHI delta_phi = 2.*M_PI) inline
Constructor to create a new anonymous object with attribute initialization.
Definition at line 485 of file Shapes.h.
References DD4hep::_toDouble().
Torus() [6/6]
DD4hep::Geometry::Torus::Torus (double r, double rmin, double rmax, double phi = M_PI, double delta_phi = 2.*M_PI) inline
Constructor to create a new anonymous object with attribute initialization.
Definition at line 488 of file Shapes.h.
References DD4hep::Alignments::AlignmentTools::copy(), and DD4hep::Geometry::Solid_type< T >::operator=().
Member Function Documentation
make()
void Torus::make (double r, double rmin, double rmax, double phi, double delta_phi) private
Internal helper method to support object construction.
Constructor to be used when creating a new object with attribute initialization.
Definition at line 365 of file Shapes.cpp.
References dd4hep::deg.
operator=()
Torus& DD4hep::Geometry::Torus::operator= (const Torus & copy) default
Assignment operator.
setDimensions()
Torus & Torus::setDimensions (double r, double rmin, double rmax, double phi, double delta_phi)
Set the Torus dimensions.
Definition at line 370 of file Shapes.cpp.
References dd4hep::deg.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp