DD4hep: DD4hep::DDSegmentation::CartesianGridXYZ Class Reference
DD4hep::DDSegmentation::CartesianGridXYZ Class Reference
#include <CartesianGridXYZ.h>
Public Member Functions
CartesianGridXYZ (const std::string &cellEncoding)
default constructor using an arbitrary type
CartesianGridXYZ (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
virtual ~CartesianGridXYZ ()
destructor
virtual Vector3D position (const CellID &cellID) const
determine the position based on the cell ID
virtual CellID cellID (const Vector3D &localPosition, const Vector3D &globalPosition, const VolumeID &volumeID) const
determine the cell ID based on the position
double gridSizeZ () const
access the grid size in Z
double offsetZ () const
access the coordinate offset in Z
const std::string & fieldNameZ () const
access the field name used for Z
void setGridSizeZ (double cellSize)
set the grid size in Z
void setOffsetZ (double offset)
set the coordinate offset in Z
void setFieldNameZ (const std::string &fieldName)
set the field name used for Z
virtual std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Public Member Functions inherited from DD4hep::DDSegmentation::CartesianGridXY
CartesianGridXY (const std::string &cellEncoding="")
Default constructor passing the encoding string.
CartesianGridXY (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
virtual ~CartesianGridXY ()
destructor
double gridSizeX () const
access the grid size in X
double gridSizeY () const
access the grid size in Y
double offsetX () const
access the coordinate offset in X
double offsetY () const
access the coordinate offset in Y
const std::string & fieldNameX () const
access the field name used for X
const std::string & fieldNameY () const
access the field name used for Y
void setGridSizeX (double cellSize)
set the grid size in X
void setGridSizeY (double cellSize)
set the grid size in Y
void setOffsetX (double offset)
set the coordinate offset in X
void setOffsetY (double offset)
set the coordinate offset in Y
void setFieldNameX (const std::string &fieldName)
set the field name used for X
void setFieldNameY (const std::string &fieldName)
set the field name used for Y
Public Member Functions inherited from DD4hep::DDSegmentation::CartesianGrid
virtual ~CartesianGrid ()
Destructor.
Public Member Functions inherited from DD4hep::DDSegmentation::Segmentation
virtual ~Segmentation ()
Destructor.
virtual void addSubsegmentation (long key_min, long key_max, Segmentation *entry)
Add subsegmentation. Call only valid for Multi-segmentations. Default implementation throws an exception.
virtual VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
virtual void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
virtual std::string fieldDescription () const
Access the encoding string.
virtual const std::string & name () const
Access the segmentation name.
virtual void setName (const std::string &value)
Set the segmentation name.
virtual const std::string & type () const
Access the segmentation type.
virtual const std::string & description () const
Access the description of the segmentation.
virtual BitField64 * decoder () const
Access the underlying decoder.
virtual void setDecoder (BitField64 *decoder)
Set the underlying decoder.
virtual Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
virtual Parameters parameters () const
Access to all parameters.
virtual void setParameters (const Parameters &parameters)
Set all parameters from an existing set of parameters.
Protected Attributes
double _gridSizeZ
the grid size in Z
double _offsetZ
the coordinate offset in Z
std::string _zId
the field name used for Z
Protected Attributes inherited from DD4hep::DDSegmentation::CartesianGridXY
double _gridSizeX
the grid size in X
double _offsetX
the coordinate offset in X
double _gridSizeY
the grid size in Y
double _offsetY
the coordinate offset in Y
std::string _xId
the field name used for X
std::string _yId
the field name used for Y
Protected Attributes inherited from DD4hep::DDSegmentation::Segmentation
std::string _name
The segmentation name.
std::string _type
The segmentation type.
std::string _description
The description of the segmentation.
std::map< std::string, Parameter > _parameters
The parameters for this segmentation.
std::map< std::string, StringParameter > _indexIdentifiers
The indices used for the encoding.
BitField64 * _decoder
The cell ID encoder and decoder.
bool _ownsDecoder
Keeps track of the decoder ownership.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDSegmentation::CartesianGrid
CartesianGrid (const std::string &cellEncoding="")
Default constructor used by derived classes passing the encoding string.
CartesianGrid (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
Segmentation (const std::string &cellEncoding="")
Default constructor used by derived classes passing the encoding string.
Segmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
template<typename TYPE >
void registerParameter (const std::string &nam, const std::string &desc, TYPE &param, const TYPE &defaultVal, UnitType unitTyp=SegmentationParameter::NoUnit, bool isOpt=false)
Add a parameter to this segmentation. Used by derived classes to define their parameters.
void registerIdentifier (const std::string &nam, const std::string &desc, std::string &ident, const std::string &defaultVal)
Add a cell identifier to this segmentation. Used by derived classes to define their required identifiers.
Static Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
static double binToPosition (CellID bin, double cellSize, double offset=0.)
Helper method to convert a bin number to a 1D position.
static int positionToBin (double position, double cellSize, double offset=0.)
Helper method to convert a 1D position to a cell ID.
static double binToPosition (CellID bin, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a bin number to a 1D position given a vector of binBoundaries.
static int positionToBin (double position, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a 1D position to a cell ID given a vector of binBoundaries.
Detailed Description
Definition at line 16 of file CartesianGridXYZ.h.
Constructor & Destructor Documentation
CartesianGridXYZ() [1/2]
DD4hep::DDSegmentation::CartesianGridXYZ::CartesianGridXYZ (const std::string & cellEncoding)
default constructor using an arbitrary type
default constructor using an encoding string
Definition at line 14 of file CartesianGridXYZ.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, _gridSizeZ, _offsetZ, DD4hep::DDSegmentation::Segmentation::_type, _zId, DD4hep::DDSegmentation::SegmentationParameter::LengthUnit, DD4hep::DDSegmentation::Segmentation::registerIdentifier(), and DD4hep::DDSegmentation::Segmentation::registerParameter().
CartesianGridXYZ() [2/2]
DD4hep::DDSegmentation::CartesianGridXYZ::CartesianGridXYZ (BitField64 * decoder)
Default constructor used by derived classes passing an existing decoder.
Definition at line 27 of file CartesianGridXYZ.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, _gridSizeZ, _offsetZ, DD4hep::DDSegmentation::Segmentation::_type, _zId, DD4hep::DDSegmentation::SegmentationParameter::LengthUnit, DD4hep::DDSegmentation::Segmentation::registerIdentifier(), and DD4hep::DDSegmentation::Segmentation::registerParameter().
~CartesianGridXYZ()
DD4hep::DDSegmentation::CartesianGridXYZ::~CartesianGridXYZ () virtual
destructor
Definition at line 40 of file CartesianGridXYZ.cpp.
Member Function Documentation
cellDimensions()
std::vector< double > DD4hep::DDSegmentation::CartesianGridXYZ::cellDimensions (const CellID & cellID) const virtual
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters
cellID is ignored as all cells have the same dimension
Returns
std::vector<double> size 3:
size in x
size in y
size in z
Reimplemented from DD4hep::DDSegmentation::CartesianGridXY.
Definition at line 63 of file CartesianGridXYZ.cpp.
References DD4hep::DDSegmentation::CartesianGridXY::_gridSizeX, DD4hep::DDSegmentation::CartesianGridXY::_gridSizeY, _gridSizeZ, and REGISTER_SEGMENTATION.
Referenced by setFieldNameZ().
cellID()
CellID DD4hep::DDSegmentation::CartesianGridXYZ::cellID (const Vector3D & localPosition, const Vector3D & globalPosition, const VolumeID & volumeID) const virtual
determine the cell ID based on the position
Reimplemented from DD4hep::DDSegmentation::CartesianGridXY.
Definition at line 55 of file CartesianGridXYZ.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, DD4hep::DDSegmentation::CartesianGridXY::_gridSizeX, DD4hep::DDSegmentation::CartesianGridXY::_gridSizeY, _gridSizeZ, DD4hep::DDSegmentation::CartesianGridXY::_offsetX, DD4hep::DDSegmentation::CartesianGridXY::_offsetY, _offsetZ, DD4hep::DDSegmentation::CartesianGridXY::_xId, DD4hep::DDSegmentation::CartesianGridXY::_yId, _zId, DD4hep::DDSegmentation::BitField64::getValue(), DD4hep::DDSegmentation::Segmentation::positionToBin(), DD4hep::DDSegmentation::BitField64::setValue(), DD4hep::DDSegmentation::Vector3D::X, DD4hep::DDSegmentation::Vector3D::Y, and DD4hep::DDSegmentation::Vector3D::Z.
fieldNameZ()
const std::string& DD4hep::DDSegmentation::CartesianGridXYZ::fieldNameZ () const inline
access the field name used for Z
Definition at line 38 of file CartesianGridXYZ.h.
References _zId.
gridSizeZ()
double DD4hep::DDSegmentation::CartesianGridXYZ::gridSizeZ () const inline
access the grid size in Z
Definition at line 30 of file CartesianGridXYZ.h.
References _gridSizeZ.
offsetZ()
double DD4hep::DDSegmentation::CartesianGridXYZ::offsetZ () const inline
access the coordinate offset in Z
Definition at line 34 of file CartesianGridXYZ.h.
References _offsetZ.
position()
Vector3D DD4hep::DDSegmentation::CartesianGridXYZ::position (const CellID & cellID) const virtual
determine the position based on the cell ID
Reimplemented from DD4hep::DDSegmentation::CartesianGridXY.
Definition at line 45 of file CartesianGridXYZ.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, DD4hep::DDSegmentation::CartesianGridXY::_gridSizeX, DD4hep::DDSegmentation::CartesianGridXY::_gridSizeY, _gridSizeZ, DD4hep::DDSegmentation::CartesianGridXY::_offsetX, DD4hep::DDSegmentation::CartesianGridXY::_offsetY, _offsetZ, DD4hep::DDSegmentation::CartesianGridXY::_xId, DD4hep::DDSegmentation::CartesianGridXY::_yId, _zId, DD4hep::DDSegmentation::Segmentation::binToPosition(), DD4hep::DDSegmentation::BitField64::setValue(), DD4hep::DDSegmentation::Vector3D::X, DD4hep::DDSegmentation::Vector3D::Y, and DD4hep::DDSegmentation::Vector3D::Z.
setFieldNameZ()
void DD4hep::DDSegmentation::CartesianGridXYZ::setFieldNameZ (const std::string & fieldName) inline
set the field name used for Z
Definition at line 50 of file CartesianGridXYZ.h.
References _zId, and cellDimensions().
setGridSizeZ()
void DD4hep::DDSegmentation::CartesianGridXYZ::setGridSizeZ (double cellSize) inline
set the grid size in Z
Definition at line 42 of file CartesianGridXYZ.h.
References _gridSizeZ.
setOffsetZ()
void DD4hep::DDSegmentation::CartesianGridXYZ::setOffsetZ (double offset) inline
set the coordinate offset in Z
Definition at line 46 of file CartesianGridXYZ.h.
References _offsetZ.
Member Data Documentation
_gridSizeZ
double DD4hep::DDSegmentation::CartesianGridXYZ::_gridSizeZ protected
the grid size in Z
Definition at line 67 of file CartesianGridXYZ.h.
Referenced by CartesianGridXYZ(), cellDimensions(), cellID(), gridSizeZ(), position(), and setGridSizeZ().
_offsetZ
double DD4hep::DDSegmentation::CartesianGridXYZ::_offsetZ protected
the coordinate offset in Z
Definition at line 69 of file CartesianGridXYZ.h.
Referenced by CartesianGridXYZ(), cellID(), offsetZ(), position(), and setOffsetZ().
_zId
std::string DD4hep::DDSegmentation::CartesianGridXYZ::_zId protected
the field name used for Z
Definition at line 71 of file CartesianGridXYZ.h.
Referenced by CartesianGridXYZ(), cellID(), fieldNameZ(), position(), and setFieldNameZ().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/CartesianGridXYZ.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/CartesianGridXYZ.cpp