DD4hep: DD4hep: DD4hep::Simulation::Geant4StepHandler Class Reference
DD4hep::Simulation::Geant4StepHandler Class Reference
[DD4hep::Simulation components, classes and objects]
Helper class to ease the extraction of information from a G4Step object.
#include <Geant4StepHandler.h>
Public Member Functions
Geant4StepHandler (const G4Step *s)
G4ParticleDefinition * trackDef () const
int trkPdgID () const
const char * preStepStatus () const
Returns the pre-step status in form of a string.
const char * postStepStatus () const
Returns the post-step status in form of a string.
double totalEnergy () const
Returns total energy deposit.
Position prePos () const
Returns the pre-step position.
const G4ThreeVector & prePosG4 () const
Returns the pre-step position as a G4ThreeVector.
Position postPos () const
Returns the post-step position.
const G4ThreeVector & postPosG4 () const
Returns the post-step position as a G4ThreeVector.
Position avgPosition () const
Average position vector of the step.
Position direction () const
Direction calculated from the post- and pre-position ofthe step.
Momentum preMom () const
Momentum postMom () const
Momentum trkMom () const
double deposit () const
double stepLength () const
int trkID () const
int parentID () const
double trkTime () const
double trkEnergy () const
double trkKineEnergy () const
int trkStatus () const
bool trkAlive () const
const G4VProcess * trkProcess () const
const G4VTouchable * preTouchable () const
const G4VTouchable * postTouchable () const
const char * volName (const G4StepPoint *p, const char *undefined="") const
G4VPhysicalVolume * volume (const G4StepPoint *p) const
G4VSolid * solid (const G4StepPoint *p) const
G4VPhysicalVolume * physvol (const G4StepPoint *p) const
G4LogicalVolume * logvol (const G4StepPoint *p) const
G4VSensitiveDetector * sd (const G4StepPoint *p) const
const char * sdName (const G4StepPoint *p, const char *undefined="") const
bool isSensitive (const G4LogicalVolume *lv) const
bool isSensitive (const G4VPhysicalVolume *pv) const
bool isSensitive (const G4StepPoint *point) const
G4VPhysicalVolume * preVolume () const
G4VSensitiveDetector * preSD () const
G4VPhysicalVolume * postVolume () const
G4VSensitiveDetector * postSD () const
bool firstInVolume () const
bool lastInVolume () const
Position localToGlobal (const Position &local) const
Coordinate transformation to global coordinates.
Position localToGlobal (const DDSegmentation::Vector3D &local) const
Coordinate transformation to global coordinates.
Position localToGlobal (const G4ThreeVector &local) const
Coordinate transformation to global coordinates in MM.
Position localToGlobal (double x, double y, double z) const
Coordinate transformation to global coordinates in MM.
Position globalToLocal (double x, double y, double z) const
Coordinate transformation to local coordinates.
Position globalToLocal (const Position &global) const
Coordinate transformation to local coordinates.
Position globalToLocal (const G4ThreeVector &global) const
Coordinate transformation to local coordinates.
G4ThreeVector globalToLocalG4 (double x, double y, double z) const
Coordinate transformation to local coordinates.
G4ThreeVector globalToLocalG4 (const G4ThreeVector &loc) const
Coordinate transformation to local coordinates with G4 objects.
double birkAttenuation () const
Apply BirksLaw.
void doApplyBirksLaw (void)
Set applyBirksLaw to ture.
Static Public Member Functions
static const char * stepStatus (G4StepStatus status)
Returns the step status (argument) in form of a string.
Public Attributes
const G4Step * step
G4StepPoint * pre
G4StepPoint * post
G4Track * track
bool applyBirksLaw
Detailed Description
Helper class to ease the extraction of information from a G4Step object.
Helper/utility class to easily access Geant4 step information. Born by lazyness: Avoid typing millions of statements!
Author:
M.Frank
Version:
1.0
Definition at line 47 of file Geant4StepHandler.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4StepHandler::Geant4StepHandler (const G4Step * s) [inline]
Definition at line 54 of file Geant4StepHandler.h.
References applyBirksLaw, post, pre, and track.
Member Function Documentation
Position DD4hep::Simulation::Geant4StepHandler::avgPosition () const [inline]
Average position vector of the step.
Definition at line 99 of file Geant4StepHandler.h.
References post, and pre.
double Geant4StepHandler::birkAttenuation () const
Apply BirksLaw.
Definition at line 115 of file Geant4StepHandler.cpp.
References step.
Referenced by totalEnergy().
double DD4hep::Simulation::Geant4StepHandler::deposit () const [inline]
Definition at line 129 of file Geant4StepHandler.h.
References step.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::process(), and DD4hep::Simulation::Geant4EscapeCounter::process().
Position DD4hep::Simulation::Geant4StepHandler::direction () const [inline]
Direction calculated from the post- and pre-position ofthe step.
Definition at line 106 of file Geant4StepHandler.h.
References post, and pre.
void DD4hep::Simulation::Geant4StepHandler::doApplyBirksLaw (void) [inline]
Set applyBirksLaw to ture.
Definition at line 242 of file Geant4StepHandler.h.
References applyBirksLaw.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution().
bool DD4hep::Simulation::Geant4StepHandler::firstInVolume () const [inline]
Definition at line 211 of file Geant4StepHandler.h.
References step.
Position Geant4StepHandler::globalToLocal (const G4ThreeVector & global) const
Coordinate transformation to local coordinates.
Definition at line 98 of file Geant4StepHandler.cpp.
References globalToLocalG4().
Position Geant4StepHandler::globalToLocal (const Position & global) const
Coordinate transformation to local coordinates.
Definition at line 92 of file Geant4StepHandler.cpp.
References globalToLocalG4().
Position Geant4StepHandler::globalToLocal (double x, double y, double z) const
Coordinate transformation to local coordinates.
Definition at line 86 of file Geant4StepHandler.cpp.
References globalToLocalG4().
G4ThreeVector Geant4StepHandler::globalToLocalG4 (const G4ThreeVector & loc) const
Coordinate transformation to local coordinates with G4 objects.
Coordinate transformation to local coordinates.
Definition at line 109 of file Geant4StepHandler.cpp.
References step.
G4ThreeVector Geant4StepHandler::globalToLocalG4 (double x, double y, double z) const
Coordinate transformation to local coordinates.
Definition at line 104 of file Geant4StepHandler.cpp.
Referenced by globalToLocal(), and DD4hep::Simulation::TrackerWeighted::process().
bool DD4hep::Simulation::Geant4StepHandler::isSensitive (const G4StepPoint * point) const [inline]
Definition at line 196 of file Geant4StepHandler.h.
References isSensitive(), and volume().
bool DD4hep::Simulation::Geant4StepHandler::isSensitive (const G4VPhysicalVolume * pv) const [inline]
Definition at line 193 of file Geant4StepHandler.h.
References isSensitive().
bool DD4hep::Simulation::Geant4StepHandler::isSensitive (const G4LogicalVolume * lv) const [inline]
Definition at line 190 of file Geant4StepHandler.h.
Referenced by isSensitive().
bool DD4hep::Simulation::Geant4StepHandler::lastInVolume () const [inline]
Definition at line 214 of file Geant4StepHandler.h.
References step.
Position Geant4StepHandler::localToGlobal (double x, double y, double z) const
Coordinate transformation to global coordinates in MM.
Coordinate transformation to global coordinates.
Definition at line 74 of file Geant4StepHandler.cpp.
References localToGlobal().
Position Geant4StepHandler::localToGlobal (const G4ThreeVector & local) const
Coordinate transformation to global coordinates in MM.
Coordinate transformation to global coordinates.
Definition at line 79 of file Geant4StepHandler.cpp.
References step.
Position Geant4StepHandler::localToGlobal (const DDSegmentation::Vector3D & local) const
Coordinate transformation to global coordinates.
Coordinate transformation to global coordinate.
Note: DDSegmentation points are units in CM! Conversion done inside!
Definition at line 64 of file Geant4StepHandler.cpp.
References localToGlobal(), dd4hep::mm, DD4hep::DDSegmentation::Vector3D::X, DD4hep::DDSegmentation::Vector3D::Y, and DD4hep::DDSegmentation::Vector3D::Z.
Position Geant4StepHandler::localToGlobal (const Position & local) const
Coordinate transformation to global coordinates.
Note: Positions are in units of MM!
Definition at line 69 of file Geant4StepHandler.cpp.
Referenced by localToGlobal(), and DD4hep::Simulation::Geant4SensitiveAction< T >::process().
G4LogicalVolume* DD4hep::Simulation::Geant4StepHandler::logvol (const G4StepPoint * p) const [inline]
Definition at line 178 of file Geant4StepHandler.h.
References physvol().
Referenced by DD4hep::Simulation::Geant4MaterialScanner::operator()(), and sd().
int DD4hep::Simulation::Geant4StepHandler::parentID () const [inline]
Definition at line 138 of file Geant4StepHandler.h.
References track.
G4VPhysicalVolume* DD4hep::Simulation::Geant4StepHandler::physvol (const G4StepPoint * p) const [inline]
Definition at line 175 of file Geant4StepHandler.h.
Referenced by logvol().
Momentum DD4hep::Simulation::Geant4StepHandler::postMom () const [inline]
Definition at line 121 of file Geant4StepHandler.h.
References post.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), and Tests::Geant4SensitiveAction< T >::process().
Position DD4hep::Simulation::Geant4StepHandler::postPos () const [inline]
Returns the post-step position.
Definition at line 90 of file Geant4StepHandler.h.
References post.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::Simulation::Geant4MaterialScanner::operator()(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), and Tests::Geant4SensitiveAction< T >::process().
const G4ThreeVector& DD4hep::Simulation::Geant4StepHandler::postPosG4 () const [inline]
Returns the post-step position as a G4ThreeVector.
Definition at line 95 of file Geant4StepHandler.h.
References post.
Referenced by DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4HitData::extractContribution(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), and DD4hep::Simulation::TrackerWeighted::process().
G4VSensitiveDetector* DD4hep::Simulation::Geant4StepHandler::postSD () const [inline]
Definition at line 208 of file Geant4StepHandler.h.
References post, and sd().
Referenced by DD4hep::Simulation::TrackerWeighted::process().
const char * Geant4StepHandler::postStepStatus () const
Returns the post-step status in form of a string.
Definition at line 59 of file Geant4StepHandler.cpp.
References post, and stepStatus().
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep().
const G4VTouchable* DD4hep::Simulation::Geant4StepHandler::postTouchable () const [inline]
Definition at line 162 of file Geant4StepHandler.h.
References post.
G4VPhysicalVolume* DD4hep::Simulation::Geant4StepHandler::postVolume () const [inline]
Definition at line 205 of file Geant4StepHandler.h.
References post, and volume().
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), and DD4hep::Simulation::TrackerWeighted::process().
Momentum DD4hep::Simulation::Geant4StepHandler::preMom () const [inline]
Definition at line 117 of file Geant4StepHandler.h.
References pre.
Referenced by Tests::Geant4SensitiveAction< T >::process().
Position DD4hep::Simulation::Geant4StepHandler::prePos () const [inline]
Returns the pre-step position.
Definition at line 81 of file Geant4StepHandler.h.
References pre.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::Simulation::Geant4MaterialScanner::operator()(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), DD4hep::Simulation::Geant4EscapeCounter::process(), and Tests::Geant4SensitiveAction< T >::process().
const G4ThreeVector& DD4hep::Simulation::Geant4StepHandler::prePosG4 () const [inline]
Returns the pre-step position as a G4ThreeVector.
Definition at line 86 of file Geant4StepHandler.h.
References pre.
Referenced by DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4HitData::extractContribution(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), and DD4hep::Simulation::TrackerWeighted::process().
G4VSensitiveDetector* DD4hep::Simulation::Geant4StepHandler::preSD () const [inline]
Definition at line 202 of file Geant4StepHandler.h.
References pre, and sd().
Referenced by DD4hep::Simulation::TrackerWeighted::process().
const char * Geant4StepHandler::preStepStatus () const
Returns the pre-step status in form of a string.
Definition at line 54 of file Geant4StepHandler.cpp.
References pre, and stepStatus().
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep().
const G4VTouchable* DD4hep::Simulation::Geant4StepHandler::preTouchable () const [inline]
Definition at line 159 of file Geant4StepHandler.h.
References pre.
Referenced by DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::operator()(), and DD4hep::Simulation::Geant4Sensitive::volumeID().
G4VPhysicalVolume* DD4hep::Simulation::Geant4StepHandler::preVolume () const [inline]
Definition at line 199 of file Geant4StepHandler.h.
References pre, and volume().
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), and DD4hep::Simulation::TrackerWeighted::process().
G4VSensitiveDetector* DD4hep::Simulation::Geant4StepHandler::sd (const G4StepPoint * p) const [inline]
Definition at line 182 of file Geant4StepHandler.h.
References logvol().
Referenced by postSD(), preSD(), DD4hep::Simulation::TrackerCombine::process(), and sdName().
const char* DD4hep::Simulation::Geant4StepHandler::sdName (const G4StepPoint * p, const char * undefined = "") const [inline]
Definition at line 186 of file Geant4StepHandler.h.
References s, and sd().
G4VSolid* DD4hep::Simulation::Geant4StepHandler::solid (const G4StepPoint * p) const [inline]
Definition at line 172 of file Geant4StepHandler.h.
Referenced by DD4hep::Simulation::TrackerWeighted::process().
double DD4hep::Simulation::Geant4StepHandler::stepLength () const [inline]
Definition at line 132 of file Geant4StepHandler.h.
References step.
const char * Geant4StepHandler::stepStatus (G4StepStatus status) [static]
Returns the step status (argument) in form of a string.
Returns the step status in form of a string.
Definition at line 23 of file Geant4StepHandler.cpp.
Referenced by postStepStatus(), and preStepStatus().
double DD4hep::Simulation::Geant4StepHandler::totalEnergy () const [inline]
Returns total energy deposit.
Definition at line 74 of file Geant4StepHandler.h.
References applyBirksLaw, birkAttenuation(), and step.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution().
G4ParticleDefinition* DD4hep::Simulation::Geant4StepHandler::trackDef () const [inline]
Definition at line 61 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution().
bool DD4hep::Simulation::Geant4StepHandler::trkAlive () const [inline]
Definition at line 153 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::TrackerWeighted::process().
double DD4hep::Simulation::Geant4StepHandler::trkEnergy () const [inline]
Definition at line 144 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution(), and DD4hep::Simulation::Geant4EscapeCounter::process().
int DD4hep::Simulation::Geant4StepHandler::trkID () const [inline]
Definition at line 135 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution(), DD4hep::Simulation::TrackerWeighted::process(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), and DD4hep::Simulation::Geant4EscapeCounter::process().
double DD4hep::Simulation::Geant4StepHandler::trkKineEnergy () const [inline]
Definition at line 147 of file Geant4StepHandler.h.
References track.
Momentum DD4hep::Simulation::Geant4StepHandler::trkMom () const [inline]
Definition at line 125 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process().
int DD4hep::Simulation::Geant4StepHandler::trkPdgID () const [inline]
Definition at line 64 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution(), and DD4hep::Simulation::Geant4SensitiveAction< T >::process().
const G4VProcess* DD4hep::Simulation::Geant4StepHandler::trkProcess () const [inline]
Definition at line 156 of file Geant4StepHandler.h.
References track.
int DD4hep::Simulation::Geant4StepHandler::trkStatus () const [inline]
Definition at line 150 of file Geant4StepHandler.h.
References track.
double DD4hep::Simulation::Geant4StepHandler::trkTime () const [inline]
Definition at line 141 of file Geant4StepHandler.h.
References track.
Referenced by DD4hep::Simulation::Geant4HitData::extractContribution().
const char* DD4hep::Simulation::Geant4StepHandler::volName (const G4StepPoint * p, const char * undefined = "") const [inline]
Definition at line 165 of file Geant4StepHandler.h.
References v, and volume().
G4VPhysicalVolume* DD4hep::Simulation::Geant4StepHandler::volume (const G4StepPoint * p) const [inline]
Definition at line 169 of file Geant4StepHandler.h.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), isSensitive(), postVolume(), preVolume(), DD4hep::Simulation::TrackerCombine::process(), and volName().
Member Data Documentation
bool DD4hep::Simulation::Geant4StepHandler::applyBirksLaw
Definition at line 53 of file Geant4StepHandler.h.
Referenced by doApplyBirksLaw(), Geant4StepHandler(), and totalEnergy().
G4StepPoint* DD4hep::Simulation::Geant4StepHandler::post
Definition at line 51 of file Geant4StepHandler.h.
Referenced by avgPosition(), direction(), DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), Geant4StepHandler(), postMom(), postPos(), postPosG4(), postSD(), postStepStatus(), postTouchable(), postVolume(), DD4hep::Simulation::TrackerWeighted::process(), and DD4hep::Simulation::TrackerCombine::process().
G4StepPoint* DD4hep::Simulation::Geant4StepHandler::pre
Definition at line 50 of file Geant4StepHandler.h.
Referenced by avgPosition(), direction(), Geant4StepHandler(), DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), DD4hep::Simulation::Geant4MaterialScanner::operator()(), preMom(), prePos(), prePosG4(), preSD(), preStepStatus(), preTouchable(), preVolume(), DD4hep::Simulation::TrackerWeighted::process(), and DD4hep::Simulation::TrackerCombine::process().
const G4Step* DD4hep::Simulation::Geant4StepHandler::step
Definition at line 49 of file Geant4StepHandler.h.
Referenced by birkAttenuation(), deposit(), firstInVolume(), globalToLocalG4(), lastInVolume(), localToGlobal(), stepLength(), and totalEnergy().
G4Track* DD4hep::Simulation::Geant4StepHandler::track
Definition at line 52 of file Geant4StepHandler.h.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), Geant4StepHandler(), parentID(), DD4hep::Simulation::TrackerCombine::process(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), DD4hep::Simulation::Geant4EscapeCounter::process(), trackDef(), trkAlive(), trkEnergy(), trkID(), trkKineEnergy(), trkMom(), trkPdgID(), trkProcess(), trkStatus(), and trkTime().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4StepHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4StepHandler.cpp