DD4hep: DD4hep::Alignments::GlobalAlignmentWriter Class Reference
DD4hep::Alignments::GlobalAlignmentWriter Class Reference
DDAlign: DD4hep Detector geometry alignment components.
Write aligment data to XML data file.
#include <GlobalAlignmentWriter.h>
Public Member Functions
GlobalAlignmentWriter (LCDD &lcdd)
Initializing Constructor.
virtual ~GlobalAlignmentWriter ()
Standard destructor.
XML::Document dump (DetElement element, bool enable_transactions=false) const
Dump one full DetElement subtree into a newly created document.
XML::Element scan (XML::Document doc, DetElement element) const
Scan one DetElement structure and return an XML element containing the alignment in this subtree.
XML::Element createElement (XML::Document doc, DetElement element) const
Create the element corresponding to one single detector element without children.
long write (XML::Document doc, const std::string &output) const
Write the XML document structure to a file.
Protected Member Functions
void addNode (XML::Element elt, GlobalAlignment a) const
Add single alignment node to the XML document.
Protected Attributes
LCDD & m_lcdd
Reference to detector description.
GlobalAlignmentCache * m_cache
Reference to the alignment cache.
Detailed Description
Write aligment data to XML data file.
Author
M.Frank
Version
1.0
Definition at line 37 of file GlobalAlignmentWriter.h.
Constructor & Destructor Documentation
GlobalAlignmentWriter()
GlobalAlignmentWriter::GlobalAlignmentWriter (LCDD & lcdd)
Initializing Constructor.
Definition at line 39 of file GlobalAlignmentWriter.cpp.
References DD4hep::Alignments::GlobalAlignmentCache::addRef(), DD4hep::Geometry::LCDD::extension(), and m_cache.
~GlobalAlignmentWriter()
GlobalAlignmentWriter::~GlobalAlignmentWriter () virtual
Standard destructor.
Definition at line 47 of file GlobalAlignmentWriter.cpp.
References m_cache, and DD4hep::Alignments::GlobalAlignmentCache::release().
Member Function Documentation
addNode()
void GlobalAlignmentWriter::addNode (XML::Element elt, GlobalAlignment a) const protected
Add single alignment node to the XML document.
Definition at line 73 of file GlobalAlignmentWriter.cpp.
References _ALU, _U, DD4hep::Geometry::_XYZangles(), DD4hep::XML::Element::append(), DD4hep::XML::Element::document(), e, DD4hep::INFO, DD4hep::printout(), and DD4hep::XML::Element::setAttr().
Referenced by createElement().
createElement()
XML::Element GlobalAlignmentWriter::createElement (XML::Document doc, DetElement element) const
Create the element corresponding to one single detector element without children.
Definition at line 52 of file GlobalAlignmentWriter.cpp.
References _ALU, _U, addNode(), DD4hep::XML::Element::append(), e, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::path(), DD4hep::Geometry::DetElement::placementPath(), DD4hep::XML::Element::setAttr(), and DD4hep::Alignments::GlobalDetectorAlignment::volumeAlignments().
Referenced by scan().
dump()
XML::Document GlobalAlignmentWriter::dump (DetElement element, bool enable_transactions = false) const
Dump one full DetElement subtree into a newly created document.
Dump the tree content into a XML document structure.
Definition at line 128 of file GlobalAlignmentWriter.cpp.
References _ALU, DD4hep::XML::Element::append(), DD4hep::XML::DocumentHandler::create(), DD4hep::XML::Document::root(), scan(), and XML_IMPLEMENTATION_TYPE.
scan()
XML::Element GlobalAlignmentWriter::scan (XML::Document doc, DetElement element) const
Scan one DetElement structure and return an XML element containing the alignment in this subtree.
Scan a DetElement subtree and add on the fly the XML entries.
Definition at line 111 of file GlobalAlignmentWriter.cpp.
References DD4hep::Geometry::DetElement::children(), createElement(), and DD4hep::Handle< T >::isValid().
Referenced by dump().
write()
long GlobalAlignmentWriter::write (XML::Document doc, const std::string & output) const
Write the XML document structure to a file.
Definition at line 151 of file GlobalAlignmentWriter.cpp.
References DD4hep::XML::DocumentHandler::output().
Member Data Documentation
m_cache
GlobalAlignmentCache* DD4hep::Alignments::GlobalAlignmentWriter::m_cache protected
Reference to the alignment cache.
Definition at line 42 of file GlobalAlignmentWriter.h.
Referenced by GlobalAlignmentWriter(), and ~GlobalAlignmentWriter().
m_lcdd
LCDD& DD4hep::Alignments::GlobalAlignmentWriter::m_lcdd protected
Reference to detector description.
Definition at line 40 of file GlobalAlignmentWriter.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/GlobalAlignmentWriter.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/GlobalAlignmentWriter.cpp