DD4hep: DD4hep: DD4hep::Conditions::Container Class Reference
DD4hep::Conditions::Container Class Reference
[DDCond: DD4hep Detector Conditions components, classes and functions]
Container class for condition handles aggregated by a detector element.
#include <Conditions.h>
Public Types
typedef Interna::ConditionContainer Object
Standard object type.
typedef Condition::key_type key_type
Forward definition of the key type.
typedef Condition::iov_type iov_type
Forward definition of the iov type.
Public Member Functions
Container ()
Default constructor.
Container (const Container &c)
Constructor to be used when reading the already parsed object.
template<typename Q >
Container (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
Container & operator= (const Container &c)
Assignment operator.
size_t numKeys () const
Access the number of conditons keys available for this detector element.
Condition get (const std::string &condition_key, const iov_type &iov)
Access to condition objects by key and IOV.
Condition get (key_type condition_key, const iov_type &iov)
Access to condition objects directly by their hash key.
Condition get (const std::string &condition_key, const UserPool &iov)
Access to condition objects. Only conditions in the pool are accessed.
Condition get (key_type condition_key, const UserPool &iov)
Access to condition objects. Only conditions in the pool are accessed.
Detailed Description
Container class for condition handles aggregated by a detector element.
Note: The conditions container is owner by the detector element On deletion the detector element will destroy the container and all associated entries.
Author:
M.Frank
Version:
1.0
Definition at line 195 of file Conditions.h.
Member Typedef Documentation
typedef Condition::iov_type DD4hep::Conditions::Container::iov_type
Forward definition of the iov type.
Definition at line 202 of file Conditions.h.
typedef Condition::key_type DD4hep::Conditions::Container::key_type
Forward definition of the key type.
Definition at line 200 of file Conditions.h.
typedef Interna::ConditionContainer DD4hep::Conditions::Container::Object
Standard object type.
Definition at line 198 of file Conditions.h.
Constructor & Destructor Documentation
DD4hep::Conditions::Container::Container ()
Default constructor.
DD4hep::Conditions::Container::Container (const Container & c)
Constructor to be used when reading the already parsed object.
template<typename Q > DD4hep::Conditions::Container::Container (const Handle< Q > & e) [inline]
Constructor to be used when reading the already parsed object.
Definition at line 211 of file Conditions.h.
Member Function Documentation
Condition Container::get (key_type condition_key, const UserPool & iov)
Access to condition objects. Only conditions in the pool are accessed.
Access to condition objects.
Definition at line 220 of file Conditions.cpp.
References DD4hep::Conditions::Interna::ConditionContainer::get(), DD4hep::Handle< T >::isValid(), and DD4hep::Handle< Interna::ConditionContainer >::ptr().
Condition DD4hep::Conditions::Container::get (const std::string & condition_key, const UserPool & iov)
Access to condition objects. Only conditions in the pool are accessed.
Condition Container::get (key_type condition_key, const iov_type & iov)
Access to condition objects directly by their hash key.
Access to condition objects.
Definition at line 192 of file Conditions.cpp.
References DD4hep::Conditions::Interna::ConditionContainer::get(), DD4hep::Handle< T >::isValid(), and DD4hep::Handle< Interna::ConditionContainer >::ptr().
Condition DD4hep::Conditions::Container::get (const std::string & condition_key, const iov_type & iov)
Access to condition objects by key and IOV.
Referenced by DD4hep::Conditions::DetConditions::get().
size_t Container::numKeys () const
Access the number of conditons keys available for this detector element.
Definition at line 169 of file Conditions.cpp.
References DD4hep::Conditions::Interna::ConditionContainer::keys, and DD4hep::Handle< Interna::ConditionContainer >::ptr().
Referenced by DD4hep::Conditions::Test::TestEnv::dump_detector_element().
Container& DD4hep::Conditions::Container::operator= (const Container & c)
Assignment operator.
Reimplemented from DD4hep::Handle< Interna::ConditionContainer >.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Conditions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Conditions.cpp