DD4hep: DD4hep::PopupMenu Class Reference
DD4hep::PopupMenu Class Reference
class PopupMenu PopupMenu.h DDEve/PopupMenu.h
#include <PopupMenu.h>
Public Types
typedef std::map< int, Callback > Callbacks
Public Member Functions
PopupMenu (const TGWindow *parent)
Standard constructor.
virtual ~PopupMenu ()
Default destructor.
void HandleMenu (int id)
Handle menu items.
TGPopupMenu & menu ()
Access to implementation.
virtual void Build (TGMenuBar *bar, int hints=kLHintsNormal)
Add the menu to the menu bar.
virtual void AddSeparator (TGMenuEntry *before=0)
Add a menu separator to the menu.
virtual void AddLabel (const char *s, const TGPicture *p=0, TGMenuEntry *before=0)
Add a menu label to the menu.
virtual void AddPopup (const char *s, TGPopupMenu *popup, TGMenuEntry *before=0, const TGPicture *p=0)
Add a (cascading) popup menu to a popup menu.
virtual int AddEntry (const char *name, Callback cb, void *ud=0, const TGPicture *p=0, TGMenuEntry *before=0)
Add a new popup menu entry with a callback.
template<typename T >
int AddEntry (const char *name, T *ptr, void(T::*pmf)(TGMenuEntry *, void *), void *ud=0, const TGPicture *p=0, TGMenuEntry *before=0)
Add a new popup menu entry with a callback.
void CheckEntry (int id)
Check menu entry.
void UnCheckEntry (int id)
Uncheck menu entry.
bool IsEntryChecked (int id)
Get check-value.
TGPopupMenu * operator-> ()
Public access to the popup menu using '->'.
operator TGPopupMenu * ()
Public access to the popup menu using '->'.
ClassDef (PopupMenu, 0)
Protected Attributes
Callbacks m_calls
Callback map.
TGPopupMenu m_popup
int m_cmd
Detailed Description
class PopupMenu PopupMenu.h DDEve/PopupMenu.h
Definition at line 37 of file PopupMenu.h.
Member Typedef Documentation
Callbacks
typedef std::map<int,Callback> DD4hep::PopupMenu::Callbacks
Definition at line 39 of file PopupMenu.h.
Constructor & Destructor Documentation
PopupMenu()
DD4hep::PopupMenu::PopupMenu (const TGWindow * parent)
Standard constructor.
~PopupMenu()
PopupMenu::~PopupMenu () virtual
Default destructor.
Definition at line 35 of file PopupMenu.cpp.
References DD4hep::InstanceCount::decrement(), m_calls, and m_popup.
Member Function Documentation
AddEntry() [1/2]
int PopupMenu::AddEntry (const char * name, Callback cb, void * ud = 0, const TGPicture * p = 0, TGMenuEntry * before = 0) virtual
Add a new popup menu entry with a callback.
Definition at line 61 of file PopupMenu.cpp.
References m_calls, m_cmd, and m_popup.
Referenced by AddEntry(), DD4hep::ViewMenu::Build(), DD4hep::DD4hepMenu::Build(), and menu().
AddEntry() [2/2]
template<typename T > int DD4hep::PopupMenu::AddEntry (const char * name, T * ptr, void(T::*)(TGMenuEntry *, void *) pmf, void * ud = 0, const TGPicture * p = 0, TGMenuEntry * before = 0) inline
Add a new popup menu entry with a callback.
Definition at line 69 of file PopupMenu.h.
References AddEntry(), CheckEntry(), IsEntryChecked(), and UnCheckEntry().
AddLabel()
void PopupMenu::AddLabel (const char * s, const TGPicture * p = 0, TGMenuEntry * before = 0) virtual
Add a menu label to the menu.
Definition at line 51 of file PopupMenu.cpp.
References m_popup.
Referenced by menu().
AddPopup()
void PopupMenu::AddPopup (const char * s, TGPopupMenu * popup, TGMenuEntry * before = 0, const TGPicture * p = 0) virtual
Add a (cascading) popup menu to a popup menu.
Definition at line 56 of file PopupMenu.cpp.
References m_popup.
Referenced by menu().
AddSeparator()
void PopupMenu::AddSeparator (TGMenuEntry * before = 0) virtual
Add a menu separator to the menu.
Definition at line 46 of file PopupMenu.cpp.
References m_popup.
Referenced by menu().
Build()
void PopupMenu::Build (TGMenuBar * bar, int hints = kLHintsNormal) virtual
Add the menu to the menu bar.
Reimplemented in DD4hep::DD4hepMenu, and DD4hep::ViewMenu.
Definition at line 42 of file PopupMenu.cpp.
Referenced by DD4hep::Display::AddMenu(), and menu().
CheckEntry()
void PopupMenu::CheckEntry (int id)
Check menu entry.
Definition at line 82 of file PopupMenu.cpp.
References m_popup.
Referenced by AddEntry().
ClassDef()
DD4hep::PopupMenu::ClassDef (PopupMenu , 0)
Referenced by operator TGPopupMenu *().
HandleMenu()
void PopupMenu::HandleMenu (int id)
Handle menu items.
Definition at line 68 of file PopupMenu.cpp.
References e, DD4hep::INFO, m_calls, m_popup, and DD4hep::printout().
IsEntryChecked()
bool PopupMenu::IsEntryChecked (int id)
Get check-value.
Definition at line 92 of file PopupMenu.cpp.
References m_popup.
Referenced by AddEntry().
menu()
TGPopupMenu& DD4hep::PopupMenu::menu () inline
Access to implementation.
Definition at line 54 of file PopupMenu.h.
References AddEntry(), AddLabel(), AddPopup(), AddSeparator(), dd4hep::bar, Build(), m_popup, and s.
Referenced by DD4hep::DD4hepMenu::Build().
operator TGPopupMenu *()
DD4hep::PopupMenu::operator TGPopupMenu * () inline
Public access to the popup menu using '->'.
Definition at line 82 of file PopupMenu.h.
References ClassDef(), and m_popup.
operator->()
TGPopupMenu* DD4hep::PopupMenu::operator-> () inline
Public access to the popup menu using '->'.
Definition at line 80 of file PopupMenu.h.
References m_popup.
UnCheckEntry()
void PopupMenu::UnCheckEntry (int id)
Uncheck menu entry.
Definition at line 87 of file PopupMenu.cpp.
References m_popup.
Referenced by AddEntry().
Member Data Documentation
m_calls
Callbacks DD4hep::PopupMenu::m_calls protected
Callback map.
Definition at line 42 of file PopupMenu.h.
Referenced by AddEntry(), HandleMenu(), and ~PopupMenu().
m_cmd
int DD4hep::PopupMenu::m_cmd protected
Definition at line 44 of file PopupMenu.h.
Referenced by AddEntry().
m_popup
TGPopupMenu DD4hep::PopupMenu::m_popup protected
Definition at line 43 of file PopupMenu.h.
Referenced by AddEntry(), AddLabel(), AddPopup(), AddSeparator(), CheckEntry(), HandleMenu(), IsEntryChecked(), menu(), operator TGPopupMenu *(), operator->(), UnCheckEntry(), and ~PopupMenu().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/PopupMenu.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/PopupMenu.cpp