DD4hep: DD4hep: DD4hep::DDRec::VolSurfaceBase Class Reference
DD4hep::DDRec::VolSurfaceBase Class Reference
#include <Surface.h>
Public Member Functions
virtual ~VolSurfaceBase ()
VolSurfaceBase ()
default c'tor
VolSurfaceBase (SurfaceType typ, double thickness_inner, double thickness_outer, Vector3D u_val, Vector3D v_val, Vector3D n, Vector3D o, Geometry::Volume vol, int identifier)
VolSurfaceBase (const VolSurfaceBase &c)
Copy the from object.
Geometry::Volume volume () const
the volume to which this surface is attached.
virtual long64 id () const
The id of this surface.
virtual const SurfaceType & type () const
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
Access to the normal direction at the given point.
virtual const Vector3D & origin () const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double innerThickness () const
virtual double outerThickness () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual double distance (const Vector3D &point) const
virtual bool insideBounds (const Vector3D &point, double epsilon=1e-4) const
Checks if the given point lies within the surface.
virtual std::vector< std::pair
< Vector3D, Vector3D > > getLines (unsigned nMax=100)
void setInnerMaterial (const IMaterial &mat)
set the inner Material
void setOuterMaterial (const IMaterial &mat)
set the outer Materal
Protected Member Functions
virtual void setU (const Vector3D &u)
setter for daughter classes
virtual void setV (const Vector3D &v)
setter for daughter classes
virtual void setNormal (const Vector3D &n)
setter for daughter classes
virtual void setOrigin (const Vector3D &o)
setter for daughter classes
Protected Attributes
SurfaceType _type
Vector3D _u
Vector3D _v
Vector3D _n
Vector3D _o
double _th_i
double _th_o
MaterialData _innerMat
MaterialData _outerMat
Geometry::Volume _vol
long64 _id
unsigned _refCount
Friends
class VolSurface
Detailed Description
Implementation of ISurface for a local surface attached to a volume. Provides default implementations for all methods but distance(). Subclasses for specific surfaces overwrite methods as needed.
Author:
F.Gaede, DESY
Date:
Sep 11, 2015
Version:
$Id$
Definition at line 32 of file Surface.h.
Constructor & Destructor Documentation
virtual DD4hep::DDRec::VolSurfaceBase::~VolSurfaceBase () [inline, virtual]
Definition at line 61 of file Surface.h.
DD4hep::DDRec::VolSurfaceBase::VolSurfaceBase () [inline]
default c'tor
Definition at line 65 of file Surface.h.
DD4hep::DDRec::VolSurfaceBase::VolSurfaceBase (SurfaceType typ, double thickness_inner, double thickness_outer, Vector3D u_val, Vector3D v_val, Vector3D n, Vector3D o, Geometry::Volume vol, int identifier) [inline]
Definition at line 80 of file Surface.h.
DD4hep::DDRec::VolSurfaceBase::VolSurfaceBase (const VolSurfaceBase & c) [inline]
Copy the from object.
Definition at line 99 of file Surface.h.
References _id, _innerMat, _n, _o, _outerMat, _refCount, _th_i, _th_o, _type, _u, _v, and _vol.
Member Function Documentation
double DD4hep::DDRec::VolSurfaceBase::distance (const Vector3D & point) const [virtual]
Distance to surface
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::VolPlaneImpl, DD4hep::DDRec::VolCylinderImpl, and DD4hep::DDRec::VolConeImpl.
Definition at line 193 of file Surface.cpp.
References DDSurfaces::Vector3D::x().
Referenced by DD4hep::DDRec::VolSurface::distance(), and insideBounds().
std::vector< std::pair< Vector3D, Vector3D > > DD4hep::DDRec::VolSurfaceBase::getLines (unsigned nMax = 100) [virtual]
Reimplemented in DD4hep::DDRec::VolConeImpl.
Definition at line 218 of file Surface.cpp.
Referenced by DD4hep::DDRec::VolSurface::getLines().
Vector2D DD4hep::DDRec::VolSurfaceBase::globalToLocal (const Vector3D & point) const [virtual]
Convert the global position to the local position (u,v) on the surface
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::VolCylinderImpl, and DD4hep::DDRec::VolConeImpl.
Definition at line 38 of file Surface.cpp.
References origin(), u(), and v().
Referenced by DD4hep::DDRec::VolSurface::globalToLocal().
long64 DD4hep::DDRec::VolSurfaceBase::id () const [virtual]
The id of this surface.
Implements DDSurfaces::ISurface.
Definition at line 30 of file Surface.cpp.
References _id.
Referenced by DD4hep::DDRec::VolSurface::id().
const IMaterial & DD4hep::DDRec::VolSurfaceBase::innerMaterial () const [virtual]
Access to the material in opposite direction of the normal.
Implements DDSurfaces::ISurface.
Definition at line 61 of file Surface.cpp.
References _innerMat.
Referenced by DD4hep::DDRec::VolSurface::innerMaterial().
double DD4hep::DDRec::VolSurfaceBase::innerThickness () const [virtual]
Thickness of inner material
Implements DDSurfaces::ISurface.
Definition at line 63 of file Surface.cpp.
References _th_i.
Referenced by DD4hep::DDRec::VolSurface::innerThickness().
bool DD4hep::DDRec::VolSurfaceBase::insideBounds (const Vector3D & point, double epsilon = 1e-4) const [virtual]
Checks if the given point lies within the surface.
Implements DDSurfaces::ISurface.
Definition at line 196 of file Surface.cpp.
References DDSurfaces::Vector3D::const_array(), distance(), normal(), origin(), and volume().
Referenced by DD4hep::DDRec::VolSurface::insideBounds().
double DD4hep::DDRec::VolSurfaceBase::length_along_u () const [virtual]
The length of the surface along direction u at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implements DDSurfaces::ISurface.
Definition at line 67 of file Surface.cpp.
References DDSurfaces::Vector3D::array(), DDSurfaces::Vector3D::const_array(), origin(), u(), dd4hep::um, and volume().
Referenced by DD4hep::DDRec::VolSurface::length_along_u().
double DD4hep::DDRec::VolSurfaceBase::length_along_v () const [virtual]
The length of the surface along direction v at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implements DDSurfaces::ISurface.
Definition at line 130 of file Surface.cpp.
References DDSurfaces::Vector3D::array(), DDSurfaces::Vector3D::const_array(), origin(), v(), and volume().
Referenced by DD4hep::DDRec::VolConeImpl::getLines(), and DD4hep::DDRec::VolSurface::length_along_v().
Vector3D DD4hep::DDRec::VolSurfaceBase::localToGlobal (const Vector2D & point) const [virtual]
Convert the local position (u,v) on the surface to the global position
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::VolCylinderImpl, and DD4hep::DDRec::VolConeImpl.
Definition at line 54 of file Surface.cpp.
References dd4hep::g, origin(), u(), and v().
Referenced by DD4hep::DDRec::VolSurface::localToGlobal().
Vector3D DD4hep::DDRec::VolSurfaceBase::normal (const Vector3D & point = Vector3D()) const [virtual]
Access to the normal direction at the given point.
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::VolCylinderImpl, and DD4hep::DDRec::VolConeImpl.
Definition at line 35 of file Surface.cpp.
References _n, and DDSurfaces::Vector3D::x().
Referenced by DD4hep::DDRec::VolPlaneImpl::distance(), insideBounds(), and DD4hep::DDRec::VolSurface::normal().
const Vector3D & DD4hep::DDRec::VolSurfaceBase::origin () const [virtual]
Get Origin of local coordinate system on surface
Implements DDSurfaces::ISurface.
Definition at line 36 of file Surface.cpp.
References _o.
Referenced by DD4hep::DDRec::VolCylinderImpl::distance(), DD4hep::DDRec::VolPlaneImpl::distance(), DD4hep::DDRec::VolConeImpl::getLines(), DD4hep::DDRec::VolConeImpl::globalToLocal(), DD4hep::DDRec::VolCylinderImpl::globalToLocal(), globalToLocal(), insideBounds(), length_along_u(), length_along_v(), DD4hep::DDRec::VolConeImpl::localToGlobal(), DD4hep::DDRec::VolCylinderImpl::localToGlobal(), localToGlobal(), and DD4hep::DDRec::VolSurface::origin().
const IMaterial & DD4hep::DDRec::VolSurfaceBase::outerMaterial () const [virtual]
Access to the material in direction of the normal.
Implements DDSurfaces::ISurface.
Definition at line 62 of file Surface.cpp.
References _outerMat.
Referenced by DD4hep::DDRec::VolSurface::outerMaterial().
double DD4hep::DDRec::VolSurfaceBase::outerThickness () const [virtual]
Thickness of outer material
Implements DDSurfaces::ISurface.
Definition at line 64 of file Surface.cpp.
References _th_o.
Referenced by DD4hep::DDRec::VolSurface::outerThickness().
void DD4hep::DDRec::VolSurfaceBase::setInnerMaterial (const IMaterial & mat) [inline]
set the inner Material
Definition at line 180 of file Surface.h.
References _innerMat.
Referenced by DD4hep::DDRec::VolSurface::setInnerMaterial().
void DD4hep::DDRec::VolSurfaceBase::setNormal (const Vector3D & n) [protected, virtual]
setter for daughter classes
Definition at line 27 of file Surface.cpp.
References _n.
Referenced by DD4hep::DDRec::VolConeImpl::VolConeImpl(), and DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
void DD4hep::DDRec::VolSurfaceBase::setOrigin (const Vector3D & o) [protected, virtual]
setter for daughter classes
Definition at line 28 of file Surface.cpp.
References _o.
Referenced by DD4hep::DDRec::VolConeImpl::VolConeImpl().
void DD4hep::DDRec::VolSurfaceBase::setOuterMaterial (const IMaterial & mat) [inline]
set the outer Materal
Definition at line 183 of file Surface.h.
References _outerMat.
Referenced by DD4hep::DDRec::VolSurface::setOuterMaterial().
void DD4hep::DDRec::VolSurfaceBase::setU (const Vector3D & u) [protected, virtual]
setter for daughter classes
Definition at line 25 of file Surface.cpp.
References _u.
Referenced by DD4hep::DDRec::VolConeImpl::VolConeImpl(), and DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
void DD4hep::DDRec::VolSurfaceBase::setV (const Vector3D & v) [protected, virtual]
setter for daughter classes
Definition at line 26 of file Surface.cpp.
References _v.
Referenced by DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
const SurfaceType & DD4hep::DDRec::VolSurfaceBase::type () const [virtual]
properties of the surface encoded in Type.
See also:
SurfaceType
Implements DDSurfaces::ISurface.
Definition at line 32 of file Surface.cpp.
References _type.
Referenced by DD4hep::DDRec::VolSurface::type().
Vector3D DD4hep::DDRec::VolSurfaceBase::u (const Vector3D & point = Vector3D()) const [virtual]
First direction of measurement U
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::VolCylinderImpl, and DD4hep::DDRec::VolConeImpl.
Definition at line 33 of file Surface.cpp.
References _u, and DDSurfaces::Vector3D::x().
Referenced by globalToLocal(), length_along_u(), localToGlobal(), and DD4hep::DDRec::VolSurface::u().
Vector3D DD4hep::DDRec::VolSurfaceBase::v (const Vector3D & point = Vector3D()) const [virtual]
Second direction of measurement V
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::VolConeImpl.
Definition at line 34 of file Surface.cpp.
References _v, and DDSurfaces::Vector3D::x().
Referenced by globalToLocal(), length_along_v(), localToGlobal(), DD4hep::DDRec::VolCylinderImpl::u(), and DD4hep::DDRec::VolSurface::v().
Geometry::Volume DD4hep::DDRec::VolSurfaceBase::volume () const [inline]
the volume to which this surface is attached.
Definition at line 116 of file Surface.h.
References _vol.
Referenced by insideBounds(), length_along_u(), length_along_v(), and DD4hep::DDRec::VolSurface::volume().
Friends And Related Function Documentation
friend class VolSurface [friend]
Definition at line 34 of file Surface.h.
Member Data Documentation
long64 DD4hep::DDRec::VolSurfaceBase::_id [protected]
Definition at line 47 of file Surface.h.
Referenced by id(), and VolSurfaceBase().
MaterialData DD4hep::DDRec::VolSurfaceBase::_innerMat [protected]
Definition at line 44 of file Surface.h.
Referenced by innerMaterial(), setInnerMaterial(), and VolSurfaceBase().
Vector3D DD4hep::DDRec::VolSurfaceBase::_n [protected]
Definition at line 40 of file Surface.h.
Referenced by DD4hep::DDRec::VolConeImpl::normal(), normal(), setNormal(), and VolSurfaceBase().
Vector3D DD4hep::DDRec::VolSurfaceBase::_o [protected]
Definition at line 41 of file Surface.h.
Referenced by origin(), setOrigin(), and VolSurfaceBase().
MaterialData DD4hep::DDRec::VolSurfaceBase::_outerMat [protected]
Definition at line 45 of file Surface.h.
Referenced by outerMaterial(), setOuterMaterial(), and VolSurfaceBase().
unsigned DD4hep::DDRec::VolSurfaceBase::_refCount [protected]
Definition at line 48 of file Surface.h.
Referenced by DD4hep::DDRec::VolSurface::operator=(), DD4hep::DDRec::VolSurface::VolSurface(), VolSurfaceBase(), and DD4hep::DDRec::VolSurface::~VolSurface().
double DD4hep::DDRec::VolSurfaceBase::_th_i [protected]
Definition at line 42 of file Surface.h.
Referenced by innerThickness(), and VolSurfaceBase().
double DD4hep::DDRec::VolSurfaceBase::_th_o [protected]
Definition at line 43 of file Surface.h.
Referenced by outerThickness(), and VolSurfaceBase().
SurfaceType DD4hep::DDRec::VolSurfaceBase::_type [protected]
Definition at line 37 of file Surface.h.
Referenced by type(), DD4hep::DDRec::VolConeImpl::VolConeImpl(), DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl(), DD4hep::DDRec::VolPlaneImpl::VolPlaneImpl(), and VolSurfaceBase().
Vector3D DD4hep::DDRec::VolSurfaceBase::_u [protected]
Definition at line 38 of file Surface.h.
Referenced by setU(), u(), and VolSurfaceBase().
Vector3D DD4hep::DDRec::VolSurfaceBase::_v [protected]
Definition at line 39 of file Surface.h.
Referenced by DD4hep::DDRec::VolConeImpl::distance(), DD4hep::DDRec::VolConeImpl::globalToLocal(), DD4hep::DDRec::VolConeImpl::localToGlobal(), setV(), DD4hep::DDRec::VolConeImpl::v(), v(), and VolSurfaceBase().
Geometry::Volume DD4hep::DDRec::VolSurfaceBase::_vol [protected]
Definition at line 46 of file Surface.h.
Referenced by VolSurfaceBase(), and volume().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp