DD4hep: DD4hep::BasicGrammar Class Reference
DD4hep::BasicGrammar Class Reference abstract
DD4hep classes and objects
Base class describing string evaluation to C++ objects using boost::spirit.
#include <BasicGrammar.h>
Public Member Functions
BasicGrammar ()
Default constructor.
virtual ~BasicGrammar ()
Default destructor.
virtual const std::type_info & type () const =0
Access to the type information.
virtual const std::string & type_name () const =0
Access to the type information name.
virtual size_t sizeOf () const =0
Access the object size (sizeof operator)
virtual std::string str (const void *ptr) const =0
Serialize an opaque value to a string.
virtual bool fromString (void *ptr, const std::string &value) const =0
Set value from serialized string. On successful data conversion TRUE is returned.
Static Public Member Functions
template<typename TYPE >
static const BasicGrammar & instance ()
Instance factory.
static void invalidConversion (const std::type_info &from, const std::type_info &to)
Error callback on invalid conversion.
static void invalidConversion (const std::string &value, const std::type_info &to)
Error callback on invalid conversion.
Detailed Description
Base class describing string evaluation to C++ objects using boost::spirit.
Grammar object handle the boost::spirit conversion between strings and numeric values/objects. Numeric objects could be atomic (int, long, float, double, etc) or complex (vector<int>, vector<float>...). This way e.g. a vector<int> may be converted into a list<double>. The conversion though requires an intermediate string representation. For this reason the conversion mechanism is relatively slow and hence should not be used inside number-crunching algorithms.
Author
M.Frank
Version
1.0
Date
13.08.2013
Definition at line 37 of file BasicGrammar.h.
Constructor & Destructor Documentation
BasicGrammar()
DD4hep::BasicGrammar::BasicGrammar ()
Default constructor.
Definition at line 24 of file BasicGrammar.cpp.
~BasicGrammar()
DD4hep::BasicGrammar::~BasicGrammar () virtual
Default destructor.
Definition at line 28 of file BasicGrammar.cpp.
Member Function Documentation
fromString()
virtual bool DD4hep::BasicGrammar::fromString (void * ptr, const std::string & value) const pure virtual
Set value from serialized string. On successful data conversion TRUE is returned.
Implemented in DD4hep::Grammar< TYPE >.
Referenced by DD4hep::eval_pair(), DD4hep::fill_data(), DD4hep::OpaqueData::fromString(), and DD4hep::PropertyGrammar::fromString().
instance()
template<typename TYPE > static const BasicGrammar& DD4hep::BasicGrammar::instance () static
Instance factory.
invalidConversion() [1/2]
void DD4hep::BasicGrammar::invalidConversion (const std::type_info & from, const std::type_info & to) static
Error callback on invalid conversion.
Definition at line 40 of file BasicGrammar.cpp.
References DD4hep::typeName().
Referenced by DD4hep::Grammar< TYPE >::fromString(), and DD4hep::PropertyGrammar::invalidConversion().
invalidConversion() [2/2]
void DD4hep::BasicGrammar::invalidConversion (const std::string & value, const std::type_info & to) static
Error callback on invalid conversion.
Definition at line 32 of file BasicGrammar.cpp.
References DD4hep::typeName().
sizeOf()
virtual size_t DD4hep::BasicGrammar::sizeOf () const pure virtual
Access the object size (sizeof operator)
Implemented in DD4hep::Grammar< TYPE >.
Referenced by DD4hep::OpaqueDataBlock::bind().
str()
virtual std::string DD4hep::BasicGrammar::str (const void * ptr) const pure virtual
Serialize an opaque value to a string.
Implemented in DD4hep::Grammar< TYPE >.
Referenced by DD4hep::OpaqueData::str(), and DD4hep::PropertyGrammar::str().
type()
virtual const std::type_info& DD4hep::BasicGrammar::type () const pure virtual
Access to the type information.
Implemented in DD4hep::Grammar< TYPE >.
Referenced by DD4hep::OpaqueDataBlock::assign(), DD4hep::OpaqueDataBlock::bind(), DD4hep::OpaqueData::get(), DD4hep::PropertyGrammar::type(), DD4hep::OpaqueData::typeInfo(), and DD4hep::Conditions::Condition::typeInfo().
type_name()
virtual const std::string& DD4hep::BasicGrammar::type_name () const pure virtual
Access to the type information name.
Implemented in DD4hep::Grammar< TYPE >.
Referenced by DD4hep::OpaqueData::dataType().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/BasicGrammar.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/BasicGrammar.cpp