DD4hep: DD4hep::Alignments::AlignmentOperator Class Reference
DD4hep::Alignments::AlignmentOperator Class Reference
DDAlign: DD4hep Detector geometry alignment components.
Base class for alignment functors.
#include <AlignmentOperators.h>
Public Types
typedef AlignmentStack::StackEntry Entry
typedef GlobalAlignmentCache::Cache Cache
typedef std::vector< Entry * > Entries
typedef std::map< std::string, std::pair< TGeoPhysicalNode *, Entry * > > Nodes
Public Member Functions
AlignmentOperator (GlobalAlignmentCache &c, Nodes &n)
Initializing functor constructor.
void insert (GlobalAlignment alignment) const
Insert alignment entry.
Public Attributes
GlobalAlignmentCache & cache
Nodes & nodes
Detailed Description
Base class for alignment functors.
Author
M.Frank
Version
1.0
Definition at line 34 of file AlignmentOperators.h.
Member Typedef Documentation
Cache
typedef GlobalAlignmentCache::Cache DD4hep::Alignments::AlignmentOperator::Cache
Definition at line 37 of file AlignmentOperators.h.
Entries
typedef std::vector<Entry*> DD4hep::Alignments::AlignmentOperator::Entries
Definition at line 38 of file AlignmentOperators.h.
Entry
typedef AlignmentStack::StackEntry DD4hep::Alignments::AlignmentOperator::Entry
Definition at line 36 of file AlignmentOperators.h.
Nodes
typedef std::map<std::string,std::pair<TGeoPhysicalNode*,Entry*> > DD4hep::Alignments::AlignmentOperator::Nodes
Definition at line 39 of file AlignmentOperators.h.
Constructor & Destructor Documentation
AlignmentOperator()
DD4hep::Alignments::AlignmentOperator::AlignmentOperator (GlobalAlignmentCache & c, Nodes & n) inline
Initializing functor constructor.
Definition at line 44 of file AlignmentOperators.h.
References insert().
Member Function Documentation
insert()
void AlignmentOperator::insert (GlobalAlignment alignment) const
Insert alignment entry.
Definition at line 29 of file AlignmentOperators.cpp.
References DD4hep::Alignments::GlobalDetectorAlignment::align(), DD4hep::ALWAYS, DD4hep::Alignments::Delta::checkFlag(), DD4hep::Alignments::AlignmentStack::StackEntry::checkOverlap(), DD4hep::Alignments::AlignmentStack::StackEntry::delta, DD4hep::Alignments::AlignmentStack::StackEntry::detector, e, DD4hep::except(), DD4hep::Alignments::AlignmentStack::StackEntry::hasMatrix(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), dd4hep::mm, DD4hep::Alignments::AlignmentStack::StackEntry::needsReset(), DD4hep::Alignments::AlignmentStack::StackEntry::overlap, DD4hep::Alignments::AlignmentStack::StackEntry::overlapDefined(), DD4hep::Alignments::AlignmentStack::StackEntry::overlapValue(), DD4hep::Alignments::AlignmentStack::StackEntry::path, DD4hep::Alignments::Delta::pivot, DD4hep::Geometry::DetElement::placementPath(), DD4hep::printout(), DD4hep::Handle< T >::ptr(), DD4hep::Alignments::Delta::rotation, DD4hep::Alignments::Delta::translation, DD4hep::WARNING, and DD4hep::yes_no().
Referenced by AlignmentOperator().
Member Data Documentation
cache
GlobalAlignmentCache& DD4hep::Alignments::AlignmentOperator::cache
Definition at line 40 of file AlignmentOperators.h.
nodes
Nodes& DD4hep::Alignments::AlignmentOperator::nodes
Definition at line 41 of file AlignmentOperators.h.
Referenced by DD4hep::Alignments::AlignmentSelector::reset().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/AlignmentOperators.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentOperators.cpp