DD4hep: DD4hep: DD4hep::Geometry::PolyhedraRegular Class Reference
DD4hep::Geometry::PolyhedraRegular Class Reference
[DD4hep::Geometry components, classes and objects]
Class describing a regular polyhedron shape.
#include <Shapes.h>
Public Member Functions
PolyhedraRegular ()
Default constructor.
PolyhedraRegular (const PolyhedraRegular &e)
Constructor to be used when passing an already created object.
template<typename Q >
PolyhedraRegular (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
PolyhedraRegular (const Handle< Q > &e)
Constructor to be used when passing an already created object.
PolyhedraRegular (int nsides, double rmin, double rmax, double zlen)
Constructor to create a new object. Phi(start)=0, deltaPhi=2PI, Z-planes at -zlen/2 and +zlen/2.
PolyhedraRegular (int nsides, double rmin, double rmax, double zplanes[2])
Constructor to create a new object. Phi(start)=0, deltaPhi=2PI, Z-planes a zplanes[0] and zplanes[1].
PolyhedraRegular (int nsides, double phi_start, double rmin, double rmax, double zlen)
Constructor to create a new object with phi_start, deltaPhi=2PI, Z-planes at -zlen/2 and +zlen/2.
PolyhedraRegular & operator= (const PolyhedraRegular &copy)
Assignment operator.
Protected Member Functions
void _create (int nsides, double rmin, double rmax, double zpos, double zneg, double start, double delta)
Helper function to create the polyhedron.
Detailed Description
Class describing a regular polyhedron shape.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoPgon.html
Author:
M.Frank
Version:
1.0
Definition at line 589 of file Shapes.h.
Constructor & Destructor Documentation
DD4hep::Geometry::PolyhedraRegular::PolyhedraRegular ()
Default constructor.
DD4hep::Geometry::PolyhedraRegular::PolyhedraRegular (const PolyhedraRegular & e)
Constructor to be used when passing an already created object.
template<typename Q > DD4hep::Geometry::PolyhedraRegular::PolyhedraRegular (const Q * p) [inline]
Constructor to be used with an existing object.
Definition at line 599 of file Shapes.h.
template<typename Q > DD4hep::Geometry::PolyhedraRegular::PolyhedraRegular (const Handle< Q > & e) [inline]
Constructor to be used when passing an already created object.
Definition at line 601 of file Shapes.h.
PolyhedraRegular::PolyhedraRegular (int nsides, double rmin, double rmax, double zlen)
Constructor to create a new object. Phi(start)=0, deltaPhi=2PI, Z-planes at -zlen/2 and +zlen/2.
Constructor to be used when creating a new object.
Definition at line 414 of file Shapes.cpp.
References _create().
PolyhedraRegular::PolyhedraRegular (int nsides, double rmin, double rmax, double zplanes[2])
Constructor to create a new object. Phi(start)=0, deltaPhi=2PI, Z-planes a zplanes[0] and zplanes[1].
Constructor to be used when creating a new object.
Definition at line 424 of file Shapes.cpp.
References _create().
PolyhedraRegular::PolyhedraRegular (int nsides, double phi_start, double rmin, double rmax, double zlen)
Constructor to create a new object with phi_start, deltaPhi=2PI, Z-planes at -zlen/2 and +zlen/2.
Constructor to be used when creating a new object.
Definition at line 419 of file Shapes.cpp.
References _create(), and dd4hep::deg.
Member Function Documentation
void PolyhedraRegular::_create (int nsides, double rmin, double rmax, double zpos, double zneg, double start, double delta) [protected]
Helper function to create the polyhedron.
Helper function to create holy hedron.
Definition at line 403 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoPgon >::_assign(), DD4hep::Geometry::Solid_type< TGeoPgon >::_setDimensions(), and DD4hep::Geometry::_toString().
Referenced by PolyhedraRegular().
PolyhedraRegular& DD4hep::Geometry::PolyhedraRegular::operator= (const PolyhedraRegular & copy)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp