DD4hep: DD4hep::DDRec::Surface Class Reference
DD4hep::DDRec::Surface Class Reference
#include <Surface.h>
Public Member Functions
virtual ~Surface ()
Surface (Geometry::DetElement det, VolSurface volSurf)
virtual long64 id () const
The id of this surface - corresponds to DetElement id.
virtual const SurfaceType & type () const
Geometry::Volume volume () const
The volume that has the surface attached.
VolSurface volSurface () const
The VolSurface attched to the volume.
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
Access to the normal direction at the given point.
virtual const Vector3D & origin () const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
virtual double innerThickness () const
virtual double outerThickness () const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double distance (const Vector3D &point) const
virtual bool insideBounds (const Vector3D &point, double epsilon=1.e-4) const
Checks if the given point lies within the surface.
virtual Vector3D volumeOrigin () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual std::vector< std::pair< Vector3D, Vector3D > > getLines (unsigned nMax=100)
Public Member Functions inherited from DDSurfaces::ISurface
virtual ~ISurface ()
Destructor.
Protected Member Functions
Surface ()
default c'tor
void initialize ()
Protected Attributes
Geometry::DetElement _det
VolSurface _volSurf
TGeoMatrix * _wtM
long64 _id
SurfaceType _type
Vector3D _u
Vector3D _v
Vector3D _n
Vector3D _o
Detailed Description
Implementation of Surface class holding a local surface attached to a volume and the DetElement holding this surface.
Author
F.Gaede, DESY
Date
Apr, 7 2014
Version
$Id$
Definition at line 511 of file Surface.h.
Constructor & Destructor Documentation
Surface() [1/2]
DD4hep::DDRec::Surface::Surface () inline protected
default c'tor
Definition at line 528 of file Surface.h.
~Surface()
virtual DD4hep::DDRec::Surface::~Surface () inline virtual
Definition at line 532 of file Surface.h.
Surface() [2/2]
DD4hep::DDRec::Surface::Surface (Geometry::DetElement det, VolSurface volSurf)
Standard c'tor initializes the surface from the parameters of the VolSurface and the transform (placement) of the corresponding volume, if found in DetElement
Definition at line 597 of file Surface.cpp.
References initialize().
Member Function Documentation
distance()
double DD4hep::DDRec::Surface::distance (const Vector3D & point) const virtual
Distance to surface
Implements DDSurfaces::ISurface.
Definition at line 693 of file Surface.cpp.
References _volSurf, _wtM, and DD4hep::DDRec::VolSurface::distance().
getLines()
std::vector< std::pair< Vector3D, Vector3D > > DD4hep::DDRec::Surface::getLines (unsigned nMax = 100) virtual
Get lines constraining the surface for drawing (might not be exact boundaries) - at most nMax lines are returned.
Definition at line 825 of file Surface.cpp.
References _o, _volSurf, _wtM, DDSurfaces::Vector3D::array(), DDSurfaces::Vector3D::const_array(), e, DDSurfaces::Vector3D::fill(), DD4hep::DDRec::VolSurface::getLines(), DDSurfaces::SurfaceType::isZDisk(), DD4hep::DDRec::VolSurface::normal(), DD4hep::DDRec::VolSurface::origin(), DDSurfaces::Vector3D::rho(), dd4hep::second, type(), DD4hep::DDRec::VolSurface::u(), volume(), DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().
globalToLocal()
Vector2D DD4hep::DDRec::Surface::globalToLocal (const Vector3D & point) const virtual
Convert the global position to the local position (u,v) on the surface
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::CylinderSurface.
Definition at line 657 of file Surface.cpp.
References origin(), u(), and v().
id()
long64 DD4hep::DDRec::Surface::id () const virtual
The id of this surface - corresponds to DetElement id.
Implements DDSurfaces::ISurface.
Definition at line 603 of file Surface.cpp.
References _id.
initialize()
void DD4hep::DDRec::Surface::initialize () protected
Definition at line 711 of file Surface.cpp.
References _det, _id, _n, _o, _type, _u, _v, _volSurf, _wtM, DDSurfaces::SurfaceType::checkOrthogonalToZ(), DDSurfaces::SurfaceType::checkParallelToZ(), DDSurfaces::Vector3D::fill(), DD4hep::DDRec::findVolume(), DD4hep::DDRec::VolSurface::id(), DDSurfaces::SurfaceType::isCone(), m, DD4hep::Handle< T >::name(), DD4hep::DDRec::VolSurface::normal(), DD4hep::DDRec::VolSurface::origin(), DD4hep::Geometry::DetElement::placement(), DD4hep::DDRec::VolSurface::u(), DD4hep::DDRec::VolSurface::v(), DD4hep::DDRec::VolSurface::volume(), DD4hep::Geometry::DetElement::volumeID(), and DD4hep::Geometry::DetElement::worldTransformation().
Referenced by Surface().
innerMaterial()
const IMaterial & DD4hep::DDRec::Surface::innerMaterial () const virtual
Access to the material in opposite direction of the normal.
Thickness of outer material
Implements DDSurfaces::ISurface.
Definition at line 618 of file Surface.cpp.
References _n, _o, _volSurf, DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::VolSurface::innerMaterial(), innerThickness(), DD4hep::DDRec::MaterialManager::materialsBetween(), DD4hep::DDRec::VolSurface::setInnerMaterial(), and DDSurfaces::IMaterial::Z().
innerThickness()
double DD4hep::DDRec::Surface::innerThickness () const virtual
Thickness of inner material
Implements DDSurfaces::ISurface.
Definition at line 611 of file Surface.cpp.
References _volSurf, and DD4hep::DDRec::VolSurface::innerThickness().
Referenced by innerMaterial().
insideBounds()
bool DD4hep::DDRec::Surface::insideBounds (const Vector3D & point, double epsilon = 1.e-4) const virtual
Checks if the given point lies within the surface.
Implements DDSurfaces::ISurface.
Definition at line 702 of file Surface.cpp.
References _volSurf, _wtM, and DD4hep::DDRec::VolSurface::insideBounds().
length_along_u()
double DD4hep::DDRec::Surface::length_along_u () const virtual
The length of the surface along direction u at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implements DDSurfaces::ISurface.
Definition at line 613 of file Surface.cpp.
References _volSurf, and DD4hep::DDRec::VolSurface::length_along_u().
length_along_v()
double DD4hep::DDRec::Surface::length_along_v () const virtual
The length of the surface along direction v at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implements DDSurfaces::ISurface.
Definition at line 614 of file Surface.cpp.
References _volSurf, and DD4hep::DDRec::VolSurface::length_along_v().
Referenced by DD4hep::DDRec::ConeSurface::radius0(), DD4hep::DDRec::ConeSurface::radius1(), DD4hep::DDRec::ConeSurface::z0(), and DD4hep::DDRec::ConeSurface::z1().
localToGlobal()
Vector3D DD4hep::DDRec::Surface::localToGlobal (const Vector2D & point) const virtual
Convert the local position (u,v) on the surface to the global position
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::CylinderSurface.
Definition at line 674 of file Surface.cpp.
References dd4hep::g, origin(), u(), and v().
normal()
Vector3D DD4hep::DDRec::Surface::normal (const Vector3D & point = Vector3D()) const virtual
Access to the normal direction at the given point.
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::CylinderSurface.
Definition at line 609 of file Surface.cpp.
References _n, and DDSurfaces::Vector3D::x().
origin()
const Vector3D & DD4hep::DDRec::Surface::origin () const virtual
Get Origin of local coordinate system on surface
Implements DDSurfaces::ISurface.
Definition at line 610 of file Surface.cpp.
References _o.
Referenced by globalToLocal(), localToGlobal(), DD4hep::DDRec::ConeSurface::radius0(), DD4hep::DDRec::ConeSurface::radius1(), DD4hep::DDRec::ConeSurface::z0(), and DD4hep::DDRec::ConeSurface::z1().
outerMaterial()
const IMaterial & DD4hep::DDRec::Surface::outerMaterial () const virtual
Access to the material in direction of the normal.
Implements DDSurfaces::ISurface.
Definition at line 637 of file Surface.cpp.
References _n, _o, _volSurf, DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::MaterialManager::materialsBetween(), DD4hep::DDRec::VolSurface::outerMaterial(), outerThickness(), DD4hep::DDRec::VolSurface::setOuterMaterial(), and DDSurfaces::IMaterial::Z().
outerThickness()
double DD4hep::DDRec::Surface::outerThickness () const virtual
Thickness of outer material
Implements DDSurfaces::ISurface.
Definition at line 612 of file Surface.cpp.
References _volSurf, and DD4hep::DDRec::VolSurface::outerThickness().
Referenced by outerMaterial().
type()
const SurfaceType & DD4hep::DDRec::Surface::type () const virtual
properties of the surface encoded in Type.
See also
SurfaceType
Implements DDSurfaces::ISurface.
Definition at line 605 of file Surface.cpp.
References _type.
Referenced by getLines().
u()
Vector3D DD4hep::DDRec::Surface::u (const Vector3D & point = Vector3D()) const virtual
First direction of measurement U
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::CylinderSurface.
Definition at line 607 of file Surface.cpp.
References _u, and DDSurfaces::Vector3D::x().
Referenced by globalToLocal(), and localToGlobal().
v()
Vector3D DD4hep::DDRec::Surface::v (const Vector3D & point = Vector3D()) const virtual
Second direction of measurement V
Implements DDSurfaces::ISurface.
Reimplemented in DD4hep::DDRec::CylinderSurface.
Definition at line 608 of file Surface.cpp.
References _v, and DDSurfaces::Vector3D::x().
Referenced by globalToLocal(), and localToGlobal().
volSurface()
VolSurface DD4hep::DDRec::Surface::volSurface () const inline
The VolSurface attched to the volume.
Definition at line 551 of file Surface.h.
References e, and v.
volume()
Geometry::Volume DD4hep::DDRec::Surface::volume () const inline
The volume that has the surface attached.
Definition at line 548 of file Surface.h.
References DD4hep::DDRec::VolSurface::volume().
Referenced by getLines().
volumeOrigin()
Vector3D DD4hep::DDRec::Surface::volumeOrigin () const virtual
Get Origin of local coordinate system of the associated volume
Definition at line 681 of file Surface.cpp.
References _wtM.
Referenced by DD4hep::DDRec::CylinderSurface::center(), and DD4hep::DDRec::ConeSurface::center().
Member Data Documentation
_det
Geometry::DetElement DD4hep::DDRec::Surface::_det protected
Definition at line 515 of file Surface.h.
Referenced by initialize().
_id
long64 DD4hep::DDRec::Surface::_id protected
Definition at line 519 of file Surface.h.
Referenced by id(), and initialize().
_n
Vector3D DD4hep::DDRec::Surface::_n protected
Definition at line 524 of file Surface.h.
Referenced by initialize(), innerMaterial(), normal(), and outerMaterial().
_o
Vector3D DD4hep::DDRec::Surface::_o protected
Definition at line 525 of file Surface.h.
Referenced by getLines(), initialize(), innerMaterial(), origin(), and outerMaterial().
_type
SurfaceType DD4hep::DDRec::Surface::_type protected
Definition at line 521 of file Surface.h.
Referenced by initialize(), and type().
_u
Vector3D DD4hep::DDRec::Surface::_u protected
Definition at line 522 of file Surface.h.
Referenced by initialize(), and u().
_v
Vector3D DD4hep::DDRec::Surface::_v protected
Definition at line 523 of file Surface.h.
Referenced by initialize(), and v().
_volSurf
VolSurface DD4hep::DDRec::Surface::_volSurf mutable protected
Definition at line 516 of file Surface.h.
Referenced by distance(), getLines(), DD4hep::DDRec::CylinderSurface::globalToLocal(), initialize(), innerMaterial(), innerThickness(), insideBounds(), length_along_u(), length_along_v(), DD4hep::DDRec::CylinderSurface::localToGlobal(), DD4hep::DDRec::CylinderSurface::normal(), outerMaterial(), outerThickness(), DD4hep::DDRec::CylinderSurface::radius(), DD4hep::DDRec::ConeSurface::radius0(), DD4hep::DDRec::ConeSurface::radius1(), DD4hep::DDRec::CylinderSurface::u(), DD4hep::DDRec::CylinderSurface::v(), DD4hep::DDRec::ConeSurface::z0(), and DD4hep::DDRec::ConeSurface::z1().
_wtM
TGeoMatrix* DD4hep::DDRec::Surface::_wtM protected
Definition at line 517 of file Surface.h.
Referenced by distance(), getLines(), DD4hep::DDRec::CylinderSurface::globalToLocal(), initialize(), insideBounds(), DD4hep::DDRec::CylinderSurface::localToGlobal(), DD4hep::DDRec::CylinderSurface::normal(), DD4hep::DDRec::CylinderSurface::u(), DD4hep::DDRec::CylinderSurface::v(), and volumeOrigin().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp