DD4hep: TiXmlDocument Class Reference
TiXmlDocument Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlDocument ()
Create an empty document, that has no name.
TiXmlDocument (const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
TiXmlDocument (const std::string &documentName)
Constructor.
TiXmlDocument (const TiXmlDocument &copy)
void operator= (const TiXmlDocument &copy)
virtual ~TiXmlDocument ()
bool LoadFile (TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile () const
Save a file using the current document value. Returns true if successful.
bool LoadFile (const char *filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
bool SaveFile (const char *filename) const
Save a file using the given filename. Returns true if successful.
bool LoadFile (FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile (FILE *) const
Save a file using the given FILE*. Returns true if successful.
bool LoadFile (const std::string &filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile (const std::string &filename) const
< STL std::string version.
virtual const char * Parse (const char *p, TiXmlParsingData *data=0, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
const TiXmlElement * RootElement () const
TiXmlElement * RootElement ()
bool Error () const
const char * ErrorDesc () const
Contains a textual (english) description of the error if one occurs.
int ErrorId () const
int ErrorRow () const
int ErrorCol () const
The column where the error occured. See ErrorRow()
void SetTabSize (int _tabsize)
int TabSize () const
void ClearError ()
void Print () const
virtual void Print (FILE *cfile, int depth=0) const
Print this Document to a FILE stream.
void SetError (int err, const char *errorLocation, TiXmlParsingData *prevData, TiXmlEncoding encoding)
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Public Member Functions inherited from TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
const std::string & ValueStr () const
void SetValue (const char *_value)
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * PreviousSiblingElement () const
TiXmlElement * PreviousSiblingElement ()
const TiXmlElement * PreviousSiblingElement (const char *) const
TiXmlElement * PreviousSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
const TiXmlDocument * GetDocument () const
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
virtual TiXmlNode * Clone () const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Protected Member Functions inherited from TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Private Member Functions
void CopyTo (TiXmlDocument *target) const
Private Attributes
bool error
int errorId
TIXML_STRING errorDesc
int tabsize
TiXmlCursor errorLocation
bool useMicrosoftBOM
Additional Inherited Members
Public Types inherited from TiXmlNode
enum NodeType {
DOCUMENT, ELEMENT, COMMENT, UNKNOWN,
TEXT, DECLARATION, TYPECOUNT
}
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_DOCUMENT_TOP_ONLY, TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
Always the top level node. A document binds together all the XML pieces. It can be saved, loaded, and printed to the screen. The 'value' of a document node is the xml file name.
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 1544 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlDocument() [1/4]
TiXmlDocument::TiXmlDocument ()
Create an empty document, that has no name.
Definition at line 910 of file tinyxml_inl.h.
References ClearError(), tabsize, and useMicrosoftBOM.
Referenced by Clone(), and TiXmlDocument().
TiXmlDocument() [2/4]
TiXmlDocument::TiXmlDocument (const char * documentName)
Create a document with a name. The name of the document is also the filename of the xml.
Definition at line 917 of file tinyxml_inl.h.
References ClearError(), TiXmlNode::DOCUMENT, tabsize, TiXmlDocument(), TiXmlNode::TiXmlNode(), useMicrosoftBOM, and TiXmlNode::value.
TiXmlDocument() [3/4]
TiXmlDocument::TiXmlDocument (const std::string & documentName)
Constructor.
TiXmlDocument() [4/4]
TiXmlDocument::TiXmlDocument (const TiXmlDocument & copy)
Definition at line 937 of file tinyxml_inl.h.
References CopyTo().
~TiXmlDocument()
virtual TiXmlDocument::~TiXmlDocument () inline virtual
Definition at line 1559 of file tinyxml.h.
References TIXML_DEFAULT_ENCODING.
Member Function Documentation
Accept()
bool TiXmlDocument::Accept (TiXmlVisitor * content) const virtual
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
Definition at line 1182 of file tinyxml_inl.h.
References TiXmlNode::FirstChild(), TiXmlNode::NextSibling(), TiXmlVisitor::VisitEnter(), and TiXmlVisitor::VisitExit().
Referenced by DD4hep::XML::DocumentHandler::output().
ClearError()
void TiXmlDocument::ClearError () inline
If you have handled the error, it can be reset with this call. The error state is automatically cleared if you Parse a new XML block.
Definition at line 1684 of file tinyxml.h.
Referenced by Parse(), and TiXmlDocument().
Clone()
TiXmlNode * TiXmlDocument::Clone () const protected virtual
Create an exact duplicate of this node and return it. The memory must be deleted by the caller.
Implements TiXmlNode.
Definition at line 1160 of file tinyxml_inl.h.
References CopyTo(), and TiXmlDocument().
CopyTo()
void TiXmlDocument::CopyTo (TiXmlDocument * target) const private
Definition at line 1145 of file tinyxml_inl.h.
References TiXmlNode::Clone(), TiXmlNode::CopyTo(), error, errorDesc, TiXmlNode::firstChild, TiXmlNode::LinkEndChild(), and TiXmlNode::NextSibling().
Referenced by Clone(), operator=(), and TiXmlDocument().
Error()
bool TiXmlDocument::Error () const inline
If an error occurs, Error will be set to true. Also,
The ErrorId() will contain the integer identifier of the error (not generally useful)
The ErrorDesc() method will return the name of the error. (very useful)
The ErrorRow() and ErrorCol() will return the location of the error (if known)
Definition at line 1619 of file tinyxml.h.
Referenced by LoadFile(), and DD4hep::XML::DocumentHandler::output().
ErrorCol()
int TiXmlDocument::ErrorCol () const inline
The column where the error occured. See ErrorRow()
Definition at line 1645 of file tinyxml.h.
Referenced by DD4hep::XML::DocumentHandler::output().
ErrorDesc()
const char* TiXmlDocument::ErrorDesc () const inline
Contains a textual (english) description of the error if one occurs.
Definition at line 1624 of file tinyxml.h.
Referenced by DD4hep::XML::DocumentHandler::output().
ErrorId()
int TiXmlDocument::ErrorId () const inline
Generally, you probably want the error string (ErrorDesc()). But if you prefer the ErrorId, this function will fetch it.
Definition at line 1631 of file tinyxml.h.
ErrorRow()
int TiXmlDocument::ErrorRow () const inline
Returns the location (if known) of the error. The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)
See also
SetTabSize, Row, Column
Definition at line 1642 of file tinyxml.h.
Referenced by DD4hep::XML::DocumentHandler::output().
LoadFile() [1/4]
bool TiXmlDocument::LoadFile (TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the current document value. Returns true if successful. Will delete any existing document data before loading.
Definition at line 950 of file tinyxml_inl.h.
References TiXmlNode::Value().
Referenced by LoadFile(), and DD4hep::XML::DocumentHandler::output().
LoadFile() [2/4]
bool TiXmlDocument::LoadFile (const char * filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
Definition at line 971 of file tinyxml_inl.h.
References LoadFile(), SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_STRING, and TiXmlNode::value.
LoadFile() [3/4]
bool TiXmlDocument::LoadFile (FILE * file, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*. Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. TinyXML doesn't stream in XML from the current file location. Streaming may be added in the future.
Definition at line 999 of file tinyxml_inl.h.
References TiXmlCursor::Clear(), TiXmlNode::Clear(), Error(), TiXmlBase::location, Parse(), SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, TiXmlBase::TIXML_ERROR_OPENING_FILE, and TIXML_STRING.
LoadFile() [4/4]
bool TiXmlDocument::LoadFile (const std::string & filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) inline
Parameters
encoding STL std::string version.
Definition at line 1583 of file tinyxml.h.
operator=()
void TiXmlDocument::operator= (const TiXmlDocument & copy)
Definition at line 943 of file tinyxml_inl.h.
References TiXmlNode::Clear(), and CopyTo().
Referenced by TiXmlBase::ToLower().
Parse()
const char * TiXmlDocument::Parse (const char * p, TiXmlParsingData * data = 0, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) virtual
Parse the given null terminated block of xml data. Passing in an encoding to this method (either TIXML_ENCODING_LEGACY or TIXML_ENCODING_UTF8 will force TinyXml to use that encoding, regardless of what TinyXml might otherwise try to detect.
Implements TiXmlBase.
Definition at line 712 of file tinyxmlparser_inl.h.
References TiXmlCursor::Clear(), ClearError(), TiXmlCursor::col, TiXmlParsingData::Cursor(), TiXmlParsingData::cursor, TiXmlDeclaration::Encoding(), TiXmlNode::firstChild, TiXmlNode::Identify(), TiXmlNode::LinkEndChild(), TiXmlBase::location, TiXmlBase::Parse(), TiXmlCursor::row, SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlBase::StringEqual(), TabSize(), TIXML_ENCODING_LEGACY, TIXML_ENCODING_UNKNOWN, TIXML_ENCODING_UTF8, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, TiXmlNode::ToDeclaration(), and useMicrosoftBOM.
Referenced by LoadFile(), and DD4hep::XML::DocumentHandler::output().
Print() [1/2]
void TiXmlDocument::Print () const inline
Write the document to standard out using formatted printing ("pretty print").
Definition at line 1693 of file tinyxml.h.
Referenced by DD4hep::XML::DocumentHandler::output(), SaveFile(), and TiXmlBase::~TiXmlBase().
Print() [2/2]
void TiXmlDocument::Print (FILE * cfile, int depth = 0) const virtual
Print this Document to a FILE stream.
Implements TiXmlBase.
Definition at line 1171 of file tinyxml_inl.h.
References TiXmlNode::FirstChild(), and TiXmlNode::NextSibling().
RootElement() [1/2]
const TiXmlElement* TiXmlDocument::RootElement () const inline
Get the root element – the only top level element – of the document. In well formed XML, there should only be one. TinyXml is tolerant of multiple elements at the document level.
Definition at line 1607 of file tinyxml.h.
RootElement() [2/2]
TiXmlElement* TiXmlDocument::RootElement () inline
Definition at line 1610 of file tinyxml.h.
SaveFile() [1/4]
bool TiXmlDocument::SaveFile () const
Save a file using the current document value. Returns true if successful.
Definition at line 959 of file tinyxml_inl.h.
References TiXmlNode::Value().
Referenced by SaveFile().
SaveFile() [2/4]
bool TiXmlDocument::SaveFile (const char * filename) const
Save a file using the given filename. Returns true if successful.
Definition at line 1114 of file tinyxml_inl.h.
References SaveFile().
SaveFile() [3/4]
bool TiXmlDocument::SaveFile (FILE * fp) const
Save a file using the given FILE*. Returns true if successful.
Definition at line 1128 of file tinyxml_inl.h.
References Print(), TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, and useMicrosoftBOM.
SaveFile() [4/4]
bool TiXmlDocument::SaveFile (const std::string & filename) const inline
< STL std::string version.
Definition at line 1589 of file tinyxml.h.
References TIXML_DEFAULT_ENCODING.
SetError()
void TiXmlDocument::SetError (int err, const char * errorLocation, TiXmlParsingData * prevData, TiXmlEncoding encoding)
Definition at line 806 of file tinyxmlparser_inl.h.
References TiXmlCursor::Clear(), TiXmlParsingData::Cursor(), error, errorDesc, errorId, errorLocation, TiXmlBase::errorString, TiXmlParsingData::Stamp(), and TiXmlBase::TIXML_ERROR_STRING_COUNT.
Referenced by TiXmlNode::Identify(), TiXmlNode::InsertAfterChild(), TiXmlNode::InsertBeforeChild(), TiXmlNode::InsertEndChild(), TiXmlNode::LinkEndChild(), LoadFile(), TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), Parse(), TiXmlBase::ReadText(), TiXmlElement::ReadValue(), and TiXmlElement::SetAttribute().
SetTabSize()
void TiXmlDocument::SetTabSize (int _tabsize) inline
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column. It does not change the output or input in any way.
By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.
The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.
Note that row and column tracking is not supported when using operator>>.
The tab size needs to be enabled before the parse or load. Correct usage:
TiXmlDocument doc;
doc.SetTabSize(8);
doc.Load("myfile.xml");
See also
Row, Column
Definition at line 1673 of file tinyxml.h.
StreamIn()
virtual void TiXmlDocument::StreamIn (std::istream * in, TIXML_STRING * tag) protected virtual
Implements TiXmlNode.
Referenced by TiXmlBase::ReadText().
TabSize()
int TiXmlDocument::TabSize () const inline
Definition at line 1677 of file tinyxml.h.
Referenced by Parse().
ToDocument() [1/2]
virtual const TiXmlDocument* TiXmlDocument::ToDocument () const inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1707 of file tinyxml.h.
ToDocument() [2/2]
virtual TiXmlDocument* TiXmlDocument::ToDocument () inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1710 of file tinyxml.h.
References TIXML_STRING.
Member Data Documentation
error
bool TiXmlDocument::error private
Definition at line 1728 of file tinyxml.h.
Referenced by CopyTo(), and SetError().
errorDesc
TIXML_STRING TiXmlDocument::errorDesc private
Definition at line 1729 of file tinyxml.h.
Referenced by CopyTo(), and SetError().
errorId
int TiXmlDocument::errorId private
Definition at line 1729 of file tinyxml.h.
Referenced by SetError().
errorLocation
TiXmlCursor TiXmlDocument::errorLocation private
Definition at line 1731 of file tinyxml.h.
Referenced by SetError().
tabsize
int TiXmlDocument::tabsize private
Definition at line 1730 of file tinyxml.h.
Referenced by TiXmlParsingData::Stamp(), TiXmlDocument(), and TiXmlParsingData::TiXmlParsingData().
useMicrosoftBOM
bool TiXmlDocument::useMicrosoftBOM private
Definition at line 1732 of file tinyxml.h.
Referenced by Parse(), SaveFile(), and TiXmlDocument().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h