DD4hep: DD4hep: DD4hep::XML::NodeList Class Reference
DD4hep::XML::NodeList Class Reference
[DD4hep::XML classes and objects]
Class describing a list of XML nodes.
#include <XMLElements.h>
Public Member Functions
NodeList (const NodeList &l)
Copy constructor.
NodeList (XmlElement *frst, const XmlChar *t)
Initializing constructor.
~NodeList ()
Default destructor.
XmlElement * reset ()
Reset the nodelist - e.g. restart iteration from beginning.
XmlElement * next () const
Advance to next element.
XmlElement * previous () const
Go back to previous element.
NodeList & operator= (const NodeList &l)
Assignment operator.
Public Attributes
Tag_t m_tag
XmlElement * m_node
XmlElement * m_ptr
Detailed Description
Class describing a list of XML nodes.
Definition of a "list" of xml elements hanging of the parent. The list allows iterations, which can be restarted. Please not: Copies are not entirely free, since the string tag need to be replicated using strdup/free (or when using xerces the corresponding unicode routines).
Author:
M.Frank
Version:
1.0
Definition at line 330 of file XMLElements.h.
Constructor & Destructor Documentation
NodeList::NodeList (const NodeList & l)
Copy constructor.
Definition at line 556 of file XMLElements.cpp.
References reset().
NodeList::NodeList (XmlElement * frst, const XmlChar * t)
Initializing constructor.
Definition at line 563 of file XMLElements.cpp.
References reset().
NodeList::~NodeList ()
Default destructor.
Definition at line 570 of file XMLElements.cpp.
Member Function Documentation
XmlElement * NodeList::next () const
Advance to next element.
Definition at line 579 of file XMLElements.cpp.
References _E, DD4hep::XML::_toString(), _XE, m_ptr, m_tag, and DD4hep::XML::Tag_t::str().
Referenced by DD4hep::XML::Collection_t::operator++().
NodeList & NodeList::operator= (const NodeList & l)
Assignment operator.
Definition at line 613 of file XMLElements.cpp.
References m_node, m_tag, and reset().
XmlElement * NodeList::previous () const
Go back to previous element.
Definition at line 596 of file XMLElements.cpp.
References _E, DD4hep::XML::_toString(), _XE, m_ptr, m_tag, and DD4hep::XML::Tag_t::str().
Referenced by DD4hep::XML::Collection_t::operator--().
XmlElement * NodeList::reset ()
Reset the nodelist - e.g. restart iteration from beginning.
Reset the nodelist.
Definition at line 574 of file XMLElements.cpp.
References m_node, m_ptr, and m_tag.
Referenced by DD4hep::XML::Collection_t::Collection_t(), NodeList(), operator=(), and DD4hep::XML::Collection_t::reset().
Member Data Documentation
XmlElement* DD4hep::XML::NodeList::m_node
Definition at line 333 of file XMLElements.h.
Referenced by operator=(), reset(), and DD4hep::XML::Collection_t::size().
XmlElement* DD4hep::XML::NodeList::m_ptr [mutable]
Definition at line 334 of file XMLElements.h.
Referenced by next(), previous(), and reset().
Tag_t DD4hep::XML::NodeList::m_tag
Definition at line 332 of file XMLElements.h.
Referenced by next(), operator=(), previous(), reset(), and DD4hep::XML::Collection_t::size().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp