DD4hep: DD4hep::Conditions::Entry Class Reference
DD4hep::Conditions::Entry Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
The intermediate conditions data used to populate the DetElement conditions.
#include <ConditionsEntry.h>
Public Member Functions
Entry ()
Default constructor.
Entry (const Geometry::DetElement &det, const std::string &nam, const std::string &typ, const std::string &valid, int hash)
Initializing constructor.
Entry (const Entry &c)
Copy constructor.
virtual ~Entry ()
Default destructor.
Entry & operator= (const Entry &c)
Assignment operator.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
Geometry::DetElement detector
Reference to the detector element.
std::string value
The actual conditions data.
std::string validity
The validity string to be interpreted by the updating engine.
int hash
Hash value of the name for fast identification.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Detailed Description
The intermediate conditions data used to populate the DetElement conditions.
Author
M.Frank
Version
1.0
Definition at line 37 of file ConditionsEntry.h.
Constructor & Destructor Documentation
Entry() [1/3]
DD4hep::Conditions::Entry::Entry () inline
Default constructor.
Definition at line 48 of file ConditionsEntry.h.
References operator=(), and ~Entry().
Entry() [2/3]
Entry::Entry (const Geometry::DetElement & det, const std::string & nam, const std::string & typ, const std::string & valid, int hash)
Initializing constructor.
Definition at line 23 of file ConditionsEntry.cpp.
References DD4hep::InstanceCount::increment().
Entry() [3/3]
Entry::Entry (const Entry & c)
Copy constructor.
Definition at line 30 of file ConditionsEntry.cpp.
References DD4hep::InstanceCount::increment().
~Entry()
Entry::~Entry () virtual
Default destructor.
Definition at line 37 of file ConditionsEntry.cpp.
References DD4hep::InstanceCount::decrement().
Referenced by Entry().
Member Function Documentation
operator=()
Entry & Entry::operator= (const Entry & c)
Assignment operator.
Definition at line 42 of file ConditionsEntry.cpp.
References detector, DD4hep::NamedObject::operator=(), validity, and value.
Referenced by Entry().
Member Data Documentation
detector
Geometry::DetElement DD4hep::Conditions::Entry::detector
Reference to the detector element.
Definition at line 40 of file ConditionsEntry.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), and operator=().
hash
int DD4hep::Conditions::Entry::hash
Hash value of the name for fast identification.
Definition at line 46 of file ConditionsEntry.h.
validity
std::string DD4hep::Conditions::Entry::validity
The validity string to be interpreted by the updating engine.
Definition at line 44 of file ConditionsEntry.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), and operator=().
value
std::string DD4hep::Conditions::Entry::value
The actual conditions data.
Definition at line 42 of file ConditionsEntry.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), and operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsEntry.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsEntry.cpp