DD4hep: DD4hep: DD4hep::RhoZProjection Class Reference
DD4hep::RhoZProjection Class Reference
class RhoZProjection RhoZProjection.h DDEve/RhoZProjection.h
#include <RhoZProjection.h>
Public Member Functions
RhoZProjection (Display *eve, const std::string &name)
Initializing constructor.
virtual ~RhoZProjection ()
Default destructor.
virtual View & Build (TEveWindow *slot)
Build the projection view and map it to the given slot.
ClassDef (RhoZProjection, 0)
Root implementation macro.
Detailed Description
class RhoZProjection RhoZProjection.h DDEve/RhoZProjection.h
Definition at line 30 of file RhoZProjection.h.
Constructor & Destructor Documentation
DD4hep::RhoZProjection::RhoZProjection (Display * eve, const std::string & name)
Initializing constructor.
RhoZProjection::~RhoZProjection () [virtual]
Default destructor.
Definition at line 33 of file RhoZProjection.cpp.
Member Function Documentation
View & RhoZProjection::Build (TEveWindow * slot) [virtual]
Build the projection view and map it to the given slot.
Reimplemented from DD4hep::View.
Definition at line 37 of file RhoZProjection.cpp.
References DD4hep::Projection::AddAxis(), DD4hep::Projection::CreateRhoZProjection(), DD4hep::View::CreateScenes(), and DD4hep::Projection::Map().
DD4hep::RhoZProjection::ClassDef (RhoZProjection , 0)
Root implementation macro.
Reimplemented from DD4hep::Projection.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/RhoZProjection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/RhoZProjection.cpp