DD4hep: DD4hep: DD4hep::Geometry::EllipticalTube Class Reference
DD4hep::Geometry::EllipticalTube Class Reference
[DD4hep::Geometry components, classes and objects]
Class describing a elliptical tube shape of a section of a tube.
#include <Shapes.h>
Public Member Functions
EllipticalTube ()
Default constructor.
EllipticalTube (const EllipticalTube &e)
Constructor to be used when passing an already created object.
template<typename Q >
EllipticalTube (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
EllipticalTube (const Handle< Q > &e)
Constructor to assign an object.
EllipticalTube (double a, double b, double dz)
Constructor to create a new anonymous tube object with attribute initialization.
template<typename A , typename B , typename DZ >
EllipticalTube (const A &a, const B &b, const DZ &dz)
Constructor to create a new anonymous tube object with attribute initialization.
EllipticalTube & operator= (const EllipticalTube &copy)
Assignment operator.
EllipticalTube & setDimensions (double a, double b, double dz)
Set the tube dimensions.
Protected Member Functions
void make (double a, double b, double dz)
Internal helper method to support object construction.
Detailed Description
Class describing a elliptical tube shape of a section of a tube.
TGeoEltu - cylindrical tube class. It takes 3 parameters : Semi axis of ellipsis in x and y and half-length dz.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoElTu.html
Author:
M.Frank
Version:
1.0
Definition at line 326 of file Shapes.h.
Constructor & Destructor Documentation
DD4hep::Geometry::EllipticalTube::EllipticalTube ()
Default constructor.
DD4hep::Geometry::EllipticalTube::EllipticalTube (const EllipticalTube & e)
Constructor to be used when passing an already created object.
template<typename Q > DD4hep::Geometry::EllipticalTube::EllipticalTube (const Q * p) [inline]
Constructor to be used with an existing object.
Definition at line 337 of file Shapes.h.
template<typename Q > DD4hep::Geometry::EllipticalTube::EllipticalTube (const Handle< Q > & e) [inline]
Constructor to assign an object.
Definition at line 339 of file Shapes.h.
DD4hep::Geometry::EllipticalTube::EllipticalTube (double a, double b, double dz) [inline]
Constructor to create a new anonymous tube object with attribute initialization.
Definition at line 341 of file Shapes.h.
References make().
template<typename A , typename B , typename DZ > DD4hep::Geometry::EllipticalTube::EllipticalTube (const A & a, const B & b, const DZ & dz) [inline]
Constructor to create a new anonymous tube object with attribute initialization.
Definition at line 344 of file Shapes.h.
References DD4hep::_toDouble(), and make().
Member Function Documentation
void EllipticalTube::make (double a, double b, double dz) [protected]
Internal helper method to support object construction.
Constructor to be used when creating a new object with attribute initialization.
Definition at line 288 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoEltu >::_assign(), and setDimensions().
Referenced by EllipticalTube().
EllipticalTube& DD4hep::Geometry::EllipticalTube::operator= (const EllipticalTube & copy)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
EllipticalTube & EllipticalTube::setDimensions (double a, double b, double dz)
Set the tube dimensions.
Definition at line 294 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoEltu >::_setDimensions().
Referenced by make().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp