DD4hep: DD4hep::Simulation::Geant4MaterialScanner Class Reference
DD4hep::Simulation::Geant4MaterialScanner Class Reference
DD4hep::Simulation components, classes and objects
Class to perform directional material scans using Geantinos.
Classes
class StepInfo
Structure to hold the information of one simulation step.
Public Member Functions
Geant4MaterialScanner (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4MaterialScanner ()
Default destructor.
virtual void operator() (const G4Step *step, G4SteppingManager *mgr)
User stepping callback.
virtual void begin (const G4Track *track)
Begin-of-tracking callback.
virtual void end (const G4Track *track)
End-of-tracking callback.
void beginEvent (const G4Event *event)
Registered callback on Begin-event.
Public Member Functions inherited from DD4hep::Simulation::Geant4SteppingAction
Geant4SteppingAction (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4SteppingAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Types
typedef std::vector< StepInfo * > Steps
Protected Attributes
double m_sumX0
double m_sumLambda
double m_sumPath
Steps m_steps
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4SteppingAction
typedef Geant4SharedSteppingAction shared_type
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Class to perform directional material scans using Geantinos.
Author
M.Frank
Version
1.0
Definition at line 36 of file Geant4MaterialScanner.cpp.
Member Typedef Documentation
Steps
typedef std::vector<StepInfo*> DD4hep::Simulation::Geant4MaterialScanner::Steps protected
Definition at line 55 of file Geant4MaterialScanner.cpp.
Constructor & Destructor Documentation
Geant4MaterialScanner()
Geant4MaterialScanner::Geant4MaterialScanner (Geant4Context * context, const std::string & name)
Standard constructor.
Definition at line 126 of file Geant4MaterialScanner.cpp.
References begin(), beginEvent(), DD4hep::Simulation::Geant4EventActionSequence::callAtBegin(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtBegin(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtEnd(), end(), DD4hep::Simulation::Geant4Action::eventAction(), DD4hep::InstanceCount::increment(), DD4hep::Simulation::Geant4Action::m_needsControl, and DD4hep::Simulation::Geant4Action::trackingAction().
~Geant4MaterialScanner()
Geant4MaterialScanner::~Geant4MaterialScanner () virtual
Default destructor.
Definition at line 137 of file Geant4MaterialScanner.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
begin()
void Geant4MaterialScanner::begin (const G4Track * track) virtual
Begin-of-tracking callback.
Definition at line 164 of file Geant4MaterialScanner.cpp.
References m_steps, m_sumLambda, m_sumPath, m_sumX0, and DD4hep::Simulation::Geant4Action::printP2().
Referenced by Geant4MaterialScanner().
beginEvent()
void Geant4MaterialScanner::beginEvent (const G4Event * event)
Registered callback on Begin-event.
Definition at line 155 of file Geant4MaterialScanner.cpp.
References m_steps, m_sumLambda, m_sumPath, and m_sumX0.
Referenced by Geant4MaterialScanner().
end()
void Geant4MaterialScanner::end (const G4Track * track) virtual
End-of-tracking callback.
Definition at line 174 of file Geant4MaterialScanner.cpp.
References dd4hep::cm, dd4hep::cm3, dd4hep::gram, m_steps, m_sumLambda, m_sumPath, and m_sumX0.
Referenced by Geant4MaterialScanner().
operator()()
void Geant4MaterialScanner::operator() (const G4Step * step, G4SteppingManager * mgr) virtual
User stepping callback.
Reimplemented from DD4hep::Simulation::Geant4SteppingAction.
Definition at line 142 of file Geant4MaterialScanner.cpp.
References DD4hep::Simulation::Geant4StepHandler::logvol(), m_steps, DD4hep::Simulation::Geant4TouchableHandler::path(), DD4hep::Simulation::Geant4StepHandler::postPos(), DD4hep::Simulation::Geant4StepHandler::pre, and DD4hep::Simulation::Geant4StepHandler::prePos().
Member Data Documentation
m_steps
Steps DD4hep::Simulation::Geant4MaterialScanner::m_steps protected
Definition at line 60 of file Geant4MaterialScanner.cpp.
Referenced by begin(), beginEvent(), end(), and operator()().
m_sumLambda
double DD4hep::Simulation::Geant4MaterialScanner::m_sumLambda protected
Definition at line 58 of file Geant4MaterialScanner.cpp.
Referenced by begin(), beginEvent(), and end().
m_sumPath
double DD4hep::Simulation::Geant4MaterialScanner::m_sumPath protected
Definition at line 59 of file Geant4MaterialScanner.cpp.
Referenced by begin(), beginEvent(), and end().
m_sumX0
double DD4hep::Simulation::Geant4MaterialScanner::m_sumX0 protected
Definition at line 57 of file Geant4MaterialScanner.cpp.
Referenced by begin(), beginEvent(), and end().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4MaterialScanner.cpp