DD4hep: DD4hep::MultiView Class Reference
DD4hep::MultiView Class Reference
class MultiView MultiView.h DDEve/MultiView.h
#include <MultiView.h>
Public Member Functions
MultiView (Display *eve, const std::string &name)
Initializing constructor.
virtual ~MultiView ()
Default destructor.
virtual View & Build (TEveWindow *slot)
Build the 3d view and map it to the given slot.
ClassDef (MultiView, 0)
Root implementation macro.
Public Member Functions inherited from DD4hep::View
virtual TEveElement * ImportGeoElement (TEveElement *element, TEveElementList *list)
Call an element to a geometry element list.
virtual TEveElement * ImportGeoTopic (TEveElement *element, TEveElementList *list)
Call an element to a geometry element list.
virtual TEveElement * ImportEventElement (TEveElement *element, TEveElementList *list)
Call an element to a event element list.
View (Display *eve, const std::string &name)
Initializing constructor.
virtual ~View ()
Default destructor.
const std::string & name () const
Access to the view name/title.
const char * c_name () const
TEveViewer * viewer () const
Access to the Eve viewer.
bool showGlobal () const
Show global directory.
void setShowGlobal (bool value)
Set show globals.
virtual void Initialize ()
Initialize the view port.
virtual View & Map (TEveWindow *slot)
Map the view view to the slot.
virtual View & CreateScenes ()
Create the geometry and the event scene.
virtual TEveElementList * AddToGlobalItems (const std::string &nam)
Add the view to the global list of eve objects.
TEveScene * geoScene () const
Access to the Eve geometry scene.
virtual View & CreateGeoScene ()
Create the geometry scene.
virtual void ConfigureGeometryFromInfo ()
Configure a view with geo info. Used configuration if present.
virtual void ConfigureGeometryFromGlobal ()
Configure a single geometry view by default from the global geometry scene with all subdetectors.
virtual void ConfigureGeometry (const DisplayConfiguration::ViewConfig &config)
Configure a single geometry view.
virtual std::pair< bool, TEveElement * > CreateGeometry (DetElement de, const DisplayConfiguration::Config &cfg)
Create a new instance of the geometry of a sub-detector.
virtual std::pair< bool, TEveElement * > GetGlobalGeometry (DetElement de, const DisplayConfiguration::Config &cfg)
Access the global instance of the subdetector geometry.
virtual void ImportGeo (const std::string &topic, TEveElement *element)
Call to import geometry elements into topics.
virtual void ImportGeo (TEveElementList &topic, TEveElement *element)
Call to import geometry elements into topics.
virtual void ImportGeo (TEveElement *element)
Call to import geometry elements into the main geometry scene menu.
virtual void ImportGeoTopics (const std::string &title)
Call to import geometry topics. If title is empty, do not add to global item list.
virtual TEveElementList & GetGeoTopic (const std::string &name)
Access/Create an geometry topic by name.
TEveScene * eveScene () const
Access to the Eve event scene.
virtual View & CreateEventScene ()
Create the event scene.
virtual void ConfigureEventFromInfo ()
Configure a view with event info. Used configuration if present.
virtual void ConfigureEventFromGlobal ()
Configure an event view by default from the global event scene.
virtual void ConfigureEvent (const DisplayConfiguration::ViewConfig &config)
Configure a single event scene view.
virtual void ImportEvent (TEveElement *element)
Call to import event elements into the main event scene.
virtual void ImportEventTopics ()
Import event typics after creation.
ClassDef (View, 0)
Root implementation macro.
Additional Inherited Members
Public Types inherited from DD4hep::View
typedef Geometry::LCDD LCDD
typedef Geometry::DetElement DetElement
typedef Geometry::SensitiveDetector SensitiveDetector
typedef std::map< std::string, TEveElementList * > Topics
Protected Attributes inherited from DD4hep::View
Display * m_eve
TEveViewer * m_view
Reference to the view.
TEveScene * m_geoScene
Reference to the geometry scene.
TEveScene * m_eveScene
Reference to the event scene.
TEveElementList * m_global
Reference to the global item (if added.
const DisplayConfiguration::ViewConfig * m_config
std::string m_name
The name of the view.
Topics m_geoTopics
Topics m_eveTopics
bool m_showGlobal
Detailed Description
class MultiView MultiView.h DDEve/MultiView.h
Definition at line 33 of file MultiView.h.
Constructor & Destructor Documentation
MultiView()
MultiView::MultiView (Display * eve, const std::string & name)
Initializing constructor.
Definition at line 39 of file MultiView.cpp.
~MultiView()
MultiView::~MultiView () virtual
Default destructor.
Definition at line 44 of file MultiView.cpp.
Member Function Documentation
Build()
View & MultiView::Build (TEveWindow * slot) virtual
Build the 3d view and map it to the given slot.
Build the projection view and map it to the given slot.
First panel
Second panel
Reimplemented from DD4hep::View.
Definition at line 48 of file MultiView.cpp.
References DD4hep::View::CreateScenes(), DD4hep::View::m_eve, DD4hep::View::m_name, DD4hep::View::Map(), DD4hep::DisplayConfiguration::Config::name, DD4hep::DisplayConfiguration::PANEL, DD4hep::DisplayConfiguration::Config::use, v, and DD4hep::Display::viewConfigurations().
ClassDef()
DD4hep::MultiView::ClassDef (MultiView , 0)
Root implementation macro.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/MultiView.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/MultiView.cpp