DD4hep: DD4hep::Alignments::GlobalAlignmentCache Class Reference
DD4hep::Alignments::GlobalAlignmentCache Class Reference
DDAlign: DD4hep Detector geometry alignment components.
Class caching all known alignment operations for one LCDD instance.
#include <GlobalAlignmentCache.h>
Public Types
typedef AlignmentStack Stack
typedef AlignmentStack::StackEntry Entry
typedef std::map< unsigned int, TGeoPhysicalNode * > Cache
typedef std::map< std::string, GlobalAlignmentCache * > SubdetectorAlignments
Public Member Functions
int addRef ()
Add reference count.
int release ()
Release object. If reference count goes to NULL, automatic deletion is triggered.
const std::string & name () const
Access the section name.
void commit (AlignmentStack &stack)
Close existing transaction stack and apply all alignments.
GlobalAlignmentCache * section (const std::string &path_name) const
Retrieve the cache section corresponding to the path of an entry.
GlobalAlignment get (const std::string &path) const
Retrieve an alignment entry by its lacement path.
std::vector< GlobalAlignment > matches (const std::string &path_match, bool exclude_exact=false) const
Return all entries matching a given path. Careful: Expensive operaton!
Static Public Member Functions
static GlobalAlignmentCache * install (LCDD &lcdd)
Create and install a new instance tree.
static void uninstall (LCDD &lcdd)
Unregister and delete a tree instance.
Protected Member Functions
GlobalAlignmentCache (LCDD &lcdd, const std::string &sdPath, bool top)
Default constructor initializing variables.
virtual ~GlobalAlignmentCache ()
Default destructor.
GlobalAlignmentCache * subdetectorAlignments (const std::string &name)
Retrieve branch cache by name. If not present it will be created.
void apply (AlignmentStack &stack)
Population entry: Apply a complete stack of ordered alignments to the geometry structure.
void apply (const std::vector< Entry *> &changes)
Apply a vector of SD entries of ordered alignments to the geometry structure.
bool insert (GlobalAlignment alignment)
Add a new entry to the cache. The key is the placement path.
Protected Attributes
LCDD & m_lcdd
SubdetectorAlignments m_detectors
Cache of subdetectors.
Cache m_cache
The subdetector specific map of alignments caches.
std::string m_sdPath
size_t m_sdPathLen
The length of the branch name to optimize lookups....
int m_refCount
Reference count.
bool m_top
Flag to indicate the top instance.
Friends
class LCDD
class AlignmentOperator
Detailed Description
Class caching all known alignment operations for one LCDD instance.
Internally the instances are fragmented to subdetectors defined by the next-to-top level detector elements.
Author
M.Frank
Version
1.0
Definition at line 41 of file GlobalAlignmentCache.h.
Member Typedef Documentation
Cache
typedef std::map<unsigned int, TGeoPhysicalNode*> DD4hep::Alignments::GlobalAlignmentCache::Cache
Definition at line 48 of file GlobalAlignmentCache.h.
Entry
typedef AlignmentStack::StackEntry DD4hep::Alignments::GlobalAlignmentCache::Entry
Definition at line 47 of file GlobalAlignmentCache.h.
Stack
typedef AlignmentStack DD4hep::Alignments::GlobalAlignmentCache::Stack
Definition at line 46 of file GlobalAlignmentCache.h.
SubdetectorAlignments
typedef std::map<std::string,GlobalAlignmentCache*> DD4hep::Alignments::GlobalAlignmentCache::SubdetectorAlignments
Definition at line 49 of file GlobalAlignmentCache.h.
Constructor & Destructor Documentation
GlobalAlignmentCache()
GlobalAlignmentCache::GlobalAlignmentCache (LCDD & lcdd, const std::string & sdPath, bool top) protected
Default constructor initializing variables.
Default constructor.
Definition at line 44 of file GlobalAlignmentCache.cpp.
Referenced by install(), and subdetectorAlignments().
~GlobalAlignmentCache()
GlobalAlignmentCache::~GlobalAlignmentCache () protected virtual
Default destructor.
Definition at line 50 of file GlobalAlignmentCache.cpp.
References DD4hep::INFO, m_cache, m_detectors, m_sdPath, DD4hep::printout(), and DD4hep::releaseObjects().
Member Function Documentation
addRef()
int GlobalAlignmentCache::addRef ()
Add reference count.
Definition at line 61 of file GlobalAlignmentCache.cpp.
References m_refCount.
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::GlobalAlignmentWriter().
apply() [1/2]
void GlobalAlignmentCache::apply (AlignmentStack & stack) protected
Population entry: Apply a complete stack of ordered alignments to the geometry structure.
Apply a complete stack of ordered alignments to the geometry structure.
Definition at line 186 of file GlobalAlignmentCache.cpp.
References _detector(), apply(), DD4hep::DEBUG, DD4hep::Alignments::AlignmentStack::StackEntry::detector, e, DD4hep::Alignments::AlignmentStack::StackEntry::hasMatrix(), DD4hep::INFO, m_lcdd, DD4hep::Geometry::LCDD::manager(), DD4hep::Handle< T >::name(), DD4hep::Alignments::AlignmentStack::StackEntry::needsReset(), DD4hep::Geometry::DetElement::path(), DD4hep::Geometry::DetElement::placement(), DD4hep::Geometry::DetElement::PLACEMENT_CHANGED, DD4hep::Geometry::DetElement::PLACEMENT_DETECTOR, DD4hep::Geometry::DetElement::PLACEMENT_ELEMENT, DD4hep::Geometry::DetElement::PLACEMENT_HIGHEST, DD4hep::Alignments::AlignmentStack::pop(), DD4hep::printout(), DD4hep::Handle< T >::ptr(), DD4hep::Alignments::AlignmentStack::StackEntry::resetChildren(), DD4hep::Alignments::AlignmentStack::size(), and subdetectorAlignments().
Referenced by apply(), and commit().
apply() [2/2]
void GlobalAlignmentCache::apply (const std::vector< Entry *> & changes) protected
Apply a vector of SD entries of ordered alignments to the geometry structure.
Definition at line 239 of file GlobalAlignmentCache.cpp.
References m_cache, and DD4hep::Alignments::AlignmentSelector::reset().
commit()
void GlobalAlignmentCache::commit (AlignmentStack & stack)
Close existing transaction stack and apply all alignments.
Definition at line 167 of file GlobalAlignmentCache.cpp.
References apply(), m_lcdd, and DD4hep::Geometry::LCDD::manager().
Referenced by name().
get()
GlobalAlignment GlobalAlignmentCache::get (const std::string & path) const
Retrieve an alignment entry by its lacement path.
Retrieve an alignment entry by its placement path.
Definition at line 123 of file GlobalAlignmentCache.cpp.
References DD4hep::hash32(), m_cache, m_detectors, m_lcdd, m_sdPathLen, DD4hep::Geometry::DetElement::placementPath(), and DD4hep::Geometry::LCDD::world().
insert()
bool GlobalAlignmentCache::insert (GlobalAlignment alignment) protected
Add a new entry to the cache. The key is the placement path.
Definition at line 91 of file GlobalAlignmentCache.cpp.
References DD4hep::ALWAYS, DD4hep::hash32(), m_cache, m_sdPathLen, name(), DD4hep::printout(), and DD4hep::Handle< T >::ptr().
install()
GlobalAlignmentCache * GlobalAlignmentCache::install (LCDD & lcdd) static
Create and install a new instance tree.
Definition at line 75 of file GlobalAlignmentCache.cpp.
References DD4hep::Geometry::LCDD::addExtension(), DD4hep::Geometry::LCDD::extension(), and GlobalAlignmentCache().
matches()
vector< GlobalAlignment > GlobalAlignmentCache::matches (const std::string & path_match, bool exclude_exact = false) const
Return all entries matching a given path. Careful: Expensive operaton!
Return all entries matching a given path.
Definition at line 148 of file GlobalAlignmentCache.cpp.
References m_cache, section(), and v.
Referenced by name().
name()
const std::string& DD4hep::Alignments::GlobalAlignmentCache::name () const inline
Access the section name.
Definition at line 93 of file GlobalAlignmentCache.h.
References commit(), m_sdPath, matches(), and section().
Referenced by insert().
release()
int GlobalAlignmentCache::release ()
Release object. If reference count goes to NULL, automatic deletion is triggered.
Definition at line 66 of file GlobalAlignmentCache.cpp.
References m_refCount.
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::~GlobalAlignmentWriter().
section()
GlobalAlignmentCache * GlobalAlignmentCache::section (const std::string & path_name) const
Retrieve the cache section corresponding to the path of an entry.
Definition at line 105 of file GlobalAlignmentCache.cpp.
References m_detectors, m_lcdd, m_sdPath, DD4hep::Geometry::DetElement::placementPath(), and DD4hep::Geometry::LCDD::world().
Referenced by matches(), and name().
subdetectorAlignments()
GlobalAlignmentCache * GlobalAlignmentCache::subdetectorAlignments (const std::string & name) protected
Retrieve branch cache by name. If not present it will be created.
Definition at line 175 of file GlobalAlignmentCache.cpp.
References GlobalAlignmentCache(), m_detectors, and m_lcdd.
Referenced by apply().
uninstall()
void GlobalAlignmentCache::uninstall (LCDD & lcdd) static
Unregister and delete a tree instance.
Definition at line 84 of file GlobalAlignmentCache.cpp.
References DD4hep::Geometry::LCDD::extension(), and DD4hep::Geometry::LCDD::removeExtension().
Friends And Related Function Documentation
AlignmentOperator
friend class AlignmentOperator friend
Definition at line 43 of file GlobalAlignmentCache.h.
LCDD
friend class LCDD friend
Definition at line 42 of file GlobalAlignmentCache.h.
Member Data Documentation
m_cache
Cache DD4hep::Alignments::GlobalAlignmentCache::m_cache protected
The subdetector specific map of alignments caches.
Definition at line 56 of file GlobalAlignmentCache.h.
Referenced by apply(), get(), insert(), matches(), and ~GlobalAlignmentCache().
m_detectors
SubdetectorAlignments DD4hep::Alignments::GlobalAlignmentCache::m_detectors protected
Cache of subdetectors.
Definition at line 54 of file GlobalAlignmentCache.h.
Referenced by get(), section(), subdetectorAlignments(), and ~GlobalAlignmentCache().
m_lcdd
LCDD& DD4hep::Alignments::GlobalAlignmentCache::m_lcdd protected
Definition at line 52 of file GlobalAlignmentCache.h.
Referenced by apply(), commit(), get(), section(), and subdetectorAlignments().
m_refCount
int DD4hep::Alignments::GlobalAlignmentCache::m_refCount protected
Reference count.
Definition at line 63 of file GlobalAlignmentCache.h.
Referenced by addRef(), and release().
m_sdPath
std::string DD4hep::Alignments::GlobalAlignmentCache::m_sdPath protected
Branchg name: If it is not the main tree instance, the name of the subdetector
Definition at line 59 of file GlobalAlignmentCache.h.
Referenced by name(), section(), and ~GlobalAlignmentCache().
m_sdPathLen
size_t DD4hep::Alignments::GlobalAlignmentCache::m_sdPathLen protected
The length of the branch name to optimize lookups....
Definition at line 61 of file GlobalAlignmentCache.h.
Referenced by get(), and insert().
m_top
bool DD4hep::Alignments::GlobalAlignmentCache::m_top protected
Flag to indicate the top instance.
Definition at line 65 of file GlobalAlignmentCache.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/GlobalAlignmentCache.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/GlobalAlignmentCache.cpp