DD4hep: DD4hep: DD4hep::Annotation Class Reference
DD4hep::Annotation Class Reference
[DDEve: DD4hep event display components, classes and objects]
Class to add annotations to eve viewers.
#include <Annotation.h>
Public Member Functions
Annotation (TEveViewer *v, const std::string &text, float x, float y, Color_t c)
Standard constructor with initialization.
virtual ~Annotation ()
Default destructor.
virtual Bool_t MouseEnter (TGLOvlSelectRecord &selRec)
Mouse has entered overlay area.
Static Public Member Functions
static float DefaultTextSize ()
Default text size.
static float DefaultMargin ()
Default margin for placement in bottom left corner.
Detailed Description
Class to add annotations to eve viewers.
Implements slightly larger text size and one line constructor
Author:
M.Frank
Version:
1.0
Definition at line 35 of file Annotation.h.
Constructor & Destructor Documentation
DD4hep::Annotation::Annotation (TEveViewer * v, const std::string & text, float x, float y, Color_t c)
Standard constructor with initialization.
Annotation::~Annotation () [virtual]
Default destructor.
Definition at line 40 of file Annotation.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
float Annotation::DefaultMargin () [static]
Default margin for placement in bottom left corner.
Definition at line 55 of file Annotation.cpp.
Referenced by DD4hep::View::ConfigureGeometry(), DD4hep::CaloLego::ConfigureGeometry(), and DD4hep::Calo2DProjection::ConfigureGeometry().
float Annotation::DefaultTextSize () [static]
Default text size.
Definition at line 51 of file Annotation.cpp.
Referenced by DD4hep::View::ConfigureGeometry(), DD4hep::CaloLego::ConfigureGeometry(), and DD4hep::Calo2DProjection::ConfigureGeometry().
Bool_t Annotation::MouseEnter (TGLOvlSelectRecord & selRec) [virtual]
Mouse has entered overlay area.
Definition at line 45 of file Annotation.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/Annotation.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/Annotation.cpp