DD4hep: DD4hep: DD4hep::DDRec::VolSurface Class Reference
DD4hep::DDRec::VolSurface Class Reference
#include <Surface.h>
Public Member Functions
virtual ~VolSurface ()
VolSurface ()
default c'tor
VolSurface (VolSurfaceBase *p)
Constructor to be used with an existing object.
VolSurface (const VolSurface &vsurf)
Constructor to be used with an existing object.
VolSurface & operator= (const VolSurface &vsurf)
Geometry::Volume volume () const
the volume to which this surface is attached.
VolSurfaceBase * ptr () const
pointer to underlying object
virtual long64 id () const
The id of this surface - always 0 for VolSurfaces.
virtual const SurfaceType & type () const
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
Access to the normal direction at the given point.
virtual const Vector3D & origin () const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double innerThickness () const
virtual double outerThickness () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual double distance (const Vector3D &point) const
virtual bool insideBounds (const Vector3D &point, double epsilon=1e-4) const
Checks if the given point lies within the surface.
virtual std::vector< std::pair
< Vector3D, Vector3D > > getLines (unsigned nMax=100)
void setInnerMaterial (const IMaterial &mat)
set the innerMaterial
void setOuterMaterial (const IMaterial &mat)
set the outer Materal
Protected Attributes
VolSurfaceBase * _surf
Detailed Description
Reference counted handle class for a local surface attached to a volume (VolSurfaceBase).
Author:
F.Gaede, DESY
Date:
Sep, 14 2015
Version:
$Id$
Definition at line 194 of file Surface.h.
Constructor & Destructor Documentation
virtual DD4hep::DDRec::VolSurface::~VolSurface () [inline, virtual]
Definition at line 202 of file Surface.h.
References DD4hep::DDRec::VolSurfaceBase::_refCount, and _surf.
DD4hep::DDRec::VolSurface::VolSurface () [inline]
default c'tor
Definition at line 209 of file Surface.h.
DD4hep::DDRec::VolSurface::VolSurface (VolSurfaceBase * p) [inline]
Constructor to be used with an existing object.
Definition at line 212 of file Surface.h.
References DD4hep::DDRec::VolSurfaceBase::_refCount, and _surf.
DD4hep::DDRec::VolSurface::VolSurface (const VolSurface & vsurf) [inline]
Constructor to be used with an existing object.
Definition at line 215 of file Surface.h.
References DD4hep::DDRec::VolSurfaceBase::_refCount, and _surf.
Member Function Documentation
double DD4hep::DDRec::VolSurface::distance (const Vector3D & point) const [virtual]
Distance to surface
Implements DDSurfaces::ISurface.
Definition at line 241 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::distance().
Referenced by DD4hep::DDRec::Surface::distance().
std::vector< std::pair< Vector3D, Vector3D > > DD4hep::DDRec::VolSurface::getLines (unsigned nMax = 100) [virtual]
Definition at line 245 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::getLines().
Referenced by DD4hep::DDRec::Surface::getLines().
Vector2D DD4hep::DDRec::VolSurface::globalToLocal (const Vector3D & point) const [virtual]
Convert the global position to the local position (u,v) on the surface
Implements DDSurfaces::ISurface.
Definition at line 233 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::globalToLocal().
Referenced by DD4hep::DDRec::CylinderSurface::globalToLocal().
long64 DD4hep::DDRec::VolSurface::id () const [virtual]
The id of this surface - always 0 for VolSurfaces.
Implements DDSurfaces::ISurface.
Definition at line 227 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::id().
Referenced by DD4hep::DDRec::Surface::initialize().
const IMaterial & DD4hep::DDRec::VolSurface::innerMaterial () const [virtual]
Access to the material in opposite direction of the normal.
Implements DDSurfaces::ISurface.
Definition at line 235 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::innerMaterial().
Referenced by DD4hep::DDRec::Surface::innerMaterial().
double DD4hep::DDRec::VolSurface::innerThickness () const [virtual]
Thickness of inner material
Implements DDSurfaces::ISurface.
Definition at line 237 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::innerThickness().
Referenced by DD4hep::DDRec::Surface::innerThickness().
bool DD4hep::DDRec::VolSurface::insideBounds (const Vector3D & point, double epsilon = 1e-4) const [virtual]
Checks if the given point lies within the surface.
Implements DDSurfaces::ISurface.
Definition at line 242 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::insideBounds().
Referenced by DD4hep::DDRec::Surface::insideBounds().
double DD4hep::DDRec::VolSurface::length_along_u () const [virtual]
The length of the surface along direction u at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implements DDSurfaces::ISurface.
Definition at line 239 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::length_along_u().
Referenced by DD4hep::DDRec::Surface::length_along_u().
double DD4hep::DDRec::VolSurface::length_along_v () const [virtual]
The length of the surface along direction v at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implements DDSurfaces::ISurface.
Definition at line 240 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::length_along_v().
Referenced by DD4hep::DDRec::Surface::length_along_v().
Vector3D DD4hep::DDRec::VolSurface::localToGlobal (const Vector2D & point) const [virtual]
Convert the local position (u,v) on the surface to the global position
Implements DDSurfaces::ISurface.
Definition at line 234 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::localToGlobal().
Referenced by DD4hep::DDRec::CylinderSurface::localToGlobal().
Vector3D DD4hep::DDRec::VolSurface::normal (const Vector3D & point = Vector3D()) const [virtual]
Access to the normal direction at the given point.
Implements DDSurfaces::ISurface.
Definition at line 231 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::normal().
Referenced by DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::Surface::initialize(), and DD4hep::DDRec::CylinderSurface::normal().
VolSurface& DD4hep::DDRec::VolSurface::operator= (const VolSurface & vsurf) [inline]
Definition at line 219 of file Surface.h.
References DD4hep::DDRec::VolSurfaceBase::_refCount, and _surf.
const Vector3D & DD4hep::DDRec::VolSurface::origin () const [virtual]
Get Origin of local coordinate system on surface
Implements DDSurfaces::ISurface.
Definition at line 232 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::origin().
Referenced by DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::Surface::initialize(), and DD4hep::DDRec::CylinderSurface::radius().
const IMaterial & DD4hep::DDRec::VolSurface::outerMaterial () const [virtual]
Access to the material in direction of the normal.
Implements DDSurfaces::ISurface.
Definition at line 236 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::outerMaterial().
Referenced by DD4hep::DDRec::Surface::outerMaterial().
double DD4hep::DDRec::VolSurface::outerThickness () const [virtual]
Thickness of outer material
Implements DDSurfaces::ISurface.
Definition at line 238 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::outerThickness().
Referenced by DD4hep::DDRec::Surface::outerThickness().
VolSurfaceBase* DD4hep::DDRec::VolSurface::ptr () const [inline]
pointer to underlying object
Definition at line 230 of file Surface.h.
References _surf.
void DD4hep::DDRec::VolSurface::setInnerMaterial (const IMaterial & mat) [inline]
set the innerMaterial
Definition at line 292 of file Surface.h.
References _surf, and DD4hep::DDRec::VolSurfaceBase::setInnerMaterial().
Referenced by DD4hep::DDRec::Surface::innerMaterial().
void DD4hep::DDRec::VolSurface::setOuterMaterial (const IMaterial & mat) [inline]
set the outer Materal
Definition at line 295 of file Surface.h.
References _surf, and DD4hep::DDRec::VolSurfaceBase::setOuterMaterial().
Referenced by DD4hep::DDRec::Surface::outerMaterial().
const SurfaceType & DD4hep::DDRec::VolSurface::type () const [virtual]
properties of the surface encoded in Type.
See also:
SurfaceType
Implements DDSurfaces::ISurface.
Definition at line 228 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::type().
Referenced by DD4hep::DDRec::DetectorSurfaces::initialize().
Vector3D DD4hep::DDRec::VolSurface::u (const Vector3D & point = Vector3D()) const [virtual]
First direction of measurement U
Implements DDSurfaces::ISurface.
Definition at line 229 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::u().
Referenced by DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::Surface::initialize(), and DD4hep::DDRec::CylinderSurface::u().
Vector3D DD4hep::DDRec::VolSurface::v (const Vector3D & point = Vector3D()) const [virtual]
Second direction of measurement V
Implements DDSurfaces::ISurface.
Definition at line 230 of file Surface.cpp.
References _surf, and DD4hep::DDRec::VolSurfaceBase::v().
Referenced by DD4hep::DDRec::Surface::initialize(), DD4hep::DDRec::ConeSurface::radius0(), DD4hep::DDRec::ConeSurface::radius1(), DD4hep::DDRec::CylinderSurface::v(), DD4hep::DDRec::ConeSurface::z0(), and DD4hep::DDRec::ConeSurface::z1().
Geometry::Volume DD4hep::DDRec::VolSurface::volume () const [inline]
the volume to which this surface is attached.
Definition at line 227 of file Surface.h.
References _surf, and DD4hep::DDRec::VolSurfaceBase::volume().
Referenced by DD4hep::DDRec::Surface::initialize(), and DD4hep::DDRec::Surface::volume().
Member Data Documentation
VolSurfaceBase* DD4hep::DDRec::VolSurface::_surf [protected]
Definition at line 198 of file Surface.h.
Referenced by distance(), getLines(), globalToLocal(), id(), innerMaterial(), innerThickness(), insideBounds(), length_along_u(), length_along_v(), localToGlobal(), normal(), DD4hep::DDRec::VolSurfaceHandle< T >::operator->(), operator=(), origin(), outerMaterial(), outerThickness(), ptr(), setInnerMaterial(), setOuterMaterial(), type(), u(), v(), VolSurface(), volume(), and ~VolSurface().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp