DD4hep: DD4hep: DD4hep::Simulation::Geant4TrackingAction Class Reference
DD4hep::Simulation::Geant4TrackingAction Class Reference
[DD4hep::Simulation components, classes and objects]
Default base class for all geant 4 tracking actions used in DDG4.
#include <Geant4TrackingAction.h>
Public Types
typedef Geant4SharedTrackingAction shared_type
Public Member Functions
Geant4TrackingAction (Geant4Context *context, const std::string &name="")
Standard constructor.
virtual ~Geant4TrackingAction ()
Default destructor.
G4TrackingManager * trackMgr () const
Access the Geant4 tracking manager. Only use between tracking pre- and post action.
void mark (const G4Track *track) const
Mark the track to be kept for MC truth propagation.
virtual void begin (const G4Track *track)
Pre-track action callback.
virtual void end (const G4Track *track)
Post-track action callback.
Detailed Description
Default base class for all geant 4 tracking actions used in DDG4.
Author:
M.Frank
Version:
1.0
Definition at line 42 of file Geant4TrackingAction.h.
Member Typedef Documentation
typedef Geant4SharedTrackingAction DD4hep::Simulation::Geant4TrackingAction::shared_type
Definition at line 44 of file Geant4TrackingAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4TrackingAction::Geant4TrackingAction (Geant4Context * context, const std::string & name = "")
Standard constructor.
Geant4TrackingAction::~Geant4TrackingAction () [virtual]
Default destructor.
Definition at line 106 of file Geant4TrackingAction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4TrackingAction::begin (const G4Track * track) [virtual]
Pre-track action callback.
Reimplemented in DD4hep::Simulation::Test::Geant4TestTrackAction, DD4hep::Simulation::Geant4SharedTrackingAction, DD4hep::Simulation::Geant4TrackingPostAction, and DD4hep::Simulation::Geant4TrackingPreAction.
Definition at line 111 of file Geant4TrackingAction.cpp.
Referenced by DD4hep::Simulation::Geant4SharedTrackingAction::begin(), and DD4hep::Simulation::Geant4TrackingActionSequence::begin().
void Geant4TrackingAction::end (const G4Track * track) [virtual]
Post-track action callback.
Reimplemented in DD4hep::Simulation::Test::Geant4TestTrackAction, DD4hep::Simulation::Geant4SharedTrackingAction, DD4hep::Simulation::Geant4TrackingPostAction, and DD4hep::Simulation::Geant4TrackingPreAction.
Definition at line 115 of file Geant4TrackingAction.cpp.
Referenced by DD4hep::Simulation::Geant4SharedTrackingAction::end(), and DD4hep::Simulation::Geant4TrackingActionSequence::end().
void Geant4TrackingAction::mark (const G4Track * track) const
Mark the track to be kept for MC truth propagation.
Definition at line 119 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), and DD4hep::Simulation::Geant4MonteCarloTruth::mark().
G4TrackingManager* DD4hep::Simulation::Geant4TrackingAction::trackMgr () const [inline]
Access the Geant4 tracking manager. Only use between tracking pre- and post action.
Definition at line 51 of file Geant4TrackingAction.h.
References DD4hep::Simulation::Geant4Action::m_context, and DD4hep::Simulation::Geant4Context::trackMgr().
Referenced by DD4hep::Simulation::Geant4TrackingPreAction::begin(), DD4hep::Simulation::Geant4TrackingPostAction::begin(), and DD4hep::Simulation::Geant4TrackingPostAction::end().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TrackingAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TrackingAction.cpp