DD4hep: DD4hep::Geometry::HeaderObject Class Reference
DD4hep::Geometry::HeaderObject Class Reference
DD4hep::Geometry components, classes and objects
Concrete object implementation for the Header handle.
#include <ObjectsInterna.h>
Public Member Functions
HeaderObject ()
Standard constructor.
virtual ~HeaderObject ()
Default destructor.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
std::string url
std::string author
std::string status
std::string version
std::string comment
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Private Member Functions
HeaderObject (const HeaderObject &)
Private copy constructor.
HeaderObject & operator= (const HeaderObject &)
Private assignment operator.
Detailed Description
Concrete object implementation for the Header handle.
Author
M.Frank
Version
1.0
Definition at line 42 of file ObjectsInterna.h.
Constructor & Destructor Documentation
HeaderObject() [1/2]
HeaderObject::HeaderObject ()
Standard constructor.
Definition at line 41 of file ObjectsInterna.cpp.
References DD4hep::InstanceCount::increment().
~HeaderObject()
HeaderObject::~HeaderObject () virtual
Default destructor.
Definition at line 47 of file ObjectsInterna.cpp.
References DD4HEP_INSTANTIATE_HANDLE_NAMED(), and DD4hep::InstanceCount::decrement().
HeaderObject() [2/2]
DD4hep::Geometry::HeaderObject::HeaderObject (const HeaderObject &) inline private
Private copy constructor.
Definition at line 55 of file ObjectsInterna.h.
Member Function Documentation
operator=()
HeaderObject& DD4hep::Geometry::HeaderObject::operator= (const HeaderObject &) inline private
Private assignment operator.
Definition at line 57 of file ObjectsInterna.h.
Referenced by DD4hep::Geometry::HitCollection::HitCollection().
Member Data Documentation
author
std::string DD4hep::Geometry::HeaderObject::author
Definition at line 45 of file ObjectsInterna.h.
comment
std::string DD4hep::Geometry::HeaderObject::comment
Definition at line 48 of file ObjectsInterna.h.
status
std::string DD4hep::Geometry::HeaderObject::status
Definition at line 46 of file ObjectsInterna.h.
url
std::string DD4hep::Geometry::HeaderObject::url
Definition at line 44 of file ObjectsInterna.h.
version
std::string DD4hep::Geometry::HeaderObject::version
Definition at line 47 of file ObjectsInterna.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/ObjectsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ObjectsInterna.cpp