DD4hep: DD4hep: DD4hep::LayerStack Class Reference
DD4hep::LayerStack Class Reference
[DD4hep classes and objects]
Class to describe a layering stack.
#include <Layering.h>
Public Member Functions
LayerStack ()
Default constructor.
LayerStack (const LayerStack &c)
Copy constructor.
~LayerStack ()
Default destructor.
LayerStack & operator= (const LayerStack &c)
Assignment operator.
std::vector< Layer * > & layers ()
const std::vector< Layer * > & layers () const
double sectionThickness (size_t is, size_t ie) const
double totalThickness () const
Public Attributes
std::vector< Layer * > _layers
Detailed Description
Class to describe a layering stack.
Author:
M.Frank
Version:
1.0
Definition at line 97 of file Layering.h.
Constructor & Destructor Documentation
DD4hep::LayerStack::LayerStack () [inline]
Default constructor.
Definition at line 125 of file Layering.h.
DD4hep::LayerStack::LayerStack (const LayerStack & c) [inline]
Copy constructor.
Definition at line 128 of file Layering.h.
DD4hep::LayerStack::~LayerStack () [inline]
Default destructor.
Definition at line 105 of file Layering.h.
Member Function Documentation
const std::vector<Layer*>& DD4hep::LayerStack::layers () const [inline]
Definition at line 115 of file Layering.h.
References _layers.
std::vector<Layer*>& DD4hep::LayerStack::layers () [inline]
Definition at line 112 of file Layering.h.
References _layers.
Referenced by DD4hep::Layering::layer(), and DD4hep::Layering::layers().
LayerStack& DD4hep::LayerStack::operator= (const LayerStack & c) [inline]
Assignment operator.
Definition at line 108 of file Layering.h.
References _layers.
double LayerStack::sectionThickness (size_t is, size_t ie) const
Definition at line 58 of file Layering.cpp.
References _layers, and DD4hep::_toString().
Referenced by totalThickness().
double DD4hep::LayerStack::totalThickness () const [inline]
Definition at line 119 of file Layering.h.
References _layers, and sectionThickness().
Referenced by DD4hep::Layering::totalThickness().
Member Data Documentation
std::vector<Layer*> DD4hep::LayerStack::_layers
Definition at line 99 of file Layering.h.
Referenced by layers(), operator=(), sectionThickness(), and totalThickness().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/Layering.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/Layering.cpp