DD4hep: DD4hep: DD4hep::Simulation::Geant4SharedGeneratorAction Class Reference
DD4hep::Simulation::Geant4SharedGeneratorAction Class Reference
[DD4hep::Simulation components, classes and objects]
Implementation of the Geant4 shared generator action.
#include <Geant4GeneratorAction.h>
Public Member Functions
Geant4SharedGeneratorAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4SharedGeneratorAction ()
Default destructor.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
virtual void use (Geant4GeneratorAction *action)
Underlying object to be used during the execution of this thread.
virtual void operator() (G4Event *event)
User generator callback.
Protected Attributes
Geant4GeneratorAction * m_action
Reference to the shared action.
Detailed Description
Implementation of the Geant4 shared generator action.
Wrapper to share single instances of generator actions for multi-threaded purposes. The wrapper ensures the locking of the basic actions to avoid race conditions.
Shared action should be 'fast'. The global lock otherwise inhibits the efficient use of the multiple threads.
Author:
M.Frank
Version:
1.0
Definition at line 76 of file Geant4GeneratorAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4SharedGeneratorAction::Geant4SharedGeneratorAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4SharedGeneratorAction::~Geant4SharedGeneratorAction () [virtual]
Default destructor.
Definition at line 50 of file Geant4GeneratorAction.cpp.
References DD4hep::InstanceCount::decrement(), m_action, and DD4hep::releasePtr().
Member Function Documentation
void Geant4SharedGeneratorAction::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 56 of file Geant4GeneratorAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_action.
void Geant4SharedGeneratorAction::operator() (G4Event * event) [virtual]
User generator callback.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 71 of file Geant4GeneratorAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), and m_action.
void Geant4SharedGeneratorAction::use (Geant4GeneratorAction * action) [virtual]
Underlying object to be used during the execution of this thread.
Definition at line 61 of file Geant4GeneratorAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_action.
Member Data Documentation
Geant4GeneratorAction* DD4hep::Simulation::Geant4SharedGeneratorAction::m_action [protected]
Reference to the shared action.
Definition at line 79 of file Geant4GeneratorAction.h.
Referenced by configureFiber(), operator()(), use(), and ~Geant4SharedGeneratorAction().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4GeneratorAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4GeneratorAction.cpp