DD4hep: TiXmlDeclaration Class Reference
TiXmlDeclaration Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlDeclaration ()
Construct an empty declaration.
TiXmlDeclaration (const std::string &_version, const std::string &_encoding, const std::string &_standalone)
Constructor.
TiXmlDeclaration (const char *_version, const char *_encoding, const char *_standalone)
Construct.
TiXmlDeclaration (const TiXmlDeclaration &copy)
void operator= (const TiXmlDeclaration &copy)
virtual ~TiXmlDeclaration ()
const char * Version () const
Version. Will return an empty string if none was found.
const char * Encoding () const
Encoding. Will return an empty string if none was found.
const char * Standalone () const
Is this a standalone document?
virtual TiXmlNode * Clone () const
Creates a copy of this Declaration and returns it.
virtual void Print (FILE *cfile, int depth, TIXML_STRING *str) const
virtual void Print (FILE *cfile, int depth) const
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *visitor) const
Public Member Functions inherited from TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
const std::string & ValueStr () const
void SetValue (const char *_value)
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * PreviousSiblingElement () const
TiXmlElement * PreviousSiblingElement ()
const TiXmlElement * PreviousSiblingElement (const char *) const
TiXmlElement * PreviousSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
const TiXmlDocument * GetDocument () const
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
void CopyTo (TiXmlDeclaration *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Protected Member Functions inherited from TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Private Attributes
TIXML_STRING version
TIXML_STRING encoding
TIXML_STRING standalone
Additional Inherited Members
Public Types inherited from TiXmlNode
enum NodeType {
DOCUMENT, ELEMENT, COMMENT, UNKNOWN,
TEXT, DECLARATION, TYPECOUNT
}
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_DOCUMENT_TOP_ONLY, TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
In correct XML the declaration is the first entry in the file.
<?xml version="1.0" standalone="yes"?>
TinyXml will happily read or write files without a declaration, however. There are 3 possible attributes to the declaration: version, encoding, and standalone.
Note: In this version of the code, the attributes are handled as special cases, not generic attributes, simply because there can only be at most 3 and they are always the same.
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 1421 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlDeclaration() [1/4]
TiXmlDeclaration::TiXmlDeclaration () inline
Construct an empty declaration.
Definition at line 1424 of file tinyxml.h.
References DD4hep::Alignments::AlignmentTools::copy().
Referenced by Clone(), and TiXmlDeclaration().
TiXmlDeclaration() [2/4]
TiXmlDeclaration::TiXmlDeclaration (const std::string & _version, const std::string & _encoding, const std::string & _standalone)
Constructor.
TiXmlDeclaration() [3/4]
TiXmlDeclaration::TiXmlDeclaration (const char * _version, const char * _encoding, const char * _standalone)
Construct.
Definition at line 1404 of file tinyxml_inl.h.
References TiXmlNode::DECLARATION, encoding, standalone, TiXmlDeclaration(), TiXmlNode::TiXmlNode(), and version.
TiXmlDeclaration() [4/4]
TiXmlDeclaration::TiXmlDeclaration (const TiXmlDeclaration & copy)
Definition at line 1428 of file tinyxml_inl.h.
References CopyTo().
~TiXmlDeclaration()
virtual TiXmlDeclaration::~TiXmlDeclaration () inline virtual
Definition at line 1439 of file tinyxml.h.
Member Function Documentation
Accept()
bool TiXmlDeclaration::Accept (TiXmlVisitor * visitor) const virtual
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
Definition at line 1474 of file tinyxml_inl.h.
References TiXmlVisitor::Visit().
Clone()
TiXmlNode * TiXmlDeclaration::Clone () const virtual
Creates a copy of this Declaration and returns it.
Implements TiXmlNode.
Definition at line 1480 of file tinyxml_inl.h.
References CopyTo(), and TiXmlDeclaration().
CopyTo()
void TiXmlDeclaration::CopyTo (TiXmlDeclaration * target) const protected
Definition at line 1464 of file tinyxml_inl.h.
References TiXmlNode::CopyTo(), encoding, standalone, and version.
Referenced by Clone(), TiXmlUnknown::Clone(), operator=(), and TiXmlDeclaration().
Encoding()
const char* TiXmlDeclaration::Encoding () const inline
Encoding. Will return an empty string if none was found.
Definition at line 1447 of file tinyxml.h.
Referenced by TiXmlDocument::Parse().
operator=()
void TiXmlDeclaration::operator= (const TiXmlDeclaration & copy)
Definition at line 1435 of file tinyxml_inl.h.
References TiXmlNode::Clear(), and CopyTo().
Parse()
const char * TiXmlDeclaration::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements TiXmlBase.
Definition at line 1548 of file tinyxmlparser_inl.h.
References TiXmlParsingData::Cursor(), TiXmlNode::GetDocument(), TiXmlBase::IsWhiteSpace(), TiXmlBase::location, TiXmlAttribute::Parse(), TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlParsingData::Stamp(), TiXmlBase::StringEqual(), TiXmlBase::TIXML_ERROR_PARSING_DECLARATION, and TiXmlAttribute::Value().
Print() [1/2]
void TiXmlDeclaration::Print (FILE * cfile, int depth, TIXML_STRING * str) const virtual
Definition at line 1442 of file tinyxml_inl.h.
References encoding, standalone, and version.
Referenced by TiXmlPrinter::Visit().
Print() [2/2]
virtual void TiXmlDeclaration::Print (FILE * cfile, int depth) const inline virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements TiXmlBase.
Definition at line 1459 of file tinyxml.h.
Standalone()
const char* TiXmlDeclaration::Standalone () const inline
Is this a standalone document?
Definition at line 1451 of file tinyxml.h.
References TIXML_STRING.
StreamIn()
virtual void TiXmlDeclaration::StreamIn (std::istream * in, TIXML_STRING * tag) protected virtual
Implements TiXmlNode.
Referenced by TiXmlText::Parse().
ToDeclaration() [1/2]
virtual const TiXmlDeclaration* TiXmlDeclaration::ToDeclaration () const inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1465 of file tinyxml.h.
ToDeclaration() [2/2]
virtual TiXmlDeclaration* TiXmlDeclaration::ToDeclaration () inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1468 of file tinyxml.h.
References TIXML_STRING.
Version()
const char* TiXmlDeclaration::Version () const inline
Version. Will return an empty string if none was found.
Definition at line 1443 of file tinyxml.h.
Member Data Documentation
encoding
TIXML_STRING TiXmlDeclaration::encoding private
Definition at line 1485 of file tinyxml.h.
Referenced by CopyTo(), Print(), and TiXmlDeclaration().
standalone
TIXML_STRING TiXmlDeclaration::standalone private
Definition at line 1485 of file tinyxml.h.
Referenced by CopyTo(), Print(), and TiXmlDeclaration().
version
TIXML_STRING TiXmlDeclaration::version private
Definition at line 1485 of file tinyxml.h.
Referenced by CopyTo(), Print(), and TiXmlDeclaration().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h