DD4hep: DD4hep::Geometry::Region Class Reference
DD4hep::Geometry::Region Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing a region as used in simulation.
#include <Objects.h>
Public Types
typedef RegionObject Object
Implemeting class.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Region ()
Default constructor.
Region (const Region &e)
Copy Constructor.
Region (const Handle< RegionObject > &e)
Copy Constructor.
template<typename Q >
Region (const Handle< Q > &e)
Constructor to be used when assigning handle.
Region (const std::string &name)
Constructor to be used when creating a new object.
Region & operator= (const Region &c)
Assignment operator.
Region & setStoreSecondaries (bool value)
Region & setThreshold (double value)
Region & setCut (double value)
std::vector< std::string > & limits () const
Access references to user limits.
double cut () const
Access cut value.
double threshold () const
Access production threshold.
bool storeSecondaries () const
Access secondaries flag.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing a region as used in simulation.
Author
M.Frank
Version
1.0
Definition at line 516 of file Objects.h.
Member Typedef Documentation
Object
typedef RegionObject DD4hep::Geometry::Region::Object
Implemeting class.
Definition at line 519 of file Objects.h.
Constructor & Destructor Documentation
Region() [1/5]
DD4hep::Geometry::Region::Region () inline
Default constructor.
Definition at line 521 of file Objects.h.
Region() [2/5]
DD4hep::Geometry::Region::Region (const Region & e) inline
Copy Constructor.
Definition at line 525 of file Objects.h.
References e.
Region() [3/5]
DD4hep::Geometry::Region::Region (const Handle< RegionObject > & e) inline
Copy Constructor.
Definition at line 530 of file Objects.h.
Region() [4/5]
template<typename Q > DD4hep::Geometry::Region::Region (const Handle< Q > & e) inline
Constructor to be used when assigning handle.
Definition at line 536 of file Objects.h.
References DD4hep::Handle< T >::name().
Region() [5/5]
Region::Region (const std::string & name)
Constructor to be used when creating a new object.
Constructor to be used when creating a new DOM tree.
Definition at line 440 of file Objects.cpp.
References DD4hep::Geometry::RegionObject::cut, DD4hep::Geometry::RegionObject::magic, DD4hep::magic_word(), DD4hep::Geometry::RegionObject::store_secondaries, and DD4hep::Geometry::RegionObject::threshold.
Member Function Documentation
cut()
double Region::cut () const
Access cut value.
Definition at line 470 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleRegion().
limits()
vector< string > & Region::limits () const
Access references to user limits.
Definition at line 465 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleRegion().
operator=()
Region& DD4hep::Geometry::Region::operator= (const Region & c) inline
Assignment operator.
Definition at line 542 of file Objects.h.
References DD4hep::Handle< T >::m_element.
setCut()
Region & Region::setCut (double value)
Definition at line 459 of file Objects.cpp.
setStoreSecondaries()
Region & Region::setStoreSecondaries (bool value)
Definition at line 449 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::endDocument().
setThreshold()
Region & Region::setThreshold (double value)
Definition at line 454 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::endDocument().
storeSecondaries()
bool Region::storeSecondaries () const
Access secondaries flag.
Definition at line 480 of file Objects.cpp.
References e, DD4hep::Geometry::IDDescriptor::fields(), DD4hep::Geometry::IDDescriptor::ids(), m, and DD4hep::Geometry::IDDescriptor::maxBit().
Referenced by DD4hep::Simulation::Geant4Converter::handleRegion().
threshold()
double Region::threshold () const
Access production threshold.
Definition at line 475 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleRegion().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp