DD4hep: DD4hep: DD4hep::Simulation::Geant4Context Class Reference
DD4hep::Simulation::Geant4Context Class Reference
[DD4hep::Simulation components, classes and objects]
Generic context to extend user, run and event information.
#include <Geant4Context.h>
Public Member Functions
virtual ~Geant4Context ()
Default destructor.
void setRun (Geant4Run *new_run)
Set the geant4 run reference.
Geant4Run & run () const
Access the geant4 run -- valid only between BeginRun() and EndRun()!
Geant4Run * runPtr () const
Access the geant4 run by ptr. Must be checked by clients!
void setEvent (Geant4Event *new_event)
Set the geant4 event reference.
Geant4Event & event () const
Access the geant4 event -- valid only between BeginEvent() and EndEvent()!
Geant4Event * eventPtr () const
Access the geant4 event by ptr. Must be checked by clients!
Geant4Kernel & kernel () const
Access to the kernel object.
Geometry::LCDD & lcdd () const
Access to detector description.
G4TrackingManager * trackMgr () const
Access the tracking manager.
virtual G4VTrajectory * createTrajectory (const G4Track *track) const
Create a user trajectory.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Geant4SensDetSequences & sensitiveActions () const
Access to the sensitive detector sequences from the kernel object.
Protected Member Functions
Geant4Context (Geant4Kernel *kernel)
Default constructor.
Protected Attributes
Geant4Kernel * m_kernel
Geant4Run * m_run
Geant4Event * m_event
Friends
class Geant4Kernel
Detailed Description
Generic context to extend user, run and event information.
Author:
M.Frank
Version:
1.0
Definition at line 168 of file Geant4Context.h.
Constructor & Destructor Documentation
Geant4Context::Geant4Context (Geant4Kernel * kernel) [protected]
Default constructor.
Definition at line 53 of file Geant4Context.cpp.
References DD4hep::InstanceCount::increment().
Geant4Context::~Geant4Context () [virtual]
Default destructor.
Definition at line 59 of file Geant4Context.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
G4VTrajectory * Geant4Context::createTrajectory (const G4Track * track) const [virtual]
Create a user trajectory.
Definition at line 94 of file Geant4Context.cpp.
References DD4hep::FATAL, DD4hep::format(), and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4TrackingPreAction::begin(), and DD4hep::Simulation::Geant4TrackingPostAction::begin().
Geant4Event & Geant4Context::event () const
Access the geant4 event -- valid only between BeginEvent() and EndEvent()!
Definition at line 82 of file Geant4Context.cpp.
References m_event.
Referenced by DD4hep::Simulation::Test::Geant4TestSensitive::begin(), DD4hep::Simulation::Test::Geant4TestTrackAction::begin(), DD4hep::Simulation::Test::Geant4TestEventAction::begin(), DD4hep::Simulation::Geant4Output2LCIO::begin(), DD4hep::Simulation::Geant4ParticleHandler::beginEvent(), DD4hep::Simulation::Geant4Output2LCIO::commit(), DD4hep::Simulation::Test::Geant4TestSensitive::end(), DD4hep::Simulation::Test::Geant4TestTrackAction::end(), DD4hep::Simulation::Test::Geant4TestEventAction::end(), DD4hep::Simulation::Geant4OutputAction::end(), DD4hep::Simulation::Geant4ParticleHandler::endEvent(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::generationInitialization(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionCosTheta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionEta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionFFbar(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionUniform(), DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), DD4hep::Simulation::Geant4TrackingAction::mark(), DD4hep::Simulation::Geant4Sensitive::mark(), DD4hep::Simulation::mergeInteractions(), DD4hep::Simulation::Geant4ParticleHandler::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::operator()(), DD4hep::Simulation::Geant4InteractionVertexSmear::operator()(), DD4hep::Simulation::Geant4InteractionVertexBoost::operator()(), DD4hep::Simulation::Geant4InteractionMerger::operator()(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4GeneratorWrapper::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::printInteraction(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), DD4hep::Simulation::Test::Geant4TestSensitive::process(), DD4hep::Simulation::Geant4ParticleHandler::rebaseSimulatedTracks(), DD4hep::Simulation::Geant4Output2LCIO::saveCollection(), DD4hep::Simulation::Geant4Output2ROOT::saveEvent(), DD4hep::Simulation::Geant4Output2LCIO::saveEvent(), and DD4hep::Simulation::Geant4InteractionVertexSmear::smear().
Geant4EventActionSequence & Geant4Context::eventAction () const
Access to the main event action sequence from the kernel object.
Definition at line 111 of file Geant4Context.cpp.
References DD4hep::Simulation::Geant4ActionContainer::eventAction(), and m_kernel.
Geant4Event* DD4hep::Simulation::Geant4Context::eventPtr () const [inline]
Access the geant4 event by ptr. Must be checked by clients!
Definition at line 196 of file Geant4Context.h.
References m_event.
Referenced by DD4hep::Simulation::Test::Geant4TestRunAction::beginEvent(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::destroyClientContext(), DD4hep::Simulation::Test::Geant4TestRunAction::endEvent(), and DD4hep::Simulation::Test::Geant4TestGeneratorAction::operator()().
Geant4GeneratorActionSequence & Geant4Context::generatorAction () const
Access to the main generator action sequence from the kernel object.
Definition at line 131 of file Geant4Context.cpp.
References DD4hep::Simulation::Geant4ActionContainer::generatorAction(), and m_kernel.
Geant4Kernel& DD4hep::Simulation::Geant4Context::kernel () const [inline]
Access to the kernel object.
Definition at line 198 of file Geant4Context.h.
References m_kernel.
Referenced by DD4hep::Simulation::Geant4Action::eventAction(), DD4hep::Simulation::Geant4GeneratorActionInit::Geant4GeneratorActionInit(), DD4hep::Simulation::Geant4Action::generatorAction(), DD4hep::Simulation::Geant4Action::installMessengers(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::kernel(), DD4hep::Simulation::Geant4UserTrackingAction::PostUserTrackingAction(), DD4hep::Simulation::Geant4UserTrackingAction::PreUserTrackingAction(), DD4hep::Simulation::Geant4Action::runAction(), DD4hep::Simulation::Geant4Action::stackingAction(), DD4hep::Simulation::Geant4UIManager::start(), DD4hep::Simulation::Geant4Action::steppingAction(), and DD4hep::Simulation::Geant4Action::trackingAction().
Geometry::LCDD & Geant4Context::lcdd () const
Access to detector description.
Definition at line 89 of file Geant4Context.cpp.
References DD4hep::Simulation::Geant4Kernel::lcdd(), and m_kernel.
Geant4Run & Geant4Context::run () const
Access the geant4 run -- valid only between BeginRun() and EndRun()!
Definition at line 70 of file Geant4Context.cpp.
References m_run.
Referenced by DD4hep::Simulation::Test::Geant4TestSensitive::begin(), DD4hep::Simulation::Test::Geant4TestTrackAction::begin(), DD4hep::Simulation::Test::Geant4TestEventAction::begin(), DD4hep::Simulation::Test::Geant4TestRunAction::begin(), DD4hep::Simulation::Test::Geant4TestSensitive::end(), DD4hep::Simulation::Test::Geant4TestTrackAction::end(), DD4hep::Simulation::Test::Geant4TestEventAction::end(), DD4hep::Simulation::Test::Geant4TestRunAction::end(), and DD4hep::Simulation::Test::Geant4TestSensitive::process().
Geant4RunActionSequence & Geant4Context::runAction () const
Access to the main run action sequence from the kernel object.
Definition at line 106 of file Geant4Context.cpp.
References m_kernel, and DD4hep::Simulation::Geant4ActionContainer::runAction().
Referenced by DD4hep::Simulation::Geant4OutputAction::configureFiber().
Geant4Run* DD4hep::Simulation::Geant4Context::runPtr () const [inline]
Access the geant4 run by ptr. Must be checked by clients!
Definition at line 190 of file Geant4Context.h.
References m_run.
Referenced by DD4hep::Simulation::Test::Geant4TestRunAction::beginEvent(), DD4hep::Simulation::Test::Geant4TestEventAction::beginRun(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::destroyClientContext(), DD4hep::Simulation::Test::Geant4TestRunAction::endEvent(), DD4hep::Simulation::Test::Geant4TestEventAction::endRun(), and DD4hep::Simulation::Test::Geant4TestGeneratorAction::operator()().
Geant4SensDetSequences & Geant4Context::sensitiveActions () const
Access to the sensitive detector sequences from the kernel object.
Access to the main generator action sequence from the kernel object.
Definition at line 136 of file Geant4Context.cpp.
References m_kernel, and DD4hep::Simulation::Geant4ActionContainer::sensitiveActions().
void Geant4Context::setEvent (Geant4Event * new_event)
Set the geant4 event reference.
Definition at line 77 of file Geant4Context.cpp.
References m_event.
Referenced by DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::createClientContext(), and DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::destroyClientContext().
void Geant4Context::setRun (Geant4Run * new_run)
Set the geant4 run reference.
Definition at line 65 of file Geant4Context.cpp.
References m_run.
Referenced by DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::createClientContext(), and DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::destroyClientContext().
Geant4StackingActionSequence & Geant4Context::stackingAction () const
Access to the main stacking action sequence from the kernel object.
Definition at line 126 of file Geant4Context.cpp.
References m_kernel, and DD4hep::Simulation::Geant4ActionContainer::stackingAction().
Geant4SteppingActionSequence & Geant4Context::steppingAction () const
Access to the main stepping action sequence from the kernel object.
Definition at line 116 of file Geant4Context.cpp.
References m_kernel, and DD4hep::Simulation::Geant4ActionContainer::steppingAction().
Geant4TrackingActionSequence & Geant4Context::trackingAction () const
Access to the main tracking action sequence from the kernel object.
Definition at line 121 of file Geant4Context.cpp.
References m_kernel, and DD4hep::Simulation::Geant4ActionContainer::trackingAction().
G4TrackingManager * Geant4Context::trackMgr () const
Access the tracking manager.
Definition at line 101 of file Geant4Context.cpp.
References m_kernel, and DD4hep::Simulation::Geant4Kernel::trackMgr().
Referenced by DD4hep::Simulation::Geant4TrackingAction::trackMgr().
Friends And Related Function Documentation
friend class Geant4Kernel [friend]
Definition at line 169 of file Geant4Context.h.
Member Data Documentation
Geant4Event* DD4hep::Simulation::Geant4Context::m_event [protected]
Definition at line 179 of file Geant4Context.h.
Referenced by event(), eventPtr(), and setEvent().
Geant4Kernel* DD4hep::Simulation::Geant4Context::m_kernel [protected]
Definition at line 177 of file Geant4Context.h.
Referenced by eventAction(), generatorAction(), kernel(), lcdd(), runAction(), sensitiveActions(), stackingAction(), steppingAction(), trackingAction(), and trackMgr().
Geant4Run* DD4hep::Simulation::Geant4Context::m_run [protected]
Definition at line 178 of file Geant4Context.h.
Referenced by run(), runPtr(), and setRun().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Context.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Context.cpp