DD4hep: DD4hep::Simulation::Geant4SensDetActionSequence Class Reference
DD4hep::Simulation::Geant4SensDetActionSequence Class Reference
DD4hep::Simulation components, classes and objects
The sequencer to host Geant4 sensitive actions called if particles interact with sensitive elements.
#include <Geant4SensDetAction.h>
Public Types
typedef Geometry::SensitiveDetector SensitiveDetector
typedef Geant4HitCollection *(* create_t) (const std::string &, const std::string &, Geant4Sensitive *)
typedef std::pair< std::string, std::pair< Geant4Sensitive *, create_t > > HitCollection
typedef std::vector< HitCollection > HitCollections
Public Member Functions
Geant4SensDetActionSequence (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4SensDetActionSequence ()
Default destructor.
virtual const std::string & sensitiveType () const
Access to the sensitive type of the detector.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
size_t defineCollections (Geant4ActionSD *sens_det)
Called at construction time of the sensitive detector to declare all hit collections.
size_t defineCollection (Geant4Sensitive *owner, const std::string &name, create_t func)
Initialize the usage of a hit collection. Returns the collection identifier.
template<typename TYPE >
size_t defineCollection (Geant4Sensitive *owner, const std::string &coll_name)
Define a named collection containing hist of a specified type.
const std::string & hitCollectionName (size_t which) const
Access HitCollection container names.
Geant4HitCollection * collection (size_t which) const
Retrieve the hits collection associated with this detector by its serial number.
Geant4HitCollection * collectionByID (size_t id) const
Retrieve the hits collection associated with this detector by its collection identifier.
template<typename T >
void callAtBegin (T *p, void(T::*f)(G4HCofThisEvent *))
Register begin-of-event callback.
template<typename T >
void callAtEnd (T *p, void(T::*f)(G4HCofThisEvent *))
Register end-of-event callback.
template<typename T >
void callAtProcess (T *p, void(T::*f)(G4Step *, G4TouchableHistory *))
Register process-hit callback.
template<typename T >
void callAtClear (T *p, void(T::*f)(G4HCofThisEvent *))
Register clear callback.
void adopt (Geant4Sensitive *sensitive)
Add an actor responding to all callbacks. Sequence takes ownership.
void adopt (Geant4Filter *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adoptFilter (Geant4Action *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
bool accept (const G4Step *step) const
Callback before hit processing starts. Invoke all filters.
virtual bool process (G4Step *step, G4TouchableHistory *hist)
Function to process hits.
virtual void begin (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the begining of each event.
virtual void end (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the end of each event.
virtual void clear ()
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Static Protected Member Functions
template<typename TYPE >
static Geant4HitCollection * _create (const std::string &det, const std::string &coll, Geant4Sensitive *sd)
Create a new typed hit collection.
Protected Attributes
G4HCofThisEvent * m_hce
Geant4 hit collection context.
CallbackSequence m_begin
Callback sequence for event initialization action.
CallbackSequence m_end
Callback sequence for event finalization action.
CallbackSequence m_process
Callback sequence for step processing.
CallbackSequence m_clear
Callback sequence to invoke the event deletion.
Actors< Geant4Sensitive > m_actors
The list of sensitive detector objects.
Actors< Geant4Filter > m_filters
The list of sensitive detector filter objects.
HitCollections m_collections
Hit collection creators.
SensitiveDetector m_sensitive
Reference to the sensitive detector element.
Geant4ActionSD * m_detector
Reference to G4 sensitive detector.
std::string m_sensitiveType
The true sensitive type of the detector.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
The sequencer to host Geant4 sensitive actions called if particles interact with sensitive elements.
Concrete implementation of the sensitive detector action sequence
Author
M.Frank
Version
1.0
Definition at line 282 of file Geant4SensDetAction.h.
Member Typedef Documentation
create_t
typedef Geant4HitCollection*(* DD4hep::Simulation::Geant4SensDetActionSequence::create_t) (const std::string &, const std::string &, Geant4Sensitive *)
Definition at line 286 of file Geant4SensDetAction.h.
HitCollection
typedef std::pair<std::string, std::pair<Geant4Sensitive*,create_t> > DD4hep::Simulation::Geant4SensDetActionSequence::HitCollection
Definition at line 287 of file Geant4SensDetAction.h.
HitCollections
typedef std::vector<HitCollection> DD4hep::Simulation::Geant4SensDetActionSequence::HitCollections
Definition at line 288 of file Geant4SensDetAction.h.
SensitiveDetector
typedef Geometry::SensitiveDetector DD4hep::Simulation::Geant4SensDetActionSequence::SensitiveDetector
Definition at line 285 of file Geant4SensDetAction.h.
Constructor & Destructor Documentation
Geant4SensDetActionSequence()
Geant4SensDetActionSequence::Geant4SensDetActionSequence (Geant4Context * context, const std::string & name)
Standard constructor.
Update the sensitive detector type, so that the proper instance is created
Definition at line 242 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::InstanceCount::increment(), DD4hep::Simulation::Geant4SensDetSequences::insert(), DD4hep::Simulation::Geant4Context::lcdd(), DD4hep::Simulation::Geant4Action::m_needsControl, m_sensitive, m_sensitiveType, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4Context::sensitiveActions(), DD4hep::Geometry::LCDD::sensitiveDetector(), DD4hep::Geometry::SensitiveDetector::setType(), and DD4hep::Geometry::SensitiveDetector::type().
~Geant4SensDetActionSequence()
Geant4SensDetActionSequence::~Geant4SensDetActionSequence () virtual
Default destructor.
Definition at line 255 of file Geant4SensDetAction.cpp.
References DD4hep::InstanceCount::decrement(), m_actors, m_filters, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
_create()
template<typename TYPE > static Geant4HitCollection* DD4hep::Simulation::Geant4SensDetActionSequence::_create (const std::string & det, const std::string & coll, Geant4Sensitive * sd) inline static protected
Create a new typed hit collection.
Definition at line 316 of file Geant4SensDetAction.h.
accept()
bool Geant4SensDetActionSequence::accept (const G4Step * step) const
Callback before hit processing starts. Invoke all filters.
Return fals if any filter returns false
Definition at line 348 of file Geant4SensDetAction.cpp.
References m_filters.
adopt() [1/2]
void Geant4SensDetActionSequence::adopt (Geant4Sensitive * sensitive)
Add an actor responding to all callbacks. Sequence takes ownership.
Add an actor responding to all callbacks.
Definition at line 277 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by adoptFilter().
adopt() [2/2]
void Geant4SensDetActionSequence::adopt (Geant4Filter * filter)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 287 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_filters.
adoptFilter()
void Geant4SensDetActionSequence::adoptFilter (Geant4Action * filter)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 271 of file Geant4SensDetAction.cpp.
References adopt().
begin()
void Geant4SensDetActionSequence::begin (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked at the begining of each event.
The hits collection(s) created by this sensitive detector must be set to the G4HCofThisEvent object at one of these two methods.
G4VSensitiveDetector interface: Method invoked at the begining of each event. The hits collection(s) created by this sensitive detector must be set to the G4HCofThisEvent object at one of these two methods.
Definition at line 369 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Sensitive::begin(), DD4hep::Simulation::Geant4ActionSD::GetCollectionID(), m_actors, m_begin, m_collections, m_detector, m_hce, and DD4hep::Simulation::Geant4Action::name().
callAtBegin()
template<typename T > void DD4hep::Simulation::Geant4SensDetActionSequence::callAtBegin (T * p, void(T::*)(G4HCofThisEvent *) f) inline
Register begin-of-event callback.
Definition at line 353 of file Geant4SensDetAction.h.
References DD4hep::CallbackSequence::add().
callAtClear()
template<typename T > void DD4hep::Simulation::Geant4SensDetActionSequence::callAtClear (T * p, void(T::*)(G4HCofThisEvent *) f) inline
Register clear callback.
Definition at line 368 of file Geant4SensDetAction.h.
References DD4hep::CallbackSequence::add().
callAtEnd()
template<typename T > void DD4hep::Simulation::Geant4SensDetActionSequence::callAtEnd (T * p, void(T::*)(G4HCofThisEvent *) f) inline
Register end-of-event callback.
Definition at line 358 of file Geant4SensDetAction.h.
References DD4hep::CallbackSequence::add().
callAtProcess()
template<typename T > void DD4hep::Simulation::Geant4SensDetActionSequence::callAtProcess (T * p, void(T::*)(G4Step *, G4TouchableHistory *) f) inline
Register process-hit callback.
Definition at line 363 of file Geant4SensDetAction.h.
References DD4hep::CallbackSequence::add().
clear()
void Geant4SensDetActionSequence::clear () virtual
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Hits collections created but not beibg set to G4HCofThisEvent at the event should be deleted. Collection(s) which have already set to G4HCofThisEvent will be deleted automatically.
Hits collections created but not being set to G4HCofThisEvent at the event should be deleted. Collection(s) which have already set to G4HCofThisEvent will be deleted automatically.
Definition at line 394 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Sensitive::clear(), m_actors, m_clear, and m_hce.
collection()
Geant4HitCollection * Geant4SensDetActionSequence::collection (size_t which) const
Retrieve the hits collection associated with this detector by its serial number.
Definition at line 326 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4ActionSD::GetCollectionID(), m_collections, m_detector, and m_hce.
Referenced by DD4hep::Simulation::Geant4Sensitive::collection().
collectionByID()
Geant4HitCollection * Geant4SensDetActionSequence::collectionByID (size_t id) const
Retrieve the hits collection associated with this detector by its collection identifier.
Definition at line 339 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), and m_hce.
Referenced by DD4hep::Simulation::Geant4Sensitive::collectionByID().
defineCollection() [1/2]
size_t Geant4SensDetActionSequence::defineCollection (Geant4Sensitive * owner, const std::string & name, create_t func)
Initialize the usage of a hit collection. Returns the collection identifier.
Definition at line 297 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4ActionSD::defineCollection(), DD4hep::Simulation::Geant4Sensitive::defineCollections(), m_actors, m_collections, m_detector, and DD4hep::Simulation::Geant4Sensitive::setDetector().
defineCollection() [2/2]
template<typename TYPE > size_t DD4hep::Simulation::Geant4SensDetActionSequence::defineCollection (Geant4Sensitive * owner, const std::string & coll_name) inline
Define a named collection containing hist of a specified type.
Definition at line 342 of file Geant4SensDetAction.h.
defineCollections()
size_t DD4hep::Simulation::Geant4SensDetActionSequence::defineCollections (Geant4ActionSD * sens_det)
Called at construction time of the sensitive detector to declare all hit collections.
end()
void Geant4SensDetActionSequence::end (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked at the end of each event.
Definition at line 382 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Sensitive::end(), m_actors, and m_end.
hitCollectionName()
const std::string & Geant4SensDetActionSequence::hitCollectionName (size_t which) const
Access HitCollection container names.
Definition at line 316 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), and m_collections.
Referenced by DD4hep::Simulation::Geant4Sensitive::hitCollectionName().
process()
bool Geant4SensDetActionSequence::process (G4Step * step, G4TouchableHistory * hist) virtual
Function to process hits.
Definition at line 354 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Sensitive::accept(), m_actors, m_process, DD4hep::Simulation::Geant4Sensitive::process(), and s.
sensitiveType()
virtual const std::string& DD4hep::Simulation::Geant4SensDetActionSequence::sensitiveType () const inline virtual
Access to the sensitive type of the detector.
Definition at line 328 of file Geant4SensDetAction.h.
updateContext()
void Geant4SensDetActionSequence::updateContext (Geant4Context * ctxt) virtual
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 264 of file Geant4SensDetAction.cpp.
References m_actors, DD4hep::Simulation::Geant4Action::m_context, and m_filters.
Member Data Documentation
m_actors
Actors<Geant4Sensitive> DD4hep::Simulation::Geant4SensDetActionSequence::m_actors protected
The list of sensitive detector objects.
Definition at line 302 of file Geant4SensDetAction.h.
Referenced by adopt(), begin(), clear(), defineCollection(), end(), process(), updateContext(), and ~Geant4SensDetActionSequence().
m_begin
CallbackSequence DD4hep::Simulation::Geant4SensDetActionSequence::m_begin protected
Callback sequence for event initialization action.
Definition at line 294 of file Geant4SensDetAction.h.
Referenced by begin().
m_clear
CallbackSequence DD4hep::Simulation::Geant4SensDetActionSequence::m_clear protected
Callback sequence to invoke the event deletion.
Definition at line 300 of file Geant4SensDetAction.h.
Referenced by clear().
m_collections
HitCollections DD4hep::Simulation::Geant4SensDetActionSequence::m_collections protected
Hit collection creators.
Definition at line 307 of file Geant4SensDetAction.h.
Referenced by begin(), collection(), defineCollection(), and hitCollectionName().
m_detector
Geant4ActionSD* DD4hep::Simulation::Geant4SensDetActionSequence::m_detector protected
Reference to G4 sensitive detector.
Definition at line 311 of file Geant4SensDetAction.h.
Referenced by begin(), collection(), and defineCollection().
m_end
CallbackSequence DD4hep::Simulation::Geant4SensDetActionSequence::m_end protected
Callback sequence for event finalization action.
Definition at line 296 of file Geant4SensDetAction.h.
Referenced by end().
m_filters
Actors<Geant4Filter> DD4hep::Simulation::Geant4SensDetActionSequence::m_filters protected
The list of sensitive detector filter objects.
Definition at line 304 of file Geant4SensDetAction.h.
Referenced by accept(), adopt(), updateContext(), and ~Geant4SensDetActionSequence().
m_hce
G4HCofThisEvent* DD4hep::Simulation::Geant4SensDetActionSequence::m_hce protected
Geant4 hit collection context.
Definition at line 292 of file Geant4SensDetAction.h.
Referenced by begin(), clear(), collection(), and collectionByID().
m_process
CallbackSequence DD4hep::Simulation::Geant4SensDetActionSequence::m_process protected
Callback sequence for step processing.
Definition at line 298 of file Geant4SensDetAction.h.
Referenced by process().
m_sensitive
SensitiveDetector DD4hep::Simulation::Geant4SensDetActionSequence::m_sensitive protected
Reference to the sensitive detector element.
Definition at line 309 of file Geant4SensDetAction.h.
Referenced by Geant4SensDetActionSequence().
m_sensitiveType
std::string DD4hep::Simulation::Geant4SensDetActionSequence::m_sensitiveType protected
The true sensitive type of the detector.
Definition at line 313 of file Geant4SensDetAction.h.
Referenced by Geant4SensDetActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensDetAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SensDetAction.cpp