DD4hep: DD4hep::Alignments::Alignment Class Reference
DD4hep::Alignments::Alignment Class Reference
DD4hep::Geometry components, classes and objects | DDAlign: DD4hep Detector geometry alignment components.
Main handle class to hold an alignment object.
#include <Alignments.h>
Public Types
typedef AlignmentData Object
Forward definition of the base data object containing alignment data.
typedef AlignmentData Data
Forward definition of the base data object containing alignment data.
typedef Geometry::PlacedVolume PlacedVolume
Forward definition of the geometry placement.
typedef std::vector< PlacedVolume > NodeList
Forward definition of the nodelist leading to the world.
typedef Alignments::Delta Delta
Forward definition of the alignment delta data.
typedef unsigned int key_type
Forward definition of the key type.
typedef IOV iov_type
Forward definition of the iov type.
Public Types inherited from DD4hep::Handle< AlignmentData >
typedef AlignmentData Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Alignment ()
Default constructor.
Alignment (Object *p)
Default constructor.
template<typename Q >
Alignment (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
Alignment (const std::string &name)
Object constructor for pure alignment objects.
Data & data ()
Data accessor for the use of decorators.
const Data & data () const
Data accessor for the use of decorators.
const TGeoHMatrix & worldTransformation () const
Create cached matrix to transform to world coordinates.
const TGeoHMatrix & detectorTransformation () const
Access the alignment/placement matrix with respect to the world.
Public Member Functions inherited from DD4hep::Handle< AlignmentData >
Handle ()
Defaulot constructor.
Handle (AlignmentData *e)
Initializing constructor from pointer.
Handle (const Handle< AlignmentData > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< AlignmentData > & operator= (const Handle< AlignmentData > &e)=default
Assignment operator.
bool operator== (const Handle< AlignmentData > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< AlignmentData > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< AlignmentData > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< AlignmentData > & clear ()
Release the object held by the handle.
AlignmentData * operator-> () const
Access the held object using the -> operator.
operator AlignmentData & () const
Automatic type conversion to an object references.
AlignmentData & operator* () const
Access the held object using the * operator.
AlignmentData * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
AlignmentData * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Static Public Member Functions
static key_type hashCode (const char *value)
Hash code generation from input string.
static key_type hashCode (const std::string &value)
Hash code generation from input string.
Static Public Member Functions inherited from DD4hep::Handle< AlignmentData >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Additional Inherited Members
Public Attributes inherited from DD4hep::Handle< AlignmentData >
AlignmentData * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Main handle class to hold an alignment object.
Author
M.Frank
Version
1.0
Definition at line 64 of file Alignments.h.
Member Typedef Documentation
Data
typedef AlignmentData DD4hep::Alignments::Alignment::Data
Forward definition of the base data object containing alignment data.
Definition at line 69 of file Alignments.h.
Delta
typedef Alignments::Delta DD4hep::Alignments::Alignment::Delta
Forward definition of the alignment delta data.
Definition at line 75 of file Alignments.h.
iov_type
typedef IOV DD4hep::Alignments::Alignment::iov_type
Forward definition of the iov type.
Definition at line 79 of file Alignments.h.
key_type
typedef unsigned int DD4hep::Alignments::Alignment::key_type
Forward definition of the key type.
Definition at line 77 of file Alignments.h.
NodeList
typedef std::vector<PlacedVolume> DD4hep::Alignments::Alignment::NodeList
Forward definition of the nodelist leading to the world.
Definition at line 73 of file Alignments.h.
Object
typedef AlignmentData DD4hep::Alignments::Alignment::Object
Forward definition of the base data object containing alignment data.
Definition at line 67 of file Alignments.h.
PlacedVolume
typedef Geometry::PlacedVolume DD4hep::Alignments::Alignment::PlacedVolume
Forward definition of the geometry placement.
Definition at line 71 of file Alignments.h.
Constructor & Destructor Documentation
Alignment() [1/4]
DD4hep::Alignments::Alignment::Alignment () inline
Default constructor.
Definition at line 83 of file Alignments.h.
Alignment() [2/4]
DD4hep::Alignments::Alignment::Alignment (Object * p) inline
Default constructor.
Definition at line 85 of file Alignments.h.
Alignment() [3/4]
template<typename Q > DD4hep::Alignments::Alignment::Alignment (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 87 of file Alignments.h.
Alignment() [4/4]
DD4hep::Alignments::Alignment::Alignment (const std::string & name)
Object constructor for pure alignment objects.
Initializing constructor to create a new object (Specialized for AlignmentNamedObject)
Definition at line 44 of file Alignments.cpp.
Member Function Documentation
data() [1/2]
Data& DD4hep::Alignments::Alignment::data () inline
Data accessor for the use of decorators.
Definition at line 98 of file Alignments.h.
data() [2/2]
const Data& DD4hep::Alignments::Alignment::data () const inline
Data accessor for the use of decorators.
Definition at line 100 of file Alignments.h.
detectorTransformation()
const TGeoHMatrix & Alignment::detectorTransformation () const
Access the alignment/placement matrix with respect to the world.
Definition at line 67 of file Alignments.cpp.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::to_world().
hashCode() [1/2]
Alignment::key_type DD4hep::Alignments::Alignment::hashCode (const char * value) inline static
Hash code generation from input string.
Definition at line 108 of file Alignments.h.
References DD4hep::hash32().
Referenced by DD4hep::Alignments::Interna::AlignmentContainer::addKey(), and DD4hep::Alignments::Interna::AlignmentContainer::get().
hashCode() [2/2]
Alignment::key_type DD4hep::Alignments::Alignment::hashCode (const std::string & value) inline static
Hash code generation from input string.
Definition at line 112 of file Alignments.h.
References DD4hep::hash32().
worldTransformation()
const TGeoHMatrix & Alignment::worldTransformation () const
Create cached matrix to transform to world coordinates.
Definition at line 62 of file Alignments.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Alignments.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Alignments.cpp