DD4hep: DD4hep::Simulation::SequenceHdl< T > Class Template Reference
DD4hep::Simulation::SequenceHdl< T > Class Template Reference
Sequence handler implementing common actions to all sequences.
Public Types
typedef SequenceHdl< T > Base
Public Member Functions
SequenceHdl ()
Default constructor.
SequenceHdl (Geant4Context *ctxt, T *seq)
virtual ~SequenceHdl ()
void _aquire (T *s)
void updateContext (Geant4Context *ctxt)
void _release ()
Geant4Context * context () const
Geant4Kernel & kernel () const
void configureFiber (Geant4Context *ctxt)
void createClientContext (const G4Run *run)
void destroyClientContext (const G4Run *)
void createClientContext (const G4Event *evt)
void destroyClientContext (const G4Event *)
Public Attributes
T * m_sequence
Geant4Context * m_activeContext
Detailed Description
template<typename T>
class DD4hep::Simulation::SequenceHdl< T >
Sequence handler implementing common actions to all sequences.
Definition at line 61 of file Geant4Exec.cpp.
Member Typedef Documentation
Base
template<typename T> typedef SequenceHdl<T> DD4hep::Simulation::SequenceHdl< T >::Base
Definition at line 63 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
SequenceHdl() [1/2]
template<typename T> DD4hep::Simulation::SequenceHdl< T >::SequenceHdl () inline
Default constructor.
Definition at line 67 of file Geant4Exec.cpp.
SequenceHdl() [2/2]
template<typename T> DD4hep::Simulation::SequenceHdl< T >::SequenceHdl (Geant4Context * ctxt, T * seq) inline
Definition at line 70 of file Geant4Exec.cpp.
~SequenceHdl()
template<typename T> virtual DD4hep::Simulation::SequenceHdl< T >::~SequenceHdl () inline virtual
Definition at line 73 of file Geant4Exec.cpp.
Member Function Documentation
_aquire()
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::_aquire (T * s) inline
Definition at line 76 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::SequenceHdl().
_release()
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::_release () inline
Definition at line 87 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::~SequenceHdl().
configureFiber()
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::configureFiber (Geant4Context * ctxt) inline
Definition at line 97 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserEventAction::Geant4UserEventAction(), DD4hep::Simulation::Geant4UserGeneratorAction::Geant4UserGeneratorAction(), DD4hep::Simulation::Geant4UserRunAction::Geant4UserRunAction(), DD4hep::Simulation::Geant4UserStackingAction::Geant4UserStackingAction(), DD4hep::Simulation::Geant4UserSteppingAction::Geant4UserSteppingAction(), and DD4hep::Simulation::Geant4UserTrackingAction::Geant4UserTrackingAction().
context()
template<typename T> Geant4Context* DD4hep::Simulation::SequenceHdl< T >::context () const inline
Definition at line 91 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::kernel().
createClientContext() [1/2]
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::createClientContext (const G4Run * run) inline
Definition at line 102 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserRunAction::BeginOfRunAction(), and DD4hep::Simulation::Geant4UserGeneratorAction::GeneratePrimaries().
createClientContext() [2/2]
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::createClientContext (const G4Event * evt) inline
Definition at line 113 of file Geant4Exec.cpp.
destroyClientContext() [1/2]
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::destroyClientContext (const G4Run *) inline
Definition at line 106 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserEventAction::EndOfEventAction(), and DD4hep::Simulation::Geant4UserRunAction::EndOfRunAction().
destroyClientContext() [2/2]
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::destroyClientContext (const G4Event *) inline
Definition at line 117 of file Geant4Exec.cpp.
kernel()
template<typename T> Geant4Kernel& DD4hep::Simulation::SequenceHdl< T >::kernel () const inline
Definition at line 94 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserEventAction::BeginOfEventAction(), DD4hep::Simulation::Geant4UserRunAction::BeginOfRunAction(), DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField(), DD4hep::Simulation::Geant4UserEventAction::EndOfEventAction(), DD4hep::Simulation::Geant4UserRunAction::EndOfRunAction(), and Geant4Compatibility::Geant4Compatibility().
updateContext()
template<typename T> void DD4hep::Simulation::SequenceHdl< T >::updateContext (Geant4Context * ctxt) inline
Definition at line 81 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserDetectorConstruction::Construct(), DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField(), DD4hep::Simulation::Geant4UserEventAction::Geant4UserEventAction(), DD4hep::Simulation::Geant4UserGeneratorAction::Geant4UserGeneratorAction(), DD4hep::Simulation::Geant4UserRunAction::Geant4UserRunAction(), DD4hep::Simulation::Geant4UserStackingAction::Geant4UserStackingAction(), DD4hep::Simulation::Geant4UserSteppingAction::Geant4UserSteppingAction(), and DD4hep::Simulation::Geant4UserTrackingAction::Geant4UserTrackingAction().
Member Data Documentation
m_activeContext
template<typename T> Geant4Context* DD4hep::Simulation::SequenceHdl< T >::m_activeContext mutable
Definition at line 65 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::context().
m_sequence
template<typename T> T* DD4hep::Simulation::SequenceHdl< T >::m_sequence
Definition at line 64 of file Geant4Exec.cpp.
Referenced by DD4hep::Simulation::Geant4UserEventAction::BeginOfEventAction(), DD4hep::Simulation::Geant4UserRunAction::BeginOfRunAction(), DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4UserActionInitialization::BuildForMaster(), DD4hep::Simulation::Geant4UserDetectorConstruction::Construct(), DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField(), DD4hep::Simulation::Geant4UserEventAction::EndOfEventAction(), DD4hep::Simulation::Geant4UserRunAction::EndOfRunAction(), DD4hep::Simulation::Geant4UserGeneratorAction::GeneratePrimaries(), DD4hep::Simulation::Geant4UserStackingAction::NewStage(), DD4hep::Simulation::Geant4UserTrackingAction::PostUserTrackingAction(), DD4hep::Simulation::Geant4UserStackingAction::PrepareNewEvent(), and DD4hep::Simulation::Geant4UserTrackingAction::PreUserTrackingAction().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp