DD4hep: DD4hep::Simulation::Geant4SensitiveDetector Class Reference
DD4hep::Simulation::Geant4SensitiveDetector Class Reference
Deprecated: Example G4VSensitiveDetector implementation.
#include <Geant4SensitiveDetector.h>
Public Types
typedef Geometry::SensitiveDetector SensitiveDetector
typedef G4THitsCollection< Geant4Hit > HitCollection
typedef Geant4Hit::Contribution HitContribution
typedef Geant4StepHandler StepHandler
Public Member Functions
Geant4SensitiveDetector (const std::string &name, LCDD &lcdd)
Constructor. The sensitive detector element is identified by the detector name.
virtual bool defineCollection (const std::string &coll_name)
Initialize the sensitive detector for the usage of a single hit collection.
virtual ~Geant4SensitiveDetector ()
Standard destructor.
std::string name () const
Standard access to the name.
virtual HitCollection * createCollection (const std::string &coll_name) const
Create single hits collection.
const std::string & hitCollectionName (int which) const
Access HitCollection container names.
HitCollection * collection (int id)
Retrieve the hits collection associated with this detector by its serial number.
HitCollection * collectionByID (int id)
Retrieve the hits collection associated with this detector by its collection identifier.
virtual bool buildHits (G4Step *, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
long long getVolumeID (G4Step *step)
long long getCellID (G4Step *step)
virtual void Initialize (G4HCofThisEvent *HCE)
Method invoked at the begining of each event.
virtual void EndOfEvent (G4HCofThisEvent *HCE)
G4VSensitiveDetector interface: Method invoked at the end of each event.
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
virtual G4bool process (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
virtual void clear ()
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Protected Member Functions
template<typename T >
T * find (const HitCollection *c, const HitCompare< T > &cmp)
Find hits by position in a collection.
void dumpStep (G4Step *step, G4TouchableHistory *history)
Dump Step information (careful: very verbose)
template<>
Geant4CalorimeterHit * find (const HitCollection *c, const HitCompare< Geant4CalorimeterHit > &cmp)
Protected Attributes
LCDD & m_lcdd
Reference to the detector description object.
DetElement m_detector
Reference to the detector element describing this sensitive element.
SensitiveDetector m_sensitive
Reference to the sensitive detector element.
Readout m_readout
Reference to the readout structure.
G4HCofThisEvent * m_hce
Geant4 event context.
Detailed Description
Deprecated: Example G4VSensitiveDetector implementation.
Deprecated:
Deprecated class. Not supported by the DDG4 kernel.
Author
M.Frank
Version
1.0
Definition at line 47 of file Geant4SensitiveDetector.h.
Member Typedef Documentation
HitCollection
typedef G4THitsCollection<Geant4Hit> DD4hep::Simulation::Geant4SensitiveDetector::HitCollection
Definition at line 50 of file Geant4SensitiveDetector.h.
HitContribution
typedef Geant4Hit::Contribution DD4hep::Simulation::Geant4SensitiveDetector::HitContribution
Definition at line 51 of file Geant4SensitiveDetector.h.
SensitiveDetector
typedef Geometry::SensitiveDetector DD4hep::Simulation::Geant4SensitiveDetector::SensitiveDetector
Definition at line 49 of file Geant4SensitiveDetector.h.
StepHandler
typedef Geant4StepHandler DD4hep::Simulation::Geant4SensitiveDetector::StepHandler
Definition at line 52 of file Geant4SensitiveDetector.h.
Constructor & Destructor Documentation
Geant4SensitiveDetector()
Geant4SensitiveDetector::Geant4SensitiveDetector (const std::string & name, LCDD & lcdd)
Constructor. The sensitive detector element is identified by the detector name.
Constructor. The detector element is identified by the name.
Definition at line 41 of file Geant4SensitiveDetector.cpp.
References DD4hep::Geometry::LCDD::detector(), m_detector, m_readout, m_sensitive, DD4hep::Geometry::SensitiveDetector::readout(), and DD4hep::Geometry::LCDD::sensitiveDetector().
~Geant4SensitiveDetector()
Geant4SensitiveDetector::~Geant4SensitiveDetector () virtual
Standard destructor.
Definition at line 49 of file Geant4SensitiveDetector.cpp.
Member Function Documentation
buildHits()
virtual bool DD4hep::Simulation::Geant4SensitiveDetector::buildHits (G4Step * , G4TouchableHistory *) inline virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented in DD4hep::Simulation::Geant4GenericSD< T >.
Definition at line 101 of file Geant4SensitiveDetector.h.
References clear(), EndOfEvent(), getCellID(), getVolumeID(), Initialize(), process(), and ProcessHits().
Referenced by process().
clear()
void Geant4SensitiveDetector::clear () virtual
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Method is invoked if the event abortion is occured.
Hits collections created but not beibg set to G4HCofThisEvent at the event should be deleted. Collection(s) which have already set to G4HCofThisEvent will be deleted automatically.
Reimplemented in DD4hep::Simulation::Geant4GenericSD< T >.
Definition at line 148 of file Geant4SensitiveDetector.cpp.
Referenced by buildHits(), and DD4hep::Simulation::Geant4GenericSD< T >::clear().
collection()
Geant4SensitiveDetector::HitCollection * Geant4SensitiveDetector::collection (int id)
Retrieve the hits collection associated with this detector by its serial number.
Definition at line 136 of file Geant4SensitiveDetector.cpp.
References m_hce, and name().
Referenced by name().
collectionByID()
Geant4SensitiveDetector::HitCollection * Geant4SensitiveDetector::collectionByID (int id)
Retrieve the hits collection associated with this detector by its collection identifier.
Definition at line 128 of file Geant4SensitiveDetector.cpp.
References m_hce, and name().
Referenced by name().
createCollection()
Geant4SensitiveDetector::HitCollection * Geant4SensitiveDetector::createCollection (const std::string & coll_name) const virtual
Create single hits collection.
Definition at line 71 of file Geant4SensitiveDetector.cpp.
References DD4hep::Utilities::GetName().
Referenced by Initialize(), and name().
defineCollection()
bool Geant4SensitiveDetector::defineCollection (const std::string & coll_name) virtual
Initialize the sensitive detector for the usage of a single hit collection.
Reimplemented in DD4hep::Simulation::Geant4GenericSD< T >.
Definition at line 53 of file Geant4SensitiveDetector.cpp.
References m_sensitive, name(), and DD4hep::Geometry::SensitiveDetector::type().
Referenced by DD4hep::Simulation::Geant4GenericSD< T >::defineCollection().
dumpStep()
void Geant4SensitiveDetector::dumpStep (G4Step * step, G4TouchableHistory * history) protected
Dump Step information (careful: very verbose)
Definition at line 152 of file Geant4SensitiveDetector.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Simulation::Geant4GeometryInfo::g4Placements, DD4hep::INFO, DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Simulation::Geant4StepHandler::post, DD4hep::Simulation::Geant4StepHandler::postMom(), DD4hep::Simulation::Geant4StepHandler::postPos(), DD4hep::Simulation::Geant4StepHandler::postStepStatus(), DD4hep::Simulation::Geant4StepHandler::postVolume(), DD4hep::Simulation::Geant4StepHandler::prePos(), DD4hep::Simulation::Geant4StepHandler::preStepStatus(), DD4hep::Simulation::Geant4StepHandler::preVolume(), DD4hep::printout(), DD4hep::Simulation::Geant4StepHandler::track, and DD4hep::Simulation::Geant4StepHandler::volume().
Referenced by process().
EndOfEvent()
void Geant4SensitiveDetector::EndOfEvent (G4HCofThisEvent * HCE) virtual
G4VSensitiveDetector interface: Method invoked at the end of each event.
Method invoked at the end of each event.
Reimplemented in DD4hep::Simulation::Geant4GenericSD< T >.
Definition at line 99 of file Geant4SensitiveDetector.cpp.
References m_hce.
Referenced by buildHits(), and DD4hep::Simulation::Geant4GenericSD< T >::EndOfEvent().
find() [1/2]
template<typename T > T* DD4hep::Simulation::Geant4SensitiveDetector::find (const HitCollection * c, const HitCompare< T > & cmp) protected
Find hits by position in a collection.
find() [2/2]
template<> Geant4CalorimeterHit* DD4hep::Simulation::Geant4SensitiveDetector::find (const HitCollection * c, const HitCompare< Geant4CalorimeterHit > & cmp) protected
Definition at line 77 of file Geant4SensitiveDetector.cpp.
References v.
getCellID()
long long Geant4SensitiveDetector::getCellID (G4Step * step)
Returns the volumeID of the sensitive volume corresponding to the step - combining the VolIDS of the complete geometry path (Geant4TouchableHistory)
Definition at line 220 of file Geant4SensitiveDetector.cpp.
References DD4hep::Geometry::Segmentation::cellID(), DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Handle< T >::isValid(), m_readout, MM_2_CM, DD4hep::Simulation::Geant4StepHandler::postPosG4(), DD4hep::Simulation::Geant4StepHandler::prePosG4(), DD4hep::Simulation::Geant4StepHandler::preTouchable(), DD4hep::Geometry::Readout::segmentation(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), and DD4hep::Simulation::Geant4Mapping::volumeManager().
Referenced by buildHits().
getVolumeID()
long long Geant4SensitiveDetector::getVolumeID (G4Step * step)
Returns the volumeID of the sensitive volume corresponding to the step - combining the VolIDS of the complete geometry path (Geant4TouchableHistory)
Definition at line 187 of file Geant4SensitiveDetector.cpp.
References DD4hep::Simulation::Geant4VolumeManager::Insensitive, DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Simulation::Geant4VolumeManager::InvalidPath, DD4hep::Simulation::Geant4VolumeManager::NonExisting, DD4hep::Simulation::Geant4StepHandler::pre, DD4hep::Simulation::Geant4StepHandler::preTouchable(), DD4hep::Simulation::Geant4StepHandler::volume(), DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), and DD4hep::Simulation::Geant4Mapping::volumeManager().
Referenced by buildHits().
hitCollectionName()
const string & Geant4SensitiveDetector::hitCollectionName (int which) const
Access HitCollection container names.
Definition at line 62 of file Geant4SensitiveDetector.cpp.
References name().
Referenced by name().
Initialize()
void Geant4SensitiveDetector::Initialize (G4HCofThisEvent * HCE) virtual
Method invoked at the begining of each event.
G4VSensitiveDetector interface: Method invoked at the begining of each event. The hits collection(s) created by this sensitive detector must be set to the G4HCofThisEvent object at one of these two methods.
Reimplemented in DD4hep::Simulation::Geant4GenericSD< T >.
Definition at line 89 of file Geant4SensitiveDetector.cpp.
References createCollection(), and m_hce.
Referenced by buildHits(), and DD4hep::Simulation::Geant4GenericSD< T >::Initialize().
name()
std::string DD4hep::Simulation::Geant4SensitiveDetector::name () const inline
Standard access to the name.
Definition at line 86 of file Geant4SensitiveDetector.h.
References collection(), collectionByID(), createCollection(), DD4hep::Utilities::GetName(), and hitCollectionName().
Referenced by collection(), collectionByID(), defineCollection(), and hitCollectionName().
process()
G4bool Geant4SensitiveDetector::process (G4Step * step, G4TouchableHistory * history) virtual
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
Method for generating hit(s) using the information of G4Step object.
Definition at line 110 of file Geant4SensitiveDetector.cpp.
References buildHits(), dumpStep(), DD4hep::Geometry::SensitiveDetector::energyCutoff(), DD4hep::Simulation::Geant4Hit::isGeantino(), and m_sensitive.
Referenced by buildHits(), and ProcessHits().
ProcessHits()
G4bool Geant4SensitiveDetector::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
Method for generating hit(s) using the information of G4Step object.
Reimplemented in DD4hep::Simulation::Geant4GenericSD< T >.
Definition at line 105 of file Geant4SensitiveDetector.cpp.
References process().
Referenced by buildHits(), and DD4hep::Simulation::Geant4GenericSD< T >::ProcessHits().
Member Data Documentation
m_detector
DetElement DD4hep::Simulation::Geant4SensitiveDetector::m_detector protected
Reference to the detector element describing this sensitive element.
Definition at line 59 of file Geant4SensitiveDetector.h.
Referenced by Geant4SensitiveDetector().
m_hce
G4HCofThisEvent* DD4hep::Simulation::Geant4SensitiveDetector::m_hce protected
Geant4 event context.
Definition at line 66 of file Geant4SensitiveDetector.h.
Referenced by collection(), collectionByID(), EndOfEvent(), and Initialize().
m_lcdd
LCDD& DD4hep::Simulation::Geant4SensitiveDetector::m_lcdd protected
Reference to the detector description object.
Definition at line 57 of file Geant4SensitiveDetector.h.
m_readout
Readout DD4hep::Simulation::Geant4SensitiveDetector::m_readout protected
Reference to the readout structure.
Definition at line 63 of file Geant4SensitiveDetector.h.
Referenced by Geant4SensitiveDetector(), and getCellID().
m_sensitive
SensitiveDetector DD4hep::Simulation::Geant4SensitiveDetector::m_sensitive protected
Reference to the sensitive detector element.
Definition at line 61 of file Geant4SensitiveDetector.h.
Referenced by defineCollection(), DD4hep::Simulation::Geant4GenericSD< T >::Geant4GenericSD(), Geant4SensitiveDetector(), and process().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensitiveDetector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SensitiveDetector.cpp