DD4hep: DD4hep: DD4hep::Simulation::Geant4InteractionVertexBoost Class Reference
DD4hep::Simulation::Geant4InteractionVertexBoost Class Reference
[DD4hep::Simulation components, classes and objects]
Action class to boost the primary vertex (and all outgoing particles) of a single interaction.
#include <Geant4InteractionVertexBoost.h>
Public Types
typedef Geant4PrimaryInteraction Interaction
Interaction definition.
Public Member Functions
Geant4InteractionVertexBoost (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4InteractionVertexBoost ()
Default destructor.
virtual void operator() (G4Event *event)
Callback to generate primary particles.
Protected Member Functions
void boost (Interaction *interaction) const
Action routine to boost one single interaction according to the properties.
Protected Attributes
double m_angle
Property: The constant Lorentz transformation angle.
int m_mask
Property: Unique identifier of the interaction to be modified.
Detailed Description
Action class to boost the primary vertex (and all outgoing particles) of a single interaction.
The vertex smearing is steered by the Lorentz transformation angle. The interaction to be modified is identified by the interaction's unique mask.
Author:
M.Frank
Version:
1.0
Definition at line 36 of file Geant4InteractionVertexBoost.h.
Member Typedef Documentation
typedef Geant4PrimaryInteraction DD4hep::Simulation::Geant4InteractionVertexBoost::Interaction
Interaction definition.
Definition at line 39 of file Geant4InteractionVertexBoost.h.
Constructor & Destructor Documentation
Geant4InteractionVertexBoost::Geant4InteractionVertexBoost (Geant4Context * context, const std::string & name)
Standard constructor.
Definition at line 24 of file Geant4InteractionVertexBoost.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_angle, m_mask, and DD4hep::Simulation::Geant4Action::m_needsControl.
Geant4InteractionVertexBoost::~Geant4InteractionVertexBoost () [virtual]
Default destructor.
Definition at line 34 of file Geant4InteractionVertexBoost.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4InteractionVertexBoost::boost (Interaction * interaction) const [protected]
Action routine to boost one single interaction according to the properties.
Action to boost one single interaction according to the properties.
Definition at line 39 of file Geant4InteractionVertexBoost.cpp.
References DD4hep::Simulation::boostInteraction(), m_angle, m_mask, and DD4hep::Simulation::Geant4Action::print().
Referenced by operator()().
void Geant4InteractionVertexBoost::operator() (G4Event * event) [virtual]
Callback to generate primary particles.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 48 of file Geant4InteractionVertexBoost.cpp.
References boost(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4PrimaryEvent::get(), DD4hep::Simulation::Geant4PrimaryEvent::interactions(), and m_mask.
Member Data Documentation
double DD4hep::Simulation::Geant4InteractionVertexBoost::m_angle [protected]
Property: The constant Lorentz transformation angle.
Definition at line 43 of file Geant4InteractionVertexBoost.h.
Referenced by boost(), and Geant4InteractionVertexBoost().
int DD4hep::Simulation::Geant4InteractionVertexBoost::m_mask [protected]
Property: Unique identifier of the interaction to be modified.
Definition at line 45 of file Geant4InteractionVertexBoost.h.
Referenced by boost(), Geant4InteractionVertexBoost(), and operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4InteractionVertexBoost.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4InteractionVertexBoost.cpp