DD4hep: DD4hep::Projection Class Reference
DD4hep::Projection Class Reference
class Projection Projection.h DDEve/Projection.h
#include <Projection.h>
Public Member Functions
Projection (Display *eve, const std::string &name)
Initializing constructor.
virtual ~Projection ()
Default destructor.
virtual View & Map (TEveWindow *slot)
Map the projection view to the slot.
virtual Projection & AddAxis ()
Add projection axis to the view.
virtual Projection & CreateRhoPhiProjection ()
Create Rho-Phi projection.
virtual Projection & CreateRhoZProjection ()
Create Rho-Z projection.
virtual void SetDepth (Float_t d)
ClassDef (Projection, 0)
Public Member Functions inherited from DD4hep::View
View (Display *eve, const std::string &name)
Initializing constructor.
virtual ~View ()
Default destructor.
const std::string & name () const
Access to the view name/title.
const char * c_name () const
TEveViewer * viewer () const
Access to the Eve viewer.
bool showGlobal () const
Show global directory.
void setShowGlobal (bool value)
Set show globals.
virtual View & Build (TEveWindow *slot)
Build the view view and map it to the given slot.
virtual void Initialize ()
Initialize the view port.
virtual View & CreateScenes ()
Create the geometry and the event scene.
virtual TEveElementList * AddToGlobalItems (const std::string &nam)
Add the view to the global list of eve objects.
TEveScene * geoScene () const
Access to the Eve geometry scene.
virtual View & CreateGeoScene ()
Create the geometry scene.
virtual void ConfigureGeometryFromInfo ()
Configure a view with geo info. Used configuration if present.
virtual void ConfigureGeometryFromGlobal ()
Configure a single geometry view by default from the global geometry scene with all subdetectors.
virtual void ConfigureGeometry (const DisplayConfiguration::ViewConfig &config)
Configure a single geometry view.
virtual std::pair< bool, TEveElement * > CreateGeometry (DetElement de, const DisplayConfiguration::Config &cfg)
Create a new instance of the geometry of a sub-detector.
virtual std::pair< bool, TEveElement * > GetGlobalGeometry (DetElement de, const DisplayConfiguration::Config &cfg)
Access the global instance of the subdetector geometry.
virtual void ImportGeo (const std::string &topic, TEveElement *element)
Call to import geometry elements into topics.
virtual void ImportGeo (TEveElementList &topic, TEveElement *element)
Call to import geometry elements into topics.
virtual void ImportGeo (TEveElement *element)
Call to import geometry elements into the main geometry scene menu.
virtual void ImportGeoTopics (const std::string &title)
Call to import geometry topics. If title is empty, do not add to global item list.
virtual TEveElementList & GetGeoTopic (const std::string &name)
Access/Create an geometry topic by name.
TEveScene * eveScene () const
Access to the Eve event scene.
virtual View & CreateEventScene ()
Create the event scene.
virtual void ConfigureEventFromInfo ()
Configure a view with event info. Used configuration if present.
virtual void ConfigureEventFromGlobal ()
Configure an event view by default from the global event scene.
virtual void ConfigureEvent (const DisplayConfiguration::ViewConfig &config)
Configure a single event scene view.
virtual void ImportEvent (TEveElement *element)
Call to import event elements into the main event scene.
virtual void ImportEventTopics ()
Import event typics after creation.
ClassDef (View, 0)
Root implementation macro.
Protected Member Functions
virtual TEveElement * ImportElement (TEveElement *el, TEveElementList *list)
Call an element to a event element list.
virtual TEveElement * ImportGeoElement (TEveElement *element, TEveElementList *list)
Call an element to a geometry element list.
virtual TEveElement * ImportGeoTopic (TEveElement *element, TEveElementList *list)
Call an element to a geometry element list.
virtual TEveElement * ImportEventElement (TEveElement *element, TEveElementList *list)
Call an element to a event element list.
Protected Attributes
TEveProjectionManager * m_projMgr
Reference to the projection manager.
TEveProjectionAxes * m_axis
Reference to the projection axis.
Protected Attributes inherited from DD4hep::View
Display * m_eve
TEveViewer * m_view
Reference to the view.
TEveScene * m_geoScene
Reference to the geometry scene.
TEveScene * m_eveScene
Reference to the event scene.
TEveElementList * m_global
Reference to the global item (if added.
const DisplayConfiguration::ViewConfig * m_config
std::string m_name
The name of the view.
Topics m_geoTopics
Topics m_eveTopics
bool m_showGlobal
Additional Inherited Members
Public Types inherited from DD4hep::View
typedef Geometry::LCDD LCDD
typedef Geometry::DetElement DetElement
typedef Geometry::SensitiveDetector SensitiveDetector
typedef std::map< std::string, TEveElementList * > Topics
Detailed Description
class Projection Projection.h DDEve/Projection.h
Definition at line 33 of file Projection.h.
Constructor & Destructor Documentation
Projection()
Projection::Projection (Display * eve, const std::string & name)
Initializing constructor.
Definition at line 31 of file Projection.cpp.
~Projection()
Projection::~Projection () virtual
Default destructor.
Definition at line 37 of file Projection.cpp.
Member Function Documentation
AddAxis()
Projection & Projection::AddAxis () virtual
Add projection axis to the view.
Add axis to the projection view.
Definition at line 85 of file Projection.cpp.
References m_axis, DD4hep::View::m_geoScene, and m_projMgr.
Referenced by DD4hep::RhoPhiProjection::Build(), and DD4hep::RhoZProjection::Build().
ClassDef()
DD4hep::Projection::ClassDef (Projection , 0)
CreateRhoPhiProjection()
Projection & Projection::CreateRhoPhiProjection () virtual
Create Rho-Phi projection.
Definition at line 99 of file Projection.cpp.
References DD4hep::View::AddToGlobalItems(), m_projMgr, and DD4hep::View::name().
Referenced by DD4hep::RhoPhiProjection::Build().
CreateRhoZProjection()
Projection & Projection::CreateRhoZProjection () virtual
Create Rho-Z projection.
Definition at line 108 of file Projection.cpp.
References DD4hep::View::AddToGlobalItems(), m_projMgr, and DD4hep::View::name().
Referenced by DD4hep::RhoZProjection::Build().
ImportElement()
TEveElement * Projection::ImportElement (TEveElement * el, TEveElementList * list) protected virtual
Call an element to a event element list.
Definition at line 51 of file Projection.cpp.
References e, find(), DD4hep::View::GetGeoTopic(), DD4hep::Utilities::GetName(), DD4hep::INFO, DD4hep::View::m_eveScene, DD4hep::View::m_geoScene, DD4hep::View::m_geoTopics, m_projMgr, and DD4hep::printout().
Referenced by ImportEventElement(), and ImportGeoElement().
ImportEventElement()
TEveElement * Projection::ImportEventElement (TEveElement * element, TEveElementList * list) protected virtual
Call an element to a event element list.
Reimplemented from DD4hep::View.
Definition at line 80 of file Projection.cpp.
References ImportElement().
ImportGeoElement()
TEveElement * Projection::ImportGeoElement (TEveElement * element, TEveElementList * list) protected virtual
Call an element to a geometry element list.
Reimplemented from DD4hep::View.
Definition at line 75 of file Projection.cpp.
References ImportElement().
ImportGeoTopic()
TEveElement * Projection::ImportGeoTopic (TEveElement * element, TEveElementList * list) protected virtual
Call an element to a geometry element list.
Reimplemented from DD4hep::View.
Definition at line 46 of file Projection.cpp.
Map()
View & Projection::Map (TEveWindow * slot) virtual
Map the projection view to the slot.
Reimplemented from DD4hep::View.
Definition at line 117 of file Projection.cpp.
References DD4hep::View::m_view, and DD4hep::View::Map().
Referenced by DD4hep::RhoPhiProjection::Build(), and DD4hep::RhoZProjection::Build().
SetDepth()
void Projection::SetDepth (Float_t d) virtual
Definition at line 40 of file Projection.cpp.
References m_projMgr.
Member Data Documentation
m_axis
TEveProjectionAxes* DD4hep::Projection::m_axis protected
Reference to the projection axis.
Definition at line 38 of file Projection.h.
Referenced by AddAxis().
m_projMgr
TEveProjectionManager* DD4hep::Projection::m_projMgr protected
Reference to the projection manager.
Definition at line 36 of file Projection.h.
Referenced by AddAxis(), CreateRhoPhiProjection(), CreateRhoZProjection(), ImportElement(), and SetDepth().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/Projection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/Projection.cpp