DD4hep: DD4hep: DD4hep::Geometry::Header Class Reference
DD4hep::Geometry::Header Class Reference
[DD4hep::Geometry components, classes and objects]
Handle class describing the basic information about geometry objects as it is defined in LCDD.
#include <Objects.h>
Public Types
typedef HeaderObject Object
Public Member Functions
Header ()
Default constructor.
Header (const Header &e)
Constructorto be used for assignment from a handle.
template<typename Q >
Header (const Handle< Q > &e)
Constructor to be used when reading the already parsed DOM tree.
Header (const std::string &author, const std::string &url)
Constructor to be used when creating a new DOM tree.
Header & operator= (const Header &e)
Assignment operator.
const std::string name () const
Accessor to object name.
void setName (const std::string &new_name)
Accessor: set object name.
const std::string title () const
Accessor to object title.
void setTitle (const std::string &new_title)
Accessor: set object title.
const std::string & author () const
Accessor to object author.
void setAuthor (const std::string &new_author)
Accessor: set object author.
const std::string & url () const
Accessor to object url.
void setUrl (const std::string &new_url)
Accessor: set object url.
const std::string & status () const
Accessor to object status.
void setStatus (const std::string &new_status)
Accessor: set object status.
const std::string & version () const
Accessor to object version.
void setVersion (const std::string &new_version)
Accessor: set object version.
const std::string & comment () const
Accessor to object comment.
void setComment (const std::string &new_comment)
Accessor: set object comment.
Detailed Description
Handle class describing the basic information about geometry objects as it is defined in LCDD.
Description of the geometry header. Containes useful auxiliary information.
Author:
M.Frank
Version:
1.0
Definition at line 168 of file Objects.h.
Member Typedef Documentation
typedef HeaderObject DD4hep::Geometry::Header::Object
Definition at line 170 of file Objects.h.
Constructor & Destructor Documentation
DD4hep::Geometry::Header::Header () [inline]
Default constructor.
Definition at line 172 of file Objects.h.
DD4hep::Geometry::Header::Header (const Header & e) [inline]
Constructorto be used for assignment from a handle.
Definition at line 176 of file Objects.h.
template<typename Q > DD4hep::Geometry::Header::Header (const Handle< Q > & e) [inline]
Constructor to be used when reading the already parsed DOM tree.
Definition at line 180 of file Objects.h.
DD4hep::Geometry::Header::Header (const std::string & author, const std::string & url)
Constructor to be used when creating a new DOM tree.
Member Function Documentation
const std::string & Header::author () const
Accessor to object author.
Definition at line 100 of file Objects.cpp.
Referenced by setAuthor().
const std::string & Header::comment () const
Accessor to object comment.
Definition at line 130 of file Objects.cpp.
Referenced by setComment().
const std::string Header::name () const
Accessor to object name.
Reimplemented from DD4hep::Handle< T >.
Definition at line 70 of file Objects.cpp.
References DD4hep::Handle< T >::m_element.
Header& DD4hep::Geometry::Header::operator= (const Header & e) [inline]
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 186 of file Objects.h.
References DD4hep::Handle< T >::m_element.
void Header::setAuthor (const std::string & new_author)
Accessor: set object author.
Definition at line 105 of file Objects.cpp.
References author().
void Header::setComment (const std::string & new_comment)
Accessor: set object comment.
Definition at line 135 of file Objects.cpp.
References comment().
void Header::setName (const std::string & new_name)
Accessor: set object name.
Definition at line 75 of file Objects.cpp.
References DD4hep::Handle< T >::m_element.
void Header::setStatus (const std::string & new_status)
Accessor: set object status.
Definition at line 115 of file Objects.cpp.
References status().
void Header::setTitle (const std::string & new_title)
Accessor: set object title.
Definition at line 85 of file Objects.cpp.
References DD4hep::Handle< T >::m_element.
void Header::setUrl (const std::string & new_url)
Accessor: set object url.
Definition at line 95 of file Objects.cpp.
References url().
void Header::setVersion (const std::string & new_version)
Accessor: set object version.
Definition at line 125 of file Objects.cpp.
References version().
const std::string & Header::status () const
Accessor to object status.
Definition at line 110 of file Objects.cpp.
Referenced by setStatus().
const std::string Header::title () const
Accessor to object title.
Definition at line 80 of file Objects.cpp.
References DD4hep::Handle< T >::m_element.
const std::string & Header::url () const
Accessor to object url.
Definition at line 90 of file Objects.cpp.
Referenced by setUrl().
const std::string & Header::version () const
Accessor to object version.
Definition at line 120 of file Objects.cpp.
Referenced by setVersion().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp