DD4hep: DD4hep::DDRec::VolConeImpl Class Reference
DD4hep::DDRec::VolConeImpl Class Reference
#include <Surface.h>
Public Member Functions
VolConeImpl ()
default c'tor
VolConeImpl (Geometry::Volume vol, SurfaceType type, double thickness_inner, double thickness_outer, Vector3D v, Vector3D origin)
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
virtual double distance (const Vector3D &point) const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
virtual std::vector< std::pair< DDSurfaces::Vector3D, DDSurfaces::Vector3D > > getLines (unsigned nMax=100)
create outer bounding lines for the given symmetry of the polyhedron
Public Member Functions inherited from DD4hep::DDRec::VolSurfaceBase
virtual ~VolSurfaceBase ()
VolSurfaceBase ()
default c'tor
VolSurfaceBase (SurfaceType typ, double thickness_inner, double thickness_outer, Vector3D u_val, Vector3D v_val, Vector3D n, Vector3D o, Geometry::Volume vol, int identifier)
VolSurfaceBase (const VolSurfaceBase &c)
Copy the from object.
Geometry::Volume volume () const
the volume to which this surface is attached.
virtual long64 id () const
The id of this surface.
virtual const SurfaceType & type () const
virtual const Vector3D & origin () const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double innerThickness () const
virtual double outerThickness () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual bool insideBounds (const Vector3D &point, double epsilon=1e-4) const
Checks if the given point lies within the surface.
void setInnerMaterial (const IMaterial &mat)
set the inner Material
void setOuterMaterial (const IMaterial &mat)
set the outer Materal
Public Member Functions inherited from DDSurfaces::ISurface
virtual ~ISurface ()
Destructor.
Private Attributes
double _ztip
double _zt0
double _zt1
double _tanTheta
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDRec::VolSurfaceBase
virtual void setU (const Vector3D &u)
setter for daughter classes
virtual void setV (const Vector3D &v)
setter for daughter classes
virtual void setNormal (const Vector3D &n)
setter for daughter classes
virtual void setOrigin (const Vector3D &o)
setter for daughter classes
Protected Attributes inherited from DD4hep::DDRec::VolSurfaceBase
SurfaceType _type
Vector3D _u
Vector3D _v
Vector3D _n
Vector3D _o
double _th_i
double _th_o
MaterialData _innerMat
MaterialData _outerMat
Geometry::Volume _vol
long64 _id
unsigned _refCount
Detailed Description
Implementation of conical surface attached to a volume
Author
F.Gaede, DESY
Date
Nov, 6 2015
Version
$Id$
Definition at line 414 of file Surface.h.
Constructor & Destructor Documentation
VolConeImpl() [1/2]
DD4hep::DDRec::VolConeImpl::VolConeImpl () inline
default c'tor
Definition at line 425 of file Surface.h.
References v.
VolConeImpl() [2/2]
DD4hep::DDRec::VolConeImpl::VolConeImpl (Geometry::Volume vol, SurfaceType type, double thickness_inner, double thickness_outer, Vector3D v, Vector3D origin)
The standard constructor. The origin vector points to the origin of the coordinate system on the cone, its rho defining the mean radius of the cone (z-component of the origin is ignored !). The measurement direction v defines the opening angle of the cone, the normal is chosen to be orthogonal to v. NB: the cone is always parallel to the local z axis.
Definition at line 321 of file Surface.cpp.
References _tanTheta, DD4hep::DDRec::VolSurfaceBase::_type, _zt0, _zt1, _ztip, DDSurfaces::Vector3D::array(), DDSurfaces::SurfaceType::Cone, DDSurfaces::Vector3D::const_array(), DDSurfaces::Vector3D::cross(), DDSurfaces::SurfaceType::Cylinder, e, M_PI, DDSurfaces::SurfaceType::OrthogonalToZ, DDSurfaces::SurfaceType::ParallelToZ, DDSurfaces::Vector3D::phi(), DDSurfaces::SurfaceType::Plane, DDSurfaces::Vector3D::rho(), DD4hep::DDRec::VolSurfaceBase::setNormal(), DD4hep::DDRec::VolSurfaceBase::setOrigin(), DDSurfaces::SurfaceType::setProperty(), DD4hep::DDRec::VolSurfaceBase::setU(), DDSurfaces::Vector3D::spherical(), DDSurfaces::Vector3D::theta(), DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().
Member Function Documentation
distance()
double DD4hep::DDRec::VolConeImpl::distance (const Vector3D & point) const virtual
Distance to surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 422 of file Surface.cpp.
References _tanTheta, DD4hep::DDRec::VolSurfaceBase::_v, _ztip, DDSurfaces::Vector3D::rho(), DDSurfaces::Vector3D::theta(), and DDSurfaces::Vector3D::z().
getLines()
std::vector< std::pair< DDSurfaces::Vector3D, DDSurfaces::Vector3D > > DD4hep::DDRec::VolConeImpl::getLines (unsigned nMax = 100) virtual
create outer bounding lines for the given symmetry of the polyhedron
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 447 of file Surface.cpp.
References DD4hep::DDRec::VolSurfaceBase::length_along_v(), DD4hep::DDRec::VolSurfaceBase::origin(), DDSurfaces::Vector3D::rho(), DDSurfaces::Vector3D::theta(), and v().
globalToLocal()
Vector2D DD4hep::DDRec::VolConeImpl::globalToLocal (const Vector3D & point) const virtual
Convert the global position to the local position (u,v) on the surface - v runs along the axis of the cone, u is r*phi
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 391 of file Surface.cpp.
References _tanTheta, DD4hep::DDRec::VolSurfaceBase::_v, _ztip, M_PI, DD4hep::DDRec::VolSurfaceBase::origin(), DDSurfaces::Vector3D::phi(), DDSurfaces::Vector3D::theta(), and DDSurfaces::Vector3D::z().
localToGlobal()
Vector3D DD4hep::DDRec::VolConeImpl::localToGlobal (const Vector2D & point) const virtual
Convert the local position (u,v) on the surface to the global position - v runs along the axis of the cone, u is r*phi
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 406 of file Surface.cpp.
References _tanTheta, DD4hep::DDRec::VolSurfaceBase::_v, _ztip, DDSurfaces::Vector3D::cylindrical(), M_PI, DD4hep::DDRec::VolSurfaceBase::origin(), DDSurfaces::Vector3D::phi(), DDSurfaces::Vector3D::theta(), DDSurfaces::Vector2D::u(), DDSurfaces::Vector2D::v(), and DDSurfaces::Vector3D::z().
normal()
Vector3D DD4hep::DDRec::VolConeImpl::normal (const Vector3D & point = Vector3D()) const virtual
The normal direction at the given point, projected onto the cone. No check is done whether the point actually is on the cone surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 385 of file Surface.cpp.
References DD4hep::DDRec::VolSurfaceBase::_n, DDSurfaces::Vector3D::phi(), DDSurfaces::Vector3D::spherical(), and DDSurfaces::Vector3D::theta().
Referenced by u().
u()
Vector3D DD4hep::DDRec::VolConeImpl::u (const Vector3D & point = Vector3D()) const virtual
First direction of measurement U - rotated to point projected onto the cone. No check is done whether the point actually is on the cone surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 378 of file Surface.cpp.
References DDSurfaces::Vector3D::cross(), normal(), and v().
v()
Vector3D DD4hep::DDRec::VolConeImpl::v (const Vector3D & point = Vector3D()) const virtual
Second direction of measurement V - rotated to point projected onto the cone. No check is done whether the point actually is on the cone surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 372 of file Surface.cpp.
References DD4hep::DDRec::VolSurfaceBase::_v, DDSurfaces::Vector3D::phi(), DDSurfaces::Vector3D::spherical(), and DDSurfaces::Vector3D::theta().
Referenced by getLines(), and u().
Member Data Documentation
_tanTheta
double DD4hep::DDRec::VolConeImpl::_tanTheta private
Definition at line 420 of file Surface.h.
Referenced by distance(), globalToLocal(), localToGlobal(), and VolConeImpl().
_zt0
double DD4hep::DDRec::VolConeImpl::_zt0 private
Definition at line 418 of file Surface.h.
Referenced by VolConeImpl().
_zt1
double DD4hep::DDRec::VolConeImpl::_zt1 private
Definition at line 419 of file Surface.h.
Referenced by VolConeImpl().
_ztip
double DD4hep::DDRec::VolConeImpl::_ztip private
Definition at line 417 of file Surface.h.
Referenced by distance(), globalToLocal(), localToGlobal(), and VolConeImpl().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp