DD4hep: DD4hep: DD4hep::Simulation::Geant4ParticleMap Class Reference
DD4hep::Simulation::Geant4ParticleMap Class Reference
[DD4hep::Simulation components, classes and objects]
Data structure to map particles produced during the generation and the simulation.
#include <Geant4Particle.h>
Public Types
typedef Geant4Particle Particle
typedef std::map< int, Particle * > ParticleMap
typedef std::map< int, int > TrackEquivalents
Public Member Functions
Geant4ParticleMap ()
Default constructor.
virtual ~Geant4ParticleMap ()
Default destructor.
bool isValid () const
Check if the particle map was ever filled (ie. some particle handler was present).
void dump () const
Dump content.
void clear ()
Clear particle maps.
void adopt (ParticleMap &pm, TrackEquivalents &equiv)
Adopt particle maps.
const ParticleMap & particles () const
Access the particle map.
const TrackEquivalents & equivalents () const
Access the map of track equivalents.
int particleID (int track, bool throw_if_not_found=true) const
Access the equivalent track id (shortcut to the usage of TrackEquivalents).
Public Attributes
ParticleMap particleMap
Mapping of particles of this event.
TrackEquivalents equivalentTracks
Map associating the G4Track identifiers with identifiers of existing MCParticles.
Detailed Description
Data structure to map particles produced during the generation and the simulation.
This data structure is added to the Geant4Event data extensions by the Geant4GenerationInit action. Particles are added:
During the generation if the required modules are activated
At the end of the handling of the MC truth are particles to be kept are inserted if the required modules are activated such as the Geant4ParticleHandler.
Note: This object takes OWNERSHIP of the inserted particles! beware of double deletion of objects!
Author:
M.Frank
Version:
1.0
Definition at line 308 of file Geant4Particle.h.
Member Typedef Documentation
typedef Geant4Particle DD4hep::Simulation::Geant4ParticleMap::Particle
Definition at line 310 of file Geant4Particle.h.
typedef std::map<int,Particle*> DD4hep::Simulation::Geant4ParticleMap::ParticleMap
Definition at line 311 of file Geant4Particle.h.
typedef std::map<int,int> DD4hep::Simulation::Geant4ParticleMap::TrackEquivalents
Definition at line 312 of file Geant4Particle.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4ParticleMap::Geant4ParticleMap () [inline]
Default constructor.
Definition at line 319 of file Geant4Particle.h.
Geant4ParticleMap::~Geant4ParticleMap () [virtual]
Default destructor.
Definition at line 395 of file Geant4Particle.cpp.
References clear().
Member Function Documentation
void Geant4ParticleMap::adopt (ParticleMap & pm, TrackEquivalents & equiv)
Adopt particle maps.
Definition at line 439 of file Geant4Particle.cpp.
References clear(), equivalentTracks, and particleMap.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::endEvent().
void Geant4ParticleMap::clear ()
Clear particle maps.
Definition at line 400 of file Geant4Particle.cpp.
References equivalentTracks, particleMap, and DD4hep::releaseObjects().
Referenced by adopt(), and ~Geant4ParticleMap().
void Geant4ParticleMap::dump () const
Dump content.
Definition at line 407 of file Geant4Particle.cpp.
References equivalentTracks, dd4hep::m, and particleMap.
Referenced by particleID().
const TrackEquivalents& DD4hep::Simulation::Geant4ParticleMap::equivalents () const [inline]
Access the map of track equivalents.
Definition at line 333 of file Geant4Particle.h.
References equivalentTracks.
bool Geant4ParticleMap::isValid () const
Check if the particle map was ever filled (ie. some particle handler was present).
Definition at line 449 of file Geant4Particle.cpp.
References equivalentTracks.
Referenced by DD4hep::Simulation::Geant4OutputAction::end().
int Geant4ParticleMap::particleID (int track, bool throw_if_not_found = true) const
Access the equivalent track id (shortcut to the usage of TrackEquivalents).
Definition at line 454 of file Geant4Particle.cpp.
References dump(), equivalentTracks, DD4hep::ERROR, and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4ParticlePrint::printParticle(), and DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
const ParticleMap& DD4hep::Simulation::Geant4ParticleMap::particles () const [inline]
Access the particle map.
Definition at line 331 of file Geant4Particle.h.
References particleMap.
Referenced by DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), and DD4hep::Simulation::Geant4Output2ROOT::saveEvent().
Member Data Documentation
TrackEquivalents DD4hep::Simulation::Geant4ParticleMap::equivalentTracks
Map associating the G4Track identifiers with identifiers of existing MCParticles.
not persistent
Definition at line 316 of file Geant4Particle.h.
Referenced by adopt(), clear(), dump(), equivalents(), isValid(), and particleID().
ParticleMap DD4hep::Simulation::Geant4ParticleMap::particleMap
Mapping of particles of this event.
Definition at line 314 of file Geant4Particle.h.
Referenced by adopt(), clear(), dump(), particles(), and DD4hep::Simulation::Geant4Output2LCIO::saveParticles().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Particle.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Particle.cpp