DD4hep: DD4hep::Alignments::AlignmentsManagerObject Class Reference
DD4hep::Alignments::AlignmentsManagerObject Class Reference
Alignment manager.
#include <AlignmentsManager.h>
Public Types
typedef AlignmentsManager::Dependencies Dependencies
Public Member Functions
AlignmentsManagerObject ()
Initializing constructor.
virtual ~AlignmentsManagerObject ()
Default destructor.
void compute (UserPool &user_pool) const
Compute all alignment conditions of the internal dependency list.
void compute (UserPool &user_pool, const Dependencies &deps) const
Compute all alignment conditions of the specified dependency list.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
Dependencies * dependencies
Full list of alignment dependencies.
AlignContext * all_alignments
References to all alignment possibilities known.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Protected Member Functions
void to_world (AlignContext &new_alignments, UserPool &pool, DetElement det, TGeoHMatrix &mat) const
Compute the transformation from the closest detector element of the alignment to the world system.
void compute (AlignContext &new_alignments, UserPool &pool, DetElement child, int level) const
Compute all alignment conditions of the lower levels.
Detailed Description
Alignment manager.
Uses internally the conditions mechanism to manager the alignment conditions.
Author
M.Frank
Version
1.0
Definition at line 110 of file AlignmentsManager.h.
Member Typedef Documentation
Dependencies
typedef AlignmentsManager::Dependencies DD4hep::Alignments::AlignmentsManagerObject::Dependencies
Definition at line 112 of file AlignmentsManager.h.
Constructor & Destructor Documentation
AlignmentsManagerObject()
AlignmentsManagerObject::AlignmentsManagerObject ()
Initializing constructor.
Definition at line 92 of file AlignmentsManager.cpp.
References all_alignments, dependencies, and DD4hep::InstanceCount::increment().
Referenced by DD4hep::Alignments::AlignmentsManager::AlignmentsManager().
~AlignmentsManagerObject()
AlignmentsManagerObject::~AlignmentsManagerObject () virtual
Default destructor.
Definition at line 99 of file AlignmentsManager.cpp.
References all_alignments, DD4hep::Conditions::ConditionsDependencyCollection::clear(), DD4hep::InstanceCount::decrement(), DD4hep::deletePtr(), and dependencies.
Member Function Documentation
compute() [1/3]
void AlignmentsManagerObject::compute (AlignContext & new_alignments, UserPool & pool, DetElement child, int level) const protected
Compute all alignment conditions of the lower levels.
Definition at line 208 of file AlignmentsManager.cpp.
References DD4hep::Geometry::_transform(), DD4hep::Geometry::DetElement::children(), computeDelta(), DD4hep::Alignments::AlignContext::Entry::cond, DD4hep::Alignments::AlignmentCondition::data(), DD4hep::DEBUG, DD4hep::Alignments::AlignContext::entries, DD4hep::Alignments::AlignmentCondition::iov(), DD4hep::Geometry::DetElement::key(), DD4hep::Alignments::AlignContext::keys, DD4hep::Geometry::DetElement::level(), DD4hep::Geometry::DetElement::path(), DD4hep::printout(), DD4hep::IOV::str(), to_world(), DD4hep::Alignments::AlignmentData::trToWorld, and DD4hep::Alignments::AlignmentData::worldTrafo.
Referenced by DD4hep::Alignments::AlignmentsManager::compute(), and compute().
compute() [2/3]
void AlignmentsManagerObject::compute (UserPool & user_pool) const
Compute all alignment conditions of the internal dependency list.
Definition at line 141 of file AlignmentsManager.cpp.
References compute(), and dependencies.
compute() [3/3]
void AlignmentsManagerObject::compute (UserPool & user_pool, const Dependencies & deps) const
Compute all alignment conditions of the specified dependency list.
Definition at line 146 of file AlignmentsManager.cpp.
References compute(), DD4hep::Conditions::UserPool::compute(), DD4hep::DEBUG, DD4hep::Alignments::AlignContext::Entry::det, DD4hep::Alignments::AlignContext::detectors, e, DD4hep::Alignments::AlignContext::entries, DD4hep::INFO, DD4hep::Geometry::DetElement::key(), DD4hep::Geometry::DetElement::level(), DD4hep::Geometry::DetElement::path(), DD4hep::printout(), DD4hep::Conditions::ConditionsDependencyCollection::size(), and DD4hep::Alignments::AlignContext::Entry::top.
to_world()
void AlignmentsManagerObject::to_world (AlignContext & new_alignments, UserPool & pool, DetElement det, TGeoHMatrix & mat) const protected
Compute the transformation from the closest detector element of the alignment to the world system.
Definition at line 106 of file AlignmentsManager.cpp.
References all_alignments, DD4hep::Alignments::AlignContext::Entry::cond, DD4hep::Alignments::AlignmentCondition::data(), DD4hep::Alignments::AlignContext::Entry::dep, DD4hep::Alignments::Alignment::detectorTransformation(), e, DD4hep::Alignments::AlignContext::entries, DD4hep::Conditions::UserPool::get(), DD4hep::Conditions::ConditionKey::hash, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::key(), DD4hep::Alignments::AlignContext::keys, DD4hep::Geometry::DetElement::nominal(), DD4hep::Geometry::DetElement::parent(), DD4hep::Conditions::ConditionDependency::target, and DD4hep::Alignments::AlignmentData::worldTransformation().
Referenced by compute().
Member Data Documentation
all_alignments
AlignContext* DD4hep::Alignments::AlignmentsManagerObject::all_alignments
References to all alignment possibilities known.
Definition at line 117 of file AlignmentsManager.h.
Referenced by DD4hep::Alignments::AlignmentsManager::adoptDependency(), AlignmentsManagerObject(), to_world(), and ~AlignmentsManagerObject().
dependencies
Dependencies* DD4hep::Alignments::AlignmentsManagerObject::dependencies
Full list of alignment dependencies.
Definition at line 115 of file AlignmentsManager.h.
Referenced by DD4hep::Alignments::AlignmentsManager::adoptDependency(), AlignmentsManagerObject(), DD4hep::Alignments::AlignmentsManager::compute(), compute(), and ~AlignmentsManagerObject().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/AlignmentsManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentsManager.cpp