DD4hep: DD4hep::Conditions::ConditionsRepository Class Reference
DD4hep::Conditions::ConditionsRepository Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Forward declarations.
#include <ConditionsRepository.h>
Classes
class Entry
Public Types
typedef std::vector< Entry > Data
Public Member Functions
ConditionsRepository ()
Default constructor.
virtual ~ConditionsRepository ()
Default destructor.
int save (ConditionsManager m, const std::string &output) const
Save the repository to file.
int load (const std::string &input, Data &data) const
Load the repository from file and fill user passed data structory.
Detailed Description
Forward declarations.
Base class to be implemented by objects to listen on condition callbacks
Author
M.Frank
Version
1.0
Definition at line 42 of file ConditionsRepository.h.
Member Typedef Documentation
Data
typedef std::vector<Entry> DD4hep::Conditions::ConditionsRepository::Data
Definition at line 64 of file ConditionsRepository.h.
Constructor & Destructor Documentation
ConditionsRepository()
ConditionsRepository::ConditionsRepository ()
Default constructor.
Definition at line 40 of file ConditionsRepository.cpp.
~ConditionsRepository()
ConditionsRepository::~ConditionsRepository () virtual
Default destructor.
Definition at line 44 of file ConditionsRepository.cpp.
References _U, DD4hep::Conditions::ConditionsRepository::Entry::address, DD4hep::Conditions::Interna::ConditionObject::address, DD4hep::Conditions::Condition::address(), DD4hep::ALWAYS, DD4hep::XML::Element::append(), DD4hep::XML::Handle_t::attr(), DD4hep::XML::DocumentHandler::create(), e, DD4hep::except(), DD4hep::XML::Collection_t::for_each(), DD4hep::Conditions::ConditionsRepository::Entry::key, DD4hep::Conditions::Condition::key(), load(), DD4hep::NamedObject::name, DD4hep::Conditions::ConditionsRepository::Entry::name, DD4hep::Conditions::Condition::name(), DD4hep::XML::DocumentHandler::output(), DD4hep::printout(), and DD4hep::XML::Document::root().
Member Function Documentation
load()
int ConditionsRepository::load (const std::string & input, Data & data) const
Load the repository from file and fill user passed data structory.
Definition at line 231 of file ConditionsRepository.cpp.
save()
int ConditionsRepository::save (ConditionsManager m, const std::string & output) const
Save the repository to file.
Write XML file with conditions addresses
Write fixed records with conditions addresses
Write fixed records with conditions addresses
Write records separated by ';' with conditions addresses
Definition at line 188 of file ConditionsRepository.cpp.
References _E, _T(), e, DD4hep::Conditions::ConditionsIOVPool::elements, DD4hep::Conditions::ConditionsManager::iovPool(), DD4hep::Conditions::ConditionsManager::iovTypesUsed(), and DD4hep::Conditions::ConditionsPool::select_all().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsRepository.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsRepository.cpp