DD4hep: DD4hep::Conditions::ConditionKey Class Reference
DD4hep::Conditions::ConditionKey Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Key definition to optimize ans simplyfy the access to conditions entities.
#include <Conditions.h>
Public Types
typedef Condition::key_type key_type
Forward definition of the key type.
Public Member Functions
ConditionKey ()
Default constructor.
ConditionKey (const std::string &compare)
Constructor from string.
ConditionKey (const std::string &s, key_type h)
Constructor from string.
ConditionKey (const ConditionKey &c)
Copy constructor.
ConditionKey & operator= (const std::string &value)
Assignment operator from the string representation.
ConditionKey & operator= (const ConditionKey &key)
Assignment operator from object copy.
bool operator== (const ConditionKey &compare) const
Equality operator using key object.
bool operator== (const key_type compare) const
Equality operator using hash value.
bool operator== (const std::string &compare) const
Equality operator using the string representation.
bool operator< (const ConditionKey &compare) const
Operator less (for map insertions) using key object.
bool operator< (const key_type compare) const
Operator less (for map insertions) using hash value.
bool operator< (const std::string &compare) const
Operator less (for map insertions) using the string representation.
operator const std::string & () const
Automatic conversion to the string representation of the key object.
operator key_type () const
Automatic conversion to the hashed representation of the key object.
Static Public Member Functions
static key_type hashCode (const char *value)
Hash code generation from input string.
static key_type hashCode (const std::string &value)
Hash code generation from input string.
Public Attributes
std::string name
String representation of the key object.
key_type hash
Hashed key representation.
Detailed Description
Key definition to optimize ans simplyfy the access to conditions entities.
Author
M.Frank
Version
1.0
Definition at line 238 of file Conditions.h.
Member Typedef Documentation
key_type
typedef Condition::key_type DD4hep::Conditions::ConditionKey::key_type
Forward definition of the key type.
Definition at line 241 of file Conditions.h.
Constructor & Destructor Documentation
ConditionKey() [1/4]
DD4hep::Conditions::ConditionKey::ConditionKey () inline
Default constructor.
Definition at line 250 of file Conditions.h.
ConditionKey() [2/4]
ConditionKey::ConditionKey (const std::string & compare)
Constructor from string.
Definition at line 36 of file Conditions.cpp.
ConditionKey() [3/4]
DD4hep::Conditions::ConditionKey::ConditionKey (const std::string & s, key_type h) inline
Constructor from string.
Definition at line 254 of file Conditions.h.
ConditionKey() [4/4]
DD4hep::Conditions::ConditionKey::ConditionKey (const ConditionKey & c) inline
Copy constructor.
Definition at line 256 of file Conditions.h.
References DD4hep::Conditions::Condition::key(), DD4hep::Handle< Interna::ConditionObject >::operator<(), DD4hep::Conditions::Condition::operator=(), DD4hep::Handle< Interna::ConditionObject >::operator==(), and DD4hep::Conditions::Condition::value().
Member Function Documentation
hashCode() [1/2]
ConditionKey::key_type DD4hep::Conditions::ConditionKey::hashCode (const char * value) inline static
Hash code generation from input string.
Definition at line 288 of file Conditions.h.
References DD4hep::hash32().
Referenced by DD4hep::Conditions::Interna::ConditionContainer::addKey(), DD4hep::Conditions::Condition::Condition(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), DD4hep::Conditions::Interna::ConditionContainer::get(), operator<(), and operator=().
hashCode() [2/2]
ConditionKey::key_type DD4hep::Conditions::ConditionKey::hashCode (const std::string & value) inline static
Hash code generation from input string.
Definition at line 292 of file Conditions.h.
References DD4hep::hash32().
operator const std::string &()
DD4hep::Conditions::ConditionKey::operator const std::string & () const inline
Automatic conversion to the string representation of the key object.
Definition at line 282 of file Conditions.h.
References DD4hep::Conditions::Condition::name().
operator key_type()
DD4hep::Conditions::ConditionKey::operator key_type () const inline
Automatic conversion to the hashed representation of the key object.
Definition at line 284 of file Conditions.h.
References DD4hep::Simulation::hash().
operator<() [1/3]
bool DD4hep::Conditions::ConditionKey::operator< (const ConditionKey & compare) const inline
Operator less (for map insertions) using key object.
Definition at line 313 of file Conditions.h.
References DD4hep::Simulation::hash(), and hash.
operator<() [2/3]
bool DD4hep::Conditions::ConditionKey::operator< (const key_type compare) const inline
Operator less (for map insertions) using hash value.
Definition at line 317 of file Conditions.h.
References DD4hep::Simulation::hash(), and DD4hep::Conditions::make_key().
operator<() [3/3]
bool ConditionKey::operator< (const std::string & compare) const
Operator less (for map insertions) using the string representation.
Definition at line 50 of file Conditions.cpp.
References hash, and hashCode().
operator=() [1/2]
ConditionKey & ConditionKey::operator= (const std::string & value)
Assignment operator from the string representation.
Definition at line 42 of file Conditions.cpp.
References hash, hashCode(), and name.
operator=() [2/2]
ConditionKey & DD4hep::Conditions::ConditionKey::operator= (const ConditionKey & key) inline
Assignment operator from object copy.
Definition at line 296 of file Conditions.h.
References DD4hep::Simulation::hash(), hash, DD4hep::Conditions::Condition::name(), and name.
operator==() [1/3]
bool DD4hep::Conditions::ConditionKey::operator== (const ConditionKey & compare) const inline
Equality operator using key object.
Definition at line 305 of file Conditions.h.
References DD4hep::Simulation::hash(), and hash.
operator==() [2/3]
bool DD4hep::Conditions::ConditionKey::operator== (const key_type compare) const inline
Equality operator using hash value.
Definition at line 309 of file Conditions.h.
References DD4hep::Simulation::hash().
operator==() [3/3]
bool DD4hep::Conditions::ConditionKey::operator== (const std::string & compare) const
Equality operator using the string representation.
Member Data Documentation
hash
key_type DD4hep::Conditions::ConditionKey::hash
Hashed key representation.
Definition at line 246 of file Conditions.h.
Referenced by DD4hep::Conditions::ConditionDependency::key(), operator<(), operator=(), operator==(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
name
std::string DD4hep::Conditions::ConditionKey::name
String representation of the key object.
Definition at line 244 of file Conditions.h.
Referenced by DD4hep::Conditions::ConditionUpdateContext::condition(), DD4hep::Conditions::ConditionDependency::ConditionDependency(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), DD4hep::Alignments::AlignmentUpdateCall::handle(), DD4hep::Conditions::ConditionDependency::operator=(), and operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Conditions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Conditions.cpp