DD4hep: DD4hep: DD4hep::DDRec::LayeredSubdetector Class Reference
DD4hep::DDRec::LayeredSubdetector Class Reference
#include <LayeredSubdetector.h>
Public Member Functions
LayeredSubdetector (const Geometry::DetElement &det)
Default constructor.
virtual ~LayeredSubdetector ()
Destructor.
int numberOfLayers () const
Access to the total number of layers.
int numberOfSensors (int layerIndex=0) const
Access to the total number of sensors in a given layer index.
Geometry::DetElement layer (int layerIndex) const
Access to the layer DetElement for the given index.
const std::vector
< Geometry::DetElement > & sensors (int layerIndex=0) const
Access to the sensitive DetElements of a given layer index.
const std::vector
< Geometry::DetElement > & absorbers (int layerIndex=0) const
Access to the non-sensitive DetElements of a given layer index.
double totalThickness () const
Access the total thickness of the sub detector.
double totalRadiationLength () const
Access the total radiation length of the sub detector.
double totalInteractionLength () const
Access the total nuclear interaction length of the sub detector.
double thickness (int layerIndex=0) const
Access the total thickness of the layer with the given index.
double radiationLength (int layerIndex=0) const
Access the total radiation length of the layer with the given index.
double interactionLength (int layerIndex=0) const
Access the total nuclear interaction length of the layer with the given index.
double absorberThickness (int layerIndex) const
Access the total thickness of all non-sensitive elements of the layer with the given index.
double absorberRadiationLength (int layerIndex) const
Access the total radiation length of all non-sensitive elements of the layer with the given index.
double absorberInteractionLength (int layerIndex) const
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
virtual double sensorThickness (int layerIndex) const
Access the total thickness of all sensitive elements of the layer with the given index.
double sensorRadiationLength (int layerIndex) const
Access the total radiation length of all sensitive elements of the layer with the given index.
double sensorInteractionLength (int layerIndex) const
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
Protected Attributes
LayeringExtension * _layering
Private Member Functions
void getLayeringExtension ()
Helper method to retrieve the extension.
Detailed Description
Definition at line 21 of file LayeredSubdetector.h.
Constructor & Destructor Documentation
DD4hep::DDRec::LayeredSubdetector::LayeredSubdetector (const Geometry::DetElement & det) [inline]
Default constructor.
Definition at line 24 of file LayeredSubdetector.h.
References getLayeringExtension().
virtual DD4hep::DDRec::LayeredSubdetector::~LayeredSubdetector () [inline, virtual]
Destructor.
Definition at line 30 of file LayeredSubdetector.h.
Member Function Documentation
double DD4hep::DDRec::LayeredSubdetector::absorberInteractionLength (int layerIndex) const [inline, virtual]
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 89 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::absorberInteractionLength().
double DD4hep::DDRec::LayeredSubdetector::absorberRadiationLength (int layerIndex) const [inline, virtual]
Access the total radiation length of all non-sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 84 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::absorberRadiationLength().
const std::vector<Geometry::DetElement>& DD4hep::DDRec::LayeredSubdetector::absorbers (int layerIndex = 0) const [inline, virtual]
Access to the non-sensitive DetElements of a given layer index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 50 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::absorbers().
double DD4hep::DDRec::LayeredSubdetector::absorberThickness (int layerIndex) const [inline, virtual]
Access the total thickness of all non-sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 79 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::absorberThickness().
void DD4hep::DDRec::LayeredSubdetector::getLayeringExtension () [inline, private]
Helper method to retrieve the extension.
Definition at line 114 of file LayeredSubdetector.h.
References _layering, and DD4hep::Handle< T >::isValid().
Referenced by LayeredSubdetector().
double DD4hep::DDRec::LayeredSubdetector::interactionLength (int layerIndex = 0) const [inline, virtual]
Access the total nuclear interaction length of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 74 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::interactionLength().
Geometry::DetElement DD4hep::DDRec::LayeredSubdetector::layer (int layerIndex) const [inline, virtual]
Access to the layer DetElement for the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 42 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::layer().
int DD4hep::DDRec::LayeredSubdetector::numberOfLayers () const [inline, virtual]
Access to the total number of layers.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 34 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::numberOfLayers().
int DD4hep::DDRec::LayeredSubdetector::numberOfSensors (int layerIndex = 0) const [inline, virtual]
Access to the total number of sensors in a given layer index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 38 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::numberOfSensors().
double DD4hep::DDRec::LayeredSubdetector::radiationLength (int layerIndex = 0) const [inline, virtual]
Access the total radiation length of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 70 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::radiationLength().
double DD4hep::DDRec::LayeredSubdetector::sensorInteractionLength (int layerIndex) const [inline, virtual]
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 104 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::sensorInteractionLength().
double DD4hep::DDRec::LayeredSubdetector::sensorRadiationLength (int layerIndex) const [inline, virtual]
Access the total radiation length of all sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 99 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::sensorRadiationLength().
const std::vector<Geometry::DetElement>& DD4hep::DDRec::LayeredSubdetector::sensors (int layerIndex = 0) const [inline, virtual]
Access to the sensitive DetElements of a given layer index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 46 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::sensors().
virtual double DD4hep::DDRec::LayeredSubdetector::sensorThickness (int layerIndex) const [inline, virtual]
Access the total thickness of all sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 94 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::sensorThickness().
double DD4hep::DDRec::LayeredSubdetector::thickness (int layerIndex = 0) const [inline, virtual]
Access the total thickness of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 66 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::thickness().
double DD4hep::DDRec::LayeredSubdetector::totalInteractionLength () const [inline, virtual]
Access the total nuclear interaction length of the sub detector.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 62 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::totalInteractionLength().
double DD4hep::DDRec::LayeredSubdetector::totalRadiationLength () const [inline, virtual]
Access the total radiation length of the sub detector.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 58 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::totalRadiationLength().
double DD4hep::DDRec::LayeredSubdetector::totalThickness () const [inline, virtual]
Access the total thickness of the sub detector.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 54 of file LayeredSubdetector.h.
References _layering, and DD4hep::DDRec::LayeringExtension::totalThickness().
Member Data Documentation
LayeringExtension* DD4hep::DDRec::LayeredSubdetector::_layering [protected]
Definition at line 110 of file LayeredSubdetector.h.
Referenced by absorberInteractionLength(), absorberRadiationLength(), absorbers(), absorberThickness(), getLayeringExtension(), interactionLength(), layer(), numberOfLayers(), numberOfSensors(), radiationLength(), sensorInteractionLength(), sensorRadiationLength(), sensors(), sensorThickness(), thickness(), totalInteractionLength(), totalRadiationLength(), and totalThickness().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/API/LayeredSubdetector.h