DD4hep: DD4hep: DD4hep::Simulation::Geant4UIManager Class Reference
DD4hep::Simulation::Geant4UIManager Class Reference
Standard UI interface implementation with configuration using property options.
#include <Geant4UIManager.h>
Public Member Functions
Geant4UIManager (Geant4Context *context, const std::string &name)
Initializing constructor.
virtual ~Geant4UIManager ()
Default destructor.
G4VisManager * startVis ()
Start visualization.
G4UIExecutive * startUI ()
Start UI.
void start ()
Start manager & session.
void stop ()
Stop and release resources.
virtual void operator() (void *param)
Run UI.
Protected Attributes
std::string m_sessionType
Name of the default session type (="cmd").
std::string m_uiSetup
Property: Name of the UI macro file.
std::string m_visSetup
Property: Name of the visualization macro file.
std::vector< std::string > m_commands
Property: Array of macro files to be chained.
std::vector< std::string > m_macros
Property: Array of commands to be chained.
std::string m_prompt
Property: New prompt if the user wants to change it. (Default is do nothing).
bool m_haveVis
Property: Flag to instantiate Vis manager (default=false, unless m_visSetup set).
bool m_haveUI
Property: Flag to instantiate UI (default=true).
G4VisManager * m_vis
Reference to Geant4 visualtion manager.
G4UIExecutive * m_ui
Reference to Geant4 UI manager.
Detailed Description
Standard UI interface implementation with configuration using property options.
The {{Geant4UIManager}} is a component attached to the {{Geant4Kernel}} object.
All properties of all {{Geant4Action}} instances may be exported to Geant4 messengers and {{may}} hence be accessible directly from the Geant4 prompt. To export properties from any action, call the {{enableUI()}} method of the action.
Please note:
Any type of commands may be put together, but the overall execution order is as follows: 1. Execution of the visualization setup (Property: SetupVIS) 2. Execution of the user interface setup (Property: SetupUI) 3. Execution of the macro file list (Property: Macros) 4. Execution of the command list (Property: Commands)
Author:
M.Frank
Version:
1.0
Definition at line 54 of file Geant4UIManager.h.
Constructor & Destructor Documentation
Geant4UIManager::Geant4UIManager (Geant4Context * context, const std::string & name)
Initializing constructor.
Definition at line 39 of file Geant4UIManager.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), m_commands, m_haveUI, m_haveVis, m_macros, m_prompt, m_sessionType, m_uiSetup, and m_visSetup.
Geant4UIManager::~Geant4UIManager () [virtual]
Default destructor.
Definition at line 53 of file Geant4UIManager.cpp.
Member Function Documentation
void Geant4UIManager::operator() (void * param) [virtual]
Run UI.
Implements DD4hep::Simulation::Geant4Call.
Definition at line 84 of file Geant4UIManager.cpp.
References start(), and stop().
void Geant4UIManager::start ()
Start manager & session.
Definition at line 90 of file Geant4UIManager.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::INFO, DD4hep::Simulation::Geant4Context::kernel(), m_commands, m_haveUI, m_haveVis, m_macros, m_ui, m_uiSetup, m_vis, m_visSetup, DD4hep::printout(), DD4hep::Simulation::Geant4Kernel::property(), DD4hep::Simulation::Geant4Kernel::runManager(), startUI(), startVis(), DD4hep::Property::value(), and DD4hep::WARNING.
Referenced by operator()().
G4UIExecutive * Geant4UIManager::startUI ()
Start UI.
Definition at line 66 of file Geant4UIManager.cpp.
References DD4hep::INFO, m_prompt, m_sessionType, and DD4hep::printout().
Referenced by start().
G4VisManager * Geant4UIManager::startVis ()
Start visualization.
Definition at line 57 of file Geant4UIManager.cpp.
References DD4hep::INFO, and DD4hep::printout().
Referenced by start().
void Geant4UIManager::stop ()
Stop and release resources.
Definition at line 149 of file Geant4UIManager.cpp.
References DD4hep::deletePtr(), m_ui, and m_vis.
Referenced by operator()().
Member Data Documentation
std::vector<std::string> DD4hep::Simulation::Geant4UIManager::m_commands [protected]
Property: Array of macro files to be chained.
Definition at line 63 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and start().
bool DD4hep::Simulation::Geant4UIManager::m_haveUI [protected]
Property: Flag to instantiate UI (default=true).
Definition at line 71 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and start().
bool DD4hep::Simulation::Geant4UIManager::m_haveVis [protected]
Property: Flag to instantiate Vis manager (default=false, unless m_visSetup set).
Definition at line 69 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and start().
std::vector<std::string> DD4hep::Simulation::Geant4UIManager::m_macros [protected]
Property: Array of commands to be chained.
Definition at line 65 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and start().
std::string DD4hep::Simulation::Geant4UIManager::m_prompt [protected]
Property: New prompt if the user wants to change it. (Default is do nothing).
Definition at line 67 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and startUI().
std::string DD4hep::Simulation::Geant4UIManager::m_sessionType [protected]
Name of the default session type (="cmd").
Definition at line 57 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and startUI().
G4UIExecutive* DD4hep::Simulation::Geant4UIManager::m_ui [protected]
Reference to Geant4 UI manager.
Definition at line 75 of file Geant4UIManager.h.
Referenced by start(), and stop().
std::string DD4hep::Simulation::Geant4UIManager::m_uiSetup [protected]
Property: Name of the UI macro file.
Definition at line 59 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and start().
G4VisManager* DD4hep::Simulation::Geant4UIManager::m_vis [protected]
Reference to Geant4 visualtion manager.
Definition at line 73 of file Geant4UIManager.h.
Referenced by start(), and stop().
std::string DD4hep::Simulation::Geant4UIManager::m_visSetup [protected]
Property: Name of the visualization macro file.
Definition at line 61 of file Geant4UIManager.h.
Referenced by Geant4UIManager(), and start().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4UIManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4UIManager.cpp