DD4hep: DD4hep::Simulation::Geant4IsotropeGenerator Class Reference
DD4hep::Simulation::Geant4IsotropeGenerator Class Reference
DD4hep::Simulation components, classes and objects
Generate particles isotrop in space around origine (0,0,0)
#include <Geant4IsotropeGenerator.h>
Public Member Functions
Geant4IsotropeGenerator (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4IsotropeGenerator ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4ParticleGenerator
Geant4ParticleGenerator (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4ParticleGenerator ()
Default destructor.
virtual void operator() (G4Event *event)
Callback to generate primary particles.
Public Member Functions inherited from DD4hep::Simulation::Geant4GeneratorAction
Geant4GeneratorAction (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4GeneratorAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Member Functions
virtual void getParticleDirection (int num, ROOT::Math::XYZVector &direction, double &momentum) const
Particle modification. Caller presets defaults to: (direction = m_direction, momentum = m_energy)
void getParticleDirectionFFbar (int num, ROOT::Math::XYZVector &direction, double &momentum) const
e+e- –> ffbar particle distribution ~ 1 + cos^2(theta)
void getParticleDirectionEta (int num, ROOT::Math::XYZVector &direction, double &momentum) const
e+e- –> ffbar particle distribution ~ 1 + cos^2(theta)
void getParticleDirectionCosTheta (int num, ROOT::Math::XYZVector &direction, double &momentum) const
Particle distribution ~ cos(theta)
void getParticleDirectionUniform (int num, ROOT::Math::XYZVector &direction, double &momentum) const
Uniform particle distribution.
Protected Member Functions inherited from DD4hep::Simulation::Geant4ParticleGenerator
virtual void getParticleMultiplicity (int &multiplicity) const
Particle modification. Caller presets defaults to: (multiplicity=m_multiplicity)
virtual void getVertexPosition (ROOT::Math::XYZVector &position) const
Particle's vertex modification. Caller presets defaults to: (multiplicity=m_multiplicity)
virtual void printInteraction (int mask) const
Print single particle interaction identified by its mask.
virtual void printInteraction (Geant4PrimaryInteraction *inter) const
Print single particle interaction identified by it's reference.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes
std::string m_distribution
Property: Distribution name. Default: "uniform". Allowed: "uniform", "cos(theta)", "ffbar", "eta".
double m_phiMin
Property: Minimal phi angular value.
double m_phiMax
Property: Maximal phi angular value.
double m_thetaMin
Property: Minimal theta angular value.
double m_thetaMax
Property: Maximal theta angular value.
Protected Attributes inherited from DD4hep::Simulation::Geant4ParticleGenerator
ROOT::Math::XYZVector m_direction
Property: Shooting direction of the gun.
ROOT::Math::XYZVector m_position
Property: Position of the gun in space.
std::string m_particleName
Property: Particle name.
G4ParticleDefinition * m_particle
Pointer to geant4 particle definition.
double m_energy
Property: Particle energy.
int m_multiplicity
Property: Desired multiplicity of the particles to be shot.
int m_mask
Property: User mask passed to all particles in the generated interaction.
Protected Attributes inherited from DD4hep::Simulation::Geant4GeneratorAction
Callback m_calls
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4GeneratorAction
typedef Geant4SharedGeneratorAction shared_type
Detailed Description
Generate particles isotrop in space around origine (0,0,0)
Author
M.Frank
Version
1.0
Definition at line 32 of file Geant4IsotropeGenerator.h.
Constructor & Destructor Documentation
Geant4IsotropeGenerator()
Geant4IsotropeGenerator::Geant4IsotropeGenerator (Geant4Context * context, const std::string & name)
Standard constructor.
Definition at line 25 of file Geant4IsotropeGenerator.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_distribution, m_phiMax, m_phiMin, M_PI, m_thetaMax, and m_thetaMin.
~Geant4IsotropeGenerator()
Geant4IsotropeGenerator::~Geant4IsotropeGenerator () virtual
Default destructor.
Definition at line 37 of file Geant4IsotropeGenerator.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
getParticleDirection()
void Geant4IsotropeGenerator::getParticleDirection (int num, ROOT::Math::XYZVector & direction, double & momentum) const protected virtual
Particle modification. Caller presets defaults to: (direction = m_direction, momentum = m_energy)
Use this function to implement isotrop guns, multiple guns etc. User must return a UNIT vector, which gets scaled with momentum.
Reimplemented from DD4hep::Simulation::Geant4ParticleGenerator.
Reimplemented in DD4hep::Simulation::Geant4ParticleGun.
Definition at line 121 of file Geant4IsotropeGenerator.cpp.
References DD4hep::Simulation::Geant4Action::except(), getParticleDirectionCosTheta(), getParticleDirectionEta(), getParticleDirectionFFbar(), getParticleDirectionUniform(), and m_distribution.
Referenced by DD4hep::Simulation::Geant4ParticleGun::operator()().
getParticleDirectionCosTheta()
void Geant4IsotropeGenerator::getParticleDirectionCosTheta (int num, ROOT::Math::XYZVector & direction, double & momentum) const protected
Particle distribution ~ cos(theta)
Definition at line 56 of file Geant4IsotropeGenerator.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), m_phiMax, m_phiMin, m_thetaMax, m_thetaMin, DD4hep::Simulation::Geant4Event::random(), and DD4hep::Simulation::Geant4Random::rndm().
Referenced by getParticleDirection().
getParticleDirectionEta()
void Geant4IsotropeGenerator::getParticleDirectionEta (int num, ROOT::Math::XYZVector & direction, double & momentum) const protected
e+e- –> ffbar particle distribution ~ 1 + cos^2(theta)
Particle distribution flat in eta (pseudo rapidity)
Definition at line 71 of file Geant4IsotropeGenerator.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), m_phiMax, m_phiMin, M_PI, m_thetaMax, m_thetaMin, DD4hep::Simulation::Geant4Event::random(), and DD4hep::Simulation::Geant4Random::rndm().
Referenced by getParticleDirection().
getParticleDirectionFFbar()
void Geant4IsotropeGenerator::getParticleDirectionFFbar (int num, ROOT::Math::XYZVector & direction, double & momentum) const protected
e+e- –> ffbar particle distribution ~ 1 + cos^2(theta)
Definition at line 92 of file Geant4IsotropeGenerator.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), m_phiMax, m_phiMin, m_thetaMax, m_thetaMin, DD4hep::Simulation::Geant4Event::random(), and DD4hep::Simulation::Geant4Random::rndm().
Referenced by getParticleDirection().
getParticleDirectionUniform()
void Geant4IsotropeGenerator::getParticleDirectionUniform (int num, ROOT::Math::XYZVector & direction, double & momentum) const protected
Uniform particle distribution.
Definition at line 42 of file Geant4IsotropeGenerator.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), m_phiMax, m_phiMin, m_thetaMax, m_thetaMin, DD4hep::Simulation::Geant4Event::random(), and DD4hep::Simulation::Geant4Random::rndm().
Referenced by getParticleDirection().
Member Data Documentation
m_distribution
std::string DD4hep::Simulation::Geant4IsotropeGenerator::m_distribution protected
Property: Distribution name. Default: "uniform". Allowed: "uniform", "cos(theta)", "ffbar", "eta".
Definition at line 35 of file Geant4IsotropeGenerator.h.
Referenced by Geant4IsotropeGenerator(), and getParticleDirection().
m_phiMax
double DD4hep::Simulation::Geant4IsotropeGenerator::m_phiMax protected
Property: Maximal phi angular value.
Definition at line 39 of file Geant4IsotropeGenerator.h.
Referenced by Geant4IsotropeGenerator(), getParticleDirectionCosTheta(), getParticleDirectionEta(), getParticleDirectionFFbar(), and getParticleDirectionUniform().
m_phiMin
double DD4hep::Simulation::Geant4IsotropeGenerator::m_phiMin protected
Property: Minimal phi angular value.
Definition at line 37 of file Geant4IsotropeGenerator.h.
Referenced by Geant4IsotropeGenerator(), getParticleDirectionCosTheta(), getParticleDirectionEta(), getParticleDirectionFFbar(), and getParticleDirectionUniform().
m_thetaMax
double DD4hep::Simulation::Geant4IsotropeGenerator::m_thetaMax protected
Property: Maximal theta angular value.
Definition at line 43 of file Geant4IsotropeGenerator.h.
Referenced by Geant4IsotropeGenerator(), getParticleDirectionCosTheta(), getParticleDirectionEta(), getParticleDirectionFFbar(), and getParticleDirectionUniform().
m_thetaMin
double DD4hep::Simulation::Geant4IsotropeGenerator::m_thetaMin protected
Property: Minimal theta angular value.
Definition at line 41 of file Geant4IsotropeGenerator.h.
Referenced by Geant4IsotropeGenerator(), getParticleDirectionCosTheta(), getParticleDirectionEta(), getParticleDirectionFFbar(), and getParticleDirectionUniform().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4IsotropeGenerator.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4IsotropeGenerator.cpp