DD4hep: DD4hep: DD4hep::Simulation::LCIOFileReader Class Reference
DD4hep::Simulation::LCIOFileReader Class Reference
[DD4hep::Simulation components, classes and objects]
Base class to read lcio event files.
Public Member Functions
LCIOFileReader (const std::string &nam)
Initializing constructor.
virtual ~LCIOFileReader ()
Default destructor.
virtual EventReaderStatus readParticleCollection (int event_number, EVENT::LCCollection **particles)
Read an event and fill a vector of MCParticles.
virtual EventReaderStatus moveToEvent (int event_number)
moveToSpecifiedEvent, a.k.a. skipNEvents
virtual EventReaderStatus skipEvent ()
Skip event. To be implemented for sequential sources.
Protected Attributes
IO::LCReader * m_reader
Reference to reader object.
Detailed Description
Base class to read lcio event files.
Author:
P.Kostka (main author)
M.Frank (code reshuffeling into new DDG4 scheme)
Version:
1.0
Definition at line 51 of file LCIOFileReader.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::LCIOFileReader::LCIOFileReader (const std::string & nam)
Initializing constructor.
Definition at line 80 of file LCIOFileReader.cpp.
References DD4hep::INFO, m_reader, and DD4hep::printout().
DD4hep::Simulation::LCIOFileReader::~LCIOFileReader () [virtual]
Default destructor.
Definition at line 90 of file LCIOFileReader.cpp.
References DD4hep::deletePtr(), and m_reader.
Member Function Documentation
Geant4EventReader::EventReaderStatus DD4hep::Simulation::LCIOFileReader::moveToEvent (int event_number) [virtual]
moveToSpecifiedEvent, a.k.a. skipNEvents
Reimplemented from DD4hep::Simulation::Geant4EventReader.
Definition at line 97 of file LCIOFileReader.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::INFO, DD4hep::Simulation::Geant4EventReader::m_currEvent, m_reader, and DD4hep::printout().
Geant4EventReader::EventReaderStatus DD4hep::Simulation::LCIOFileReader::readParticleCollection (int event_number, EVENT::LCCollection ** particles) [virtual]
Read an event and fill a vector of MCParticles.
Implements DD4hep::Simulation::LCIOEventReader.
Definition at line 112 of file LCIOFileReader.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_ERROR, DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::INFO, DD4hep::Simulation::Geant4EventReader::m_currEvent, m_reader, and DD4hep::printout().
virtual EventReaderStatus DD4hep::Simulation::LCIOFileReader::skipEvent () [inline, virtual]
Skip event. To be implemented for sequential sources.
Reimplemented from DD4hep::Simulation::Geant4EventReader.
Definition at line 64 of file LCIOFileReader.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK.
Member Data Documentation
IO::LCReader* DD4hep::Simulation::LCIOFileReader::m_reader [protected]
Reference to reader object.
Definition at line 54 of file LCIOFileReader.cpp.
Referenced by moveToEvent(), readParticleCollection(), and ~LCIOFileReader().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/lcio/LCIOFileReader.cpp