DD4hep: DD4hep::Alignments::Container Class Reference
DD4hep::Alignments::Container Class Reference
Container class for alignment handles aggregated by a detector element.
#include <Alignments.h>
Public Types
typedef Interna::AlignmentContainer Object
Standard object type.
typedef Alignment::key_type key_type
Forward definition of the key type.
typedef Alignment::iov_type iov_type
Forward definition of the iov type.
Public Types inherited from DD4hep::Handle< Interna::AlignmentContainer >
typedef Interna::AlignmentContainer Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Container ()
Default constructor.
template<typename Q >
Container (const Container &c)
Constructor to be used when reading the already parsed object.
template<typename Q >
Container (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
size_t numKeys () const
Access the number of conditons keys available for this detector element.
Alignment get (const std::string &alignment_key, const iov_type &iov)
Access to alignment objects by key and IOV.
Alignment get (key_type alignment_key, const iov_type &iov)
Access to alignment objects directly by their hash key.
Alignment get (const std::string &alignment_key, const UserPool &iov)
Access to alignment objects. Only alignments in the pool are accessed.
Alignment get (key_type alignment_key, const UserPool &iov)
Access to alignment objects. Only alignments in the pool are accessed.
Public Member Functions inherited from DD4hep::Handle< Interna::AlignmentContainer >
Handle ()
Defaulot constructor.
Handle (Interna::AlignmentContainer *e)
Initializing constructor from pointer.
Handle (const Handle< Interna::AlignmentContainer > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< Interna::AlignmentContainer > & operator= (const Handle< Interna::AlignmentContainer > &e)=default
Assignment operator.
bool operator== (const Handle< Interna::AlignmentContainer > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< Interna::AlignmentContainer > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< Interna::AlignmentContainer > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< Interna::AlignmentContainer > & clear ()
Release the object held by the handle.
Interna::AlignmentContainer * operator-> () const
Access the held object using the -> operator.
operator Interna::AlignmentContainer & () const
Automatic type conversion to an object references.
Interna::AlignmentContainer & operator* () const
Access the held object using the * operator.
Interna::AlignmentContainer * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
Interna::AlignmentContainer * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< Interna::AlignmentContainer >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< Interna::AlignmentContainer >
Interna::AlignmentContainer * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Container class for alignment handles aggregated by a detector element.
Note: The alignments container is owner by the detector element On deletion the detector element will destroy the container and all associated entries.
Author
M.Frank
Version
1.0
Definition at line 183 of file Alignments.h.
Member Typedef Documentation
iov_type
typedef Alignment::iov_type DD4hep::Alignments::Container::iov_type
Forward definition of the iov type.
Definition at line 190 of file Alignments.h.
key_type
typedef Alignment::key_type DD4hep::Alignments::Container::key_type
Forward definition of the key type.
Definition at line 188 of file Alignments.h.
Object
typedef Interna::AlignmentContainer DD4hep::Alignments::Container::Object
Standard object type.
Definition at line 186 of file Alignments.h.
Constructor & Destructor Documentation
Container() [1/3]
DD4hep::Alignments::Container::Container () inline
Default constructor.
Definition at line 219 of file Alignments.h.
Container() [2/3]
template<typename Q > DD4hep::Alignments::Container::Container (const Container & c) inline
Constructor to be used when reading the already parsed object.
Definition at line 197 of file Alignments.h.
Container() [3/3]
template<typename Q > DD4hep::Alignments::Container::Container (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 200 of file Alignments.h.
Member Function Documentation
get() [1/4]
Alignment Container::get (const std::string & alignment_key, const iov_type & iov)
Access to alignment objects by key and IOV.
Access to alignment objects.
Definition at line 124 of file Alignments.cpp.
References DD4hep::Alignments::Interna::AlignmentContainer::get(), and DD4hep::Handle< T >::isValid().
get() [2/4]
Alignment Container::get (key_type alignment_key, const iov_type & iov)
Access to alignment objects directly by their hash key.
Access to alignment objects.
Definition at line 138 of file Alignments.cpp.
References DD4hep::Alignments::Interna::AlignmentContainer::get(), and DD4hep::Handle< T >::isValid().
get() [3/4]
Alignment Container::get (const std::string & alignment_key, const UserPool & iov)
Access to alignment objects. Only alignments in the pool are accessed.
Access to alignment objects.
Definition at line 152 of file Alignments.cpp.
References DD4hep::Alignments::Interna::AlignmentContainer::get(), and DD4hep::Handle< T >::isValid().
get() [4/4]
Alignment Container::get (key_type alignment_key, const UserPool & iov)
Access to alignment objects. Only alignments in the pool are accessed.
Access to alignment objects.
Definition at line 166 of file Alignments.cpp.
References DD4hep::Alignments::Interna::AlignmentContainer::get(), and DD4hep::Handle< T >::isValid().
numKeys()
size_t Container::numKeys () const
Access the number of conditons keys available for this detector element.
Definition at line 119 of file Alignments.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Alignments.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Alignments.cpp