DD4hep: DD4hep::Simulation::Geant4Converter Class Reference
DD4hep::Simulation::Geant4Converter Class Reference
DD4hep::Simulation components, classes and objects
Geometry converter from DD4hep to Geant 4.
#include <Geant4Converter.h>
Public Member Functions
Geant4Converter (LCDD &lcdd)
Initializing Constructor.
Geant4Converter (LCDD &lcdd, PrintLevel level)
Initializing Constructor.
virtual ~Geant4Converter ()
Standard destructor.
Geant4Converter & create (DetElement top)
Create geometry conversion.
virtual void * handleMaterial (const std::string &name, Material medium) const
Convert the geometry type material into the corresponding Geant4 object(s).
virtual void * handleElement (const std::string &name, Atom element) const
Convert the geometry type element into the corresponding Geant4 object(s).
virtual void * handleSolid (const std::string &name, const TGeoShape *volume) const
Convert the geometry type solid into the corresponding Geant4 object(s).
virtual void * handleVolume (const std::string &name, const TGeoVolume *volume) const
Convert the geometry type logical volume into the corresponding Geant4 object(s).
virtual void * collectVolume (const std::string &name, const TGeoVolume *volume) const
Dump logical volume in GDML format to output stream.
virtual void * handlePlacement (const std::string &name, const TGeoNode *node) const
Convert the geometry type volume placement into the corresponding Geant4 object(s).
virtual void * handleAssembly (const std::string &name, const TGeoNode *node) const
Dump volume placement in GDML format to output stream.
virtual void * handleRegion (Region region, const std::set< const TGeoVolume *> &volumes) const
Convert the geometry type region into the corresponding Geant4 object(s).
virtual void * handleVis (const std::string &name, VisAttr vis) const
Convert the geometry visualisation attributes to the corresponding Geant4 object(s).
virtual void * handleLimitSet (LimitSet limitset, const std::set< const TGeoVolume *> &volumes) const
Convert the geometry type LimitSet into the corresponding Geant4 object(s).
void handleProperties (LCDD::Properties &prp) const
Handle the geant 4 specific properties.
virtual void printSensitive (SensitiveDetector sens_det, const std::set< const TGeoVolume *> &volumes) const
Print the geometry type SensitiveDetector.
virtual void * printPlacement (const std::string &name, const TGeoNode *node) const
Print Geant4 placement.
Public Member Functions inherited from DD4hep::Geometry::GeoHandler
GeoHandler ()
Default constructor.
GeoHandler (Data *ptr)
Initializing constructor.
virtual ~GeoHandler ()
Default destructor.
bool setPropagateRegions (bool value)
Propagate regions. Returns the previous value.
GeoHandler & collect (DetElement top)
Collect geometry information from traversal.
GeoHandler & collect (DetElement top, GeometryInfo &info)
Collect geometry information from traversal with aggregated information.
Data * release ()
Access to collected node list.
Public Member Functions inherited from DD4hep::Simulation::Geant4Mapping
Geant4Mapping (LCDD &lcdd)
Initializing Constructor.
virtual ~Geant4Mapping ()
Standard destructor.
LCDD & lcdd () const
Accesor to the LCDD instance.
Geant4GeometryInfo & data () const
Access to the data pointer.
Geant4GeometryInfo * ptr () const
Access to the data pointer.
Geant4GeometryInfo & init ()
Create and attach new data block. Delete old data block if present.
Geant4GeometryInfo * detach ()
Release data and pass over the ownership.
void attach (Geant4GeometryInfo *data)
Set a new data block.
Geant4VolumeManager volumeManager () const
Access the volume manager.
PlacedVolume placement (const G4VPhysicalVolume *node) const
Accessor to resolve geometry placements.
Public Attributes
bool m_checkOverlaps
PrintLevel m_outputLevel
Additional Inherited Members
Public Types inherited from DD4hep::Geometry::GeoHandlerTypes
typedef std::set< Volume > VolumeSet
typedef std::vector< Volume > VolumeVector
typedef std::set< const TGeoVolume * > ConstVolumeSet
typedef std::vector< std::pair< std::string, TGeoMatrix * > > TransformSet
typedef std::set< TGeoShape * > SolidSet
typedef std::set< Material > MaterialSet
typedef std::map< SensitiveDetector, ConstVolumeSet > SensitiveVolumes
typedef std::map< Region, ConstVolumeSet > RegionVolumes
typedef std::map< LimitSet, ConstVolumeSet > LimitVolumes
typedef std::map< int, std::set< const TGeoNode * > > Data
typedef std::set< VisAttr > VisRefs
typedef std::set< SensitiveDetector > SensitiveDetectorSet
typedef std::set< Region > RegionSet
typedef std::set< LimitSet > LimitSetSet
typedef std::set< Ref_t > Fields
typedef std::set< TNamed * > ObjectSet
typedef LCDD::HandleMap DefinitionSet
Public Types inherited from DD4hep::Simulation::Geant4Mapping
typedef Geometry::LCDD LCDD
typedef Geometry::DetElement DetElement
typedef Geometry::SensitiveDetector SensitiveDetector
typedef Geometry::Solid Solid
typedef Geometry::Volume Volume
typedef Geometry::PlacedVolume PlacedVolume
typedef Geometry::Atom Atom
typedef Geometry::Material Material
typedef Geometry::Region Region
typedef Geometry::VisAttr VisAttr
typedef Geometry::LimitSet LimitSet
Static Public Member Functions inherited from DD4hep::Simulation::Geant4Mapping
static Geant4Mapping & instance ()
Possibility to define a singleton instance.
Protected Member Functions inherited from DD4hep::Geometry::GeoHandler
GeoHandler & i_collect (const TGeoNode *node, int level, Region rg, LimitSet ls)
Internal helper to collect geometry information from traversal.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Mapping
void checkValidity () const
When resolving pointers, we must check for the validity of the data block.
Protected Attributes inherited from DD4hep::Geometry::GeoHandler
bool m_propagateRegions
Data * m_data
Protected Attributes inherited from DD4hep::Simulation::Geant4Mapping
LCDD & m_lcdd
Geant4GeometryInfo * m_dataPtr
Detailed Description
Geometry converter from DD4hep to Geant 4.
Author
M.Frank
Version
1.0
Definition at line 33 of file Geant4Converter.h.
Constructor & Destructor Documentation
Geant4Converter() [1/2]
Geant4Converter::Geant4Converter (LCDD & lcdd)
Initializing Constructor.
Definition at line 265 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::init(), m_outputLevel, DD4hep::Geometry::GeoHandler::m_propagateRegions, and DD4hep::printLevel().
Geant4Converter() [2/2]
Geant4Converter::Geant4Converter (LCDD & lcdd, PrintLevel level)
Initializing Constructor.
Definition at line 273 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::init(), m_outputLevel, and DD4hep::Geometry::GeoHandler::m_propagateRegions.
~Geant4Converter()
Geant4Converter::~Geant4Converter () virtual
Standard destructor.
Definition at line 281 of file Geant4Converter.cpp.
Member Function Documentation
collectVolume()
void * Geant4Converter::collectVolume (const std::string & name, const TGeoVolume * volume) const virtual
Dump logical volume in GDML format to output stream.
Definition at line 633 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Handle< T >::isValid(), DD4hep::Simulation::Geant4GeometryInfo::limits, DD4hep::Geometry::Volume::limitSet(), DD4hep::Geometry::Volume::region(), DD4hep::Simulation::Geant4GeometryInfo::regions, DD4hep::Geometry::Volume::sensitiveDetector(), DD4hep::Simulation::Geant4GeometryInfo::sensitives, and v.
Referenced by create().
create()
Geant4Converter & Geant4Converter::create (DetElement top)
Create geometry conversion.
Definition at line 1003 of file Geant4Converter.cpp.
References DD4hep::Geometry::GeoHandler::collect(), collectVolume(), handle(), handleAssembly(), handleLimitSet(), handleMap(), handleMaterial(), handlePlacement(), handleProperties(), handleRefs(), handleRegion(), handleRMap(), handleSolid(), handleVis(), handleVolume(), DD4hep::INFO, DD4hep::Simulation::Geant4Mapping::init(), DD4hep::Simulation::Geant4GeometryInfo::limits, m_checkOverlaps, DD4hep::Geometry::GeoHandler::m_data, DD4hep::Simulation::Geant4Mapping::m_lcdd, m_outputLevel, DD4hep::Geometry::LCDD::material(), DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), DD4hep::printout(), DD4hep::Geometry::LCDD::properties(), DD4hep::Handle< T >::ptr(), DD4hep::Simulation::Geant4GeometryInfo::regions, DD4hep::Simulation::Geant4GeometryInfo::setWorld(), DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::solids, DD4hep::Simulation::Geant4GeometryInfo::valid, DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::vis, and DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::volumes.
Referenced by DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo().
handleAssembly()
void * Geant4Converter::handleAssembly (const std::string & name, const TGeoNode * node) const virtual
Dump volume placement in GDML format to output stream.
Definition at line 651 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::FATAL, DD4hep::Simulation::Geant4GeometryInfo::g4AssemblyVolumes, DD4hep::Simulation::Geant4GeometryInfo::g4Volumes, m_outputLevel, DD4hep::Simulation::Geant4AssemblyVolume::placeAssembly(), DD4hep::Simulation::Geant4AssemblyVolume::placeVolume(), and DD4hep::printout().
Referenced by create().
handleElement()
void * Geant4Converter::handleElement (const std::string & name, Atom element) const virtual
Convert the geometry type element into the corresponding Geant4 object(s).
Dump element in GDML format to output stream.
Definition at line 285 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), dd4hep::g, DD4hep::Simulation::Geant4GeometryInfo::g4Elements, m_outputLevel, dd4hep::mole, and DD4hep::printout().
Referenced by handleMaterial().
handleLimitSet()
void * Geant4Converter::handleLimitSet (LimitSet limitset, const std::set< const TGeoVolume *> & volumes) const virtual
Convert the geometry type LimitSet into the corresponding Geant4 object(s).
Definition at line 813 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Simulation::Geant4GeometryInfo::g4Limits, DD4hep::Geometry::LimitSet::limits(), dd4hep::MeV, dd4hep::mm, DD4hep::Geometry::Limit::name, dd4hep::ns, DD4hep::Geometry::Limit::toString(), and DD4hep::Geometry::Limit::value.
Referenced by create().
handleMaterial()
void * Geant4Converter::handleMaterial (const std::string & name, Material medium) const virtual
Convert the geometry type material into the corresponding Geant4 object(s).
Dump material in GDML format to output stream.
Definition at line 314 of file Geant4Converter.cpp.
References dd4hep::cm3, DD4hep::Simulation::Geant4Mapping::data(), e, DD4hep::ERROR, DD4hep::Simulation::Geant4GeometryInfo::g4Materials, dd4hep::gram, handleElement(), m_outputLevel, mix, and DD4hep::printout().
Referenced by create(), and handleVolume().
handlePlacement()
void * Geant4Converter::handlePlacement (const std::string & name, const TGeoNode * node) const virtual
Convert the geometry type volume placement into the corresponding Geant4 object(s).
Dump volume placement in GDML format to output stream.
Definition at line 697 of file Geant4Converter.cpp.
References DD4hep::Alignments::AlignmentTools::copy(), DD4hep::Simulation::Geant4Mapping::data(), DD4hep::ERROR, DD4hep::FATAL, DD4hep::Simulation::Geant4GeometryInfo::g4AssemblyVolumes, DD4hep::Simulation::Geant4GeometryInfo::g4Placements, DD4hep::Simulation::Geant4GeometryInfo::g4Volumes, m_checkOverlaps, m_outputLevel, and DD4hep::printout().
Referenced by create().
handleProperties()
void Geant4Converter::handleProperties (LCDD::Properties & prp) const
Handle the geant 4 specific properties.
Definition at line 866 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::m_lcdd, m_outputLevel, and DD4hep::printout().
Referenced by create().
handleRegion()
void * Geant4Converter::handleRegion (Region region, const std::set< const TGeoVolume *> & volumes) const virtual
Convert the geometry type region into the corresponding Geant4 object(s).
Convert the geometry type field into the corresponding Geant4 object(s). virtual void* handleField(const std::string& name, Ref_t field) const;
Definition at line 770 of file Geant4Converter.cpp.
References DD4hep::Geometry::Region::cut(), DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Simulation::Geant4GeometryInfo::g4Limits, DD4hep::Simulation::Geant4GeometryInfo::g4Regions, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::Region::limits(), DD4hep::Geometry::LCDD::limitSet(), DD4hep::Simulation::Geant4Mapping::m_lcdd, m_outputLevel, dd4hep::MeV, DD4hep::Handle< T >::name(), DD4hep::printout(), DD4hep::Geometry::Region::storeSecondaries(), and DD4hep::Geometry::Region::threshold().
Referenced by create().
handleSolid()
void * Geant4Converter::handleSolid (const std::string & name, const TGeoShape * volume) const virtual
Convert the geometry type solid into the corresponding Geant4 object(s).
Dump solid in GDML format to output stream.
Definition at line 379 of file Geant4Converter.cpp.
References CM_2_MM, DD4hep::Simulation::Geant4Mapping::data(), DEGREE_2_RAD, DD4hep::Simulation::Geant4GeometryInfo::g4Solids, m, M_PI, and s.
Referenced by create(), and handleVolume().
handleVis()
void * Geant4Converter::handleVis (const std::string & name, VisAttr vis) const virtual
Convert the geometry visualisation attributes to the corresponding Geant4 object(s).
Definition at line 840 of file Geant4Converter.cpp.
References DD4hep::Geometry::VisAttr::alpha(), DD4hep::Geometry::VisAttr::DASHED, DD4hep::Simulation::Geant4Mapping::data(), dd4hep::g, DD4hep::Simulation::Geant4GeometryInfo::g4Vis, DD4hep::Geometry::VisAttr::lineStyle(), DD4hep::Geometry::VisAttr::rgb(), DD4hep::Geometry::VisAttr::showDaughters(), DD4hep::Geometry::VisAttr::SOLID, DD4hep::Geometry::VisAttr::visible(), and DD4hep::Geometry::VisAttr::WIREFRAME.
Referenced by create(), and handleVolume().
handleVolume()
void * Geant4Converter::handleVolume (const std::string & name, const TGeoVolume * volume) const virtual
Convert the geometry type logical volume into the corresponding Geant4 object(s).
Dump logical volume in GDML format to output stream.
Definition at line 561 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Simulation::Geant4GeometryInfo::g4Limits, DD4hep::Simulation::Geant4GeometryInfo::g4Regions, DD4hep::Simulation::Geant4GeometryInfo::g4Volumes, handleMaterial(), handleSolid(), handleVis(), DD4hep::Handle< T >::isValid(), DD4hep::Geometry::Volume::limitSet(), m, m_outputLevel, DD4hep::Handle< T >::name(), DD4hep::printout(), DD4hep::Geometry::Volume::region(), s, v, DD4hep::Geometry::Volume::visAttributes(), and DD4hep::yes_no().
Referenced by create().
printPlacement()
void * Geant4Converter::printPlacement (const std::string & name, const TGeoNode * node) const virtual
Print Geant4 placement.
Print G4 placement.
Definition at line 948 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Simulation::Geant4GeometryInfo::g4Placements, DD4hep::Simulation::Geant4GeometryInfo::g4Volumes, m_outputLevel, DD4hep::printout(), and printSolid().
printSensitive()
void Geant4Converter::printSensitive (SensitiveDetector sens_det, const std::set< const TGeoVolume *> & volumes) const virtual
Print the geometry type SensitiveDetector.
Convert the geometry type SensitiveDetector into the corresponding Geant4 object(s).
Definition at line 906 of file Geant4Converter.cpp.
References DD4hep::Simulation::Geant4Mapping::data(), DD4hep::Geometry::SensitiveDetector::energyCutoff(), DD4hep::Simulation::Geant4GeometryInfo::g4Volumes, DD4hep::Geometry::SensitiveDetector::hitsCollection(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::SensitiveDetector::limits(), DD4hep::Handle< T >::name(), DD4hep::printout(), DD4hep::Geometry::SensitiveDetector::region(), DD4hep::Simulation::Geant4GeometryInfo::sensitives, DD4hep::Geometry::SensitiveDetector::type(), and v.
Member Data Documentation
m_checkOverlaps
bool DD4hep::Simulation::Geant4Converter::m_checkOverlaps
Definition at line 35 of file Geant4Converter.h.
Referenced by create(), and handlePlacement().
m_outputLevel
PrintLevel DD4hep::Simulation::Geant4Converter::m_outputLevel
Definition at line 36 of file Geant4Converter.h.
Referenced by create(), Geant4Converter(), handleAssembly(), handleElement(), handleMaterial(), handlePlacement(), handleProperties(), handleRegion(), handleVolume(), and printPlacement().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Converter.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Converter.cpp