DD4hep: DD4hep::Conditions::ConditionsManager Class Reference
DD4hep::Conditions::ConditionsManager Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Manager class for condition handles.
#include <ConditionsManager.h>
Public Types
typedef ConditionsManagerObject Object
Standard object type.
typedef ConditionsDataLoader Loader
typedef std::vector< IOVType > IOVTypes
typedef std::map< IOVType *, Container > TypeConditions
typedef std::map< DetElement, Container > DetectorConditions
typedef std::set< ConditionKey > ConditionKeys
typedef ConditionDependency Dependency
typedef ConditionsDependencyCollection Dependencies
Public Types inherited from DD4hep::Handle< ConditionsManagerObject >
typedef ConditionsManagerObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
ConditionsManager (LCDD &lcdd)
Initializing constructor.
ConditionsManager ()=default
Default constructor.
ConditionsManager (Object *p)
Constructor to be used with valid pointer to object.
ConditionsManager (const ConditionsManager &c)
Constructor to assing handle of the same type.
template<typename Q >
ConditionsManager (const Handle< Q > &e)
Constructor to be used assigning from different type.
~ConditionsManager ()=default
Default destructor.
ConditionsManager & operator= (const ConditionsManager &c)=default
Assignment operator.
ConditionsManager & initialize ()
Initialize the object after having set the properties.
Property & operator[] (const std::string &property_name) const
Access to properties.
PropertyManager & properties () const
Access to the property manager.
Handle< Loader > loader () const
Access the conditions loader.
const std::vector< const IOVType * > iovTypesUsed () const
Access the used/registered IOV types.
const IOVType * iovType (const std::string &iov_name) const
Access IOV by its name.
ConditionsIOVPool * iovPool (const IOVType &type) const
Access conditions multi IOV pool by iov type.
void fromString (const std::string &iov_str, IOV &iov)
Create IOV from string.
std::pair< bool, const IOVType * > registerIOVType (size_t iov_type, const std::string &iov_name)
Register new IOV type if it does not (yet) exist.
ConditionsPool * registerIOV (const IOVType &typ, IOV::Key key)
Register IOV with type and key.
bool registerUnlocked (ConditionsPool *pool, Condition cond)
Register new condition with the conditions store. Unlocked version, not multi-threaded.
void clean (const IOVType *typ, int max_age)
Clean conditions, which are above the age limit.
void clear ()
Full cleanup of all managed conditions.
long prepare (const IOV &required_validity, const ConditionKeys &keys, dd4hep_ptr< UserPool > &user_pool)
Prepare all updates for the given keys to the clients with the defined IOV.
long prepare (const IOV &required_validity, const ConditionKeys &keys, dd4hep_ptr< UserPool > &user_pool, const Dependencies &dependencies, bool verify_dependencies=true)
Prepare all updates for the given keys to the clients with the defined IOV.
long prepare (const IOV &required_validity, dd4hep_ptr< UserPool > &user_pool)
Prepare all updates to the clients with the defined IOV.
long prepare (const IOV &required_validity, dd4hep_ptr< UserPool > &user_pool, const Dependencies &dependencies, bool verify_dependencies=true)
Prepare all updates to the clients with the defined IOV.
template<>
ConditionsManager from (LCDD &host)
Access specialization.
Public Member Functions inherited from DD4hep::Handle< ConditionsManagerObject >
Handle ()
Defaulot constructor.
Handle (ConditionsManagerObject *e)
Initializing constructor from pointer.
Handle (const Handle< ConditionsManagerObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< ConditionsManagerObject > & operator= (const Handle< ConditionsManagerObject > &e)=default
Assignment operator.
bool operator== (const Handle< ConditionsManagerObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< ConditionsManagerObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< ConditionsManagerObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< ConditionsManagerObject > & clear ()
Release the object held by the handle.
ConditionsManagerObject * operator-> () const
Access the held object using the -> operator.
operator ConditionsManagerObject & () const
Automatic type conversion to an object references.
ConditionsManagerObject & operator* () const
Access the held object using the * operator.
ConditionsManagerObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
ConditionsManagerObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Static Public Member Functions
template<typename T >
static ConditionsManager from (T &host)
Static accessor if installed as an extension.
Static Public Member Functions inherited from DD4hep::Handle< ConditionsManagerObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Additional Inherited Members
Public Attributes inherited from DD4hep::Handle< ConditionsManagerObject >
ConditionsManagerObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Manager class for condition handles.
Author
M.Frank
Version
1.0
Definition at line 46 of file ConditionsManager.h.
Member Typedef Documentation
ConditionKeys
typedef std::set<ConditionKey> DD4hep::Conditions::ConditionsManager::ConditionKeys
Definition at line 55 of file ConditionsManager.h.
Dependencies
typedef ConditionsDependencyCollection DD4hep::Conditions::ConditionsManager::Dependencies
Definition at line 57 of file ConditionsManager.h.
Dependency
typedef ConditionDependency DD4hep::Conditions::ConditionsManager::Dependency
Definition at line 56 of file ConditionsManager.h.
DetectorConditions
typedef std::map<DetElement,Container> DD4hep::Conditions::ConditionsManager::DetectorConditions
Definition at line 54 of file ConditionsManager.h.
IOVTypes
typedef std::vector<IOVType> DD4hep::Conditions::ConditionsManager::IOVTypes
Definition at line 52 of file ConditionsManager.h.
Loader
typedef ConditionsDataLoader DD4hep::Conditions::ConditionsManager::Loader
Definition at line 51 of file ConditionsManager.h.
Object
typedef ConditionsManagerObject DD4hep::Conditions::ConditionsManager::Object
Standard object type.
Definition at line 50 of file ConditionsManager.h.
TypeConditions
typedef std::map<IOVType*,Container> DD4hep::Conditions::ConditionsManager::TypeConditions
Definition at line 53 of file ConditionsManager.h.
Constructor & Destructor Documentation
ConditionsManager() [1/5]
ConditionsManager::ConditionsManager (LCDD & lcdd)
Initializing constructor.
Default constructor.
Definition at line 42 of file ConditionsManager.cpp.
ConditionsManager() [2/5]
DD4hep::Conditions::ConditionsManager::ConditionsManager () default
Default constructor.
ConditionsManager() [3/5]
DD4hep::Conditions::ConditionsManager::ConditionsManager (Object * p) inline
Constructor to be used with valid pointer to object.
Definition at line 78 of file ConditionsManager.h.
ConditionsManager() [4/5]
DD4hep::Conditions::ConditionsManager::ConditionsManager (const ConditionsManager & c) inline
Constructor to assing handle of the same type.
Definition at line 81 of file ConditionsManager.h.
ConditionsManager() [5/5]
template<typename Q > DD4hep::Conditions::ConditionsManager::ConditionsManager (const Handle< Q > & e) inline
Constructor to be used assigning from different type.
Definition at line 84 of file ConditionsManager.h.
References clean(), clear(), fromString(), initialize(), iovPool(), iovType(), iovTypesUsed(), loader(), operator=(), operator[](), prepare(), properties(), registerIOV(), registerIOVType(), registerUnlocked(), and ~ConditionsManager().
~ConditionsManager()
DD4hep::Conditions::ConditionsManager::~ConditionsManager () default
Default destructor.
Referenced by ConditionsManager().
Member Function Documentation
clean()
void ConditionsManager::clean (const IOVType * typ, int max_age)
Clean conditions, which are above the age limit.
Definition at line 108 of file ConditionsManager.cpp.
Referenced by ConditionsManager().
clear()
void ConditionsManager::clear ()
Full cleanup of all managed conditions.
Definition at line 113 of file ConditionsManager.cpp.
References DD4hep::Conditions::ConditionsPool::clear().
Referenced by ConditionsManager().
from() [1/2]
template<> ConditionsManager DD4hep::Conditions::ConditionsManager::from (LCDD & host)
Access specialization.
Definition at line 32 of file ConditionsManager.cpp.
References DD4hep::except(), and DD4hep::ObjectExtensions::extension().
from() [2/2]
template<typename T > static ConditionsManager DD4hep::Conditions::ConditionsManager::from (T & host) static
Static accessor if installed as an extension.
Note:
There may very well be several instances of a conditions manager. Do not think this is a sort of 'static constructor'. This would be a big mistake!.
Referenced by DD4hep::Conditions::Test::TestEnv::TestEnv().
fromString()
void ConditionsManager::fromString (const std::string & iov_str, IOV & iov)
Create IOV from string.
Definition at line 98 of file ConditionsManager.cpp.
Referenced by DD4hep::Conditions::Test::TestEnv::add_xml_data_source(), and ConditionsManager().
initialize()
ConditionsManager & ConditionsManager::initialize ()
Initialize the object after having set the properties.
Definition at line 46 of file ConditionsManager.cpp.
References initialize().
Referenced by ConditionsManager(), initialize(), and DD4hep::Conditions::Test::TestEnv::TestEnv().
iovPool()
ConditionsIOVPool * ConditionsManager::iovPool (const IOVType & type) const
Access conditions multi IOV pool by iov type.
Definition at line 78 of file ConditionsManager.cpp.
References DD4hep::IOVType::type.
Referenced by DD4hep::Conditions::Operators::collectAllConditions(), ConditionsManager(), DD4hep::Conditions::ConditionsTextRepository::save(), and DD4hep::Conditions::ConditionsRepository::save().
iovType()
const IOVType * ConditionsManager::iovType (const std::string & iov_name) const
Access IOV by its name.
Definition at line 73 of file ConditionsManager.cpp.
Referenced by ConditionsManager(), and DD4hep::Conditions::Test::TestEnv::dump_conditions_pools().
iovTypesUsed()
const vector< const IOVType * > ConditionsManager::iovTypesUsed () const
Access the used/registered IOV types.
Definition at line 83 of file ConditionsManager.cpp.
References DD4hep::Conditions::ConditionsManagerObject::iovTypes().
Referenced by DD4hep::Conditions::Operators::collectAllConditions(), ConditionsManager(), DD4hep::Conditions::ConditionsTextRepository::save(), and DD4hep::Conditions::ConditionsRepository::save().
loader()
Handle< ConditionsManager::Loader > ConditionsManager::loader () const
Access the conditions loader.
Definition at line 62 of file ConditionsManager.cpp.
Referenced by ConditionsManager(), and DD4hep::Conditions::Test::TestEnv::TestEnv().
operator=()
ConditionsManager& DD4hep::Conditions::ConditionsManager::operator= (const ConditionsManager & c) default
Assignment operator.
Referenced by ConditionsManager().
operator[]()
Property & ConditionsManager::operator[] (const std::string & property_name) const
Access to properties.
Definition at line 57 of file ConditionsManager.cpp.
Referenced by ConditionsManager().
prepare() [1/4]
long ConditionsManager::prepare (const IOV & required_validity, const ConditionKeys & keys, dd4hep_ptr< UserPool > & user_pool)
Prepare all updates for the given keys to the clients with the defined IOV.
Definition at line 118 of file ConditionsManager.cpp.
Referenced by ConditionsManager().
prepare() [2/4]
long ConditionsManager::prepare (const IOV & required_validity, const ConditionKeys & keys, dd4hep_ptr< UserPool > & user_pool, const Dependencies & dependencies, bool verify_dependencies = true)
Prepare all updates for the given keys to the clients with the defined IOV.
Definition at line 126 of file ConditionsManager.cpp.
prepare() [3/4]
long ConditionsManager::prepare (const IOV & required_validity, dd4hep_ptr< UserPool > & user_pool)
Prepare all updates to the clients with the defined IOV.
Prepare all updates to the clients with the defined new IOV. Changes are not yet applied.
Definition at line 135 of file ConditionsManager.cpp.
prepare() [4/4]
long ConditionsManager::prepare (const IOV & required_validity, dd4hep_ptr< UserPool > & user_pool, const Dependencies & dependencies, bool verify_dependencies = true)
Prepare all updates to the clients with the defined IOV.
Definition at line 140 of file ConditionsManager.cpp.
properties()
PropertyManager & ConditionsManager::properties () const
Access to the property manager.
Definition at line 52 of file ConditionsManager.cpp.
Referenced by ConditionsManager().
registerIOV()
ConditionsPool * ConditionsManager::registerIOV (const IOVType & typ, IOV::Key key)
Register IOV with type and key.
Definition at line 93 of file ConditionsManager.cpp.
Referenced by ConditionsManager().
registerIOVType()
pair< bool, const IOVType * > ConditionsManager::registerIOVType (size_t iov_type, const std::string & iov_name)
Register new IOV type if it does not (yet) exist.
Returns (false,pointer) if IOV existed and (true,pointer) if new IOV was registered to the manager.
Definition at line 68 of file ConditionsManager.cpp.
Referenced by ConditionsManager(), and DD4hep::Conditions::Test::TestEnv::TestEnv().
registerUnlocked()
bool ConditionsManager::registerUnlocked (ConditionsPool * pool, Condition cond)
Register new condition with the conditions store. Unlocked version, not multi-threaded.
Definition at line 103 of file ConditionsManager.cpp.
Referenced by ConditionsManager().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsManager.cpp