DD4hep: DD4hep: DD4hep::Geometry::MultiSegmentation Class Reference
DD4hep::Geometry::MultiSegmentation Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid XZ segmentation.
#include <MultiSegmentation.h>
Public Types
typedef
MultiSegmentationHandle::Implementation Object
typedef
DDSegmentation::MultiSegmentation::Segmentations Segmentations
Public Member Functions
MultiSegmentation ()
Default constructor.
MultiSegmentation (const MultiSegmentation &e)
Copy constructor.
MultiSegmentation (const Segmentation &e)
Copy Constructor from segmentation base object.
MultiSegmentation (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
MultiSegmentation (const Handle< Q > &e)
Copy constructor from other polymorph/equivalent handle.
MultiSegmentation & operator= (const MultiSegmentation &seg)
Assignment operator.
bool operator== (const MultiSegmentation &seg) const
Equality operator.
const std::string & discriminatorName () const
access the field name used to discriminate sub-segmentations
BitFieldValue * discriminator () const
Discriminating bitfield entry.
const Segmentations & subSegmentations () const
The underlying sub-segementations.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
const std::string & fieldNameY () const
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid XZ segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 58 of file MultiSegmentation.h.
Member Typedef Documentation
typedef MultiSegmentationHandle::Implementation DD4hep::Geometry::MultiSegmentation::Object
Definition at line 60 of file MultiSegmentation.h.
typedef DDSegmentation::MultiSegmentation::Segmentations DD4hep::Geometry::MultiSegmentation::Segmentations
Definition at line 61 of file MultiSegmentation.h.
Constructor & Destructor Documentation
DD4hep::Geometry::MultiSegmentation::MultiSegmentation ()
Default constructor.
DD4hep::Geometry::MultiSegmentation::MultiSegmentation (const MultiSegmentation & e)
Copy constructor.
DD4hep::Geometry::MultiSegmentation::MultiSegmentation (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 69 of file MultiSegmentation.h.
DD4hep::Geometry::MultiSegmentation::MultiSegmentation (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 71 of file MultiSegmentation.h.
template<typename Q > DD4hep::Geometry::MultiSegmentation::MultiSegmentation (const Handle< Q > & e) [inline]
Copy constructor from other polymorph/equivalent handle.
Definition at line 73 of file MultiSegmentation.h.
Member Function Documentation
vector< double > MultiSegmentation::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in x
size in z
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in x
size in y
Definition at line 62 of file MultiSegmentation.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID MultiSegmentation::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 46 of file MultiSegmentation.cpp.
References DD4hep::Handle< T >::access().
BitFieldValue * MultiSegmentation::discriminator () const
Discriminating bitfield entry.
Definition at line 30 of file MultiSegmentation.cpp.
References DD4hep::Handle< T >::access().
const std::string & MultiSegmentation::discriminatorName () const
access the field name used to discriminate sub-segmentations
Definition at line 25 of file MultiSegmentation.cpp.
References DD4hep::Handle< T >::access().
const std::string& DD4hep::Geometry::MultiSegmentation::fieldNameY () const
MultiSegmentation& DD4hep::Geometry::MultiSegmentation::operator= (const MultiSegmentation & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::MultiSegmentation::operator== (const MultiSegmentation & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 77 of file MultiSegmentation.h.
References DD4hep::Handle< T >::m_element.
Position MultiSegmentation::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 41 of file MultiSegmentation.cpp.
References DD4hep::Handle< T >::access().
const MultiSegmentation::Segmentations & MultiSegmentation::subSegmentations () const
The underlying sub-segementations.
Definition at line 36 of file MultiSegmentation.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/MultiSegmentation.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/MultiSegmentation.cpp