DD4hep: DD4hep::Geometry::SimpleGDMLWriter Class Reference
DD4hep::Geometry::SimpleGDMLWriter Class Reference
DD4hep::Geometry components, classes and objects
Simple GDML creator from TGeo geometries in memory.
#include <SimpleGDMLWriter.h>
Public Member Functions
SimpleGDMLWriter (std::ostream &os)
virtual ~SimpleGDMLWriter ()
Standard destructor.
void create (DetElement top)
Main entry point: create required object(s)
virtual void * handleVolume (const std::string &name, const TGeoVolume *volume) const
Dump logical volume in GDML format to output stream.
virtual void * handleTransformation (const std::string &name, const TGeoMatrix *matrix) const
Dump single volume transformation in GDML format to output stream.
virtual void * handleSolid (const std::string &name, const TGeoShape *volume) const
Dump solid in GDML format to output stream.
virtual void handleDefines (const DefinitionSet &defs) const
Dump all constants in GDML format to output stream.
void handleVisualisation (const VisRefs &vis) const
Dump all visualisation specs in LCDD format to output stream.
virtual void handleSolids (const SolidSet &solids) const
Dump all solids in GDML format to output stream.
virtual void handleTransformations (const TransformSet &trafos) const
Dump Transformations in GDML format to output stream.
virtual void handleStructure (const VolumeVector &volset) const
Dump structure information in GDML format to output stream.
Public Member Functions inherited from DD4hep::Geometry::GeoHandler
GeoHandler ()
Default constructor.
GeoHandler (Data *ptr)
Initializing constructor.
virtual ~GeoHandler ()
Default destructor.
bool setPropagateRegions (bool value)
Propagate regions. Returns the previous value.
GeoHandler & collect (DetElement top)
Collect geometry information from traversal.
GeoHandler & collect (DetElement top, GeometryInfo &info)
Collect geometry information from traversal with aggregated information.
Data * release ()
Access to collected node list.
Public Attributes
std::ostream & m_output
Reference to output stream.
Additional Inherited Members
Public Types inherited from DD4hep::Geometry::GeoHandlerTypes
typedef std::set< Volume > VolumeSet
typedef std::vector< Volume > VolumeVector
typedef std::set< const TGeoVolume * > ConstVolumeSet
typedef std::vector< std::pair< std::string, TGeoMatrix * > > TransformSet
typedef std::set< TGeoShape * > SolidSet
typedef std::set< Material > MaterialSet
typedef std::map< SensitiveDetector, ConstVolumeSet > SensitiveVolumes
typedef std::map< Region, ConstVolumeSet > RegionVolumes
typedef std::map< LimitSet, ConstVolumeSet > LimitVolumes
typedef std::map< int, std::set< const TGeoNode * > > Data
typedef std::set< VisAttr > VisRefs
typedef std::set< SensitiveDetector > SensitiveDetectorSet
typedef std::set< Region > RegionSet
typedef std::set< LimitSet > LimitSetSet
typedef std::set< Ref_t > Fields
typedef std::set< TNamed * > ObjectSet
typedef LCDD::HandleMap DefinitionSet
Protected Member Functions inherited from DD4hep::Geometry::GeoHandler
GeoHandler & i_collect (const TGeoNode *node, int level, Region rg, LimitSet ls)
Internal helper to collect geometry information from traversal.
Protected Attributes inherited from DD4hep::Geometry::GeoHandler
bool m_propagateRegions
Data * m_data
Detailed Description
Simple GDML creator from TGeo geometries in memory.
Author
M.Frank
Version
1.0
Definition at line 43 of file SimpleGDMLWriter.h.
Constructor & Destructor Documentation
SimpleGDMLWriter()
DD4hep::Geometry::SimpleGDMLWriter::SimpleGDMLWriter (std::ostream & os) inline
Definition at line 48 of file SimpleGDMLWriter.h.
~SimpleGDMLWriter()
virtual DD4hep::Geometry::SimpleGDMLWriter::~SimpleGDMLWriter () inline virtual
Standard destructor.
Definition at line 52 of file SimpleGDMLWriter.h.
References create(), handleDefines(), handleSolid(), handleSolids(), handleStructure(), handleTransformation(), handleTransformations(), handleVisualisation(), and handleVolume().
Member Function Documentation
create()
void SimpleGDMLWriter::create (DetElement top)
Main entry point: create required object(s)
Definition at line 292 of file SimpleGDMLWriter.cpp.
References DD4hep::Geometry::LCDD::getInstance(), DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::solids, DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::trafos, DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::vis, and DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::volumes.
Referenced by ~SimpleGDMLWriter().
handleDefines()
void SimpleGDMLWriter::handleDefines (const DefinitionSet & defs) const virtual
Dump all constants in GDML format to output stream.
Definition at line 241 of file SimpleGDMLWriter.cpp.
Referenced by ~SimpleGDMLWriter().
handleSolid()
void * SimpleGDMLWriter::handleSolid (const std::string & name, const TGeoShape * volume) const virtual
Dump solid in GDML format to output stream.
Definition at line 109 of file SimpleGDMLWriter.cpp.
References s.
Referenced by ~SimpleGDMLWriter().
handleSolids()
void SimpleGDMLWriter::handleSolids (const SolidSet & solids) const virtual
Dump all solids in GDML format to output stream.
Definition at line 233 of file SimpleGDMLWriter.cpp.
Referenced by ~SimpleGDMLWriter().
handleStructure()
void SimpleGDMLWriter::handleStructure (const VolumeVector & volset) const virtual
Dump structure information in GDML format to output stream.
Definition at line 194 of file SimpleGDMLWriter.cpp.
Referenced by ~SimpleGDMLWriter().
handleTransformation()
void * SimpleGDMLWriter::handleTransformation (const std::string & name, const TGeoMatrix * matrix) const virtual
Dump single volume transformation in GDML format to output stream.
Definition at line 202 of file SimpleGDMLWriter.cpp.
Referenced by ~SimpleGDMLWriter().
handleTransformations()
void SimpleGDMLWriter::handleTransformations (const TransformSet & trafos) const virtual
Dump Transformations in GDML format to output stream.
Definition at line 225 of file SimpleGDMLWriter.cpp.
Referenced by ~SimpleGDMLWriter().
handleVisualisation()
void SimpleGDMLWriter::handleVisualisation (const VisRefs & vis) const
Dump all visualisation specs in LCDD format to output stream.
Definition at line 250 of file SimpleGDMLWriter.cpp.
References DD4hep::Geometry::VisAttr::color(), DD4hep::Geometry::VisAttr::DASHED, DD4hep::Geometry::VisAttr::drawingStyle(), dd4hep::g, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::VisAttr::lineStyle(), DD4hep::Handle< T >::name(), DD4hep::Geometry::VisAttr::showDaughters(), DD4hep::Geometry::VisAttr::SOLID, v, DD4hep::Geometry::VisAttr::visible(), and DD4hep::Geometry::VisAttr::WIREFRAME.
Referenced by ~SimpleGDMLWriter().
handleVolume()
void * SimpleGDMLWriter::handleVolume (const std::string & name, const TGeoVolume * volume) const virtual
Dump logical volume in GDML format to output stream.
Definition at line 71 of file SimpleGDMLWriter.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), v, and DD4hep::Geometry::Volume::visAttributes().
Referenced by ~SimpleGDMLWriter().
Member Data Documentation
m_output
std::ostream& DD4hep::Geometry::SimpleGDMLWriter::m_output
Reference to output stream.
Definition at line 46 of file SimpleGDMLWriter.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/SimpleGDMLWriter.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/SimpleGDMLWriter.cpp