DD4hep: DD4hep: DD4hep::Geometry::PolarGridRPhi Class Reference
DD4hep::Geometry::PolarGridRPhi Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid XZ segmentation.
#include <PolarGridRPhi.h>
Public Types
typedef
PolarGridRPhiHandle::Implementation Object
Defintiion of the basic handled object.
Public Member Functions
PolarGridRPhi ()
Default constructor.
PolarGridRPhi (const PolarGridRPhi &e)
Copy constructor.
PolarGridRPhi (const Segmentation &e)
Copy Constructor from segmentation base object.
PolarGridRPhi (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
PolarGridRPhi (const Handle< Q > &e)
Copy constructor from other polymorph/equivalent handle.
PolarGridRPhi & operator= (const PolarGridRPhi &seg)
Assignment operator.
bool operator== (const PolarGridRPhi &seg) const
Equality operator.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
double gridSizeR () const
access the grid size in R
double gridSizePhi () const
access the grid size in Phi
void setGridSizeR (double cellSize) const
set the grid size in R
void setGridSizePhi (double cellSize) const
set the grid size in Phi
double offsetR () const
access the coordinate offset in R
double offsetPhi () const
access the coordinate offset in Phi
void setOffsetR (double offset) const
set the coordinate offset in R
void setOffsetPhi (double offset) const
set the coordinate offset in Phi
const std::string & fieldNameR () const
access the field name used for R
const std::string & fieldNamePhi () const
access the field name used for Phi
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid XZ segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 57 of file PolarGridRPhi.h.
Member Typedef Documentation
typedef PolarGridRPhiHandle::Implementation DD4hep::Geometry::PolarGridRPhi::Object
Defintiion of the basic handled object.
Definition at line 60 of file PolarGridRPhi.h.
Constructor & Destructor Documentation
DD4hep::Geometry::PolarGridRPhi::PolarGridRPhi ()
Default constructor.
DD4hep::Geometry::PolarGridRPhi::PolarGridRPhi (const PolarGridRPhi & e)
Copy constructor.
DD4hep::Geometry::PolarGridRPhi::PolarGridRPhi (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 68 of file PolarGridRPhi.h.
DD4hep::Geometry::PolarGridRPhi::PolarGridRPhi (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 70 of file PolarGridRPhi.h.
template<typename Q > DD4hep::Geometry::PolarGridRPhi::PolarGridRPhi (const Handle< Q > & e) [inline]
Copy constructor from other polymorph/equivalent handle.
Definition at line 72 of file PolarGridRPhi.h.
Member Function Documentation
vector< double > PolarGridRPhi::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in x
size in z
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in x
size in z
Definition at line 96 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID PolarGridRPhi::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 30 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
const string & PolarGridRPhi::fieldNamePhi () const
access the field name used for Phi
Definition at line 83 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
const string & PolarGridRPhi::fieldNameR () const
access the field name used for R
Definition at line 78 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
double PolarGridRPhi::gridSizePhi () const
access the grid size in Phi
Definition at line 43 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
double PolarGridRPhi::gridSizeR () const
access the grid size in R
Definition at line 38 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
double PolarGridRPhi::offsetPhi () const
access the coordinate offset in Phi
Definition at line 53 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
double PolarGridRPhi::offsetR () const
access the coordinate offset in R
Definition at line 48 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
PolarGridRPhi& DD4hep::Geometry::PolarGridRPhi::operator= (const PolarGridRPhi & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::PolarGridRPhi::operator== (const PolarGridRPhi & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 76 of file PolarGridRPhi.h.
References DD4hep::Handle< T >::m_element.
Position PolarGridRPhi::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 25 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi::setGridSizePhi (double cellSize) const
set the grid size in Phi
Definition at line 73 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi::setGridSizeR (double cellSize) const
set the grid size in R
Definition at line 68 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi::setOffsetPhi (double offset) const
set the coordinate offset in Phi
Definition at line 63 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi::setOffsetR (double offset) const
set the coordinate offset in R
Definition at line 58 of file PolarGridRPhi.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/PolarGridRPhi.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/PolarGridRPhi.cpp