DD4hep: DD4hep: DD4hep::Geometry::Trapezoid Class Reference
DD4hep::Geometry::Trapezoid Class Reference
[DD4hep::Geometry components, classes and objects]
Class describing a Trapezoid shape.
#include <Shapes.h>
Public Member Functions
Trapezoid ()
Default constructor.
Trapezoid (const Trapezoid &e)
Constructor to be used when passing an already created object.
template<typename Q >
Trapezoid (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
Trapezoid (const Handle< Q > &e)
Constructor to be used when passing an already created object.
Trapezoid (double x1, double x2, double y1, double y2, double z)
Constructor to create a new anonymous object with attribute initialization.
template<typename X1 , typename X2 , typename Y1 , typename Y2 , typename Z >
Trapezoid (X1 x1, X2 x2, Y1 y1, Y2 y2, Z z)
Constructor to create a new anonymous object with attribute initialization.
Trapezoid & operator= (const Trapezoid &copy)
Assignment operator.
Trapezoid & setDimensions (double x1, double x2, double y1, double y2, double z)
Set the Trapezoid dimensions.
Private Member Functions
void make (double x1, double x2, double y1, double y2, double z)
Internal helper method to support object construction.
Detailed Description
Class describing a Trapezoid shape.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoTrd2.html
Author:
M.Frank
Version:
1.0
Definition at line 435 of file Shapes.h.
Constructor & Destructor Documentation
DD4hep::Geometry::Trapezoid::Trapezoid ()
Default constructor.
DD4hep::Geometry::Trapezoid::Trapezoid (const Trapezoid & e)
Constructor to be used when passing an already created object.
template<typename Q > DD4hep::Geometry::Trapezoid::Trapezoid (const Q * p) [inline]
Constructor to be used with an existing object.
Definition at line 446 of file Shapes.h.
template<typename Q > DD4hep::Geometry::Trapezoid::Trapezoid (const Handle< Q > & e) [inline]
Constructor to be used when passing an already created object.
Definition at line 448 of file Shapes.h.
Trapezoid::Trapezoid (double x1, double x2, double y1, double y2, double z)
Constructor to create a new anonymous object with attribute initialization.
Definition at line 312 of file Shapes.cpp.
References make().
template<typename X1 , typename X2 , typename Y1 , typename Y2 , typename Z > DD4hep::Geometry::Trapezoid::Trapezoid (X1 x1, X2 x2, Y1 y1, Y2 y2, Z z) [inline]
Constructor to create a new anonymous object with attribute initialization.
Definition at line 453 of file Shapes.h.
References DD4hep::_toDouble(), and make().
Member Function Documentation
void Trapezoid::make (double x1, double x2, double y1, double y2, double z) [private]
Internal helper method to support object construction.
Constructor to be used when creating a new object with attribute initialization.
Definition at line 317 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoTrd2 >::_assign().
Referenced by Trapezoid().
Trapezoid& DD4hep::Geometry::Trapezoid::operator= (const Trapezoid & copy)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
Trapezoid & Trapezoid::setDimensions (double x1, double x2, double y1, double y2, double z)
Set the Trapezoid dimensions.
Definition at line 322 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoTrd2 >::_setDimensions().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp