DD4hep: DD4hep::Alignments::AlignmentStack Class Reference
DD4hep::Alignments::AlignmentStack Class Reference
DDAlign: DD4hep Detector geometry alignment components.
Alignment Stack object definition.
#include <AlignmentStack.h>
Classes
struct StackEntry
Stack entry definition.
Public Types
enum {
OVERLAP_DEFINED = 1<<20, MATRIX_DEFINED = 1<<21, CHECKOVL_DEFINED = 1<<22, CHECKOVL_VALUE = 1<<23,
RESET_VALUE = 1<<24, RESET_CHILDREN = 1<<25, ____LLLAST = 1<<31
}
typedef std::map< std::string, StackEntry * > Stack
Public Member Functions
virtual ~AlignmentStack ()
Default destructor. Careful with this one:
bool insert (const std::string &full_path, dd4hep_ptr< StackEntry > &new_entry)
Add a new entry to the cache. The key is the placement path.
bool insert (dd4hep_ptr< StackEntry > &new_entry)
Add a new entry to the cache. The key is the placement path. The placement path must be set in the entry.
void release ()
Clear data content and remove the slignment stack.
size_t size () const
Access size of the alignment stack.
bool add (dd4hep_ptr< StackEntry > &new_entry)
Add a new entry to the cache. The key is the placement path.
dd4hep_ptr< StackEntry > pop ()
Retrieve an alignment entry of the current stack.
std::vector< const StackEntry * > entries () const
Get all path entries to be aligned. Note: transient!
Static Public Member Functions
static AlignmentStack & get ()
Static client accessor.
static void create ()
Create an alignment stack instance. The creation of a second instance will be refused.
static bool exists ()
Check existence of alignment stack.
Public Attributes
enum DD4hep::Alignments::AlignmentStack:: { ... } Flags
Protected Member Functions
AlignmentStack ()
Default constructor.
Protected Attributes
Stack m_stack
The subdetector specific map of alignments caches.
Detailed Description
Alignment Stack object definition.
Author
M.Frank
Version
1.0
Definition at line 35 of file AlignmentStack.h.
Member Typedef Documentation
Stack
typedef std::map<std::string, StackEntry*> DD4hep::Alignments::AlignmentStack::Stack
Definition at line 95 of file AlignmentStack.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OVERLAP_DEFINED
MATRIX_DEFINED
CHECKOVL_DEFINED
CHECKOVL_VALUE
RESET_VALUE
RESET_CHILDREN
____LLLAST
Definition at line 37 of file AlignmentStack.h.
Constructor & Destructor Documentation
AlignmentStack()
AlignmentStack::AlignmentStack () protected
Default constructor.
Definition at line 96 of file AlignmentStack.cpp.
References DD4hep::InstanceCount::increment().
Referenced by create().
~AlignmentStack()
AlignmentStack::~AlignmentStack () virtual
Default destructor. Careful with this one:
Default destructor.
Definition at line 102 of file AlignmentStack.cpp.
References DD4hep::InstanceCount::decrement(), DD4hep::destroyObjects(), and m_stack.
Member Function Documentation
add()
bool AlignmentStack::add (dd4hep_ptr< StackEntry > & new_entry)
Add a new entry to the cache. The key is the placement path.
Definition at line 150 of file AlignmentStack.cpp.
References DD4hep::INFO, m_stack, and DD4hep::printout().
Referenced by insert(), and size().
create()
void AlignmentStack::create () static
Create an alignment stack instance. The creation of a second instance will be refused.
Definition at line 114 of file AlignmentStack.cpp.
References _stack(), and AlignmentStack().
entries()
vector< const AlignmentStack::StackEntry * > AlignmentStack::entries () const
Get all path entries to be aligned. Note: transient!
Get all pathes to be aligned.
Definition at line 183 of file AlignmentStack.cpp.
References m_stack.
Referenced by size().
exists()
bool AlignmentStack::exists () static
Check existence of alignment stack.
Definition at line 122 of file AlignmentStack.cpp.
References _stack().
get()
AlignmentStack & AlignmentStack::get () static
Static client accessor.
Definition at line 108 of file AlignmentStack.cpp.
References _stack().
insert() [1/2]
bool AlignmentStack::insert (const std::string & full_path, dd4hep_ptr< StackEntry > & new_entry)
Add a new entry to the cache. The key is the placement path.
Definition at line 136 of file AlignmentStack.cpp.
References add().
insert() [2/2]
bool AlignmentStack::insert (dd4hep_ptr< StackEntry > & new_entry)
Add a new entry to the cache. The key is the placement path. The placement path must be set in the entry.
Add a new entry to the cache. The key is the placement path.
Definition at line 145 of file AlignmentStack.cpp.
References add().
pop()
dd4hep_ptr< AlignmentStack::StackEntry > AlignmentStack::pop ()
Retrieve an alignment entry of the current stack.
Definition at line 171 of file AlignmentStack.cpp.
References e, and m_stack.
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply(), and size().
release()
void AlignmentStack::release ()
Clear data content and remove the slignment stack.
Definition at line 127 of file AlignmentStack.cpp.
References _stack().
size()
size_t DD4hep::Alignments::AlignmentStack::size () const inline
Access size of the alignment stack.
Definition at line 121 of file AlignmentStack.h.
References add(), entries(), and pop().
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply().
Member Data Documentation
Flags
enum { ... } DD4hep::Alignments::AlignmentStack::Flags
m_stack
Stack DD4hep::Alignments::AlignmentStack::m_stack protected
The subdetector specific map of alignments caches.
Definition at line 99 of file AlignmentStack.h.
Referenced by add(), entries(), pop(), and ~AlignmentStack().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/AlignmentStack.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentStack.cpp