DD4hep: DD4hep::Simulation::Geant4DataDump Class Reference
DD4hep::Simulation::Geant4DataDump Class Reference
DD4hep::Simulation components, classes and objects
Class to dump the records of the intrinsic Geant4 event model.
#include <Geant4DataDump.h>
Public Types
typedef Geant4Particle Particle
typedef std::vector< Particle * > Particles
typedef SimpleTracker::Hit TrackerHit
typedef std::vector< SimpleTracker::Hit * > TrackerHits
typedef SimpleCalorimeter::Hit CalorimeterHit
typedef std::vector< SimpleCalorimeter::Hit * > CalorimeterHits
Public Member Functions
Geant4DataDump (const std::string &tag)
Default constructor.
virtual ~Geant4DataDump ()
Standard destructor.
void print (PrintLevel level, Geant4ParticleHandle p) const
Print a single particle to the output logging using the specified print level.
void print (PrintLevel level, const std::string &container, const Particles *parts)
Print the particle container to the output logging using the specified print level.
void print (PrintLevel level, const TrackerHit *h)
Print a single tracker hit to the output logging using the specified print level.
void print (PrintLevel level, const std::string &container, const TrackerHits *hits)
Print the tracker hits container to the output logging using the specified print level.
void print (PrintLevel level, const CalorimeterHit *h)
Print a calorimeter tracker hit to the output logging using the specified print level.
void print (PrintLevel level, const std::string &container, const CalorimeterHits *hits)
Print the calorimeter hits container to the output logging using the specified print level.
Protected Attributes
std::string m_tag
Tag variable.
Detailed Description
Class to dump the records of the intrinsic Geant4 event model.
Author
M.Frank
Version
1.0
Definition at line 38 of file Geant4DataDump.h.
Member Typedef Documentation
CalorimeterHit
typedef SimpleCalorimeter::Hit DD4hep::Simulation::Geant4DataDump::CalorimeterHit
Definition at line 46 of file Geant4DataDump.h.
CalorimeterHits
typedef std::vector<SimpleCalorimeter::Hit*> DD4hep::Simulation::Geant4DataDump::CalorimeterHits
Definition at line 47 of file Geant4DataDump.h.
Particle
typedef Geant4Particle DD4hep::Simulation::Geant4DataDump::Particle
Definition at line 40 of file Geant4DataDump.h.
Particles
typedef std::vector<Particle*> DD4hep::Simulation::Geant4DataDump::Particles
Definition at line 41 of file Geant4DataDump.h.
TrackerHit
typedef SimpleTracker::Hit DD4hep::Simulation::Geant4DataDump::TrackerHit
Definition at line 43 of file Geant4DataDump.h.
TrackerHits
typedef std::vector<SimpleTracker::Hit*> DD4hep::Simulation::Geant4DataDump::TrackerHits
Definition at line 44 of file Geant4DataDump.h.
Constructor & Destructor Documentation
Geant4DataDump()
Geant4DataDump::Geant4DataDump (const std::string & tag)
Default constructor.
Definition at line 26 of file Geant4DataDump.cpp.
~Geant4DataDump()
Geant4DataDump::~Geant4DataDump () virtual
Standard destructor.
Definition at line 30 of file Geant4DataDump.cpp.
Member Function Documentation
print() [1/6]
void Geant4DataDump::print (PrintLevel level, Geant4ParticleHandle p) const
Print a single particle to the output logging using the specified print level.
Definition at line 34 of file Geant4DataDump.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4ParticleHandle::energy(), DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_CREATED_CALORIMETER_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, DD4hep::Simulation::G4PARTICLE_HAS_SECONDARIES, DD4hep::Simulation::G4PARTICLE_KEEP_PARENT, DD4hep::Simulation::G4PARTICLE_KEEP_PROCESS, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::Geant4Particle::id, DD4hep::ReferenceBitMask< T >::isSet(), m_tag, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::printout(), DD4hep::Simulation::Geant4Particle::reason, and DD4hep::yes_no().
Referenced by dump_root(), and print().
print() [2/6]
void Geant4DataDump::print (PrintLevel level, const std::string & container, const Particles * parts)
Print the particle container to the output logging using the specified print level.
Definition at line 54 of file Geant4DataDump.cpp.
References m_tag, print(), and DD4hep::printout().
print() [3/6]
void Geant4DataDump::print (PrintLevel level, const TrackerHit * h)
Print a single tracker hit to the output logging using the specified print level.
Definition at line 66 of file Geant4DataDump.cpp.
References DD4hep::Simulation::Geant4HitData::cellID, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::deposit, DD4hep::Simulation::Geant4Tracker::Hit::energyDeposit, DD4hep::Simulation::Geant4Tracker::Hit::length, m_tag, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::pdgID, DD4hep::Simulation::Geant4Tracker::Hit::position, DD4hep::printout(), DD4hep::Simulation::Geant4HitData::MonteCarloContrib::time, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::trackID, and DD4hep::Simulation::Geant4Tracker::Hit::truth.
print() [4/6]
void Geant4DataDump::print (PrintLevel level, const std::string & container, const TrackerHits * hits)
Print the tracker hits container to the output logging using the specified print level.
Definition at line 73 of file Geant4DataDump.cpp.
References m_tag, print(), and DD4hep::printout().
print() [5/6]
void Geant4DataDump::print (PrintLevel level, const CalorimeterHit * h)
Print a calorimeter tracker hit to the output logging using the specified print level.
Definition at line 83 of file Geant4DataDump.cpp.
References DD4hep::Simulation::Geant4HitData::cellID, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::deposit, DD4hep::Simulation::Geant4Calorimeter::Hit::energyDeposit, m_tag, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::pdgID, DD4hep::Simulation::Geant4Calorimeter::Hit::position, DD4hep::printout(), DD4hep::Simulation::Geant4HitData::MonteCarloContrib::time, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::trackID, and DD4hep::Simulation::Geant4Calorimeter::Hit::truth.
print() [6/6]
void Geant4DataDump::print (PrintLevel level, const std::string & container, const CalorimeterHits * hits)
Print the calorimeter hits container to the output logging using the specified print level.
Definition at line 96 of file Geant4DataDump.cpp.
References m_tag, print(), and DD4hep::printout().
Member Data Documentation
m_tag
std::string DD4hep::Simulation::Geant4DataDump::m_tag protected
Tag variable.
Definition at line 51 of file Geant4DataDump.h.
Referenced by print().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4DataDump.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4DataDump.cpp