DD4hep: DD4hep: DD4hep::Geometry::CartesianGridXYZ Class Reference
DD4hep::Geometry::CartesianGridXYZ Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid XYZ segmentation.
#include <CartesianGridXYZ.h>
Public Types
typedef
CartesianGridXYZHandle::Implementation Object
Defintiion of the basic handled object.
Public Member Functions
CartesianGridXYZ ()
Default constructor.
CartesianGridXYZ (const CartesianGridXYZ &e)
Copy constructor.
CartesianGridXYZ (const Segmentation &e)
Copy Constructor from segmentation base object.
CartesianGridXYZ (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
CartesianGridXYZ (const Handle< Q > &e)
Copy constructor from other polymorph/equivalent handle.
CartesianGridXYZ & operator= (const CartesianGridXYZ &seg)
Assignment operator.
bool operator== (const CartesianGridXYZ &seg) const
Equality operator.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
double gridSizeX () const
access the grid size in X
double gridSizeY () const
access the grid size in Y
double gridSizeZ () const
access the grid size in Z
void setGridSizeX (double cellSize) const
set the grid size in X
void setGridSizeY (double cellSize) const
set the grid size in Y
void setGridSizeZ (double cellSize) const
set the grid size in Z
double offsetX () const
access the coordinate offset in X
double offsetY () const
access the coordinate offset in Y
double offsetZ () const
access the coordinate offset in Z
void setOffsetX (double offset) const
set the coordinate offset in X
void setOffsetY (double offset) const
set the coordinate offset in Y
void setOffsetZ (double offset) const
set the coordinate offset in Z
const std::string & fieldNameX () const
access the field name used for X
const std::string & fieldNameY () const
access the field name used for Y
const std::string & fieldNameZ () const
access the field name used for Z
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid XYZ segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 58 of file CartesianGridXYZ.h.
Member Typedef Documentation
typedef CartesianGridXYZHandle::Implementation DD4hep::Geometry::CartesianGridXYZ::Object
Defintiion of the basic handled object.
Definition at line 61 of file CartesianGridXYZ.h.
Constructor & Destructor Documentation
DD4hep::Geometry::CartesianGridXYZ::CartesianGridXYZ ()
Default constructor.
DD4hep::Geometry::CartesianGridXYZ::CartesianGridXYZ (const CartesianGridXYZ & e)
Copy constructor.
DD4hep::Geometry::CartesianGridXYZ::CartesianGridXYZ (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 69 of file CartesianGridXYZ.h.
DD4hep::Geometry::CartesianGridXYZ::CartesianGridXYZ (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 71 of file CartesianGridXYZ.h.
template<typename Q > DD4hep::Geometry::CartesianGridXYZ::CartesianGridXYZ (const Handle< Q > & e) [inline]
Copy constructor from other polymorph/equivalent handle.
Definition at line 74 of file CartesianGridXYZ.h.
Member Function Documentation
vector< double > CartesianGridXYZ::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in x
size in y
size in z
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in x
size in y
size in z
Definition at line 122 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID CartesianGridXYZ::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 30 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
const string & CartesianGridXYZ::fieldNameX () const
access the field name used for X
Definition at line 98 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
const string & CartesianGridXYZ::fieldNameY () const
access the field name used for Y
Definition at line 103 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
const string & CartesianGridXYZ::fieldNameZ () const
access the field name used for Z
Definition at line 108 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXYZ::gridSizeX () const
access the grid size in X
Definition at line 38 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXYZ::gridSizeY () const
access the grid size in Y
Definition at line 43 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXYZ::gridSizeZ () const
access the grid size in Z
Definition at line 48 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXYZ::offsetX () const
access the coordinate offset in X
Definition at line 68 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXYZ::offsetY () const
access the coordinate offset in Y
Definition at line 73 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridXYZ::offsetZ () const
access the coordinate offset in Z
Definition at line 78 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
CartesianGridXYZ& DD4hep::Geometry::CartesianGridXYZ::operator= (const CartesianGridXYZ & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::CartesianGridXYZ::operator== (const CartesianGridXYZ & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 78 of file CartesianGridXYZ.h.
References DD4hep::Handle< T >::m_element.
Position CartesianGridXYZ::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 25 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXYZ::setGridSizeX (double cellSize) const
set the grid size in X
Definition at line 53 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXYZ::setGridSizeY (double cellSize) const
set the grid size in Y
Definition at line 58 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXYZ::setGridSizeZ (double cellSize) const
set the grid size in Z
Definition at line 63 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXYZ::setOffsetX (double offset) const
set the coordinate offset in X
Definition at line 83 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXYZ::setOffsetY (double offset) const
set the coordinate offset in Y
Definition at line 88 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridXYZ::setOffsetZ (double offset) const
set the coordinate offset in Z
Definition at line 93 of file CartesianGridXYZ.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/CartesianGridXYZ.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/CartesianGridXYZ.cpp