DD4hep: DD4hep::Geometry::World Class Reference
DD4hep::Geometry::World Class Reference
DD4hep::Geometry components, classes and objects
Handle class to hold the information of the top DetElement object 'world'.
#include <World.h>
Public Types
typedef WorldObject Object
Internal object type.
typedef Handle< Object > RefObject
Definition of the base handle type.
typedef Conditions::ConditionsLoader ConditionsLoader
Conditions stuff.
typedef Alignments::AlignmentsLoader AlignmentsLoader
Alignment stuff.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
World ()
Default constructor.
World (const RefObject &o)
Copy from named handle.
World (const World &w)
Copy from handle.
World (Object *p)
Copy from pointer.
template<typename Q >
World (const Handle< Q > &e)
Templated constructor for handle conversions.
World & operator= (const World &sd)
Assignment operator.
LCDD & lcdd () const
Access the detector descrion tree.
ConditionsLoader & conditionsLoader () const
Access the conditions loading.
AlignmentsLoader & alignmentsLoader () const
Access to the alignment loading.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class to hold the information of the top DetElement object 'world'.
Author
M.Frank
Version
1.0
Definition at line 35 of file World.h.
Member Typedef Documentation
AlignmentsLoader
typedef Alignments::AlignmentsLoader DD4hep::Geometry::World::AlignmentsLoader
Alignment stuff.
Definition at line 44 of file World.h.
ConditionsLoader
typedef Conditions::ConditionsLoader DD4hep::Geometry::World::ConditionsLoader
Conditions stuff.
Definition at line 42 of file World.h.
Object
typedef WorldObject DD4hep::Geometry::World::Object
Internal object type.
Definition at line 38 of file World.h.
RefObject
typedef Handle<Object> DD4hep::Geometry::World::RefObject
Definition of the base handle type.
Definition at line 40 of file World.h.
Constructor & Destructor Documentation
World() [1/5]
DD4hep::Geometry::World::World () inline
Default constructor.
Definition at line 48 of file World.h.
World() [2/5]
DD4hep::Geometry::World::World (const RefObject & o) inline
Copy from named handle.
Definition at line 51 of file World.h.
World() [3/5]
DD4hep::Geometry::World::World (const World & w) inline
Copy from handle.
Definition at line 54 of file World.h.
World() [4/5]
DD4hep::Geometry::World::World (Object * p) inline
Copy from pointer.
Definition at line 57 of file World.h.
World() [5/5]
template<typename Q > DD4hep::Geometry::World::World (const Handle< Q > & e) inline
Templated constructor for handle conversions.
Definition at line 60 of file World.h.
Member Function Documentation
alignmentsLoader()
World::AlignmentsLoader & World::alignmentsLoader () const
Access to the alignment loading.
Definition at line 31 of file World.cpp.
References DD4hep::Handle< T >::access(), and DD4hep::except().
Referenced by operator=().
conditionsLoader()
World::ConditionsLoader & World::conditionsLoader () const
Access the conditions loading.
Definition at line 22 of file World.cpp.
References DD4hep::Handle< T >::access(), and DD4hep::except().
Referenced by DD4hep::Conditions::ConditionsManagerObject::initialize(), and operator=().
lcdd()
LCDD & World::lcdd () const
Access the detector descrion tree.
Definition at line 40 of file World.cpp.
References DD4hep::Handle< T >::access().
Referenced by operator=().
operator=()
World& DD4hep::Geometry::World::operator= (const World & sd) inline
Assignment operator.
Definition at line 63 of file World.h.
References alignmentsLoader(), conditionsLoader(), lcdd(), and DD4hep::Handle< T >::m_element.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/World.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/World.cpp