DD4hep: DD4hep: DD4hep::Alignments::GlobalDetectorAlignment Class Reference
DD4hep::Alignments::GlobalDetectorAlignment Class Reference
[DDAlign: DD4hep Detector geometry alignment components.]
GlobalDetectorAlignment. DetElement Handle supporting alignment operations.
#include <GlobalDetectorAlignment.h>
Inherits Geometry::DetElement.
Public Member Functions
GlobalDetectorAlignment (DetElement e)
Initializing constructor.
void collectNodes (std::vector< PlacedVolume > &nodes)
Collect all placements from the detector element up to the world volume.
GlobalAlignment alignment () const
Access to the alignment block.
std::vector< GlobalAlignment > & volumeAlignments ()
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
const std::vector
< GlobalAlignment > & volumeAlignments () const
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
GlobalAlignment align (const Position &pos, bool check=false, double overlap=0.001)
Align the PhysicalNode of the placement of the detector element (translation only).
GlobalAlignment align (const RotationZYX &rot, bool check=false, double overlap=0.001)
Align the PhysicalNode of the placement of the detector element (rotation only).
GlobalAlignment align (const Position &pos, const RotationZYX &rot, bool check=false, double overlap=0.001)
Align the PhysicalNode of the placement of the detector element (translation + rotation).
GlobalAlignment align (const Transform3D &tr, bool check=false, double overlap=0.001)
Align the physical node according to a generic Transform3D.
GlobalAlignment align (TGeoHMatrix *matrix, bool check=false, double overlap=0.001)
Align the physical node according to a generic TGeo matrix.
GlobalAlignment align (const std::string &volume_path, const Position &pos, bool check=false, double overlap=0.001)
Align the PhysicalNode of the placement of the detector element (translation only).
GlobalAlignment align (const std::string &volume_path, const RotationZYX &rot, bool check=false, double overlap=0.001)
Align the PhysicalNode of the placement of the detector element (rotation only).
GlobalAlignment align (const std::string &volume_path, const Position &pos, const RotationZYX &rot, bool check=false, double overlap=0.001)
Align the PhysicalNode of the placement of the detector element (translation + rotation).
GlobalAlignment align (const std::string &volume_path, const Transform3D &tr, bool check=false, double overlap=0.001)
Align the physical node according to a generic Transform3D.
GlobalAlignment align (const std::string &volume_path, TGeoHMatrix *matrix, bool check=false, double overlap=0.001)
Align the physical node according to a generic TGeo matrix.
Static Public Member Functions
static bool debug ()
Access debugging flag.
static bool debug (bool value)
Set debugging flag.
Detailed Description
GlobalDetectorAlignment. DetElement Handle supporting alignment operations.
Author:
M.Frank
Version:
1.0
Definition at line 36 of file GlobalDetectorAlignment.h.
Constructor & Destructor Documentation
GlobalDetectorAlignment::GlobalDetectorAlignment (DetElement e)
Initializing constructor.
Definition at line 137 of file GlobalDetectorAlignment.cpp.
Member Function Documentation
GlobalAlignment DD4hep::Alignments::GlobalDetectorAlignment::align (const std::string & volume_path, TGeoHMatrix * matrix, bool check = false, double overlap = 0.001)
Align the physical node according to a generic TGeo matrix.
GlobalAlignment DD4hep::Alignments::GlobalDetectorAlignment::align (const std::string & volume_path, const Transform3D & tr, bool check = false, double overlap = 0.001)
Align the physical node according to a generic Transform3D.
GlobalAlignment DD4hep::Alignments::GlobalDetectorAlignment::align (const std::string & volume_path, const Position & pos, const RotationZYX & rot, bool check = false, double overlap = 0.001)
Align the PhysicalNode of the placement of the detector element (translation + rotation).
GlobalAlignment DD4hep::Alignments::GlobalDetectorAlignment::align (const std::string & volume_path, const RotationZYX & rot, bool check = false, double overlap = 0.001)
Align the PhysicalNode of the placement of the detector element (rotation only).
GlobalAlignment DD4hep::Alignments::GlobalDetectorAlignment::align (const std::string & volume_path, const Position & pos, bool check = false, double overlap = 0.001)
Align the PhysicalNode of the placement of the detector element (translation only).
alignment: Calls to align the volumes within on detector element
GlobalAlignment GlobalDetectorAlignment::align (TGeoHMatrix * matrix, bool check = false, double overlap = 0.001)
Align the physical node according to a generic TGeo matrix.
Definition at line 197 of file GlobalDetectorAlignment.cpp.
GlobalAlignment GlobalDetectorAlignment::align (const Transform3D & tr, bool check = false, double overlap = 0.001)
Align the physical node according to a generic Transform3D.
Definition at line 192 of file GlobalDetectorAlignment.cpp.
References DD4hep::Geometry::_transform(), and align().
GlobalAlignment GlobalDetectorAlignment::align (const Position & pos, const RotationZYX & rot, bool check = false, double overlap = 0.001)
Align the PhysicalNode of the placement of the detector element (translation + rotation).
Definition at line 187 of file GlobalDetectorAlignment.cpp.
References DD4hep::Geometry::_transform(), and align().
GlobalAlignment GlobalDetectorAlignment::align (const RotationZYX & rot, bool check = false, double overlap = 0.001)
Align the PhysicalNode of the placement of the detector element (rotation only).
Definition at line 182 of file GlobalDetectorAlignment.cpp.
References DD4hep::Geometry::_transform(), and align().
GlobalAlignment GlobalDetectorAlignment::align (const Position & pos, bool check = false, double overlap = 0.001)
Align the PhysicalNode of the placement of the detector element (translation only).
alignment: Calls to align the detector element itself
Definition at line 177 of file GlobalDetectorAlignment.cpp.
References DD4hep::Geometry::_transform().
Referenced by align().
GlobalAlignment GlobalDetectorAlignment::alignment () const
Access to the alignment block.
Definition at line 160 of file GlobalDetectorAlignment.cpp.
void DD4hep::Alignments::GlobalDetectorAlignment::collectNodes (std::vector< PlacedVolume > & nodes)
Collect all placements from the detector element up to the world volume.
bool GlobalDetectorAlignment::debug (bool value) [static]
Set debugging flag.
Definition at line 148 of file GlobalDetectorAlignment.cpp.
bool GlobalDetectorAlignment::debug () [static]
Access debugging flag.
Definition at line 143 of file GlobalDetectorAlignment.cpp.
const vector< GlobalAlignment > & GlobalDetectorAlignment::volumeAlignments () const
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
Definition at line 171 of file GlobalDetectorAlignment.cpp.
References _data().
vector< GlobalAlignment > & GlobalDetectorAlignment::volumeAlignments ()
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
Definition at line 165 of file GlobalDetectorAlignment.cpp.
References _data().
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::createElement().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/GlobalDetectorAlignment.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/GlobalDetectorAlignment.cpp