DD4hep: DD4hep: DD4hep::EventControl Class Reference
DD4hep::EventControl Class Reference
[DDEve: DD4hep event display components, classes and objects]
#include <EventControl.h>
Public Member Functions
EventControl (Display *disp, unsigned int width, unsigned int height)
Standard constructor.
virtual ~EventControl ()
Default destructor.
virtual void OnBuild ()
User callback to add elements to the control.
TGCompositeFrame * CreateFrame ()
Create the frame for this control structure. Default: create horizontal frame.
virtual bool Open ()
Open a new event data file.
virtual void NextEvent ()
Load the next event.
virtual void PreviousEvent ()
Load the previous event.
virtual void GotoEvent ()
Goto a specified event.
virtual void OnNewEvent (EventHandler *handler)
EventConsumer overload: New consumer event data.
virtual void OnFileOpen (EventHandler *handler)
EventConsumer overload: New event data file.
Private Types
enum { NUM_DATA_LINES = 40 }
typedef std::pair< TGLabel
*, TGLabel * > Labels
typedef std::pair
< TGCompositeFrame *, Labels > Line
typedef std::vector< Line > Lines
Private Attributes
Display * m_display
Refernece to the display object.
TGGroupFrame * m_dataGroup
Data frame.
TGCompositeFrame * m_dataFrame
TGGroupFrame * m_eventGroup
Data frame.
TGCompositeFrame * m_numEvtFrame
TGLabel * m_input1
TGLabel * m_input2
TGLabel * m_numEvtLabel
TGPictureButton * m_open
TGPictureButton * m_prev
TGPictureButton * m_next
TGPictureButton * m_goto
Lines m_lines
Detailed Description
EventControl EventControl.h DDEve/EventControl.h
Author:
M.Frank
Version:
1.0
Definition at line 37 of file EventControl.h.
Member Typedef Documentation
typedef std::pair<TGLabel*,TGLabel*> DD4hep::EventControl::Labels [private]
Definition at line 50 of file EventControl.h.
typedef std::pair<TGCompositeFrame*,Labels> DD4hep::EventControl::Line [private]
Definition at line 51 of file EventControl.h.
typedef std::vector<Line > DD4hep::EventControl::Lines [private]
Definition at line 52 of file EventControl.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
NUM_DATA_LINES
Definition at line 38 of file EventControl.h.
Constructor & Destructor Documentation
DD4hep::EventControl::EventControl (Display * disp, unsigned int width, unsigned int height)
Standard constructor.
EventControl::~EventControl () [virtual]
Default destructor.
Definition at line 50 of file EventControl.cpp.
References DD4hep::InstanceCount::decrement(), DD4hep::Display::eventHandler(), m_display, and DD4hep::GenericEventHandler::Unsubscribe().
Member Function Documentation
TGCompositeFrame * EventControl::CreateFrame () [virtual]
Create the frame for this control structure. Default: create horizontal frame.
Reimplemented from DD4hep::FrameControl.
Definition at line 56 of file EventControl.cpp.
void EventControl::GotoEvent () [virtual]
Goto a specified event.
Definition at line 71 of file EventControl.cpp.
References DD4hep::Display::eventHandler(), DD4hep::GenericEventHandler::GotoEvent(), and m_display.
void EventControl::NextEvent () [virtual]
Load the next event.
Definition at line 61 of file EventControl.cpp.
References DD4hep::Display::eventHandler(), m_display, and DD4hep::GenericEventHandler::NextEvent().
void EventControl::OnBuild () [virtual]
User callback to add elements to the control.
Reimplemented from DD4hep::FrameControl.
Definition at line 156 of file EventControl.cpp.
References DD4hep::GenericEventHandler::datasourceName(), DD4hep::Display::eventHandler(), DD4hep::EventHandler::hasFile(), DD4hep::FrameControl::LoadPicture(), m_dataFrame, m_dataGroup, m_display, m_eventGroup, DD4hep::FrameControl::m_frame, m_goto, m_input1, m_input2, m_lines, m_next, m_numEvtFrame, m_open, m_prev, NUM_DATA_LINES, and DD4hep::GenericEventHandler::numEvents().
void EventControl::OnFileOpen (EventHandler * handler) [virtual]
EventConsumer overload: New event data file.
Reimplemented from DD4hep::EventConsumer.
Definition at line 91 of file EventControl.cpp.
References DD4hep::FrameControl::client(), DD4hep::EventHandler::datasourceName(), DD4hep::EventHandler::hasFile(), m_eventGroup, m_input1, m_input2, and DD4hep::EventHandler::numEvents().
void EventControl::OnNewEvent (EventHandler * handler) [virtual]
EventConsumer overload: New consumer event data.
Consumer event data.
Reimplemented from DD4hep::EventConsumer.
Definition at line 111 of file EventControl.cpp.
References DD4hep::FrameControl::client(), DD4hep::EventHandler::data(), m_dataGroup, and m_lines.
bool EventControl::Open () [virtual]
Open a new event data file.
Definition at line 77 of file EventControl.cpp.
References DD4hep::Display::eventHandler(), DD4hep::Display::getEventHandlerName(), m_display, DD4hep::GenericEventHandler::Open(), and DD4hep::Display::OpenEventFileDialog().
Referenced by DD4hep::DD4hepMenu::OnOpenEventData().
void EventControl::PreviousEvent () [virtual]
Load the previous event.
Definition at line 66 of file EventControl.cpp.
References DD4hep::Display::eventHandler(), m_display, and DD4hep::GenericEventHandler::PreviousEvent().
Member Data Documentation
TGCompositeFrame* DD4hep::EventControl::m_dataFrame [private]
Definition at line 43 of file EventControl.h.
Referenced by OnBuild().
TGGroupFrame* DD4hep::EventControl::m_dataGroup [private]
Data frame.
Definition at line 42 of file EventControl.h.
Referenced by OnBuild(), and OnNewEvent().
Display* DD4hep::EventControl::m_display [private]
Refernece to the display object.
Definition at line 40 of file EventControl.h.
Referenced by GotoEvent(), NextEvent(), OnBuild(), Open(), PreviousEvent(), and ~EventControl().
TGGroupFrame* DD4hep::EventControl::m_eventGroup [private]
Data frame.
Definition at line 45 of file EventControl.h.
Referenced by OnBuild(), and OnFileOpen().
TGPictureButton * DD4hep::EventControl::m_goto [private]
Definition at line 49 of file EventControl.h.
Referenced by OnBuild().
TGLabel* DD4hep::EventControl::m_input1 [private]
Definition at line 47 of file EventControl.h.
Referenced by OnBuild(), and OnFileOpen().
TGLabel * DD4hep::EventControl::m_input2 [private]
Definition at line 47 of file EventControl.h.
Referenced by OnBuild(), and OnFileOpen().
Lines DD4hep::EventControl::m_lines [private]
Definition at line 53 of file EventControl.h.
Referenced by OnBuild(), and OnNewEvent().
TGPictureButton * DD4hep::EventControl::m_next [private]
Definition at line 49 of file EventControl.h.
Referenced by OnBuild().
TGCompositeFrame* DD4hep::EventControl::m_numEvtFrame [private]
Definition at line 46 of file EventControl.h.
Referenced by OnBuild().
TGLabel* DD4hep::EventControl::m_numEvtLabel [private]
Definition at line 48 of file EventControl.h.
TGPictureButton* DD4hep::EventControl::m_open [private]
Definition at line 49 of file EventControl.h.
Referenced by OnBuild().
TGPictureButton * DD4hep::EventControl::m_prev [private]
Definition at line 49 of file EventControl.h.
Referenced by OnBuild().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/EventControl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/EventControl.cpp