DD4hep: DD4hep::Simulation::Geant4EventReader Class Reference
DD4hep::Simulation::Geant4EventReader Class Reference abstract
DD4hep::Simulation components, classes and objects
Basic geant4 event reader class. This interface/base-class must be implemented by concrete readers.
#include <Geant4InputAction.h>
Public Types
enum EventReaderStatus {
EVENT_READER_ERROR =0, EVENT_READER_OK =1, EVENT_READER_NO_DIRECT =2, EVENT_READER_NO_PRIMARIES =4,
EVENT_READER_NO_FACTORY =6, EVENT_READER_IO_ERROR =8
}
Status codes of the event reader object. Anything with NOT low-bit set is an error.
typedef Geant4Vertex Vertex
typedef Geant4Particle Particle
typedef std::vector< Particle * > Particles
Public Member Functions
Geant4EventReader (const std::string &nam)
Initializing constructor.
virtual ~Geant4EventReader ()
Default destructor.
const std::string & name () const
File name.
bool hasDirectAccess () const
Flag if direct event access (by event sequence number) is supported (Default: false)
int currentEventNumber () const
return current Event Number
virtual EventReaderStatus moveToEvent (int event_number)
Move to the indicated event number.
virtual EventReaderStatus skipEvent ()
Skip event. To be implemented for sequential sources.
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, Particles &particles)=0
Read an event and fill a vector of MCParticles.
Protected Attributes
std::string m_name
File name to be opened and read.
bool m_directAccess
Flag if direct event access is supported. To be explicitly set by subclass constructors.
int m_currEvent
Current event number.
Detailed Description
Basic geant4 event reader class. This interface/base-class must be implemented by concrete readers.
Base class to read input files containing simulation data.
Author
P.Kostka (main author)
M.Frank (code reshuffeling into new DDG4 scheme)
Version
1.0
Definition at line 45 of file Geant4InputAction.h.
Member Typedef Documentation
Particle
typedef Geant4Particle DD4hep::Simulation::Geant4EventReader::Particle
Definition at line 49 of file Geant4InputAction.h.
Particles
typedef std::vector<Particle*> DD4hep::Simulation::Geant4EventReader::Particles
Definition at line 50 of file Geant4InputAction.h.
Vertex
typedef Geant4Vertex DD4hep::Simulation::Geant4EventReader::Vertex
Definition at line 48 of file Geant4InputAction.h.
Member Enumeration Documentation
EventReaderStatus
enum DD4hep::Simulation::Geant4EventReader::EventReaderStatus
Status codes of the event reader object. Anything with NOT low-bit set is an error.
Enumerator
EVENT_READER_ERROR
EVENT_READER_OK
EVENT_READER_NO_DIRECT
EVENT_READER_NO_PRIMARIES
EVENT_READER_NO_FACTORY
EVENT_READER_IO_ERROR
Definition at line 52 of file Geant4InputAction.h.
Constructor & Destructor Documentation
Geant4EventReader()
Geant4EventReader::Geant4EventReader (const std::string & nam)
Initializing constructor.
Definition at line 30 of file Geant4InputAction.cpp.
~Geant4EventReader()
Geant4EventReader::~Geant4EventReader () virtual
Default destructor.
Definition at line 36 of file Geant4InputAction.cpp.
Member Function Documentation
currentEventNumber()
int DD4hep::Simulation::Geant4EventReader::currentEventNumber () const inline
return current Event Number
Definition at line 77 of file Geant4InputAction.h.
References m_currEvent, moveToEvent(), readParticles(), and skipEvent().
hasDirectAccess()
bool DD4hep::Simulation::Geant4EventReader::hasDirectAccess () const inline
Flag if direct event access (by event sequence number) is supported (Default: false)
Definition at line 75 of file Geant4InputAction.h.
References m_directAccess.
Referenced by moveToEvent(), and skipEvent().
moveToEvent()
Geant4EventReader::EventReaderStatus Geant4EventReader::moveToEvent (int event_number) virtual
Move to the indicated event number.
For pure sequential access, the default implementation will skip events one by one. For technologies supporting direct event access the default implementation will be empty.
Returns
Reimplemented in DD4hep::Simulation::LCIOFileReader, DD4hep::Simulation::Geant4EventReaderHepMC, DD4hep::Simulation::Geant4EventReaderHepEvt, and DD4hep::Simulation::LCIOStdHepReader.
Definition at line 55 of file Geant4InputAction.cpp.
References EVENT_READER_ERROR, EVENT_READER_OK, hasDirectAccess(), m_currEvent, and skipEvent().
Referenced by currentEventNumber(), and DD4hep::Simulation::Geant4InputAction::readParticles().
name()
const std::string& DD4hep::Simulation::Geant4EventReader::name () const inline
File name.
Definition at line 73 of file Geant4InputAction.h.
References m_name.
Referenced by DD4hep::Simulation::HepMC::read_weight_names().
readParticles()
virtual EventReaderStatus DD4hep::Simulation::Geant4EventReader::readParticles (int event_number, Vertex & primary_vertex, Particles & particles) pure virtual
Read an event and fill a vector of MCParticles.
The additional argument
Referenced by currentEventNumber(), DD4hep::Simulation::Geant4InputAction::readParticles(), and skipEvent().
skipEvent()
Geant4EventReader::EventReaderStatus Geant4EventReader::skipEvent () virtual
Skip event. To be implemented for sequential sources.
Reimplemented in DD4hep::Simulation::LCIOFileReader, DD4hep::Simulation::Geant4EventReaderHepMC, DD4hep::Simulation::Geant4EventReaderHepEvt, and DD4hep::Simulation::LCIOStdHepReader.
Definition at line 40 of file Geant4InputAction.cpp.
References EVENT_READER_OK, hasDirectAccess(), m_currEvent, readParticles(), and DD4hep::Simulation::HepMC::vertex().
Referenced by currentEventNumber(), and moveToEvent().
Member Data Documentation
m_currEvent
int DD4hep::Simulation::Geant4EventReader::m_currEvent protected
Current event number.
Definition at line 66 of file Geant4InputAction.h.
Referenced by currentEventNumber(), DD4hep::Simulation::LCIOStdHepReader::moveToEvent(), DD4hep::Simulation::Geant4EventReaderHepEvt::moveToEvent(), DD4hep::Simulation::Geant4EventReaderHepMC::moveToEvent(), moveToEvent(), DD4hep::Simulation::LCIOStdHepReader::readParticleCollection(), DD4hep::Simulation::Geant4EventReaderHepEvt::readParticles(), DD4hep::Simulation::Geant4EventReaderHepMC::readParticles(), and skipEvent().
m_directAccess
bool DD4hep::Simulation::Geant4EventReader::m_directAccess protected
Flag if direct event access is supported. To be explicitly set by subclass constructors.
Definition at line 64 of file Geant4InputAction.h.
Referenced by hasDirectAccess().
m_name
std::string DD4hep::Simulation::Geant4EventReader::m_name protected
File name to be opened and read.
Definition at line 62 of file Geant4InputAction.h.
Referenced by name(), and DD4hep::Simulation::Geant4EventReaderHepMC::readParticles().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4InputAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4InputAction.cpp