DD4hep: DD4hep::Conditions::ConditionsLoaderImp Class Reference
DD4hep::Conditions::ConditionsLoaderImp Class Reference
Concrete class to interface conditions loading from DetElements.
#include <ConditionsLoaderImp.h>
Public Member Functions
ConditionsLoaderImp (ConditionsManager mgr)
Default constructor.
virtual ~ConditionsLoaderImp ()
Default destructor.
virtual void addRef ()
Addreference count. Use object.
virtual void release ()
Release object. The client may not use any reference any further.
virtual Condition get (key_type key, const iov_type &iov)
Access the conditions loading mechanism.
virtual Condition get (key_type key, const UserPool &pool)
Access the conditions loading mechanism. Only conditions in the user pool will be accessed.
Protected Attributes
ConditionsManager m_manager
Reference to conditions manager.
long m_refCount
Referenec count.
Additional Inherited Members
Protected Types inherited from DD4hep::Conditions::ConditionsLoader
typedef Condition::key_type key_type
typedef Condition::iov_type iov_type
Protected Member Functions inherited from DD4hep::Conditions::ConditionsLoader
virtual ~ConditionsLoader ()
Protected destructor.
Detailed Description
Concrete class to interface conditions loading from DetElements.
Author
M.Frank
Version
1.0
Definition at line 33 of file ConditionsLoaderImp.h.
Constructor & Destructor Documentation
ConditionsLoaderImp()
ConditionsLoaderImp::ConditionsLoaderImp (ConditionsManager mgr)
Default constructor.
Definition at line 23 of file ConditionsLoaderImp.cpp.
~ConditionsLoaderImp()
ConditionsLoaderImp::~ConditionsLoaderImp () virtual
Default destructor.
Definition at line 29 of file ConditionsLoaderImp.cpp.
Member Function Documentation
addRef()
void ConditionsLoaderImp::addRef () virtual
Addreference count. Use object.
Implements DD4hep::Conditions::ConditionsLoader.
Definition at line 33 of file ConditionsLoaderImp.cpp.
References m_refCount.
get() [1/2]
Condition ConditionsLoaderImp::get (key_type key, const iov_type & iov) virtual
Access the conditions loading mechanism.
Implements DD4hep::Conditions::ConditionsLoader.
Definition at line 45 of file ConditionsLoaderImp.cpp.
References DD4hep::Conditions::ConditionsManagerObject::get(), m_manager, and DD4hep::Handle< T >::ptr().
get() [2/2]
Condition ConditionsLoaderImp::get (key_type key, const UserPool & pool) virtual
Access the conditions loading mechanism. Only conditions in the user pool will be accessed.
Implements DD4hep::Conditions::ConditionsLoader.
Definition at line 50 of file ConditionsLoaderImp.cpp.
References DD4hep::Conditions::UserPool::get().
release()
void ConditionsLoaderImp::release () virtual
Release object. The client may not use any reference any further.
Implements DD4hep::Conditions::ConditionsLoader.
Definition at line 38 of file ConditionsLoaderImp.cpp.
References m_refCount.
Member Data Documentation
m_manager
ConditionsManager DD4hep::Conditions::ConditionsLoaderImp::m_manager protected
Reference to conditions manager.
Definition at line 36 of file ConditionsLoaderImp.h.
Referenced by get().
m_refCount
long DD4hep::Conditions::ConditionsLoaderImp::m_refCount protected
Referenec count.
Definition at line 38 of file ConditionsLoaderImp.h.
Referenced by addRef(), and release().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsLoaderImp.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsLoaderImp.cpp