DD4hep: DD4hep::Conditions::Condition Class Reference
DD4hep::Conditions::Condition Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Main condition object handle.
#include <Conditions.h>
Classes
class Processor
Abstract base for processing callbacks.
Public Types
enum StringFlags {
WITH_IOV = 1<<0, WITH_ADDRESS = 1<<1, WITH_TYPE = 1<<2, WITH_COMMENT = 1<<4,
WITH_DATATYPE = 1<<5, WITH_DATA = 1<<6, NO_NAME = 1<<20, NONE
}
enum ConditionState {
INACTIVE = 0, ACTIVE = 1<<0, CHECKED = 1<<2, DERIVED = 1<<3,
TEMPERATURE = 1<<4, PRESSURE = 1<<5, ALIGNMENT = 1<<6, USER_FLAGS_FIRST = 1<<16,
USER_FLAGS_LAST = 1<<31
}
typedef Interna::ConditionObject Object
Standard object type.
typedef unsigned int key_type
Forward definition of the key type.
typedef IOV iov_type
Forward definition of the iov type.
Public Types inherited from DD4hep::Handle< Interna::ConditionObject >
typedef Interna::ConditionObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Condition ()=default
Default constructor.
Condition (const Condition &c)=default
Copy constructor.
Condition (Object *p)
Initializing constructor.
template<typename Q >
Condition (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
Condition (const std::string &name, const std::string &type)
Initializing constructor for a pure, undecorated conditions object.
Condition & operator= (const Condition &c)=default
Assignment operator.
std::string str (int with_data=WITH_IOV|WITH_ADDRESS|WITH_DATATYPE) const
Output method.
int dataType () const
Access the data type.
OpaqueData & data () const
Access the IOV block.
const IOVType & iovType () const
Access the IOV type.
const iov_type & iov () const
Access the IOV block.
const std::string & name () const
Access the name of the condition.
const std::string & type () const
Access the type field of the condition.
const std::string & comment () const
Access the comment field of the condition.
const std::string & value () const
Access the value field of the condition as a string.
const std::string & address () const
Access the address string [e.g. database identifier].
const std::type_info & typeInfo () const
Access to the type information.
const BasicGrammar & descriptor () const
Access to the grammar type.
key_type key () const
Hash identifier.
Condition & rebind ()
Re-evaluate the conditions data according to the previous bound type definition.
template<typename T >
T & bind ()
Bind the data of the conditions object to a given format.
template<typename T >
T & get ()
Generic getter. Specify the exact type, not a polymorph type.
template<typename T >
const T & get () const
Generic getter (const version). Specify the exact type, not a polymorph type.
bool is_bound () const
Check if object is already bound....
Public Member Functions inherited from DD4hep::Handle< Interna::ConditionObject >
Handle ()
Defaulot constructor.
Handle (Interna::ConditionObject *e)
Initializing constructor from pointer.
Handle (const Handle< Interna::ConditionObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< Interna::ConditionObject > & operator= (const Handle< Interna::ConditionObject > &e)=default
Assignment operator.
bool operator== (const Handle< Interna::ConditionObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< Interna::ConditionObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< Interna::ConditionObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< Interna::ConditionObject > & clear ()
Release the object held by the handle.
Interna::ConditionObject * operator-> () const
Access the held object using the -> operator.
operator Interna::ConditionObject & () const
Automatic type conversion to an object references.
Interna::ConditionObject & operator* () const
Access the held object using the * operator.
Interna::ConditionObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
Interna::ConditionObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< Interna::ConditionObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< Interna::ConditionObject >
Interna::ConditionObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Main condition object handle.
This objects allows access to the data block and the interval of validity for a single condition.
Note: Conditions may be shared between several DetElement objects. Hence, the back-link to the DetElement structure cannot be set - it would be ambiguous.
Author
M.Frank
Version
1.0
Definition at line 70 of file Conditions.h.
Member Typedef Documentation
iov_type
typedef IOV DD4hep::Conditions::Condition::iov_type
Forward definition of the iov type.
Definition at line 77 of file Conditions.h.
key_type
typedef unsigned int DD4hep::Conditions::Condition::key_type
Forward definition of the key type.
Definition at line 75 of file Conditions.h.
Object
typedef Interna::ConditionObject DD4hep::Conditions::Condition::Object
Standard object type.
Definition at line 73 of file Conditions.h.
Member Enumeration Documentation
ConditionState
enum DD4hep::Conditions::Condition::ConditionState
Enumerator
INACTIVE
ACTIVE
CHECKED
DERIVED
TEMPERATURE
PRESSURE
ALIGNMENT
USER_FLAGS_FIRST
USER_FLAGS_LAST
Definition at line 90 of file Conditions.h.
StringFlags
enum DD4hep::Conditions::Condition::StringFlags
Enumerator
WITH_IOV
WITH_ADDRESS
WITH_TYPE
WITH_COMMENT
WITH_DATATYPE
WITH_DATA
NO_NAME
NONE
Definition at line 80 of file Conditions.h.
Constructor & Destructor Documentation
Condition() [1/5]
DD4hep::Conditions::Condition::Condition () default
Default constructor.
Referenced by DD4hep::Conditions::Container::get().
Condition() [2/5]
DD4hep::Conditions::Condition::Condition (const Condition & c) default
Copy constructor.
Condition() [3/5]
DD4hep::Conditions::Condition::Condition (Condition::Object * p) inline
Initializing constructor.
Definition at line 182 of file Conditions.h.
Condition() [4/5]
template<typename Q > DD4hep::Conditions::Condition::Condition (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 122 of file Conditions.h.
Condition() [5/5]
Condition::Condition (const std::string & name, const std::string & type)
Initializing constructor for a pure, undecorated conditions object.
Initializing constructor.
Definition at line 55 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::assign(), DD4hep::Conditions::Interna::ConditionObject::hash, and DD4hep::Conditions::ConditionKey::hashCode().
Member Function Documentation
address()
const string & Condition::address () const
Access the address string [e.g. database identifier].
Definition at line 124 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::address.
Referenced by DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
bind()
template<typename T > T & DD4hep::Conditions::Condition::bind ()
Bind the data of the conditions object to a given format.
Bind the data of the conditions object to a given format.
Note: The type definition is possible exactly once. Any further rebindings MUST match the identical type.
Definition at line 194 of file ConditionsInterna.h.
References DD4hep::Conditions::Interna::ConditionObject::data, DD4hep::OpaqueDataBlock::set(), and DD4hep::Conditions::Interna::ConditionObject::value.
Referenced by DD4hep::Conditions::Test::access_val(), and DD4hep::Alignments::AlignmentCondition::data().
comment()
const string & Condition::comment () const
Access the comment field of the condition.
Definition at line 119 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::comment.
data()
DD4hep::OpaqueData & Condition::data () const
Access the IOV block.
Definition at line 89 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::data.
Referenced by DD4hep::Conditions::Test::__print_bound_container(), and DD4hep::Alignments::AlignmentCondition::is_bound().
dataType()
int Condition::dataType () const
Access the data type.
Data block (bound type)
Definition at line 84 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), DD4hep::Conditions::Interna::ConditionObject::data, and DD4hep::OpaqueDataBlock::type.
descriptor()
const DD4hep::BasicGrammar & Condition::descriptor () const
Access to the grammar type.
Definition at line 139 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), DD4hep::Conditions::Interna::ConditionObject::data, dd4hep::g, and DD4hep::OpaqueData::grammar.
Referenced by typeInfo().
get() [1/2]
template<typename T > T & DD4hep::Conditions::Condition::get ()
Generic getter. Specify the exact type, not a polymorph type.
Definition at line 199 of file ConditionsInterna.h.
Referenced by DD4hep::Conditions::Test::__print_bound_val(), DD4hep::Conditions::Test::access_val(), DD4hep::Alignments::AlignmentCondition::data(), DD4hep::Conditions::ConditionsAccess::get(), DD4hep::Conditions::ConditionUpdateContext::get(), and DD4hep::Conditions::DetConditions::get().
get() [2/2]
template<typename T > const T & DD4hep::Conditions::Condition::get () const
Generic getter (const version). Specify the exact type, not a polymorph type.
Definition at line 203 of file ConditionsInterna.h.
iov()
const DD4hep::IOV & Condition::iov () const
Access the IOV block.
Definition at line 99 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::iovData().
Referenced by DD4hep::Conditions::Test::check_discrete_condition(), DD4hep::Conditions::Container::Container(), DD4hep::Conditions::ConditionUpdateContext::get(), DD4hep::Conditions::ConditionsManagerObject::get(), DD4hep::Conditions::ConditionsManagerObject::registerUnlocked(), and DD4hep::Conditions::ConditionsManagerObject::select_range().
iovType()
const DD4hep::IOVType & Condition::iovType () const
Access the IOV type.
Interval of validity
Definition at line 94 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::iovType().
is_bound()
bool DD4hep::Conditions::Condition::is_bound () const inline
Check if object is already bound....
Definition at line 178 of file Conditions.h.
References DD4hep::OpaqueData::is_bound().
Referenced by DD4hep::Conditions::Test::access_val(), and DD4hep::Alignments::AlignmentCondition::data().
key()
Condition::key_type Condition::key () const
Hash identifier.
Definition at line 134 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::hash.
Referenced by DD4hep::Conditions::ConditionKey::ConditionKey(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
name()
const string & Condition::name () const
Access the name of the condition.
Direct data items in string form
Definition at line 104 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::NamedObject::name.
Referenced by DD4hep::Conditions::Test::__print_bound_container(), DD4hep::Conditions::Test::__print_bound_val(), DD4hep::Conditions::Test::check_discrete_condition(), DD4hep::Conditions::ConditionsManagerObject::get(), DD4hep::Conditions::ConditionKey::operator const std::string &(), DD4hep::Conditions::ConditionKey::operator=(), rebind(), DD4hep::Conditions::ConditionsManagerObject::select_range(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
operator=()
Condition& DD4hep::Conditions::Condition::operator= (const Condition & c) default
Assignment operator.
Referenced by DD4hep::Conditions::ConditionKey::ConditionKey(), and DD4hep::Conditions::Container::Container().
rebind()
Condition & Condition::rebind ()
Re-evaluate the conditions data according to the previous bound type definition.
Conditions handling
Definition at line 151 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), DD4hep::Conditions::Interna::ConditionObject::data, DD4hep::except(), DD4hep::OpaqueData::fromString(), DD4hep::INFO, DD4hep::Conditions::Interna::ConditionObject::iov, DD4hep::IOV::iovType, name(), DD4hep::printout(), DD4hep::IOVType::type, DD4hep::Conditions::Interna::ConditionObject::validity, and DD4hep::Conditions::Interna::ConditionObject::value.
str()
string Condition::str (int with_data = WITH_IOV|WITH_ADDRESS|WITH_DATATYPE) const
Output method.
Definition at line 62 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), DD4hep::Conditions::Interna::ConditionObject::address, DD4hep::Conditions::Interna::ConditionObject::comment, DD4hep::Conditions::Interna::ConditionObject::data, DD4hep::OpaqueData::dataType(), DD4hep::Conditions::Interna::ConditionObject::iovData(), DD4hep::NamedObject::name, NO_NAME, DD4hep::OpaqueData::str(), DD4hep::IOV::str(), DD4hep::NamedObject::type, WITH_ADDRESS, WITH_COMMENT, WITH_DATA, WITH_DATATYPE, WITH_IOV, and WITH_TYPE.
Referenced by DD4hep::Printer< T >::operator()().
type()
const string & Condition::type () const
Access the type field of the condition.
Definition at line 109 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::NamedObject::type.
typeInfo()
const type_info & Condition::typeInfo () const
Access to the type information.
Conditions meta-data
Definition at line 129 of file Conditions.cpp.
References descriptor(), and DD4hep::BasicGrammar::type().
Referenced by DD4hep::Conditions::Test::__print_bound_container(), and DD4hep::Conditions::Test::__print_bound_val().
value()
const string & Condition::value () const
Access the value field of the condition as a string.
Definition at line 114 of file Conditions.cpp.
References DD4hep::Handle< Interna::ConditionObject >::access(), and DD4hep::Conditions::Interna::ConditionObject::value.
Referenced by DD4hep::Conditions::ConditionKey::ConditionKey(), and DD4hep::Conditions::ConditionsManagerObject::get().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Conditions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Conditions.cpp
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/ConditionsInterna.h