DD4hep: DD4hep::dd4hep_file< T > Class Template Reference
DD4hep::dd4hep_file< T > Class Template Reference
DD4hep classes and objects
DD4hep file handling extension to boost::iostreams.
#include <IoStreams.h>
Classes
struct category
Public Types
typedef T handle_type
typedef char char_type
typedef boost::iostreams::stream_offset stream_offset
typedef boost::iostreams::detail::path detail_path
Public Member Functions
dd4hep_file ()
dd4hep_file (handle_type fd, dd4hep_file_flags)
dd4hep_file (const char *fname, BOOST_IOS::openmode mode)
void open (handle_type fd, dd4hep_file_flags flags)
void open (const char *path, BOOST_IOS::openmode mode=BOOST_IOS::in|BOOST_IOS::out)
bool is_open () const
void close ()
std::streamsize read (char_type *s, std::streamsize n)
std::streamsize write (const char_type *s, std::streamsize n)
std::streampos seek (stream_offset off, BOOST_IOS::seekdir way)
handle_type handle () const
template<>
void open (const char *path, BOOST_IOS::openmode mode)
Specialization for standard file descriptor files according to the posix standard.
template<>
dd4hep_file (handle_type fd, dd4hep_file_flags flags)
Specialization for standard file descriptor files according to the posix standard.
template<>
dd4hep_file (const char *fn, BOOST_IOS::openmode mode)
Specialization for standard file descriptor files according to the posix standard.
template<>
std::streamsize read (char_type *s, std::streamsize n)
Specialization for standard file descriptor files according to the posix standard.
template<>
std::streamsize write (const char_type *s, std::streamsize n)
Specialization for standard file descriptor files according to the posix standard.
template<>
std::streampos seek (stream_offset off, BOOST_IOS::seekdir way)
Specialization for standard file descriptor files according to the posix standard.
template<>
void close ()
Specialization for standard file descriptor files according to the posix standard.
template<>
void open (const char *path, BOOST_IOS::openmode mode)
Specialization for the usage of TFile structures.
template<>
dd4hep_file (handle_type fd, dd4hep_file_flags flags)
Specialization for the usage of TFile structures.
template<>
dd4hep_file (const char *fname, BOOST_IOS::openmode mode)
Specialization for the usage of TFile structures.
template<>
std::streamsize read (char_type *s, std::streamsize n)
Specialization for the usage of TFile structures.
template<>
std::streamsize write (const char_type *s, std::streamsize n)
Specialization for the usage of TFile structures.
template<>
std::streampos seek (stream_offset off, BOOST_IOS::seekdir way)
Specialization for the usage of TFile structures.
template<>
void close ()
Specialization for the usage of TFile structures.
Private Attributes
handle_type m_handle
dd4hep_file_flags m_flag
Friends
class dd4hep_file_source< T >
class dd4hep_file_sink< T >
Detailed Description
template<typename T>
class DD4hep::dd4hep_file< T >
DD4hep file handling extension to boost::iostreams.
Basic file handling for data sources and data sinks. Please see boost::iostreams for details. This got inspired by boost::iostreams::device::file_descriptor
The final aim is to hide all this behind a TFile object, so that we get the entire network file handling for free!
Note: Credits go to a large extend to the authors of boost::iostreams. Without their work I could not have done this!
Author
M.Frank
Version
1.0
See also
http://www.boost.org/libs/iostreams for further documentation.
Definition at line 74 of file IoStreams.h.
Member Typedef Documentation
char_type
template<typename T > typedef char DD4hep::dd4hep_file< T >::char_type
Definition at line 79 of file IoStreams.h.
detail_path
template<typename T > typedef boost::iostreams::detail::path DD4hep::dd4hep_file< T >::detail_path
Definition at line 81 of file IoStreams.h.
handle_type
template<typename T > typedef T DD4hep::dd4hep_file< T >::handle_type
Definition at line 78 of file IoStreams.h.
stream_offset
template<typename T > typedef boost::iostreams::stream_offset DD4hep::dd4hep_file< T >::stream_offset
Definition at line 80 of file IoStreams.h.
Constructor & Destructor Documentation
dd4hep_file() [1/7]
template<typename T > DD4hep::dd4hep_file< T >::dd4hep_file () inline
Definition at line 85 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::open().
dd4hep_file() [2/7]
template<typename T > DD4hep::dd4hep_file< T >::dd4hep_file (handle_type fd, dd4hep_file_flags)
dd4hep_file() [3/7]
template<typename T > DD4hep::dd4hep_file< T >::dd4hep_file (const char * fname, BOOST_IOS::openmode mode)
dd4hep_file() [4/7]
template<> DD4hep::dd4hep_file< int >::dd4hep_file (handle_type fd, dd4hep_file_flags flags)
Specialization for standard file descriptor files according to the posix standard.
Definition at line 54 of file IoStreams.cpp.
dd4hep_file() [5/7]
template<> DD4hep::dd4hep_file< int >::dd4hep_file (const char * fn, BOOST_IOS::openmode mode)
Specialization for standard file descriptor files according to the posix standard.
Definition at line 58 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::open().
dd4hep_file() [6/7]
template<> DD4hep::dd4hep_file< TFile * >::dd4hep_file (handle_type fd, dd4hep_file_flags flags)
Specialization for the usage of TFile structures.
Definition at line 100 of file IoStreams.cpp.
dd4hep_file() [7/7]
template<> DD4hep::dd4hep_file< TFile * >::dd4hep_file (const char * fname, BOOST_IOS::openmode mode)
Specialization for the usage of TFile structures.
Definition at line 104 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::open().
Member Function Documentation
close() [1/3]
template<> void DD4hep::dd4hep_file< int >::close ()
Specialization for standard file descriptor files according to the posix standard.
Definition at line 74 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::close(), and DD4hep::dd4hep_file< T >::m_handle.
close() [2/3]
template<typename T > void DD4hep::dd4hep_file< T >::close ()
Referenced by DD4hep::dd4hep_file< T >::close(), and DD4hep::dd4hep_file< T >::is_open().
close() [3/3]
template<> void DD4hep::dd4hep_file< TFile * >::close ()
Specialization for the usage of TFile structures.
Definition at line 129 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::m_handle.
handle()
template<typename T > handle_type DD4hep::dd4hep_file< T >::handle () const inline
Definition at line 102 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::m_handle.
is_open()
template<typename T > bool DD4hep::dd4hep_file< T >::is_open () const inline
Definition at line 97 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::close(), DD4hep::dd4hep_file< T >::m_handle, DD4hep::dd4hep_file< T >::read(), s, DD4hep::dd4hep_file< T >::seek(), and DD4hep::dd4hep_file< T >::write().
open() [1/4]
template<> void DD4hep::dd4hep_file< int >::open (const char * path, BOOST_IOS::openmode mode)
Specialization for standard file descriptor files according to the posix standard.
Definition at line 48 of file IoStreams.cpp.
open() [2/4]
template<> void DD4hep::dd4hep_file< TFile * >::open (const char * path, BOOST_IOS::openmode mode)
Specialization for the usage of TFile structures.
Definition at line 80 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::m_handle.
open() [3/4]
template<typename T > void DD4hep::dd4hep_file< T >::open (handle_type fd, dd4hep_file_flags flags)
Referenced by DD4hep::dd4hep_file< T >::dd4hep_file(), DD4hep::dd4hep_file_source< T >::open(), and DD4hep::dd4hep_file_sink< T >::open().
open() [4/4]
template<typename T > void DD4hep::dd4hep_file< T >::open (const char * path, BOOST_IOS::openmode mode = BOOST_IOS::in|BOOST_IOS::out)
read() [1/3]
template<> std::streamsize DD4hep::dd4hep_file< int >::read (char_type * s, std::streamsize n)
Specialization for standard file descriptor files according to the posix standard.
Definition at line 62 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::m_handle.
read() [2/3]
template<typename T > std::streamsize DD4hep::dd4hep_file< T >::read (char_type * s, std::streamsize n)
Referenced by DD4hep::dd4hep_file< T >::is_open().
read() [3/3]
template<> std::streamsize DD4hep::dd4hep_file< TFile * >::read (char_type * s, std::streamsize n)
Specialization for the usage of TFile structures.
Definition at line 108 of file IoStreams.cpp.
References _p, and DD4hep::dd4hep_file< T >::m_handle.
seek() [1/3]
template<> std::streampos DD4hep::dd4hep_file< int >::seek (stream_offset off, BOOST_IOS::seekdir way)
Specialization for standard file descriptor files according to the posix standard.
Definition at line 70 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::m_handle.
seek() [2/3]
template<typename T > std::streampos DD4hep::dd4hep_file< T >::seek (stream_offset off, BOOST_IOS::seekdir way)
Referenced by DD4hep::dd4hep_file< T >::is_open().
seek() [3/3]
template<> std::streampos DD4hep::dd4hep_file< TFile * >::seek (stream_offset off, BOOST_IOS::seekdir way)
Specialization for the usage of TFile structures.
Definition at line 125 of file IoStreams.cpp.
References _p, and DD4hep::dd4hep_file< T >::m_handle.
write() [1/3]
template<> std::streamsize DD4hep::dd4hep_file< int >::write (const char_type * s, std::streamsize n)
Specialization for standard file descriptor files according to the posix standard.
Definition at line 66 of file IoStreams.cpp.
References DD4hep::dd4hep_file< T >::m_handle.
write() [2/3]
template<typename T > std::streamsize DD4hep::dd4hep_file< T >::write (const char_type * s, std::streamsize n)
Referenced by DD4hep::dd4hep_file< T >::is_open().
write() [3/3]
template<> std::streamsize DD4hep::dd4hep_file< TFile * >::write (const char_type * s, std::streamsize n)
Specialization for the usage of TFile structures.
Definition at line 121 of file IoStreams.cpp.
References _p, DD4hep::dd4hep_file< T >::m_handle, and s.
Friends And Related Function Documentation
dd4hep_file_sink< T >
template<typename T > friend class dd4hep_file_sink< T > friend
Definition at line 77 of file IoStreams.h.
dd4hep_file_source< T >
template<typename T > friend class dd4hep_file_source< T > friend
Definition at line 76 of file IoStreams.h.
Member Data Documentation
m_flag
template<typename T > dd4hep_file_flags DD4hep::dd4hep_file< T >::m_flag private
Definition at line 105 of file IoStreams.h.
m_handle
template<typename T > handle_type DD4hep::dd4hep_file< T >::m_handle private
Definition at line 104 of file IoStreams.h.
Referenced by DD4hep::dd4hep_file< T >::close(), DD4hep::dd4hep_file< T >::handle(), DD4hep::dd4hep_file< T >::is_open(), DD4hep::dd4hep_file< T >::open(), DD4hep::dd4hep_file< T >::read(), DD4hep::dd4hep_file< T >::seek(), and DD4hep::dd4hep_file< T >::write().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/IoStreams.h