DD4hep: DD4hep: DD4hep::DDSegmentation::SegmentationParameter Class Reference
DD4hep::DDSegmentation::SegmentationParameter Class Reference
Class to hold a segmentation parameter with its description.
#include <SegmentationParameter.h>
Public Types
enum UnitType { NoUnit, LengthUnit, AngleUnit }
Defines the parameter unit type (useful to convert to default set of units).
Public Member Functions
virtual ~SegmentationParameter ()
Destructor.
const std::string & name () const
Access to the parameter name.
const std::string & description () const
Access to the parameter description.
UnitType unitType () const
Access to the unit type.
virtual std::string type () const =0
Access to the parameter type.
virtual std::string value () const =0
Access to the parameter value in string representation.
virtual void setValue (const std::string &value)=0
Set the parameter value in string representation.
virtual std::string defaultValue () const =0
Access to the parameter default value in string representation.
bool isOptional () const
Check if this parameter is optional.
std::string toString () const
Printable version.
Protected Member Functions
SegmentationParameter (const std::string &nam, const std::string &desc, UnitType unitTyp=NoUnit, bool isOpt=false)
Default constructor used by derived classes.
Protected Attributes
std::string _name
The parameter name.
std::string _description
The parameter description.
UnitType _unitType
The unit type.
bool _isOptional
Store if parameter is optional.
Detailed Description
Class to hold a segmentation parameter with its description.
Definition at line 97 of file SegmentationParameter.h.
Member Enumeration Documentation
enum DD4hep::DDSegmentation::SegmentationParameter::UnitType
Defines the parameter unit type (useful to convert to default set of units).
Enumerator:
NoUnit
LengthUnit
AngleUnit
Definition at line 100 of file SegmentationParameter.h.
Constructor & Destructor Documentation
virtual DD4hep::DDSegmentation::SegmentationParameter::~SegmentationParameter () [inline, virtual]
Destructor.
Definition at line 104 of file SegmentationParameter.h.
DD4hep::DDSegmentation::SegmentationParameter::SegmentationParameter (const std::string & nam, const std::string & desc, UnitType unitTyp = NoUnit, bool isOpt = false) [inline, protected]
Default constructor used by derived classes.
Definition at line 141 of file SegmentationParameter.h.
Member Function Documentation
virtual std::string DD4hep::DDSegmentation::SegmentationParameter::defaultValue () const [pure virtual]
Access to the parameter default value in string representation.
Implemented in DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >, and DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >.
const std::string& DD4hep::DDSegmentation::SegmentationParameter::description () const [inline]
Access to the parameter description.
Definition at line 111 of file SegmentationParameter.h.
References _description.
bool DD4hep::DDSegmentation::SegmentationParameter::isOptional () const [inline]
Check if this parameter is optional.
Definition at line 127 of file SegmentationParameter.h.
References _isOptional.
const std::string& DD4hep::DDSegmentation::SegmentationParameter::name () const [inline]
Access to the parameter name.
Definition at line 107 of file SegmentationParameter.h.
References _name.
Referenced by DD4hep::DDSegmentation::Segmentation::setParameters(), and DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >::type().
virtual void DD4hep::DDSegmentation::SegmentationParameter::setValue (const std::string & value) [pure virtual]
Set the parameter value in string representation.
Implemented in DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >, and DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >.
std::string DD4hep::DDSegmentation::SegmentationParameter::toString () const [inline]
Printable version.
Definition at line 131 of file SegmentationParameter.h.
References _description, _name, s, and value().
virtual std::string DD4hep::DDSegmentation::SegmentationParameter::type () const [pure virtual]
Access to the parameter type.
Implemented in DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >, and DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >.
UnitType DD4hep::DDSegmentation::SegmentationParameter::unitType () const [inline]
Access to the unit type.
Definition at line 115 of file SegmentationParameter.h.
References _unitType.
virtual std::string DD4hep::DDSegmentation::SegmentationParameter::value () const [pure virtual]
Access to the parameter value in string representation.
Implemented in DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >, and DD4hep::DDSegmentation::TypedSegmentationParameter< std::vector< TYPE > >.
Referenced by DD4hep::DDSegmentation::Segmentation::setParameters(), and toString().
Member Data Documentation
std::string DD4hep::DDSegmentation::SegmentationParameter::_description [protected]
The parameter description.
Definition at line 148 of file SegmentationParameter.h.
Referenced by description(), and toString().
bool DD4hep::DDSegmentation::SegmentationParameter::_isOptional [protected]
Store if parameter is optional.
Definition at line 152 of file SegmentationParameter.h.
Referenced by isOptional().
std::string DD4hep::DDSegmentation::SegmentationParameter::_name [protected]
The parameter name.
Definition at line 146 of file SegmentationParameter.h.
Referenced by name(), and toString().
UnitType DD4hep::DDSegmentation::SegmentationParameter::_unitType [protected]
The unit type.
Definition at line 150 of file SegmentationParameter.h.
Referenced by unitType().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/SegmentationParameter.h