DD4hep: DD4hep: DD4hep::Simulation::Geant4TrackingPostAction Class Reference
DD4hep::Simulation::Geant4TrackingPostAction Class Reference
[DD4hep::Simulation components, classes and objects]
Default base class for all geant 4 tracking actions.
#include <Geant4TrackingPostAction.h>
Public Member Functions
Geant4TrackingPostAction (Geant4Context *context, const std::string &name="")
Standard constructor.
virtual ~Geant4TrackingPostAction ()
Default destructor.
void saveTrack (const G4Track *track)
virtual void begin (const G4Track *track)
Begin-of-tracking callback.
virtual void end (const G4Track *track)
End-of-tracking callback.
Protected Types
typedef std::vector< std::string > StringV
Protected Attributes
StringV m_requiredProcs
StringV m_ignoredProcs
bool m_storeMarkedTracks
Detailed Description
Default base class for all geant 4 tracking actions.
Author:
M.Frank
Version:
1.0
Definition at line 33 of file Geant4TrackingPostAction.h.
Member Typedef Documentation
typedef std::vector<std::string> DD4hep::Simulation::Geant4TrackingPostAction::StringV [protected]
Definition at line 35 of file Geant4TrackingPostAction.h.
Constructor & Destructor Documentation
Geant4TrackingPostAction::Geant4TrackingPostAction (Geant4Context * context, const std::string & name = "")
Standard constructor.
Definition at line 50 of file Geant4TrackingPostAction.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_ignoredProcs, m_requiredProcs, and m_storeMarkedTracks.
Geant4TrackingPostAction::~Geant4TrackingPostAction () [virtual]
Default destructor.
Definition at line 59 of file Geant4TrackingPostAction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4TrackingPostAction::begin (const G4Track * track) [virtual]
Begin-of-tracking callback.
Reimplemented from DD4hep::Simulation::Geant4TrackingAction.
Definition at line 64 of file Geant4TrackingPostAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::createTrajectory(), and DD4hep::Simulation::Geant4TrackingAction::trackMgr().
void Geant4TrackingPostAction::end (const G4Track * track) [virtual]
End-of-tracking callback.
Reimplemented from DD4hep::Simulation::Geant4TrackingAction.
Definition at line 77 of file Geant4TrackingPostAction.cpp.
References DD4hep::Simulation::Geant4TrackHandler::creatorProcess(), m_ignoredProcs, m_requiredProcs, m_storeMarkedTracks, saveTrack(), DD4hep::Simulation::Geant4TrackingAction::trackMgr(), and DD4hep::Simulation::Geant4Action::warning().
void Geant4TrackingPostAction::saveTrack (const G4Track * track)
Definition at line 102 of file Geant4TrackingPostAction.cpp.
Referenced by end().
Member Data Documentation
StringV DD4hep::Simulation::Geant4TrackingPostAction::m_ignoredProcs [protected]
Definition at line 37 of file Geant4TrackingPostAction.h.
Referenced by end(), and Geant4TrackingPostAction().
StringV DD4hep::Simulation::Geant4TrackingPostAction::m_requiredProcs [protected]
Definition at line 36 of file Geant4TrackingPostAction.h.
Referenced by end(), and Geant4TrackingPostAction().
bool DD4hep::Simulation::Geant4TrackingPostAction::m_storeMarkedTracks [protected]
Definition at line 38 of file Geant4TrackingPostAction.h.
Referenced by end(), and Geant4TrackingPostAction().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TrackingPostAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TrackingPostAction.cpp