DD4hep: DD4hep::View Class Reference
DD4hep::View Class Reference
class View View.h DDEve/View.h
#include <View.h>
Public Types
typedef Geometry::LCDD LCDD
typedef Geometry::DetElement DetElement
typedef Geometry::SensitiveDetector SensitiveDetector
typedef std::map< std::string, TEveElementList * > Topics
Public Member Functions
virtual TEveElement * ImportGeoElement (TEveElement *element, TEveElementList *list)
Call an element to a geometry element list.
virtual TEveElement * ImportGeoTopic (TEveElement *element, TEveElementList *list)
Call an element to a geometry element list.
virtual TEveElement * ImportEventElement (TEveElement *element, TEveElementList *list)
Call an element to a event element list.
View (Display *eve, const std::string &name)
Initializing constructor.
virtual ~View ()
Default destructor.
const std::string & name () const
Access to the view name/title.
const char * c_name () const
TEveViewer * viewer () const
Access to the Eve viewer.
bool showGlobal () const
Show global directory.
void setShowGlobal (bool value)
Set show globals.
virtual View & Build (TEveWindow *slot)
Build the view view and map it to the given slot.
virtual void Initialize ()
Initialize the view port.
virtual View & Map (TEveWindow *slot)
Map the view view to the slot.
virtual View & CreateScenes ()
Create the geometry and the event scene.
virtual TEveElementList * AddToGlobalItems (const std::string &nam)
Add the view to the global list of eve objects.
TEveScene * geoScene () const
Access to the Eve geometry scene.
virtual View & CreateGeoScene ()
Create the geometry scene.
virtual void ConfigureGeometryFromInfo ()
Configure a view with geo info. Used configuration if present.
virtual void ConfigureGeometryFromGlobal ()
Configure a single geometry view by default from the global geometry scene with all subdetectors.
virtual void ConfigureGeometry (const DisplayConfiguration::ViewConfig &config)
Configure a single geometry view.
virtual std::pair< bool, TEveElement * > CreateGeometry (DetElement de, const DisplayConfiguration::Config &cfg)
Create a new instance of the geometry of a sub-detector.
virtual std::pair< bool, TEveElement * > GetGlobalGeometry (DetElement de, const DisplayConfiguration::Config &cfg)
Access the global instance of the subdetector geometry.
virtual void ImportGeo (const std::string &topic, TEveElement *element)
Call to import geometry elements into topics.
virtual void ImportGeo (TEveElementList &topic, TEveElement *element)
Call to import geometry elements into topics.
virtual void ImportGeo (TEveElement *element)
Call to import geometry elements into the main geometry scene menu.
virtual void ImportGeoTopics (const std::string &title)
Call to import geometry topics. If title is empty, do not add to global item list.
virtual TEveElementList & GetGeoTopic (const std::string &name)
Access/Create an geometry topic by name.
TEveScene * eveScene () const
Access to the Eve event scene.
virtual View & CreateEventScene ()
Create the event scene.
virtual void ConfigureEventFromInfo ()
Configure a view with event info. Used configuration if present.
virtual void ConfigureEventFromGlobal ()
Configure an event view by default from the global event scene.
virtual void ConfigureEvent (const DisplayConfiguration::ViewConfig &config)
Configure a single event scene view.
virtual void ImportEvent (TEveElement *element)
Call to import event elements into the main event scene.
virtual void ImportEventTopics ()
Import event typics after creation.
ClassDef (View, 0)
Root implementation macro.
Protected Attributes
Display * m_eve
TEveViewer * m_view
Reference to the view.
TEveScene * m_geoScene
Reference to the geometry scene.
TEveScene * m_eveScene
Reference to the event scene.
TEveElementList * m_global
Reference to the global item (if added.
const DisplayConfiguration::ViewConfig * m_config
std::string m_name
The name of the view.
Topics m_geoTopics
Topics m_eveTopics
bool m_showGlobal
Detailed Description
class View View.h DDEve/View.h
Definition at line 46 of file View.h.
Member Typedef Documentation
DetElement
typedef Geometry::DetElement DD4hep::View::DetElement
Definition at line 49 of file View.h.
LCDD
typedef Geometry::LCDD DD4hep::View::LCDD
Definition at line 48 of file View.h.
SensitiveDetector
typedef Geometry::SensitiveDetector DD4hep::View::SensitiveDetector
Definition at line 50 of file View.h.
Topics
typedef std::map<std::string, TEveElementList*> DD4hep::View::Topics
Definition at line 51 of file View.h.
Constructor & Destructor Documentation
View()
View::View (Display * eve, const std::string & name)
Initializing constructor.
Definition at line 41 of file View.cpp.
References DD4hep::Display::GetViewConfiguration(), DD4hep::InstanceCount::increment(), m_config, m_eve, and m_name.
~View()
View::~View () virtual
Default destructor.
Definition at line 49 of file View.cpp.
References DD4hep::InstanceCount::decrement(), m_eve, m_eveScene, m_geoScene, m_geoTopics, m_global, and DD4hep::Display::UnregisterEvents().
Member Function Documentation
AddToGlobalItems()
TEveElementList * View::AddToGlobalItems (const std::string & nam) virtual
Add the view to the global list of eve objects.
Definition at line 83 of file View.cpp.
References eveScene(), geoScene(), m_eve, m_eveScene, m_geoScene, m_global, m_showGlobal, and DD4hep::Display::manager().
Referenced by DD4hep::Calo3DProjection::Build(), DD4hep::Projection::CreateRhoPhiProjection(), DD4hep::Projection::CreateRhoZProjection(), ImportGeoTopics(), and setShowGlobal().
Build()
View & View::Build (TEveWindow * slot) virtual
Build the view view and map it to the given slot.
Build the projection view and map it to the given slot.
Reimplemented in DD4hep::CaloLego, DD4hep::Calo2DProjection, DD4hep::Calo3DProjection, DD4hep::MultiView, DD4hep::View3D, DD4hep::RhoPhiProjection, and DD4hep::RhoZProjection.
Definition at line 60 of file View.cpp.
Referenced by DD4hep::ViewMenu::BuildView(), and setShowGlobal().
c_name()
const char* DD4hep::View::c_name () const inline
Definition at line 86 of file View.h.
Referenced by ConfigureEventFromInfo(), ConfigureGeometry(), ConfigureGeometryFromInfo(), and ImportGeoTopics().
ClassDef()
DD4hep::View::ClassDef (View , 0)
Root implementation macro.
Referenced by setShowGlobal().
ConfigureEvent()
void View::ConfigureEvent (const DisplayConfiguration::ViewConfig & config) virtual
Configure a single event scene view.
Configure a single view.
Reimplemented in DD4hep::CaloLego, and DD4hep::Calo2DProjection.
Definition at line 245 of file View.cpp.
References DD4hep::DisplayConfiguration::CALODATA, DD4hep::Geometry::DetElement::children(), DD4hep::DisplayConfiguration::COLLECTION, DD4hep::DisplayConfiguration::Config::data, DD4hep::DisplayConfiguration::Config::Values::defaults, DD4hep::DisplayConfiguration::DETELEMENT, ImportEvent(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Display::lcdd(), m_eve, m_eveScene, DD4hep::Display::manager(), DD4hep::DisplayConfiguration::Config::name, DD4hep::Handle< T >::name(), DD4hep::printout(), DD4hep::Geometry::SensitiveDetector::readout(), DD4hep::Geometry::LCDD::sensitiveDetector(), DD4hep::DisplayConfiguration::Defaults::show_evt, DD4hep::DisplayConfiguration::ViewConfig::subdetectors, DD4hep::DisplayConfiguration::Config::type, and DD4hep::Geometry::LCDD::world().
Referenced by ConfigureEventFromInfo(), and setShowGlobal().
ConfigureEventFromGlobal()
void View::ConfigureEventFromGlobal () virtual
Configure an event view by default from the global event scene.
Definition at line 238 of file View.cpp.
References ImportEvent(), m_eve, and DD4hep::Display::manager().
Referenced by ConfigureEventFromInfo(), and setShowGlobal().
ConfigureEventFromInfo()
void View::ConfigureEventFromInfo () virtual
Configure a view with event info. Used configuration if present.
Configure the adding of event data.
Definition at line 231 of file View.cpp.
References c_name(), ConfigureEvent(), ConfigureEventFromGlobal(), ImportEventTopics(), DD4hep::INFO, m_config, and DD4hep::printout().
Referenced by DD4hep::ViewMenu::BuildView(), and setShowGlobal().
ConfigureGeometry()
void View::ConfigureGeometry (const DisplayConfiguration::ViewConfig & config) virtual
Configure a single geometry view.
Reimplemented in DD4hep::CaloLego, and DD4hep::Calo2DProjection.
Definition at line 160 of file View.cpp.
References c_name(), DD4hep::Display::CalodataContext::calo3D, DD4hep::DisplayConfiguration::CALODATA, DD4hep::Geometry::DetElement::children(), DD4hep::Display::CalodataContext::config, CreateGeometry(), DD4hep::DisplayConfiguration::Config::data, DD4hep::Annotation::DefaultMargin(), DD4hep::DisplayConfiguration::Config::Values::defaults, DD4hep::Annotation::DefaultTextSize(), DD4hep::DisplayConfiguration::DETELEMENT, e, DD4hep::Display::GetCaloHistogram(), GetGeoTopic(), GetGlobalGeometry(), ImportGeo(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Display::lcdd(), DD4hep::DisplayConfiguration::Defaults::load_geo, m_eve, m_view, DD4hep::Display::manager(), name(), DD4hep::DisplayConfiguration::Config::name, DD4hep::printout(), DD4hep::Geometry::LCDD::sensitiveDetector(), DD4hep::Display::CalodataContext::slice, DD4hep::DisplayConfiguration::ViewConfig::subdetectors, DD4hep::DisplayConfiguration::Config::type, DD4hep::DisplayConfiguration::Config::use, viewer(), and DD4hep::Geometry::LCDD::world().
Referenced by ConfigureGeometryFromInfo(), and setShowGlobal().
ConfigureGeometryFromGlobal()
void View::ConfigureGeometryFromGlobal () virtual
Configure a single geometry view by default from the global geometry scene with all subdetectors.
Configure a single geometry view by default from the global geometry scene.
Definition at line 147 of file View.cpp.
References GetGeoTopic(), DD4hep::Display::GetGeoTopic(), ImportGeo(), and m_eve.
Referenced by ConfigureGeometryFromInfo(), and setShowGlobal().
ConfigureGeometryFromInfo()
void View::ConfigureGeometryFromInfo () virtual
Configure a view with geo info. Used configuration if present.
Configure a view using the view's name and a proper ViewConfiguration if present.
Definition at line 140 of file View.cpp.
References c_name(), ConfigureGeometry(), ConfigureGeometryFromGlobal(), ImportGeoTopics(), DD4hep::INFO, m_config, name(), and DD4hep::printout().
Referenced by DD4hep::ViewMenu::BuildView(), and setShowGlobal().
CreateEventScene()
View & View::CreateEventScene () virtual
Create the event scene.
Definition at line 315 of file View.cpp.
References m_eve, m_eveScene, m_name, and DD4hep::Display::manager().
Referenced by CreateScenes(), and setShowGlobal().
CreateGeometry()
pair< bool, TEveElement * > View::CreateGeometry (DetElement de, const DisplayConfiguration::Config & cfg) virtual
Create a new instance of the geometry of a sub-detector.
Definition at line 133 of file View.cpp.
References DD4hep::DisplayConfiguration::Config::data, DD4hep::DisplayConfiguration::Config::Values::defaults, GetGeoTopic(), DD4hep::Handle< T >::isValid(), DD4hep::Display::lcdd(), DD4hep::DisplayConfiguration::Defaults::load_geo, DD4hep::Utilities::LoadDetElement(), m_eve, DD4hep::Handle< T >::name(), and DD4hep::Geometry::LCDD::sensitiveDetector().
Referenced by ConfigureGeometry(), and setShowGlobal().
CreateGeoScene()
View & View::CreateGeoScene () virtual
Create the geometry scene.
Definition at line 325 of file View.cpp.
References m_eve, m_geoScene, m_name, and DD4hep::Display::manager().
Referenced by CreateScenes(), and setShowGlobal().
CreateScenes()
View & View::CreateScenes () virtual
Create the geometry and the event scene.
Definition at line 307 of file View.cpp.
References CreateEventScene(), and CreateGeoScene().
Referenced by DD4hep::RhoPhiProjection::Build(), DD4hep::RhoZProjection::Build(), DD4hep::MultiView::Build(), DD4hep::View3D::Build(), DD4hep::Calo3DProjection::Build(), and setShowGlobal().
eveScene()
TEveScene* DD4hep::View::eveScene () const inline
Access to the Eve event scene.
Manipulation of the event scene
Definition at line 142 of file View.h.
Referenced by AddToGlobalItems(), Initialize(), and setShowGlobal().
geoScene()
TEveScene* DD4hep::View::geoScene () const inline
Access to the Eve geometry scene.
Manipulation of the geometry scene
Definition at line 108 of file View.h.
Referenced by AddToGlobalItems(), Initialize(), and setShowGlobal().
GetGeoTopic()
TEveElementList & View::GetGeoTopic (const std::string & name) virtual
Access/Create an geometry topic by name.
Access/Create a topic by name.
Definition at line 296 of file View.cpp.
References m_geoTopics.
Referenced by ConfigureGeometry(), ConfigureGeometryFromGlobal(), CreateGeometry(), DD4hep::Projection::ImportElement(), ImportGeo(), and setShowGlobal().
GetGlobalGeometry()
pair< bool, TEveElement * > View::GetGlobalGeometry (DetElement de, const DisplayConfiguration::Config & cfg) virtual
Access the global instance of the subdetector geometry.
Definition at line 124 of file View.cpp.
References DD4hep::Display::GetGeoTopic(), DD4hep::Handle< T >::isValid(), DD4hep::Display::lcdd(), m_eve, DD4hep::Handle< T >::name(), and DD4hep::Geometry::LCDD::sensitiveDetector().
Referenced by ConfigureGeometry(), and setShowGlobal().
ImportEvent()
void View::ImportEvent (TEveElement * element) virtual
Call to import event elements into the main event scene.
Definition at line 289 of file View.cpp.
References ImportEventElement(), and m_eveScene.
Referenced by ConfigureEvent(), ConfigureEventFromGlobal(), and setShowGlobal().
ImportEventElement()
TEveElement * View::ImportEventElement (TEveElement * element, TEveElementList * list) virtual
Call an element to a event element list.
Reimplemented in DD4hep::Projection.
Definition at line 109 of file View.cpp.
References DD4hep::Utilities::GetName(), DD4hep::INFO, DD4hep::printout(), and s.
Referenced by ImportEvent().
ImportEventTopics()
void View::ImportEventTopics () virtual
Import event typics after creation.
Definition at line 285 of file View.cpp.
Referenced by ConfigureEventFromInfo(), and setShowGlobal().
ImportGeo() [1/3]
void View::ImportGeo (const std::string & topic, TEveElement * element) virtual
Call to import geometry elements into topics.
Call to import geometry elements by topic.
Definition at line 216 of file View.cpp.
References GetGeoTopic(), and ImportGeoElement().
Referenced by ConfigureGeometry(), ConfigureGeometryFromGlobal(), and setShowGlobal().
ImportGeo() [2/3]
void View::ImportGeo (TEveElementList & topic, TEveElement * element) virtual
Call to import geometry elements into topics.
Definition at line 221 of file View.cpp.
References ImportGeoElement().
ImportGeo() [3/3]
void View::ImportGeo (TEveElement * element) virtual
Call to import geometry elements into the main geometry scene menu.
Call to import geometry elements.
Definition at line 226 of file View.cpp.
References ImportGeoElement(), and m_geoScene.
ImportGeoElement()
TEveElement * View::ImportGeoElement (TEveElement * element, TEveElementList * list) virtual
Call an element to a geometry element list.
Call an element to a event element list.
Reimplemented in DD4hep::Projection.
Definition at line 94 of file View.cpp.
References s.
Referenced by ImportGeo(), and ImportGeoTopic().
ImportGeoTopic()
TEveElement * View::ImportGeoTopic (TEveElement * element, TEveElementList * list) virtual
Call an element to a geometry element list.
Reimplemented in DD4hep::Projection.
Definition at line 104 of file View.cpp.
References ImportGeoElement().
Referenced by ImportGeoTopics().
ImportGeoTopics()
void View::ImportGeoTopics (const std::string & title) virtual
Call to import geometry topics. If title is empty, do not add to global item list.
Call to import geometry topics.
Reimplemented in DD4hep::CaloLego, and DD4hep::Calo2DProjection.
Definition at line 206 of file View.cpp.
References AddToGlobalItems(), c_name(), ImportGeoTopic(), DD4hep::INFO, m_geoScene, m_geoTopics, and DD4hep::printout().
Referenced by ConfigureGeometryFromInfo(), and setShowGlobal().
Initialize()
void View::Initialize () virtual
Initialize the view port.
Update color set
Definition at line 65 of file View.cpp.
References eveScene(), geoScene(), m_eve, DD4hep::Display::manager(), and viewer().
Referenced by DD4hep::ViewMenu::BuildView(), and setShowGlobal().
Map()
View & View::Map (TEveWindow * slot) virtual
Map the view view to the slot.
Map the projection view to the slot.
Reimplemented in DD4hep::Projection.
Definition at line 335 of file View.cpp.
References m_eve, m_eveScene, m_geoScene, m_name, m_view, and DD4hep::Display::manager().
Referenced by DD4hep::MultiView::Build(), DD4hep::View3D::Build(), DD4hep::Calo3DProjection::Build(), DD4hep::Projection::Map(), and setShowGlobal().
name()
const std::string& DD4hep::View::name () const inline
Access to the view name/title.
Definition at line 85 of file View.h.
References m_name.
Referenced by DD4hep::Calo3DProjection::Build(), ConfigureGeometry(), ConfigureGeometryFromInfo(), DD4hep::Projection::CreateRhoPhiProjection(), DD4hep::Projection::CreateRhoZProjection(), and setShowGlobal().
setShowGlobal()
void DD4hep::View::setShowGlobal (bool value) inline
Set show globals.
Definition at line 92 of file View.h.
References AddToGlobalItems(), Build(), ClassDef(), ConfigureEvent(), ConfigureEventFromGlobal(), ConfigureEventFromInfo(), ConfigureGeometry(), ConfigureGeometryFromGlobal(), ConfigureGeometryFromInfo(), CreateEventScene(), CreateGeometry(), CreateGeoScene(), CreateScenes(), eveScene(), geoScene(), GetGeoTopic(), GetGlobalGeometry(), ImportEvent(), ImportEventTopics(), ImportGeo(), ImportGeoTopics(), Initialize(), m_eveScene, m_geoScene, Map(), name(), and slot.
showGlobal()
bool DD4hep::View::showGlobal () const inline
Show global directory.
Definition at line 90 of file View.h.
References m_showGlobal.
viewer()
TEveViewer* DD4hep::View::viewer () const inline
Access to the Eve viewer.
Definition at line 88 of file View.h.
References m_view.
Referenced by ConfigureGeometry(), and Initialize().
Member Data Documentation
m_config
const DisplayConfiguration::ViewConfig* DD4hep::View::m_config protected
Definition at line 62 of file View.h.
Referenced by ConfigureEventFromInfo(), ConfigureGeometryFromInfo(), and View().
m_eve
Display* DD4hep::View::m_eve protected
Definition at line 53 of file View.h.
Referenced by AddToGlobalItems(), DD4hep::MultiView::Build(), ConfigureEvent(), ConfigureEventFromGlobal(), ConfigureGeometry(), ConfigureGeometryFromGlobal(), CreateEventScene(), CreateGeometry(), CreateGeoScene(), GetGlobalGeometry(), Initialize(), Map(), View(), and ~View().
m_eveScene
TEveScene* DD4hep::View::m_eveScene protected
Reference to the event scene.
Definition at line 59 of file View.h.
Referenced by AddToGlobalItems(), ConfigureEvent(), CreateEventScene(), DD4hep::Projection::ImportElement(), ImportEvent(), Map(), setShowGlobal(), and ~View().
m_eveTopics
Topics DD4hep::View::m_eveTopics protected
Definition at line 68 of file View.h.
m_geoScene
TEveScene* DD4hep::View::m_geoScene protected
Reference to the geometry scene.
Definition at line 57 of file View.h.
Referenced by DD4hep::Projection::AddAxis(), AddToGlobalItems(), CreateGeoScene(), DD4hep::Projection::ImportElement(), ImportGeo(), ImportGeoTopics(), Map(), setShowGlobal(), and ~View().
m_geoTopics
Topics DD4hep::View::m_geoTopics protected
Definition at line 67 of file View.h.
Referenced by GetGeoTopic(), DD4hep::Projection::ImportElement(), ImportGeoTopics(), and ~View().
m_global
TEveElementList* DD4hep::View::m_global protected
Reference to the global item (if added.
Definition at line 61 of file View.h.
Referenced by AddToGlobalItems(), and ~View().
m_name
std::string DD4hep::View::m_name protected
The name of the view.
Definition at line 65 of file View.h.
Referenced by DD4hep::MultiView::Build(), CreateEventScene(), CreateGeoScene(), Map(), name(), and View().
m_showGlobal
bool DD4hep::View::m_showGlobal protected
Definition at line 69 of file View.h.
Referenced by AddToGlobalItems(), and showGlobal().
m_view
TEveViewer* DD4hep::View::m_view protected
Reference to the view.
Definition at line 55 of file View.h.
Referenced by ConfigureGeometry(), DD4hep::Projection::Map(), Map(), and viewer().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/View.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/View.cpp