DD4hep: DD4hep::Geometry::Author Class Reference
DD4hep::Geometry::Author Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing an author entity.
#include <Objects.h>
Public Types
typedef NamedObject Object
Definition of the implementation type.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Author ()
Default constructor.
Author (const Author &e)
Constructorto be used for assignment from a handle.
template<typename Q >
Author (const Handle< Q > &e)
Constructor to be used when assigning already valid handle.
Author (LCDD &doc)
Constructor to be used when creating a new object.
Author & operator= (const Author &e)
Assignment operator.
std::string authorName () const
Access the auhor's name.
void setAuthorName (const std::string &nam)
Set the author's name.
std::string authorEmail () const
Access the auhor's email address.
void setAuthorEmail (const std::string &addr)
Set the author's email address.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing an author entity.
Author
M.Frank
Version
1.0
Definition at line 124 of file Objects.h.
Member Typedef Documentation
Object
typedef NamedObject DD4hep::Geometry::Author::Object
Definition of the implementation type.
Definition at line 127 of file Objects.h.
Constructor & Destructor Documentation
Author() [1/4]
DD4hep::Geometry::Author::Author () inline
Default constructor.
Definition at line 129 of file Objects.h.
Referenced by Author().
Author() [2/4]
DD4hep::Geometry::Author::Author (const Author & e) inline
Constructorto be used for assignment from a handle.
Definition at line 133 of file Objects.h.
Author() [3/4]
template<typename Q > DD4hep::Geometry::Author::Author (const Handle< Q > & e) inline
Constructor to be used when assigning already valid handle.
Definition at line 138 of file Objects.h.
References Author().
Author() [4/4]
Author::Author (LCDD & doc)
Constructor to be used when creating a new object.
Constructor to be used when creating a new DOM tree.
Definition at line 39 of file Objects.cpp.
Member Function Documentation
authorEmail()
std::string Author::authorEmail () const
Access the auhor's email address.
Definition at line 54 of file Objects.cpp.
Referenced by operator=().
authorName()
std::string Author::authorName () const
Access the auhor's name.
Definition at line 44 of file Objects.cpp.
Referenced by operator=().
operator=()
Author& DD4hep::Geometry::Author::operator= (const Author & e) inline
Assignment operator.
Definition at line 144 of file Objects.h.
References authorEmail(), authorName(), DD4hep::Handle< T >::m_element, setAuthorEmail(), and setAuthorName().
Referenced by DD4hep::Geometry::Limit::Limit().
setAuthorEmail()
void Author::setAuthorEmail (const std::string & addr)
Set the author's email address.
Definition at line 59 of file Objects.cpp.
Referenced by operator=().
setAuthorName()
void Author::setAuthorName (const std::string & nam)
Set the author's name.
Definition at line 49 of file Objects.cpp.
Referenced by operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp