DD4hep: DD4hep::Simulation::Geant4TCUserParticleHandler Class Reference
DD4hep::Simulation::Geant4TCUserParticleHandler Class Reference
Rejects to keep particles, which are created outside a tracking cylinder.
Public Member Functions
Geant4TCUserParticleHandler (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4TCUserParticleHandler ()
Default destructor.
virtual void end (const G4Track *track, Particle &particle)
Post-track action callback.
virtual void end (const G4Event *event)
Post-event action callback: avoid warning (...) was hidden [-Woverloaded-virtual].
Public Member Functions inherited from DD4hep::Simulation::Geant4UserParticleHandler
Geant4UserParticleHandler (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4UserParticleHandler ()
Default destructor.
virtual void generate (G4Event *event, Geant4ParticleHandler *handler)
Event generation action callback.
virtual void begin (const G4Event *event)
Pre-event action callback.
virtual void step (const G4Step *step, G4SteppingManager *mgr, Particle &particle)
User stepping callback.
virtual void begin (const G4Track *track, Particle &particle)
Pre-track action callback.
virtual bool keepParticle (Particle &particle)
Callback to be answered if the particle MUST be kept during recombination step.
virtual void combine (Particle &to_be_deleted, Particle &remaining_parent)
Callback when parent should be combined.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Private Attributes
double m_zTracker
double m_rTracker
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4UserParticleHandler
typedef Geant4Particle Particle
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes inherited from DD4hep::Simulation::Geant4UserParticleHandler
double m_kinEnergyCut
Property: Energy cut below which particles are not collected, but assigned to the parent.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Detailed Description
Rejects to keep particles, which are created outside a tracking cylinder.
Geant4TCUserParticleHandler
TC stands for TrackingCylinder ;-)
Author
M.Frank
Version
1.0
Definition at line 35 of file Geant4TCUserParticleHandler.cpp.
Constructor & Destructor Documentation
Geant4TCUserParticleHandler()
Geant4TCUserParticleHandler::Geant4TCUserParticleHandler (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 82 of file Geant4TCUserParticleHandler.cpp.
Referenced by ~Geant4TCUserParticleHandler().
~Geant4TCUserParticleHandler()
virtual DD4hep::Simulation::Geant4TCUserParticleHandler::~Geant4TCUserParticleHandler () inline virtual
Default destructor.
Definition at line 42 of file Geant4TCUserParticleHandler.cpp.
References DECLARE_GEANT4ACTION, DD4hep::Simulation::Geant4Action::declareProperty(), end(), Geant4TCUserParticleHandler(), DD4hep::Simulation::Geant4UserParticleHandler::Geant4UserParticleHandler(), m_rTracker, and m_zTracker.
Member Function Documentation
end() [1/2]
void Geant4TCUserParticleHandler::end (const G4Track * track, Particle & particle) virtual
Post-track action callback.
Allow the user to force the particle handling in the post track action set the reason mask to NULL in order to drop the particle. The parent's reasoning mask will be or'ed with the particle's mask to preserve the MC truth for the hit creation. The default implementation is empty.
Note: The particle passed is a temporary and will be copied if kept.
Reimplemented from DD4hep::Simulation::Geant4UserParticleHandler.
Definition at line 90 of file Geant4TCUserParticleHandler.cpp.
References DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, DD4hep::Simulation::G4PARTICLE_SIM_BACKSCATTER, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_CALO, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_TRACKER, DD4hep::Simulation::G4PARTICLE_SIM_LEFT_DETECTOR, DD4hep::ReferenceBitMask< T >::isSet(), m_rTracker, m_zTracker, DD4hep::Simulation::Geant4Particle::reason, DD4hep::ReferenceBitMask< T >::set(), DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
Referenced by ~Geant4TCUserParticleHandler().
end() [2/2]
void Geant4TCUserParticleHandler::end (const G4Event * event) virtual
Post-event action callback: avoid warning (...) was hidden [-Woverloaded-virtual].
Post-event action callback.
Reimplemented from DD4hep::Simulation::Geant4UserParticleHandler.
Definition at line 138 of file Geant4TCUserParticleHandler.cpp.
Member Data Documentation
m_rTracker
double DD4hep::Simulation::Geant4TCUserParticleHandler::m_rTracker private
Definition at line 36 of file Geant4TCUserParticleHandler.cpp.
Referenced by end(), and ~Geant4TCUserParticleHandler().
m_zTracker
double DD4hep::Simulation::Geant4TCUserParticleHandler::m_zTracker private
Definition at line 36 of file Geant4TCUserParticleHandler.cpp.
Referenced by end(), and ~Geant4TCUserParticleHandler().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4TCUserParticleHandler.cpp