DD4hep: DD4hep::Geometry::DetElementObject Class Reference
DD4hep::Geometry::DetElementObject Class Reference
DD4hep classes and objects | DD4hep::Geometry components, classes and objects
Data class with properties of a detector element.
#include <DetectorInterna.h>
Public Types
enum DetFlags {
HAVE_WORLD_TRAFO = 1<<0, HAVE_PARENT_TRAFO = 1<<1, HAVE_REFERENCE_TRAFO = 1<<2, HAVE_SENSITIVE_DETECTOR = 1<<29,
IS_TOP_LEVEL_DETECTOR = 1<<30, HAVE_OTHER = 1<<31
}
typedef DetElement::destruct_t destruct_t
typedef DetElement::copy_t copy_t
typedef DetElement::Children Children
typedef DetElement::Extensions Extensions
typedef std::pair< Callback, unsigned long > UpdateCall
typedef std::vector< UpdateCall > UpdateCallbacks
typedef Conditions::Container ConditionsContainer
typedef Conditions::Condition Condition
typedef Alignments::Alignment Alignment
typedef Alignments::Container AlignmentsContainer
Public Types inherited from DD4hep::ObjectExtensions
typedef std::map< const std::type_info *, void * > Extensions
Definition of the extension type.
typedef void *(* copy_t) (const void *, void *arg)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< const std::type_info *, Entry > ExtensionMap
Public Member Functions
const TGeoHMatrix & worldTransformation ()
Create cached matrix to transform to world coordinates.
const TGeoHMatrix & parentTransformation ()
Create cached matrix to transform to parent coordinates.
const TGeoHMatrix & referenceTransformation ()
Create cached matrix to transform to reference coordinates.
void removeAtUpdate (unsigned int type, void *pointer)
Remove callback from object.
void update (unsigned int tags, void *param)
Trigger update callbacks.
void revalidate (TGeoHMatrix *parent_world_trafo)
Revalidate the caches.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Member Functions inherited from DD4hep::ObjectExtensions
ObjectExtensions (const std::type_info &parent_type)
Default constructor.
ObjectExtensions (const ObjectExtensions &copy)=delete
Copy constructor.
virtual ~ObjectExtensions ()
Default destructor.
ObjectExtensions & operator= (const ObjectExtensions &copy)=delete
Assignment operator.
void move (ObjectExtensions &copy)
Move extensions to target object.
void clear (bool destroy=true)
Clear all extensions.
void copyFrom (const Extensions &ext, void *arg)
Copy object extensions from another object. Hosting type must be identical!
void * addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
void * removeExtension (const std::type_info &info, bool destroy)
Remove an existing extension object from the instance.
void * extension (const std::type_info &info, bool alert) const
Access an existing extension object from the detector element.
void * extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Public Attributes
unsigned int magic
Magic number to ensure data integrity.
unsigned int flag
Flag to remember internally calculated quatities.
int id
Unique integer identifier of the detector instance.
int combineHits
Flag to process hits.
unsigned int typeFlag
Flag to encode detector types.
int level
Hierarchical level within the detector description.
unsigned int key
Access hash key of this detector element (Only valid once geometry is closed!)
std::string path
Full path to this detector element. May be invalid.
std::string placementPath
The path to the placement of the detector element (if placed)
PlacedVolume idealPlace
The subdetector placement corresponding to the ideal detector element's volume.
PlacedVolume placement
The subdetector placement corresponding to the actual detector element's volume.
VolumeID volumeID
The cached VolumeID of this subdetector element.
World privateWorld
Reference to the parent element.
DetElement parent
Reference to the parent element.
DetElement reference
Reference element for stored transformations.
Children children
The array of children.
UpdateCallbacks updateCalls
Placeholder for structure with update callbacks.
Alignment nominal
Basic ideal/nominal detector element alignment entry.
Alignment survey
Basic detector element alignment entry containing the survey data.
AlignmentsContainer alignments
The detector elements alignments access.
ConditionsContainer conditions
The detector elements conditions access.
Ref_t global_alignment
Global alignment data.
std::vector< Alignment > volume_alignments
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
std::vector< Alignment > volume_surveys
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
TGeoHMatrix worldTrafo
Intermediate buffer to store the transformation to the world coordination system.
TGeoHMatrix parentTrafo
Intermediate buffer to store the transformation to the parent detector element.
TGeoHMatrix * referenceTrafo
Intermediate buffer for the transformation to an arbitrary DetElement.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Public Attributes inherited from DD4hep::ObjectExtensions
Extensions extensions
The extensions object.
ExtensionMap * extensionMap
Pointer to the extension map.
World i_access_world ()
Resolve the world object. Internal use ONLY.
DetElementObject (const std::string &nam, int ident)
Initializing constructor.
DetElementObject ()
Default constructor.
virtual ~DetElementObject ()
Internal object destructor: release extension object(s)
virtual DetElementObject * clone (int new_id, int flag) const
Deep object copy to replicate DetElement trees e.g. for reflection.
World world ()
Access to the world object. Only possible once the geometry is closed.
ConditionsContainer assign_conditions ()
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::ObjectExtensions
static void _noDelete (void *)
Function to be passed as dtor if object should NOT be deleted!
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Detailed Description
Data class with properties of a detector element.
Author
M.Frank
Version
1.0
Definition at line 84 of file DetectorInterna.h.
Member Typedef Documentation
Alignment
typedef Alignments::Alignment DD4hep::Geometry::DetElementObject::Alignment
Definition at line 97 of file DetectorInterna.h.
AlignmentsContainer
typedef Alignments::Container DD4hep::Geometry::DetElementObject::AlignmentsContainer
Definition at line 98 of file DetectorInterna.h.
Children
typedef DetElement::Children DD4hep::Geometry::DetElementObject::Children
Definition at line 91 of file DetectorInterna.h.
Condition
typedef Conditions::Condition DD4hep::Geometry::DetElementObject::Condition
Definition at line 96 of file DetectorInterna.h.
ConditionsContainer
typedef Conditions::Container DD4hep::Geometry::DetElementObject::ConditionsContainer
Definition at line 95 of file DetectorInterna.h.
copy_t
typedef DetElement::copy_t DD4hep::Geometry::DetElementObject::copy_t
Definition at line 89 of file DetectorInterna.h.
destruct_t
typedef DetElement::destruct_t DD4hep::Geometry::DetElementObject::destruct_t
Definition at line 88 of file DetectorInterna.h.
Extensions
typedef DetElement::Extensions DD4hep::Geometry::DetElementObject::Extensions
Definition at line 92 of file DetectorInterna.h.
UpdateCall
typedef std::pair<Callback,unsigned long> DD4hep::Geometry::DetElementObject::UpdateCall
Definition at line 93 of file DetectorInterna.h.
UpdateCallbacks
typedef std::vector<UpdateCall> DD4hep::Geometry::DetElementObject::UpdateCallbacks
Definition at line 94 of file DetectorInterna.h.
Member Enumeration Documentation
DetFlags
enum DD4hep::Geometry::DetElementObject::DetFlags
Enumerator
HAVE_WORLD_TRAFO
HAVE_PARENT_TRAFO
HAVE_REFERENCE_TRAFO
HAVE_SENSITIVE_DETECTOR
IS_TOP_LEVEL_DETECTOR
HAVE_OTHER
Definition at line 100 of file DetectorInterna.h.
Constructor & Destructor Documentation
DetElementObject() [1/2]
DetElementObject::DetElementObject (const std::string & nam, int ident)
Initializing constructor.
Definition at line 75 of file DetectorInterna.cpp.
References id, DD4hep::InstanceCount::increment(), DD4hep::printout(), DD4hep::NamedObject::SetName(), and DD4hep::VERBOSE.
DetElementObject() [2/2]
DetElementObject::DetElementObject ()
Default constructor.
Definition at line 64 of file DetectorInterna.cpp.
References DD4hep::InstanceCount::increment(), DD4hep::printout(), and DD4hep::VERBOSE.
Referenced by clone().
~DetElementObject()
DetElementObject::~DetElementObject () virtual
Internal object destructor: release extension object(s)
Definition at line 87 of file DetectorInterna.cpp.
References alignments, children, DD4hep::ObjectExtensions::clear(), DD4hep::Handle< T >::clear(), conditions, DD4hep::InstanceCount::decrement(), DD4hep::deletePtr(), DD4hep::destroyHandle(), DD4hep::destroyHandles(), idealPlace, nominal, parent, placement, referenceTrafo, and survey.
Member Function Documentation
assign_conditions()
Conditions::Container DetElementObject::assign_conditions ()
Definition at line 290 of file DetectorInterna.cpp.
References DD4hep::Handle< T >::assign(), conditions, and DD4hep::Handle< T >::isValid().
Referenced by DD4hep::Conditions::DetConditions::conditions().
clone()
DetElementObject * DetElementObject::clone (int new_id, int flag) const virtual
Deep object copy to replicate DetElement trees e.g. for reflection.
Definition at line 104 of file DetectorInterna.cpp.
References alignments, children, clone(), combineHits, conditions, DD4hep::Geometry::DetElement::COPY_PLACEMENT, DetElementObject(), DD4hep::ObjectExtensions::extensions, flag, DD4hep::NamedObject::GetName(), DD4hep::NamedObject::GetTitle(), id, idealPlace, key, level, nominal, parent, dd4hep::pc, placement, placementPath, survey, and typeFlag.
Referenced by clone(), and DD4hep::Geometry::DetElement::clone().
i_access_world()
World DetElementObject::i_access_world () private
Resolve the world object. Internal use ONLY.
Access to the world object. Only possible once the geometry is closed.
Definition at line 144 of file DetectorInterna.cpp.
References DD4hep::Handle< T >::isValid(), parent, privateWorld, DD4hep::Handle< T >::ptr(), and world().
parentTransformation()
const TGeoHMatrix & DetElementObject::parentTransformation ()
Create cached matrix to transform to parent coordinates.
Definition at line 168 of file DetectorInterna.cpp.
References flag, HAVE_PARENT_TRAFO, parent, parentTrafo, DD4hep::Geometry::DetectorTools::placementPath(), and DD4hep::Geometry::DetectorTools::placementTrafo().
Referenced by revalidate().
referenceTransformation()
const TGeoHMatrix & DetElementObject::referenceTransformation ()
Create cached matrix to transform to reference coordinates.
Definition at line 179 of file DetectorInterna.cpp.
References DD4hep::Geometry::DetectorTools::isParentElement(), DD4hep::NamedObject::name, DD4hep::Handle< T >::name(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Geometry::DetectorTools::placementTrafo(), DD4hep::Handle< T >::ptr(), reference, and referenceTrafo.
removeAtUpdate()
void DetElementObject::removeAtUpdate (unsigned int type, void * pointer)
Remove callback from object.
Definition at line 259 of file DetectorInterna.cpp.
References updateCalls.
revalidate()
void DetElementObject::revalidate (TGeoHMatrix * parent_world_trafo)
Revalidate the caches.
Compute world transformations
Now iterate down the children....
Definition at line 205 of file DetectorInterna.cpp.
References children, DD4hep::DEBUG, DD4hep::deletePtr(), DD4hep::Geometry::DetectorTools::findNode(), flag, HAVE_PARENT_TRAFO, HAVE_WORLD_TRAFO, idealPlace, DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::parent(), parentTrafo, parentTransformation(), DD4hep::Geometry::DetElement::path(), placement, DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Geometry::DetElement::placementPath(), DD4hep::Geometry::DetectorTools::placementTrafo(), DD4hep::print(), DD4hep::printLevel(), DD4hep::printout(), DD4hep::Handle< T >::ptr(), referenceTrafo, world(), and worldTrafo.
Referenced by update().
update()
void DetElementObject::update (unsigned int tags, void * param)
Trigger update callbacks.
Definition at line 269 of file DetectorInterna.cpp.
References HAVE_PARENT_TRAFO, DD4hep::INFO, DD4hep::Geometry::DetElement::parent(), DD4hep::Geometry::DetElement::path(), DD4hep::Geometry::DetElement::PLACEMENT_CHANGED, DD4hep::Geometry::DetElement::PLACEMENT_HIGHEST, DD4hep::printout(), revalidate(), and updateCalls.
world()
World DD4hep::Geometry::DetElementObject::world () inline
Access to the world object. Only possible once the geometry is closed.
Definition at line 193 of file DetectorInterna.h.
References DD4hep::Handle< T >::isValid(), and DD4hep::NamedObject::type.
Referenced by i_access_world(), revalidate(), and DD4hep::Geometry::DetElement::world().
worldTransformation()
const TGeoHMatrix & DetElementObject::worldTransformation ()
Create cached matrix to transform to world coordinates.
Definition at line 157 of file DetectorInterna.cpp.
References flag, HAVE_WORLD_TRAFO, DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Geometry::DetectorTools::placementTrafo(), and worldTrafo.
Member Data Documentation
alignments
AlignmentsContainer DD4hep::Geometry::DetElementObject::alignments
The detector elements alignments access.
Definition at line 155 of file DetectorInterna.h.
Referenced by DD4hep::Alignments::DetAlign::alignments(), clone(), DD4hep::Alignments::DetAlign::hasAlignments(), DD4hep::Geometry::DetElement::hasAlignments(), and ~DetElementObject().
children
Children DD4hep::Geometry::DetElementObject::children
The array of children.
Definition at line 145 of file DetectorInterna.h.
Referenced by clone(), revalidate(), and ~DetElementObject().
combineHits
int DD4hep::Geometry::DetElementObject::combineHits
Flag to process hits.
Definition at line 116 of file DetectorInterna.h.
Referenced by clone().
conditions
ConditionsContainer DD4hep::Geometry::DetElementObject::conditions
The detector elements conditions access.
Definition at line 157 of file DetectorInterna.h.
Referenced by assign_conditions(), clone(), DD4hep::Conditions::DetConditions::conditions(), DD4hep::Conditions::DetConditions::hasConditions(), DD4hep::Geometry::DetElement::hasConditions(), and ~DetElementObject().
flag
unsigned int DD4hep::Geometry::DetElementObject::flag
Flag to remember internally calculated quatities.
Definition at line 112 of file DetectorInterna.h.
Referenced by clone(), parentTransformation(), revalidate(), and worldTransformation().
global_alignment
Ref_t DD4hep::Geometry::DetElementObject::global_alignment
Global alignment data.
Definition at line 160 of file DetectorInterna.h.
id
int DD4hep::Geometry::DetElementObject::id
Unique integer identifier of the detector instance.
Definition at line 114 of file DetectorInterna.h.
Referenced by clone(), DD4hep::Geometry::DetElement::clone(), and DetElementObject().
idealPlace
PlacedVolume DD4hep::Geometry::DetElementObject::idealPlace
The subdetector placement corresponding to the ideal detector element's volume.
Definition at line 129 of file DetectorInterna.h.
Referenced by clone(), revalidate(), DD4hep::Geometry::DetElement::setPlacement(), and ~DetElementObject().
key
unsigned int DD4hep::Geometry::DetElementObject::key
Access hash key of this detector element (Only valid once geometry is closed!)
Definition at line 122 of file DetectorInterna.h.
Referenced by clone(), DD4hep::Geometry::DetElement::key(), and DD4hep::Geometry::DetElement::setTypeFlag().
level
int DD4hep::Geometry::DetElementObject::level
Hierarchical level within the detector description.
Definition at line 120 of file DetectorInterna.h.
Referenced by clone(), DD4hep::Geometry::DetElement::level(), and DD4hep::Geometry::DetElement::setTypeFlag().
magic
unsigned int DD4hep::Geometry::DetElementObject::magic
Magic number to ensure data integrity.
Definition at line 110 of file DetectorInterna.h.
nominal
Alignment DD4hep::Geometry::DetElementObject::nominal
Basic ideal/nominal detector element alignment entry.
Definition at line 151 of file DetectorInterna.h.
Referenced by clone(), DD4hep::Geometry::DetElement::nominal(), and ~DetElementObject().
parent
DetElement DD4hep::Geometry::DetElementObject::parent
Reference to the parent element.
Definition at line 141 of file DetectorInterna.h.
Referenced by clone(), i_access_world(), DD4hep::Geometry::DetElement::parent(), parentTransformation(), DD4hep::Geometry::DetElement::setTypeFlag(), and ~DetElementObject().
parentTrafo
TGeoHMatrix DD4hep::Geometry::DetElementObject::parentTrafo
Intermediate buffer to store the transformation to the parent detector element.
Definition at line 172 of file DetectorInterna.h.
Referenced by parentTransformation(), and revalidate().
path
std::string DD4hep::Geometry::DetElementObject::path
Full path to this detector element. May be invalid.
Definition at line 124 of file DetectorInterna.h.
Referenced by DD4hep::Geometry::DetElement::path(), and DD4hep::Geometry::DetElement::setTypeFlag().
placement
PlacedVolume DD4hep::Geometry::DetElementObject::placement
The subdetector placement corresponding to the actual detector element's volume.
Definition at line 131 of file DetectorInterna.h.
Referenced by clone(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Geometry::DetElement::placement(), revalidate(), DD4hep::Geometry::DetElement::setPlacement(), and ~DetElementObject().
placementPath
std::string DD4hep::Geometry::DetElementObject::placementPath
The path to the placement of the detector element (if placed)
Definition at line 126 of file DetectorInterna.h.
Referenced by clone(), and DD4hep::Geometry::DetElement::placementPath().
privateWorld
World DD4hep::Geometry::DetElementObject::privateWorld
Reference to the parent element.
Definition at line 139 of file DetectorInterna.h.
Referenced by i_access_world().
reference
DetElement DD4hep::Geometry::DetElementObject::reference
Reference element for stored transformations.
Definition at line 143 of file DetectorInterna.h.
Referenced by referenceTransformation().
referenceTrafo
TGeoHMatrix* DD4hep::Geometry::DetElementObject::referenceTrafo
Intermediate buffer for the transformation to an arbitrary DetElement.
Definition at line 174 of file DetectorInterna.h.
Referenced by referenceTransformation(), revalidate(), DD4hep::Geometry::DetElement::setAttributes(), and ~DetElementObject().
survey
Alignment DD4hep::Geometry::DetElementObject::survey
Basic detector element alignment entry containing the survey data.
Definition at line 153 of file DetectorInterna.h.
Referenced by clone(), DD4hep::Geometry::DetElement::survey(), and ~DetElementObject().
typeFlag
unsigned int DD4hep::Geometry::DetElementObject::typeFlag
Flag to encode detector types.
Definition at line 118 of file DetectorInterna.h.
Referenced by clone(), and DD4hep::Geometry::DetElement::setTypeFlag().
updateCalls
UpdateCallbacks DD4hep::Geometry::DetElementObject::updateCalls
Placeholder for structure with update callbacks.
Definition at line 147 of file DetectorInterna.h.
Referenced by removeAtUpdate(), and update().
volume_alignments
std::vector<Alignment> DD4hep::Geometry::DetElementObject::volume_alignments
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
Definition at line 164 of file DetectorInterna.h.
volume_surveys
std::vector<Alignment> DD4hep::Geometry::DetElementObject::volume_surveys
Alignment entries for lower level volumes, which are NOT attached to daughter DetElements.
Definition at line 166 of file DetectorInterna.h.
volumeID
VolumeID DD4hep::Geometry::DetElementObject::volumeID
The cached VolumeID of this subdetector element.
Please note: These values are set when populating the volume manager. There are restrictions: e.g. only sensitive subdetectors are present.
Definition at line 137 of file DetectorInterna.h.
worldTrafo
TGeoHMatrix DD4hep::Geometry::DetElementObject::worldTrafo
Intermediate buffer to store the transformation to the world coordination system.
Definition at line 170 of file DetectorInterna.h.
Referenced by revalidate(), and worldTransformation().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/DetectorInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetectorInterna.cpp