DD4hep: DD4hep::Simulation::Geant4AssemblyVolume Class Reference
DD4hep::Simulation::Geant4AssemblyVolume Class Reference
DD4hep::Simulation components, classes and objects
Hack! Wrapper around G4AssemblyVolume to access protected members.
#include <Geant4AssemblyVolume.h>
Public Types
typedef std::vector< const TGeoNode * > Chain
Public Member Functions
Geant4AssemblyVolume ()
Default constructor with initialization.
virtual ~Geant4AssemblyVolume ()
Default destructor.
long placeVolume (const TGeoNode *n, G4LogicalVolume *pPlacedVolume, G4Transform3D &transformation)
long placeAssembly (const TGeoNode *n, Geant4AssemblyVolume *pPlacedVolume, G4Transform3D &transformation)
void imprint (Geant4GeometryInfo &info, const TGeoNode *n, Chain chain, Geant4AssemblyVolume *pAssembly, G4LogicalVolume *pMotherLV, G4Transform3D &transformation, G4int copyNumBase, G4bool surfCheck)
Public Attributes
std::vector< const TGeoNode * > m_entries
Detailed Description
Hack! Wrapper around G4AssemblyVolume to access protected members.
Author
M.Frank
Version
1.0
Definition at line 31 of file Geant4AssemblyVolume.h.
Member Typedef Documentation
Chain
typedef std::vector<const TGeoNode*> DD4hep::Simulation::Geant4AssemblyVolume::Chain
Definition at line 34 of file Geant4AssemblyVolume.h.
Constructor & Destructor Documentation
Geant4AssemblyVolume()
DD4hep::Simulation::Geant4AssemblyVolume::Geant4AssemblyVolume () inline
Default constructor with initialization.
Definition at line 36 of file Geant4AssemblyVolume.h.
~Geant4AssemblyVolume()
virtual DD4hep::Simulation::Geant4AssemblyVolume::~Geant4AssemblyVolume () inline virtual
Default destructor.
Definition at line 39 of file Geant4AssemblyVolume.h.
Member Function Documentation
imprint()
void Geant4AssemblyVolume::imprint (Geant4GeometryInfo & info, const TGeoNode * n, Chain chain, Geant4AssemblyVolume * pAssembly, G4LogicalVolume * pMotherLV, G4Transform3D & transformation, G4int copyNumBase, G4bool surfCheck)
Definition at line 109 of file Geant4Converter.cpp.
References CM_2_MM, DD4hep::DEBUG, DD4hep::Simulation::Geant4GeometryInfo::g4VolumeImprints, DD4hep::Handle< T >::isValid(), m, m_entries, DD4hep::Handle< T >::name(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::printout(), s, and v.
Referenced by placeAssembly().
placeAssembly()
long DD4hep::Simulation::Geant4AssemblyVolume::placeAssembly (const TGeoNode * n, Geant4AssemblyVolume * pPlacedVolume, G4Transform3D & transformation) inline
Definition at line 48 of file Geant4AssemblyVolume.h.
References imprint().
Referenced by DD4hep::Simulation::Geant4Converter::handleAssembly().
placeVolume()
long DD4hep::Simulation::Geant4AssemblyVolume::placeVolume (const TGeoNode * n, G4LogicalVolume * pPlacedVolume, G4Transform3D & transformation) inline
Definition at line 42 of file Geant4AssemblyVolume.h.
Referenced by DD4hep::Simulation::Geant4Converter::handleAssembly().
Member Data Documentation
m_entries
std::vector<const TGeoNode*> DD4hep::Simulation::Geant4AssemblyVolume::m_entries
Definition at line 33 of file Geant4AssemblyVolume.h.
Referenced by imprint().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4AssemblyVolume.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Converter.cpp