DD4hep: DD4hep::ROOTUI Class Reference
DD4hep::ROOTUI Class Reference
DD4hep classes and objects
ROOT interactive UI for DD4hep applications.
#include <ROOTUI.h>
Public Member Functions
ROOTUI (Geometry::LCDD &instance)
Default constructor.
virtual ~ROOTUI ()
Default destructor.
Geometry::LCDD * instance () const
Access to the LCDD instance.
Handle< NamedObject > conditionsMgr () const
Install the DD4hep conditions manager object.
long loadConditions (const std::string &fname) const
Load conditions from file.
Handle< NamedObject > alignmentMgr () const
Install the DD4hep alignment manager object.
virtual long apply (const char *factory, int argc, char **argv) const
LCDD interface: Manipulate geometry using facroy converter.
virtual void fromXML (const std::string &fname, LCDDBuildType type=BUILD_DEFAULT) const
LCDD interface: Read any geometry description or alignment file.
virtual void redraw () const
LCDD interface: Re-draw the entire scene.
Protected Attributes
Geometry::LCDD & m_lcdd
Reference to the LCDD instance object.
Handle< NamedObject > m_condMgr
Handle< NamedObject > m_alignMgr
Detailed Description
ROOT interactive UI for DD4hep applications.
Author
M.Frank
Version
1.0
Definition at line 29 of file ROOTUI.h.
Constructor & Destructor Documentation
ROOTUI()
ROOTUI::ROOTUI (Geometry::LCDD & instance)
Default constructor.
Definition at line 23 of file ROOTUI.cpp.
~ROOTUI()
ROOTUI::~ROOTUI () virtual
Default destructor.
Definition at line 27 of file ROOTUI.cpp.
Member Function Documentation
alignmentMgr()
Handle< NamedObject > ROOTUI::alignmentMgr () const
Install the DD4hep alignment manager object.
Definition at line 60 of file ROOTUI.cpp.
References apply(), DD4hep::except(), DD4hep::Handle< T >::isValid(), and m_alignMgr.
apply()
long ROOTUI::apply (const char * factory, int argc, char ** argv) const virtual
LCDD interface: Manipulate geometry using facroy converter.
Definition at line 74 of file ROOTUI.cpp.
References DD4hep::Geometry::LCDD::apply(), and m_lcdd.
Referenced by alignmentMgr(), and conditionsMgr().
conditionsMgr()
Handle< NamedObject > ROOTUI::conditionsMgr () const
Install the DD4hep conditions manager object.
Definition at line 36 of file ROOTUI.cpp.
References apply(), DD4hep::except(), DD4hep::Handle< T >::isValid(), and m_condMgr.
Referenced by loadConditions().
fromXML()
void ROOTUI::fromXML (const std::string & fname, LCDDBuildType type = BUILD_DEFAULT) const virtual
LCDD interface: Read any geometry description or alignment file.
Definition at line 79 of file ROOTUI.cpp.
References DD4hep::Geometry::LCDD::fromXML(), and m_lcdd.
instance()
LCDD * ROOTUI::instance () const
Access to the LCDD instance.
Definition at line 31 of file ROOTUI.cpp.
References m_lcdd.
loadConditions()
long ROOTUI::loadConditions (const std::string & fname) const
Load conditions from file.
Definition at line 50 of file ROOTUI.cpp.
References DD4hep::BUILD_DEFAULT, conditionsMgr(), DD4hep::Geometry::LCDD::fromXML(), DD4hep::Handle< T >::isValid(), and m_lcdd.
redraw()
void ROOTUI::redraw () const virtual
LCDD interface: Re-draw the entire scene.
Definition at line 84 of file ROOTUI.cpp.
References m_lcdd, and DD4hep::Geometry::LCDD::worldVolume().
Member Data Documentation
m_alignMgr
Handle<NamedObject> DD4hep::ROOTUI::m_alignMgr protected
Definition at line 34 of file ROOTUI.h.
Referenced by alignmentMgr().
m_condMgr
Handle<NamedObject> DD4hep::ROOTUI::m_condMgr protected
Definition at line 33 of file ROOTUI.h.
Referenced by conditionsMgr().
m_lcdd
Geometry::LCDD& DD4hep::ROOTUI::m_lcdd protected
Reference to the LCDD instance object.
Definition at line 32 of file ROOTUI.h.
Referenced by apply(), fromXML(), instance(), loadConditions(), and redraw().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ROOTUI.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ROOTUI.cpp