DD4hep: DD4hep::Conditions::Operators Class Reference
DD4hep::Conditions::Operators Class Reference
Helper class for common stuff used frequently.
#include <ConditionsOperators.h>
Static Public Member Functions
static size_t collectAllConditions (Geometry::LCDD &lcdd, RangeConditions &conditions)
Select all condition from the conditions manager registered at the LCDD object.
static size_t collectAllConditions (ConditionsManager mgr, RangeConditions &conditions)
Select all condition from the conditions manager registered at the LCDD object.
static size_t collectAllConditions (Geometry::LCDD &lcdd, std::map< int, Condition > &conditions)
Select all condition from the conditions manager registered at the LCDD object.
static size_t collectAllConditions (ConditionsManager mgr, std::map< int, Condition > &conditions)
Select all condition from the conditions manager registered at the LCDD object.
Detailed Description
Helper class for common stuff used frequently.
Definition at line 35 of file ConditionsOperators.h.
Member Function Documentation
collectAllConditions() [1/4]
size_t Operators::collectAllConditions (Geometry::LCDD & lcdd, RangeConditions & conditions) static
Select all condition from the conditions manager registered at the LCDD object.
Definition at line 31 of file ConditionsOperators.cpp.
collectAllConditions() [2/4]
size_t Operators::collectAllConditions (ConditionsManager mgr, RangeConditions & conditions) static
Select all condition from the conditions manager registered at the LCDD object.
Definition at line 37 of file ConditionsOperators.cpp.
References _E, _T(), e, DD4hep::Conditions::ConditionsIOVPool::elements, DD4hep::Conditions::ConditionsManager::iovPool(), DD4hep::Conditions::ConditionsManager::iovTypesUsed(), and DD4hep::Conditions::ConditionsPool::select_all().
collectAllConditions() [3/4]
size_t Operators::collectAllConditions (Geometry::LCDD & lcdd, std::map< int, Condition > & conditions) static
Select all condition from the conditions manager registered at the LCDD object.
Definition at line 63 of file ConditionsOperators.cpp.
collectAllConditions() [4/4]
size_t Operators::collectAllConditions (ConditionsManager mgr, std::map< int, Condition > & conditions) static
Select all condition from the conditions manager registered at the LCDD object.
Definition at line 69 of file ConditionsOperators.cpp.
References _E, _T(), e, DD4hep::Conditions::ConditionsIOVPool::elements, DD4hep::Conditions::ConditionsManager::iovPool(), DD4hep::Conditions::ConditionsManager::iovTypesUsed(), and DD4hep::Conditions::ConditionsPool::select_all().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsOperators.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsOperators.cpp