DD4hep: DD4hep::Geometry::VisAttr Class Reference
DD4hep::Geometry::VisAttr Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing visualization attributes.
#include <Objects.h>
Public Types
enum Style { SOLID = 0x1, WIREFRAME = 0x2, DASHED = 0x2, LAST_STYLE }
typedef VisAttrObject Object
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
VisAttr ()
Default constructor.
VisAttr (const VisAttr &e)
Copy constructor for handle.
VisAttr (const Handle< Object > &e)
Copy constructor for handle.
template<typename Q >
VisAttr (const Handle< Q > &e)
Constructor to be used for assignment from object handle.
VisAttr (const std::string &name)
Constructor to be used when creating a new registered visualization object.
VisAttr (const char *name)
Constructor to be used when creating a new registered visualization object.
VisAttr & operator= (const VisAttr &attr)
Assignment operator.
bool showDaughters () const
Get Flag to show/hide daughter elements.
void setShowDaughters (bool value)
Set Flag to show/hide daughter elements.
bool visible () const
Get visibility flag.
void setVisible (bool value)
Set visibility flag.
int lineStyle () const
Get line style.
void setLineStyle (int style)
Set line style.
int drawingStyle () const
Get drawing style.
void setDrawingStyle (int style)
Set drawing style.
float alpha () const
Get alpha value.
void setAlpha (float value)
Set alpha value.
int color () const
Get object color.
void setColor (float red, float green, float blue)
Set object color.
bool rgb (float &red, float &green, float &blue) const
Get RGB values of the color (if valid)
std::string toString () const
String representation of this object.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing visualization attributes.
Author
M.Frank
Version
1.0
Definition at line 341 of file Objects.h.
Member Typedef Documentation
Object
typedef VisAttrObject DD4hep::Geometry::VisAttr::Object
Definition at line 346 of file Objects.h.
Member Enumeration Documentation
Style
enum DD4hep::Geometry::VisAttr::Style
Enumerator
SOLID
WIREFRAME
DASHED
LAST_STYLE
Definition at line 343 of file Objects.h.
Constructor & Destructor Documentation
VisAttr() [1/6]
DD4hep::Geometry::VisAttr::VisAttr () inline
Default constructor.
Definition at line 348 of file Objects.h.
VisAttr() [2/6]
DD4hep::Geometry::VisAttr::VisAttr (const VisAttr & e) inline
Copy constructor for handle.
Definition at line 352 of file Objects.h.
References e.
VisAttr() [3/6]
DD4hep::Geometry::VisAttr::VisAttr (const Handle< Object > & e) inline
Copy constructor for handle.
Definition at line 357 of file Objects.h.
VisAttr() [4/6]
template<typename Q > DD4hep::Geometry::VisAttr::VisAttr (const Handle< Q > & e) inline
Constructor to be used for assignment from object handle.
Definition at line 363 of file Objects.h.
References DD4hep::Handle< T >::name().
VisAttr() [5/6]
VisAttr::VisAttr (const std::string & name)
Constructor to be used when creating a new registered visualization object.
Constructor to be used when creating a new entity.
Definition at line 245 of file Objects.cpp.
References DD4hep::Geometry::VisAttrObject::color.
VisAttr() [6/6]
VisAttr::VisAttr (const char * name)
Constructor to be used when creating a new registered visualization object.
Constructor to be used when creating a new entity.
Definition at line 256 of file Objects.cpp.
References DD4hep::Geometry::VisAttrObject::color.
Member Function Documentation
alpha()
float VisAttr::alpha () const
Get alpha value.
Definition at line 307 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleVis().
color()
int VisAttr::color () const
Get object color.
Definition at line 321 of file Objects.cpp.
Referenced by DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation().
drawingStyle()
int VisAttr::drawingStyle () const
Get drawing style.
Definition at line 297 of file Objects.cpp.
Referenced by DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation().
lineStyle()
int VisAttr::lineStyle () const
Get line style.
Definition at line 287 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleVis(), and DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation().
operator=()
VisAttr& DD4hep::Geometry::VisAttr::operator= (const VisAttr & attr) inline
Assignment operator.
Definition at line 371 of file Objects.h.
References DD4hep::Handle< T >::m_element, and DD4hep::Geometry::DetectorTools::toString().
rgb()
bool VisAttr::rgb (float & red, float & green, float & blue) const
Get RGB values of the color (if valid)
Definition at line 333 of file Objects.cpp.
References DD4hep::Geometry::VisAttrObject::col.
Referenced by DD4hep::Utilities::createEveShape(), and DD4hep::Simulation::Geant4Converter::handleVis().
setAlpha()
void VisAttr::setAlpha (float value)
Set alpha value.
Definition at line 314 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::init(), and DD4hep::Geometry::LCDDImp::LCDDImp().
setColor()
void VisAttr::setColor (float red, float green, float blue)
Set object color.
Definition at line 326 of file Objects.cpp.
References DD4hep::Geometry::VisAttrObject::col, and DD4hep::Geometry::VisAttrObject::color.
Referenced by DD4hep::Geometry::LCDDImp::init(), and DD4hep::Geometry::LCDDImp::LCDDImp().
setDrawingStyle()
void VisAttr::setDrawingStyle (int style)
Set drawing style.
Definition at line 302 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::init(), and DD4hep::Geometry::LCDDImp::LCDDImp().
setLineStyle()
void VisAttr::setLineStyle (int style)
Set line style.
Definition at line 292 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::init(), and DD4hep::Geometry::LCDDImp::LCDDImp().
setShowDaughters()
void VisAttr::setShowDaughters (bool value)
Set Flag to show/hide daughter elements.
Definition at line 272 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::init(), and DD4hep::Geometry::LCDDImp::LCDDImp().
setVisible()
void VisAttr::setVisible (bool value)
Set visibility flag.
Definition at line 282 of file Objects.cpp.
Referenced by DD4hep::Geometry::LCDDImp::endDocument(), DD4hep::Geometry::LCDDImp::init(), and DD4hep::Geometry::LCDDImp::LCDDImp().
showDaughters()
bool VisAttr::showDaughters () const
Get Flag to show/hide daughter elements.
Definition at line 267 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleVis(), and DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation().
toString()
string VisAttr::toString () const
String representation of this object.
Definition at line 344 of file Objects.cpp.
References DD4hep::Geometry::VisAttrObject::color, DD4hep::Geometry::VisAttrObject::drawingStyle, DD4hep::Utilities::GetName(), DD4hep::Geometry::VisAttrObject::lineStyle, DD4hep::Geometry::VisAttrObject::showDaughters, DD4hep::Geometry::VisAttrObject::visible, and DD4hep::yes_no().
Referenced by DD4hep::Printer< T >::operator()().
visible()
bool VisAttr::visible () const
Get visibility flag.
Definition at line 277 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleVis(), and DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp