DD4hep: Tests::Geant4SensitiveAction< T > Class Template Reference
Tests::Geant4SensitiveAction< T > Class Template Reference
Deprecated: Simple SensitiveAction class ...
Public Member Functions
Geant4SensitiveAction (Geant4Context *ctxt, const std::string &nam, DetElement det, LCDD &lcdd_ref)
virtual ~Geant4SensitiveAction ()
Default destructor.
virtual void defineCollections ()
Define collections created by this sensitivie action object.
virtual void begin (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the begining of each event.
virtual void end (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the end of each event.
virtual bool process (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the G4Step object.
virtual void clear (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked if the event was aborted.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
bool process (G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
Public Member Functions inherited from DD4hep::Simulation::Geant4Sensitive
Geant4Sensitive (Geant4Context *context, const std::string &name, DetElement det, LCDD &lcdd)
Constructor. The sensitive detector element is identified by the detector name.
virtual ~Geant4Sensitive ()
Standard destructor.
Geant4ActionSD & detector () const
Access to the sensitive detector object.
void setDetector (Geant4ActionSD *sens_det)
Access to the sensitive detector object.
int hitCreationMode () const
Property access to the hit creation mode.
std::string detectorName () const
G4VSensitiveDetector internals: Access to the detector name.
std::string path () const
G4VSensitiveDetector internals: Access to the detector path name.
std::string fullPath () const
G4VSensitiveDetector internals: Access to the detector path name.
bool isActive () const
G4VSensitiveDetector internals: Is the detector active?
SensitiveDetector sensitiveDetector () const
Access the DD4hep sensitive detector.
G4VReadOutGeometry * readoutGeometry () const
Access to the readout geometry of the sensitive detector.
void mark (const G4Track *track) const
Mark the track to be kept for MC truth propagation during hit processing.
void mark (const G4Step *step) const
Mark the track of this step to be kept for MC truth propagation during hit processing.
Geant4SensDetActionSequence & sequence () const
Access to the hosting sequence.
void adopt (Geant4Filter *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adopt_front (Geant4Filter *filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
void adoptFilter (Geant4Action *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adoptFilter_front (Geant4Action *filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
bool accept (const G4Step *step) const
Callback before hit processing starts. Invoke all filters.
template<typename TYPE >
size_t defineCollection (const std::string &coll_name)
Initialize the usage of a single hit collection. Returns the collection ID.
const std::string & hitCollectionName (size_t which) const
Access HitCollection container names.
HitCollection * collection (size_t which)
Retrieve the hits collection associated with this detector by its serial number.
HitCollection * collectionByID (size_t id)
Retrieve the hits collection associated with this detector by its collection identifier.
long long int volumeID (const G4Step *step)
Returns the volumeID of the sensitive volume corresponding to the step.
long long int cellID (const G4Step *step)
Returns the cellID of the sensitive volume corresponding to the step.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Types
typedef Geant4Sensitive Base
Protected Attributes
size_t m_collectionID
Collection identifiers.
bool _detailedHitsStoring
Protected Attributes inherited from DD4hep::Simulation::Geant4Sensitive
int m_hitCreationMode
Property: Hit creation mode. Maybe one of the enum HitCreationFlags.
LCDD & m_lcdd
Reference to the detector description object.
DetElement m_detector
Reference to the detector element describing this sensitive element.
SensitiveDetector m_sensitive
Reference to the sensitive detector element.
Readout m_readout
Reference to the readout structure.
Segmentation m_segmentation
Reference to segmentation.
Actors< Geant4Filter > m_filters
The list of sensitive detector filter objects.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4Sensitive
enum HitCreationFlags { SIMPLE_MODE = 0, MEDIUM_MODE = 1<<0, DETAILED_MODE = 1<<1 }
typedef Geometry::LCDD LCDD
typedef Geometry::Readout Readout
typedef Geometry::DetElement DetElement
typedef Geometry::Segmentation Segmentation
typedef Geometry::SensitiveDetector SensitiveDetector
Definition: Sensitive detector type.
typedef Geant4StepHandler StepHandler
typedef Geant4HitCollection HitCollection
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
template<typename T>
class Tests::Geant4SensitiveAction< T >
Deprecated: Simple SensitiveAction class ...
Deprecated:
Author
M.Frank
Version
1.0
Definition at line 45 of file LCIOSDTestActions.cpp.
Member Typedef Documentation
Base
template<typename T > typedef Geant4Sensitive Tests::Geant4SensitiveAction< T >::Base protected
Definition at line 47 of file LCIOSDTestActions.cpp.
Constructor & Destructor Documentation
Geant4SensitiveAction()
template<typename T > Tests::Geant4SensitiveAction< T >::Geant4SensitiveAction (Geant4Context * ctxt, const std::string & nam, DetElement det, LCDD & lcdd_ref) inline
Definition at line 57 of file LCIOSDTestActions.cpp.
References DD4hep::InstanceCount::increment().
~Geant4SensitiveAction()
template<typename T > virtual Tests::Geant4SensitiveAction< T >::~Geant4SensitiveAction () inline virtual
Default destructor.
Definition at line 64 of file LCIOSDTestActions.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
begin()
template<typename T > virtual void Tests::Geant4SensitiveAction< T >::begin (G4HCofThisEvent * hce) inline virtual
G4VSensitiveDetector interface: Method invoked at the begining of each event.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 70 of file LCIOSDTestActions.cpp.
clear()
template<typename T > virtual void Tests::Geant4SensitiveAction< T >::clear (G4HCofThisEvent * hce) inline virtual
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 82 of file LCIOSDTestActions.cpp.
defineCollections() [1/2]
template<typename T > virtual void Tests::Geant4SensitiveAction< T >::defineCollections () inline virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 68 of file LCIOSDTestActions.cpp.
defineCollections() [2/2]
template<> void Tests::Geant4SensitiveAction< LcioTestTracker >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 101 of file LCIOSDTestActions.cpp.
end()
template<typename T > virtual void Tests::Geant4SensitiveAction< T >::end (G4HCofThisEvent * hce) inline virtual
G4VSensitiveDetector interface: Method invoked at the end of each event.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 74 of file LCIOSDTestActions.cpp.
process() [1/2]
template<typename T > virtual bool Tests::Geant4SensitiveAction< T >::process (G4Step * step, G4TouchableHistory * history) inline virtual
G4VSensitiveDetector interface: Method for generating hit(s) using the G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 78 of file LCIOSDTestActions.cpp.
process() [2/2]
template<> bool Tests::Geant4SensitiveAction< LcioTestTracker >::process (G4Step * step, G4TouchableHistory *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 106 of file LCIOSDTestActions.cpp.
References DD4hep::INFO, ROOT::Math::mean_direction(), ROOT::Math::mean_length(), DD4hep::Simulation::Geant4StepHandler::postMom(), DD4hep::Simulation::Geant4StepHandler::postPos(), DD4hep::Simulation::Geant4StepHandler::preMom(), DD4hep::Simulation::Geant4StepHandler::prePos(), and DD4hep::printout().
Member Data Documentation
_detailedHitsStoring
template<typename T > bool Tests::Geant4SensitiveAction< T >::_detailedHitsStoring protected
Definition at line 52 of file LCIOSDTestActions.cpp.
m_collectionID
template<typename T > size_t Tests::Geant4SensitiveAction< T >::m_collectionID protected
Collection identifiers.
Definition at line 49 of file LCIOSDTestActions.cpp.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/lcio/LCIOSDTestActions.cpp