DD4hep: DD4hep::Geometry::LCDDImp Class Reference
DD4hep::Geometry::LCDDImp Class Reference
Concrete implementation class of the LCDD interface.
#include <src/LCDDImp.h>
Public Member Functions
void imp_loadVolumeManager ()
Local method (no interface): Load volume manager.
LCDDImp ()
Default constructor.
virtual ~LCDDImp ()
Standard destructor.
virtual LCDDBuildType buildType () const
Access flag to steer the detail of building of the geometry/detector description.
virtual void fromCompact (const std::string &fname, LCDDBuildType type=BUILD_DEFAULT)
Read compact geometry description or alignment file.
virtual void fromXML (const std::string &fname, LCDDBuildType type=BUILD_DEFAULT)
Read any XML file.
virtual void fromXML (const std::string &fname, UriReader *entity_resolver, LCDDBuildType type=BUILD_DEFAULT)
Read any geometry description or alignment file with external XML entity resolution.
virtual void dump () const
Stupid legacy method.
virtual long apply (const char *factory, int argc, char **argv)
Manipulate geometry using facroy converter.
virtual void init ()
Initialize geometry.
virtual void endDocument ()
Finalize the geometry.
virtual void * addUserExtension (void *ptr, const std::type_info &info, void(*destruct)(void *))
Add an extension object to the LCDD instance.
virtual void * removeUserExtension (const std::type_info &info, bool destroy=true)
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
virtual void * userExtension (const std::type_info &info, bool alert=true) const
Access an existing extension object from the LCDD instance.
virtual Handle< TObject > getRefChild (const HandleMap &e, const std::string &name, bool throw_if_not=true) const
virtual void declareMotherVolume (const std::string &detector_name, const Volume &vol)
Register new mother volume using the detector name.
virtual Volume pickMotherVolume (const DetElement &sd) const
Access mother volume by detector element.
virtual TGeoManager & manager () const
Access the geometry manager of this instance.
Properties & properties () const
Access to properties.
virtual Material air () const
Return handle to material describing air.
virtual Material vacuum () const
Return handle to material describing vacuum.
virtual VisAttr invisible () const
Return handle to "invisible" visualization attributes.
virtual DetElement world () const
Return reference to the top-most (world) detector element.
virtual DetElement trackers () const
Return reference to detector element with all tracker devices.
virtual Volume worldVolume () const
Return handle to the world volume containing everything.
virtual Volume trackingVolume () const
Return handle to the world volume containing the volume with the tracking devices.
virtual VolumeManager volumeManager () const
Return handle to the VolumeManager.
virtual OverlayedField field () const
Return handle to the combined electromagentic field description.
virtual Header header () const
Accessor to the header entry.
virtual void setHeader (Header h)
Accessor to the header entry.
virtual std::string constantAsString (const std::string &name) const
Typed access to constants: access string values.
virtual long constantAsLong (const std::string &name) const
Typed access to constants: long values.
virtual double constantAsDouble (const std::string &name) const
Typed access to constants: double values.
virtual Constant constant (const std::string &name) const
Retrieve a constant by it's name from the detector description.
virtual LimitSet limitSet (const std::string &name) const
Retrieve a limitset by it's name from the detector description.
virtual VisAttr visAttributes (const std::string &name) const
Retrieve a visualization attribute by it's name from the detector description.
virtual Material material (const std::string &name) const
Retrieve a matrial by it's name from the detector description.
virtual Region region (const std::string &name) const
Retrieve a region object by it's name from the detector description.
virtual IDDescriptor idSpecification (const std::string &name) const
Retrieve a id descriptor by it's name from the detector description.
virtual Readout readout (const std::string &name) const
Retrieve a readout object by it's name from the detector description.
virtual AlignmentEntry alignment (const std::string &path) const
Retrieve an alignment entry by it's name from the detector description.
virtual DetElement detector (const std::string &name) const
Retrieve a subdetector element by it's name from the detector description.
virtual SensitiveDetector sensitiveDetector (const std::string &name) const
Retrieve a sensitive detector by it's name from the detector description.
virtual CartesianField field (const std::string &name) const
Retrieve a subdetector element by it's name from the detector description.
virtual const HandleMap & constants () const
Accessor to the map of constants.
virtual const HandleMap & visAttributes () const
Accessor to the map of visualisation attributes.
virtual const HandleMap & limitsets () const
Accessor to the map of limit settings.
virtual const HandleMap & regions () const
Accessor to the map of region settings.
virtual const HandleMap & readouts () const
Accessor to the map of readout structures.
virtual const HandleMap & detectors () const
Accessor to the map of sub-detectors.
virtual const HandleMap & sensitiveDetectors () const
Retrieve a sensitive detector by it's name from the detector description.
virtual const HandleMap & alignments () const
Accessor to the map of aligment entries.
virtual const HandleMap & fields () const
Accessor to the map of field entries, which together form the global field.
virtual const HandleMap & idSpecifications () const
Accessor to the map of ID specifications.
virtual const std::vector< DetElement > & detectors (const std::string &type, bool throw_exc)
Access a set of subdetectors according to the sensitive type.
virtual std::vector< DetElement > detectors (const std::string &type1, const std::string &type2, const std::string &type3="", const std::string &type4="", const std::string &type5="")
Access a set of subdetectors according to several sensitive types.
virtual std::vector< std::string > detectorTypes () const
Access the availible detector types.
virtual std::vector< DetElement > detectors (unsigned int includeFlag, unsigned int excludeFlag=0) const
virtual LCDD & add (Constant x)
Add a new constant to the detector description.
virtual LCDD & add (LimitSet x)
Add a new limit set to the detector description.
virtual LCDD & add (Region x)
Add a new detector region to the detector description.
virtual LCDD & add (VisAttr x)
Add a new visualisation attribute to the detector description.
virtual LCDD & add (IDDescriptor x)
Add a new id descriptor to the detector description.
virtual LCDD & add (AlignmentEntry x)
Add alignment entry to the detector description.
virtual LCDD & add (Readout x)
Add a new detector readout to the detector description.
virtual LCDD & add (SensitiveDetector x)
Add a new sensitive detector to the detector description.
virtual LCDD & add (DetElement x)
Add a new subdetector to the detector description.
virtual LCDD & add (CartesianField x)
Add a field component to the detector description.
virtual LCDD & addConstant (const Ref_t &x)
Add a new constant by named reference to the detector description.
virtual LCDD & addLimitSet (const Ref_t &x)
Add a new limit set by named reference to the detector description.
virtual LCDD & addRegion (const Ref_t &x)
Add a new detector region by named reference to the detector description.
virtual LCDD & addIDSpecification (const Ref_t &x)
Add a new id descriptor by named reference to the detector description.
virtual LCDD & addReadout (const Ref_t &x)
Add a new detector readout by named reference to the detector description.
virtual LCDD & addVisAttribute (const Ref_t &x)
Add a new visualisation attribute by named reference to the detector description.
virtual LCDD & addSensitiveDetector (const Ref_t &x)
Add a new sensitive detector by named reference to the detector description.
virtual LCDD & addDetector (const Ref_t &x)
Add a new subdetector by named reference to the detector description.
virtual LCDD & addAlignment (const Ref_t &x)
Add a new alignment entry by named reference to the detector description.
virtual LCDD & addField (const Ref_t &x)
Add a field component by named reference to the detector description.
Public Member Functions inherited from DD4hep::Geometry::LCDD
virtual ~LCDD ()=default
Destructor.
template<class T >
T constant (const std::string &name) const
Typed access to constants: access any type values.
template<typename IFACE , typename CONCRETE >
IFACE * addExtension (CONCRETE *c)
Extend the sensitive detector element with an arbitrary structure accessible by the type.
template<class T >
T * removeExtension (bool destroy=true)
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
template<class T >
T * extension (bool alert=true) const
Access extension element by the type.
template<>
short constant (const std::string &name) const
Typed access to constants: short values.
template<>
unsigned short constant (const std::string &name) const
Typed access to constants: unsigned short values.
template<>
int constant (const std::string &name) const
Typed access to constants: integer values.
template<>
unsigned int constant (const std::string &name) const
Typed access to constants: unsigned integer values.
template<>
long constant (const std::string &name) const
Typed access to constants: long values.
template<>
unsigned long constant (const std::string &name) const
Typed access to constants: unsigned long values.
template<>
float constant (const std::string &name) const
Typed access to constants: float values.
template<>
double constant (const std::string &name) const
Typed access to constants: double values.
Public Member Functions inherited from DD4hep::Geometry::LCDDData
void destroyData (bool destroy_mgr=true)
Assignment operator.
void clearData ()
Clear data content: DOES NOT RELEASEW ALLOCATED RESOURCES!
void adoptData (LCDDData &source)
Adopt all data from source structure.
Public Member Functions inherited from DD4hep::LCDDLoad
virtual void processXML (const std::string &fname, XML::UriReader *entity_resolver=0)
Process XML unit and adopt all data from source structure.
virtual void processXML (const XML::Handle_t &base, const std::string &fname, XML::UriReader *entity_resolver=0)
Process XML unit and adopt all data from source structure.
virtual void processXMLElement (const std::string &msg_source, const XML::Handle_t &root)
Process a given DOM (sub-) tree.
virtual void processXMLElement (const XML::Handle_t &root, LCDDBuildType type)
Process a given DOM (sub-) tree.
Protected Types
typedef std::map< std::string, std::vector< DetElement > > DetectorTypeMap
Cached map with detector types:
Protected Attributes
DetectorTypeMap m_detectorTypes
Inventory of detector types.
LCDDBuildType m_buildType
VolumeManager m_volManager;.
Protected Attributes inherited from DD4hep::Geometry::LCDDData
TGeoManager * m_manager
ObjectHandleMap m_readouts
ObjectHandleMap m_idDict
ObjectHandleMap m_limits
ObjectHandleMap m_regions
ObjectHandleMap m_detectors
ObjectHandleMap m_alignments
ObjectHandleMap m_sensitive
ObjectHandleMap m_display
ObjectHandleMap m_fields
ObjectHandleMap m_motherVolumes
ObjectHandleMap m_define
DetElement m_world
DetElement m_trackers
Volume m_worldVol
Volume m_trackingVol
Material m_materialAir
Material m_materialVacuum
VisAttr m_invisibleVis
OverlayedField m_field
Header m_header
LCDD::Properties m_properties
LCDDBuildType m_buildType
ObjectExtensions m_extensions
Definition of the extension type.
VolumeManager m_volManager
Volume manager reference.
bool m_inhibitConstants
Flag to inhibit the access to global constants. Value set by constants section 'LCDD_InhibitConstants'.
Protected Attributes inherited from DD4hep::LCDDLoad
Geometry::LCDD * m_lcdd
Reference to the LCDD instance.
Private Member Functions
LCDDImp (const LCDDImp &copy)=delete
Disable copy constructor.
LCDDImp & operator= (const LCDDImp &copy)=delete
Disable assignment operator.
void mapDetectorTypes ()
Internal helper to map detector types once the geometry is closed.
Additional Inherited Members
Public Types inherited from DD4hep::Geometry::LCDD
typedef XML::UriReader UriReader
Type definition of a map of named handles.
typedef Handle< NamedObject > NamedHandle
typedef std::map< std::string, NamedHandle > HandleMap
typedef std::map< std::string, std::string > PropertyValues
typedef std::map< std::string, PropertyValues > Properties
Static Public Member Functions inherited from DD4hep::Geometry::LCDD
static LCDD & getInstance (void)
—Factory method----—
static void destroyInstance ()
Destroy the instance.
Protected Member Functions inherited from DD4hep::Geometry::LCDDData
LCDDData ()
Default constructor.
virtual ~LCDDData ()
Default destructor.
LCDDData (const LCDDData &copy)=delete
Copy constructor.
Protected Member Functions inherited from DD4hep::LCDDLoad
LCDDLoad (Geometry::LCDD *lcdd)
Default constructor.
virtual ~LCDDLoad ()
Default destructor.
Static Protected Member Functions inherited from DD4hep::Geometry::LCDD
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Detailed Description
Concrete implementation class of the LCDD interface.
Author
M.Frank
Version
1.0
Definition at line 40 of file LCDDImp.h.
Member Typedef Documentation
DetectorTypeMap
typedef std::map<std::string, std::vector<DetElement> > DD4hep::Geometry::LCDDImp::DetectorTypeMap protected
Cached map with detector types:
Definition at line 43 of file LCDDImp.h.
Constructor & Destructor Documentation
LCDDImp() [1/2]
DD4hep::Geometry::LCDDImp::LCDDImp (const LCDDImp & copy) private delete
Disable copy constructor.
LCDDImp() [2/2]
LCDDImp::LCDDImp ()
Default constructor.
Definition at line 101 of file LCDDImp.cpp.
References addVisAttribute(), DD4hep::InstanceCount::increment(), DD4hep::Geometry::LCDDData::m_invisibleVis, DD4hep::Geometry::LCDDData::m_manager, DD4hep::Geometry::VisAttr::setAlpha(), DD4hep::Geometry::VisAttr::setColor(), DD4hep::Geometry::VisAttr::setDrawingStyle(), DD4hep::Geometry::VisAttr::setLineStyle(), DD4hep::Geometry::VisAttr::setShowDaughters(), DD4hep::Geometry::VisAttr::setVisible(), and DD4hep::Geometry::VisAttr::SOLID.
~LCDDImp()
LCDDImp::~LCDDImp () virtual
Standard destructor.
Definition at line 133 of file LCDDImp.cpp.
References DD4hep::ObjectExtensions::clear(), DD4hep::InstanceCount::decrement(), DD4hep::Geometry::LCDDData::destroyData(), DD4hep::Geometry::LCDDData::m_extensions, and DD4hep::Geometry::LCDDData::m_manager.
Member Function Documentation
add() [1/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (Constant x) inline virtual
Add a new constant to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 290 of file LCDDImp.h.
Referenced by endDocument(), and init().
add() [2/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (LimitSet x) inline virtual
Add a new limit set to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 294 of file LCDDImp.h.
References addLimitSet().
add() [3/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (Region x) inline virtual
Add a new detector region to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 298 of file LCDDImp.h.
References addRegion().
add() [4/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (VisAttr x) inline virtual
Add a new visualisation attribute to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 302 of file LCDDImp.h.
References addVisAttribute().
add() [5/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (IDDescriptor x) inline virtual
Add a new id descriptor to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 306 of file LCDDImp.h.
References addIDSpecification().
add() [6/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (AlignmentEntry x) inline virtual
Add alignment entry to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 310 of file LCDDImp.h.
References addAlignment().
add() [7/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (Readout x) inline virtual
Add a new detector readout to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 314 of file LCDDImp.h.
References addReadout().
add() [8/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (SensitiveDetector x) inline virtual
Add a new sensitive detector to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 318 of file LCDDImp.h.
References addSensitiveDetector().
add() [9/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (DetElement x) inline virtual
Add a new subdetector to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 322 of file LCDDImp.h.
References addDetector().
add() [10/10]
virtual LCDD& DD4hep::Geometry::LCDDImp::add (CartesianField x) inline virtual
Add a field component to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 326 of file LCDDImp.h.
References addConstant(), and addField().
addAlignment()
virtual LCDD& DD4hep::Geometry::LCDDImp::addAlignment (const Ref_t & x) inline virtual
Add a new alignment entry by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 366 of file LCDDImp.h.
References __R, addField(), DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_alignments.
Referenced by add().
addConstant()
LCDD & LCDDImp::addConstant (const Ref_t & x) virtual
Add a new constant by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 227 of file LCDDImp.cpp.
References DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), DD4hep::NamedObject::GetTitle(), DD4hep::Geometry::LCDDData::m_define, DD4hep::Geometry::LCDDData::m_inhibitConstants, and DD4hep::Handle< T >::name().
Referenced by add().
addDetector()
LCDD & LCDDImp::addDetector (const Ref_t & x) virtual
Add a new subdetector by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 190 of file LCDDImp.cpp.
References DD4hep::Geometry::DetElement::add(), DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), DD4hep::DEBUG, DD4hep::Geometry::LCDDHelper::detectorByID(), DD4hep::ERROR, DD4hep::Geometry::DetElement::id(), DD4hep::INFO, DD4hep::Geometry::DetElementObject::IS_TOP_LEVEL_DETECTOR, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::LCDDData::m_detectors, DD4hep::Geometry::LCDDData::m_world, DD4hep::Geometry::LCDDData::m_worldVol, DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), DD4hep::printout(), DD4hep::Geometry::LCDDHelper::sensitiveDetector(), and DD4hep::Geometry::PlacedVolume::volume().
Referenced by add(), and addSensitiveDetector().
addField()
LCDD & LCDDImp::addField (const Ref_t & x) virtual
Add a field component by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 273 of file LCDDImp.cpp.
References DD4hep::Geometry::OverlayedField::add(), DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), DD4hep::Geometry::LCDDData::m_field, and DD4hep::Geometry::LCDDData::m_fields.
Referenced by add(), and addAlignment().
addIDSpecification()
virtual LCDD& DD4hep::Geometry::LCDDImp::addIDSpecification (const Ref_t & x) inline virtual
Add a new id descriptor by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 344 of file LCDDImp.h.
References __R, DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_idDict.
Referenced by add().
addLimitSet()
virtual LCDD& DD4hep::Geometry::LCDDImp::addLimitSet (const Ref_t & x) inline virtual
Add a new limit set by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 334 of file LCDDImp.h.
References __R, DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_limits.
Referenced by add().
addReadout()
virtual LCDD& DD4hep::Geometry::LCDDImp::addReadout (const Ref_t & x) inline virtual
Add a new detector readout by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 349 of file LCDDImp.h.
References __R, DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_readouts.
Referenced by add().
addRegion()
virtual LCDD& DD4hep::Geometry::LCDDImp::addRegion (const Ref_t & x) inline virtual
Add a new detector region by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 339 of file LCDDImp.h.
References __R, DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_regions.
Referenced by add().
addSensitiveDetector()
virtual LCDD& DD4hep::Geometry::LCDDImp::addSensitiveDetector (const Ref_t & x) inline virtual
Add a new sensitive detector by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 359 of file LCDDImp.h.
References __R, addDetector(), DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_sensitive.
Referenced by add().
addUserExtension()
void * LCDDImp::addUserExtension (void * ptr, const std::type_info & info, void(*)(void *) destruct) virtual
Add an extension object to the LCDD instance.
Implements DD4hep::Geometry::LCDD.
Definition at line 147 of file LCDDImp.cpp.
References DD4hep::ObjectExtensions::addExtension(), and DD4hep::Geometry::LCDDData::m_extensions.
Referenced by fromCompact().
addVisAttribute()
virtual LCDD& DD4hep::Geometry::LCDDImp::addVisAttribute (const Ref_t & x) inline virtual
Add a new visualisation attribute by named reference to the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 354 of file LCDDImp.h.
References __R, DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), and DD4hep::Geometry::LCDDData::m_display.
Referenced by add(), and LCDDImp().
air()
virtual Material DD4hep::Geometry::LCDDImp::air () const inline virtual
Return handle to material describing air.
Implements DD4hep::Geometry::LCDD.
Definition at line 123 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_materialAir.
alignment()
virtual AlignmentEntry DD4hep::Geometry::LCDDImp::alignment (const std::string & path) const inline virtual
Retrieve an alignment entry by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 203 of file LCDDImp.h.
References alignments(), and getRefChild().
alignments()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::alignments () const inline virtual
Accessor to the map of aligment entries.
Implements DD4hep::Geometry::LCDD.
Definition at line 248 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_alignments.
Referenced by alignment().
apply()
long LCDDImp::apply (const char * factory, int argc, char ** argv) virtual
Manipulate geometry using facroy converter.
Implements DD4hep::Geometry::LCDD.
Definition at line 551 of file LCDDImp.cpp.
References DD4hep::XML::_toString(), e, and DD4hep::PluginDebug::missingFactory().
Referenced by fromCompact().
buildType()
virtual LCDDBuildType DD4hep::Geometry::LCDDImp::buildType () const inline virtual
Access flag to steer the detail of building of the geometry/detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 72 of file LCDDImp.h.
References m_buildType.
constant()
Constant LCDDImp::constant (const std::string & name) const virtual
Retrieve a constant by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 238 of file LCDDImp.cpp.
References getRefChild(), DD4hep::Geometry::LCDDData::m_define, and DD4hep::Geometry::LCDDData::m_inhibitConstants.
Referenced by constantAsString(), and setHeader().
constantAsDouble()
double LCDDImp::constantAsDouble (const std::string & name) const virtual
Typed access to constants: double values.
Implements DD4hep::Geometry::LCDD.
Definition at line 265 of file LCDDImp.cpp.
References DD4hep::_toDouble(), constantAsString(), and DD4hep::Geometry::LCDDData::m_inhibitConstants.
Referenced by setHeader().
constantAsLong()
long LCDDImp::constantAsLong (const std::string & name) const virtual
Typed access to constants: long values.
Implements DD4hep::Geometry::LCDD.
Definition at line 257 of file LCDDImp.cpp.
References DD4hep::_toLong(), constantAsString(), and DD4hep::Geometry::LCDDData::m_inhibitConstants.
Referenced by setHeader().
constantAsString()
string LCDDImp::constantAsString (const std::string & name) const virtual
Typed access to constants: access string values.
Implements DD4hep::Geometry::LCDD.
Definition at line 246 of file LCDDImp.cpp.
References constant(), DD4hep::NamedObject::GetTitle(), DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::LCDDData::m_inhibitConstants.
Referenced by constantAsDouble(), constantAsLong(), and setHeader().
constants()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::constants () const inline virtual
Accessor to the map of constants.
Implements DD4hep::Geometry::LCDD.
Definition at line 220 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_define.
declareMotherVolume()
void LCDDImp::declareMotherVolume (const std::string & detector_name, const Volume & vol) virtual
Register new mother volume using the detector name.
Implements DD4hep::Geometry::LCDD.
Definition at line 162 of file LCDDImp.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::LCDDData::m_motherVolumes.
Referenced by fromCompact().
detector()
virtual DetElement DD4hep::Geometry::LCDDImp::detector (const std::string & name) const inline virtual
Retrieve a subdetector element by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 207 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_detectors.
detectors() [1/4]
virtual const HandleMap& DD4hep::Geometry::LCDDImp::detectors () const inline virtual
Accessor to the map of sub-detectors.
Implements DD4hep::Geometry::LCDD.
Definition at line 240 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_detectors.
Referenced by idSpecifications().
detectors() [2/4]
const vector< DetElement > & LCDDImp::detectors (const std::string & type, bool throw_exc) virtual
Access a set of subdetectors according to the sensitive type.
Please note:
The sensitive type of a detector is set in the 'detector constructor'.
Not sensitive detector structures have the name 'passive'
Compounds (ie. nested detectors) are of type 'compound'
If throw_exc is set to true, an exception is thrown if the type is not present. Otherwise an empty detector container is returned.
Implements DD4hep::Geometry::LCDD.
Definition at line 320 of file LCDDImp.cpp.
References m_detectorTypes, and DD4hep::Geometry::LCDDData::m_manager.
detectors() [3/4]
vector< DetElement > LCDDImp::detectors (const std::string & type1, const std::string & type2, const std::string & type3 = "", const std::string & type4 = "", const std::string & type5 = "") virtual
Access a set of subdetectors according to several sensitive types.
Implements DD4hep::Geometry::LCDD.
Definition at line 356 of file LCDDImp.cpp.
References m_detectorTypes, DD4hep::Geometry::LCDDData::m_manager, and v.
detectors() [4/4]
vector< DetElement > LCDDImp::detectors (unsigned int includeFlag, unsigned int excludeFlag = 0) const virtual
return a vector with all detectors that have all the type properties in includeFlag set but none of the properties given in excludeFlag
Implements DD4hep::Geometry::LCDD.
Definition at line 333 of file LCDDImp.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Geometry::LCDDData::m_detectors, DD4hep::Geometry::LCDDData::m_manager, DD4hep::Geometry::DetElement::parent(), and DD4hep::Geometry::DetElement::typeFlag().
detectorTypes()
vector< string > LCDDImp::detectorTypes () const virtual
Access the availible detector types.
Implements DD4hep::Geometry::LCDD.
Definition at line 309 of file LCDDImp.cpp.
References m_detectorTypes, DD4hep::Geometry::LCDDData::m_manager, and v.
Referenced by idSpecifications().
dump()
void LCDDImp::dump () const virtual
Stupid legacy method.
Implements DD4hep::Geometry::LCDD.
Definition at line 543 of file LCDDImp.cpp.
References DD4hep::Geometry::LCDDData::m_manager, and DD4hep::Geometry::LCDDData::m_worldVol.
Referenced by fromCompact().
endDocument()
void LCDDImp::endDocument () virtual
Finalize the geometry.
Since we allow now for anonymous shapes, we will rename them to use the name of the volume they are assigned to
Implements DD4hep::Geometry::LCDD.
Definition at line 458 of file LCDDImp.cpp.
References add(), DD4hep::Geometry::LCDDData::m_manager, DD4hep::Geometry::LCDDData::m_trackingVol, DD4hep::Geometry::LCDDData::m_volManager, DD4hep::Geometry::LCDDData::m_world, mapDetectorTypes(), DD4hep::Geometry::Volume::setRegion(), DD4hep::Geometry::Region::setStoreSecondaries(), DD4hep::Geometry::Region::setThreshold(), DD4hep::Geometry::Volume::setVisAttributes(), and DD4hep::Geometry::VisAttr::setVisible().
Referenced by fromCompact().
field() [1/2]
virtual OverlayedField DD4hep::Geometry::LCDDImp::field () const inline virtual
Return handle to the combined electromagentic field description.
Implements DD4hep::Geometry::LCDD.
Definition at line 155 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_field.
field() [2/2]
virtual CartesianField DD4hep::Geometry::LCDDImp::field (const std::string & name) const inline virtual
Retrieve a subdetector element by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 215 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_fields.
fields()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::fields () const inline virtual
Accessor to the map of field entries, which together form the global field.
Implements DD4hep::Geometry::LCDD.
Definition at line 252 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_fields.
fromCompact()
virtual void DD4hep::Geometry::LCDDImp::fromCompact (const std::string & fname, LCDDBuildType type = BUILD_DEFAULT) inline virtual
Read compact geometry description or alignment file.
Implements DD4hep::Geometry::LCDD.
Definition at line 77 of file LCDDImp.h.
References addUserExtension(), apply(), DD4hep::BUILD_DEFAULT, declareMotherVolume(), dump(), e, endDocument(), fromXML(), getRefChild(), init(), pickMotherVolume(), removeUserExtension(), and userExtension().
fromXML() [1/2]
void LCDDImp::fromXML (const std::string & fname, LCDDBuildType type = BUILD_DEFAULT) virtual
Read any XML file.
Read any geometry description or alignment file.
Implements DD4hep::Geometry::LCDD.
Definition at line 525 of file LCDDImp.cpp.
References m_buildType, and DD4hep::LCDDLoad::processXML().
Referenced by fromCompact().
fromXML() [2/2]
void LCDDImp::fromXML (const std::string & fname, UriReader * entity_resolver, LCDDBuildType type = BUILD_DEFAULT) virtual
Read any geometry description or alignment file with external XML entity resolution.
Implements DD4hep::Geometry::LCDD.
Definition at line 538 of file LCDDImp.cpp.
References m_buildType, and DD4hep::LCDDLoad::processXML().
getRefChild()
Handle< TObject > LCDDImp::getRefChild (const HandleMap & e, const std::string & name, bool throw_if_not = true) const virtual
Definition at line 379 of file LCDDImp.cpp.
References e, DD4hep::INFO, m, DD4hep::Geometry::LCDDData::m_volManager, DD4hep::Geometry::LCDDData::m_world, DD4hep::printout(), s, and v.
Referenced by alignment(), constant(), detector(), field(), fromCompact(), idSpecification(), limitSet(), readout(), region(), sensitiveDetector(), and visAttributes().
header()
virtual Header DD4hep::Geometry::LCDDImp::header () const inline virtual
Accessor to the header entry.
Implements DD4hep::Geometry::LCDD.
Definition at line 159 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_header.
idSpecification()
virtual IDDescriptor DD4hep::Geometry::LCDDImp::idSpecification (const std::string & name) const inline virtual
Retrieve a id descriptor by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 195 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_idDict.
idSpecifications()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::idSpecifications () const inline virtual
Accessor to the map of ID specifications.
Implements DD4hep::Geometry::LCDD.
Definition at line 256 of file LCDDImp.h.
References detectors(), detectorTypes(), and DD4hep::Geometry::LCDDData::m_idDict.
imp_loadVolumeManager()
void LCDDImp::imp_loadVolumeManager ()
Local method (no interface): Load volume manager.
Definition at line 141 of file LCDDImp.cpp.
References DD4hep::destroyHandle(), DD4hep::Geometry::LCDDData::m_volManager, DD4hep::Geometry::VolumeManager::TREE, and world().
init()
void LCDDImp::init () virtual
Initialize geometry.
Implements DD4hep::Geometry::LCDD.
Definition at line 482 of file LCDDImp.cpp.
References add(), DD4hep::Geometry::DetElement::add(), DD4hep::Geometry::LCDDData::ObjectHandleMap::append(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::LCDDData::m_detectors, DD4hep::Geometry::LCDDData::m_manager, DD4hep::Geometry::LCDDData::m_materialAir, DD4hep::Geometry::LCDDData::m_materialVacuum, M_PI, DD4hep::Geometry::LCDDData::m_trackers, DD4hep::Geometry::LCDDData::m_trackingVol, DD4hep::Geometry::LCDDData::m_world, DD4hep::Geometry::LCDDData::m_worldVol, material(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::printout(), DD4hep::Handle< T >::ptr(), DD4hep::Geometry::VisAttr::setAlpha(), DD4hep::Geometry::VisAttr::setColor(), DD4hep::Geometry::VisAttr::setDrawingStyle(), DD4hep::Geometry::VisAttr::setLineStyle(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::Geometry::VisAttr::setShowDaughters(), DD4hep::Geometry::VisAttr::setVisible(), DD4hep::Geometry::VisAttr::SOLID, and DD4hep::Geometry::VisAttr::WIREFRAME.
Referenced by fromCompact().
invisible()
virtual VisAttr DD4hep::Geometry::LCDDImp::invisible () const inline virtual
Return handle to "invisible" visualization attributes.
Implements DD4hep::Geometry::LCDD.
Definition at line 131 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_invisibleVis.
limitSet()
virtual LimitSet DD4hep::Geometry::LCDDImp::limitSet (const std::string & name) const inline virtual
Retrieve a limitset by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 180 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_limits.
limitsets()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::limitsets () const inline virtual
Accessor to the map of limit settings.
Implements DD4hep::Geometry::LCDD.
Definition at line 228 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_limits.
manager()
virtual TGeoManager& DD4hep::Geometry::LCDDImp::manager () const inline virtual
Access the geometry manager of this instance.
Implements DD4hep::Geometry::LCDD.
Definition at line 115 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_manager.
mapDetectorTypes()
void LCDDImp::mapDetectorTypes () private
Internal helper to map detector types once the geometry is closed.
Definition at line 289 of file LCDDImp.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Geometry::LCDDData::m_detectors, m_detectorTypes, DD4hep::Geometry::LCDDData::m_sensitive, DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::parent(), DD4hep::Geometry::SensitiveDetector::type(), and DD4hep::Geometry::DetElement::type().
Referenced by endDocument().
material()
Material LCDDImp::material (const std::string & name) const virtual
Retrieve a matrial by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 280 of file LCDDImp.cpp.
References DD4hep::Geometry::LCDDData::m_manager.
Referenced by init(), and visAttributes().
operator=()
LCDDImp& DD4hep::Geometry::LCDDImp::operator= (const LCDDImp & copy) private delete
Disable assignment operator.
pickMotherVolume()
Volume LCDDImp::pickMotherVolume (const DetElement & sd) const virtual
Access mother volume by detector element.
Implements DD4hep::Geometry::LCDD.
Definition at line 178 of file LCDDImp.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Geometry::LCDDData::m_motherVolumes, DD4hep::Geometry::LCDDData::m_worldVol, and DD4hep::Handle< T >::name().
Referenced by fromCompact().
properties()
Properties& DD4hep::Geometry::LCDDImp::properties () const inline virtual
Access to properties.
Implements DD4hep::Geometry::LCDD.
Definition at line 119 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_properties.
readout()
virtual Readout DD4hep::Geometry::LCDDImp::readout (const std::string & name) const inline virtual
Retrieve a readout object by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 199 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_readouts.
readouts()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::readouts () const inline virtual
Accessor to the map of readout structures.
Implements DD4hep::Geometry::LCDD.
Definition at line 236 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_readouts.
region()
virtual Region DD4hep::Geometry::LCDDImp::region (const std::string & name) const inline virtual
Retrieve a region object by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 191 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_regions.
regions()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::regions () const inline virtual
Accessor to the map of region settings.
Implements DD4hep::Geometry::LCDD.
Definition at line 232 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_regions.
removeUserExtension()
void * LCDDImp::removeUserExtension (const std::type_info & info, bool destroy = true) virtual
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
Remove an existing extension object from the LCDD instance.
Implements DD4hep::Geometry::LCDD.
Definition at line 152 of file LCDDImp.cpp.
References DD4hep::Geometry::LCDDData::m_extensions, and DD4hep::ObjectExtensions::removeExtension().
Referenced by fromCompact().
sensitiveDetector()
virtual SensitiveDetector DD4hep::Geometry::LCDDImp::sensitiveDetector (const std::string & name) const inline virtual
Retrieve a sensitive detector by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 211 of file LCDDImp.h.
References getRefChild(), and DD4hep::Geometry::LCDDData::m_sensitive.
sensitiveDetectors()
virtual const HandleMap& DD4hep::Geometry::LCDDImp::sensitiveDetectors () const inline virtual
Retrieve a sensitive detector by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 244 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_sensitive.
setHeader()
virtual void DD4hep::Geometry::LCDDImp::setHeader (Header h) inline virtual
Accessor to the header entry.
Implements DD4hep::Geometry::LCDD.
Definition at line 163 of file LCDDImp.h.
References constant(), constantAsDouble(), constantAsLong(), constantAsString(), and DD4hep::Geometry::LCDDData::m_header.
trackers()
virtual DetElement DD4hep::Geometry::LCDDImp::trackers () const inline virtual
Return reference to detector element with all tracker devices.
Implements DD4hep::Geometry::LCDD.
Definition at line 139 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_trackers.
trackingVolume()
virtual Volume DD4hep::Geometry::LCDDImp::trackingVolume () const inline virtual
Return handle to the world volume containing the volume with the tracking devices.
Implements DD4hep::Geometry::LCDD.
Definition at line 147 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_trackingVol.
userExtension()
void * LCDDImp::userExtension (const std::type_info & info, bool alert = true) const virtual
Access an existing extension object from the LCDD instance.
Implements DD4hep::Geometry::LCDD.
Definition at line 157 of file LCDDImp.cpp.
References DD4hep::ObjectExtensions::extension(), and DD4hep::Geometry::LCDDData::m_extensions.
Referenced by fromCompact().
vacuum()
virtual Material DD4hep::Geometry::LCDDImp::vacuum () const inline virtual
Return handle to material describing vacuum.
Implements DD4hep::Geometry::LCDD.
Definition at line 127 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_materialVacuum.
visAttributes() [1/2]
virtual VisAttr DD4hep::Geometry::LCDDImp::visAttributes (const std::string & name) const inline virtual
Retrieve a visualization attribute by it's name from the detector description.
Implements DD4hep::Geometry::LCDD.
Definition at line 184 of file LCDDImp.h.
References getRefChild(), DD4hep::Geometry::LCDDData::m_display, and material().
visAttributes() [2/2]
virtual const HandleMap& DD4hep::Geometry::LCDDImp::visAttributes () const inline virtual
Accessor to the map of visualisation attributes.
Implements DD4hep::Geometry::LCDD.
Definition at line 224 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_display.
volumeManager()
virtual VolumeManager DD4hep::Geometry::LCDDImp::volumeManager () const inline virtual
Return handle to the VolumeManager.
Implements DD4hep::Geometry::LCDD.
Definition at line 151 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_volManager.
world()
virtual DetElement DD4hep::Geometry::LCDDImp::world () const inline virtual
Return reference to the top-most (world) detector element.
Implements DD4hep::Geometry::LCDD.
Definition at line 135 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_world.
Referenced by imp_loadVolumeManager().
worldVolume()
virtual Volume DD4hep::Geometry::LCDDImp::worldVolume () const inline virtual
Return handle to the world volume containing everything.
Implements DD4hep::Geometry::LCDD.
Definition at line 143 of file LCDDImp.h.
References DD4hep::Geometry::LCDDData::m_worldVol.
Member Data Documentation
m_buildType
LCDDBuildType DD4hep::Geometry::LCDDImp::m_buildType protected
VolumeManager m_volManager;.
Definition at line 49 of file LCDDImp.h.
Referenced by buildType(), and fromXML().
m_detectorTypes
DetectorTypeMap DD4hep::Geometry::LCDDImp::m_detectorTypes protected
Inventory of detector types.
Definition at line 46 of file LCDDImp.h.
Referenced by detectors(), detectorTypes(), and mapDetectorTypes().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/LCDDImp.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/LCDDImp.cpp