DD4hep: DD4hep::Geometry::GeometryTreeDump Class Reference
DD4hep::Geometry::GeometryTreeDump Class Reference
DD4hep::Geometry components, classes and objects
Geometry to screen dump action.
#include <GeometryTreeDump.h>
Public Member Functions
GeometryTreeDump ()
virtual ~GeometryTreeDump ()
Standard destructor.
void create (DetElement top)
Main entry point: create required object(s)
virtual void * handleVolume (const std::string &name, Volume volume) const
Dump logical volume in GDML format to output stream.
virtual void * handleTransformation (const std::string &name, const TGeoMatrix *matrix) const
Dump single volume transformation in GDML format to output stream.
virtual void * handleSolid (const std::string &name, const TGeoShape *volume) const
Dump solid in GDML format to output stream.
virtual void handleDefines (const LCDD::HandleMap &defs) const
Dump all constants in GDML format to output stream.
void handleVisualisation (const LCDD::HandleMap &vis) const
Dump all visualisation specs in LCDD format to output stream.
virtual void handleSolids (const SolidSet &solids) const
Dump all solids in GDML format to output stream.
virtual void handleTransformations (const TransformSet &trafos) const
Dump Transformations in GDML format to output stream.
virtual void handleStructure (const VolumeSet &volset) const
Dump structure information in GDML format to output stream.
Public Member Functions inherited from DD4hep::Geometry::GeoHandler
GeoHandler ()
Default constructor.
GeoHandler (Data *ptr)
Initializing constructor.
virtual ~GeoHandler ()
Default destructor.
bool setPropagateRegions (bool value)
Propagate regions. Returns the previous value.
GeoHandler & collect (DetElement top)
Collect geometry information from traversal.
GeoHandler & collect (DetElement top, GeometryInfo &info)
Collect geometry information from traversal with aggregated information.
Data * release ()
Access to collected node list.
Additional Inherited Members
Public Types inherited from DD4hep::Geometry::GeoHandlerTypes
typedef std::set< Volume > VolumeSet
typedef std::vector< Volume > VolumeVector
typedef std::set< const TGeoVolume * > ConstVolumeSet
typedef std::vector< std::pair< std::string, TGeoMatrix * > > TransformSet
typedef std::set< TGeoShape * > SolidSet
typedef std::set< Material > MaterialSet
typedef std::map< SensitiveDetector, ConstVolumeSet > SensitiveVolumes
typedef std::map< Region, ConstVolumeSet > RegionVolumes
typedef std::map< LimitSet, ConstVolumeSet > LimitVolumes
typedef std::map< int, std::set< const TGeoNode * > > Data
typedef std::set< VisAttr > VisRefs
typedef std::set< SensitiveDetector > SensitiveDetectorSet
typedef std::set< Region > RegionSet
typedef std::set< LimitSet > LimitSetSet
typedef std::set< Ref_t > Fields
typedef std::set< TNamed * > ObjectSet
typedef LCDD::HandleMap DefinitionSet
Protected Member Functions inherited from DD4hep::Geometry::GeoHandler
GeoHandler & i_collect (const TGeoNode *node, int level, Region rg, LimitSet ls)
Internal helper to collect geometry information from traversal.
Protected Attributes inherited from DD4hep::Geometry::GeoHandler
bool m_propagateRegions
Data * m_data
Detailed Description
Geometry to screen dump action.
Author
M.Frank
Version
1.0
Definition at line 38 of file GeometryTreeDump.h.
Constructor & Destructor Documentation
GeometryTreeDump()
DD4hep::Geometry::GeometryTreeDump::GeometryTreeDump () inline
Definition at line 40 of file GeometryTreeDump.h.
~GeometryTreeDump()
virtual DD4hep::Geometry::GeometryTreeDump::~GeometryTreeDump () inline virtual
Standard destructor.
Definition at line 43 of file GeometryTreeDump.h.
References create(), handleDefines(), handleSolid(), handleSolids(), handleStructure(), handleTransformation(), handleTransformations(), handleVisualisation(), and handleVolume().
Member Function Documentation
create()
void GeometryTreeDump::create (DetElement top)
Main entry point: create required object(s)
Definition at line 295 of file GeometryTreeDump.cpp.
References dumpDetectors(), dumpStructure(), and DD4hep::Geometry::DetElement::placement().
Referenced by ~GeometryTreeDump().
handleDefines()
void GeometryTreeDump::handleDefines (const LCDD::HandleMap & defs) const virtual
Dump all constants in GDML format to output stream.
Definition at line 240 of file GeometryTreeDump.cpp.
Referenced by ~GeometryTreeDump().
handleSolid()
void * GeometryTreeDump::handleSolid (const std::string & name, const TGeoShape * volume) const virtual
Dump solid in GDML format to output stream.
Definition at line 108 of file GeometryTreeDump.cpp.
References s.
Referenced by ~GeometryTreeDump().
handleSolids()
void GeometryTreeDump::handleSolids (const SolidSet & solids) const virtual
Dump all solids in GDML format to output stream.
Definition at line 232 of file GeometryTreeDump.cpp.
Referenced by ~GeometryTreeDump().
handleStructure()
void GeometryTreeDump::handleStructure (const VolumeSet & volset) const virtual
Dump structure information in GDML format to output stream.
Definition at line 193 of file GeometryTreeDump.cpp.
Referenced by ~GeometryTreeDump().
handleTransformation()
void * GeometryTreeDump::handleTransformation (const std::string & name, const TGeoMatrix * matrix) const virtual
Dump single volume transformation in GDML format to output stream.
Definition at line 201 of file GeometryTreeDump.cpp.
Referenced by ~GeometryTreeDump().
handleTransformations()
void GeometryTreeDump::handleTransformations (const TransformSet & trafos) const virtual
Dump Transformations in GDML format to output stream.
Definition at line 224 of file GeometryTreeDump.cpp.
Referenced by ~GeometryTreeDump().
handleVisualisation()
void GeometryTreeDump::handleVisualisation (const LCDD::HandleMap & vis) const
Dump all visualisation specs in LCDD format to output stream.
Definition at line 249 of file GeometryTreeDump.cpp.
Referenced by ~GeometryTreeDump().
handleVolume()
void * GeometryTreeDump::handleVolume (const std::string & name, Volume volume) const virtual
Dump logical volume in GDML format to output stream.
Definition at line 72 of file GeometryTreeDump.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), DD4hep::Handle< T >::ptr(), v, and DD4hep::Geometry::Volume::visAttributes().
Referenced by ~GeometryTreeDump().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/GeometryTreeDump.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/GeometryTreeDump.cpp