DD4hep: DD4hep::DDRec::LayeringExtensionImpl Class Reference
DD4hep::DDRec::LayeringExtensionImpl Class Reference
#include <LayeringExtensionImpl.h>
Classes
struct LayerAttributes
Helper class to store layer attributes.
Public Types
typedef Geometry::Position Position
Shortcut to use geometrical positions.
Public Member Functions
LayeringExtensionImpl ()
Default constructor.
LayeringExtensionImpl (const LayeringExtensionImpl &, const Geometry::DetElement &)
Copy constructor.
virtual ~LayeringExtensionImpl ()
Destructor.
virtual int numberOfLayers () const
Access to the total number of layers.
virtual int numberOfSensors (int layerIndex) const
Access to the total number of sensors in a given layer index.
virtual Geometry::DetElement layer (int layerIndex) const
Access to the layer DetElement for the given index.
virtual const std::vector< Geometry::DetElement > & sensors (int layerIndex) const
Access to the sensitive DetElements of a given layer index.
virtual const std::vector< Geometry::DetElement > & absorbers (int layerIndex) const
Access to the non-sensitive DetElements of a given layer index.
virtual double totalThickness () const
Access the total thickness of the sub detector.
virtual double totalRadiationLength () const
Access the total radiation length of the sub detector.
virtual double totalInteractionLength () const
Access the total nuclear interaction length of the sub detector.
virtual double thickness (int layerIndex) const
Access the total thickness of the layer with the given index.
virtual double radiationLength (int layerIndex) const
Access the total radiation length of the layer with the given index.
virtual double interactionLength (int layerIndex) const
Access the total nuclear interaction length of the layer with the given index.
virtual double absorberThickness (int layerIndex) const
Access the total thickness of all non-sensitive elements of the layer with the given index.
virtual double absorberRadiationLength (int layerIndex) const
Access the total radiation length of all non-sensitive elements of the layer with the given index.
virtual double absorberInteractionLength (int layerIndex) const
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
virtual double sensorThickness (int layerIndex) const
Access the total thickness of all sensitive elements of the layer with the given index.
virtual double sensorRadiationLength (int layerIndex) const
Access the total radiation length of all sensitive elements of the layer with the given index.
virtual double sensorInteractionLength (int layerIndex) const
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
void setLayer (int layerIndex, Geometry::DetElement layer, const Position &normal)
Stores the layer information for the given layer index.
Public Member Functions inherited from DD4hep::DDRec::LayeringExtension
virtual ~LayeringExtension ()
Destructor.
Protected Member Functions
void checkMap (int layerIndex) const
Map to store layer attributes.
Protected Member Functions inherited from DD4hep::DDRec::LayeringExtension
LayeringExtension ()
Protected Attributes
std::map< int, LayerAttributes > _layerMap
Detailed Description
Definition at line 28 of file LayeringExtensionImpl.h.
Member Typedef Documentation
Position
typedef Geometry::Position DD4hep::DDRec::LayeringExtensionImpl::Position
Shortcut to use geometrical positions.
Definition at line 31 of file LayeringExtensionImpl.h.
Constructor & Destructor Documentation
LayeringExtensionImpl() [1/2]
DD4hep::DDRec::LayeringExtensionImpl::LayeringExtensionImpl ()
Default constructor.
Definition at line 23 of file LayeringExtensionImpl.cpp.
LayeringExtensionImpl() [2/2]
DD4hep::DDRec::LayeringExtensionImpl::LayeringExtensionImpl (const LayeringExtensionImpl & , const Geometry::DetElement &) inline
Copy constructor.
Definition at line 37 of file LayeringExtensionImpl.h.
References absorberInteractionLength(), absorberRadiationLength(), absorbers(), absorberThickness(), interactionLength(), layer(), numberOfLayers(), numberOfSensors(), radiationLength(), sensorInteractionLength(), sensorRadiationLength(), sensors(), sensorThickness(), setLayer(), thickness(), totalInteractionLength(), totalRadiationLength(), totalThickness(), and ~LayeringExtensionImpl().
~LayeringExtensionImpl()
DD4hep::DDRec::LayeringExtensionImpl::~LayeringExtensionImpl () virtual
Destructor.
Copy constructor.
Destructor
Definition at line 30 of file LayeringExtensionImpl.cpp.
Referenced by LayeringExtensionImpl().
Member Function Documentation
absorberInteractionLength()
double DD4hep::DDRec::LayeringExtensionImpl::absorberInteractionLength (int layerIndex) const virtual
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 138 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
absorberRadiationLength()
double DD4hep::DDRec::LayeringExtensionImpl::absorberRadiationLength (int layerIndex) const virtual
Access the total radiation length of all non-sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 132 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
absorbers()
const vector< DetElement > & DD4hep::DDRec::LayeringExtensionImpl::absorbers (int layerIndex) const virtual
Access to the non-sensitive DetElements of a given layer index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 57 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
absorberThickness()
double DD4hep::DDRec::LayeringExtensionImpl::absorberThickness (int layerIndex) const virtual
Access the total thickness of all non-sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 126 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
checkMap()
void DD4hep::DDRec::LayeringExtensionImpl::checkMap (int layerIndex) const protected
Map to store layer attributes.
Helper method to check validity of layer entry.
Helper method to check validity of layer entry
Definition at line 170 of file LayeringExtensionImpl.cpp.
References _layerMap.
Referenced by absorberInteractionLength(), absorberRadiationLength(), absorbers(), absorberThickness(), interactionLength(), layer(), numberOfSensors(), radiationLength(), sensorInteractionLength(), sensorRadiationLength(), sensors(), sensorThickness(), and thickness().
interactionLength()
double DD4hep::DDRec::LayeringExtensionImpl::interactionLength (int layerIndex) const virtual
Access the total nuclear interaction length of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 120 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
layer()
DetElement DD4hep::DDRec::LayeringExtensionImpl::layer (int layerIndex) const virtual
Access to the layer DetElement for the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 45 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
numberOfLayers()
int DD4hep::DDRec::LayeringExtensionImpl::numberOfLayers () const virtual
Access to the total number of layers.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 34 of file LayeringExtensionImpl.cpp.
References _layerMap.
Referenced by LayeringExtensionImpl().
numberOfSensors()
int DD4hep::DDRec::LayeringExtensionImpl::numberOfSensors (int layerIndex) const virtual
Access to the total number of sensors in a given layer index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 39 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
radiationLength()
double DD4hep::DDRec::LayeringExtensionImpl::radiationLength (int layerIndex) const virtual
Access the total radiation length of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 114 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
sensorInteractionLength()
double DD4hep::DDRec::LayeringExtensionImpl::sensorInteractionLength (int layerIndex) const virtual
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 156 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
sensorRadiationLength()
double DD4hep::DDRec::LayeringExtensionImpl::sensorRadiationLength (int layerIndex) const virtual
Access the total radiation length of all sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 150 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
sensors()
const vector< DetElement > & DD4hep::DDRec::LayeringExtensionImpl::sensors (int layerIndex) const virtual
Access to the sensitive DetElements of a given layer index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 51 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
sensorThickness()
double DD4hep::DDRec::LayeringExtensionImpl::sensorThickness (int layerIndex) const virtual
Access the total thickness of all sensitive elements of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 144 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
setLayer()
void DD4hep::DDRec::LayeringExtensionImpl::setLayer (int layerIndex, Geometry::DetElement layer, const Position & normal)
Stores the layer information for the given layer index.
Definition at line 162 of file LayeringExtensionImpl.cpp.
References _layerMap, DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::isCalculated, DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::layer, and DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::normal.
Referenced by LayeringExtensionImpl().
thickness()
double DD4hep::DDRec::LayeringExtensionImpl::thickness (int layerIndex) const virtual
Access the total thickness of the layer with the given index.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 108 of file LayeringExtensionImpl.cpp.
References _layerMap, and checkMap().
Referenced by LayeringExtensionImpl().
totalInteractionLength()
double DD4hep::DDRec::LayeringExtensionImpl::totalInteractionLength () const virtual
Access the total nuclear interaction length of the sub detector.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 93 of file LayeringExtensionImpl.cpp.
References _layerMap, DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::calculate(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::interactionLength, and DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::isCalculated.
Referenced by LayeringExtensionImpl().
totalRadiationLength()
double DD4hep::DDRec::LayeringExtensionImpl::totalRadiationLength () const virtual
Access the total radiation length of the sub detector.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 78 of file LayeringExtensionImpl.cpp.
References _layerMap, DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::calculate(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::isCalculated, and DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::radiationLength.
Referenced by LayeringExtensionImpl().
totalThickness()
double DD4hep::DDRec::LayeringExtensionImpl::totalThickness () const virtual
Access the total thickness of the sub detector.
Implements DD4hep::DDRec::LayeringExtension.
Definition at line 63 of file LayeringExtensionImpl.cpp.
References _layerMap, DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::calculate(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::isCalculated, and DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::thickness.
Referenced by LayeringExtensionImpl().
Member Data Documentation
_layerMap
std::map<int, LayerAttributes> DD4hep::DDRec::LayeringExtensionImpl::_layerMap mutable protected
Definition at line 121 of file LayeringExtensionImpl.h.
Referenced by absorberInteractionLength(), absorberRadiationLength(), absorbers(), absorberThickness(), checkMap(), interactionLength(), layer(), numberOfLayers(), numberOfSensors(), radiationLength(), sensorInteractionLength(), sensorRadiationLength(), sensors(), sensorThickness(), setLayer(), thickness(), totalInteractionLength(), totalRadiationLength(), and totalThickness().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Extensions/LayeringExtensionImpl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/LayeringExtensionImpl.cpp