DD4hep: DD4hep::Simulation::Geant4MonteCarloTruth Class Reference
DD4hep::Simulation::Geant4MonteCarloTruth Class Reference abstract
DD4hep::Simulation components, classes and objects
Default Interface class to handle monte carlo truth records.
#include <Geant4MonteCarloTruth.h>
Public Member Functions
virtual ~Geant4MonteCarloTruth ()
Default destructor.
virtual void mark (const G4Track *track)=0
Mark a Geant4 track to be kept for later MC truth analysis.
virtual void mark (const G4Track *track, int reason)=0
Store a track, with a flag.
virtual void mark (const G4Step *step)=0
Mark a Geant4 track of the step to be kept for later MC truth analysis.
virtual void mark (const G4Step *step, int reason)=0
Store a track produced in a step to be kept for later MC truth analysis.
Protected Member Functions
Geant4MonteCarloTruth ()
Standard constructor.
Detailed Description
Default Interface class to handle monte carlo truth records.
Author
M.Frank
Version
1.0
Definition at line 44 of file Geant4MonteCarloTruth.h.
Constructor & Destructor Documentation
Geant4MonteCarloTruth()
Geant4MonteCarloTruth::Geant4MonteCarloTruth () protected
Standard constructor.
Standard action constructor.
Definition at line 22 of file Geant4MonteCarloTruth.cpp.
References DD4hep::InstanceCount::increment().
~Geant4MonteCarloTruth()
Geant4MonteCarloTruth::~Geant4MonteCarloTruth () virtual
Default destructor.
Definition at line 27 of file Geant4MonteCarloTruth.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
mark() [1/4]
virtual void DD4hep::Simulation::Geant4MonteCarloTruth::mark (const G4Track * track) pure virtual
Mark a Geant4 track to be kept for later MC truth analysis.
Implemented in DD4hep::Simulation::Geant4ParticleHandler, and DD4hep::Simulation::Geant4DummyTruthHandler.
Referenced by DD4hep::Simulation::Geant4TrackingAction::mark(), and DD4hep::Simulation::Geant4Sensitive::mark().
mark() [2/4]
virtual void DD4hep::Simulation::Geant4MonteCarloTruth::mark (const G4Track * track, int reason) pure virtual
Store a track, with a flag.
Implemented in DD4hep::Simulation::Geant4ParticleHandler, and DD4hep::Simulation::Geant4DummyTruthHandler.
mark() [3/4]
virtual void DD4hep::Simulation::Geant4MonteCarloTruth::mark (const G4Step * step) pure virtual
Mark a Geant4 track of the step to be kept for later MC truth analysis.
Implemented in DD4hep::Simulation::Geant4ParticleHandler, and DD4hep::Simulation::Geant4DummyTruthHandler.
mark() [4/4]
virtual void DD4hep::Simulation::Geant4MonteCarloTruth::mark (const G4Step * step, int reason) pure virtual
Store a track produced in a step to be kept for later MC truth analysis.
Implemented in DD4hep::Simulation::Geant4ParticleHandler, and DD4hep::Simulation::Geant4DummyTruthHandler.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4MonteCarloTruth.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4MonteCarloTruth.cpp