DD4hep: DD4hep: DD4hep::Simulation::Geant4GeneratorActionSequence Class Reference
DD4hep::Simulation::Geant4GeneratorActionSequence Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete implementation of the Geant4 generator action sequence.
#include <Geant4GeneratorAction.h>
Public Member Functions
Geant4GeneratorActionSequence (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4GeneratorActionSequence ()
Default destructor.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
Geant4GeneratorAction * get (const std::string &name) const
Get an action by name.
template<typename Q , typename T >
void call (Q *p, void(T::*f)(G4Event *))
Register primary particle generation callback. Types Q and T must be polymorph!
void adopt (Geant4GeneratorAction *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void operator() (G4Event *event)
Callback to generate primary particles.
Protected Attributes
CallbackSequence m_calls
Callback sequence to generate primary particles.
Actors< Geant4GeneratorAction > m_actors
The list of action objects to be called.
Detailed Description
Concrete implementation of the Geant4 generator action sequence.
The sequence dispatches the callbacks at the beginning of an event to all registered Geant4GeneratorAction members and all registered callbacks.
The callback signature is: void operator()(G4Event* event)
Note Multi-Threading issue: Neither callbacks not the action list is protected against multiple threads calling the Geant4 callbacks! These must be protected in the user actions themselves.
Author:
M.Frank
Version:
1.0
Definition at line 110 of file Geant4GeneratorAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4GeneratorActionSequence::Geant4GeneratorActionSequence (Geant4Context * context, const std::string & name)
Standard constructor.
Geant4GeneratorActionSequence::~Geant4GeneratorActionSequence () [virtual]
Default destructor.
Definition at line 88 of file Geant4GeneratorAction.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_calls, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
void Geant4GeneratorActionSequence::adopt (Geant4GeneratorAction * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 112 of file Geant4GeneratorAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by DD4hep::Converter< T, ARG >::operator()().
template<typename Q , typename T > void DD4hep::Simulation::Geant4GeneratorActionSequence::call (Q * p, void(T::*)(G4Event *) f) [inline]
Register primary particle generation callback. Types Q and T must be polymorph!
Definition at line 129 of file Geant4GeneratorAction.h.
References DD4hep::CallbackSequence::add(), and m_calls.
Referenced by DD4hep::Converter< T, ARG >::operator()().
void Geant4GeneratorActionSequence::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 102 of file Geant4GeneratorAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_actors.
Geant4GeneratorAction* DD4hep::Simulation::Geant4GeneratorActionSequence::get (const std::string & name) const
Get an action by name.
void Geant4GeneratorActionSequence::operator() (G4Event * event) [virtual]
Callback to generate primary particles.
Generator callback.
Definition at line 123 of file Geant4GeneratorAction.cpp.
References m_actors, and m_calls.
void Geant4GeneratorActionSequence::updateContext (Geant4Context * ctxt) [virtual]
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 96 of file Geant4GeneratorAction.cpp.
References m_actors, and DD4hep::Simulation::Geant4Action::m_context.
Member Data Documentation
Actors<Geant4GeneratorAction> DD4hep::Simulation::Geant4GeneratorActionSequence::m_actors [protected]
The list of action objects to be called.
Definition at line 115 of file Geant4GeneratorAction.h.
Referenced by adopt(), configureFiber(), operator()(), updateContext(), and ~Geant4GeneratorActionSequence().
CallbackSequence DD4hep::Simulation::Geant4GeneratorActionSequence::m_calls [protected]
Callback sequence to generate primary particles.
Definition at line 113 of file Geant4GeneratorAction.h.
Referenced by call(), operator()(), and ~Geant4GeneratorActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4GeneratorAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4GeneratorAction.cpp