DD4hep: DD4hep: DD4hep::Geometry::CartesianGridYZ Class Reference
DD4hep::Geometry::CartesianGridYZ Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid YZ segmentation.
#include <CartesianGridYZ.h>
Public Types
typedef
CartesianGridYZHandle::Implementation Object
Defintiion of the basic handled object.
Public Member Functions
CartesianGridYZ ()
Default constructor.
CartesianGridYZ (const CartesianGridYZ &e)
Copy constructor.
CartesianGridYZ (const Segmentation &e)
Copy Constructor from segmentation base object.
CartesianGridYZ (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
CartesianGridYZ (const Handle< Q > &e)
Copy constructor from other polymorph/equivalent handle.
CartesianGridYZ & operator= (const CartesianGridYZ &seg)
Assignment operator.
bool operator== (const CartesianGridYZ &seg) const
Equality operator.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
double gridSizeY () const
access the grid size in Y
double gridSizeZ () const
access the grid size in Z
void setGridSizeY (double cellSize) const
set the grid size in Y
void setGridSizeZ (double cellSize) const
set the grid size in Z
double offsetY () const
access the coordinate offset in Y
double offsetZ () const
access the coordinate offset in Z
void setOffsetY (double offset) const
set the coordinate offset in Y
void setOffsetZ (double offset) const
set the coordinate offset in Z
const std::string & fieldNameX () const
access the field name used for X
const std::string & fieldNameY () const
access the field name used for Y
const std::string & fieldNameZ () const
access the field name used for Z
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid YZ segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 58 of file CartesianGridYZ.h.
Member Typedef Documentation
typedef CartesianGridYZHandle::Implementation DD4hep::Geometry::CartesianGridYZ::Object
Defintiion of the basic handled object.
Definition at line 61 of file CartesianGridYZ.h.
Constructor & Destructor Documentation
DD4hep::Geometry::CartesianGridYZ::CartesianGridYZ ()
Default constructor.
DD4hep::Geometry::CartesianGridYZ::CartesianGridYZ (const CartesianGridYZ & e)
Copy constructor.
DD4hep::Geometry::CartesianGridYZ::CartesianGridYZ (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 69 of file CartesianGridYZ.h.
DD4hep::Geometry::CartesianGridYZ::CartesianGridYZ (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 71 of file CartesianGridYZ.h.
template<typename Q > DD4hep::Geometry::CartesianGridYZ::CartesianGridYZ (const Handle< Q > & e) [inline]
Copy constructor from other polymorph/equivalent handle.
Definition at line 74 of file CartesianGridYZ.h.
Member Function Documentation
vector< double > CartesianGridYZ::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in y
size in z
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in y
size in z
Definition at line 96 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID CartesianGridYZ::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 30 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
const std::string& DD4hep::Geometry::CartesianGridYZ::fieldNameX () const
access the field name used for X
const string & CartesianGridYZ::fieldNameY () const
access the field name used for Y
Definition at line 78 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
const string & CartesianGridYZ::fieldNameZ () const
access the field name used for Z
Definition at line 83 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridYZ::gridSizeY () const
access the grid size in Y
Definition at line 38 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridYZ::gridSizeZ () const
access the grid size in Z
Definition at line 43 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridYZ::offsetY () const
access the coordinate offset in Y
Definition at line 58 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
double CartesianGridYZ::offsetZ () const
access the coordinate offset in Z
Definition at line 63 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
CartesianGridYZ& DD4hep::Geometry::CartesianGridYZ::operator= (const CartesianGridYZ & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::CartesianGridYZ::operator== (const CartesianGridYZ & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 78 of file CartesianGridYZ.h.
References DD4hep::Handle< T >::m_element.
Position CartesianGridYZ::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 25 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridYZ::setGridSizeY (double cellSize) const
set the grid size in Y
Definition at line 48 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridYZ::setGridSizeZ (double cellSize) const
set the grid size in Z
Definition at line 53 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridYZ::setOffsetY (double offset) const
set the coordinate offset in Y
Definition at line 68 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
void CartesianGridYZ::setOffsetZ (double offset) const
set the coordinate offset in Z
Definition at line 73 of file CartesianGridYZ.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/CartesianGridYZ.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/CartesianGridYZ.cpp