DD4hep: DD4hep::DDSegmentation::ProjectiveCylinder Class Reference
DD4hep::DDSegmentation::ProjectiveCylinder Class Reference
#include <ProjectiveCylinder.h>
Public Member Functions
ProjectiveCylinder (const std::string &cellEncoding)
default constructor using an arbitrary type
ProjectiveCylinder (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
virtual ~ProjectiveCylinder ()
destructor
virtual Vector3D position (const CellID &cellID) const
determine the position based on the cell ID
virtual CellID cellID (const Vector3D &localPosition, const Vector3D &globalPosition, const VolumeID &volumeID) const
determine the cell ID based on the position
double theta (const CellID &cellID) const
determine the polar angle theta based on the cell ID
double phi (const CellID &cellID) const
determine the azimuthal angle phi based on the cell ID
int thetaBins () const
access the number of bins in theta
int phiBins () const
access the number of bins in theta
double offsetTheta () const
access the coordinate offset in theta
double offsetPhi () const
access the coordinate offset in phi
std::string fieldNameTheta () const
access the field name used for theta
std::string fieldNamePhi () const
access the field name used for phi
void setThetaBins (int bins)
set the number of bins in theta
void setPhiBins (int bins)
set the number of bins in phi
void setOffsetTheta (double offset)
set the coordinate offset in theta
void setOffsetPhi (double offset)
set the coordinate offset in phi
void setFieldNameTheta (const std::string &fieldName)
set the field name used for theta
void setFieldNamePhi (const std::string &fieldName)
set the field name used for phi
Public Member Functions inherited from DD4hep::DDSegmentation::CylindricalSegmentation
virtual ~CylindricalSegmentation ()
destructor
Public Member Functions inherited from DD4hep::DDSegmentation::Segmentation
virtual ~Segmentation ()
Destructor.
virtual void addSubsegmentation (long key_min, long key_max, Segmentation *entry)
Add subsegmentation. Call only valid for Multi-segmentations. Default implementation throws an exception.
virtual VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
virtual void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
virtual std::string fieldDescription () const
Access the encoding string.
virtual const std::string & name () const
Access the segmentation name.
virtual void setName (const std::string &value)
Set the segmentation name.
virtual const std::string & type () const
Access the segmentation type.
virtual const std::string & description () const
Access the description of the segmentation.
virtual BitField64 * decoder () const
Access the underlying decoder.
virtual void setDecoder (BitField64 *decoder)
Set the underlying decoder.
virtual Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
virtual Parameters parameters () const
Access to all parameters.
virtual void setParameters (const Parameters &parameters)
Set all parameters from an existing set of parameters.
virtual std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Protected Member Functions
double theta () const
determine the polar angle theta based on the current cell ID
double phi () const
determine the azimuthal angle phi based on the current cell ID
Protected Member Functions inherited from DD4hep::DDSegmentation::CylindricalSegmentation
CylindricalSegmentation (const std::string &cellEncoding)
default constructor using an arbitrary type
CylindricalSegmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
Segmentation (const std::string &cellEncoding="")
Default constructor used by derived classes passing the encoding string.
Segmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
template<typename TYPE >
void registerParameter (const std::string &nam, const std::string &desc, TYPE &param, const TYPE &defaultVal, UnitType unitTyp=SegmentationParameter::NoUnit, bool isOpt=false)
Add a parameter to this segmentation. Used by derived classes to define their parameters.
void registerIdentifier (const std::string &nam, const std::string &desc, std::string &ident, const std::string &defaultVal)
Add a cell identifier to this segmentation. Used by derived classes to define their required identifiers.
Protected Attributes
int _thetaBins
the number of bins in theta
int _phiBins
the number of bins in phi
double _offsetTheta
the coordinate offset in theta
double _offsetPhi
the coordinate offset in phi
std::string _thetaID
the field name used for theta
std::string _phiID
the field name used for phi
Protected Attributes inherited from DD4hep::DDSegmentation::Segmentation
std::string _name
The segmentation name.
std::string _type
The segmentation type.
std::string _description
The description of the segmentation.
std::map< std::string, Parameter > _parameters
The parameters for this segmentation.
std::map< std::string, StringParameter > _indexIdentifiers
The indices used for the encoding.
BitField64 * _decoder
The cell ID encoder and decoder.
bool _ownsDecoder
Keeps track of the decoder ownership.
Additional Inherited Members
Static Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
static double binToPosition (CellID bin, double cellSize, double offset=0.)
Helper method to convert a bin number to a 1D position.
static int positionToBin (double position, double cellSize, double offset=0.)
Helper method to convert a 1D position to a cell ID.
static double binToPosition (CellID bin, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a bin number to a 1D position given a vector of binBoundaries.
static int positionToBin (double position, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a 1D position to a cell ID given a vector of binBoundaries.
Detailed Description
Definition at line 16 of file ProjectiveCylinder.h.
Constructor & Destructor Documentation
ProjectiveCylinder() [1/2]
DD4hep::DDSegmentation::ProjectiveCylinder::ProjectiveCylinder (const std::string & cellEncoding)
default constructor using an arbitrary type
default constructor using an encoding string
Definition at line 21 of file ProjectiveCylinder.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, _offsetPhi, _offsetTheta, _phiBins, _phiID, _thetaBins, _thetaID, DD4hep::DDSegmentation::Segmentation::_type, DD4hep::DDSegmentation::SegmentationParameter::AngleUnit, DD4hep::DDSegmentation::Segmentation::registerIdentifier(), and DD4hep::DDSegmentation::Segmentation::registerParameter().
ProjectiveCylinder() [2/2]
DD4hep::DDSegmentation::ProjectiveCylinder::ProjectiveCylinder (BitField64 * decoder)
Default constructor used by derived classes passing an existing decoder.
Definition at line 38 of file ProjectiveCylinder.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, _offsetPhi, _offsetTheta, _phiBins, _phiID, _thetaBins, _thetaID, DD4hep::DDSegmentation::Segmentation::_type, DD4hep::DDSegmentation::SegmentationParameter::AngleUnit, DD4hep::DDSegmentation::Segmentation::registerIdentifier(), and DD4hep::DDSegmentation::Segmentation::registerParameter().
~ProjectiveCylinder()
DD4hep::DDSegmentation::ProjectiveCylinder::~ProjectiveCylinder () virtual
destructor
Definition at line 53 of file ProjectiveCylinder.cpp.
Member Function Documentation
cellID()
CellID DD4hep::DDSegmentation::ProjectiveCylinder::cellID (const Vector3D & localPosition, const Vector3D & globalPosition, const VolumeID & volumeID) const virtual
determine the cell ID based on the position
Implements DD4hep::DDSegmentation::Segmentation.
Definition at line 64 of file ProjectiveCylinder.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, _offsetPhi, _offsetTheta, _phiBins, _phiID, _thetaBins, _thetaID, DD4hep::DDSegmentation::BitField64::getValue(), M_PI, DD4hep::DDSegmentation::Util::phiFromXYZ(), DD4hep::DDSegmentation::Segmentation::positionToBin(), DD4hep::DDSegmentation::BitField64::setValue(), and DD4hep::DDSegmentation::Util::thetaFromXYZ().
fieldNamePhi()
std::string DD4hep::DDSegmentation::ProjectiveCylinder::fieldNamePhi () const inline
access the field name used for phi
Definition at line 54 of file ProjectiveCylinder.h.
References _phiID.
fieldNameTheta()
std::string DD4hep::DDSegmentation::ProjectiveCylinder::fieldNameTheta () const inline
access the field name used for theta
Definition at line 50 of file ProjectiveCylinder.h.
References _thetaID.
offsetPhi()
double DD4hep::DDSegmentation::ProjectiveCylinder::offsetPhi () const inline
access the coordinate offset in phi
Definition at line 46 of file ProjectiveCylinder.h.
References _offsetPhi.
offsetTheta()
double DD4hep::DDSegmentation::ProjectiveCylinder::offsetTheta () const inline
access the coordinate offset in theta
Definition at line 42 of file ProjectiveCylinder.h.
References _offsetTheta.
phi() [1/2]
double DD4hep::DDSegmentation::ProjectiveCylinder::phi (const CellID & cellID) const
determine the azimuthal angle phi based on the cell ID
Definition at line 91 of file ProjectiveCylinder.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, _phiBins, _phiID, M_PI, REGISTER_SEGMENTATION, and DD4hep::DDSegmentation::BitField64::setValue().
phi() [2/2]
double DD4hep::DDSegmentation::ProjectiveCylinder::phi () const protected
determine the azimuthal angle phi based on the current cell ID
Definition at line 79 of file ProjectiveCylinder.cpp.
References _phiBins, _phiID, and M_PI.
Referenced by position().
phiBins()
int DD4hep::DDSegmentation::ProjectiveCylinder::phiBins () const inline
access the number of bins in theta
Definition at line 38 of file ProjectiveCylinder.h.
References _phiBins.
position()
Vector3D DD4hep::DDSegmentation::ProjectiveCylinder::position (const CellID & cellID) const virtual
determine the position based on the cell ID
determine the local based on the cell ID
Implements DD4hep::DDSegmentation::Segmentation.
Definition at line 58 of file ProjectiveCylinder.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, phi(), DD4hep::DDSegmentation::Util::positionFromRThetaPhi(), DD4hep::DDSegmentation::BitField64::setValue(), and theta().
setFieldNamePhi()
void DD4hep::DDSegmentation::ProjectiveCylinder::setFieldNamePhi (const std::string & fieldName) inline
set the field name used for phi
Definition at line 78 of file ProjectiveCylinder.h.
References _phiID.
setFieldNameTheta()
void DD4hep::DDSegmentation::ProjectiveCylinder::setFieldNameTheta (const std::string & fieldName) inline
set the field name used for theta
Definition at line 74 of file ProjectiveCylinder.h.
References _thetaID.
setOffsetPhi()
void DD4hep::DDSegmentation::ProjectiveCylinder::setOffsetPhi (double offset) inline
set the coordinate offset in phi
Definition at line 70 of file ProjectiveCylinder.h.
References _offsetPhi.
setOffsetTheta()
void DD4hep::DDSegmentation::ProjectiveCylinder::setOffsetTheta (double offset) inline
set the coordinate offset in theta
Definition at line 66 of file ProjectiveCylinder.h.
References _offsetTheta.
setPhiBins()
void DD4hep::DDSegmentation::ProjectiveCylinder::setPhiBins (int bins) inline
set the number of bins in phi
Definition at line 62 of file ProjectiveCylinder.h.
References _phiBins.
setThetaBins()
void DD4hep::DDSegmentation::ProjectiveCylinder::setThetaBins (int bins) inline
set the number of bins in theta
Definition at line 58 of file ProjectiveCylinder.h.
References _thetaBins.
theta() [1/2]
double DD4hep::DDSegmentation::ProjectiveCylinder::theta (const CellID & cellID) const
determine the polar angle theta based on the cell ID
Definition at line 85 of file ProjectiveCylinder.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, _thetaBins, _thetaID, M_PI, and DD4hep::DDSegmentation::BitField64::setValue().
theta() [2/2]
double DD4hep::DDSegmentation::ProjectiveCylinder::theta () const protected
determine the polar angle theta based on the current cell ID
Definition at line 74 of file ProjectiveCylinder.cpp.
References _thetaBins, _thetaID, and M_PI.
Referenced by position().
thetaBins()
int DD4hep::DDSegmentation::ProjectiveCylinder::thetaBins () const inline
access the number of bins in theta
Definition at line 34 of file ProjectiveCylinder.h.
References _thetaBins.
Member Data Documentation
_offsetPhi
double DD4hep::DDSegmentation::ProjectiveCylinder::_offsetPhi protected
the coordinate offset in phi
Definition at line 90 of file ProjectiveCylinder.h.
Referenced by cellID(), offsetPhi(), ProjectiveCylinder(), and setOffsetPhi().
_offsetTheta
double DD4hep::DDSegmentation::ProjectiveCylinder::_offsetTheta protected
the coordinate offset in theta
Definition at line 88 of file ProjectiveCylinder.h.
Referenced by cellID(), offsetTheta(), ProjectiveCylinder(), and setOffsetTheta().
_phiBins
int DD4hep::DDSegmentation::ProjectiveCylinder::_phiBins protected
the number of bins in phi
Definition at line 86 of file ProjectiveCylinder.h.
Referenced by cellID(), phi(), phiBins(), ProjectiveCylinder(), and setPhiBins().
_phiID
std::string DD4hep::DDSegmentation::ProjectiveCylinder::_phiID protected
the field name used for phi
Definition at line 94 of file ProjectiveCylinder.h.
Referenced by cellID(), fieldNamePhi(), phi(), ProjectiveCylinder(), and setFieldNamePhi().
_thetaBins
int DD4hep::DDSegmentation::ProjectiveCylinder::_thetaBins protected
the number of bins in theta
Definition at line 84 of file ProjectiveCylinder.h.
Referenced by cellID(), ProjectiveCylinder(), setThetaBins(), theta(), and thetaBins().
_thetaID
std::string DD4hep::DDSegmentation::ProjectiveCylinder::_thetaID protected
the field name used for theta
Definition at line 92 of file ProjectiveCylinder.h.
Referenced by cellID(), fieldNameTheta(), ProjectiveCylinder(), setFieldNameTheta(), and theta().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/ProjectiveCylinder.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/ProjectiveCylinder.cpp