DD4hep: DD4hep::Geometry::LimitSetObject Class Reference
DD4hep::Geometry::LimitSetObject Class Reference
DD4hep::Geometry components, classes and objects
Concrete object implementation of the LimitSet Handle.
#include <ObjectsInterna.h>
Public Member Functions
LimitSetObject ()
Standard constructor.
virtual ~LimitSetObject ()
Default destructor.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Additional Inherited Members
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Detailed Description
Concrete object implementation of the LimitSet Handle.
Author
M.Frank
Version
1.0
Definition at line 129 of file ObjectsInterna.h.
Constructor & Destructor Documentation
LimitSetObject()
LimitSetObject::LimitSetObject ()
Standard constructor.
Definition at line 82 of file ObjectsInterna.cpp.
References DD4hep::InstanceCount::increment().
~LimitSetObject()
LimitSetObject::~LimitSetObject () virtual
Default destructor.
Definition at line 87 of file ObjectsInterna.cpp.
References DD4HEP_INSTANTIATE_HANDLE_NAMED(), and DD4hep::InstanceCount::decrement().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/ObjectsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ObjectsInterna.cpp