DD4hep: DD4hep::Geometry::Readout Class Reference
DD4hep::Geometry::Readout Class Reference
DD4hep::Geometry components, classes and objects
Handle to the implementation of the readout structure of a subdetector.
#include <Readout.h>
Public Types
typedef ReadoutObject Object
Implementation type.
typedef HitCollection Collection
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Readout ()=default
Default constructor.
Readout (const Readout &e)=default
Copy Constructor from object.
Readout (const Handle< ReadoutObject > &e)
Copy Constructor from handle.
template<typename Q >
Readout (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
Readout (const std::string &name)
Initializing constructor.
Readout & operator= (const Readout &ro)=default
Assignment operator.
std::vector< std::string > collectionNames () const
Access explicit names of hit collections if present.
std::vector< const Collection * > collections () const
Access hit collections if present.
size_t numCollections () const
Access number of hit collections.
void setIDDescriptor (const Ref_t &spec) const
Assign IDDescription to readout structure.
IDDescriptor idSpec () const
Access IDDescription structure.
void setSegmentation (const Segmentation &segment) const
Assign segmentation structure to readout.
Segmentation segmentation () const
Access segmentation structure.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle to the implementation of the readout structure of a subdetector.
If there is no explicit hit collection defined, by default one single hit collection is defined by the name of the readout itself. If hit collections are defined, ALL must be defined.
Author
M.Frank
Version
1.0
Definition at line 46 of file Readout.h.
Member Typedef Documentation
Collection
typedef HitCollection DD4hep::Geometry::Readout::Collection
Definition at line 50 of file Readout.h.
Object
typedef ReadoutObject DD4hep::Geometry::Readout::Object
Implementation type.
Definition at line 49 of file Readout.h.
Constructor & Destructor Documentation
Readout() [1/5]
DD4hep::Geometry::Readout::Readout () default
Default constructor.
Readout() [2/5]
DD4hep::Geometry::Readout::Readout (const Readout & e) default
Copy Constructor from object.
Readout() [3/5]
DD4hep::Geometry::Readout::Readout (const Handle< ReadoutObject > & e) inline
Copy Constructor from handle.
Definition at line 58 of file Readout.h.
Readout() [4/5]
template<typename Q > DD4hep::Geometry::Readout::Readout (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 61 of file Readout.h.
Readout() [5/5]
Readout::Readout (const std::string & name)
Initializing constructor.
Initializing constructor to create a new object.
Definition at line 52 of file Readout.cpp.
Member Function Documentation
collectionNames()
vector< string > Readout::collectionNames () const
Access explicit names of hit collections if present.
Access names of hit collections.
Definition at line 66 of file Readout.cpp.
References DD4hep::Geometry::ReadoutObject::hits.
collections()
vector< const HitCollection * > Readout::collections () const
Access hit collections if present.
Access hit collections.
Definition at line 80 of file Readout.cpp.
References DD4hep::Geometry::ReadoutObject::hits.
idSpec()
IDDescriptor Readout::idSpec () const
Access IDDescription structure.
Definition at line 110 of file Readout.cpp.
Referenced by DD4hep::Geometry::VolumeManager::addSubdetector(), DD4hep::DDRec::IDDecoder::barrelEndcapFlag(), DD4hep::Simulation::Geant4ConversionHelper::encoding(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::Geant4ReadoutVolumeFilter(), DD4hep::DDRec::IDDecoder::layerIndex(), DD4hep::DDRec::IDDecoder::systemIndex(), DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor(), and DD4hep::Geometry::VolumeManager::VolumeManager().
numCollections()
size_t Readout::numCollections () const
Access number of hit collections.
Definition at line 57 of file Readout.cpp.
References DD4hep::Geometry::ReadoutObject::hits.
operator=()
Readout& DD4hep::Geometry::Readout::operator= (const Readout & ro) default
Assignment operator.
segmentation()
Segmentation Readout::segmentation () const
Access segmentation structure.
Definition at line 131 of file Readout.cpp.
Referenced by DD4hep::DDRec::IDDecoder::areNeighbours(), DD4hep::DDRec::IDDecoder::cellID(), DD4hep::DDRec::IDDecoder::cellIDFromLocal(), DD4hep::DDRec::createGearForILD(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), DD4hep::DDRec::IDDecoder::localPosition(), DD4hep::DDRec::IDDecoder::neighbours(), DD4hep::DDRec::IDDecoder::position(), and DD4hep::DDRec::IDDecoder::volumeID().
setIDDescriptor()
void Readout::setIDDescriptor (const Ref_t & spec) const
Assign IDDescription to readout structure.
Definition at line 94 of file Readout.cpp.
References DD4hep::Handle< T >::isValid().
setSegmentation()
void Readout::setSegmentation (const Segmentation & segment) const
Assign segmentation structure to readout.
Definition at line 115 of file Readout.cpp.
References e, DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::ptr(), and DD4hep::Geometry::ReadoutObject::segmentation.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Readout.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Readout.cpp