DD4hep: DD4hep::Alignments::AlignmentsManager Class Reference
DD4hep::Alignments::AlignmentsManager Class Reference
DDAlign: DD4hep Detector geometry alignment components.
Alignment manager instance to handle alignment dependencies.
#include <AlignmentsManager.h>
Public Types
typedef AlignmentsManagerObject Object
Standard object type.
typedef Conditions::ConditionUpdateContext Context
Conditions derivation context.
typedef Conditions::ConditionDependency Dependency
Alignments re-use conditions dependency definition from the conditions manager.
typedef Conditions::ConditionsDependencyCollection Dependencies
Alignments re-use conditions dependency container def from the conditions manager.
Public Types inherited from DD4hep::Handle< AlignmentsManagerObject >
typedef AlignmentsManagerObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
AlignmentsManager ()=default
Default constructor.
AlignmentsManager (const AlignmentsManager &copy)=default
Copy constructor.
AlignmentsManager (const Handle< Object > &e)
Constructor to be used for proper handles.
template<typename Q >
AlignmentsManager (const Handle< Q > &e)
Constructor to be used for proper handles.
AlignmentsManager (const std::string &name)
Initializing constructor. Creates the object!
AlignmentsManager (char const *name)
Initializing constructor. Creates the object!
AlignmentsManager & operator= (const AlignmentsManager &mgr)=default
Assignment operator.
void destroy ()
Delete the manager. Be careful: this affects all referencing handles!
void adoptDependency (Dependency *dependency) const
Adopy alignment dependency for later recalculation.
const Dependencies & knownDependencies () const
Access all known dependencies.
void compute (dd4hep_ptr< UserPool > &user_pool) const
Compute all alignment conditions of the internal dependency list.
void compute (dd4hep_ptr< UserPool > &user_pool, const Dependencies &deps) const
Compute all alignment conditions of the specified dependency list.
template<>
AlignmentsManager from (LCDD &host)
Access specialization.
Public Member Functions inherited from DD4hep::Handle< AlignmentsManagerObject >
Handle ()
Defaulot constructor.
Handle (AlignmentsManagerObject *e)
Initializing constructor from pointer.
Handle (const Handle< AlignmentsManagerObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< AlignmentsManagerObject > & operator= (const Handle< AlignmentsManagerObject > &e)=default
Assignment operator.
bool operator== (const Handle< AlignmentsManagerObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< AlignmentsManagerObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< AlignmentsManagerObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< AlignmentsManagerObject > & clear ()
Release the object held by the handle.
AlignmentsManagerObject * operator-> () const
Access the held object using the -> operator.
operator AlignmentsManagerObject & () const
Automatic type conversion to an object references.
AlignmentsManagerObject & operator* () const
Access the held object using the * operator.
AlignmentsManagerObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
AlignmentsManagerObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Static Public Member Functions
template<typename T >
static AlignmentsManager from (T &host)
Static accessor if installed as an extension.
static void newEntry (const Context &parameter, DetElement &det, const Dependency *dep, AlignmentCondition &con)
Register new updated derived alignment during the computation step.
Static Public Member Functions inherited from DD4hep::Handle< AlignmentsManagerObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Additional Inherited Members
Public Attributes inherited from DD4hep::Handle< AlignmentsManagerObject >
AlignmentsManagerObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Alignment manager instance to handle alignment dependencies.
Author
M.Frank
Version
1.0
Definition at line 47 of file AlignmentsManager.h.
Member Typedef Documentation
Context
typedef Conditions::ConditionUpdateContext DD4hep::Alignments::AlignmentsManager::Context
Conditions derivation context.
Definition at line 52 of file AlignmentsManager.h.
Dependencies
typedef Conditions::ConditionsDependencyCollection DD4hep::Alignments::AlignmentsManager::Dependencies
Alignments re-use conditions dependency container def from the conditions manager.
Definition at line 56 of file AlignmentsManager.h.
Dependency
typedef Conditions::ConditionDependency DD4hep::Alignments::AlignmentsManager::Dependency
Alignments re-use conditions dependency definition from the conditions manager.
Definition at line 54 of file AlignmentsManager.h.
Object
typedef AlignmentsManagerObject DD4hep::Alignments::AlignmentsManager::Object
Standard object type.
Definition at line 50 of file AlignmentsManager.h.
Constructor & Destructor Documentation
AlignmentsManager() [1/6]
DD4hep::Alignments::AlignmentsManager::AlignmentsManager () default
Default constructor.
AlignmentsManager() [2/6]
DD4hep::Alignments::AlignmentsManager::AlignmentsManager (const AlignmentsManager & copy) default
Copy constructor.
AlignmentsManager() [3/6]
DD4hep::Alignments::AlignmentsManager::AlignmentsManager (const Handle< Object > & e) inline
Constructor to be used for proper handles.
Definition at line 75 of file AlignmentsManager.h.
AlignmentsManager() [4/6]
template<typename Q > DD4hep::Alignments::AlignmentsManager::AlignmentsManager (const Handle< Q > & e) inline
Constructor to be used for proper handles.
Definition at line 77 of file AlignmentsManager.h.
AlignmentsManager() [5/6]
AlignmentsManager::AlignmentsManager (const std::string & name)
Initializing constructor. Creates the object!
Initializing constructor.
Definition at line 245 of file AlignmentsManager.cpp.
References DD4hep::Alignments::AlignmentsManagerObject::AlignmentsManagerObject().
AlignmentsManager() [6/6]
AlignmentsManager::AlignmentsManager (char const * name)
Initializing constructor. Creates the object!
Initializing constructor.
Definition at line 250 of file AlignmentsManager.cpp.
References DD4hep::Alignments::AlignmentsManagerObject::AlignmentsManagerObject().
Member Function Documentation
adoptDependency()
void AlignmentsManager::adoptDependency (Dependency * dependency) const
Adopy alignment dependency for later recalculation.
Definition at line 260 of file AlignmentsManager.cpp.
References DD4hep::Alignments::AlignmentsManagerObject::all_alignments, DD4hep::Alignments::AlignmentsManagerObject::dependencies, DD4hep::Conditions::ConditionDependency::detector, DD4hep::Conditions::ConditionsDependencyCollection::insert(), and DD4hep::Alignments::AlignContext::newEntry().
compute() [1/2]
void AlignmentsManager::compute (dd4hep_ptr< UserPool > & user_pool) const
Compute all alignment conditions of the internal dependency list.
Definition at line 272 of file AlignmentsManager.cpp.
References DD4hep::Alignments::AlignmentsManagerObject::compute(), and DD4hep::Alignments::AlignmentsManagerObject::dependencies.
compute() [2/2]
void AlignmentsManager::compute (dd4hep_ptr< UserPool > & user_pool, const Dependencies & deps) const
Compute all alignment conditions of the specified dependency list.
Definition at line 278 of file AlignmentsManager.cpp.
destroy()
void AlignmentsManager::destroy ()
Delete the manager. Be careful: this affects all referencing handles!
Delete the manager.
Definition at line 255 of file AlignmentsManager.cpp.
References DD4hep::deletePtr().
from() [1/2]
template<typename T > static AlignmentsManager DD4hep::Alignments::AlignmentsManager::from (T & host) static
Static accessor if installed as an extension.
Note:
There may very well be several instances of the alignment manager. Do not think this is a sort of 'static constructor'. This would be a big mistake!.
from() [2/2]
template<> AlignmentsManager DD4hep::Alignments::AlignmentsManager::from (LCDD & host)
Access specialization.
Definition at line 78 of file AlignmentsManager.cpp.
References DD4HEP_INSTANTIATE_HANDLE_NAMED(), and DD4hep::except().
knownDependencies()
const AlignmentsManager::Dependencies & AlignmentsManager::knownDependencies () const
Access all known dependencies.
Definition at line 267 of file AlignmentsManager.cpp.
newEntry()
void AlignmentsManager::newEntry (const Context & parameter, DetElement & det, const Dependency * dep, AlignmentCondition & con) static
Register new updated derived alignment during the computation step.
Definition at line 283 of file AlignmentsManager.cpp.
References DD4hep::Alignments::AlignContext::magic, DD4hep::magic_word(), DD4hep::Alignments::AlignContext::newEntry(), DD4hep::Conditions::ConditionUpdateContext::parameter, and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Alignments::AlignmentUpdateCall::handle().
operator=()
AlignmentsManager& DD4hep::Alignments::AlignmentsManager::operator= (const AlignmentsManager & mgr) default
Assignment operator.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/AlignmentsManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentsManager.cpp