DD4hep: TiXmlBase Class Reference
TiXmlBase Class Reference abstract
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Classes
class Entity
TinyXML class. See http://www.grinninglizard.com/tinyxml.
Public Types
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_DOCUMENT_TOP_ONLY, TIXML_ERROR_STRING_COUNT
}
Public Member Functions
TiXmlBase ()
virtual ~TiXmlBase ()
virtual void Print (FILE *cfile, int depth) const =0
int Row () const
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)=0
Static Public Member Functions
static void SetCondenseWhiteSpace (bool condense)
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes
static const int utf8ByteTable [256]
Static Protected Member Functions
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Private Types
enum { NUM_ENTITY = 5, MAX_ENTITY_LENGTH = 6 }
Private Member Functions
TiXmlBase (const TiXmlBase &)
void operator= (const TiXmlBase &base)
Static Private Attributes
static Entity entity [NUM_ENTITY]
static bool condenseWhiteSpace = true
Friends
class TiXmlNode
class TiXmlElement
class TiXmlDocument
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
TiXmlBase is a base class for every class in TinyXml. It does little except to establish that TinyXml classes can be printed and provide some utility functions.
In XML, the document and elements can contain other elements and other types of nodes.
A Document can contain:     Element (container or leaf)
Comment (leaf)
Unknown (leaf)
Declaration(leaf)
An Element can contain:     Element (container or leaf)
Text        (leaf)
Attributes (not on tree)
Comment (leaf)
Unknown (leaf)
A Decleration contains: Attributes (not on tree)
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 207 of file tinyxml.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
TIXML_NO_ERROR
TIXML_ERROR
TIXML_ERROR_OPENING_FILE
TIXML_ERROR_OUT_OF_MEMORY
TIXML_ERROR_PARSING_ELEMENT
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME
TIXML_ERROR_READING_ELEMENT_VALUE
TIXML_ERROR_READING_ATTRIBUTES
TIXML_ERROR_PARSING_EMPTY
TIXML_ERROR_READING_END_TAG
TIXML_ERROR_PARSING_UNKNOWN
TIXML_ERROR_PARSING_COMMENT
TIXML_ERROR_PARSING_DECLARATION
TIXML_ERROR_DOCUMENT_EMPTY
TIXML_ERROR_EMBEDDED_NULL
TIXML_ERROR_PARSING_CDATA
TIXML_ERROR_DOCUMENT_TOP_ONLY
TIXML_ERROR_STRING_COUNT
Definition at line 286 of file tinyxml.h.
anonymous enum
anonymous enum private
Enumerator
NUM_ENTITY
MAX_ENTITY_LENGTH
Definition at line 417 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlBase() [1/2]
TiXmlBase::TiXmlBase () inline
Definition at line 213 of file tinyxml.h.
Referenced by ToLower().
~TiXmlBase()
virtual TiXmlBase::~TiXmlBase () inline virtual
Definition at line 216 of file tinyxml.h.
References TiXmlDocument::Print().
TiXmlBase() [2/2]
TiXmlBase::TiXmlBase (const TiXmlBase &) private
Member Function Documentation
Column()
int TiXmlBase::Column () const inline
See Row()
Definition at line 266 of file tinyxml.h.
References TiXmlCursor::col, and location.
ConvertUTF32ToUTF8()
void TiXmlBase::ConvertUTF32ToUTF8 (unsigned long input, char * output, int * length) static protected
Definition at line 96 of file tinyxmlparser_inl.h.
Referenced by GetEntity(), and ToLower().
GetChar()
static const char* TiXmlBase::GetChar (const char * p, char * _value, int * length, TiXmlEncoding encoding) inline static protected
Definition at line 346 of file tinyxml.h.
References GetEntity(), PutString(), StringEqual(), TIXML_ENCODING_UTF8, and TIXML_STRING.
Referenced by ReadText().
GetEntity()
const char * TiXmlBase::GetEntity (const char * in, char * value, int * length, TiXmlEncoding encoding) static protected
Definition at line 446 of file tinyxmlparser_inl.h.
References TiXmlBase::Entity::chr, ConvertUTF32ToUTF8(), entity, NUM_ENTITY, TIXML_ENCODING_UTF8, and TIXML_STRING.
Referenced by GetChar(), and IsWhiteSpace().
GetUserData() [1/2]
void* TiXmlBase::GetUserData () inline
Get a pointer to arbitrary user data.
Definition at line 273 of file tinyxml.h.
References userData.
GetUserData() [2/2]
const void* TiXmlBase::GetUserData () const inline
Get a pointer to arbitrary user data.
Definition at line 276 of file tinyxml.h.
References userData.
IsAlpha()
int TiXmlBase::IsAlpha (unsigned char anyByte, TiXmlEncoding encoding) static protected
Definition at line 137 of file tinyxmlparser_inl.h.
Referenced by TiXmlNode::Identify(), and ReadName().
IsAlphaNum()
int TiXmlBase::IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding) static protected
Definition at line 158 of file tinyxmlparser_inl.h.
Referenced by ReadName().
IsWhiteSpace() [1/2]
static bool TiXmlBase::IsWhiteSpace (char c) inline static protected
Definition at line 311 of file tinyxml.h.
Referenced by TiXmlText::Blank(), TiXmlNode::Identify(), IsWhiteSpace(), TiXmlAttribute::Parse(), TiXmlDeclaration::Parse(), ReadText(), and SkipWhiteSpace().
IsWhiteSpace() [2/2]
static bool TiXmlBase::IsWhiteSpace (int c) inline static protected
Definition at line 314 of file tinyxml.h.
References GetEntity(), IsWhiteSpace(), ReadName(), ReadText(), StreamTo(), StreamWhiteSpace(), TIXML_STRING, and TiXmlNode::value.
IsWhiteSpaceCondensed()
static bool TiXmlBase::IsWhiteSpaceCondensed () inline static
Return the current white space setting.
Definition at line 241 of file tinyxml.h.
References condenseWhiteSpace.
Referenced by TiXmlElement::ReadValue().
operator=()
void TiXmlBase::operator= (const TiXmlBase & base) private
Parse()
virtual const char* TiXmlBase::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) pure virtual
Implemented in TiXmlDocument, TiXmlUnknown, TiXmlDeclaration, TiXmlText, TiXmlComment, TiXmlElement, and TiXmlAttribute.
Referenced by TiXmlAttributeSet::Find(), TiXmlDocument::Parse(), and TiXmlElement::ReadValue().
Print()
virtual void TiXmlBase::Print (FILE * cfile, int depth) const pure virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implemented in TiXmlDocument, TiXmlUnknown, TiXmlDeclaration, TiXmlText, TiXmlComment, TiXmlElement, and TiXmlAttribute.
Referenced by TiXmlElement::Print().
PutString()
void TiXmlBase::PutString (const TIXML_STRING & str, TIXML_STRING * out) static protected
Definition at line 42 of file tinyxml_inl.h.
References entity.
Referenced by GetChar(), TiXmlAttribute::Print(), and TiXmlText::Print().
ReadName()
const char * TiXmlBase::ReadName (const char * p, TIXML_STRING * name, TiXmlEncoding encoding) static protected
Definition at line 409 of file tinyxmlparser_inl.h.
References IsAlpha(), and IsAlphaNum().
Referenced by IsWhiteSpace(), TiXmlAttribute::Parse(), and TiXmlElement::Parse().
ReadText()
const char * TiXmlBase::ReadText (const char * in, TIXML_STRING * text, bool ignoreWhiteSpace, const char * endTag, bool ignoreCase, TiXmlEncoding encoding) static protected
Definition at line 582 of file tinyxmlparser_inl.h.
References condenseWhiteSpace, GetChar(), TiXmlNode::Identify(), IsWhiteSpace(), TiXmlDocument::SetError(), SkipWhiteSpace(), TiXmlNode::StreamIn(), TiXmlDocument::StreamIn(), StreamTo(), StringEqual(), TIXML_DEFAULT_ENCODING, TIXML_ENCODING_UNKNOWN, TIXML_ERROR, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_EMPTY, TIXML_STRING, and TiXmlNode::ToElement().
Referenced by IsWhiteSpace(), TiXmlAttribute::Parse(), TiXmlComment::Parse(), and TiXmlText::Parse().
Row()
int TiXmlBase::Row () const inline
Return the position, in the original source file, of this node or attribute. The row and column are 1-based. (That is the first row and first column is 1,1). If the returns values are 0 or less, then the parser does not have a row and column value.
Generally, the row and column value will be set when the TiXmlDocument::Load(), TiXmlDocument::LoadFile(), or any TiXmlNode::Parse() is called. It will NOT be set when the DOM was created from operator>>.
The values reflect the initial load. Once the DOM is modified programmatically (by adding or changing nodes and attributes) the new values will NOT update to reflect changes in the document.
There is a minor performance cost to computing the row and column. Computation can be disabled if TiXmlDocument::SetTabSize() is called with 0 as the value.
See also
TiXmlDocument::SetTabSize()
Definition at line 263 of file tinyxml.h.
References location, and TiXmlCursor::row.
SetCondenseWhiteSpace()
static void TiXmlBase::SetCondenseWhiteSpace (bool condense) inline static
The world does not agree on whether white space should be kept or not. In order to make everyone happy, these global, static functions are provided to set whether or not TinyXml will condense all white space into a single space or not. The default is to condense. Note changing this value is not thread safe.
Definition at line 236 of file tinyxml.h.
References condenseWhiteSpace.
SetUserData()
void TiXmlBase::SetUserData (void * user) inline
Set a pointer to arbitrary user data.
Definition at line 270 of file tinyxml.h.
References userData.
SkipWhiteSpace()
const char * TiXmlBase::SkipWhiteSpace (const char * p, TiXmlEncoding encoding) static protected
Definition at line 322 of file tinyxmlparser_inl.h.
References IsWhiteSpace(), StreamTo(), StreamWhiteSpace(), TIXML_ENCODING_UTF8, TIXML_STRING, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, and TIXML_UTF_LEAD_2.
Referenced by TiXmlNode::Identify(), TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), TiXmlDocument::Parse(), ReadText(), and TiXmlElement::ReadValue().
StreamTo()
static bool TiXmlBase::StreamTo (std::istream * in, int character, TIXML_STRING * tag) static protected
Referenced by IsWhiteSpace(), ReadText(), and SkipWhiteSpace().
StreamWhiteSpace()
static bool TiXmlBase::StreamWhiteSpace (std::istream * in, TIXML_STRING * tag) static protected
Referenced by TiXmlNode::Identify(), IsWhiteSpace(), and SkipWhiteSpace().
StringEqual()
bool TiXmlBase::StringEqual (const char * p, const char * endTag, bool ignoreCase, TiXmlEncoding encoding) static protected
Definition at line 542 of file tinyxmlparser_inl.h.
References ToLower().
Referenced by GetChar(), TiXmlNode::Identify(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlDocument::Parse(), ReadText(), and TiXmlElement::ReadValue().
ToLower()
static int TiXmlBase::ToLower (int v, TiXmlEncoding encoding) inline static protected
Definition at line 396 of file tinyxml.h.
References ConvertUTF32ToUTF8(), TiXmlDocument::operator=(), TIXML_ENCODING_UTF8, TiXmlBase(), and v.
Referenced by StringEqual().
Friends And Related Function Documentation
TiXmlDocument
friend class TiXmlDocument friend
Definition at line 210 of file tinyxml.h.
TiXmlElement
friend class TiXmlElement friend
Definition at line 209 of file tinyxml.h.
Referenced by TiXmlNode::Identify().
TiXmlNode
friend class TiXmlNode friend
Definition at line 208 of file tinyxml.h.
Member Data Documentation
condenseWhiteSpace
bool TiXmlBase::condenseWhiteSpace = true static private
Definition at line 422 of file tinyxml.h.
Referenced by IsWhiteSpaceCondensed(), ReadText(), and SetCondenseWhiteSpace().
entity
TiXmlBase::Entity TiXmlBase::entity static private
Initial value:
=
  {
    { "&",  1, '&' },
    { "&lt;",   4, '<' },
    { "&gt;",   4, '>' },
    { "&quot;", 6, '\"' },
    { "&apos;", 6, '\'' }
  }
Definition at line 421 of file tinyxml.h.
Referenced by GetEntity(), and PutString().
errorString
const char * TiXmlBase::errorString static protected
Initial value:
=
  {
    "No error",
    "Error",
    "Failed to open file",
    "Memory allocation failed.",
    "Error parsing Element.",
    "Failed to read Element name",
    "Error reading Element value.",
    "Error reading Attributes.",
    "Error: empty tag.",
    "Error reading end tag.",
    "Error parsing Unknown.",
    "Error parsing Comment.",
    "Error parsing Declaration.",
    "Error document empty.",
    "Error null (0) or unexpected EOF found in input stream.",
    "Error parsing CDATA.",
    "Error when TiXmlDocument added to document, because TiXmlDocument can only be at the root.",
  }
Definition at line 385 of file tinyxml.h.
Referenced by TiXmlDocument::SetError().
location
TiXmlCursor TiXmlBase::location protected
Definition at line 387 of file tinyxml.h.
Referenced by Column(), TiXmlDocument::LoadFile(), TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), TiXmlDocument::Parse(), and Row().
userData
void* TiXmlBase::userData protected
Field containing a generic user pointer.
Definition at line 390 of file tinyxml.h.
Referenced by TiXmlNode::CopyTo(), GetUserData(), and SetUserData().
utf8ByteTable
const int TiXmlBase::utf8ByteTable static
Initial value:
=
  {
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,
    1,  1,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,
    2,  2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,      2,
    3,  3,      3,      3,      3,      3,      3,      3,      3,      3,      3,      3,      3,      3,      3,      3,
    4,  4,      4,      4,      4,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1,      1
  }
Definition at line 282 of file tinyxml.h.
Referenced by TiXmlParsingData::Stamp().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlerror_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h