DD4hep: DD4hep: DD4hep::Simulation::Geant4UserDetectorConstruction Class Reference
DD4hep::Simulation::Geant4UserDetectorConstruction Class Reference
Concrete implementation of the Geant4 user detector construction action sequence.
Public Member Functions
Geant4UserDetectorConstruction (Geant4Context *ctxt, Geant4DetectorConstructionSequence *seq)
Standard constructor.
virtual ~Geant4UserDetectorConstruction ()
Default destructor.
virtual void ConstructSDandField ()
Call the actions for the construction of the sensitive detectors and the field.
virtual G4VPhysicalVolume * Construct ()
Call the actions to construct the detector geometry.
Protected Attributes
Geant4DetectorConstructionContext m_ctxt
Detailed Description
Concrete implementation of the Geant4 user detector construction action sequence.
Author:
M.Frank
Version:
1.0
Definition at line 302 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4UserDetectorConstruction::Geant4UserDetectorConstruction (Geant4Context * ctxt, Geant4DetectorConstructionSequence * seq) [inline]
Standard constructor.
Definition at line 310 of file Geant4Exec.cpp.
virtual DD4hep::Simulation::Geant4UserDetectorConstruction::~Geant4UserDetectorConstruction () [inline, virtual]
Default destructor.
Definition at line 316 of file Geant4Exec.cpp.
Member Function Documentation
G4VPhysicalVolume * DD4hep::Simulation::Geant4UserDetectorConstruction::Construct () [virtual]
Call the actions to construct the detector geometry.
Construct electro magnetic field entity from the DD4hep field.
Definition at line 398 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4DetectorConstructionSequence::constructGeo(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Action::except(), m_ctxt, DD4hep::Simulation::SequenceHdl< Geant4DetectorConstructionSequence >::m_sequence, DD4hep::Simulation::SequenceHdl< Geant4DetectorConstructionSequence >::updateContext(), and DD4hep::Simulation::Geant4DetectorConstructionContext::world.
void DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField () [virtual]
Call the actions for the construction of the sensitive detectors and the field.
Instantiate Geant4 sensitive detectors and electro-magnetic field.
Definition at line 387 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4DetectorConstructionSequence::constructField(), DD4hep::Simulation::Geant4DetectorConstructionSequence::constructSensitives(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::SequenceHdl< Geant4DetectorConstructionSequence >::kernel(), m_ctxt, DD4hep::Simulation::SequenceHdl< Geant4DetectorConstructionSequence >::m_sequence, DD4hep::Simulation::Geant4Kernel::thread_self(), DD4hep::Simulation::SequenceHdl< Geant4DetectorConstructionSequence >::updateContext(), DD4hep::Simulation::Geant4Kernel::worker(), and DD4hep::Simulation::Geant4ActionContainer::workerContext().
Member Data Documentation
Geant4DetectorConstructionContext DD4hep::Simulation::Geant4UserDetectorConstruction::m_ctxt [protected]
Definition at line 307 of file Geant4Exec.cpp.
Referenced by Construct(), and ConstructSDandField().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp