DD4hep: DD4hep: DD4hep::Simulation::Geant4DetectorConstructionSequence Class Reference
DD4hep::Simulation::Geant4DetectorConstructionSequence Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete basic implementation of the Geant4 detector construction sequencer.
#include <Geant4DetectorConstruction.h>
Public Member Functions
Geant4DetectorConstructionSequence (Geant4Context *context, const std::string &nam)
Standard Constructor.
virtual ~Geant4DetectorConstructionSequence ()
Default destructor.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
void adopt (Geant4DetectorConstruction *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void constructGeo (Geant4DetectorConstructionContext *ctxt)
Geometry construction callback. Called at "Construct()".
virtual void constructField (Geant4DetectorConstructionContext *ctxt)
Electromagnetic field construction callback. Called at "ConstructSDandField()".
virtual void constructSensitives (Geant4DetectorConstructionContext *ctxt)
Sensitive detector construction callback. Called at "ConstructSDandField()".
const
Geant4GeometryMaps::MaterialMap & materials () const
Access to the converted materials.
const
Geant4GeometryMaps::ElementMap & elements () const
Access to the converted elements.
const
Geant4GeometryMaps::SolidMap & shapes () const
Access to the converted shapes.
const
Geant4GeometryMaps::VolumeMap & volumes () const
Access to the converted volumes.
const
Geant4GeometryMaps::PlacementMap & placements () const
Access to the converted placements.
const
Geant4GeometryMaps::AssemblyMap & assemblies () const
Access to the converted assemblys.
const
Geant4GeometryMaps::LimitMap & limits () const
Access to the converted limit sets.
const
Geant4GeometryMaps::RegionMap & regions () const
Access to the converted regions.
Protected Attributes
Actors
< Geant4DetectorConstruction > m_actors
The list of action objects to be called.
Detailed Description
Concrete basic implementation of the Geant4 detector construction sequencer.
Concrete implementation of the Geant4 detector construction sequence. The sequence dispatches the callbacks for the "Construct()" method to create a detector geometry and to dispatch the "ConstructSDandField()" calls for each worker.
Please note: constructField() and constructSensitives() are executed in a thread-local context. See the Geant4 documentation for details: https://twiki.cern.ch/twiki/bin/view/Geant4/QuickMigrationGuideForGeant4V10
Author:
M.Frank
Version:
1.0
Definition at line 133 of file Geant4DetectorConstruction.h.
Constructor & Destructor Documentation
Geant4DetectorConstructionSequence::Geant4DetectorConstructionSequence (Geant4Context * context, const std::string & nam)
Standard Constructor.
Definition at line 59 of file Geant4DetectorConstruction.cpp.
References DD4hep::InstanceCount::increment(), and DD4hep::Simulation::Geant4Action::m_needsControl.
Geant4DetectorConstructionSequence::~Geant4DetectorConstructionSequence () [virtual]
Default destructor.
Definition at line 67 of file Geant4DetectorConstruction.cpp.
References DD4hep::InstanceCount::decrement(), m_actors, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
void Geant4DetectorConstructionSequence::adopt (Geant4DetectorConstruction * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 79 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by Geant4Compatibility::buildDefaultDetectorConstruction().
const Geant4GeometryMaps::AssemblyMap & Geant4DetectorConstructionSequence::assemblies () const
Access to the converted assemblys.
Access to the converted assemblies.
Definition at line 139 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4AssemblyVolumes, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
void Geant4DetectorConstructionSequence::constructField (Geant4DetectorConstructionContext * ctxt) [virtual]
Electromagnetic field construction callback. Called at "ConstructSDandField()".
Definition at line 94 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4DetectorConstruction::constructField(), and m_actors.
Referenced by DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField().
void Geant4DetectorConstructionSequence::constructGeo (Geant4DetectorConstructionContext * ctxt) [virtual]
Geometry construction callback. Called at "Construct()".
Definition at line 89 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4DetectorConstruction::constructGeo(), and m_actors.
Referenced by DD4hep::Simulation::Geant4UserDetectorConstruction::Construct().
void Geant4DetectorConstructionSequence::constructSensitives (Geant4DetectorConstructionContext * ctxt) [virtual]
Sensitive detector construction callback. Called at "ConstructSDandField()".
Definition at line 99 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4DetectorConstruction::constructSensitives(), and m_actors.
Referenced by DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField().
const Geant4GeometryMaps::ElementMap & Geant4DetectorConstructionSequence::elements () const
Access to the converted elements.
Definition at line 160 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Elements, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
const Geant4GeometryMaps::LimitMap & Geant4DetectorConstructionSequence::limits () const
Access to the converted limit sets.
Definition at line 132 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Limits, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
const Geant4GeometryMaps::MaterialMap & Geant4DetectorConstructionSequence::materials () const
Access to the converted materials.
Definition at line 153 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Materials, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
const Geant4GeometryMaps::PlacementMap & Geant4DetectorConstructionSequence::placements () const
Access to the converted placements.
Definition at line 146 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Placements, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
const Geant4GeometryMaps::RegionMap & Geant4DetectorConstructionSequence::regions () const
Access to the converted regions.
Definition at line 104 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Regions, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
const Geant4GeometryMaps::SolidMap & Geant4DetectorConstructionSequence::shapes () const
Access to the converted shapes.
Definition at line 125 of file Geant4DetectorConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Solids, DD4hep::Simulation::Geant4Mapping::instance(), and DD4hep::Simulation::Geant4Mapping::ptr().
void Geant4DetectorConstructionSequence::updateContext (Geant4Context * ctxt) [virtual]
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 73 of file Geant4DetectorConstruction.cpp.
References m_actors, DD4hep::Simulation::Geant4Action::m_context, and DD4hep::Simulation::Geant4Action::updateContext().
const Geant4GeometryMaps::VolumeMap & Geant4DetectorConstructionSequence::volumes () const
Access to the converted volumes.
Definition at line 118 of file Geant4DetectorConstruction.cpp.
Member Data Documentation
Actors<Geant4DetectorConstruction> DD4hep::Simulation::Geant4DetectorConstructionSequence::m_actors [protected]
The list of action objects to be called.
Definition at line 136 of file Geant4DetectorConstruction.h.
Referenced by adopt(), constructField(), constructGeo(), constructSensitives(), updateContext(), and ~Geant4DetectorConstructionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4DetectorConstruction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4DetectorConstruction.cpp