DD4hep: DD4hep::Simulation::Geant4Action Class Reference
DD4hep::Simulation::Geant4Action Class Reference
DD4hep::Simulation components, classes and objects
Default base class for all Geant 4 actions and derivates thereof.
#include <Geant4Action.h>
Classes
class Actors
Actor class to manipulate action groups.
class ContextSwap
Functor to update the context of a Geant4Action object.
struct FindByName
Functor to access elements by name.
Public Member Functions
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Member Functions
virtual ~Geant4Action ()
Default destructor.
Protected Attributes
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Detailed Description
Default base class for all Geant 4 actions and derivates thereof.
This is a utility class supporting properties, output and access to event and run objects through the context.
Author
M.Frank
Version
1.0
Definition at line 89 of file Geant4Action.h.
Constructor & Destructor Documentation
~Geant4Action()
Geant4Action::~Geant4Action () protected virtual
Default destructor.
Definition at line 70 of file Geant4Action.cpp.
Geant4Action()
Geant4Action::Geant4Action (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 57 of file Geant4Action.cpp.
Member Function Documentation
abortRun()
void Geant4Action::abortRun (const std::string & exception, const char * fmt, ...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Definition at line 268 of file Geant4Action.cpp.
References DD4hep::format(), and DD4hep::typeName().
Referenced by appendInteraction(), DD4hep::Simulation::boostInteraction(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::mergeInteractions(), DD4hep::Simulation::Geant4InputAction::readParticles(), and DD4hep::Simulation::smearInteraction().
addRef()
long Geant4Action::addRef ()
Increase reference count.
Implicit destruction.
Definition at line 75 of file Geant4Action.cpp.
Referenced by DD4hep::Simulation::Geant4ActionPhase::add(), DD4hep::Simulation::Geant4UserInitializationSequence::adopt(), DD4hep::Simulation::Geant4SteppingActionSequence::adopt(), DD4hep::Simulation::Geant4StackingActionSequence::adopt(), DD4hep::Simulation::Geant4GeneratorActionSequence::adopt(), DD4hep::Simulation::Geant4ParticleHandler::adopt(), DD4hep::Simulation::Geant4RunActionSequence::adopt(), DD4hep::Simulation::Geant4DetectorConstructionSequence::adopt(), DD4hep::Simulation::Geant4EventActionSequence::adopt(), DD4hep::Simulation::Geant4TrackingActionSequence::adopt(), DD4hep::Simulation::Geant4Sensitive::adopt(), DD4hep::Simulation::Geant4PhysicsListActionSequence::adopt(), DD4hep::Simulation::Geant4SensDetActionSequence::adopt(), DD4hep::Simulation::Geant4Sensitive::adopt_front(), DD4hep::Simulation::Geant4PhysicsList::adoptPhysicsConstructor(), DD4hep::Simulation::Geant4SensDetSequences::insert(), DD4hep::Simulation::Geant4Kernel::registerGlobalAction(), DD4hep::Simulation::Geant4Kernel::registerGlobalFilter(), DD4hep::Simulation::Geant4SharedStackingAction::use(), DD4hep::Simulation::Geant4SharedSteppingAction::use(), DD4hep::Simulation::Geant4SharedRunAction::use(), DD4hep::Simulation::Geant4SharedTrackingAction::use(), DD4hep::Simulation::Geant4SharedGeneratorAction::use(), and DD4hep::Simulation::Geant4SharedEventAction::use().
c_name()
const char* DD4hep::Simulation::Geant4Action::c_name () const inline
Access name of the action.
Definition at line 281 of file Geant4Action.h.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::adopt(), DD4hep::Simulation::Geant4PhysicsList::adoptPhysicsConstructor(), DD4hep::Simulation::Geant4SensDetActionSequence::collection(), DD4hep::Simulation::Geant4SensDetActionSequence::collectionByID(), DD4hep::Simulation::TrackerCombine::extractHit(), DD4hep::Simulation::Geant4SensDetActionSequence::hitCollectionName(), DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), and DD4hep::Simulation::Geant4ParticleHandler::mark().
configureFiber()
void Geant4Action::configureFiber (Geant4Context * thread_context) virtual
Set or update client for the use in a new thread fiber.
Reimplemented in DD4hep::Simulation::Geant4EventActionSequence, DD4hep::Simulation::Geant4TrackingActionSequence, DD4hep::Simulation::Geant4GeneratorActionSequence, DD4hep::Simulation::Geant4RunActionSequence, DD4hep::Simulation::Geant4StackingActionSequence, DD4hep::Simulation::Geant4SteppingActionSequence, DD4hep::Simulation::Geant4SharedEventAction, DD4hep::Simulation::Geant4SharedGeneratorAction, DD4hep::Simulation::Geant4SharedTrackingAction, DD4hep::Simulation::Geant4SharedRunAction, DD4hep::Simulation::Geant4SharedStackingAction, DD4hep::Simulation::Geant4SharedSteppingAction, and DD4hep::Simulation::Geant4OutputAction.
Definition at line 150 of file Geant4Action.cpp.
Referenced by DD4hep::Simulation::Geant4OutputAction::configureFiber(), DD4hep::Simulation::Geant4SharedStackingAction::configureFiber(), DD4hep::Simulation::Geant4SharedSteppingAction::configureFiber(), DD4hep::Simulation::Geant4SharedRunAction::configureFiber(), DD4hep::Simulation::Geant4SharedTrackingAction::configureFiber(), DD4hep::Simulation::Geant4SharedGeneratorAction::configureFiber(), DD4hep::Simulation::Geant4SharedEventAction::configureFiber(), DD4hep::Simulation::Geant4SteppingActionSequence::configureFiber(), DD4hep::Simulation::Geant4StackingActionSequence::configureFiber(), DD4hep::Simulation::Geant4RunActionSequence::configureFiber(), DD4hep::Simulation::Geant4GeneratorActionSequence::configureFiber(), DD4hep::Simulation::Geant4TrackingActionSequence::configureFiber(), and DD4hep::Simulation::Geant4EventActionSequence::configureFiber().
context()
Geant4Context* DD4hep::Simulation::Geant4Action::context () const inline
Access the context.
Definition at line 267 of file Geant4Action.h.
Referenced by DD4hep::Simulation::Geant4TrackingPreAction::begin(), DD4hep::Simulation::Geant4TrackingPostAction::begin(), DD4hep::Simulation::Test::Geant4TestRunAction::begin(), DD4hep::Simulation::Geant4SharedRunAction::begin(), DD4hep::Simulation::Geant4SharedTrackingAction::begin(), DD4hep::Simulation::Geant4SharedEventAction::begin(), DD4hep::Simulation::Test::Geant4TestEventAction::begin(), DD4hep::Simulation::Test::Geant4TestTrackAction::begin(), DD4hep::Simulation::Test::Geant4TestSensitive::begin(), DD4hep::Simulation::Test::Geant4TestRunAction::beginEvent(), DD4hep::Simulation::Geant4ParticleHandler::beginEvent(), DD4hep::Simulation::Test::Geant4TestEventAction::beginRun(), DD4hep::Simulation::Geant4Action::ContextSwap::ContextSwap(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), DD4hep::Simulation::Geant4OutputAction::end(), DD4hep::Simulation::Test::Geant4TestRunAction::end(), DD4hep::Simulation::Geant4SharedRunAction::end(), DD4hep::Simulation::Geant4SharedTrackingAction::end(), DD4hep::Simulation::Geant4SharedEventAction::end(), DD4hep::Simulation::Test::Geant4TestEventAction::end(), DD4hep::Simulation::Test::Geant4TestTrackAction::end(), DD4hep::Simulation::Test::Geant4TestSensitive::end(), DD4hep::Simulation::Test::Geant4TestRunAction::endEvent(), DD4hep::Simulation::Geant4ParticleHandler::endEvent(), DD4hep::Simulation::Test::Geant4TestEventAction::endRun(), DD4hep::Simulation::Geant4GeneratorActionInit::Geant4GeneratorActionInit(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), DD4hep::Simulation::Geant4ParticleGun::getParticleDirection(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionCosTheta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionEta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionFFbar(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionUniform(), DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), DD4hep::Simulation::Geant4TrackingAction::mark(), DD4hep::Simulation::Geant4Sensitive::mark(), DD4hep::Simulation::Geant4SharedStackingAction::newStage(), DD4hep::Simulation::Geant4PrimaryHandler::operator()(), DD4hep::Simulation::Geant4InteractionMerger::operator()(), DD4hep::Simulation::Geant4GeneratorWrapper::operator()(), DD4hep::Simulation::Geant4InteractionVertexBoost::operator()(), DD4hep::Simulation::Geant4InteractionVertexSmear::operator()(), DD4hep::Simulation::Geant4GeneratorActionInit::operator()(), DD4hep::Simulation::Geant4ParticleGun::operator()(), DD4hep::Simulation::Test::Geant4TestGeneratorAction::operator()(), DD4hep::Simulation::Geant4SharedSteppingAction::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::operator()(), DD4hep::Simulation::Geant4SharedGeneratorAction::operator()(), DD4hep::Simulation::Geant4FieldTrackingSetupAction::operator()(), DD4hep::Simulation::Geant4FieldTrackingConstruction::operator()(), DD4hep::Simulation::Geant4ParticleHandler::operator()(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4SharedStackingAction::prepare(), DD4hep::Simulation::Geant4ParticleGenerator::printInteraction(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), DD4hep::Simulation::Test::Geant4TestSensitive::process(), DD4hep::Simulation::Geant4ParticleHandler::rebaseSimulatedTracks(), DD4hep::Simulation::Geant4Output2ROOT::saveEvent(), DD4hep::Simulation::Geant4InteractionVertexSmear::smear(), and DD4hep::Simulation::Geant4UIManager::start().
control()
Geant4UIMessenger * Geant4Action::control () const
Access to the UI messenger.
Definition at line 135 of file Geant4Action.cpp.
References DD4hep::except().
Referenced by DD4hep::Simulation::Geant4PhysicsList::installCommandMessenger(), and DD4hep::Simulation::Geant4PhysicsListActionSequence::installCommandMessenger().
debug()
void Geant4Action::debug (const char * fmt, ...) const
Support of debug messages.
Definition at line 209 of file Geant4Action.cpp.
References DD4hep::DEBUG, and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4PhysicsList::constructParticles(), DD4hep::Simulation::Geant4PhysicsList::constructPhysics(), DD4hep::Simulation::Geant4PhysicsList::constructProcesses(), DD4hep::Simulation::Geant4ParticleHandler::endEvent(), DD4hep::Simulation::mergeInteractions(), DD4hep::Simulation::Geant4InteractionMerger::operator()(), and DD4hep::Simulation::Geant4ParticleHandler::operator()().
declareProperty() [1/2]
template<typename T > Geant4Action & DD4hep::Simulation::Geant4Action::declareProperty (const std::string & nam, T & val)
Declare property.
Definition at line 364 of file Geant4Action.h.
References DD4hep::PropertyManager::add().
Referenced by DD4hep::Simulation::EnergyDepositMinimumCut::EnergyDepositMinimumCut(), DD4hep::Simulation::Geant4DefaultRangeCut::Geant4DefaultRangeCut(), DD4hep::Simulation::Geant4EscapeCounter::Geant4EscapeCounter(), DD4hep::Simulation::Geant4FieldTrackingConstruction::Geant4FieldTrackingConstruction(), DD4hep::Simulation::Geant4FieldTrackingSetupAction::Geant4FieldTrackingSetupAction(), DD4hep::Simulation::Geant4GeneratorWrapper::Geant4GeneratorWrapper(), DD4hep::Simulation::Geant4InputAction::Geant4InputAction(), DD4hep::Simulation::Geant4InteractionVertexBoost::Geant4InteractionVertexBoost(), DD4hep::Simulation::Geant4InteractionVertexSmear::Geant4InteractionVertexSmear(), DD4hep::Simulation::Geant4IsotropeGenerator::Geant4IsotropeGenerator(), DD4hep::Simulation::Geant4Output2ROOT::Geant4Output2ROOT(), DD4hep::Simulation::Geant4OutputAction::Geant4OutputAction(), DD4hep::Simulation::Geant4ParticleGenerator::Geant4ParticleGenerator(), DD4hep::Simulation::Geant4ParticleGun::Geant4ParticleGun(), DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler(), DD4hep::Simulation::Geant4ParticlePrint::Geant4ParticlePrint(), DD4hep::Simulation::Geant4PhysicsConstructor::Geant4PhysicsConstructor(), DD4hep::Simulation::Geant4PhysicsListActionSequence::Geant4PhysicsListActionSequence(), DD4hep::Simulation::Geant4Random::Geant4Random(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), DD4hep::Simulation::Geant4SensitiveAction< T >::Geant4SensitiveAction(), DD4hep::Simulation::Test::Geant4TestBase::Geant4TestBase(), DD4hep::Simulation::Geant4TrackingPostAction::Geant4TrackingPostAction(), DD4hep::Simulation::Geant4UIManager::Geant4UIManager(), DD4hep::Simulation::Geant4UserParticleHandler::Geant4UserParticleHandler(), DD4hep::Simulation::ParticleFilter::ParticleFilter(), and DD4hep::Simulation::Geant4TCUserParticleHandler::~Geant4TCUserParticleHandler().
declareProperty() [2/2]
template<typename T > Geant4Action & DD4hep::Simulation::Geant4Action::declareProperty (const char * nam, T & val)
Declare property.
Definition at line 370 of file Geant4Action.h.
References DD4hep::PropertyManager::add().
enableUI()
void Geant4Action::enableUI () virtual
Enable and install UI messenger.
Definition at line 144 of file Geant4Action.cpp.
error()
void Geant4Action::error (const char * fmt, ...) const
Support of error messages.
Action to support error messages.
Definition at line 233 of file Geant4Action.cpp.
References DD4hep::ERROR, and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::checkConsistency(), DD4hep::Simulation::TrackerWeighted::process(), DD4hep::Simulation::Geant4InputAction::readParticles(), DD4hep::Simulation::Geant4ParticleHandler::rebaseSimulatedTracks(), and DD4hep::Simulation::Geant4Random::showStatus().
eventAction()
Geant4EventActionSequence & Geant4Action::eventAction () const
Access to the main event action sequence from the kernel object.
Definition at line 285 of file Geant4Action.cpp.
References eventAction().
Referenced by eventAction(), DD4hep::Simulation::Geant4EventSeed::Geant4EventSeed(), DD4hep::Simulation::Geant4MaterialScanner::Geant4MaterialScanner(), and DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler().
except()
void Geant4Action::except (const char * fmt, ...) const
Support of exceptions: Print fatal message and throw runtime_error.
Definition at line 258 of file Geant4Action.cpp.
References DD4hep::FATAL, DD4hep::format(), and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::adopt(), DD4hep::Simulation::Geant4PhysicsListActionSequence::adopt(), DD4hep::Simulation::Geant4PhysicsList::adoptPhysicsConstructor(), DD4hep::Simulation::Geant4ParticleHandler::begin(), DD4hep::Simulation::Geant4ParticleHandler::checkConsistency(), DD4hep::Simulation::Geant4SensDetActionSequence::collection(), DD4hep::Simulation::Geant4SensDetActionSequence::collectionByID(), DD4hep::Simulation::Geant4PhysicsList::constructParticles(), DD4hep::Simulation::Geant4PhysicsList::constructPhysics(), DD4hep::Simulation::Geant4DefaultRangeCut::constructProcesses(), DD4hep::Simulation::Geant4PhysicsList::constructProcesses(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::Geant4ReadoutVolumeFilter(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirection(), DD4hep::Simulation::Geant4SensDetActionSequence::hitCollectionName(), DD4hep::Simulation::Geant4Random::initialize(), DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), DD4hep::Simulation::Geant4ParticleHandler::mark(), DD4hep::Simulation::Geant4PhysicsList::processes(), DD4hep::Simulation::Geant4InputAction::readParticles(), DD4hep::Simulation::Geant4Exec::run(), DD4hep::Simulation::Geant4Random::saveStatus(), DD4hep::Simulation::TrackerWeighted::update(), and DD4hep::Simulation::TrackerCombine::update().
fatal()
void Geant4Action::fatal (const char * fmt, ...) const
Support of fatal messages. Throws exception.
Support of fatal messages. Throws exception if required.
Definition at line 250 of file Geant4Action.cpp.
References DD4hep::FATAL, and DD4hep::printout().
generatorAction()
Geant4GeneratorActionSequence & Geant4Action::generatorAction () const
Access to the main generator action sequence from the kernel object.
Definition at line 305 of file Geant4Action.cpp.
References generatorAction().
Referenced by generatorAction().
hasProperty()
bool Geant4Action::hasProperty (const std::string & name) const
Check property for existence.
Definition at line 104 of file Geant4Action.cpp.
info()
void Geant4Action::info (const char * fmt, ...) const
Support of info messages.
Definition at line 217 of file Geant4Action.cpp.
References DD4hep::INFO, and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::beginEvent(), DD4hep::Simulation::Geant4PhysicsListActionSequence::constructDecays(), DD4hep::Simulation::Geant4PhysicsList::constructParticles(), DD4hep::Simulation::Geant4PhysicsList::constructPhysics(), DD4hep::Simulation::Geant4DefaultRangeCut::constructProcesses(), and DD4hep::Simulation::Geant4PhysicsList::constructProcesses().
installCommandMessenger()
void Geant4Action::installCommandMessenger () virtual
Install command control messenger if wanted.
Reimplemented in DD4hep::Simulation::Geant4PhysicsListActionSequence, and DD4hep::Simulation::Geant4PhysicsList.
Definition at line 131 of file Geant4Action.cpp.
installMessengers()
void Geant4Action::installMessengers () virtual
Install property control messenger if wanted.
Install all control messenger if wanted.
Definition at line 114 of file Geant4Action.cpp.
installPropertyMessenger()
void Geant4Action::installPropertyMessenger () virtual
Install property control messenger if wanted.
Definition at line 126 of file Geant4Action.cpp.
name()
const std::string& DD4hep::Simulation::Geant4Action::name () const inline
Access name of the action.
Definition at line 277 of file Geant4Action.h.
Referenced by DD4hep::Simulation::Geant4PhysicsList::adoptPhysicsConstructor(), DD4hep::Simulation::Geant4SensDetActionSequence::begin(), DD4hep::Simulation::Geant4ParticleHandler::checkConsistency(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), DD4hep::Simulation::Geant4Sensitive::detector(), DD4hep::Simulation::Geant4PhysicsList::dump(), DD4hep::Simulation::Geant4PhysicsListActionSequence::dump(), DD4hep::Simulation::Geant4ParticleHandler::dumpMap(), DD4hep::Simulation::Geant4OutputAction::end(), DD4hep::Simulation::Geant4ParticleHandler::end(), DD4hep::Simulation::Geant4SensDetSequences::find(), DD4hep::Simulation::Geant4EscapeCounter::Geant4EscapeCounter(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::Geant4ParticleGun::getParticleDirection(), DD4hep::Simulation::Geant4SensDetSequences::insert(), DD4hep::Simulation::Geant4PhysicsList::installCommandMessenger(), DD4hep::Simulation::Geant4PhysicsListActionSequence::installCommandMessenger(), DD4hep::Simulation::Geant4InputAction::issue(), DD4hep::Simulation::mergeInteractions(), DD4hep::Simulation::Geant4ParticleGenerator::operator()(), DD4hep::Simulation::Geant4Action::FindByName::operator()(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4SensDetSequences::operator[](), DD4hep::Simulation::Geant4ParticleGenerator::printInteraction(), DD4hep::Simulation::Geant4Kernel::registerGlobalAction(), DD4hep::Simulation::Geant4Kernel::registerGlobalFilter(), and DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
outputLevel()
PrintLevel DD4hep::Simulation::Geant4Action::outputLevel () const inline
Access the output level.
Definition at line 293 of file Geant4Action.h.
References DD4hep::except(), and DD4hep::print().
Referenced by DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), DD4hep::Simulation::Geant4ParticleHandler::end(), DD4hep::Simulation::Geant4ParticleHandler::endEvent(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::Geant4InputAction::operator()(), and DD4hep::Simulation::Geant4ParticleGenerator::printInteraction().
print()
void Geant4Action::print (const char * fmt, ...) const
Support for messages with variable output level using output level.
Definition at line 154 of file Geant4Action.cpp.
References DD4hep::printLevel(), DD4hep::printout(), and DD4hep::VERBOSE.
Referenced by DD4hep::Simulation::Geant4InteractionVertexBoost::boost(), DD4hep::Simulation::Geant4DetectorSensitivesConstruction::constructSensitives(), DD4hep::Simulation::TrackerWeighted::endEvent(), DD4hep::Simulation::TrackerWeighted::extractHit(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::Geant4ParticlePrint::makePrintout(), DD4hep::Simulation::Geant4GeneratorActionInit::operator()(), DD4hep::Simulation::Geant4ParticleGun::operator()(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::printInteraction(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), DD4hep::Simulation::Geant4ParticlePrint::printParticles(), DD4hep::Simulation::Geant4ParticlePrint::printParticleTree(), DD4hep::Simulation::Geant4EscapeCounter::process(), DD4hep::Simulation::TrackerWeighted::process(), and DD4hep::Simulation::Geant4InteractionVertexSmear::smear().
printM1()
void Geant4Action::printM1 (const char * fmt, ...) const
Support for messages with variable output level using output level-1.
Definition at line 165 of file Geant4Action.cpp.
References DD4hep::printLevel(), DD4hep::printout(), and DD4hep::VERBOSE.
printM2()
void Geant4Action::printM2 (const char * fmt, ...) const
Support for messages with variable output level using output level-2.
Definition at line 176 of file Geant4Action.cpp.
References DD4hep::printLevel(), DD4hep::printout(), and DD4hep::VERBOSE.
Referenced by DD4hep::Simulation::TrackerCombine::extractHit().
printP1()
void Geant4Action::printP1 (const char * fmt, ...) const
Support for messages with variable output level using output level+1.
Support for messages with variable output level using output level-1.
Definition at line 187 of file Geant4Action.cpp.
References DD4hep::FATAL, DD4hep::printLevel(), and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4GeneratorActionInit::end().
printP2()
void Geant4Action::printP2 (const char * fmt, ...) const
Support for messages with variable output level using output level+2.
Support for messages with variable output level using output level-2.
Definition at line 198 of file Geant4Action.cpp.
References DD4hep::FATAL, DD4hep::printLevel(), and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4MaterialScanner::begin(), DD4hep::Simulation::Geant4Random::setMainInstance(), and DD4hep::Simulation::Geant4Random::showStatus().
properties()
PropertyManager& DD4hep::Simulation::Geant4Action::properties () inline
Access to the properties of the object.
Definition at line 289 of file Geant4Action.h.
Referenced by DD4hep::Converter< T, ARG >::operator()(), DD4hep::Simulation::Geant4SharedStackingAction::use(), DD4hep::Simulation::Geant4SharedSteppingAction::use(), DD4hep::Simulation::Geant4SharedRunAction::use(), DD4hep::Simulation::Geant4SharedTrackingAction::use(), and DD4hep::Simulation::Geant4SharedEventAction::use().
property()
Property & Geant4Action::property (const std::string & name)
Access single property.
Definition at line 109 of file Geant4Action.cpp.
Referenced by DD4hep::Simulation::Geant4Exec::configure().
release()
long Geant4Action::release ()
Decrease reference count. Implicit destruction.
Definition at line 80 of file Geant4Action.cpp.
References DD4hep::typeName().
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::~Geant4DetectorConstructionSequence(), DD4hep::Simulation::Geant4EventActionSequence::~Geant4EventActionSequence(), DD4hep::Simulation::Geant4GeneratorActionSequence::~Geant4GeneratorActionSequence(), DD4hep::Simulation::Geant4PhysicsListActionSequence::~Geant4PhysicsListActionSequence(), DD4hep::Simulation::Geant4RunActionSequence::~Geant4RunActionSequence(), DD4hep::Simulation::Geant4SensDetActionSequence::~Geant4SensDetActionSequence(), DD4hep::Simulation::Geant4Sensitive::~Geant4Sensitive(), DD4hep::Simulation::Geant4StackingActionSequence::~Geant4StackingActionSequence(), DD4hep::Simulation::Geant4SteppingActionSequence::~Geant4SteppingActionSequence(), DD4hep::Simulation::Geant4TrackingActionSequence::~Geant4TrackingActionSequence(), and DD4hep::Simulation::Geant4UserInitializationSequence::~Geant4UserInitializationSequence().
return_error()
bool Geant4Action::return_error (bool return_value, const char * fmt, ...) const
Action to support error messages.
Definition at line 241 of file Geant4Action.cpp.
References DD4hep::ERROR, and DD4hep::printout().
runAction()
Geant4RunActionSequence & Geant4Action::runAction () const
Access to the main run action sequence from the kernel object.
Definition at line 280 of file Geant4Action.cpp.
References runAction().
Referenced by DD4hep::Simulation::Geant4EventSeed::Geant4EventSeed(), and runAction().
setName()
void DD4hep::Simulation::Geant4Action::setName (const std::string & new_name) inline
Set the object name.
Definition at line 285 of file Geant4Action.h.
setOutputLevel()
PrintLevel Geant4Action::setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Definition at line 91 of file Geant4Action.cpp.
setProperties()
Geant4Action & Geant4Action::setProperties (PropertyConfigurator & setup)
Set object properties.
Definition at line 98 of file Geant4Action.cpp.
stackingAction()
Geant4StackingActionSequence & Geant4Action::stackingAction () const
Access to the main stacking action sequence from the kernel object.
Definition at line 300 of file Geant4Action.cpp.
References stackingAction().
Referenced by stackingAction().
steppingAction()
Geant4SteppingActionSequence & Geant4Action::steppingAction () const
Access to the main stepping action sequence from the kernel object.
Definition at line 290 of file Geant4Action.cpp.
References steppingAction().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler(), and steppingAction().
trackingAction()
Geant4TrackingActionSequence & Geant4Action::trackingAction () const
Access to the main tracking action sequence from the kernel object.
Definition at line 295 of file Geant4Action.cpp.
References trackingAction().
Referenced by DD4hep::Simulation::Geant4MaterialScanner::Geant4MaterialScanner(), DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler(), and trackingAction().
updateContext()
virtual void DD4hep::Simulation::Geant4Action::updateContext (Geant4Context * ctxt) inline virtual
Set or update client context.
Reimplemented in DD4hep::Simulation::Geant4SensDetActionSequence, DD4hep::Simulation::Geant4DetectorConstructionSequence, DD4hep::Simulation::Geant4EventActionSequence, DD4hep::Simulation::Geant4TrackingActionSequence, DD4hep::Simulation::Geant4GeneratorActionSequence, DD4hep::Simulation::Geant4RunActionSequence, DD4hep::Simulation::Geant4StackingActionSequence, DD4hep::Simulation::Geant4SteppingActionSequence, and DD4hep::Simulation::Geant4UserInitializationSequence.
Definition at line 271 of file Geant4Action.h.
Referenced by DD4hep::Simulation::Geant4UserInitializationSequence::buildMaster(), DD4hep::Simulation::Geant4Action::ContextSwap::ContextSwap(), DD4hep::Simulation::Geant4DetectorConstructionSequence::updateContext(), and DD4hep::Simulation::Geant4Action::ContextSwap::~ContextSwap().
warning()
void Geant4Action::warning (const char * fmt, ...) const
Support of warning messages.
Definition at line 225 of file Geant4Action.cpp.
References DD4hep::printout(), and DD4hep::WARNING.
Referenced by DD4hep::Simulation::Geant4TrackingPostAction::end(), and DD4hep::Simulation::Geant4ParticleGenerator::printInteraction().
Member Data Documentation
m_context
Geant4Context* DD4hep::Simulation::Geant4Action::m_context protected
Reference to the Geant4 context.
Definition at line 92 of file Geant4Action.h.
Referenced by DD4hep::Simulation::TypeName::split(), DD4hep::Simulation::Geant4TrackingAction::trackMgr(), DD4hep::Simulation::Geant4UserInitializationSequence::updateContext(), DD4hep::Simulation::Geant4SteppingActionSequence::updateContext(), DD4hep::Simulation::Geant4StackingActionSequence::updateContext(), DD4hep::Simulation::Geant4RunActionSequence::updateContext(), DD4hep::Simulation::Geant4GeneratorActionSequence::updateContext(), DD4hep::Simulation::Geant4TrackingActionSequence::updateContext(), DD4hep::Simulation::Geant4EventActionSequence::updateContext(), DD4hep::Simulation::Geant4DetectorConstructionSequence::updateContext(), and DD4hep::Simulation::Geant4SensDetActionSequence::updateContext().
m_control
Geant4UIMessenger* DD4hep::Simulation::Geant4Action::m_control protected
Control directory of this action.
Definition at line 94 of file Geant4Action.h.
m_name
std::string DD4hep::Simulation::Geant4Action::m_name protected
Action name.
Definition at line 101 of file Geant4Action.h.
m_needsControl
bool DD4hep::Simulation::Geant4Action::m_needsControl protected
Default property: Flag to create control instance.
Definition at line 99 of file Geant4Action.h.
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::Geant4DetectorConstructionSequence(), DD4hep::Simulation::Geant4EscapeCounter::Geant4EscapeCounter(), DD4hep::Simulation::Geant4EventActionSequence::Geant4EventActionSequence(), DD4hep::Simulation::Geant4GeneratorActionSequence::Geant4GeneratorActionSequence(), DD4hep::Simulation::Geant4InputAction::Geant4InputAction(), DD4hep::Simulation::Geant4InteractionVertexBoost::Geant4InteractionVertexBoost(), DD4hep::Simulation::Geant4InteractionVertexSmear::Geant4InteractionVertexSmear(), DD4hep::Simulation::Geant4MaterialScanner::Geant4MaterialScanner(), DD4hep::Simulation::Geant4ParticleGenerator::Geant4ParticleGenerator(), DD4hep::Simulation::Geant4ParticleGun::Geant4ParticleGun(), DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler(), DD4hep::Simulation::Geant4PhysicsListActionSequence::Geant4PhysicsListActionSequence(), DD4hep::Simulation::Geant4RunActionSequence::Geant4RunActionSequence(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), DD4hep::Simulation::Geant4StackingActionSequence::Geant4StackingActionSequence(), DD4hep::Simulation::Geant4SteppingActionSequence::Geant4SteppingActionSequence(), DD4hep::Simulation::Geant4TrackingActionSequence::Geant4TrackingActionSequence(), DD4hep::Simulation::Geant4UserInitialization::Geant4UserInitialization(), DD4hep::Simulation::Geant4UserInitializationSequence::Geant4UserInitializationSequence(), and DD4hep::Simulation::Geant4UserParticleHandler::Geant4UserParticleHandler().
m_outputLevel
int DD4hep::Simulation::Geant4Action::m_outputLevel protected
Default property: Output level.
Definition at line 97 of file Geant4Action.h.
m_properties
PropertyManager DD4hep::Simulation::Geant4Action::m_properties protected
Property pool.
Definition at line 103 of file Geant4Action.h.
Referenced by DD4hep::Simulation::Geant4SharedStackingAction::use(), DD4hep::Simulation::Geant4SharedSteppingAction::use(), DD4hep::Simulation::Geant4SharedRunAction::use(), DD4hep::Simulation::Geant4SharedTrackingAction::use(), and DD4hep::Simulation::Geant4SharedEventAction::use().
m_refCount
long DD4hep::Simulation::Geant4Action::m_refCount protected
Reference count. Initial value: 1.
Definition at line 105 of file Geant4Action.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Action.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Action.cpp