DD4hep: DD4hep: DD4hep::Simulation::Geant4EventActionSequence Class Reference
DD4hep::Simulation::Geant4EventActionSequence Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete implementation of the Geant4 event action sequence.
#include <Geant4EventAction.h>
Public Member Functions
Geant4EventActionSequence (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4EventActionSequence ()
Default destructor.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
Geant4EventAction * get (const std::string &name) const
Get an action by name.
template<typename Q , typename T >
void callAtBegin (Q *p, void(T::*f)(const G4Event *))
Register begin-of-event callback.
template<typename Q , typename T >
void callAtEnd (Q *p, void(T::*f)(const G4Event *))
Register end-of-event callback.
template<typename Q , typename T >
void callAtFinal (Q *p, void(T::*f)(const G4Event *))
Register event-cleanup callback (after end-of-event callback -- unordered).
void adopt (Geant4EventAction *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void begin (const G4Event *event)
Begin-of-event callback.
virtual void end (const G4Event *event)
End-of-event callback.
Protected Attributes
CallbackSequence m_begin
Callback sequence for event initialization action.
CallbackSequence m_end
Callback sequence for event finalization action.
CallbackSequence m_final
Callback sequence for event finalization action.
Actors< Geant4EventAction > m_actors
The list of action objects to be called.
Detailed Description
Concrete implementation of the Geant4 event action sequence.
The sequence dispatches the callbacks at the beginning and the and of an event to all registered Geant4EventAction members and all registered callbacks.
Note Multi-Threading issue: Neither callbacks not the action list is protected against multiple threads calling the Geant4 callbacks! These must be protected in the user actions themselves.
Author:
M.Frank
Version:
1.0
Definition at line 115 of file Geant4EventAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4EventActionSequence::Geant4EventActionSequence (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4EventActionSequence::~Geant4EventActionSequence () [virtual]
Default destructor.
Definition at line 108 of file Geant4EventAction.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_begin, m_end, m_final, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
void Geant4EventActionSequence::adopt (Geant4EventAction * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 134 of file Geant4EventAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by DD4hep::Converter< T, ARG >::operator()().
void Geant4EventActionSequence::begin (const G4Event * event) [virtual]
Begin-of-event callback.
Pre-track action callback.
Definition at line 145 of file Geant4EventAction.cpp.
References DD4hep::Simulation::Geant4EventAction::begin(), m_actors, and m_begin.
Referenced by DD4hep::Simulation::Geant4UserEventAction::BeginOfEventAction().
template<typename Q , typename T > void DD4hep::Simulation::Geant4EventActionSequence::callAtBegin (Q * p, void(T::*)(const G4Event *) f) [inline]
Register begin-of-event callback.
Definition at line 138 of file Geant4EventAction.h.
References DD4hep::CallbackSequence::add(), and m_begin.
Referenced by DD4hep::Simulation::Geant4EventSeed::Geant4EventSeed(), and DD4hep::Converter< T, ARG >::operator()().
template<typename Q , typename T > void DD4hep::Simulation::Geant4EventActionSequence::callAtEnd (Q * p, void(T::*)(const G4Event *) f) [inline]
Register end-of-event callback.
Definition at line 143 of file Geant4EventAction.h.
References DD4hep::CallbackSequence::add(), and m_end.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::initialize(), and DD4hep::Converter< T, ARG >::operator()().
template<typename Q , typename T > void DD4hep::Simulation::Geant4EventActionSequence::callAtFinal (Q * p, void(T::*)(const G4Event *) f) [inline]
Register event-cleanup callback (after end-of-event callback -- unordered).
Definition at line 148 of file Geant4EventAction.h.
References DD4hep::CallbackSequence::add(), and m_final.
void Geant4EventActionSequence::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 124 of file Geant4EventAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_actors.
void Geant4EventActionSequence::end (const G4Event * event) [virtual]
End-of-event callback.
Post-track action callback.
Definition at line 151 of file Geant4EventAction.cpp.
References DD4hep::Simulation::Geant4EventAction::end(), m_actors, m_end, and m_final.
Referenced by DD4hep::Simulation::Geant4UserEventAction::EndOfEventAction().
Geant4EventAction* DD4hep::Simulation::Geant4EventActionSequence::get (const std::string & name) const
Get an action by name.
void Geant4EventActionSequence::updateContext (Geant4Context * ctxt) [virtual]
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 118 of file Geant4EventAction.cpp.
References m_actors, and DD4hep::Simulation::Geant4Action::m_context.
Member Data Documentation
Actors<Geant4EventAction> DD4hep::Simulation::Geant4EventActionSequence::m_actors [protected]
The list of action objects to be called.
Definition at line 124 of file Geant4EventAction.h.
Referenced by adopt(), begin(), configureFiber(), end(), updateContext(), and ~Geant4EventActionSequence().
CallbackSequence DD4hep::Simulation::Geant4EventActionSequence::m_begin [protected]
Callback sequence for event initialization action.
Definition at line 118 of file Geant4EventAction.h.
Referenced by begin(), callAtBegin(), and ~Geant4EventActionSequence().
CallbackSequence DD4hep::Simulation::Geant4EventActionSequence::m_end [protected]
Callback sequence for event finalization action.
Definition at line 120 of file Geant4EventAction.h.
Referenced by callAtEnd(), end(), and ~Geant4EventActionSequence().
CallbackSequence DD4hep::Simulation::Geant4EventActionSequence::m_final [protected]
Callback sequence for event finalization action.
Definition at line 122 of file Geant4EventAction.h.
Referenced by callAtFinal(), end(), and ~Geant4EventActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4EventAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4EventAction.cpp