DD4hep: DD4hep::ContextMenuHandler Class Reference
DD4hep::ContextMenuHandler Class Reference
#include <DDEve/ContextMenu.h>
Public Member Functions
ContextMenuHandler (Callback cb, void *param)
Initializing constructor.
virtual ~ContextMenuHandler ()
Default destructor.
void * param () const
User parameter hook.
void Context (TObject *target)
Callback.
ClassDef (ContextMenuHandler, 0)
Root implementation macro.
Protected Attributes
Callback m_call
User callback.
void * m_param
User parameter.
Detailed Description
Author
M.Frank
Version
1.0
Definition at line 36 of file ContextMenu.h.
Constructor & Destructor Documentation
ContextMenuHandler()
DD4hep::ContextMenuHandler::ContextMenuHandler (Callback cb, void * param)
Initializing constructor.
~ContextMenuHandler()
ContextMenuHandler::~ContextMenuHandler () virtual
Default destructor.
Definition at line 44 of file ContextMenu.cpp.
Member Function Documentation
ClassDef()
DD4hep::ContextMenuHandler::ClassDef (ContextMenuHandler , 0)
Root implementation macro.
Referenced by DD4hep::ContextMenu::Add(), and param().
Context()
void ContextMenuHandler::Context (TObject * target)
Callback.
Definition at line 48 of file ContextMenu.cpp.
Referenced by param().
param()
void* DD4hep::ContextMenuHandler::param () const inline
User parameter hook.
Definition at line 48 of file ContextMenu.h.
References ClassDef(), Context(), and m_param.
Member Data Documentation
m_call
Callback DD4hep::ContextMenuHandler::m_call protected
User callback.
Definition at line 39 of file ContextMenu.h.
m_param
void* DD4hep::ContextMenuHandler::m_param protected
User parameter.
Definition at line 41 of file ContextMenu.h.
Referenced by param().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/ContextMenu.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/ContextMenu.cpp