DD4hep: DD4hep::XML::UriContextReader Class Reference
DD4hep::XML::UriContextReader Class Reference
DD4hep::XML classes and objects
Class supporting to read data given a URI.
#include <UriReader.h>
Public Member Functions
UriContextReader (UriReader *reader, UriReader::UserContext *ctxt)
Default initializing constructor.
UriContextReader (const UriContextReader &copy)
Copy constructor.
virtual ~UriContextReader ()
Default destructor.
virtual UserContext * context ()
Access to local context.
virtual bool load (const std::string &system_id, std::string &data)
Resolve a given URI to a string containing the data.
virtual bool load (const std::string &system_id, UserContext *context, std::string &data)
Resolve a given URI to a string containing the data with context.
virtual void parserLoaded (const std::string &system_id)
Inform reader about a locally (e.g. by XercesC) handled source load.
virtual void parserLoaded (const std::string &system_id, UserContext *ctxt)
Inform reader about a locally (e.g. by XercesC) handled source load.
Public Member Functions inherited from DD4hep::XML::UriReader
UriReader ()
Default constructor.
virtual ~UriReader ()
Default destructor.
Protected Attributes
UriReader * m_reader
Pointer to true reader object.
UriReader::UserContext * m_context
Pointer to user context.
Detailed Description
Class supporting to read data given a URI.
Wrapper to read XML URI using a virtual reader instance. This implementation allows to externally chain an argument structure to the resolution function, which allows to set/retrieve further arguments such as e.g. conditions IOVs.
Author
M.Frank
Version
1.0
Definition at line 71 of file UriReader.h.
Constructor & Destructor Documentation
UriContextReader() [1/2]
DD4hep::XML::UriContextReader::UriContextReader (UriReader * reader, UriReader::UserContext * ctxt)
Default initializing constructor.
Default constructor.
Definition at line 33 of file UriReader.cpp.
UriContextReader() [2/2]
DD4hep::XML::UriContextReader::UriContextReader (const UriContextReader & copy)
Copy constructor.
Definition at line 39 of file UriReader.cpp.
~UriContextReader()
DD4hep::XML::UriContextReader::~UriContextReader () virtual
Default destructor.
Definition at line 45 of file UriReader.cpp.
Member Function Documentation
context()
virtual UserContext* DD4hep::XML::UriContextReader::context () inline virtual
Access to local context.
Reimplemented from DD4hep::XML::UriReader.
Definition at line 85 of file UriReader.h.
References DD4hep::XML::UriReader::context(), DD4hep::XML::UriReader::load(), and DD4hep::XML::UriReader::parserLoaded().
Referenced by load(), and parserLoaded().
load() [1/2]
bool DD4hep::XML::UriContextReader::load (const std::string & system_id, std::string & data) virtual
Resolve a given URI to a string containing the data.
Reimplemented from DD4hep::XML::UriReader.
Definition at line 49 of file UriReader.cpp.
References context(), DD4hep::XML::UriReader::load(), and m_reader.
load() [2/2]
bool DD4hep::XML::UriContextReader::load (const std::string & system_id, UserContext * context, std::string & data) virtual
Resolve a given URI to a string containing the data with context.
Resolve a given URI to a string containing the data.
Implements DD4hep::XML::UriReader.
Definition at line 54 of file UriReader.cpp.
References DD4hep::XML::UriReader::load(), and m_reader.
parserLoaded() [1/2]
void DD4hep::XML::UriContextReader::parserLoaded (const std::string & system_id) virtual
Inform reader about a locally (e.g. by XercesC) handled source load.
Reimplemented from DD4hep::XML::UriReader.
Definition at line 59 of file UriReader.cpp.
References context(), m_reader, and DD4hep::XML::UriReader::parserLoaded().
parserLoaded() [2/2]
void DD4hep::XML::UriContextReader::parserLoaded (const std::string & system_id, UserContext * ctxt) virtual
Inform reader about a locally (e.g. by XercesC) handled source load.
Implements DD4hep::XML::UriReader.
Definition at line 64 of file UriReader.cpp.
References m_reader, and DD4hep::XML::UriReader::parserLoaded().
Member Data Documentation
m_context
UriReader::UserContext* DD4hep::XML::UriContextReader::m_context protected
Pointer to user context.
Definition at line 76 of file UriReader.h.
m_reader
UriReader* DD4hep::XML::UriContextReader::m_reader protected
Pointer to true reader object.
Definition at line 74 of file UriReader.h.
Referenced by load(), and parserLoaded().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/UriReader.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/UriReader.cpp