DD4hep: DD4hep::Simulation::Geant4Run Class Reference
DD4hep::Simulation::Geant4Run Class Reference
DD4hep::Simulation components, classes and objects
User run context for DDG4.
#include <Geant4Context.h>
Public Member Functions
Geant4Run (const G4Run *run)
Intializing constructor.
virtual ~Geant4Run ()
Default destructor.
operator const G4Run & () const
Access the G4Run directly: Automatic type conversion.
const G4Run & run () const
Access the G4Event directly: Explicit G4Run accessor.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
template<typename T >
T * addExtension (T *ptr, bool take_ownership=true)
Add user extension object. Ownership is transferred!
template<typename T >
T * extension (bool alert=true)
Access to type safe extension object. Exception is thrown if the object is invalid.
Public Member Functions inherited from DD4hep::ObjectExtensions
ObjectExtensions (const std::type_info &parent_type)
Default constructor.
ObjectExtensions (const ObjectExtensions &copy)=delete
Copy constructor.
virtual ~ObjectExtensions ()
Default destructor.
ObjectExtensions & operator= (const ObjectExtensions &copy)=delete
Assignment operator.
void move (ObjectExtensions &copy)
Move extensions to target object.
void clear (bool destroy=true)
Clear all extensions.
void copyFrom (const Extensions &ext, void *arg)
Copy object extensions from another object. Hosting type must be identical!
void * addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
void * removeExtension (const std::type_info &info, bool destroy)
Remove an existing extension object from the instance.
void * extension (const std::type_info &info, bool alert) const
Access an existing extension object from the detector element.
void * extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Private Attributes
const G4Run * m_run
Reference to the original Geant4 run object.
Additional Inherited Members
Public Types inherited from DD4hep::ObjectExtensions
typedef std::map< const std::type_info *, void * > Extensions
Definition of the extension type.
typedef void *(* copy_t) (const void *, void *arg)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< const std::type_info *, Entry > ExtensionMap
Static Public Member Functions inherited from DD4hep::ObjectExtensions
static void _noDelete (void *)
Function to be passed as dtor if object should NOT be deleted!
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Public Attributes inherited from DD4hep::ObjectExtensions
Extensions extensions
The extensions object.
ExtensionMap * extensionMap
Pointer to the extension map.
Detailed Description
User run context for DDG4.
The context is accessible from the Geant4Context pointer, which is present in every Geant4Action. The run context is only valid however, if there is actually an run being procesed ie. only during the lifetime of the corresponding G4Run objects.
Please note: Extensions are only valid within the hosting run and are INVALID across different runs. Hence: They are only useful to extend data of an run.
Author
M.Frank
Version
1.0
Definition at line 71 of file Geant4Context.h.
Constructor & Destructor Documentation
Geant4Run()
Geant4Run::Geant4Run (const G4Run * run)
Intializing constructor.
Definition at line 29 of file Geant4Context.cpp.
References DD4hep::InstanceCount::increment().
~Geant4Run()
Geant4Run::~Geant4Run () virtual
Default destructor.
Definition at line 36 of file Geant4Context.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
addExtension() [1/2]
void* DD4hep::Simulation::Geant4Run::addExtension (void * ptr, const std::type_info & info, destruct_t dtor) inline
Add an extension object to the detector element.
Note: To add an extension, which should NOT be deleted, set 'dtor' to ObjectExtensions::_noDelete or 0.
Definition at line 90 of file Geant4Context.h.
References DD4hep::ObjectExtensions::addExtension().
addExtension() [2/2]
template<typename T > T* DD4hep::Simulation::Geant4Run::addExtension (T * ptr, bool take_ownership = true) inline
Add user extension object. Ownership is transferred!
Definition at line 94 of file Geant4Context.h.
References DD4hep::ObjectExtensions::addExtension().
extension()
template<typename T > T* DD4hep::Simulation::Geant4Run::extension (bool alert = true) inline
Access to type safe extension object. Exception is thrown if the object is invalid.
Definition at line 99 of file Geant4Context.h.
References DD4hep::ObjectExtensions::extension().
operator const G4Run &()
DD4hep::Simulation::Geant4Run::operator const G4Run & () const inline
Access the G4Run directly: Automatic type conversion.
Definition at line 82 of file Geant4Context.h.
run()
const G4Run& DD4hep::Simulation::Geant4Run::run () const inline
Access the G4Event directly: Explicit G4Run accessor.
Definition at line 84 of file Geant4Context.h.
Referenced by DD4hep::Simulation::Test::Geant4TestEventAction::begin(), and DD4hep::Simulation::Test::Geant4TestEventAction::end().
Member Data Documentation
m_run
const G4Run* DD4hep::Simulation::Geant4Run::m_run private
Reference to the original Geant4 run object.
Definition at line 73 of file Geant4Context.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Context.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Context.cpp