DD4hep: DD4hep::Geometry::LCDDData::ObjectHandleMap Class Reference
DD4hep::Geometry::LCDDData::ObjectHandleMap Class Reference
DD4hep::Geometry components, classes and objects
Implementation of a map of named DD4hep Handles.
#include <LCDDData.h>
Public Member Functions
ObjectHandleMap ()
Default constructor.
void append (const Ref_t &e, bool throw_on_doubles=true)
template<typename T >
void append (const Ref_t &e, bool throw_on_doubles=true)
Detailed Description
Implementation of a map of named DD4hep Handles.
Author
M.Frank
Version
1.0
Definition at line 61 of file LCDDData.h.
Constructor & Destructor Documentation
ObjectHandleMap()
DD4hep::Geometry::LCDDData::ObjectHandleMap::ObjectHandleMap () inline
Default constructor.
Definition at line 64 of file LCDDData.h.
Member Function Documentation
append() [1/2]
void DD4hep::Geometry::LCDDData::ObjectHandleMap::append (const Ref_t & e, bool throw_on_doubles = true) inline
Definition at line 66 of file LCDDData.h.
References DD4hep::Geometry::LCDDData::InvalidObjectError::InvalidObjectError(), DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Geometry::LCDDImp::addAlignment(), DD4hep::Geometry::LCDDImp::addConstant(), DD4hep::Geometry::LCDDImp::addDetector(), DD4hep::Geometry::LCDDImp::addField(), DD4hep::Geometry::LCDDImp::addIDSpecification(), DD4hep::Geometry::LCDDImp::addLimitSet(), DD4hep::Geometry::LCDDImp::addReadout(), DD4hep::Geometry::LCDDImp::addRegion(), DD4hep::Geometry::LCDDImp::addSensitiveDetector(), DD4hep::Geometry::LCDDImp::addVisAttribute(), and DD4hep::Geometry::LCDDImp::init().
append() [2/2]
template<typename T > void DD4hep::Geometry::LCDDData::ObjectHandleMap::append (const Ref_t & e, bool throw_on_doubles = true) inline
Definition at line 77 of file LCDDData.h.
References DD4hep::Geometry::LCDDData::InvalidObjectError::InvalidObjectError(), and DD4hep::Handle< T >::ptr().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/LCDDData.h