DD4hep: DD4hep::Simulation::Geant4HitWrapper Class Reference
DD4hep::Simulation::Geant4HitWrapper Class Reference
DD4hep::Simulation components, classes and objects
Generic wrapper class for hit structures created in Geant4 sensitive detectors.
#include <Geant4HitCollection.h>
Classes
class HitManipulator
Generic type manipulation class for generic hit structures created in Geant4 sensitive detectors.
class InvalidHit
Helper class to indicate invalid hit wrappers or containers.
Public Types
typedef HitManipulator::Wrapper Wrapper
Public Member Functions
Geant4HitWrapper ()
Default constructor.
Geant4HitWrapper (const Geant4HitWrapper &v)
Copy constructor.
Geant4HitWrapper (const Wrapper &v)
Copy constructor.
virtual ~Geant4HitWrapper ()
Default destructor.
void * operator new (size_t)
Geant4 required object allocator.
void operator delete (void *ptr)
Geant4 required object destroyer.
void * release ()
Pointer/Object release.
Wrapper releaseData ()
Release data for copy.
HitManipulator * manip () const
Access to cast grammar.
void * data ()
Pointer/Object access.
void * data () const
Pointer/Object access (CONST)
Geant4HitWrapper & operator= (const Geant4HitWrapper &v)
Assignment transfers the pointer ownership.
template<typename TYPE >
operator TYPE * () const
Automatic conversion to the desired type.
Static Public Member Functions
template<typename TYPE >
static HitManipulator * manipulator ()
Generate manipulator object.
Protected Attributes
Wrapper m_data
Detailed Description
Generic wrapper class for hit structures created in Geant4 sensitive detectors.
Default base class for all geant 4 created hits. The hit is stored in an opaque way and can be accessed by the collection.
Author
M.Frank
Version
1.0
Definition at line 51 of file Geant4HitCollection.h.
Member Typedef Documentation
Wrapper
typedef HitManipulator::Wrapper DD4hep::Simulation::Geant4HitWrapper::Wrapper
Definition at line 107 of file Geant4HitCollection.h.
Constructor & Destructor Documentation
Geant4HitWrapper() [1/3]
DD4hep::Simulation::Geant4HitWrapper::Geant4HitWrapper () inline
Default constructor.
Definition at line 114 of file Geant4HitCollection.h.
Geant4HitWrapper() [2/3]
DD4hep::Simulation::Geant4HitWrapper::Geant4HitWrapper (const Geant4HitWrapper & v) inline
Copy constructor.
Definition at line 119 of file Geant4HitCollection.h.
References m_data.
Geant4HitWrapper() [3/3]
DD4hep::Simulation::Geant4HitWrapper::Geant4HitWrapper (const Wrapper & v) inline
Copy constructor.
Definition at line 125 of file Geant4HitCollection.h.
References release(), releaseData(), v, and ~Geant4HitWrapper().
~Geant4HitWrapper()
Geant4HitWrapper::~Geant4HitWrapper () virtual
Default destructor.
Definition at line 41 of file Geant4HitCollection.cpp.
References m_data.
Referenced by Geant4HitWrapper().
Member Function Documentation
data() [1/2]
void* DD4hep::Simulation::Geant4HitWrapper::data () inline
Pointer/Object access.
Definition at line 143 of file Geant4HitCollection.h.
Referenced by DD4hep::Simulation::Geant4HitCollection::getData(), and DD4hep::Simulation::Geant4HitCollection::getHitsUnchecked().
data() [2/2]
void* DD4hep::Simulation::Geant4HitWrapper::data () const inline
Pointer/Object access (CONST)
Definition at line 147 of file Geant4HitCollection.h.
manip()
HitManipulator* DD4hep::Simulation::Geant4HitWrapper::manip () const inline
Access to cast grammar.
Definition at line 139 of file Geant4HitCollection.h.
Referenced by DD4hep::Simulation::Geant4HitCollection::getData(), and DD4hep::Simulation::Geant4HitCollection::releaseData().
manipulator()
template<typename TYPE > static HitManipulator* DD4hep::Simulation::Geant4HitWrapper::manipulator () inline static
Generate manipulator object.
Definition at line 151 of file Geant4HitCollection.h.
operator delete()
void Geant4HitWrapper::operator delete (void * ptr)
Geant4 required object destroyer.
Geat4 required object destroyer.
Definition at line 57 of file Geant4HitCollection.cpp.
References HitWrapperAllocator.
operator new()
void * Geant4HitWrapper::operator new (size_t)
Geant4 required object allocator.
Definition at line 49 of file Geant4HitCollection.cpp.
References HitWrapperAllocator.
operator TYPE *()
template<typename TYPE > DD4hep::Simulation::Geant4HitWrapper::operator TYPE * () const inline
Automatic conversion to the desired type.
Definition at line 164 of file Geant4HitCollection.h.
operator=()
Geant4HitWrapper& DD4hep::Simulation::Geant4HitWrapper::operator= (const Geant4HitWrapper & v) inline
Assignment transfers the pointer ownership.
Definition at line 155 of file Geant4HitCollection.h.
References m_data.
release()
void * Geant4HitWrapper::release ()
Pointer/Object release.
Definition at line 62 of file Geant4HitCollection.cpp.
References m_data.
Referenced by Geant4HitWrapper(), DD4hep::Simulation::moveEntries(), DD4hep::Simulation::Geant4HitCollection::releaseData(), and DD4hep::Simulation::Geant4HitCollection::releaseHitsUnchecked().
releaseData()
Geant4HitWrapper::Wrapper Geant4HitWrapper::releaseData ()
Release data for copy.
Pointer/Object release.
Definition at line 70 of file Geant4HitCollection.cpp.
References m_data.
Referenced by Geant4HitWrapper(), and DD4hep::Simulation::Geant4HitCollection::releaseHits().
Member Data Documentation
m_data
Wrapper DD4hep::Simulation::Geant4HitWrapper::m_data mutable protected
Definition at line 109 of file Geant4HitCollection.h.
Referenced by Geant4HitWrapper(), operator=(), release(), releaseData(), and ~Geant4HitWrapper().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4HitCollection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4HitCollection.cpp