DD4hep: DD4hep::Grammar< TYPE > Class Template Reference
DD4hep::Grammar< TYPE > Class Template Reference
DD4hep classes and objects
Concrete type dependent grammar definition.
#include <BasicGrammar_inl.h>
Public Member Functions
Grammar ()
Standarsd constructor.
virtual ~Grammar ()
Default destructor.
virtual const std::type_info & type () const
PropertyGrammar overload: Access to the type information.
virtual const std::string & type_name () const
Access to the type information name.
virtual size_t sizeOf () const
Access the object size (sizeof operator)
virtual std::string str (const void *ptr) const
PropertyGrammar overload: Serialize a property to a string.
virtual bool fromString (void *ptr, const std::string &value) const
PropertyGrammar overload: Retrieve value from string.
virtual int evaluate (void *ptr, const std::string &value) const
Evaluate string value if possible before calling boost::spirit.
Public Member Functions inherited from DD4hep::BasicGrammar
BasicGrammar ()
Default constructor.
virtual ~BasicGrammar ()
Default destructor.
Private Attributes
std::string m_typeName
Cached type information name.
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::BasicGrammar
template<typename TYPE >
static const BasicGrammar & instance ()
Instance factory.
static void invalidConversion (const std::type_info &from, const std::type_info &to)
Error callback on invalid conversion.
static void invalidConversion (const std::string &value, const std::type_info &to)
Error callback on invalid conversion.
Detailed Description
template<typename TYPE>
class DD4hep::Grammar< TYPE >
Concrete type dependent grammar definition.
Author
M.Frank
Date
13.08.2013
Definition at line 63 of file BasicGrammar_inl.h.
Constructor & Destructor Documentation
Grammar()
template<typename TYPE > DD4hep::Grammar< TYPE >::Grammar ()
Standarsd constructor.
Definition at line 86 of file BasicGrammar_inl.h.
References DD4hep::Grammar< TYPE >::m_typeName, and DD4hep::typeName().
~Grammar()
template<typename TYPE > DD4hep::Grammar< TYPE >::~Grammar () virtual
Default destructor.
Definition at line 91 of file BasicGrammar_inl.h.
Member Function Documentation
evaluate()
template<typename TYPE > int DD4hep::Grammar< TYPE >::evaluate (void * ptr, const std::string & value) const virtual
Evaluate string value if possible before calling boost::spirit.
Definition at line 110 of file BasicGrammar_inl.h.
Referenced by DD4hep::Grammar< TYPE >::fromString().
fromString()
template<typename TYPE > bool DD4hep::Grammar< TYPE >::fromString (void * ptr, const std::string & value) const virtual
PropertyGrammar overload: Retrieve value from string.
Implements DD4hep::BasicGrammar.
Definition at line 115 of file BasicGrammar_inl.h.
References DD4hep::Grammar< TYPE >::evaluate(), DD4hep::BasicGrammar::invalidConversion(), and DD4hep::Parsers::parse().
Referenced by DD4hep::eval_obj().
sizeOf()
template<typename TYPE > size_t DD4hep::Grammar< TYPE >::sizeOf () const virtual
Access the object size (sizeof operator)
Implements DD4hep::BasicGrammar.
Definition at line 105 of file BasicGrammar_inl.h.
str()
template<typename TYPE > std::string DD4hep::Grammar< TYPE >::str (const void * ptr) const virtual
PropertyGrammar overload: Serialize a property to a string.
Serialize a property to a string.
Implements DD4hep::BasicGrammar.
Definition at line 142 of file BasicGrammar_inl.h.
References DD4hep::Utils::toStream().
type()
template<typename TYPE > const std::type_info & DD4hep::Grammar< TYPE >::type () const virtual
PropertyGrammar overload: Access to the type information.
Implements DD4hep::BasicGrammar.
Definition at line 95 of file BasicGrammar_inl.h.
type_name()
template<typename TYPE > const std::string & DD4hep::Grammar< TYPE >::type_name () const virtual
Access to the type information name.
PropertyGrammar overload: Access to the type information.
Implements DD4hep::BasicGrammar.
Definition at line 100 of file BasicGrammar_inl.h.
References DD4hep::Grammar< TYPE >::m_typeName.
Member Data Documentation
m_typeName
template<typename TYPE > std::string DD4hep::Grammar< TYPE >::m_typeName private
Cached type information name.
Definition at line 65 of file BasicGrammar_inl.h.
Referenced by DD4hep::Grammar< TYPE >::Grammar(), and DD4hep::Grammar< TYPE >::type_name().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/BasicGrammar_inl.h