DD4hep: DD4hep: DD4hep::Simulation::Geant4PhysicsList Class Reference
DD4hep::Simulation::Geant4PhysicsList Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete basic implementation of a Geant4 physics list action.
#include <Geant4PhysicsList.h>
Classes
class ParticleConstructor
Structure describing a G4 particle constructor.
class PhysicsConstructor
Structure describing a G4 physics constructor.
class Process
Structure describing a G4 process.
Public Types
typedef std::vector< Process > ParticleProcesses
typedef std::map< std::string,
ParticleProcesses > PhysicsProcesses
typedef std::vector
< ParticleConstructor > ParticleConstructors
typedef std::vector
< PhysicsConstructor > PhysicsConstructors
Public Member Functions
Geant4PhysicsList (Geant4Context *context, const std::string &nam)
Standard constructor with initailization parameters.
virtual ~Geant4PhysicsList ()
Default destructor.
void dump ()
Dump content to stdout.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
PhysicsProcesses & processes ()
Access all physics processes.
const PhysicsProcesses & processes () const
Access all physics processes.
ParticleProcesses & processes (const std::string &part_name)
Access processes for one particle type.
const ParticleProcesses & processes (const std::string &part_name) const
Access processes for one particle type (CONST).
ParticleConstructors & particles ()
Access all physics particles.
const ParticleConstructors & particles () const
Access all physics particles.
PhysicsConstructors & physics ()
Access all physics constructors.
const PhysicsConstructors & physics () const
Access all physics constructors.
void addParticleConstructor (const std::string &part_name)
Add physics particle constructor by name.
void addParticleProcess (const std::string &part_name, const std::string &proc_name, int ordAtRestDoIt, int ordAlongSteptDoIt, int ordPostStepDoIt)
Add particle process by name with arguments.
void addPhysicsConstructor (const std::string &physics_name)
Add PhysicsConstructor by name.
void adoptPhysicsConstructor (Geant4Action *action)
Add PhysicsConstructor as Geant4Action object.
virtual void constructPhysics (G4VModularPhysicsList *physics)
constructPhysics callback
virtual void constructParticles (G4VUserPhysicsList *physics)
Callback to construct particles.
virtual void constructProcesses (G4VUserPhysicsList *physics)
Callback to construct processes (uses the G4 particle table).
Public Attributes
PhysicsProcesses m_processes
ParticleConstructors m_particles
PhysicsConstructors m_physics
Detailed Description
Concrete basic implementation of a Geant4 physics list action.
Author:
M.Frank
Version:
1.0
Definition at line 42 of file Geant4PhysicsList.h.
Member Typedef Documentation
typedef std::vector<ParticleConstructor> DD4hep::Simulation::Geant4PhysicsList::ParticleConstructors
Definition at line 81 of file Geant4PhysicsList.h.
typedef std::vector<Process> DD4hep::Simulation::Geant4PhysicsList::ParticleProcesses
Definition at line 65 of file Geant4PhysicsList.h.
typedef std::vector<PhysicsConstructor> DD4hep::Simulation::Geant4PhysicsList::PhysicsConstructors
Definition at line 106 of file Geant4PhysicsList.h.
typedef std::map<std::string, ParticleProcesses> DD4hep::Simulation::Geant4PhysicsList::PhysicsProcesses
Definition at line 66 of file Geant4PhysicsList.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4PhysicsList::Geant4PhysicsList (Geant4Context * context, const std::string & nam)
Standard constructor with initailization parameters.
Geant4PhysicsList::~Geant4PhysicsList () [virtual]
Default destructor.
Definition at line 124 of file Geant4PhysicsList.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4PhysicsList::addParticleConstructor (const std::string & part_name)
Add physics particle constructor by name.
Definition at line 155 of file Geant4PhysicsList.cpp.
References particles().
void Geant4PhysicsList::addParticleProcess (const std::string & part_name, const std::string & proc_name, int ordAtRestDoIt, int ordAlongSteptDoIt, int ordPostStepDoIt)
Add particle process by name with arguments.
Definition at line 160 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4PhysicsList::Process::name, DD4hep::Simulation::Geant4PhysicsList::Process::ordAlongSteptDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordAtRestDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordPostStepDoIt, and processes().
void Geant4PhysicsList::addPhysicsConstructor (const std::string & physics_name)
Add PhysicsConstructor by name.
This constructor is used for intrinsic Geant4 defined physics constructors. Such physics constructors are only created by the factory and attached to the physics list object.
Definition at line 175 of file Geant4PhysicsList.cpp.
References physics().
void Geant4PhysicsList::adoptPhysicsConstructor (Geant4Action * action)
Add PhysicsConstructor as Geant4Action object.
Add PhysicsConstructor by name.
The action object must bve a sub-class of type G4VPhysicsConstructor. -- The Geant4Action object to supports properties. -- Specific user actions may be implemented in the base class calls to 'ConstructParticle' or 'ConstructProcess'. Both calls are invoked by the framework when the physics list is configured for the use in the run-manager.
Definition at line 200 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), m_physics, and DD4hep::Simulation::Geant4Action::name().
void Geant4PhysicsList::constructParticles (G4VUserPhysicsList * physics) [virtual]
Callback to construct particles.
constructParticle callback
Now define all particles
Check if we have here a particle group constructor
Definition at line 234 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::debug(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Action::info(), and m_particles.
Referenced by DD4hep::Simulation::Geant4PhysicsListActionSequence::constructParticles().
void Geant4PhysicsList::constructPhysics (G4VModularPhysicsList * physics) [virtual]
constructPhysics callback
Callback to construct particle decays.
Reimplemented in DD4hep::Simulation::Geant4PhysicsConstructor.
Definition at line 216 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::debug(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Action::info(), and m_physics.
Referenced by DD4hep::Simulation::Geant4PhysicsListActionSequence::constructPhysics().
void Geant4PhysicsList::constructProcesses (G4VUserPhysicsList * physics) [virtual]
Callback to construct processes (uses the G4 particle table).
Reimplemented in DD4hep::Simulation::Geant4DefaultRangeCut.
Definition at line 252 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::debug(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Action::info(), m_processes, DD4hep::Simulation::Geant4PhysicsList::Process::name, DD4hep::Simulation::Geant4PhysicsList::Process::ordAlongSteptDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordAtRestDoIt, and DD4hep::Simulation::Geant4PhysicsList::Process::ordPostStepDoIt.
Referenced by DD4hep::Simulation::Geant4PhysicsListActionSequence::constructProcesses().
void Geant4PhysicsList::dump ()
Dump content to stdout.
Definition at line 134 of file Geant4PhysicsList.cpp.
References DD4hep::ALWAYS, m_particles, m_physics, m_processes, DD4hep::Simulation::Geant4PhysicsList::Process::name, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4PhysicsList::Process::ordAlongSteptDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordAtRestDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordPostStepDoIt, and DD4hep::printout().
Referenced by DD4hep::Simulation::Geant4PhysicsListActionSequence::dump(), and installCommandMessenger().
void Geant4PhysicsList::installCommandMessenger () [virtual]
Install command control messenger if wanted.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 129 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4UIMessenger::addCall(), DD4hep::Simulation::Geant4Action::control(), dump(), and DD4hep::Simulation::Geant4Action::name().
const ParticleConstructors& DD4hep::Simulation::Geant4PhysicsList::particles () const [inline]
Access all physics particles.
Definition at line 138 of file Geant4PhysicsList.h.
References m_particles.
ParticleConstructors& DD4hep::Simulation::Geant4PhysicsList::particles () [inline]
Access all physics particles.
Definition at line 134 of file Geant4PhysicsList.h.
References m_particles.
Referenced by addParticleConstructor().
const PhysicsConstructors& DD4hep::Simulation::Geant4PhysicsList::physics () const [inline]
Access all physics constructors.
Definition at line 146 of file Geant4PhysicsList.h.
References m_physics.
PhysicsConstructors& DD4hep::Simulation::Geant4PhysicsList::physics () [inline]
Access all physics constructors.
Definition at line 142 of file Geant4PhysicsList.h.
References m_physics.
Referenced by addPhysicsConstructor().
const ParticleProcesses& DD4hep::Simulation::Geant4PhysicsList::processes (const std::string & part_name) const
Access processes for one particle type (CONST).
ParticleProcesses& DD4hep::Simulation::Geant4PhysicsList::processes (const std::string & part_name)
Access processes for one particle type.
const PhysicsProcesses& DD4hep::Simulation::Geant4PhysicsList::processes () const [inline]
Access all physics processes.
Definition at line 126 of file Geant4PhysicsList.h.
References m_processes.
PhysicsProcesses& DD4hep::Simulation::Geant4PhysicsList::processes () [inline]
Access all physics processes.
Definition at line 122 of file Geant4PhysicsList.h.
References m_processes.
Referenced by addParticleProcess().
Member Data Documentation
ParticleConstructors DD4hep::Simulation::Geant4PhysicsList::m_particles
Definition at line 109 of file Geant4PhysicsList.h.
Referenced by constructParticles(), dump(), and particles().
PhysicsConstructors DD4hep::Simulation::Geant4PhysicsList::m_physics
Definition at line 110 of file Geant4PhysicsList.h.
Referenced by adoptPhysicsConstructor(), constructPhysics(), dump(), and physics().
PhysicsProcesses DD4hep::Simulation::Geant4PhysicsList::m_processes
Definition at line 108 of file Geant4PhysicsList.h.
Referenced by constructProcesses(), dump(), and processes().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4PhysicsList.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4PhysicsList.cpp