DD4hep: DD4hep::Layering Class Reference
DD4hep::Layering Class Reference
DD4hep classes and objects
Class to convert a layering object from the compact notation.
#include <Layering.h>
Public Member Functions
Layering ()
Default constructor.
Layering (XML::Element e)
Initializing constructor.
virtual ~Layering ()
Default destructor.
std::vector< Layer * > & layers ()
const Layer * layer (size_t which) const
double totalThickness () const
double singleLayerThickness (XML::Element e) const
double absorberThicknessInLayer (XML::Element e) const
void sensitivePositionsInLayer (XML::Element e, std::vector< double > &sens_pos) const
Public Attributes
LayerStack _stack
Detailed Description
Class to convert a layering object from the compact notation.
Author
M.Frank
Version
1.0
Definition at line 138 of file Layering.h.
Constructor & Destructor Documentation
Layering() [1/2]
Layering::Layering ()
Default constructor.
Definition at line 76 of file Layering.cpp.
Layering() [2/2]
Layering::Layering (XML::Element e)
Initializing constructor.
Definition at line 79 of file Layering.cpp.
References DD4hep::XML::LayeringCnv::fromCompact().
~Layering()
Layering::~Layering () virtual
Default destructor.
Definition at line 83 of file Layering.cpp.
Member Function Documentation
absorberThicknessInLayer()
double Layering::absorberThicknessInLayer (XML::Element e) const
Definition at line 125 of file Layering.cpp.
References _U, e, DD4hep::XML::Component::isRadiator(), s, DD4hep::Layer::thickness(), and DD4hep::XML::Dimension::thickness().
layer()
const Layer * Layering::layer (size_t which) const
Definition at line 86 of file Layering.cpp.
References _stack().
Referenced by create_detector().
layers()
std::vector<Layer*>& DD4hep::Layering::layers () inline
Definition at line 148 of file Layering.h.
References DD4hep::LayerStack::layers().
Referenced by DD4hep::XML::LayeringCnv::fromCompact().
sensitivePositionsInLayer()
void Layering::sensitivePositionsInLayer (XML::Element e, std::vector< double > & sens_pos) const
Definition at line 136 of file Layering.cpp.
References _U, e, DD4hep::XML::Component::isSensitive(), s, and DD4hep::XML::Dimension::thickness().
singleLayerThickness()
double Layering::singleLayerThickness (XML::Element e) const
Definition at line 115 of file Layering.cpp.
References _U, e, s, DD4hep::Layer::thickness(), and DD4hep::XML::Dimension::thickness().
Referenced by create_detector().
totalThickness()
double DD4hep::Layering::totalThickness () const inline
Definition at line 153 of file Layering.h.
References e, and DD4hep::LayerStack::totalThickness().
Referenced by create_detector().
Member Data Documentation
_stack
LayerStack DD4hep::Layering::_stack
Definition at line 140 of file Layering.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/Layering.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/Layering.cpp