DD4hep: DD4hep::Simulation::Geant4UserActionInitialization Class Reference
DD4hep::Simulation::Geant4UserActionInitialization Class Reference
Concrete implementation of the Geant4 user initialization action sequence.
Public Member Functions
Geant4UserActionInitialization (Geant4Context *ctxt, Geant4UserInitializationSequence *seq)
Standard constructor.
virtual ~Geant4UserActionInitialization ()
Default destructor.
virtual void Build () const
Build the actions for the worker thread.
virtual void BuildForMaster () const
Build the action sequences for the master thread.
Public Member Functions inherited from DD4hep::Simulation::SequenceHdl< Geant4UserInitializationSequence >
SequenceHdl ()
Default constructor.
SequenceHdl (Geant4Context *ctxt, Geant4UserInitializationSequence *seq)
virtual ~SequenceHdl ()
void _aquire (Geant4UserInitializationSequence *s)
void updateContext (Geant4Context *ctxt)
void _release ()
Geant4Context * context () const
Geant4Kernel & kernel () const
void configureFiber (Geant4Context *ctxt)
void createClientContext (const G4Run *run)
void createClientContext (const G4Event *evt)
void destroyClientContext (const G4Run *)
void destroyClientContext (const G4Event *)
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::SequenceHdl< Geant4UserInitializationSequence >
typedef SequenceHdl< Geant4UserInitializationSequence > Base
Public Attributes inherited from DD4hep::Simulation::SequenceHdl< Geant4UserInitializationSequence >
Geant4UserInitializationSequence * m_sequence
Geant4Context * m_activeContext
Detailed Description
Concrete implementation of the Geant4 user initialization action sequence.
Author
M.Frank
Version
1.0
Definition at line 330 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
Geant4UserActionInitialization()
DD4hep::Simulation::Geant4UserActionInitialization::Geant4UserActionInitialization (Geant4Context * ctxt, Geant4UserInitializationSequence * seq) inline
Standard constructor.
Definition at line 336 of file Geant4Exec.cpp.
~Geant4UserActionInitialization()
virtual DD4hep::Simulation::Geant4UserActionInitialization::~Geant4UserActionInitialization () inline virtual
Default destructor.
Definition at line 340 of file Geant4Exec.cpp.
Member Function Documentation
Build()
void DD4hep::Simulation::Geant4UserActionInitialization::Build () const virtual
Build the actions for the worker thread.
Definition at line 412 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4ActionContainer::eventAction(), DD4hep::Simulation::Geant4UserRunAction::eventAction, DD4hep::Simulation::Geant4ActionContainer::generatorAction(), DD4hep::Simulation::Geant4Kernel::id(), DD4hep::Simulation::SequenceHdl< T >::kernel(), DD4hep::Simulation::SequenceHdl< T >::m_sequence, DD4hep::Simulation::Geant4ActionContainer::runAction(), DD4hep::Simulation::Geant4UserEventAction::runAction, DD4hep::Simulation::Geant4ActionContainer::stackingAction(), DD4hep::Simulation::Geant4ActionContainer::steppingAction(), DD4hep::Simulation::Geant4Kernel::thread_self(), DD4hep::Simulation::Geant4ActionContainer::trackingAction(), DD4hep::Simulation::Geant4Kernel::worker(), and DD4hep::Simulation::Geant4ActionContainer::workerContext().
BuildForMaster()
void DD4hep::Simulation::Geant4UserActionInitialization::BuildForMaster () const virtual
Build the action sequences for the master thread.
Definition at line 462 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< T >::m_sequence.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp