DD4hep: DD4hep: DD4hep::Simulation::Geant4SharedRunAction Class Reference
DD4hep::Simulation::Geant4SharedRunAction Class Reference
[DD4hep::Simulation components, classes and objects]
Implementation of the Geant4 shared run action.
#include <Geant4RunAction.h>
Public Member Functions
Geant4SharedRunAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4SharedRunAction ()
Default destructor.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
virtual void use (Geant4RunAction *action)
Underlying object to be used during the execution of this thread.
virtual void begin (const G4Run *run)
Begin-of-run callback.
virtual void end (const G4Run *run)
End-of-run callback.
Protected Attributes
Geant4RunAction * m_action
Reference to the shared action.
Detailed Description
Implementation of the Geant4 shared run action.
Wrapper to share single instances of run actions for multi-threaded purposes. The wrapper ensures the locking of the basic actions to avoid race conditions.
Shared action should be 'fast'. The global lock otherwise inhibits the efficient use of the multiple threads.
Author:
M.Frank
Version:
1.0
Definition at line 73 of file Geant4RunAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4SharedRunAction::Geant4SharedRunAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4SharedRunAction::~Geant4SharedRunAction () [virtual]
Default destructor.
Definition at line 59 of file Geant4RunAction.cpp.
References DD4hep::InstanceCount::decrement(), m_action, and DD4hep::releasePtr().
Member Function Documentation
void Geant4SharedRunAction::begin (const G4Run * run) [virtual]
Begin-of-run callback.
Reimplemented from DD4hep::Simulation::Geant4RunAction.
Definition at line 81 of file Geant4RunAction.cpp.
References DD4hep::Simulation::Geant4RunAction::begin(), DD4hep::Simulation::Geant4Action::context(), and m_action.
void Geant4SharedRunAction::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 65 of file Geant4RunAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_action.
void Geant4SharedRunAction::end (const G4Run * run) [virtual]
End-of-run callback.
Reimplemented from DD4hep::Simulation::Geant4RunAction.
Definition at line 91 of file Geant4RunAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4RunAction::end(), and m_action.
void Geant4SharedRunAction::use (Geant4RunAction * action) [virtual]
Underlying object to be used during the execution of this thread.
Definition at line 70 of file Geant4RunAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::PropertyManager::adopt(), m_action, DD4hep::Simulation::Geant4Action::m_properties, and DD4hep::Simulation::Geant4Action::properties().
Member Data Documentation
Geant4RunAction* DD4hep::Simulation::Geant4SharedRunAction::m_action [protected]
Reference to the shared action.
Definition at line 76 of file Geant4RunAction.h.
Referenced by begin(), configureFiber(), end(), use(), and ~Geant4SharedRunAction().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4RunAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4RunAction.cpp