DD4hep: DD4hep::Alignments::AlignContext Class Reference
DD4hep::Alignments::AlignContext Class Reference
Classes
struct Entry
struct PathOrdering
Public Types
typedef std::map< DetElement, size_t, PathOrdering > DetectorMap
typedef std::map< unsigned int, size_t > Keys
typedef std::vector< Entry > Entries
Public Member Functions
AlignContext ()
~AlignContext ()
void newEntry (DetElement det, const Dependency *dep, AlignmentCondition::Object *con)
Public Attributes
DetectorMap detectors
Keys keys
Entries entries
unsigned long long int magic
Detailed Description
Definition at line 35 of file AlignmentsManager.cpp.
Member Typedef Documentation
DetectorMap
typedef std::map<DetElement,size_t,PathOrdering> DD4hep::Alignments::AlignContext::DetectorMap
Definition at line 47 of file AlignmentsManager.cpp.
Entries
typedef std::vector<Entry> DD4hep::Alignments::AlignContext::Entries
Definition at line 49 of file AlignmentsManager.cpp.
Keys
typedef std::map<unsigned int,size_t> DD4hep::Alignments::AlignContext::Keys
Definition at line 48 of file AlignmentsManager.cpp.
Constructor & Destructor Documentation
AlignContext()
DD4hep::Alignments::AlignContext::AlignContext () inline
Definition at line 55 of file AlignmentsManager.cpp.
References DD4hep::InstanceCount::increment().
~AlignContext()
DD4hep::Alignments::AlignContext::~AlignContext () inline
Definition at line 58 of file AlignmentsManager.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
newEntry()
void DD4hep::Alignments::AlignContext::newEntry (DetElement det, const Dependency * dep, AlignmentCondition::Object * con) inline
Definition at line 61 of file AlignmentsManager.cpp.
References DD4hep::Alignments::AlignContext::Entry::cond, DD4hep::Alignments::AlignContext::Entry::dep, DD4hep::Alignments::AlignContext::Entry::det, DD4hep::Handle< T >::isValid(), DD4hep::Alignments::AlignContext::Entry::key, DD4hep::Geometry::DetElement::key(), DD4hep::Handle< T >::ptr(), and DD4hep::Alignments::AlignContext::Entry::top.
Referenced by DD4hep::Alignments::AlignmentsManager::adoptDependency(), and DD4hep::Alignments::AlignmentsManager::newEntry().
Member Data Documentation
detectors
DetectorMap DD4hep::Alignments::AlignContext::detectors
Definition at line 51 of file AlignmentsManager.cpp.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute().
entries
Entries DD4hep::Alignments::AlignContext::entries
Definition at line 53 of file AlignmentsManager.cpp.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
keys
Keys DD4hep::Alignments::AlignContext::keys
Definition at line 52 of file AlignmentsManager.cpp.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
magic
unsigned long long int DD4hep::Alignments::AlignContext::magic
Definition at line 54 of file AlignmentsManager.cpp.
Referenced by DD4hep::Alignments::AlignmentsManager::newEntry().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentsManager.cpp