DD4hep: DD4hep: DD4hep::Simulation::Geant4UserTrackingAction Class Reference
DD4hep::Simulation::Geant4UserTrackingAction Class Reference
Concrete implementation of the Geant4 tracking action.
Public Member Functions
Geant4UserTrackingAction (Geant4Context *ctxt, Geant4TrackingActionSequence *seq)
Standard constructor.
virtual ~Geant4UserTrackingAction ()
Default destructor.
virtual void PreUserTrackingAction (const G4Track *trk)
Pre-track action callback.
virtual void PostUserTrackingAction (const G4Track *trk)
Post-track action callback.
Detailed Description
Concrete implementation of the Geant4 tracking action.
Author:
M.Frank
Version:
1.0
Definition at line 189 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4UserTrackingAction::Geant4UserTrackingAction (Geant4Context * ctxt, Geant4TrackingActionSequence * seq) [inline]
Standard constructor.
Definition at line 195 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< Geant4TrackingActionSequence >::configureFiber(), and DD4hep::Simulation::SequenceHdl< Geant4TrackingActionSequence >::updateContext().
virtual DD4hep::Simulation::Geant4UserTrackingAction::~Geant4UserTrackingAction () [inline, virtual]
Default destructor.
Definition at line 201 of file Geant4Exec.cpp.
Member Function Documentation
virtual void DD4hep::Simulation::Geant4UserTrackingAction::PostUserTrackingAction (const G4Track * trk) [inline, virtual]
Post-track action callback.
Definition at line 209 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4TrackingActionSequence::end(), DD4hep::Simulation::Geant4Context::kernel(), DD4hep::Simulation::SequenceHdl< Geant4TrackingActionSequence >::m_sequence, and DD4hep::Simulation::Geant4Kernel::setTrackMgr().
virtual void DD4hep::Simulation::Geant4UserTrackingAction::PreUserTrackingAction (const G4Track * trk) [inline, virtual]
Pre-track action callback.
Definition at line 204 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4TrackingActionSequence::begin(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::kernel(), DD4hep::Simulation::SequenceHdl< Geant4TrackingActionSequence >::m_sequence, and DD4hep::Simulation::Geant4Kernel::setTrackMgr().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp