DD4hep: DD4hep: DD4hep::Simulation::Geant4PrimaryMap Class Reference
DD4hep::Simulation::Geant4PrimaryMap Class Reference
[DD4hep::Simulation components, classes and objects]
Data structure to map primaries to particles.
#include <Geant4Primary.h>
Public Types
typedef std::map< const
G4PrimaryParticle
*, Geant4Particle * > Primaries
Public Member Functions
Geant4PrimaryMap ()
not persistent
virtual ~Geant4PrimaryMap ()
Default destructor.
void insert (G4PrimaryParticle *g4_particle, Geant4Particle *particle)
Add a new object pair (G4 primary particle, DDG4 particle) into the maps.
Geant4Particle * get (const G4PrimaryParticle *particle)
Access DDG4 particle by G4 primary particle.
const Geant4Particle * get (const G4PrimaryParticle *particle) const
Access DDG4 particle by G4 primary particle (const).
Primaries & primaries ()
Access primary map directly.
const Primaries & primaries () const
Access primary map directly (const).
Private Attributes
Primaries m_primaryMap
Mapping of primary particles of this event.
Detailed Description
Data structure to map primaries to particles.
This data structure is added to the Geant4Event data extensions by the Geant4GenerationInit action.
Author:
M.Frank
Version:
1.0
Definition at line 65 of file Geant4Primary.h.
Member Typedef Documentation
typedef std::map<const G4PrimaryParticle*,Geant4Particle*> DD4hep::Simulation::Geant4PrimaryMap::Primaries
Definition at line 67 of file Geant4Primary.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4PrimaryMap::Geant4PrimaryMap () [inline]
not persistent
Default constructor
Definition at line 74 of file Geant4Primary.h.
Geant4PrimaryMap::~Geant4PrimaryMap () [virtual]
Default destructor.
Definition at line 35 of file Geant4Primary.cpp.
References m_primaryMap, and DD4hep::releaseObjects().
Member Function Documentation
const Geant4Particle * Geant4PrimaryMap::get (const G4PrimaryParticle * particle) const
Access DDG4 particle by G4 primary particle (const).
Definition at line 51 of file Geant4Primary.cpp.
References m_primaryMap.
Geant4Particle * Geant4PrimaryMap::get (const G4PrimaryParticle * particle)
Access DDG4 particle by G4 primary particle.
Definition at line 45 of file Geant4Primary.cpp.
References m_primaryMap.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin().
void Geant4PrimaryMap::insert (G4PrimaryParticle * g4_particle, Geant4Particle * particle)
Add a new object pair (G4 primary particle, DDG4 particle) into the maps.
Definition at line 40 of file Geant4Primary.cpp.
References DD4hep::Simulation::Geant4Particle::addRef(), and m_primaryMap.
Referenced by collectPrimaries(), and DD4hep::Simulation::generatePrimaries().
const Primaries& DD4hep::Simulation::Geant4PrimaryMap::primaries () const [inline]
Access primary map directly (const).
Definition at line 86 of file Geant4Primary.h.
References m_primaryMap.
Primaries& DD4hep::Simulation::Geant4PrimaryMap::primaries () [inline]
Access primary map directly.
Definition at line 84 of file Geant4Primary.h.
References m_primaryMap.
Member Data Documentation
Primaries DD4hep::Simulation::Geant4PrimaryMap::m_primaryMap [private]
Mapping of primary particles of this event.
Definition at line 70 of file Geant4Primary.h.
Referenced by get(), insert(), primaries(), and ~Geant4PrimaryMap().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Primary.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Primary.cpp