DD4hep: DD4hep: DD4hep::Simulation::Geant4ParticleGenerator Class Reference
DD4hep::Simulation::Geant4ParticleGenerator Class Reference
[DD4hep::Simulation components, classes and objects]
Generate particles isotrop in space around origine (0,0,0).
#include <Geant4ParticleGenerator.h>
Public Member Functions
Geant4ParticleGenerator (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4ParticleGenerator ()
Default destructor.
virtual void operator() (G4Event *event)
Callback to generate primary particles.
Protected Member Functions
virtual void getParticleMultiplicity (int &multiplicity) const
Particle modification. Caller presets defaults to: (multiplicity=m_multiplicity).
virtual void getVertexPosition (ROOT::Math::XYZVector &position) const
Particle's vertex modification. Caller presets defaults to: (multiplicity=m_multiplicity).
virtual void getParticleDirection (int num, ROOT::Math::XYZVector &direction, double &momentum) const
Particle modification. Caller presets defaults to: (direction = m_direction, momentum = m_energy).
virtual void printInteraction (int mask) const
Print single particle interaction identified by its mask.
virtual void printInteraction (Geant4PrimaryInteraction *inter) const
Print single particle interaction identified by it's reference.
Protected Attributes
ROOT::Math::XYZVector m_direction
Property: Shooting direction of the gun.
ROOT::Math::XYZVector m_position
Property: Position of the gun in space.
std::string m_particleName
Property: Particle name.
G4ParticleDefinition * m_particle
Pointer to geant4 particle definition.
double m_energy
Property: Particle energy.
int m_multiplicity
Property: Desired multiplicity of the particles to be shot.
int m_mask
Property: User mask passed to all particles in the generated interaction.
Detailed Description
Generate particles isotrop in space around origine (0,0,0).
Author:
M.Frank
Version:
1.0
Definition at line 39 of file Geant4ParticleGenerator.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4ParticleGenerator::Geant4ParticleGenerator (Geant4Context * context, const std::string & name)
Standard constructor.
Geant4ParticleGenerator::~Geant4ParticleGenerator () [virtual]
Default destructor.
Definition at line 46 of file Geant4ParticleGenerator.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4ParticleGenerator::getParticleDirection (int num, ROOT::Math::XYZVector & direction, double & momentum) const [protected, virtual]
Particle modification. Caller presets defaults to: (direction = m_direction, momentum = m_energy).
Use this function to implement isotrop guns, multiple guns etc. User must return a UNIT vector, which gets scaled with momentum.
Reimplemented in DD4hep::Simulation::Geant4IsotropeGenerator, and DD4hep::Simulation::Geant4ParticleGun.
Definition at line 51 of file Geant4ParticleGenerator.cpp.
Referenced by operator()().
void Geant4ParticleGenerator::getParticleMultiplicity (int & multiplicity) const [protected, virtual]
Particle modification. Caller presets defaults to: (multiplicity=m_multiplicity).
Definition at line 55 of file Geant4ParticleGenerator.cpp.
Referenced by operator()().
void Geant4ParticleGenerator::getVertexPosition (ROOT::Math::XYZVector & position) const [protected, virtual]
Particle's vertex modification. Caller presets defaults to: (multiplicity=m_multiplicity).
Particle modification. Caller presets defaults to: (multiplicity=m_multiplicity).
Definition at line 59 of file Geant4ParticleGenerator.cpp.
Referenced by operator()().
void Geant4ParticleGenerator::operator() (G4Event * event) [virtual]
Callback to generate primary particles.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Reimplemented in DD4hep::Simulation::Geant4ParticleGun.
Definition at line 99 of file Geant4ParticleGenerator.cpp.
References DD4hep::Simulation::Geant4PrimaryEvent::add(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::G4PARTICLE_GEN_STABLE, getParticleDirection(), getParticleMultiplicity(), getVertexPosition(), dd4hep::GeV, DD4hep::INFO, m_direction, m_energy, m_mask, m_multiplicity, m_particle, m_particleName, m_position, DD4hep::Simulation::Geant4Vertex::mask, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4Vertex::out, DD4hep::printout(), DD4hep::Simulation::Geant4Vertex::x, DD4hep::Simulation::Geant4Vertex::y, and DD4hep::Simulation::Geant4Vertex::z.
void Geant4ParticleGenerator::printInteraction (Geant4PrimaryInteraction * inter) const [protected, virtual]
Print single particle interaction identified by it's reference.
Definition at line 78 of file Geant4ParticleGenerator.cpp.
References DD4hep::Simulation::Geant4ParticleHandle::dumpWithVertex(), dd4hep::GeV, m_energy, m_particleName, dd4hep::mm, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4Vertex::out, DD4hep::Simulation::Geant4Action::outputLevel(), DD4hep::Simulation::Geant4PrimaryInteraction::particles, DD4hep::Simulation::Geant4Action::print(), v, DD4hep::Simulation::Geant4PrimaryInteraction::vertices, DD4hep::Simulation::Geant4Action::warning(), DD4hep::Simulation::Geant4Vertex::x, DD4hep::Simulation::Geant4Vertex::y, and DD4hep::Simulation::Geant4Vertex::z.
void Geant4ParticleGenerator::printInteraction (int mask) const [protected, virtual]
Print single particle interaction identified by its mask.
Print single particle interaction identified by it's mask.
Definition at line 63 of file Geant4ParticleGenerator.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4PrimaryEvent::get(), and DD4hep::Simulation::Geant4Action::warning().
Referenced by DD4hep::Simulation::Geant4ParticleGun::operator()().
Member Data Documentation
ROOT::Math::XYZVector DD4hep::Simulation::Geant4ParticleGenerator::m_direction [protected]
Property: Shooting direction of the gun.
Definition at line 43 of file Geant4ParticleGenerator.h.
Referenced by DD4hep::Simulation::Geant4ParticleGun::getParticleDirection(), DD4hep::Simulation::Geant4ParticleGun::operator()(), and operator()().
double DD4hep::Simulation::Geant4ParticleGenerator::m_energy [protected]
Property: Particle energy.
Definition at line 51 of file Geant4ParticleGenerator.h.
Referenced by DD4hep::Simulation::Geant4ParticleGun::getParticleDirection(), DD4hep::Simulation::Geant4ParticleGun::operator()(), operator()(), and printInteraction().
int DD4hep::Simulation::Geant4ParticleGenerator::m_mask [protected]
Property: User mask passed to all particles in the generated interaction.
Definition at line 55 of file Geant4ParticleGenerator.h.
Referenced by DD4hep::Simulation::Geant4ParticleGun::operator()(), and operator()().
int DD4hep::Simulation::Geant4ParticleGenerator::m_multiplicity [protected]
Property: Desired multiplicity of the particles to be shot.
Definition at line 53 of file Geant4ParticleGenerator.h.
Referenced by operator()().
G4ParticleDefinition* DD4hep::Simulation::Geant4ParticleGenerator::m_particle [protected]
Pointer to geant4 particle definition.
Definition at line 49 of file Geant4ParticleGenerator.h.
Referenced by operator()().
std::string DD4hep::Simulation::Geant4ParticleGenerator::m_particleName [protected]
Property: Particle name.
Definition at line 47 of file Geant4ParticleGenerator.h.
Referenced by DD4hep::Simulation::Geant4ParticleGun::operator()(), operator()(), and printInteraction().
ROOT::Math::XYZVector DD4hep::Simulation::Geant4ParticleGenerator::m_position [protected]
Property: Position of the gun in space.
Definition at line 45 of file Geant4ParticleGenerator.h.
Referenced by DD4hep::Simulation::Geant4ParticleGun::operator()(), and operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ParticleGenerator.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ParticleGenerator.cpp