DD4hep: DD4hep::Alignments::Interna::AlignmentConditionObject Class Reference
DD4hep::Alignments::Interna::AlignmentConditionObject Class Reference
The data class behind a alignments handle.
#include <AlignmentsInterna.h>
Public Member Functions
AlignmentConditionObject (const std::string &nam, const std::string &tit="")
Standard constructor.
virtual ~AlignmentConditionObject ()
Standard Destructor.
void clear ()
Clear data.
Public Member Functions inherited from DD4hep::Conditions::Interna::ConditionObject
ConditionObject (const std::string &nam="", const std::string &tit="")
Standard constructor.
virtual ~ConditionObject ()
Standard Destructor.
ConditionObject & move (ConditionObject &from)
Move data content: 'from' will be reset to NULL.
const iov_type * iovData () const
Access safely the IOV.
const IOVType * iovType () const
Access safely the IOV-type.
bool is_bound () const
Check if object is already bound....
bool is_traced () const
void setFlag (int option)
void unFlag (int option)
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
AlignmentData * alignment_data
Cached pointer to the bound conditions data, since these may be accessed very frequently.
Public Attributes inherited from DD4hep::Conditions::Interna::ConditionObject
std::string value
Condition value (in string form)
std::string validity
Condition validity (in string form)
std::string address
Condition address.
std::string comment
Comment string.
OpaqueDataBlock data
Data block.
ConditionsPool * pool
Reference to conditions pool.
const iov_type * iov
Interval of validity.
key_type hash
Hash value of the name.
mask_type flags
Flags.
int refCount
Reference count.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Additional Inherited Members
Public Types inherited from DD4hep::Conditions::Interna::ConditionObject
typedef Condition::key_type key_type
Forward definition of the key type.
typedef Condition::iov_type iov_type
Forward definition of the iov type.
typedef unsigned int mask_type
Forward definition of the object properties.
typedef ReferenceBitMask< mask_type > MaskManip
Forward definition of the object mask manipulator.
Detailed Description
The data class behind a alignments handle.
See AlignmentsInterna.cpp for the implementation.
Author
M.Frank
Version
1.0
Definition at line 91 of file AlignmentsInterna.h.
Constructor & Destructor Documentation
AlignmentConditionObject()
AlignmentConditionObject::AlignmentConditionObject (const std::string & nam, const std::string & tit = "")
Standard constructor.
Definition at line 35 of file AlignmentsInterna.cpp.
References DD4hep::Conditions::Condition::ALIGNMENT, DD4hep::Conditions::Interna::ConditionObject::flags, and DD4hep::InstanceCount::increment().
~AlignmentConditionObject()
AlignmentConditionObject::~AlignmentConditionObject () virtual
Standard Destructor.
Definition at line 43 of file AlignmentsInterna.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
clear()
void AlignmentConditionObject::clear ()
Clear data.
Clear data content on demand.
Definition at line 48 of file AlignmentsInterna.cpp.
References DD4hep::Conditions::Condition::ALIGNMENT, DD4hep::Alignments::AlignmentCondition::data(), DD4hep::Alignments::AlignmentData::detectorTrafo, DD4hep::Conditions::Interna::ConditionObject::flags, DD4hep::Alignments::AlignmentData::nodes, DD4hep::Alignments::AlignmentData::trToWorld, and DD4hep::Alignments::AlignmentData::worldTrafo.
Member Data Documentation
alignment_data
AlignmentData* DD4hep::Alignments::Interna::AlignmentConditionObject::alignment_data
Cached pointer to the bound conditions data, since these may be accessed very frequently.
Definition at line 95 of file AlignmentsInterna.h.
Referenced by DD4hep::Alignments::AlignmentCondition::data().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/AlignmentsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/AlignmentsInterna.cpp