DD4hep: DD4hep::DDSegmentation::BitField64 Class Reference
DD4hep::DDSegmentation::BitField64 Class Reference
#include <BitField64.h>
Public Types
typedef std::map< std::string, unsigned int > IndexMap
Public Member Functions
virtual ~BitField64 ()
BitField64 (const std::string &initString)
long64 getValue () const
void setValue (long64 value)
void setValue (unsigned low_Word, unsigned high_Word)
BitField64 & operator() (long64 val)
void reset ()
BitFieldValue & operator[] (size_t idx)
const BitFieldValue & operator[] (size_t idx) const
unsigned highestBit () const
size_t size () const
size_t index (const std::string &name) const
BitFieldValue & operator[] (const std::string &name)
const BitFieldValue & operator[] (const std::string &name) const
unsigned lowWord () const
unsigned highWord () const
std::string fieldDescription () const
std::string valueString () const
Protected Member Functions
void addField (const std::string &name, unsigned offset, int width)
void init (const std::string &initString)
BitField64 ()
Protected Attributes
std::vector< BitFieldValue * > _fields
long64 _value
IndexMap _map
long64 _joined
Friends
std::ostream & operator<< (std::ostream &os, const BitField64 &b)
Detailed Description
A bit field of 64bits that allows convenient declaration and manipulation of sub fields of various widths.
Example:
BitField64 b("layer:7,system:-3,barrel:3,theta:32:11,phi:11") ;
b[ "layer" ] = 123 ;
b[ "system" ] = -4 ;
b[ "barrel" ] = 7 ;
b[ "theta" ] = 180 ;
b[ "phi" ] = 270 ;
...
int theta = b["theta"] ;
...
unsigned phiIndex = b.index("phi") ;
int phi = b[ phiIndex ] ;
Author
F.Gaede, DESY
Version
$Id:$
Date
2013-06
Definition at line 43 of file BitField64.h.
Member Typedef Documentation
IndexMap
typedef std::map<std::string, unsigned int> DD4hep::DDSegmentation::BitField64::IndexMap
Definition at line 49 of file BitField64.h.
Constructor & Destructor Documentation
~BitField64()
DD4hep::DDSegmentation::BitField64::~BitField64 () inline virtual
Definition at line 292 of file BitField64.h.
References _fields.
BitField64() [1/2]
DD4hep::DDSegmentation::BitField64::BitField64 (const std::string & initString) inline
The c'tor takes an initialization string of the form:
<fieldDesc>[,<fieldDesc>...]
fieldDesc = name:[start]:[-]length
where:
name: The name of the field
start: The start bit of the field. If omitted assumed to start immediately following previous field, or at the least significant bit if the first field.
length: The number of bits in the field. If preceeded by '-' the field is signed, otherwise unsigned.
Bit numbering is from the least significant bit (bit 0) to the most significant (bit 63).
Example: "layer:7,system:-3,barrel:3,theta:32:11,phi:11"
Definition at line 68 of file BitField64.h.
References init().
BitField64() [2/2]
DD4hep::DDSegmentation::BitField64::BitField64 () inline protected
No default c'tor
Definition at line 160 of file BitField64.h.
Member Function Documentation
addField()
void DD4hep::DDSegmentation::BitField64::addField (const std::string & name, unsigned offset, int width) protected
Add an additional field to the list
Definition at line 191 of file BitField64.cpp.
References DD4hep::DDSegmentation::BitFieldValue::BitFieldValue(), DD4hep::DDSegmentation::BitFieldValue::mask(), DD4hep::DDSegmentation::BitFieldValue::name(), and s.
Referenced by highWord().
fieldDescription()
std::string DD4hep::DDSegmentation::BitField64::fieldDescription () const
Return a valid description string of all fields
Definition at line 155 of file BitField64.cpp.
References DD4hep::DDSegmentation::BitFieldValue::isSigned().
Referenced by DD4hep::Geometry::IDDescriptor::fieldDescription(), and highWord().
getValue()
long64 DD4hep::DDSegmentation::BitField64::getValue () const inline
Returns the current 64bit value
Definition at line 75 of file BitField64.h.
References _value.
Referenced by DD4hep::DDSegmentation::CartesianGridXY::cellID(), DD4hep::DDSegmentation::CartesianGridXYZ::cellID(), DD4hep::DDSegmentation::ProjectiveCylinder::cellID(), DD4hep::DDSegmentation::CartesianGridXZ::cellID(), DD4hep::DDSegmentation::PolarGridRPhi::cellID(), DD4hep::DDSegmentation::CartesianGridYZ::cellID(), DD4hep::DDSegmentation::MegatileLayerGridXY::cellID(), DD4hep::DDSegmentation::WaferGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerGridXY::cellID(), DD4hep::DDSegmentation::PolarGridRPhi2::cellID(), DD4hep::DDSegmentation::Segmentation::neighbours(), and DD4hep::DDSegmentation::Segmentation::volumeID().
highestBit()
unsigned DD4hep::DDSegmentation::BitField64::highestBit () const
Highest bit used in fields [0-63]
Definition at line 128 of file BitField64.cpp.
References DD4hep::DDSegmentation::BitFieldValue::offset(), and DD4hep::DDSegmentation::BitFieldValue::width().
Referenced by operator[]().
highWord()
unsigned DD4hep::DDSegmentation::BitField64::highWord () const inline
The high word, bits 32-63
Definition at line 137 of file BitField64.h.
References _value, addField(), fieldDescription(), init(), and valueString().
index()
size_t DD4hep::DDSegmentation::BitField64::index (const std::string & name) const
Index for field named 'name'
Definition at line 116 of file BitField64.cpp.
Referenced by operator[](), and size().
init()
void DD4hep::DDSegmentation::BitField64::init (const std::string & initString) protected
Decode the initialization string as described in the constructor.
See also
BitField64(const std::string& initString)
Definition at line 214 of file BitField64.cpp.
References DD4hep::DDSegmentation::BitFieldValue::name(), DD4hep::DDSegmentation::BitFieldValue::offset(), s, and DD4hep::DDSegmentation::BitFieldValue::width().
Referenced by BitField64(), and highWord().
lowWord()
unsigned DD4hep::DDSegmentation::BitField64::lowWord () const inline
The low word, bits 0-31
Definition at line 133 of file BitField64.h.
References _value.
operator()()
BitField64& DD4hep::DDSegmentation::BitField64::operator() (long64 val) inline
Operator for setting a new value and accessing the BitField directly
Definition at line 88 of file BitField64.h.
References setValue().
operator[]() [1/4]
BitFieldValue& DD4hep::DDSegmentation::BitField64::operator[] (size_t idx) inline
Acces to field through index
Definition at line 96 of file BitField64.h.
References _fields.
operator[]() [2/4]
const BitFieldValue& DD4hep::DDSegmentation::BitField64::operator[] (size_t idx) const inline
Const acces to field through index
Definition at line 102 of file BitField64.h.
References _fields, and highestBit().
operator[]() [3/4]
BitFieldValue& DD4hep::DDSegmentation::BitField64::operator[] (const std::string & name) inline
Access to field through name .
Definition at line 119 of file BitField64.h.
References _fields, and index().
operator[]() [4/4]
const BitFieldValue& DD4hep::DDSegmentation::BitField64::operator[] (const std::string & name) const inline
Const Access to field through name .
Definition at line 125 of file BitField64.h.
References _fields, and index().
reset()
void DD4hep::DDSegmentation::BitField64::reset () inline
Reset - same as setValue(0) - useful if the same encoder is used for many objects.
Definition at line 92 of file BitField64.h.
References _value.
setValue() [1/2]
void DD4hep::DDSegmentation::BitField64::setValue (long64 value) inline
Set a new 64bit value - bits not used in description are set to 0.
Definition at line 79 of file BitField64.h.
References _joined, and _value.
Referenced by DD4hep::DDSegmentation::PolarGridRPhi::cellDimensions(), DD4hep::DDSegmentation::PolarGridRPhi2::cellDimensions(), DD4hep::DDSegmentation::MegatileLayerGridXY::cellDimensions(), DD4hep::DDSegmentation::CartesianGridXZ::cellID(), DD4hep::DDSegmentation::ProjectiveCylinder::cellID(), DD4hep::DDSegmentation::CartesianGridXY::cellID(), DD4hep::DDSegmentation::CartesianGridXYZ::cellID(), DD4hep::DDSegmentation::PolarGridRPhi::cellID(), DD4hep::DDSegmentation::CartesianGridYZ::cellID(), DD4hep::DDSegmentation::WaferGridXY::cellID(), DD4hep::DDSegmentation::MegatileLayerGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerSegmentation::cellID(), DD4hep::DDSegmentation::PolarGridRPhi2::cellID(), DD4hep::DDSegmentation::Segmentation::neighbours(), operator()(), DD4hep::DDSegmentation::ProjectiveCylinder::phi(), DD4hep::DDSegmentation::ProjectiveCylinder::position(), DD4hep::DDSegmentation::CartesianGridXYZ::position(), DD4hep::DDSegmentation::CartesianGridXZ::position(), DD4hep::DDSegmentation::CartesianGridXY::position(), DD4hep::DDSegmentation::PolarGridRPhi::position(), DD4hep::DDSegmentation::CartesianGridYZ::position(), DD4hep::DDSegmentation::WaferGridXY::position(), DD4hep::DDSegmentation::MegatileLayerGridXY::position(), DD4hep::DDSegmentation::TiledLayerGridXY::position(), DD4hep::DDSegmentation::TiledLayerSegmentation::position(), DD4hep::DDSegmentation::PolarGridRPhi2::position(), setValue(), DD4hep::DDSegmentation::ProjectiveCylinder::theta(), and DD4hep::DDSegmentation::Segmentation::volumeID().
setValue() [2/2]
void DD4hep::DDSegmentation::BitField64::setValue (unsigned low_Word, unsigned high_Word) inline
Set a new 64bit value given as high and low 32bit words.
Definition at line 83 of file BitField64.h.
References setValue().
size()
size_t DD4hep::DDSegmentation::BitField64::size () const inline
Number of values
Definition at line 111 of file BitField64.h.
References _fields, and index().
valueString()
std::string DD4hep::DDSegmentation::BitField64::valueString () const
Return a string with a comma separated list of the current sub field values
Definition at line 141 of file BitField64.cpp.
Referenced by highWord().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const BitField64 & b) friend
Operator for dumping BitField64 to streams
Definition at line 271 of file BitField64.cpp.
Member Data Documentation
_fields
std::vector<BitFieldValue*> DD4hep::DDSegmentation::BitField64::_fields protected
Definition at line 165 of file BitField64.h.
Referenced by operator[](), size(), and ~BitField64().
_joined
long64 DD4hep::DDSegmentation::BitField64::_joined protected
Definition at line 168 of file BitField64.h.
Referenced by setValue().
_map
IndexMap DD4hep::DDSegmentation::BitField64::_map protected
Definition at line 167 of file BitField64.h.
Referenced by DD4hep::DDSegmentation::operator<<().
_value
long64 DD4hep::DDSegmentation::BitField64::_value protected
Definition at line 166 of file BitField64.h.
Referenced by getValue(), highWord(), lowWord(), DD4hep::DDSegmentation::operator<<(), reset(), and setValue().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/BitField64.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/BitField64.cpp