DD4hep: DD4hep: DD4hep::Simulation::Geant4SteppingActionSequence Class Reference
DD4hep::Simulation::Geant4SteppingActionSequence Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete implementation of the Geant4 stepping action sequence.
#include <Geant4SteppingAction.h>
Public Member Functions
Geant4SteppingActionSequence (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4SteppingActionSequence ()
Default destructor.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
Geant4SteppingAction * get (const std::string &name) const
Get an action by name.
template<typename Q , typename T >
void call (Q *p, void(T::*f)(const G4Step *, G4SteppingManager *))
Register stepping action callback. Types Q and T must be polymorph!
void adopt (Geant4SteppingAction *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void operator() (const G4Step *step, G4SteppingManager *mgr)
User stepping callback.
Protected Attributes
CallbackSequence m_calls
Callback sequence for user stepping action calls.
Actors< Geant4SteppingAction > m_actors
The list of action objects to be called.
Detailed Description
Concrete implementation of the Geant4 stepping action sequence.
The sequence dispatches the callbacks for each stepping action to all registered Geant4SteppingAction members and all registered callbacks.
Note Multi-Threading issue: Neither callbacks not the action list is protected against multiple threads calling the Geant4 callbacks! These must be protected in the user actions themselves.
Author:
M.Frank
Version:
1.0
Definition at line 98 of file Geant4SteppingAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4SteppingActionSequence::Geant4SteppingActionSequence (Geant4Context * context, const std::string & name)
Standard constructor.
Geant4SteppingActionSequence::~Geant4SteppingActionSequence () [virtual]
Default destructor.
Definition at line 92 of file Geant4SteppingAction.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_calls, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
void Geant4SteppingActionSequence::adopt (Geant4SteppingAction * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 122 of file Geant4SteppingAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by DD4hep::Converter< T, ARG >::operator()().
template<typename Q , typename T > void DD4hep::Simulation::Geant4SteppingActionSequence::call (Q * p, void(T::*)(const G4Step *, G4SteppingManager *) f) [inline]
Register stepping action callback. Types Q and T must be polymorph!
Definition at line 118 of file Geant4SteppingAction.h.
References DD4hep::CallbackSequence::add(), and m_calls.
Referenced by DD4hep::Converter< T, ARG >::operator()().
void Geant4SteppingActionSequence::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 100 of file Geant4SteppingAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_actors.
Geant4SteppingAction* DD4hep::Simulation::Geant4SteppingActionSequence::get (const std::string & name) const
Get an action by name.
void Geant4SteppingActionSequence::operator() (const G4Step * step, G4SteppingManager * mgr) [virtual]
User stepping callback.
Pre-track action callback.
Definition at line 116 of file Geant4SteppingAction.cpp.
References m_actors, and m_calls.
void Geant4SteppingActionSequence::updateContext (Geant4Context * ctxt) [virtual]
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 105 of file Geant4SteppingAction.cpp.
References m_actors, and DD4hep::Simulation::Geant4Action::m_context.
Member Data Documentation
Actors<Geant4SteppingAction> DD4hep::Simulation::Geant4SteppingActionSequence::m_actors [protected]
The list of action objects to be called.
Definition at line 103 of file Geant4SteppingAction.h.
Referenced by adopt(), configureFiber(), operator()(), updateContext(), and ~Geant4SteppingActionSequence().
CallbackSequence DD4hep::Simulation::Geant4SteppingActionSequence::m_calls [protected]
Callback sequence for user stepping action calls.
Definition at line 101 of file Geant4SteppingAction.h.
Referenced by call(), operator()(), and ~Geant4SteppingActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SteppingAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SteppingAction.cpp