DD4hep: DD4hep::ComponentCast Class Reference
DD4hep::ComponentCast Class Reference
Class to perform dynamic casts using unknown pointers.
#include <DD4hep/Primitives.h>
Public Types
typedef void(* destroy_t) (void *)
typedef void *(* cast_t) (const void *)
Public Member Functions
void * apply_dynCast (const ComponentCast &to, const void *ptr) const
Apply cast using typeinfo instead of dynamic_cast.
void * apply_upCast (const ComponentCast &to, const void *ptr) const
Apply cast using typeinfo instead of dynamic_cast.
void * apply_downCast (const ComponentCast &to, const void *ptr) const
Apply cast using typeinfo instead of dynamic_cast.
Static Public Member Functions
template<typename TYPE >
static void _destroy (void *p)
template<typename TYPE >
static void * _cast (const void *p)
template<typename TYPE >
static ComponentCast & instance ()
Public Attributes
const std::type_info & type
const void * abi_class
destroy_t destroy
cast_t cast
Private Member Functions
ComponentCast (const std::type_info &t, destroy_t d, cast_t c)
Initializing Constructor.
virtual ~ComponentCast ()
Defautl destructor.
Detailed Description
Class to perform dynamic casts using unknown pointers.
It is mandatory that the pointers referred do actually support the asked functionalty. Miracles also I cannot do.....
Author
M.Frank
Date
13.08.2013
Definition at line 168 of file Primitives.h.
Member Typedef Documentation
cast_t
typedef void*(* DD4hep::ComponentCast::cast_t) (const void *)
Definition at line 171 of file Primitives.h.
destroy_t
typedef void(* DD4hep::ComponentCast::destroy_t) (void *)
Definition at line 170 of file Primitives.h.
Constructor & Destructor Documentation
ComponentCast()
DD4hep::ComponentCast::ComponentCast (const std::type_info & t, destroy_t d, cast_t c) private
Initializing Constructor.
Definition at line 277 of file Primitives.cpp.
References abi_class, type, and DD4hep::typeName().
~ComponentCast()
DD4hep::ComponentCast::~ComponentCast () private virtual
Defautl destructor.
Definition at line 290 of file Primitives.cpp.
Member Function Documentation
_cast()
template<typename TYPE > static void* DD4hep::ComponentCast::_cast (const void * p) inline static
Definition at line 192 of file Primitives.h.
_destroy()
template<typename TYPE > static void DD4hep::ComponentCast::_destroy (void * p) inline static
Definition at line 188 of file Primitives.h.
apply_downCast()
void * DD4hep::ComponentCast::apply_downCast (const ComponentCast & to, const void * ptr) const
Apply cast using typeinfo instead of dynamic_cast.
Definition at line 368 of file Primitives.cpp.
References abi_class, cast, cast_wrap(), and type.
Referenced by DD4hep::Simulation::Geant4HitCollection::getData(), and DD4hep::Simulation::Geant4HitCollection::releaseData().
apply_dynCast()
void * DD4hep::ComponentCast::apply_dynCast (const ComponentCast & to, const void * ptr) const
Apply cast using typeinfo instead of dynamic_cast.
Definition at line 319 of file Primitives.cpp.
References abi_class, cast, cast_wrap(), and type.
Referenced by apply_upCast(), and DD4hep::Simulation::Geant4HitWrapper::HitManipulator::castHit().
apply_upCast()
void * DD4hep::ComponentCast::apply_upCast (const ComponentCast & to, const void * ptr) const
Apply cast using typeinfo instead of dynamic_cast.
Definition at line 359 of file Primitives.cpp.
References apply_dynCast().
instance()
template<typename TYPE > static ComponentCast& DD4hep::ComponentCast::instance () inline static
Definition at line 197 of file Primitives.h.
Referenced by DD4hep::Simulation::Geant4HitWrapper::HitManipulator::instance().
Member Data Documentation
abi_class
const void* DD4hep::ComponentCast::abi_class
Definition at line 177 of file Primitives.h.
Referenced by apply_downCast(), apply_dynCast(), and ComponentCast().
cast
cast_t DD4hep::ComponentCast::cast
Definition at line 179 of file Primitives.h.
Referenced by apply_downCast(), apply_dynCast(), and DD4hep::Simulation::Geant4HitCollection::type().
destroy
destroy_t DD4hep::ComponentCast::destroy
Definition at line 178 of file Primitives.h.
type
const std::type_info& DD4hep::ComponentCast::type
Definition at line 175 of file Primitives.h.
Referenced by apply_downCast(), apply_dynCast(), ComponentCast(), and DD4hep::Simulation::Geant4Output2ROOT::fill().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Primitives.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Primitives.cpp