DD4hep: DD4hep::IOV Class Reference
DD4hep::IOV Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Class describing the interval of validty.
#include <IOV.h>
Public Types
typedef long Key_first_type
Key definition.
typedef long Key_second_type
typedef std::pair< Key_first_type, Key_second_type > Key
Public Member Functions
IOV (const IOVType *typ)
Initializing constructor.
IOV (const IOVType *typ, const Key &key)
Specialized copy constructor.
IOV (const IOV &copy)=default
Copy constructor.
~IOV ()=default
Standard Destructor.
IOV & operator= (const IOV &c)=default
Assignment operator.
void move (IOV &from)
Move the data content: 'from' will be reset to NULL.
std::string str () const
Create string representation of the IOV.
bool has_range () const
Check if the IOV corresponds to a range.
bool is_discrete () const
Check if the IOV corresponds to a range.
Key key () const
Get the local key of the IOV.
void set (const Key &value)
Set discrete IOV value.
void set (Key_first_type value)
Set discrete IOV value.
void set (Key_first_type val_1, Key_second_type val_2)
Set range IOV value.
IOV & reset ()
Set keys to unphysical values (LONG_MAX, LONG_MIN)
IOV & invert ()
Invert the key values (first=second and second=first)
void iov_intersection (const IOV &comparator)
Set the intersection of this IOV with the argument IOV.
void iov_intersection (const IOV::Key &comparator)
Set the intersection of this IOV with the argument IOV.
void iov_union (const IOV &comparator)
Set the union of this IOV with the argument IOV.
void iov_union (const IOV::Key &comparator)
Set the union of this IOV with the argument IOV.
bool contains (const IOV &iov) const
Check for validity containment.
Static Public Member Functions
static bool same_type (const IOV &iov, const IOV &test)
Check if 2 IOV objects are of the same type.
static bool key_is_contained (const Key &key, const Key &test)
Check if IOV 'test' is fully contained in IOV 'key'.
static bool key_contains_range (const Key &key, const Key &test)
Same as above, but reverse logic. Gives sometimes more understandable logic.
static bool key_overlaps_lower_end (const Key &key, const Key &test)
Check if IOV 'test' has an overlap on the lower interval edge with IOV 'key'.
static bool key_overlaps_higher_end (const Key &key, const Key &test)
Check if IOV 'test' has an overlap on the upper interval edge with IOV 'key'.
static bool key_partially_contained (const Key &key, const Key &test)
Check if IOV 'test' has an overlap on the upper interval edge with IOV 'key'.
static bool full_match (const IOV &iov, const IOV &test)
Check if IOV 'test' is of same type and is fully contained in iov.
static bool partial_match (const IOV &iov, const IOV &test)
Check if IOV 'test' is of same type and is at least partially contained in iov.
Public Attributes
const IOVType * iovType
Key keyData
int optData
unsigned int type
IOV buffer type: Must be a bitmap!
Private Member Functions
IOV ()=delete
Initializing constructor: Does not set reference to IOVType !
Detailed Description
Class describing the interval of validty.
Author
M.Frank
Version
1.0
Definition at line 59 of file IOV.h.
Member Typedef Documentation
Key
typedef std::pair<Key_first_type,Key_second_type> DD4hep::IOV::Key
Definition at line 67 of file IOV.h.
Key_first_type
typedef long DD4hep::IOV::Key_first_type
Key definition.
Definition at line 65 of file IOV.h.
Key_second_type
typedef long DD4hep::IOV::Key_second_type
Definition at line 66 of file IOV.h.
Constructor & Destructor Documentation
IOV() [1/4]
DD4hep::IOV::IOV () explicit private delete
Initializing constructor: Does not set reference to IOVType !
IOV() [2/4]
IOV::IOV (const IOVType * typ) explicit
Initializing constructor.
Definition at line 43 of file IOV.cpp.
References DD4hep::IOVType::type, type, and DD4hep::IOVType::UNKNOWN_IOV.
IOV() [3/4]
IOV::IOV (const IOVType * typ, const Key & key) explicit
Specialized copy constructor.
Copy constructor.
Definition at line 48 of file IOV.cpp.
References DD4hep::IOVType::type, type, and DD4hep::IOVType::UNKNOWN_IOV.
IOV() [4/4]
DD4hep::IOV::IOV (const IOV & copy) default
Copy constructor.
~IOV()
DD4hep::IOV::~IOV () default
Standard Destructor.
Member Function Documentation
contains()
bool IOV::contains (const IOV & iov) const
Check for validity containment.
Check if the caller 'iov' is of the same type and the range is fully conained by the caller.
Definition at line 156 of file IOV.cpp.
References iovType, key_is_contained(), keyData, DD4hep::IOVType::type, and type.
Referenced by DD4hep::Conditions::Test::check_discrete_condition().
full_match()
static bool DD4hep::IOV::full_match (const IOV & iov, const IOV & test) inline static
Check if IOV 'test' is of same type and is fully contained in iov.
Definition at line 147 of file IOV.h.
References keyData.
has_range()
bool DD4hep::IOV::has_range () const inline
Check if the IOV corresponds to a range.
Definition at line 90 of file IOV.h.
invert()
IOV & IOV::invert ()
Invert the key values (first=second and second=first)
Set keys to unphysical values (LONG_MAX, LONG_MIN)
Definition at line 78 of file IOV.cpp.
References keyData.
Referenced by DD4hep::Conditions::ConditionsManagerObject::pushUpdates().
iov_intersection() [1/2]
void IOV::iov_intersection (const IOV & comparator)
Set the intersection of this IOV with the argument IOV.
Definition at line 85 of file IOV.cpp.
References iovType, and keyData.
Referenced by DD4hep::Conditions::ConditionUpdateContext::get(), and DD4hep::Conditions::ConditionsIOVPool::select().
iov_intersection() [2/2]
void IOV::iov_intersection (const IOV::Key & comparator)
Set the intersection of this IOV with the argument IOV.
Definition at line 94 of file IOV.cpp.
References keyData.
iov_union() [1/2]
void IOV::iov_union (const IOV & comparator)
Set the union of this IOV with the argument IOV.
Definition at line 101 of file IOV.cpp.
References iovType, and keyData.
iov_union() [2/2]
void IOV::iov_union (const IOV::Key & comparator)
Set the union of this IOV with the argument IOV.
Definition at line 110 of file IOV.cpp.
References keyData.
is_discrete()
bool DD4hep::IOV::is_discrete () const inline
Check if the IOV corresponds to a range.
Definition at line 92 of file IOV.h.
Referenced by DD4hep::Conditions::Test::check_discrete_condition().
key()
Key DD4hep::IOV::key () const inline
Get the local key of the IOV.
Definition at line 94 of file IOV.h.
Referenced by DD4hep::Conditions::ConditionsIOVPool::select(), and DD4hep::Conditions::ConditionsIOVPool::selectRange().
key_contains_range()
static bool DD4hep::IOV::key_contains_range (const Key & key, const Key & test) inline static
Same as above, but reverse logic. Gives sometimes more understandable logic.
Definition at line 130 of file IOV.h.
Referenced by DD4hep::Conditions::ConditionsIOVPool::select().
key_is_contained()
static bool DD4hep::IOV::key_is_contained (const Key & key, const Key & test) inline static
Check if IOV 'test' is fully contained in IOV 'key'.
Definition at line 127 of file IOV.h.
Referenced by contains(), DD4hep::Conditions::ConditionsDependencyHandler::get(), and DD4hep::Conditions::ConditionsIOVPool::selectRange().
key_overlaps_higher_end()
static bool DD4hep::IOV::key_overlaps_higher_end (const Key & key, const Key & test) inline static
Check if IOV 'test' has an overlap on the upper interval edge with IOV 'key'.
Definition at line 136 of file IOV.h.
Referenced by DD4hep::Conditions::ConditionsIOVPool::selectRange().
key_overlaps_lower_end()
static bool DD4hep::IOV::key_overlaps_lower_end (const Key & key, const Key & test) inline static
Check if IOV 'test' has an overlap on the lower interval edge with IOV 'key'.
Definition at line 133 of file IOV.h.
Referenced by DD4hep::Conditions::ConditionsIOVPool::selectRange().
key_partially_contained()
static bool DD4hep::IOV::key_partially_contained (const Key & key, const Key & test) inline static
Check if IOV 'test' has an overlap on the upper interval edge with IOV 'key'.
Definition at line 139 of file IOV.h.
move()
void IOV::move (IOV & from)
Move the data content: 'from' will be reset to NULL.
Definition at line 118 of file IOV.cpp.
References iovType, keyData, optData, type, and DD4hep::IOVType::UNKNOWN_IOV.
operator=()
IOV& DD4hep::IOV::operator= (const IOV & c) default
Assignment operator.
partial_match()
static bool DD4hep::IOV::partial_match (const IOV & iov, const IOV & test) inline static
Check if IOV 'test' is of same type and is at least partially contained in iov.
Definition at line 150 of file IOV.h.
References keyData.
reset()
IOV & IOV::reset ()
Set keys to unphysical values (LONG_MAX, LONG_MIN)
Definition at line 71 of file IOV.cpp.
References keyData.
Referenced by DD4hep::Conditions::ConditionsManagerObject::pushUpdates().
same_type()
static bool DD4hep::IOV::same_type (const IOV & iov, const IOV & test) inline static
Check if 2 IOV objects are of the same type.
Definition at line 121 of file IOV.h.
References iovType, DD4hep::IOVType::type, and type.
set() [1/3]
void IOV::set (const Key & value)
Set discrete IOV value.
Definition at line 55 of file IOV.cpp.
References keyData.
Referenced by DD4hep::Conditions::ConditionsManagerObject::fromString().
set() [2/3]
void DD4hep::IOV::set (Key_first_type value)
Set discrete IOV value.
set() [3/3]
void DD4hep::IOV::set (Key_first_type val_1, Key_second_type val_2)
Set range IOV value.
str()
string IOV::str () const
Create string representation of the IOV.
Definition at line 126 of file IOV.cpp.
References iovType, keyData, DD4hep::IOVType::name, DD4hep::IOVType::type, and type.
Referenced by DD4hep::Conditions::Test::check_discrete_condition(), DD4hep::Alignments::AlignmentsManagerObject::compute(), DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), DD4hep::Conditions::ConditionsManagerObject::get(), DD4hep::Conditions::ConditionsManagerObject::getRange(), DD4hep::Conditions::ConditionsPool::print(), DD4hep::Conditions::ConditionsManagerObject::select_range(), and DD4hep::Conditions::Condition::str().
Member Data Documentation
iovType
const IOVType* DD4hep::IOV::iovType
Definition at line 69 of file IOV.h.
Referenced by contains(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), DD4hep::Conditions::ConditionsManagerObject::fromString(), iov_intersection(), iov_union(), DD4hep::Conditions::Interna::ConditionObject::iovType(), move(), DD4hep::Conditions::Condition::rebind(), DD4hep::Conditions::ConditionsManagerObject::registerIOV(), same_type(), and str().
keyData
Key DD4hep::IOV::keyData
Definition at line 70 of file IOV.h.
Referenced by DD4hep::Conditions::ConditionsIOVPool::clean(), contains(), full_match(), DD4hep::Conditions::ConditionsDependencyHandler::get(), invert(), iov_intersection(), iov_union(), move(), partial_match(), DD4hep::Conditions::ConditionsManagerObject::registerCondition(), DD4hep::Conditions::ConditionsManagerObject::registerIOV(), reset(), set(), and str().
optData
int DD4hep::IOV::optData
Definition at line 71 of file IOV.h.
Referenced by move().
type
unsigned int DD4hep::IOV::type
IOV buffer type: Must be a bitmap!
Definition at line 73 of file IOV.h.
Referenced by contains(), DD4hep::Conditions::ConditionsManagerObject::fromString(), IOV(), move(), DD4hep::Conditions::ConditionsManagerObject::registerCondition(), same_type(), DD4hep::Conditions::ConditionsManagerObject::select(), DD4hep::Conditions::ConditionsManagerObject::select_range(), and str().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/IOV.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/IOV.cpp