DD4hep: DD4hep: DD4hep::Simulation::Geant4InteractionMerger Class Reference
DD4hep::Simulation::Geant4InteractionMerger Class Reference
[DD4hep::Simulation components, classes and objects]
Geant4Action to merge several independent interaction to one.
#include <Geant4InteractionMerger.h>
Public Member Functions
Geant4InteractionMerger (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4InteractionMerger ()
Default destructor.
virtual void operator() (G4Event *event)
Event generation action callback.
Private Member Functions
void appendInteraction (Geant4PrimaryInteraction *output, Geant4PrimaryInteraction *input)
Append input interaction to global output.
Detailed Description
Geant4Action to merge several independent interaction to one.
Merge all interactions created by each {Geant4InputAction} into one single record. The input records are taken from the item {Geant4PrimaryEvent} and are merged into the {Geant4PrimaryInteraction} object attached to the {Geant4Event} event context.
Author:
M.Frank
Version:
1.0
Definition at line 39 of file Geant4InteractionMerger.h.
Constructor & Destructor Documentation
Geant4InteractionMerger::Geant4InteractionMerger (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 24 of file Geant4InteractionMerger.cpp.
References DD4hep::InstanceCount::increment().
Geant4InteractionMerger::~Geant4InteractionMerger () [virtual]
Default destructor.
Definition at line 31 of file Geant4InteractionMerger.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void DD4hep::Simulation::Geant4InteractionMerger::appendInteraction (Geant4PrimaryInteraction * output, Geant4PrimaryInteraction * input) [private]
Append input interaction to global output.
void Geant4InteractionMerger::operator() (G4Event * event) [virtual]
Event generation action callback.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 36 of file Geant4InteractionMerger.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Action::debug(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4PrimaryEvent::interactions(), and DD4hep::Simulation::mergeInteractions().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4InteractionMerger.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4InteractionMerger.cpp