DD4hep: DD4hep: DD4hep::EventHandler Class Reference
DD4hep::EventHandler Class Reference
Event handler base class. Interface to all DDEve I/O actions.
#include <EventHandler.h>
Public Types
enum CollectionType {
NO_COLLECTION = 1<<0, PARTICLE_COLLECTION = 1<<1, TRACK_COLLECTION = 1<<2, CALO_HIT_COLLECTION = 1<<3,
TRACKER_HIT_COLLECTION = 1<<4, HIT_COLLECTION = CALO_HIT_COLLECTION|TRACKER_HIT_COLLECTION
}
typedef std::pair< const char
*, size_t > Collection
Collection definition: name, size.
typedef std::map< std::string,
std::vector< Collection > > TypedEventCollections
Types collection: collections are grouped by type (class name).
Public Member Functions
EventHandler ()
Standard constructor.
virtual ~EventHandler ()
Default destructor.
virtual bool hasEvent () const
Check if an event is present in memory.
virtual bool hasFile () const
Check if a data file is connected to the handler.
virtual const
TypedEventCollections & data () const =0
Access the map of simulation data collections.
virtual long numEvents () const =0
Access the number of events on the current input data source (-1 if no data source connected).
virtual std::string datasourceName () const =0
Access the data source name.
virtual size_t collectionLoop (const std::string &collection, DDEveHitActor &actor)=0
Loop over collection and extract hit data.
virtual size_t collectionLoop (const std::string &collection, DDEveParticleActor &actor)=0
Loop over collection and extract particle data.
virtual CollectionType collectionType (const std::string &collection) const =0
Access to the collection type by name.
virtual bool Open (const std::string &type, const std::string &file_name)=0
Open a new event data file.
virtual bool NextEvent ()=0
Load the next event.
virtual bool PreviousEvent ()=0
User overloadable function: Load the previous event.
virtual bool GotoEvent (long event_number)=0
Goto a specified event in the file.
ClassDef (EventHandler, 0)
Protected Attributes
bool m_hasFile
Flag to indicate that a file is opened.
bool m_hasEvent
Flag to indicate that an event is loaded.
Detailed Description
Event handler base class. Interface to all DDEve I/O actions.
Author:
M.Frank
Version:
1.0
Definition at line 66 of file EventHandler.h.
Member Typedef Documentation
typedef std::pair<const char*,size_t> DD4hep::EventHandler::Collection
Collection definition: name, size.
Definition at line 77 of file EventHandler.h.
typedef std::map<std::string,std::vector<Collection> > DD4hep::EventHandler::TypedEventCollections
Types collection: collections are grouped by type (class name).
Definition at line 79 of file EventHandler.h.
Member Enumeration Documentation
enum DD4hep::EventHandler::CollectionType
Enumerator:
NO_COLLECTION
PARTICLE_COLLECTION
TRACK_COLLECTION
CALO_HIT_COLLECTION
TRACKER_HIT_COLLECTION
HIT_COLLECTION
Definition at line 68 of file EventHandler.h.
Constructor & Destructor Documentation
DD4hep::EventHandler::EventHandler ()
Standard constructor.
EventHandler::~EventHandler () [virtual]
Default destructor.
Definition at line 28 of file EventHandler.cpp.
Member Function Documentation
DD4hep::EventHandler::ClassDef (EventHandler , 0)
Reimplemented in DD4hep::DDG4EventHandler, and DD4hep::GenericEventHandler.
virtual size_t DD4hep::EventHandler::collectionLoop (const std::string & collection, DDEveParticleActor & actor) [pure virtual]
Loop over collection and extract particle data.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
virtual size_t DD4hep::EventHandler::collectionLoop (const std::string & collection, DDEveHitActor & actor) [pure virtual]
Loop over collection and extract hit data.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
Referenced by DD4hep::Display::OnNewEvent().
virtual CollectionType DD4hep::EventHandler::collectionType (const std::string & collection) const [pure virtual]
Access to the collection type by name.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
Referenced by DD4hep::Display::OnNewEvent().
virtual const TypedEventCollections& DD4hep::EventHandler::data () const [pure virtual]
Access the map of simulation data collections.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
Referenced by DD4hep::GenericEventHandler::data(), DD4hep::EventControl::OnNewEvent(), and DD4hep::Display::OnNewEvent().
virtual std::string DD4hep::EventHandler::datasourceName () const [pure virtual]
Access the data source name.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
Referenced by DD4hep::GenericEventHandler::datasourceName(), and DD4hep::EventControl::OnFileOpen().
virtual bool DD4hep::EventHandler::GotoEvent (long event_number) [pure virtual]
Goto a specified event in the file.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
virtual bool DD4hep::EventHandler::hasEvent () const [inline, virtual]
Check if an event is present in memory.
Definition at line 92 of file EventHandler.h.
References m_hasEvent.
virtual bool DD4hep::EventHandler::hasFile () const [inline, virtual]
Check if a data file is connected to the handler.
Definition at line 94 of file EventHandler.h.
References m_hasFile.
Referenced by DD4hep::DDG4EventHandler::datasourceName(), DD4hep::LCIOEventHandler::datasourceName(), DD4hep::LCIOEventHandler::NextEvent(), DD4hep::DDG4EventHandler::numEvents(), DD4hep::LCIOEventHandler::numEvents(), DD4hep::EventControl::OnBuild(), DD4hep::EventControl::OnFileOpen(), and DD4hep::DDG4EventHandler::ReadEvent().
virtual bool DD4hep::EventHandler::NextEvent () [pure virtual]
Load the next event.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
virtual long DD4hep::EventHandler::numEvents () const [pure virtual]
Access the number of events on the current input data source (-1 if no data source connected).
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
Referenced by DD4hep::GenericEventHandler::numEvents(), and DD4hep::EventControl::OnFileOpen().
virtual bool DD4hep::EventHandler::Open (const std::string & type, const std::string & file_name) [pure virtual]
Open a new event data file.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
virtual bool DD4hep::EventHandler::PreviousEvent () [pure virtual]
User overloadable function: Load the previous event.
Implemented in DD4hep::DDG4EventHandler, DD4hep::GenericEventHandler, and DD4hep::LCIOEventHandler.
Member Data Documentation
bool DD4hep::EventHandler::m_hasEvent [protected]
Flag to indicate that an event is loaded.
Definition at line 85 of file EventHandler.h.
Referenced by DD4hep::GenericEventHandler::GotoEvent(), hasEvent(), DD4hep::GenericEventHandler::NextEvent(), DD4hep::LCIOEventHandler::NextEvent(), DD4hep::DDG4EventHandler::Open(), DD4hep::LCIOEventHandler::Open(), DD4hep::GenericEventHandler::PreviousEvent(), and DD4hep::DDG4EventHandler::ReadEvent().
bool DD4hep::EventHandler::m_hasFile [protected]
Flag to indicate that a file is opened.
Definition at line 83 of file EventHandler.h.
Referenced by DD4hep::GenericEventHandler::GotoEvent(), hasFile(), DD4hep::GenericEventHandler::NextEvent(), DD4hep::DDG4EventHandler::Open(), DD4hep::LCIOEventHandler::Open(), and DD4hep::GenericEventHandler::PreviousEvent().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/EventHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/EventHandler.cpp