DD4hep: DD4hep: DD4hep::DDSegmentation::SegmentationFactory Class Reference
DD4hep::DDSegmentation::SegmentationFactory Class Reference
Factory for creating segmentation objects by type name.
#include <SegmentationFactory.h>
Public Member Functions
Segmentation * create (const std::string &name, const std::string &identifier="") const
Create a new segmentation object with the given type name. Returns NULL if type name is unknown.
std::vector< std::string > registeredSegmentations () const
Access to the list of registered segmentations.
Static Public Member Functions
static SegmentationFactory * instance ()
Access to the global factory instance.
Protected Member Functions
SegmentationFactory ()
Default constructor.
SegmentationFactory (const SegmentationFactory &)
Copy constructor.
virtual ~SegmentationFactory ()
Destructor.
void registerSegmentation (const std::string &name, SegmentationCreatorBase *creator)
Registers a new SegmentationCreator with the factory.
Protected Attributes
std::map< std::string,
SegmentationCreatorBase * > _segmentations
Map to store SegmentationCreators by name.
Static Private Attributes
static SegmentationFactory * _instance = 0
The global factory instance.
Friends
class SegmentationCreatorBase
Allow SegmentationCreators to register themselves with the factory.
Detailed Description
Factory for creating segmentation objects by type name.
Definition at line 49 of file SegmentationFactory.h.
Constructor & Destructor Documentation
DD4hep::DDSegmentation::SegmentationFactory::SegmentationFactory () [inline, protected]
Default constructor.
Definition at line 61 of file SegmentationFactory.h.
Referenced by instance().
DD4hep::DDSegmentation::SegmentationFactory::SegmentationFactory (const SegmentationFactory &) [inline, protected]
Copy constructor.
Definition at line 63 of file SegmentationFactory.h.
virtual DD4hep::DDSegmentation::SegmentationFactory::~SegmentationFactory () [inline, protected, virtual]
Destructor.
Definition at line 65 of file SegmentationFactory.h.
Member Function Documentation
Segmentation * DD4hep::DDSegmentation::SegmentationFactory::create (const std::string & name, const std::string & identifier = "") const
Create a new segmentation object with the given type name. Returns NULL if type name is unknown.
Definition at line 33 of file SegmentationFactory.cpp.
References _segmentations.
SegmentationFactory * DD4hep::DDSegmentation::SegmentationFactory::instance () [static]
Access to the global factory instance.
Definition at line 25 of file SegmentationFactory.cpp.
References _instance, and SegmentationFactory().
Referenced by DD4hep::DDSegmentation::SegmentationCreatorBase::SegmentationCreatorBase().
vector< std::string > DD4hep::DDSegmentation::SegmentationFactory::registeredSegmentations () const
Access to the list of registered segmentations.
Definition at line 43 of file SegmentationFactory.cpp.
References _segmentations.
void DD4hep::DDSegmentation::SegmentationFactory::registerSegmentation (const std::string & name, SegmentationCreatorBase * creator) [protected]
Registers a new SegmentationCreator with the factory.
Definition at line 53 of file SegmentationFactory.cpp.
References _segmentations.
Referenced by DD4hep::DDSegmentation::SegmentationCreatorBase::SegmentationCreatorBase().
Friends And Related Function Documentation
friend class SegmentationCreatorBase [friend]
Allow SegmentationCreators to register themselves with the factory.
Definition at line 51 of file SegmentationFactory.h.
Member Data Documentation
SegmentationFactory * DD4hep::DDSegmentation::SegmentationFactory::_instance = 0 [static, private]
The global factory instance.
Initialize the global factory instance.
Definition at line 72 of file SegmentationFactory.h.
Referenced by instance().
std::map<std::string, SegmentationCreatorBase*> DD4hep::DDSegmentation::SegmentationFactory::_segmentations [protected]
Map to store SegmentationCreators by name.
Definition at line 69 of file SegmentationFactory.h.
Referenced by create(), registeredSegmentations(), and registerSegmentation().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/SegmentationFactory.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/SegmentationFactory.cpp