DD4hep: DD4hep: DD4hep::Geometry::EightPointSolid Class Reference
DD4hep::Geometry::EightPointSolid Class Reference
[DD4hep::Geometry components, classes and objects]
Class describing an arbitray solid defined by 8 vertices.
#include <Shapes.h>
Public Member Functions
EightPointSolid ()
Default constructor.
EightPointSolid (const EightPointSolid &e)
Constructor to be used when passing an already created object.
template<typename Q >
EightPointSolid (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
EightPointSolid (const Handle< Q > &e)
Constructor to be used when passing an already created object.
EightPointSolid (double dz, const double *vertices)
Constructor to create a new anonymous object with attribute initialization.
EightPointSolid & operator= (const EightPointSolid &copy)
Assignment operator.
Private Member Functions
void make (double dz, const double *vtx)
Internal helper method to support object construction.
Detailed Description
Class describing an arbitray solid defined by 8 vertices.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoArb8.html
Author:
M.Frank
Version:
1.0
Definition at line 621 of file Shapes.h.
Constructor & Destructor Documentation
DD4hep::Geometry::EightPointSolid::EightPointSolid ()
Default constructor.
DD4hep::Geometry::EightPointSolid::EightPointSolid (const EightPointSolid & e)
Constructor to be used when passing an already created object.
template<typename Q > DD4hep::Geometry::EightPointSolid::EightPointSolid (const Q * p) [inline]
Constructor to be used with an existing object.
Definition at line 631 of file Shapes.h.
template<typename Q > DD4hep::Geometry::EightPointSolid::EightPointSolid (const Handle< Q > & e) [inline]
Constructor to be used when passing an already created object.
Definition at line 633 of file Shapes.h.
DD4hep::Geometry::EightPointSolid::EightPointSolid (double dz, const double * vertices) [inline]
Constructor to create a new anonymous object with attribute initialization.
Definition at line 635 of file Shapes.h.
References make().
Member Function Documentation
void EightPointSolid::make (double dz, const double * vtx) [private]
Internal helper method to support object construction.
Creator method.
Definition at line 429 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoArb8 >::_assign().
Referenced by EightPointSolid().
EightPointSolid& DD4hep::Geometry::EightPointSolid::operator= (const EightPointSolid & copy)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp