DD4hep: TiXmlAttributeSet Class Reference
TiXmlAttributeSet Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlAttributeSet ()
~TiXmlAttributeSet ()
void Add (TiXmlAttribute *attribute)
void Remove (TiXmlAttribute *attribute)
const TiXmlAttribute * First () const
TiXmlAttribute * First ()
const TiXmlAttribute * Last () const
TiXmlAttribute * Last ()
const TiXmlAttribute * Find (const char *_name) const
TiXmlAttribute * Find (const char *_name)
const TiXmlAttribute * Find (const std::string &_name) const
TiXmlAttribute * Find (const std::string &_name)
Private Member Functions
TiXmlAttributeSet (const TiXmlAttributeSet &)
void operator= (const TiXmlAttributeSet &)
Private Attributes
TiXmlAttribute sentinel
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 1020 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlAttributeSet() [1/2]
TiXmlAttributeSet::TiXmlAttributeSet ()
Definition at line 1524 of file tinyxml_inl.h.
~TiXmlAttributeSet()
TiXmlAttributeSet::~TiXmlAttributeSet ()
Definition at line 1531 of file tinyxml_inl.h.
TiXmlAttributeSet() [2/2]
TiXmlAttributeSet::TiXmlAttributeSet (const TiXmlAttributeSet &) private
Member Function Documentation
Add()
void TiXmlAttributeSet::Add (TiXmlAttribute * attribute)
Definition at line 1538 of file tinyxml_inl.h.
References TiXmlAttribute::Name(), TiXmlAttribute::next, TiXmlAttribute::prev, and TIXML_STRING.
Referenced by TiXmlElement::SetAttribute().
Find() [1/4]
const TiXmlAttribute * TiXmlAttributeSet::Find (const char * _name) const
Definition at line 1597 of file tinyxml_inl.h.
References TiXmlNode::Accept(), TiXmlAttribute::next, TiXmlNode::operator<<, TiXmlNode::operator>>, TiXmlBase::Parse(), TiXmlPrinter::SetStreamPrinting(), TiXmlPrinter::Str(), TiXmlNode::StreamIn(), TIXML_DEFAULT_ENCODING, and TIXML_STRING.
Referenced by TiXmlElement::Attribute(), TiXmlElement::QueryDoubleAttribute(), TiXmlElement::QueryIntAttribute(), Remove(), and TiXmlElement::SetAttribute().
Find() [2/4]
TiXmlAttribute* TiXmlAttributeSet::Find (const char * _name) inline
Definition at line 1042 of file tinyxml.h.
Find() [3/4]
const TiXmlAttribute* TiXmlAttributeSet::Find (const std::string & _name) const
Find() [4/4]
TiXmlAttribute* TiXmlAttributeSet::Find (const std::string & _name) inline
Definition at line 1047 of file tinyxml.h.
First() [1/2]
const TiXmlAttribute* TiXmlAttributeSet::First () const inline
Definition at line 1028 of file tinyxml.h.
References TiXmlAttribute::next.
Referenced by TiXmlElement::Accept(), TiXmlElement::ClearAttributes(), TiXmlElement::ClearThis(), TiXmlElement::CopyTo(), and TiXmlElement::Print().
First() [2/2]
TiXmlAttribute* TiXmlAttributeSet::First () inline
Definition at line 1031 of file tinyxml.h.
References TiXmlAttribute::next.
Last() [1/2]
const TiXmlAttribute* TiXmlAttributeSet::Last () const inline
Definition at line 1034 of file tinyxml.h.
References TiXmlAttribute::prev.
Last() [2/2]
TiXmlAttribute* TiXmlAttributeSet::Last () inline
Definition at line 1037 of file tinyxml.h.
References TiXmlAttribute::prev.
operator=()
void TiXmlAttributeSet::operator= (const TiXmlAttributeSet &) private
Referenced by TiXmlAttribute::SetDocument().
Remove()
void TiXmlAttributeSet::Remove (TiXmlAttribute * attribute)
Definition at line 1553 of file tinyxml_inl.h.
References Find(), TiXmlAttribute::next, and TiXmlAttribute::prev.
Referenced by TiXmlElement::ClearAttributes(), and TiXmlElement::ClearThis().
Member Data Documentation
sentinel
TiXmlAttribute TiXmlAttributeSet::sentinel private
Definition at line 1059 of file tinyxml.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h