DD4hep: TiXmlPrinter Class Reference
TiXmlPrinter Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlPrinter ()
virtual bool VisitEnter (const TiXmlDocument &doc)
Visit a document.
virtual bool VisitExit (const TiXmlDocument &doc)
Visit a document.
virtual bool VisitEnter (const TiXmlElement &element, const TiXmlAttribute *firstAttribute)
Visit an element.
virtual bool VisitExit (const TiXmlElement &element)
Visit an element.
virtual bool Visit (const TiXmlDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const TiXmlText &text)
Visit a text node.
virtual bool Visit (const TiXmlComment &comment)
Visit a comment node.
virtual bool Visit (const TiXmlUnknown &unknown)
Visit an unknow node.
void SetIndent (const char *_indent)
const char * Indent ()
Query the indention string.
void SetLineBreak (const char *_lineBreak)
const char * LineBreak ()
Query the current line breaking string.
void SetStreamPrinting ()
const char * CStr ()
Return the result.
size_t Size ()
Return the length of the result string.
const std::string & Str ()
Return the result.
Public Member Functions inherited from TiXmlVisitor
virtual ~TiXmlVisitor ()
Private Member Functions
void DoIndent ()
void DoLineBreak ()
Private Attributes
int depth
bool simpleTextPrint
TIXML_STRING buffer
TIXML_STRING indent
TIXML_STRING lineBreak
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
Print to memory functionality. The TiXmlPrinter is useful when you need to:
Print to memory (especially in non-STL mode)
Control formatting (line endings, etc.)
When constructed, the TiXmlPrinter is in its default "pretty printing" mode. Before calling Accept() you can call methods to control the printing of the XML document. After TiXmlNode::Accept() is called, the printed document can be accessed via the CStr(), Str(), and Size() methods.
TiXmlPrinter uses the Visitor API.
TiXmlPrinter printer;
printer.SetIndent("\t");
doc.Accept(&printer);
fprintf(stdout, "%s", printer.CStr());
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 1943 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlPrinter()
TiXmlPrinter::TiXmlPrinter () inline
Definition at line 1945 of file tinyxml.h.
Member Function Documentation
CStr()
const char* TiXmlPrinter::CStr () inline
Return the result.
Definition at line 1990 of file tinyxml.h.
DoIndent()
void TiXmlPrinter::DoIndent () inline private
Definition at line 2006 of file tinyxml.h.
DoLineBreak()
void TiXmlPrinter::DoLineBreak () inline private
Definition at line 2010 of file tinyxml.h.
Indent()
const char* TiXmlPrinter::Indent () inline
Query the indention string.
Definition at line 1967 of file tinyxml.h.
LineBreak()
const char* TiXmlPrinter::LineBreak () inline
Query the current line breaking string.
Definition at line 1978 of file tinyxml.h.
SetIndent()
void TiXmlPrinter::SetIndent (const char * _indent) inline
Set the indent characters for printing. By default 4 spaces but tab () is also useful, or null/empty string for no indentation.
Definition at line 1963 of file tinyxml.h.
SetLineBreak()
void TiXmlPrinter::SetLineBreak (const char * _lineBreak) inline
Set the line breaking string. By default set to newline (
). Some operating systems prefer other characters, or can be set to the null/empty string for no indenation.
Definition at line 1974 of file tinyxml.h.
SetStreamPrinting()
void TiXmlPrinter::SetStreamPrinting () inline
Switch over to "stream printing" which is the most dense formatting without linebreaks. Common when the XML is needed for network transmission.
Definition at line 1985 of file tinyxml.h.
Referenced by TiXmlAttributeSet::Find(), and DD4hep::XML::DocumentHandler::output().
Size()
size_t TiXmlPrinter::Size () inline
Return the length of the result string.
Definition at line 1994 of file tinyxml.h.
Str()
const std::string& TiXmlPrinter::Str () inline
Return the result.
Definition at line 2000 of file tinyxml.h.
Referenced by TiXmlAttributeSet::Find(), and DD4hep::XML::DocumentHandler::output().
Visit() [1/4]
bool TiXmlPrinter::Visit (const TiXmlDeclaration &) virtual
Visit a declaration.
Reimplemented from TiXmlVisitor.
Definition at line 1877 of file tinyxml_inl.h.
References TiXmlDeclaration::Print().
Visit() [2/4]
bool TiXmlPrinter::Visit (const TiXmlText &) virtual
Visit a text node.
Reimplemented from TiXmlVisitor.
Definition at line 1853 of file tinyxml_inl.h.
References TiXmlText::CDATA(), and TiXmlNode::Value().
Visit() [3/4]
bool TiXmlPrinter::Visit (const TiXmlComment &) virtual
Visit a comment node.
Reimplemented from TiXmlVisitor.
Definition at line 1886 of file tinyxml_inl.h.
References TiXmlNode::Value().
Visit() [4/4]
bool TiXmlPrinter::Visit (const TiXmlUnknown &) virtual
Visit an unknow node.
Reimplemented from TiXmlVisitor.
Definition at line 1897 of file tinyxml_inl.h.
References TiXmlNode::Value().
VisitEnter() [1/2]
bool TiXmlPrinter::VisitEnter (const TiXmlDocument &) virtual
Visit a document.
Reimplemented from TiXmlVisitor.
Definition at line 1780 of file tinyxml_inl.h.
VisitEnter() [2/2]
bool TiXmlPrinter::VisitEnter (const TiXmlElement & , const TiXmlAttribute *) virtual
Visit an element.
Reimplemented from TiXmlVisitor.
Definition at line 1790 of file tinyxml_inl.h.
References TiXmlText::CDATA(), TiXmlNode::FirstChild(), TiXmlNode::LastChild(), TiXmlAttribute::Next(), TiXmlNode::ToText(), and TiXmlNode::Value().
VisitExit() [1/2]
bool TiXmlPrinter::VisitExit (const TiXmlDocument &) virtual
Visit a document.
Reimplemented from TiXmlVisitor.
Definition at line 1785 of file tinyxml_inl.h.
VisitExit() [2/2]
bool TiXmlPrinter::VisitExit (const TiXmlElement &) virtual
Visit an element.
Reimplemented from TiXmlVisitor.
Definition at line 1827 of file tinyxml_inl.h.
References TiXmlNode::FirstChild(), and TiXmlNode::Value().
Member Data Documentation
buffer
TIXML_STRING TiXmlPrinter::buffer private
Definition at line 2015 of file tinyxml.h.
depth
int TiXmlPrinter::depth private
Definition at line 2014 of file tinyxml.h.
indent
TIXML_STRING TiXmlPrinter::indent private
Definition at line 2015 of file tinyxml.h.
lineBreak
TIXML_STRING TiXmlPrinter::lineBreak private
Definition at line 2015 of file tinyxml.h.
simpleTextPrint
bool TiXmlPrinter::simpleTextPrint private
Definition at line 2015 of file tinyxml.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h