DD4hep: DD4hep::DDRec::SubdetectorExtensionImpl Class Reference
DD4hep::DDRec::SubdetectorExtensionImpl Class Reference
#include <SubdetectorExtensionImpl.h>
Public Member Functions
SubdetectorExtensionImpl (const Geometry::DetElement &det)
Default constructor using a top level DetElement.
SubdetectorExtensionImpl (const SubdetectorExtensionImpl &e, const Geometry::DetElement &d)
Copy constructor.
virtual ~SubdetectorExtensionImpl ()
Destructor.
virtual bool isBarrel () const
Is this a barrel detector.
virtual bool isEndcap () const
Is this an endcap detector.
virtual double getRMin () const
Access to the inner radius.
virtual double getRMax () const
Access to the outer radius.
virtual double getZMin () const
Access to the lower z extent.
virtual double getZMax () const
Access to the upper z extent.
virtual int getNSides () const
Access to the number of sides.
void setDetectorElement (const Geometry::DetElement &det)
Sets the top level detector element used to determine shape information.
void setIsBarrel (bool value)
Sets the isBarrel flag.
void setIsEndcap (bool value)
Sets the isEndcap flag.
void setRMin (double value)
Sets the value for the inner radius.
void setRMax (double value)
Sets the value for the outer radius.
void setZMin (double value)
Sets the value for the inner z extent.
void setZMax (double value)
Sets the value for the outer z extent.
void setNSides (int value)
Sets the number of sides.
Public Member Functions inherited from DD4hep::DDRec::SubdetectorExtension
virtual ~SubdetectorExtension ()
Destructor.
Protected Member Functions
void resetAll ()
Protected Member Functions inherited from DD4hep::DDRec::SubdetectorExtension
SubdetectorExtension ()
Protected Attributes
Geometry::DetElement det
bool _isBarrel
bool _setIsBarrel
bool _isEndcap
bool _setIsEndcap
double _rMin
bool _setRMin
double _rMax
bool _setRMax
double _zMin
bool _setZMin
double _zMax
bool _setZMax
int _nSides
bool _setNSides
Detailed Description
Class describing general parameters of a subdetector. By default information is retrieved from the DetElement if possible. Values can be set manually which will superseed the information from the DetElement.
Definition at line 25 of file SubdetectorExtensionImpl.h.
Constructor & Destructor Documentation
SubdetectorExtensionImpl() [1/2]
DD4hep::DDRec::SubdetectorExtensionImpl::SubdetectorExtensionImpl (const Geometry::DetElement & det)
Default constructor using a top level DetElement.
Constructor using a top level DetElement.
Definition at line 20 of file SubdetectorExtensionImpl.cpp.
References det, and resetAll().
SubdetectorExtensionImpl() [2/2]
DD4hep::DDRec::SubdetectorExtensionImpl::SubdetectorExtensionImpl (const SubdetectorExtensionImpl & e, const Geometry::DetElement & d)
Copy constructor.
Definition at line 26 of file SubdetectorExtensionImpl.cpp.
References _setIsBarrel, _setIsEndcap, _setNSides, _setRMax, _setRMin, _setZMax, _setZMin, det, getNSides(), getRMax(), getRMin(), getZMax(), getZMin(), isBarrel(), isEndcap(), setIsBarrel(), setIsEndcap(), setNSides(), setRMax(), setRMin(), setZMax(), and setZMin().
~SubdetectorExtensionImpl()
DD4hep::DDRec::SubdetectorExtensionImpl::~SubdetectorExtensionImpl () virtual
Destructor.
Definition at line 52 of file SubdetectorExtensionImpl.cpp.
Member Function Documentation
getNSides()
int DD4hep::DDRec::SubdetectorExtensionImpl::getNSides () const virtual
Access to the number of sides.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 164 of file SubdetectorExtensionImpl.cpp.
References _nSides, _setNSides, det, e, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::Volume::solid(), and DD4hep::Geometry::DetElement::volume().
Referenced by SubdetectorExtensionImpl().
getRMax()
double DD4hep::DDRec::SubdetectorExtensionImpl::getRMax () const virtual
Access to the outer radius.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 100 of file SubdetectorExtensionImpl.cpp.
References _rMax, _setRMax, det, e, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::Volume::solid(), and DD4hep::Geometry::DetElement::volume().
Referenced by SubdetectorExtensionImpl().
getRMin()
double DD4hep::DDRec::SubdetectorExtensionImpl::getRMin () const virtual
Access to the inner radius.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 75 of file SubdetectorExtensionImpl.cpp.
References _rMin, _setRMin, det, e, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::Volume::solid(), and DD4hep::Geometry::DetElement::volume().
Referenced by SubdetectorExtensionImpl().
getZMax()
double DD4hep::DDRec::SubdetectorExtensionImpl::getZMax () const virtual
Access to the upper z extent.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 143 of file SubdetectorExtensionImpl.cpp.
References _setZMax, _zMax, det, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::localToWorld(), DD4hep::Geometry::Volume::solid(), and DD4hep::Geometry::DetElement::volume().
Referenced by SubdetectorExtensionImpl().
getZMin()
double DD4hep::DDRec::SubdetectorExtensionImpl::getZMin () const virtual
Access to the lower z extent.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 125 of file SubdetectorExtensionImpl.cpp.
References _setZMin, _zMin, det, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::localToWorld(), DD4hep::Geometry::Volume::solid(), and DD4hep::Geometry::DetElement::volume().
Referenced by SubdetectorExtensionImpl().
isBarrel()
bool DD4hep::DDRec::SubdetectorExtensionImpl::isBarrel () const virtual
Is this a barrel detector.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 57 of file SubdetectorExtensionImpl.cpp.
References _isBarrel, _setIsBarrel, det, DD4hep::DDRec::IDDecoder::getInstance(), and DD4hep::Geometry::DetElement::volumeID().
Referenced by SubdetectorExtensionImpl().
isEndcap()
bool DD4hep::DDRec::SubdetectorExtensionImpl::isEndcap () const virtual
Is this an endcap detector.
Implements DD4hep::DDRec::SubdetectorExtension.
Definition at line 66 of file SubdetectorExtensionImpl.cpp.
References _isEndcap, _setIsEndcap, det, DD4hep::DDRec::IDDecoder::getInstance(), and DD4hep::Geometry::DetElement::volumeID().
Referenced by SubdetectorExtensionImpl().
resetAll()
void DD4hep::DDRec::SubdetectorExtensionImpl::resetAll () protected
Definition at line 227 of file SubdetectorExtensionImpl.cpp.
References _isBarrel, _isEndcap, _nSides, _rMax, _rMin, _setIsBarrel, _setIsEndcap, _setNSides, _setRMax, _setRMin, _setZMax, _setZMin, _zMax, and _zMin.
Referenced by SubdetectorExtensionImpl().
setDetectorElement()
void DD4hep::DDRec::SubdetectorExtensionImpl::setDetectorElement (const Geometry::DetElement & det)
Sets the top level detector element used to determine shape information.
Definition at line 183 of file SubdetectorExtensionImpl.cpp.
References det.
setIsBarrel()
void DD4hep::DDRec::SubdetectorExtensionImpl::setIsBarrel (bool value)
Sets the isBarrel flag.
Definition at line 188 of file SubdetectorExtensionImpl.cpp.
References _isBarrel.
Referenced by SubdetectorExtensionImpl().
setIsEndcap()
void DD4hep::DDRec::SubdetectorExtensionImpl::setIsEndcap (bool value)
Sets the isEndcap flag.
Definition at line 193 of file SubdetectorExtensionImpl.cpp.
References _isEndcap.
Referenced by SubdetectorExtensionImpl().
setNSides()
void DD4hep::DDRec::SubdetectorExtensionImpl::setNSides (int value)
Sets the number of sides.
Definition at line 222 of file SubdetectorExtensionImpl.cpp.
References _nSides, and _setNSides.
Referenced by SubdetectorExtensionImpl().
setRMax()
void DD4hep::DDRec::SubdetectorExtensionImpl::setRMax (double value)
Sets the value for the outer radius.
Definition at line 204 of file SubdetectorExtensionImpl.cpp.
References _rMax, and _setRMax.
Referenced by SubdetectorExtensionImpl().
setRMin()
void DD4hep::DDRec::SubdetectorExtensionImpl::setRMin (double value)
Sets the value for the inner radius.
Definition at line 198 of file SubdetectorExtensionImpl.cpp.
References _rMin, and _setRMin.
Referenced by SubdetectorExtensionImpl().
setZMax()
void DD4hep::DDRec::SubdetectorExtensionImpl::setZMax (double value)
Sets the value for the outer z extent.
Definition at line 216 of file SubdetectorExtensionImpl.cpp.
References _setZMax, and _zMax.
Referenced by SubdetectorExtensionImpl().
setZMin()
void DD4hep::DDRec::SubdetectorExtensionImpl::setZMin (double value)
Sets the value for the inner z extent.
Definition at line 210 of file SubdetectorExtensionImpl.cpp.
References _setZMin, and _zMin.
Referenced by SubdetectorExtensionImpl().
Member Data Documentation
_isBarrel
bool DD4hep::DDRec::SubdetectorExtensionImpl::_isBarrel protected
Definition at line 86 of file SubdetectorExtensionImpl.h.
Referenced by isBarrel(), resetAll(), and setIsBarrel().
_isEndcap
bool DD4hep::DDRec::SubdetectorExtensionImpl::_isEndcap protected
Definition at line 88 of file SubdetectorExtensionImpl.h.
Referenced by isEndcap(), resetAll(), and setIsEndcap().
_nSides
int DD4hep::DDRec::SubdetectorExtensionImpl::_nSides protected
Definition at line 98 of file SubdetectorExtensionImpl.h.
Referenced by getNSides(), resetAll(), and setNSides().
_rMax
double DD4hep::DDRec::SubdetectorExtensionImpl::_rMax protected
Definition at line 92 of file SubdetectorExtensionImpl.h.
Referenced by getRMax(), resetAll(), and setRMax().
_rMin
double DD4hep::DDRec::SubdetectorExtensionImpl::_rMin protected
Definition at line 90 of file SubdetectorExtensionImpl.h.
Referenced by getRMin(), resetAll(), and setRMin().
_setIsBarrel
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setIsBarrel protected
Definition at line 87 of file SubdetectorExtensionImpl.h.
Referenced by isBarrel(), resetAll(), and SubdetectorExtensionImpl().
_setIsEndcap
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setIsEndcap protected
Definition at line 89 of file SubdetectorExtensionImpl.h.
Referenced by isEndcap(), resetAll(), and SubdetectorExtensionImpl().
_setNSides
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setNSides protected
Definition at line 99 of file SubdetectorExtensionImpl.h.
Referenced by getNSides(), resetAll(), setNSides(), and SubdetectorExtensionImpl().
_setRMax
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setRMax protected
Definition at line 93 of file SubdetectorExtensionImpl.h.
Referenced by getRMax(), resetAll(), setRMax(), and SubdetectorExtensionImpl().
_setRMin
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setRMin protected
Definition at line 91 of file SubdetectorExtensionImpl.h.
Referenced by getRMin(), resetAll(), setRMin(), and SubdetectorExtensionImpl().
_setZMax
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setZMax protected
Definition at line 97 of file SubdetectorExtensionImpl.h.
Referenced by getZMax(), resetAll(), setZMax(), and SubdetectorExtensionImpl().
_setZMin
bool DD4hep::DDRec::SubdetectorExtensionImpl::_setZMin protected
Definition at line 95 of file SubdetectorExtensionImpl.h.
Referenced by getZMin(), resetAll(), setZMin(), and SubdetectorExtensionImpl().
_zMax
double DD4hep::DDRec::SubdetectorExtensionImpl::_zMax protected
Definition at line 96 of file SubdetectorExtensionImpl.h.
Referenced by getZMax(), resetAll(), and setZMax().
_zMin
double DD4hep::DDRec::SubdetectorExtensionImpl::_zMin protected
Definition at line 94 of file SubdetectorExtensionImpl.h.
Referenced by getZMin(), resetAll(), and setZMin().
det
Geometry::DetElement DD4hep::DDRec::SubdetectorExtensionImpl::det protected
Definition at line 85 of file SubdetectorExtensionImpl.h.
Referenced by getNSides(), getRMax(), getRMin(), getZMax(), getZMin(), isBarrel(), isEndcap(), setDetectorElement(), and SubdetectorExtensionImpl().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Extensions/SubdetectorExtensionImpl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/SubdetectorExtensionImpl.cpp