DD4hep: DD4hep::Simulation::Geant4Output2ROOT Class Reference
DD4hep::Simulation::Geant4Output2ROOT Class Reference
DD4hep::Simulation components, classes and objects
Class to output Geant4 event data to ROOT files.
#include <Geant4Output2ROOT.h>
Public Member Functions
Geant4Output2ROOT (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4Output2ROOT ()
Default destructor.
TTree * section (const std::string &nam)
Create/access tree by name for non collection user data.
int fill (const std::string &nam, const ComponentCast &type, void *ptr)
Fill single EVENT branch entry (Geant4 collection data)
virtual void beginRun (const G4Run *run)
Callback to store the Geant4 run information.
virtual void saveCollection (OutputContext< G4Event > &ctxt, G4VHitsCollection *collection)
Callback to store each Geant4 hit collection.
virtual void saveEvent (OutputContext< G4Event > &ctxt)
Callback to store the Geant4 event.
virtual void commit (OutputContext< G4Event > &ctxt)
Commit data at end of filling procedure.
Public Member Functions inherited from DD4hep::Simulation::Geant4OutputAction
Geant4OutputAction (Geant4Context *c, const std::string &nam)
Standard constructor.
virtual ~Geant4OutputAction ()
Default destructor.
virtual void configureFiber (Geant4Context *ctxt)
Set or update client for the use in a new thread fiber.
virtual void begin (const G4Event *event)
begin-of-event callback
virtual void end (const G4Event *event)
End-of-event callback.
virtual void endRun (const G4Run *run)
Callback to store the Geant4 run information.
virtual void saveRun (const G4Run *run)
Callback to store the Geant4 event.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventAction
Geant4EventAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4EventAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Types
typedef std::map< std::string, TBranch * > Branches
typedef std::map< std::string, TTree * > Sections
Protected Attributes
Sections m_sections
Known file sections.
Branches m_branches
Branches in the event tree.
std::string m_section
name of the event tree
TFile * m_file
Reference to the ROOT file to open.
TTree * m_tree
Reference to the event data tree.
bool m_handleMCTruth
Flag if Monte-Carlo truth should be followed and checked.
Protected Attributes inherited from DD4hep::Simulation::Geant4OutputAction
std::string m_output
Property: "Output" output destination.
bool m_errorFatal
Property: "HandleErrorsAsFatal" Handle errors as fatal and rethrow eventual exceptions.
Geant4ParticleMap * m_truth
Reference to MC truth object.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4EventAction
typedef Geant4SharedEventAction shared_type
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Class to output Geant4 event data to ROOT files.
Author
M.Frank
Version
1.0
Definition at line 38 of file Geant4Output2ROOT.h.
Member Typedef Documentation
Branches
typedef std::map<std::string, TBranch*> DD4hep::Simulation::Geant4Output2ROOT::Branches protected
Definition at line 40 of file Geant4Output2ROOT.h.
Sections
typedef std::map<std::string, TTree*> DD4hep::Simulation::Geant4Output2ROOT::Sections protected
Definition at line 41 of file Geant4Output2ROOT.h.
Constructor & Destructor Documentation
Geant4Output2ROOT()
Geant4Output2ROOT::Geant4Output2ROOT (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 36 of file Geant4Output2ROOT.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_handleMCTruth, and m_section.
~Geant4Output2ROOT()
Geant4Output2ROOT::~Geant4Output2ROOT () virtual
Default destructor.
Definition at line 44 of file Geant4Output2ROOT.cpp.
References DD4hep::InstanceCount::decrement(), DD4hep::deletePtr(), m_file, and m_tree.
Member Function Documentation
beginRun()
void Geant4Output2ROOT::beginRun (const G4Run * run) virtual
Callback to store the Geant4 run information.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 68 of file Geant4Output2ROOT.cpp.
References DD4hep::Simulation::Geant4OutputAction::beginRun(), DD4hep::deletePtr(), m_file, DD4hep::Simulation::Geant4OutputAction::m_output, m_tree, and section().
commit()
void Geant4Output2ROOT::commit (OutputContext< G4Event > & ctxt) virtual
Commit data at end of filling procedure.
Fill NULL pointers to all branches, which have less entries than the Event branch
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 119 of file Geant4Output2ROOT.cpp.
References DD4hep::Simulation::Geant4OutputAction::commit(), m_file, and m_tree.
fill()
int Geant4Output2ROOT::fill (const std::string & nam, const ComponentCast & type, void * ptr)
Fill single EVENT branch entry (Geant4 collection data)
Definition at line 82 of file Geant4Output2ROOT.cpp.
References m_branches, m_file, m_tree, DD4hep::ComponentCast::type, and DD4hep::typeName().
Referenced by saveCollection(), and saveEvent().
saveCollection()
void Geant4Output2ROOT::saveCollection (OutputContext< G4Event > & ctxt, G4VHitsCollection * collection) virtual
Callback to store each Geant4 hit collection.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 159 of file Geant4Output2ROOT.cpp.
References DD4hep::ERROR, fill(), DD4hep::Simulation::Geant4HitCollection::getHitsUnchecked(), DD4hep::Simulation::Geant4HitCollection::GetSize(), DD4hep::Simulation::Geant4HitCollection::hit(), m_handleMCTruth, DD4hep::Simulation::Geant4OutputAction::m_truth, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4ParticleMap::particleID(), DD4hep::printout(), DD4hep::Simulation::Geant4HitData::MonteCarloContrib::trackID, DD4hep::Simulation::Geant4Tracker::Hit::truth, DD4hep::Simulation::Geant4Calorimeter::Hit::truth, and DD4hep::Simulation::Geant4HitCollection::vector_type().
saveEvent()
void Geant4Output2ROOT::saveEvent (OutputContext< G4Event > & ctxt) virtual
Callback to store the Geant4 event.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 143 of file Geant4Output2ROOT.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), fill(), and DD4hep::Simulation::Geant4ParticleMap::particles().
section()
TTree * Geant4Output2ROOT::section (const std::string & nam)
Create/access tree by name for non collection user data.
Create/access tree by name.
Definition at line 56 of file Geant4Output2ROOT.cpp.
References m_file, and m_sections.
Referenced by beginRun().
Member Data Documentation
m_branches
Branches DD4hep::Simulation::Geant4Output2ROOT::m_branches protected
Branches in the event tree.
Definition at line 45 of file Geant4Output2ROOT.h.
Referenced by fill().
m_file
TFile* DD4hep::Simulation::Geant4Output2ROOT::m_file protected
Reference to the ROOT file to open.
Definition at line 49 of file Geant4Output2ROOT.h.
Referenced by beginRun(), commit(), fill(), section(), and ~Geant4Output2ROOT().
m_handleMCTruth
bool DD4hep::Simulation::Geant4Output2ROOT::m_handleMCTruth protected
Flag if Monte-Carlo truth should be followed and checked.
Definition at line 53 of file Geant4Output2ROOT.h.
Referenced by Geant4Output2ROOT(), and saveCollection().
m_section
std::string DD4hep::Simulation::Geant4Output2ROOT::m_section protected
name of the event tree
Definition at line 47 of file Geant4Output2ROOT.h.
Referenced by Geant4Output2ROOT().
m_sections
Sections DD4hep::Simulation::Geant4Output2ROOT::m_sections protected
Known file sections.
Definition at line 43 of file Geant4Output2ROOT.h.
Referenced by section().
m_tree
TTree* DD4hep::Simulation::Geant4Output2ROOT::m_tree protected
Reference to the event data tree.
Definition at line 51 of file Geant4Output2ROOT.h.
Referenced by beginRun(), commit(), fill(), and ~Geant4Output2ROOT().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Output2ROOT.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Output2ROOT.cpp