DD4hep: DD4hep::Conditions::DependencyBuilder Class Reference
DD4hep::Conditions::DependencyBuilder Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Condition dependency builder.
#include <ConditionDerived.h>
Public Member Functions
DependencyBuilder (const ConditionKey &target, ConditionUpdateCall *call)
Initializing constructor.
virtual ~DependencyBuilder ()
Default destructor.
ConditionDependency * operator-> ()
Access underlying object directly.
void add (const ConditionKey &source)
Add a new dependency.
ConditionDependency * release ()
Release the created dependency and take ownership.
Protected Attributes
ConditionDependency * m_dependency
The created dependency.
Detailed Description
Condition dependency builder.
Author
M.Frank
Version
1.0
Definition at line 202 of file ConditionDerived.h.
Constructor & Destructor Documentation
DependencyBuilder()
DependencyBuilder::DependencyBuilder (const ConditionKey & target, ConditionUpdateCall * call)
Initializing constructor.
Definition at line 85 of file ConditionDerived.cpp.
~DependencyBuilder()
DependencyBuilder::~DependencyBuilder () virtual
Default destructor.
Definition at line 91 of file ConditionDerived.cpp.
References m_dependency, and DD4hep::releasePtr().
Member Function Documentation
add()
void DependencyBuilder::add (const ConditionKey & source)
Add a new dependency.
Definition at line 96 of file ConditionDerived.cpp.
References DD4hep::Conditions::ConditionDependency::dependencies, DD4hep::except(), and m_dependency.
operator->()
ConditionDependency* DD4hep::Conditions::DependencyBuilder::operator-> () inline
Access underlying object directly.
Definition at line 212 of file ConditionDerived.h.
release()
ConditionDependency * DependencyBuilder::release ()
Release the created dependency and take ownership.
Definition at line 105 of file ConditionDerived.cpp.
References DD4hep::except(), and m_dependency.
Member Data Documentation
m_dependency
ConditionDependency* DD4hep::Conditions::DependencyBuilder::m_dependency protected
The created dependency.
Definition at line 205 of file ConditionDerived.h.
Referenced by add(), release(), and ~DependencyBuilder().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ConditionDerived.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ConditionDerived.cpp