DD4hep: DD4hep: TiXmlComment Class Reference
TiXmlComment Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlComment ()
Constructs an empty comment.
TiXmlComment (const char *_value)
Construct a comment from text.
TiXmlComment (const TiXmlComment &)
void operator= (const TiXmlComment &base)
virtual ~TiXmlComment ()
virtual TiXmlNode * Clone () const
Returns a copy of this Comment.
virtual void Print (FILE *cfile, int depth) const
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *visitor) const
Protected Member Functions
void CopyTo (TiXmlComment *target) const
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
An XML comment.
See
See also:
http://www.grinninglizard.com/tinyxml
Definition at line 1280 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlComment::TiXmlComment () [inline]
Constructs an empty comment.
Definition at line 1283 of file tinyxml.h.
Referenced by Clone().
TiXmlComment::TiXmlComment (const char * _value) [inline]
Construct a comment from text.
Definition at line 1287 of file tinyxml.h.
References TiXmlNode::SetValue().
TiXmlComment::TiXmlComment (const TiXmlComment & copy)
Definition at line 1309 of file tinyxml_inl.h.
References CopyTo().
virtual TiXmlComment::~TiXmlComment () [inline, virtual]
Definition at line 1294 of file tinyxml.h.
Member Function Documentation
bool TiXmlComment::Accept (TiXmlVisitor * visitor) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
Definition at line 1339 of file tinyxml_inl.h.
References TiXmlVisitor::Visit().
TiXmlNode * TiXmlComment::Clone () const [virtual]
Returns a copy of this Comment.
Implements TiXmlNode.
Definition at line 1345 of file tinyxml_inl.h.
References CopyTo(), and TiXmlComment().
void TiXmlComment::CopyTo (TiXmlComment * target) const [protected]
Reimplemented from TiXmlNode.
Definition at line 1333 of file tinyxml_inl.h.
Referenced by Clone(), operator=(), and TiXmlComment().
void TiXmlComment::operator= (const TiXmlComment & base)
Reimplemented from TiXmlNode.
Definition at line 1315 of file tinyxml_inl.h.
References TiXmlNode::Clear(), and CopyTo().
const char * TiXmlComment::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements TiXmlBase.
Definition at line 1339 of file tinyxmlparser_inl.h.
References TiXmlParsingData::Cursor(), TiXmlNode::GetDocument(), TiXmlBase::location, TiXmlBase::ReadText(), TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlParsingData::Stamp(), TiXmlBase::StringEqual(), TiXmlBase::TIXML_ERROR_PARSING_COMMENT, and TiXmlNode::value.
void TiXmlComment::Print (FILE * cfile, int depth) const [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements TiXmlBase.
Definition at line 1322 of file tinyxml_inl.h.
References TiXmlNode::value.
virtual TiXmlComment* TiXmlComment::ToComment () [inline, virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1310 of file tinyxml.h.
virtual const TiXmlComment* TiXmlComment::ToComment () const [inline, virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1307 of file tinyxml.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h