DD4hep: DD4hep: DD4hep::Simulation::Geant4SharedSteppingAction Class Reference
DD4hep::Simulation::Geant4SharedSteppingAction Class Reference
[DD4hep::Simulation components, classes and objects]
Implementation of the Geant4 shared stepping action.
#include <Geant4SteppingAction.h>
Public Member Functions
Geant4SharedSteppingAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4SharedSteppingAction ()
Default destructor.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
virtual void use (Geant4SteppingAction *action)
Underlying object to be used during the execution of this thread.
virtual void operator() (const G4Step *step, G4SteppingManager *mgr)
User stepping callback.
Protected Attributes
Geant4SteppingAction * m_action
Reference to the shared action.
Detailed Description
Implementation of the Geant4 shared stepping action.
Wrapper to share single instances of stepping actions for multi-threaded purposes. The wrapper ensures the locking of the basic actions to avoid race conditions.
Shared action should be 'fast'. The global lock otherwise inhibits the efficient use of the multiple threads.
Author:
M.Frank
Version:
1.0
Definition at line 66 of file Geant4SteppingAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4SharedSteppingAction::Geant4SharedSteppingAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4SharedSteppingAction::~Geant4SharedSteppingAction () [virtual]
Default destructor.
Definition at line 53 of file Geant4SteppingAction.cpp.
References DD4hep::InstanceCount::decrement(), m_action, and DD4hep::releasePtr().
Member Function Documentation
void Geant4SharedSteppingAction::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 70 of file Geant4SteppingAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_action.
void Geant4SharedSteppingAction::operator() (const G4Step * step, G4SteppingManager * mgr) [virtual]
User stepping callback.
Reimplemented from DD4hep::Simulation::Geant4SteppingAction.
Definition at line 75 of file Geant4SteppingAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), and m_action.
void Geant4SharedSteppingAction::use (Geant4SteppingAction * action) [virtual]
Underlying object to be used during the execution of this thread.
Definition at line 59 of file Geant4SteppingAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::PropertyManager::adopt(), m_action, DD4hep::Simulation::Geant4Action::m_properties, and DD4hep::Simulation::Geant4Action::properties().
Member Data Documentation
Geant4SteppingAction* DD4hep::Simulation::Geant4SharedSteppingAction::m_action [protected]
Reference to the shared action.
Definition at line 69 of file Geant4SteppingAction.h.
Referenced by configureFiber(), operator()(), use(), and ~Geant4SharedSteppingAction().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SteppingAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SteppingAction.cpp