DD4hep: DD4hep::Conditions::Interna::ConditionContainer Class Reference
DD4hep::Conditions::Interna::ConditionContainer Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
The data class behind a conditions container handle.
#include <ConditionsInterna.h>
Public Types
typedef Condition::key_type key_type
Forward defintion of the key type.
typedef Condition::iov_type iov_type
Forward definition of the iov type.
typedef std::pair< key_type, std::string > key_value
Forward definition of the mapping type.
typedef std::map< key_type, key_value > Keys
Definition of the keys.
Public Member Functions
ConditionContainer (Geometry::DetElementObject *parent)
Standard constructor.
virtual ~ConditionContainer ()
Default destructor.
Condition get (const std::string &condition_key, const iov_type &iov)
Access to condition objects by key and IOV.
Condition get (key_type hash_key, const iov_type &iov)
Access to condition objects directly by their hash key.
Condition get (const std::string &condition_key, const UserPool &iov)
Access to condition objects. Only conditions in the pool are accessed.
Condition get (key_type condition_key, const UserPool &iov)
Access to condition objects. Only conditions in the pool are accessed.
void addKey (const std::string &key_value)
Add a new key to the conditions access map.
void addKey (const std::string &key_value, const std::string &data_value)
Add a new key to the conditions access map: Allow for alias if key_val != data_val.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
DetElement detector
The hosting detector element.
Keys keys
Known keys of conditions in this container.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Detailed Description
The data class behind a conditions container handle.
See ConditionsInterna.cpp for the implementation.
Author
M.Frank
Version
1.0
Definition at line 146 of file ConditionsInterna.h.
Member Typedef Documentation
iov_type
typedef Condition::iov_type DD4hep::Conditions::Interna::ConditionContainer::iov_type
Forward definition of the iov type.
Definition at line 151 of file ConditionsInterna.h.
key_type
typedef Condition::key_type DD4hep::Conditions::Interna::ConditionContainer::key_type
Forward defintion of the key type.
Definition at line 149 of file ConditionsInterna.h.
key_value
typedef std::pair<key_type, std::string> DD4hep::Conditions::Interna::ConditionContainer::key_value
Forward definition of the mapping type.
Definition at line 153 of file ConditionsInterna.h.
Keys
typedef std::map<key_type, key_value> DD4hep::Conditions::Interna::ConditionContainer::Keys
Definition of the keys.
Definition at line 155 of file ConditionsInterna.h.
Constructor & Destructor Documentation
ConditionContainer()
Interna::ConditionContainer::ConditionContainer (Geometry::DetElementObject * parent)
Standard constructor.
Definition at line 63 of file ConditionsInterna.cpp.
References DD4hep::InstanceCount::increment().
~ConditionContainer()
Interna::ConditionContainer::~ConditionContainer () virtual
Default destructor.
Definition at line 70 of file ConditionsInterna.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
addKey() [1/2]
void Interna::ConditionContainer::addKey (const std::string & key_value)
Add a new key to the conditions access map.
Definition at line 75 of file ConditionsInterna.cpp.
References DD4hep::except(), DD4hep::Simulation::hash(), DD4hep::Conditions::ConditionKey::hashCode(), and keys.
addKey() [2/2]
void Interna::ConditionContainer::addKey (const std::string & key_value, const std::string & data_value)
Add a new key to the conditions access map: Allow for alias if key_val != data_val.
Definition at line 83 of file ConditionsInterna.cpp.
References DD4hep::except(), DD4hep::Conditions::ConditionKey::hashCode(), and keys.
get() [1/4]
Condition Interna::ConditionContainer::get (const std::string & condition_key, const iov_type & iov)
Access to condition objects by key and IOV.
Access to condition objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 92 of file ConditionsInterna.cpp.
References detector, DD4hep::Conditions::ConditionsLoader::get(), DD4hep::Simulation::hash(), DD4hep::Conditions::ConditionKey::hashCode(), keys, and DD4hep::Geometry::DetElement::world().
Referenced by DD4hep::Conditions::Container::get().
get() [2/4]
Condition Interna::ConditionContainer::get (key_type hash_key, const iov_type & iov)
Access to condition objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 105 of file ConditionsInterna.cpp.
References detector, DD4hep::Conditions::ConditionsLoader::get(), keys, and DD4hep::Geometry::DetElement::world().
get() [3/4]
Condition Interna::ConditionContainer::get (const std::string & condition_key, const UserPool & iov)
Access to condition objects. Only conditions in the pool are accessed.
Access to condition objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 117 of file ConditionsInterna.cpp.
References detector, DD4hep::Conditions::ConditionsLoader::get(), DD4hep::Simulation::hash(), DD4hep::Conditions::ConditionKey::hashCode(), keys, and DD4hep::Geometry::DetElement::world().
get() [4/4]
Condition Interna::ConditionContainer::get (key_type condition_key, const UserPool & iov)
Access to condition objects. Only conditions in the pool are accessed.
Access to condition objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 130 of file ConditionsInterna.cpp.
References detector, DD4hep::Conditions::ConditionsLoader::get(), keys, and DD4hep::Geometry::DetElement::world().
Member Data Documentation
detector
DetElement DD4hep::Conditions::Interna::ConditionContainer::detector
The hosting detector element.
Definition at line 167 of file ConditionsInterna.h.
Referenced by get().
keys
Keys DD4hep::Conditions::Interna::ConditionContainer::keys
Known keys of conditions in this container.
Definition at line 183 of file ConditionsInterna.h.
Referenced by addKey(), get(), and DD4hep::Conditions::Container::numKeys().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/ConditionsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ConditionsInterna.cpp