DD4hep: DD4hep::Simulation::TypeName Class Reference
DD4hep::Simulation::TypeName Class Reference
DD4hep::Simulation components, classes and objects
Helper class to handle strings of the format "type/name".
#include <Geant4Action.h>
Public Member Functions
TypeName ()
Default constructor.
TypeName (const std::pair< std::string, std::string > &c)
TypeName (const std::string &typ, const std::string &nam)
Static Public Member Functions
static TypeName split (const std::string &type_name)
Split string pair according to default delimiter ('/')
static TypeName split (const std::string &type_name, const std::string &delim)
Split string pair according to custom delimiter.
Detailed Description
Helper class to handle strings of the format "type/name".
Author
M.Frank
Version
1.0
Definition at line 62 of file Geant4Action.h.
Constructor & Destructor Documentation
TypeName() [1/3]
DD4hep::Simulation::TypeName::TypeName () inline
Default constructor.
Definition at line 65 of file Geant4Action.h.
TypeName() [2/3]
DD4hep::Simulation::TypeName::TypeName (const std::pair< std::string, std::string > & c) inline
Definition at line 68 of file Geant4Action.h.
TypeName() [3/3]
DD4hep::Simulation::TypeName::TypeName (const std::string & typ, const std::string & nam) inline
Definition at line 71 of file Geant4Action.h.
References split().
Member Function Documentation
split() [1/2]
TypeName TypeName::split (const std::string & type_name) static
Split string pair according to default delimiter ('/')
Definition at line 43 of file Geant4Action.cpp.
References DD4hep::Simulation::Geant4Kernel::getOutputLevel(), DD4hep::INFO, DD4hep::Simulation::Geant4Context::kernel(), DD4hep::Simulation::Geant4Action::m_context, and DD4hep::printLevel().
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_convertSensitive(), DD4hep::Simulation::_create_share(), DD4hep::Simulation::_createAction(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Simulation::Geant4SteppingActionSequence::get(), DD4hep::Simulation::Geant4StackingActionSequence::get(), DD4hep::Simulation::Geant4RunActionSequence::get(), DD4hep::Simulation::Geant4GeneratorActionSequence::get(), DD4hep::Simulation::Geant4TrackingActionSequence::get(), DD4hep::Simulation::Geant4EventActionSequence::get(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::Simulation::Geant4InputAction::readParticles(), and TypeName().
split() [2/2]
TypeName TypeName::split (const std::string & type_name, const std::string & delim) static
Split string pair according to custom delimiter.
Definition at line 33 of file Geant4Action.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Action.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Action.cpp