DD4hep: DD4hep: DD4hep::dd4hep_file_sink< T > Class Template Reference
DD4hep::dd4hep_file_sink< T > Class Template Reference
[DD4hep classes and objects]
DD4hep file sink extension to boost::iostreams.
#include <IoStreams.h>
Classes
struct category
Public Types
typedef dd4hep_file< T > descriptor
typedef descriptor::handle_type handle_type
typedef descriptor::char_type char_type
Public Member Functions
dd4hep_file_sink ()
Default constructor.
dd4hep_file_sink (const dd4hep_file_sink< T > &other)
Copy constructor.
dd4hep_file_sink (handle_type fd, dd4hep_file_flags flags)
Constructors taking file desciptors.
dd4hep_file_sink (const std::string &path, BOOST_IOS::openmode mode=BOOST_IOS::out)
Constructor taking a std::string.
dd4hep_file_sink (const char *path, BOOST_IOS::openmode mode=BOOST_IOS::out)
Constructor taking a C-style string.
template<typename Path >
dd4hep_file_sink (const Path &path, BOOST_IOS::openmode mode=BOOST_IOS::out)
Constructor taking a Boost.Filesystem path.
void open (handle_type fd, dd4hep_file_flags flags)
open overloads taking file descriptors
void open (const std::string &path, BOOST_IOS::openmode mode=BOOST_IOS::out)
open overload taking a std::string
void open (const char *path, BOOST_IOS::openmode mode=BOOST_IOS::out)
open overload taking C-style string
template<typename Path >
void open (const Path &path, BOOST_IOS::openmode mode=BOOST_IOS::out)
open overload taking a Boost.Filesystem path
Detailed Description
template<typename T>
class DD4hep::dd4hep_file_sink< T >
DD4hep file sink extension to boost::iostreams.
Basic data sink implementation. Please see boost::iostreams for details. This got inspired by boost::iostreams::device::file_descriptor
The final aim is to hide all this behind a TFile object, so that we get the entire network file handling for free!
Note: Credits go to a large extend to the authors of boost::iostreams. Without their work I could not have done this!
Author:
M.Frank
Version:
1.0
See also:
http://www.boost.org/libs/iostreams for further documentation.
Definition at line 192 of file IoStreams.h.
Member Typedef Documentation
template<typename T> typedef descriptor::char_type DD4hep::dd4hep_file_sink< T >::char_type
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 199 of file IoStreams.h.
template<typename T> typedef dd4hep_file<T> DD4hep::dd4hep_file_sink< T >::descriptor
Definition at line 194 of file IoStreams.h.
template<typename T> typedef descriptor::handle_type DD4hep::dd4hep_file_sink< T >::handle_type
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 198 of file IoStreams.h.
Constructor & Destructor Documentation
template<typename T> DD4hep::dd4hep_file_sink< T >::dd4hep_file_sink () [inline]
Default constructor.
Definition at line 207 of file IoStreams.h.
template<typename T> DD4hep::dd4hep_file_sink< T >::dd4hep_file_sink (const dd4hep_file_sink< T > & other) [inline]
Copy constructor.
Definition at line 210 of file IoStreams.h.
template<typename T> DD4hep::dd4hep_file_sink< T >::dd4hep_file_sink (handle_type fd, dd4hep_file_flags flags) [inline, explicit]
Constructors taking file desciptors.
Definition at line 214 of file IoStreams.h.
template<typename T> DD4hep::dd4hep_file_sink< T >::dd4hep_file_sink (const std::string & path, BOOST_IOS::openmode mode = BOOST_IOS::out) [inline, explicit]
Constructor taking a std::string.
Definition at line 218 of file IoStreams.h.
template<typename T> DD4hep::dd4hep_file_sink< T >::dd4hep_file_sink (const char * path, BOOST_IOS::openmode mode = BOOST_IOS::out) [inline, explicit]
Constructor taking a C-style string.
Definition at line 222 of file IoStreams.h.
template<typename T> template<typename Path > DD4hep::dd4hep_file_sink< T >::dd4hep_file_sink (const Path & path, BOOST_IOS::openmode mode = BOOST_IOS::out) [inline, explicit]
Constructor taking a Boost.Filesystem path.
Definition at line 227 of file IoStreams.h.
Member Function Documentation
template<typename T> template<typename Path > void DD4hep::dd4hep_file_sink< T >::open (const Path & path, BOOST_IOS::openmode mode = BOOST_IOS::out) [inline]
open overload taking a Boost.Filesystem path
Definition at line 243 of file IoStreams.h.
References DD4hep::dd4hep_file_sink< T >::open().
Referenced by DD4hep::dd4hep_file_sink< T >::open().
template<typename T> void DD4hep::dd4hep_file_sink< T >::open (const char * path, BOOST_IOS::openmode mode = BOOST_IOS::out) [inline]
open overload taking C-style string
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 239 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::open().
template<typename T> void DD4hep::dd4hep_file_sink< T >::open (const std::string & path, BOOST_IOS::openmode mode = BOOST_IOS::out) [inline]
open overload taking a std::string
Definition at line 235 of file IoStreams.h.
References DD4hep::dd4hep_file_sink< T >::open().
Referenced by DD4hep::dd4hep_file_sink< T >::open().
template<typename T> void DD4hep::dd4hep_file_sink< T >::open (handle_type fd, dd4hep_file_flags flags) [inline]
open overloads taking file descriptors
Reimplemented from DD4hep::dd4hep_file< T >.
Definition at line 231 of file IoStreams.h.
References DD4hep::dd4hep_file< T >::open().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/IoStreams.h