DD4hep: DD4hep::Conditions::DetConditions Class Reference
DD4hep::Conditions::DetConditions Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing the access to DetElement dependent conditions.
#include <DetConditions.h>
Public Types
typedef Geometry::DetElementObject Object
Internal object type.
typedef Handle< Object > RefObject
Definition of the base handle type.
Public Types inherited from DD4hep::Handle< Geometry::DetElementObject >
typedef Geometry::DetElementObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
DetConditions ()
Default constructor.
DetConditions (Object *object_ptr)
Constructor to hold handled object.
template<typename Q >
DetConditions (const Handle< Q > &e)
Templated constructor for handle conversions.
DetConditions (const DetConditions &e)
Constructor to copy handle.
DetConditions (const Geometry::DetElement &e)
Constructor to copy handle.
Object & _data () const
Additional data accessor.
DetConditions & operator= (const DetConditions &e)
Assignment operator.
bool hasConditions () const
Check if conditions are at all present.
Container conditions () const
Access to the conditions information.
Condition get (const std::string &key, const UserPool &pool)
Access to condition objects from a given pool.
Condition get (Condition::key_type key, const UserPool &pool)
Access to condition objects from a given pool.
Condition get (const std::string &key, const Condition::iov_type &iov)
Access to condition objects. Only conditions in the pool are accessed.
Condition get (Condition::key_type key, const Condition::iov_type &iov)
Access to condition objects. Only conditions in the pool are accessed.
Public Member Functions inherited from DD4hep::Handle< Geometry::DetElementObject >
Handle ()
Defaulot constructor.
Handle (Geometry::DetElementObject *e)
Initializing constructor from pointer.
Handle (const Handle< Geometry::DetElementObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< Geometry::DetElementObject > & operator= (const Handle< Geometry::DetElementObject > &e)=default
Assignment operator.
bool operator== (const Handle< Geometry::DetElementObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< Geometry::DetElementObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< Geometry::DetElementObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< Geometry::DetElementObject > & clear ()
Release the object held by the handle.
Geometry::DetElementObject * operator-> () const
Access the held object using the -> operator.
operator Geometry::DetElementObject & () const
Automatic type conversion to an object references.
Geometry::DetElementObject & operator* () const
Access the held object using the * operator.
Geometry::DetElementObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
Geometry::DetElementObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< Geometry::DetElementObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< Geometry::DetElementObject >
Geometry::DetElementObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing the access to DetElement dependent conditions.
Author
M.Frank
Version
1.0
Definition at line 43 of file DetConditions.h.
Member Typedef Documentation
Object
typedef Geometry::DetElementObject DD4hep::Conditions::DetConditions::Object
Internal object type.
Definition at line 46 of file DetConditions.h.
RefObject
typedef Handle<Object> DD4hep::Conditions::DetConditions::RefObject
Definition of the base handle type.
Definition at line 48 of file DetConditions.h.
Constructor & Destructor Documentation
DetConditions() [1/5]
DD4hep::Conditions::DetConditions::DetConditions () inline
Default constructor.
Definition at line 53 of file DetConditions.h.
DetConditions() [2/5]
DD4hep::Conditions::DetConditions::DetConditions (Object * object_ptr) inline
Constructor to hold handled object.
Definition at line 56 of file DetConditions.h.
DetConditions() [3/5]
template<typename Q > DD4hep::Conditions::DetConditions::DetConditions (const Handle< Q > & e) inline
Templated constructor for handle conversions.
Definition at line 59 of file DetConditions.h.
DetConditions() [4/5]
DD4hep::Conditions::DetConditions::DetConditions (const DetConditions & e) inline
Constructor to copy handle.
Definition at line 62 of file DetConditions.h.
DetConditions() [5/5]
DD4hep::Conditions::DetConditions::DetConditions (const Geometry::DetElement & e) inline
Constructor to copy handle.
Definition at line 65 of file DetConditions.h.
References _data(), and e.
Member Function Documentation
_data()
Object& DD4hep::Conditions::DetConditions::_data () const inline
Additional data accessor.
Definition at line 74 of file DetConditions.h.
conditions()
Container DetConditions::conditions () const
Access to the conditions information.
Definition at line 35 of file DetConditions.cpp.
References DD4hep::Handle< T >::assign(), DD4hep::Geometry::DetElementObject::assign_conditions(), DD4hep::Geometry::DetElementObject::conditions, and DD4hep::Handle< T >::isValid().
Referenced by DD4hep::Conditions::Test::TestEnv::dump_detector_element().
get() [1/4]
Condition DetConditions::get (const std::string & key, const UserPool & pool)
Access to condition objects from a given pool.
Access to condition objects from a given pool. Only conditions in the pool are accessed.
Definition at line 53 of file DetConditions.cpp.
References DD4hep::Conditions::Condition::get().
get() [2/4]
Condition DetConditions::get (Condition::key_type key, const UserPool & pool)
Access to condition objects from a given pool.
Access to condition objects from a given pool. Only conditions in the pool are accessed.
Definition at line 58 of file DetConditions.cpp.
References DD4hep::Conditions::Condition::get().
get() [3/4]
Condition DetConditions::get (const std::string & key, const Condition::iov_type & iov)
Access to condition objects. Only conditions in the pool are accessed.
Access to condition objects.
Definition at line 43 of file DetConditions.cpp.
References DD4hep::Conditions::Condition::get().
get() [4/4]
Condition DetConditions::get (Condition::key_type key, const Condition::iov_type & iov)
Access to condition objects. Only conditions in the pool are accessed.
Access to condition objects.
Definition at line 48 of file DetConditions.cpp.
References DD4hep::Conditions::Condition::get().
hasConditions()
bool DetConditions::hasConditions () const
Check if conditions are at all present.
Definition at line 27 of file DetConditions.cpp.
References DD4hep::Geometry::DetElementObject::conditions, and DD4hep::Handle< T >::isValid().
operator=()
DetConditions& DD4hep::Conditions::DetConditions::operator= (const DetConditions & e) inline
Assignment operator.
Definition at line 78 of file DetConditions.h.
References DD4hep::Handle< T >::m_element.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/DetConditions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetConditions.cpp