DD4hep: DD4hep::Simulation::Geant4TouchableHandler Class Reference
DD4hep::Simulation::Geant4TouchableHandler Class Reference
DD4hep::Simulation components, classes and objects
Helper class to ease the extraction of information from a G4Touchable object.
#include <Geant4TouchableHandler.h>
Public Types
typedef std::vector< const G4VPhysicalVolume * > Geant4PlacementPath
Public Member Functions
Geant4TouchableHandler (const G4VTouchable *t)
Default constructor.
Geant4TouchableHandler (const G4Step *step)
Default constructor. Takes the step's pre-touchable.
Geant4TouchableHandler (const G4Step *step, bool use_post_step_point)
Default constructor. Takes the step's pre-touchable.
Geant4PlacementPath placementPath (bool exception=false) const
Helper: Generate placement path from touchable object.
std::string path () const
Helper: Access the placement path of a Geant4 touchable object as a string.
int depth () const
Touchable history depth.
Public Attributes
const G4VTouchable * touchable
Data member of the helper objects.
Detailed Description
Helper class to ease the extraction of information from a G4Touchable object.
Tiny helper/utility class to easily access Geant4 touchable information. Born by lazyness: Avoid typing millions of statements!
Author
M.Frank
Version
1.0
Definition at line 44 of file Geant4TouchableHandler.h.
Member Typedef Documentation
Geant4PlacementPath
typedef std::vector<const G4VPhysicalVolume*> DD4hep::Simulation::Geant4TouchableHandler::Geant4PlacementPath
Definition at line 47 of file Geant4TouchableHandler.h.
Constructor & Destructor Documentation
Geant4TouchableHandler() [1/3]
DD4hep::Simulation::Geant4TouchableHandler::Geant4TouchableHandler (const G4VTouchable * t) inline
Default constructor.
Definition at line 52 of file Geant4TouchableHandler.h.
References depth(), path(), and placementPath().
Geant4TouchableHandler() [2/3]
Geant4TouchableHandler::Geant4TouchableHandler (const G4Step * step)
Default constructor. Takes the step's pre-touchable.
Definition at line 34 of file Geant4TouchableHandler.cpp.
References touchable.
Geant4TouchableHandler() [3/3]
Geant4TouchableHandler::Geant4TouchableHandler (const G4Step * step, bool use_post_step_point)
Default constructor. Takes the step's pre-touchable.
Definition at line 28 of file Geant4TouchableHandler.cpp.
References touchable.
Member Function Documentation
depth()
int Geant4TouchableHandler::depth () const
Touchable history depth.
Definition at line 39 of file Geant4TouchableHandler.cpp.
References touchable.
Referenced by Geant4TouchableHandler().
path()
std::string Geant4TouchableHandler::path () const
Helper: Access the placement path of a Geant4 touchable object as a string.
Definition at line 62 of file Geant4TouchableHandler.cpp.
References placementPath(), and DD4hep::Simulation::Geant4GeometryMaps::placementPath().
Referenced by Geant4TouchableHandler(), DD4hep::Simulation::Geant4MaterialScanner::operator()(), DD4hep::Simulation::Geant4EscapeCounter::process(), and DD4hep::Simulation::Geant4SensitiveAction< T >::process().
placementPath()
Geant4TouchableHandler::Geant4PlacementPath Geant4TouchableHandler::placementPath (bool exception = false) const
Helper: Generate placement path from touchable object.
Definition at line 44 of file Geant4TouchableHandler.cpp.
References touchable.
Referenced by Geant4TouchableHandler(), path(), DD4hep::Simulation::Geant4VolumeManager::placementPath(), and DD4hep::Simulation::Geant4VolumeManager::volumeID().
Member Data Documentation
touchable
const G4VTouchable* DD4hep::Simulation::Geant4TouchableHandler::touchable
Data member of the helper objects.
Definition at line 49 of file Geant4TouchableHandler.h.
Referenced by depth(), Geant4TouchableHandler(), and placementPath().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TouchableHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TouchableHandler.cpp