DD4hep: DD4hep: DD4hep::XML::XmlString Class Reference
DD4hep::XML::XmlString Class Reference
[DD4hep::XML classes and objects]
Definition of the XmlString class.
#include <XMLElements.h>
Static Public Member Functions
static XmlChar * replicate (const XmlChar *c)
Replicate string: internally allocates new string, which must be free'ed with release.
static XmlChar * transcode (const char *c)
Transcode string.
static void release (char **p)
Release string.
static size_t length (const char *s)
String length in native representation.
static size_t length (const XmlChar *s)
String length in native representation.
static char * transcode (const XmlChar *c)
Transcoded string from unicode to ascii.
static void release (XmlChar **p)
Release string.
Detailed Description
Definition of the XmlString class.
Definition of the XmlString class. Unly used to have the same code base as for XercesC, where this class does the unicode translations and en/decoding.
Author:
M.Frank
Version:
1.0
Definition at line 53 of file XMLElements.h.
Member Function Documentation
size_t DD4hep::XML::XmlString::length (const XmlChar * s) [static]
String length in native representation.
Definition at line 146 of file XMLElements.cpp.
size_t DD4hep::XML::XmlString::length (const char * s) [static]
String length in native representation.
Definition at line 143 of file XMLElements.cpp.
void DD4hep::XML::XmlString::release (XmlChar ** p) [static]
Release string.
Definition at line 137 of file XMLElements.cpp.
References release().
void DD4hep::XML::XmlString::release (char ** p) [static]
Release string.
Definition at line 140 of file XMLElements.cpp.
Referenced by DD4hep::XML::_toString(), DD4hep::XML::Tag_t::operator=(), DD4hep::XML::Strng_t::operator=(), and release().
XmlChar * DD4hep::XML::XmlString::replicate (const XmlChar * c) [static]
Replicate string: internally allocates new string, which must be free'ed with release.
Definition at line 128 of file XMLElements.cpp.
Referenced by DD4hep::XML::Strng_t::operator=().
char * DD4hep::XML::XmlString::transcode (const XmlChar * c) [static]
Transcoded string from unicode to ascii.
Definition at line 131 of file XMLElements.cpp.
References transcode().
XmlChar * DD4hep::XML::XmlString::transcode (const char * c) [static]
Transcode string.
Definition at line 134 of file XMLElements.cpp.
Referenced by DD4hep::XML::_toString(), DD4hep::XML::Tag_t::operator=(), DD4hep::XML::Strng_t::operator=(), and transcode().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp