DD4hep: DD4hep: DD4hep::Simulation::Geant4DefaultRangeCut Class Reference
DD4hep::Simulation::Geant4DefaultRangeCut Class Reference
[DD4hep::Simulation components, classes and objects]
Geant4 physics list action to set global range cuts for secondary productions.
Public Member Functions
Geant4DefaultRangeCut (Geant4Context *ctxt, const std::string &nam)
virtual ~Geant4DefaultRangeCut ()
virtual void constructProcesses (G4VUserPhysicsList *physics_list)
Callback to construct processes (uses the G4 particle table).
Private Attributes
double m_rangeCut
global range cut for secondary productions
Detailed Description
Geant4 physics list action to set global range cuts for secondary productions.
Author:
M.Frank
Version:
1.0
Definition at line 50 of file Geant4DefaultRangeCut.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4DefaultRangeCut::Geant4DefaultRangeCut (Geant4Context * ctxt, const std::string & nam) [inline]
Definition at line 52 of file Geant4DefaultRangeCut.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), and m_rangeCut.
virtual DD4hep::Simulation::Geant4DefaultRangeCut::~Geant4DefaultRangeCut () [inline, virtual]
Definition at line 57 of file Geant4DefaultRangeCut.cpp.
Member Function Documentation
virtual void DD4hep::Simulation::Geant4DefaultRangeCut::constructProcesses (G4VUserPhysicsList * physics_list) [inline, virtual]
Callback to construct processes (uses the G4 particle table).
Reimplemented from DD4hep::Simulation::Geant4PhysicsList.
Definition at line 60 of file Geant4DefaultRangeCut.cpp.
References DD4hep::DEBUG, DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Action::info(), m_rangeCut, dd4hep::mm, and DD4hep::printLevel().
Member Data Documentation
double DD4hep::Simulation::Geant4DefaultRangeCut::m_rangeCut [private]
global range cut for secondary productions
Definition at line 73 of file Geant4DefaultRangeCut.cpp.
Referenced by constructProcesses(), and Geant4DefaultRangeCut().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4DefaultRangeCut.cpp