DD4hep: DD4hep::Simulation::Geant4EventReaderHepMC Class Reference
DD4hep::Simulation::Geant4EventReaderHepMC Class Reference
DD4hep::Simulation components, classes and objects
Class to populate Geant4 primaries from StdHep files.
Public Member Functions
Geant4EventReaderHepMC (const std::string &nam)
Initializing constructor.
virtual ~Geant4EventReaderHepMC ()
Default destructor.
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, std::vector< Particle *> &particles)
Read an event and fill a vector of MCParticles.
virtual EventReaderStatus moveToEvent (int event_number)
skipEvents if required
virtual EventReaderStatus skipEvent ()
Skip event. To be implemented for sequential sources.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventReader
Geant4EventReader (const std::string &nam)
Initializing constructor.
virtual ~Geant4EventReader ()
Default destructor.
const std::string & name () const
File name.
bool hasDirectAccess () const
Flag if direct event access (by event sequence number) is supported (Default: false)
int currentEventNumber () const
return current Event Number
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, Particles &particles)=0
Read an event and fill a vector of MCParticles.
Protected Attributes
in_stream m_input
EventStream * m_events
Protected Attributes inherited from DD4hep::Simulation::Geant4EventReader
std::string m_name
File name to be opened and read.
bool m_directAccess
Flag if direct event access is supported. To be explicitly set by subclass constructors.
int m_currEvent
Current event number.
Private Types
typedef boost::iostreams::stream< dd4hep_file_source< int > > in_stream
typedef HepMC::EventStream EventStream
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4EventReader
enum EventReaderStatus {
EVENT_READER_ERROR =0, EVENT_READER_OK =1, EVENT_READER_NO_DIRECT =2, EVENT_READER_NO_PRIMARIES =4,
EVENT_READER_NO_FACTORY =6, EVENT_READER_IO_ERROR =8
}
Status codes of the event reader object. Anything with NOT low-bit set is an error.
typedef Geant4Vertex Vertex
typedef Geant4Particle Particle
typedef std::vector< Particle * > Particles
Detailed Description
Class to populate Geant4 primaries from StdHep files.
Class to populate Geant4 primary particles and vertices from a file in HepMC format (ASCII)
Author
P.Kostka (main author)
M.Frank (code reshuffeling into new DDG4 scheme)
Version
1.0
Definition at line 38 of file Geant4EventReaderHepMC.cpp.
Member Typedef Documentation
EventStream
typedef HepMC::EventStream DD4hep::Simulation::Geant4EventReaderHepMC::EventStream private
Definition at line 41 of file Geant4EventReaderHepMC.cpp.
in_stream
typedef boost::iostreams::stream<dd4hep_file_source<int> > DD4hep::Simulation::Geant4EventReaderHepMC::in_stream private
Definition at line 39 of file Geant4EventReaderHepMC.cpp.
Constructor & Destructor Documentation
Geant4EventReaderHepMC()
Geant4EventReaderHepMC::Geant4EventReaderHepMC (const std::string & nam) explicit
Initializing constructor.
Definition at line 167 of file Geant4EventReaderHepMC.cpp.
References m_events, and m_input.
~Geant4EventReaderHepMC()
Geant4EventReaderHepMC::~Geant4EventReaderHepMC () virtual
Default destructor.
Definition at line 181 of file Geant4EventReaderHepMC.cpp.
References m_events, and m_input.
Member Function Documentation
moveToEvent()
Geant4EventReader::EventReaderStatus Geant4EventReaderHepMC::moveToEvent (int event_number) virtual
skipEvents if required
Reimplemented from DD4hep::Simulation::Geant4EventReader.
Definition at line 189 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_ERROR, DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::INFO, DD4hep::Simulation::Geant4EventReader::m_currEvent, m_events, DD4hep::printout(), and DD4hep::Simulation::HepMC::EventStream::read().
readParticles()
Geant4EventReaderHepMC::EventReaderStatus Geant4EventReaderHepMC::readParticles (int event_number, Vertex & primary_vertex, std::vector< Particle *> & particles) virtual
Read an event and fill a vector of MCParticles.
Definition at line 204 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::EventStream::clear(), DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4EventReader::EVENT_READER_IO_ERROR, DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4EventReader::m_currEvent, m_events, DD4hep::Simulation::Geant4EventReader::m_name, dd4hep::MeV, dd4hep::ns, DD4hep::Simulation::HepMC::EventStream::ok(), DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::HepMC::EventStream::particles(), DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::printout(), DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::Simulation::HepMC::EventStream::read(), DD4hep::reference2nd(), DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::time, DD4hep::VERBOSE, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, DD4hep::Simulation::Geant4Particle::vsz, DD4hep::Simulation::Geant4Vertex::x, DD4hep::Simulation::Geant4Vertex::y, and DD4hep::Simulation::Geant4Vertex::z.
skipEvent()
virtual EventReaderStatus DD4hep::Simulation::Geant4EventReaderHepMC::skipEvent () inline virtual
Skip event. To be implemented for sequential sources.
Reimplemented from DD4hep::Simulation::Geant4EventReader.
Definition at line 55 of file Geant4EventReaderHepMC.cpp.
Member Data Documentation
m_events
EventStream* DD4hep::Simulation::Geant4EventReaderHepMC::m_events protected
Definition at line 44 of file Geant4EventReaderHepMC.cpp.
Referenced by Geant4EventReaderHepMC(), moveToEvent(), readParticles(), and ~Geant4EventReaderHepMC().
m_input
in_stream DD4hep::Simulation::Geant4EventReaderHepMC::m_input protected
Definition at line 43 of file Geant4EventReaderHepMC.cpp.
Referenced by Geant4EventReaderHepMC(), and ~Geant4EventReaderHepMC().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4EventReaderHepMC.cpp