DD4hep: DD4hep::InstanceCount::Counter Class Reference
DD4hep::InstanceCount::Counter Class Reference
DD4hep classes and objects
Internal class to could object constructions and destructions.
#include <InstanceCount.h>
Public Member Functions
Counter ()
Default constructor.
Counter (const Counter &c)
Copy constructor.
~Counter ()
Destructor.
void increment ()
Increment counter.
void decrement ()
Decrement counter.
counter_t value () const
Access counter value.
counter_t total () const
Access counter value.
counter_t maximum () const
Access maximum counter value.
Private Attributes
counter_t m_count
Reference counter value.
counter_t m_tot
Increment counter value.
counter_t m_max
Maximum number of simultaneous instances.
Detailed Description
Internal class to could object constructions and destructions.
Small class to enable object construction/destruction tracing.
Author
M.Frank
Version
1.0
Definition at line 47 of file InstanceCount.h.
Constructor & Destructor Documentation
Counter() [1/2]
DD4hep::InstanceCount::Counter::Counter () inline
Default constructor.
Definition at line 57 of file InstanceCount.h.
Counter() [2/2]
DD4hep::InstanceCount::Counter::Counter (const Counter & c) inline
Copy constructor.
Definition at line 61 of file InstanceCount.h.
~Counter()
DD4hep::InstanceCount::Counter::~Counter () inline
Destructor.
Definition at line 65 of file InstanceCount.h.
Member Function Documentation
decrement()
void DD4hep::InstanceCount::Counter::decrement () inline
Decrement counter.
Definition at line 74 of file InstanceCount.h.
References m_count.
Referenced by DD4hep::InstanceCount::decrement(), DD4hep::InstanceCount::get(), and DD4hep::InstanceCount::~InstanceCount().
increment()
void DD4hep::InstanceCount::Counter::increment () inline
Increment counter.
Definition at line 68 of file InstanceCount.h.
References m_count, and m_tot.
Referenced by DD4hep::InstanceCount::get(), DD4hep::InstanceCount::increment(), and DD4hep::InstanceCount::InstanceCount().
maximum()
counter_t DD4hep::InstanceCount::Counter::maximum () const inline
Access maximum counter value.
Definition at line 86 of file InstanceCount.h.
References DD4hep::InstanceCount::getCounter(), DD4hep::InstanceCount::InstanceCount(), m_max, and DD4hep::InstanceCount::~InstanceCount().
total()
counter_t DD4hep::InstanceCount::Counter::total () const inline
Access counter value.
Definition at line 82 of file InstanceCount.h.
References m_tot.
value()
counter_t DD4hep::InstanceCount::Counter::value () const inline
Access counter value.
Definition at line 78 of file InstanceCount.h.
References m_count.
Referenced by DD4hep::InstanceCount::get(), and DD4hep::InstanceCount::~InstanceCount().
Member Data Documentation
m_count
counter_t DD4hep::InstanceCount::Counter::m_count private
Reference counter value.
Definition at line 50 of file InstanceCount.h.
Referenced by decrement(), increment(), and value().
m_max
counter_t DD4hep::InstanceCount::Counter::m_max private
Maximum number of simultaneous instances.
Definition at line 54 of file InstanceCount.h.
Referenced by maximum().
m_tot
counter_t DD4hep::InstanceCount::Counter::m_tot private
Increment counter value.
Definition at line 52 of file InstanceCount.h.
Referenced by increment(), and total().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/InstanceCount.h