DD4hep: DD4hep: DD4hep::PropertyConfigurable Class Reference
DD4hep::PropertyConfigurable Class Reference
Property object as base class for all objects supporting properties.
#include <ComponentProperties.h>
Public Member Functions
PropertyConfigurable ()
Standard constructor.
virtual ~PropertyConfigurable ()
Default destructor.
PropertyManager & properties ()
Access to the properties of the object.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
template<typename T >
void declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
void declareProperty (const char *nam, T &val)
Declare property.
Protected Attributes
PropertyManager m_properties
Property pool.
Detailed Description
Property object as base class for all objects supporting properties.
Author:
M.Frank
Version:
1.0
Definition at line 238 of file ComponentProperties.h.
Constructor & Destructor Documentation
PropertyConfigurable::PropertyConfigurable ()
Standard constructor.
Standard PropertyConfigurable constructor.
Definition at line 220 of file ComponentProperties.cpp.
PropertyConfigurable::~PropertyConfigurable () [virtual]
Default destructor.
Default PropertyConfigurable destructor.
Definition at line 224 of file ComponentProperties.cpp.
Member Function Documentation
template<typename T > void DD4hep::PropertyConfigurable::declareProperty (const char * nam, T & val) [inline]
Declare property.
Definition at line 270 of file ComponentProperties.h.
References DD4hep::PropertyManager::add(), and m_properties.
template<typename T > void DD4hep::PropertyConfigurable::declareProperty (const std::string & nam, T & val) [inline]
Declare property.
Definition at line 264 of file ComponentProperties.h.
References DD4hep::PropertyManager::add(), and m_properties.
Referenced by DD4hep::Conditions::ConditionsManagerObject::ConditionsManagerObject().
bool DD4hep::PropertyConfigurable::hasProperty (const std::string & name) const
Check property for existence.
PropertyManager& DD4hep::PropertyConfigurable::properties () [inline]
Access to the properties of the object.
Definition at line 249 of file ComponentProperties.h.
References m_properties.
Referenced by DD4hep::Conditions::ConditionsManager::operator[](), and DD4hep::Conditions::ConditionsManager::properties().
Property& DD4hep::PropertyConfigurable::property (const std::string & name)
Access single property.
Member Data Documentation
PropertyManager DD4hep::PropertyConfigurable::m_properties [protected]
Property pool.
Definition at line 241 of file ComponentProperties.h.
Referenced by declareProperty(), and properties().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ComponentProperties.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ComponentProperties.cpp