DD4hep: DD4hep::IOVType Class Reference
DD4hep::IOVType Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Class describing the interval of validty type.
#include <IOV.h>
Public Types
enum { UNKNOWN_IOV = ~0x0 }
Public Member Functions
IOVType ()
Standard Constructor.
~IOVType ()=default
Standard Destructor.
IOVType (const IOVType &copy)
Copy constructor.
IOVType & operator= (const IOVType &copy)
Assignment operator.
std::string str () const
Conversion to string.
Public Attributes
enum DD4hep::IOVType:: { ... } _IOVTypes
unsigned int type
integer identifier ised internally
std::string name
String name.
Detailed Description
Class describing the interval of validty type.
Author
M.Frank
Version
1.0
Definition at line 33 of file IOV.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
UNKNOWN_IOV
Definition at line 35 of file IOV.h.
Constructor & Destructor Documentation
IOVType() [1/2]
DD4hep::IOVType::IOVType () inline
Standard Constructor.
Definition at line 41 of file IOV.h.
References ~IOVType().
~IOVType()
DD4hep::IOVType::~IOVType () default
Standard Destructor.
Referenced by IOVType().
IOVType() [2/2]
DD4hep::IOVType::IOVType (const IOVType & copy) inline
Copy constructor.
Definition at line 45 of file IOV.h.
References DD4hep::Alignments::AlignmentTools::copy(), operator=(), and str().
Member Function Documentation
operator=()
IOVType & IOVType::operator= (const IOVType & copy)
Assignment operator.
Definition at line 27 of file IOV.cpp.
References name, and type.
Referenced by IOVType().
str()
std::string IOVType::str () const
Conversion to string.
Definition at line 36 of file IOV.cpp.
Referenced by DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), and IOVType().
Member Data Documentation
_IOVTypes
enum { ... } DD4hep::IOVType::_IOVTypes
name
std::string DD4hep::IOVType::name
String name.
Definition at line 39 of file IOV.h.
Referenced by operator=(), DD4hep::Conditions::ConditionsManagerObject::registerIOVType(), and DD4hep::IOV::str().
type
unsigned int DD4hep::IOVType::type
integer identifier ised internally
Definition at line 37 of file IOV.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__get_checked_pool(), DD4hep::Conditions::ConditionsManagerObject::clean(), DD4hep::IOV::contains(), DD4hep::IOV::IOV(), DD4hep::Conditions::ConditionsManager::iovPool(), DD4hep::Conditions::ConditionsManagerObject::iovType(), operator=(), DD4hep::Conditions::ConditionsManagerObject::pushUpdates(), DD4hep::Conditions::Condition::rebind(), DD4hep::Conditions::ConditionsManagerObject::registerIOV(), DD4hep::Conditions::ConditionsManagerObject::registerIOVType(), DD4hep::IOV::same_type(), and DD4hep::IOV::str().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/IOV.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/IOV.cpp