DD4hep: DD4hep::DDRec::SurfaceHelper Class Reference
DD4hep::DDRec::SurfaceHelper Class Reference
#include <SurfaceHelper.h>
Public Member Functions
SurfaceHelper (const Geometry::DetElement &e)
~SurfaceHelper ()
const SurfaceList & surfaceList ()
Protected Member Functions
void initialize ()
initializes surfaces from VolSurfaces assigned to this DetElement in detector construction
Protected Attributes
SurfaceList _sL
const Geometry::DetElement & _det
Detailed Description
Surface helper class that allows to access all surfaces assigned to a DetElement and all its daughters. (originally this was called SurfaceManager).
Author
F.Gaede, DESY
Date
Apr, 11 2014
Version
Id
Definition at line 17 of file SurfaceHelper.h.
Constructor & Destructor Documentation
SurfaceHelper()
DD4hep::DDRec::SurfaceHelper::SurfaceHelper (const Geometry::DetElement & e)
Definition at line 15 of file SurfaceHelper.cpp.
References initialize().
~SurfaceHelper()
DD4hep::DDRec::SurfaceHelper::~SurfaceHelper ()
Definition at line 20 of file SurfaceHelper.cpp.
Member Function Documentation
initialize()
void DD4hep::DDRec::SurfaceHelper::initialize () protected
initializes surfaces from VolSurfaces assigned to this DetElement in detector construction
Definition at line 25 of file SurfaceHelper.cpp.
References _det, _sL, DD4hep::Geometry::DetElement::children(), DD4hep::Geometry::LCDD::getInstance(), DD4hep::DDRec::DetectorSurfaces::surfaceList(), and DD4hep::Geometry::LCDD::world().
Referenced by SurfaceHelper().
surfaceList()
const SurfaceList& DD4hep::DDRec::SurfaceHelper::surfaceList () inline
Get the list of all surfaces added to this DetElement and all its daughters - instantiate SurfaceHelper with lcdd.world() to get all surfaces.
Definition at line 28 of file SurfaceHelper.h.
References _sL.
Referenced by DD4hep::DDRec::SurfaceManager::initialize().
Member Data Documentation
_det
const Geometry::DetElement& DD4hep::DDRec::SurfaceHelper::_det protected
Definition at line 32 of file SurfaceHelper.h.
Referenced by initialize().
_sL
SurfaceList DD4hep::DDRec::SurfaceHelper::_sL protected
Definition at line 31 of file SurfaceHelper.h.
Referenced by initialize(), and surfaceList().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/SurfaceHelper.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/SurfaceHelper.cpp