DD4hep: DD4hep: DD4hep::Simulation::Geant4HitWrapper::HitManipulator Class Reference
DD4hep::Simulation::Geant4HitWrapper::HitManipulator Class Reference
[DD4hep::Simulation components, classes and objects]
Generic type manipulation class for generic hit structures created in Geant4 sensitive detectors.
#include <Geant4HitCollection.h>
Public Types
typedef std::pair< void
*, HitManipulator * > Wrapper
Public Member Functions
HitManipulator (const ComponentCast &c, const ComponentCast &v)
Initializing Constructor.
~HitManipulator ()
Default destructor.
template<typename TYPE >
Wrapper castHit (TYPE *obj)
Check pointer to be of proper type.
Static Public Member Functions
template<typename TYPE >
static void deleteHit (Wrapper &obj)
Static function to delete contained hits.
template<typename TYPE >
static HitManipulator * instance ()
Public Attributes
const ComponentCast & cast
const ComponentCast & vec_type
Detailed Description
Generic type manipulation class for generic hit structures created in Geant4 sensitive detectors.
Author:
M.Frank
Version:
1.0
Definition at line 66 of file Geant4HitCollection.h.
Member Typedef Documentation
typedef std::pair<void*, HitManipulator*> DD4hep::Simulation::Geant4HitWrapper::HitManipulator::Wrapper
Definition at line 68 of file Geant4HitCollection.h.
Constructor & Destructor Documentation
Geant4HitWrapper::HitManipulator::HitManipulator (const ComponentCast & c, const ComponentCast & v)
Initializing Constructor.
Definition at line 30 of file Geant4HitCollection.cpp.
References DD4hep::InstanceCount::increment().
Geant4HitWrapper::HitManipulator::~HitManipulator ()
Default destructor.
Definition at line 36 of file Geant4HitCollection.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
template<typename TYPE > Wrapper DD4hep::Simulation::Geant4HitWrapper::HitManipulator::castHit (TYPE * obj) [inline]
Check pointer to be of proper type.
Definition at line 81 of file Geant4HitCollection.h.
References DD4hep::ComponentCast::apply_dynCast(), and cast.
Referenced by DD4hep::Simulation::Geant4HitCollection::add().
template<typename TYPE > static void DD4hep::Simulation::Geant4HitWrapper::HitManipulator::deleteHit (Wrapper & obj) [inline, static]
Static function to delete contained hits.
Definition at line 95 of file Geant4HitCollection.h.
template<typename TYPE > static HitManipulator* DD4hep::Simulation::Geant4HitWrapper::HitManipulator::instance () [inline, static]
Definition at line 101 of file Geant4HitCollection.h.
References DD4hep::ComponentCast::instance().
Member Data Documentation
const ComponentCast& DD4hep::Simulation::Geant4HitWrapper::HitManipulator::cast
Definition at line 73 of file Geant4HitCollection.h.
Referenced by castHit(), DD4hep::Simulation::Geant4HitCollection::getData(), DD4hep::Simulation::Geant4HitCollection::releaseData(), and DD4hep::Simulation::Geant4HitCollection::type().
const ComponentCast& DD4hep::Simulation::Geant4HitWrapper::HitManipulator::vec_type
Definition at line 74 of file Geant4HitCollection.h.
Referenced by DD4hep::Simulation::Geant4HitCollection::vector_type().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4HitCollection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4HitCollection.cpp