DD4hep: DD4hep::Conditions::ConditionsDependencyCollection Class Reference
DD4hep::Conditions::ConditionsDependencyCollection Class Reference
Collection of condition dependencies.
#include <ConditionsDependencyCollection.h>
Classes
class Functor
Functor base to create views.
struct Holder
Public Types
typedef ConditionDependency Dependency
Forward definition of the dependency type.
typedef std::map< unsigned int, Holder > Dependencies
Forward definition of the dependency container type.
typedef Dependencies::const_iterator const_iterator
typedef Dependencies::iterator iterator
typedef Dependencies::key_type key_type
typedef Dependencies::mapped_type mapped_type
Public Member Functions
ConditionsDependencyCollection ()
Initializing constructor.
ConditionsDependencyCollection (const ConditionsDependencyCollection &copy)
Copy constructor.
virtual ~ConditionsDependencyCollection ()
Default destructor.
void clear ()
Clear the dependency container. Destroys the contained stuff.
bool empty () const
Mini-container interface: emptyness check.
size_t size () const
Mini-container interface: number of entries.
iterator begin ()
Mini-container interface: begin of iteration.
const_iterator begin () const
Mini-container interface: begin of iteration (const)
iterator end ()
Mini-container interface: end of iteration.
const_iterator end () const
Mini-container interface: end of iteration (const)
iterator find (Condition::key_type key)
Mini-container interface: find element by key.
const_iterator find (Condition::key_type key) const
Mini-container interface: find element by key (const)
std::pair< iterator, bool > insert (const Dependencies::value_type &entry)
Mini-container interface: insert element by key.
std::pair< iterator, bool > insert (Dependency *dep)
Insert new element by key.
template<typename T >
void for_each (const T &function) const
Create view by application of functor.
Public Attributes
Dependencies dependencies
Dependency container.
Detailed Description
Collection of condition dependencies.
Author
M.Frank
Version
1.0
Definition at line 42 of file ConditionsDependencyCollection.h.
Member Typedef Documentation
const_iterator
typedef Dependencies::const_iterator DD4hep::Conditions::ConditionsDependencyCollection::const_iterator
Definition at line 60 of file ConditionsDependencyCollection.h.
Dependencies
typedef std::map<unsigned int,Holder> DD4hep::Conditions::ConditionsDependencyCollection::Dependencies
Forward definition of the dependency container type.
Definition at line 59 of file ConditionsDependencyCollection.h.
Dependency
typedef ConditionDependency DD4hep::Conditions::ConditionsDependencyCollection::Dependency
Forward definition of the dependency type.
Definition at line 46 of file ConditionsDependencyCollection.h.
iterator
typedef Dependencies::iterator DD4hep::Conditions::ConditionsDependencyCollection::iterator
Definition at line 61 of file ConditionsDependencyCollection.h.
key_type
typedef Dependencies::key_type DD4hep::Conditions::ConditionsDependencyCollection::key_type
Definition at line 62 of file ConditionsDependencyCollection.h.
mapped_type
typedef Dependencies::mapped_type DD4hep::Conditions::ConditionsDependencyCollection::mapped_type
Definition at line 63 of file ConditionsDependencyCollection.h.
Constructor & Destructor Documentation
ConditionsDependencyCollection() [1/2]
ConditionsDependencyCollection::ConditionsDependencyCollection ()
Initializing constructor.
Default constructor.
Definition at line 24 of file ConditionsDependencyCollection.cpp.
ConditionsDependencyCollection() [2/2]
ConditionsDependencyCollection::ConditionsDependencyCollection (const ConditionsDependencyCollection & copy)
Copy constructor.
Definition at line 29 of file ConditionsDependencyCollection.cpp.
References dependencies.
~ConditionsDependencyCollection()
ConditionsDependencyCollection::~ConditionsDependencyCollection () virtual
Default destructor.
Definition at line 37 of file ConditionsDependencyCollection.cpp.
References dependencies, and DD4hep::releaseObjects().
Member Function Documentation
begin() [1/2]
iterator DD4hep::Conditions::ConditionsDependencyCollection::begin () inline
Mini-container interface: begin of iteration.
Definition at line 94 of file ConditionsDependencyCollection.h.
begin() [2/2]
const_iterator DD4hep::Conditions::ConditionsDependencyCollection::begin () const inline
Mini-container interface: begin of iteration (const)
Definition at line 96 of file ConditionsDependencyCollection.h.
clear()
void ConditionsDependencyCollection::clear ()
Clear the dependency container. Destroys the contained stuff.
Definition at line 42 of file ConditionsDependencyCollection.cpp.
References dependencies, and DD4hep::releaseObjects().
Referenced by DD4hep::Alignments::AlignmentsManagerObject::~AlignmentsManagerObject().
empty()
bool DD4hep::Conditions::ConditionsDependencyCollection::empty () const inline
Mini-container interface: emptyness check.
Definition at line 90 of file ConditionsDependencyCollection.h.
end() [1/2]
iterator DD4hep::Conditions::ConditionsDependencyCollection::end () inline
Mini-container interface: end of iteration.
Definition at line 98 of file ConditionsDependencyCollection.h.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::get().
end() [2/2]
const_iterator DD4hep::Conditions::ConditionsDependencyCollection::end () const inline
Mini-container interface: end of iteration (const)
Definition at line 100 of file ConditionsDependencyCollection.h.
find() [1/2]
iterator DD4hep::Conditions::ConditionsDependencyCollection::find (Condition::key_type key) inline
Mini-container interface: find element by key.
Definition at line 102 of file ConditionsDependencyCollection.h.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::get().
find() [2/2]
const_iterator DD4hep::Conditions::ConditionsDependencyCollection::find (Condition::key_type key) const inline
Mini-container interface: find element by key (const)
Definition at line 105 of file ConditionsDependencyCollection.h.
References DD4hep::Conditions::ConditionsDependencyCollection::Holder::dep, and insert().
for_each()
template<typename T > void DD4hep::Conditions::ConditionsDependencyCollection::for_each (const T & function) const inline
Create view by application of functor.
Definition at line 112 of file ConditionsDependencyCollection.h.
insert() [1/2]
std::pair< ConditionsDependencyCollection::iterator, bool > ConditionsDependencyCollection::insert (const Dependencies::value_type & entry)
Mini-container interface: insert element by key.
Definition at line 48 of file ConditionsDependencyCollection.cpp.
References dependencies.
Referenced by DD4hep::Alignments::AlignmentsManager::adoptDependency(), and find().
insert() [2/2]
std::pair< ConditionsDependencyCollection::iterator, bool > ConditionsDependencyCollection::insert (Dependency * dep)
Insert new element by key.
Definition at line 55 of file ConditionsDependencyCollection.cpp.
References DD4hep::Conditions::ConditionDependency::addRef(), dependencies, and DD4hep::Conditions::ConditionDependency::key().
size()
size_t DD4hep::Conditions::ConditionsDependencyCollection::size () const inline
Mini-container interface: number of entries.
Definition at line 92 of file ConditionsDependencyCollection.h.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute().
Member Data Documentation
dependencies
Dependencies DD4hep::Conditions::ConditionsDependencyCollection::dependencies
Dependency container.
Definition at line 79 of file ConditionsDependencyCollection.h.
Referenced by clear(), ConditionsDependencyCollection(), insert(), and ~ConditionsDependencyCollection().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsDependencyCollection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsDependencyCollection.cpp