DD4hep: DD4hep::Geometry::Material Class Reference
DD4hep::Geometry::Material Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing a material.
#include <Objects.h>
Public Types
typedef TGeoMedium Object
Definition of the implementation type.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Material ()
Default constructor.
Material (const Handle< Object > &e)
Constructorto be used for assignment from material handle.
template<typename Q >
Material (const Handle< Q > &e)
Constructorto be used for assignment from object handle.
double Z () const
proton number of the underlying material
double A () const
atomic number of the underlying material
double density () const
density of the underlying material
std::string toString () const
String representation of this object.
double radLength () const
Access the radiation length of the underlying material.
double intLength () const
Access the interaction length of the underlying material.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing a material.
For details please see the ROOT TGeo information:
See also
http://root.cern.ch/root/html/TGeoMedium.html
Author
M.Frank
Version
1.0
Definition at line 300 of file Objects.h.
Member Typedef Documentation
Object
typedef TGeoMedium DD4hep::Geometry::Material::Object
Definition of the implementation type.
Definition at line 303 of file Objects.h.
Constructor & Destructor Documentation
Material() [1/3]
DD4hep::Geometry::Material::Material () inline
Default constructor.
Definition at line 306 of file Objects.h.
References e.
Material() [2/3]
DD4hep::Geometry::Material::Material (const Handle< Object > & e) inline
Constructorto be used for assignment from material handle.
Definition at line 311 of file Objects.h.
Material() [3/3]
template<typename Q > DD4hep::Geometry::Material::Material (const Handle< Q > & e) inline
Constructorto be used for assignment from object handle.
Definition at line 317 of file Objects.h.
References DD4hep::Geometry::DetectorTools::toString().
Member Function Documentation
A()
double Material::A () const
atomic number of the underlying material
Definition at line 189 of file Objects.cpp.
References DD4hep::Handle< T >::isValid(), and m.
Referenced by DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::DDRec::operator<<(), and DD4hep::DDRec::MaterialData::operator=().
density()
double Material::density () const
density of the underlying material
Definition at line 201 of file Objects.cpp.
References DD4hep::Handle< T >::isValid(), and m.
Referenced by DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::DDRec::operator<<(), and DD4hep::DDRec::MaterialData::operator=().
intLength()
double Material::intLength () const
Access the interaction length of the underlying material.
Access the radiation length of the underlying material.
Definition at line 225 of file Objects.cpp.
References DD4hep::Handle< T >::isValid(), and m.
Referenced by DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::DDRec::operator<<(), and DD4hep::DDRec::MaterialData::operator=().
radLength()
double Material::radLength () const
Access the radiation length of the underlying material.
Definition at line 213 of file Objects.cpp.
References DD4hep::Handle< T >::isValid(), and m.
Referenced by DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::DDRec::operator<<(), and DD4hep::DDRec::MaterialData::operator=().
toString()
string Material::toString () const
String representation of this object.
Definition at line 237 of file Objects.cpp.
Referenced by DD4hep::Printer< T >::operator()().
Z()
double Material::Z () const
proton number of the underlying material
Definition at line 178 of file Objects.cpp.
References DD4hep::Handle< T >::isValid(), and m.
Referenced by DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::DDRec::operator<<(), and DD4hep::DDRec::MaterialData::operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp