DD4hep: DD4hep::Simulation::Geant4ActionContainer Class Reference
DD4hep::Simulation::Geant4ActionContainer Class Reference
DD4hep::Simulation components, classes and objects
Class, which allows all Geant4Action to be stored.
#include <Geant4ActionContainer.h>
Public Member Functions
Geant4Context * workerContext ()
Thread's Geant4 execution context.
virtual int terminate ()
Terminate all associated action instances.
Geant4GeneratorActionSequence * generatorAction (bool create)
Access generator action sequence.
Geant4GeneratorActionSequence & generatorAction ()
Access generator action sequence.
Geant4RunActionSequence * runAction (bool create)
Access run action sequence.
Geant4RunActionSequence & runAction ()
Access run action sequence.
Geant4EventActionSequence * eventAction (bool create)
Access run action sequence.
Geant4EventActionSequence & eventAction ()
Access run action sequence.
Geant4SteppingActionSequence * steppingAction (bool create)
Access stepping action sequence.
Geant4SteppingActionSequence & steppingAction ()
Access stepping action sequence.
Geant4TrackingActionSequence * trackingAction (bool create)
Access tracking action sequence.
Geant4TrackingActionSequence & trackingAction ()
Access tracking action sequence.
Geant4StackingActionSequence * stackingAction (bool create)
Access stacking action sequence.
Geant4StackingActionSequence & stackingAction ()
Access stacking action sequence.
Geant4DetectorConstructionSequence * detectorConstruction (bool create)
Access detector construcion action sequence (geometry+sensitives+field)
Geant4DetectorConstructionSequence & detectorConstruction ()
Access detector construcion action sequence (geometry+sensitives+field)
Geant4SensDetSequences & sensitiveActions () const
Access to the sensitive detector sequences from the actioncontainer object.
Geant4SensDetActionSequence * sensitiveAction (const std::string &name)
Access to the sensitive detector action from the actioncontainer object.
Geant4PhysicsListActionSequence * physicsList (bool create)
Access to the physics list.
Geant4PhysicsListActionSequence & physicsList ()
Access to the physics list.
Geant4UserInitializationSequence * userInitialization (bool create)
Access to the user initialization object.
Geant4UserInitializationSequence & userInitialization ()
Access to the user initialization object.
Protected Member Functions
template<typename C >
bool registerSequence (C *&seq, const std::string &name)
Helper to register an action sequence.
Geant4ActionContainer (Geant4Context *ctxt=0)
Standard constructor.
virtual ~Geant4ActionContainer ()
Default destructor.
void setContext (Geant4Context *ctxt)
Set the thread's context.
Protected Attributes
Geant4Context * m_context
Geant4 worker context (thread specific)
Geant4GeneratorActionSequence * m_generatorAction
Reference to the Geant4 primary generator action.
Geant4RunActionSequence * m_runAction
Reference to the Geant4 run action.
Geant4EventActionSequence * m_eventAction
Reference to the Geant4 event action.
Geant4TrackingActionSequence * m_trackingAction
Reference to the Geant4 track action.
Geant4SteppingActionSequence * m_steppingAction
Reference to the Geant4 step action.
Geant4StackingActionSequence * m_stackingAction
Reference to the Geant4 stacking action.
Geant4DetectorConstructionSequence * m_constructionAction
Reference to the Geant4 detector construction sequence.
Geant4SensDetSequences * m_sensDetActions
Reference to the Geant4 sensitive action sequences.
Geant4PhysicsListActionSequence * m_physicsList
Reference to the Geant4 physics list.
Geant4UserInitializationSequence * m_userInit
Reference to the user initialization object.
Detailed Description
Class, which allows all Geant4Action to be stored.
Author
M.Frank
Version
1.0
Definition at line 61 of file Geant4ActionContainer.h.
Constructor & Destructor Documentation
Geant4ActionContainer()
Geant4ActionContainer::Geant4ActionContainer (Geant4Context * ctxt = 0) protected
Standard constructor.
Definition at line 40 of file Geant4ActionContainer.cpp.
References DD4hep::InstanceCount::increment(), and m_sensDetActions.
~Geant4ActionContainer()
Geant4ActionContainer::~Geant4ActionContainer () protected virtual
Default destructor.
Definition at line 51 of file Geant4ActionContainer.cpp.
References DD4hep::InstanceCount::decrement(), and terminate().
Member Function Documentation
detectorConstruction() [1/2]
Geant4DetectorConstructionSequence * Geant4ActionContainer::detectorConstruction (bool create)
Access detector construcion action sequence (geometry+sensitives+field)
Definition at line 133 of file Geant4ActionContainer.cpp.
References m_constructionAction, and registerSequence().
Referenced by Geant4Compatibility::buildDefaultDetectorConstruction(), and DD4hep::Simulation::Geant4Exec::configure().
detectorConstruction() [2/2]
Geant4DetectorConstructionSequence& DD4hep::Simulation::Geant4ActionContainer::detectorConstruction () inline
Access detector construcion action sequence (geometry+sensitives+field)
Definition at line 153 of file Geant4ActionContainer.h.
References physicsList(), sensitiveAction(), and sensitiveActions().
Referenced by stackingAction().
eventAction() [1/2]
Geant4EventActionSequence * Geant4ActionContainer::eventAction (bool create)
Access run action sequence.
Access event action sequence.
Definition at line 105 of file Geant4ActionContainer.cpp.
References m_eventAction, and registerSequence().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4Context::eventAction(), and DD4hep::Converter< T, ARG >::operator()().
eventAction() [2/2]
Geant4EventActionSequence& DD4hep::Simulation::Geant4ActionContainer::eventAction () inline
Access run action sequence.
Definition at line 125 of file Geant4ActionContainer.h.
References steppingAction().
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), and runAction().
generatorAction() [1/2]
Geant4GeneratorActionSequence * Geant4ActionContainer::generatorAction (bool create)
Access generator action sequence.
Definition at line 91 of file Geant4ActionContainer.cpp.
References m_generatorAction, and registerSequence().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4Context::generatorAction(), and DD4hep::Converter< T, ARG >::operator()().
generatorAction() [2/2]
Geant4GeneratorActionSequence& DD4hep::Simulation::Geant4ActionContainer::generatorAction () inline
Access generator action sequence.
Definition at line 111 of file Geant4ActionContainer.h.
References runAction().
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
physicsList() [1/2]
Geant4PhysicsListActionSequence * Geant4ActionContainer::physicsList (bool create)
Access to the physics list.
Definition at line 156 of file Geant4ActionContainer.cpp.
References m_physicsList, and registerSequence().
Referenced by DD4hep::Simulation::Geant4Exec::configure(), and DD4hep::Converter< T, ARG >::operator()().
physicsList() [2/2]
Geant4PhysicsListActionSequence& DD4hep::Simulation::Geant4ActionContainer::physicsList () inline
Access to the physics list.
Definition at line 165 of file Geant4ActionContainer.h.
References userInitialization().
Referenced by detectorConstruction().
registerSequence()
template<class C > bool Geant4ActionContainer::registerSequence (C *& seq, const std::string & name) protected
Helper to register an action sequence.
Definition at line 81 of file Geant4ActionContainer.cpp.
References DD4hep::format(), and m_context.
Referenced by detectorConstruction(), eventAction(), generatorAction(), physicsList(), runAction(), stackingAction(), steppingAction(), trackingAction(), and userInitialization().
runAction() [1/2]
Geant4RunActionSequence * Geant4ActionContainer::runAction (bool create)
Access run action sequence.
Definition at line 98 of file Geant4ActionContainer.cpp.
References m_runAction, and registerSequence().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4GeneratorActionInit::Geant4GeneratorActionInit(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::Simulation::Geant4Context::runAction().
runAction() [2/2]
Geant4RunActionSequence& DD4hep::Simulation::Geant4ActionContainer::runAction () inline
Access run action sequence.
Definition at line 118 of file Geant4ActionContainer.h.
References eventAction().
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), and generatorAction().
sensitiveAction()
Geant4SensDetActionSequence * Geant4ActionContainer::sensitiveAction (const std::string & name)
Access to the sensitive detector action from the actioncontainer object.
Access to the sensitive detector action from the kernel object.
Definition at line 145 of file Geant4ActionContainer.cpp.
References DD4hep::Simulation::Geant4SensDetSequences::find(), DD4hep::Simulation::Geant4SensDetSequences::insert(), m_sensDetActions, and workerContext().
Referenced by detectorConstruction(), DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), and DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive().
sensitiveActions()
Geant4SensDetSequences & Geant4ActionContainer::sensitiveActions () const
Access to the sensitive detector sequences from the actioncontainer object.
Access to the sensitive detector sequences from the kernel object.
Definition at line 140 of file Geant4ActionContainer.cpp.
References m_sensDetActions.
Referenced by detectorConstruction(), and DD4hep::Simulation::Geant4Context::sensitiveActions().
setContext()
void Geant4ActionContainer::setContext (Geant4Context * ctxt) protected
Set the thread's context.
Definition at line 77 of file Geant4ActionContainer.cpp.
References m_context.
Referenced by DD4hep::Simulation::Geant4Kernel::Geant4Kernel().
stackingAction() [1/2]
Geant4StackingActionSequence * Geant4ActionContainer::stackingAction (bool create)
Access stacking action sequence.
Definition at line 126 of file Geant4ActionContainer.cpp.
References m_stackingAction, and registerSequence().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::Simulation::Geant4Context::stackingAction().
stackingAction() [2/2]
Geant4StackingActionSequence& DD4hep::Simulation::Geant4ActionContainer::stackingAction () inline
Access stacking action sequence.
Definition at line 146 of file Geant4ActionContainer.h.
References detectorConstruction().
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), and trackingAction().
steppingAction() [1/2]
Geant4SteppingActionSequence * Geant4ActionContainer::steppingAction (bool create)
Access stepping action sequence.
Definition at line 112 of file Geant4ActionContainer.cpp.
References m_steppingAction, and registerSequence().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::Simulation::Geant4Context::steppingAction().
steppingAction() [2/2]
Geant4SteppingActionSequence& DD4hep::Simulation::Geant4ActionContainer::steppingAction () inline
Access stepping action sequence.
Definition at line 132 of file Geant4ActionContainer.h.
References trackingAction().
Referenced by eventAction(), and DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
terminate()
int Geant4ActionContainer::terminate () virtual
Terminate all associated action instances.
Reimplemented in DD4hep::Simulation::Geant4Kernel.
Definition at line 57 of file Geant4ActionContainer.cpp.
References DD4hep::deletePtr(), m_constructionAction, m_context, m_eventAction, m_generatorAction, m_physicsList, m_runAction, m_sensDetActions, m_stackingAction, m_steppingAction, m_trackingAction, and DD4hep::releasePtr().
Referenced by DD4hep::Simulation::Geant4Kernel::terminate(), ~Geant4ActionContainer(), and DD4hep::Simulation::Geant4Kernel::~Geant4Kernel().
trackingAction() [1/2]
Geant4TrackingActionSequence * Geant4ActionContainer::trackingAction (bool create)
Access tracking action sequence.
Definition at line 119 of file Geant4ActionContainer.cpp.
References m_trackingAction, and registerSequence().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::Simulation::Geant4Context::trackingAction().
trackingAction() [2/2]
Geant4TrackingActionSequence& DD4hep::Simulation::Geant4ActionContainer::trackingAction () inline
Access tracking action sequence.
Definition at line 139 of file Geant4ActionContainer.h.
References stackingAction().
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), and steppingAction().
userInitialization() [1/2]
Geant4UserInitializationSequence * Geant4ActionContainer::userInitialization (bool create)
Access to the user initialization object.
Access to the physics list.
Definition at line 163 of file Geant4ActionContainer.cpp.
References m_userInit, and registerSequence().
Referenced by DD4hep::Simulation::Geant4Exec::configure().
userInitialization() [2/2]
Geant4UserInitializationSequence& DD4hep::Simulation::Geant4ActionContainer::userInitialization () inline
Access to the user initialization object.
Definition at line 171 of file Geant4ActionContainer.h.
Referenced by physicsList().
workerContext()
Geant4Context * Geant4ActionContainer::workerContext ()
Thread's Geant4 execution context.
Definition at line 71 of file Geant4ActionContainer.cpp.
References DD4hep::format(), and m_context.
Referenced by DD4hep::Simulation::_create_object(), DD4hep::Simulation::Geant4Kernel::addSimplePhase(), DD4hep::Simulation::Geant4UserActionInitialization::Build(), Geant4Compatibility::buildDefaultDetectorConstruction(), DD4hep::Simulation::Geant4Exec::configure(), DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), and sensitiveAction().
Member Data Documentation
m_constructionAction
Geant4DetectorConstructionSequence* DD4hep::Simulation::Geant4ActionContainer::m_constructionAction protected
Reference to the Geant4 detector construction sequence.
Definition at line 80 of file Geant4ActionContainer.h.
Referenced by detectorConstruction(), and terminate().
m_context
Geant4Context* DD4hep::Simulation::Geant4ActionContainer::m_context protected
Geant4 worker context (thread specific)
Definition at line 65 of file Geant4ActionContainer.h.
Referenced by registerSequence(), setContext(), terminate(), and workerContext().
m_eventAction
Geant4EventActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_eventAction protected
Reference to the Geant4 event action.
Definition at line 72 of file Geant4ActionContainer.h.
Referenced by eventAction(), and terminate().
m_generatorAction
Geant4GeneratorActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_generatorAction protected
Reference to the Geant4 primary generator action.
Definition at line 68 of file Geant4ActionContainer.h.
Referenced by generatorAction(), and terminate().
m_physicsList
Geant4PhysicsListActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_physicsList protected
Reference to the Geant4 physics list.
Definition at line 85 of file Geant4ActionContainer.h.
Referenced by physicsList(), and terminate().
m_runAction
Geant4RunActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_runAction protected
Reference to the Geant4 run action.
Definition at line 70 of file Geant4ActionContainer.h.
Referenced by runAction(), and terminate().
m_sensDetActions
Geant4SensDetSequences* DD4hep::Simulation::Geant4ActionContainer::m_sensDetActions protected
Reference to the Geant4 sensitive action sequences.
Definition at line 83 of file Geant4ActionContainer.h.
Referenced by Geant4ActionContainer(), sensitiveAction(), sensitiveActions(), and terminate().
m_stackingAction
Geant4StackingActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_stackingAction protected
Reference to the Geant4 stacking action.
Definition at line 78 of file Geant4ActionContainer.h.
Referenced by stackingAction(), and terminate().
m_steppingAction
Geant4SteppingActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_steppingAction protected
Reference to the Geant4 step action.
Definition at line 76 of file Geant4ActionContainer.h.
Referenced by steppingAction(), and terminate().
m_trackingAction
Geant4TrackingActionSequence* DD4hep::Simulation::Geant4ActionContainer::m_trackingAction protected
Reference to the Geant4 track action.
Definition at line 74 of file Geant4ActionContainer.h.
Referenced by terminate(), and trackingAction().
m_userInit
Geant4UserInitializationSequence* DD4hep::Simulation::Geant4ActionContainer::m_userInit protected
Reference to the user initialization object.
Definition at line 87 of file Geant4ActionContainer.h.
Referenced by userInitialization().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ActionContainer.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ActionContainer.cpp