DD4hep: DD4hep: DD4hep::Geometry::PolarGridRPhi2 Class Reference
DD4hep::Geometry::PolarGridRPhi2 Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid XZ segmentation.
#include <PolarGridRPhi2.h>
Public Types
typedef
PolarGridRPhi2Handle::Implementation Object
Defintiion of the basic handled object.
Public Member Functions
PolarGridRPhi2 ()
Default constructor.
PolarGridRPhi2 (const PolarGridRPhi2 &e)
Copy constructor.
PolarGridRPhi2 (const Segmentation &e)
Copy Constructor from segmentation base object.
PolarGridRPhi2 (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
PolarGridRPhi2 (const Handle< Q > &e)
Copy constructor from other polymorph/equivalent handle.
PolarGridRPhi2 & operator= (const PolarGridRPhi2 &seg)
Assignment operator.
bool operator== (const PolarGridRPhi2 &seg) const
Equality operator.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
double gridSizeR () const
access the grid size in R
double gridSizePhi () const
access the grid size in Phi
double offsetR () const
access the coordinate offset in R
double offsetPhi () const
access the coordinate offset in Phi
void setOffsetR (double offset) const
set the coordinate offset in R
void setOffsetPhi (double offset) const
set the coordinate offset in Phi
std::vector< double > gridRValues () const
access the grid size in R
std::vector< double > gridPhiValues () const
access the grid size in Phi
void setGridSizeR (double cellSize, int rID) const
set the grid Boundaries in R
void setGridSizePhi (double cellSize, int phiID) const
set the grid size in Phi
void setGridRValues (std::vector< double > const &rValues) const
set the grid boundaries for R
void setGridPhiValues (std::vector< double > const &phiValues) const
set the grid size in Phi for each bin in R
const std::string & fieldNameR () const
access the field name used for R
const std::string & fieldNamePhi () const
access the field name used for Phi
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid XZ segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 57 of file PolarGridRPhi2.h.
Member Typedef Documentation
typedef PolarGridRPhi2Handle::Implementation DD4hep::Geometry::PolarGridRPhi2::Object
Defintiion of the basic handled object.
Definition at line 60 of file PolarGridRPhi2.h.
Constructor & Destructor Documentation
DD4hep::Geometry::PolarGridRPhi2::PolarGridRPhi2 ()
Default constructor.
DD4hep::Geometry::PolarGridRPhi2::PolarGridRPhi2 (const PolarGridRPhi2 & e)
Copy constructor.
DD4hep::Geometry::PolarGridRPhi2::PolarGridRPhi2 (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 68 of file PolarGridRPhi2.h.
DD4hep::Geometry::PolarGridRPhi2::PolarGridRPhi2 (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 70 of file PolarGridRPhi2.h.
template<typename Q > DD4hep::Geometry::PolarGridRPhi2::PolarGridRPhi2 (const Handle< Q > & e) [inline]
Copy constructor from other polymorph/equivalent handle.
Definition at line 72 of file PolarGridRPhi2.h.
Member Function Documentation
vector< double > PolarGridRPhi2::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in x
size in z
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in x
size in z
Definition at line 105 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID PolarGridRPhi2::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 30 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
const string & PolarGridRPhi2::fieldNamePhi () const
access the field name used for Phi
Definition at line 92 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
const string & PolarGridRPhi2::fieldNameR () const
access the field name used for R
Definition at line 87 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
vector< double > PolarGridRPhi2::gridPhiValues () const
access the grid size in Phi
Definition at line 43 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
vector< double > PolarGridRPhi2::gridRValues () const
access the grid size in R
Definition at line 38 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
double DD4hep::Geometry::PolarGridRPhi2::gridSizePhi () const
access the grid size in Phi
double DD4hep::Geometry::PolarGridRPhi2::gridSizeR () const
access the grid size in R
double PolarGridRPhi2::offsetPhi () const
access the coordinate offset in Phi
Definition at line 72 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
double PolarGridRPhi2::offsetR () const
access the coordinate offset in R
Definition at line 67 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
PolarGridRPhi2& DD4hep::Geometry::PolarGridRPhi2::operator= (const PolarGridRPhi2 & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::PolarGridRPhi2::operator== (const PolarGridRPhi2 & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 76 of file PolarGridRPhi2.h.
References DD4hep::Handle< T >::m_element.
Position PolarGridRPhi2::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 25 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi2::setGridPhiValues (std::vector< double > const & phiValues) const
set the grid size in Phi for each bin in R
Parameters:
phiValues The size in phi for each bin in R, this vector is one smaller than the vector for PolarGridRPhi2::setGridRValues
Definition at line 62 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi2::setGridRValues (std::vector< double > const & rValues) const
set the grid boundaries for R
Parameters:
rValues The boundaries of the segments in radius, the first value is the lower boundary of the first bin, the highest value is the upper boundary of the last bin
Definition at line 57 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi2::setGridSizePhi (double cellSize, int phiID) const
set the grid size in Phi
Definition at line 52 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi2::setGridSizeR (double cellSize, int rID) const
set the grid Boundaries in R
Definition at line 47 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi2::setOffsetPhi (double offset) const
set the coordinate offset in Phi
Definition at line 82 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
void PolarGridRPhi2::setOffsetR (double offset) const
set the coordinate offset in R
Definition at line 77 of file PolarGridRPhi2.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/PolarGridRPhi2.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/PolarGridRPhi2.cpp