DD4hep: DD4hep::DDSegmentation::TiledLayerSegmentation Class Reference
DD4hep::DDSegmentation::TiledLayerSegmentation Class Reference
#include <TiledLayerSegmentation.h>
Classes
struct LayerDimensions
Helper class to store x and y dimensions of a layer.
Public Member Functions
TiledLayerSegmentation (const std::string &cellEncoding="")
Default constructor passing the encoding string.
TiledLayerSegmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
virtual ~TiledLayerSegmentation ()
destructor
virtual Vector3D position (const CellID &cellID) const
determine the position based on the cell ID
virtual CellID cellID (const Vector3D &localPosition, const Vector3D &globalPosition, const VolumeID &volumeID) const
determine the cell ID based on the position
double gridSizeX () const
access the default grid size in X
double gridSizeY () const
access the default grid size in Y
double layerGridSizeX (int layerIndex) const
access the actual grid size in X for a given layer
double layerGridSizeY (int layerIndex) const
access the actual grid size in Y for a given layer
const std::string & identifierX () const
access the encoding field name used for X
const std::string & identifierY () const
access the encoding field name used for Y
const std::string & identifierLayer () const
access the encoding field name used for Y
LayerDimensions layerDimensions (int layerIndex) const
access to the dimensions of the given layer
void setGridSizeX (double cellSize)
set the default grid size in X
void setGridSizeY (double cellSize)
set the default grid size in Y
void setIdentifierX (const std::string &fieldName)
set the encoding field name used for X
void setIdentifierY (const std::string &fieldName)
set the encoding field name used for Y
void setIdentifierLayer (const std::string &fieldName)
set the encoding field name used for layer
void setLayerDimensions (int layerIndex, double x, double y)
set the dimensions of the given layer
Public Member Functions inherited from DD4hep::DDSegmentation::Segmentation
virtual ~Segmentation ()
Destructor.
virtual void addSubsegmentation (long key_min, long key_max, Segmentation *entry)
Add subsegmentation. Call only valid for Multi-segmentations. Default implementation throws an exception.
virtual VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
virtual void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
virtual std::string fieldDescription () const
Access the encoding string.
virtual const std::string & name () const
Access the segmentation name.
virtual void setName (const std::string &value)
Set the segmentation name.
virtual const std::string & type () const
Access the segmentation type.
virtual const std::string & description () const
Access the description of the segmentation.
virtual BitField64 * decoder () const
Access the underlying decoder.
virtual void setDecoder (BitField64 *decoder)
Set the underlying decoder.
virtual Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
virtual Parameters parameters () const
Access to all parameters.
virtual void setParameters (const Parameters &parameters)
Set all parameters from an existing set of parameters.
virtual std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Static Protected Member Functions
static double calculateOptimalCellSize (double nominalCellSize, double totalSize)
list of layer y dimensions
static double calculateOffset (double cellSize, double totalSize)
helper method to calculate offset of bin 0 based on the total size
Static Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
static double binToPosition (CellID bin, double cellSize, double offset=0.)
Helper method to convert a bin number to a 1D position.
static int positionToBin (double position, double cellSize, double offset=0.)
Helper method to convert a 1D position to a cell ID.
static double binToPosition (CellID bin, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a bin number to a 1D position given a vector of binBoundaries.
static int positionToBin (double position, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a 1D position to a cell ID given a vector of binBoundaries.
Protected Attributes
double _gridSizeX
double _gridSizeY
default grid size in X
std::string _identifierX
default grid size in Y
std::string _identifierY
encoding field used for X
std::string _identifierLayer
encoding field used for Y
std::vector< int > _layerIndices
encoding field used for the layer
std::vector< double > _layerDimensionsX
list of valid layer identifiers
std::vector< double > _layerDimensionsY
list of layer x dimensions
Protected Attributes inherited from DD4hep::DDSegmentation::Segmentation
std::string _name
The segmentation name.
std::string _type
The segmentation type.
std::string _description
The description of the segmentation.
std::map< std::string, Parameter > _parameters
The parameters for this segmentation.
std::map< std::string, StringParameter > _indexIdentifiers
The indices used for the encoding.
BitField64 * _decoder
The cell ID encoder and decoder.
bool _ownsDecoder
Keeps track of the decoder ownership.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
Segmentation (const std::string &cellEncoding="")
Default constructor used by derived classes passing the encoding string.
Segmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
template<typename TYPE >
void registerParameter (const std::string &nam, const std::string &desc, TYPE &param, const TYPE &defaultVal, UnitType unitTyp=SegmentationParameter::NoUnit, bool isOpt=false)
Add a parameter to this segmentation. Used by derived classes to define their parameters.
void registerIdentifier (const std::string &nam, const std::string &desc, std::string &ident, const std::string &defaultVal)
Add a cell identifier to this segmentation. Used by derived classes to define their required identifiers.
Detailed Description
Definition at line 20 of file TiledLayerSegmentation.h.
Constructor & Destructor Documentation
TiledLayerSegmentation() [1/2]
DD4hep::DDSegmentation::TiledLayerSegmentation::TiledLayerSegmentation (const std::string & cellEncoding = "")
Default constructor passing the encoding string.
Definition at line 23 of file TiledLayerSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, _gridSizeX, _gridSizeY, _identifierLayer, _identifierX, _identifierY, _layerDimensionsX, _layerDimensionsY, _layerIndices, DD4hep::DDSegmentation::Segmentation::_type, DD4hep::DDSegmentation::SegmentationParameter::LengthUnit, DD4hep::DDSegmentation::SegmentationParameter::NoUnit, DD4hep::DDSegmentation::Segmentation::registerIdentifier(), and DD4hep::DDSegmentation::Segmentation::registerParameter().
TiledLayerSegmentation() [2/2]
DD4hep::DDSegmentation::TiledLayerSegmentation::TiledLayerSegmentation (BitField64 * decoder)
Default constructor used by derived classes passing an existing decoder.
Definition at line 45 of file TiledLayerSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, _gridSizeX, _gridSizeY, _identifierLayer, _identifierX, _identifierY, _layerDimensionsX, _layerDimensionsY, _layerIndices, DD4hep::DDSegmentation::Segmentation::_type, DD4hep::DDSegmentation::SegmentationParameter::LengthUnit, DD4hep::DDSegmentation::SegmentationParameter::NoUnit, DD4hep::DDSegmentation::Segmentation::registerIdentifier(), and DD4hep::DDSegmentation::Segmentation::registerParameter().
~TiledLayerSegmentation()
DD4hep::DDSegmentation::TiledLayerSegmentation::~TiledLayerSegmentation () virtual
destructor
Definition at line 65 of file TiledLayerSegmentation.cpp.
Member Function Documentation
calculateOffset()
double DD4hep::DDSegmentation::TiledLayerSegmentation::calculateOffset (double cellSize, double totalSize) static protected
helper method to calculate offset of bin 0 based on the total size
Definition at line 152 of file TiledLayerSegmentation.cpp.
Referenced by cellID(), and position().
calculateOptimalCellSize()
double DD4hep::DDSegmentation::TiledLayerSegmentation::calculateOptimalCellSize (double nominalCellSize, double totalSize) static protected
list of layer y dimensions
helper method to calculate optimal cell size based on total size
Definition at line 146 of file TiledLayerSegmentation.cpp.
Referenced by layerGridSizeX(), and layerGridSizeY().
cellID()
CellID DD4hep::DDSegmentation::TiledLayerSegmentation::cellID (const Vector3D & localPosition, const Vector3D & globalPosition, const VolumeID & volumeID) const virtual
determine the cell ID based on the position
Implements DD4hep::DDSegmentation::Segmentation.
Definition at line 131 of file TiledLayerSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, _identifierLayer, _identifierX, _identifierY, calculateOffset(), layerDimensions(), layerGridSizeX(), layerGridSizeY(), DD4hep::DDSegmentation::Segmentation::positionToBin(), DD4hep::DDSegmentation::BitField64::setValue(), DD4hep::DDSegmentation::TiledLayerSegmentation::LayerDimensions::x, DD4hep::DDSegmentation::Vector3D::x(), DD4hep::DDSegmentation::TiledLayerSegmentation::LayerDimensions::y, and DD4hep::DDSegmentation::Vector3D::y().
gridSizeX()
double DD4hep::DDSegmentation::TiledLayerSegmentation::gridSizeX () const inline
access the default grid size in X
Definition at line 43 of file TiledLayerSegmentation.h.
References _gridSizeX.
gridSizeY()
double DD4hep::DDSegmentation::TiledLayerSegmentation::gridSizeY () const inline
access the default grid size in Y
Definition at line 47 of file TiledLayerSegmentation.h.
References _gridSizeY, layerGridSizeX(), and layerGridSizeY().
identifierLayer()
const std::string& DD4hep::DDSegmentation::TiledLayerSegmentation::identifierLayer () const inline
access the encoding field name used for Y
Definition at line 65 of file TiledLayerSegmentation.h.
References _identifierLayer, and layerDimensions().
identifierX()
const std::string& DD4hep::DDSegmentation::TiledLayerSegmentation::identifierX () const inline
access the encoding field name used for X
Definition at line 57 of file TiledLayerSegmentation.h.
References _identifierX.
identifierY()
const std::string& DD4hep::DDSegmentation::TiledLayerSegmentation::identifierY () const inline
access the encoding field name used for Y
Definition at line 61 of file TiledLayerSegmentation.h.
References _identifierY.
layerDimensions()
TiledLayerSegmentation::LayerDimensions DD4hep::DDSegmentation::TiledLayerSegmentation::layerDimensions (int layerIndex) const
access to the dimensions of the given layer
Definition at line 100 of file TiledLayerSegmentation.cpp.
References _layerDimensionsX, _layerDimensionsY, _layerIndices, and find().
Referenced by cellID(), identifierLayer(), layerGridSizeX(), layerGridSizeY(), and position().
layerGridSizeX()
double DD4hep::DDSegmentation::TiledLayerSegmentation::layerGridSizeX (int layerIndex) const
access the actual grid size in X for a given layer
Definition at line 69 of file TiledLayerSegmentation.cpp.
References _gridSizeX, calculateOptimalCellSize(), and layerDimensions().
Referenced by cellID(), gridSizeY(), and position().
layerGridSizeY()
double DD4hep::DDSegmentation::TiledLayerSegmentation::layerGridSizeY (int layerIndex) const
access the actual grid size in Y for a given layer
Definition at line 75 of file TiledLayerSegmentation.cpp.
References _gridSizeY, calculateOptimalCellSize(), and layerDimensions().
Referenced by cellID(), gridSizeY(), and position().
position()
Vector3D DD4hep::DDSegmentation::TiledLayerSegmentation::position (const CellID & cellID) const virtual
determine the position based on the cell ID
Implements DD4hep::DDSegmentation::Segmentation.
Definition at line 118 of file TiledLayerSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::_decoder, _identifierLayer, _identifierX, _identifierY, DD4hep::DDSegmentation::Segmentation::binToPosition(), calculateOffset(), layerDimensions(), layerGridSizeX(), layerGridSizeY(), DD4hep::DDSegmentation::BitField64::setValue(), DD4hep::DDSegmentation::TiledLayerSegmentation::LayerDimensions::x, and DD4hep::DDSegmentation::TiledLayerSegmentation::LayerDimensions::y.
setGridSizeX()
void DD4hep::DDSegmentation::TiledLayerSegmentation::setGridSizeX (double cellSize) inline
set the default grid size in X
Definition at line 73 of file TiledLayerSegmentation.h.
References _gridSizeX.
setGridSizeY()
void DD4hep::DDSegmentation::TiledLayerSegmentation::setGridSizeY (double cellSize) inline
set the default grid size in Y
Definition at line 77 of file TiledLayerSegmentation.h.
References _gridSizeY.
setIdentifierLayer()
void DD4hep::DDSegmentation::TiledLayerSegmentation::setIdentifierLayer (const std::string & fieldName) inline
set the encoding field name used for layer
Definition at line 90 of file TiledLayerSegmentation.h.
References _identifierLayer, setLayerDimensions(), DD4hep::DDSegmentation::TiledLayerSegmentation::LayerDimensions::x, and DD4hep::DDSegmentation::TiledLayerSegmentation::LayerDimensions::y.
setIdentifierX()
void DD4hep::DDSegmentation::TiledLayerSegmentation::setIdentifierX (const std::string & fieldName) inline
set the encoding field name used for X
Definition at line 82 of file TiledLayerSegmentation.h.
References _identifierX.
setIdentifierY()
void DD4hep::DDSegmentation::TiledLayerSegmentation::setIdentifierY (const std::string & fieldName) inline
set the encoding field name used for Y
Definition at line 86 of file TiledLayerSegmentation.h.
References _identifierY.
setLayerDimensions()
void DD4hep::DDSegmentation::TiledLayerSegmentation::setLayerDimensions (int layerIndex, double x, double y)
set the dimensions of the given layer
Definition at line 81 of file TiledLayerSegmentation.cpp.
References _layerDimensionsX, _layerDimensionsY, _layerIndices, and find().
Referenced by setIdentifierLayer().
Member Data Documentation
_gridSizeX
double DD4hep::DDSegmentation::TiledLayerSegmentation::_gridSizeX protected
Definition at line 100 of file TiledLayerSegmentation.h.
Referenced by gridSizeX(), layerGridSizeX(), setGridSizeX(), and TiledLayerSegmentation().
_gridSizeY
double DD4hep::DDSegmentation::TiledLayerSegmentation::_gridSizeY protected
default grid size in X
Definition at line 101 of file TiledLayerSegmentation.h.
Referenced by gridSizeY(), layerGridSizeY(), setGridSizeY(), and TiledLayerSegmentation().
_identifierLayer
std::string DD4hep::DDSegmentation::TiledLayerSegmentation::_identifierLayer protected
encoding field used for Y
Definition at line 104 of file TiledLayerSegmentation.h.
Referenced by cellID(), identifierLayer(), position(), setIdentifierLayer(), and TiledLayerSegmentation().
_identifierX
std::string DD4hep::DDSegmentation::TiledLayerSegmentation::_identifierX protected
default grid size in Y
Definition at line 102 of file TiledLayerSegmentation.h.
Referenced by cellID(), identifierX(), position(), setIdentifierX(), and TiledLayerSegmentation().
_identifierY
std::string DD4hep::DDSegmentation::TiledLayerSegmentation::_identifierY protected
encoding field used for X
Definition at line 103 of file TiledLayerSegmentation.h.
Referenced by cellID(), identifierY(), position(), setIdentifierY(), and TiledLayerSegmentation().
_layerDimensionsX
std::vector<double> DD4hep::DDSegmentation::TiledLayerSegmentation::_layerDimensionsX protected
list of valid layer identifiers
Definition at line 106 of file TiledLayerSegmentation.h.
Referenced by layerDimensions(), setLayerDimensions(), and TiledLayerSegmentation().
_layerDimensionsY
std::vector<double> DD4hep::DDSegmentation::TiledLayerSegmentation::_layerDimensionsY protected
list of layer x dimensions
Definition at line 107 of file TiledLayerSegmentation.h.
Referenced by layerDimensions(), setLayerDimensions(), and TiledLayerSegmentation().
_layerIndices
std::vector<int> DD4hep::DDSegmentation::TiledLayerSegmentation::_layerIndices protected
encoding field used for the layer
Definition at line 105 of file TiledLayerSegmentation.h.
Referenced by layerDimensions(), setLayerDimensions(), and TiledLayerSegmentation().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/TiledLayerSegmentation.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/TiledLayerSegmentation.cpp