DD4hep: DD4hep::Simulation::Geant4Handle< TYPE > Class Template Reference
DD4hep::Simulation::Geant4Handle< TYPE > Class Template Reference
DD4hep::Simulation components, classes and objects
Handle to Geant4 actions with built-in creation mechanism.
#include <Geant4Config.h>
Public Types
typedef TYPE handled_type
Public Member Functions
Geant4Handle ()
Default constructor.
Geant4Handle (handled_type *typ)
Construction initialized with object pointer.
template<typename T >
Geant4Handle (T *typ)
Cross type initialization.
Geant4Handle (const Geant4Handle &handle)
Copy constructor.
Geant4Handle (Geant4Kernel &, const char *type_name, bool shared=false)
Initializing constructor.
Geant4Handle (Geant4Kernel &, const std::string &type_name, bool shared=false)
Initializing constructor.
Geant4Handle (Geant4Kernel &ctxt, const std::string &type_name, const std::string &detector, bool shared=false)
Constructor only implemented for sensitive objects.
~Geant4Handle ()
Default destructor.
Property & operator[] (const std::string &property_name) const
Property accessor.
Geant4Handle & operator= (const Geant4Handle &handle)
Assignment operator.
Geant4Handle & operator= (handled_type *ptr)
Assignment operator.
bool operator! () const
Validity check.
Geant4Action * action () const
Access to the underlying object.
handled_type * operator-> () const
Access to the underlying object.
operator handled_type * () const
Conversion operator.
handled_type * get () const
Access to the underlying object.
handled_type * release ()
Release the underlying object.
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const char *type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const char *type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const char *type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const char *type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const char *type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const char *type_name, bool shared)
template<>
Geant4Handle (Geant4Kernel &kernel, const string &type_name, const string &detector, bool)
Public Attributes
handled_type * value
Pointer to referenced object.
Protected Member Functions
void checked_assign (TYPE *p)
Detailed Description
template<typename TYPE>
class DD4hep::Simulation::Geant4Handle< TYPE >
Handle to Geant4 actions with built-in creation mechanism.
Author
M.Frank
Version
1.0
Definition at line 29 of file Geant4Config.h.
Member Typedef Documentation
handled_type
template<typename TYPE> typedef TYPE DD4hep::Simulation::Geant4Handle< TYPE >::handled_type
Definition at line 46 of file Geant4Handle.h.
Constructor & Destructor Documentation
Geant4Handle() [1/20]
template<typename TYPE > DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle () explicit
Default constructor.
Definition at line 59 of file Geant4Handle.cpp.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
Geant4Handle() [2/20]
template<typename TYPE > DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle (handled_type * typ)
Construction initialized with object pointer.
Definition at line 63 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
Geant4Handle() [3/20]
template<typename TYPE> template<typename T > DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle (T * typ) inline
Cross type initialization.
Definition at line 54 of file Geant4Handle.h.
References DD4hep::Simulation::Geant4Handle< TYPE >::action(), DD4hep::Simulation::Geant4Handle< TYPE >::checked_assign(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), handle(), DD4hep::Simulation::Geant4Handle< TYPE >::operator!(), DD4hep::Simulation::Geant4Handle< TYPE >::operator->(), DD4hep::Simulation::Geant4Handle< TYPE >::operator=(), DD4hep::Simulation::Geant4Handle< TYPE >::operator[](), DD4hep::Simulation::Geant4Handle< TYPE >::release(), and DD4hep::Simulation::Geant4Handle< TYPE >::~Geant4Handle().
Geant4Handle() [4/20]
template<typename TYPE > DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle (const Geant4Handle< TYPE > & handle)
Copy constructor.
Definition at line 69 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::get(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Geant4Handle() [5/20]
template<typename TYPE > DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared = false)
Initializing constructor.
Definition at line 139 of file Geant4Handle.cpp.
References DD4hep::Simulation::TypeName::split(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Geant4Handle() [6/20]
template<typename TYPE > DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle (Geant4Kernel & kernel, const std::string & type_name, bool shared = false)
Initializing constructor.
Definition at line 134 of file Geant4Handle.cpp.
References DD4hep::Simulation::TypeName::split(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Geant4Handle() [7/20]
template<typename TYPE> DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle (Geant4Kernel & ctxt, const std::string & type_name, const std::string & detector, bool shared = false)
Constructor only implemented for sensitive objects.
~Geant4Handle()
template<typename TYPE > DD4hep::Simulation::Geant4Handle< TYPE >::~Geant4Handle ()
Default destructor.
Definition at line 143 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
Geant4Handle() [8/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4RunAction >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, bool shared)
Definition at line 225 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::runAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [9/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4RunAction >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared)
Definition at line 229 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::runAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [10/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4EventAction >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, bool shared)
Definition at line 234 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::eventAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [11/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4EventAction >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared)
Definition at line 238 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::eventAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [12/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4GeneratorAction >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, bool shared)
Definition at line 243 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::generatorAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [13/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4GeneratorAction >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared)
Definition at line 247 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::generatorAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [14/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4TrackingAction >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, bool shared)
Definition at line 252 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::trackingAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [15/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4TrackingAction >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared)
Definition at line 256 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::trackingAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [16/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4SteppingAction >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, bool shared)
Definition at line 261 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::steppingAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [17/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4SteppingAction >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared)
Definition at line 265 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::steppingAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [18/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4StackingAction >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, bool shared)
Definition at line 270 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::stackingAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [19/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4StackingAction >::Geant4Handle (Geant4Kernel & kernel, const char * type_name, bool shared)
Definition at line 274 of file Geant4Handle.cpp.
References DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4ActionContainer::stackingAction(), and DD4hep::Simulation::KernelHandle::value.
Geant4Handle() [20/20]
template<> DD4hep::Simulation::Geant4Handle< Geant4Sensitive >::Geant4Handle (Geant4Kernel & kernel, const string & type_name, const string & detector, bool)
Definition at line 278 of file Geant4Handle.cpp.
References DD4hep::Geometry::LCDD::detector(), e, DD4hep::ERROR, DD4hep::format(), DD4hep::Simulation::Geant4Kernel::lcdd(), DD4hep::printout(), DD4hep::Simulation::TypeName::split(), DD4hep::Simulation::KernelHandle::value, and DD4hep::Simulation::Geant4ActionContainer::workerContext().
Member Function Documentation
action()
template<typename TYPE > Geant4Action * DD4hep::Simulation::Geant4Handle< TYPE >::action () const
Access to the underlying object.
Definition at line 184 of file Geant4Handle.cpp.
References DD4hep::Simulation::checked_value(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
checked_assign()
template<typename TYPE > void DD4hep::Simulation::Geant4Handle< TYPE >::checked_assign (TYPE * p) protected
Definition at line 155 of file Geant4Handle.cpp.
References DD4hep::Simulation::checked_value(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
get()
template<typename TYPE > TYPE * DD4hep::Simulation::Geant4Handle< TYPE >::get () const
Access to the underlying object.
Definition at line 176 of file Geant4Handle.cpp.
References DD4hep::Simulation::checked_value(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_convertSensitive(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::Simulation::Geant4Handle< TYPE >::operator=().
operator handled_type *()
template<typename TYPE> DD4hep::Simulation::Geant4Handle< TYPE >::operator handled_type * () const
Conversion operator.
operator!()
template<typename TYPE > bool DD4hep::Simulation::Geant4Handle< TYPE >::operator! () const
Validity check.
Definition at line 172 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
operator->()
template<typename TYPE > TYPE * DD4hep::Simulation::Geant4Handle< TYPE >::operator-> () const
Access to the underlying object.
Definition at line 180 of file Geant4Handle.cpp.
References DD4hep::Simulation::checked_value(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
operator=() [1/2]
template<typename TYPE > Geant4Handle< TYPE > & DD4hep::Simulation::Geant4Handle< TYPE >::operator= (const Geant4Handle< TYPE > & handle)
Assignment operator.
Definition at line 188 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::get(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
operator=() [2/2]
template<typename TYPE > Geant4Handle< TYPE > & DD4hep::Simulation::Geant4Handle< TYPE >::operator= (handled_type * ptr)
Assignment operator.
Definition at line 197 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
operator[]()
template<typename TYPE > Property & DD4hep::Simulation::Geant4Handle< TYPE >::operator[] (const std::string & property_name) const
Property accessor.
Definition at line 163 of file Geant4Handle.cpp.
References DD4hep::Simulation::checked_value(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
release()
template<typename TYPE > TYPE * DD4hep::Simulation::Geant4Handle< TYPE >::release ()
Release the underlying object.
Definition at line 149 of file Geant4Handle.cpp.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle().
Member Data Documentation
value
template<typename TYPE> handled_type* DD4hep::Simulation::Geant4Handle< TYPE >::value mutable
Pointer to referenced object.
Definition at line 48 of file Geant4Handle.h.
Referenced by DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4Handle< TYPE >::action(), DD4hep::Simulation::Geant4Handle< TYPE >::checked_assign(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Simulation::Geant4Handle< TYPE >::get(), DD4hep::Simulation::KernelHandle::get(), DD4hep::Simulation::KernelHandle::KernelHandle(), DD4hep::Simulation::KernelHandle::operator handled_type *(), DD4hep::Simulation::Geant4Handle< TYPE >::operator!(), DD4hep::Simulation::Geant4Handle< TYPE >::operator->(), DD4hep::Simulation::KernelHandle::operator->(), DD4hep::Simulation::Geant4Handle< TYPE >::operator=(), DD4hep::Simulation::Geant4Handle< TYPE >::operator[](), DD4hep::Simulation::Geant4Handle< TYPE >::release(), and DD4hep::Simulation::Geant4Handle< TYPE >::~Geant4Handle().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Config.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Handle.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Handle.cpp