DD4hep: DD4hep::Geometry::PlacedVolume Class Reference
DD4hep::Geometry::PlacedVolume Class Reference
DD4hep::Geometry components, classes and objects
Handle class holding a placed volume (also called physical volume)
#include <Volumes.h>
Public Types
typedef PlacedVolumeExtension Object
typedef Object::VolIDs VolIDs
typedef Object::VolID VolID
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
PlacedVolume (const TGeoNode *e)
Constructor to be used when reading the already parsed DOM tree.
PlacedVolume ()
Default constructor.
PlacedVolume (const PlacedVolume &e)
Copy assignment.
template<typename T >
PlacedVolume (const Handle< T > &e)
Copy assignment from other handle type.
PlacedVolume & operator= (const PlacedVolume &v)
Assignment operator (must match copy constructor)
Object * data () const
Check if placement is properly instrumented.
PlacedVolume & addPhysVolID (const std::string &name, int value)
Add identifier.
Material material () const
Volume material.
Volume volume () const
Logical volume of this placement.
Volume motherVol () const
Parent volume (envelope)
const VolIDs & volIDs () const
Access to the volume IDs.
std::string toString () const
String dump.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class holding a placed volume (also called physical volume)
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoNode.html
Author
M.Frank
Version
1.0
Definition at line 135 of file Volumes.h.
Member Typedef Documentation
Object
typedef PlacedVolumeExtension DD4hep::Geometry::PlacedVolume::Object
Definition at line 137 of file Volumes.h.
VolID
typedef Object::VolID DD4hep::Geometry::PlacedVolume::VolID
Definition at line 139 of file Volumes.h.
VolIDs
typedef Object::VolIDs DD4hep::Geometry::PlacedVolume::VolIDs
Definition at line 138 of file Volumes.h.
Constructor & Destructor Documentation
PlacedVolume() [1/4]
DD4hep::Geometry::PlacedVolume::PlacedVolume (const TGeoNode * e) inline
Constructor to be used when reading the already parsed DOM tree.
Definition at line 142 of file Volumes.h.
PlacedVolume() [2/4]
DD4hep::Geometry::PlacedVolume::PlacedVolume () inline
Default constructor.
Definition at line 146 of file Volumes.h.
PlacedVolume() [3/4]
DD4hep::Geometry::PlacedVolume::PlacedVolume (const PlacedVolume & e) inline
Copy assignment.
Definition at line 150 of file Volumes.h.
PlacedVolume() [4/4]
template<typename T > DD4hep::Geometry::PlacedVolume::PlacedVolume (const Handle< T > & e) inline
Copy assignment from other handle type.
Definition at line 154 of file Volumes.h.
Member Function Documentation
addPhysVolID()
PlacedVolume & PlacedVolume::addPhysVolID (const std::string & name, int value)
Add identifier.
Definition at line 378 of file Volumes.cpp.
References _data(), and DD4hep::Geometry::PlacedVolumeExtension::volIDs.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and placeStaves().
data()
PlacedVolume::Object * PlacedVolume::data () const
Check if placement is properly instrumented.
Definition at line 372 of file Volumes.cpp.
References _userExtension().
Referenced by DD4hep::DDRec::findVolume().
material()
Material PlacedVolume::material () const
Volume material.
Definition at line 385 of file Volumes.cpp.
Referenced by DD4hep::Printer< T >::operator()().
motherVol()
Volume PlacedVolume::motherVol () const
Parent volume (envelope)
Definition at line 395 of file Volumes.cpp.
Referenced by DD4hep::Printer< T >::operator()().
operator=()
PlacedVolume& DD4hep::Geometry::PlacedVolume::operator= (const PlacedVolume & v) inline
Assignment operator (must match copy constructor)
Definition at line 158 of file Volumes.h.
References DD4hep::Handle< T >::m_element, and DD4hep::Geometry::DetectorTools::toString().
toString()
string PlacedVolume::toString () const
String dump.
Definition at line 405 of file Volumes.cpp.
References _data(), s, and DD4hep::Geometry::PlacedVolumeExtension::volIDs.
volIDs()
const PlacedVolume::VolIDs & PlacedVolume::volIDs () const
Access to the volume IDs.
Definition at line 400 of file Volumes.cpp.
References _data(), and DD4hep::Geometry::PlacedVolumeExtension::volIDs.
Referenced by DD4hep::Geometry::VolumeManager::addSubdetector(), DD4hep::SurfaceInstaller::install(), and DD4hep::Geometry::LCDDHelper::sensitiveDetector().
volume()
Volume PlacedVolume::volume () const
Logical volume of this placement.
Definition at line 390 of file Volumes.cpp.
Referenced by DD4hep::Geometry::LCDDImp::addDetector(), DD4hep::Geometry::VolumeManager::adoptPlacement(), create_detector(), DD4hep::Simulation::Geant4ConversionHelper::encoding(), DD4hep::DDRec::findVolume(), DD4hep::SurfaceInstaller::install(), DD4hep::Printer< T >::operator()(), DD4hep::SurfaceInstaller::parentVolume(), and DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Volumes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Volumes.cpp