DD4hep: DD4hep::DDSegmentation::Segmentation Class Reference
DD4hep::DDSegmentation::Segmentation Class Reference abstract
Base class for all segmentations.
#include <Segmentation.h>
Public Member Functions
virtual ~Segmentation ()
Destructor.
virtual void addSubsegmentation (long key_min, long key_max, Segmentation *entry)
Add subsegmentation. Call only valid for Multi-segmentations. Default implementation throws an exception.
virtual Vector3D position (const CellID &cellID) const =0
Determine the local position based on the cell ID.
virtual CellID cellID (const Vector3D &localPosition, const Vector3D &globalPosition, const VolumeID &volumeID) const =0
Determine the cell ID based on the position.
virtual VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
virtual void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
virtual std::string fieldDescription () const
Access the encoding string.
virtual const std::string & name () const
Access the segmentation name.
virtual void setName (const std::string &value)
Set the segmentation name.
virtual const std::string & type () const
Access the segmentation type.
virtual const std::string & description () const
Access the description of the segmentation.
virtual BitField64 * decoder () const
Access the underlying decoder.
virtual void setDecoder (BitField64 *decoder)
Set the underlying decoder.
virtual Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
virtual Parameters parameters () const
Access to all parameters.
virtual void setParameters (const Parameters &parameters)
Set all parameters from an existing set of parameters.
virtual std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Protected Member Functions
Segmentation (const std::string &cellEncoding="")
Default constructor used by derived classes passing the encoding string.
Segmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
template<typename TYPE >
void registerParameter (const std::string &nam, const std::string &desc, TYPE &param, const TYPE &defaultVal, UnitType unitTyp=SegmentationParameter::NoUnit, bool isOpt=false)
Add a parameter to this segmentation. Used by derived classes to define their parameters.
void registerIdentifier (const std::string &nam, const std::string &desc, std::string &ident, const std::string &defaultVal)
Add a cell identifier to this segmentation. Used by derived classes to define their required identifiers.
Static Protected Member Functions
static double binToPosition (CellID bin, double cellSize, double offset=0.)
Helper method to convert a bin number to a 1D position.
static int positionToBin (double position, double cellSize, double offset=0.)
Helper method to convert a 1D position to a cell ID.
static double binToPosition (CellID bin, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a bin number to a 1D position given a vector of binBoundaries.
static int positionToBin (double position, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a 1D position to a cell ID given a vector of binBoundaries.
Protected Attributes
std::string _name
The segmentation name.
std::string _type
The segmentation type.
std::string _description
The description of the segmentation.
std::map< std::string, Parameter > _parameters
The parameters for this segmentation.
std::map< std::string, StringParameter > _indexIdentifiers
The indices used for the encoding.
BitField64 * _decoder
The cell ID encoder and decoder.
bool _ownsDecoder
Keeps track of the decoder ownership.
Private Member Functions
Segmentation (const Segmentation &)
No copy constructor allowed.
Detailed Description
Base class for all segmentations.
Definition at line 68 of file Segmentation.h.
Constructor & Destructor Documentation
~Segmentation()
DD4hep::DDSegmentation::Segmentation::~Segmentation () virtual
Destructor.
Definition at line 39 of file Segmentation.cpp.
References _decoder, _ownsDecoder, and _parameters.
Segmentation() [1/3]
DD4hep::DDSegmentation::Segmentation::Segmentation (const std::string & cellEncoding = "") protected
Default constructor used by derived classes passing the encoding string.
Definition at line 28 of file Segmentation.cpp.
Segmentation() [2/3]
DD4hep::DDSegmentation::Segmentation::Segmentation (BitField64 * decoder) protected
Default constructor used by derived classes passing an existing decoder.
Definition at line 34 of file Segmentation.cpp.
Segmentation() [3/3]
DD4hep::DDSegmentation::Segmentation::Segmentation (const Segmentation &) private
No copy constructor allowed.
Member Function Documentation
addSubsegmentation()
void DD4hep::DDSegmentation::Segmentation::addSubsegmentation (long key_min, long key_max, Segmentation * entry) virtual
Add subsegmentation. Call only valid for Multi-segmentations. Default implementation throws an exception.
Reimplemented in DD4hep::DDSegmentation::MultiSegmentation.
Definition at line 54 of file Segmentation.cpp.
References _type.
binToPosition() [1/2]
double DD4hep::DDSegmentation::Segmentation::binToPosition (CellID bin, double cellSize, double offset = 0.) static protected
Helper method to convert a bin number to a 1D position.
Definition at line 144 of file Segmentation.cpp.
Referenced by DD4hep::DDSegmentation::PolarGridRPhi::cellDimensions(), DD4hep::DDSegmentation::PolarGridRPhi2::cellDimensions(), DD4hep::DDSegmentation::CartesianGridXYZ::position(), DD4hep::DDSegmentation::CartesianGridXY::position(), DD4hep::DDSegmentation::CartesianGridXZ::position(), DD4hep::DDSegmentation::PolarGridRPhi::position(), DD4hep::DDSegmentation::CartesianGridYZ::position(), DD4hep::DDSegmentation::WaferGridXY::position(), DD4hep::DDSegmentation::TiledLayerGridXY::position(), DD4hep::DDSegmentation::TiledLayerSegmentation::position(), and DD4hep::DDSegmentation::PolarGridRPhi2::position().
binToPosition() [2/2]
double DD4hep::DDSegmentation::Segmentation::binToPosition (CellID bin, std::vector< double > const & cellBoundaries, double offset = 0.) static protected
Helper method to convert a bin number to a 1D position given a vector of binBoundaries.
Definition at line 157 of file Segmentation.cpp.
cellDimensions()
std::vector< double > DD4hep::DDSegmentation::Segmentation::cellDimensions (const CellID & cellID) const virtual
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Parameters
cellID cellID of the cell for which parameters are returned
Returns
vector<double> in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi
Reimplemented in DD4hep::DDSegmentation::MegatileLayerGridXY, DD4hep::DDSegmentation::TiledLayerGridXY, DD4hep::DDSegmentation::PolarGridRPhi2, DD4hep::DDSegmentation::WaferGridXY, DD4hep::DDSegmentation::CartesianGridYZ, DD4hep::DDSegmentation::PolarGridRPhi, DD4hep::DDSegmentation::CartesianGridXY, DD4hep::DDSegmentation::CartesianGridXZ, DD4hep::DDSegmentation::MultiSegmentation, and DD4hep::DDSegmentation::CartesianGridXYZ.
Definition at line 197 of file Segmentation.cpp.
References _type.
Referenced by DD4hep::DDSegmentation::MultiSegmentation::cellDimensions(), and DD4hep::Geometry::Segmentation::cellDimensions().
cellID()
virtual CellID DD4hep::DDSegmentation::Segmentation::cellID (const Vector3D & localPosition, const Vector3D & globalPosition, const VolumeID & volumeID) const pure virtual
Determine the cell ID based on the position.
Implemented in DD4hep::DDSegmentation::MultiSegmentation, DD4hep::DDSegmentation::PolarGridRPhi2, DD4hep::DDSegmentation::TiledLayerSegmentation, DD4hep::DDSegmentation::TiledLayerGridXY, DD4hep::DDSegmentation::MegatileLayerGridXY, DD4hep::DDSegmentation::WaferGridXY, DD4hep::DDSegmentation::CartesianGridYZ, DD4hep::DDSegmentation::PolarGridRPhi, DD4hep::DDSegmentation::CartesianGridXY, DD4hep::DDSegmentation::CartesianGridXYZ, DD4hep::DDSegmentation::CartesianGridXZ, and DD4hep::DDSegmentation::ProjectiveCylinder.
Referenced by DD4hep::DDSegmentation::MultiSegmentation::cellID(), DD4hep::Geometry::SegmentationObject::cellID(), and DD4hep::Geometry::Segmentation::cellID().
decoder()
virtual BitField64* DD4hep::DDSegmentation::Segmentation::decoder () const inline virtual
Access the underlying decoder.
Definition at line 105 of file Segmentation.h.
Referenced by DD4hep::Geometry::SegmentationObject::decoder(), DD4hep::Geometry::Segmentation::decoder(), and DD4hep::DDSegmentation::MultiSegmentation::discriminator().
description()
virtual const std::string& DD4hep::DDSegmentation::Segmentation::description () const inline virtual
Access the description of the segmentation.
Definition at line 101 of file Segmentation.h.
Referenced by DD4hep::Geometry::SegmentationObject::description().
fieldDescription()
virtual std::string DD4hep::DDSegmentation::Segmentation::fieldDescription () const inline virtual
Access the encoding string.
Definition at line 85 of file Segmentation.h.
Referenced by DD4hep::Geometry::SegmentationObject::fieldDescription().
name()
virtual const std::string& DD4hep::DDSegmentation::Segmentation::name () const inline virtual
Access the segmentation name.
Definition at line 89 of file Segmentation.h.
Referenced by DD4hep::Geometry::SegmentationObject::name(), and DD4hep::DDSegmentation::MultiSegmentation::subsegmentation().
neighbours()
void DD4hep::DDSegmentation::Segmentation::neighbours (const CellID & cellID, std::set< CellID > & neighbours) const virtual
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
Definition at line 70 of file Segmentation.cpp.
References _decoder, _indexIdentifiers, e, DD4hep::DDSegmentation::BitField64::getValue(), and DD4hep::DDSegmentation::BitField64::setValue().
Referenced by DD4hep::Geometry::Segmentation::neighbours().
parameter()
Parameter DD4hep::DDSegmentation::Segmentation::parameter (const std::string & parameterName) const virtual
Access to parameter by name.
Definition at line 103 of file Segmentation.cpp.
References _parameters, _type, and s.
Referenced by DD4hep::Geometry::SegmentationObject::parameter(), and setParameters().
parameters()
Parameters DD4hep::DDSegmentation::Segmentation::parameters () const virtual
Access to all parameters.
Definition at line 115 of file Segmentation.cpp.
References _parameters.
Referenced by DD4hep::Geometry::SegmentationObject::parameters(), and DD4hep::DDSegmentation::MultiSegmentation::subsegmentation().
position()
virtual Vector3D DD4hep::DDSegmentation::Segmentation::position (const CellID & cellID) const pure virtual
Determine the local position based on the cell ID.
Implemented in DD4hep::DDSegmentation::MultiSegmentation, DD4hep::DDSegmentation::PolarGridRPhi2, DD4hep::DDSegmentation::TiledLayerSegmentation, DD4hep::DDSegmentation::TiledLayerGridXY, DD4hep::DDSegmentation::MegatileLayerGridXY, DD4hep::DDSegmentation::WaferGridXY, DD4hep::DDSegmentation::CartesianGridYZ, DD4hep::DDSegmentation::PolarGridRPhi, DD4hep::DDSegmentation::CartesianGridXY, DD4hep::DDSegmentation::CartesianGridXYZ, DD4hep::DDSegmentation::CartesianGridXZ, and DD4hep::DDSegmentation::ProjectiveCylinder.
Referenced by DD4hep::DDSegmentation::MultiSegmentation::position(), DD4hep::Geometry::SegmentationObject::position(), and DD4hep::Geometry::Segmentation::position().
positionToBin() [1/2]
int DD4hep::DDSegmentation::Segmentation::positionToBin (double position, double cellSize, double offset = 0.) static protected
Helper method to convert a 1D position to a cell ID.
Definition at line 149 of file Segmentation.cpp.
References e.
Referenced by DD4hep::DDSegmentation::CartesianGridXY::cellID(), DD4hep::DDSegmentation::CartesianGridXYZ::cellID(), DD4hep::DDSegmentation::ProjectiveCylinder::cellID(), DD4hep::DDSegmentation::CartesianGridXZ::cellID(), DD4hep::DDSegmentation::PolarGridRPhi::cellID(), DD4hep::DDSegmentation::CartesianGridYZ::cellID(), DD4hep::DDSegmentation::WaferGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerSegmentation::cellID(), and DD4hep::DDSegmentation::PolarGridRPhi2::cellID().
positionToBin() [2/2]
int DD4hep::DDSegmentation::Segmentation::positionToBin (double position, std::vector< double > const & cellBoundaries, double offset = 0.) static protected
Helper method to convert a 1D position to a cell ID given a vector of binBoundaries.
Definition at line 161 of file Segmentation.cpp.
References e.
registerIdentifier()
void DD4hep::DDSegmentation::Segmentation::registerIdentifier (const std::string & nam, const std::string & desc, std::string & ident, const std::string & defaultVal) protected
Add a cell identifier to this segmentation. Used by derived classes to define their required identifiers.
Definition at line 134 of file Segmentation.cpp.
References _indexIdentifiers, _parameters, and DD4hep::DDSegmentation::SegmentationParameter::NoUnit.
Referenced by DD4hep::DDSegmentation::CartesianGridXY::CartesianGridXY(), DD4hep::DDSegmentation::CartesianGridXYZ::CartesianGridXYZ(), DD4hep::DDSegmentation::CartesianGridXZ::CartesianGridXZ(), DD4hep::DDSegmentation::CartesianGridYZ::CartesianGridYZ(), DD4hep::DDSegmentation::MegatileLayerGridXY::MegatileLayerGridXY(), DD4hep::DDSegmentation::PolarGridRPhi::PolarGridRPhi(), DD4hep::DDSegmentation::PolarGridRPhi2::PolarGridRPhi2(), DD4hep::DDSegmentation::ProjectiveCylinder::ProjectiveCylinder(), DD4hep::DDSegmentation::TiledLayerGridXY::TiledLayerGridXY(), DD4hep::DDSegmentation::TiledLayerSegmentation::TiledLayerSegmentation(), and DD4hep::DDSegmentation::WaferGridXY::WaferGridXY().
registerParameter()
template<typename TYPE > void DD4hep::DDSegmentation::Segmentation::registerParameter (const std::string & nam, const std::string & desc, TYPE & param, const TYPE & defaultVal, UnitType unitTyp = SegmentationParameter::NoUnit, bool isOpt = false) inline protected
Add a parameter to this segmentation. Used by derived classes to define their parameters.
Definition at line 131 of file Segmentation.h.
Referenced by DD4hep::DDSegmentation::CartesianGridXY::CartesianGridXY(), DD4hep::DDSegmentation::CartesianGridXYZ::CartesianGridXYZ(), DD4hep::DDSegmentation::CartesianGridXZ::CartesianGridXZ(), DD4hep::DDSegmentation::CartesianGridYZ::CartesianGridYZ(), DD4hep::DDSegmentation::MegatileLayerGridXY::MegatileLayerGridXY(), DD4hep::DDSegmentation::PolarGridRPhi::PolarGridRPhi(), DD4hep::DDSegmentation::PolarGridRPhi2::PolarGridRPhi2(), DD4hep::DDSegmentation::ProjectiveCylinder::ProjectiveCylinder(), DD4hep::DDSegmentation::TiledLayerGridXY::TiledLayerGridXY(), DD4hep::DDSegmentation::TiledLayerSegmentation::TiledLayerSegmentation(), and DD4hep::DDSegmentation::WaferGridXY::WaferGridXY().
setDecoder()
void DD4hep::DDSegmentation::Segmentation::setDecoder (BitField64 * decoder) virtual
Set the underlying decoder.
Reimplemented in DD4hep::DDSegmentation::MultiSegmentation.
Definition at line 93 of file Segmentation.cpp.
References _decoder, and _ownsDecoder.
Referenced by DD4hep::Geometry::SegmentationObject::setDecoder(), DD4hep::Geometry::Segmentation::setDecoder(), and DD4hep::DDSegmentation::MultiSegmentation::setDecoder().
setName()
virtual void DD4hep::DDSegmentation::Segmentation::setName (const std::string & value) inline virtual
Set the segmentation name.
Definition at line 93 of file Segmentation.h.
Referenced by DD4hep::Handle< ReadoutObject >::assign(), and DD4hep::Geometry::SegmentationObject::setName().
setParameters()
void DD4hep::DDSegmentation::Segmentation::setParameters (const Parameters & parameters) virtual
Set all parameters from an existing set of parameters.
Definition at line 125 of file Segmentation.cpp.
References DD4hep::DDSegmentation::SegmentationParameter::name(), parameter(), and DD4hep::DDSegmentation::SegmentationParameter::value().
Referenced by DD4hep::Geometry::SegmentationObject::setParameters().
type()
virtual const std::string& DD4hep::DDSegmentation::Segmentation::type () const inline virtual
Access the segmentation type.
Definition at line 97 of file Segmentation.h.
Referenced by DD4hep::Geometry::SegmentationObject::type().
volumeID()
VolumeID DD4hep::DDSegmentation::Segmentation::volumeID (const CellID & cellID) const virtual
Determine the volume ID from the full cell ID by removing all local fields.
Definition at line 59 of file Segmentation.cpp.
References _decoder, _indexIdentifiers, DD4hep::DDSegmentation::BitField64::getValue(), and DD4hep::DDSegmentation::BitField64::setValue().
Referenced by DD4hep::Geometry::SegmentationObject::volumeID(), and DD4hep::Geometry::Segmentation::volumeID().
Member Data Documentation
_decoder
BitField64* DD4hep::DDSegmentation::Segmentation::_decoder mutable protected
The cell ID encoder and decoder.
Definition at line 161 of file Segmentation.h.
Referenced by DD4hep::DDSegmentation::PolarGridRPhi::cellDimensions(), DD4hep::DDSegmentation::PolarGridRPhi2::cellDimensions(), DD4hep::DDSegmentation::MegatileLayerGridXY::cellDimensions(), DD4hep::DDSegmentation::CartesianGridXY::cellID(), DD4hep::DDSegmentation::CartesianGridXYZ::cellID(), DD4hep::DDSegmentation::ProjectiveCylinder::cellID(), DD4hep::DDSegmentation::CartesianGridXZ::cellID(), DD4hep::DDSegmentation::PolarGridRPhi::cellID(), DD4hep::DDSegmentation::CartesianGridYZ::cellID(), DD4hep::DDSegmentation::WaferGridXY::cellID(), DD4hep::DDSegmentation::MegatileLayerGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerGridXY::cellID(), DD4hep::DDSegmentation::TiledLayerSegmentation::cellID(), DD4hep::DDSegmentation::PolarGridRPhi2::cellID(), neighbours(), DD4hep::DDSegmentation::ProjectiveCylinder::phi(), DD4hep::DDSegmentation::CartesianGridXY::position(), DD4hep::DDSegmentation::ProjectiveCylinder::position(), DD4hep::DDSegmentation::CartesianGridXZ::position(), DD4hep::DDSegmentation::CartesianGridXYZ::position(), DD4hep::DDSegmentation::PolarGridRPhi::position(), DD4hep::DDSegmentation::CartesianGridYZ::position(), DD4hep::DDSegmentation::MegatileLayerGridXY::position(), DD4hep::DDSegmentation::WaferGridXY::position(), DD4hep::DDSegmentation::TiledLayerGridXY::position(), DD4hep::DDSegmentation::TiledLayerSegmentation::position(), DD4hep::DDSegmentation::PolarGridRPhi2::position(), setDecoder(), DD4hep::DDSegmentation::ProjectiveCylinder::theta(), volumeID(), and ~Segmentation().
_description
std::string DD4hep::DDSegmentation::Segmentation::_description protected
The description of the segmentation.
Definition at line 155 of file Segmentation.h.
Referenced by DD4hep::DDSegmentation::CartesianGridXY::CartesianGridXY(), DD4hep::DDSegmentation::CartesianGridXYZ::CartesianGridXYZ(), DD4hep::DDSegmentation::CartesianGridXZ::CartesianGridXZ(), DD4hep::DDSegmentation::CartesianGridYZ::CartesianGridYZ(), DD4hep::DDSegmentation::MegatileLayerGridXY::MegatileLayerGridXY(), DD4hep::DDSegmentation::MultiSegmentation::MultiSegmentation(), DD4hep::DDSegmentation::PolarGridRPhi::PolarGridRPhi(), DD4hep::DDSegmentation::PolarGridRPhi2::PolarGridRPhi2(), DD4hep::DDSegmentation::ProjectiveCylinder::ProjectiveCylinder(), DD4hep::DDSegmentation::TiledLayerGridXY::TiledLayerGridXY(), DD4hep::DDSegmentation::TiledLayerSegmentation::TiledLayerSegmentation(), and DD4hep::DDSegmentation::WaferGridXY::WaferGridXY().
_indexIdentifiers
std::map<std::string, StringParameter> DD4hep::DDSegmentation::Segmentation::_indexIdentifiers protected
The indices used for the encoding.
Definition at line 159 of file Segmentation.h.
Referenced by neighbours(), registerIdentifier(), and volumeID().
_name
std::string DD4hep::DDSegmentation::Segmentation::_name protected
The segmentation name.
Definition at line 151 of file Segmentation.h.
_ownsDecoder
bool DD4hep::DDSegmentation::Segmentation::_ownsDecoder protected
Keeps track of the decoder ownership.
Definition at line 163 of file Segmentation.h.
Referenced by setDecoder(), and ~Segmentation().
_parameters
std::map<std::string, Parameter> DD4hep::DDSegmentation::Segmentation::_parameters protected
The parameters for this segmentation.
Definition at line 157 of file Segmentation.h.
Referenced by parameter(), parameters(), registerIdentifier(), and ~Segmentation().
_type
std::string DD4hep::DDSegmentation::Segmentation::_type protected
The segmentation type.
Definition at line 153 of file Segmentation.h.
Referenced by addSubsegmentation(), DD4hep::DDSegmentation::CartesianGridXY::CartesianGridXY(), DD4hep::DDSegmentation::CartesianGridXYZ::CartesianGridXYZ(), DD4hep::DDSegmentation::CartesianGridXZ::CartesianGridXZ(), DD4hep::DDSegmentation::CartesianGridYZ::CartesianGridYZ(), cellDimensions(), DD4hep::DDSegmentation::MegatileLayerGridXY::MegatileLayerGridXY(), DD4hep::DDSegmentation::MultiSegmentation::MultiSegmentation(), parameter(), DD4hep::DDSegmentation::PolarGridRPhi::PolarGridRPhi(), DD4hep::DDSegmentation::PolarGridRPhi2::PolarGridRPhi2(), DD4hep::DDSegmentation::ProjectiveCylinder::ProjectiveCylinder(), DD4hep::DDSegmentation::TiledLayerGridXY::TiledLayerGridXY(), DD4hep::DDSegmentation::TiledLayerSegmentation::TiledLayerSegmentation(), and DD4hep::DDSegmentation::WaferGridXY::WaferGridXY().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/Segmentation.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/Segmentation.cpp