DD4hep: DD4hep::Simulation::Test::Geant4TestTrackAction Class Reference
DD4hep::Simulation::Test::Geant4TestTrackAction Class Reference
DD4hep::Simulation components, classes and objects
Example tracking action doing nothing, but print.
#include <Geant4TestActions.h>
Public Member Functions
Geant4TestTrackAction (Geant4Context *c, const std::string &n)
Standard constructor with initializing arguments.
virtual ~Geant4TestTrackAction ()
Default destructor.
virtual void begin (const G4Track *)
Begin-of-tracking callback.
virtual void end (const G4Track *)
End-of-tracking callback.
Public Member Functions inherited from DD4hep::Simulation::Geant4TrackingAction
Geant4TrackingAction (Geant4Context *context, const std::string &name="")
Standard constructor.
virtual ~Geant4TrackingAction ()
Default destructor.
G4TrackingManager * trackMgr () const
Access the Geant4 tracking manager. Only use between tracking pre- and post action.
void mark (const G4Track *track) const
Mark the track to be kept for MC truth propagation.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Public Member Functions inherited from DD4hep::Simulation::Test::Geant4TestBase
Geant4TestBase (Geant4Action *action, const std::string &typ)
Standard constructor.
virtual ~Geant4TestBase ()
Default destructor.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4TrackingAction
typedef Geant4SharedTrackingAction shared_type
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Protected Attributes inherited from DD4hep::Simulation::Test::Geant4TestBase
int m_value1
double m_value2
std::string m_value3
std::string m_type
Detailed Description
Example tracking action doing nothing, but print.
Author
M.Frank
Version
1.0
Definition at line 124 of file Geant4TestActions.h.
Constructor & Destructor Documentation
Geant4TestTrackAction()
Geant4TestTrackAction::Geant4TestTrackAction (Geant4Context * c, const std::string & n)
Standard constructor with initializing arguments.
Definition at line 149 of file Geant4TestActions.cpp.
References DD4hep::InstanceCount::increment().
~Geant4TestTrackAction()
Geant4TestTrackAction::~Geant4TestTrackAction () virtual
Default destructor.
Definition at line 155 of file Geant4TestActions.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
begin()
void Geant4TestTrackAction::begin (const G4Track * trk) virtual
Begin-of-tracking callback.
Reimplemented from DD4hep::Simulation::Geant4TrackingAction.
Definition at line 159 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, and DD4hep::Simulation::Geant4Context::run().
end()
void Geant4TestTrackAction::end (const G4Track * trk) virtual
End-of-tracking callback.
Reimplemented from DD4hep::Simulation::Geant4TrackingAction.
Definition at line 167 of file Geant4TestActions.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Test::Geant4TestBase::m_type, PRINT, and DD4hep::Simulation::Geant4Context::run().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TestActions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TestActions.cpp