DD4hep: DDSurfaces::IMaterial Class Reference
DDSurfaces::IMaterial Class Reference abstract
#include <IMaterial.h>
Public Member Functions
virtual ~IMaterial ()
Destructor.
virtual std::string name () const =0
material name
virtual double A () const =0
averaged atomic number
virtual double Z () const =0
averaged proton number
virtual double density () const =0
density - units ?
virtual double radiationLength () const =0
radiation length - units ?
virtual double interactionLength () const =0
interaction length - units ?
Protected Member Functions
IMaterial & operator= (const IMaterial &)
Assignment operator.
Detailed Description
Interface for material description for tracking.
Author
F.Gaede, DESY
Version
$Id$
Date
Apr 6 2014
Definition at line 16 of file IMaterial.h.
Constructor & Destructor Documentation
~IMaterial()
virtual DDSurfaces::IMaterial::~IMaterial () inline virtual
Destructor.
Definition at line 25 of file IMaterial.h.
References A(), density(), interactionLength(), name(), radiationLength(), and Z().
Member Function Documentation
A()
virtual double DDSurfaces::IMaterial::A () const pure virtual
averaged atomic number
Implemented in DD4hep::DDRec::MaterialData.
Referenced by DDSurfaces::operator<<(), DD4hep::DDRec::MaterialData::operator=(), and ~IMaterial().
density()
virtual double DDSurfaces::IMaterial::density () const pure virtual
density - units ?
Implemented in DD4hep::DDRec::MaterialData.
Referenced by DDSurfaces::operator<<(), DD4hep::DDRec::MaterialData::operator=(), and ~IMaterial().
interactionLength()
virtual double DDSurfaces::IMaterial::interactionLength () const pure virtual
interaction length - units ?
Implemented in DD4hep::DDRec::MaterialData.
Referenced by DDSurfaces::operator<<(), DD4hep::DDRec::MaterialData::operator=(), and ~IMaterial().
name()
virtual std::string DDSurfaces::IMaterial::name () const pure virtual
material name
Implemented in DD4hep::DDRec::MaterialData.
Referenced by DDSurfaces::operator<<(), DD4hep::DDRec::MaterialData::operator=(), and ~IMaterial().
operator=()
IMaterial& DDSurfaces::IMaterial::operator= (const IMaterial &) inline protected
Assignment operator.
Definition at line 20 of file IMaterial.h.
radiationLength()
virtual double DDSurfaces::IMaterial::radiationLength () const pure virtual
radiation length - units ?
Implemented in DD4hep::DDRec::MaterialData.
Referenced by DDSurfaces::operator<<(), DD4hep::DDRec::MaterialData::operator=(), and ~IMaterial().
Z()
virtual double DDSurfaces::IMaterial::Z () const pure virtual
averaged proton number
Implemented in DD4hep::DDRec::MaterialData.
Referenced by DD4hep::DDRec::Surface::innerMaterial(), DDSurfaces::operator<<(), DD4hep::DDRec::MaterialData::operator=(), DD4hep::DDRec::Surface::outerMaterial(), and ~IMaterial().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSurfaces/include/DDSurfaces/IMaterial.h