DD4hep: DD4hep::Simulation::Geant4Kernel Class Reference
DD4hep::Simulation::Geant4Kernel Class Reference
DD4hep::Simulation components, classes and objects
Class, which allows all Geant4Action derivatives to access the DDG4 kernel structures.
#include <Geant4Kernel.h>
Classes
class PhaseSelector
Embedded helper class to facilitate map access to the phases.
Public Types
enum State { SETTING_UP, INITIALIZED }
typedef DD4hep::Geometry::LCDD LCDD
typedef std::map< unsigned long, Geant4Kernel * > Workers
typedef std::map< std::string, Geant4ActionPhase * > Phases
typedef std::map< std::string, Geant4Action * > GlobalActions
typedef std::map< std::string, int > ClientOutputLevels
Public Member Functions
Geant4Kernel (LCDD &lcdd)
Standard constructor for the master instance.
Geant4Kernel & master () const
Thread's master context.
Geant4Kernel & shared () const
Shared action context.
bool isMultiThreaded () const
virtual ~Geant4Kernel ()
Default destructor.
const Phases & phases () const
Access phase phases.
LCDD & lcdd () const
Access to detector description.
G4TrackingManager * trackMgr () const
Access the tracking manager.
void setTrackMgr (G4TrackingManager *mgr)
Access the tracking manager.
const std::string & directoryName () const
Access the command directory.
unsigned long id () const
Access worker identifier.
G4RunManager & runManager ()
Access to the Geant4 run manager.
PropertyManager & properties ()
Access to the properties of the object.
void printProperties () const
Print the property values.
template<typename T >
Geant4Kernel & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Kernel & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the global output level of the kernel object; returns previous value.
void setOutputLevel (const std::string object, PrintLevel new_level)
Fill cache with the global output level of a named object. Must be set before instantiation.
PrintLevel getOutputLevel (const std::string object) const
Retrieve the global output level of a named object.
Geant4Kernel & registerGlobalAction (Geant4Action *action)
Register action by name to be retrieved when setting up and connecting action objects.
Geant4Action * globalAction (const std::string &action_name, bool throw_if_not_present=true)
Retrieve action from repository.
Geant4Kernel & registerGlobalFilter (Geant4Action *filter)
Register filter by name to be retrieved when setting up and connecting filter objects.
Geant4Action * globalFilter (const std::string &filter_name, bool throw_if_not_present=true)
Retrieve filter from repository.
Geant4ActionPhase * getPhase (const std::string &name)
Access phase by name.
virtual Geant4ActionPhase * addSimplePhase (const std::string &name, bool throw_on_exist)
Add a new phase to the phase.
virtual Geant4ActionPhase * addPhase (const std::string &name, const std::type_info &arg1, const std::type_info &arg2, const std::type_info &arg3, bool throw_on_exist)
Add a new phase to the phase.
template<typename A0 >
Geant4ActionPhase * addPhase (const std::string &name, bool throw_on_exist=true)
Add a new phase to the phase.
template<typename A0 , typename A1 >
Geant4ActionPhase * addPhase (const std::string &name, bool throw_on_exist=true)
Add a new phase to the phase.
template<typename A0 , typename A1 , typename A2 >
Geant4ActionPhase * addPhase (const std::string &name, bool throw_on_exist=true)
Add a new phase to the phase.
virtual bool removePhase (const std::string &name)
Remove an existing phase from the phase. If not existing returns false.
virtual void destroyPhases ()
Destroy all phases. To be called only at shutdown.
virtual bool executePhase (const std::string &name, const void **args) const
Execute phase action if it exists.
virtual void loadGeometry (const std::string &compact_file)
Construct detector geometry using lcdd plugin.
virtual void loadXML (const char *fname)
Load XML file.
virtual Geant4Kernel & createWorker ()
Create identified worker instance.
Geant4Kernel & worker (unsigned long thread_identifier, bool create_if=false)
Access worker instance by it's identifier.
int numWorkers () const
Access number of workers.
virtual int configure ()
Run the simulation: Configure Geant4.
virtual int initialize ()
Run the simulation: Initialize Geant4.
virtual int run ()
Run the simulation: Simulate the number of events given by the property "NumEvents".
virtual int runEvents (int num_events)
Run the simulation: Simulate the number of events "num_events" and modify the property "NumEvents".
virtual int terminate ()
Run the simulation: Terminate Geant4.
Public Member Functions inherited from DD4hep::Simulation::Geant4ActionContainer
Geant4Context * workerContext ()
Thread's Geant4 execution context.
Geant4GeneratorActionSequence * generatorAction (bool create)
Access generator action sequence.
Geant4GeneratorActionSequence & generatorAction ()
Access generator action sequence.
Geant4RunActionSequence * runAction (bool create)
Access run action sequence.
Geant4RunActionSequence & runAction ()
Access run action sequence.
Geant4EventActionSequence * eventAction (bool create)
Access run action sequence.
Geant4EventActionSequence & eventAction ()
Access run action sequence.
Geant4SteppingActionSequence * steppingAction (bool create)
Access stepping action sequence.
Geant4SteppingActionSequence & steppingAction ()
Access stepping action sequence.
Geant4TrackingActionSequence * trackingAction (bool create)
Access tracking action sequence.
Geant4TrackingActionSequence & trackingAction ()
Access tracking action sequence.
Geant4StackingActionSequence * stackingAction (bool create)
Access stacking action sequence.
Geant4StackingActionSequence & stackingAction ()
Access stacking action sequence.
Geant4DetectorConstructionSequence * detectorConstruction (bool create)
Access detector construcion action sequence (geometry+sensitives+field)
Geant4DetectorConstructionSequence & detectorConstruction ()
Access detector construcion action sequence (geometry+sensitives+field)
Geant4SensDetSequences & sensitiveActions () const
Access to the sensitive detector sequences from the actioncontainer object.
Geant4SensDetActionSequence * sensitiveAction (const std::string &name)
Access to the sensitive detector action from the actioncontainer object.
Geant4PhysicsListActionSequence * physicsList (bool create)
Access to the physics list.
Geant4PhysicsListActionSequence & physicsList ()
Access to the physics list.
Geant4UserInitializationSequence * userInitialization (bool create)
Access to the user initialization object.
Geant4UserInitializationSequence & userInitialization ()
Access to the user initialization object.
Static Public Member Functions
static unsigned long int thread_self ()
Access thread identifier.
static Geant4Kernel & instance (LCDD &lcdd)
Instance accessor.
Public Attributes
class DD4hep::Simulation::Geant4Kernel::PhaseSelector phase
Protected Member Functions
bool isMaster () const
bool isWorker () const
Geant4Kernel (Geant4Kernel *m, unsigned long identifier)
Standard constructor for workers.
Protected Member Functions inherited from DD4hep::Simulation::Geant4ActionContainer
template<typename C >
bool registerSequence (C *&seq, const std::string &name)
Helper to register an action sequence.
Geant4ActionContainer (Geant4Context *ctxt=0)
Standard constructor.
virtual ~Geant4ActionContainer ()
Default destructor.
void setContext (Geant4Context *ctxt)
Set the thread's context.
Protected Attributes
G4RunManager * m_runManager
Reference to the run manager.
G4UIdirectory * m_control
Top level control directory.
G4TrackingManager * m_trackMgr
Reference to Geant4 track manager.
LCDD * m_lcdd
Detector description object.
PropertyManager m_properties
Property pool.
Phases m_phases
Action phases.
Workers m_workers
Worker threads.
GlobalActions m_globalActions
Globally registered actions.
GlobalActions m_globalFilters
Globally registered filters of sensitive detectors.
std::string m_controlName
Property: Name of the G4UI command tree.
std::string m_uiName
Property: Name of the UI action. Must be member of the global actions.
long m_numEvent
Property: Number of events to be executed in batch mode.
int m_outputLevel
Property: Output level.
ClientOutputLevels m_clientLevels
Property: Client output levels.
int m_numThreads
Property: Running in multi threaded context.
unsigned long m_id
Flag: Master instance (id<0) or worker (id >= 0)
unsigned long m_ident
Geant4Kernel * m_master
Parent reference.
Geant4Kernel * m_shared
Geant4Context * m_threadContext
Protected Attributes inherited from DD4hep::Simulation::Geant4ActionContainer
Geant4Context * m_context
Geant4 worker context (thread specific)
Geant4GeneratorActionSequence * m_generatorAction
Reference to the Geant4 primary generator action.
Geant4RunActionSequence * m_runAction
Reference to the Geant4 run action.
Geant4EventActionSequence * m_eventAction
Reference to the Geant4 event action.
Geant4TrackingActionSequence * m_trackingAction
Reference to the Geant4 track action.
Geant4SteppingActionSequence * m_steppingAction
Reference to the Geant4 step action.
Geant4StackingActionSequence * m_stackingAction
Reference to the Geant4 stacking action.
Geant4DetectorConstructionSequence * m_constructionAction
Reference to the Geant4 detector construction sequence.
Geant4SensDetSequences * m_sensDetActions
Reference to the Geant4 sensitive action sequences.
Geant4PhysicsListActionSequence * m_physicsList
Reference to the Geant4 physics list.
Geant4UserInitializationSequence * m_userInit
Reference to the user initialization object.
Detailed Description
Class, which allows all Geant4Action derivatives to access the DDG4 kernel structures.
Author
M.Frank
Version
1.0
Definition at line 43 of file Geant4Kernel.h.
Member Typedef Documentation
ClientOutputLevels
typedef std::map<std::string,int> DD4hep::Simulation::Geant4Kernel::ClientOutputLevels
Definition at line 49 of file Geant4Kernel.h.
GlobalActions
typedef std::map<std::string, Geant4Action*> DD4hep::Simulation::Geant4Kernel::GlobalActions
Definition at line 48 of file Geant4Kernel.h.
LCDD
typedef DD4hep::Geometry::LCDD DD4hep::Simulation::Geant4Kernel::LCDD
Definition at line 45 of file Geant4Kernel.h.
Phases
typedef std::map<std::string, Geant4ActionPhase*> DD4hep::Simulation::Geant4Kernel::Phases
Definition at line 47 of file Geant4Kernel.h.
Workers
typedef std::map<unsigned long, Geant4Kernel*> DD4hep::Simulation::Geant4Kernel::Workers
Definition at line 46 of file Geant4Kernel.h.
Member Enumeration Documentation
State
enum DD4hep::Simulation::Geant4Kernel::State
Enumerator
SETTING_UP
INITIALIZED
Definition at line 140 of file Geant4Kernel.h.
Constructor & Destructor Documentation
Geant4Kernel() [1/2]
Geant4Kernel::Geant4Kernel (Geant4Kernel * m, unsigned long identifier) protected
Standard constructor for workers.
Standard constructor.
Definition at line 98 of file Geant4Kernel.cpp.
References declareProperty(), DD4hep::InstanceCount::increment(), m_clientLevels, m_control, m_controlName, m_ident, m_lcdd, m_master, m_outputLevel, m_uiName, m_workers, and DD4hep::Simulation::Geant4ActionContainer::setContext().
Referenced by createWorker(), instance(), and isWorker().
Geant4Kernel() [2/2]
Geant4Kernel::Geant4Kernel (LCDD & lcdd)
Standard constructor for the master instance.
Standard constructor.
Definition at line 78 of file Geant4Kernel.cpp.
References DD4hep::Geometry::LCDD::addExtension(), DD4hep::DEBUG, declareProperty(), DD4hep::InstanceCount::increment(), m_clientLevels, m_control, m_controlName, m_ident, m_lcdd, m_numEvent, m_numThreads, m_outputLevel, m_uiName, and DD4hep::Simulation::Geant4ActionContainer::setContext().
~Geant4Kernel()
Geant4Kernel::~Geant4Kernel () virtual
Default destructor.
Definition at line 117 of file Geant4Kernel.cpp.
References DD4hep::InstanceCount::decrement(), DD4hep::deletePtr(), DD4hep::Geometry::LCDD::destroyInstance(), DD4hep::destroyObjects(), destroyPhases(), isMaster(), m_globalActions, m_globalFilters, m_lcdd, m_runManager, m_workers, DD4hep::releaseObjects(), DD4hep::Geometry::LCDD::removeExtension(), and DD4hep::Simulation::Geant4ActionContainer::terminate().
Member Function Documentation
addPhase() [1/4]
virtual Geant4ActionPhase* DD4hep::Simulation::Geant4Kernel::addPhase (const std::string & name, const std::type_info & arg1, const std::type_info & arg2, const std::type_info & arg3, bool throw_on_exist) virtual
Add a new phase to the phase.
Referenced by addPhase(), addSimplePhase(), id(), and DD4hep::Converter< T, ARG >::operator()().
addPhase() [2/4]
template<typename A0 > Geant4ActionPhase* DD4hep::Simulation::Geant4Kernel::addPhase (const std::string & name, bool throw_on_exist = true) inline
Add a new phase to the phase.
Definition at line 216 of file Geant4Kernel.h.
References addPhase().
addPhase() [3/4]
template<typename A0 , typename A1 > Geant4ActionPhase* DD4hep::Simulation::Geant4Kernel::addPhase (const std::string & name, bool throw_on_exist = true) inline
Add a new phase to the phase.
Definition at line 221 of file Geant4Kernel.h.
References addPhase().
addPhase() [4/4]
template<typename A0 , typename A1 , typename A2 > Geant4ActionPhase* DD4hep::Simulation::Geant4Kernel::addPhase (const std::string & name, bool throw_on_exist = true) inline
Add a new phase to the phase.
Definition at line 226 of file Geant4Kernel.h.
References addPhase(), configure(), createWorker(), destroyPhases(), executePhase(), initialize(), loadGeometry(), loadXML(), numWorkers(), removePhase(), run(), runEvents(), terminate(), and worker().
addSimplePhase()
Geant4ActionPhase * Geant4Kernel::addSimplePhase (const std::string & name, bool throw_on_exist) virtual
Add a new phase to the phase.
Definition at line 415 of file Geant4Kernel.cpp.
References addPhase(), DD4hep::format(), m_phases, and DD4hep::Simulation::Geant4ActionContainer::workerContext().
Referenced by id().
configure()
int Geant4Kernel::configure () virtual
Run the simulation: Configure Geant4.
Definition at line 277 of file Geant4Kernel.cpp.
References DD4hep::Simulation::Geant4Exec::configure().
Referenced by addPhase().
createWorker()
Geant4Kernel & Geant4Kernel::createWorker () virtual
Create identified worker instance.
Geant4 Multi threading support
Definition at line 160 of file Geant4Kernel.cpp.
References DD4hep::format(), Geant4Kernel(), DD4hep::INFO, isMaster(), m_workers, DD4hep::printout(), and thread_self().
Referenced by addPhase(), and worker().
declareProperty() [1/2]
template<typename T > Geant4Kernel & DD4hep::Simulation::Geant4Kernel::declareProperty (const std::string & nam, T & val)
Declare property.
Definition at line 262 of file Geant4Kernel.h.
References DD4hep::PropertyManager::add(), and m_properties.
Referenced by Geant4Kernel(), and id().
declareProperty() [2/2]
template<typename T > Geant4Kernel & DD4hep::Simulation::Geant4Kernel::declareProperty (const char * nam, T & val)
Declare property.
Definition at line 268 of file Geant4Kernel.h.
References DD4hep::PropertyManager::add(), and m_properties.
destroyPhases()
void Geant4Kernel::destroyPhases () virtual
Destroy all phases. To be called only at shutdown.
Definition at line 447 of file Geant4Kernel.cpp.
References DD4hep::destroyObjects(), and m_phases.
Referenced by addPhase(), terminate(), and ~Geant4Kernel().
directoryName()
const std::string& DD4hep::Simulation::Geant4Kernel::directoryName () const inline
Access the command directory.
Definition at line 159 of file Geant4Kernel.h.
References m_controlName.
executePhase()
bool Geant4Kernel::executePhase (const std::string & name, const void ** args) const virtual
Execute phase action if it exists.
Definition at line 395 of file Geant4Kernel.cpp.
References m_phases.
Referenced by addPhase(), DD4hep::Simulation::Geant4UserEventAction::BeginOfEventAction(), DD4hep::Simulation::Geant4UserRunAction::BeginOfRunAction(), DD4hep::Simulation::Geant4Exec::configure(), DD4hep::Simulation::Geant4UserEventAction::EndOfEventAction(), DD4hep::Simulation::Geant4UserRunAction::EndOfRunAction(), DD4hep::Simulation::Geant4Exec::initialize(), DD4hep::Simulation::Geant4Exec::run(), and DD4hep::Simulation::Geant4Exec::terminate().
getOutputLevel()
DD4hep::PrintLevel Geant4Kernel::getOutputLevel (const std::string object) const
Retrieve the global output level of a named object.
Definition at line 223 of file Geant4Kernel.cpp.
References m_clientLevels, and DD4hep::printLevel().
Referenced by DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), id(), and DD4hep::Simulation::TypeName::split().
getPhase()
Geant4ActionPhase * Geant4Kernel::getPhase (const std::string & name)
Access phase by name.
Definition at line 405 of file Geant4Kernel.cpp.
References DD4hep::format(), and m_phases.
Referenced by id(), and DD4hep::Simulation::Geant4Kernel::PhaseSelector::operator[]().
globalAction()
Geant4Action * Geant4Kernel::globalAction (const std::string & action_name, bool throw_if_not_present = true)
Retrieve action from repository.
Definition at line 348 of file Geant4Kernel.cpp.
References DD4hep::format(), and m_globalActions.
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_createAction(), id(), and DD4hep::Simulation::Geant4Exec::run().
globalFilter()
Geant4Action * Geant4Kernel::globalFilter (const std::string & filter_name, bool throw_if_not_present = true)
Retrieve filter from repository.
Definition at line 382 of file Geant4Kernel.cpp.
References DD4hep::format(), and m_globalFilters.
Referenced by DD4hep::Simulation::_convertSensitive(), DD4hep::Simulation::_createAction(), and id().
hasProperty()
bool Geant4Kernel::hasProperty (const std::string & name) const
Check property for existence.
Definition at line 208 of file Geant4Kernel.cpp.
References DD4hep::PropertyManager::exists(), and m_properties.
Referenced by id().
id()
unsigned long DD4hep::Simulation::Geant4Kernel::id () const inline
Access worker identifier.
Definition at line 161 of file Geant4Kernel.h.
References addPhase(), addSimplePhase(), declareProperty(), getOutputLevel(), getPhase(), globalAction(), globalFilter(), hasProperty(), m_ident, m_outputLevel, m_properties, outputLevel(), printProperties(), properties(), property(), registerGlobalAction(), registerGlobalFilter(), runManager(), and setOutputLevel().
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build().
initialize()
int Geant4Kernel::initialize () virtual
Run the simulation: Initialize Geant4.
Definition at line 281 of file Geant4Kernel.cpp.
References DD4hep::Simulation::Geant4Exec::initialize().
Referenced by addPhase().
instance()
Geant4Kernel & Geant4Kernel::instance (LCDD & lcdd) static
Instance accessor.
Definition at line 142 of file Geant4Kernel.cpp.
References Geant4Kernel().
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_convertSensitive(), DD4hep::Simulation::_createAction(), DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), DD4hep::Simulation::KernelHandle::KernelHandle(), and DD4hep::Converter< T, ARG >::operator()().
isMaster()
bool DD4hep::Simulation::Geant4Kernel::isMaster () const inline protected
Definition at line 94 of file Geant4Kernel.h.
References m_master.
Referenced by createWorker(), runManager(), and ~Geant4Kernel().
isMultiThreaded()
bool DD4hep::Simulation::Geant4Kernel::isMultiThreaded () const inline
Definition at line 113 of file Geant4Kernel.h.
References thread_self().
Referenced by DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4Exec::configure(), and worker().
isWorker()
bool DD4hep::Simulation::Geant4Kernel::isWorker () const inline protected
Definition at line 95 of file Geant4Kernel.h.
References Geant4Kernel(), lcdd(), m, and m_master.
lcdd()
LCDD& DD4hep::Simulation::Geant4Kernel::lcdd () const inline
Access to detector description.
Definition at line 153 of file Geant4Kernel.h.
References m_lcdd.
Referenced by DD4hep::Simulation::Geant4Exec::configure(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), isWorker(), and DD4hep::Simulation::Geant4Context::lcdd().
loadGeometry()
void Geant4Kernel::loadGeometry (const std::string & compact_file) virtual
Construct detector geometry using lcdd plugin.
Definition at line 265 of file Geant4Kernel.cpp.
References DD4hep::Geometry::LCDD::apply(), and m_lcdd.
Referenced by addPhase().
loadXML()
void Geant4Kernel::loadXML (const char * fname) virtual
Load XML file.
Definition at line 272 of file Geant4Kernel.cpp.
References DD4hep::Geometry::LCDD::apply(), and m_lcdd.
Referenced by addPhase().
master()
Geant4Kernel& DD4hep::Simulation::Geant4Kernel::master () const inline
Thread's master context.
Definition at line 107 of file Geant4Kernel.h.
References m_master.
Referenced by DD4hep::Simulation::_create_share().
numWorkers()
int Geant4Kernel::numWorkers () const
Access number of workers.
Definition at line 193 of file Geant4Kernel.cpp.
References m_workers.
Referenced by addPhase().
outputLevel()
PrintLevel DD4hep::Simulation::Geant4Kernel::outputLevel () const inline
Access the output level.
Output level settings
Definition at line 181 of file Geant4Kernel.h.
Referenced by id().
phases()
const Phases& DD4hep::Simulation::Geant4Kernel::phases () const inline
Access phase phases.
Definition at line 151 of file Geant4Kernel.h.
printProperties()
void Geant4Kernel::printProperties () const
Print the property values.
Definition at line 197 of file Geant4Kernel.cpp.
References DD4hep::ALWAYS, m_clientLevels, m_numEvent, m_numThreads, m_outputLevel, m_uiName, and DD4hep::printout().
Referenced by id().
properties()
PropertyManager& DD4hep::Simulation::Geant4Kernel::properties () inline
Access to the properties of the object.
Property access
Definition at line 167 of file Geant4Kernel.h.
Referenced by id(), and property().
property()
DD4hep::Property & Geant4Kernel::property (const std::string & name)
Access single property.
Definition at line 213 of file Geant4Kernel.cpp.
References properties().
Referenced by id(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::Simulation::Geant4Exec::run(), and DD4hep::Simulation::Geant4UIManager::start().
registerGlobalAction()
Geant4Kernel & Geant4Kernel::registerGlobalAction (Geant4Action * action)
Register action by name to be retrieved when setting up and connecting action objects.
Note: registered actions MUST be unique. However, not all actions need to registered.... Only register those, you later need to retrieve by name.
Definition at line 329 of file Geant4Kernel.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::format(), DD4hep::INFO, m_globalActions, DD4hep::Simulation::Geant4Action::name(), DD4hep::printout(), and DD4hep::typeName().
Referenced by id(), and DD4hep::Converter< T, ARG >::operator()().
registerGlobalFilter()
Geant4Kernel & Geant4Kernel::registerGlobalFilter (Geant4Action * filter)
Register filter by name to be retrieved when setting up and connecting filter objects.
Note: registered filters MUST be unique. However, not all filters need to registered.... Only register those, you later need to retrieve by name.
Definition at line 365 of file Geant4Kernel.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::format(), m_globalFilters, and DD4hep::Simulation::Geant4Action::name().
Referenced by id(), and DD4hep::Converter< T, ARG >::operator()().
removePhase()
bool Geant4Kernel::removePhase (const std::string & name) virtual
Remove an existing phase from the phase. If not existing returns false.
Definition at line 436 of file Geant4Kernel.cpp.
References m_phases.
Referenced by addPhase().
run()
int Geant4Kernel::run () virtual
Run the simulation: Simulate the number of events given by the property "NumEvents".
Definition at line 285 of file Geant4Kernel.cpp.
References e, DD4hep::FATAL, DD4hep::printout(), and DD4hep::Simulation::Geant4Exec::run().
Referenced by addPhase().
runEvents()
int Geant4Kernel::runEvents (int num_events) virtual
Run the simulation: Simulate the number of events "num_events" and modify the property "NumEvents".
Definition at line 298 of file Geant4Kernel.cpp.
References m_numEvent, and DD4hep::Simulation::Geant4Exec::run().
Referenced by addPhase().
runManager()
G4RunManager & Geant4Kernel::runManager ()
Access to the Geant4 run manager.
Definition at line 237 of file Geant4Kernel.cpp.
References DD4hep::format(), isMaster(), m_numThreads, m_runManager, DD4hep::printout(), and DD4hep::WARNING.
Referenced by DD4hep::Simulation::Geant4Exec::configure(), id(), DD4hep::Simulation::Geant4Exec::initialize(), DD4hep::Simulation::Geant4Exec::run(), and DD4hep::Simulation::Geant4UIManager::start().
setOutputLevel() [1/2]
DD4hep::PrintLevel Geant4Kernel::setOutputLevel (PrintLevel new_level)
Set the global output level of the kernel object; returns previous value.
Set the output level; returns previous value.
Definition at line 230 of file Geant4Kernel.cpp.
References m_outputLevel.
Referenced by id().
setOutputLevel() [2/2]
void Geant4Kernel::setOutputLevel (const std::string object, PrintLevel new_level)
Fill cache with the global output level of a named object. Must be set before instantiation.
Definition at line 218 of file Geant4Kernel.cpp.
References m_clientLevels.
setTrackMgr()
void DD4hep::Simulation::Geant4Kernel::setTrackMgr (G4TrackingManager * mgr) inline
Access the tracking manager.
Definition at line 157 of file Geant4Kernel.h.
shared()
Geant4Kernel& DD4hep::Simulation::Geant4Kernel::shared () const inline
Shared action context.
Definition at line 110 of file Geant4Kernel.h.
References m_shared.
terminate()
int Geant4Kernel::terminate () virtual
Run the simulation: Terminate Geant4.
Reimplemented from DD4hep::Simulation::Geant4ActionContainer.
Definition at line 303 of file Geant4Kernel.cpp.
References DD4hep::deletePtr(), DD4hep::Geometry::LCDD::destroyInstance(), destroyPhases(), DD4hep::INFO, m_globalActions, m_globalFilters, m_lcdd, m_runManager, DD4hep::printout(), DD4hep::releaseObjects(), DD4hep::Geometry::LCDD::removeExtension(), DD4hep::Simulation::Geant4ActionContainer::terminate(), and DD4hep::Simulation::Geant4Exec::terminate().
Referenced by addPhase().
thread_self()
unsigned long int Geant4Kernel::thread_self () static
Access thread identifier.
Definition at line 154 of file Geant4Kernel.cpp.
Referenced by DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField(), createWorker(), DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), isMultiThreaded(), DD4hep::Simulation::KernelHandle::worker(), and worker().
trackMgr()
G4TrackingManager* DD4hep::Simulation::Geant4Kernel::trackMgr () const inline
Access the tracking manager.
Definition at line 155 of file Geant4Kernel.h.
References m_trackMgr.
Referenced by DD4hep::Simulation::Geant4Context::trackMgr().
worker()
Geant4Kernel & Geant4Kernel::worker (unsigned long thread_identifier, bool create_if = false)
Access worker instance by it's identifier.
Definition at line 172 of file Geant4Kernel.cpp.
References createWorker(), DD4hep::format(), isMultiThreaded(), m_id, m_workers, and thread_self().
Referenced by addPhase(), DD4hep::Simulation::Geant4UserActionInitialization::Build(), DD4hep::Simulation::Geant4UserDetectorConstruction::ConstructSDandField(), DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), and DD4hep::Simulation::KernelHandle::worker().
Member Data Documentation
m_clientLevels
ClientOutputLevels DD4hep::Simulation::Geant4Kernel::m_clientLevels protected
Property: Client output levels.
Definition at line 81 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), getOutputLevel(), printProperties(), and setOutputLevel().
m_control
G4UIdirectory* DD4hep::Simulation::Geant4Kernel::m_control protected
Top level control directory.
Definition at line 55 of file Geant4Kernel.h.
Referenced by Geant4Kernel().
m_controlName
std::string DD4hep::Simulation::Geant4Kernel::m_controlName protected
Property: Name of the G4UI command tree.
Definition at line 73 of file Geant4Kernel.h.
Referenced by directoryName(), and Geant4Kernel().
m_globalActions
GlobalActions DD4hep::Simulation::Geant4Kernel::m_globalActions protected
Globally registered actions.
Definition at line 69 of file Geant4Kernel.h.
Referenced by globalAction(), registerGlobalAction(), terminate(), and ~Geant4Kernel().
m_globalFilters
GlobalActions DD4hep::Simulation::Geant4Kernel::m_globalFilters protected
Globally registered filters of sensitive detectors.
Definition at line 71 of file Geant4Kernel.h.
Referenced by globalFilter(), registerGlobalFilter(), terminate(), and ~Geant4Kernel().
m_id
unsigned long DD4hep::Simulation::Geant4Kernel::m_id protected
Flag: Master instance (id<0) or worker (id >= 0)
Definition at line 88 of file Geant4Kernel.h.
Referenced by worker().
m_ident
unsigned long DD4hep::Simulation::Geant4Kernel::m_ident protected
Definition at line 88 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), and id().
m_lcdd
LCDD* DD4hep::Simulation::Geant4Kernel::m_lcdd protected
Detector description object.
Definition at line 59 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), lcdd(), loadGeometry(), loadXML(), terminate(), and ~Geant4Kernel().
m_master
Geant4Kernel* DD4hep::Simulation::Geant4Kernel::m_master protected
Parent reference.
Definition at line 90 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), isMaster(), isWorker(), and master().
m_numEvent
long DD4hep::Simulation::Geant4Kernel::m_numEvent protected
Property: Number of events to be executed in batch mode.
Definition at line 77 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), printProperties(), and runEvents().
m_numThreads
int DD4hep::Simulation::Geant4Kernel::m_numThreads protected
Property: Running in multi threaded context.
Master property: Number of execution threads in multi threaded mode.
Definition at line 86 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), printProperties(), and runManager().
m_outputLevel
int DD4hep::Simulation::Geant4Kernel::m_outputLevel protected
Property: Output level.
Definition at line 79 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), id(), printProperties(), and setOutputLevel().
m_phases
Phases DD4hep::Simulation::Geant4Kernel::m_phases protected
Action phases.
Definition at line 65 of file Geant4Kernel.h.
Referenced by addSimplePhase(), destroyPhases(), executePhase(), getPhase(), and removePhase().
m_properties
PropertyManager DD4hep::Simulation::Geant4Kernel::m_properties protected
Property pool.
Definition at line 61 of file Geant4Kernel.h.
Referenced by declareProperty(), hasProperty(), and id().
m_runManager
G4RunManager* DD4hep::Simulation::Geant4Kernel::m_runManager protected
Reference to the run manager.
Definition at line 53 of file Geant4Kernel.h.
Referenced by runManager(), terminate(), and ~Geant4Kernel().
m_shared
Geant4Kernel* DD4hep::Simulation::Geant4Kernel::m_shared protected
Definition at line 91 of file Geant4Kernel.h.
Referenced by shared().
m_threadContext
Geant4Context* DD4hep::Simulation::Geant4Kernel::m_threadContext protected
Definition at line 92 of file Geant4Kernel.h.
m_trackMgr
G4TrackingManager* DD4hep::Simulation::Geant4Kernel::m_trackMgr protected
Reference to Geant4 track manager.
Definition at line 57 of file Geant4Kernel.h.
Referenced by trackMgr().
m_uiName
std::string DD4hep::Simulation::Geant4Kernel::m_uiName protected
Property: Name of the UI action. Must be member of the global actions.
Definition at line 75 of file Geant4Kernel.h.
Referenced by Geant4Kernel(), and printProperties().
m_workers
Workers DD4hep::Simulation::Geant4Kernel::m_workers protected
Worker threads.
Definition at line 67 of file Geant4Kernel.h.
Referenced by createWorker(), Geant4Kernel(), numWorkers(), worker(), and ~Geant4Kernel().
phase
class DD4hep::Simulation::Geant4Kernel::PhaseSelector DD4hep::Simulation::Geant4Kernel::phase
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Kernel.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Kernel.cpp