DD4hep: DD4hep::Display Class Reference
DD4hep::Display Class Reference
The main class of the DDEve display.
#include <Display.h>
Classes
struct CalodataContext
Public Types
typedef DisplayConfiguration::ViewConfig ViewConfig
typedef DisplayConfiguration::Config DataConfig
typedef std::set< View * > Views
typedef std::set< DisplayConfiguration * > Configurations
typedef std::set< PopupMenu * > Menus
typedef std::map< std::string, TEveElementList * > Topics
typedef std::map< std::string, ViewConfig > ViewConfigurations
typedef std::map< std::string, DataConfig > DataConfigurations
typedef std::map< std::string, CalodataContext > Calodata
Public Member Functions
Display (TEveManager *eve)
Standard constructor.
virtual ~Display ()
Default destructor.
Geometry::LCDD & lcdd () const
Access to geometry hub.
TEveManager & manager () const
Access to the EVE manager.
const ViewConfigurations & viewConfigurations () const
Access View configurations.
void setVisLevel (int new_level)
Set Vis level in geo manager (either from XML or BEFORE XML file was loaded)
void setLoadLevel (int new_level)
Set Eve Geometry load level in manager (either from XML or BEFORE XML file was loaded)
void setEventHandlerName (std::string eventHandlerName)
Set Event Handler Plugin name.
std::string getEventHandlerName ()
Get Event Handler Plugin name.
TGClient & client () const
Access to X-client.
void ChooseGeometry ()
Load geometry with panel.
void LoadXML (const char *xmlFile)
Load geometry from compact xml file.
void LoadGeometryRoot (const char *rootFile)
Load geometry from compact xml file.
TFile * Open (const char *rootFile) const
Open ROOT file.
GenericEventHandler & eventHandler () const
Access to the event reader.
void MessageBox (PrintLevel level, const std::string &text, const std::string &title="") const
Open standard message box.
std::string OpenXmlFileDialog (const std::string &default_dir) const
Popup XML file chooser. returns chosen file name; empty on cancel.
std::string OpenEventFileDialog (const std::string &default_dir) const
Popup ROOT file chooser. returns chosen file name; empty on cancel.
void LoadGeoChildren (TEveElement *start, int levels, bool redraw)
Load 'levels' Children into the geometry scene.
void MakeNodesVisible (TEveElement *e, bool visible, int level)
Make a set of nodes starting from a top element (in-)visible with a given depth.
void ImportConfiguration (const DisplayConfiguration &config)
Import configuration parameters.
const ViewConfig * GetViewConfiguration (const std::string &name) const
Access a data filter by name. Data filters are used to customize views.
const DataConfig * GetCalodataConfiguration (const std::string &name) const
Access a data filter by name. Data filters are used to customize views.
CalodataContext & GetCaloHistogram (const std::string &name)
Access to calo data histograms by name as defined in the configuration.
virtual void RegisterEvents (View *view)
Register to the main event scene on new events.
virtual void UnregisterEvents (View *view)
Unregister from the main event scene.
TEveElementList & GetGeo ()
Access / Create global geometry element.
virtual TEveElementList & GetGeoTopic (const std::string &name)
Access/Create an geometry topic by name.
virtual TEveElementList & GetGeoTopic (const std::string &name) const
Access/Create an geometry topic by name. Throws exception if the topic does not exist.
void ImportGeo (TEveElement *el)
Call to import geometry elements.
void ImportGeo (const std::string &topic, TEveElement *el)
Call to import geometry elements by topic.
virtual TEveElementList & GetEveTopic (const std::string &name)
Access/Create an event topic by name.
virtual TEveElementList & GetEveTopic (const std::string &name) const
Access/Create an event topic by name. Throws exception if the topic does not exist.
void ImportEvent (TEveElement *el)
Call to import top level event elements.
void ImportEvent (const std::string &topic, TEveElement *el)
Call to import event elements by topic.
virtual void OnNewEvent (EventHandler *handler)
EventConsumer overload: Consumer event data.
virtual void BuildMenus (TGMenuBar *bar=0)
Build the DDEve specific menues. Default bar is the ROOT browser's bar.
virtual void AddMenu (TGMenuBar *bar, PopupMenu *menu, int hints=kLHintsNormal)
Add new menu to the main menu bar.
ClassDef (Display, 0)
Public Member Functions inherited from DD4hep::EventConsumer
EventConsumer ()
Standard constructor.
virtual ~EventConsumer ()
Default destructor.
virtual void OnFileOpen (EventHandler *)
Consumer file open callback.
ClassDef (EventConsumer, 0)
Protected Attributes
TEveManager * m_eve
Reference to TEve manager.
Geometry::LCDD * m_lcdd
Reference to geometry hub.
GenericEventHandler * m_evtHandler
Reference to the event reader object.
TEveElementList * m_geoGlobal
TEveElementList * m_eveGlobal
ViewMenu * m_viewMenu
DD4hepMenu * m_dd4Menu
Topics m_geoTopics
Topics m_eveTopics
Views m_eveViews
Menus m_menus
ViewConfigurations m_viewConfigs
DataConfigurations m_calodataConfigs
DataConfigurations m_collectionsConfigs
Calodata m_calodata
Container with calorimeter data (projections)
int m_visLevel
TGeoManager visualisation level.
int m_loadLevel
Load level for the eve geometry.
std::string m_eventHandlerName
Name of the event handler plugin.
Detailed Description
The main class of the DDEve display.
Definition at line 57 of file Display.h.
Member Typedef Documentation
Calodata
typedef std::map<std::string, CalodataContext> DD4hep::Display::Calodata
Definition at line 78 of file Display.h.
Configurations
typedef std::set<DisplayConfiguration*> DD4hep::Display::Configurations
Definition at line 62 of file Display.h.
DataConfig
typedef DisplayConfiguration::Config DD4hep::Display::DataConfig
Definition at line 60 of file Display.h.
DataConfigurations
typedef std::map<std::string, DataConfig> DD4hep::Display::DataConfigurations
Definition at line 66 of file Display.h.
Menus
typedef std::set<PopupMenu*> DD4hep::Display::Menus
Definition at line 63 of file Display.h.
Topics
typedef std::map<std::string, TEveElementList*> DD4hep::Display::Topics
Definition at line 64 of file Display.h.
ViewConfig
typedef DisplayConfiguration::ViewConfig DD4hep::Display::ViewConfig
Definition at line 59 of file Display.h.
ViewConfigurations
typedef std::map<std::string, ViewConfig> DD4hep::Display::ViewConfigurations
Definition at line 65 of file Display.h.
Views
typedef std::set<View*> DD4hep::Display::Views
Definition at line 61 of file Display.h.
Constructor & Destructor Documentation
Display()
Display::Display (TEveManager * eve)
Standard constructor.
Definition at line 111 of file Display.cpp.
References DD4hep::Geometry::LCDD::addExtension(), dd4hep::bar, BuildMenus(), DD4hep::Geometry::LCDD::getInstance(), DD4hep::EvePgonSetProjectedContextMenu::install(), DD4hep::EveShapeContextMenu::install(), DD4hep::ElementListContextMenu::install(), m_eve, m_evtHandler, m_lcdd, and DD4hep::GenericEventHandler::Subscribe().
~Display()
Display::~Display () virtual
Default destructor.
Definition at line 132 of file Display.cpp.
References DD4hep::deletePtr(), DD4hep::Geometry::LCDDData::destroyData(), m_dd4Menu, m_eve, m_eveGlobal, m_evtHandler, m_geoGlobal, m_lcdd, m_viewConfigs, m_viewMenu, and DD4hep::Geometry::LCDD::removeExtension().
Member Function Documentation
AddMenu()
void Display::AddMenu (TGMenuBar * bar, PopupMenu * menu, int hints = kLHintsNormal) virtual
Add new menu to the main menu bar.
Definition at line 197 of file Display.cpp.
References DD4hep::PopupMenu::Build(), m_eve, and m_menus.
Referenced by BuildMenus(), and getEventHandlerName().
BuildMenus()
void Display::BuildMenus (TGMenuBar * bar = 0) virtual
Build the DDEve specific menues. Default bar is the ROOT browser's bar.
Build the DDEve specific menues.
Definition at line 354 of file Display.cpp.
References AddMenu(), m_dd4Menu, m_eve, m_viewConfigs, and m_viewMenu.
Referenced by Display(), getEventHandlerName(), and LoadXML().
ChooseGeometry()
void Display::ChooseGeometry ()
Load geometry with panel.
Definition at line 174 of file Display.cpp.
References m_dd4Menu, and DD4hep::DD4hepMenu::OnLoadXML().
Referenced by ClassImp(), and getEventHandlerName().
ClassDef()
DD4hep::Display::ClassDef (Display , 0)
Referenced by getEventHandlerName().
client()
TGClient & Display::client () const
Access to X-client.
Definition at line 184 of file Display.cpp.
Referenced by getEventHandlerName(), MessageBox(), OpenEventFileDialog(), and OpenXmlFileDialog().
eventHandler()
GenericEventHandler & Display::eventHandler () const
Access to the event reader.
Definition at line 189 of file Display.cpp.
References m_evtHandler.
Referenced by ClassImp(), GetCaloHistogram(), getEventHandlerName(), and OnNewEvent().
GetCalodataConfiguration()
const Display::DataConfig * Display::GetCalodataConfiguration (const std::string & name) const
Access a data filter by name. Data filters are used to customize views.
Access a data filter by name. Data filters are used to customize calodatas.
Definition at line 274 of file Display.cpp.
References m_calodataConfigs.
Referenced by getEventHandlerName().
GetCaloHistogram()
Display::CalodataContext & Display::GetCaloHistogram (const std::string & name)
Access to calo data histograms by name as defined in the configuration.
Definition at line 217 of file Display.cpp.
References DD4hep::Display::CalodataContext::calo3D, DD4hep::GenericEventHandler::collectionLoop(), DD4hep::DisplayConfiguration::Defaults::color, DD4hep::Display::CalodataContext::config, DD4hep::DisplayConfiguration::Calodata::dz, DD4hep::DisplayConfiguration::Calodata::eta_max, DD4hep::DisplayConfiguration::Calodata::eta_min, DD4hep::Display::CalodataContext::eveHist, eventHandler(), DD4hep::DisplayConfiguration::Config::hits, ImportGeo(), m_calodata, m_calodataConfigs, DD4hep::DisplayConfiguration::Calodata::n_eta, DD4hep::DisplayConfiguration::Calodata::n_phi, DD4hep::DisplayConfiguration::Config::name, DD4hep::DisplayConfiguration::Calodata::phi_max, DD4hep::DisplayConfiguration::Calodata::phi_min, DD4hep::DisplayConfiguration::Calodata::rmin, DD4hep::Display::CalodataContext::slice, DD4hep::DisplayConfiguration::Calodata::threshold, DD4hep::DisplayConfiguration::Calodata::towerH, and DD4hep::DisplayConfiguration::Config::use.
Referenced by DD4hep::View::ConfigureGeometry(), and getEventHandlerName().
getEventHandlerName()
std::string DD4hep::Display::getEventHandlerName () inline
Get Event Handler Plugin name.
Definition at line 125 of file Display.h.
References AddMenu(), dd4hep::bar, BuildMenus(), ChooseGeometry(), ClassDef(), client(), DD4hep::Display::CalodataContext::config, e, eventHandler(), GetCalodataConfiguration(), GetCaloHistogram(), GetEveTopic(), GetGeo(), GetGeoTopic(), GetViewConfiguration(), ImportConfiguration(), ImportEvent(), ImportGeo(), LoadGeoChildren(), LoadGeometryRoot(), LoadXML(), m_eventHandlerName, MakeNodesVisible(), MessageBox(), OnNewEvent(), Open(), OpenEventFileDialog(), OpenXmlFileDialog(), RegisterEvents(), and UnregisterEvents().
Referenced by ClassImp().
GetEveTopic() [1/2]
TEveElementList & Display::GetEveTopic (const std::string & name) virtual
Access/Create an event topic by name.
Access/Create a topic by name.
Definition at line 492 of file Display.cpp.
References m_eveTopics, and manager().
Referenced by getEventHandlerName(), and ImportEvent().
GetEveTopic() [2/2]
TEveElementList & Display::GetEveTopic (const std::string & name) const virtual
Access/Create an event topic by name. Throws exception if the topic does not exist.
Access/Create a topic by name. Throws exception if the topic does not exist.
Definition at line 504 of file Display.cpp.
References m_eveTopics.
GetGeo()
TEveElementList & Display::GetGeo ()
Access / Create global geometry element.
Definition at line 462 of file Display.cpp.
References m_geoGlobal, and manager().
Referenced by getEventHandlerName(), GetGeoTopic(), and ImportGeo().
GetGeoTopic() [1/2]
TEveElementList & Display::GetGeoTopic (const std::string & name) virtual
Access/Create an geometry topic by name.
Access/Create a topic by name.
Definition at line 471 of file Display.cpp.
References GetGeo(), and m_geoTopics.
Referenced by DD4hep::View::ConfigureGeometryFromGlobal(), getEventHandlerName(), DD4hep::View::GetGlobalGeometry(), ImportGeo(), and LoadGeoChildren().
GetGeoTopic() [2/2]
TEveElementList & Display::GetGeoTopic (const std::string & name) const virtual
Access/Create an geometry topic by name. Throws exception if the topic does not exist.
Access/Create a topic by name. Throws exception if the topic does not exist.
Definition at line 483 of file Display.cpp.
References m_geoTopics.
GetViewConfiguration()
const Display::ViewConfig * Display::GetViewConfiguration (const std::string & name) const
Access a data filter by name. Data filters are used to customize views.
Definition at line 268 of file Display.cpp.
References m_viewConfigs.
Referenced by getEventHandlerName(), and DD4hep::View::View().
ImportConfiguration()
void Display::ImportConfiguration (const DisplayConfiguration & config)
Import configuration parameters.
Definition at line 204 of file Display.cpp.
References DD4hep::DisplayConfiguration::calodata, DD4hep::DisplayConfiguration::collections, m_calodataConfigs, m_collectionsConfigs, m_viewConfigs, and DD4hep::DisplayConfiguration::views.
Referenced by extract(), and getEventHandlerName().
ImportEvent() [1/2]
void Display::ImportEvent (TEveElement * el)
Call to import top level event elements.
Definition at line 528 of file Display.cpp.
References manager().
Referenced by getEventHandlerName(), and OnNewEvent().
ImportEvent() [2/2]
void Display::ImportEvent (const std::string & topic, TEveElement * el)
Call to import event elements by topic.
Definition at line 523 of file Display.cpp.
References GetEveTopic().
ImportGeo() [1/2]
void Display::ImportGeo (TEveElement * el)
Call to import geometry elements.
Definition at line 513 of file Display.cpp.
References GetGeo().
Referenced by GetCaloHistogram(), and getEventHandlerName().
ImportGeo() [2/2]
void Display::ImportGeo (const std::string & topic, TEveElement * el)
Call to import geometry elements by topic.
Definition at line 518 of file Display.cpp.
References GetGeoTopic().
lcdd()
Geometry::LCDD & Display::lcdd () const
Access to geometry hub.
Definition at line 179 of file Display.cpp.
References m_lcdd.
Referenced by DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureGeometry(), DD4hep::View::CreateGeometry(), DD4hep::View::GetGlobalGeometry(), and LoadGeoChildren().
LoadGeoChildren()
void Display::LoadGeoChildren (TEveElement * start, int levels, bool redraw)
Load 'levels' Children into the geometry scene.
Definition at line 533 of file Display.cpp.
References DD4hep::Geometry::DetElement::children(), DD4hep::Utilities::createEveShape(), e, DD4hep::Utilities::findNodeWithMatrix(), GetGeoTopic(), DD4hep::Utilities::GetName(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), lcdd(), DD4hep::Utilities::LoadDetElement(), m_lcdd, manager(), MessageBox(), DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), DD4hep::printout(), DD4hep::Handle< T >::ptr(), DD4hep::Geometry::LCDD::sensitiveDetector(), and DD4hep::Geometry::LCDD::world().
Referenced by getEventHandlerName(), and LoadXML().
LoadGeometryRoot()
void Display::LoadGeometryRoot (const char * rootFile)
Load geometry from compact xml file.
Definition at line 169 of file Display.cpp.
Referenced by getEventHandlerName().
LoadXML()
void Display::LoadXML (const char * xmlFile)
Load geometry from compact xml file.
Definition at line 152 of file Display.cpp.
References BuildMenus(), DD4hep::Geometry::LCDD::fromXML(), LoadGeoChildren(), m_dd4Menu, m_eve, m_geoTopics, m_lcdd, m_loadLevel, m_visLevel, DD4hep::Geometry::LCDD::manager(), and DD4hep::DD4hepMenu::OnGeometryLoaded().
Referenced by ClassImp(), and getEventHandlerName().
MakeNodesVisible()
void Display::MakeNodesVisible (TEveElement * e, bool visible, int level)
Make a set of nodes starting from a top element (in-)visible with a given depth.
Definition at line 597 of file Display.cpp.
References DD4hep::Utilities::GetName(), DD4hep::INFO, DD4hep::Utilities::MakeNodesVisible(), manager(), and DD4hep::printout().
Referenced by getEventHandlerName().
manager()
TEveManager& DD4hep::Display::manager () const inline
Access to the EVE manager.
Definition at line 115 of file Display.h.
References m_eve.
Referenced by DD4hep::View::AddToGlobalItems(), DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureEventFromGlobal(), DD4hep::View::ConfigureGeometry(), DD4hep::View::CreateEventScene(), DD4hep::View::CreateGeoScene(), GetEveTopic(), GetGeo(), ImportEvent(), DD4hep::View::Initialize(), LoadGeoChildren(), MakeNodesVisible(), DD4hep::View::Map(), and OnNewEvent().
MessageBox()
void Display::MessageBox (PrintLevel level, const std::string & text, const std::string & title = "") const
Open standard message box.
Definition at line 293 of file Display.cpp.
References client(), DD4hep::DEBUG, DD4hep::ERROR, DD4hep::FATAL, DD4hep::INFO, DD4hep::VERBOSE, and DD4hep::WARNING.
Referenced by ClassImp(), getEventHandlerName(), and LoadGeoChildren().
OnNewEvent()
void Display::OnNewEvent (EventHandler * handler) virtual
EventConsumer overload: Consumer event data.
Consumer event data.
We absolutely want to import the particles as the last elements, otherwise they end up under the hits and are close to invisible
Reimplemented from DD4hep::EventConsumer.
Definition at line 376 of file Display.cpp.
References DD4hep::Display::CalodataContext::calo3D, DD4hep::EventHandler::CALO_HIT_COLLECTION, DD4hep::MCParticleCreator::close(), DD4hep::GenericEventHandler::collectionLoop(), DD4hep::EventHandler::collectionLoop(), DD4hep::EventHandler::collectionType(), DD4hep::Display::CalodataContext::config, DD4hep::EventHandler::data(), DD4hep::PointsetCreator::element(), DD4hep::BoxsetCreator::element(), DD4hep::ERROR, DD4hep::Display::CalodataContext::eveHist, eventHandler(), DD4hep::DisplayConfiguration::Config::hits, ImportEvent(), DD4hep::INFO, m_calodata, m_collectionsConfigs, m_eveViews, manager(), DD4hep::EventHandler::PARTICLE_COLLECTION, DD4hep::MCParticleCreator::particles, DD4hep::printout(), and DD4hep::EventHandler::TRACKER_HIT_COLLECTION.
Referenced by getEventHandlerName().
Open()
TFile * Display::Open (const char * rootFile) const
Open ROOT file.
Definition at line 369 of file Display.cpp.
Referenced by getEventHandlerName().
OpenEventFileDialog()
string Display::OpenEventFileDialog (const std::string & default_dir) const
Popup ROOT file chooser. returns chosen file name; empty on cancel.
Definition at line 334 of file Display.cpp.
References client().
Referenced by getEventHandlerName().
OpenXmlFileDialog()
string Display::OpenXmlFileDialog (const std::string & default_dir) const
Popup XML file chooser. returns chosen file name; empty on cancel.
Definition at line 313 of file Display.cpp.
References client().
Referenced by getEventHandlerName().
RegisterEvents()
void Display::RegisterEvents (View * view) virtual
Register to the main event scene on new events.
Definition at line 280 of file Display.cpp.
References m_eveViews.
Referenced by getEventHandlerName().
setEventHandlerName()
void DD4hep::Display::setEventHandlerName (std::string eventHandlerName) inline
Set Event Handler Plugin name.
Definition at line 123 of file Display.h.
Referenced by extract().
setLoadLevel()
void DD4hep::Display::setLoadLevel (int new_level) inline
Set Eve Geometry load level in manager (either from XML or BEFORE XML file was loaded)
Definition at line 121 of file Display.h.
Referenced by extract().
setVisLevel()
void DD4hep::Display::setVisLevel (int new_level) inline
Set Vis level in geo manager (either from XML or BEFORE XML file was loaded)
Definition at line 119 of file Display.h.
Referenced by extract().
UnregisterEvents()
void Display::UnregisterEvents (View * view) virtual
Unregister from the main event scene.
Definition at line 285 of file Display.cpp.
References m_eveViews.
Referenced by getEventHandlerName(), and DD4hep::View::~View().
viewConfigurations()
const ViewConfigurations& DD4hep::Display::viewConfigurations () const inline
Access View configurations.
Definition at line 117 of file Display.h.
References m_viewConfigs.
Referenced by DD4hep::MultiView::Build().
Member Data Documentation
m_calodata
Calodata DD4hep::Display::m_calodata protected
Container with calorimeter data (projections)
Definition at line 99 of file Display.h.
Referenced by GetCaloHistogram(), and OnNewEvent().
m_calodataConfigs
DataConfigurations DD4hep::Display::m_calodataConfigs protected
Definition at line 96 of file Display.h.
Referenced by GetCalodataConfiguration(), GetCaloHistogram(), and ImportConfiguration().
m_collectionsConfigs
DataConfigurations DD4hep::Display::m_collectionsConfigs protected
Definition at line 97 of file Display.h.
Referenced by ImportConfiguration(), and OnNewEvent().
m_dd4Menu
DD4hepMenu* DD4hep::Display::m_dd4Menu protected
Definition at line 90 of file Display.h.
Referenced by BuildMenus(), ChooseGeometry(), LoadXML(), and ~Display().
m_eve
TEveManager* DD4hep::Display::m_eve protected
Reference to TEve manager.
Definition at line 82 of file Display.h.
Referenced by AddMenu(), BuildMenus(), Display(), LoadXML(), manager(), and ~Display().
m_eveGlobal
TEveElementList* DD4hep::Display::m_eveGlobal protected
Definition at line 88 of file Display.h.
Referenced by ~Display().
m_eventHandlerName
std::string DD4hep::Display::m_eventHandlerName protected
Name of the event handler plugin.
Definition at line 105 of file Display.h.
Referenced by getEventHandlerName().
m_eveTopics
Topics DD4hep::Display::m_eveTopics protected
Definition at line 92 of file Display.h.
Referenced by GetEveTopic().
m_eveViews
Views DD4hep::Display::m_eveViews protected
Definition at line 93 of file Display.h.
Referenced by OnNewEvent(), RegisterEvents(), and UnregisterEvents().
m_evtHandler
GenericEventHandler* DD4hep::Display::m_evtHandler protected
Reference to the event reader object.
Definition at line 86 of file Display.h.
Referenced by Display(), eventHandler(), and ~Display().
m_geoGlobal
TEveElementList* DD4hep::Display::m_geoGlobal protected
Definition at line 87 of file Display.h.
Referenced by GetGeo(), and ~Display().
m_geoTopics
Topics DD4hep::Display::m_geoTopics protected
Definition at line 91 of file Display.h.
Referenced by GetGeoTopic(), and LoadXML().
m_lcdd
Geometry::LCDD* DD4hep::Display::m_lcdd protected
Reference to geometry hub.
Definition at line 84 of file Display.h.
Referenced by Display(), lcdd(), LoadGeoChildren(), LoadXML(), and ~Display().
m_loadLevel
int DD4hep::Display::m_loadLevel protected
Load level for the eve geometry.
Definition at line 103 of file Display.h.
Referenced by LoadXML().
m_menus
Menus DD4hep::Display::m_menus protected
Definition at line 94 of file Display.h.
Referenced by AddMenu().
m_viewConfigs
ViewConfigurations DD4hep::Display::m_viewConfigs protected
Definition at line 95 of file Display.h.
Referenced by BuildMenus(), GetViewConfiguration(), ImportConfiguration(), viewConfigurations(), and ~Display().
m_viewMenu
ViewMenu* DD4hep::Display::m_viewMenu protected
Definition at line 89 of file Display.h.
Referenced by BuildMenus(), and ~Display().
m_visLevel
int DD4hep::Display::m_visLevel protected
TGeoManager visualisation level.
Definition at line 101 of file Display.h.
Referenced by LoadXML().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/Display.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/Display.cpp