DD4hep: DD4hep::Simulation::Geant4ActionPhase Class Reference
DD4hep::Simulation::Geant4ActionPhase Class Reference
DD4hep::Simulation components, classes and objects
Action phase definition. Client callback at various stage of the simulation processing.
#include <Geant4ActionPhase.h>
Public Types
typedef std::vector< std::pair< Geant4Action *, Callback > > Members
Public Member Functions
Geant4ActionPhase (Geant4Context *context, const std::string &name, const std::type_info &arg_type0, const std::type_info &arg_type1, const std::type_info &arg_type2)
Standard constructor.
virtual ~Geant4ActionPhase ()
Default destructor.
const Members & members () const
Access phase members.
const std::type_info *const * argTypes () const
Type of the first phase callback-argument.
void execute (void *argument)
Execute all members in the phase context.
virtual bool add (Geant4Action *action, Callback callback)
Add a new member to the phase.
virtual bool remove (Geant4Action *action, Callback callback)
Remove an existing member from the phase. If not existing returns false.
template<typename TYPE , typename IF_TYPE , typename A0 , typename R >
bool add (TYPE *member, R(IF_TYPE::*callback)(A0 arg))
Add a new member to the phase.
template<typename TYPE , typename IF_TYPE , typename A0 , typename A1 , typename R >
bool add (TYPE *member, R(IF_TYPE::*callback)(A0 arg0, A1 arg1))
Add a new member to the phase.
template<typename TYPE , typename IF_TYPE , typename A0 , typename A1 , typename A2 , typename R >
bool add (TYPE *member, R(IF_TYPE::*callback)(A0 arg0, A1 arg1))
Add a new member to the phase.
template<typename TYPE , typename PMF >
bool remove (TYPE *member)
Remove all member callbacks from the phase. If not existing returns false.
template<typename TYPE , typename PMF >
bool remove (TYPE *member, PMF callback)
Remove an existing member callback from the phase. If not existing returns false.
void call ()
Create action to execute phase members.
template<typename A0 >
void call (A0 a0)
template<typename A0 , typename A1 >
void call (A0 a0, A1 a1)
template<typename A0 , typename A1 , typename A2 >
void call (A0 a0, A1 a1, A2 a2)
template<>
void call (const G4Run *run)
Callback in BeginRun/EndRun.
template<>
void call (G4Event *event)
Callback in prepare primaries.
template<>
void call (const G4Event *event)
Callback in BeginEvent/EndEvent.
template<>
void call (const G4Track *track)
Callback in Begin/End tracking action.
template<>
void call (const G4Step *step)
Callback in Begin/End stepping action.
template<>
void call (const G4Step *step, G4SteppingManager *mgr)
Callback for user stepping action.
template<>
void call (G4HCofThisEvent *hce)
Callback for sensitives begin/end/clear.
template<>
void call (G4Step *step, G4TouchableHistory *history)
Callback for sensitives.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
Members m_members
Phase members (actions) being called for a particular phase.
const std::type_info * m_argTypes [3]
Type information of the argument type of the callback.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Action phase definition. Client callback at various stage of the simulation processing.
Author
M.Frank
Version
1.0
Definition at line 69 of file Geant4ActionPhase.h.
Member Typedef Documentation
Members
typedef std::vector<std::pair<Geant4Action*, Callback> > DD4hep::Simulation::Geant4ActionPhase::Members
Definition at line 71 of file Geant4ActionPhase.h.
Constructor & Destructor Documentation
Geant4ActionPhase()
Geant4ActionPhase::Geant4ActionPhase (Geant4Context * context, const std::string & name, const std::type_info & arg_type0, const std::type_info & arg_type1, const std::type_info & arg_type2)
Standard constructor.
Definition at line 41 of file Geant4ActionPhase.cpp.
References DD4hep::InstanceCount::increment(), and m_argTypes.
~Geant4ActionPhase()
Geant4ActionPhase::~Geant4ActionPhase () virtual
Default destructor.
Definition at line 51 of file Geant4ActionPhase.cpp.
References DD4hep::InstanceCount::decrement(), and m_members.
Member Function Documentation
add() [1/4]
bool Geant4ActionPhase::add (Geant4Action * action, Callback callback) virtual
Add a new member to the phase.
Definition at line 59 of file Geant4ActionPhase.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_members.
add() [2/4]
template<typename TYPE , typename IF_TYPE , typename A0 , typename R > bool DD4hep::Simulation::Geant4ActionPhase::add (TYPE * member, R(IF_TYPE::*)(A0 arg) callback) inline
Add a new member to the phase.
Definition at line 100 of file Geant4ActionPhase.h.
References DD4hep::typeinfoCheck().
add() [3/4]
template<typename TYPE , typename IF_TYPE , typename A0 , typename A1 , typename R > bool DD4hep::Simulation::Geant4ActionPhase::add (TYPE * member, R(IF_TYPE::*)(A0 arg0, A1 arg1) callback) inline
Add a new member to the phase.
Definition at line 109 of file Geant4ActionPhase.h.
References DD4hep::typeinfoCheck().
add() [4/4]
template<typename TYPE , typename IF_TYPE , typename A0 , typename A1 , typename A2 , typename R > bool DD4hep::Simulation::Geant4ActionPhase::add (TYPE * member, R(IF_TYPE::*)(A0 arg0, A1 arg1) callback) inline
Add a new member to the phase.
Definition at line 119 of file Geant4ActionPhase.h.
References DD4hep::typeinfoCheck().
argTypes()
const std::type_info* const* DD4hep::Simulation::Geant4ActionPhase::argTypes () const inline
Type of the first phase callback-argument.
Definition at line 89 of file Geant4ActionPhase.h.
References DD4hep::Simulation::Geant4PhaseAction::callback().
call() [1/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (const G4Run * run)
Callback in BeginRun/EndRun.
Definition at line 108 of file Geant4ActionPhase.cpp.
References execute().
call() [2/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (G4Event * event)
Callback in prepare primaries.
Definition at line 112 of file Geant4ActionPhase.cpp.
References execute().
call() [3/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (const G4Event * event)
Callback in BeginEvent/EndEvent.
Definition at line 116 of file Geant4ActionPhase.cpp.
References execute().
call() [4/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (const G4Track * track)
Callback in Begin/End tracking action.
Definition at line 120 of file Geant4ActionPhase.cpp.
References execute().
call() [5/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (const G4Step * step)
Callback in Begin/End stepping action.
Definition at line 124 of file Geant4ActionPhase.cpp.
References execute().
call() [6/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (const G4Step * step, G4SteppingManager * mgr)
Callback for user stepping action.
Definition at line 128 of file Geant4ActionPhase.cpp.
References execute().
call() [7/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (G4HCofThisEvent * hce)
Callback for sensitives begin/end/clear.
Definition at line 133 of file Geant4ActionPhase.cpp.
References execute().
call() [8/12]
template<> void DD4hep::Simulation::Geant4ActionPhase::call (G4Step * step, G4TouchableHistory * history)
Callback for sensitives.
Definition at line 137 of file Geant4ActionPhase.cpp.
References execute().
call() [9/12]
void DD4hep::Simulation::Geant4ActionPhase::call ()
Create action to execute phase members.
Callback in Begin stacking action.
Definition at line 104 of file Geant4ActionPhase.cpp.
References execute().
Referenced by DD4hep::Converter< T, ARG >::operator()().
call() [10/12]
template<typename A0 > void DD4hep::Simulation::Geant4ActionPhase::call (A0 a0)
call() [11/12]
template<typename A0 , typename A1 > void DD4hep::Simulation::Geant4ActionPhase::call (A0 a0, A1 a1)
call() [12/12]
template<typename A0 , typename A1 , typename A2 > void DD4hep::Simulation::Geant4ActionPhase::call (A0 a0, A1 a1, A2 a2)
execute()
void Geant4ActionPhase::execute (void * argument)
Execute all members in the phase context.
Definition at line 88 of file Geant4ActionPhase.cpp.
References m_members.
Referenced by call().
members()
const Members& DD4hep::Simulation::Geant4ActionPhase::members () const inline
Access phase members.
Definition at line 85 of file Geant4ActionPhase.h.
remove() [1/3]
bool Geant4ActionPhase::remove (Geant4Action * action, Callback callback) virtual
Remove an existing member from the phase. If not existing returns false.
Definition at line 66 of file Geant4ActionPhase.cpp.
References find(), DD4hep::Callback::mfunc_t::first, DD4hep::Callback::func, m_members, and DD4hep::Callback::par.
remove() [2/3]
template<typename TYPE , typename PMF > bool DD4hep::Simulation::Geant4ActionPhase::remove (TYPE * member) inline
Remove all member callbacks from the phase. If not existing returns false.
Definition at line 130 of file Geant4ActionPhase.h.
remove() [3/3]
template<typename TYPE , typename PMF > bool DD4hep::Simulation::Geant4ActionPhase::remove (TYPE * member, PMF callback) inline
Remove an existing member callback from the phase. If not existing returns false.
Definition at line 134 of file Geant4ActionPhase.h.
References DD4hep::Callback::make().
Member Data Documentation
m_argTypes
const std::type_info* DD4hep::Simulation::Geant4ActionPhase::m_argTypes[3] protected
Type information of the argument type of the callback.
Definition at line 76 of file Geant4ActionPhase.h.
Referenced by Geant4ActionPhase().
m_members
Members DD4hep::Simulation::Geant4ActionPhase::m_members protected
Phase members (actions) being called for a particular phase.
Definition at line 74 of file Geant4ActionPhase.h.
Referenced by add(), execute(), remove(), and ~Geant4ActionPhase().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ActionPhase.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ActionPhase.cpp