DD4hep: DD4hep::Alignments::Delta Class Reference
DD4hep::Alignments::Delta Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Class describing an condition to re-adjust an alignment.
#include <AlignmentData.h>
Public Types
enum AlignmentFlags { HAVE_NONE = 0, HAVE_TRANSLATION = 1<<2, HAVE_ROTATION = 1<<3, HAVE_PIVOT = 1<<4 }
typedef Translation3D Pivot
Public Member Functions
Delta ()
Default constructor.
Delta (const Position &tr)
Initializing constructor.
Delta (const RotationZYX &rot)
Initializing constructor.
Delta (const Position &tr, const RotationZYX &rot)
Initializing constructor.
Delta (const Translation3D &piv, const RotationZYX &rot)
Initializing constructor.
Delta (const Position &tr, const Translation3D &piv, const RotationZYX &rot)
Initializing constructor.
Delta (const Delta &c)
Copy constructor.
~Delta ()
Default destructor.
Delta & operator= (const Delta &c)
Assignment operator.
void clear ()
Reset information to identity.
bool checkFlag (unsigned int mask) const
Check a given flag.
void setFlag (unsigned int mask)
Check a given flag.
bool hasTranslation () const
Access flags: Check if the delta operation contains a translation.
bool hasRotation () const
Access flags: Check if the delta operation contains a rotation.
bool hasPivot () const
Access flags: Check if the delta operation contains a pivot.
Public Attributes
Position translation
Pivot pivot
RotationZYX rotation
unsigned int flags
Detailed Description
Class describing an condition to re-adjust an alignment.
Author
M.Frank
Version
1.0
Definition at line 49 of file AlignmentData.h.
Member Typedef Documentation
Pivot
typedef Translation3D DD4hep::Alignments::Delta::Pivot
Definition at line 51 of file AlignmentData.h.
Member Enumeration Documentation
AlignmentFlags
enum DD4hep::Alignments::Delta::AlignmentFlags
Enumerator
HAVE_NONE
HAVE_TRANSLATION
HAVE_ROTATION
HAVE_PIVOT
Definition at line 57 of file AlignmentData.h.
Constructor & Destructor Documentation
Delta() [1/7]
DD4hep::Alignments::Delta::Delta () inline
Default constructor.
Definition at line 65 of file AlignmentData.h.
Referenced by Delta().
Delta() [2/7]
DD4hep::Alignments::Delta::Delta (const Position & tr) inline
Initializing constructor.
Definition at line 67 of file AlignmentData.h.
Delta() [3/7]
DD4hep::Alignments::Delta::Delta (const RotationZYX & rot) inline
Initializing constructor.
Definition at line 70 of file AlignmentData.h.
Delta() [4/7]
DD4hep::Alignments::Delta::Delta (const Position & tr, const RotationZYX & rot) inline
Initializing constructor.
Definition at line 73 of file AlignmentData.h.
Delta() [5/7]
DD4hep::Alignments::Delta::Delta (const Translation3D & piv, const RotationZYX & rot) inline
Initializing constructor.
Definition at line 76 of file AlignmentData.h.
Delta() [6/7]
DD4hep::Alignments::Delta::Delta (const Position & tr, const Translation3D & piv, const RotationZYX & rot) inline
Initializing constructor.
Definition at line 79 of file AlignmentData.h.
References clear(), Delta(), operator=(), and ~Delta().
Delta() [7/7]
Delta::Delta (const Delta & c)
Copy constructor.
Definition at line 30 of file AlignmentData.cpp.
~Delta()
Delta::~Delta ()
Default destructor.
Definition at line 36 of file AlignmentData.cpp.
Referenced by Delta().
Member Function Documentation
checkFlag()
bool DD4hep::Alignments::Delta::checkFlag (unsigned int mask) const inline
Check a given flag.
Definition at line 90 of file AlignmentData.h.
Referenced by DD4hep::Alignments::AlignmentStack::StackEntry::checkOverlap(), DD4hep::Alignments::AlignmentStack::StackEntry::hasMatrix(), hasPivot(), hasRotation(), hasTranslation(), DD4hep::Alignments::AlignmentOperator::insert(), DD4hep::Alignments::AlignmentStack::StackEntry::needsReset(), DD4hep::Alignments::AlignmentStack::StackEntry::overlapDefined(), DD4hep::Alignments::AlignmentStack::StackEntry::overlapValue(), and DD4hep::Alignments::AlignmentStack::StackEntry::resetChildren().
clear()
void Delta::clear ()
Reset information to identity.
Definition at line 51 of file AlignmentData.cpp.
References flags, pivot, rotation, and translation.
Referenced by Delta().
hasPivot()
bool DD4hep::Alignments::Delta::hasPivot () const inline
Access flags: Check if the delta operation contains a pivot.
Definition at line 98 of file AlignmentData.h.
References checkFlag(), and HAVE_PIVOT.
hasRotation()
bool DD4hep::Alignments::Delta::hasRotation () const inline
Access flags: Check if the delta operation contains a rotation.
Definition at line 96 of file AlignmentData.h.
References checkFlag(), and HAVE_ROTATION.
hasTranslation()
bool DD4hep::Alignments::Delta::hasTranslation () const inline
Access flags: Check if the delta operation contains a translation.
Definition at line 94 of file AlignmentData.h.
References checkFlag(), and HAVE_TRANSLATION.
operator=()
Delta & Delta::operator= (const Delta & c)
Assignment operator.
Definition at line 40 of file AlignmentData.cpp.
References flags, pivot, rotation, and translation.
Referenced by Delta().
setFlag()
void DD4hep::Alignments::Delta::setFlag (unsigned int mask) inline
Check a given flag.
Definition at line 92 of file AlignmentData.h.
Member Data Documentation
flags
unsigned int DD4hep::Alignments::Delta::flags
Definition at line 55 of file AlignmentData.h.
Referenced by clear(), computeDelta(), operator=(), DD4hep::Alignments::AlignmentDecorator< T >::setDelta(), DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot(), DD4hep::Alignments::AlignmentStack::StackEntry::setOverlapCheck(), DD4hep::Alignments::AlignmentStack::StackEntry::setOverlapPrecision(), DD4hep::Alignments::AlignmentStack::StackEntry::setReset(), and DD4hep::Alignments::AlignmentStack::StackEntry::setResetChildren().
pivot
Pivot DD4hep::Alignments::Delta::pivot
Definition at line 53 of file AlignmentData.h.
Referenced by clear(), computeDelta(), DD4hep::Alignments::AlignmentOperator::insert(), operator<<(), operator=(), and DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot().
rotation
RotationZYX DD4hep::Alignments::Delta::rotation
Definition at line 54 of file AlignmentData.h.
Referenced by clear(), computeDelta(), DD4hep::Alignments::AlignmentOperator::insert(), operator<<(), operator=(), DD4hep::Alignments::AlignmentDecorator< T >::setDelta(), and DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot().
translation
Position DD4hep::Alignments::Delta::translation
Definition at line 52 of file AlignmentData.h.
Referenced by clear(), computeDelta(), DD4hep::Alignments::AlignmentOperator::insert(), operator<<(), operator=(), DD4hep::Alignments::AlignmentDecorator< T >::setDelta(), and DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/AlignmentData.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/AlignmentData.cpp