DD4hep: DD4hep: DD4hep::Simulation::Geant4UserInitialization Class Reference
DD4hep::Simulation::Geant4UserInitialization Class Reference
[DD4hep::Simulation components, classes and objects]
Base class to initialize a multi-threaded or single threaded Geant4 application.
#include <Geant4UserInitialization.h>
Public Member Functions
Geant4UserInitialization (Geant4Context *c, const std::string &nam)
Standard constructor.
virtual ~Geant4UserInitialization ()
Default destructor.
virtual void build () const
Callback function to build setup for the MT worker thread.
virtual void buildMaster () const
Callback function to build setup for the MT master thread.
Detailed Description
Base class to initialize a multi-threaded or single threaded Geant4 application.
Author:
M.Frank
Version:
1.0
Definition at line 34 of file Geant4UserInitialization.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4UserInitialization::Geant4UserInitialization (Geant4Context * c, const std::string & nam)
Standard constructor.
Geant4UserInitialization::~Geant4UserInitialization () [virtual]
Default destructor.
Definition at line 33 of file Geant4UserInitialization.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4UserInitialization::build () const [virtual]
Callback function to build setup for the MT worker thread.
Reimplemented in DD4hep::Simulation::Geant4UserInitializationSequence.
Definition at line 38 of file Geant4UserInitialization.cpp.
Referenced by DD4hep::Simulation::Geant4UserInitializationSequence::build().
void Geant4UserInitialization::buildMaster () const [virtual]
Callback function to build setup for the MT master thread.
Reimplemented in DD4hep::Simulation::Geant4UserInitializationSequence.
Definition at line 42 of file Geant4UserInitialization.cpp.
Referenced by DD4hep::Simulation::Geant4UserInitializationSequence::buildMaster().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4UserInitialization.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4UserInitialization.cpp