DD4hep: DD4hep: DD4hep::Conditions::ConditionUpdateContext Class Reference
DD4hep::Conditions::ConditionUpdateContext Class Reference
[DDCond: DD4hep Detector Conditions components, classes and functions]
ConditionUpdateContext class used by the derived conditions calculation mechanism.
#include <ConditionDerived.h>
Public Member Functions
ConditionUpdateContext (const ConditionResolver &r, const ConditionDependency &d, void *parameter, Condition::iov_type &iov)
Initializing constructor.
const ConditionKey & key (size_t which) const
Access to dependency keys.
Condition condition (size_t which) const
Access to condition object by dependency index.
Condition condition (const ConditionKey &key_value) const
Access to condition object by dependency key.
template<typename Q >
Q * param () const
Access user parameter.
template<typename T >
T & get (const ConditionKey &key_value)
Access of other conditions data from the resolver.
template<typename T >
const T & get (const ConditionKey &key_value) const
Access of other conditions data from the resolver.
template<typename T >
T & get (size_t key_id)
Access of other conditions data from the resolver.
template<typename T >
const T & get (size_t key_id) const
Access of other conditions data from the resolver.
Public Attributes
const ConditionResolver & resolver
const ConditionDependency & dependency
Condition::iov_type * iov
void * parameter
Detailed Description
ConditionUpdateContext class used by the derived conditions calculation mechanism.
Author:
M.Frank
Version:
1.0
Definition at line 63 of file ConditionDerived.h.
Constructor & Destructor Documentation
DD4hep::Conditions::ConditionUpdateContext::ConditionUpdateContext (const ConditionResolver & r, const ConditionDependency & d, void * parameter, Condition::iov_type & iov) [inline]
Initializing constructor.
Definition at line 220 of file ConditionDerived.h.
Member Function Documentation
Condition DD4hep::Conditions::ConditionUpdateContext::condition (const ConditionKey & key_value) const [inline]
Access to condition object by dependency key.
Definition at line 234 of file ConditionDerived.h.
References DD4hep::Conditions::ConditionResolver::get(), DD4hep::Handle< T >::isValid(), DD4hep::Conditions::ConditionKey::name, and resolver.
Condition DD4hep::Conditions::ConditionUpdateContext::condition (size_t which) const [inline]
Access to condition object by dependency index.
Definition at line 241 of file ConditionDerived.h.
References key().
template<typename T > const T& DD4hep::Conditions::ConditionUpdateContext::get (size_t key_id) const [inline]
Access of other conditions data from the resolver.
Definition at line 112 of file ConditionDerived.h.
References key().
template<typename T > T& DD4hep::Conditions::ConditionUpdateContext::get (size_t key_id) [inline]
Access of other conditions data from the resolver.
Definition at line 107 of file ConditionDerived.h.
References key().
template<typename T > const T& DD4hep::Conditions::ConditionUpdateContext::get (const ConditionKey & key_value) const [inline]
Access of other conditions data from the resolver.
Bind data to wanted type
Update result IOV according by and'ing the new iov structure
Definition at line 96 of file ConditionDerived.h.
References DD4hep::Conditions::Condition::get(), DD4hep::Conditions::ConditionResolver::get(), DD4hep::Conditions::Condition::iov(), iov, DD4hep::IOV::iov_intersection(), DD4hep::Handle< T >::isValid(), and resolver.
template<typename T > T& DD4hep::Conditions::ConditionUpdateContext::get (const ConditionKey & key_value) [inline]
Access of other conditions data from the resolver.
Bind data to wanted type
Update result IOV according by and'ing the new iov structure
Definition at line 85 of file ConditionDerived.h.
References DD4hep::Conditions::Condition::get(), DD4hep::Conditions::ConditionResolver::get(), DD4hep::Conditions::Condition::iov(), iov, DD4hep::IOV::iov_intersection(), DD4hep::Handle< T >::isValid(), and resolver.
const ConditionKey & DD4hep::Conditions::ConditionUpdateContext::key (size_t which) const [inline]
Access to dependency keys.
Definition at line 229 of file ConditionDerived.h.
References DD4hep::Conditions::ConditionDependency::dependencies, and dependency.
Referenced by condition(), and get().
template<typename Q > Q* DD4hep::Conditions::ConditionUpdateContext::param () const [inline]
Access user parameter.
Definition at line 81 of file ConditionDerived.h.
References parameter.
Member Data Documentation
const ConditionDependency& DD4hep::Conditions::ConditionUpdateContext::dependency
Definition at line 66 of file ConditionDerived.h.
Referenced by DD4hep::Alignments::AlignmentUpdateCall::handle(), and key().
Condition::iov_type* DD4hep::Conditions::ConditionUpdateContext::iov
Definition at line 67 of file ConditionDerived.h.
Referenced by get().
void* DD4hep::Conditions::ConditionUpdateContext::parameter
Definition at line 68 of file ConditionDerived.h.
Referenced by DD4hep::Alignments::AlignmentsManager::newEntry(), and param().
const ConditionResolver& DD4hep::Conditions::ConditionUpdateContext::resolver
Definition at line 65 of file ConditionDerived.h.
Referenced by condition(), and get().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ConditionDerived.h