DD4hep: DD4hep: DD4hep::DDRec::SurfaceManager Class Reference
DD4hep::DDRec::SurfaceManager Class Reference
#include <SurfaceManager.h>
Public Member Functions
SurfaceManager ()
~SurfaceManager ()
const SurfaceMap * map (const std::string name) const
std::string toString () const
create a string with all available maps and their size (number of surfaces)
Protected Member Functions
void initialize ()
initialize all known surface maps
Protected Attributes
SurfaceMapsMap _map
Private Types
typedef std::map< std::string,
SurfaceMap > SurfaceMapsMap
Detailed Description
Surface manager class that holds maps of surfaces for all known sensitive detector types and individual sub detectors. Maps can be retrieved via detector name.
Author:
F.Gaede, DESY
Date:
May, 11 2015
Version:
$Id$
Definition at line 22 of file SurfaceManager.h.
Member Typedef Documentation
typedef std::map< std::string, SurfaceMap > DD4hep::DDRec::SurfaceManager::SurfaceMapsMap [private]
Definition at line 24 of file SurfaceManager.h.
Constructor & Destructor Documentation
DD4hep::DDRec::SurfaceManager::SurfaceManager ()
Definition at line 16 of file SurfaceManager.cpp.
References initialize().
DD4hep::DDRec::SurfaceManager::~SurfaceManager ()
Definition at line 21 of file SurfaceManager.cpp.
Member Function Documentation
void DD4hep::DDRec::SurfaceManager::initialize () [protected]
initialize all known surface maps
Definition at line 38 of file SurfaceManager.cpp.
References _map, DD4hep::Geometry::LCDD::detectors(), DD4hep::Geometry::LCDD::detectorTypes(), DD4hep::Geometry::LCDD::getInstance(), DDSurfaces::ISurface::id(), and DD4hep::DDRec::SurfaceHelper::surfaceList().
Referenced by SurfaceManager().
const SurfaceMap * DD4hep::DDRec::SurfaceManager::map (const std::string name) const
Get the maps of all surfaces associated to the given detector or type of detectors, e.g. map("tracker") returns a map with all surfaces assigned to tracking detectors. Returns 0 if no map exists.
Definition at line 26 of file SurfaceManager.cpp.
References _map.
std::string DD4hep::DDRec::SurfaceManager::toString () const
create a string with all available maps and their size (number of surfaces)
Definition at line 77 of file SurfaceManager.cpp.
References _map.
Member Data Documentation
SurfaceMapsMap DD4hep::DDRec::SurfaceManager::_map [protected]
Definition at line 48 of file SurfaceManager.h.
Referenced by initialize(), map(), and toString().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/SurfaceManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/SurfaceManager.cpp