DD4hep: DD4hep::XML::Element Class Reference
DD4hep::XML::Element Class Reference
DD4hep::XML classes and objects
User abstraction class to manipulate XML elements within a document.
#include <XMLElements.h>
Public Types
typedef Handle_t::Elt_t Elt_t
Simplification type declarations.
Public Member Functions
Element (const Handle_t &e)
Constructor from XmlElement handle.
Element (const Element &e)
Constructor from XmlElement handle.
Element (const Document &document, const XmlChar *type)
Constructor from DOM document entity.
Document document () const
Access the hosting document handle of this DOM element.
operator bool () const
operator bool: check handle validity
bool operator! () const
operator NOT: check handle validity
Element & operator= (const Element &c)
Assignment operator.
Element & operator= (Handle_t handle)
Assignment operator.
operator Handle_t () const
Automatic conversion to DOM element handle.
operator Elt_t () const
Automatic conversion to XmlElement pointer.
Elt_t ptr () const
Access to XmlElement pointer.
Handle_t parent () const
Access the XmlElements parent.
Elt_t parentElement () const
Access the XmlElements parent.
std::string tag () const
Access the tag name of this DOM element.
const XmlChar * tagName () const
Access the tag name of this DOM element.
void append (Handle_t handle) const
Append a new element to the existing tree.
Handle_t clone (const Document &new_doc) const
Clone the DOMelement.
bool hasAttr (const XmlChar *name) const
Check for the existence of a named attribute.
template<class T >
T attr (const XmlChar *tag_value) const
Access attribute with implicit return type conversion.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
const XmlChar * attr_name (const Attribute a) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute a) const
Access attribute value by the attribute (throws exception if not present)
size_t numChildren (const XmlChar *tag_value, bool exc=true) const
Access the number of children of this DOM element with a given tag name.
void setAttrs (Handle_t e) const
Remove own attributes and copy all attributes from handle 'e'.
void removeAttrs () const
Remove all attributes of this element.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
Attribute getAttr (const XmlChar *name) const
Access single attribute by it's name.
template<class T >
Attribute setAttr (const XmlChar *nam, const T &val) const
Set single attribute.
template<class T >
void setValue (const T &val) const
Set element value.
Handle_t clone (Handle_t h) const
Clone the DOM element tree.
Handle_t addChild (const XmlChar *tag) const
Add a new child to the DOM node.
Handle_t setChild (const XmlChar *tag) const
Check if a child with the required tag exists - if not create it and add it to the current node.
Handle_t child (const Strng_t &tag_value, bool except=true) const
Access child by tag name. Thow an exception if required in case the child is not present.
Handle_t remove (Handle_t node) const
Remove a child node identified by its handle.
bool hasChild (const XmlChar *tag_value) const
Check the existence of a child with a given tag name.
Attribute setRef (const XmlChar *tag, const XmlChar *refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Attribute setRef (const XmlChar *tag, const std::string &refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
const XmlChar * getRef (const XmlChar *tag) const
Access the value of the reference attribute of the node (attribute ref="ref-name")
void addComment (const char *text) const
Add comment node to the element.
Public Attributes
Handle_t m_element
The underlying object holding the XmlElement pointer.
Detailed Description
User abstraction class to manipulate XML elements within a document.
User class encapsulating a DOM element using the Handle helper. This is the main class we interact with when analysing the xml documents for constructing sub-detectors etc.
Author
M.Frank
Version
1.0
Definition at line 686 of file XMLElements.h.
Member Typedef Documentation
Elt_t
typedef Handle_t::Elt_t DD4hep::XML::Element::Elt_t
Simplification type declarations.
Definition at line 689 of file XMLElements.h.
Constructor & Destructor Documentation
Element() [1/3]
DD4hep::XML::Element::Element (const Handle_t & e) inline
Constructor from XmlElement handle.
Definition at line 695 of file XMLElements.h.
Element() [2/3]
DD4hep::XML::Element::Element (const Element & e) inline
Constructor from XmlElement handle.
Definition at line 697 of file XMLElements.h.
Element() [3/3]
Element::Element (const Document & document, const XmlChar * type)
Constructor from DOM document entity.
Definition at line 1067 of file XMLElements.cpp.
Member Function Documentation
addChild()
Handle_t Element::addChild (const XmlChar * tag) const
Add a new child to the DOM node.
Definition at line 1113 of file XMLElements.cpp.
References DD4hep::XML::Handle_t::append(), DD4hep::XML::Document::createElt(), document(), e, and m_element.
Referenced by setChild().
addComment()
void Element::addComment (const char * text) const
Add comment node to the element.
Definition at line 1126 of file XMLElements.cpp.
References _D, _N, document(), and m_element.
Referenced by DD4hep::XML::DocumentHandler::create().
append()
void DD4hep::XML::Element::append (Handle_t handle) const inline
Append a new element to the existing tree.
Definition at line 748 of file XMLElements.h.
References DD4hep::XML::Handle_t::append().
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::addNode(), DD4hep::Alignments::GlobalAlignmentWriter::createElement(), DD4hep::Alignments::GlobalAlignmentWriter::dump(), DD4hep::XML::Handle_t::setRef(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
attr() [1/2]
template<class T > T DD4hep::XML::Element::attr (const XmlChar * tag_value) const inline
Access attribute with implicit return type conversion.
Definition at line 760 of file XMLElements.h.
References DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Handle_t::attr_name().
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_convertSensitive(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::XML::Dimension::padType().
attr() [2/2]
template<class T > T DD4hep::XML::Element::attr (const char * name) const inline
Access typed attribute value by it's name.
Definition at line 765 of file XMLElements.h.
attr_name()
const XmlChar* DD4hep::XML::Element::attr_name (const Attribute a) const inline
Access attribute name (throws exception if not present)
Definition at line 770 of file XMLElements.h.
attr_value()
const XmlChar* DD4hep::XML::Element::attr_value (const Attribute a) const inline
Access attribute value by the attribute (throws exception if not present)
Definition at line 774 of file XMLElements.h.
References DD4hep::XML::Handle_t::attr_value().
attributes()
std::vector<Attribute> DD4hep::XML::Element::attributes () const inline
Retrieve a collection of all attributes of this DOM element.
Definition at line 790 of file XMLElements.h.
References DD4hep::XML::Handle_t::attributes().
child()
Handle_t DD4hep::XML::Element::child (const Strng_t & tag_value, bool except = true) const inline
Access child by tag name. Thow an exception if required in case the child is not present.
Definition at line 811 of file XMLElements.h.
References DD4hep::XML::Handle_t::child(), and DD4hep::except().
Referenced by DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_setProperties(), create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), getRef(), and DD4hep::XML::setDetectorTypeFlag().
clone() [1/2]
Handle_t DD4hep::XML::Element::clone (const Document & new_doc) const inline
Clone the DOMelement.
Definition at line 752 of file XMLElements.h.
References DD4hep::XML::Document::clone().
clone() [2/2]
Handle_t Element::clone (Handle_t h) const
Clone the DOM element tree.
Definition at line 1086 of file XMLElements.cpp.
References DD4hep::XML::Handle_t::clone(), document(), and m_element.
document()
Document Element::document () const
Access the hosting document handle of this DOM element.
Definition at line 1081 of file XMLElements.cpp.
References _N, and m_element.
Referenced by addChild(), addComment(), DD4hep::Alignments::GlobalAlignmentWriter::addNode(), clone(), DD4hep::XML::DocumentHandler::output(), and DD4hep::XML::Handle_t::setRef().
getAttr()
Attribute Element::getAttr (const XmlChar * name) const
Access single attribute by it's name.
Definition at line 1093 of file XMLElements.cpp.
References m_element.
Referenced by DD4hep::XML::RefElement::RefElement().
getRef()
const XmlChar * Element::getRef (const XmlChar * tag) const
Access the value of the reference attribute of the node (attribute ref="ref-name")
Definition at line 1108 of file XMLElements.cpp.
References DD4hep::XML::Handle_t::attr(), and child().
hasAttr()
bool DD4hep::XML::Element::hasAttr (const XmlChar * name) const inline
Check for the existence of a named attribute.
Definition at line 756 of file XMLElements.h.
References DD4hep::XML::Handle_t::hasAttr().
Referenced by DD4hep::Simulation::_setProperties(), create_detector(), create_element(), DD4hep::XML::LayeringCnv::fromCompact(), and DD4hep::Converter< T, ARG >::operator()().
hasChild()
bool DD4hep::XML::Element::hasChild (const XmlChar * tag_value) const inline
Check the existence of a child with a given tag name.
Definition at line 819 of file XMLElements.h.
References DD4hep::XML::Handle_t::hasChild().
Referenced by DD4hep::Simulation::_convertAction(), create_element(), and DD4hep::XML::createPlacedEnvelope().
numChildren()
size_t DD4hep::XML::Element::numChildren (const XmlChar * tag_value, bool exc = true) const inline
Access the number of children of this DOM element with a given tag name.
Definition at line 778 of file XMLElements.h.
References DD4hep::XML::Handle_t::numChildren().
Referenced by create_detector().
operator bool()
DD4hep::XML::Element::operator bool () const inline
operator bool: check handle validity
Definition at line 704 of file XMLElements.h.
References DD4hep::XML::Handle_t::ptr().
operator Elt_t()
DD4hep::XML::Element::operator Elt_t () const inline
Automatic conversion to XmlElement pointer.
Definition at line 726 of file XMLElements.h.
operator Handle_t()
DD4hep::XML::Element::operator Handle_t () const inline
Automatic conversion to DOM element handle.
Definition at line 722 of file XMLElements.h.
operator!()
bool DD4hep::XML::Element::operator! () const inline
operator NOT: check handle validity
Definition at line 708 of file XMLElements.h.
References DD4hep::XML::Handle_t::ptr().
operator=() [1/2]
Element& DD4hep::XML::Element::operator= (const Element & c) inline
Assignment operator.
Definition at line 712 of file XMLElements.h.
References m_element.
operator=() [2/2]
Element& DD4hep::XML::Element::operator= (Handle_t handle) inline
Assignment operator.
Definition at line 717 of file XMLElements.h.
References handle().
parent()
Handle_t DD4hep::XML::Element::parent () const inline
Access the XmlElements parent.
Definition at line 734 of file XMLElements.h.
References DD4hep::XML::Handle_t::parent().
parentElement()
Element::Elt_t Element::parentElement () const
Access the XmlElements parent.
Definition at line 1072 of file XMLElements.cpp.
References _N, ELEMENT_NODE_TYPE, m_element, DD4hep::XML::Handle_t::parent(), and DD4hep::XML::Handle_t::ptr().
ptr()
Elt_t DD4hep::XML::Element::ptr () const inline
Access to XmlElement pointer.
Definition at line 730 of file XMLElements.h.
Referenced by setRef().
remove()
Handle_t DD4hep::XML::Element::remove (Handle_t node) const inline
Remove a child node identified by its handle.
Definition at line 815 of file XMLElements.h.
References DD4hep::XML::Handle_t::remove().
removeAttrs()
void DD4hep::XML::Element::removeAttrs () const inline
Remove all attributes of this element.
Definition at line 786 of file XMLElements.h.
References DD4hep::XML::Handle_t::removeAttrs().
setAttr()
template<class T > Attribute DD4hep::XML::Element::setAttr (const XmlChar * nam, const T & val) const inline
Set single attribute.
Definition at line 797 of file XMLElements.h.
References DD4hep::XML::Handle_t::setAttr().
Referenced by DD4hep::Alignments::GlobalAlignmentWriter::addNode(), DD4hep::Alignments::GlobalAlignmentWriter::createElement(), DD4hep::XML::RefElement::RefElement(), DD4hep::XML::RefElement::setName(), and DD4hep::XML::Handle_t::setRef().
setAttrs()
void DD4hep::XML::Element::setAttrs (Handle_t e) const inline
Remove own attributes and copy all attributes from handle 'e'.
Definition at line 782 of file XMLElements.h.
References DD4hep::XML::Handle_t::setAttrs().
setChild()
Handle_t Element::setChild (const XmlChar * tag) const
Check if a child with the required tag exists - if not create it and add it to the current node.
Definition at line 1120 of file XMLElements.cpp.
References addChild(), DD4hep::XML::Handle_t::child(), e, and m_element.
Referenced by setRef().
setRef() [1/2]
Attribute Element::setRef (const XmlChar * tag, const XmlChar * refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Definition at line 1098 of file XMLElements.cpp.
References DD4hep::XML::Handle_t::setAttr(), and setChild().
Referenced by setRef().
setRef() [2/2]
Attribute Element::setRef (const XmlChar * tag, const std::string & refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Definition at line 1103 of file XMLElements.cpp.
References ptr(), and setRef().
setValue()
template<class T > void DD4hep::XML::Element::setValue (const T & val) const inline
Set element value.
Definition at line 801 of file XMLElements.h.
References DD4hep::XML::Handle_t::setValue().
tag()
std::string DD4hep::XML::Element::tag () const inline
Access the tag name of this DOM element.
Definition at line 740 of file XMLElements.h.
References DD4hep::XML::Handle_t::tag().
tagName()
const XmlChar* DD4hep::XML::Element::tagName () const inline
Access the tag name of this DOM element.
Definition at line 744 of file XMLElements.h.
References DD4hep::XML::Handle_t::rawTag().
Member Data Documentation
m_element
Handle_t DD4hep::XML::Element::m_element
The underlying object holding the XmlElement pointer.
Definition at line 692 of file XMLElements.h.
Referenced by addChild(), addComment(), DD4hep::XML::DetElement::attr(), clone(), document(), getAttr(), DD4hep::XML::DetElement::handle(), DD4hep::XML::Dimension::limitsStr(), DD4hep::XML::Dimension::moduleStr(), DD4hep::XML::RefElement::name(), DD4hep::XML::Dimension::nameStr(), operator=(), DD4hep::XML::RefElement::operator=(), parentElement(), DD4hep::XML::Dimension::readoutStr(), DD4hep::XML::RefElement::RefElement(), DD4hep::XML::RefElement::refName(), DD4hep::XML::Dimension::refStr(), DD4hep::XML::Dimension::regionStr(), setChild(), DD4hep::XML::Dimension::typeStr(), DD4hep::XML::Dimension::valueStr(), and DD4hep::XML::Dimension::visStr().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp