DD4hep: DD4hep: DD4hep::Geometry::Solid_type< T > Class Template Reference
DD4hep::Geometry::Solid_type< T > Class Template Reference
[DD4hep::Geometry components, classes and objects]
Base class for Solid (shape) objects.
#include <Shapes.h>
Public Member Functions
Solid_type ()
Default constructor for uninitialized object.
Solid_type (const Solid_type &e)
Constructor to be used when passing an already created object.
Solid_type (T *p)
Direct assignment using the implementation pointer.
Solid_type (const Handle< T > &e)
Constructor to be used when passing an already created object.
template<typename Q >
Solid_type (const Handle< Q > &e)
Constructor to be used when passing an already created object: need to check pointers.
Solid_type & operator= (const Solid_type &copy)
Assignment operator.
const char * name () const
Access to shape name.
operator T * () const
Auto conversion to underlying ROOT object.
T * operator-> () const
Overloaded operator -> to access underlying object.
std::string toString (int precision=2) const
Conversion to string for pretty print.
Protected Types
typedef T Implementation
Extern accessible definition of the contained element type.
Protected Member Functions
void _setDimensions (double *param)
void _assign (T *n, const std::string &nam, const std::string &tit, bool cbbox)
Assign pointrs and register solid to geometry.
Detailed Description
template<typename T>
class DD4hep::Geometry::Solid_type< T >
Base class for Solid (shape) objects.
Generic handle holding an object of base TGeoShape.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoShape.html
Author:
M.Frank
Version:
1.0
Definition at line 69 of file Shapes.h.
Member Typedef Documentation
template<typename T> typedef T DD4hep::Geometry::Solid_type< T >::Implementation [protected]
Extern accessible definition of the contained element type.
Type definitions and class specific abbreviations and forward declarations
Reimplemented from DD4hep::Handle< T >.
Definition at line 71 of file Shapes.h.
Constructor & Destructor Documentation
template<typename T> DD4hep::Geometry::Solid_type< T >::Solid_type ()
Default constructor for uninitialized object.
template<typename T> DD4hep::Geometry::Solid_type< T >::Solid_type (const Solid_type< T > & e)
Constructor to be used when passing an already created object.
template<typename T> DD4hep::Geometry::Solid_type< T >::Solid_type (T * p) [inline]
Direct assignment using the implementation pointer.
Definition at line 83 of file Shapes.h.
template<typename T> DD4hep::Geometry::Solid_type< T >::Solid_type (const Handle< T > & e) [inline]
Constructor to be used when passing an already created object.
Definition at line 85 of file Shapes.h.
template<typename T> template<typename Q > DD4hep::Geometry::Solid_type< T >::Solid_type (const Handle< Q > & e) [inline]
Constructor to be used when passing an already created object: need to check pointers.
Definition at line 87 of file Shapes.h.
Member Function Documentation
template<typename T> void DD4hep::Geometry::Solid_type< T >::_assign (T * n, const std::string & nam, const std::string & tit, bool cbbox) [protected]
Assign pointrs and register solid to geometry.
template<typename T > void Solid_type::_setDimensions (double * param) [inline, protected]
Definition at line 158 of file Shapes.cpp.
References DD4hep::Handle< T >::ptr().
template<typename T > const char * Solid_type::name () const [inline]
Access to shape name.
Reimplemented from DD4hep::Handle< T >.
Definition at line 172 of file Shapes.cpp.
References DD4hep::Handle< T >::ptr().
template<typename T> DD4hep::Geometry::Solid_type< T >::operator T * () const [inline]
Auto conversion to underlying ROOT object.
Definition at line 94 of file Shapes.h.
template<typename T> T* DD4hep::Geometry::Solid_type< T >::operator-> () const [inline]
Overloaded operator -> to access underlying object.
Reimplemented from DD4hep::Handle< T >.
Definition at line 98 of file Shapes.h.
template<typename T> Solid_type& DD4hep::Geometry::Solid_type< T >::operator= (const Solid_type< T > & copy)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
template<typename T> std::string DD4hep::Geometry::Solid_type< T >::toString (int precision = 2) const [inline]
Conversion to string for pretty print.
Definition at line 102 of file Shapes.h.
Referenced by DD4hep::SurfaceInstaller::install().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp