DD4hep: DD4hep::Conditions::ConditionsDependencyHandler Class Reference
DD4hep::Conditions::ConditionsDependencyHandler Class Reference
Callback handler to update condition dependencies.
#include <ConditionsDependencyHandler.h>
Public Types
typedef ConditionsManager::Dependencies Dependencies
Public Member Functions
ConditionsDependencyHandler (ConditionsManager::Object *mgr, UserPool &pool, const Dependencies &dependencies, void *user_param)
Initializing constructor.
~ConditionsDependencyHandler ()
Default destructor.
virtual Ref_t manager () const
ConditionResolver implementation: Access to the conditions manager.
virtual LCDD & lcdd () const
ConditionResolver implementation: Access to the detector description instance.
virtual const IOV & requiredValidity () const
Required IOV value for update cycle.
virtual Condition get (const ConditionKey &key) const
ConditionResolver implementation: Interface to access conditions.
virtual Condition get (unsigned int key) const
ConditionResolver implementation: Interface to access conditions.
Condition::Object * operator() (const ConditionDependency *dep) const
Handler callback to process multiple derived conditions.
Public Member Functions inherited from DD4hep::Conditions::ConditionResolver
virtual ~ConditionResolver ()
Standard destructor.
Protected Member Functions
Condition::Object * do_callback (const ConditionDependency &dep) const
Internal call to trigger update callback.
Protected Attributes
ConditionsManager::Object * m_manager
Reference to conditions manager.
UserPool & m_pool
Reference to the user pool object.
const Dependencies & m_dependencies
Dependency container to be resolved.
void * m_userParam
User defined optional processing parameter.
Detailed Description
Callback handler to update condition dependencies.
Author
M.Frank
Version
1.0
Definition at line 38 of file ConditionsDependencyHandler.h.
Member Typedef Documentation
Dependencies
typedef ConditionsManager::Dependencies DD4hep::Conditions::ConditionsDependencyHandler::Dependencies
Definition at line 40 of file ConditionsDependencyHandler.h.
Constructor & Destructor Documentation
ConditionsDependencyHandler()
ConditionsDependencyHandler::ConditionsDependencyHandler (ConditionsManager::Object * mgr, UserPool & pool, const Dependencies & dependencies, void * user_param)
Initializing constructor.
Default constructor.
Definition at line 23 of file ConditionsDependencyHandler.cpp.
~ConditionsDependencyHandler()
ConditionsDependencyHandler::~ConditionsDependencyHandler ()
Default destructor.
Definition at line 32 of file ConditionsDependencyHandler.cpp.
Member Function Documentation
do_callback()
Condition::Object * ConditionsDependencyHandler::do_callback (const ConditionDependency & dep) const protected
Internal call to trigger update callback.
Definition at line 62 of file ConditionsDependencyHandler.cpp.
References DD4hep::Conditions::ConditionDependency::callback, DD4hep::Conditions::Condition::DERIVED, e, DD4hep::ERROR, DD4hep::except(), DD4hep::Conditions::Interna::ConditionObject::hash, DD4hep::Conditions::ConditionKey::hashCode(), DD4hep::Conditions::UserPool::insert(), DD4hep::IOV::iovType, m_pool, m_userParam, DD4hep::NamedObject::name, DD4hep::Conditions::ConditionKey::name, DD4hep::Conditions::UserPool::print(), DD4hep::printout(), DD4hep::Conditions::ConditionDependency::target, DD4hep::Conditions::UserPool::validity(), and DD4hep::Conditions::UserPool::validityPtr().
Referenced by get(), and operator()().
get() [1/2]
virtual Condition DD4hep::Conditions::ConditionsDependencyHandler::get (const ConditionKey & key) const inline virtual
ConditionResolver implementation: Interface to access conditions.
Implements DD4hep::Conditions::ConditionResolver.
Definition at line 72 of file ConditionsDependencyHandler.h.
References operator()().
get() [2/2]
Condition ConditionsDependencyHandler::get (unsigned int key) const virtual
ConditionResolver implementation: Interface to access conditions.
This condition is no longer valid. remove it! Will be added again afterwards.
Implements DD4hep::Conditions::ConditionResolver.
Definition at line 36 of file ConditionsDependencyHandler.cpp.
References do_callback(), DD4hep::Conditions::ConditionsDependencyCollection::end(), DD4hep::Conditions::ConditionsDependencyCollection::find(), DD4hep::Conditions::UserPool::get(), DD4hep::Conditions::Interna::ConditionObject::iov, DD4hep::Handle< T >::isValid(), DD4hep::IOV::key_is_contained(), DD4hep::IOV::keyData, m_dependencies, m_pool, DD4hep::Handle< T >::ptr(), DD4hep::Conditions::UserPool::remove(), and DD4hep::Conditions::UserPool::validity().
lcdd()
virtual LCDD& DD4hep::Conditions::ConditionsDependencyHandler::lcdd () const inline virtual
ConditionResolver implementation: Access to the detector description instance.
Implements DD4hep::Conditions::ConditionResolver.
Definition at line 67 of file ConditionsDependencyHandler.h.
References DD4hep::Conditions::ConditionsManagerObject::lcdd().
manager()
virtual Ref_t DD4hep::Conditions::ConditionsDependencyHandler::manager () const inline virtual
ConditionResolver implementation: Access to the conditions manager.
Implements DD4hep::Conditions::ConditionResolver.
Definition at line 64 of file ConditionsDependencyHandler.h.
References m_manager.
operator()()
Condition::Object * ConditionsDependencyHandler::operator() (const ConditionDependency * dep) const
Handler callback to process multiple derived conditions.
Definition at line 96 of file ConditionsDependencyHandler.cpp.
References do_callback().
Referenced by get().
requiredValidity()
virtual const IOV& DD4hep::Conditions::ConditionsDependencyHandler::requiredValidity () const inline virtual
Required IOV value for update cycle.
Implements DD4hep::Conditions::ConditionResolver.
Definition at line 69 of file ConditionsDependencyHandler.h.
References DD4hep::Conditions::UserPool::validity().
Member Data Documentation
m_dependencies
const Dependencies& DD4hep::Conditions::ConditionsDependencyHandler::m_dependencies protected
Dependency container to be resolved.
Definition at line 48 of file ConditionsDependencyHandler.h.
Referenced by get().
m_manager
ConditionsManager::Object* DD4hep::Conditions::ConditionsDependencyHandler::m_manager protected
Reference to conditions manager.
Definition at line 44 of file ConditionsDependencyHandler.h.
Referenced by manager().
m_pool
UserPool& DD4hep::Conditions::ConditionsDependencyHandler::m_pool protected
Reference to the user pool object.
Definition at line 46 of file ConditionsDependencyHandler.h.
Referenced by do_callback(), and get().
m_userParam
void* DD4hep::Conditions::ConditionsDependencyHandler::m_userParam protected
User defined optional processing parameter.
Definition at line 50 of file ConditionsDependencyHandler.h.
Referenced by do_callback().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsDependencyHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsDependencyHandler.cpp