DD4hep: DD4hep::Conditions::ConditionsIOVPool Class Reference
DD4hep::Conditions::ConditionsIOVPool Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Pool of conditions satisfying one IOV type (epoch, run, fill, etc)
#include <ConditionsIOVPool.h>
Public Types
typedef ConditionsPool * Element
typedef std::map< IOV::Key, Element > Elements
Public Member Functions
ConditionsIOVPool ()
Default constructor.
virtual ~ConditionsIOVPool ()
Default destructor.
void select (Condition::key_type key, const Condition::iov_type &req_validity, RangeConditions &result)
Retrieve a condition set given the key according to their validity.
void selectRange (Condition::key_type key, const Condition::iov_type &req_validity, RangeConditions &result)
Retrieve a condition set given the key according to their validity.
void select (const Condition::iov_type &required_validity, RangeConditions &valid, RangeConditions &expired, Condition::iov_type &conditions_validity)
Select all ACTIVE conditions, which do no longer match the IOV requirement.
int clean (int max_age)
Remove all key based pools with an age beyon the minimum age.
Public Attributes
Elements elements
Container of IOV dependent conditions pools.
Detailed Description
Pool of conditions satisfying one IOV type (epoch, run, fill, etc)
Purely internal class to the conditions manager implementation. Not at all to be accessed by clients!
Author
M.Frank
Version
1.0
Definition at line 41 of file ConditionsIOVPool.h.
Member Typedef Documentation
Element
typedef ConditionsPool* DD4hep::Conditions::ConditionsIOVPool::Element
Definition at line 43 of file ConditionsIOVPool.h.
Elements
typedef std::map<IOV::Key, Element > DD4hep::Conditions::ConditionsIOVPool::Elements
Definition at line 44 of file ConditionsIOVPool.h.
Constructor & Destructor Documentation
ConditionsIOVPool()
ConditionsIOVPool::ConditionsIOVPool ()
Default constructor.
Definition at line 26 of file ConditionsIOVPool.cpp.
References DD4hep::InstanceCount::increment().
~ConditionsIOVPool()
ConditionsIOVPool::~ConditionsIOVPool () virtual
Default destructor.
Definition at line 31 of file ConditionsIOVPool.cpp.
References clean(), and DD4hep::InstanceCount::decrement().
Member Function Documentation
clean()
int ConditionsIOVPool::clean (int max_age)
Remove all key based pools with an age beyon the minimum age.
Returns
Number of conditions cleaned up and removed.
Definition at line 66 of file ConditionsIOVPool.cpp.
References DD4hep::Conditions::ConditionsPool::age_value, DD4hep::Conditions::ConditionsPool::count(), elements, DD4hep::Conditions::ConditionsPool::insert(), DD4hep::Conditions::ConditionsPool::iov, DD4hep::IOV::keyData, and DD4hep::Conditions::ConditionsPool::print().
Referenced by DD4hep::Conditions::ConditionsManagerObject::clean(), DD4hep::Conditions::ConditionsManagerObject::clear(), and ~ConditionsIOVPool().
select() [1/2]
void ConditionsIOVPool::select (Condition::key_type key, const Condition::iov_type & req_validity, RangeConditions & result)
Retrieve a condition set given the key according to their validity.
Definition at line 36 of file ConditionsIOVPool.cpp.
References elements, DD4hep::IOV::key(), and DD4hep::IOV::key_contains_range().
Referenced by DD4hep::Conditions::ConditionsManagerObject::pushUpdates(), and DD4hep::Conditions::ConditionsManagerObject::select().
select() [2/2]
void ConditionsIOVPool::select (const Condition::iov_type & required_validity, RangeConditions & valid, RangeConditions & expired, Condition::iov_type & conditions_validity)
Select all ACTIVE conditions, which do no longer match the IOV requirement.
Definition at line 84 of file ConditionsIOVPool.cpp.
References DD4hep::Conditions::ConditionsPool::AGE_NONE, DD4hep::Conditions::ConditionsPool::age_value, elements, DD4hep::IOV::iov_intersection(), DD4hep::IOV::key(), DD4hep::IOV::key_contains_range(), and DD4hep::Conditions::ConditionsPool::select_used().
selectRange()
void ConditionsIOVPool::selectRange (Condition::key_type key, const Condition::iov_type & req_validity, RangeConditions & result)
Retrieve a condition set given the key according to their validity.
Definition at line 48 of file ConditionsIOVPool.cpp.
References elements, DD4hep::IOV::key(), DD4hep::IOV::key_is_contained(), DD4hep::IOV::key_overlaps_higher_end(), and DD4hep::IOV::key_overlaps_lower_end().
Referenced by DD4hep::Conditions::ConditionsManagerObject::select_range().
Member Data Documentation
elements
Elements DD4hep::Conditions::ConditionsIOVPool::elements
Container of IOV dependent conditions pools.
Definition at line 47 of file ConditionsIOVPool.h.
Referenced by clean(), DD4hep::Conditions::Operators::collectAllConditions(), DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), DD4hep::Conditions::ConditionsManagerObject::registerIOV(), DD4hep::Conditions::ConditionsTextRepository::save(), DD4hep::Conditions::ConditionsRepository::save(), select(), and selectRange().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsIOVPool.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsIOVPool.cpp