DD4hep: DD4hep::Geometry::OverlayedField Class Reference
DD4hep::Geometry::OverlayedField Class Reference
DD4hep::Geometry components, classes and objects
Class describing a field overlay with several sources.
#include <Fields.h>
Classes
class Object
Internal data class shared by all handles.
Public Types
enum FieldType { ELECTRIC = 0x1, MAGNETIC = 0x2 }
typedef std::map< std::string, std::string > PropertyValues
typedef std::map< std::string, PropertyValues > Properties
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
OverlayedField ()=default
Default constructor.
template<typename Q >
OverlayedField (const Handle< Q > &e)
Constructor to be used when reading the already parsed DOM tree.
OverlayedField (const std::string &name)
Object constructor.
int type () const
Access the field type.
bool changesEnergy () const
Does the field change the energy of charged particles?
void add (CartesianField field)
Add a new field component.
void combinedElectric (const Position &pos, double *field) const
Returns the 3 electric field components (x, y, z) if many components are present.
void combinedElectric (const double *pos, double *field) const
Returns the 3 electric field components (x, y, z) if many components are present.
void combinedMagnetic (const Position &pos, double *field) const
Returns the 3 magnetic field components (x, y, z) if many components are present.
void combinedMagnetic (const double *pos, double *field) const
Returns the 3 magnetic field components (x, y, z) if many components are present.
void electricField (const Position &pos, Direction &field) const
Returns the 3 electric field components (x, y, z).
void electricField (const Position &pos, double *field) const
Returns the 3 electric field components (x, y, z).
void electricField (const double *pos, double *field) const
Returns the 3 electric field components (x, y, z).
void magneticField (const Position &pos, Direction &field) const
Returns the 3 magnetic field components (x, y, z).
void magneticField (const Position &pos, double *field) const
Returns the 3 magnetic field components (x, y, z).
void magneticField (const double *pos, double *field) const
Returns the 3 magnetic field components (x, y, z).
void electromagneticField (const Position &pos, double *val) const
Returns the 3 electric (val[0]-val[2]) and magnetic field components (val[3]-val[5]).
void electromagneticField (const double *pos, double *val) const
Returns the 3 electric (val[0]-val[2]) and magnetic field components (val[3]-val[5]).
Properties & properties () const
Access to properties container.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Class describing a field overlay with several sources.
Generic structure describing any field type (electric or magnetic) with field components in Cartesian coordinates.
The actual behaviour is solely implemented in the underlying object classes. The overlay field is the sum of several magnetic of electric field components.
The resulting field vectors are computed by the vector addition of the individual components.
Author
M.Frank
Version
1.0
Definition at line 130 of file Fields.h.
Member Typedef Documentation
Properties
typedef std::map<std::string, PropertyValues> DD4hep::Geometry::OverlayedField::Properties
Definition at line 136 of file Fields.h.
PropertyValues
typedef std::map<std::string, std::string> DD4hep::Geometry::OverlayedField::PropertyValues
Definition at line 135 of file Fields.h.
Member Enumeration Documentation
FieldType
enum DD4hep::Geometry::OverlayedField::FieldType
Enumerator
ELECTRIC
MAGNETIC
Definition at line 132 of file Fields.h.
Constructor & Destructor Documentation
OverlayedField() [1/3]
DD4hep::Geometry::OverlayedField::OverlayedField () default
Default constructor.
OverlayedField() [2/3]
template<typename Q > DD4hep::Geometry::OverlayedField::OverlayedField (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed DOM tree.
Definition at line 163 of file Fields.h.
References DD4hep::NamedObject::name.
OverlayedField() [3/3]
OverlayedField::OverlayedField (const std::string & name)
Object constructor.
Definition at line 88 of file Fields.cpp.
References DD4hep::Handle< T >::assign().
Member Function Documentation
add()
void OverlayedField::add (CartesianField field)
Add a new field component.
Definition at line 105 of file Fields.cpp.
References DD4hep::Geometry::CartesianField::ELECTRIC, DD4hep::Geometry::OverlayedField::Object::electric, DD4hep::Geometry::OverlayedField::Object::electric_components, DD4hep::Geometry::CartesianField::fieldType(), DD4hep::Handle< T >::isValid(), DD4hep::Geometry::CartesianField::MAGNETIC, DD4hep::Geometry::OverlayedField::Object::magnetic, DD4hep::Geometry::OverlayedField::Object::magnetic_components, and DD4hep::Geometry::OverlayedField::Object::type.
Referenced by DD4hep::Geometry::LCDDImp::addField().
changesEnergy()
bool OverlayedField::changesEnergy () const
Does the field change the energy of charged particles?
Definition at line 99 of file Fields.cpp.
References DD4hep::Geometry::CartesianField::ELECTRIC, and type().
Referenced by DD4hep::Simulation::Geant4Field::DoesFieldChangeEnergy(), and DD4hep::Simulation::Geant4FieldTrackingSetup::execute().
combinedElectric() [1/2]
void DD4hep::Geometry::OverlayedField::combinedElectric (const Position & pos, double * field) const inline
Returns the 3 electric field components (x, y, z) if many components are present.
Definition at line 180 of file Fields.h.
combinedElectric() [2/2]
void OverlayedField::combinedElectric (const double * pos, double * field) const
Returns the 3 electric field components (x, y, z) if many components are present.
Returns the 3 electric field components (x, y, z).
Definition at line 134 of file Fields.cpp.
combinedMagnetic() [1/2]
void DD4hep::Geometry::OverlayedField::combinedMagnetic (const Position & pos, double * field) const inline
Returns the 3 magnetic field components (x, y, z) if many components are present.
Definition at line 188 of file Fields.h.
combinedMagnetic() [2/2]
void OverlayedField::combinedMagnetic (const double * pos, double * field) const
Returns the 3 magnetic field components (x, y, z) if many components are present.
Returns the 3 magnetic field components (x, y, z).
Definition at line 140 of file Fields.cpp.
electricField() [1/3]
void DD4hep::Geometry::OverlayedField::electricField (const Position & pos, Direction & field) const inline
Returns the 3 electric field components (x, y, z).
Definition at line 196 of file Fields.h.
electricField() [2/3]
void DD4hep::Geometry::OverlayedField::electricField (const Position & pos, double * field) const inline
Returns the 3 electric field components (x, y, z).
Definition at line 201 of file Fields.h.
electricField() [3/3]
void DD4hep::Geometry::OverlayedField::electricField (const double * pos, double * field) const inline
Returns the 3 electric field components (x, y, z).
Definition at line 206 of file Fields.h.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::CartesianField::value().
electromagneticField() [1/2]
void DD4hep::Geometry::OverlayedField::electromagneticField (const Position & pos, double * val) const inline
Returns the 3 electric (val[0]-val[2]) and magnetic field components (val[3]-val[5]).
Definition at line 230 of file Fields.h.
References DD4hep::Geometry::CartesianField::Object::properties.
electromagneticField() [2/2]
void OverlayedField::electromagneticField (const double * pos, double * val) const
Returns the 3 electric (val[0]-val[2]) and magnetic field components (val[3]-val[5]).
Definition at line 146 of file Fields.cpp.
References DD4hep::Geometry::OverlayedField::Object::electric_components, and DD4hep::Geometry::OverlayedField::Object::magnetic_components.
magneticField() [1/3]
void DD4hep::Geometry::OverlayedField::magneticField (const Position & pos, Direction & field) const inline
Returns the 3 magnetic field components (x, y, z).
Definition at line 213 of file Fields.h.
Referenced by DD4hep::createGearMgr(), and DD4hep::Simulation::Geant4Field::GetFieldValue().
magneticField() [2/3]
void DD4hep::Geometry::OverlayedField::magneticField (const Position & pos, double * field) const inline
Returns the 3 magnetic field components (x, y, z).
Definition at line 218 of file Fields.h.
magneticField() [3/3]
void DD4hep::Geometry::OverlayedField::magneticField (const double * pos, double * field) const inline
Returns the 3 magnetic field components (x, y, z).
Definition at line 223 of file Fields.h.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::CartesianField::value().
properties()
OverlayedField::Properties & OverlayedField::properties () const
Access to properties container.
Definition at line 94 of file Fields.cpp.
type()
int DD4hep::Geometry::OverlayedField::type () const inline
Access the field type.
Definition at line 169 of file Fields.h.
References DD4hep::Geometry::CartesianField::changesEnergy(), and DD4hep::Geometry::CartesianField::Object::type.
Referenced by changesEnergy().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Fields.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Fields.cpp