DD4hep: DD4hep::LCIOEventHandler Class Reference
DD4hep::LCIOEventHandler Class Reference
#include <DDEve/LCIOEventHandler.h>
Public Types
typedef std::map< std::string, lcio::LCCollection * > Branches
typedef const void *(* HitAccessor_t) (const lcio::LCObject *, DDEveHit *)
Public Types inherited from DD4hep::EventHandler
enum CollectionType {
NO_COLLECTION =1<<0, PARTICLE_COLLECTION =1<<1, TRACK_COLLECTION =1<<2, CALO_HIT_COLLECTION =1<<3,
TRACKER_HIT_COLLECTION =1<<4, HIT_COLLECTION =CALO_HIT_COLLECTION|TRACKER_HIT_COLLECTION
}
typedef std::pair< const char *, size_t > Collection
Collection definition: name, size.
typedef std::map< std::string, std::vector< Collection > > TypedEventCollections
Types collection: collections are grouped by type (class name)
Public Member Functions
LCIOEventHandler ()
Standard constructor.
virtual ~LCIOEventHandler ()
Default destructor.
virtual const TypedEventCollections & data () const
Access the map of simulation data collections.
std::string datasourceName () const
Access the data source name.
virtual long numEvents () const
Access the number of events on the current input data source (-1 if no data source connected)
virtual CollectionType collectionType (const std::string &collection) const
Access to the collection type by name.
virtual size_t collectionLoop (const std::string &collection, DDEveHitActor &actor)
Call functor on hit collection.
virtual size_t collectionLoop (const std::string &collection, DDEveParticleActor &actor)
Loop over collection and extract particle data.
virtual bool Open (const std::string &type, const std::string &file_name)
Open new data file.
virtual bool NextEvent ()
User overloadable function: Load the next event.
virtual bool PreviousEvent ()
User overloadable function: Load the previous event.
virtual bool GotoEvent (long event_number)
Goto a specified event in the file.
Public Member Functions inherited from DD4hep::EventHandler
EventHandler ()
Standard constructor.
virtual ~EventHandler ()
Default destructor.
virtual bool hasEvent () const
Check if an event is present in memory.
virtual bool hasFile () const
Check if a data file is connected to the handler.
ClassDef (EventHandler, 0)
Protected Attributes
lcio::LCReader * m_lcReader
Reference to data file reader.
lcio::LCEvent * m_event
std::string m_fileName
Branches m_branches
Branch map.
TypedEventCollections m_data
Data collection map.
Protected Attributes inherited from DD4hep::EventHandler
bool m_hasFile
Flag to indicate that a file is opened.
bool m_hasEvent
Flag to indicate that an event is loaded.
Detailed Description
Author
M.Frank
Version
1.0
Definition at line 38 of file LCIOEventHandler.h.
Member Typedef Documentation
Branches
typedef std::map<std::string,lcio::LCCollection*> DD4hep::LCIOEventHandler::Branches
Definition at line 40 of file LCIOEventHandler.h.
HitAccessor_t
typedef const void*(* DD4hep::LCIOEventHandler::HitAccessor_t) (const lcio::LCObject *, DDEveHit *)
Definition at line 41 of file LCIOEventHandler.h.
Constructor & Destructor Documentation
LCIOEventHandler()
LCIOEventHandler::LCIOEventHandler ()
Standard constructor.
Definition at line 77 of file LCIOEventHandler.cpp.
~LCIOEventHandler()
LCIOEventHandler::~LCIOEventHandler () virtual
Default destructor.
Definition at line 82 of file LCIOEventHandler.cpp.
Member Function Documentation
collectionLoop() [1/2]
size_t LCIOEventHandler::collectionLoop (const std::string & collection, DDEveHitActor & actor) virtual
Call functor on hit collection.
Implements DD4hep::EventHandler.
Definition at line 106 of file LCIOEventHandler.cpp.
References _convertHitFunc(), and DD4hep::DDEveHitActor::setSize().
Referenced by datasourceName().
collectionLoop() [2/2]
size_t LCIOEventHandler::collectionLoop (const std::string & collection, DDEveParticleActor & actor) virtual
Loop over collection and extract particle data.
Implements DD4hep::EventHandler.
Definition at line 127 of file LCIOEventHandler.cpp.
References _convertParticleFunc(), and DD4hep::DDEveParticleActor::setSize().
collectionType()
EventHandler::CollectionType LCIOEventHandler::collectionType (const std::string & collection) const virtual
Access to the collection type by name.
Implements DD4hep::EventHandler.
Definition at line 95 of file LCIOEventHandler.cpp.
Referenced by datasourceName().
data()
virtual const TypedEventCollections& DD4hep::LCIOEventHandler::data () const inline virtual
Access the map of simulation data collections.
Implements DD4hep::EventHandler.
Definition at line 58 of file LCIOEventHandler.h.
References m_data.
datasourceName()
std::string DD4hep::LCIOEventHandler::datasourceName () const inline virtual
Access the data source name.
Implements DD4hep::EventHandler.
Definition at line 60 of file LCIOEventHandler.h.
References collectionLoop(), collectionType(), GotoEvent(), DD4hep::EventHandler::hasFile(), NextEvent(), numEvents(), Open(), and PreviousEvent().
GotoEvent()
bool LCIOEventHandler::GotoEvent (long event_number) virtual
Goto a specified event in the file.
Implements DD4hep::EventHandler.
Definition at line 190 of file LCIOEventHandler.cpp.
Referenced by datasourceName().
NextEvent()
bool LCIOEventHandler::NextEvent () virtual
User overloadable function: Load the next event.
Load the next event.
Implements DD4hep::EventHandler.
Definition at line 160 of file LCIOEventHandler.cpp.
Referenced by datasourceName().
numEvents()
long LCIOEventHandler::numEvents () const virtual
Access the number of events on the current input data source (-1 if no data source connected)
Implements DD4hep::EventHandler.
Definition at line 87 of file LCIOEventHandler.cpp.
Referenced by datasourceName().
Open()
bool LCIOEventHandler::Open (const std::string & type, const std::string & file_name) virtual
Open new data file.
Implements DD4hep::EventHandler.
Definition at line 148 of file LCIOEventHandler.cpp.
Referenced by datasourceName().
PreviousEvent()
bool LCIOEventHandler::PreviousEvent () virtual
User overloadable function: Load the previous event.
Load the previous event.
Implements DD4hep::EventHandler.
Definition at line 184 of file LCIOEventHandler.cpp.
Referenced by datasourceName().
Member Data Documentation
m_branches
Branches DD4hep::LCIOEventHandler::m_branches protected
Branch map.
Definition at line 48 of file LCIOEventHandler.h.
m_data
TypedEventCollections DD4hep::LCIOEventHandler::m_data protected
Data collection map.
Definition at line 50 of file LCIOEventHandler.h.
Referenced by data().
m_event
lcio::LCEvent* DD4hep::LCIOEventHandler::m_event protected
Definition at line 45 of file LCIOEventHandler.h.
m_fileName
std::string DD4hep::LCIOEventHandler::m_fileName protected
Definition at line 46 of file LCIOEventHandler.h.
m_lcReader
lcio::LCReader* DD4hep::LCIOEventHandler::m_lcReader protected
Reference to data file reader.
Definition at line 44 of file LCIOEventHandler.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/lcio/LCIOEventHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/lcio/LCIOEventHandler.cpp