DD4hep: DD4hep::XML::Handle_t Class Reference
DD4hep::XML::Handle_t Class Reference
DD4hep::XML classes and objects
Class to easily access the properties of single XmlElements.
#include <XMLElements.h>
Public Types
typedef XmlElement * Elt_t
Public Member Functions
Handle_t (Elt_t e=0)
Initializing constructor.
Elt_t operator-> () const
Direct access to the XmlElement using the operator->
operator Elt_t () const
Direct access to the XmlElement by dereferencing.
Elt_t ptr () const
Direct access to the XmlElement by function.
Handle_t clone (XmlDocument *new_doc) const
Clone the DOMelement - with the option of a deep copy.
const XmlChar * rawTag () const
Unicode text access to the element's tag. Tis must be wrong ....
const XmlChar * rawText () const
Unicode text access to the element's text.
const XmlChar * rawValue () const
Unicode text access to the element's value.
std::string tag () const
Text access to the element's tag.
std::string text () const
Text access to the element's text.
std::string value () const
Text access to the element's value.
void setValue (const XmlChar *text) const
Set the element's value.
void setValue (const std::string &text) const
Set the element's value.
void setText (const XmlChar *text) const
Set the element's text.
void setText (const std::string &text) const
Set the element's text.
const XmlChar * attr_name (const Attribute attr) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute attr) const
Access attribute value by the attribute (throws exception if not present)
const XmlChar * attr_value (const XmlChar *attr) const
Access attribute value by the attribute's unicode name (throws exception if not present)
const XmlChar * attr_value_nothrow (const XmlChar *attr) const
Access attribute value by the attribute's unicode name (no exception thrown if not present)
Attribute attr_ptr (const XmlChar *attr) const
Access attribute pointer by the attribute's unicode name (throws exception if not present)
Attribute attr_nothrow (const XmlChar *tag) const
Access attribute pointer by the attribute's unicode name (no exception thrown if not present)
bool hasAttr (const XmlChar *t) const
Check for the existence of a named attribute.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
template<class T >
T attr (const Attribute a) const
Access typed attribute value by the XmlAttr.
void removeAttrs () const
Remove all attributes of this element.
void setAttrs (Handle_t e) const
Set attributes as in argument handle.
template<class T >
T attr (const XmlChar *name) const
Access typed attribute value by it's unicode name.
Attribute setAttr (const XmlChar *t, const XmlChar *v) const
Generic attribute setter with unicode value.
Attribute setAttr (const XmlChar *t, const Attribute v) const
Generic attribute setter with XmlAttr value.
Attribute setAttr (const XmlChar *t, int val) const
Generic attribute setter with integer value.
Attribute setAttr (const XmlChar *t, bool val) const
Generic attribute setter with boolen value.
Attribute setAttr (const XmlChar *t, float val) const
Generic attribute setter with floating point value.
Attribute setAttr (const XmlChar *t, double val) const
Generic attribute setter with double precision floating point value.
Attribute setAttr (const XmlChar *t, const std::string &val) const
Generic attribute setter with string value.
bool hasAttr (const char *t) const
Check for the existence of a named attribute.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
Attribute setAttr (const XmlChar *t, const char *v) const
Generic attribute setter with text value.
Handle_t setRef (const XmlChar *tag, const XmlChar *ref)
Add reference child as a new child node. The obj must have the "name" attribute!
Handle_t setRef (const XmlChar *tag, const std::string &ref)
Add reference child as a new child node. The obj must have the "name" attribute!
bool hasChild (const XmlChar *tag) const
Check the existence of a child with a given tag name.
Handle_t child (const XmlChar *tag, bool throw_exception=true) const
Access a single child by it's tag name (unicode)
NodeList children (const XmlChar *tag) const
Access a group of children identified by the same tag name.
size_t numChildren (const XmlChar *tag, bool throw_exception) const
Access the number of children of this DOM element with a given tag name.
Handle_t remove (Handle_t e) const
Remove a single child node identified by it's handle from the tree of the element.
void removeChildren (const XmlChar *tag) const
Remove children with a given tag name from the DOM node.
void append (Handle_t e) const
Append a DOM element to the current node.
Handle_t parent () const
Access the element's parent element.
unsigned int checksum (unsigned int param, unsigned int(fcn)(unsigned int param, const XmlChar *, size_t)=0) const
Checksum (sub-)tree of a xml document/tree. Default will pick up the adler32 checksum.
template<>
INLINE Attribute attr (const XmlChar *tag_value) const
template<>
INLINE cpXmlChar attr (const XmlChar *tag_value) const
template<>
INLINE bool attr (const XmlChar *tag_value) const
template<>
INLINE int attr (const XmlChar *tag_value) const
template<>
INLINE long attr (const XmlChar *tag_value) const
template<>
INLINE float attr (const XmlChar *tag_value) const
template<>
INLINE double attr (const XmlChar *tag_value) const
Public Attributes
Elt_t m_node
The pointer to the XmlElement.
Detailed Description
Class to easily access the properties of single XmlElements.
Note: The assignmant operator as well as the copy constructor do not have to be implemented, they are aut-generated by the compiler!
Author
M.Frank
Version
1.0
Definition at line 361 of file XMLElements.h.
Member Typedef Documentation
Elt_t
typedef XmlElement* DD4hep::XML::Handle_t::Elt_t
Definition at line 364 of file XMLElements.h.
Constructor & Destructor Documentation
Handle_t()
DD4hep::XML::Handle_t::Handle_t (Elt_t e = 0) inline
Initializing constructor.
Definition at line 370 of file XMLElements.h.
Referenced by DD4hep::XML::Collection_t::size().
Member Function Documentation
append()
void Handle_t::append (Handle_t e) const
Append a DOM element to the current node.
Definition at line 719 of file XMLElements.cpp.
References _N, DD4hep::XML::NodeList::m_node, and ptr().
Referenced by DD4hep::XML::Element::addChild(), and DD4hep::XML::Element::append().
attr() [1/10]
template<class T > T DD4hep::XML::Handle_t::attr (const Attribute a) const inline
Access typed attribute value by the XmlAttr.
Definition at line 435 of file XMLElements.h.
References e.
Referenced by DD4hep::Simulation::_createAction(), DD4hep::Simulation::_setAttributes(), DD4hep::Simulation::_setProperties(), DD4hep::XML::DetElement::attr(), DD4hep::XML::Element::attr(), extract(), DD4hep::XML::Element::getRef(), DD4hep::XML::Dimension::limitsStr(), DD4hep::XML::DetElement::materialStr(), DD4hep::XML::Dimension::moduleStr(), DD4hep::XML::Dimension::nameStr(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::XML::Dimension::readoutStr(), DD4hep::XML::Dimension::refStr(), DD4hep::XML::Dimension::regionStr(), DD4hep::XML::Dimension::typeStr(), DD4hep::XML::Dimension::valueStr(), DD4hep::XML::Dimension::visStr(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
attr() [2/10]
template<class T > T DD4hep::XML::Handle_t::attr (const XmlChar * name) const
Access typed attribute value by it's unicode name.
attr() [3/10]
template<class T > T DD4hep::XML::Handle_t::attr (const char * name) const inline
Access typed attribute value by it's name.
Definition at line 465 of file XMLElements.h.
References e.
attr() [4/10]
template<> INLINE Attribute DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 502 of file XMLElements.h.
attr() [5/10]
template<> INLINE cpXmlChar DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 506 of file XMLElements.h.
attr() [6/10]
template<> INLINE bool DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 510 of file XMLElements.h.
References DD4hep::XML::_toBool().
attr() [7/10]
template<> INLINE int DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 514 of file XMLElements.h.
References DD4hep::XML::_toInt().
attr() [8/10]
template<> INLINE long DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 518 of file XMLElements.h.
References DD4hep::XML::_toLong().
attr() [9/10]
template<> INLINE float DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 522 of file XMLElements.h.
References DD4hep::XML::_toFloat().
attr() [10/10]
template<> INLINE double DD4hep::XML::Handle_t::attr (const XmlChar * tag_value) const
Definition at line 526 of file XMLElements.h.
References DD4hep::XML::_toDouble().
attr_name()
const XmlChar * Handle_t::attr_name (const Attribute attr) const
Access attribute name (throws exception if not present)
Definition at line 843 of file XMLElements.cpp.
References Xml::a.
Referenced by DD4hep::Simulation::_setAttributes(), and DD4hep::XML::Element::attr().
attr_nothrow()
Attribute Handle_t::attr_nothrow (const XmlChar * tag) const
Access attribute pointer by the attribute's unicode name (no exception thrown if not present)
Definition at line 660 of file XMLElements.cpp.
References DD4hep::XML::NodeList::m_node.
attr_ptr()
Attribute Handle_t::attr_ptr (const XmlChar * attr) const
Access attribute pointer by the attribute's unicode name (throws exception if not present)
Definition at line 830 of file XMLElements.cpp.
References DD4hep::XML::_toString(), and DD4hep::XML::NodeList::m_node.
attr_value() [1/2]
const XmlChar * Handle_t::attr_value (const Attribute attr) const
Access attribute value by the attribute (throws exception if not present)
Definition at line 856 of file XMLElements.cpp.
Referenced by DD4hep::XML::Element::attr_value().
attr_value() [2/2]
const XmlChar * Handle_t::attr_value (const XmlChar * attr) const
Access attribute value by the attribute's unicode name (throws exception if not present)
Definition at line 851 of file XMLElements.cpp.
attr_value_nothrow()
const XmlChar * Handle_t::attr_value_nothrow (const XmlChar * attr) const
Access attribute value by the attribute's unicode name (no exception thrown if not present)
Definition at line 861 of file XMLElements.cpp.
attributes()
vector< Attribute > Handle_t::attributes () const
Retrieve a collection of all attributes of this DOM element.
Definition at line 670 of file XMLElements.cpp.
References _E, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::Simulation::_setAttributes(), and DD4hep::XML::Element::attributes().
checksum()
unsigned int Handle_t::checksum (unsigned int param, unsigned intfcn)(unsigned int param, const XmlChar *, size_t = 0) const
Checksum (sub-)tree of a xml document/tree. Default will pick up the adler32 checksum.
Definition at line 982 of file XMLElements.cpp.
References adler32(), TiXmlNode::COMMENT, TiXmlNode::DECLARATION, TiXmlNode::DOCUMENT, e, TiXmlNode::ELEMENT, TiXmlElement::FirstAttribute(), TiXmlNode::FirstChild(), m, DD4hep::XML::NodeList::m_node, Xml::n, TiXmlAttribute::Name(), TiXmlAttribute::Next(), TiXmlNode::NextSibling(), TiXmlNode::TEXT, TiXmlNode::ToElement(), TiXmlNode::ToText(), TiXmlNode::Type(), TiXmlNode::UNKNOWN, TiXmlNode::Value(), and TiXmlAttribute::Value().
child()
Handle_t Handle_t::child (const XmlChar * tag, bool throw_exception = true) const
Access a single child by it's tag name (unicode)
Remove a single child node identified by it's handle from the tree of the element.
Definition at line 702 of file XMLElements.cpp.
References DD4hep::XML::_toString(), e, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Element::child(), DD4hep::XML::DetElement::materialStr(), and DD4hep::XML::Element::setChild().
children()
NodeList Handle_t::children (const XmlChar * tag) const
Access a group of children identified by the same tag name.
Definition at line 714 of file XMLElements.cpp.
References DD4hep::XML::NodeList::m_node, and DD4hep::XML::NodeList::NodeList().
clone()
Handle_t Handle_t::clone (XmlDocument * new_doc) const
Clone the DOMelement - with the option of a deep copy.
Definition at line 638 of file XMLElements.cpp.
References _D, _E, _N, _XE, e, ELEMENT_NODE_TYPE, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Document::clone(), and DD4hep::XML::Element::clone().
hasAttr() [1/2]
bool Handle_t::hasAttr (const XmlChar * t) const
Check for the existence of a named attribute.
Definition at line 665 of file XMLElements.cpp.
References _E, and DD4hep::XML::NodeList::m_node.
Referenced by extract(), DD4hep::XML::Element::hasAttr(), DD4hep::XML::Dimension::limitsStr(), DD4hep::XML::DetElement::materialStr(), DD4hep::XML::Dimension::moduleStr(), DD4hep::XML::Dimension::readoutStr(), DD4hep::XML::Dimension::regionStr(), and DD4hep::XML::Dimension::visStr().
hasAttr() [2/2]
bool DD4hep::XML::Handle_t::hasAttr (const char * t) const inline
Check for the existence of a named attribute.
Definition at line 461 of file XMLElements.h.
hasChild()
bool Handle_t::hasChild (const XmlChar * tag) const
Check the existence of a child with a given tag name.
Definition at line 756 of file XMLElements.cpp.
References DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Element::hasChild().
numChildren()
size_t Handle_t::numChildren (const XmlChar * tag, bool throw_exception) const
Access the number of children of this DOM element with a given tag name.
Definition at line 687 of file XMLElements.cpp.
References DD4hep::XML::_toString(), INVALID_NODE, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Element::numChildren().
operator Elt_t()
DD4hep::XML::Handle_t::operator Elt_t () const inline
Direct access to the XmlElement by dereferencing.
Definition at line 378 of file XMLElements.h.
operator->()
Elt_t DD4hep::XML::Handle_t::operator-> () const inline
Direct access to the XmlElement using the operator->
Definition at line 374 of file XMLElements.h.
parent()
Handle_t Handle_t::parent () const
Access the element's parent element.
Definition at line 655 of file XMLElements.cpp.
References _N, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Collection_t::operator++(), DD4hep::XML::Collection_t::operator--(), DD4hep::XML::Element::parent(), and DD4hep::XML::Element::parentElement().
ptr()
Elt_t DD4hep::XML::Handle_t::ptr () const inline
Direct access to the XmlElement by function.
Definition at line 382 of file XMLElements.h.
Referenced by DD4hep::XML::_toString(), append(), DD4hep::XML::Document::clone(), DD4hep::XML::dump_tree(), DD4hep::XML::Element::operator bool(), DD4hep::XML::Element::operator!(), DD4hep::XML::DocumentHandler::output(), DD4hep::XML::Element::parentElement(), remove(), and DD4hep::XML::DocumentHandler::system_path().
rawTag()
const XmlChar * Handle_t::rawTag () const
Unicode text access to the element's tag. Tis must be wrong ....
Definition at line 623 of file XMLElements.cpp.
References _E, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Element::tagName().
rawText()
const XmlChar * Handle_t::rawText () const
Unicode text access to the element's text.
Definition at line 628 of file XMLElements.cpp.
References _E, and DD4hep::XML::NodeList::m_node.
rawValue()
const XmlChar * Handle_t::rawValue () const
Unicode text access to the element's value.
Definition at line 633 of file XMLElements.cpp.
References _N, and DD4hep::XML::NodeList::m_node.
remove()
Handle_t Handle_t::remove (Handle_t e) const
Remove a single child node identified by it's handle from the tree of the element.
Definition at line 724 of file XMLElements.cpp.
References _N, e, DD4hep::XML::NodeList::m_node, ptr(), and tag().
Referenced by DD4hep::XML::Element::remove().
removeAttrs()
void Handle_t::removeAttrs () const
Remove all attributes of this element.
Definition at line 793 of file XMLElements.cpp.
References _E, Xml::e, e, TiXmlElement::FirstAttribute(), DD4hep::XML::NodeList::m_node, TiXmlAttribute::Next(), TiXmlElement::SetAttribute(), and setAttrs().
Referenced by DD4hep::XML::Element::removeAttrs().
removeChildren()
void Handle_t::removeChildren (const XmlChar * tag) const
Remove children with a given tag name from the DOM node.
Definition at line 744 of file XMLElements.cpp.
References _E, e, and DD4hep::XML::NodeList::m_node.
setAttr() [1/8]
Attribute Handle_t::setAttr (const XmlChar * t, const XmlChar * v) const
Generic attribute setter with unicode value.
Definition at line 911 of file XMLElements.cpp.
References _E, TiXmlElement::AttributeNode(), Xml::e, e, DD4hep::XML::NodeList::m_node, and TiXmlElement::SetAttribute().
Referenced by DD4hep::XML::Element::setAttr(), and DD4hep::XML::Element::setRef().
setAttr() [2/8]
Attribute Handle_t::setAttr (const XmlChar * t, const Attribute v) const
Generic attribute setter with XmlAttr value.
Definition at line 906 of file XMLElements.cpp.
setAttr() [3/8]
Attribute Handle_t::setAttr (const XmlChar * t, int val) const
Generic attribute setter with integer value.
Definition at line 867 of file XMLElements.cpp.
setAttr() [4/8]
Attribute Handle_t::setAttr (const XmlChar * t, bool val) const
Generic attribute setter with boolen value.
Definition at line 874 of file XMLElements.cpp.
setAttr() [5/8]
Attribute Handle_t::setAttr (const XmlChar * t, float val) const
Generic attribute setter with floating point value.
Definition at line 881 of file XMLElements.cpp.
setAttr() [6/8]
Attribute Handle_t::setAttr (const XmlChar * t, double val) const
Generic attribute setter with double precision floating point value.
Definition at line 888 of file XMLElements.cpp.
setAttr() [7/8]
Attribute Handle_t::setAttr (const XmlChar * t, const std::string & val) const
Generic attribute setter with string value.
Definition at line 895 of file XMLElements.cpp.
setAttr() [8/8]
Attribute Handle_t::setAttr (const XmlChar * t, const char * v) const
Generic attribute setter with text value.
Definition at line 900 of file XMLElements.cpp.
setAttrs()
void Handle_t::setAttrs (Handle_t e) const
Set attributes as in argument handle.
Definition at line 815 of file XMLElements.cpp.
References _E, e, and DD4hep::XML::NodeList::m_node.
Referenced by removeAttrs(), and DD4hep::XML::Element::setAttrs().
setRef() [1/2]
Handle_t Handle_t::setRef (const XmlChar * tag, const XmlChar * ref)
Add reference child as a new child node. The obj must have the "name" attribute!
Definition at line 929 of file XMLElements.cpp.
References DD4hep::XML::Element::append(), DD4hep::XML::Element::document(), and DD4hep::XML::Element::setAttr().
setRef() [2/2]
Handle_t Handle_t::setRef (const XmlChar * tag, const std::string & ref)
Add reference child as a new child node. The obj must have the "name" attribute!
Definition at line 938 of file XMLElements.cpp.
setText() [1/2]
void Handle_t::setText (const XmlChar * text) const
Set the element's text.
Definition at line 775 of file XMLElements.cpp.
References _N, and DD4hep::XML::NodeList::m_node.
setText() [2/2]
void Handle_t::setText (const std::string & text) const
Set the element's text.
Definition at line 784 of file XMLElements.cpp.
References _N, and DD4hep::XML::NodeList::m_node.
setValue() [1/2]
void Handle_t::setValue (const XmlChar * text) const
Set the element's value.
Definition at line 761 of file XMLElements.cpp.
References _N, and DD4hep::XML::NodeList::m_node.
Referenced by DD4hep::XML::Element::setValue().
setValue() [2/2]
void Handle_t::setValue (const std::string & text) const
Set the element's value.
Definition at line 766 of file XMLElements.cpp.
References _N, and DD4hep::XML::NodeList::m_node.
tag()
std::string DD4hep::XML::Handle_t::tag () const inline
Text access to the element's tag.
Definition at line 395 of file XMLElements.h.
References DD4hep::XML::_toString().
Referenced by DD4hep::XML::RefElement::name(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::LCDDLoad::processXMLElement(), DD4hep::XML::RefElement::refName(), remove(), DD4hep::XML::Element::tag(), and DD4hep::XML::Collection_t::throw_loop_exception().
text()
std::string DD4hep::XML::Handle_t::text () const inline
Text access to the element's text.
Definition at line 399 of file XMLElements.h.
References DD4hep::XML::_toString().
value()
std::string DD4hep::XML::Handle_t::value () const inline
Text access to the element's value.
Definition at line 403 of file XMLElements.h.
References DD4hep::XML::_toString().
Member Data Documentation
m_node
Elt_t DD4hep::XML::Handle_t::m_node mutable
The pointer to the XmlElement.
Definition at line 367 of file XMLElements.h.
Referenced by DD4hep::XML::Collection_t::Collection_t(), DD4hep::XML::Collection_t::operator++(), DD4hep::XML::Collection_t::operator--(), DD4hep::XML::Collection_t::reset(), and DD4hep::XML::Collection_t::throw_loop_exception().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp