DD4hep: DD4hep::PropertyValue< TYPE > Class Template Reference
DD4hep::PropertyValue< TYPE > Class Template Reference
DD4hep::Simulation components, classes and objects
Concrete template instantiation of a combined property value pair.
#include <ComponentProperties.h>
Public Member Functions
PropertyValue ()
PropertyValue & operator= (const TYPE &val)
Assignment operator.
bool operator== (const TYPE &val) const
const PropertyGrammar & grammar () const
Access grammar object.
std::string str () const
Conversion to string value.
template<typename T >
T value () const
Retrieve value with data conversion.
template<typename T >
void value (TYPE &val) const
Retrieve value from stack with data conversion (large values e.g. vectors etc.)
template<typename T >
void set (const T &val)
Set value of this property with data conversion.
Public Attributes
TYPE data
Additional Inherited Members
Private Member Functions inherited from DD4hep::Property
Property ()
Default constructor.
Property (const Property &p)
Copy constructor.
template<typename TYPE >
Property (TYPE &val)
User constructor.
std::string type () const
Property type name.
void * ptr () const
Access void data pointer.
const PropertyGrammar & grammar () const
Access grammar object.
std::string str () const
Conversion to string value.
Property & str (const std::string &input)
Conversion from string value.
Property & operator= (const Property &p)
Assignment operator.
Property & operator= (const char *val)
Assignment operator / set new balue.
template<typename TYPE >
Property & operator= (const TYPE &val)
Assignment operator / set new balue.
template<typename TYPE >
TYPE value () const
Retrieve value.
template<typename TYPE >
void value (TYPE &value) const
Retrieve value from stack (large values e.g. vectors etc.)
template<typename TYPE >
void set (const TYPE &value)
Set value of this property.
template<typename TYPE >
void make (TYPE &value)
Setup property.
Static Private Member Functions inherited from DD4hep::Property
static std::string type (const Property &proptery)
Property type name.
static std::string type (const std::type_info &proptery)
Property type name.
Private Attributes inherited from DD4hep::Property
void * m_par
Pointer to the data location.
const PropertyGrammar * m_hdl
Detailed Description
template<class TYPE>
class DD4hep::PropertyValue< TYPE >
Concrete template instantiation of a combined property value pair.
Author
M.Frank
Version
1.0
Definition at line 142 of file ComponentProperties.h.
Constructor & Destructor Documentation
PropertyValue()
template<class TYPE > DD4hep::PropertyValue< TYPE >::PropertyValue () inline
Definition at line 145 of file ComponentProperties.h.
Member Function Documentation
grammar()
template<class TYPE > const PropertyGrammar& DD4hep::PropertyValue< TYPE >::grammar () const inline
Access grammar object.
Definition at line 158 of file ComponentProperties.h.
References DD4hep::Property::grammar().
operator=()
template<class TYPE > PropertyValue& DD4hep::PropertyValue< TYPE >::operator= (const TYPE & val) inline
Assignment operator.
Definition at line 149 of file ComponentProperties.h.
operator==()
template<class TYPE > bool DD4hep::PropertyValue< TYPE >::operator== (const TYPE & val) const inline
Definition at line 154 of file ComponentProperties.h.
set()
template<class TYPE > template<typename T > void DD4hep::PropertyValue< TYPE >::set (const T & val) inline
Set value of this property with data conversion.
Definition at line 174 of file ComponentProperties.h.
References DD4hep::Property::set().
str()
template<class TYPE > std::string DD4hep::PropertyValue< TYPE >::str () const inline
Conversion to string value.
Definition at line 162 of file ComponentProperties.h.
References DD4hep::Property::str().
value() [1/2]
template<class TYPE > template<typename T > T DD4hep::PropertyValue< TYPE >::value () const inline
Retrieve value with data conversion.
Definition at line 166 of file ComponentProperties.h.
value() [2/2]
template<class TYPE > template<typename T > void DD4hep::PropertyValue< TYPE >::value (TYPE & val) const inline
Retrieve value from stack with data conversion (large values e.g. vectors etc.)
Definition at line 170 of file ComponentProperties.h.
References DD4hep::Property::value().
Member Data Documentation
data
template<class TYPE > TYPE DD4hep::PropertyValue< TYPE >::data
Definition at line 144 of file ComponentProperties.h.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ComponentProperties.h