DD4hep: DD4hep::DDSegmentation::MultiSegmentation Class Reference
DD4hep::DDSegmentation::MultiSegmentation Class Reference
Wrapper to support multiple segmentations.
#include <MultiSegmentation.h>
Classes
struct Entry
Public Types
typedef std::vector< Entry > Segmentations
Public Member Functions
MultiSegmentation (const std::string &cellEncoding="")
Default constructor passing the encoding string.
MultiSegmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
virtual ~MultiSegmentation ()
Default destructor.
virtual void addSubsegmentation (long key_min, long key_max, Segmentation *entry)
Add subsegmentation.
const Segmentation & subsegmentation (const CellID &cellID) const
Access subsegmentation by cell identifier.
virtual Vector3D position (const CellID &cellID) const
determine the position based on the cell ID
virtual CellID cellID (const Vector3D &localPosition, const Vector3D &globalPosition, const VolumeID &volumeID) const
determine the cell ID based on the position
virtual std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
const std::string & discriminatorName () const
access the field name used to discriminate sub-segmentations
BitFieldValue * discriminator () const
Discriminating bitfield entry.
virtual void setDecoder (BitField64 *decoder)
Set the underlying decoder.
const Segmentations & subSegmentations () const
The underlying sub-segementations.
Public Member Functions inherited from DD4hep::DDSegmentation::Segmentation
virtual ~Segmentation ()
Destructor.
virtual VolumeID volumeID (const CellID &cellID) const
Determine the volume ID from the full cell ID by removing all local fields.
virtual void neighbours (const CellID &cellID, std::set< CellID > &neighbours) const
Calculates the neighbours of the given cell ID and adds them to the list of neighbours.
virtual std::string fieldDescription () const
Access the encoding string.
virtual const std::string & name () const
Access the segmentation name.
virtual void setName (const std::string &value)
Set the segmentation name.
virtual const std::string & type () const
Access the segmentation type.
virtual const std::string & description () const
Access the description of the segmentation.
virtual BitField64 * decoder () const
Access the underlying decoder.
virtual Parameter parameter (const std::string &parameterName) const
Access to parameter by name.
virtual Parameters parameters () const
Access to all parameters.
virtual void setParameters (const Parameters &parameters)
Set all parameters from an existing set of parameters.
Protected Attributes
Segmentations m_segmentations
Sub-segmentaion container.
std::string m_discriminatorId
the field name used to discriminate sub-segmentations
BitFieldValue * m_discriminator
Bitfield corresponding to dicriminator identifier.
int m_debug
Debug flags.
Protected Attributes inherited from DD4hep::DDSegmentation::Segmentation
std::string _name
The segmentation name.
std::string _type
The segmentation type.
std::string _description
The description of the segmentation.
std::map< std::string, Parameter > _parameters
The parameters for this segmentation.
std::map< std::string, StringParameter > _indexIdentifiers
The indices used for the encoding.
BitField64 * _decoder
The cell ID encoder and decoder.
bool _ownsDecoder
Keeps track of the decoder ownership.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
Segmentation (const std::string &cellEncoding="")
Default constructor used by derived classes passing the encoding string.
Segmentation (BitField64 *decoder)
Default constructor used by derived classes passing an existing decoder.
template<typename TYPE >
void registerParameter (const std::string &nam, const std::string &desc, TYPE &param, const TYPE &defaultVal, UnitType unitTyp=SegmentationParameter::NoUnit, bool isOpt=false)
Add a parameter to this segmentation. Used by derived classes to define their parameters.
void registerIdentifier (const std::string &nam, const std::string &desc, std::string &ident, const std::string &defaultVal)
Add a cell identifier to this segmentation. Used by derived classes to define their required identifiers.
Static Protected Member Functions inherited from DD4hep::DDSegmentation::Segmentation
static double binToPosition (CellID bin, double cellSize, double offset=0.)
Helper method to convert a bin number to a 1D position.
static int positionToBin (double position, double cellSize, double offset=0.)
Helper method to convert a 1D position to a cell ID.
static double binToPosition (CellID bin, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a bin number to a 1D position given a vector of binBoundaries.
static int positionToBin (double position, std::vector< double > const &cellBoundaries, double offset=0.)
Helper method to convert a 1D position to a cell ID given a vector of binBoundaries.
Detailed Description
Wrapper to support multiple segmentations.
Author
M.Frank
Version
1.0
Definition at line 30 of file MultiSegmentation.h.
Member Typedef Documentation
Segmentations
typedef std::vector<Entry> DD4hep::DDSegmentation::MultiSegmentation::Segmentations
Definition at line 37 of file MultiSegmentation.h.
Constructor & Destructor Documentation
MultiSegmentation() [1/2]
DD4hep::DDSegmentation::MultiSegmentation::MultiSegmentation (const std::string & cellEncoding = "")
Default constructor passing the encoding string.
default constructor using an encoding string
Definition at line 18 of file MultiSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, DD4hep::DDSegmentation::Segmentation::_type, and m_discriminatorId.
MultiSegmentation() [2/2]
DD4hep::DDSegmentation::MultiSegmentation::MultiSegmentation (BitField64 * decoder)
Default constructor used by derived classes passing an existing decoder.
Definition at line 29 of file MultiSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::_description, DD4hep::DDSegmentation::Segmentation::_type, and m_discriminatorId.
~MultiSegmentation()
DD4hep::DDSegmentation::MultiSegmentation::~MultiSegmentation () virtual
Default destructor.
destructor
Definition at line 40 of file MultiSegmentation.cpp.
References m_segmentations.
Member Function Documentation
addSubsegmentation()
void DD4hep::DDSegmentation::MultiSegmentation::addSubsegmentation (long key_min, long key_max, Segmentation * entry) virtual
Add subsegmentation.
Add subsegmentation. Call only valid for Multi-segmentations. Default implementation throws an exception.
Reimplemented from DD4hep::DDSegmentation::Segmentation.
Definition at line 47 of file MultiSegmentation.cpp.
References e, DD4hep::DDSegmentation::MultiSegmentation::Entry::key_max, DD4hep::DDSegmentation::MultiSegmentation::Entry::key_min, m_segmentations, and DD4hep::DDSegmentation::MultiSegmentation::Entry::segmentation.
cellDimensions()
vector< double > DD4hep::DDSegmentation::MultiSegmentation::cellDimensions (const CellID & cellID) const virtual
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Parameters
cellID cellID of the cell for which parameters are returned
Returns
vector<double> in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi
Reimplemented from DD4hep::DDSegmentation::Segmentation.
Definition at line 96 of file MultiSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::cellDimensions(), REGISTER_SEGMENTATION, and subsegmentation().
cellID()
CellID DD4hep::DDSegmentation::MultiSegmentation::cellID (const Vector3D & localPosition, const Vector3D & globalPosition, const VolumeID & volumeID) const virtual
determine the cell ID based on the position
Implements DD4hep::DDSegmentation::Segmentation.
Definition at line 92 of file MultiSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::cellID(), and subsegmentation().
discriminator()
BitFieldValue* DD4hep::DDSegmentation::MultiSegmentation::discriminator () const inline
Discriminating bitfield entry.
Definition at line 86 of file MultiSegmentation.h.
References DD4hep::DDSegmentation::Segmentation::decoder(), m_discriminator, and setDecoder().
discriminatorName()
const std::string& DD4hep::DDSegmentation::MultiSegmentation::discriminatorName () const inline
access the field name used to discriminate sub-segmentations
Definition at line 83 of file MultiSegmentation.h.
References m_discriminatorId.
position()
Vector3D DD4hep::DDSegmentation::MultiSegmentation::position (const CellID & cellID) const virtual
determine the position based on the cell ID
Implements DD4hep::DDSegmentation::Segmentation.
Definition at line 87 of file MultiSegmentation.cpp.
References DD4hep::DDSegmentation::Segmentation::position(), and subsegmentation().
setDecoder()
void DD4hep::DDSegmentation::MultiSegmentation::setDecoder (BitField64 * decoder) virtual
Set the underlying decoder.
Reimplemented from DD4hep::DDSegmentation::Segmentation.
Definition at line 56 of file MultiSegmentation.cpp.
References m_discriminator, m_discriminatorId, m_segmentations, and DD4hep::DDSegmentation::Segmentation::setDecoder().
Referenced by discriminator().
subsegmentation()
const Segmentation & DD4hep::DDSegmentation::MultiSegmentation::subsegmentation (const CellID & cellID) const
Access subsegmentation by cell identifier.
Definition at line 64 of file MultiSegmentation.cpp.
References e, DD4hep::DDSegmentation::MultiSegmentation::Entry::key_max, DD4hep::DDSegmentation::MultiSegmentation::Entry::key_min, m_debug, m_discriminator, m_segmentations, DD4hep::DDSegmentation::Segmentation::name(), DD4hep::DDSegmentation::Segmentation::parameters(), s, DD4hep::DDSegmentation::MultiSegmentation::Entry::segmentation, and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by cellDimensions(), cellID(), and position().
subSegmentations()
const Segmentations& DD4hep::DDSegmentation::MultiSegmentation::subSegmentations () const inline
The underlying sub-segementations.
Definition at line 92 of file MultiSegmentation.h.
References m_segmentations.
Member Data Documentation
m_debug
int DD4hep::DDSegmentation::MultiSegmentation::m_debug protected
Debug flags.
Definition at line 50 of file MultiSegmentation.h.
Referenced by subsegmentation().
m_discriminator
BitFieldValue* DD4hep::DDSegmentation::MultiSegmentation::m_discriminator protected
Bitfield corresponding to dicriminator identifier.
Definition at line 47 of file MultiSegmentation.h.
Referenced by discriminator(), setDecoder(), and subsegmentation().
m_discriminatorId
std::string DD4hep::DDSegmentation::MultiSegmentation::m_discriminatorId protected
the field name used to discriminate sub-segmentations
Definition at line 44 of file MultiSegmentation.h.
Referenced by discriminatorName(), MultiSegmentation(), and setDecoder().
m_segmentations
Segmentations DD4hep::DDSegmentation::MultiSegmentation::m_segmentations protected
Sub-segmentaion container.
Definition at line 41 of file MultiSegmentation.h.
Referenced by addSubsegmentation(), setDecoder(), subsegmentation(), subSegmentations(), and ~MultiSegmentation().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/MultiSegmentation.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/MultiSegmentation.cpp