DD4hep: DD4hep::ElementList Class Reference
DD4hep::ElementList Class Reference
Local implementation with overrides of the TEveElementList.
#include <ElementList.h>
Public Member Functions
ElementList ()
Default constructor.
ElementList (const std::string &name, const std::string &title="", bool doCol=false, bool doTrans=false)
Initializing constructor.
ElementList (const ElementList &l)
Copy constructor.
virtual ~ElementList ()
Default destructor.
virtual TEveElementList * CloneElement () const
Clone object: Overload from TEveElementList.
ClassDef (ElementList, 0)
Root implementation macro.
Detailed Description
Local implementation with overrides of the TEveElementList.
Definition at line 36 of file ElementList.h.
Constructor & Destructor Documentation
ElementList() [1/3]
DD4hep::ElementList::ElementList ()
Default constructor.
Referenced by CloneElement().
ElementList() [2/3]
ElementList::ElementList (const std::string & name, const std::string & title = "", bool doCol = false, bool doTrans = false)
Initializing constructor.
Definition at line 37 of file ElementList.cpp.
References DD4hep::InstanceCount::increment().
ElementList() [3/3]
ElementList::ElementList (const ElementList & l)
Copy constructor.
Definition at line 43 of file ElementList.cpp.
References DD4hep::InstanceCount::increment().
~ElementList()
ElementList::~ElementList () virtual
Default destructor.
Definition at line 49 of file ElementList.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
ClassDef()
DD4hep::ElementList::ClassDef (ElementList , 0)
Root implementation macro.
CloneElement()
TEveElementList * ElementList::CloneElement () const virtual
Clone object: Overload from TEveElementList.
Clone object.
Definition at line 54 of file ElementList.cpp.
References ElementList().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/ElementList.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/ElementList.cpp