DD4hep: DD4hep::Geometry::CartesianField Class Reference
DD4hep::Geometry::CartesianField Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing any field with 3D cartesian vectors for the field strength.
#include <Fields.h>
Classes
class Object
Internal data class shared by all handles of a given type.
Public Types
enum FieldType { UNKNOWN = 0, ELECTRIC = 0x1, MAGNETIC = 0x2 }
typedef std::map< std::string, std::string > PropertyValues
typedef std::map< std::string, PropertyValues > Properties
Public Types inherited from DD4hep::Handle< NamedObject >
typedef NamedObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
CartesianField ()=default
Default constructor.
CartesianField (const CartesianField &e)=default
Constructor to be used when reading the already parsed DOM tree.
template<typename Q >
CartesianField (const Handle< Q > &e)
Constructor to be used when reading the already parsed DOM tree.
CartesianField & operator= (const CartesianField &f)=default
Assignment operator.
int fieldType () const
Access the field type.
const char * type () const
Access the field type (string)
bool changesEnergy () const
Does the field change the energy of charged particles?
void value (const Position &pos, Direction &field) const
Returns the 3 field components (x, y, z).
void value (const Position &pos, double *val) const
Returns the 3 field components (x, y, z).
void value (const double *pos, double *val) const
Returns the 3 field components (x, y, z).
Properties & properties () const
Access to properties container.
Public Member Functions inherited from DD4hep::Handle< NamedObject >
Handle ()
Defaulot constructor.
Handle (NamedObject *e)
Initializing constructor from pointer.
Handle (const Handle< NamedObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< NamedObject > & operator= (const Handle< NamedObject > &e)=default
Assignment operator.
bool operator== (const Handle< NamedObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< NamedObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< NamedObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< NamedObject > & clear ()
Release the object held by the handle.
NamedObject * operator-> () const
Access the held object using the -> operator.
operator NamedObject & () const
Automatic type conversion to an object references.
NamedObject & operator* () const
Access the held object using the * operator.
NamedObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
NamedObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< NamedObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< NamedObject >
NamedObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing any field with 3D cartesian vectors for the field strength.
Generic structure describing any field type (electric or magnetic) with field components in Cartesian coordinates.
The actual behaviour is solely implemented in the underlying object class.
Author
M.Frank
Version
1.0
Definition at line 46 of file Fields.h.
Member Typedef Documentation
Properties
typedef std::map<std::string, PropertyValues> DD4hep::Geometry::CartesianField::Properties
Definition at line 52 of file Fields.h.
PropertyValues
typedef std::map<std::string, std::string> DD4hep::Geometry::CartesianField::PropertyValues
Definition at line 51 of file Fields.h.
Member Enumeration Documentation
FieldType
enum DD4hep::Geometry::CartesianField::FieldType
Enumerator
UNKNOWN
ELECTRIC
MAGNETIC
Definition at line 48 of file Fields.h.
Constructor & Destructor Documentation
CartesianField() [1/3]
DD4hep::Geometry::CartesianField::CartesianField () default
Default constructor.
CartesianField() [2/3]
DD4hep::Geometry::CartesianField::CartesianField (const CartesianField & e) default
Constructor to be used when reading the already parsed DOM tree.
CartesianField() [3/3]
template<typename Q > DD4hep::Geometry::CartesianField::CartesianField (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed DOM tree.
Definition at line 81 of file Fields.h.
References DD4hep::NamedObject::operator=().
Member Function Documentation
changesEnergy()
bool CartesianField::changesEnergy () const
Does the field change the energy of charged particles?
Definition at line 52 of file Fields.cpp.
References ELECTRIC, and fieldType().
Referenced by fieldType(), and DD4hep::Geometry::OverlayedField::type().
fieldType()
int DD4hep::Geometry::CartesianField::fieldType () const inline
Access the field type.
Definition at line 88 of file Fields.h.
References changesEnergy(), DD4hep::Geometry::CartesianField::Object::properties, DD4hep::Geometry::CartesianField::Object::type, and value().
Referenced by DD4hep::Geometry::OverlayedField::add(), and changesEnergy().
operator=()
CartesianField& DD4hep::Geometry::CartesianField::operator= (const CartesianField & f) default
Assignment operator.
properties()
CartesianField::Properties & CartesianField::properties () const
Access to properties container.
Definition at line 57 of file Fields.cpp.
References DD4hep::Geometry::CartesianField::Object::properties.
type()
const char * CartesianField::type () const
Access the field type (string)
Definition at line 47 of file Fields.cpp.
References DD4hep::NamedObject::GetTitle(), and DD4hep::Handle< NamedObject >::m_element.
value() [1/3]
void CartesianField::value (const Position & pos, Direction & field) const
Returns the 3 field components (x, y, z).
Definition at line 62 of file Fields.cpp.
Referenced by DD4hep::Geometry::OverlayedField::electricField(), fieldType(), DD4hep::Geometry::OverlayedField::magneticField(), and value().
value() [2/3]
void CartesianField::value (const Position & pos, double * val) const
Returns the 3 field components (x, y, z).
Definition at line 67 of file Fields.cpp.
References value().
value() [3/3]
void CartesianField::value (const double * pos, double * val) const
Returns the 3 field components (x, y, z).
Definition at line 72 of file Fields.cpp.
References DD4hep::Geometry::CartesianField::Object::fieldComponents().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Fields.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Fields.cpp