DD4hep: DD4hep::XML::LayeringCnv Class Reference
DD4hep::XML::LayeringCnv Class Reference
DD4hep::XML classes and objects
XML converter for layering objects.
#include <Layering.h>
Public Member Functions
LayeringCnv (Element e)
Initializing constructor.
void fromCompact (Layering &layering) const
Invoke converter.
Public Member Functions inherited from DD4hep::XML::Element
Element (const Handle_t &e)
Constructor from XmlElement handle.
Element (const Element &e)
Constructor from XmlElement handle.
Element (const Document &document, const XmlChar *type)
Constructor from DOM document entity.
Document document () const
Access the hosting document handle of this DOM element.
operator bool () const
operator bool: check handle validity
bool operator! () const
operator NOT: check handle validity
Element & operator= (const Element &c)
Assignment operator.
Element & operator= (Handle_t handle)
Assignment operator.
operator Handle_t () const
Automatic conversion to DOM element handle.
operator Elt_t () const
Automatic conversion to XmlElement pointer.
Elt_t ptr () const
Access to XmlElement pointer.
Handle_t parent () const
Access the XmlElements parent.
Elt_t parentElement () const
Access the XmlElements parent.
std::string tag () const
Access the tag name of this DOM element.
const XmlChar * tagName () const
Access the tag name of this DOM element.
void append (Handle_t handle) const
Append a new element to the existing tree.
Handle_t clone (const Document &new_doc) const
Clone the DOMelement.
bool hasAttr (const XmlChar *name) const
Check for the existence of a named attribute.
template<class T >
T attr (const XmlChar *tag_value) const
Access attribute with implicit return type conversion.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
const XmlChar * attr_name (const Attribute a) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute a) const
Access attribute value by the attribute (throws exception if not present)
size_t numChildren (const XmlChar *tag_value, bool exc=true) const
Access the number of children of this DOM element with a given tag name.
void setAttrs (Handle_t e) const
Remove own attributes and copy all attributes from handle 'e'.
void removeAttrs () const
Remove all attributes of this element.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
Attribute getAttr (const XmlChar *name) const
Access single attribute by it's name.
template<class T >
Attribute setAttr (const XmlChar *nam, const T &val) const
Set single attribute.
template<class T >
void setValue (const T &val) const
Set element value.
Handle_t clone (Handle_t h) const
Clone the DOM element tree.
Handle_t addChild (const XmlChar *tag) const
Add a new child to the DOM node.
Handle_t setChild (const XmlChar *tag) const
Check if a child with the required tag exists - if not create it and add it to the current node.
Handle_t child (const Strng_t &tag_value, bool except=true) const
Access child by tag name. Thow an exception if required in case the child is not present.
Handle_t remove (Handle_t node) const
Remove a child node identified by its handle.
bool hasChild (const XmlChar *tag_value) const
Check the existence of a child with a given tag name.
Attribute setRef (const XmlChar *tag, const XmlChar *refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Attribute setRef (const XmlChar *tag, const std::string &refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
const XmlChar * getRef (const XmlChar *tag) const
Access the value of the reference attribute of the node (attribute ref="ref-name")
void addComment (const char *text) const
Add comment node to the element.
Additional Inherited Members
Public Types inherited from DD4hep::XML::Element
typedef Handle_t::Elt_t Elt_t
Simplification type declarations.
Public Attributes inherited from DD4hep::XML::Element
Handle_t m_element
The underlying object holding the XmlElement pointer.
Detailed Description
XML converter for layering objects.
Author
M.Frank
Version
1.0
Definition at line 171 of file Layering.h.
Constructor & Destructor Documentation
LayeringCnv()
DD4hep::XML::LayeringCnv::LayeringCnv (Element e) inline
Initializing constructor.
Definition at line 180 of file Layering.h.
Member Function Documentation
fromCompact()
void LayeringCnv::fromCompact (Layering & layering) const
Invoke converter.
Definition at line 90 of file Layering.cpp.
References _U, DD4hep::Layer::add(), DD4hep::Layer::compute(), DD4hep::XML::Element::hasAttr(), DD4hep::XML::Component::isSensitive(), DD4hep::Layering::layers(), DD4hep::XML::Component::materialStr(), DD4hep::XML::Dimension::repeat(), s, and DD4hep::XML::Dimension::thickness().
Referenced by DD4hep::Layering::Layering().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/Layering.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/Layering.cpp