DD4hep: DD4hep::PropertyManager Class Reference
DD4hep::PropertyManager Class Reference
DD4hep::Simulation components, classes and objects
Manager to ease the handling of groups of properties.
#include <ComponentProperties.h>
Public Types
typedef std::map< std::string, Property > Properties
Property array definition.
Public Member Functions
PropertyManager ()
Default constructor.
virtual ~PropertyManager ()
Default destructor.
bool exists (const std::string &name) const
Check for existence.
const Property & property (const std::string &name) const
Access property by name (CONST)
Property & property (const std::string &name)
Access property by name.
Property & operator[] (const std::string &name)
Access property by name.
const Property & operator[] (const std::string &name) const
Access property by name.
void add (const std::string &name, const Property &property)
Add a new property.
template<typename T >
void add (const std::string &name, T &value)
Add a new property.
void set (const std::string &component_name, PropertyConfigurator &setup)
Bulk set of all properties.
template<typename FUNCTOR >
void for_each (FUNCTOR &func)
Apply functor on properties.
void adopt (const PropertyManager &copy)
Export properties of another instance.
void dump () const
Dump string values.
Protected Member Functions
void verifyNonExistence (const std::string &name) const
Verify that this property does not exist (throw exception if the name was found)
Properties::iterator verifyExistence (const std::string &name)
Verify that this property exists (throw exception if the name was not found)
Properties::const_iterator verifyExistence (const std::string &name) const
Verify that this property exists (throw exception if the name was not found)
Protected Attributes
Properties m_properties
Property array/map.
Detailed Description
Manager to ease the handling of groups of properties.
Author
M.Frank
Version
1.0
Definition at line 185 of file ComponentProperties.h.
Member Typedef Documentation
Properties
typedef std::map<std::string, Property> DD4hep::PropertyManager::Properties
Property array definition.
Definition at line 188 of file ComponentProperties.h.
Constructor & Destructor Documentation
PropertyManager()
PropertyManager::PropertyManager ()
Default constructor.
Definition at line 134 of file ComponentProperties.cpp.
~PropertyManager()
PropertyManager::~PropertyManager () virtual
Default destructor.
Definition at line 138 of file ComponentProperties.cpp.
Member Function Documentation
add() [1/2]
void PropertyManager::add (const std::string & name, const Property & property)
Add a new property.
Definition at line 198 of file ComponentProperties.cpp.
Referenced by DD4hep::Simulation::Geant4Kernel::declareProperty(), and DD4hep::Simulation::Geant4Action::declareProperty().
add() [2/2]
template<typename T > void DD4hep::PropertyManager::add (const std::string & name, T & value) inline
Add a new property.
Definition at line 218 of file ComponentProperties.h.
adopt()
void PropertyManager::adopt (const PropertyManager & copy)
Export properties of another instance.
Definition at line 143 of file ComponentProperties.cpp.
References m_properties.
Referenced by DD4hep::Simulation::Geant4SharedStackingAction::use(), DD4hep::Simulation::Geant4SharedSteppingAction::use(), DD4hep::Simulation::Geant4SharedRunAction::use(), DD4hep::Simulation::Geant4SharedTrackingAction::use(), and DD4hep::Simulation::Geant4SharedEventAction::use().
dump()
void PropertyManager::dump () const
Dump string values.
Definition at line 212 of file ComponentProperties.cpp.
References DD4hep::ALWAYS, DD4hep::printout(), and DD4hep::Property::str().
Referenced by DD4hep::Simulation::Geant4UIMessenger::exportProperties(), and DD4hep::Converter< T, ARG >::operator()().
exists()
bool PropertyManager::exists (const std::string & name) const
Check for existence.
Definition at line 148 of file ComponentProperties.cpp.
Referenced by DD4hep::Simulation::Geant4Kernel::hasProperty().
for_each()
template<typename FUNCTOR > void DD4hep::PropertyManager::for_each (FUNCTOR & func) inline
Apply functor on properties.
Definition at line 224 of file ComponentProperties.h.
References DD4hep::Alignments::AlignmentTools::copy().
Referenced by DD4hep::Simulation::Geant4UIMessenger::exportProperties().
operator[]() [1/2]
Property & PropertyManager::operator[] (const std::string & name)
Access property by name.
Definition at line 188 of file ComponentProperties.cpp.
operator[]() [2/2]
const Property & PropertyManager::operator[] (const std::string & name) const
Access property by name.
Definition at line 193 of file ComponentProperties.cpp.
property() [1/2]
const Property & PropertyManager::property (const std::string & name) const
Access property by name (CONST)
Access property by name.
Definition at line 183 of file ComponentProperties.cpp.
property() [2/2]
Property & PropertyManager::property (const std::string & name)
Access property by name.
Access property by name (CONST)
Definition at line 178 of file ComponentProperties.cpp.
set()
void PropertyManager::set (const std::string & component_name, PropertyConfigurator & setup)
Bulk set of all properties.
Definition at line 204 of file ComponentProperties.cpp.
References DD4hep::Property::grammar(), DD4hep::Property::ptr(), and DD4hep::PropertyConfigurator::set().
verifyExistence() [1/2]
PropertyManager::Properties::iterator PropertyManager::verifyExistence (const std::string & name) protected
Verify that this property exists (throw exception if the name was not found)
Definition at line 170 of file ComponentProperties.cpp.
verifyExistence() [2/2]
PropertyManager::Properties::const_iterator PropertyManager::verifyExistence (const std::string & name) const protected
Verify that this property exists (throw exception if the name was not found)
Definition at line 162 of file ComponentProperties.cpp.
verifyNonExistence()
void PropertyManager::verifyNonExistence (const std::string & name) const protected
Verify that this property does not exist (throw exception if the name was found)
Definition at line 154 of file ComponentProperties.cpp.
Member Data Documentation
m_properties
Properties DD4hep::PropertyManager::m_properties protected
Property array/map.
Definition at line 191 of file ComponentProperties.h.
Referenced by adopt().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ComponentProperties.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ComponentProperties.cpp