DD4hep: DD4hep::DDRec::ConeSurface Class Reference
DD4hep::DDRec::ConeSurface Class Reference
#include <Surface.h>
Public Member Functions
ConeSurface (Geometry::DetElement det, VolSurface volSurf)
virtual double radius0 () const
the start radius of the cone
virtual double radius1 () const
the end radius of the cone
virtual double z0 () const
the start z of the cone
virtual double z1 () const
the end z of the cone
virtual Vector3D center () const
the center of the cone
Public Member Functions inherited from DD4hep::DDRec::CylinderSurface
CylinderSurface (Geometry::DetElement det, VolSurface volSurf)
Standard c'tor.
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
virtual double radius () const
the radius of the cylinder (rho of the origin vector)
Public Member Functions inherited from DD4hep::DDRec::Surface
virtual ~Surface ()
Surface (Geometry::DetElement det, VolSurface volSurf)
virtual long64 id () const
The id of this surface - corresponds to DetElement id.
virtual const SurfaceType & type () const
Geometry::Volume volume () const
The volume that has the surface attached.
VolSurface volSurface () const
The VolSurface attched to the volume.
virtual const Vector3D & origin () const
virtual double innerThickness () const
virtual double outerThickness () const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double distance (const Vector3D &point) const
virtual bool insideBounds (const Vector3D &point, double epsilon=1.e-4) const
Checks if the given point lies within the surface.
virtual Vector3D volumeOrigin () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual std::vector< std::pair< Vector3D, Vector3D > > getLines (unsigned nMax=100)
Public Member Functions inherited from DDSurfaces::ISurface
virtual ~ISurface ()
Destructor.
Public Member Functions inherited from DDSurfaces::ICylinder
virtual ~ICylinder ()
Destructor.
Public Member Functions inherited from DDSurfaces::ICone
virtual ~ICone ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDRec::Surface
Surface ()
default c'tor
void initialize ()
Protected Attributes inherited from DD4hep::DDRec::Surface
Geometry::DetElement _det
VolSurface _volSurf
TGeoMatrix * _wtM
long64 _id
SurfaceType _type
Vector3D _u
Vector3D _v
Vector3D _n
Vector3D _o
Detailed Description
Specialization of Surface for cones - specializes CyliderSurface (for lazyness ...)
Author
F.Gaede, DESY
Date
May, 10 2014
Definition at line 663 of file Surface.h.
Constructor & Destructor Documentation
ConeSurface()
DD4hep::DDRec::ConeSurface::ConeSurface (Geometry::DetElement det, VolSurface volSurf) inline
Definition at line 665 of file Surface.h.
Member Function Documentation
center()
Vector3D DD4hep::DDRec::ConeSurface::center () const virtual
the center of the cone
Reimplemented from DD4hep::DDRec::CylinderSurface.
Definition at line 1284 of file Surface.cpp.
References DD4hep::DDRec::Surface::volumeOrigin().
radius0()
double DD4hep::DDRec::ConeSurface::radius0 () const virtual
the start radius of the cone
Implements DDSurfaces::ICone.
Definition at line 1252 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::length_along_v(), DD4hep::DDRec::Surface::origin(), DDSurfaces::Vector3D::rho(), DDSurfaces::Vector3D::theta(), and DD4hep::DDRec::VolSurface::v().
radius1()
double DD4hep::DDRec::ConeSurface::radius1 () const virtual
the end radius of the cone
Implements DDSurfaces::ICone.
Definition at line 1260 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::length_along_v(), DD4hep::DDRec::Surface::origin(), DDSurfaces::Vector3D::rho(), DDSurfaces::Vector3D::theta(), and DD4hep::DDRec::VolSurface::v().
z0()
double DD4hep::DDRec::ConeSurface::z0 () const virtual
the start z of the cone
Implements DDSurfaces::ICone.
Definition at line 1268 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::length_along_v(), DD4hep::DDRec::Surface::origin(), DDSurfaces::Vector3D::theta(), DD4hep::DDRec::VolSurface::v(), and DDSurfaces::Vector3D::z().
z1()
double DD4hep::DDRec::ConeSurface::z1 () const virtual
the end z of the cone
Implements DDSurfaces::ICone.
Definition at line 1276 of file Surface.cpp.
References DD4hep::DDRec::Surface::_volSurf, DD4hep::DDRec::Surface::length_along_v(), DD4hep::DDRec::Surface::origin(), DDSurfaces::Vector3D::theta(), DD4hep::DDRec::VolSurface::v(), and DDSurfaces::Vector3D::z().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp