DD4hep: DD4hep::DDRec::MaterialData Class Reference
DD4hep::DDRec::MaterialData Class Reference
#include <Material.h>
Public Member Functions
MaterialData (Geometry::Material m)
MaterialData ()
MaterialData (const std::string &nam, double Z_val, double A_val, double density_val, double radLength, double intLength)
MaterialData (const MaterialData &m)
MaterialData (const IMaterial &m)
MaterialData & operator= (const MaterialData &m)
copy assignement
MaterialData & operator= (const IMaterial &m)
assignment from Geometry::Material
MaterialData & operator= (const Geometry::Material &m)
assignment from Geometry::Material
bool isValid () const
true if initialized
virtual ~MaterialData ()
virtual std::string name () const
material name
virtual double Z () const
averaged proton number
virtual double A () const
averaged atomic number
virtual double density () const
density
virtual double radiationLength () const
radiation length - tgeo units
virtual double interactionLength () const
interaction length - tgeo units
Public Member Functions inherited from DDSurfaces::IMaterial
virtual ~IMaterial ()
Destructor.
Protected Attributes
std::string _name
double _Z
double _A
double _rho
double _x0
double _lambda
Additional Inherited Members
Protected Member Functions inherited from DDSurfaces::IMaterial
IMaterial & operator= (const IMaterial &)
Assignment operator.
Detailed Description
Simple data class that implements the DDSurfaces::IMaterial interface and is used in the Surface implementation.
Author
F.Gaede, DESY
Date
May, 20 2014
Version
$Id$
Definition at line 20 of file Material.h.
Constructor & Destructor Documentation
MaterialData() [1/5]
DD4hep::DDRec::MaterialData::MaterialData (Geometry::Material m) inline
Instantiate from Geometry::Material - default initialization if handle is not valid
Definition at line 33 of file Material.h.
References DD4hep::Geometry::Material::A(), DD4hep::Geometry::Material::density(), DD4hep::Geometry::Material::intLength(), DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), DD4hep::Geometry::Material::radLength(), and DD4hep::Geometry::Material::Z().
MaterialData() [2/5]
DD4hep::DDRec::MaterialData::MaterialData () inline
Default c'tor .
Definition at line 55 of file Material.h.
MaterialData() [3/5]
DD4hep::DDRec::MaterialData::MaterialData (const std::string & nam, double Z_val, double A_val, double density_val, double radLength, double intLength) inline
C'tor setting all attributes .
Definition at line 63 of file Material.h.
MaterialData() [4/5]
DD4hep::DDRec::MaterialData::MaterialData (const MaterialData & m) inline
Copy c'tor .
Definition at line 72 of file Material.h.
MaterialData() [5/5]
DD4hep::DDRec::MaterialData::MaterialData (const IMaterial & m) inline
Copy c'tor .
Definition at line 80 of file Material.h.
~MaterialData()
virtual DD4hep::DDRec::MaterialData::~MaterialData () inline virtual
D'tor.
Definition at line 142 of file Material.h.
Member Function Documentation
A()
virtual double DD4hep::DDRec::MaterialData::A () const inline virtual
averaged atomic number
Implements DDSurfaces::IMaterial.
Definition at line 151 of file Material.h.
References _A.
Referenced by DD4hep::DDRec::createGearForILD().
density()
virtual double DD4hep::DDRec::MaterialData::density () const inline virtual
density
Implements DDSurfaces::IMaterial.
Definition at line 154 of file Material.h.
References _rho.
Referenced by DD4hep::DDRec::createGearForILD().
interactionLength()
virtual double DD4hep::DDRec::MaterialData::interactionLength () const inline virtual
interaction length - tgeo units
Implements DDSurfaces::IMaterial.
Definition at line 160 of file Material.h.
References _lambda.
Referenced by DD4hep::DDRec::createGearForILD().
isValid()
bool DD4hep::DDRec::MaterialData::isValid () const inline
true if initialized
Definition at line 139 of file Material.h.
name()
virtual std::string DD4hep::DDRec::MaterialData::name () const inline virtual
material name
Implements DDSurfaces::IMaterial.
Definition at line 145 of file Material.h.
References _name.
operator=() [1/3]
MaterialData& DD4hep::DDRec::MaterialData::operator= (const MaterialData & m) inline
copy assignement
Definition at line 88 of file Material.h.
References _A, _lambda, _name, _rho, _x0, and _Z.
operator=() [2/3]
MaterialData& DD4hep::DDRec::MaterialData::operator= (const IMaterial & m) inline
assignment from Geometry::Material
Definition at line 101 of file Material.h.
References DDSurfaces::IMaterial::A(), DDSurfaces::IMaterial::density(), DDSurfaces::IMaterial::interactionLength(), DDSurfaces::IMaterial::name(), DDSurfaces::IMaterial::radiationLength(), and DDSurfaces::IMaterial::Z().
operator=() [3/3]
MaterialData& DD4hep::DDRec::MaterialData::operator= (const Geometry::Material & m) inline
assignment from Geometry::Material
Definition at line 114 of file Material.h.
References DD4hep::Geometry::Material::A(), DD4hep::Geometry::Material::density(), DD4hep::Geometry::Material::intLength(), DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), DD4hep::Geometry::Material::radLength(), and DD4hep::Geometry::Material::Z().
radiationLength()
virtual double DD4hep::DDRec::MaterialData::radiationLength () const inline virtual
radiation length - tgeo units
Implements DDSurfaces::IMaterial.
Definition at line 157 of file Material.h.
References _x0.
Referenced by DD4hep::DDRec::createGearForILD().
Z()
virtual double DD4hep::DDRec::MaterialData::Z () const inline virtual
averaged proton number
Implements DDSurfaces::IMaterial.
Definition at line 148 of file Material.h.
References _Z.
Referenced by DD4hep::DDRec::createGearForILD().
Member Data Documentation
_A
double DD4hep::DDRec::MaterialData::_A protected
Definition at line 25 of file Material.h.
Referenced by A(), and operator=().
_lambda
double DD4hep::DDRec::MaterialData::_lambda protected
Definition at line 28 of file Material.h.
Referenced by interactionLength(), and operator=().
_name
std::string DD4hep::DDRec::MaterialData::_name protected
Definition at line 23 of file Material.h.
Referenced by name(), and operator=().
_rho
double DD4hep::DDRec::MaterialData::_rho protected
Definition at line 26 of file Material.h.
Referenced by density(), and operator=().
_x0
double DD4hep::DDRec::MaterialData::_x0 protected
Definition at line 27 of file Material.h.
Referenced by operator=(), and radiationLength().
_Z
double DD4hep::DDRec::MaterialData::_Z protected
Definition at line 24 of file Material.h.
Referenced by operator=(), and Z().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Material.h