DD4hep: DD4hep::XML::Strng_t Class Reference
DD4hep::XML::Strng_t Class Reference
DD4hep::XML classes and objects
Helper class to encapsulate a unicode string.
#include <XMLElements.h>
Public Member Functions
Strng_t (const XmlChar *c)
Initializing constructor from unicode string.
Strng_t & operator= (const XmlChar *s)
Assignment opertor from unicode string.
Strng_t (const char *c)
Initializing constructor from ascii string.
Strng_t (const std::string &c)
Initializing constructor from STL string.
Strng_t (const Strng_t &c)
Copy constructor.
~Strng_t ()
Default destructor - release unicode string.
operator const XmlChar * () const
Auto-conversion to unicode string.
const XmlChar * ptr () const
Accessor to unicode string.
size_t length () const
String length in native representation.
Strng_t & operator= (const char *s)
Assignment opertor from ascii string.
Strng_t & operator= (const Strng_t &s)
Assignment opertor from helper string.
Strng_t & operator= (const std::string &s)
Assignment opertor from STL string.
Public Attributes
XmlChar * m_xml
Pointer to unicode string.
Detailed Description
Helper class to encapsulate a unicode string.
Simple conversion from ascii strings to unicode strings. Useful when using XercesC - dummy implementation for TiXml.
Author
M.Frank
Version
1.0
Definition at line 160 of file XMLElements.h.
Constructor & Destructor Documentation
Strng_t() [1/4]
DD4hep::XML::Strng_t::Strng_t (const XmlChar * c) inline
Initializing constructor from unicode string.
Definition at line 166 of file XMLElements.h.
Strng_t() [2/4]
DD4hep::XML::Strng_t::Strng_t (const char * c) inline
Initializing constructor from ascii string.
Definition at line 173 of file XMLElements.h.
Strng_t() [3/4]
DD4hep::XML::Strng_t::Strng_t (const std::string & c) inline
Initializing constructor from STL string.
Definition at line 177 of file XMLElements.h.
References DD4hep::XML::XmlString::transcode().
Strng_t() [4/4]
DD4hep::XML::Strng_t::Strng_t (const Strng_t & c) inline
Copy constructor.
Definition at line 181 of file XMLElements.h.
References m_xml, and DD4hep::XML::XmlString::replicate().
~Strng_t()
DD4hep::XML::Strng_t::~Strng_t () inline
Default destructor - release unicode string.
Definition at line 185 of file XMLElements.h.
References DD4hep::XML::XmlString::release().
Member Function Documentation
length()
size_t DD4hep::XML::Strng_t::length () const inline
String length in native representation.
Definition at line 198 of file XMLElements.h.
References DD4hep::XML::XmlString::length(), and DD4hep::XML::operator+().
operator const XmlChar *()
DD4hep::XML::Strng_t::operator const XmlChar * () const inline
Auto-conversion to unicode string.
Definition at line 190 of file XMLElements.h.
operator=() [1/4]
Strng_t & Strng_t::operator= (const XmlChar * s)
Assignment opertor from unicode string.
Definition at line 479 of file XMLElements.cpp.
operator=() [2/4]
Strng_t & Strng_t::operator= (const char * s)
Assignment opertor from ascii string.
Definition at line 487 of file XMLElements.cpp.
operator=() [3/4]
Strng_t & Strng_t::operator= (const Strng_t & s)
Assignment opertor from helper string.
Definition at line 494 of file XMLElements.cpp.
References m_xml.
operator=() [4/4]
Strng_t & Strng_t::operator= (const std::string & s)
Assignment opertor from STL string.
Definition at line 503 of file XMLElements.cpp.
ptr()
const XmlChar* DD4hep::XML::Strng_t::ptr () const inline
Accessor to unicode string.
Definition at line 194 of file XMLElements.h.
Referenced by DD4hep::XML::operator+().
Member Data Documentation
m_xml
XmlChar* DD4hep::XML::Strng_t::m_xml
Pointer to unicode string.
Definition at line 163 of file XMLElements.h.
Referenced by operator=(), DD4hep::XML::Tag_t::operator=(), and Strng_t().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp