DD4hep: DD4hep::Simulation::Geant4ConversionHelper Class Reference
DD4hep::Simulation::Geant4ConversionHelper Class Reference
DD4hep::Simulation components, classes and objects
Helper class for data conversion.
#include <Geant4DataConversion.h>
Public Member Functions
Geant4ConversionHelper ()
Default constructor.
virtual ~Geant4ConversionHelper ()
Default destructor.
Static Public Member Functions
static std::string encoding (Geometry::VolumeManager vm, Geometry::VolumeManager::VolumeID vid)
Access to the data encoding using the volume manager and a specified volume id.
static std::string encoding (Geometry::Handle< Geometry::SensitiveDetectorObject > sd)
Access to the hit encoding in this sensitive detector.
static std::string encoding (Geometry::Readout ro)
Access to the hit encoding in this readout object.
Detailed Description
Helper class for data conversion.
Author
M.Frank
Version
1.0
Definition at line 35 of file Geant4DataConversion.h.
Constructor & Destructor Documentation
Geant4ConversionHelper()
Geant4ConversionHelper::Geant4ConversionHelper ()
Default constructor.
Definition at line 21 of file Geant4DataConversion.cpp.
~Geant4ConversionHelper()
Geant4ConversionHelper::~Geant4ConversionHelper () virtual
Default destructor.
Definition at line 25 of file Geant4DataConversion.cpp.
Member Function Documentation
encoding() [1/3]
std::string Geant4ConversionHelper::encoding (Geometry::VolumeManager vm, Geometry::VolumeManager::VolumeID vid) static
Access to the data encoding using the volume manager and a specified volume id.
Definition at line 29 of file Geant4DataConversion.cpp.
References DD4hep::Geometry::VolumeManager::lookupPlacement(), DD4hep::Geometry::Volume::sensitiveDetector(), and DD4hep::Geometry::PlacedVolume::volume().
encoding() [2/3]
std::string Geant4ConversionHelper::encoding (Geometry::Handle< Geometry::SensitiveDetectorObject > sd) static
Access to the hit encoding in this sensitive detector.
Definition at line 36 of file Geant4DataConversion.cpp.
References DD4hep::Geometry::IDDescriptor::fieldDescription(), DD4hep::Geometry::Readout::idSpec(), and DD4hep::Geometry::SensitiveDetector::readout().
encoding() [3/3]
std::string Geant4ConversionHelper::encoding (Geometry::Readout ro) static
Access to the hit encoding in this readout object.
Definition at line 42 of file Geant4DataConversion.cpp.
References DD4hep::Geometry::IDDescriptor::fieldDescription(), and DD4hep::Geometry::Readout::idSpec().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4DataConversion.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4DataConversion.cpp