DD4hep: DD4hep::Simulation::Geant4ActionSD Class Reference
DD4hep::Simulation::Geant4ActionSD Class Reference abstract
DD4hep::Simulation components, classes and objects
Interface class to access properties of the underlying Geant4 sensitive detector structure.
#include <Geant4SensDetAction.h>
Public Types
typedef Geometry::SensitiveDetector SensitiveDetector
Definition: Sensitive detector type.
Public Member Functions
virtual size_t defineCollection (const std::string &name)=0
Initialize the usage of a hit collection. Returns the collection identifier.
virtual G4VReadOutGeometry * readoutGeometry () const =0
Access to the readout geometry of the sensitive detector.
virtual G4int GetCollectionID (G4int i)=0
This is a utility method which returns the hits collection ID.
virtual bool isActive () const =0
Is the detector active?
virtual SensitiveDetector sensitiveDetector () const =0
Access to the LCDD sensitive detector handle.
virtual std::string path () const =0
G4VSensitiveDetector internals: Access to the detector path name.
virtual std::string fullPath () const =0
G4VSensitiveDetector internals: Access to the detector path name.
virtual const std::string & sensitiveType () const =0
Access to the sensitive type of the detector.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Member Functions
Geant4ActionSD (const std::string &name)
Standard action constructor.
virtual ~Geant4ActionSD ()
Default destructor.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Additional Inherited Members
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Detailed Description
Interface class to access properties of the underlying Geant4 sensitive detector structure.
Author
M.Frank
Version
1.0
Definition at line 60 of file Geant4SensDetAction.h.
Member Typedef Documentation
SensitiveDetector
typedef Geometry::SensitiveDetector DD4hep::Simulation::Geant4ActionSD::SensitiveDetector
Definition: Sensitive detector type.
Definition at line 68 of file Geant4SensDetAction.h.
Constructor & Destructor Documentation
Geant4ActionSD()
Geant4ActionSD::Geant4ActionSD (const std::string & name) protected
Standard action constructor.
Definition at line 62 of file Geant4SensDetAction.cpp.
References DD4hep::InstanceCount::increment().
~Geant4ActionSD()
Geant4ActionSD::~Geant4ActionSD () protected virtual
Default destructor.
Definition at line 68 of file Geant4SensDetAction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
defineCollection()
virtual size_t DD4hep::Simulation::Geant4ActionSD::defineCollection (const std::string & name) pure virtual
Initialize the usage of a hit collection. Returns the collection identifier.
Implemented in DD4hep::Simulation::Geant4SensDet.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::defineCollection().
fullPath()
virtual std::string DD4hep::Simulation::Geant4ActionSD::fullPath () const pure virtual
G4VSensitiveDetector internals: Access to the detector path name.
Implemented in DD4hep::Simulation::Geant4SensDet.
GetCollectionID()
virtual G4int DD4hep::Simulation::Geant4ActionSD::GetCollectionID (G4int i) pure virtual
This is a utility method which returns the hits collection ID.
Implemented in DD4hep::Simulation::Geant4SensDet.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::begin(), and DD4hep::Simulation::Geant4SensDetActionSequence::collection().
isActive()
virtual bool DD4hep::Simulation::Geant4ActionSD::isActive () const pure virtual
Is the detector active?
Implemented in DD4hep::Simulation::Geant4SensDet.
path()
virtual std::string DD4hep::Simulation::Geant4ActionSD::path () const pure virtual
G4VSensitiveDetector internals: Access to the detector path name.
Implemented in DD4hep::Simulation::Geant4SensDet.
readoutGeometry()
virtual G4VReadOutGeometry* DD4hep::Simulation::Geant4ActionSD::readoutGeometry () const pure virtual
Access to the readout geometry of the sensitive detector.
Implemented in DD4hep::Simulation::Geant4SensDet.
sensitiveDetector()
virtual SensitiveDetector DD4hep::Simulation::Geant4ActionSD::sensitiveDetector () const pure virtual
Access to the LCDD sensitive detector handle.
Implemented in DD4hep::Simulation::Geant4SensDet.
sensitiveType()
virtual const std::string& DD4hep::Simulation::Geant4ActionSD::sensitiveType () const pure virtual
Access to the sensitive type of the detector.
Implemented in DD4hep::Simulation::Geant4SensDet.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::mark().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensDetAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SensDetAction.cpp