DD4hep: DD4hep::Geometry::DetectorSelector Class Reference
DD4hep::Geometry::DetectorSelector Class Reference
View on LCDD to select detectors according to certain criteria.
#include <DetectorSelector.h>
Public Types
typedef std::vector< DetElement > Result
Result set definition.
Public Member Functions
DetectorSelector (LCDD &_lcdd)
Default constructor.
~DetectorSelector ()
Default destructor.
const Result & detectors (const std::string &type)
Access a set of subdetectors according to the sensitive type.
Result detectors (const std::string &type1, const std::string &type2, const std::string &type3="", const std::string &type4="", const std::string &type5="")
Access a set of subdetectors according to several sensitive types.
Result detectors (unsigned int includeFlag, unsigned int excludeFlag=0) const
Public Attributes
LCDD & lcdd
Reference to main detector description object.
Detailed Description
View on LCDD to select detectors according to certain criteria.
Usage:
LCDD& lcd = ....; DetectorSelector selector(lcdd); DetectorSelector::Result r = selector.detectors("tracker");
or multiple types: r = selector.detectors("tracker", "calorimeter");
or selections using DetType flags, e.g: select all barrel trackers but not the Vertex detector r = selector.detectors(DetType::TRACKER | DetType::BARREL , DetType::VERTEX) ;
Author
M.Frank
Version
1.0
Definition at line 45 of file DetectorSelector.h.
Member Typedef Documentation
Result
typedef std::vector<DetElement> DD4hep::Geometry::DetectorSelector::Result
Result set definition.
Definition at line 48 of file DetectorSelector.h.
Constructor & Destructor Documentation
DetectorSelector()
DD4hep::Geometry::DetectorSelector::DetectorSelector (LCDD & _lcdd) inline
Default constructor.
Definition at line 57 of file DetectorSelector.h.
~DetectorSelector()
DD4hep::Geometry::DetectorSelector::~DetectorSelector () inline
Default destructor.
Definition at line 60 of file DetectorSelector.h.
Member Function Documentation
detectors() [1/3]
const DetectorSelector::Result & DetectorSelector::detectors (const std::string & type)
Access a set of subdetectors according to the sensitive type.
Please note:
The sensitive type of a detector is set in the 'detector constructor'.
Not sensitive detector structures have the name 'passive'
Compounds (ie. nested detectors) are of type 'compound'
Definition at line 24 of file DetectorSelector.cpp.
detectors() [2/3]
DetectorSelector::Result DetectorSelector::detectors (const std::string & type1, const std::string & type2, const std::string & type3 = "", const std::string & type4 = "", const std::string & type5 = "")
Access a set of subdetectors according to several sensitive types.
Definition at line 31 of file DetectorSelector.cpp.
References v.
detectors() [3/3]
DetectorSelector::Result DetectorSelector::detectors (unsigned int includeFlag, unsigned int excludeFlag = 0) const
return a vector with all detectors that have all the type properties in includeFlag set but none of the properties given in excludeFlag
Definition at line 54 of file DetectorSelector.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::parent(), and DD4hep::Geometry::DetElement::typeFlag().
Member Data Documentation
lcdd
LCDD& DD4hep::Geometry::DetectorSelector::lcdd
Reference to main detector description object.
Definition at line 51 of file DetectorSelector.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/DetectorSelector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetectorSelector.cpp