DD4hep: DD4hep::Geometry::LimitSet Class Reference
DD4hep::Geometry::LimitSet Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing a set of limits as they are used for simulation.
#include <Objects.h>
Public Types
typedef LimitSetObject Object
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
LimitSet ()
Constructor to be used when reading the already parsed DOM tree.
LimitSet (const LimitSet &e)
Copy constructor for handle.
LimitSet (const Handle< LimitSetObject > &e)
Copy constructor for handle.
template<typename Q >
LimitSet (const Handle< Q > &e)
Constructor to be used when reading the already parsed DOM tree.
LimitSet & operator= (const LimitSet &c)
Assignment operator.
LimitSet (const std::string &name)
Constructor to be used when creating a new object.
bool addLimit (const DD4hep::Geometry::Limit &limit)
Add new limit. Returns true if the new limit was added, false if it already existed.
const std::set< DD4hep::Geometry::Limit > & limits () const
Accessor to limits container.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing a set of limits as they are used for simulation.
Author
M.Frank
Version
1.0
Definition at line 475 of file Objects.h.
Member Typedef Documentation
Object
typedef LimitSetObject DD4hep::Geometry::LimitSet::Object
Definition at line 477 of file Objects.h.
Constructor & Destructor Documentation
LimitSet() [1/5]
DD4hep::Geometry::LimitSet::LimitSet () inline
Constructor to be used when reading the already parsed DOM tree.
Definition at line 479 of file Objects.h.
LimitSet() [2/5]
DD4hep::Geometry::LimitSet::LimitSet (const LimitSet & e) inline
Copy constructor for handle.
Definition at line 483 of file Objects.h.
References e.
LimitSet() [3/5]
DD4hep::Geometry::LimitSet::LimitSet (const Handle< LimitSetObject > & e) inline
Copy constructor for handle.
Definition at line 488 of file Objects.h.
LimitSet() [4/5]
template<typename Q > DD4hep::Geometry::LimitSet::LimitSet (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed DOM tree.
Definition at line 494 of file Objects.h.
LimitSet() [5/5]
LimitSet::LimitSet (const std::string & name)
Constructor to be used when creating a new object.
Constructor to be used when creating a new DOM tree.
Definition at line 423 of file Objects.cpp.
Member Function Documentation
addLimit()
bool LimitSet::addLimit (const DD4hep::Geometry::Limit & limit)
Add new limit. Returns true if the new limit was added, false if it already existed.
Definition at line 428 of file Objects.cpp.
limits()
const set< Limit > & LimitSet::limits () const
Accessor to limits container.
Definition at line 434 of file Objects.cpp.
Referenced by DD4hep::Simulation::Geant4Converter::handleLimitSet(), and DD4hep::Printer< T >::operator()().
operator=()
LimitSet& DD4hep::Geometry::LimitSet::operator= (const LimitSet & c) inline
Assignment operator.
Definition at line 498 of file Objects.h.
References DD4hep::Handle< T >::m_element, and DD4hep::Handle< T >::name().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp