DD4hep: DD4hep::invalid_handle_exception Class Reference
DD4hep::invalid_handle_exception Class Reference
Specialized exception to be thrown if invalid handles are accessed.
#include <Primitives.h>
Public Member Functions
invalid_handle_exception (const char *msg)
Initializing constructor.
invalid_handle_exception (const std::string &msg)
Initializing constructor.
invalid_handle_exception (const std::exception &e)
Generic copy constructor.
invalid_handle_exception (const invalid_handle_exception &e)
Generic copy constructor.
virtual ~invalid_handle_exception ()=default
Default destructor of specialized exception.
Detailed Description
Specialized exception to be thrown if invalid handles are accessed.
Definition at line 63 of file Primitives.h.
Constructor & Destructor Documentation
invalid_handle_exception() [1/4]
DD4hep::invalid_handle_exception::invalid_handle_exception (const char * msg) inline
Initializing constructor.
Definition at line 66 of file Primitives.h.
invalid_handle_exception() [2/4]
DD4hep::invalid_handle_exception::invalid_handle_exception (const std::string & msg) inline
Initializing constructor.
Definition at line 68 of file Primitives.h.
invalid_handle_exception() [3/4]
DD4hep::invalid_handle_exception::invalid_handle_exception (const std::exception & e) inline
Generic copy constructor.
Definition at line 70 of file Primitives.h.
invalid_handle_exception() [4/4]
DD4hep::invalid_handle_exception::invalid_handle_exception (const invalid_handle_exception & e) inline
Generic copy constructor.
Definition at line 72 of file Primitives.h.
References DD4hep::invalidHandleAssignmentError(), DD4hep::invalidHandleError(), DD4hep::typeinfoCheck(), and DD4hep::typeName().
~invalid_handle_exception()
virtual DD4hep::invalid_handle_exception::~invalid_handle_exception () virtual default
Default destructor of specialized exception.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Primitives.h