DD4hep: DD4hep::Geometry::GeoHandler Class Reference
DD4hep::Geometry::GeoHandler Class Reference
DD4hep::Geometry components, classes and objects
The base class for all DD4hep geometry crawlers.
#include <GeoHandler.h>
Public Member Functions
GeoHandler ()
Default constructor.
GeoHandler (Data *ptr)
Initializing constructor.
virtual ~GeoHandler ()
Default destructor.
bool setPropagateRegions (bool value)
Propagate regions. Returns the previous value.
GeoHandler & collect (DetElement top)
Collect geometry information from traversal.
GeoHandler & collect (DetElement top, GeometryInfo &info)
Collect geometry information from traversal with aggregated information.
Data * release ()
Access to collected node list.
Protected Member Functions
GeoHandler & i_collect (const TGeoNode *node, int level, Region rg, LimitSet ls)
Internal helper to collect geometry information from traversal.
Protected Attributes
bool m_propagateRegions
Data * m_data
Private Member Functions
GeoHandler (const GeoHandler &)
Never call Copy constructor.
GeoHandler & operator= (const GeoHandler &)
Never call assignment operator.
Additional Inherited Members
Public Types inherited from DD4hep::Geometry::GeoHandlerTypes
typedef std::set< Volume > VolumeSet
typedef std::vector< Volume > VolumeVector
typedef std::set< const TGeoVolume * > ConstVolumeSet
typedef std::vector< std::pair< std::string, TGeoMatrix * > > TransformSet
typedef std::set< TGeoShape * > SolidSet
typedef std::set< Material > MaterialSet
typedef std::map< SensitiveDetector, ConstVolumeSet > SensitiveVolumes
typedef std::map< Region, ConstVolumeSet > RegionVolumes
typedef std::map< LimitSet, ConstVolumeSet > LimitVolumes
typedef std::map< int, std::set< const TGeoNode * > > Data
typedef std::set< VisAttr > VisRefs
typedef std::set< SensitiveDetector > SensitiveDetectorSet
typedef std::set< Region > RegionSet
typedef std::set< LimitSet > LimitSetSet
typedef std::set< Ref_t > Fields
typedef std::set< TNamed * > ObjectSet
typedef LCDD::HandleMap DefinitionSet
Detailed Description
The base class for all DD4hep geometry crawlers.
Geometry crawlers are used for multiple purposes, whenever entire geometries must be traversed like e.g. to create a new geometry for simulation etc. While analysing the geometry, information is collected, which may be later processed.
Author
M.Frank
Version
1.0
Definition at line 102 of file GeoHandler.h.
Constructor & Destructor Documentation
GeoHandler() [1/3]
DD4hep::Geometry::GeoHandler::GeoHandler (const GeoHandler &) inline private
Never call Copy constructor.
Definition at line 113 of file GeoHandler.h.
GeoHandler() [2/3]
GeoHandler::GeoHandler ()
Default constructor.
Definition at line 51 of file GeoHandler.cpp.
References m_data.
Referenced by DD4hep::Geometry::GeoScan::GeoScan().
GeoHandler() [3/3]
GeoHandler::GeoHandler (Data * ptr)
Initializing constructor.
Definition at line 56 of file GeoHandler.cpp.
~GeoHandler()
GeoHandler::~GeoHandler () virtual
Default destructor.
Definition at line 61 of file GeoHandler.cpp.
References m_data.
Member Function Documentation
collect() [1/2]
GeoHandler & GeoHandler::collect (DetElement top)
Collect geometry information from traversal.
Definition at line 80 of file GeoHandler.cpp.
References i_collect(), m_data, DD4hep::Geometry::DetElement::placement(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Simulation::Geant4Converter::create(), and DD4hep::Geometry::GeoScan::GeoScan().
collect() [2/2]
GeoHandler & GeoHandler::collect (DetElement top, GeometryInfo & info)
Collect geometry information from traversal with aggregated information.
Definition at line 85 of file GeoHandler.cpp.
References i_collect(), DD4hep::Handle< T >::isValid(), m, m_data, DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::materials, DD4hep::Geometry::DetElement::placement(), DD4hep::Handle< T >::ptr(), v, DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::vis, DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::volumes, and DD4hep::Geometry::GeoHandlerTypes::GeometryInfo::volumeSet.
i_collect()
GeoHandler & GeoHandler::i_collect (const TGeoNode * node, int level, Region rg, LimitSet ls) protected
Internal helper to collect geometry information from traversal.
Definition at line 122 of file GeoHandler.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Geometry::Volume::limitSet(), m_propagateRegions, DD4hep::Geometry::Volume::region(), DD4hep::Geometry::Volume::setLimitSet(), and DD4hep::Geometry::Volume::setRegion().
Referenced by collect().
operator=()
GeoHandler& DD4hep::Geometry::GeoHandler::operator= (const GeoHandler &) inline private
Never call assignment operator.
Definition at line 116 of file GeoHandler.h.
release()
GeoHandler::Data * GeoHandler::release ()
Access to collected node list.
Definition at line 67 of file GeoHandler.cpp.
References m_data.
Referenced by DD4hep::Geometry::GeoScan::GeoScan().
setPropagateRegions()
bool GeoHandler::setPropagateRegions (bool value)
Propagate regions. Returns the previous value.
Definition at line 74 of file GeoHandler.cpp.
References m_propagateRegions.
Referenced by DD4hep::Geometry::GeoScan::GeoScan().
Member Data Documentation
m_data
Data* DD4hep::Geometry::GeoHandler::m_data protected
Definition at line 106 of file GeoHandler.h.
Referenced by collect(), DD4hep::Simulation::Geant4Converter::create(), GeoHandler(), DD4hep::Geometry::GeoScan::GeoScan(), release(), ~GeoHandler(), and DD4hep::Geometry::GeoScan::~GeoScan().
m_propagateRegions
bool DD4hep::Geometry::GeoHandler::m_propagateRegions protected
Definition at line 105 of file GeoHandler.h.
Referenced by DD4hep::Simulation::Geant4Converter::Geant4Converter(), i_collect(), and setPropagateRegions().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/GeoHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/GeoHandler.cpp