DD4hep: DD4hep::Geometry::LCDD Class Reference
DD4hep::Geometry::LCDD Class Reference abstract
DD4hep::Geometry components, classes and objects
The main interface to the DD4hep detector description package.
#include <LCDD.h>
Public Types
typedef XML::UriReader UriReader
Type definition of a map of named handles.
typedef Handle< NamedObject > NamedHandle
typedef std::map< std::string, NamedHandle > HandleMap
typedef std::map< std::string, std::string > PropertyValues
typedef std::map< std::string, PropertyValues > Properties
Public Member Functions
virtual ~LCDD ()=default
Destructor.
virtual LCDDBuildType buildType () const =0
Access flag to steer the detail of building of the geometry/detector description.
virtual void init ()=0
Initialize geometry.
virtual void endDocument ()=0
Finalize the geometry.
virtual TGeoManager & manager () const =0
Access the geometry manager of this instance.
virtual Properties & properties () const =0
Access to properties map.
virtual Material air () const =0
Return handle to material describing air.
virtual Material vacuum () const =0
Return handle to material describing vacuum.
virtual VisAttr invisible () const =0
Return handle to "invisible" visualization attributes.
virtual DetElement world () const =0
Return reference to the top-most (world) detector element.
virtual DetElement trackers () const =0
Return reference to detector element with all tracker devices.
virtual Volume worldVolume () const =0
Return handle to the world volume containing everything.
virtual Volume trackingVolume () const =0
Return handle to the volume containing the tracking devices.
virtual VolumeManager volumeManager () const =0
Return handle to the VolumeManager.
virtual Header header () const =0
Accessor to the map of header entries.
virtual void setHeader (Header h)=0
Accessor to the header entry.
virtual OverlayedField field () const =0
Return handle to the combined electromagentic field description.
virtual const HandleMap & constants () const =0
Accessor to the map of constants.
virtual const HandleMap & regions () const =0
Accessor to the map of region settings.
virtual const HandleMap & detectors () const =0
Accessor to the map of sub-detectors.
virtual const HandleMap & sensitiveDetectors () const =0
Accessor to the map of sub-detectors.
virtual const HandleMap & readouts () const =0
Accessor to the map of readout structures.
virtual const HandleMap & visAttributes () const =0
Accessor to the map of visualisation attributes.
virtual const HandleMap & limitsets () const =0
Accessor to the map of limit settings.
virtual const HandleMap & alignments () const =0
Accessor to the map of aligment entries.
virtual const HandleMap & fields () const =0
Accessor to the map of field entries, which together form the global field.
virtual const HandleMap & idSpecifications () const =0
Accessor to the map of ID specifications.
virtual const std::vector< DetElement > & detectors (const std::string &type, bool throw_exc=false)=0
Access a set of subdetectors according to the sensitive type.
virtual std::vector< DetElement > detectors (const std::string &type1, const std::string &type2, const std::string &type3="", const std::string &type4="", const std::string &type5="")=0
Access a set of subdetectors according to several sensitive types.
virtual std::vector< std::string > detectorTypes () const =0
Access the availible detector types.
virtual std::vector< DetElement > detectors (unsigned int includeFlag, unsigned int excludeFlag=0) const =0
virtual void declareMotherVolume (const std::string &detector_name, const Volume &vol)=0
Register new mother volume using the detector name.
virtual Volume pickMotherVolume (const DetElement &sd) const =0
Access mother volume by detector element.
virtual std::string constantAsString (const std::string &name) const =0
Typed access to constants: access string values.
virtual long constantAsLong (const std::string &name) const =0
Typed access to constants: long values.
virtual double constantAsDouble (const std::string &name) const =0
Typed access to constants: double values.
virtual Constant constant (const std::string &name) const =0
Retrieve a constant by it's name from the detector description.
template<class T >
T constant (const std::string &name) const
Typed access to constants: access any type values.
virtual Material material (const std::string &name) const =0
Retrieve a matrial by it's name from the detector description.
virtual IDDescriptor idSpecification (const std::string &name) const =0
Retrieve a id descriptor by it's name from the detector description.
virtual Region region (const std::string &name) const =0
Retrieve a region object by it's name from the detector description.
virtual VisAttr visAttributes (const std::string &name) const =0
Retrieve a visualization attribute by it's name from the detector description.
virtual LimitSet limitSet (const std::string &name) const =0
Retrieve a limitset by it's name from the detector description.
virtual Readout readout (const std::string &name) const =0
Retrieve a readout object by it's name from the detector description.
virtual AlignmentEntry alignment (const std::string &path) const =0
Retrieve an alignment entry by it's name from the detector description.
virtual SensitiveDetector sensitiveDetector (const std::string &name) const =0
Retrieve a sensitive detector by it's name from the detector description.
virtual CartesianField field (const std::string &name) const =0
Retrieve a subdetector element by it's name from the detector description.
virtual DetElement detector (const std::string &name) const =0
Retrieve a field component by it's name from the detector description.
virtual LCDD & add (Constant constant)=0
Add a new constant to the detector description.
virtual LCDD & add (VisAttr attr)=0
Add a new visualisation attribute to the detector description.
virtual LCDD & add (LimitSet limitset)=0
Add a new limit set to the detector description.
virtual LCDD & add (Region region)=0
Add a new detector region to the detector description.
virtual LCDD & add (IDDescriptor spec)=0
Add a new id descriptor to the detector description.
virtual LCDD & add (Readout readout)=0
Add a new detector readout to the detector description.
virtual LCDD & add (SensitiveDetector entry)=0
Add a new sensitive detector to the detector description.
virtual LCDD & add (DetElement detector)=0
Add a new subdetector to the detector description.
virtual LCDD & add (AlignmentEntry entry)=0
Add alignment entry to the detector description.
virtual LCDD & add (CartesianField entry)=0
Add a field component to the detector description.
virtual LCDD & addConstant (const Ref_t &element)=0
Add a new constant by named reference to the detector description.
virtual LCDD & addVisAttribute (const Ref_t &element)=0
Add a new visualisation attribute by named reference to the detector description.
virtual LCDD & addLimitSet (const Ref_t &limset)=0
Add a new limit set by named reference to the detector description.
virtual LCDD & addIDSpecification (const Ref_t &element)=0
Add a new id descriptor by named reference to the detector description.
virtual LCDD & addRegion (const Ref_t &region)=0
Add a new detector region by named reference to the detector description.
virtual LCDD & addReadout (const Ref_t &readout)=0
Add a new detector readout by named reference to the detector description.
virtual LCDD & addSensitiveDetector (const Ref_t &element)=0
Add a new sensitive detector by named reference to the detector description.
virtual LCDD & addDetector (const Ref_t &detector)=0
Add a new subdetector by named reference to the detector description.
virtual LCDD & addAlignment (const Ref_t &alignment)=0
Add alignment entry by named reference to the detector description.
virtual LCDD & addField (const Ref_t &field)=0
Add a field component by named reference to the detector description.
virtual void fromCompact (const std::string &fname, LCDDBuildType type=BUILD_DEFAULT)=0
Deprecated call (use fromXML): Read compact geometry description or alignment file.
virtual void fromXML (const std::string &fname, LCDDBuildType type=BUILD_DEFAULT)=0
Read any geometry description or alignment file.
virtual void fromXML (const std::string &fname, UriReader *entity_resolver, LCDDBuildType type=BUILD_DEFAULT)=0
Read any geometry description or alignment file with external XML entity resolution.
virtual void dump () const =0
Stupid legacy method.
virtual long apply (const char *factory, int argc, char **argv)=0
Manipulate geometry using factory converter.
template<typename IFACE , typename CONCRETE >
IFACE * addExtension (CONCRETE *c)
Extend the sensitive detector element with an arbitrary structure accessible by the type.
template<class T >
T * removeExtension (bool destroy=true)
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
template<class T >
T * extension (bool alert=true) const
Access extension element by the type.
template<>
short constant (const std::string &name) const
Typed access to constants: short values.
template<>
unsigned short constant (const std::string &name) const
Typed access to constants: unsigned short values.
template<>
int constant (const std::string &name) const
Typed access to constants: integer values.
template<>
unsigned int constant (const std::string &name) const
Typed access to constants: unsigned integer values.
template<>
long constant (const std::string &name) const
Typed access to constants: long values.
template<>
unsigned long constant (const std::string &name) const
Typed access to constants: unsigned long values.
template<>
float constant (const std::string &name) const
Typed access to constants: float values.
template<>
double constant (const std::string &name) const
Typed access to constants: double values.
Static Public Member Functions
static LCDD & getInstance (void)
—Factory method----—
static void destroyInstance ()
Destroy the instance.
Protected Member Functions
virtual void * addUserExtension (void *ptr, const std::type_info &info, void(*destruct)(void *))=0
Add an extension object to the detector element.
virtual void * removeUserExtension (const std::type_info &info, bool destroy)=0
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
virtual void * userExtension (const std::type_info &info, bool alert=true) const =0
Access an existing extension object from the detector element.
Static Protected Member Functions
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Detailed Description
The main interface to the DD4hep detector description package.
Note: The usage of the factory method:
static LCDD& getInstance(void);
is DEPRECATED!
You should rather use the plugin mechanism to create a new instance.
Author
M.Frank
Version
1.0
Definition at line 91 of file LCDD.h.
Member Typedef Documentation
HandleMap
typedef std::map<std::string, NamedHandle > DD4hep::Geometry::LCDD::HandleMap
Definition at line 96 of file LCDD.h.
NamedHandle
typedef Handle<NamedObject> DD4hep::Geometry::LCDD::NamedHandle
Definition at line 95 of file LCDD.h.
Properties
typedef std::map<std::string, PropertyValues> DD4hep::Geometry::LCDD::Properties
Definition at line 98 of file LCDD.h.
PropertyValues
typedef std::map<std::string, std::string> DD4hep::Geometry::LCDD::PropertyValues
Definition at line 97 of file LCDD.h.
UriReader
typedef XML::UriReader DD4hep::Geometry::LCDD::UriReader
Type definition of a map of named handles.
Definition at line 94 of file LCDD.h.
Constructor & Destructor Documentation
~LCDD()
virtual DD4hep::Geometry::LCDD::~LCDD () virtual default
Destructor.
Member Function Documentation
_delete()
template<typename T > static void DD4hep::Geometry::LCDD::_delete (void * ptr) inline static protected
Templated destructor function.
Definition at line 320 of file LCDD.h.
add() [1/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (Constant constant) pure virtual
Add a new constant to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [2/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (VisAttr attr) pure virtual
Add a new visualisation attribute to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [3/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (LimitSet limitset) pure virtual
Add a new limit set to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [4/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (Region region) pure virtual
Add a new detector region to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [5/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (IDDescriptor spec) pure virtual
Add a new id descriptor to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [6/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (Readout readout) pure virtual
Add a new detector readout to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [7/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (SensitiveDetector entry) pure virtual
Add a new sensitive detector to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [8/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (DetElement detector) pure virtual
Add a new subdetector to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [9/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (AlignmentEntry entry) pure virtual
Add alignment entry to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
add() [10/10]
virtual LCDD& DD4hep::Geometry::LCDD::add (CartesianField entry) pure virtual
Add a field component to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addAlignment()
virtual LCDD& DD4hep::Geometry::LCDD::addAlignment (const Ref_t & alignment) pure virtual
Add alignment entry by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addConstant()
virtual LCDD& DD4hep::Geometry::LCDD::addConstant (const Ref_t & element) pure virtual
Add a new constant by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addDetector()
virtual LCDD& DD4hep::Geometry::LCDD::addDetector (const Ref_t & detector) pure virtual
Add a new subdetector by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addExtension()
template<typename IFACE , typename CONCRETE > IFACE* DD4hep::Geometry::LCDD::addExtension (CONCRETE * c) inline
Extend the sensitive detector element with an arbitrary structure accessible by the type.
Definition at line 299 of file LCDD.h.
Referenced by DD4hep::DDRec::createSurfaceManager(), DD4hep::Display::Display(), DD4hep::Simulation::Geant4Kernel::Geant4Kernel(), and DD4hep::Alignments::GlobalAlignmentCache::install().
addField()
virtual LCDD& DD4hep::Geometry::LCDD::addField (const Ref_t & field) pure virtual
Add a field component by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addIDSpecification()
virtual LCDD& DD4hep::Geometry::LCDD::addIDSpecification (const Ref_t & element) pure virtual
Add a new id descriptor by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addLimitSet()
virtual LCDD& DD4hep::Geometry::LCDD::addLimitSet (const Ref_t & limset) pure virtual
Add a new limit set by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addReadout()
virtual LCDD& DD4hep::Geometry::LCDD::addReadout (const Ref_t & readout) pure virtual
Add a new detector readout by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addRegion()
virtual LCDD& DD4hep::Geometry::LCDD::addRegion (const Ref_t & region) pure virtual
Add a new detector region by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addSensitiveDetector()
virtual LCDD& DD4hep::Geometry::LCDD::addSensitiveDetector (const Ref_t & element) pure virtual
Add a new sensitive detector by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
addUserExtension()
virtual void* DD4hep::Geometry::LCDD::addUserExtension (void * ptr, const std::type_info & info, void(*)(void *) destruct) protected pure virtual
Add an extension object to the detector element.
Implemented in DD4hep::Geometry::LCDDImp.
addVisAttribute()
virtual LCDD& DD4hep::Geometry::LCDD::addVisAttribute (const Ref_t & element) pure virtual
Add a new visualisation attribute by named reference to the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
air()
virtual Material DD4hep::Geometry::LCDD::air () const pure virtual
Return handle to material describing air.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by create_detector().
alignment()
virtual AlignmentEntry DD4hep::Geometry::LCDD::alignment (const std::string & path) const pure virtual
Retrieve an alignment entry by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
alignments()
virtual const HandleMap& DD4hep::Geometry::LCDD::alignments () const pure virtual
Accessor to the map of aligment entries.
Implemented in DD4hep::Geometry::LCDDImp.
apply()
virtual long DD4hep::Geometry::LCDD::apply (const char * factory, int argc, char ** argv) pure virtual
Manipulate geometry using factory converter.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::ROOTUI::apply(), DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), DD4hep::createGearMgr(), DD4hep::Simulation::Geant4Kernel::loadGeometry(), and DD4hep::Simulation::Geant4Kernel::loadXML().
buildType()
virtual LCDDBuildType DD4hep::Geometry::LCDD::buildType () const pure virtual
Access flag to steer the detail of building of the geometry/detector description.
Implemented in DD4hep::Geometry::LCDDImp.
constant() [1/10]
virtual Constant DD4hep::Geometry::LCDD::constant (const std::string & name) const pure virtual
Retrieve a constant by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::DDRec::createGearForILD().
constant() [2/10]
template<class T > T DD4hep::Geometry::LCDD::constant (const std::string & name) const
Typed access to constants: access any type values.
constant() [3/10]
template<> short DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: short values.
Definition at line 339 of file LCDD.h.
constant() [4/10]
template<> unsigned short DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: unsigned short values.
Definition at line 344 of file LCDD.h.
constant() [5/10]
template<> int DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: integer values.
Definition at line 349 of file LCDD.h.
constant() [6/10]
template<> unsigned int DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: unsigned integer values.
Definition at line 354 of file LCDD.h.
constant() [7/10]
template<> long DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: long values.
Definition at line 359 of file LCDD.h.
constant() [8/10]
template<> unsigned long DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: unsigned long values.
Definition at line 364 of file LCDD.h.
constant() [9/10]
template<> float DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: float values.
Definition at line 369 of file LCDD.h.
constant() [10/10]
template<> double DD4hep::Geometry::LCDD::constant (const std::string & name) const inline
Typed access to constants: double values.
Definition at line 374 of file LCDD.h.
constantAsDouble()
virtual double DD4hep::Geometry::LCDD::constantAsDouble (const std::string & name) const pure virtual
Typed access to constants: double values.
Implemented in DD4hep::Geometry::LCDDImp.
constantAsLong()
virtual long DD4hep::Geometry::LCDD::constantAsLong (const std::string & name) const pure virtual
Typed access to constants: long values.
Implemented in DD4hep::Geometry::LCDDImp.
constantAsString()
virtual std::string DD4hep::Geometry::LCDD::constantAsString (const std::string & name) const pure virtual
Typed access to constants: access string values.
Implemented in DD4hep::Geometry::LCDDImp.
constants()
virtual const HandleMap& DD4hep::Geometry::LCDD::constants () const pure virtual
Accessor to the map of constants.
Implemented in DD4hep::Geometry::LCDDImp.
declareMotherVolume()
virtual void DD4hep::Geometry::LCDD::declareMotherVolume (const std::string & detector_name, const Volume & vol) pure virtual
Register new mother volume using the detector name.
Miscaneleous accessors to the detexctor descriptionVolumes must be registered/declared PRIOR to be picked up! The method throws an exception if another volume was already declared for this subdetector The method throws an exception if the volume to be registered is invalid.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by create_element().
destroyInstance()
void LCDD::destroyInstance () static
Destroy the instance.
Definition at line 94 of file LCDDImp.cpp.
Referenced by DD4hep::Simulation::Geant4Kernel::terminate(), and DD4hep::Simulation::Geant4Kernel::~Geant4Kernel().
detector()
virtual DetElement DD4hep::Geometry::LCDD::detector (const std::string & name) const pure virtual
Retrieve a field component by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Simulation::Geant4SensitiveDetector::Geant4SensitiveDetector(), DD4hep::SurfaceInstaller::SurfaceInstaller(), and DD4hep::Conditions::Test::TestEnv::TestEnv().
detectors() [1/4]
virtual const HandleMap& DD4hep::Geometry::LCDD::detectors () const pure virtual
Accessor to the map of sub-detectors.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::DDRec::SurfaceManager::initialize().
detectors() [2/4]
virtual const std::vector<DetElement>& DD4hep::Geometry::LCDD::detectors (const std::string & type, bool throw_exc = false) pure virtual
Access a set of subdetectors according to the sensitive type.
Access to predefined caches of subdetectors according to the sensitive type Please note:
The sensitive type of a detector is set in the 'detector constructor'.
Not sensitive detector structures have the name 'passive'
Compounds (ie. nested detectors) are of type 'compound'
If throw_exc is set to true, an exception is thrown if the type is not present. Otherwise an empty detector container is returned.
Implemented in DD4hep::Geometry::LCDDImp.
detectors() [3/4]
virtual std::vector<DetElement> DD4hep::Geometry::LCDD::detectors (const std::string & type1, const std::string & type2, const std::string & type3 = "", const std::string & type4 = "", const std::string & type5 = "") pure virtual
Access a set of subdetectors according to several sensitive types.
Implemented in DD4hep::Geometry::LCDDImp.
detectors() [4/4]
virtual std::vector<DetElement> DD4hep::Geometry::LCDD::detectors (unsigned int includeFlag, unsigned int excludeFlag = 0) const pure virtual
return a vector with all detectors that have all the type properties in includeFlag set but none of the properties given in excludeFlag
Implemented in DD4hep::Geometry::LCDDImp.
detectorTypes()
virtual std::vector<std::string> DD4hep::Geometry::LCDD::detectorTypes () const pure virtual
Access the availible detector types.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::DDRec::SurfaceManager::initialize().
dump()
virtual void DD4hep::Geometry::LCDD::dump () const pure virtual
Stupid legacy method.
Implemented in DD4hep::Geometry::LCDDImp.
endDocument()
virtual void DD4hep::Geometry::LCDD::endDocument () pure virtual
Finalize the geometry.
Implemented in DD4hep::Geometry::LCDDImp.
extension()
template<class T > T* DD4hep::Geometry::LCDD::extension (bool alert = true) const inline
Access extension element by the type.
Definition at line 309 of file LCDD.h.
Referenced by DD4hep::DDRec::createSurfaceManager(), DD4hep::Alignments::GlobalAlignmentWriter::GlobalAlignmentWriter(), DD4hep::Alignments::GlobalAlignmentCache::install(), setup_DDEve(), and DD4hep::Alignments::GlobalAlignmentCache::uninstall().
field() [1/2]
virtual OverlayedField DD4hep::Geometry::LCDD::field () const pure virtual
Return handle to the combined electromagentic field description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::createGearMgr(), and DD4hep::Simulation::Geant4FieldTrackingSetup::execute().
field() [2/2]
virtual CartesianField DD4hep::Geometry::LCDD::field (const std::string & name) const pure virtual
Retrieve a subdetector element by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
fields()
virtual const HandleMap& DD4hep::Geometry::LCDD::fields () const pure virtual
Accessor to the map of field entries, which together form the global field.
Implemented in DD4hep::Geometry::LCDDImp.
fromCompact()
virtual void DD4hep::Geometry::LCDD::fromCompact (const std::string & fname, LCDDBuildType type = BUILD_DEFAULT) pure virtual
Deprecated call (use fromXML): Read compact geometry description or alignment file.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by main().
fromXML() [1/2]
virtual void DD4hep::Geometry::LCDD::fromXML (const std::string & fname, LCDDBuildType type = BUILD_DEFAULT) pure virtual
Read any geometry description or alignment file.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::ROOTUI::fromXML(), DD4hep::ROOTUI::loadConditions(), and DD4hep::Display::LoadXML().
fromXML() [2/2]
virtual void DD4hep::Geometry::LCDD::fromXML (const std::string & fname, UriReader * entity_resolver, LCDDBuildType type = BUILD_DEFAULT) pure virtual
Read any geometry description or alignment file with external XML entity resolution.
Implemented in DD4hep::Geometry::LCDDImp.
getInstance()
LCDD & LCDD::getInstance (void) static
—Factory method----—
Definition at line 87 of file LCDDImp.cpp.
Referenced by DD4hep::Geometry::SimpleGDMLWriter::create(), DD4hep::DDRec::IDDecoder::detectorElement(), DD4hep::Display::Display(), DD4hep::DDRec::IDDecoder::IDDecoder(), DD4hep::DDRec::SurfaceHelper::initialize(), DD4hep::DDRec::SurfaceManager::initialize(), DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Simulation::KernelHandle::KernelHandle(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::LayerAttributes(), and DD4hep::DDRec::MaterialManager::MaterialManager().
header()
virtual Header DD4hep::Geometry::LCDD::header () const pure virtual
Accessor to the map of header entries.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::createGearMgr().
idSpecification()
virtual IDDescriptor DD4hep::Geometry::LCDD::idSpecification (const std::string & name) const pure virtual
Retrieve a id descriptor by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
idSpecifications()
virtual const HandleMap& DD4hep::Geometry::LCDD::idSpecifications () const pure virtual
Accessor to the map of ID specifications.
Implemented in DD4hep::Geometry::LCDDImp.
init()
virtual void DD4hep::Geometry::LCDD::init () pure virtual
Initialize geometry.
Implemented in DD4hep::Geometry::LCDDImp.
invisible()
virtual VisAttr DD4hep::Geometry::LCDD::invisible () const pure virtual
Return handle to "invisible" visualization attributes.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by create_detector().
limitSet()
virtual LimitSet DD4hep::Geometry::LCDD::limitSet (const std::string & name) const pure virtual
Retrieve a limitset by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::Simulation::Geant4Converter::handleRegion(), DD4hep::Geometry::Volume::setAttributes(), DD4hep::Geometry::Volume::setLimitSet(), and DD4hep::Geometry::DetElement::setLimitSet().
limitsets()
virtual const HandleMap& DD4hep::Geometry::LCDD::limitsets () const pure virtual
Accessor to the map of limit settings.
Implemented in DD4hep::Geometry::LCDDImp.
manager()
virtual TGeoManager& DD4hep::Geometry::LCDD::manager () const pure virtual
Access the geometry manager of this instance.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply(), DD4hep::Alignments::GlobalAlignmentCache::commit(), and DD4hep::Display::LoadXML().
material()
virtual Material DD4hep::Geometry::LCDD::material (const std::string & name) const pure virtual
Retrieve a matrial by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::Simulation::Geant4Converter::create(), create_detector(), create_element(), and DD4hep::XML::createPlacedEnvelope().
pickMotherVolume()
virtual Volume DD4hep::Geometry::LCDD::pickMotherVolume (const DetElement & sd) const pure virtual
Access mother volume by detector element.
The method uses the detector element's name for volume identification. Unregistered detectors are hosted by the world volume.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by create_detector(), create_element(), and DD4hep::XML::createPlacedEnvelope().
properties()
virtual Properties& DD4hep::Geometry::LCDD::properties () const pure virtual
Access to properties map.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::Simulation::Geant4Converter::create().
readout()
virtual Readout DD4hep::Geometry::LCDD::readout (const std::string & name) const pure virtual
Retrieve a readout object by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
readouts()
virtual const HandleMap& DD4hep::Geometry::LCDD::readouts () const pure virtual
Accessor to the map of readout structures.
Implemented in DD4hep::Geometry::LCDDImp.
region()
virtual Region DD4hep::Geometry::LCDD::region (const std::string & name) const pure virtual
Retrieve a region object by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::Geometry::Volume::setAttributes(), DD4hep::Geometry::Volume::setRegion(), and DD4hep::Geometry::DetElement::setRegion().
regions()
virtual const HandleMap& DD4hep::Geometry::LCDD::regions () const pure virtual
Accessor to the map of region settings.
Implemented in DD4hep::Geometry::LCDDImp.
removeExtension()
template<class T > T* DD4hep::Geometry::LCDD::removeExtension (bool destroy = true) inline
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
Definition at line 304 of file LCDD.h.
Referenced by DD4hep::Simulation::Geant4Kernel::terminate(), DD4hep::Alignments::GlobalAlignmentCache::uninstall(), DD4hep::Display::~Display(), and DD4hep::Simulation::Geant4Kernel::~Geant4Kernel().
removeUserExtension()
virtual void* DD4hep::Geometry::LCDD::removeUserExtension (const std::type_info & info, bool destroy) protected pure virtual
Remove an existing extension object from the LCDD instance. If not destroyed, the instance is returned.
Implemented in DD4hep::Geometry::LCDDImp.
sensitiveDetector()
virtual SensitiveDetector DD4hep::Geometry::LCDD::sensitiveDetector (const std::string & name) const pure virtual
Retrieve a sensitive detector by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureGeometry(), DD4hep::DDRec::createGearForILD(), DD4hep::View::CreateGeometry(), DD4hep::Simulation::Geant4SensDet::Geant4SensDet(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), DD4hep::Simulation::Geant4SensitiveDetector::Geant4SensitiveDetector(), DD4hep::View::GetGlobalGeometry(), and DD4hep::Display::LoadGeoChildren().
sensitiveDetectors()
virtual const HandleMap& DD4hep::Geometry::LCDD::sensitiveDetectors () const pure virtual
Accessor to the map of sub-detectors.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::Simulation::Geant4Exec::configure().
setHeader()
virtual void DD4hep::Geometry::LCDD::setHeader (Header h) pure virtual
Accessor to the header entry.
Implemented in DD4hep::Geometry::LCDDImp.
trackers()
virtual DetElement DD4hep::Geometry::LCDD::trackers () const pure virtual
Return reference to detector element with all tracker devices.
Implemented in DD4hep::Geometry::LCDDImp.
trackingVolume()
virtual Volume DD4hep::Geometry::LCDD::trackingVolume () const pure virtual
Return handle to the volume containing the tracking devices.
Implemented in DD4hep::Geometry::LCDDImp.
userExtension()
virtual void* DD4hep::Geometry::LCDD::userExtension (const std::type_info & info, bool alert = true) const protected pure virtual
Access an existing extension object from the detector element.
Implemented in DD4hep::Geometry::LCDDImp.
vacuum()
virtual Material DD4hep::Geometry::LCDD::vacuum () const pure virtual
Return handle to material describing vacuum.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by create_detector().
visAttributes() [1/2]
virtual const HandleMap& DD4hep::Geometry::LCDD::visAttributes () const pure virtual
Accessor to the map of visualisation attributes.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by create_detector(), and DD4hep::Geometry::Volume::setVisAttributes().
visAttributes() [2/2]
virtual VisAttr DD4hep::Geometry::LCDD::visAttributes (const std::string & name) const pure virtual
Retrieve a visualization attribute by it's name from the detector description.
Implemented in DD4hep::Geometry::LCDDImp.
volumeManager()
virtual VolumeManager DD4hep::Geometry::LCDD::volumeManager () const pure virtual
Return handle to the VolumeManager.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::DDRec::IDDecoder::IDDecoder().
world()
virtual DetElement DD4hep::Geometry::LCDD::world () const pure virtual
Return reference to the top-most (world) detector element.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureGeometry(), DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), DD4hep::createGearMgr(), DD4hep::DDRec::IDDecoder::detectorElement(), DD4hep::Geometry::DetectorTools::findElement(), DD4hep::Simulation::Geant4VolumeManager::Geant4VolumeManager(), DD4hep::Alignments::GlobalAlignmentCache::get(), DD4hep::DDRec::IDDecoder::IDDecoder(), DD4hep::DDRec::SurfaceHelper::initialize(), DD4hep::Conditions::ConditionsManagerObject::initialize(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::LayerAttributes(), DD4hep::Display::LoadGeoChildren(), DD4hep::DDRec::MaterialManager::MaterialManager(), DD4hep::Alignments::GlobalAlignmentCache::section(), and DD4hep::Conditions::ConditionsManagerObject::~ConditionsManagerObject().
worldVolume()
virtual Volume DD4hep::Geometry::LCDD::worldVolume () const pure virtual
Return handle to the world volume containing everything.
Implemented in DD4hep::Geometry::LCDDImp.
Referenced by DD4hep::ROOTUI::redraw().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/LCDD.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/LCDDImp.cpp