DD4hep: DD4hep::Alignments::Interna::AlignmentContainer Class Reference
DD4hep::Alignments::Interna::AlignmentContainer Class Reference
The data class behind a alignments container handle.
#include <AlignmentsInterna.h>
Public Types
typedef Alignment::key_type key_type
Forward defintion of the key type.
typedef Alignment::iov_type iov_type
Forward definition of the iov type.
typedef std::pair< key_type, std::string > key_value
Forward definition of the mapping type.
typedef std::map< key_type, key_value > Keys
Definition of the keys.
Public Member Functions
AlignmentContainer (Geometry::DetElementObject *parent)
Standard constructor.
virtual ~AlignmentContainer ()
Default destructor.
Alignment get (const std::string &alignment_key, const iov_type &iov)
Access to alignment objects by key and IOV.
Alignment get (key_type hash_key, const iov_type &iov)
Access to alignment objects directly by their hash key.
Alignment get (const std::string &alignment_key, const UserPool &iov)
Access to alignment objects. Only alignments in the pool are accessed.
Alignment get (key_type alignment_key, const UserPool &iov)
Access to alignment objects. Only alignments in the pool are accessed.
void addKey (const std::string &key_value)
Add a new key to the alignments access map.
void addKey (const std::string &key_value, const std::string &data_value)
Add a new key to the alignments access map: Allow for alias if key_val != data_val.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
DetElement detector
The hosting detector element.
Keys keys
Known keys of alignments in this container.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Detailed Description
The data class behind a alignments container handle.
See AlignmentsInterna.cpp for the implementation.
Author
M.Frank
Version
1.0
Definition at line 112 of file AlignmentsInterna.h.
Member Typedef Documentation
iov_type
typedef Alignment::iov_type DD4hep::Alignments::Interna::AlignmentContainer::iov_type
Forward definition of the iov type.
Definition at line 117 of file AlignmentsInterna.h.
key_type
typedef Alignment::key_type DD4hep::Alignments::Interna::AlignmentContainer::key_type
Forward defintion of the key type.
Definition at line 115 of file AlignmentsInterna.h.
key_value
typedef std::pair<key_type, std::string> DD4hep::Alignments::Interna::AlignmentContainer::key_value
Forward definition of the mapping type.
Definition at line 119 of file AlignmentsInterna.h.
Keys
typedef std::map<key_type, key_value> DD4hep::Alignments::Interna::AlignmentContainer::Keys
Definition of the keys.
Definition at line 121 of file AlignmentsInterna.h.
Constructor & Destructor Documentation
AlignmentContainer()
AlignmentContainer::AlignmentContainer (Geometry::DetElementObject * parent)
Standard constructor.
Definition at line 59 of file AlignmentsInterna.cpp.
References DD4hep::InstanceCount::increment().
~AlignmentContainer()
AlignmentContainer::~AlignmentContainer () virtual
Default destructor.
Definition at line 66 of file AlignmentsInterna.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
addKey() [1/2]
void AlignmentContainer::addKey (const std::string & key_value)
Add a new key to the alignments access map.
Definition at line 71 of file AlignmentsInterna.cpp.
References DD4hep::except(), DD4hep::Simulation::hash(), DD4hep::Alignments::Alignment::hashCode(), and keys.
addKey() [2/2]
void AlignmentContainer::addKey (const std::string & key_value, const std::string & data_value)
Add a new key to the alignments access map: Allow for alias if key_val != data_val.
Definition at line 80 of file AlignmentsInterna.cpp.
References DD4hep::except(), DD4hep::Alignments::Alignment::hashCode(), and keys.
get() [1/4]
Alignment AlignmentContainer::get (const std::string & alignment_key, const iov_type & iov)
Access to alignment objects by key and IOV.
Access to alignment objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 90 of file AlignmentsInterna.cpp.
References detector, DD4hep::Alignments::AlignmentsLoader::get(), DD4hep::Simulation::hash(), DD4hep::Alignments::Alignment::hashCode(), keys, and DD4hep::Geometry::DetElement::world().
Referenced by DD4hep::Alignments::Container::get().
get() [2/4]
Alignment AlignmentContainer::get (key_type hash_key, const iov_type & iov)
Access to alignment objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 103 of file AlignmentsInterna.cpp.
References detector, DD4hep::Alignments::AlignmentsLoader::get(), keys, and DD4hep::Geometry::DetElement::world().
get() [3/4]
Alignment AlignmentContainer::get (const std::string & alignment_key, const UserPool & iov)
Access to alignment objects. Only alignments in the pool are accessed.
Access to alignment objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 115 of file AlignmentsInterna.cpp.
References detector, DD4hep::Alignments::AlignmentsLoader::get(), DD4hep::Simulation::hash(), DD4hep::Alignments::Alignment::hashCode(), keys, and DD4hep::Geometry::DetElement::world().
get() [4/4]
Alignment AlignmentContainer::get (key_type alignment_key, const UserPool & iov)
Access to alignment objects. Only alignments in the pool are accessed.
Access to alignment objects directly by their hash key.
Last resort: Assume the key value is globally known:
Definition at line 128 of file AlignmentsInterna.cpp.
References detector, DD4hep::Alignments::AlignmentsLoader::get(), keys, and DD4hep::Geometry::DetElement::world().
Member Data Documentation
detector
DetElement DD4hep::Alignments::Interna::AlignmentContainer::detector
The hosting detector element.
Definition at line 133 of file AlignmentsInterna.h.
Referenced by get().
keys
Keys DD4hep::Alignments::Interna::AlignmentContainer::keys
Known keys of alignments in this container.
Definition at line 149 of file AlignmentsInterna.h.
Referenced by addKey(), and get().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/AlignmentsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/AlignmentsInterna.cpp