DD4hep: DD4hep::DDRec::LayeringExtension Class Reference
DD4hep::DDRec::LayeringExtension Class Reference abstract
#include <LayeringExtension.h>
Public Member Functions
virtual ~LayeringExtension ()
Destructor.
virtual int numberOfLayers () const =0
Access to the total number of layers.
virtual int numberOfSensors (int layerIndex) const =0
Access to the total number of sensors in a given layer index.
virtual Geometry::DetElement layer (int layerIndex) const =0
Access to the layer DetElement for the given index.
virtual const std::vector< Geometry::DetElement > & sensors (int layerIndex) const =0
Access to the sensitive DetElements of a given layer index.
virtual const std::vector< Geometry::DetElement > & absorbers (int layerIndex) const =0
Access to the non-sensitive DetElements of a given layer index.
virtual double totalThickness () const =0
Access the total thickness of the sub detector.
virtual double totalRadiationLength () const =0
Access the total radiation length of the sub detector.
virtual double totalInteractionLength () const =0
Access the total nuclear interaction length of the sub detector.
virtual double thickness (int layerIndex) const =0
Access the total thickness of the layer with the given index.
virtual double radiationLength (int layerIndex) const =0
Access the total radiation length of the layer with the given index.
virtual double interactionLength (int layerIndex) const =0
Access the total nuclear interaction length of the layer with the given index.
virtual double absorberThickness (int layerIndex) const =0
Access the total thickness of all non-sensitive elements of the layer with the given index.
virtual double absorberRadiationLength (int layerIndex) const =0
Access the total radiation length of all non-sensitive elements of the layer with the given index.
virtual double absorberInteractionLength (int layerIndex) const =0
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
virtual double sensorThickness (int layerIndex) const =0
Access the total thickness of all sensitive elements of the layer with the given index.
virtual double sensorRadiationLength (int layerIndex) const =0
Access the total radiation length of all sensitive elements of the layer with the given index.
virtual double sensorInteractionLength (int layerIndex) const =0
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
Protected Member Functions
LayeringExtension ()
Detailed Description
Class describing the layer structure of a sub detector. The information for one layer corresponds to a typical module if, for example, a layer consists of multiple modules.
Definition at line 23 of file LayeringExtension.h.
Constructor & Destructor Documentation
~LayeringExtension()
virtual DD4hep::DDRec::LayeringExtension::~LayeringExtension () inline virtual
Destructor.
Definition at line 26 of file LayeringExtension.h.
References absorberInteractionLength(), absorberRadiationLength(), absorbers(), absorberThickness(), interactionLength(), layer(), numberOfLayers(), numberOfSensors(), radiationLength(), sensorInteractionLength(), sensorRadiationLength(), sensors(), sensorThickness(), thickness(), totalInteractionLength(), totalRadiationLength(), and totalThickness().
LayeringExtension()
DD4hep::DDRec::LayeringExtension::LayeringExtension () inline protected
Definition at line 81 of file LayeringExtension.h.
Member Function Documentation
absorberInteractionLength()
virtual double DD4hep::DDRec::LayeringExtension::absorberInteractionLength (int layerIndex) const pure virtual
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::absorberInteractionLength(), and ~LayeringExtension().
absorberRadiationLength()
virtual double DD4hep::DDRec::LayeringExtension::absorberRadiationLength (int layerIndex) const pure virtual
Access the total radiation length of all non-sensitive elements of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::absorberRadiationLength(), and ~LayeringExtension().
absorbers()
virtual const std::vector<Geometry::DetElement>& DD4hep::DDRec::LayeringExtension::absorbers (int layerIndex) const pure virtual
Access to the non-sensitive DetElements of a given layer index.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::absorbers(), and ~LayeringExtension().
absorberThickness()
virtual double DD4hep::DDRec::LayeringExtension::absorberThickness (int layerIndex) const pure virtual
Access the total thickness of all non-sensitive elements of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::absorberThickness(), and ~LayeringExtension().
interactionLength()
virtual double DD4hep::DDRec::LayeringExtension::interactionLength (int layerIndex) const pure virtual
Access the total nuclear interaction length of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::interactionLength(), and ~LayeringExtension().
layer()
virtual Geometry::DetElement DD4hep::DDRec::LayeringExtension::layer (int layerIndex) const pure virtual
Access to the layer DetElement for the given index.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::layer(), and ~LayeringExtension().
numberOfLayers()
virtual int DD4hep::DDRec::LayeringExtension::numberOfLayers () const pure virtual
Access to the total number of layers.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::numberOfLayers(), and ~LayeringExtension().
numberOfSensors()
virtual int DD4hep::DDRec::LayeringExtension::numberOfSensors (int layerIndex) const pure virtual
Access to the total number of sensors in a given layer index.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::numberOfSensors(), and ~LayeringExtension().
radiationLength()
virtual double DD4hep::DDRec::LayeringExtension::radiationLength (int layerIndex) const pure virtual
Access the total radiation length of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::radiationLength(), and ~LayeringExtension().
sensorInteractionLength()
virtual double DD4hep::DDRec::LayeringExtension::sensorInteractionLength (int layerIndex) const pure virtual
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::sensorInteractionLength(), and ~LayeringExtension().
sensorRadiationLength()
virtual double DD4hep::DDRec::LayeringExtension::sensorRadiationLength (int layerIndex) const pure virtual
Access the total radiation length of all sensitive elements of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::sensorRadiationLength(), and ~LayeringExtension().
sensors()
virtual const std::vector<Geometry::DetElement>& DD4hep::DDRec::LayeringExtension::sensors (int layerIndex) const pure virtual
Access to the sensitive DetElements of a given layer index.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::sensors(), and ~LayeringExtension().
sensorThickness()
virtual double DD4hep::DDRec::LayeringExtension::sensorThickness (int layerIndex) const pure virtual
Access the total thickness of all sensitive elements of the layer with the given index.
Implemented in DD4hep::DDRec::LayeredSubdetector, and DD4hep::DDRec::LayeringExtensionImpl.
Referenced by DD4hep::DDRec::LayeredSubdetector::sensorThickness(), and ~LayeringExtension().
thickness()
virtual double DD4hep::DDRec::LayeringExtension::thickness (int layerIndex) const pure virtual
Access the total thickness of the layer with the given index.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::thickness(), and ~LayeringExtension().
totalInteractionLength()
virtual double DD4hep::DDRec::LayeringExtension::totalInteractionLength () const pure virtual
Access the total nuclear interaction length of the sub detector.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::totalInteractionLength(), and ~LayeringExtension().
totalRadiationLength()
virtual double DD4hep::DDRec::LayeringExtension::totalRadiationLength () const pure virtual
Access the total radiation length of the sub detector.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::totalRadiationLength(), and ~LayeringExtension().
totalThickness()
virtual double DD4hep::DDRec::LayeringExtension::totalThickness () const pure virtual
Access the total thickness of the sub detector.
Implemented in DD4hep::DDRec::LayeringExtensionImpl, and DD4hep::DDRec::LayeredSubdetector.
Referenced by DD4hep::DDRec::LayeredSubdetector::totalThickness(), and ~LayeringExtension().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Extensions/LayeringExtension.h