DD4hep: DD4hep::XML::Collection_t Class Reference
DD4hep::XML::Collection_t Class Reference
DD4hep::XML classes and objects
Class to support the access to collections of XmlNodes (or XmlElements)
#include <XMLElements.h>
Public Member Functions
Collection_t (Handle_t node, const XmlChar *tag)
Constructor over XmlElements with a given tag name.
Collection_t (Handle_t node, const char *tag)
Constructor over XmlElements with a given tag name.
Collection_t (NodeList children)
Constructor over XmlElements in a node list.
Collection_t & reset ()
Reset the collection object to restart the iteration.
size_t size () const
Access the collection size. Avoid this call – sloooow!
void operator++ () const
Operator to advance the collection (pre increment)
void operator++ (int) const
Operator to advance the collection (post increment)
void operator-- () const
Operator to advance the collection (pre decrement)
void operator-- (int) const
Operator to advance the collection (post decrement)
Elt_t current () const
Access to current element.
void throw_loop_exception (const std::exception &e) const
Helper function to throw an exception.
template<class T >
void for_each (T oper) const
Loop processor using function object.
template<class T >
void for_each (const XmlChar *tag_name, T oper) const
Loop processor using function object.
Public Member Functions inherited from DD4hep::XML::Handle_t
Handle_t (Elt_t e=0)
Initializing constructor.
Elt_t operator-> () const
Direct access to the XmlElement using the operator->
operator Elt_t () const
Direct access to the XmlElement by dereferencing.
Elt_t ptr () const
Direct access to the XmlElement by function.
Handle_t clone (XmlDocument *new_doc) const
Clone the DOMelement - with the option of a deep copy.
const XmlChar * rawTag () const
Unicode text access to the element's tag. Tis must be wrong ....
const XmlChar * rawText () const
Unicode text access to the element's text.
const XmlChar * rawValue () const
Unicode text access to the element's value.
std::string tag () const
Text access to the element's tag.
std::string text () const
Text access to the element's text.
std::string value () const
Text access to the element's value.
void setValue (const XmlChar *text) const
Set the element's value.
void setValue (const std::string &text) const
Set the element's value.
void setText (const XmlChar *text) const
Set the element's text.
void setText (const std::string &text) const
Set the element's text.
const XmlChar * attr_name (const Attribute attr) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute attr) const
Access attribute value by the attribute (throws exception if not present)
const XmlChar * attr_value (const XmlChar *attr) const
Access attribute value by the attribute's unicode name (throws exception if not present)
const XmlChar * attr_value_nothrow (const XmlChar *attr) const
Access attribute value by the attribute's unicode name (no exception thrown if not present)
Attribute attr_ptr (const XmlChar *attr) const
Access attribute pointer by the attribute's unicode name (throws exception if not present)
Attribute attr_nothrow (const XmlChar *tag) const
Access attribute pointer by the attribute's unicode name (no exception thrown if not present)
bool hasAttr (const XmlChar *t) const
Check for the existence of a named attribute.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
template<class T >
T attr (const Attribute a) const
Access typed attribute value by the XmlAttr.
void removeAttrs () const
Remove all attributes of this element.
void setAttrs (Handle_t e) const
Set attributes as in argument handle.
template<class T >
T attr (const XmlChar *name) const
Access typed attribute value by it's unicode name.
Attribute setAttr (const XmlChar *t, const XmlChar *v) const
Generic attribute setter with unicode value.
Attribute setAttr (const XmlChar *t, const Attribute v) const
Generic attribute setter with XmlAttr value.
Attribute setAttr (const XmlChar *t, int val) const
Generic attribute setter with integer value.
Attribute setAttr (const XmlChar *t, bool val) const
Generic attribute setter with boolen value.
Attribute setAttr (const XmlChar *t, float val) const
Generic attribute setter with floating point value.
Attribute setAttr (const XmlChar *t, double val) const
Generic attribute setter with double precision floating point value.
Attribute setAttr (const XmlChar *t, const std::string &val) const
Generic attribute setter with string value.
bool hasAttr (const char *t) const
Check for the existence of a named attribute.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
Attribute setAttr (const XmlChar *t, const char *v) const
Generic attribute setter with text value.
Handle_t setRef (const XmlChar *tag, const XmlChar *ref)
Add reference child as a new child node. The obj must have the "name" attribute!
Handle_t setRef (const XmlChar *tag, const std::string &ref)
Add reference child as a new child node. The obj must have the "name" attribute!
bool hasChild (const XmlChar *tag) const
Check the existence of a child with a given tag name.
Handle_t child (const XmlChar *tag, bool throw_exception=true) const
Access a single child by it's tag name (unicode)
NodeList children (const XmlChar *tag) const
Access a group of children identified by the same tag name.
size_t numChildren (const XmlChar *tag, bool throw_exception) const
Access the number of children of this DOM element with a given tag name.
Handle_t remove (Handle_t e) const
Remove a single child node identified by it's handle from the tree of the element.
void removeChildren (const XmlChar *tag) const
Remove children with a given tag name from the DOM node.
void append (Handle_t e) const
Append a DOM element to the current node.
Handle_t parent () const
Access the element's parent element.
unsigned int checksum (unsigned int param, unsigned int(fcn)(unsigned int param, const XmlChar *, size_t)=0) const
Checksum (sub-)tree of a xml document/tree. Default will pick up the adler32 checksum.
template<>
INLINE Attribute attr (const XmlChar *tag_value) const
template<>
INLINE cpXmlChar attr (const XmlChar *tag_value) const
template<>
INLINE bool attr (const XmlChar *tag_value) const
template<>
INLINE int attr (const XmlChar *tag_value) const
template<>
INLINE long attr (const XmlChar *tag_value) const
template<>
INLINE float attr (const XmlChar *tag_value) const
template<>
INLINE double attr (const XmlChar *tag_value) const
Public Attributes
NodeList m_children
Reference to the list of child nodes.
Public Attributes inherited from DD4hep::XML::Handle_t
Elt_t m_node
The pointer to the XmlElement.
Additional Inherited Members
Public Types inherited from DD4hep::XML::Handle_t
typedef XmlElement * Elt_t
Detailed Description
Class to support the access to collections of XmlNodes (or XmlElements)
Author
M.Frank
Version
1.0
Definition at line 556 of file XMLElements.h.
Constructor & Destructor Documentation
Collection_t() [1/3]
Collection_t::Collection_t (Handle_t node, const XmlChar * tag)
Constructor over XmlElements with a given tag name.
Definition at line 1174 of file XMLElements.cpp.
References m_children, DD4hep::XML::Handle_t::m_node, and DD4hep::XML::NodeList::reset().
Collection_t() [2/3]
Collection_t::Collection_t (Handle_t node, const char * tag)
Constructor over XmlElements with a given tag name.
Definition at line 1180 of file XMLElements.cpp.
References m_children, DD4hep::XML::Handle_t::m_node, and DD4hep::XML::NodeList::reset().
Collection_t() [3/3]
Collection_t::Collection_t (NodeList children)
Constructor over XmlElements in a node list.
Definition at line 1186 of file XMLElements.cpp.
References m_children, DD4hep::XML::Handle_t::m_node, and DD4hep::XML::NodeList::reset().
Member Function Documentation
current()
Elt_t DD4hep::XML::Collection_t::current () const inline
Access to current element.
Definition at line 581 of file XMLElements.h.
References e.
for_each() [1/2]
template<class T > void DD4hep::XML::Collection_t::for_each (T oper) const inline
Loop processor using function object.
Definition at line 587 of file XMLElements.h.
Referenced by extract(), for_each(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
for_each() [2/2]
template<class T > void DD4hep::XML::Collection_t::for_each (const XmlChar * tag_name, T oper) const inline
Loop processor using function object.
Definition at line 597 of file XMLElements.h.
References for_each().
operator++() [1/2]
void Collection_t::operator++ () const
Operator to advance the collection (pre increment)
Definition at line 1210 of file XMLElements.cpp.
References _N, e, ELEMENT_NODE_TYPE, m_children, DD4hep::XML::Handle_t::m_node, DD4hep::XML::NodeList::next(), and DD4hep::XML::Handle_t::parent().
operator++() [2/2]
void Collection_t::operator++ (int) const
Operator to advance the collection (post increment)
Definition at line 1232 of file XMLElements.cpp.
operator--() [1/2]
void Collection_t::operator-- () const
Operator to advance the collection (pre decrement)
Definition at line 1221 of file XMLElements.cpp.
References _N, e, ELEMENT_NODE_TYPE, m_children, DD4hep::XML::Handle_t::m_node, DD4hep::XML::Handle_t::parent(), and DD4hep::XML::NodeList::previous().
operator--() [2/2]
void Collection_t::operator-- (int) const
Operator to advance the collection (post decrement)
Definition at line 1236 of file XMLElements.cpp.
reset()
Collection_t & Collection_t::reset ()
Reset the collection object to restart the iteration.
Definition at line 1192 of file XMLElements.cpp.
References m_children, DD4hep::XML::Handle_t::m_node, and DD4hep::XML::NodeList::reset().
Referenced by create_detector().
size()
size_t Collection_t::size () const
Access the collection size. Avoid this call – sloooow!
Definition at line 1198 of file XMLElements.cpp.
References DD4hep::XML::Handle_t::Handle_t(), m_children, DD4hep::XML::NodeList::m_node, and DD4hep::XML::NodeList::m_tag.
throw_loop_exception()
void Collection_t::throw_loop_exception (const std::exception & e) const
Helper function to throw an exception.
Definition at line 1203 of file XMLElements.cpp.
References DD4hep::XML::Handle_t::m_node, and DD4hep::XML::Handle_t::tag().
Member Data Documentation
m_children
NodeList DD4hep::XML::Collection_t::m_children
Reference to the list of child nodes.
Definition at line 559 of file XMLElements.h.
Referenced by Collection_t(), operator++(), operator--(), reset(), and size().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp