DD4hep: DD4hep::Simulation::Geant4ParticleHandle Class Reference
DD4hep::Simulation::Geant4ParticleHandle Class Reference
DD4hep::Simulation components, classes and objects
Data structure to access derived MC particle information.
#include <Geant4Particle.h>
Public Types
typedef ROOT::Math::PxPyPzM4D< double > FourVector
typedef ROOT::Math::Cartesian3D< double > ThreeVector
Public Member Functions
Geant4ParticleHandle (Geant4Particle *part)
Default constructor.
Geant4ParticleHandle (const Geant4ParticleHandle &h)
Initializing constructor.
Geant4ParticleHandle & operator= (Geant4Particle *part)
Assignment operator.
Geant4Particle * operator-> () const
Overloaded -> operator to access particle details.
operator Geant4Particle * () const
Conversion operator to pointer.
size_t numParent () const
Accessor to the number of particle parents.
size_t numDaughter () const
Accessor to the number of particle daughters.
double momentum2 () const
Scalar particle momentum squared.
double energy () const
Scalar particle energy.
double momentum () const
Scalar particle momentum.
double charge () const
Geant4 charge of the particle.
double mass () const
Geant4 mass of the particle.
double time () const
Geant4 time of the particle.
std::string particleName () const
Access to the Geant4 particle name.
std::string particleType () const
Access to the Geant4 particle type.
std::string processName () const
Access to the creator process name.
std::string processTypeName () const
Access to the creator process type name.
FourVector pxPyPzM () const
Access patricle momentum, energy as 4 vector.
ThreeVector startVertex () const
Access patricle momentum, energy as 4 vector.
ThreeVector endVertex () const
Access patricle momentum, energy as 4 vector.
const G4ParticleDefinition * definition () const
Access the Geant4 particle definition object (expensive!)
void dump1 (int level, const std::string &src, const char *tag) const
Various output formats:
void dump2 (int level, const std::string &src, const char *tag, int g4id, bool inrec) const
Output type 2:+++ "tag" 20 G4: 7 def:0xde4eaa8 [gamma , gamma] reason: 20 E:+3.304035e+01 in record:YES #Par: 1/18 #Dau: 0.
void dumpWithVertex (int level, const std::string &src, const char *tag) const
Output type 3:+++ "tag" ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
void dumpWithMomentum (int level, const std::string &src, const char *tag) const
Output type 3:+++ <tag> ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
void dumpWithMomentumAndVertex (int level, const std::string &src, const char *tag) const
Output type 3:+++ <tag> ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
void dump4 (int level, const std::string &src, const char *tag) const
void offset (int off) const
Handlers.
Protected Attributes
Geant4Particle * particle
Particle pointer.
Detailed Description
Data structure to access derived MC particle information.
Author
M.Frank
Version
1.0
Definition at line 160 of file Geant4Particle.h.
Member Typedef Documentation
FourVector
typedef ROOT::Math::PxPyPzM4D<double> DD4hep::Simulation::Geant4ParticleHandle::FourVector
Definition at line 162 of file Geant4Particle.h.
ThreeVector
typedef ROOT::Math::Cartesian3D<double> DD4hep::Simulation::Geant4ParticleHandle::ThreeVector
Definition at line 163 of file Geant4Particle.h.
Constructor & Destructor Documentation
Geant4ParticleHandle() [1/2]
DD4hep::Simulation::Geant4ParticleHandle::Geant4ParticleHandle (Geant4Particle * part) inline
Default constructor.
Initializing constructor.
Definition at line 235 of file Geant4Particle.h.
Geant4ParticleHandle() [2/2]
DD4hep::Simulation::Geant4ParticleHandle::Geant4ParticleHandle (const Geant4ParticleHandle & h) inline
Initializing constructor.
Definition at line 230 of file Geant4Particle.h.
Member Function Documentation
charge()
double DD4hep::Simulation::Geant4ParticleHandle::charge () const inline
Geant4 charge of the particle.
Definition at line 189 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::charge.
Referenced by createG4Primary().
definition()
const G4ParticleDefinition * Geant4ParticleHandle::definition () const
Access the Geant4 particle definition object (expensive!)
Definition at line 154 of file Geant4Particle.cpp.
Referenced by createG4Primary(), DD4hep::Simulation::Geant4ParticleHandler::rebaseSimulatedTracks(), and DD4hep::Simulation::Geant4Output2LCIO::saveParticles().
dump1()
void Geant4ParticleHandle::dump1 (int level, const std::string & src, const char * tag) const
Various output formats:
Output type 1:+++ <tag> 10 def:0xde4eaa8 [gamma , gamma] reason: 20 E:+1.017927e+03 #Par: 1/4 #Dau: 2.
Output type 1:+++ "tag" 10 def:0xde4eaa8 [gamma , gamma] reason: 20 E:+1.017927e+03 #Par: 1/4 #Dau: 2
Definition at line 236 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, energy(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4Particle::parents, particleName(), particleType(), DD4hep::printout(), and DD4hep::Simulation::Geant4Particle::reason.
Referenced by DD4hep::Simulation::mergeInteractions().
dump2()
void Geant4ParticleHandle::dump2 (int level, const std::string & src, const char * tag, int g4id, bool inrec) const
Output type 2:+++ "tag" 20 G4: 7 def:0xde4eaa8 [gamma , gamma] reason: 20 E:+3.304035e+01 in record:YES #Par: 1/18 #Dau: 0.
Output type 2:+++ <tag> 20 G4: 7 def:0xde4eaa8 [gamma , gamma] reason: 20 E:+3.304035e+01 in record:YES #Par: 1/18 #Dau: 0.
Definition at line 260 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, energy(), DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4Particle::parents, particleName(), particleType(), DD4hep::printout(), DD4hep::Simulation::Geant4Particle::reason, and DD4hep::yes_no().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::end().
dump4()
void Geant4ParticleHandle::dump4 (int level, const std::string & src, const char * tag) const
Definition at line 347 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, energy(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_CREATED_CALORIMETER_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, DD4hep::Simulation::G4PARTICLE_HAS_SECONDARIES, DD4hep::Simulation::G4PARTICLE_KEEP_PARENT, DD4hep::Simulation::G4PARTICLE_KEEP_PROCESS, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::G4PARTICLE_SIM_BACKSCATTER, DD4hep::Simulation::G4PARTICLE_SIM_CREATED, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_CALO, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_TRACKER, DD4hep::Simulation::G4PARTICLE_SIM_LEFT_DETECTOR, DD4hep::Simulation::G4PARTICLE_SIM_PARENT_RADIATED, DD4hep::Simulation::G4PARTICLE_SIM_STOPPED, DD4hep::Simulation::Geant4Particle::id, DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::Simulation::Geant4Particle::mask, numParent(), DD4hep::Simulation::Geant4Particle::parents, particleName(), DD4hep::printout(), DD4hep::Simulation::Geant4Particle::process, processName(), processTypeName(), DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4Particle::status, and DD4hep::yes_no().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::dumpMap().
dumpWithMomentum()
void Geant4ParticleHandle::dumpWithMomentum (int level, const std::string & src, const char * tag) const
Output type 3:+++ <tag> ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
Definition at line 303 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4Particle::id, dd4hep::MeV, dd4hep::ns, DD4hep::Simulation::Geant4Particle::parents, particleName(), DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::printout(), DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::Simulation::Geant4Particle::status, and DD4hep::Simulation::Geant4Particle::time.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::checkConsistency(), and DD4hep::Simulation::generatePrimaries().
dumpWithMomentumAndVertex()
void Geant4ParticleHandle::dumpWithMomentumAndVertex (int level, const std::string & src, const char * tag) const
Output type 3:+++ <tag> ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
Definition at line 325 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4Particle::id, dd4hep::MeV, dd4hep::mm, DD4hep::Simulation::Geant4Particle::parents, particleName(), DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::printout(), DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
Referenced by DD4hep::Simulation::Geant4InputAction::operator()().
dumpWithVertex()
void Geant4ParticleHandle::dumpWithVertex (int level, const std::string & src, const char * tag) const
Output type 3:+++ "tag" ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
Output type 3:+++ <tag> ID: 0 e- status:00000014 type: 11 Vertex:(+0.00e+00,+0.00e+00,+0.00e+00) [mm] time: +0.00e+00 [ns] #Par: 0 #Dau: 4.
Definition at line 280 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4Particle::id, dd4hep::mm, dd4hep::ns, DD4hep::Simulation::Geant4Particle::parents, particleName(), DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::printout(), DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::time, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::end(), and DD4hep::Simulation::Geant4ParticleGenerator::printInteraction().
endVertex()
ROOT::Math::Cartesian3D< double > DD4hep::Simulation::Geant4ParticleHandle::endVertex () const inline
Access patricle momentum, energy as 4 vector.
Definition at line 273 of file Geant4Particle.h.
References particle, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, and DD4hep::Simulation::Geant4Particle::vez.
energy()
double DD4hep::Simulation::Geant4ParticleHandle::energy () const inline
Scalar particle energy.
Definition at line 279 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::mass, particle, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, and v.
Referenced by dump1(), dump2(), dump4(), getRelevant(), DD4hep::Simulation::Geant4DataDump::print(), and DD4hep::Simulation::Geant4ParticlePrint::printParticle().
mass()
double DD4hep::Simulation::Geant4ParticleHandle::mass () const inline
Geant4 mass of the particle.
Definition at line 191 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::mass.
momentum()
double DD4hep::Simulation::Geant4ParticleHandle::momentum () const inline
Scalar particle momentum.
Definition at line 187 of file Geant4Particle.h.
momentum2()
double DD4hep::Simulation::Geant4ParticleHandle::momentum2 () const inline
Scalar particle momentum squared.
Definition at line 286 of file Geant4Particle.h.
References particle, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, and DD4hep::Simulation::Geant4Particle::psz.
numDaughter()
size_t DD4hep::Simulation::Geant4ParticleHandle::numDaughter () const inline
Accessor to the number of particle daughters.
Definition at line 257 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::daughters, and particle.
numParent()
size_t DD4hep::Simulation::Geant4ParticleHandle::numParent () const inline
Accessor to the number of particle parents.
Definition at line 253 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::parents, and particle.
Referenced by dump4(), and DD4hep::Simulation::Geant4ParticlePrint::printParticle().
offset()
void Geant4ParticleHandle::offset (int off) const
Handlers.
Offset all particle identifiers (id, parents, daughters) by a constant number.
Offset all particle identifiers (id, parents, daughters) by a constant number
Definition at line 219 of file Geant4Particle.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4Particle::id, and DD4hep::Simulation::Geant4Particle::parents.
Referenced by rebaseParticles().
operator Geant4Particle *()
DD4hep::Simulation::Geant4ParticleHandle::operator Geant4Particle * () const inline
Conversion operator to pointer.
Definition at line 249 of file Geant4Particle.h.
References particle.
operator->()
Geant4Particle * DD4hep::Simulation::Geant4ParticleHandle::operator-> () const inline
Overloaded -> operator to access particle details.
Definition at line 240 of file Geant4Particle.h.
References particle.
operator=()
Geant4ParticleHandle & DD4hep::Simulation::Geant4ParticleHandle::operator= (Geant4Particle * part) inline
Assignment operator.
Definition at line 244 of file Geant4Particle.h.
References particle.
particleName()
std::string Geant4ParticleHandle::particleName () const
Access to the Geant4 particle name.
Definition at line 166 of file Geant4Particle.cpp.
Referenced by dump1(), dump2(), dump4(), dumpWithMomentum(), dumpWithMomentumAndVertex(), dumpWithVertex(), and DD4hep::Simulation::Geant4ParticlePrint::printParticle().
particleType()
std::string Geant4ParticleHandle::particleType () const
Access to the Geant4 particle type.
Definition at line 183 of file Geant4Particle.cpp.
Referenced by dump1(), and dump2().
processName()
std::string Geant4ParticleHandle::processName () const
Access to the creator process name.
Definition at line 200 of file Geant4Particle.cpp.
References DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, and DD4hep::Simulation::G4PARTICLE_PRIMARY.
Referenced by dump4(), and DD4hep::Simulation::Geant4ParticlePrint::printParticle().
processTypeName()
std::string Geant4ParticleHandle::processTypeName () const
Access to the creator process type name.
Definition at line 211 of file Geant4Particle.cpp.
Referenced by dump4(), and DD4hep::Simulation::Geant4ParticlePrint::printParticle().
pxPyPzM()
ROOT::Math::PxPyPzM4D< double > DD4hep::Simulation::Geant4ParticleHandle::pxPyPzM () const inline
Access patricle momentum, energy as 4 vector.
Definition at line 261 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::mass, particle, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, and DD4hep::Simulation::Geant4Particle::psz.
startVertex()
ROOT::Math::Cartesian3D< double > DD4hep::Simulation::Geant4ParticleHandle::startVertex () const inline
Access patricle momentum, energy as 4 vector.
Definition at line 267 of file Geant4Particle.h.
References particle, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
time()
double DD4hep::Simulation::Geant4ParticleHandle::time () const inline
Geant4 time of the particle.
Definition at line 193 of file Geant4Particle.h.
References DD4hep::Simulation::Geant4Particle::time.
Member Data Documentation
particle
Geant4Particle* DD4hep::Simulation::Geant4ParticleHandle::particle protected
Particle pointer.
Definition at line 166 of file Geant4Particle.h.
Referenced by endVertex(), energy(), momentum2(), numDaughter(), numParent(), operator Geant4Particle *(), operator->(), operator=(), pxPyPzM(), and startVertex().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Particle.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Particle.cpp