DD4hep: DD4hep: DD4hep::XML::RefElement Class Reference
DD4hep::XML::RefElement Class Reference
[DD4hep::XML classes and objects]
User abstraction class to manipulate named XML elements (references) within a document.
#include <XMLElements.h>
Public Member Functions
RefElement (const Handle_t &e)
Construction from existing object handle.
RefElement (const RefElement &e)
Copy constructor.
RefElement (const Document &d, const XmlChar *type, const XmlChar *name)
Initializing constructor to create a new XMLElement and add it to the document.
RefElement & operator= (const RefElement &e)
Assignment operator.
const XmlChar * name () const
Access the object's name in unicode.
const XmlChar * refName () const
Access the object's reference name in unicode (same as name).
void setName (const XmlChar *new_name)
Change/set the object's name.
Public Attributes
Attribute m_name
Attribute holding thre name.
Detailed Description
User abstraction class to manipulate named XML elements (references) within a document.
User class encapsulating a DOM element which can be referenced. Like the Element, but the "name" attribute is required. The reference then has the corresponding "ref" attribute. The value of "name" and "ref" must match to establish the reference.
Author:
M.Frank
Version:
1.0
Definition at line 844 of file XMLElements.h.
Constructor & Destructor Documentation
RefElement::RefElement (const Handle_t & e)
Construction from existing object handle.
Definition at line 1141 of file XMLElements.cpp.
References _U, DD4hep::XML::Element::getAttr(), DD4hep::XML::Element::m_element, and m_name.
RefElement::RefElement (const RefElement & e)
Copy constructor.
Definition at line 1147 of file XMLElements.cpp.
RefElement::RefElement (const Document & d, const XmlChar * type, const XmlChar * name)
Initializing constructor to create a new XMLElement and add it to the document.
Definition at line 1135 of file XMLElements.cpp.
References _U, m_name, and DD4hep::XML::Element::setAttr().
Member Function Documentation
const XmlChar * RefElement::name () const
Access the object's name in unicode.
Definition at line 1157 of file XMLElements.cpp.
References DD4hep::XML::Element::m_element, m_name, and DD4hep::XML::Handle_t::tag().
RefElement & RefElement::operator= (const RefElement & e)
Assignment operator.
Reimplemented from DD4hep::XML::Element.
Definition at line 1152 of file XMLElements.cpp.
References DD4hep::XML::Element::m_element.
const XmlChar * RefElement::refName () const
Access the object's reference name in unicode (same as name).
Definition at line 1163 of file XMLElements.cpp.
References DD4hep::XML::Element::m_element, m_name, and DD4hep::XML::Handle_t::tag().
void RefElement::setName (const XmlChar * new_name)
Change/set the object's name.
Definition at line 1169 of file XMLElements.cpp.
References _U, and DD4hep::XML::Element::setAttr().
Member Data Documentation
Attribute DD4hep::XML::RefElement::m_name
Attribute holding thre name.
Definition at line 847 of file XMLElements.h.
Referenced by name(), RefElement(), and refName().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp