DD4hep: DD4hep: DD4hep::Alignments::AlignmentDecorator< T > Class Template Reference
DD4hep::Alignments::AlignmentDecorator< T > Class Template Reference
[DDCond: DD4hep Detector Conditions components, classes and functions]
#include <AlignmentData.h>
Public Types
typedef AlignmentData::PlacedVolume PlacedVolume
Forward definition of the geometry placement.
typedef AlignmentData::NodeList NodeList
Forward definition of the nodelist leading to the world.
typedef AlignmentData::Delta Delta
Forward definition of the alignment delta data.
Public Member Functions
AlignmentDecorator ()
Default constructor.
AlignmentDecorator (const AlignmentDecorator &c)
Copy constructor.
template<typename Q >
AlignmentDecorator (Q q)
Special constructors.
~AlignmentDecorator ()
Default destructor.
const AlignmentData & data () const
Data accessor.
DetElement detector () const
Access to the DetElement node.
PlacedVolume placement () const
Access the placement of this node.
PlacedVolume detectorPlacement () const
Access the placement of the DetElement node.
const Transform3D & localToWorld () const
Access the alignment/placement matrix with respect to the world.
const TGeoHMatrix & worldTransformation () const
Create cached matrix to transform to world coordinates.
const TGeoHMatrix & detectorTransformation () const
Create cached matrix to transform to detector coordinates.
void localToWorld (const Position &local, Position &global) const
Transformation from local coordinates of the placed volume to the world system.
void localToWorld (const Double_t local[3], Double_t global[3]) const
Transformation from local coordinates of the placed volume to the world system.
void localToDetector (const Position &local, Position &det) const
Transformation from local coordinates of the placed volume to the detector system.
void localToDetector (const Double_t local[3], Double_t det[3]) const
Transformation from local coordinates of the placed volume to the detector system.
void worldToLocal (const Position &global, Position &local) const
Transformation from world coordinates of the local placed volume coordinates.
void worldToLocal (const Double_t global[3], Double_t local[3]) const
Transformation from world coordinates of the local placed volume coordinates.
void detectorToLocal (const Position &det, Position &local) const
Transformation from world coordinates of the local placed volume coordinates.
void detectorToLocal (const Double_t det[3], Double_t local[3]) const
Transformation from world coordinates of the local placed volume coordinates.
const Alignment & nominal () const
Access the currently applied alignment/placement matrix (mother to daughter).
const Delta & delta () const
Access the currently applied correction matrix (delta) (mother to daughter).
void setDelta (const Delta &del)
Set the delta alignment information.
void setDelta (const Position &translation)
Set the delta alignment if only a single translation.
void setDelta (const RotationZYX &rotation)
Set the delta alignment if only a single rotation.
void setDelta (const Position &translation, RotationZYX &rotation)
Set the delta alignment as a composite of a translation and a rotation.
void setDeltaPivot (const Translation3D &pivot, const RotationZYX &rotation)
Set the delta alignment if only a single rotation around a pivot point.
void setDeltaPivot (const Position &translation, const Translation3D &pivot, const RotationZYX &rotation)
Set the delta alignment if a translation and a rotation around pivot.
Detailed Description
template<typename T>
class DD4hep::Alignments::AlignmentDecorator< T >
Author:
M.Frank
Version:
1.0
Definition at line 228 of file AlignmentData.h.
Member Typedef Documentation
template<typename T > typedef AlignmentData::Delta DD4hep::Alignments::AlignmentDecorator< T >::Delta
Forward definition of the alignment delta data.
Definition at line 235 of file AlignmentData.h.
template<typename T > typedef AlignmentData::NodeList DD4hep::Alignments::AlignmentDecorator< T >::NodeList
Forward definition of the nodelist leading to the world.
Definition at line 233 of file AlignmentData.h.
template<typename T > typedef AlignmentData::PlacedVolume DD4hep::Alignments::AlignmentDecorator< T >::PlacedVolume
Forward definition of the geometry placement.
Definition at line 231 of file AlignmentData.h.
Constructor & Destructor Documentation
template<typename T > DD4hep::Alignments::AlignmentDecorator< T >::AlignmentDecorator () [inline]
Default constructor.
Definition at line 350 of file AlignmentData.h.
template<typename T > DD4hep::Alignments::AlignmentDecorator< T >::AlignmentDecorator (const AlignmentDecorator< T > & c) [inline]
Copy constructor.
Definition at line 354 of file AlignmentData.h.
template<typename T > template<typename Q > DD4hep::Alignments::AlignmentDecorator< T >::AlignmentDecorator (Q q) [inline]
Special constructors.
Definition at line 242 of file AlignmentData.h.
template<typename T > DD4hep::Alignments::AlignmentDecorator< T >::~AlignmentDecorator () [inline]
Default destructor.
Definition at line 244 of file AlignmentData.h.
Member Function Documentation
template<typename T > const AlignmentData& DD4hep::Alignments::AlignmentDecorator< T >::data () const [inline]
Data accessor.
Definition at line 247 of file AlignmentData.h.
Referenced by DD4hep::Alignments::AlignmentDecorator< T >::delta(), DD4hep::Alignments::AlignmentDecorator< T >::detector(), DD4hep::Alignments::AlignmentDecorator< T >::detectorPlacement(), DD4hep::Alignments::AlignmentDecorator< T >::detectorToLocal(), DD4hep::Alignments::AlignmentDecorator< T >::detectorTransformation(), DD4hep::Alignments::AlignmentDecorator< T >::localToDetector(), DD4hep::Alignments::AlignmentDecorator< T >::localToWorld(), DD4hep::Alignments::AlignmentDecorator< T >::nominal(), DD4hep::Alignments::AlignmentDecorator< T >::placement(), DD4hep::Alignments::AlignmentDecorator< T >::setDelta(), DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot(), DD4hep::Alignments::AlignmentDecorator< T >::worldToLocal(), and DD4hep::Alignments::AlignmentDecorator< T >::worldTransformation().
template<typename T > const Delta& DD4hep::Alignments::AlignmentDecorator< T >::delta () const [inline]
Access the currently applied correction matrix (delta) (mother to daughter).
Definition at line 300 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::delta.
template<typename T > DetElement DD4hep::Alignments::AlignmentDecorator< T >::detector () const [inline]
Access to the DetElement node.
Definition at line 249 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::detector.
template<typename T > PlacedVolume DD4hep::Alignments::AlignmentDecorator< T >::detectorPlacement () const [inline]
Access the placement of the DetElement node.
Definition at line 255 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::detector.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::detectorToLocal (const Double_t det[3], Double_t local[3]) const [inline]
Transformation from world coordinates of the local placed volume coordinates.
Definition at line 293 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::detectorToLocal().
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::detectorToLocal (const Position & det, Position & local) const [inline]
Transformation from world coordinates of the local placed volume coordinates.
Definition at line 290 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::detectorToLocal().
template<typename T > const TGeoHMatrix& DD4hep::Alignments::AlignmentDecorator< T >::detectorTransformation () const [inline]
Create cached matrix to transform to detector coordinates.
Definition at line 265 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::detectorTransformation().
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::localToDetector (const Double_t local[3], Double_t det[3]) const [inline]
Transformation from local coordinates of the placed volume to the detector system.
Definition at line 279 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::localToDetector().
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::localToDetector (const Position & local, Position & det) const [inline]
Transformation from local coordinates of the placed volume to the detector system.
Definition at line 276 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::localToDetector().
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::localToWorld (const Double_t local[3], Double_t global[3]) const [inline]
Transformation from local coordinates of the placed volume to the world system.
Definition at line 272 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::localToWorld().
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::localToWorld (const Position & local, Position & global) const [inline]
Transformation from local coordinates of the placed volume to the world system.
Definition at line 269 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::localToWorld().
template<typename T > const Transform3D& DD4hep::Alignments::AlignmentDecorator< T >::localToWorld () const [inline]
Access the alignment/placement matrix with respect to the world.
Definition at line 259 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::trToWorld.
template<typename T > const Alignment& DD4hep::Alignments::AlignmentDecorator< T >::nominal () const [inline]
Access the currently applied alignment/placement matrix (mother to daughter).
Definition at line 297 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::detector.
template<typename T > PlacedVolume DD4hep::Alignments::AlignmentDecorator< T >::placement () const [inline]
Access the placement of this node.
Definition at line 252 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::placement.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::setDelta (const Position & translation, RotationZYX & rotation) [inline]
Set the delta alignment as a composite of a translation and a rotation.
Definition at line 321 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::Delta::flags, DD4hep::Alignments::Delta::HAVE_ROTATION, DD4hep::Alignments::Delta::HAVE_TRANSLATION, DD4hep::Alignments::Delta::rotation, and DD4hep::Alignments::Delta::translation.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::setDelta (const RotationZYX & rotation) [inline]
Set the delta alignment if only a single rotation.
Definition at line 315 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::Delta::flags, DD4hep::Alignments::Delta::HAVE_ROTATION, and DD4hep::Alignments::Delta::rotation.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::setDelta (const Position & translation) [inline]
Set the delta alignment if only a single translation.
Definition at line 309 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::Delta::flags, DD4hep::Alignments::Delta::HAVE_TRANSLATION, and DD4hep::Alignments::Delta::translation.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::setDelta (const Delta & del) [inline]
Set the delta alignment information.
Definition at line 304 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::delta.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot (const Position & translation, const Translation3D & pivot, const RotationZYX & rotation) [inline]
Set the delta alignment if a translation and a rotation around pivot.
Definition at line 337 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::Delta::flags, DD4hep::Alignments::Delta::HAVE_PIVOT, DD4hep::Alignments::Delta::HAVE_ROTATION, DD4hep::Alignments::Delta::HAVE_TRANSLATION, DD4hep::Alignments::Delta::pivot, DD4hep::Alignments::Delta::rotation, and DD4hep::Alignments::Delta::translation.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::setDeltaPivot (const Translation3D & pivot, const RotationZYX & rotation) [inline]
Set the delta alignment if only a single rotation around a pivot point.
Definition at line 329 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::Delta::flags, DD4hep::Alignments::Delta::HAVE_PIVOT, DD4hep::Alignments::Delta::HAVE_ROTATION, DD4hep::Alignments::Delta::pivot, and DD4hep::Alignments::Delta::rotation.
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::worldToLocal (const Double_t global[3], Double_t local[3]) const [inline]
Transformation from world coordinates of the local placed volume coordinates.
Definition at line 286 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::worldToLocal().
template<typename T > void DD4hep::Alignments::AlignmentDecorator< T >::worldToLocal (const Position & global, Position & local) const [inline]
Transformation from world coordinates of the local placed volume coordinates.
Definition at line 283 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::worldToLocal().
template<typename T > const TGeoHMatrix& DD4hep::Alignments::AlignmentDecorator< T >::worldTransformation () const [inline]
Create cached matrix to transform to world coordinates.
Definition at line 262 of file AlignmentData.h.
References DD4hep::Alignments::AlignmentDecorator< T >::data(), and DD4hep::Alignments::AlignmentData::worldTransformation().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/AlignmentData.h