DD4hep: DD4hep::Geometry::DetElement Class Reference
DD4hep::Geometry::DetElement Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing a detector element.
#include <Detector.h>
Public Types
enum CopyParameters {
COPY_NONE = 0, COPY_PLACEMENT = 1 << 0, COPY_PARENT = 1 << 1, COPY_ALIGNMENT = 1 << 2,
LAST
}
enum UpdateParam {
CONDITIONS_CHANGED = 1<<0, PLACEMENT_CHANGED = 1<<1, SOMETHING_CHANGED = 1<<2, PLACEMENT_ELEMENT = 1<<20,
PLACEMENT_HIGHEST = 1<<21, PLACEMENT_DETECTOR = 1<<22, PLACEMENT_NONE
}
typedef DetElementObject Object
Internal object type.
typedef Handle< DetElementObject > RefObject
Definition of the base handle type.
typedef DetElement Parent
typedef Alignments::Alignment Alignment
typedef void *(* copy_t) (const void *, DetElement)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< std::string, DetElement > Children
typedef std::map< const std::type_info *, void * > Extensions
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
void check (bool condition, const std::string &msg) const
Internal assert function to check conditions.
DetElement ()
Default constructor.
DetElement (Object *object_ptr)
Constructor to hold handled object.
DetElement (Object *data, const std::string &name, const std::string &type)
Clone constructor.
template<typename Q >
DetElement (const Handle< Q > &e)
Templated constructor for handle conversions.
DetElement (const DetElement &e)=default
Constructor to copy handle.
DetElement (const std::string &name, const std::string &type, int id)
Constructor for a new subdetector element.
DetElement (const std::string &name, int id)
Constructor for a new subdetector element.
DetElement (DetElement parent, const std::string &name, int id)
Constructor for a new subdetector element.
Object & _data () const
Additional data accessor.
bool operator< (const DetElement e) const
Operator less to insert into a map.
bool operator== (const DetElement e) const
Equality operator.
DetElement & operator= (const DetElement &e)=default
Assignment operator.
DetElement clone (const std::string &new_name) const
Clone (Deep copy) the DetElement structure with a new name.
DetElement clone (const std::string &new_name, int new_id) const
Clone (Deep copy) the DetElement structure with a new name and new identifier.
template<typename IFACE , typename CONCRETE >
IFACE * addExtension (CONCRETE *c) const
Extend the detector element with an arbitrary structure accessible by the type.
template<typename IFACE >
IFACE * extension () const
Access extension element by the type.
template<typename Q , typename T >
void callAtUpdate (unsigned int typ, Q *pointer, void(T::*pmf)(unsigned long typ, DetElement &det, void *opt_par)) const
Extend the detector element with an arbitrary callback.
void removeAtUpdate (unsigned int type, void *pointer) const
Remove callback from object.
int id () const
Get the detector identifier.
DetElement & setCombineHits (bool value, SensitiveDetector &sens)
Setter: Combine hits attribute.
bool combineHits () const
Getter: Combine hits attribute.
std::string type () const
Access detector type (structure, tracker, calorimeter, etc.).
DetElement & setType (const std::string &typ)
Set detector type (structure, tracker, calorimeter, etc.).
unsigned int typeFlag () const
DetElement & setTypeFlag (unsigned int types)
Set the flag word encoding detector types (ideally use DD4hep::DetType for encoding)
unsigned int key () const
Access hash key of this detector element (Only valid once geometry is closed!)
int level () const
Access the hierarchical level of the detector element (Only valid once geometry is closed!)
const std::string & path () const
Path of the detector element (not necessarily identical to placement path!)
const std::string & placementPath () const
Access to the full path to the placed object.
DetElement & setAttributes (const LCDD &lcdd, const Volume &volume, const std::string &region, const std::string &limits, const std::string &vis)
Set all attributes in one go.
DetElement & setVisAttributes (const LCDD &lcdd, const std::string &name, const Volume &volume)
Set Visualization attributes to the detector element.
DetElement & setRegion (const LCDD &lcdd, const std::string &name, const Volume &volume)
Set the regional attributes to the detector element.
DetElement & setLimitSet (const LCDD &lcdd, const std::string &name, const Volume &volume)
Set the limits to the detector element.
Volume volume () const
Access to the logical volume of the detector element's placement.
PlacedVolume placement () const
Access to the physical volume of this detector element.
DetElement & setPlacement (const PlacedVolume &volume)
Set the physical volumes of the detector element.
VolumeID volumeID () const
The cached VolumeID of this subdetector element.
DetElement & add (DetElement sub_element)
Add new child to the detector structure.
const Children & children () const
Access to the list of children.
DetElement child (const std::string &name) const
Access to individual children by name.
DetElement parent () const
Access to the detector elements's parent.
DetElement world () const
Access to the world object. Only possible once the geometry is closed.
bool hasConditions () const
Check if this DetElement has time dependent Conditions attached.
bool hasAlignments () const
Check if this DetElement has time dependent Alignments attached.
Alignment nominal () const
Access to the constant ideal (nominal) alignment information.
Alignment survey () const
Access to the constant survey alignment information.
const TGeoHMatrix & worldTransformation () const
Set detector element for reference transformations. Will delete existing reference trafo.
const TGeoHMatrix & parentTransformation () const
Create cached matrix to transform to parent coordinates.
bool localToWorld (const Position &local, Position &global) const
Create cached matrix to transform to reference coordinates.
bool localToParent (const Position &local, Position &parent) const
Transformation from local coordinates of the placed volume to the parent system.
bool worldToLocal (const Position &global, Position &local) const
Transformation from local coordinates of the placed volume to arbitrary parent system set as reference.
bool parentToLocal (const Position &parent, Position &local) const
Transformation from world coordinates of the local placed volume coordinates.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Protected Member Functions
void * i_addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor) const
Add an extension object to the detector element.
void * i_extension (const std::type_info &info) const
Access an existing extension object from the detector element.
void i_addUpdateCall (unsigned int callback_type, const Callback &callback) const
Internal call to extend the detector element with an arbitrary structure accessible by the type.
Static Protected Member Functions
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
template<typename T >
static void * _copy (const void *ptr, DetElement elt)
Templated copy constructor.
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing a detector element.
Detector elements (class DetElement are entities which represent subdetectors or sizable parts of a subdetector. A DetElement instance has the means to provide to clients information about
the detector hierarchy by exposing its children.
its placement within the overall experiment if it represents an entire subdetector or its placement with respect to its parent if the DetElement represents a part of a subdetector.
information about the Readout structure if the object is instrumented and read-out. Otherwise this link is empty.
information about the environmental conditions etc. conditons. The access to conditions is exposed via the DetConditions interface. See DD4hep/DetConditions.h for further details.
alignment information.
Author
M.Frank
Version
1.0
Definition at line 172 of file Detector.h.
Member Typedef Documentation
Alignment
typedef Alignments::Alignment DD4hep::Geometry::DetElement::Alignment
Definition at line 179 of file Detector.h.
Children
typedef std::map<std::string, DetElement> DD4hep::Geometry::DetElement::Children
Definition at line 186 of file Detector.h.
copy_t
typedef void*(* DD4hep::Geometry::DetElement::copy_t) (const void *, DetElement)
Extensions copy constructor type.
Definition at line 182 of file Detector.h.
destruct_t
typedef void(* DD4hep::Geometry::DetElement::destruct_t) (void *)
Extensions destructor type.
Definition at line 184 of file Detector.h.
Extensions
typedef std::map<const std::type_info*, void*> DD4hep::Geometry::DetElement::Extensions
Definition at line 187 of file Detector.h.
Object
typedef DetElementObject DD4hep::Geometry::DetElement::Object
Internal object type.
Definition at line 175 of file Detector.h.
Parent
typedef DetElement DD4hep::Geometry::DetElement::Parent
Definition at line 178 of file Detector.h.
RefObject
typedef Handle<DetElementObject> DD4hep::Geometry::DetElement::RefObject
Definition of the base handle type.
Definition at line 177 of file Detector.h.
Member Enumeration Documentation
CopyParameters
enum DD4hep::Geometry::DetElement::CopyParameters
Enumerator
COPY_NONE
COPY_PLACEMENT
COPY_PARENT
COPY_ALIGNMENT
LAST
Definition at line 189 of file Detector.h.
UpdateParam
enum DD4hep::Geometry::DetElement::UpdateParam
Enumerator
CONDITIONS_CHANGED
PLACEMENT_CHANGED
SOMETHING_CHANGED
PLACEMENT_ELEMENT
PLACEMENT_HIGHEST
PLACEMENT_DETECTOR
PLACEMENT_NONE
Definition at line 193 of file Detector.h.
Constructor & Destructor Documentation
DetElement() [1/8]
DD4hep::Geometry::DetElement::DetElement () inline
Default constructor.
Definition at line 227 of file Detector.h.
Referenced by child(), and clone().
DetElement() [2/8]
DD4hep::Geometry::DetElement::DetElement (Object * object_ptr) inline
Constructor to hold handled object.
Definition at line 230 of file Detector.h.
References DD4hep::Handle< T >::data(), DD4hep::Handle< T >::name(), and DD4hep::Geometry::SensitiveDetector::type().
DetElement() [3/8]
DetElement::DetElement (Object * data, const std::string & name, const std::string & type)
Clone constructor.
Definition at line 33 of file Detector.cpp.
References DD4hep::Handle< T >::assign().
DetElement() [4/8]
template<typename Q > DD4hep::Geometry::DetElement::DetElement (const Handle< Q > & e) inline
Templated constructor for handle conversions.
Definition at line 236 of file Detector.h.
References e.
DetElement() [5/8]
DD4hep::Geometry::DetElement::DetElement (const DetElement & e) default
Constructor to copy handle.
DetElement() [6/8]
DetElement::DetElement (const std::string & name, const std::string & type, int id)
Constructor for a new subdetector element.
Definition at line 39 of file Detector.cpp.
References DD4hep::Handle< T >::assign(), and DD4hep::Handle< T >::ptr().
DetElement() [7/8]
DetElement::DetElement (const std::string & name, int id)
Constructor for a new subdetector element.
Definition at line 45 of file Detector.cpp.
References DD4hep::Handle< T >::assign(), and DD4hep::Handle< T >::ptr().
DetElement() [8/8]
DetElement::DetElement (DetElement parent, const std::string & name, int id)
Constructor for a new subdetector element.
Definition at line 51 of file Detector.cpp.
References add(), DD4hep::Handle< T >::assign(), DD4hep::Handle< T >::ptr(), and type().
Member Function Documentation
_copy()
template<typename T > static void* DD4hep::Geometry::DetElement::_copy (const void * ptr, DetElement elt) inline static protected
Templated copy constructor.
Definition at line 213 of file Detector.h.
References DD4hep::Geometry::SensitiveDetector::i_addExtension(), DD4hep::Geometry::SensitiveDetector::i_extension(), and DD4hep::Handle< T >::ptr().
_data()
Object& DD4hep::Geometry::DetElement::_data () const inline
Additional data accessor.
Definition at line 257 of file Detector.h.
Referenced by DD4hep::Alignments::GlobalDetectorAlignment::volumeAlignments().
_delete()
template<typename T > static void DD4hep::Geometry::DetElement::_delete (void * ptr) inline static protected
Templated destructor function.
Definition at line 209 of file Detector.h.
add()
DetElement & DetElement::add (DetElement sub_element)
Add new child to the detector structure.
Definition at line 247 of file Detector.cpp.
References DD4hep::Handle< T >::access(), children(), DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), and path().
Referenced by DD4hep::Geometry::LCDDImp::addDetector(), create_detector(), DetElement(), DD4hep::Geometry::LCDDImp::init(), and placeStaves().
addExtension()
template<typename IFACE , typename CONCRETE > IFACE* DD4hep::Geometry::DetElement::addExtension (CONCRETE * c) const inline
Extend the detector element with an arbitrary structure accessible by the type.
Definition at line 281 of file Detector.h.
References DD4hep::CallbackSequence::checkTypes(), and DD4hep::Geometry::SensitiveDetector::i_addExtension().
Referenced by DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::DetectorSurfaces::initialize(), and DD4hep::DDRec::volSurfaceList().
callAtUpdate()
template<typename Q , typename T > void DD4hep::Geometry::DetElement::callAtUpdate (unsigned int typ, Q * pointer, void(T::*)(unsigned long typ, DetElement &det, void *opt_par) pmf) const inline
Extend the detector element with an arbitrary callback.
Definition at line 291 of file Detector.h.
References DD4hep::CallbackSequence::checkTypes(), DD4hep::Geometry::SensitiveDetector::combineHits(), DD4hep::Geometry::SensitiveDetector::limits(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Geometry::SensitiveDetector::region(), DD4hep::Geometry::SensitiveDetector::setCombineHits(), DD4hep::Geometry::SensitiveDetector::setLimitSet(), DD4hep::Geometry::SensitiveDetector::setRegion(), DD4hep::Geometry::SensitiveDetector::setType(), and DD4hep::Geometry::SensitiveDetector::type().
Referenced by DD4hep::Geometry::VolumeManager::addSubdetector().
check()
void DetElement::check (bool condition, const std::string & msg) const
Internal assert function to check conditions.
Definition at line 241 of file Detector.cpp.
Referenced by create_detector().
child()
DetElement DetElement::child (const std::string & name) const
Access to individual children by name.
Definition at line 204 of file Detector.cpp.
References DetElement(), DD4hep::Handle< T >::isValid(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Geometry::DetectorTools::findDaughterElement().
children()
const DetElement::Children & DetElement::children () const
Access to the list of children.
Definition at line 199 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by add(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::Alignments::AlignmentsManagerObject::compute(), DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureGeometry(), DD4hep::createGearMgr(), DD4hep::Conditions::Test::TestEnv::dump_conditions_tree(), dumpDetectors(), DD4hep::DDRec::IDDecoder::findReadout(), DD4hep::DDRec::IDDecoder::getClosestDaughter(), DD4hep::DDRec::SurfaceHelper::initialize(), DD4hep::Display::LoadGeoChildren(), DD4hep::Printer< T >::operator()(), DD4hep::Alignments::GlobalAlignmentWriter::scan(), and DD4hep::SurfaceInstaller::scan().
clone() [1/2]
DetElement DetElement::clone (const std::string & new_name) const
Clone (Deep copy) the DetElement structure with a new name.
Definition at line 260 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Geometry::DetElementObject::clone(), COPY_NONE, DetElement(), DD4hep::NamedObject::GetTitle(), and DD4hep::Geometry::DetElementObject::id.
Referenced by create_detector(), and placeStaves().
clone() [2/2]
DetElement DetElement::clone (const std::string & new_name, int new_id) const
Clone (Deep copy) the DetElement structure with a new name and new identifier.
Definition at line 265 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Geometry::DetElementObject::clone(), COPY_NONE, DetElement(), and DD4hep::NamedObject::GetTitle().
combineHits()
bool DetElement::combineHits () const
Getter: Combine hits attribute.
Definition at line 167 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Printer< T >::operator()().
extension()
template<typename IFACE > IFACE* DD4hep::Geometry::DetElement::extension () const inline
Access extension element by the type.
Definition at line 286 of file Detector.h.
References DD4hep::Geometry::SensitiveDetector::i_extension().
Referenced by DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::DetectorSurfaces::initialize(), and DD4hep::DDRec::volSurfaceList().
hasAlignments()
bool DetElement::hasAlignments () const
Check if this DetElement has time dependent Alignments attached.
Check if alignments are at all present.
Definition at line 234 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Geometry::DetElementObject::alignments, and DD4hep::Handle< T >::isValid().
hasConditions()
bool DetElement::hasConditions () const
Check if this DetElement has time dependent Conditions attached.
Check if conditions are at all present.
Definition at line 226 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Geometry::DetElementObject::conditions, and DD4hep::Handle< T >::isValid().
i_addExtension()
void * DetElement::i_addExtension (void * ptr, const std::type_info & info, copy_t ctor, destruct_t dtor) const protected
Add an extension object to the detector element.
Definition at line 58 of file Detector.cpp.
References DD4hep::Handle< T >::access().
i_addUpdateCall()
void DetElement::i_addUpdateCall (unsigned int callback_type, const Callback & callback) const protected
Internal call to extend the detector element with an arbitrary structure accessible by the type.
Definition at line 68 of file Detector.cpp.
References DD4hep::Handle< T >::access().
i_extension()
void * DetElement::i_extension (const std::type_info & info) const protected
Access an existing extension object from the detector element.
Definition at line 63 of file Detector.cpp.
References DD4hep::Handle< T >::access().
id()
int DetElement::id () const
Get the detector identifier.
Definition at line 163 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::LCDDImp::addDetector(), create_detector(), DD4hep::XML::createPlacedEnvelope(), DD4hep::Geometry::LCDDHelper::detectorByID(), and DD4hep::Printer< T >::operator()().
key()
unsigned int DetElement::key () const
Access hash key of this detector element (Only valid once geometry is closed!)
Definition at line 128 of file Detector.cpp.
References DD4hep::Geometry::DetElementObject::key, and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute(), DD4hep::Alignments::AlignContext::newEntry(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
level()
int DetElement::level () const
Access the hierarchical level of the detector element (Only valid once geometry is closed!)
Access the hierarchical level of the detector element.
Definition at line 140 of file Detector.cpp.
References DD4hep::Geometry::DetElementObject::level, and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute(), and setTypeFlag().
localToParent()
bool DetElement::localToParent (const Position & local, Position & parent) const
Transformation from local coordinates of the placed volume to the parent system.
Definition at line 386 of file Detector.cpp.
References parentTransformation().
localToWorld()
bool DetElement::localToWorld (const Position & local, Position & global) const
Create cached matrix to transform to reference coordinates.
Transformation from local coordinates of the placed volume to the world system.
Transformation from local coordinates of the placed volume to the world system
Definition at line 377 of file Detector.cpp.
References worldTransformation().
Referenced by DD4hep::DDRec::SubdetectorExtensionImpl::getZMax(), and DD4hep::DDRec::SubdetectorExtensionImpl::getZMin().
nominal()
Alignment DetElement::nominal () const
Access to the constant ideal (nominal) alignment information.
Access to the alignment information.
Definition at line 179 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::DetElementObject::nominal.
Referenced by DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Alignments::AlignmentData::nominal(), survey(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
operator<()
bool DD4hep::Geometry::DetElement::operator< (const DetElement e) const inline
Operator less to insert into a map.
Definition at line 262 of file Detector.h.
References DD4hep::Handle< T >::ptr().
operator=()
DetElement& DD4hep::Geometry::DetElement::operator= (const DetElement & e) default
Assignment operator.
operator==()
bool DD4hep::Geometry::DetElement::operator== (const DetElement e) const inline
Equality operator.
Definition at line 267 of file Detector.h.
References DD4hep::Geometry::SensitiveDetector::operator=(), and DD4hep::Handle< T >::ptr().
parent()
DetElement DetElement::parent () const
Access to the detector elements's parent.
Definition at line 214 of file Detector.cpp.
References DD4hep::Geometry::DetElementObject::parent, and DD4hep::Handle< T >::ptr().
Referenced by _detector(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Alignments::AlignmentTools::computeSurvey(), DD4hep::Geometry::DetectorSelector::detectors(), DD4hep::Geometry::LCDDImp::detectors(), DD4hep::Geometry::LCDDImp::mapDetectorTypes(), DD4hep::SurfaceInstaller::parentVolume(), DD4hep::Geometry::DetElementObject::revalidate(), DD4hep::Alignments::AlignmentsManagerObject::to_world(), DD4hep::Geometry::DetectorTools::topElement(), and DD4hep::Geometry::DetElementObject::update().
parentToLocal()
bool DetElement::parentToLocal (const Position & parent, Position & local) const
Transformation from world coordinates of the local placed volume coordinates.
Transformation from parent coordinates of the local placed volume coordinates.
Definition at line 404 of file Detector.cpp.
References parentTransformation().
parentTransformation()
const TGeoHMatrix & DetElement::parentTransformation () const
Create cached matrix to transform to parent coordinates.
Definition at line 372 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by localToParent(), and parentToLocal().
path()
const string & DetElement::path () const
Path of the detector element (not necessarily identical to placement path!)
Access the full path of the detector element.
Definition at line 152 of file Detector.cpp.
References DD4hep::Geometry::DetElementObject::path, and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), add(), DD4hep::Alignments::GlobalAlignmentCache::apply(), DD4hep::Alignments::AlignmentsManagerObject::compute(), DD4hep::Alignments::GlobalAlignmentWriter::createElement(), DD4hep::Conditions::Test::TestEnv::dump_conditions_tree(), DD4hep::Conditions::Test::TestEnv::dump_detector_element(), DD4hep::Geometry::DetectorTools::findDaughterElement(), DD4hep::Alignments::AlignContext::PathOrdering::operator()(), DD4hep::Geometry::DetElementObject::revalidate(), setTypeFlag(), DD4hep::Geometry::VolumeManagerObject::update(), and DD4hep::Geometry::DetElementObject::update().
placement()
PlacedVolume DetElement::placement () const
Access to the physical volume of this detector element.
Definition at line 271 of file Detector.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::DetElementObject::placement.
Referenced by DD4hep::Geometry::LCDDImp::addDetector(), DD4hep::Geometry::VolumeManager::addSubdetector(), DD4hep::Alignments::GlobalAlignmentCache::apply(), DD4hep::Geometry::GeoHandler::collect(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Alignments::AlignmentTools::computeSurvey(), DD4hep::Geometry::GeometryTreeDump::create(), DD4hep::Simulation::Geant4Converter::create(), dumpDetectors(), DD4hep::DDRec::Surface::initialize(), DD4hep::Utilities::LoadDetElement(), DD4hep::Display::LoadGeoChildren(), DD4hep::Printer< T >::operator()(), DD4hep::SurfaceInstaller::parentVolume(), DD4hep::SurfaceInstaller::placementTranslation(), and DD4hep::SurfaceInstaller::scan().
placementPath()
const string & DetElement::placementPath () const
Access to the full path to the placed object.
Definition at line 78 of file Detector.cpp.
References DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Geometry::DetElementObject::placementPath, and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Alignments::GlobalDetectorAlignment::align(), DD4hep::Alignments::GlobalAlignmentWriter::createElement(), dumpDetectors(), DD4hep::Alignments::GlobalAlignmentCache::get(), DD4hep::Alignments::AlignmentOperator::insert(), DD4hep::Geometry::DetElementObject::revalidate(), and DD4hep::Alignments::GlobalAlignmentCache::section().
removeAtUpdate()
void DetElement::removeAtUpdate (unsigned int type, void * pointer) const
Remove callback from object.
Definition at line 73 of file Detector.cpp.
References DD4hep::Handle< T >::access().
setAttributes()
DetElement & DetElement::setAttributes (const LCDD & lcdd, const Volume & volume, const std::string & region, const std::string & limits, const std::string & vis)
Set all attributes in one go.
Definition at line 326 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Geometry::DetElementObject::referenceTrafo, setLimitSet(), setRegion(), and setVisAttributes().
Referenced by create_detector(), and DD4hep::XML::createPlacedEnvelope().
setCombineHits()
DetElement & DetElement::setCombineHits (bool value, SensitiveDetector & sens)
Setter: Combine hits attribute.
Definition at line 171 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::SensitiveDetector::setCombineHits().
Referenced by create_detector().
setLimitSet()
DetElement & DetElement::setLimitSet (const LCDD & lcdd, const std::string & name, const Volume & volume)
Set the limits to the detector element.
Definition at line 319 of file Detector.cpp.
References DD4hep::Geometry::LCDD::limitSet(), and DD4hep::Geometry::Volume::setLimitSet().
Referenced by setAttributes().
setPlacement()
DetElement & DetElement::setPlacement (const PlacedVolume & volume)
Set the physical volumes of the detector element.
Definition at line 282 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Geometry::DetElementObject::idealPlace, DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::DetElementObject::placement.
Referenced by create_detector(), DD4hep::XML::createPlacedEnvelope(), DD4hep::Geometry::LCDDImp::init(), and placeStaves().
setRegion()
DetElement & DetElement::setRegion (const LCDD & lcdd, const std::string & name, const Volume & volume)
Set the regional attributes to the detector element.
Definition at line 312 of file Detector.cpp.
References DD4hep::Geometry::LCDD::region(), and DD4hep::Geometry::Volume::setRegion().
Referenced by setAttributes().
setType()
DetElement & DetElement::setType (const std::string & typ)
Set detector type (structure, tracker, calorimeter, etc.).
Set the type of the sensitive detector.
Definition at line 95 of file Detector.cpp.
References DD4hep::Handle< T >::access(), and DD4hep::NamedObject::SetTitle().
setTypeFlag()
DetElement & DetElement::setTypeFlag (unsigned int types)
Set the flag word encoding detector types (ideally use DD4hep::DetType for encoding)
Set the type of the sensitive detector.
Definition at line 106 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::hash32(), DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElementObject::key, DD4hep::Geometry::DetElementObject::level, level(), DD4hep::NamedObject::name, DD4hep::Geometry::DetElementObject::parent, DD4hep::Geometry::DetElementObject::path, path(), and DD4hep::Geometry::DetElementObject::typeFlag.
Referenced by DD4hep::XML::setDetectorTypeFlag().
setVisAttributes()
DetElement & DetElement::setVisAttributes (const LCDD & lcdd, const std::string & name, const Volume & volume)
Set Visualization attributes to the detector element.
Definition at line 307 of file Detector.cpp.
References DD4hep::Geometry::Volume::setVisAttributes().
Referenced by create_detector(), and setAttributes().
survey()
Alignment DetElement::survey () const
Access to the constant survey alignment information.
Access to the survey alignment information.
Definition at line 190 of file Detector.cpp.
References DD4hep::Handle< T >::access(), DD4hep::Alignments::AlignmentTools::copy(), DD4hep::Handle< T >::isValid(), nominal(), and DD4hep::Geometry::DetElementObject::survey.
Referenced by DD4hep::Alignments::AlignmentTools::computeSurvey().
type()
string DetElement::type () const
Access detector type (structure, tracker, calorimeter, etc.).
Access detector type (structure, tracker, calorimeter, etc.). Required for determination of G4 sensitive detector.
Definition at line 90 of file Detector.cpp.
References DD4hep::Handle< T >::m_element.
Referenced by DetElement(), DD4hep::SurfaceInstaller::invalidInstaller(), DD4hep::Geometry::LCDDImp::mapDetectorTypes(), and DD4hep::Printer< T >::operator()().
typeFlag()
unsigned int DetElement::typeFlag () const
Definition at line 101 of file Detector.cpp.
References DD4hep::Handle< T >::m_element.
Referenced by DD4hep::Geometry::DetectorSelector::detectors(), and DD4hep::Geometry::LCDDImp::detectors().
volume()
Volume DetElement::volume () const
Access to the logical volume of the detector element's placement.
Access to the logical volume of the placements (all daughters have the same!)
Definition at line 303 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::DDRec::createGearForCLIC(), DD4hep::DDRec::createGearForILD(), DD4hep::createGearMgr(), DD4hep::DDRec::IDDecoder::findReadout(), DD4hep::DDRec::IDDecoder::getClosestDaughter(), DD4hep::DDRec::SubdetectorExtensionImpl::getNSides(), DD4hep::DDRec::SubdetectorExtensionImpl::getRMax(), DD4hep::DDRec::SubdetectorExtensionImpl::getRMin(), DD4hep::DDRec::SubdetectorExtensionImpl::getZMax(), DD4hep::DDRec::SubdetectorExtensionImpl::getZMin(), DD4hep::DDRec::IDDecoder::IDDecoder(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::LayerAttributes(), and DD4hep::DDRec::MaterialManager::MaterialManager().
volumeID()
DD4hep::VolumeID DetElement::volumeID () const
The cached VolumeID of this subdetector element.
Definition at line 295 of file Detector.cpp.
References DD4hep::Handle< T >::isValid().
Referenced by DD4hep::DDRec::Surface::initialize(), DD4hep::DDRec::SubdetectorExtensionImpl::isBarrel(), DD4hep::DDRec::SubdetectorExtensionImpl::isEndcap(), and DD4hep::DDRec::IDDecoder::volumeID().
world()
DetElement DetElement::world () const
Access to the world object. Only possible once the geometry is closed.
Definition at line 220 of file Detector.cpp.
References DD4hep::Handle< T >::ptr(), and DD4hep::Geometry::DetElementObject::world().
Referenced by DD4hep::Alignments::Interna::AlignmentContainer::get(), and DD4hep::Conditions::Interna::ConditionContainer::get().
worldToLocal()
bool DetElement::worldToLocal (const Position & global, Position & local) const
Transformation from local coordinates of the placed volume to arbitrary parent system set as reference.
Transformation from world coordinates of the local placed volume coordinates.
Transformation from world coordinates of the local placed volume coordinates
Definition at line 395 of file Detector.cpp.
References worldTransformation().
worldTransformation()
const TGeoHMatrix & DetElement::worldTransformation () const
Set detector element for reference transformations. Will delete existing reference trafo.
Create cached matrix to transform to world coordinates.
Create cached matrix to transform to world coordinates
Definition at line 367 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::DDRec::IDDecoder::cellID(), DD4hep::DDRec::IDDecoder::cellIDFromLocal(), DD4hep::DDRec::IDDecoder::getClosestDaughter(), DD4hep::DDRec::Surface::initialize(), localToWorld(), DD4hep::DDRec::IDDecoder::position(), and worldToLocal().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Detector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Detector.cpp