DD4hep: DD4hep::Geometry::IDDescriptor Class Reference
DD4hep::Geometry::IDDescriptor Class Reference
Class implementing the ID encoding of detector response.
#include <DDCore/IDDescriptor.h>
Public Types
typedef IDDescriptorObject Object
typedef BitFieldValue * Field
typedef std::vector< std::pair< std::string, Field > > FieldMap
typedef std::vector< std::pair< size_t, std::string > > FieldIDs
typedef std::pair< Field, VolumeID > VolIDField
typedef std::vector< VolIDField > VolIDFields
typedef std::pair< std::string, int > VolID
Encode a set of volume identifiers (corresponding to this description of course!) to a volumeID.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
IDDescriptor ()=default
Default constructor.
template<typename Q >
IDDescriptor (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
IDDescriptor (const std::string &description)
Initializing constructor.
std::string fieldDescription () const
unsigned maxBit () const
The total number of encoding bits for this descriptor.
const FieldIDs & ids () const
Access the field-id container.
const FieldMap & fields () const
Access the fieldmap container.
Field field (const std::string &field_name) const
Get the field descriptor of one field by name.
size_t fieldID (const std::string &field_name) const
Get the field identifier of one field by name.
Field field (size_t identifier) const
Get the field descriptor of one field by its identifier.
VolumeID encode (const std::vector< VolID > &ids) const
Encode a set of volume identifiers (corresponding to this description of course!) to a volumeID.
void decodeFields (VolumeID vid, VolIDFields &fields)
Decode volume IDs and return filled descriptor with all fields.
std::string toString () const
Access string representation.
BitField64 * decoder ()
Access the BitField64 object.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Class implementing the ID encoding of detector response.
Author
M.Frank
Version
1.0
Date
2012/07/31
Definition at line 40 of file IDDescriptor.h.
Member Typedef Documentation
Field
typedef BitFieldValue* DD4hep::Geometry::IDDescriptor::Field
Definition at line 43 of file IDDescriptor.h.
FieldIDs
typedef std::vector<std::pair<size_t, std::string> > DD4hep::Geometry::IDDescriptor::FieldIDs
Definition at line 45 of file IDDescriptor.h.
FieldMap
typedef std::vector<std::pair<std::string, Field> > DD4hep::Geometry::IDDescriptor::FieldMap
Definition at line 44 of file IDDescriptor.h.
Object
typedef IDDescriptorObject DD4hep::Geometry::IDDescriptor::Object
Definition at line 42 of file IDDescriptor.h.
VolID
typedef std::pair<std::string, int> DD4hep::Geometry::IDDescriptor::VolID
Encode a set of volume identifiers (corresponding to this description of course!) to a volumeID.
Definition at line 72 of file IDDescriptor.h.
VolIDField
typedef std::pair<Field, VolumeID> DD4hep::Geometry::IDDescriptor::VolIDField
Definition at line 46 of file IDDescriptor.h.
VolIDFields
typedef std::vector<VolIDField> DD4hep::Geometry::IDDescriptor::VolIDFields
Definition at line 47 of file IDDescriptor.h.
Constructor & Destructor Documentation
IDDescriptor() [1/3]
DD4hep::Geometry::IDDescriptor::IDDescriptor () default
Default constructor.
Referenced by IDDescriptor().
IDDescriptor() [2/3]
template<typename Q > DD4hep::Geometry::IDDescriptor::IDDescriptor (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 53 of file IDDescriptor.h.
References decodeFields(), decoder(), encode(), field(), fieldDescription(), fieldID(), fields(), IDDescriptor(), ids(), maxBit(), and toString().
IDDescriptor() [3/3]
IDDescriptor::IDDescriptor (const std::string & description)
Initializing constructor.
Definition at line 42 of file IDDescriptor.cpp.
Member Function Documentation
decodeFields()
void IDDescriptor::decodeFields (VolumeID vid, VolIDFields & fields)
Decode volume IDs and return filled descriptor with all fields.
Definition at line 120 of file IDDescriptor.cpp.
References v.
Referenced by IDDescriptor(), and DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor().
decoder()
BitField64 * IDDescriptor::decoder ()
Access the BitField64 object.
Definition at line 132 of file IDDescriptor.cpp.
Referenced by IDDescriptor().
encode()
VolumeID IDDescriptor::encode (const std::vector< VolID > & ids) const
Encode a set of volume identifiers (corresponding to this description of course!) to a volumeID.
Definition at line 107 of file IDDescriptor.cpp.
References DD4hep::DDSegmentation::BitFieldValue::mask(), DD4hep::DDSegmentation::BitFieldValue::offset(), and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by IDDescriptor().
field() [1/2]
IDDescriptor::Field IDDescriptor::field (const std::string & field_name) const
Get the field descriptor of one field by name.
Definition at line 83 of file IDDescriptor.cpp.
References m.
Referenced by DD4hep::Geometry::VolumeManager::addSubdetector(), DD4hep::DDRec::IDDecoder::barrelEndcapFlag(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::Geant4ReadoutVolumeFilter(), IDDescriptor(), DD4hep::DDRec::IDDecoder::layerIndex(), DD4hep::DDRec::IDDecoder::systemIndex(), and DD4hep::Geometry::DetectorTools::toString().
field() [2/2]
IDDescriptor::Field IDDescriptor::field (size_t identifier) const
Get the field descriptor of one field by its identifier.
Definition at line 92 of file IDDescriptor.cpp.
References m.
fieldDescription()
std::string IDDescriptor::fieldDescription () const
Definition at line 56 of file IDDescriptor.cpp.
References DD4hep::DDSegmentation::BitField64::fieldDescription().
Referenced by DD4hep::Simulation::Geant4ConversionHelper::encoding(), and IDDescriptor().
fieldID()
size_t IDDescriptor::fieldID (const std::string & field_name) const
Get the field identifier of one field by name.
Definition at line 98 of file IDDescriptor.cpp.
References m.
Referenced by IDDescriptor().
fields()
const IDDescriptor::FieldMap & IDDescriptor::fields () const
Access the fieldmap container.
Definition at line 75 of file IDDescriptor.cpp.
Referenced by IDDescriptor(), and DD4hep::Geometry::Region::storeSecondaries().
ids()
const IDDescriptor::FieldIDs & IDDescriptor::ids () const
Access the field-id container.
Definition at line 67 of file IDDescriptor.cpp.
Referenced by IDDescriptor(), and DD4hep::Geometry::Region::storeSecondaries().
maxBit()
unsigned IDDescriptor::maxBit () const
The total number of encoding bits for this descriptor.
Definition at line 62 of file IDDescriptor.cpp.
Referenced by IDDescriptor(), and DD4hep::Geometry::Region::storeSecondaries().
toString()
string IDDescriptor::toString () const
Access string representation.
Acces string representation.
Definition at line 49 of file IDDescriptor.cpp.
Referenced by IDDescriptor(), and DD4hep::Geometry::operator<<().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/IDDescriptor.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/IDDescriptor.cpp