DD4hep: TiXmlAttribute Class Reference
TiXmlAttribute Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlAttribute ()
Construct an empty attribute.
TiXmlAttribute (const std::string &_name, const std::string &_value)
std::string constructor.
TiXmlAttribute (const char *_name, const char *_value)
Construct an attribute with a name and value.
const char * Name () const
Return the name of this attribute.
const char * Value () const
Return the value of this attribute.
const std::string & ValueStr () const
Return the value of this attribute.
int IntValue () const
Return the value of this attribute, converted to an integer.
double DoubleValue () const
Return the value of this attribute, converted to a double.
const TIXML_STRING & NameTStr () const
int QueryIntValue (int *_value) const
int QueryDoubleValue (double *_value) const
QueryDoubleValue examines the value string. See QueryIntValue().
void SetName (const char *_name)
Set the name of this attribute.
void SetValue (const char *_value)
Set the value.
void SetIntValue (int _value)
Set the value from an integer.
void SetDoubleValue (double _value)
Set the value from a double.
void SetName (const std::string &_name)
STL std::string form.
void SetValue (const std::string &_value)
STL std::string form.
const TiXmlAttribute * Next () const
Get the next sibling attribute in the DOM. Returns null at end.
TiXmlAttribute * Next ()
const TiXmlAttribute * Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
TiXmlAttribute * Previous ()
bool operator== (const TiXmlAttribute &rhs) const
bool operator< (const TiXmlAttribute &rhs) const
bool operator> (const TiXmlAttribute &rhs) const
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual void Print (FILE *cfile, int depth) const
void Print (FILE *cfile, int depth, TIXML_STRING *str) const
void SetDocument (TiXmlDocument *doc)
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Private Member Functions
TiXmlAttribute (const TiXmlAttribute &)
void operator= (const TiXmlAttribute &base)
Private Attributes
TiXmlDocument * document
TIXML_STRING name
TIXML_STRING value
TiXmlAttribute * prev
TiXmlAttribute * next
Friends
class TiXmlAttributeSet
Additional Inherited Members
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_DOCUMENT_TOP_ONLY, TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
An attribute is a name-value pair. Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not TiXmlNodes, since they are not part of the tinyXML document object model. There are other suggested ways to look at this problem.
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 877 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlAttribute() [1/4]
TiXmlAttribute::TiXmlAttribute () inline
Construct an empty attribute.
Definition at line 882 of file tinyxml.h.
TiXmlAttribute() [2/4]
TiXmlAttribute::TiXmlAttribute (const std::string & _name, const std::string & _value) inline
std::string constructor.
Definition at line 890 of file tinyxml.h.
TiXmlAttribute() [3/4]
TiXmlAttribute::TiXmlAttribute (const char * _name, const char * _value) inline
Construct an attribute with a name and value.
Definition at line 899 of file tinyxml.h.
TiXmlAttribute() [4/4]
TiXmlAttribute::TiXmlAttribute (const TiXmlAttribute &) private
Member Function Documentation
DoubleValue()
double TiXmlAttribute::DoubleValue () const
Return the value of this attribute, converted to a double.
Definition at line 1303 of file tinyxml_inl.h.
References TiXmlNode::value.
IntValue()
int TiXmlAttribute::IntValue () const
Return the value of this attribute, converted to an integer.
Definition at line 1298 of file tinyxml_inl.h.
References TiXmlNode::value.
Name()
const char* TiXmlAttribute::Name () const inline
Return the name of this attribute.
Definition at line 906 of file tinyxml.h.
Referenced by TiXmlAttributeSet::Add(), DD4hep::XML::Handle_t::checksum(), TiXmlElement::CopyTo(), and TiXmlElement::Parse().
NameTStr()
const TIXML_STRING& TiXmlAttribute::NameTStr () const inline
Definition at line 921 of file tinyxml.h.
Referenced by TiXmlElement::Parse().
Next() [1/2]
const TiXmlAttribute * TiXmlAttribute::Next () const
Get the next sibling attribute in the DOM. Returns null at end.
Definition at line 1196 of file tinyxml_inl.h.
References TiXmlNode::next, and TiXmlNode::value.
Referenced by DD4hep::XML::Handle_t::checksum(), TiXmlElement::CopyTo(), TiXmlElement::Print(), DD4hep::XML::Handle_t::removeAttrs(), and TiXmlPrinter::VisitEnter().
Next() [2/2]
TiXmlAttribute* TiXmlAttribute::Next () inline
Definition at line 961 of file tinyxml.h.
operator<()
bool TiXmlAttribute::operator< (const TiXmlAttribute & rhs) const inline
Definition at line 974 of file tinyxml.h.
References name.
operator=()
void TiXmlAttribute::operator= (const TiXmlAttribute & base) private
operator==()
bool TiXmlAttribute::operator== (const TiXmlAttribute & rhs) const inline
Definition at line 971 of file tinyxml.h.
References name.
operator>()
bool TiXmlAttribute::operator> (const TiXmlAttribute & rhs) const inline
Definition at line 977 of file tinyxml.h.
References name.
Parse()
const char * TiXmlAttribute::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements TiXmlBase.
Definition at line 1365 of file tinyxmlparser_inl.h.
References TiXmlParsingData::Cursor(), TiXmlNode::GetDocument(), TiXmlBase::IsWhiteSpace(), TiXmlBase::location, TiXmlBase::ReadName(), TiXmlBase::ReadText(), TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlParsingData::Stamp(), TiXmlText::StreamIn(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_EMBEDDED_NULL, TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, TIXML_STRING, and TiXmlNode::value.
Referenced by TiXmlElement::Parse(), and TiXmlDeclaration::Parse().
Previous() [1/2]
const TiXmlAttribute * TiXmlAttribute::Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
Definition at line 1216 of file tinyxml_inl.h.
References TiXmlNode::prev, and TiXmlNode::value.
Previous() [2/2]
TiXmlAttribute* TiXmlAttribute::Previous () inline
Definition at line 967 of file tinyxml.h.
Print() [1/2]
virtual void TiXmlAttribute::Print (FILE * cfile, int depth) const inline virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements TiXmlBase.
Definition at line 987 of file tinyxml.h.
References TIXML_STRING.
Print() [2/2]
void TiXmlAttribute::Print (FILE * cfile, int depth, TIXML_STRING * str) const
Definition at line 1236 of file tinyxml_inl.h.
References TiXmlBase::PutString(), TIXML_STRING, v, and TiXmlNode::value.
QueryDoubleValue()
int TiXmlAttribute::QueryDoubleValue (double * _value) const
QueryDoubleValue examines the value string. See QueryIntValue().
Definition at line 1269 of file tinyxml_inl.h.
References TIXML_SUCCESS, TIXML_WRONG_TYPE, and TiXmlNode::value.
Referenced by TiXmlElement::QueryDoubleAttribute().
QueryIntValue()
int TiXmlAttribute::QueryIntValue (int * _value) const
QueryIntValue examines the value string. It is an alternative to the IntValue() method with richer error checking. If the value is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE.
A specialized but useful call. Note that for success it returns 0, which is the opposite of almost all other TinyXml calls.
Definition at line 1262 of file tinyxml_inl.h.
References TIXML_SUCCESS, TIXML_WRONG_TYPE, and TiXmlNode::value.
Referenced by TiXmlElement::QueryIntAttribute().
SetDocument()
void TiXmlAttribute::SetDocument (TiXmlDocument * doc) inline
Definition at line 994 of file tinyxml.h.
References TiXmlAttributeSet::operator=().
Referenced by TiXmlElement::Parse().
SetDoubleValue()
void TiXmlAttribute::SetDoubleValue (double _value)
Set the value from a double.
Definition at line 1287 of file tinyxml_inl.h.
References TiXmlNode::SetValue().
SetIntValue()
void TiXmlAttribute::SetIntValue (int _value)
Set the value from an integer.
Definition at line 1276 of file tinyxml_inl.h.
References TiXmlNode::SetValue().
SetName() [1/2]
void TiXmlAttribute::SetName (const char * _name) inline
Set the name of this attribute.
Definition at line 938 of file tinyxml.h.
SetName() [2/2]
void TiXmlAttribute::SetName (const std::string & _name) inline
STL std::string form.
Definition at line 950 of file tinyxml.h.
SetValue() [1/2]
void TiXmlAttribute::SetValue (const char * _value) inline
Set the value.
Definition at line 941 of file tinyxml.h.
Referenced by TiXmlElement::Parse(), and TiXmlElement::SetAttribute().
SetValue() [2/2]
void TiXmlAttribute::SetValue (const std::string & _value) inline
STL std::string form.
Definition at line 954 of file tinyxml.h.
Value()
const char* TiXmlAttribute::Value () const inline
Return the value of this attribute.
Definition at line 909 of file tinyxml.h.
Referenced by TiXmlElement::Attribute(), DD4hep::XML::Handle_t::checksum(), TiXmlElement::CopyTo(), TiXmlElement::Parse(), and TiXmlDeclaration::Parse().
ValueStr()
const std::string& TiXmlAttribute::ValueStr () const inline
Return the value of this attribute.
Definition at line 913 of file tinyxml.h.
Referenced by TiXmlElement::Attribute(), and TiXmlElement::QueryValueAttribute().
Friends And Related Function Documentation
TiXmlAttributeSet
friend class TiXmlAttributeSet friend
Definition at line 878 of file tinyxml.h.
Member Data Documentation
document
TiXmlDocument* TiXmlAttribute::document private
Definition at line 1002 of file tinyxml.h.
name
TIXML_STRING TiXmlAttribute::name private
Definition at line 1003 of file tinyxml.h.
Referenced by operator<(), operator==(), and operator>().
next
TiXmlAttribute* TiXmlAttribute::next private
Definition at line 1005 of file tinyxml.h.
Referenced by TiXmlAttributeSet::Add(), TiXmlAttributeSet::Find(), TiXmlAttributeSet::First(), and TiXmlAttributeSet::Remove().
prev
TiXmlAttribute* TiXmlAttribute::prev private
Definition at line 1004 of file tinyxml.h.
Referenced by TiXmlAttributeSet::Add(), TiXmlAttributeSet::Last(), and TiXmlAttributeSet::Remove().
value
TIXML_STRING TiXmlAttribute::value private
Definition at line 1003 of file tinyxml.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h