DD4hep: DDSurfaces::Vector3D Class Reference
DDSurfaces::Vector3D Class Reference
#include <Vector3D.h>
Classes
struct Cartesian
struct Cylindrical
struct Spherical
Public Member Functions
Vector3D ()
Vector3D (const Vector3D &v)
Vector3D (const float *v)
Vector3D (const double *v)
template<class T >
Vector3D (double x, double y, double z, T(&)())
Vector3D (double x_val, double y_val, double z_val)
Vector3D & operator= (const Vector3D &v)
template<class T >
const Vector3D & fill (const T &v)
fill vector from arbitrary class that defines operator[]
const Vector3D & fill (const double *v)
fill vector from double array
const Vector3D & fill (double x_val, double y_val, double z_val)
fill from double values
double x () const
double y () const
double z () const
double & x ()
double & y ()
double & z ()
double operator[] (int i) const
double & operator[] (int i)
double phi () const
double rho () const
double trans () const
double trans2 () const
double r () const
double r2 () const
double theta () const
double dot (const Vector3D &v) const
Vector3D cross (const Vector3D &v) const
Vector3D unit () const
operator const double * () const
direct access to data as const double*
const double * const_array () const
direct access to data as const double*
double * array ()
direct access to data as double* - allows modification
bool isEqual (const Vector3D &b, double epsilon=1e-6)
template<class T >
T to () const
Static Public Member Functions
static Cartesian cartesian ()
static Cylindrical cylindrical ()
static Spherical spherical ()
Protected Attributes
double _x
double _y
double _z
Detailed Description
Simple three dimensional vector providing the components for cartesian, cylindrical and spherical coordinate systems - internal reperesentation is cartesian. (copy of original version from gear).
Author
F. Gaede, DESY
Version
$Id$
Date
Apr 6 2014
Definition at line 20 of file Vector3D.h.
Constructor & Destructor Documentation
Vector3D() [1/6]
DDSurfaces::Vector3D::Vector3D () inline
Default c'tor - zero vector
Definition at line 25 of file Vector3D.h.
Referenced by cross(), DDSurfaces::operator*(), DDSurfaces::operator+(), DDSurfaces::operator-(), unit(), and Vector3D().
Vector3D() [2/6]
DDSurfaces::Vector3D::Vector3D (const Vector3D & v) inline
Copy constructor
Definition at line 29 of file Vector3D.h.
Vector3D() [3/6]
DDSurfaces::Vector3D::Vector3D (const float * v) inline
Constructor for float array.
Definition at line 32 of file Vector3D.h.
Vector3D() [4/6]
DDSurfaces::Vector3D::Vector3D (const double * v) inline
Constructor for double array.
Definition at line 35 of file Vector3D.h.
References Vector3D(), x(), y(), and z().
Vector3D() [5/6]
template<class T > DDSurfaces::Vector3D::Vector3D (double x, double y, double z, T(&)())
Templated c'tor - allows to have overloaded c'tors for different coordinates
Vector3D() [6/6]
DDSurfaces::Vector3D::Vector3D (double x_val, double y_val, double z_val) inline
Default corrdinate system for initialization is cartesian
Definition at line 44 of file Vector3D.h.
Member Function Documentation
array()
double* DDSurfaces::Vector3D::array () inline
direct access to data as double* - allows modification
Definition at line 204 of file Vector3D.h.
References _x.
Referenced by DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::CylinderSurface::globalToLocal(), DD4hep::DDRec::VolSurfaceBase::length_along_u(), DD4hep::DDRec::VolSurfaceBase::length_along_v(), DD4hep::DDRec::CylinderSurface::localToGlobal(), DD4hep::DDRec::CylinderSurface::normal(), DD4hep::DDRec::CylinderSurface::u(), DD4hep::DDRec::CylinderSurface::v(), and DD4hep::DDRec::VolConeImpl::VolConeImpl().
cartesian()
static Cartesian DDSurfaces::Vector3D::cartesian () inline static
Definition at line 265 of file Vector3D.h.
const_array()
const double* DDSurfaces::Vector3D::const_array () const inline
direct access to data as const double*
Definition at line 199 of file Vector3D.h.
References _x.
Referenced by DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::VolSurfaceBase::insideBounds(), DD4hep::DDRec::VolSurfaceBase::length_along_u(), DD4hep::DDRec::VolSurfaceBase::length_along_v(), and DD4hep::DDRec::VolConeImpl::VolConeImpl().
cross()
Vector3D DDSurfaces::Vector3D::cross (const Vector3D & v) const inline
Vector product
Definition at line 179 of file Vector3D.h.
References _x, _y, _z, Vector3D(), x(), y(), and z().
Referenced by DD4hep::DDRec::VolCylinderImpl::u(), DD4hep::DDRec::VolConeImpl::u(), DD4hep::DDRec::VolConeImpl::VolConeImpl(), and DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
cylindrical()
static Cylindrical DDSurfaces::Vector3D::cylindrical () inline static
Definition at line 266 of file Vector3D.h.
Referenced by DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::VolCylinderImpl::localToGlobal(), DD4hep::DDRec::VolConeImpl::localToGlobal(), DD4hep::DDRec::VolCylinderImpl::normal(), and DD4hep::DDRec::VolCylinderImpl::u().
dot()
double DDSurfaces::Vector3D::dot (const Vector3D & v) const inline
Scalar product
Definition at line 173 of file Vector3D.h.
References _x, _y, _z, x(), y(), and z().
Referenced by DDSurfaces::operator*().
fill() [1/3]
template<class T > const Vector3D& DDSurfaces::Vector3D::fill (const T & v) inline
fill vector from arbitrary class that defines operator[]
Definition at line 70 of file Vector3D.h.
References _x, _y, and _z.
Referenced by DD4hep::DDRec::Surface::getLines(), and DD4hep::DDRec::Surface::initialize().
fill() [2/3]
const Vector3D& DDSurfaces::Vector3D::fill (const double * v) inline
fill vector from double array
Definition at line 77 of file Vector3D.h.
References _x, _y, and _z.
fill() [3/3]
const Vector3D& DDSurfaces::Vector3D::fill (double x_val, double y_val, double z_val) inline
fill from double values
Definition at line 84 of file Vector3D.h.
References _x, _y, and _z.
isEqual()
bool DDSurfaces::Vector3D::isEqual (const Vector3D & b, double epsilon = 1e-6) inline
Component wise comparison of two vectors - true if all components differ less than epsilon
Definition at line 210 of file Vector3D.h.
References x(), y(), and z().
operator const double *()
DDSurfaces::Vector3D::operator const double * () const inline
direct access to data as const double*
Definition at line 195 of file Vector3D.h.
References _x.
operator=()
Vector3D& DDSurfaces::Vector3D::operator= (const Vector3D & v) inline
Copy c'tor for three vectors from other packages - requires T::x(),T::y(), T::z().
Definition at line 61 of file Vector3D.h.
References _x, _y, and _z.
operator[]() [1/2]
double DDSurfaces::Vector3D::operator[] (int i) const inline
Accessing x,y,z with bracket operator
Definition at line 110 of file Vector3D.h.
References _x, _y, and _z.
operator[]() [2/2]
double& DDSurfaces::Vector3D::operator[] (int i) inline
Accessing x,y,z with bracket operator for assignment
Definition at line 119 of file Vector3D.h.
References _x, _y, and _z.
phi()
double DDSurfaces::Vector3D::phi () const inline
Azimuthal angle - cylindrical and spherical
Definition at line 130 of file Vector3D.h.
References _x, and _y.
Referenced by DD4hep::DDRec::VolCylinderImpl::globalToLocal(), DD4hep::DDRec::VolConeImpl::globalToLocal(), DD4hep::DDRec::VolCylinderImpl::localToGlobal(), DD4hep::DDRec::VolConeImpl::localToGlobal(), DD4hep::DDRec::VolCylinderImpl::normal(), DD4hep::DDRec::VolConeImpl::normal(), DDSurfaces::operator<<(), DD4hep::DDRec::VolCylinderImpl::u(), DD4hep::DDRec::VolConeImpl::v(), and DD4hep::DDRec::VolConeImpl::VolConeImpl().
r()
double DDSurfaces::Vector3D::r () const inline
Spherical r/magnitude
Definition at line 154 of file Vector3D.h.
References _x, _y, and _z.
Referenced by DDSurfaces::operator<<(), and unit().
r2()
double DDSurfaces::Vector3D::r2 () const inline
Spherical r/magnitude, squared
Definition at line 161 of file Vector3D.h.
References _x, _y, and _z.
rho()
double DDSurfaces::Vector3D::rho () const inline
Transversal component - cylindrical 'r'
Definition at line 136 of file Vector3D.h.
References trans().
Referenced by DD4hep::DDRec::VolCylinderImpl::distance(), DD4hep::DDRec::VolConeImpl::distance(), DD4hep::DDRec::VolConeImpl::getLines(), DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::VolCylinderImpl::localToGlobal(), DDSurfaces::operator<<(), DD4hep::DDRec::CylinderSurface::radius(), DD4hep::DDRec::ConeSurface::radius0(), DD4hep::DDRec::ConeSurface::radius1(), theta(), and DD4hep::DDRec::VolConeImpl::VolConeImpl().
spherical()
static Spherical DDSurfaces::Vector3D::spherical () inline static
Definition at line 267 of file Vector3D.h.
Referenced by DD4hep::DDRec::VolConeImpl::normal(), DD4hep::DDRec::VolConeImpl::v(), and DD4hep::DDRec::VolConeImpl::VolConeImpl().
theta()
double DDSurfaces::Vector3D::theta () const inline
Polar angle - spherical
Definition at line 167 of file Vector3D.h.
References _x, _y, _z, and rho().
Referenced by DD4hep::DDRec::VolConeImpl::distance(), DD4hep::DDRec::VolConeImpl::getLines(), DD4hep::DDRec::VolConeImpl::globalToLocal(), DD4hep::DDRec::VolConeImpl::localToGlobal(), DD4hep::DDRec::VolConeImpl::normal(), DDSurfaces::operator<<(), DD4hep::DDRec::ConeSurface::radius0(), DD4hep::DDRec::ConeSurface::radius1(), DD4hep::DDRec::VolConeImpl::v(), DD4hep::DDRec::VolConeImpl::VolConeImpl(), DD4hep::DDRec::ConeSurface::z0(), and DD4hep::DDRec::ConeSurface::z1().
to()
template<class T > T DDSurfaces::Vector3D::to () const inline
Implicit templated conversion to anything that has a c'tor T(x,y,z) and accessor functions x(),y(),z(). For safety the result is checked which causes a small performance penalty.
See also
to()Explicit, unchecked conversion to anything that has a c'tor T(x,y,z). Example: CLHEP::Vector3D clhv = v.to< CLHEP::Vector3D>() ;
operator T()
Definition at line 249 of file Vector3D.h.
References _x, _y, and _z.
trans()
double DDSurfaces::Vector3D::trans () const inline
Transversal component
Definition at line 142 of file Vector3D.h.
References _x, and _y.
Referenced by rho().
trans2()
double DDSurfaces::Vector3D::trans2 () const inline
Transversal component squared
Definition at line 148 of file Vector3D.h.
References _x, and _y.
unit()
Vector3D DDSurfaces::Vector3D::unit () const inline
Parallel unit vector
Definition at line 187 of file Vector3D.h.
References _x, _y, _z, r(), and Vector3D().
Referenced by DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
x() [1/2]
double DDSurfaces::Vector3D::x () const inline
Cartesian x coordinate
Definition at line 91 of file Vector3D.h.
References _x.
Referenced by cross(), DD4hep::DDRec::VolSurfaceBase::distance(), dot(), DD4hep::DDRec::Surface::getLines(), isEqual(), DD4hep::DDRec::VolSurfaceBase::normal(), DD4hep::DDRec::Surface::normal(), DDSurfaces::operator*(), DDSurfaces::operator+(), DDSurfaces::operator-(), DDSurfaces::operator==(), DD4hep::DDRec::VolSurfaceBase::u(), DD4hep::DDRec::Surface::u(), DD4hep::DDRec::VolSurfaceBase::v(), DD4hep::DDRec::Surface::v(), Vector3D(), DD4hep::DDRec::VolConeImpl::VolConeImpl(), and DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
x() [2/2]
double& DDSurfaces::Vector3D::x () inline
Assign to cartesian x coordinate
Definition at line 100 of file Vector3D.h.
References _x.
y() [1/2]
double DDSurfaces::Vector3D::y () const inline
Cartesian y coordinate
Definition at line 94 of file Vector3D.h.
References _y.
Referenced by cross(), dot(), DD4hep::DDRec::Surface::getLines(), isEqual(), DDSurfaces::operator*(), DDSurfaces::operator+(), DDSurfaces::operator-(), DDSurfaces::operator==(), Vector3D(), DD4hep::DDRec::VolConeImpl::VolConeImpl(), and DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl().
y() [2/2]
double& DDSurfaces::Vector3D::y () inline
Assign to cartesian y coordinate
Definition at line 103 of file Vector3D.h.
References _y.
z() [1/2]
double DDSurfaces::Vector3D::z () const inline
Cartesian cartesian z coordinate
Definition at line 97 of file Vector3D.h.
References _z.
Referenced by cross(), DD4hep::DDRec::VolConeImpl::distance(), dot(), DD4hep::DDRec::Surface::getLines(), DD4hep::DDRec::VolCylinderImpl::globalToLocal(), DD4hep::DDRec::VolConeImpl::globalToLocal(), isEqual(), DD4hep::DDRec::VolCylinderImpl::localToGlobal(), DD4hep::DDRec::VolConeImpl::localToGlobal(), DDSurfaces::operator*(), DDSurfaces::operator+(), DDSurfaces::operator-(), DDSurfaces::operator==(), Vector3D(), DD4hep::DDRec::VolConeImpl::VolConeImpl(), DD4hep::DDRec::ConeSurface::z0(), and DD4hep::DDRec::ConeSurface::z1().
z() [2/2]
double& DDSurfaces::Vector3D::z () inline
Assign to cartesian z coordinate
Definition at line 106 of file Vector3D.h.
References _z.
Member Data Documentation
_x
double DDSurfaces::Vector3D::_x protected
Definition at line 254 of file Vector3D.h.
Referenced by array(), const_array(), cross(), dot(), fill(), operator const double *(), operator=(), operator[](), phi(), r(), r2(), theta(), to(), trans(), trans2(), unit(), and x().
_y
double DDSurfaces::Vector3D::_y protected
Definition at line 254 of file Vector3D.h.
Referenced by cross(), dot(), fill(), operator=(), operator[](), phi(), r(), r2(), theta(), to(), trans(), trans2(), unit(), and y().
_z
double DDSurfaces::Vector3D::_z protected
Definition at line 254 of file Vector3D.h.
Referenced by cross(), dot(), fill(), operator=(), operator[](), r(), r2(), theta(), to(), unit(), and z().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSurfaces/include/DDSurfaces/Vector3D.h