DD4hep: DD4hep::DDRec::Tracker Class Reference
DD4hep::DDRec::Tracker Class Reference
#include <Tracker.h>
Public Member Functions
Tracker (const Geometry::DetElement &det)
virtual ~Tracker ()
Public Member Functions inherited from DD4hep::DDRec::LayeredSubdetector
LayeredSubdetector (const Geometry::DetElement &det)
Default constructor.
virtual ~LayeredSubdetector ()
Destructor.
int numberOfLayers () const
Access to the total number of layers.
int numberOfSensors (int layerIndex=0) const
Access to the total number of sensors in a given layer index.
Geometry::DetElement layer (int layerIndex) const
Access to the layer DetElement for the given index.
const std::vector< Geometry::DetElement > & sensors (int layerIndex=0) const
Access to the sensitive DetElements of a given layer index.
const std::vector< Geometry::DetElement > & absorbers (int layerIndex=0) const
Access to the non-sensitive DetElements of a given layer index.
double totalThickness () const
Access the total thickness of the sub detector.
double totalRadiationLength () const
Access the total radiation length of the sub detector.
double totalInteractionLength () const
Access the total nuclear interaction length of the sub detector.
double thickness (int layerIndex=0) const
Access the total thickness of the layer with the given index.
double radiationLength (int layerIndex=0) const
Access the total radiation length of the layer with the given index.
double interactionLength (int layerIndex=0) const
Access the total nuclear interaction length of the layer with the given index.
double absorberThickness (int layerIndex) const
Access the total thickness of all non-sensitive elements of the layer with the given index.
double absorberRadiationLength (int layerIndex) const
Access the total radiation length of all non-sensitive elements of the layer with the given index.
double absorberInteractionLength (int layerIndex) const
Access the total nuclear interaction length of all non-sensitive elements of the layer with the given index.
virtual double sensorThickness (int layerIndex) const
Access the total thickness of all sensitive elements of the layer with the given index.
double sensorRadiationLength (int layerIndex) const
Access the total radiation length of all sensitive elements of the layer with the given index.
double sensorInteractionLength (int layerIndex) const
Access the total nuclear interaction length of all sensitive elements of the layer with the given index.
Public Member Functions inherited from DD4hep::Geometry::DetElement
void check (bool condition, const std::string &msg) const
Internal assert function to check conditions.
DetElement ()
Default constructor.
DetElement (Object *object_ptr)
Constructor to hold handled object.
DetElement (Object *data, const std::string &name, const std::string &type)
Clone constructor.
template<typename Q >
DetElement (const Handle< Q > &e)
Templated constructor for handle conversions.
DetElement (const DetElement &e)=default
Constructor to copy handle.
DetElement (const std::string &name, const std::string &type, int id)
Constructor for a new subdetector element.
DetElement (const std::string &name, int id)
Constructor for a new subdetector element.
DetElement (DetElement parent, const std::string &name, int id)
Constructor for a new subdetector element.
Object & _data () const
Additional data accessor.
bool operator< (const DetElement e) const
Operator less to insert into a map.
bool operator== (const DetElement e) const
Equality operator.
DetElement & operator= (const DetElement &e)=default
Assignment operator.
DetElement clone (const std::string &new_name) const
Clone (Deep copy) the DetElement structure with a new name.
DetElement clone (const std::string &new_name, int new_id) const
Clone (Deep copy) the DetElement structure with a new name and new identifier.
template<typename IFACE , typename CONCRETE >
IFACE * addExtension (CONCRETE *c) const
Extend the detector element with an arbitrary structure accessible by the type.
template<typename IFACE >
IFACE * extension () const
Access extension element by the type.
template<typename Q , typename T >
void callAtUpdate (unsigned int typ, Q *pointer, void(T::*pmf)(unsigned long typ, DetElement &det, void *opt_par)) const
Extend the detector element with an arbitrary callback.
void removeAtUpdate (unsigned int type, void *pointer) const
Remove callback from object.
int id () const
Get the detector identifier.
DetElement & setCombineHits (bool value, SensitiveDetector &sens)
Setter: Combine hits attribute.
bool combineHits () const
Getter: Combine hits attribute.
std::string type () const
Access detector type (structure, tracker, calorimeter, etc.).
DetElement & setType (const std::string &typ)
Set detector type (structure, tracker, calorimeter, etc.).
unsigned int typeFlag () const
DetElement & setTypeFlag (unsigned int types)
Set the flag word encoding detector types (ideally use DD4hep::DetType for encoding)
unsigned int key () const
Access hash key of this detector element (Only valid once geometry is closed!)
int level () const
Access the hierarchical level of the detector element (Only valid once geometry is closed!)
const std::string & path () const
Path of the detector element (not necessarily identical to placement path!)
const std::string & placementPath () const
Access to the full path to the placed object.
DetElement & setAttributes (const LCDD &lcdd, const Volume &volume, const std::string &region, const std::string &limits, const std::string &vis)
Set all attributes in one go.
DetElement & setVisAttributes (const LCDD &lcdd, const std::string &name, const Volume &volume)
Set Visualization attributes to the detector element.
DetElement & setRegion (const LCDD &lcdd, const std::string &name, const Volume &volume)
Set the regional attributes to the detector element.
DetElement & setLimitSet (const LCDD &lcdd, const std::string &name, const Volume &volume)
Set the limits to the detector element.
Volume volume () const
Access to the logical volume of the detector element's placement.
PlacedVolume placement () const
Access to the physical volume of this detector element.
DetElement & setPlacement (const PlacedVolume &volume)
Set the physical volumes of the detector element.
VolumeID volumeID () const
The cached VolumeID of this subdetector element.
DetElement & add (DetElement sub_element)
Add new child to the detector structure.
const Children & children () const
Access to the list of children.
DetElement child (const std::string &name) const
Access to individual children by name.
DetElement parent () const
Access to the detector elements's parent.
DetElement world () const
Access to the world object. Only possible once the geometry is closed.
bool hasConditions () const
Check if this DetElement has time dependent Conditions attached.
bool hasAlignments () const
Check if this DetElement has time dependent Alignments attached.
Alignment nominal () const
Access to the constant ideal (nominal) alignment information.
Alignment survey () const
Access to the constant survey alignment information.
const TGeoHMatrix & worldTransformation () const
Set detector element for reference transformations. Will delete existing reference trafo.
const TGeoHMatrix & parentTransformation () const
Create cached matrix to transform to parent coordinates.
bool localToWorld (const Position &local, Position &global) const
Create cached matrix to transform to reference coordinates.
bool localToParent (const Position &local, Position &parent) const
Transformation from local coordinates of the placed volume to the parent system.
bool worldToLocal (const Position &global, Position &local) const
Transformation from local coordinates of the placed volume to arbitrary parent system set as reference.
bool parentToLocal (const Position &parent, Position &local) const
Transformation from world coordinates of the local placed volume coordinates.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Public Member Functions inherited from DD4hep::DDRec::LayeringExtension
virtual ~LayeringExtension ()
Destructor.
Protected Attributes
TrackerExtension * _tracker
Protected Attributes inherited from DD4hep::DDRec::LayeredSubdetector
LayeringExtension * _layering
Private Member Functions
void getTrackerExtension ()
Additional Inherited Members
Public Types inherited from DD4hep::Geometry::DetElement
enum CopyParameters {
COPY_NONE = 0, COPY_PLACEMENT = 1 << 0, COPY_PARENT = 1 << 1, COPY_ALIGNMENT = 1 << 2,
LAST
}
enum UpdateParam {
CONDITIONS_CHANGED = 1<<0, PLACEMENT_CHANGED = 1<<1, SOMETHING_CHANGED = 1<<2, PLACEMENT_ELEMENT = 1<<20,
PLACEMENT_HIGHEST = 1<<21, PLACEMENT_DETECTOR = 1<<22, PLACEMENT_NONE
}
typedef DetElementObject Object
Internal object type.
typedef Handle< DetElementObject > RefObject
Definition of the base handle type.
typedef DetElement Parent
typedef Alignments::Alignment Alignment
typedef void *(* copy_t) (const void *, DetElement)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< std::string, DetElement > Children
typedef std::map< const std::type_info *, void * > Extensions
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Protected Member Functions inherited from DD4hep::Geometry::DetElement
void * i_addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor) const
Add an extension object to the detector element.
void * i_extension (const std::type_info &info) const
Access an existing extension object from the detector element.
void i_addUpdateCall (unsigned int callback_type, const Callback &callback) const
Internal call to extend the detector element with an arbitrary structure accessible by the type.
Protected Member Functions inherited from DD4hep::DDRec::LayeringExtension
LayeringExtension ()
Static Protected Member Functions inherited from DD4hep::Geometry::DetElement
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
template<typename T >
static void * _copy (const void *ptr, DetElement elt)
Templated copy constructor.
Detailed Description
Definition at line 20 of file Tracker.h.
Constructor & Destructor Documentation
Tracker()
DD4hep::DDRec::Tracker::Tracker (const Geometry::DetElement & det) inline
Definition at line 22 of file Tracker.h.
References getTrackerExtension().
~Tracker()
virtual DD4hep::DDRec::Tracker::~Tracker () inline virtual
Definition at line 27 of file Tracker.h.
Member Function Documentation
getTrackerExtension()
void DD4hep::DDRec::Tracker::getTrackerExtension () inline private
Definition at line 35 of file Tracker.h.
References DD4hep::Handle< T >::isValid().
Referenced by Tracker().
Member Data Documentation
_tracker
TrackerExtension* DD4hep::DDRec::Tracker::_tracker protected
Definition at line 32 of file Tracker.h.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/API/Tracker.h