DD4hep: DD4hep::NamedObject Class Reference
DD4hep::NamedObject Class Reference
DD4hep::Geometry components, classes and objects
Implementation of a named object.
#include <NamedObject.h>
Public Member Functions
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
std::string name
The object name.
std::string type
The object type.
Detailed Description
Implementation of a named object.
The data class behind named object handles.
Author
M.Frank
Version
1.0
Definition at line 31 of file NamedObject.h.
Constructor & Destructor Documentation
NamedObject() [1/5]
NamedObject::NamedObject ()
Standard constructor.
Definition at line 27 of file NamedObject.cpp.
NamedObject() [2/5]
NamedObject::NamedObject (const char * nam, const char * typ = "")
Initializing constructor.
Definition at line 31 of file NamedObject.cpp.
NamedObject() [3/5]
NamedObject::NamedObject (const std::string & nam)
Initializing constructor.
Definition at line 37 of file NamedObject.cpp.
NamedObject() [4/5]
NamedObject::NamedObject (const std::string & nam, const std::string & typ)
Initializing constructor.
Definition at line 43 of file NamedObject.cpp.
NamedObject() [5/5]
NamedObject::NamedObject (const NamedObject & c)
Copy constructor.
Definition at line 49 of file NamedObject.cpp.
~NamedObject()
NamedObject::~NamedObject () virtual
Default destructor.
Definition at line 53 of file NamedObject.cpp.
Member Function Documentation
GetName()
const char* DD4hep::NamedObject::GetName () const inline
Access name.
Definition at line 54 of file NamedObject.h.
Referenced by DD4hep::Geometry::DetElementObject::clone().
GetTitle()
const char* DD4hep::NamedObject::GetTitle () const inline
Get name (used by Handle)
Definition at line 66 of file NamedObject.h.
Referenced by DD4hep::Geometry::LCDDImp::addConstant(), DD4hep::Geometry::DetElementObject::clone(), DD4hep::Geometry::DetElement::clone(), DD4hep::Geometry::LCDDImp::constantAsString(), and DD4hep::Geometry::CartesianField::type().
operator=()
NamedObject & NamedObject::operator= (const NamedObject & c)
Assignment operator.
Definition at line 57 of file NamedObject.cpp.
References name, and type.
Referenced by DD4hep::Geometry::CartesianField::CartesianField(), and DD4hep::Conditions::Entry::operator=().
SetName()
void DD4hep::NamedObject::SetName (const char * nam) inline
Set name (used by Handle)
Definition at line 58 of file NamedObject.h.
Referenced by create_detector(), DD4hep::Geometry::DetElementObject::DetElementObject(), DD4hep::Conditions::ConditionsManagerObject::initialize(), and DD4hep::Geometry::SensitiveDetectorObject::SensitiveDetectorObject().
SetTitle()
void DD4hep::NamedObject::SetTitle (const char * tit) inline
Set Title (used by Handle)
Definition at line 62 of file NamedObject.h.
Referenced by DD4hep::Geometry::DetElement::setType().
Member Data Documentation
name
std::string DD4hep::NamedObject::name
The object name.
Definition at line 34 of file NamedObject.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), DD4hep::Conditions::make_key(), DD4hep::Conditions::Condition::name(), operator=(), DD4hep::Geometry::OverlayedField::OverlayedField(), DD4hep::Geometry::DetElementObject::referenceTransformation(), DD4hep::Geometry::DetElement::setTypeFlag(), DD4hep::Conditions::Condition::str(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
type
std::string DD4hep::NamedObject::type
The object type.
Definition at line 36 of file NamedObject.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), operator=(), DD4hep::Conditions::Condition::str(), DD4hep::Conditions::Condition::type(), and DD4hep::Geometry::DetElementObject::world().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/NamedObject.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/NamedObject.cpp