DD4hep: DD4hep: TiXmlParsingData Class Reference
TiXmlParsingData Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxmlparser_inl.h>
Public Member Functions
void Stamp (const char *now, TiXmlEncoding encoding)
const TiXmlCursor & Cursor ()
Private Member Functions
TiXmlParsingData (const char *start, int _tabsize, int row, int col)
Private Attributes
TiXmlCursor cursor
const char * stamp
int tabsize
Friends
class TiXmlDocument
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
See
See also:
http://www.grinninglizard.com/tinyxml
Definition at line 179 of file tinyxmlparser_inl.h.
Constructor & Destructor Documentation
TiXmlParsingData::TiXmlParsingData (const char * start, int _tabsize, int row, int col) [inline, private]
Definition at line 189 of file tinyxmlparser_inl.h.
References TiXmlCursor::col, cursor, TiXmlCursor::row, stamp, and tabsize.
Member Function Documentation
const TiXmlCursor& TiXmlParsingData::Cursor () [inline]
Definition at line 185 of file tinyxmlparser_inl.h.
References cursor.
Referenced by TiXmlDeclaration::Parse(), TiXmlText::Parse(), TiXmlAttribute::Parse(), TiXmlComment::Parse(), TiXmlUnknown::Parse(), TiXmlElement::Parse(), TiXmlDocument::Parse(), and TiXmlDocument::SetError().
void TiXmlParsingData::Stamp (const char * now, TiXmlEncoding encoding)
Definition at line 204 of file tinyxmlparser_inl.h.
References TiXmlCursor::col, cursor, TiXmlCursor::row, stamp, tabsize, TIXML_ENCODING_UTF8, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, and TiXmlBase::utf8ByteTable.
Referenced by TiXmlDeclaration::Parse(), TiXmlText::Parse(), TiXmlAttribute::Parse(), TiXmlComment::Parse(), TiXmlUnknown::Parse(), TiXmlElement::Parse(), and TiXmlDocument::SetError().
Friends And Related Function Documentation
friend class TiXmlDocument [friend]
Definition at line 181 of file tinyxmlparser_inl.h.
Member Data Documentation
TiXmlCursor TiXmlParsingData::cursor [private]
Definition at line 198 of file tinyxmlparser_inl.h.
Referenced by Cursor(), TiXmlDocument::Parse(), Stamp(), and TiXmlParsingData().
const char* TiXmlParsingData::stamp [private]
Definition at line 199 of file tinyxmlparser_inl.h.
Referenced by Stamp(), and TiXmlParsingData().
int TiXmlParsingData::tabsize [private]
Definition at line 200 of file tinyxmlparser_inl.h.
Referenced by Stamp(), and TiXmlParsingData().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h