DD4hep: DD4hep: DD4hep::Simulation::Geant4RunAction Class Reference
DD4hep::Simulation::Geant4RunAction Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete basic implementation of the Geant4 run action base class.
#include <Geant4RunAction.h>
Public Types
typedef Geant4SharedRunAction shared_type
Public Member Functions
Geant4RunAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4RunAction ()
Default destructor.
virtual void begin (const G4Run *run)
Begin-of-run callback.
virtual void end (const G4Run *run)
End-of-run callback.
Detailed Description
Concrete basic implementation of the Geant4 run action base class.
The Run Action is called once per start and end of a run. i.e. a series of generated events. These two callbacks allow clients to define run-dependent actions such as statistics summaries etc.
Author:
M.Frank
Version:
1.0
Definition at line 46 of file Geant4RunAction.h.
Member Typedef Documentation
typedef Geant4SharedRunAction DD4hep::Simulation::Geant4RunAction::shared_type
Definition at line 48 of file Geant4RunAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4RunAction::Geant4RunAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4RunAction::~Geant4RunAction () [virtual]
Default destructor.
Definition at line 39 of file Geant4RunAction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4RunAction::begin (const G4Run * run) [virtual]
Begin-of-run callback.
begin-of-run callback
Reimplemented in DD4hep::Simulation::Geant4EventSeed, DD4hep::Simulation::Geant4SharedRunAction, and DD4hep::Simulation::Test::Geant4TestRunAction.
Definition at line 44 of file Geant4RunAction.cpp.
Referenced by DD4hep::Simulation::Geant4RunActionSequence::begin(), and DD4hep::Simulation::Geant4SharedRunAction::begin().
void Geant4RunAction::end (const G4Run * run) [virtual]
End-of-run callback.
Reimplemented in DD4hep::Simulation::Geant4SharedRunAction, and DD4hep::Simulation::Test::Geant4TestRunAction.
Definition at line 48 of file Geant4RunAction.cpp.
Referenced by DD4hep::Simulation::Geant4RunActionSequence::end(), and DD4hep::Simulation::Geant4SharedRunAction::end().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4RunAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4RunAction.cpp