DD4hep: DD4hep: DD4hep::EventConsumer Class Reference
DD4hep::EventConsumer Class Reference
#include <DDEve/EventHandler.h>
Public Member Functions
EventConsumer ()
Standard constructor.
virtual ~EventConsumer ()
Default destructor.
virtual void OnNewEvent (EventHandler *)
Consumer event data callback.
virtual void OnFileOpen (EventHandler *)
Consumer file open callback.
ClassDef (EventConsumer, 0)
Detailed Description
Author:
M.Frank
Version:
1.0
Definition at line 124 of file EventHandler.h.
Constructor & Destructor Documentation
EventConsumer::EventConsumer ()
Standard constructor.
Definition at line 32 of file EventHandler.cpp.
EventConsumer::~EventConsumer () [virtual]
Default destructor.
Definition at line 36 of file EventHandler.cpp.
Member Function Documentation
DD4hep::EventConsumer::ClassDef (EventConsumer , 0)
Reimplemented in DD4hep::Display.
virtual void DD4hep::EventConsumer::OnFileOpen (EventHandler *) [inline, virtual]
Consumer file open callback.
Reimplemented in DD4hep::EventControl.
Definition at line 133 of file EventHandler.h.
virtual void DD4hep::EventConsumer::OnNewEvent (EventHandler *) [inline, virtual]
Consumer event data callback.
Reimplemented in DD4hep::Display, and DD4hep::EventControl.
Definition at line 131 of file EventHandler.h.
Referenced by DD4hep::GenericEventHandler::GotoEvent(), DD4hep::GenericEventHandler::NextEvent(), and DD4hep::GenericEventHandler::PreviousEvent().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/EventHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/EventHandler.cpp