DD4hep: DD4hep::Geometry::Tube Class Reference
DD4hep::Geometry::Tube Class Reference
DD4hep::Geometry components, classes and objects
Class describing a tube shape of a section of a tube.
#include <Shapes.h>
Public Member Functions
Tube ()=default
Default constructor.
Tube (const Tube &e)=default
Constructor to be used when passing an already created object.
template<typename Q >
Tube (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
Tube (const Handle< Q > &e)
Constructor to assign an object.
Tube (double rmin, double rmax, double z)
Constructor to create a new anonymous tube object with attribute initialization.
Tube (double rmin, double rmax, double z, double deltaPhi)
Constructor to create a new anonymous tube object with attribute initialization.
Tube (double rmin, double rmax, double z, double startPhi, double deltaPhi)
Constructor to create a new anonymous tube object with attribute initialization.
Tube (const std::string &nam, double rmin, double rmax, double z)
Legacy: Constructor to create a new identifiable tube object with attribute initialization.
Tube (const std::string &nam, double rmin, double rmax, double z, double deltaPhi)
Legacy: Constructor to create a new identifiable tube object with attribute initialization.
template<typename RMIN , typename RMAX , typename Z , typename DELTAPHI >
Tube (const RMIN &rmin, const RMAX &rmax, const Z &z, const DELTAPHI &deltaPhi)
Constructor to create a new anonymous tube object with attribute initialization.
Tube & operator= (const Tube &copy)=default
Assignment operator.
Tube & setDimensions (double rmin, double rmax, double z, double startPhi=0.0, double deltaPhi=2 *M_PI)
Set the tube dimensions.
Public Member Functions inherited from DD4hep::Geometry::Solid_type< MyConeSeg >
Solid_type ()=default
Default constructor for uninitialized object.
Solid_type (const Solid_type &e)=default
Constructor to be used when passing an already created object.
Solid_type (MyConeSeg *p)
Direct assignment using the implementation pointer.
Solid_type (const Handle< MyConeSeg > &e)
Constructor to be used when passing an already created object.
Solid_type (const Handle< Q > &e)
Constructor to be used when passing an already created object: need to check pointers.
Solid_type & operator= (const Solid_type &copy)=default
Assignment operator.
const char * name () const
Access to shape name.
operator MyConeSeg * () const
Auto conversion to underlying ROOT object.
MyConeSeg * operator-> () const
Overloaded operator -> to access underlying object.
std::string toString (int precision=2) const
Conversion to string for pretty print.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Protected Member Functions
void make (const std::string &nam, double rmin, double rmax, double z, double startPhi, double deltaPhi)
Internal helper method to support object construction.
Protected Member Functions inherited from DD4hep::Geometry::Solid_type< MyConeSeg >
void _setDimensions (double *param)
void _assign (MyConeSeg *n, const std::string &nam, const std::string &tit, bool cbbox)
Assign pointrs and register solid to geometry.
Additional Inherited Members
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Protected Types inherited from DD4hep::Geometry::Solid_type< MyConeSeg >
typedef MyConeSeg Implementation
Detailed Description
Class describing a tube shape of a section of a tube.
TGeoTube - cylindrical tube class. It takes 3 parameters : inner radius, outer radius and half-length dz.
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoConeSeg.html
Author
M.Frank
Version
1.0
Definition at line 275 of file Shapes.h.
Constructor & Destructor Documentation
Tube() [1/10]
DD4hep::Geometry::Tube::Tube () default
Default constructor.
Tube() [2/10]
DD4hep::Geometry::Tube::Tube (const Tube & e) default
Constructor to be used when passing an already created object.
Tube() [3/10]
template<typename Q > DD4hep::Geometry::Tube::Tube (const Q * p) inline
Constructor to be used with an existing object.
Definition at line 286 of file Shapes.h.
Tube() [4/10]
template<typename Q > DD4hep::Geometry::Tube::Tube (const Handle< Q > & e) inline
Constructor to assign an object.
Definition at line 288 of file Shapes.h.
Tube() [5/10]
DD4hep::Geometry::Tube::Tube (double rmin, double rmax, double z) inline
Constructor to create a new anonymous tube object with attribute initialization.
Definition at line 290 of file Shapes.h.
References M_PI.
Tube() [6/10]
DD4hep::Geometry::Tube::Tube (double rmin, double rmax, double z, double deltaPhi) inline
Constructor to create a new anonymous tube object with attribute initialization.
Definition at line 293 of file Shapes.h.
Tube() [7/10]
DD4hep::Geometry::Tube::Tube (double rmin, double rmax, double z, double startPhi, double deltaPhi) inline
Constructor to create a new anonymous tube object with attribute initialization.
Definition at line 296 of file Shapes.h.
Tube() [8/10]
DD4hep::Geometry::Tube::Tube (const std::string & nam, double rmin, double rmax, double z) inline
Legacy: Constructor to create a new identifiable tube object with attribute initialization.
Definition at line 299 of file Shapes.h.
References M_PI.
Tube() [9/10]
DD4hep::Geometry::Tube::Tube (const std::string & nam, double rmin, double rmax, double z, double deltaPhi) inline
Legacy: Constructor to create a new identifiable tube object with attribute initialization.
Definition at line 302 of file Shapes.h.
Tube() [10/10]
template<typename RMIN , typename RMAX , typename Z , typename DELTAPHI > DD4hep::Geometry::Tube::Tube (const RMIN & rmin, const RMAX & rmax, const Z & z, const DELTAPHI & deltaPhi) inline
Constructor to create a new anonymous tube object with attribute initialization.
Definition at line 306 of file Shapes.h.
References DD4hep::_toDouble(), DD4hep::Alignments::AlignmentTools::copy(), M_PI, and DD4hep::Geometry::Solid_type< T >::operator=().
Member Function Documentation
make()
void Tube::make (const std::string & nam, double rmin, double rmax, double z, double startPhi, double deltaPhi) protected
Internal helper method to support object construction.
Constructor to be used when creating a new object with attribute initialization.
Definition at line 273 of file Shapes.cpp.
operator=()
Tube& DD4hep::Geometry::Tube::operator= (const Tube & copy) default
Assignment operator.
setDimensions()
Tube & Tube::setDimensions (double rmin, double rmax, double z, double startPhi = 0.0, double deltaPhi = 2*M_PI)
Set the tube dimensions.
Definition at line 280 of file Shapes.cpp.
References dd4hep::deg.
Referenced by create_detector().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp