DD4hep: DD4hep::Simulation::Geant4ParticleHandler Class Reference
DD4hep::Simulation::Geant4ParticleHandler Class Reference
DD4hep::Simulation components, classes and objects
Geant4Action to collect the MC particle information.
#include <Geant4ParticleHandler.h>
Public Types
typedef Geant4ParticleMap::Particle Particle
typedef Geant4ParticleMap::ParticleMap ParticleMap
typedef Geant4ParticleMap::TrackEquivalents TrackEquivalents
typedef std::vector< std::string > Processes
Public Types inherited from DD4hep::Simulation::Geant4GeneratorAction
typedef Geant4SharedGeneratorAction shared_type
Public Member Functions
Geant4ParticleHandler (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4ParticleHandler ()
Default destructor.
bool adopt (Geant4Action *action)
Adopt the user particle handler.
virtual void operator() (G4Event *event)
Event generation action callback.
virtual void step (const G4Step *step, G4SteppingManager *mgr)
User stepping callback.
virtual void beginEvent (const G4Event *event)
Pre-event action callback.
virtual void endEvent (const G4Event *event)
Post-event action callback.
virtual void begin (const G4Track *track)
Pre-track action callback.
virtual void end (const G4Track *track)
Post-track action callback.
virtual void mark (const G4Track *track)
Mark a Geant4 track to be kept for later MC truth analysis. Default flag: CREATED_HIT.
virtual void mark (const G4Track *track, int reason)
Store a track.
virtual void mark (const G4Step *step)
Mark a Geant4 track of the step to be kept for later MC truth analysis. Default flag: CREATED_HIT.
virtual void mark (const G4Step *step, int reason)
Store a track produced in a step to be kept for later MC truth analysis.
Public Member Functions inherited from DD4hep::Simulation::Geant4GeneratorAction
Geant4GeneratorAction (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4GeneratorAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Public Member Functions inherited from DD4hep::Simulation::Geant4MonteCarloTruth
virtual ~Geant4MonteCarloTruth ()
Default destructor.
Static Public Member Functions
static bool defaultKeepParticle (Particle &particle)
Default callback to be answered if the particle should be kept if NO user handler is installed.
Protected Member Functions
int recombineParents ()
Recombine particles and associate the to parents with cleanup.
void clear ()
Clear particle maps.
void checkConsistency () const
Check the record consistency.
void rebaseSimulatedTracks (int base)
Rebase the simulated tracks, so that they fit to the generator particles.
void dumpMap (const char *tag) const
Debugging: Dump Geant4 particle map.
void setVertexEndpointBit ()
set the endpointIsNotVertexOfParentFlag at the end of the event
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Member Functions inherited from DD4hep::Simulation::Geant4MonteCarloTruth
Geant4MonteCarloTruth ()
Standard constructor.
Protected Attributes
bool m_printStartTracking
Property: Steer printout at tracking action begin.
bool m_printEndTracking
Property: Steer printout at tracking action end.
bool m_keepAll
Property: Flag to keep all particles generated.
bool m_ownsParticles
Property: Flag if the handler is executed in standalone mode and hence must manage particles.
double m_kinEnergyCut
Property: Energy cut below which particles are not collected, but assigned to the parent.
double m_minDistToParentVertex
Property: Minimal distance after which the vertexIsNotEndpointOfParent flag is set.
Processes m_processNames
Property: All the processes of which the decay products will be explicitly stored.
Geant4UserParticleHandler * m_userHandler
User action pointer.
int m_globalParticleID
Global particle identifier. Obtained at the begin of the event.
Geant4PrimaryMap * m_primaryMap
Primary map.
Particle m_currTrack
Local buffer about the 'current' G4Track.
ParticleMap m_particleMap
Map with stored MC Particles.
TrackEquivalents m_equivalentTracks
Map associating the G4Track identifiers with identifiers of existing MCParticles.
Protected Attributes inherited from DD4hep::Simulation::Geant4GeneratorAction
Callback m_calls
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Private Member Functions
Geant4ParticleHandler ()
No default constructor.
Geant4ParticleHandler & operator= (const Geant4ParticleHandler &c)
No assignment operator.
Detailed Description
Geant4Action to collect the MC particle information.
Extract the relevant particle information during the simulation step.
This procedure works as follows:
At the beginning of the event generation the object registers itself as Monte-Carlo truth handler to the event context.
At the begin of each track action a particle candidate is created and filled with all properties known at this time.
At each stepping action a flag is set if the step produced secondaries.
Sensitive detectors call the MC truth handler if a hit was created. This fact is remembered.
At the end of the tracking action a first decision is taken if the candidate is to be kept for the final record.
At the end of the event action finally all particles are reduced to the final record. This logic can be overridden by a user handler to be attached.
Any of these actions may be intercepted by a {{Geant4UserParticleHandler}} attached to the particle handler. See class {{Geant4UserParticleHandler}} for details.
Author
M.Frank
Version
1.0
Definition at line 63 of file Geant4ParticleHandler.h.
Member Typedef Documentation
Particle
typedef Geant4ParticleMap::Particle DD4hep::Simulation::Geant4ParticleHandler::Particle
Definition at line 65 of file Geant4ParticleHandler.h.
ParticleMap
typedef Geant4ParticleMap::ParticleMap DD4hep::Simulation::Geant4ParticleHandler::ParticleMap
Definition at line 66 of file Geant4ParticleHandler.h.
Processes
typedef std::vector<std::string> DD4hep::Simulation::Geant4ParticleHandler::Processes
Definition at line 80 of file Geant4ParticleHandler.h.
TrackEquivalents
typedef Geant4ParticleMap::TrackEquivalents DD4hep::Simulation::Geant4ParticleHandler::TrackEquivalents
Definition at line 67 of file Geant4ParticleHandler.h.
Constructor & Destructor Documentation
Geant4ParticleHandler() [1/2]
Geant4ParticleHandler::Geant4ParticleHandler () private
No default constructor.
Definition at line 72 of file Geant4ParticleHandler.cpp.
Geant4ParticleHandler() [2/2]
Geant4ParticleHandler::Geant4ParticleHandler (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 51 of file Geant4ParticleHandler.cpp.
References begin(), beginEvent(), DD4hep::Simulation::Geant4SteppingActionSequence::call(), DD4hep::Simulation::Geant4EventActionSequence::callAtBegin(), DD4hep::Simulation::Geant4EventActionSequence::callAtEnd(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtFinal(), DD4hep::Simulation::Geant4TrackingActionSequence::callUpFront(), DD4hep::Simulation::Geant4Action::declareProperty(), e, end(), endEvent(), DD4hep::Simulation::Geant4Action::eventAction(), DD4hep::CallbackSequence::FRONT, DD4hep::InstanceCount::increment(), m_globalParticleID, m_keepAll, m_kinEnergyCut, m_minDistToParentVertex, DD4hep::Simulation::Geant4Action::m_needsControl, m_printEndTracking, m_printStartTracking, m_processNames, dd4hep::MeV, dd4hep::mm, step(), DD4hep::Simulation::Geant4Action::steppingAction(), and DD4hep::Simulation::Geant4Action::trackingAction().
~Geant4ParticleHandler()
Geant4ParticleHandler::~Geant4ParticleHandler () virtual
Default destructor.
Definition at line 76 of file Geant4ParticleHandler.cpp.
References clear(), DD4hep::InstanceCount::decrement(), m_userHandler, and DD4hep::releasePtr().
Member Function Documentation
adopt()
bool Geant4ParticleHandler::adopt (Geant4Action * action)
Adopt the user particle handler.
Definition at line 88 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), and m_userHandler.
Referenced by DD4hep::Simulation::_convertAction().
begin()
void Geant4ParticleHandler::begin (const G4Track * track) virtual
Pre-track action callback.
Initial update of the particle using the user handler
Definition at line 195 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Particle::addRef(), DD4hep::Simulation::Geant4UserParticleHandler::begin(), DD4hep::Simulation::Geant4Particle::colorFlow, DD4hep::Simulation::Geant4TrackHandler::creatorProcess(), DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4Action::except(), find(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_KEEP_ALWAYS, DD4hep::Simulation::G4PARTICLE_KEEP_PROCESS, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::G4PARTICLE_SIM_CREATED, DD4hep::Simulation::Geant4PrimaryMap::get(), DD4hep::Simulation::Geant4TrackHandler::globalTime(), DD4hep::Simulation::Geant4TrackHandler::id(), DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4TrackHandler::kineticEnergy(), m, m_currTrack, m_globalParticleID, m_keepAll, m_kinEnergyCut, m_particleMap, m_primaryMap, m_processNames, m_userHandler, DD4hep::Simulation::Geant4Particle::mask, DD4hep::Simulation::Geant4Particle::mass, DD4hep::Simulation::Geant4TrackHandler::momentum(), DD4hep::Simulation::Geant4TrackHandler::parent(), DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::Simulation::Geant4Particle::pex, DD4hep::Simulation::Geant4Particle::pey, DD4hep::Simulation::Geant4Particle::pez, DD4hep::Simulation::Geant4TrackHandler::primary(), DD4hep::Simulation::Geant4Particle::process, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4Particle::secondaries, DD4hep::Simulation::Geant4Particle::spin, DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::steps, DD4hep::Simulation::Geant4Particle::time, DD4hep::Simulation::Geant4TrackHandler::trackDef(), v, DD4hep::Simulation::Geant4TrackHandler::vertex(), DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
Referenced by Geant4ParticleHandler(), and recombineParents().
beginEvent()
void Geant4ParticleHandler::beginEvent (const G4Event * event) virtual
Pre-event action callback.
Call the user particle handler
Definition at line 362 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4UserParticleHandler::begin(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4Action::info(), m_equivalentTracks, m_globalParticleID, m_particleMap, m_primaryMap, m_userHandler, and DD4hep::Simulation::Geant4PrimaryInteraction::nextPID().
Referenced by Geant4ParticleHandler().
checkConsistency()
void Geant4ParticleHandler::checkConsistency () const protected
Check the record consistency.
First check the consistency of the particle map itself
Definition at line 603 of file Geant4ParticleHandler.cpp.
References DD4hep::ReferenceBitMask< T >::anySet(), DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4ParticleHandle::dumpWithMomentum(), DD4hep::ERROR, DD4hep::Simulation::Geant4Action::error(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_GEN_GENERATOR, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::Geant4Particle::id, DD4hep::ReferenceBitMask< T >::isSet(), m_equivalentTracks, m_particleMap, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4Particle::status, and DD4hep::yes_no().
Referenced by endEvent().
clear()
void Geant4ParticleHandler::clear () protected
Clear particle maps.
Definition at line 106 of file Geant4ParticleHandler.cpp.
References m_equivalentTracks, m_particleMap, and DD4hep::releaseObjects().
Referenced by endEvent(), operator()(), and ~Geant4ParticleHandler().
defaultKeepParticle()
bool Geant4ParticleHandler::defaultKeepParticle (Particle & particle) static
Default callback to be answered if the particle should be kept if NO user handler is installed.
Remove this track if it has not created a hit and the energy is below threshold
Remove this track if the energy is below threshold. Reassign hits to parent.
Remove this track if the origine is in the calorimeter. Reassign hits to parent.
Definition at line 496 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_CREATED_CALORIMETER_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, DD4hep::Simulation::G4PARTICLE_HAS_SECONDARIES, DD4hep::ReferenceBitMask< T >::isNull(), DD4hep::ReferenceBitMask< T >::isSet(), and DD4hep::Simulation::Geant4Particle::reason.
Referenced by DD4hep::Simulation::Geant4UserParticleHandler::keepParticle(), and recombineParents().
dumpMap()
void Geant4ParticleHandler::dumpMap (const char * tag) const protected
Debugging: Dump Geant4 particle map.
Definition at line 376 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4ParticleHandle::dump4(), DD4hep::INFO, m_particleMap, and DD4hep::Simulation::Geant4Action::name().
Referenced by endEvent().
end()
void Geant4ParticleHandler::end (const G4Track * track) virtual
Post-track action callback.
Final update of the particle using the user handler
Definition at line 279 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4ParticleHandle::dump2(), DD4hep::Simulation::Geant4ParticleHandle::dumpWithVertex(), DD4hep::Simulation::Geant4UserParticleHandler::end(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::G4PARTICLE_SIM_LEFT_DETECTOR, DD4hep::Simulation::G4PARTICLE_SIM_STOPPED, DD4hep::Simulation::Geant4Particle::get_data(), DD4hep::Simulation::Geant4TrackHandler::id(), DD4hep::ReferenceBitMask< T >::isNull(), DD4hep::ReferenceBitMask< T >::isSet(), m, m_currTrack, m_equivalentTracks, m_particleMap, m_userHandler, DD4hep::Simulation::Geant4Action::name(), DD4hep::Simulation::Geant4Action::outputLevel(), DD4hep::Simulation::Geant4Particle::pex, DD4hep::Simulation::Geant4Particle::pey, DD4hep::Simulation::Geant4Particle::pez, DD4hep::Simulation::Geant4Particle::reason, DD4hep::ReferenceBitMask< T >::set(), DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, and DD4hep::Simulation::Geant4Particle::vez.
Referenced by Geant4ParticleHandler().
endEvent()
void Geant4ParticleHandler::endEvent (const G4Event * event) virtual
Post-event action callback.
Call the user particle handler
Definition at line 383 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4ParticleMap::adopt(), checkConsistency(), clear(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Action::debug(), dumpMap(), DD4hep::Simulation::Geant4UserParticleHandler::end(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), m_equivalentTracks, m_particleMap, m_primaryMap, m_userHandler, DD4hep::Simulation::Geant4Action::outputLevel(), rebaseSimulatedTracks(), recombineParents(), setVertexEndpointBit(), and DD4hep::VERBOSE.
Referenced by Geant4ParticleHandler().
mark() [1/4]
void Geant4ParticleHandler::mark (const G4Track * track) virtual
Mark a Geant4 track to be kept for later MC truth analysis. Default flag: CREATED_HIT.
Mark a Geant4 track of the step to be kept for later MC truth analysis.
Check if the track origines from the calorimeter.
Implements DD4hep::Simulation::Geant4MonteCarloTruth.
Definition at line 142 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::G4PARTICLE_CREATED_CALORIMETER_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, m_currTrack, DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4ActionSD::sensitiveType(), and DD4hep::ReferenceBitMask< T >::set().
Referenced by mark().
mark() [2/4]
void Geant4ParticleHandler::mark (const G4Track * track, int reason) virtual
Store a track.
Mark a Geant4 track to be kept for later MC truth analysis.
Implements DD4hep::Simulation::Geant4MonteCarloTruth.
Definition at line 113 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), m_currTrack, and DD4hep::Simulation::Geant4Particle::reason.
mark() [3/4]
void Geant4ParticleHandler::mark (const G4Step * step) virtual
Mark a Geant4 track of the step to be kept for later MC truth analysis. Default flag: CREATED_HIT.
Mark a Geant4 track of the step to be kept for later MC truth analysis.
Implements DD4hep::Simulation::Geant4MonteCarloTruth.
Definition at line 133 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), and mark().
mark() [4/4]
void Geant4ParticleHandler::mark (const G4Step * step, int reason) virtual
Store a track produced in a step to be kept for later MC truth analysis.
Implements DD4hep::Simulation::Geant4MonteCarloTruth.
Definition at line 124 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::except(), and mark().
operator()()
void Geant4ParticleHandler::operator() (G4Event * event) virtual
Event generation action callback.
Call the user particle handler
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 162 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Event::addExtension(), clear(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Action::debug(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4UserParticleHandler::generate(), and m_userHandler.
operator=()
Geant4ParticleHandler & Geant4ParticleHandler::operator= (const Geant4ParticleHandler & c) private
No assignment operator.
Definition at line 83 of file Geant4ParticleHandler.cpp.
rebaseSimulatedTracks()
void Geant4ParticleHandler::rebaseSimulatedTracks (int base) protected
Rebase the simulated tracks, so that they fit to the generator particles.
No we have to update the map of equivalent tracks and assign the 'equivalentTrack' entry
Definition at line 411 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::Geant4Particle::addRef(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4ParticleHandle::definition(), DD4hep::Simulation::Geant4Action::error(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::Geant4Particle::id, m_equivalentTracks, m_particleMap, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4PrimaryInteraction::particles, DD4hep::Simulation::Geant4Particle::pdgID, and DD4hep::Simulation::Geant4Particle::reason.
Referenced by endEvent().
recombineParents()
int Geant4ParticleHandler::recombineParents () protected
Recombine particles and associate the to parents with cleanup.
Clean the monte carlo record. Remove all unwanted stuff. This is the core of the object executed at the end of each event action.
Need to start from BACK, to clean first the latest produced stuff.
If user decides it must be kept, it MUST be kept!
Primary particles MUST be kept!
Remove this track from the list and also do the cleanup in the parent's children list
Update of the particle using the user handler
Definition at line 524 of file Geant4ParticleHandler.cpp.
References begin(), DD4hep::Simulation::Geant4UserParticleHandler::combine(), defaultKeepParticle(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_FORCE_KILL, DD4hep::Simulation::G4PARTICLE_KEEP_ALWAYS, DD4hep::Simulation::G4PARTICLE_KEEP_PARENT, DD4hep::Simulation::G4PARTICLE_KEEP_PROCESS, DD4hep::Simulation::G4PARTICLE_KEEP_USER, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::ReferenceBitMask< T >::isNull(), DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::Simulation::Geant4UserParticleHandler::keepParticle(), m_equivalentTracks, m_particleMap, m_userHandler, DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4Particle::secondaries, DD4hep::ReferenceBitMask< T >::set(), DD4hep::Simulation::Geant4Particle::steps, and DD4hep::ReferenceBitMask< T >::value().
Referenced by endEvent().
setVertexEndpointBit()
void Geant4ParticleHandler::setVertexEndpointBit () protected
set the endpointIsNotVertexOfParentFlag at the end of the event
Definition at line 649 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::G4PARTICLE_SIM_PARENT_RADIATED, m_minDistToParentVertex, m_particleMap, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
Referenced by endEvent().
step()
void Geant4ParticleHandler::step (const G4Step * step, G4SteppingManager * mgr) virtual
User stepping callback.
Update of the particle using the user handler
Definition at line 174 of file Geant4ParticleHandler.cpp.
References DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_HAS_SECONDARIES, m_currTrack, m_userHandler, DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4UserParticleHandler::step(), and DD4hep::Simulation::Geant4Particle::steps.
Referenced by Geant4ParticleHandler().
Member Data Documentation
m_currTrack
Particle DD4hep::Simulation::Geant4ParticleHandler::m_currTrack protected
Local buffer about the 'current' G4Track.
Definition at line 110 of file Geant4ParticleHandler.h.
Referenced by begin(), end(), mark(), and step().
m_equivalentTracks
TrackEquivalents DD4hep::Simulation::Geant4ParticleHandler::m_equivalentTracks protected
Map associating the G4Track identifiers with identifiers of existing MCParticles.
Definition at line 114 of file Geant4ParticleHandler.h.
Referenced by beginEvent(), checkConsistency(), clear(), end(), endEvent(), rebaseSimulatedTracks(), and recombineParents().
m_globalParticleID
int DD4hep::Simulation::Geant4ParticleHandler::m_globalParticleID protected
Global particle identifier. Obtained at the begin of the event.
EVENT DEPENDENT: variables containing data depending on the current event.
Definition at line 106 of file Geant4ParticleHandler.h.
Referenced by begin(), beginEvent(), and Geant4ParticleHandler().
m_keepAll
bool DD4hep::Simulation::Geant4ParticleHandler::m_keepAll protected
Property: Flag to keep all particles generated.
Definition at line 90 of file Geant4ParticleHandler.h.
Referenced by begin(), and Geant4ParticleHandler().
m_kinEnergyCut
double DD4hep::Simulation::Geant4ParticleHandler::m_kinEnergyCut protected
Property: Energy cut below which particles are not collected, but assigned to the parent.
Definition at line 94 of file Geant4ParticleHandler.h.
Referenced by begin(), and Geant4ParticleHandler().
m_minDistToParentVertex
double DD4hep::Simulation::Geant4ParticleHandler::m_minDistToParentVertex protected
Property: Minimal distance after which the vertexIsNotEndpointOfParent flag is set.
Definition at line 96 of file Geant4ParticleHandler.h.
Referenced by Geant4ParticleHandler(), and setVertexEndpointBit().
m_ownsParticles
bool DD4hep::Simulation::Geant4ParticleHandler::m_ownsParticles protected
Property: Flag if the handler is executed in standalone mode and hence must manage particles.
Definition at line 92 of file Geant4ParticleHandler.h.
m_particleMap
ParticleMap DD4hep::Simulation::Geant4ParticleHandler::m_particleMap protected
Map with stored MC Particles.
Definition at line 112 of file Geant4ParticleHandler.h.
Referenced by begin(), beginEvent(), checkConsistency(), clear(), dumpMap(), end(), endEvent(), rebaseSimulatedTracks(), recombineParents(), and setVertexEndpointBit().
m_primaryMap
Geant4PrimaryMap* DD4hep::Simulation::Geant4ParticleHandler::m_primaryMap protected
Primary map.
Definition at line 108 of file Geant4ParticleHandler.h.
Referenced by begin(), beginEvent(), and endEvent().
m_printEndTracking
bool DD4hep::Simulation::Geant4ParticleHandler::m_printEndTracking protected
Property: Steer printout at tracking action end.
Definition at line 88 of file Geant4ParticleHandler.h.
Referenced by Geant4ParticleHandler().
m_printStartTracking
bool DD4hep::Simulation::Geant4ParticleHandler::m_printStartTracking protected
Property: Steer printout at tracking action begin.
Property variables used to configure the object
Definition at line 86 of file Geant4ParticleHandler.h.
Referenced by Geant4ParticleHandler().
m_processNames
Processes DD4hep::Simulation::Geant4ParticleHandler::m_processNames protected
Property: All the processes of which the decay products will be explicitly stored.
Definition at line 98 of file Geant4ParticleHandler.h.
Referenced by begin(), and Geant4ParticleHandler().
m_userHandler
Geant4UserParticleHandler* DD4hep::Simulation::Geant4ParticleHandler::m_userHandler protected
User action pointer.
Object variables, which are constant after initialization
Definition at line 102 of file Geant4ParticleHandler.h.
Referenced by adopt(), begin(), beginEvent(), end(), endEvent(), operator()(), recombineParents(), step(), and ~Geant4ParticleHandler().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ParticleHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ParticleHandler.cpp