DD4hep: DD4hep::Geometry::SensitiveDetector Class Reference
DD4hep::Geometry::SensitiveDetector Class Reference
DD4hep::Geometry components, classes and objects
Handle class to hold the information of a sensitive detector.
#include <Detector.h>
Public Types
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef SensitiveDetectorObject Object
Internal object type.
typedef Handle< SensitiveDetectorObject > RefObject
Definition of the base handle type.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
SensitiveDetector ()
Default constructor.
SensitiveDetector (Object *obj_pointer)
Constructor to copy handled object.
SensitiveDetector (const RefObject &sd)
Copy from named handle.
SensitiveDetector (const SensitiveDetector &sd)=default
Copy from handle.
template<typename Q >
SensitiveDetector (const Handle< Q > &e)
Templated constructor for handle conversions.
SensitiveDetector (const std::string &name, const std::string &type="sensitive")
Constructor for a new sensitive detector element.
SensitiveDetector & operator= (const SensitiveDetector &sd)=default
Assignment operator.
std::string type () const
Access the type of the sensitive detector.
SensitiveDetector & setType (const std::string &typ)
Set detector type (structure, tracker, calorimeter, etc.).
SensitiveDetector & setVerbose (bool value)
Set flag to handle hits collection.
bool verbose () const
Access flag to combine hist.
SensitiveDetector & setCombineHits (bool value)
Set flag to handle hits collection.
bool combineHits () const
Access flag to combine hist.
SensitiveDetector & setHitsCollection (const std::string &spec)
Assign the name of the hits collection.
const std::string & hitsCollection () const
Access the hits collection name.
SensitiveDetector & setReadout (Readout readout)
Assign the IDDescriptor reference.
Readout readout () const
Access readout structure of the sensitive detector.
SensitiveDetector & setEnergyCutoff (double value)
Set energy cut off.
double energyCutoff () const
Access energy cut off.
SensitiveDetector & setRegion (Region reg)
Set the regional attributes to the sensitive detector.
Region region () const
Access to the region setting of the sensitive detector (not mandatory)
SensitiveDetector & setLimitSet (LimitSet limits)
Set the limits to the sensitive detector.
LimitSet limits () const
Access to the limit set of the sensitive detector (not mandatory).
template<typename IFACE , typename CONCRETE >
IFACE * addExtension (CONCRETE *c)
Extend the sensitive detector element with an arbitrary structure accessible by the type.
template<typename IFACE >
IFACE * extension () const
Access extension element by the type.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Protected Member Functions
void * i_addExtension (void *ptr, const std::type_info &info, void(*destruct)(void *))
Add an extension object to the detector element.
void * i_extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Static Protected Member Functions
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class to hold the information of a sensitive detector.
Author
M.Frank
Version
1.0
Definition at line 47 of file Detector.h.
Member Typedef Documentation
destruct_t
typedef void(* DD4hep::Geometry::SensitiveDetector::destruct_t) (void *)
Extensions destructor type.
Definition at line 50 of file Detector.h.
Object
typedef SensitiveDetectorObject DD4hep::Geometry::SensitiveDetector::Object
Internal object type.
Definition at line 52 of file Detector.h.
RefObject
typedef Handle<SensitiveDetectorObject> DD4hep::Geometry::SensitiveDetector::RefObject
Definition of the base handle type.
Definition at line 54 of file Detector.h.
Constructor & Destructor Documentation
SensitiveDetector() [1/6]
DD4hep::Geometry::SensitiveDetector::SensitiveDetector () inline
Default constructor.
Definition at line 71 of file Detector.h.
Referenced by SensitiveDetector().
SensitiveDetector() [2/6]
DD4hep::Geometry::SensitiveDetector::SensitiveDetector (Object * obj_pointer) inline
Constructor to copy handled object.
Definition at line 74 of file Detector.h.
SensitiveDetector() [3/6]
DD4hep::Geometry::SensitiveDetector::SensitiveDetector (const RefObject & sd) inline
Copy from named handle.
Definition at line 77 of file Detector.h.
References SensitiveDetector().
SensitiveDetector() [4/6]
DD4hep::Geometry::SensitiveDetector::SensitiveDetector (const SensitiveDetector & sd) default
Copy from handle.
SensitiveDetector() [5/6]
template<typename Q > DD4hep::Geometry::SensitiveDetector::SensitiveDetector (const Handle< Q > & e) inline
Templated constructor for handle conversions.
Definition at line 83 of file Detector.h.
References combineHits(), energyCutoff(), hitsCollection(), limits(), DD4hep::Handle< T >::name(), operator=(), readout(), region(), SensitiveDetector(), setCombineHits(), setEnergyCutoff(), setHitsCollection(), setLimitSet(), setReadout(), setRegion(), setType(), setVerbose(), type(), and verbose().
SensitiveDetector() [6/6]
SensitiveDetector::SensitiveDetector (const std::string & name, const std::string & type = "sensitive")
Constructor for a new sensitive detector element.
Constructor.
Definition at line 413 of file Detector.cpp.
References DD4hep::Handle< T >::assign().
Member Function Documentation
_delete()
template<typename T > static void DD4hep::Geometry::SensitiveDetector::_delete (void * ptr) inline static protected
Templated destructor function.
Definition at line 58 of file Detector.h.
References i_addExtension(), i_extension(), and DD4hep::Handle< T >::ptr().
addExtension()
template<typename IFACE , typename CONCRETE > IFACE* DD4hep::Geometry::SensitiveDetector::addExtension (CONCRETE * c) inline
Extend the sensitive detector element with an arbitrary structure accessible by the type.
Definition at line 140 of file Detector.h.
References i_addExtension().
combineHits()
bool SensitiveDetector::combineHits () const
Access flag to combine hist.
Definition at line 489 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), and SensitiveDetector().
energyCutoff()
double SensitiveDetector::energyCutoff () const
Access energy cut off.
Definition at line 454 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Simulation::Geant4Converter::printSensitive(), DD4hep::Simulation::Geant4SensitiveDetector::process(), and SensitiveDetector().
extension()
template<typename IFACE > IFACE* DD4hep::Geometry::SensitiveDetector::extension () const inline
Access extension element by the type.
Definition at line 145 of file Detector.h.
References i_extension().
hitsCollection()
const string & SensitiveDetector::hitsCollection () const
Access the hits collection name.
Definition at line 465 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Simulation::Geant4GenericSD< T >::Geant4GenericSD(), DD4hep::Simulation::Geant4Converter::printSensitive(), and SensitiveDetector().
i_addExtension()
void * SensitiveDetector::i_addExtension (void * ptr, const std::type_info & info, void(*)(void *) destruct) protected
Add an extension object to the detector element.
Definition at line 516 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::_copy(), _delete(), addExtension(), and DD4hep::Geometry::DetElement::addExtension().
i_extension()
void * SensitiveDetector::i_extension (const std::type_info & info) const protected
Access an existing extension object from the detector element.
Definition at line 521 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::_copy(), _delete(), extension(), and DD4hep::Geometry::DetElement::extension().
limits()
LimitSet SensitiveDetector::limits () const
Access to the limit set of the sensitive detector (not mandatory).
Definition at line 511 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), DD4hep::Simulation::Geant4Converter::printSensitive(), and SensitiveDetector().
operator=()
SensitiveDetector& DD4hep::Geometry::SensitiveDetector::operator= (const SensitiveDetector & sd) default
Assignment operator.
Referenced by DD4hep::Geometry::DetElement::operator==(), and SensitiveDetector().
readout()
Readout SensitiveDetector::readout () const
Access readout structure of the sensitive detector.
Assign the IDDescriptor reference.
Definition at line 443 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::View::ConfigureEvent(), DD4hep::DDRec::createGearForILD(), DD4hep::Simulation::Geant4SensitiveAction< T >::declareReadoutFilteredCollection(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), DD4hep::Simulation::Geant4ConversionHelper::encoding(), DD4hep::DDRec::IDDecoder::findReadout(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), DD4hep::Simulation::Geant4SensitiveDetector::Geant4SensitiveDetector(), SensitiveDetector(), and DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor().
region()
Region SensitiveDetector::region () const
Access to the region setting of the sensitive detector (not mandatory)
Definition at line 500 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), DD4hep::Simulation::Geant4Converter::printSensitive(), and SensitiveDetector().
setCombineHits()
SensitiveDetector & SensitiveDetector::setCombineHits (bool value)
Set flag to handle hits collection.
Assign the name of the hits collection.
Definition at line 482 of file Detector.cpp.
References DD4hep::Handle< T >::access(), and v.
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), SensitiveDetector(), and DD4hep::Geometry::DetElement::setCombineHits().
setEnergyCutoff()
SensitiveDetector & SensitiveDetector::setEnergyCutoff (double value)
Set energy cut off.
Definition at line 448 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by SensitiveDetector().
setHitsCollection()
SensitiveDetector & SensitiveDetector::setHitsCollection (const std::string & spec)
Assign the name of the hits collection.
Definition at line 459 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by SensitiveDetector().
setLimitSet()
SensitiveDetector & SensitiveDetector::setLimitSet (LimitSet limits)
Set the limits to the sensitive detector.
Definition at line 505 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), and SensitiveDetector().
setReadout()
SensitiveDetector & SensitiveDetector::setReadout (Readout readout)
Assign the IDDescriptor reference.
Definition at line 437 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by SensitiveDetector().
setRegion()
SensitiveDetector & SensitiveDetector::setRegion (Region reg)
Set the regional attributes to the sensitive detector.
Definition at line 494 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), and SensitiveDetector().
setType()
SensitiveDetector & SensitiveDetector::setType (const std::string & typ)
Set detector type (structure, tracker, calorimeter, etc.).
Set the type of the sensitive detector.
Definition at line 426 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), create_detector(), create_element(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), and SensitiveDetector().
setVerbose()
SensitiveDetector & SensitiveDetector::setVerbose (bool value)
Set flag to handle hits collection.
Assign the name of the hits collection.
Definition at line 470 of file Detector.cpp.
References DD4hep::Handle< T >::access(), and v.
Referenced by SensitiveDetector().
type()
string SensitiveDetector::type () const
Access the type of the sensitive detector.
Definition at line 432 of file Detector.cpp.
References DD4hep::Handle< T >::m_element.
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), DD4hep::Simulation::Geant4DetectorSensitivesConstruction::constructSensitives(), DD4hep::Simulation::Geant4SensitiveDetector::defineCollection(), DD4hep::Geometry::DetElement::DetElement(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), DD4hep::Geometry::LCDDImp::mapDetectorTypes(), DD4hep::Simulation::Geant4Converter::printSensitive(), and SensitiveDetector().
verbose()
bool SensitiveDetector::verbose () const
Access flag to combine hist.
Definition at line 477 of file Detector.cpp.
References DD4hep::Handle< T >::access().
Referenced by SensitiveDetector().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Detector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Detector.cpp