DD4hep: DD4hep::Simulation::Geant4Field Class Reference
DD4hep::Simulation::Geant4Field Class Reference
DD4hep::Simulation components, classes and objects
Mediator class to allow Geant4 accessing magnetic fields defined in DD4hep.
#include <Geant4Field.h>
Public Member Functions
Geant4Field (Geometry::OverlayedField field)
Constructor. The sensitive detector element is identified by the detector name.
virtual ~Geant4Field ()
Standard destructor.
virtual void GetFieldValue (const double pos[4], double *arr) const
Access field values at a given point.
virtual G4bool DoesFieldChangeEnergy () const
Does field change energy ?
Protected Attributes
Geometry::OverlayedField m_field
Reference to the detector description field.
Detailed Description
Mediator class to allow Geant4 accessing magnetic fields defined in DD4hep.
Author
M.Frank
Version
1.0
Definition at line 40 of file Geant4Field.h.
Constructor & Destructor Documentation
Geant4Field()
DD4hep::Simulation::Geant4Field::Geant4Field (Geometry::OverlayedField field) inline
Constructor. The sensitive detector element is identified by the detector name.
Definition at line 47 of file Geant4Field.h.
~Geant4Field()
virtual DD4hep::Simulation::Geant4Field::~Geant4Field () inline virtual
Standard destructor.
Definition at line 51 of file Geant4Field.h.
References DoesFieldChangeEnergy(), and GetFieldValue().
Member Function Documentation
DoesFieldChangeEnergy()
G4bool Geant4Field::DoesFieldChangeEnergy () const virtual
Does field change energy ?
Definition at line 22 of file Geant4Field.cpp.
References DD4hep::Geometry::OverlayedField::changesEnergy(), and m_field.
Referenced by ~Geant4Field().
GetFieldValue()
void Geant4Field::GetFieldValue (const double pos[4], double * arr) const virtual
Access field values at a given point.
Definition at line 26 of file Geant4Field.cpp.
References m_field, DD4hep::Geometry::OverlayedField::magneticField(), dd4hep::mm, and dd4hep::tesla.
Referenced by ~Geant4Field().
Member Data Documentation
m_field
Geometry::OverlayedField DD4hep::Simulation::Geant4Field::m_field protected
Reference to the detector description field.
Definition at line 43 of file Geant4Field.h.
Referenced by DoesFieldChangeEnergy(), and GetFieldValue().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Field.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Field.cpp