DD4hep: DD4hep: DD4hep::EveUserContextMenu Class Reference
DD4hep::EveUserContextMenu Class Reference
class EveUserContextMenu EveUserContextMenu.h DDEve/EveUserContextMenu.h
#include <EveUserContextMenu.h>
Public Member Functions
EveUserContextMenu (Display *m)
Initializing constructor.
virtual ~EveUserContextMenu ()
Default destructor.
Display & display () const
EVE display.
TEveManager & manager () const
EVE manager.
void VisibleAll (bool yes_no, TObject *target, void *user_param)
Set everything (in-) visible.
void VisibleSelf (bool yes_no, TObject *target, void *user_param)
Set self (in-) visible.
void VisibleChildren (bool yes_no, TObject *target, void *user_param)
Set the children (in-) visible.
void ShowAll (TObject *target, void *user_param)
Show all.
void HideAll (TObject *target, void *user_param)
Show all.
void ShowSelf (TObject *target, void *user_param)
Show shape self.
void HideSelf (TObject *target, void *user_param)
Show shape self.
void ShowChildren (TObject *target, void *user_param)
Show shape children.
void HideChildren (TObject *target, void *user_param)
Show shape children.
void LoadChildren (TObject *target, void *user_param)
Load next level children and add them to all scenes.
void DeepLoadChildren (TObject *target, void *user_param)
Load all children and add them to all scenes.
void InstallGeometryContextMenu (TClass *cl)
Install the geometry context menu.
ClassDef (EveUserContextMenu, 0)
Root implementation macro.
Protected Attributes
Display * m_display
Detailed Description
class EveUserContextMenu EveUserContextMenu.h DDEve/EveUserContextMenu.h
Definition at line 35 of file EveUserContextMenu.h.
Constructor & Destructor Documentation
DD4hep::EveUserContextMenu::EveUserContextMenu (Display * m)
Initializing constructor.
EveUserContextMenu::~EveUserContextMenu () [virtual]
Default destructor.
Definition at line 38 of file EveUserContextMenu.cpp.
Member Function Documentation
DD4hep::EveUserContextMenu::ClassDef (EveUserContextMenu , 0)
Root implementation macro.
Reimplemented in DD4hep::ElementListContextMenu, DD4hep::EvePgonSetProjectedContextMenu, and DD4hep::EveShapeContextMenu.
void EveUserContextMenu::DeepLoadChildren (TObject * target, void * user_param)
Load all children and add them to all scenes.
Definition at line 101 of file EveUserContextMenu.cpp.
References DD4hep::Display::LoadGeoChildren(), and m_display.
Referenced by InstallGeometryContextMenu().
Display& DD4hep::EveUserContextMenu::display () const [inline]
EVE display.
Definition at line 44 of file EveUserContextMenu.h.
References m_display.
void EveUserContextMenu::HideAll (TObject * target, void * user_param)
Show all.
Hide all.
Definition at line 80 of file EveUserContextMenu.cpp.
References VisibleAll().
Referenced by InstallGeometryContextMenu().
void EveUserContextMenu::HideChildren (TObject * target, void * user_param)
Show shape children.
Hide shape children.
Definition at line 90 of file EveUserContextMenu.cpp.
References VisibleChildren().
Referenced by InstallGeometryContextMenu().
void EveUserContextMenu::HideSelf (TObject * target, void * user_param)
Show shape self.
Hide shape self.
Definition at line 85 of file EveUserContextMenu.cpp.
References VisibleSelf().
Referenced by InstallGeometryContextMenu().
void EveUserContextMenu::InstallGeometryContextMenu (TClass * cl)
Install the geometry context menu.
Definition at line 107 of file EveUserContextMenu.cpp.
References DD4hep::ContextMenu::Add(), DD4hep::ContextMenu::AddSeparator(), DD4hep::ContextMenu::Clear(), DeepLoadChildren(), HideAll(), HideChildren(), HideSelf(), DD4hep::ContextMenu::instance(), LoadChildren(), dd4hep::m, ShowAll(), ShowChildren(), and ShowSelf().
Referenced by DD4hep::ElementListContextMenu::ElementListContextMenu(), DD4hep::EvePgonSetProjectedContextMenu::EvePgonSetProjectedContextMenu(), and DD4hep::EveShapeContextMenu::EveShapeContextMenu().
void EveUserContextMenu::LoadChildren (TObject * target, void * user_param)
Load next level children and add them to all scenes.
Definition at line 95 of file EveUserContextMenu.cpp.
References DD4hep::Display::LoadGeoChildren(), and m_display.
Referenced by InstallGeometryContextMenu().
TEveManager & EveUserContextMenu::manager () const
EVE manager.
Definition at line 42 of file EveUserContextMenu.cpp.
References m_display, and DD4hep::Display::manager().
void EveUserContextMenu::ShowAll (TObject * target, void * user_param)
Show all.
Definition at line 65 of file EveUserContextMenu.cpp.
References VisibleAll().
Referenced by InstallGeometryContextMenu().
void EveUserContextMenu::ShowChildren (TObject * target, void * user_param)
Show shape children.
Definition at line 75 of file EveUserContextMenu.cpp.
References VisibleChildren().
Referenced by InstallGeometryContextMenu().
void EveUserContextMenu::ShowSelf (TObject * target, void * user_param)
Show shape self.
Definition at line 70 of file EveUserContextMenu.cpp.
References VisibleSelf().
Referenced by InstallGeometryContextMenu().
void EveUserContextMenu::VisibleAll (bool yes_no, TObject * target, void * user_param)
Set everything (in-) visible.
Definition at line 47 of file EveUserContextMenu.cpp.
References m_display, and DD4hep::Display::MakeNodesVisible().
Referenced by HideAll(), and ShowAll().
void EveUserContextMenu::VisibleChildren (bool yes_no, TObject * target, void * user_param)
Set the children (in-) visible.
Definition at line 59 of file EveUserContextMenu.cpp.
References m_display, and DD4hep::Display::MakeNodesVisible().
Referenced by HideChildren(), and ShowChildren().
void EveUserContextMenu::VisibleSelf (bool yes_no, TObject * target, void * user_param)
Set self (in-) visible.
Definition at line 53 of file EveUserContextMenu.cpp.
References m_display, and DD4hep::Display::MakeNodesVisible().
Referenced by HideSelf(), and ShowSelf().
Member Data Documentation
Display* DD4hep::EveUserContextMenu::m_display [protected]
Definition at line 37 of file EveUserContextMenu.h.
Referenced by DeepLoadChildren(), display(), LoadChildren(), manager(), VisibleAll(), VisibleChildren(), and VisibleSelf().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/EveUserContextMenu.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/EveUserContextMenu.cpp