DD4hep: DD4hep: DD4hep::Simulation::Geant4GeneratorActionInit Class Reference
DD4hep::Simulation::Geant4GeneratorActionInit Class Reference
[DD4hep::Simulation components, classes and objects]
Initialize the Geant4Event objects to host generator and MC truth related information.
#include <Geant4GeneratorActionInit.h>
Public Member Functions
Geant4GeneratorActionInit (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4GeneratorActionInit ()
Default destructor.
virtual void operator() (G4Event *event)
Event generation action callback.
void begin (const G4Run *run)
Begin-run action callback.
void end (const G4Run *run)
End-run action callback.
Protected Attributes
int m_run
Current run identifier.
int m_evtTotal
Counter for total number of events.
int m_evtRun
Counter for total number of events in current run.
Detailed Description
Initialize the Geant4Event objects to host generator and MC truth related information.
Geant4 actions to collect the MC particle information.
This action should register all event extension required for the further processing. We want to avoid that every client has to check if a given object is present or not and than later install the required data structures.
These by default are extensions of type: -- Geant4PrimaryEvent with multiple interaction sections, one for each interaction This is the MAIN and ONLY information to feed Geant4
-- Geant4PrimaryInteraction containing the track/vertex information to create the primary particles for Geant4. This record is build from the Geant4PrimaryEvent information. -- Geant4PrimaryMap a map of the Geant4Particles converted to G4PrimaryParticles to ease particle handling later. -- Geant4ParticleMap the map of particles created during the event simulation. This map has directly the correct particle offsets, so that the merging of Geant4PrimaryInteraction particles and the simulation particles is easy....
Author:
M.Frank
Version:
1.0
Definition at line 55 of file Geant4GeneratorActionInit.h.
Constructor & Destructor Documentation
Geant4GeneratorActionInit::Geant4GeneratorActionInit (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 28 of file Geant4GeneratorActionInit.cpp.
References begin(), DD4hep::Simulation::Geant4RunActionSequence::callAtBegin(), DD4hep::Simulation::Geant4RunActionSequence::callAtEnd(), DD4hep::Simulation::Geant4Action::context(), end(), DD4hep::InstanceCount::increment(), DD4hep::Simulation::Geant4Context::kernel(), and DD4hep::Simulation::Geant4ActionContainer::runAction().
Geant4GeneratorActionInit::~Geant4GeneratorActionInit () [virtual]
Default destructor.
Definition at line 37 of file Geant4GeneratorActionInit.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4GeneratorActionInit::begin (const G4Run * run)
Begin-run action callback.
Definition at line 42 of file Geant4GeneratorActionInit.cpp.
References m_evtRun, and m_run.
Referenced by Geant4GeneratorActionInit().
void Geant4GeneratorActionInit::end (const G4Run * run)
End-run action callback.
Definition at line 48 of file Geant4GeneratorActionInit.cpp.
References m_evtRun, m_evtTotal, m_run, and DD4hep::Simulation::Geant4Action::printP1().
Referenced by Geant4GeneratorActionInit().
void Geant4GeneratorActionInit::operator() (G4Event * event) [virtual]
Event generation action callback.
Update event counters
+ Printout
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 55 of file Geant4GeneratorActionInit.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::generationInitialization(), m_evtRun, m_evtTotal, m_run, and DD4hep::Simulation::Geant4Action::print().
Member Data Documentation
int DD4hep::Simulation::Geant4GeneratorActionInit::m_evtRun [protected]
Counter for total number of events in current run.
Definition at line 62 of file Geant4GeneratorActionInit.h.
Referenced by begin(), end(), and operator()().
int DD4hep::Simulation::Geant4GeneratorActionInit::m_evtTotal [protected]
Counter for total number of events.
Definition at line 60 of file Geant4GeneratorActionInit.h.
Referenced by end(), and operator()().
int DD4hep::Simulation::Geant4GeneratorActionInit::m_run [protected]
Current run identifier.
Definition at line 58 of file Geant4GeneratorActionInit.h.
Referenced by begin(), end(), and operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4GeneratorActionInit.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4GeneratorActionInit.cpp