DD4hep: DD4hep::DDRec::SubdetectorExtension Class Reference
DD4hep::DDRec::SubdetectorExtension Class Reference abstract
#include <SubdetectorExtension.h>
Public Member Functions
virtual ~SubdetectorExtension ()
Destructor.
virtual bool isBarrel () const =0
Is this a barrel detector.
virtual bool isEndcap () const =0
Is this an endcap detector.
virtual double getRMin () const =0
Access to the inner radius.
virtual double getRMax () const =0
Access to the outer radius.
virtual double getZMin () const =0
Access to the lower z extent.
virtual double getZMax () const =0
Access to the upper z extent.
virtual int getNSides () const =0
Access to the number of sides.
Protected Member Functions
SubdetectorExtension ()
Detailed Description
Class describing general parameters of a subdetector.
Definition at line 21 of file SubdetectorExtension.h.
Constructor & Destructor Documentation
~SubdetectorExtension()
virtual DD4hep::DDRec::SubdetectorExtension::~SubdetectorExtension () inline virtual
Destructor.
Definition at line 24 of file SubdetectorExtension.h.
References getNSides(), getRMax(), getRMin(), getZMax(), getZMin(), isBarrel(), and isEndcap().
SubdetectorExtension()
DD4hep::DDRec::SubdetectorExtension::SubdetectorExtension () inline protected
Definition at line 52 of file SubdetectorExtension.h.
Member Function Documentation
getNSides()
virtual int DD4hep::DDRec::SubdetectorExtension::getNSides () const pure virtual
Access to the number of sides.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::getNSides(), and ~SubdetectorExtension().
getRMax()
virtual double DD4hep::DDRec::SubdetectorExtension::getRMax () const pure virtual
Access to the outer radius.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::getRMax(), and ~SubdetectorExtension().
getRMin()
virtual double DD4hep::DDRec::SubdetectorExtension::getRMin () const pure virtual
Access to the inner radius.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::getRMin(), and ~SubdetectorExtension().
getZMax()
virtual double DD4hep::DDRec::SubdetectorExtension::getZMax () const pure virtual
Access to the upper z extent.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::getZMax(), and ~SubdetectorExtension().
getZMin()
virtual double DD4hep::DDRec::SubdetectorExtension::getZMin () const pure virtual
Access to the lower z extent.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::getZMin(), and ~SubdetectorExtension().
isBarrel()
virtual bool DD4hep::DDRec::SubdetectorExtension::isBarrel () const pure virtual
Is this a barrel detector.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::isBarrel(), and ~SubdetectorExtension().
isEndcap()
virtual bool DD4hep::DDRec::SubdetectorExtension::isEndcap () const pure virtual
Is this an endcap detector.
Implemented in DD4hep::DDRec::SubdetectorExtensionImpl.
Referenced by DD4hep::DDRec::Subdetector::isEndcap(), and ~SubdetectorExtension().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Extensions/SubdetectorExtension.h