DD4hep: DD4hep: DD4hep::FrameControl Class Reference
DD4hep::FrameControl Class Reference
class FrameControl FrameControl.h DDEve/FrameControl.h
#include <FrameControl.h>
Public Member Functions
FrameControl (TGClient *client, const std::string &name, unsigned int width, unsigned int height)
Standard constructor.
virtual ~FrameControl ()
Default destructor.
TGClient & client () const
Access to the windows client.
TGCompositeFrame * frame () const
Access to the top level frame.
virtual void Build ()
Build the control.
virtual void OnBuild ()
User callback to add elements to the control.
virtual TGCompositeFrame * CreateFrame ()
Create the frame for this control structure. Default: create horizontal frame.
virtual const TGPicture * LoadPicture (const std::string &path)
Helper: Load picture using path name.
Protected Attributes
TGClient * m_client
Reference to TEve manager.
TGCompositeFrame * m_frame
Reference to control's frame.
Detailed Description
class FrameControl FrameControl.h DDEve/FrameControl.h
Definition at line 37 of file FrameControl.h.
Constructor & Destructor Documentation
DD4hep::FrameControl::FrameControl (TGClient * client, const std::string & name, unsigned int width, unsigned int height)
Standard constructor.
FrameControl::~FrameControl () [virtual]
Default destructor.
Definition at line 40 of file FrameControl.cpp.
References m_frame.
Member Function Documentation
void FrameControl::Build () [virtual]
Build the control.
Definition at line 48 of file FrameControl.cpp.
References CreateFrame(), m_frame, and OnBuild().
Referenced by DD4hep::DD4hepMenu::OnCreateEventIO().
TGClient& DD4hep::FrameControl::client () const [inline]
Access to the windows client.
Definition at line 51 of file FrameControl.h.
References m_client.
Referenced by DD4hep::EventControl::OnFileOpen(), and DD4hep::EventControl::OnNewEvent().
TGCompositeFrame * FrameControl::CreateFrame () [virtual]
Create the frame for this control structure. Default: create horizontal frame.
Reimplemented in DD4hep::EventControl.
Definition at line 62 of file FrameControl.cpp.
Referenced by Build().
TGCompositeFrame* DD4hep::FrameControl::frame () const [inline]
Access to the top level frame.
Definition at line 53 of file FrameControl.h.
References m_frame.
const TGPicture * FrameControl::LoadPicture (const std::string & path) [virtual]
Helper: Load picture using path name.
Helper functions to fill the graphics pane(s)
Definition at line 67 of file FrameControl.cpp.
References DD4hep::ERROR, m_client, and DD4hep::printout().
Referenced by DD4hep::EventControl::OnBuild().
void FrameControl::OnBuild () [virtual]
User callback to add elements to the control.
Reimplemented in DD4hep::EventControl.
Definition at line 58 of file FrameControl.cpp.
Referenced by Build().
Member Data Documentation
TGClient* DD4hep::FrameControl::m_client [protected]
Reference to TEve manager.
Definition at line 41 of file FrameControl.h.
Referenced by client(), and LoadPicture().
TGCompositeFrame* DD4hep::FrameControl::m_frame [protected]
Reference to control's frame.
Definition at line 43 of file FrameControl.h.
Referenced by Build(), frame(), DD4hep::EventControl::OnBuild(), and ~FrameControl().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/FrameControl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/FrameControl.cpp