DD4hep: DD4hep::Simulation::Geant4HitData Class Reference
DD4hep::Simulation::Geant4HitData Class Reference
Base class for geant4 hit structures used by the default DDG4 sensitive detector implementations.
#include <Geant4Data.h>
Classes
class MonteCarloContrib
not persisten. ROOT cannot handle
Public Types
enum HitFlags {
HIT_KILLED_TRACK = 1<<0, HIT_SECONDARY_TRACK = 1<<1, HIT_NEW_TRACK = 1<<2, HIT_STARTED_INSIDE = 1<<10,
HIT_STARTED_SURFACE = 1<<11, HIT_STARTED_OUTSIDE = 1<<12, HIT_ENDED_INSIDE = 1<<13, HIT_ENDED_SURFACE = 1<<14,
HIT_ENDED_OUTSIDE = 1<<15
}
typedef MonteCarloContrib Contribution
typedef std::vector< MonteCarloContrib > Contributions
Public Member Functions
Geant4HitData ()
Default constructor.
virtual ~Geant4HitData ()
Default destructor.
Static Public Member Functions
static Contribution extractContribution (const G4Step *step)
Extract the MC contribution for a given hit from the step information.
static Contribution extractContribution (const G4Step *step, bool ApplyBirksLaw)
Extract the MC contribution for a given hit from the step information with BirksLaw option.
Public Attributes
long long int cellID
cellID
long flag
User flag to classify hits.
long g4ID
Original Geant 4 track identifier of the creating track (debugging)
dd4hep_ptr< DataExtension > extension
User data extension if required.
Detailed Description
Base class for geant4 hit structures used by the default DDG4 sensitive detector implementations.
Definition at line 108 of file Geant4Data.h.
Member Typedef Documentation
Contribution
typedef MonteCarloContrib DD4hep::Simulation::Geant4HitData::Contribution
Definition at line 198 of file Geant4Data.h.
Contributions
typedef std::vector<MonteCarloContrib> DD4hep::Simulation::Geant4HitData::Contributions
Definition at line 199 of file Geant4Data.h.
Member Enumeration Documentation
HitFlags
enum DD4hep::Simulation::Geant4HitData::HitFlags
Enumerator
HIT_KILLED_TRACK
HIT_SECONDARY_TRACK
HIT_NEW_TRACK
HIT_STARTED_INSIDE
HIT_STARTED_SURFACE
HIT_STARTED_OUTSIDE
HIT_ENDED_INSIDE
HIT_ENDED_SURFACE
HIT_ENDED_OUTSIDE
Definition at line 110 of file Geant4Data.h.
Constructor & Destructor Documentation
Geant4HitData()
Geant4HitData::Geant4HitData ()
Default constructor.
Definition at line 57 of file Geant4Data.cpp.
References DD4hep::InstanceCount::increment().
~Geant4HitData()
Geant4HitData::~Geant4HitData () virtual
Default destructor.
Definition at line 63 of file Geant4Data.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
extractContribution() [1/2]
Geant4HitData::Contribution Geant4HitData::extractContribution (const G4Step * step) static
Extract the MC contribution for a given hit from the step information.
Definition at line 68 of file Geant4Data.cpp.
References DD4hep::Simulation::Geant4StepHandler::postPosG4(), DD4hep::Simulation::Geant4StepHandler::prePosG4(), DD4hep::Simulation::Geant4StepHandler::totalEnergy(), DD4hep::Simulation::Geant4StepHandler::trackDef(), DD4hep::Simulation::Geant4StepHandler::trkEnergy(), DD4hep::Simulation::Geant4StepHandler::trkID(), DD4hep::Simulation::Geant4StepHandler::trkPdgID(), and DD4hep::Simulation::Geant4StepHandler::trkTime().
extractContribution() [2/2]
Geant4HitData::Contribution Geant4HitData::extractContribution (const G4Step * step, bool ApplyBirksLaw) static
Extract the MC contribution for a given hit from the step information with BirksLaw option.
Extract the MC contribution for a given hit from the step information with BirksLaw effect option.
Definition at line 79 of file Geant4Data.cpp.
References DD4hep::Simulation::Geant4StepHandler::doApplyBirksLaw(), DD4hep::Simulation::Geant4StepHandler::postPosG4(), DD4hep::Simulation::Geant4StepHandler::prePosG4(), DD4hep::Simulation::Geant4StepHandler::totalEnergy(), DD4hep::Simulation::Geant4StepHandler::trackDef(), DD4hep::Simulation::Geant4StepHandler::trkEnergy(), DD4hep::Simulation::Geant4StepHandler::trkID(), DD4hep::Simulation::Geant4StepHandler::trkPdgID(), and DD4hep::Simulation::Geant4StepHandler::trkTime().
Member Data Documentation
cellID
long long int DD4hep::Simulation::Geant4HitData::cellID
cellID
Definition at line 122 of file Geant4Data.h.
Referenced by DD4hep::Simulation::TrackerWeighted::extractHit(), DD4hep::Simulation::TrackerCombine::extractHit(), DD4hep::Simulation::Geant4DataDump::print(), and DD4hep::Simulation::Geant4EscapeCounter::process().
extension
dd4hep_ptr<DataExtension> DD4hep::Simulation::Geant4HitData::extension
User data extension if required.
Definition at line 131 of file Geant4Data.h.
flag
long DD4hep::Simulation::Geant4HitData::flag
User flag to classify hits.
Definition at line 124 of file Geant4Data.h.
Referenced by DD4hep::Simulation::TrackerWeighted::extractHit().
g4ID
long DD4hep::Simulation::Geant4HitData::g4ID
Original Geant 4 track identifier of the creating track (debugging)
Definition at line 126 of file Geant4Data.h.
Referenced by DD4hep::Simulation::TrackerWeighted::extractHit().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Data.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Data.cpp