DD4hep: DD4hep: DD4hep::Geometry::AlignmentEntry Class Reference
DD4hep::Geometry::AlignmentEntry Class Reference
Deprecated: Handle class describing an alignment entry.
#include <Objects.h>
Public Types
typedef Handle< TGeoPhysicalNode > Base
Public Member Functions
template<typename Q >
AlignmentEntry (const Handle< Q > &h)
Constructor to be used when reading the already parsed DOM tree.
AlignmentEntry (const std::string &path)
Constructor to be used when creating a new aligment entry.
int align (const Position &pos, bool check=false, double overlap=0.001)
Align the PhysicalNode (translation only).
int align (const RotationZYX &rot, bool check=false, double overlap=0.001)
Align the PhysicalNode (rotation only).
int align (const Position &pos, const RotationZYX &rot, bool check=false, double overlap=0.001)
Align the PhysicalNode (translation + rotation).
Detailed Description
Deprecated: Handle class describing an alignment entry.
Deprecated:
{Class representing an alignment entry}
Author:
M.Frank
Version:
1.0
Definition at line 420 of file Objects.h.
Member Typedef Documentation
typedef Handle<TGeoPhysicalNode> DD4hep::Geometry::AlignmentEntry::Base
Definition at line 422 of file Objects.h.
Constructor & Destructor Documentation
template<typename Q > DD4hep::Geometry::AlignmentEntry::AlignmentEntry (const Handle< Q > & h) [inline]
Constructor to be used when reading the already parsed DOM tree.
Definition at line 425 of file Objects.h.
DD4hep::Geometry::AlignmentEntry::AlignmentEntry (const std::string & path)
Constructor to be used when creating a new aligment entry.
Member Function Documentation
int AlignmentEntry::align (const Position & pos, const RotationZYX & rot, bool check = false, double overlap = 0.001)
Align the PhysicalNode (translation + rotation).
Definition at line 371 of file Objects.cpp.
References DD4hep::Handle< T >::isValid(), dd4hep::m, DD4hep::Handle< T >::m_element, and RAD_2_DEGREE.
int AlignmentEntry::align (const RotationZYX & rot, bool check = false, double overlap = 0.001)
Align the PhysicalNode (rotation only).
Definition at line 366 of file Objects.cpp.
References align().
int AlignmentEntry::align (const Position & pos, bool check = false, double overlap = 0.001)
Align the PhysicalNode (translation only).
Definition at line 361 of file Objects.cpp.
Referenced by align().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp