DD4hep: DD4hep::Simulation::Geant4FieldTrackingConstruction Class Reference
DD4hep::Simulation::Geant4FieldTrackingConstruction Class Reference
Detector construction action to perform the setup of the Geant4 tracking in magnetic fields.
Public Member Functions
Geant4FieldTrackingConstruction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4FieldTrackingConstruction ()
Default destructor.
void operator() ()
Phase action callback.
Public Member Functions inherited from DD4hep::Simulation::Geant4DetectorConstruction
Geant4DetectorConstruction (Geant4Context *context, const std::string &nam)
Standard Constructor.
virtual ~Geant4DetectorConstruction ()
Default destructor.
virtual void constructGeo (Geant4DetectorConstructionContext *ctxt)
Geometry construction callback. Called at "Construct()".
virtual void constructField (Geant4DetectorConstructionContext *ctxt)
Electromagnetic field construction callback. Called at "ConstructSDandField()".
virtual void constructSensitives (Geant4DetectorConstructionContext *ctxt)
Sensitive detector construction callback. Called at "ConstructSDandField()".
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Public Member Functions inherited from DD4hep::Simulation::Geant4FieldTrackingSetup
Geant4FieldTrackingSetup ()
Default constructor.
virtual ~Geant4FieldTrackingSetup ()
Default destructor.
virtual int execute (Geometry::LCDD &lcdd)
Perform the setup of the magnetic field tracking in Geant4.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Protected Attributes inherited from DD4hep::Simulation::Geant4FieldTrackingSetup
std::string eq_typ
Name of the G4Mag_EqRhs class.
std::string stepper_typ
Name of the G4MagIntegratorStepper class.
double min_chord_step
G4ChordFinder parameter: min_chord_step.
double delta_chord
G4ChordFinder parameter: delta.
double delta_one_step
G4FieldManager parameter: delta_one_step.
double delta_intersection
G4FieldManager parameter: delta_intersection.
double eps_min
G4PropagatorInField parameter: eps_min.
double eps_max
G4PropagatorInField parameter: eps_min.
double largest_step
G4PropagatorInField parameter: LargestAcceptableStep.
Detailed Description
Detector construction action to perform the setup of the Geant4 tracking in magnetic fields.
Geant4FieldTrackingSetupAction.
The phase action configures the Geant4FieldTrackingSetup base class using properties and then configures the Geant4 tracking in magnetic fields.
Author
M.Frank
Version
1.0
Definition at line 107 of file Geant4FieldTrackingSetup.cpp.
Constructor & Destructor Documentation
Geant4FieldTrackingConstruction()
Geant4FieldTrackingConstruction::Geant4FieldTrackingConstruction (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 280 of file Geant4FieldTrackingSetup.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::Simulation::Geant4FieldTrackingSetup::delta_chord, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_intersection, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_one_step, e, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_max, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_min, DD4hep::Simulation::Geant4FieldTrackingSetup::eq_typ, DD4hep::Simulation::Geant4FieldTrackingSetup::largest_step, DD4hep::Simulation::Geant4FieldTrackingSetup::min_chord_step, and DD4hep::Simulation::Geant4FieldTrackingSetup::stepper_typ.
~Geant4FieldTrackingConstruction()
virtual DD4hep::Simulation::Geant4FieldTrackingConstruction::~Geant4FieldTrackingConstruction () inline virtual
Default destructor.
Definition at line 117 of file Geant4FieldTrackingSetup.cpp.
Member Function Documentation
operator()()
void Geant4FieldTrackingConstruction::operator() ()
Phase action callback.
Post-track action callback.
Definition at line 295 of file Geant4FieldTrackingSetup.cpp.
References DD4hep::Simulation::Geant4Action::context(), DECLARE_GEANT4_SETUP, DECLARE_GEANT4ACTION, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_chord, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_intersection, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_one_step, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_max, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_min, DD4hep::Simulation::Geant4FieldTrackingSetup::eq_typ, DD4hep::Simulation::Geant4FieldTrackingSetup::execute(), DD4hep::INFO, DD4hep::Simulation::Geant4FieldTrackingSetup::largest_step, DD4hep::printout(), setup_fields(), and DD4hep::Simulation::Geant4FieldTrackingSetup::stepper_typ.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4FieldTrackingSetup.cpp