DD4hep: DD4hep::Conditions::ConditionsTextRepository Class Reference
DD4hep::Conditions::ConditionsTextRepository Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Forward declarations.
#include <ConditionsTextRepository.h>
Classes
class Entry
Public Types
typedef std::vector< Entry > Data
Public Member Functions
ConditionsTextRepository ()
Default constructor.
virtual ~ConditionsTextRepository ()
Default destructor.
int save (ConditionsManager m, const std::string &output) const
Save the textrepository to file.
int load (const std::string &input, Data &data) const
Load the textrepository from file and fill user passed data structory.
Detailed Description
Forward declarations.
Base class to be implemented by objects to listen on condition callbacks
Author
M.Frank
Version
1.0
Definition at line 42 of file ConditionsTextRepository.h.
Member Typedef Documentation
Data
typedef std::vector<Entry> DD4hep::Conditions::ConditionsTextRepository::Data
Definition at line 59 of file ConditionsTextRepository.h.
Constructor & Destructor Documentation
ConditionsTextRepository()
ConditionsTextRepository::ConditionsTextRepository ()
Default constructor.
Default constructor. Allocates resources.
Definition at line 40 of file ConditionsTextRepository.cpp.
~ConditionsTextRepository()
ConditionsTextRepository::~ConditionsTextRepository () virtual
Default destructor.
Definition at line 44 of file ConditionsTextRepository.cpp.
References _U, DD4hep::Conditions::ConditionsTextRepository::Entry::address, DD4hep::Conditions::Interna::ConditionObject::address, DD4hep::Conditions::Condition::address(), DD4hep::ALWAYS, DD4hep::XML::Element::append(), DD4hep::XML::Handle_t::attr(), DD4hep::XML::DocumentHandler::create(), e, DD4hep::except(), DD4hep::XML::Collection_t::for_each(), DD4hep::Conditions::ConditionsTextRepository::Entry::key, DD4hep::Conditions::Condition::key(), load(), DD4hep::NamedObject::name, DD4hep::Conditions::ConditionsTextRepository::Entry::name, DD4hep::Conditions::Condition::name(), DD4hep::XML::DocumentHandler::output(), DD4hep::printout(), and DD4hep::XML::Document::root().
Member Function Documentation
load()
int ConditionsTextRepository::load (const std::string & input, Data & data) const
Load the textrepository from file and fill user passed data structory.
Load the repository from file and fill user passed data structory.
Definition at line 231 of file ConditionsTextRepository.cpp.
save()
int ConditionsTextRepository::save (ConditionsManager m, const std::string & output) const
Save the textrepository to file.
Save the repository to file.
Write XML file with conditions addresses
Write fixed records with conditions addresses
Write fixed records with conditions addresses
Write records separated by ';' with conditions addresses
Definition at line 188 of file ConditionsTextRepository.cpp.
References _E, _T(), e, DD4hep::Conditions::ConditionsIOVPool::elements, DD4hep::Conditions::ConditionsManager::iovPool(), DD4hep::Conditions::ConditionsManager::iovTypesUsed(), and DD4hep::Conditions::ConditionsPool::select_all().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsTextRepository.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsTextRepository.cpp