DD4hep: DD4hep::LCDDLoad Class Reference
DD4hep::LCDDLoad Class Reference
Data implementation class of the LCDD interface.
#include <DD4hep/LCDDLoad.h>
Public Member Functions
virtual void processXML (const std::string &fname, XML::UriReader *entity_resolver=0)
Process XML unit and adopt all data from source structure.
virtual void processXML (const XML::Handle_t &base, const std::string &fname, XML::UriReader *entity_resolver=0)
Process XML unit and adopt all data from source structure.
virtual void processXMLElement (const std::string &msg_source, const XML::Handle_t &root)
Process a given DOM (sub-) tree.
virtual void processXMLElement (const XML::Handle_t &root, LCDDBuildType type)
Process a given DOM (sub-) tree.
Protected Member Functions
LCDDLoad (Geometry::LCDD *lcdd)
Default constructor.
virtual ~LCDDLoad ()
Default destructor.
Protected Attributes
Geometry::LCDD * m_lcdd
Reference to the LCDD instance.
Friends
class Geometry::LCDD
Detailed Description
Data implementation class of the LCDD interface.
Author
M.Frank
Version
1.0
Definition at line 42 of file LCDDLoad.h.
Constructor & Destructor Documentation
LCDDLoad()
LCDDLoad::LCDDLoad (Geometry::LCDD * lcdd) protected
Default constructor.
Definition at line 39 of file LCDDLoad.cpp.
~LCDDLoad()
LCDDLoad::~LCDDLoad () protected virtual
Default destructor.
Standard destructor.
Definition at line 43 of file LCDDLoad.cpp.
Member Function Documentation
processXML() [1/2]
void LCDDLoad::processXML (const std::string & fname, XML::UriReader * entity_resolver = 0) virtual
Process XML unit and adopt all data from source structure.
Definition at line 47 of file LCDDLoad.cpp.
References DD4hep::XML::_toString(), e, handle(), load(), processXMLElement(), and DD4hep::XML::Document::root().
Referenced by extract(), and DD4hep::Geometry::LCDDImp::fromXML().
processXML() [2/2]
void LCDDLoad::processXML (const XML::Handle_t & base, const std::string & fname, XML::UriReader * entity_resolver = 0) virtual
Process XML unit and adopt all data from source structure.
Definition at line 66 of file LCDDLoad.cpp.
References DD4hep::XML::_toString(), e, handle(), load(), processXMLElement(), and DD4hep::XML::Document::root().
processXMLElement() [1/2]
void LCDDLoad::processXMLElement (const std::string & msg_source, const XML::Handle_t & root) virtual
Process a given DOM (sub-) tree.
Definition at line 85 of file LCDDLoad.cpp.
References handle(), m_lcdd, DD4hep::PluginDebug::missingFactory(), and DD4hep::XML::Handle_t::tag().
Referenced by processXML().
processXMLElement() [2/2]
void LCDDLoad::processXMLElement (const XML::Handle_t & root, LCDDBuildType type) virtual
Process a given DOM (sub-) tree.
Definition at line 105 of file LCDDLoad.cpp.
References handle(), m_lcdd, DD4hep::PluginDebug::missingFactory(), and DD4hep::XML::Handle_t::tag().
Friends And Related Function Documentation
Geometry::LCDD
friend class Geometry::LCDD friend
Definition at line 44 of file LCDDLoad.h.
Member Data Documentation
m_lcdd
Geometry::LCDD* DD4hep::LCDDLoad::m_lcdd protected
Reference to the LCDD instance.
Definition at line 48 of file LCDDLoad.h.
Referenced by processXMLElement().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/LCDDLoad.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/LCDDLoad.cpp