DD4hep: DD4hep: DD4hep::Calo2DProjection Class Reference
DD4hep::Calo2DProjection Class Reference
2D projection operator for calorimeters
#include <Calo2DProjection.h>
Public Member Functions
Calo2DProjection (Display *eve, const std::string &name)
Initializing constructor.
virtual ~Calo2DProjection ()
Default destructor.
virtual View & Build (TEveWindow *slot)
Build the projection view and map it to the given slot.
virtual void ConfigureGeometry (const DisplayConfiguration::ViewConfig &config)
Configure a single geometry view.
virtual void ConfigureEvent (const DisplayConfiguration::ViewConfig &config)
Configure a single event scene view.
void ImportGeoTopics (const std::string &title)
Call to import geometry topics.
ClassDef (Calo2DProjection, 0)
Root implementation macro.
Detailed Description
2D projection operator for calorimeters
Definition at line 36 of file Calo2DProjection.h.
Constructor & Destructor Documentation
DD4hep::Calo2DProjection::Calo2DProjection (Display * eve, const std::string & name)
Initializing constructor.
Calo2DProjection::~Calo2DProjection () [virtual]
Default destructor.
Definition at line 41 of file Calo2DProjection.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
View & Calo2DProjection::Build (TEveWindow * slot) [virtual]
Build the projection view and map it to the given slot.
Reimplemented from DD4hep::View.
Definition at line 46 of file Calo2DProjection.cpp.
References DD4hep::Projection::AddAxis(), DD4hep::View::AddToGlobalItems(), DD4hep::View::CreateEventScene(), DD4hep::View::CreateGeoScene(), DD4hep::Projection::CreateRhoPhiProjection(), DD4hep::Projection::Map(), and DD4hep::View::name().
DD4hep::Calo2DProjection::ClassDef (Calo2DProjection , 0)
Root implementation macro.
Reimplemented from DD4hep::Projection.
void Calo2DProjection::ConfigureEvent (const DisplayConfiguration::ViewConfig & config) [virtual]
Configure a single event scene view.
Reimplemented from DD4hep::View.
Definition at line 121 of file Calo2DProjection.cpp.
void Calo2DProjection::ConfigureGeometry (const DisplayConfiguration::ViewConfig & config) [virtual]
Configure a single geometry view.
Reimplemented from DD4hep::View.
Definition at line 55 of file Calo2DProjection.cpp.
References DD4hep::Display::CalodataContext::calo3D, DD4hep::DisplayConfiguration::Config::Values::calo3d, DD4hep::DisplayConfiguration::CALODATA, DD4hep::DisplayConfiguration::Defaults::color, DD4hep::Display::CalodataContext::config, DD4hep::DisplayConfiguration::Config::data, DD4hep::Annotation::DefaultMargin(), DD4hep::Annotation::DefaultTextSize(), DD4hep::DisplayConfiguration::DETELEMENT, DD4hep::DisplayConfiguration::Calo3D::dz, DD4hep::DisplayConfiguration::Calo3D::emax, DD4hep::Display::GetCaloHistogram(), DD4hep::Display::GetGeoTopic(), DD4hep::DisplayConfiguration::Config::hits, DD4hep::INFO, DD4hep::View::m_eve, DD4hep::View::m_geoScene, DD4hep::Projection::m_projMgr, DD4hep::View::name(), DD4hep::DisplayConfiguration::Config::name, DD4hep::printout(), DD4hep::DisplayConfiguration::Calo3D::rmin, DD4hep::Display::CalodataContext::slice, DD4hep::DisplayConfiguration::ViewConfig::subdetectors, DD4hep::DisplayConfiguration::Calo3D::towerH, DD4hep::DisplayConfiguration::Config::type, DD4hep::DisplayConfiguration::Config::use, and DD4hep::View::viewer().
void DD4hep::Calo2DProjection::ImportGeoTopics (const std::string & title) [virtual]
Call to import geometry topics.
Reimplemented from DD4hep::View.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/Calo2DProjection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/Calo2DProjection.cpp