DD4hep: DD4hep::Conditions::ConditionsPoolInsert Class Reference
DD4hep::Conditions::ConditionsPoolInsert Class Reference
Helper to insert objects into a conditions pool.
#include <ConditionsSelectors.h>
Public Member Functions
ConditionsPoolInsert (ConditionsPool &p)
void operator() (object_t *o) const
void operator() (const cond_t &o) const
void operator() (const mapentry_t &o) const
void operator() (const ptr_mapentry_t &o) const
Private Attributes
ConditionsPool & pool
Additional Inherited Members
Public Types inherited from DD4hep::Conditions::Cond__Oper
typedef Condition cond_t
typedef Condition::Object object_t
typedef std::pair< const Condition::key_type, Condition > mapentry_t
typedef std::pair< const Condition::key_type, object_t * > ptr_mapentry_t
Detailed Description
Helper to insert objects into a conditions pool.
Author
M.Frank
Version
1.0
Definition at line 39 of file ConditionsSelectors.h.
Constructor & Destructor Documentation
ConditionsPoolInsert()
DD4hep::Conditions::ConditionsPoolInsert::ConditionsPoolInsert (ConditionsPool & p) inline
Definition at line 42 of file ConditionsSelectors.h.
Member Function Documentation
operator()() [1/4]
void DD4hep::Conditions::ConditionsPoolInsert::operator() (object_t * o) const inline
Definition at line 43 of file ConditionsSelectors.h.
References DD4hep::Conditions::ConditionsPool::insert().
operator()() [2/4]
void DD4hep::Conditions::ConditionsPoolInsert::operator() (const cond_t & o) const inline
Definition at line 44 of file ConditionsSelectors.h.
References DD4hep::Conditions::ConditionsPool::insert(), and DD4hep::Handle< T >::ptr().
operator()() [3/4]
void DD4hep::Conditions::ConditionsPoolInsert::operator() (const mapentry_t & o) const inline
Definition at line 45 of file ConditionsSelectors.h.
operator()() [4/4]
void DD4hep::Conditions::ConditionsPoolInsert::operator() (const ptr_mapentry_t & o) const inline
Definition at line 46 of file ConditionsSelectors.h.
Member Data Documentation
pool
ConditionsPool& DD4hep::Conditions::ConditionsPoolInsert::pool private
Definition at line 40 of file ConditionsSelectors.h.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsSelectors.h