DD4hep: DD4hep: DD4hep::Simulation::Geant4DetectorSensitivesConstruction Class Reference
DD4hep::Simulation::Geant4DetectorSensitivesConstruction Class Reference
[DD4hep::Simulation components, classes and objects]
Class to create Geant4 detector geometry from TGeo representation in memory.
Public Member Functions
Geant4DetectorSensitivesConstruction (Geant4Context *ctxt, const std::string &nam)
Initializing constructor for DDG4.
virtual ~Geant4DetectorSensitivesConstruction ()
Default destructor.
void constructSensitives (Geant4DetectorConstructionContext *ctxt)
Sensitives construction callback. Called at "ConstructSDandField()".
Detailed Description
Class to create Geant4 detector geometry from TGeo representation in memory.
On demand the sensitive detectors are created and attached to all sensitive volumes. The relevant callback is executed when the call to ConstructSDandField() of the corresponding G4VUserDetectorConstruction instance is called. The call is thread-local!
Author:
M.Frank
Version:
1.0
Definition at line 35 of file Geant4DetectorSensitivesConstruction.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4DetectorSensitivesConstruction::Geant4DetectorSensitivesConstruction (Geant4Context * ctxt, const std::string & nam)
Initializing constructor for DDG4.
Geant4DetectorSensitivesConstruction::~Geant4DetectorSensitivesConstruction () [virtual]
Default destructor.
Definition at line 78 of file Geant4DetectorSensitivesConstruction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4DetectorSensitivesConstruction::constructSensitives (Geant4DetectorConstructionContext * ctxt) [virtual]
Sensitives construction callback. Called at "ConstructSDandField()".
Sensitive detector construction callback. Called at "ConstructSDandField()".
Reimplemented from DD4hep::Simulation::Geant4DetectorConstruction.
Definition at line 83 of file Geant4DetectorSensitivesConstruction.cpp.
References DD4hep::Simulation::Geant4GeometryInfo::g4Volumes, DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Simulation::Geant4DetectorConstructionContext::lcdd, DD4hep::Handle< T >::name(), DD4hep::Simulation::Geant4Action::print(), DD4hep::Simulation::Geant4Mapping::ptr(), DD4hep::Simulation::Geant4GeometryInfo::sensitives, DD4hep::Simulation::Geant4DetectorConstructionContext::setSensitiveDetector(), and DD4hep::Geometry::SensitiveDetector::type().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4DetectorSensitivesConstruction.cpp