DD4hep: DD4hep: DD4hep::Simulation::Geant4EventSeed Class Reference
DD4hep::Simulation::Geant4EventSeed Class Reference
#include <Geant4EventSeed.h>
Public Member Functions
Geant4EventSeed (Geant4Context *, const std::string &)
Standard constructor with initializing arguments.
virtual ~Geant4EventSeed ()
Default destructor.
void begin (const G4Run *)
begin-of-run callback
void beginEvent (const G4Event *)
begin-of-event callback
Protected Attributes
unsigned int m_initialSeed
unsigned int m_runID
std::string m_type
bool m_initialised
Detailed Description
Definition at line 40 of file Geant4EventSeed.h.
Constructor & Destructor Documentation
Geant4EventSeed::Geant4EventSeed (Geant4Context * c, const std::string & typ)
Standard constructor with initializing arguments.
Standard constructor.
Definition at line 35 of file Geant4EventSeed.cpp.
References begin(), beginEvent(), DD4hep::Simulation::Geant4EventActionSequence::callAtBegin(), DD4hep::Simulation::Geant4RunActionSequence::callAtBegin(), DD4hep::Simulation::Geant4Action::eventAction(), DD4hep::InstanceCount::increment(), and DD4hep::Simulation::Geant4Action::runAction().
Geant4EventSeed::~Geant4EventSeed () [virtual]
Default destructor.
Definition at line 47 of file Geant4EventSeed.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4EventSeed::begin (const G4Run * run) [virtual]
begin-of-run callback
Reimplemented from DD4hep::Simulation::Geant4RunAction.
Definition at line 52 of file Geant4EventSeed.cpp.
References DD4hep::Simulation::Geant4Random::engine(), DD4hep::INFO, DD4hep::Simulation::Geant4Random::instance(), m_initialised, m_initialSeed, m_runID, m_type, and DD4hep::printout().
Referenced by Geant4EventSeed().
void Geant4EventSeed::beginEvent (const G4Event * evt)
begin-of-event callback
Definition at line 66 of file Geant4EventSeed.cpp.
References DD4hep::DEBUG, DD4hep::Simulation::hash(), DD4hep::INFO, DD4hep::Simulation::Geant4Random::instance(), m_initialSeed, m_runID, m_type, DD4hep::printLevel(), DD4hep::printout(), DD4hep::Simulation::Geant4Random::setSeed(), and DD4hep::Simulation::Geant4Random::showStatus().
Referenced by Geant4EventSeed().
Member Data Documentation
bool DD4hep::Simulation::Geant4EventSeed::m_initialised [protected]
Definition at line 46 of file Geant4EventSeed.h.
Referenced by begin().
unsigned int DD4hep::Simulation::Geant4EventSeed::m_initialSeed [protected]
Definition at line 43 of file Geant4EventSeed.h.
Referenced by begin(), and beginEvent().
unsigned int DD4hep::Simulation::Geant4EventSeed::m_runID [protected]
Definition at line 44 of file Geant4EventSeed.h.
Referenced by begin(), and beginEvent().
std::string DD4hep::Simulation::Geant4EventSeed::m_type [protected]
Definition at line 45 of file Geant4EventSeed.h.
Referenced by begin(), and beginEvent().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4EventSeed.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4EventSeed.cpp