DD4hep: DD4hep::Simulation::Geant4EventReaderHepEvt Class Reference
DD4hep::Simulation::Geant4EventReaderHepEvt Class Reference
DD4hep::Simulation components, classes and objects
Class to populate Geant4 primaries from StdHep files.
Public Member Functions
Geant4EventReaderHepEvt (const std::string &nam, int format)
Initializing constructor.
virtual ~Geant4EventReaderHepEvt ()
Default destructor.
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, std::vector< Particle *> &particles)
Read an event and fill a vector of MCParticles.
virtual EventReaderStatus moveToEvent (int event_number)
skipEvents if required
virtual EventReaderStatus skipEvent ()
Skip event. To be implemented for sequential sources.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventReader
Geant4EventReader (const std::string &nam)
Initializing constructor.
virtual ~Geant4EventReader ()
Default destructor.
const std::string & name () const
File name.
bool hasDirectAccess () const
Flag if direct event access (by event sequence number) is supported (Default: false)
int currentEventNumber () const
return current Event Number
virtual EventReaderStatus readParticles (int event_number, Vertex &primary_vertex, Particles &particles)=0
Read an event and fill a vector of MCParticles.
Protected Attributes
std::ifstream m_input
int m_format
Protected Attributes inherited from DD4hep::Simulation::Geant4EventReader
std::string m_name
File name to be opened and read.
bool m_directAccess
Flag if direct event access is supported. To be explicitly set by subclass constructors.
int m_currEvent
Current event number.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4EventReader
enum EventReaderStatus {
EVENT_READER_ERROR =0, EVENT_READER_OK =1, EVENT_READER_NO_DIRECT =2, EVENT_READER_NO_PRIMARIES =4,
EVENT_READER_NO_FACTORY =6, EVENT_READER_IO_ERROR =8
}
Status codes of the event reader object. Anything with NOT low-bit set is an error.
typedef Geant4Vertex Vertex
typedef Geant4Particle Particle
typedef std::vector< Particle * > Particles
Detailed Description
Class to populate Geant4 primaries from StdHep files.
Class to populate Geant4 primary particles and vertices from a file in HEPEvt format (ASCII)
Author
P.Kostka (main author)
M.Frank (code reshuffeling into new DDG4 scheme)
Version
1.0
Definition at line 37 of file Geant4EventReaderHepEvt.cpp.
Constructor & Destructor Documentation
Geant4EventReaderHepEvt()
Geant4EventReaderHepEvt::Geant4EventReaderHepEvt (const std::string & nam, int format) explicit
Initializing constructor.
Definition at line 108 of file Geant4EventReaderHepEvt.cpp.
~Geant4EventReaderHepEvt()
Geant4EventReaderHepEvt::~Geant4EventReaderHepEvt () virtual
Default destructor.
Definition at line 121 of file Geant4EventReaderHepEvt.cpp.
References m_input.
Member Function Documentation
moveToEvent()
Geant4EventReader::EventReaderStatus Geant4EventReaderHepEvt::moveToEvent (int event_number) virtual
skipEvents if required
Reimplemented from DD4hep::Simulation::Geant4EventReader.
Definition at line 127 of file Geant4EventReaderHepEvt.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::INFO, DD4hep::Simulation::Geant4EventReader::m_currEvent, DD4hep::printout(), readParticles(), and DD4hep::Simulation::HepMC::vertex().
readParticles()
Geant4EventReader::EventReaderStatus Geant4EventReaderHepEvt::readParticles (int event_number, Vertex & primary_vertex, std::vector< Particle *> & particles) virtual
Read an event and fill a vector of MCParticles.
Definition at line 147 of file Geant4EventReaderHepEvt.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_IO_ERROR, DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, dd4hep::GeV, HEPEvtShort, DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4EventReader::m_currEvent, m_format, m_input, DD4hep::Simulation::Geant4Particle::mass, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::Simulation::Geant4Particle::pex, DD4hep::Simulation::Geant4Particle::pey, DD4hep::Simulation::Geant4Particle::pez, DD4hep::Simulation::Geant4Particle::properTime, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::ReferenceBitMask< T >::set(), DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::time, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
Referenced by moveToEvent().
skipEvent()
virtual EventReaderStatus DD4hep::Simulation::Geant4EventReaderHepEvt::skipEvent () inline virtual
Skip event. To be implemented for sequential sources.
Reimplemented from DD4hep::Simulation::Geant4EventReader.
Definition at line 53 of file Geant4EventReaderHepEvt.cpp.
References DD4hep::Simulation::Geant4EventReader::EVENT_READER_OK.
Member Data Documentation
m_format
int DD4hep::Simulation::Geant4EventReaderHepEvt::m_format protected
Definition at line 41 of file Geant4EventReaderHepEvt.cpp.
Referenced by readParticles().
m_input
std::ifstream DD4hep::Simulation::Geant4EventReaderHepEvt::m_input protected
Definition at line 40 of file Geant4EventReaderHepEvt.cpp.
Referenced by readParticles(), and ~Geant4EventReaderHepEvt().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4EventReaderHepEvt.cpp