DD4hep: DD4hep::Simulation::Geant4SensDet Class Reference
DD4hep::Simulation::Geant4SensDet Class Reference
DD4hep::Simulation components, classes and objects
Concrete implementation of the G4VSensitiveDetector calling the registered sequence object.
Public Member Functions
Geant4SensDet (const std::string &nam, Geometry::LCDD &lcdd)
Constructor. The detector element is identified by the name.
virtual ~Geant4SensDet ()
Destructor.
G4String GetName () const
Overload to avoid ambiguity between G4VSensitiveDetector and G4VSDFilter.
virtual std::string path () const
G4VSensitiveDetector internals: Access to the detector path name.
virtual std::string fullPath () const
G4VSensitiveDetector internals: Access to the detector path name.
virtual bool isActive () const
Is the detector active?
virtual G4int GetCollectionID (G4int i)
This is a utility method which returns the hits collection ID.
virtual G4VReadOutGeometry * readoutGeometry () const
Access to the readout geometry of the sensitive detector.
virtual SensitiveDetector sensitiveDetector () const
Access to the LCDD sensitive detector handle.
virtual const std::string & sensitiveType () const
Access to the sensitive type of the detector.
virtual G4bool Accept (const G4Step *step) const
Callback if the sequence should be accepted or filtered off.
virtual void Initialize (G4HCofThisEvent *hce)
Method invoked at the begining of each event.
virtual void EndOfEvent (G4HCofThisEvent *hce)
Method invoked at the end of each event.
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *hist)
Method for generating hit(s) using the information of G4Step object.
virtual void clear ()
G4VSensitiveDetector interface: Method invoked if the event was aborted.
virtual size_t defineCollection (const std::string &coll)
Initialize the usage of a hit collection. Returns the collection identifier.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Public Member Functions inherited from DD4hep::Simulation::RefCountedSequence< Geant4SensDetActionSequence >
RefCountedSequence ()
Default constructor.
RefCountedSequence (Geant4SensDetActionSequence *seq)
Initializing constructor.
virtual ~RefCountedSequence ()
Default destructor.
void _aquire (Geant4SensDetActionSequence *s)
void _release ()
Protected Attributes
SensitiveDetector m_sensitive
Access to the geant4 sensitive detector handle.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4ActionSD
typedef Geometry::SensitiveDetector SensitiveDetector
Definition: Sensitive detector type.
Public Types inherited from DD4hep::Simulation::RefCountedSequence< Geant4SensDetActionSequence >
typedef RefCountedSequence< Geant4SensDetActionSequence > Base
Public Attributes inherited from DD4hep::Simulation::RefCountedSequence< Geant4SensDetActionSequence >
Geant4SensDetActionSequence * m_sequence
Protected Member Functions inherited from DD4hep::Simulation::Geant4ActionSD
Geant4ActionSD (const std::string &name)
Standard action constructor.
virtual ~Geant4ActionSD ()
Default destructor.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Concrete implementation of the G4VSensitiveDetector calling the registered sequence object.
Author
M.Frank
Version
1.0
Definition at line 69 of file Geant4SensDet.cpp.
Constructor & Destructor Documentation
Geant4SensDet()
DD4hep::Simulation::Geant4SensDet::Geant4SensDet (const std::string & nam, Geometry::LCDD & lcdd) inline
Constructor. The detector element is identified by the name.
Definition at line 79 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::_aquire(), DD4hep::Simulation::Geant4Kernel::getOutputLevel(), DD4hep::Simulation::Geant4Kernel::instance(), DD4hep::Simulation::RefCountedSequence< T >::m_sequence, DD4hep::Simulation::Geant4ActionContainer::sensitiveAction(), DD4hep::Geometry::LCDD::sensitiveDetector(), DD4hep::Simulation::Geant4Kernel::thread_self(), DD4hep::Simulation::Geant4Kernel::worker(), and DD4hep::Simulation::Geant4ActionContainer::workerContext().
~Geant4SensDet()
virtual DD4hep::Simulation::Geant4SensDet::~Geant4SensDet () inline virtual
Destructor.
Definition at line 95 of file Geant4SensDet.cpp.
Member Function Documentation
Accept()
virtual G4bool DD4hep::Simulation::Geant4SensDet::Accept (const G4Step * step) const inline virtual
Callback if the sequence should be accepted or filtered off.
Definition at line 121 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::m_sequence.
clear()
virtual void DD4hep::Simulation::Geant4SensDet::clear () inline virtual
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Definition at line 133 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::m_sequence.
defineCollection()
virtual size_t DD4hep::Simulation::Geant4SensDet::defineCollection (const std::string & coll) inline virtual
Initialize the usage of a hit collection. Returns the collection identifier.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 136 of file Geant4SensDet.cpp.
References DD4hep::except().
EndOfEvent()
virtual void DD4hep::Simulation::Geant4SensDet::EndOfEvent (G4HCofThisEvent * hce) inline virtual
Method invoked at the end of each event.
Definition at line 127 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::m_sequence.
fullPath()
virtual std::string DD4hep::Simulation::Geant4SensDet::fullPath () const inline virtual
G4VSensitiveDetector internals: Access to the detector path name.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 103 of file Geant4SensDet.cpp.
GetCollectionID()
virtual G4int DD4hep::Simulation::Geant4SensDet::GetCollectionID (G4int i) inline virtual
This is a utility method which returns the hits collection ID.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 109 of file Geant4SensDet.cpp.
GetName()
G4String DD4hep::Simulation::Geant4SensDet::GetName () const inline
Overload to avoid ambiguity between G4VSensitiveDetector and G4VSDFilter.
Definition at line 97 of file Geant4SensDet.cpp.
Initialize()
virtual void DD4hep::Simulation::Geant4SensDet::Initialize (G4HCofThisEvent * hce) inline virtual
Method invoked at the begining of each event.
Definition at line 124 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::m_sequence.
isActive()
virtual bool DD4hep::Simulation::Geant4SensDet::isActive () const inline virtual
Is the detector active?
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 106 of file Geant4SensDet.cpp.
path()
virtual std::string DD4hep::Simulation::Geant4SensDet::path () const inline virtual
G4VSensitiveDetector internals: Access to the detector path name.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 100 of file Geant4SensDet.cpp.
ProcessHits()
virtual G4bool DD4hep::Simulation::Geant4SensDet::ProcessHits (G4Step * step, G4TouchableHistory * hist) inline virtual
Method for generating hit(s) using the information of G4Step object.
Definition at line 130 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::m_sequence.
readoutGeometry()
virtual G4VReadOutGeometry* DD4hep::Simulation::Geant4SensDet::readoutGeometry () const inline virtual
Access to the readout geometry of the sensitive detector.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 112 of file Geant4SensDet.cpp.
sensitiveDetector()
virtual SensitiveDetector DD4hep::Simulation::Geant4SensDet::sensitiveDetector () const inline virtual
Access to the LCDD sensitive detector handle.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 115 of file Geant4SensDet.cpp.
sensitiveType()
virtual const std::string& DD4hep::Simulation::Geant4SensDet::sensitiveType () const inline virtual
Access to the sensitive type of the detector.
Implements DD4hep::Simulation::Geant4ActionSD.
Definition at line 118 of file Geant4SensDet.cpp.
References DD4hep::Simulation::RefCountedSequence< T >::m_sequence.
Member Data Documentation
m_sensitive
SensitiveDetector DD4hep::Simulation::Geant4SensDet::m_sensitive protected
Access to the geant4 sensitive detector handle.
Definition at line 76 of file Geant4SensDet.cpp.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4SensDet.cpp