DD4hep: DD4hep: DD4hep::CaloLego Class Reference
DD4hep::CaloLego Class Reference
Lego plot for calorimeter energy deposits.
#include <CaloLego.h>
Public Member Functions
CaloLego (Display *eve, const std::string &name)
Initializing constructor.
virtual ~CaloLego ()
Default destructor.
virtual View & Build (TEveWindow *slot)
Build the projection view and map it to the given slot.
virtual void ConfigureGeometry (const DisplayConfiguration::ViewConfig &config)
Configure a single geometry view.
virtual void ConfigureEvent (const DisplayConfiguration::ViewConfig &config)
Configure a single event scene view.
void ImportGeoTopics (const std::string &title)
Call to import geometry topics.
ClassDef (CaloLego, 0)
Root implementation macro.
Private Attributes
Display::CalodataContext m_data
Detailed Description
Lego plot for calorimeter energy deposits.
Definition at line 36 of file CaloLego.h.
Constructor & Destructor Documentation
DD4hep::CaloLego::CaloLego (Display * eve, const std::string & name)
Initializing constructor.
CaloLego::~CaloLego () [virtual]
Default destructor.
Definition at line 46 of file CaloLego.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
View & CaloLego::Build (TEveWindow * slot) [virtual]
Build the projection view and map it to the given slot.
Reimplemented from DD4hep::View.
Definition at line 52 of file CaloLego.cpp.
References DD4hep::View::AddToGlobalItems(), DD4hep::View::CreateGeoScene(), DD4hep::View::Map(), and DD4hep::View::name().
DD4hep::CaloLego::ClassDef (CaloLego , 0)
Root implementation macro.
Reimplemented from DD4hep::View.
void CaloLego::ConfigureEvent (const DisplayConfiguration::ViewConfig & config) [virtual]
Configure a single event scene view.
Reimplemented from DD4hep::View.
Definition at line 108 of file CaloLego.cpp.
References DD4hep::Display::CalodataContext::config, DD4hep::Display::CalodataContext::eveHist, DD4hep::Display::GetCaloHistogram(), DD4hep::INFO, m_data, DD4hep::View::m_eve, DD4hep::View::name(), DD4hep::printout(), DD4hep::DisplayConfiguration::ViewConfig::subdetectors, and DD4hep::DisplayConfiguration::Config::use.
void CaloLego::ConfigureGeometry (const DisplayConfiguration::ViewConfig & config) [virtual]
Configure a single geometry view.
Reimplemented from DD4hep::View.
Definition at line 59 of file CaloLego.cpp.
References DD4hep::DisplayConfiguration::Config::Values::calodata, DD4hep::Display::CalodataContext::caloViz, DD4hep::DisplayConfiguration::Defaults::color, DD4hep::Display::CalodataContext::config, DD4hep::DisplayConfiguration::Config::data, DD4hep::Annotation::DefaultMargin(), DD4hep::Annotation::DefaultTextSize(), DD4hep::Display::CalodataContext::eveHist, DD4hep::Display::GetCaloHistogram(), DD4hep::View::ImportGeo(), m_data, DD4hep::View::m_eve, DD4hep::DisplayConfiguration::ViewConfig::subdetectors, DD4hep::DisplayConfiguration::Calodata::threshold, DD4hep::DisplayConfiguration::Config::use, and DD4hep::View::viewer().
void DD4hep::CaloLego::ImportGeoTopics (const std::string & title) [virtual]
Call to import geometry topics.
Reimplemented from DD4hep::View.
Member Data Documentation
Display::CalodataContext DD4hep::CaloLego::m_data [private]
Definition at line 37 of file CaloLego.h.
Referenced by ConfigureEvent(), and ConfigureGeometry().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/CaloLego.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/CaloLego.cpp