DD4hep: DD4hep: DD4hep::Handle< T > Class Template Reference
DD4hep::Handle< T > Class Template Reference
[DD4hep::Geometry components, classes and objects]
Handle: a templated class like a shared pointer, which allows specialized access to tgeometry objects.
#include <Handle.h>
Public Types
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object).
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Static Public Member Functions
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
template<typename T>
class DD4hep::Handle< T >
Handle: a templated class like a shared pointer, which allows specialized access to tgeometry objects.
The Handle is the base class to access all objects in DD4hep. Objects, which consist ONLY of data are NEVER passed directly. They are ALWAYS passed using handles. Such handles are 'handy' ;-). Assignment is to and from different handles is possible using concrete type checking.
Real benefits can result from sophisticated handle subclasses, which can implement any desired user functionality with out compromising the object's data content. This leads to very flexible implementations, where the same data may be shared by many handle implementations providing different functionality to the clients.
In this sense, is the consequent use of handles to access data nothing else then the consequent application of component oriented programming using local objects from the heap.
Note: If you cannot live with this approach, it is better you get hands of this software package, because you will try to consequently fight the framework, which will frustrate you (and also me).
Author:
M.Frank
Version:
1.0
Definition at line 87 of file Handle.h.
Member Typedef Documentation
template<typename T> typedef Handle<Implementation> DD4hep::Handle< T >::handle_t
Declaration of 'self'.
Definition at line 93 of file Handle.h.
template<typename T> typedef T DD4hep::Handle< T >::Implementation
Extern accessible definition of the contained element type.
Type definitions and class specific abbreviations and forward declarations
Reimplemented in DD4hep::Geometry::Solid_type< T >, DD4hep::Geometry::Solid_type< TGeoArb8 >, DD4hep::Geometry::Solid_type< TGeoSphere >, DD4hep::Geometry::Solid_type< TGeoHalfSpace >, DD4hep::Geometry::Solid_type< TGeoTorus >, DD4hep::Geometry::Solid_type< TGeoParaboloid >, DD4hep::Geometry::Solid_type< TGeoShape >, DD4hep::Geometry::Solid_type< TGeoEltu >, DD4hep::Geometry::Solid_type< TGeoPgon >, DD4hep::Geometry::Solid_type< TGeoCone >, DD4hep::Geometry::Solid_type< TGeoTrd2 >, DD4hep::Geometry::Solid_type< TGeoPcon >, DD4hep::Geometry::Solid_type< TGeoCompositeShape >, DD4hep::Geometry::Solid_type< TGeoConeSeg >, DD4hep::Geometry::Solid_type< TGeoTrap >, DD4hep::Geometry::Solid_type< TGeoHype >, DD4hep::Geometry::Solid_type< MyConeSeg >, and DD4hep::Geometry::Solid_type< TGeoBBox >.
Definition at line 91 of file Handle.h.
Constructor & Destructor Documentation
template<typename T> DD4hep::Handle< T >::Handle () [inline]
Defaulot constructor.
Definition at line 98 of file Handle.h.
template<typename T> DD4hep::Handle< T >::Handle (T * e) [inline]
Initializing constructor from pointer.
Definition at line 100 of file Handle.h.
template<typename T> DD4hep::Handle< T >::Handle (const Handle< T > & e)
Copy constructor.
template<typename T> template<typename Q > DD4hep::Handle< T >::Handle (Q * e) [inline]
Initializing constructor from unrelated pointer with type checking.
Definition at line 104 of file Handle.h.
template<typename T> template<typename Q > DD4hep::Handle< T >::Handle (const Handle< Q > & e) [inline]
Initializing constructor from unrelated handle with type checking.
Definition at line 107 of file Handle.h.
Member Function Documentation
template<typename T> template<typename Q > Q* DD4hep::Handle< T >::_ptr () const [inline]
Access to an unrelated object type.
Definition at line 153 of file Handle.h.
Referenced by DD4hep::Geometry::Volume::setMaterial().
template<typename T > T * DD4hep::Handle< T >::access () const [inline]
Checked object access. Throws invalid handle runtime exception.
Definition at line 41 of file Handle.inl.
References DD4hep::invalidHandleError(), and DD4hep::Handle< T >::m_element.
Referenced by DD4hep::Geometry::DetElement::add(), DD4hep::Geometry::World::alignmentsLoader(), DD4hep::Geometry::WaferGridXY::cellDimensions(), DD4hep::Geometry::PolarGridRPhi2::cellDimensions(), DD4hep::Geometry::PolarGridRPhi::cellDimensions(), DD4hep::Geometry::MultiSegmentation::cellDimensions(), DD4hep::Geometry::CartesianGridYZ::cellDimensions(), DD4hep::Geometry::CartesianGridXZ::cellDimensions(), DD4hep::Geometry::CartesianGridXYZ::cellDimensions(), DD4hep::Geometry::CartesianGridXY::cellDimensions(), DD4hep::Geometry::WaferGridXY::cellID(), DD4hep::Geometry::PolarGridRPhi2::cellID(), DD4hep::Geometry::PolarGridRPhi::cellID(), DD4hep::Geometry::MultiSegmentation::cellID(), DD4hep::Geometry::CartesianGridYZ::cellID(), DD4hep::Geometry::CartesianGridXZ::cellID(), DD4hep::Geometry::CartesianGridXYZ::cellID(), DD4hep::Geometry::CartesianGridXY::cellID(), DD4hep::Geometry::DetElement::children(), DD4hep::Geometry::SensitiveDetector::combineHits(), DD4hep::Geometry::DetElement::combineHits(), DD4hep::Geometry::World::conditionsLoader(), DD4hep::Geometry::MultiSegmentation::discriminator(), DD4hep::Geometry::MultiSegmentation::discriminatorName(), DD4hep::Geometry::SensitiveDetector::energyCutoff(), DD4hep::Geometry::PolarGridRPhi2::fieldNamePhi(), DD4hep::Geometry::PolarGridRPhi::fieldNamePhi(), DD4hep::Geometry::PolarGridRPhi2::fieldNameR(), DD4hep::Geometry::PolarGridRPhi::fieldNameR(), DD4hep::Geometry::WaferGridXY::fieldNameX(), DD4hep::Geometry::CartesianGridXZ::fieldNameX(), DD4hep::Geometry::CartesianGridXYZ::fieldNameX(), DD4hep::Geometry::CartesianGridXY::fieldNameX(), DD4hep::Geometry::WaferGridXY::fieldNameY(), DD4hep::Geometry::CartesianGridYZ::fieldNameY(), DD4hep::Geometry::CartesianGridXYZ::fieldNameY(), DD4hep::Geometry::CartesianGridXY::fieldNameY(), DD4hep::Geometry::CartesianGridYZ::fieldNameZ(), DD4hep::Geometry::CartesianGridXZ::fieldNameZ(), DD4hep::Geometry::CartesianGridXYZ::fieldNameZ(), DD4hep::Geometry::PolarGridRPhi2::gridPhiValues(), DD4hep::Geometry::PolarGridRPhi2::gridRValues(), DD4hep::Geometry::PolarGridRPhi::gridSizePhi(), DD4hep::Geometry::PolarGridRPhi::gridSizeR(), DD4hep::Geometry::WaferGridXY::gridSizeX(), DD4hep::Geometry::CartesianGridXZ::gridSizeX(), DD4hep::Geometry::CartesianGridXYZ::gridSizeX(), DD4hep::Geometry::CartesianGridXY::gridSizeX(), DD4hep::Geometry::WaferGridXY::gridSizeY(), DD4hep::Geometry::CartesianGridYZ::gridSizeY(), DD4hep::Geometry::CartesianGridXYZ::gridSizeY(), DD4hep::Geometry::CartesianGridXY::gridSizeY(), DD4hep::Geometry::CartesianGridYZ::gridSizeZ(), DD4hep::Geometry::CartesianGridXZ::gridSizeZ(), DD4hep::Geometry::CartesianGridXYZ::gridSizeZ(), DD4hep::Geometry::DetElement::hasAlignments(), DD4hep::Geometry::DetElement::hasConditions(), DD4hep::Geometry::SensitiveDetector::hitsCollection(), DD4hep::Geometry::DetElement::i_addUpdateCall(), DD4hep::Geometry::DetElement::id(), DD4hep::Geometry::World::lcdd(), DD4hep::Geometry::SensitiveDetector::limits(), DD4hep::Geometry::DetElement::nominal(), DD4hep::Geometry::PolarGridRPhi2::offsetPhi(), DD4hep::Geometry::PolarGridRPhi::offsetPhi(), DD4hep::Geometry::PolarGridRPhi2::offsetR(), DD4hep::Geometry::PolarGridRPhi::offsetR(), DD4hep::Geometry::WaferGridXY::offsetX(), DD4hep::Geometry::CartesianGridXZ::offsetX(), DD4hep::Geometry::CartesianGridXYZ::offsetX(), DD4hep::Geometry::CartesianGridXY::offsetX(), DD4hep::Geometry::WaferGridXY::offsetY(), DD4hep::Geometry::CartesianGridYZ::offsetY(), DD4hep::Geometry::CartesianGridXYZ::offsetY(), DD4hep::Geometry::CartesianGridXY::offsetY(), DD4hep::Geometry::CartesianGridYZ::offsetZ(), DD4hep::Geometry::CartesianGridXZ::offsetZ(), DD4hep::Geometry::CartesianGridXYZ::offsetZ(), DD4hep::Geometry::DetElement::parentTransformation(), DD4hep::Geometry::WaferGridXY::position(), DD4hep::Geometry::PolarGridRPhi2::position(), DD4hep::Geometry::PolarGridRPhi::position(), DD4hep::Geometry::MultiSegmentation::position(), DD4hep::Geometry::CartesianGridYZ::position(), DD4hep::Geometry::CartesianGridXZ::position(), DD4hep::Geometry::CartesianGridXYZ::position(), DD4hep::Geometry::CartesianGridXY::position(), DD4hep::Geometry::SensitiveDetector::readout(), DD4hep::Geometry::SensitiveDetector::region(), DD4hep::Geometry::DetElement::removeAtUpdate(), DD4hep::Geometry::SensitiveDetector::setCombineHits(), DD4hep::Geometry::DetElement::setCombineHits(), DD4hep::Geometry::SensitiveDetector::setEnergyCutoff(), DD4hep::Geometry::PolarGridRPhi2::setGridPhiValues(), DD4hep::Geometry::PolarGridRPhi2::setGridRValues(), DD4hep::Geometry::PolarGridRPhi2::setGridSizePhi(), DD4hep::Geometry::PolarGridRPhi::setGridSizePhi(), DD4hep::Geometry::PolarGridRPhi2::setGridSizeR(), DD4hep::Geometry::PolarGridRPhi::setGridSizeR(), DD4hep::Geometry::CartesianGridXZ::setGridSizeX(), DD4hep::Geometry::CartesianGridXYZ::setGridSizeX(), DD4hep::Geometry::CartesianGridXY::setGridSizeX(), DD4hep::Geometry::CartesianGridYZ::setGridSizeY(), DD4hep::Geometry::CartesianGridXYZ::setGridSizeY(), DD4hep::Geometry::CartesianGridXY::setGridSizeY(), DD4hep::Geometry::CartesianGridYZ::setGridSizeZ(), DD4hep::Geometry::CartesianGridXZ::setGridSizeZ(), DD4hep::Geometry::CartesianGridXYZ::setGridSizeZ(), DD4hep::Geometry::SensitiveDetector::setLimitSet(), DD4hep::Geometry::PolarGridRPhi2::setOffsetPhi(), DD4hep::Geometry::PolarGridRPhi::setOffsetPhi(), DD4hep::Geometry::PolarGridRPhi2::setOffsetR(), DD4hep::Geometry::PolarGridRPhi::setOffsetR(), DD4hep::Geometry::CartesianGridXZ::setOffsetX(), DD4hep::Geometry::CartesianGridXYZ::setOffsetX(), DD4hep::Geometry::CartesianGridXY::setOffsetX(), DD4hep::Geometry::CartesianGridYZ::setOffsetY(), DD4hep::Geometry::CartesianGridXYZ::setOffsetY(), DD4hep::Geometry::CartesianGridXY::setOffsetY(), DD4hep::Geometry::CartesianGridYZ::setOffsetZ(), DD4hep::Geometry::CartesianGridXZ::setOffsetZ(), DD4hep::Geometry::CartesianGridXYZ::setOffsetZ(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::Geometry::SensitiveDetector::setReadout(), DD4hep::Geometry::SensitiveDetector::setRegion(), DD4hep::Geometry::DetElement::setTypeFlag(), DD4hep::Geometry::SensitiveDetector::setVerbose(), DD4hep::Geometry::MultiSegmentation::subSegmentations(), DD4hep::Geometry::DetElement::survey(), DD4hep::Geometry::SensitiveDetector::verbose(), DD4hep::Geometry::DetElement::volume(), DD4hep::Geometry::WaferGridXY::waferOffsetX(), DD4hep::Geometry::WaferGridXY::waferOffsetY(), and DD4hep::Geometry::DetElement::worldTransformation().
template<> void DD4hep::Handle< _Segmentation >::assign (_Segmentation * s, const std::string & n, const std::string &) [inline]
Definition at line 261 of file Handle.cpp.
References DD4hep::Handle< T >::m_element, and DD4hep::DDSegmentation::Segmentation::setName().
template<typename T > void DD4hep::Handle< T >::assign (Implementation * n, const std::string & nam, const std::string & title) [inline]
Assign a new named object. Note: object references must be managed by the user.
Definition at line 27 of file Handle.inl.
References DD4hep::Handle< T >::m_element.
Referenced by DD4hep::Geometry::DetElementObject::assign_conditions(), DD4hep::Geometry::VisAttr::VisAttr(), and DD4hep::Geometry::VolumeManager::VolumeManager().
template<typename T > void DD4hep::Handle< T >::bad_assignment (const std::type_info & from, const std::type_info & to) [inline, static]
Helper routine called when unrelated types are assigned.
Definition at line 21 of file Handle.inl.
References DD4hep::invalidHandleAssignmentError().
template<typename T> Handle<T>& DD4hep::Handle< T >::clear () [inline]
Release the object held by the handle.
Reimplemented in DD4hep::Conditions::ConditionsManager.
Definition at line 132 of file Handle.h.
Referenced by DD4hep::Geometry::LCDDData::clearData(), DD4hep::Geometry::LCDDData::destroyData(), DD4hep::Geometry::DetElementObject::~DetElementObject(), DD4hep::Geometry::SensitiveDetectorObject::~SensitiveDetectorObject(), and DD4hep::Geometry::VolumeExtension::~VolumeExtension().
template<typename T> template<typename Q > Q* DD4hep::Handle< T >::data () const [inline]
Access to an unrelated object type.
Reimplemented in DD4hep::Alignments::Alignment, DD4hep::Alignments::AlignmentCondition, DD4hep::Conditions::Condition, DD4hep::Geometry::PlacedVolume, and DD4hep::Geometry::Volume.
Definition at line 157 of file Handle.h.
Referenced by DD4hep::Geometry::operator<<(), and DD4hep::Geometry::Volume::setVisAttributes().
template<typename T> bool DD4hep::Handle< T >::isValid () const [inline]
Check the validity of the object held by the handle.
Definition at line 124 of file Handle.h.
Referenced by _detector(), DD4hep::Geometry::Material::A(), DD4hep::Geometry::DetElement::add(), DD4hep::Geometry::LCDDImp::addDetector(), DD4hep::DDRec::LayeringExtensionImpl::LayerAttributes::addElement(), DD4hep::Geometry::VolumeManager::addSubdetector(), DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::Geometry::AlignmentEntry::align(), DD4hep::ROOTUI::alignmentMgr(), DD4hep::Geometry::DetElementObject::assign_conditions(), DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4VolumeManager::checkValidity(), DD4hep::Geometry::GeoHandler::collect(), DD4hep::Geometry::Readout::collectionNames(), DD4hep::Geometry::Readout::collections(), DD4hep::Conditions::ConditionUpdateContext::condition(), DD4hep::ROOTUI::conditionsMgr(), DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureGeometry(), DD4hep::Alignments::GlobalAlignmentWriter::createElement(), DD4hep::Utilities::createEveShape(), DD4hep::View::CreateGeometry(), DD4hep::DDRec::invalid_detector_element::createMsg(), DD4hep::XML::createPlacedEnvelope(), DD4hep::XML::createShape(), DD4hep::Geometry::Constant::dataType(), DD4hep::Geometry::LCDDImp::declareMotherVolume(), DD4hep::Geometry::IDDescriptor::decodeFields(), DD4hep::Geometry::Material::density(), DD4hep::Geometry::VolumeManager::detector(), DD4hep::DDRec::IDDecoder::detectorElement(), DD4hep::Geometry::LCDDImp::detectors(), DD4hep::Geometry::DetectorSelector::detectors(), dumpDetectors(), DD4hep::Geometry::DetectorTools::elementPath(), DD4hep::Geometry::IDDescriptor::fields(), DD4hep::Geometry::DetectorTools::findChild(), findChildByName(), DD4hep::Geometry::DetectorTools::findDaughterElement(), DD4hep::DDRec::IDDecoder::findReadout(), DD4hep::Conditions::Container::get(), DD4hep::Alignments::Container::get(), DD4hep::Conditions::ConditionUpdateContext::get(), DD4hep::Conditions::ConditionsDependencyHandler::get(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), DD4hep::DDRec::IDDecoder::getClosestDaughter(), DD4hep::View::GetGlobalGeometry(), DD4hep::DDRec::LayeredSubdetector::getLayeringExtension(), DD4hep::DDRec::SubdetectorExtensionImpl::getNSides(), DD4hep::DDRec::SubdetectorExtensionImpl::getRMax(), DD4hep::DDRec::SubdetectorExtensionImpl::getRMin(), DD4hep::DDRec::Subdetector::getSubdetectorExtension(), DD4hep::DDRec::Tracker::getTrackerExtension(), DD4hep::DDRec::SubdetectorExtensionImpl::getZMax(), DD4hep::DDRec::SubdetectorExtensionImpl::getZMin(), DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation(), DD4hep::Alignments::AlignmentData::hasCondition(), DD4hep::Geometry::DetElementObject::i_access_world(), DD4hep::Geometry::GeoHandler::i_collect(), DD4hep::DDRec::IDDecoder::IDDecoder(), DD4hep::Geometry::IDDescriptor::ids(), DD4hep::Geometry::LCDDImp::init(), DD4hep::Geometry::Material::intLength(), DD4hep::SurfaceInstaller::invalidInstaller(), DD4hep::Geometry::DetectorTools::isParentElement(), DD4hep::ROOTUI::loadConditions(), DD4hep::Utilities::LoadDetElement(), DD4hep::Display::LoadGeoChildren(), DD4hep::Geometry::VolumeManager::lookupContext(), DD4hep::Geometry::LCDDImp::mapDetectorTypes(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::Geometry::DetElement::nominal(), DD4hep::Geometry::Readout::numCollections(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::DDRec::MaterialData::operator=(), DD4hep::SurfaceInstaller::parentVolume(), DD4hep::Geometry::LCDDImp::pickMotherVolume(), DD4hep::Geometry::DetElement::placement(), DD4hep::Geometry::Material::radLength(), DD4hep::Conditions::ConditionsManagerObject::registerUnlocked(), DD4hep::Geometry::DetElementObject::revalidate(), DD4hep::Alignments::GlobalAlignmentWriter::scan(), DD4hep::Geometry::LCDDHelper::sensitiveDetector(), DD4hep::Geometry::DetElement::setCombineHits(), DD4hep::Geometry::Readout::setIDDescriptor(), DD4hep::Geometry::Volume::setMaterial(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::Geometry::Readout::setSegmentation(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::Geometry::VolumeManager::subdetector(), DD4hep::SurfaceInstaller::SurfaceInstaller(), DD4hep::Geometry::DetElement::survey(), DD4hep::Geometry::DetectorTools::topElement(), DD4hep::Geometry::IDDescriptor::toString(), DD4hep::Geometry::DetElement::volumeID(), DD4hep::Geometry::VolumeManager::VolumeManager(), DD4hep::Geometry::DetElementObject::world(), DD4hep::Geometry::Material::Z(), and DD4hep::Geometry::ReadoutObject::~ReadoutObject().
template<> const char * DD4hep::Handle< _Segmentation >::name () const [inline]
Reimplemented in DD4hep::Geometry::Header, DD4hep::Geometry::Solid_type< T >, DD4hep::Geometry::Solid_type< TGeoArb8 >, DD4hep::Geometry::Solid_type< TGeoSphere >, DD4hep::Geometry::Solid_type< TGeoHalfSpace >, DD4hep::Geometry::Solid_type< TGeoTorus >, DD4hep::Geometry::Solid_type< TGeoParaboloid >, DD4hep::Geometry::Solid_type< TGeoShape >, DD4hep::Geometry::Solid_type< TGeoEltu >, DD4hep::Geometry::Solid_type< TGeoPgon >, DD4hep::Geometry::Solid_type< TGeoCone >, DD4hep::Geometry::Solid_type< TGeoTrd2 >, DD4hep::Geometry::Solid_type< TGeoPcon >, DD4hep::Geometry::Solid_type< TGeoCompositeShape >, DD4hep::Geometry::Solid_type< TGeoConeSeg >, DD4hep::Geometry::Solid_type< TGeoTrap >, DD4hep::Geometry::Solid_type< TGeoHype >, DD4hep::Geometry::Solid_type< MyConeSeg >, and DD4hep::Geometry::Solid_type< TGeoBBox >.
Definition at line 265 of file Handle.cpp.
References DD4hep::Handle< T >::m_element.
template<typename T > const char * DD4hep::Handle< T >::name () const [inline]
Access the object name (or "" if not supported by the object).
Reimplemented in DD4hep::Conditions::Condition, DD4hep::Geometry::Header, DD4hep::Geometry::Solid_type< T >, DD4hep::Geometry::Solid_type< TGeoArb8 >, DD4hep::Geometry::Solid_type< TGeoSphere >, DD4hep::Geometry::Solid_type< TGeoHalfSpace >, DD4hep::Geometry::Solid_type< TGeoTorus >, DD4hep::Geometry::Solid_type< TGeoParaboloid >, DD4hep::Geometry::Solid_type< TGeoShape >, DD4hep::Geometry::Solid_type< TGeoEltu >, DD4hep::Geometry::Solid_type< TGeoPgon >, DD4hep::Geometry::Solid_type< TGeoCone >, DD4hep::Geometry::Solid_type< TGeoTrd2 >, DD4hep::Geometry::Solid_type< TGeoPcon >, DD4hep::Geometry::Solid_type< TGeoCompositeShape >, DD4hep::Geometry::Solid_type< TGeoConeSeg >, DD4hep::Geometry::Solid_type< TGeoTrap >, DD4hep::Geometry::Solid_type< TGeoHype >, DD4hep::Geometry::Solid_type< MyConeSeg >, and DD4hep::Geometry::Solid_type< TGeoBBox >.
Definition at line 36 of file Handle.inl.
References DD4hep::Handle< T >::m_element.
Referenced by DD4hep::Geometry::DetElement::add(), DD4hep::Geometry::LCDDImp::addDetector(), DD4hep::Geometry::VolumeManager::addSubdetector(), DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::View::ConfigureEvent(), DD4hep::Simulation::Geant4DetectorSensitivesConstruction::constructSensitives(), DD4hep::Simulation::Geant4Converter::create(), create_detector(), DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DD4hep::View::CreateGeometry(), DD4hep::DDRec::invalid_detector_element::createMsg(), DD4hep::Simulation::Geant4SensitiveAction< T >::declareReadoutFilteredCollection(), Tests::Geant4SensitiveAction< T >::defineCollections(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), DD4hep::DDRec::IDDecoder::detectorElement(), dumpDetectors(), DD4hep::Geometry::DetectorTools::elementPath(), DD4hep::DDRec::findVolume(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::Geant4ReadoutVolumeFilter(), DD4hep::View::GetGlobalGeometry(), DD4hep::Geometry::SimpleGDMLWriter::handleVisualisation(), DD4hep::DDRec::Surface::initialize(), DD4hep::SurfaceInstaller::install(), DD4hep::SurfaceInstaller::invalidInstaller(), DD4hep::Utilities::LoadDetElement(), DD4hep::Display::LoadGeoChildren(), DD4hep::Geometry::LCDDImp::mapDetectorTypes(), DD4hep::DDRec::MaterialData::MaterialData(), DD4hep::DDRec::operator<<(), DD4hep::Geometry::operator<<(), DD4hep::DDRec::MaterialData::operator=(), DD4hep::Geometry::LCDDImp::pickMotherVolume(), DD4hep::Geometry::DetElementObject::referenceTransformation(), DD4hep::Geometry::Volume::setMaterial(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::SurfaceInstaller::SurfaceInstaller(), DD4hep::Geometry::VolumeManagerObject::update(), and DD4hep::Geometry::VolumeManager::VolumeManager().
template<typename T> template<typename Q > Q& DD4hep::Handle< T >::object () const [inline]
Access to an unrelated object type.
Definition at line 161 of file Handle.h.
template<typename T> DD4hep::Handle< T >::operator T & () const [inline]
Automatic type conversion to an object references.
Definition at line 141 of file Handle.h.
template<typename T> bool DD4hep::Handle< T >::operator! () const [inline]
Check the validity of the object held by the handle.
Definition at line 128 of file Handle.h.
template<typename T> T& DD4hep::Handle< T >::operator* () const [inline]
Access the held object using the * operator.
Definition at line 145 of file Handle.h.
template<typename T> T* DD4hep::Handle< T >::operator-> () const [inline]
Access the held object using the -> operator.
Reimplemented in DD4hep::Geometry::Solid_type< T >, DD4hep::Geometry::Solid_type< TGeoArb8 >, DD4hep::Geometry::Solid_type< TGeoSphere >, DD4hep::Geometry::Solid_type< TGeoHalfSpace >, DD4hep::Geometry::Solid_type< TGeoTorus >, DD4hep::Geometry::Solid_type< TGeoParaboloid >, DD4hep::Geometry::Solid_type< TGeoShape >, DD4hep::Geometry::Solid_type< TGeoEltu >, DD4hep::Geometry::Solid_type< TGeoPgon >, DD4hep::Geometry::Solid_type< TGeoCone >, DD4hep::Geometry::Solid_type< TGeoTrd2 >, DD4hep::Geometry::Solid_type< TGeoPcon >, DD4hep::Geometry::Solid_type< TGeoCompositeShape >, DD4hep::Geometry::Solid_type< TGeoConeSeg >, DD4hep::Geometry::Solid_type< TGeoTrap >, DD4hep::Geometry::Solid_type< TGeoHype >, DD4hep::Geometry::Solid_type< MyConeSeg >, and DD4hep::Geometry::Solid_type< TGeoBBox >.
Definition at line 137 of file Handle.h.
template<typename T> bool DD4hep::Handle< T >::operator< (const Handle< T > & e) const [inline]
Boolean operator < used for RB tree insertions.
Definition at line 116 of file Handle.h.
template<typename T> Handle<T>& DD4hep::Handle< T >::operator= (const Handle< T > & e)
Assignment operator.
Reimplemented in DD4hep::Geometry::CartesianGridXY, DD4hep::Geometry::CartesianGridXYZ, DD4hep::Geometry::CartesianGridXZ, DD4hep::Geometry::CartesianGridYZ, DD4hep::Conditions::Condition, DD4hep::Conditions::Container, DD4hep::Geometry::SensitiveDetector, DD4hep::Geometry::DetElement, DD4hep::Alignments::GlobalAlignment, DD4hep::Geometry::LCDDHelper, DD4hep::Geometry::MultiSegmentation, DD4hep::Geometry::Header, DD4hep::Geometry::VisAttr, DD4hep::Geometry::LimitSet, DD4hep::Geometry::Region, DD4hep::Geometry::PolarGridRPhi, DD4hep::Geometry::PolarGridRPhi2, DD4hep::Geometry::Readout, DD4hep::Geometry::Segmentation, DD4hep::Geometry::Solid_type< T >, DD4hep::Geometry::Box, DD4hep::Geometry::HalfSpace, DD4hep::Geometry::Polycone, DD4hep::Geometry::ConeSegment, DD4hep::Geometry::Tube, DD4hep::Geometry::EllipticalTube, DD4hep::Geometry::Cone, DD4hep::Geometry::Trap, DD4hep::Geometry::Trapezoid, DD4hep::Geometry::Torus, DD4hep::Geometry::Sphere, DD4hep::Geometry::Paraboloid, DD4hep::Geometry::Hyperboloid, DD4hep::Geometry::PolyhedraRegular, DD4hep::Geometry::EightPointSolid, DD4hep::Geometry::BooleanSolid, DD4hep::Geometry::SubtractionSolid, DD4hep::Geometry::UnionSolid, DD4hep::Geometry::IntersectionSolid, DD4hep::Geometry::VolumeManager, DD4hep::Geometry::PlacedVolume, DD4hep::Geometry::Volume, DD4hep::Geometry::Assembly, DD4hep::Geometry::WaferGridXY, DD4hep::Geometry::World, DD4hep::Simulation::Geant4VolumeManager, DD4hep::Alignments::AlignmentsManager, and DD4hep::Conditions::ConditionsManager.
template<typename T> bool DD4hep::Handle< T >::operator== (const Handle< T > & e) const [inline]
Boolean operator == used for RB tree insertions.
Reimplemented in DD4hep::Geometry::CartesianGridXY, DD4hep::Geometry::CartesianGridXYZ, DD4hep::Geometry::CartesianGridXZ, DD4hep::Geometry::CartesianGridYZ, DD4hep::Geometry::MultiSegmentation, DD4hep::Geometry::PolarGridRPhi, DD4hep::Geometry::PolarGridRPhi2, and DD4hep::Geometry::WaferGridXY.
Definition at line 112 of file Handle.h.
template<typename T> bool DD4hep::Handle< T >::operator> (const Handle< T > & e) const [inline]
Boolean operator > used for RB tree insertions.
Definition at line 120 of file Handle.h.
template<typename T> T* DD4hep::Handle< T >::ptr () const [inline]
Access to the held object.
Definition at line 149 of file Handle.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), DD4hep::Geometry::VolumeManager::_data(), DD4hep::Geometry::Solid_type< T >::_setDimensions(), DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::Simulation::Geant4VolumeManager::checkValidity(), DD4hep::Geometry::GeoHandler::collect(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Alignments::AlignmentTools::computeSurvey(), DD4hep::Alignments::AlignmentTools::copy(), DD4hep::Simulation::Geant4Converter::create(), DD4hep::Geometry::IDDescriptor::decodeFields(), DD4hep::Geometry::LCDDHelper::detectorByID(), dumpStructure(), DD4hep::Geometry::DetectorTools::elementPath(), DD4hep::Geometry::MultipoleField::fieldComponents(), DD4hep::Geometry::DetectorTools::findChild(), findChildByName(), DD4hep::Geometry::DetectorTools::findNode(), DD4hep::DDRec::findVolume(), DD4hep::Conditions::ConditionsLoaderImp::get(), DD4hep::Conditions::ConditionsDependencyHandler::get(), DD4hep::Conditions::AlignmentsLoaderImp::get(), DD4hep::Geometry::DetElementObject::i_access_world(), DD4hep::Geometry::LCDDImp::init(), DD4hep::Alignments::GlobalAlignmentCache::insert(), DD4hep::SurfaceInstaller::install(), DD4hep::Geometry::DetectorTools::isParentElement(), DD4hep::Geometry::DetElement::key(), DD4hep::Geometry::DetElement::level(), DD4hep::Utilities::LoadDetElement(), DD4hep::Display::LoadGeoChildren(), DD4hep::Geometry::VolumeManager::lookupContext(), DD4hep::Conditions::make_key(), DD4hep::Geometry::Solid_type< T >::name(), DD4hep::Alignments::AlignmentsManager::newEntry(), DD4hep::Conditions::ConditionsPool::onRegister(), DD4hep::Conditions::ConditionsPool::onRemove(), DD4hep::Conditions::KeyedSelect< collection_type >::operator()(), DD4hep::Conditions::ActiveSelect< collection_type >::operator()(), DD4hep::Conditions::CollectionSelect< collection_type >::operator()(), DD4hep::Conditions::PoolInsert< pool_type >::operator()(), DD4hep::Conditions::ConditionsPoolRemove::operator()(), DD4hep::Conditions::ConditionsPoolInsert::operator()(), DD4hep::Geometry::DetElement::operator<(), DD4hep::Alignments::GlobalAlignment::operator=(), DD4hep::Geometry::DetElement::operator==(), DD4hep::Geometry::DetElement::parent(), DD4hep::Geometry::DetElement::path(), DD4hep::Geometry::DetElement::placementPath(), DD4hep::Geometry::DetElementObject::referenceTransformation(), DD4hep::Conditions::ConditionsManagerObject::registerCondition(), DD4hep::Geometry::DetElementObject::revalidate(), DD4hep::Geometry::LCDDHelper::sensitiveDetector(), DD4hep::Geometry::Readout::setSegmentation(), DD4hep::Geometry::VisAttr::toString(), DD4hep::Simulation::Geant4VolumeManager::volumeDescriptor(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), DD4hep::Geometry::DetElement::world(), DD4hep::Geometry::Box::x(), DD4hep::Geometry::Box::y(), DD4hep::Geometry::Box::z(), and DD4hep::Geometry::ReadoutObject::~ReadoutObject().
template<typename T> void DD4hep::Handle< T >::verifyObject () const
Verify the object type after a (re-)assignment.
Referenced by DD4hep::Handle< ReadoutObject >::Handle().
Member Data Documentation
template<typename T> T* DD4hep::Handle< T >::m_element
Single and only data member: Reference to the actual element.
Definition at line 96 of file Handle.h.
Referenced by DD4hep::Handle< ReadoutObject >::_ptr(), DD4hep::Handle< T >::access(), DD4hep::Geometry::AlignmentEntry::align(), DD4hep::Handle< T >::assign(), DD4hep::Handle< ReadoutObject >::clear(), DD4hep::Handle< ReadoutObject >::data(), DD4hep::Geometry::Constant::dataType(), DD4hep::Handle< ReadoutObject >::isValid(), DD4hep::Geometry::Volume::material(), DD4hep::Geometry::PlacedVolume::material(), DD4hep::Geometry::PlacedVolume::motherVol(), DD4hep::Geometry::Header::name(), DD4hep::Handle< T >::name(), DD4hep::Handle< ReadoutObject >::object(), DD4hep::Geometry::Solid_type< TGeoTrd2 >::operator TGeoTrd2 *(), DD4hep::Geometry::Volume::operator TGeoVolume *(), DD4hep::Handle< WorldObject >::operator WorldObject &(), DD4hep::Handle< ReadoutObject >::operator!(), DD4hep::Handle< ReadoutObject >::operator*(), DD4hep::Geometry::Solid_type< TGeoBBox >::operator->(), DD4hep::Handle< ReadoutObject >::operator->(), DD4hep::Handle< ReadoutObject >::operator<(), DD4hep::Simulation::Geant4VolumeManager::operator=(), DD4hep::Geometry::World::operator=(), DD4hep::Geometry::Assembly::operator=(), DD4hep::Geometry::Volume::operator=(), DD4hep::Geometry::PlacedVolume::operator=(), DD4hep::Geometry::VolumeManager::operator=(), DD4hep::Geometry::Region::operator=(), DD4hep::Geometry::LimitSet::operator=(), DD4hep::Geometry::VisAttr::operator=(), DD4hep::Geometry::Header::operator=(), DD4hep::Conditions::DetConditions::operator=(), DD4hep::Alignments::DetAlign::operator=(), DD4hep::Geometry::WaferGridXY::operator==(), DD4hep::Geometry::PolarGridRPhi2::operator==(), DD4hep::Geometry::PolarGridRPhi::operator==(), DD4hep::Geometry::MultiSegmentation::operator==(), DD4hep::Handle< ReadoutObject >::operator==(), DD4hep::Geometry::CartesianGridYZ::operator==(), DD4hep::Geometry::CartesianGridXZ::operator==(), DD4hep::Geometry::CartesianGridXYZ::operator==(), DD4hep::Geometry::CartesianGridXY::operator==(), DD4hep::Handle< ReadoutObject >::operator>(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::Handle< ReadoutObject >::ptr(), DD4hep::Geometry::Volume::setMaterial(), DD4hep::Geometry::Header::setName(), DD4hep::Geometry::Volume::setSolid(), DD4hep::Geometry::Header::setTitle(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::Geometry::Header::title(), DD4hep::Geometry::PlacedVolume::toString(), DD4hep::Geometry::Constant::toString(), DD4hep::Geometry::IDDescriptor::toString(), DD4hep::Geometry::Solid_type< TGeoBBox >::toString(), DD4hep::Geometry::SensitiveDetector::type(), DD4hep::Geometry::DetElement::type(), DD4hep::Geometry::DetElement::typeFlag(), and DD4hep::Geometry::PlacedVolume::volume().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Handle.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Handle.inl