DD4hep: DD4hep::dd4hep_ptr< T > Class Template Reference
DD4hep::dd4hep_ptr< T > Class Template Reference
DD4hep::Geometry components, classes and objects
Out version of the std auto_ptr implementation base either on auto_ptr or unique_ptr.
#include <Memory.h>
Public Types
typedef std::auto_ptr< T > base_t
Public Member Functions
void swap (base_t &c)
dd4hep_ptr (dd4hep_ptr< T > &c)
Constructor from copy.
dd4hep_ptr ()
Default Constructor.
dd4hep_ptr (T *p)
Constructor from pointer.
dd4hep_ptr (base_t &c)
Constructor from copy.
dd4hep_ptr & operator= (base_t &c)
Assignment operator.
dd4hep_ptr & adopt (T *ptr)
Assignment operator.
Detailed Description
template<typename T>
class DD4hep::dd4hep_ptr< T >
Out version of the std auto_ptr implementation base either on auto_ptr or unique_ptr.
Only need to overload constructor. Everything else like operator->, operator*, get, release etc. comes from base.
Author
M.Frank
Version
1.0
Definition at line 43 of file Memory.h.
Member Typedef Documentation
base_t
template<typename T> typedef std::auto_ptr<T> DD4hep::dd4hep_ptr< T >::base_t
Definition at line 52 of file Memory.h.
Constructor & Destructor Documentation
dd4hep_ptr() [1/4]
template<typename T> DD4hep::dd4hep_ptr< T >::dd4hep_ptr (dd4hep_ptr< T > & c) inline
Constructor from copy.
Definition at line 57 of file Memory.h.
dd4hep_ptr() [2/4]
template<typename T> DD4hep::dd4hep_ptr< T >::dd4hep_ptr () inline
Default Constructor.
Definition at line 61 of file Memory.h.
dd4hep_ptr() [3/4]
template<typename T> DD4hep::dd4hep_ptr< T >::dd4hep_ptr (T * p) inline
Constructor from pointer.
Definition at line 63 of file Memory.h.
dd4hep_ptr() [4/4]
template<typename T> DD4hep::dd4hep_ptr< T >::dd4hep_ptr (base_t & c) inline
Constructor from copy.
Definition at line 65 of file Memory.h.
Member Function Documentation
adopt()
template<typename T> dd4hep_ptr& DD4hep::dd4hep_ptr< T >::adopt (T * ptr) inline
Assignment operator.
Definition at line 74 of file Memory.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__get_checked_pool(), _stack(), DD4hep::Conditions::ConditionsManagerObject::initialize(), and DD4hep::Conditions::ConditionsManagerObject::pushUpdates().
operator=()
template<typename T> dd4hep_ptr& DD4hep::dd4hep_ptr< T >::operator= (base_t & c) inline
Assignment operator.
Definition at line 67 of file Memory.h.
swap()
template<typename T> void DD4hep::dd4hep_ptr< T >::swap (base_t & c) inline
Definition at line 53 of file Memory.h.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Memory.h