DD4hep: DD4hep::Geometry::ReadoutObject Class Reference
DD4hep::Geometry::ReadoutObject Class Reference
DD4hep::Geometry components, classes and objects
Concrete object implementation of the Readout Handle.
#include <ObjectsInterna.h>
Public Types
typedef HitCollection Collection
typedef std::vector< HitCollection > Collections
Public Member Functions
ReadoutObject ()
Standard constructor.
virtual ~ReadoutObject ()
Default destructor.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
Segmentation segmentation
Handle to the readout segmentation.
Volume readoutWorld
Handle to the volume.
IDDescriptor id
Handle to the field descriptor.
Collections hits
Hit collection container (if defined)
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Detailed Description
Concrete object implementation of the Readout Handle.
Author
M.Frank
Version
1.0
Definition at line 168 of file ObjectsInterna.h.
Member Typedef Documentation
Collection
typedef HitCollection DD4hep::Geometry::ReadoutObject::Collection
Definition at line 170 of file ObjectsInterna.h.
Collections
typedef std::vector<HitCollection> DD4hep::Geometry::ReadoutObject::Collections
Definition at line 171 of file ObjectsInterna.h.
Constructor & Destructor Documentation
ReadoutObject()
ReadoutObject::ReadoutObject ()
Standard constructor.
Definition at line 94 of file ObjectsInterna.cpp.
References DD4hep::InstanceCount::increment().
~ReadoutObject()
ReadoutObject::~ReadoutObject () virtual
Default destructor.
Definition at line 99 of file ObjectsInterna.cpp.
References DD4HEP_INSTANTIATE_HANDLE_NAMED(), and DD4hep::InstanceCount::decrement().
Member Data Documentation
hits
Collections DD4hep::Geometry::ReadoutObject::hits
Hit collection container (if defined)
Definition at line 179 of file ObjectsInterna.h.
Referenced by DD4hep::Geometry::Readout::collectionNames(), DD4hep::Geometry::Readout::collections(), and DD4hep::Geometry::Readout::numCollections().
id
IDDescriptor DD4hep::Geometry::ReadoutObject::id
Handle to the field descriptor.
Definition at line 177 of file ObjectsInterna.h.
readoutWorld
Volume DD4hep::Geometry::ReadoutObject::readoutWorld
Handle to the volume.
Definition at line 175 of file ObjectsInterna.h.
segmentation
Segmentation DD4hep::Geometry::ReadoutObject::segmentation
Handle to the readout segmentation.
Definition at line 173 of file ObjectsInterna.h.
Referenced by DD4hep::Geometry::Readout::setSegmentation().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/ObjectsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ObjectsInterna.cpp