DD4hep: DD4hep::Simulation::Geant4UIMessenger Class Reference
DD4hep::Simulation::Geant4UIMessenger Class Reference
Generic implementation to export properties and actions to the Geant4 command prompt.
#include <DDG4/Geant4UIMessenger.h>
Public Types
typedef std::map< G4UIcommand *, std::string > Commands
typedef std::map< G4UIcommand *, Callback > Actions
Public Member Functions
Geant4UIMessenger (const std::string &name, const std::string &path)
Initializing constructor.
virtual ~Geant4UIMessenger ()
Default destructor.
void addCall (const std::string &name, const std::string &description, const Callback &cb)
Add a new callback structure.
template<typename Q , typename R , typename T >
void addCall (const std::string &name, const std::string &description, Q *p, R(T::*f)())
Add any callback (without parameters to the messenger.
void exportProperties (PropertyManager &mgr)
Export all properties to the Geant4 UI.
void SetNewValue (G4UIcommand *c, G4String val)
Accept ne property value from Geant4 UI.
G4String GetCurrentValue (G4UIcommand *c)
Pass current property value to Geant4 UI.
Protected Attributes
G4UIdirectory * m_directory
The UI directory of this component.
PropertyManager * m_properties
Reference to the property manager corresponding to the component.
std::string m_name
Component name.
std::string m_path
Path in the UI hierarchy of this component.
Commands m_propertyCmd
Property update command map.
Actions m_actionCmd
Action map.
Detailed Description
Generic implementation to export properties and actions to the Geant4 command prompt.
Author
M.Frank
Version
1.0
Definition at line 36 of file Geant4UIMessenger.h.
Member Typedef Documentation
Actions
typedef std::map<G4UIcommand*, Callback> DD4hep::Simulation::Geant4UIMessenger::Actions
Definition at line 39 of file Geant4UIMessenger.h.
Commands
typedef std::map<G4UIcommand*, std::string> DD4hep::Simulation::Geant4UIMessenger::Commands
Definition at line 38 of file Geant4UIMessenger.h.
Constructor & Destructor Documentation
Geant4UIMessenger()
Geant4UIMessenger::Geant4UIMessenger (const std::string & name, const std::string & path)
Initializing constructor.
Definition at line 49 of file Geant4UIMessenger.cpp.
References DD4hep::INFO, m_directory, and DD4hep::printout().
~Geant4UIMessenger()
Geant4UIMessenger::~Geant4UIMessenger () virtual
Default destructor.
Definition at line 57 of file Geant4UIMessenger.cpp.
References DD4hep::destroyFirst(), m_actionCmd, and m_propertyCmd.
Member Function Documentation
addCall() [1/2]
void Geant4UIMessenger::addCall (const std::string & name, const std::string & description, const Callback & cb)
Add a new callback structure.
Definition at line 63 of file Geant4UIMessenger.cpp.
References m_actionCmd, and m_path.
Referenced by addCall(), exportProperties(), DD4hep::Simulation::Geant4PhysicsList::installCommandMessenger(), and DD4hep::Simulation::Geant4PhysicsListActionSequence::installCommandMessenger().
addCall() [2/2]
template<typename Q , typename R , typename T > void DD4hep::Simulation::Geant4UIMessenger::addCall (const std::string & name, const std::string & description, Q * p, R(T::*)() f) inline
Add any callback (without parameters to the messenger.
Definition at line 63 of file Geant4UIMessenger.h.
References addCall(), DD4hep::CallbackSequence::checkTypes(), exportProperties(), GetCurrentValue(), and SetNewValue().
exportProperties()
void Geant4UIMessenger::exportProperties (PropertyManager & mgr)
Export all properties to the Geant4 UI.
Definition at line 70 of file Geant4UIMessenger.cpp.
References addCall(), DD4hep::PropertyManager::dump(), DD4hep::PropertyManager::for_each(), m_name, m_path, m_properties, and m_propertyCmd.
Referenced by addCall().
GetCurrentValue()
G4String Geant4UIMessenger::GetCurrentValue (G4UIcommand * c)
Pass current property value to Geant4 UI.
Definition at line 79 of file Geant4UIMessenger.cpp.
References DD4hep::INFO, m_name, m_properties, m_propertyCmd, and DD4hep::printout().
Referenced by addCall().
SetNewValue()
void Geant4UIMessenger::SetNewValue (G4UIcommand * c, G4String val)
Accept ne property value from Geant4 UI.
Definition at line 91 of file Geant4UIMessenger.cpp.
References e, DD4hep::INFO, m_actionCmd, m_name, m_properties, m_propertyCmd, DD4hep::printout(), and DD4hep::Property::str().
Referenced by addCall().
Member Data Documentation
m_actionCmd
Actions DD4hep::Simulation::Geant4UIMessenger::m_actionCmd protected
Action map.
Definition at line 52 of file Geant4UIMessenger.h.
Referenced by addCall(), SetNewValue(), and ~Geant4UIMessenger().
m_directory
G4UIdirectory* DD4hep::Simulation::Geant4UIMessenger::m_directory protected
The UI directory of this component.
Definition at line 42 of file Geant4UIMessenger.h.
Referenced by Geant4UIMessenger().
m_name
std::string DD4hep::Simulation::Geant4UIMessenger::m_name protected
Component name.
Definition at line 46 of file Geant4UIMessenger.h.
Referenced by exportProperties(), GetCurrentValue(), and SetNewValue().
m_path
std::string DD4hep::Simulation::Geant4UIMessenger::m_path protected
Path in the UI hierarchy of this component.
Definition at line 48 of file Geant4UIMessenger.h.
Referenced by addCall(), and exportProperties().
m_properties
PropertyManager* DD4hep::Simulation::Geant4UIMessenger::m_properties protected
Reference to the property manager corresponding to the component.
Definition at line 44 of file Geant4UIMessenger.h.
Referenced by exportProperties(), GetCurrentValue(), and SetNewValue().
m_propertyCmd
Commands DD4hep::Simulation::Geant4UIMessenger::m_propertyCmd protected
Property update command map.
Definition at line 50 of file Geant4UIMessenger.h.
Referenced by exportProperties(), GetCurrentValue(), SetNewValue(), and ~Geant4UIMessenger().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4UIMessenger.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4UIMessenger.cpp