DD4hep: DD4hep::Simulation::Geant4Mapping Class Reference
DD4hep::Simulation::Geant4Mapping Class Reference
DD4hep::Simulation components, classes and objects
Geometry mapping from DD4hep to Geant 4.
#include <Geant4Mapping.h>
Public Types
typedef Geometry::LCDD LCDD
typedef Geometry::DetElement DetElement
typedef Geometry::SensitiveDetector SensitiveDetector
typedef Geometry::Solid Solid
typedef Geometry::Volume Volume
typedef Geometry::PlacedVolume PlacedVolume
typedef Geometry::Atom Atom
typedef Geometry::Material Material
typedef Geometry::Region Region
typedef Geometry::VisAttr VisAttr
typedef Geometry::LimitSet LimitSet
Public Types inherited from DD4hep::Geometry::GeoHandlerTypes
typedef std::set< Volume > VolumeSet
typedef std::vector< Volume > VolumeVector
typedef std::set< const TGeoVolume * > ConstVolumeSet
typedef std::vector< std::pair< std::string, TGeoMatrix * > > TransformSet
typedef std::set< TGeoShape * > SolidSet
typedef std::set< Material > MaterialSet
typedef std::map< SensitiveDetector, ConstVolumeSet > SensitiveVolumes
typedef std::map< Region, ConstVolumeSet > RegionVolumes
typedef std::map< LimitSet, ConstVolumeSet > LimitVolumes
typedef std::map< int, std::set< const TGeoNode * > > Data
typedef std::set< VisAttr > VisRefs
typedef std::set< SensitiveDetector > SensitiveDetectorSet
typedef std::set< Region > RegionSet
typedef std::set< LimitSet > LimitSetSet
typedef std::set< Ref_t > Fields
typedef std::set< TNamed * > ObjectSet
typedef LCDD::HandleMap DefinitionSet
Public Member Functions
Geant4Mapping (LCDD &lcdd)
Initializing Constructor.
virtual ~Geant4Mapping ()
Standard destructor.
LCDD & lcdd () const
Accesor to the LCDD instance.
Geant4GeometryInfo & data () const
Access to the data pointer.
Geant4GeometryInfo * ptr () const
Access to the data pointer.
Geant4GeometryInfo & init ()
Create and attach new data block. Delete old data block if present.
Geant4GeometryInfo * detach ()
Release data and pass over the ownership.
void attach (Geant4GeometryInfo *data)
Set a new data block.
Geant4VolumeManager volumeManager () const
Access the volume manager.
PlacedVolume placement (const G4VPhysicalVolume *node) const
Accessor to resolve geometry placements.
Static Public Member Functions
static Geant4Mapping & instance ()
Possibility to define a singleton instance.
Protected Member Functions
void checkValidity () const
When resolving pointers, we must check for the validity of the data block.
Protected Attributes
LCDD & m_lcdd
Geant4GeometryInfo * m_dataPtr
Detailed Description
Geometry mapping from DD4hep to Geant 4.
Author
M.Frank
Version
1.0
Definition at line 36 of file Geant4Mapping.h.
Member Typedef Documentation
Atom
typedef Geometry::Atom DD4hep::Simulation::Geant4Mapping::Atom
Definition at line 44 of file Geant4Mapping.h.
DetElement
typedef Geometry::DetElement DD4hep::Simulation::Geant4Mapping::DetElement
Definition at line 39 of file Geant4Mapping.h.
LCDD
typedef Geometry::LCDD DD4hep::Simulation::Geant4Mapping::LCDD
Definition at line 38 of file Geant4Mapping.h.
LimitSet
typedef Geometry::LimitSet DD4hep::Simulation::Geant4Mapping::LimitSet
Definition at line 48 of file Geant4Mapping.h.
Material
typedef Geometry::Material DD4hep::Simulation::Geant4Mapping::Material
Definition at line 45 of file Geant4Mapping.h.
PlacedVolume
typedef Geometry::PlacedVolume DD4hep::Simulation::Geant4Mapping::PlacedVolume
Definition at line 43 of file Geant4Mapping.h.
Region
typedef Geometry::Region DD4hep::Simulation::Geant4Mapping::Region
Definition at line 46 of file Geant4Mapping.h.
SensitiveDetector
typedef Geometry::SensitiveDetector DD4hep::Simulation::Geant4Mapping::SensitiveDetector
Definition at line 40 of file Geant4Mapping.h.
Solid
typedef Geometry::Solid DD4hep::Simulation::Geant4Mapping::Solid
Definition at line 41 of file Geant4Mapping.h.
VisAttr
typedef Geometry::VisAttr DD4hep::Simulation::Geant4Mapping::VisAttr
Definition at line 47 of file Geant4Mapping.h.
Volume
typedef Geometry::Volume DD4hep::Simulation::Geant4Mapping::Volume
Definition at line 42 of file Geant4Mapping.h.
Constructor & Destructor Documentation
Geant4Mapping()
Geant4Mapping::Geant4Mapping (LCDD & lcdd)
Initializing Constructor.
Definition at line 26 of file Geant4Mapping.cpp.
~Geant4Mapping()
Geant4Mapping::~Geant4Mapping () virtual
Standard destructor.
Definition at line 31 of file Geant4Mapping.cpp.
References m_dataPtr.
Member Function Documentation
attach()
void Geant4Mapping::attach (Geant4GeometryInfo * data)
Set a new data block.
Definition at line 67 of file Geant4Mapping.cpp.
References m_dataPtr.
Referenced by DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), init(), and ptr().
checkValidity()
void Geant4Mapping::checkValidity () const protected
When resolving pointers, we must check for the validity of the data block.
Definition at line 44 of file Geant4Mapping.cpp.
References m_dataPtr.
Referenced by placement().
data()
Geant4GeometryInfo& DD4hep::Simulation::Geant4Mapping::data () const inline
Access to the data pointer.
Definition at line 72 of file Geant4Mapping.h.
References m_dataPtr.
Referenced by DD4hep::Simulation::Geant4Converter::collectVolume(), DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::Simulation::Geant4Converter::handleAssembly(), DD4hep::Simulation::Geant4Converter::handleElement(), DD4hep::Simulation::Geant4Converter::handleLimitSet(), DD4hep::Simulation::Geant4Converter::handleMaterial(), DD4hep::Simulation::Geant4Converter::handlePlacement(), DD4hep::Simulation::Geant4Converter::handleRegion(), DD4hep::Simulation::Geant4Converter::handleSolid(), DD4hep::Simulation::Geant4Converter::handleVis(), DD4hep::Simulation::Geant4Converter::handleVolume(), init(), DD4hep::Simulation::Geant4Converter::printPlacement(), DD4hep::Simulation::Geant4Converter::printSensitive(), and ptr().
detach()
Geant4GeometryInfo * Geant4Mapping::detach ()
Release data and pass over the ownership.
Definition at line 60 of file Geant4Mapping.cpp.
References m_dataPtr.
Referenced by DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), init(), and ptr().
init()
Geant4GeometryInfo & Geant4Mapping::init ()
Create and attach new data block. Delete old data block if present.
Create new data block. Delete old data block if present.
Definition at line 51 of file Geant4Mapping.cpp.
References attach(), data(), and detach().
Referenced by DD4hep::Simulation::Geant4Converter::create(), DD4hep::Simulation::Geant4Converter::Geant4Converter(), and ptr().
instance()
Geant4Mapping & Geant4Mapping::instance () static
Possibility to define a singleton instance.
Definition at line 38 of file Geant4Mapping.cpp.
References DD4hep::Geometry::LCDD::getInstance().
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::assemblies(), DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), DD4hep::Simulation::Geant4DetectorSensitivesConstruction::constructSensitives(), DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::Simulation::Geant4DetectorConstructionSequence::elements(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), DD4hep::Simulation::Geant4DetectorConstructionSequence::limits(), DD4hep::Simulation::Geant4DetectorConstructionSequence::materials(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::operator()(), DD4hep::Simulation::Geant4DetectorConstructionSequence::placements(), DD4hep::Simulation::Geant4DetectorConstructionSequence::regions(), DD4hep::Simulation::Geant4DetectorConstructionSequence::shapes(), and DD4hep::Simulation::Geant4Sensitive::volumeID().
lcdd()
LCDD& DD4hep::Simulation::Geant4Mapping::lcdd () const inline
Accesor to the LCDD instance.
Definition at line 67 of file Geant4Mapping.h.
References m_lcdd.
placement()
PlacedVolume Geant4Mapping::placement (const G4VPhysicalVolume * node) const
Accessor to resolve geometry placements.
Definition at line 83 of file Geant4Mapping.cpp.
References checkValidity(), DD4hep::Simulation::Geant4GeometryInfo::g4Placements, m, and m_dataPtr.
Referenced by ptr().
ptr()
Geant4GeometryInfo* DD4hep::Simulation::Geant4Mapping::ptr () const inline
Access to the data pointer.
Definition at line 77 of file Geant4Mapping.h.
References attach(), data(), detach(), init(), m_dataPtr, placement(), and volumeManager().
Referenced by DD4hep::Simulation::Geant4DetectorConstructionSequence::assemblies(), DD4hep::Simulation::Geant4DetectorSensitivesConstruction::constructSensitives(), DD4hep::Simulation::Geant4DetectorConstructionSequence::elements(), DD4hep::Simulation::Geant4DetectorConstructionSequence::limits(), DD4hep::Simulation::Geant4DetectorConstructionSequence::materials(), DD4hep::Simulation::Geant4DetectorConstructionSequence::placements(), DD4hep::Simulation::Geant4DetectorConstructionSequence::regions(), and DD4hep::Simulation::Geant4DetectorConstructionSequence::shapes().
volumeManager()
Geant4VolumeManager Geant4Mapping::volumeManager () const
Access the volume manager.
Definition at line 72 of file Geant4Mapping.cpp.
References DD4hep::format(), DD4hep::Simulation::Geant4GeometryInfo::g4Paths, m_dataPtr, and m_lcdd.
Referenced by DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::operator()(), ptr(), and DD4hep::Simulation::Geant4Sensitive::volumeID().
Member Data Documentation
m_dataPtr
Geant4GeometryInfo* DD4hep::Simulation::Geant4Mapping::m_dataPtr protected
Definition at line 52 of file Geant4Mapping.h.
Referenced by attach(), checkValidity(), data(), detach(), placement(), ptr(), volumeManager(), and ~Geant4Mapping().
m_lcdd
LCDD& DD4hep::Simulation::Geant4Mapping::m_lcdd protected
Definition at line 51 of file Geant4Mapping.h.
Referenced by DD4hep::Simulation::Geant4Converter::create(), DD4hep::Simulation::Geant4Converter::handleProperties(), DD4hep::Simulation::Geant4Converter::handleRegion(), lcdd(), and volumeManager().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Mapping.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Mapping.cpp