DD4hep: DD4hep: DD4hep::Simulation::Geant4Action::ContextSwap Class Reference
DD4hep::Simulation::Geant4Action::ContextSwap Class Reference
[DD4hep::Simulation components, classes and objects]
Functor to update the context of a Geant4Action object.
#include <Geant4Action.h>
Public Member Functions
ContextSwap (Geant4Action *a, Geant4Context *c)
Constructor.
~ContextSwap ()
Destructor.
Private Attributes
Geant4Context * context
reference to the context;
Geant4Action * action
Detailed Description
Functor to update the context of a Geant4Action object.
Author:
M.Frank
Version:
1.0
Definition at line 114 of file Geant4Action.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4Action::ContextSwap::ContextSwap (Geant4Action * a, Geant4Context * c) [inline]
Constructor.
Definition at line 120 of file Geant4Action.h.
References action, DD4hep::Simulation::Geant4Action::context(), context, and DD4hep::Simulation::Geant4Action::updateContext().
DD4hep::Simulation::Geant4Action::ContextSwap::~ContextSwap () [inline]
Destructor.
Definition at line 125 of file Geant4Action.h.
References action, context, and DD4hep::Simulation::Geant4Action::updateContext().
Member Data Documentation
Geant4Action* DD4hep::Simulation::Geant4Action::ContextSwap::action [private]
Definition at line 117 of file Geant4Action.h.
Referenced by ContextSwap(), and ~ContextSwap().
Geant4Context* DD4hep::Simulation::Geant4Action::ContextSwap::context [private]
reference to the context;
Definition at line 116 of file Geant4Action.h.
Referenced by ContextSwap(), and ~ContextSwap().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Action.h