DD4hep: DD4hep: DD4hep::Simulation::Geant4HitCollection Class Reference
DD4hep::Simulation::Geant4HitCollection Class Reference
[DD4hep::Simulation components, classes and objects]
Generic hit container class using Geant4HitWrapper objects.
#include <Geant4HitCollection.h>
Classes
union CollectionFlags
class Compare
Generic class template to compare/select hits in Geant4HitCollection objects.
Public Types
enum { OPTIMIZE_NONE = 0, OPTIMIZE_REPEATEDLOOKUP = 1<<0, OPTIMIZE_MAPPEDLOOKUP = 1<<1, OPTIMIZE_LAST }
typedef std::vector
< Geant4HitWrapper > WrappedHits
Hit wrapper.
typedef
Geant4HitWrapper::HitManipulator Manip
Hit manipulator.
typedef std::map< VolumeID,
size_t > Keys
Hit key map for fast random lookup.
Public Member Functions
template<typename TYPE >
Geant4HitCollection (const std::string &det, const std::string &coll, Geant4Sensitive *sd)
Initializing constructor (C++ version).
template<typename TYPE >
Geant4HitCollection (const std::string &det, const std::string &coll, Geant4Sensitive *sd, const TYPE *)
Initializing constructor.
virtual ~Geant4HitCollection ()
Default destructor.
const ComponentCast & type () const
Type information of the object stored.
const ComponentCast & vector_type () const
Type information of the vector type for extracting data.
virtual void clear ()
Clear the collection (Deletes all valid references to real hits).
void setOptimize (int flag)
Set optimization flags.
void setSensitive (Geant4Sensitive *detector)
Set the sensitive detector.
Geant4Sensitive * sensitive () const
Access the sensitive detector.
virtual G4VHit * GetHit (size_t which) const
Access individual hits.
virtual size_t GetSize () const
Access the collection size.
Geant4HitWrapper & hit (size_t which)
Access the hit wrapper.
const Geant4HitWrapper & hit (size_t which) const
Access the hit wrapper (CONST).
template<typename TYPE >
void add (TYPE *hit_pointer)
Add a new hit with a check, that the hit is of the same type.
template<typename TYPE >
void add (VolumeID key, TYPE *hit_pointer)
Add a new hit with a check, that the hit is of the same type.
template<typename TYPE >
TYPE * find (const Compare &cmp)
Find hits in a collection by comparison of attributes.
template<typename TYPE >
TYPE * findByKey (VolumeID key)
Find hits in a collection by comparison of key value.
template<typename TYPE >
std::vector< TYPE * > releaseHits ()
Release all hits from the Geant4 container and pass ownership to the caller.
void releaseHitsUnchecked (std::vector< void * > &result)
Release all hits from the Geant4 container and pass ownership to the caller.
template<typename TYPE >
std::vector< TYPE * > getHits ()
Release all hits from the Geant4 container. Ownership stays with the container.
void getHitsUnchecked (std::vector< void * > &result)
Release all hits from the Geant4 container. Ownership stays with the container.
Public Attributes
enum
DD4hep::Simulation::Geant4HitCollection:: { ... } OptimizationFlags
Protected Member Functions
void newInstance ()
Notification to increase the instance counter.
void * findHit (const Compare &cmp)
Find hit in a collection by comparison of attributes.
Geant4HitWrapper * findHitByKey (VolumeID key)
Find hit in a collection by comparison of the key.
void releaseData (const ComponentCast &cast, std::vector< void * > *result)
Release all hits from the Geant4 container and pass ownership to the caller.
void getData (const ComponentCast &cast, std::vector< void * > *result)
Release all hits from the Geant4 container. Ownership stays with the container.
Protected Attributes
WrappedHits m_hits
The collection of hit pointers in the wrapped format.
Geant4Sensitive * m_detector
Handle to the sensitive detector.
Manip * m_manipulator
The type of the objects in this collection. Set by the constructor.
size_t m_lastHit
Memorize for speedup the last searched hit.
Keys m_keys
Hit key map for fast random lookup.
CollectionFlags m_flags
Optimization flags.
Detailed Description
Generic hit container class using Geant4HitWrapper objects.
Opaque hit collection. This hit collection is for good reasons homomorph, Polymorphism without an explicit type would only confuse most users.
Note: This hit collection is optimized to search repeatedly the same cell using
template <typename type>=""> TYPE* find(const Compare& cmp) const;
by remembering the last search index. The collection uses this optimization if the corresponding flag OPTIMIZE_REPEATEDLOOKUP is set:
setOptimize(OPTIMIZE_REPEATEDLOOKUP);
The last search index is automatically set to last object insertion, if one happened between 2 search calls. For the typical use case, there always contributions to the same hit are added, this should reduce the lookup speed from O(n) to O(1). This obviously only helps, if contributions to the same cell come in sequence ie. from the same G4Track.
Author:
M.Frank
Version:
1.0
Definition at line 201 of file Geant4HitCollection.h.
Member Typedef Documentation
typedef std::map<VolumeID, size_t> DD4hep::Simulation::Geant4HitCollection::Keys
Hit key map for fast random lookup.
Definition at line 209 of file Geant4HitCollection.h.
typedef Geant4HitWrapper::HitManipulator DD4hep::Simulation::Geant4HitCollection::Manip
Hit manipulator.
Definition at line 207 of file Geant4HitCollection.h.
typedef std::vector<Geant4HitWrapper> DD4hep::Simulation::Geant4HitCollection::WrappedHits
Hit wrapper.
Local type declarations
Definition at line 205 of file Geant4HitCollection.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
OPTIMIZE_NONE
OPTIMIZE_REPEATEDLOOKUP
OPTIMIZE_MAPPEDLOOKUP
OPTIMIZE_LAST
Definition at line 263 of file Geant4HitCollection.h.
Constructor & Destructor Documentation
template<typename TYPE > DD4hep::Simulation::Geant4HitCollection::Geant4HitCollection (const std::string & det, const std::string & coll, Geant4Sensitive * sd) [inline]
Initializing constructor (C++ version).
Definition at line 272 of file Geant4HitCollection.h.
References m_flags, m_hits, newInstance(), OPTIMIZE_REPEATEDLOOKUP, and DD4hep::Simulation::Geant4HitCollection::CollectionFlags::value.
template<typename TYPE > DD4hep::Simulation::Geant4HitCollection::Geant4HitCollection (const std::string & det, const std::string & coll, Geant4Sensitive * sd, const TYPE *) [inline]
Initializing constructor.
Definition at line 283 of file Geant4HitCollection.h.
References m_flags, m_hits, newInstance(), and DD4hep::Simulation::Geant4HitCollection::CollectionFlags::value.
Geant4HitCollection::~Geant4HitCollection () [virtual]
Default destructor.
Definition at line 82 of file Geant4HitCollection.cpp.
References DD4hep::InstanceCount::decrement(), m_hits, and m_keys.
Member Function Documentation
template<typename TYPE > void DD4hep::Simulation::Geant4HitCollection::add (VolumeID key, TYPE * hit_pointer) [inline]
Add a new hit with a check, that the hit is of the same type.
Definition at line 335 of file Geant4HitCollection.h.
References DD4hep::Simulation::Geant4HitWrapper::HitManipulator::castHit(), DD4hep::Utilities::GetName(), m_hits, m_keys, m_lastHit, and m_manipulator.
template<typename TYPE > void DD4hep::Simulation::Geant4HitCollection::add (TYPE * hit_pointer) [inline]
Add a new hit with a check, that the hit is of the same type.
Definition at line 329 of file Geant4HitCollection.h.
References DD4hep::Simulation::Geant4HitWrapper::HitManipulator::castHit(), m_hits, m_lastHit, and m_manipulator.
Referenced by DD4hep::Simulation::TrackerWeighted::extractHit(), DD4hep::Simulation::TrackerCombine::extractHit(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), DD4hep::Simulation::Geant4EscapeCounter::process(), and Tests::Geant4SensitiveAction< T >::process().
void Geant4HitCollection::clear () [virtual]
Clear the collection (Deletes all valid references to real hits).
Definition at line 104 of file Geant4HitCollection.cpp.
References m_hits, m_keys, and m_lastHit.
Referenced by DD4hep::Simulation::moveEntries().
template<typename TYPE > TYPE* DD4hep::Simulation::Geant4HitCollection::find (const Compare & cmp) [inline]
Find hits in a collection by comparison of attributes.
Definition at line 346 of file Geant4HitCollection.h.
References findHit().
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::process().
template<typename TYPE > TYPE* DD4hep::Simulation::Geant4HitCollection::findByKey (VolumeID key) [inline]
Find hits in a collection by comparison of key value.
Definition at line 350 of file Geant4HitCollection.h.
References m_hits, m_keys, and m_lastHit.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::process().
void * Geant4HitCollection::findHit (const Compare & cmp) [protected]
Find hit in a collection by comparison of attributes.
Definition at line 111 of file Geant4HitCollection.cpp.
References DD4hep::Simulation::Geant4HitCollection::CollectionFlags::bits, m_flags, m_hits, m_lastHit, and DD4hep::Simulation::Geant4HitCollection::CollectionFlags::BitItems::repeatedLookup.
Referenced by find().
Geant4HitWrapper * Geant4HitCollection::findHitByKey (VolumeID key) [protected]
Find hit in a collection by comparison of the key.
Definition at line 127 of file Geant4HitCollection.cpp.
References m_hits, m_keys, and m_lastHit.
void Geant4HitCollection::getData (const ComponentCast & cast, std::vector< void * > * result) [protected]
Release all hits from the Geant4 container. Ownership stays with the container.
Definition at line 149 of file Geant4HitCollection.cpp.
References DD4hep::ComponentCast::apply_downCast(), DD4hep::Simulation::Geant4HitWrapper::HitManipulator::cast, DD4hep::Simulation::Geant4HitWrapper::data(), dd4hep::m, m_hits, and DD4hep::Simulation::Geant4HitWrapper::manip().
Referenced by getHits().
virtual G4VHit* DD4hep::Simulation::Geant4HitCollection::GetHit (size_t which) const [inline, virtual]
Access individual hits.
Definition at line 313 of file Geant4HitCollection.h.
References m_hits.
template<typename TYPE > std::vector<TYPE*> DD4hep::Simulation::Geant4HitCollection::getHits () [inline]
Release all hits from the Geant4 container. Ownership stays with the container.
Definition at line 371 of file Geant4HitCollection.h.
References getData(), and m_hits.
void Geant4HitCollection::getHitsUnchecked (std::vector< void * > & result)
Release all hits from the Geant4 container. Ownership stays with the container.
Definition at line 171 of file Geant4HitCollection.cpp.
References DD4hep::Simulation::Geant4HitWrapper::data(), and m_hits.
Referenced by DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
virtual size_t DD4hep::Simulation::Geant4HitCollection::GetSize () const [inline, virtual]
Access the collection size.
Definition at line 317 of file Geant4HitCollection.h.
References m_hits.
Referenced by DD4hep::Simulation::TrackerWeighted::extractHit(), DD4hep::Simulation::moveEntries(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), and DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
const Geant4HitWrapper& DD4hep::Simulation::Geant4HitCollection::hit (size_t which) const [inline]
Access the hit wrapper (CONST).
Definition at line 325 of file Geant4HitCollection.h.
References m_hits.
Geant4HitWrapper& DD4hep::Simulation::Geant4HitCollection::hit (size_t which) [inline]
Access the hit wrapper.
Definition at line 321 of file Geant4HitCollection.h.
References m_hits.
Referenced by DD4hep::Simulation::moveEntries(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), and DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
void Geant4HitCollection::newInstance () [protected]
Notification to increase the instance counter.
Definition at line 99 of file Geant4HitCollection.cpp.
References DD4hep::InstanceCount::increment().
Referenced by Geant4HitCollection().
void Geant4HitCollection::releaseData (const ComponentCast & cast, std::vector< void * > * result) [protected]
Release all hits from the Geant4 container and pass ownership to the caller.
Definition at line 135 of file Geant4HitCollection.cpp.
References DD4hep::ComponentCast::apply_downCast(), DD4hep::Simulation::Geant4HitWrapper::HitManipulator::cast, dd4hep::m, m_hits, m_keys, m_lastHit, DD4hep::Simulation::Geant4HitWrapper::manip(), and DD4hep::Simulation::Geant4HitWrapper::release().
Referenced by releaseHits().
template<typename TYPE > std::vector<TYPE*> DD4hep::Simulation::Geant4HitCollection::releaseHits () [inline]
Release all hits from the Geant4 container and pass ownership to the caller.
Definition at line 358 of file Geant4HitCollection.h.
References m_hits, m_keys, m_lastHit, and releaseData().
void Geant4HitCollection::releaseHitsUnchecked (std::vector< void * > & result)
Release all hits from the Geant4 container and pass ownership to the caller.
Definition at line 161 of file Geant4HitCollection.cpp.
References m_hits, m_keys, m_lastHit, and DD4hep::Simulation::Geant4HitWrapper::release().
Geant4Sensitive* DD4hep::Simulation::Geant4HitCollection::sensitive () const [inline]
Access the sensitive detector.
Definition at line 309 of file Geant4HitCollection.h.
References m_detector.
void DD4hep::Simulation::Geant4HitCollection::setOptimize (int flag) [inline]
Set optimization flags.
Definition at line 301 of file Geant4HitCollection.h.
References m_flags, and DD4hep::Simulation::Geant4HitCollection::CollectionFlags::value.
void DD4hep::Simulation::Geant4HitCollection::setSensitive (Geant4Sensitive * detector) [inline]
Set the sensitive detector.
Definition at line 305 of file Geant4HitCollection.h.
References m_detector.
const ComponentCast & Geant4HitCollection::type () const
Type information of the object stored.
Definition at line 89 of file Geant4HitCollection.cpp.
References DD4hep::Simulation::Geant4HitWrapper::HitManipulator::cast, and m_manipulator.
const ComponentCast & Geant4HitCollection::vector_type () const
Type information of the vector type for extracting data.
Definition at line 94 of file Geant4HitCollection.cpp.
References m_manipulator, and DD4hep::Simulation::Geant4HitWrapper::HitManipulator::vec_type.
Referenced by DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
Member Data Documentation
Geant4Sensitive* DD4hep::Simulation::Geant4HitCollection::m_detector [protected]
Handle to the sensitive detector.
Definition at line 240 of file Geant4HitCollection.h.
Referenced by sensitive(), and setSensitive().
CollectionFlags DD4hep::Simulation::Geant4HitCollection::m_flags [protected]
Optimization flags.
Definition at line 248 of file Geant4HitCollection.h.
Referenced by findHit(), Geant4HitCollection(), and setOptimize().
WrappedHits DD4hep::Simulation::Geant4HitCollection::m_hits [protected]
The collection of hit pointers in the wrapped format.
Definition at line 238 of file Geant4HitCollection.h.
Referenced by add(), clear(), findByKey(), findHit(), findHitByKey(), Geant4HitCollection(), getData(), GetHit(), getHits(), getHitsUnchecked(), GetSize(), hit(), releaseData(), releaseHits(), releaseHitsUnchecked(), and ~Geant4HitCollection().
Keys DD4hep::Simulation::Geant4HitCollection::m_keys [protected]
Hit key map for fast random lookup.
Definition at line 246 of file Geant4HitCollection.h.
Referenced by add(), clear(), findByKey(), findHitByKey(), releaseData(), releaseHits(), releaseHitsUnchecked(), and ~Geant4HitCollection().
size_t DD4hep::Simulation::Geant4HitCollection::m_lastHit [protected]
Memorize for speedup the last searched hit.
Definition at line 244 of file Geant4HitCollection.h.
Referenced by add(), clear(), findByKey(), findHit(), findHitByKey(), releaseData(), releaseHits(), and releaseHitsUnchecked().
Manip* DD4hep::Simulation::Geant4HitCollection::m_manipulator [protected]
The type of the objects in this collection. Set by the constructor.
Definition at line 242 of file Geant4HitCollection.h.
Referenced by add(), type(), and vector_type().
enum { ... } DD4hep::Simulation::Geant4HitCollection::OptimizationFlags
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4HitCollection.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4HitCollection.cpp