DD4hep: DD4hep::Conditions::ConditionDependency Class Reference
DD4hep::Conditions::ConditionDependency Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Condition dependency definition.
#include <ConditionDerived.h>
Public Types
typedef Geometry::DetElement DetElement
typedef std::vector< ConditionKey > Dependencies
Defintion of the depencency container.
typedef Condition::key_type key_type
Forward definition of the key type.
Public Member Functions
ConditionDependency (const ConditionKey &tar, const Dependencies deps, ConditionUpdateCall *call)
Initializing constructor.
ConditionDependency (const ConditionKey &tar, ConditionUpdateCall *call)
Initializing constructor used by builder.
ConditionDependency ()
Default constructor.
key_type key () const
Access the dependency key.
ConditionDependency * addRef ()
Add use count to the object.
void release ()
Release object. May not be used any longer.
Public Attributes
DetElement detector
Reference to the target's detector element.
ConditionKey target
Key to the condition to be updated.
Dependencies dependencies
Dependency keys this condition depends on.
ConditionUpdateCall * callback
Reference to the update callback. No auto pointer. callback may be shared.
Protected Member Functions
ConditionDependency (const ConditionDependency &c)
Copy constructor.
ConditionDependency & operator= (const ConditionDependency &c)
Assignment operator.
virtual ~ConditionDependency ()
Default destructor.
Protected Attributes
int m_refCount
Reference count.
Detailed Description
Condition dependency definition.
Used by clients to update a condition.
Author
M.Frank
Version
1.0
Definition at line 152 of file ConditionDerived.h.
Member Typedef Documentation
Dependencies
typedef std::vector<ConditionKey> DD4hep::Conditions::ConditionDependency::Dependencies
Defintion of the depencency container.
Definition at line 160 of file ConditionDerived.h.
DetElement
typedef Geometry::DetElement DD4hep::Conditions::ConditionDependency::DetElement
Definition at line 158 of file ConditionDerived.h.
key_type
typedef Condition::key_type DD4hep::Conditions::ConditionDependency::key_type
Forward definition of the key type.
Definition at line 162 of file ConditionDerived.h.
Constructor & Destructor Documentation
ConditionDependency() [1/4]
ConditionDependency::ConditionDependency (const ConditionDependency & c) protected
Copy constructor.
Definition at line 60 of file ConditionDerived.cpp.
References DD4hep::Conditions::ConditionUpdateCall::addRef(), callback, DD4hep::except(), DD4hep::InstanceCount::increment(), DD4hep::Conditions::ConditionKey::name, and target.
~ConditionDependency()
ConditionDependency::~ConditionDependency () protected virtual
Default destructor.
Definition at line 71 of file ConditionDerived.cpp.
References callback, DD4hep::InstanceCount::decrement(), and DD4hep::releasePtr().
ConditionDependency() [2/4]
ConditionDependency::ConditionDependency (const ConditionKey & tar, const Dependencies deps, ConditionUpdateCall * call)
Initializing constructor.
Default constructor.
Definition at line 34 of file ConditionDerived.cpp.
References DD4hep::Conditions::ConditionUpdateCall::addRef(), callback, and DD4hep::InstanceCount::increment().
ConditionDependency() [3/4]
ConditionDependency::ConditionDependency (const ConditionKey & tar, ConditionUpdateCall * call)
Initializing constructor used by builder.
Initializing constructor.
Definition at line 44 of file ConditionDerived.cpp.
References DD4hep::Conditions::ConditionUpdateCall::addRef(), callback, and DD4hep::InstanceCount::increment().
ConditionDependency() [4/4]
ConditionDependency::ConditionDependency ()
Default constructor.
Definition at line 53 of file ConditionDerived.cpp.
References DD4hep::InstanceCount::increment().
Member Function Documentation
addRef()
ConditionDependency* DD4hep::Conditions::ConditionDependency::addRef () inline
Add use count to the object.
Definition at line 191 of file ConditionDerived.h.
Referenced by DD4hep::Conditions::ConditionsDependencyCollection::insert().
key()
key_type DD4hep::Conditions::ConditionDependency::key () const inline
Access the dependency key.
Definition at line 189 of file ConditionDerived.h.
References DD4hep::Conditions::ConditionKey::hash.
Referenced by DD4hep::Conditions::ConditionsDependencyCollection::insert().
operator=()
ConditionDependency & ConditionDependency::operator= (const ConditionDependency & c) protected
Assignment operator.
Definition at line 77 of file ConditionDerived.cpp.
References DD4hep::except(), DD4hep::Conditions::ConditionKey::name, and target.
release()
void DD4hep::Conditions::ConditionDependency::release () inline
Release object. May not be used any longer.
Definition at line 193 of file ConditionDerived.h.
Member Data Documentation
callback
ConditionUpdateCall* DD4hep::Conditions::ConditionDependency::callback
Reference to the update callback. No auto pointer. callback may be shared.
Definition at line 171 of file ConditionDerived.h.
Referenced by ConditionDependency(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), and ~ConditionDependency().
dependencies
Dependencies DD4hep::Conditions::ConditionDependency::dependencies
Dependency keys this condition depends on.
Definition at line 169 of file ConditionDerived.h.
Referenced by DD4hep::Conditions::DependencyBuilder::add(), and DD4hep::Conditions::ConditionUpdateContext::key().
detector
DetElement DD4hep::Conditions::ConditionDependency::detector
Reference to the target's detector element.
Definition at line 165 of file ConditionDerived.h.
Referenced by DD4hep::Alignments::AlignmentsManager::adoptDependency(), and DD4hep::Alignments::AlignmentUpdateCall::handle().
m_refCount
int DD4hep::Conditions::ConditionDependency::m_refCount protected
Reference count.
Definition at line 155 of file ConditionDerived.h.
target
ConditionKey DD4hep::Conditions::ConditionDependency::target
Key to the condition to be updated.
Definition at line 167 of file ConditionDerived.h.
Referenced by ConditionDependency(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), operator=(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ConditionDerived.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ConditionDerived.cpp