DD4hep: DD4hep::Simulation::KernelHandle Class Reference
DD4hep::Simulation::KernelHandle Class Reference
DD4hep::Simulation components, classes and objects
Handle to Geant4 actions with built-in creation mechanism.
#include <Geant4Handle.h>
Public Types
typedef Geant4Kernel handled_type
Public Member Functions
KernelHandle ()
Default constructor.
KernelHandle (Geant4Kernel *k)
Construction initialized with object pointer.
KernelHandle (const KernelHandle &k)
Copy constructor.
~KernelHandle ()
Default destructor.
operator handled_type * () const
Conversion operator.
handled_type * get () const
Access to the underlying object.
handled_type * operator-> () const
Access to the underlying object.
KernelHandle worker ()
Access to worker thread.
void destroy ()
Destroy referenced object (program termination)
Public Attributes
handled_type * value
Pointer to referenced object.
Detailed Description
Handle to Geant4 actions with built-in creation mechanism.
Author
M.Frank
Version
1.0
Definition at line 94 of file Geant4Handle.h.
Member Typedef Documentation
handled_type
typedef Geant4Kernel DD4hep::Simulation::KernelHandle::handled_type
Definition at line 96 of file Geant4Handle.h.
Constructor & Destructor Documentation
KernelHandle() [1/3]
DD4hep::Simulation::KernelHandle::KernelHandle () explicit
Default constructor.
Definition at line 209 of file Geant4Handle.cpp.
References DD4hep::Geometry::LCDD::getInstance(), DD4hep::Simulation::Geant4Kernel::instance(), and DD4hep::Simulation::Geant4Handle< TYPE >::value.
Referenced by worker().
KernelHandle() [2/3]
DD4hep::Simulation::KernelHandle::KernelHandle (Geant4Kernel * k) explicit
Construction initialized with object pointer.
Definition at line 212 of file Geant4Handle.cpp.
KernelHandle() [3/3]
DD4hep::Simulation::KernelHandle::KernelHandle (const KernelHandle & k) inline
Copy constructor.
Definition at line 104 of file Geant4Handle.h.
~KernelHandle()
DD4hep::Simulation::KernelHandle::~KernelHandle () inline
Default destructor.
Definition at line 106 of file Geant4Handle.h.
Member Function Documentation
destroy()
void DD4hep::Simulation::KernelHandle::destroy ()
Destroy referenced object (program termination)
Definition at line 219 of file Geant4Handle.cpp.
References value.
get()
handled_type* DD4hep::Simulation::KernelHandle::get () const inline
Access to the underlying object.
Definition at line 110 of file Geant4Handle.h.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
operator handled_type *()
DD4hep::Simulation::KernelHandle::operator handled_type * () const inline
Conversion operator.
Definition at line 108 of file Geant4Handle.h.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
operator->()
handled_type* DD4hep::Simulation::KernelHandle::operator-> () const inline
Access to the underlying object.
Definition at line 112 of file Geant4Handle.h.
References DD4hep::Simulation::Geant4Handle< TYPE >::value.
worker()
KernelHandle DD4hep::Simulation::KernelHandle::worker ()
Access to worker thread.
Definition at line 214 of file Geant4Handle.cpp.
References DD4hep::format(), KernelHandle(), DD4hep::Simulation::Geant4Kernel::thread_self(), value, and DD4hep::Simulation::Geant4Kernel::worker().
Member Data Documentation
value
handled_type* DD4hep::Simulation::KernelHandle::value mutable
Pointer to referenced object.
Definition at line 98 of file Geant4Handle.h.
Referenced by destroy(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), and worker().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Handle.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Handle.cpp