DD4hep: TiXmlString Class Reference
TiXmlString Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinystr.h>
Classes
class Rep
TinyXML class. See http://www.grinninglizard.com/tinyxml.
Public Types
typedef size_t size_type
Public Member Functions
TiXmlString ()
TiXmlString (const TiXmlString &copy)
TIXML_EXPLICIT TiXmlString (const char *copy)
TIXML_EXPLICIT TiXmlString (const char *str, size_type len)
~TiXmlString ()
TiXmlString & operator= (const char *copy)
TiXmlString & operator= (const TiXmlString &copy)
TiXmlString & operator+= (const char *suffix)
TiXmlString & operator+= (char single)
TiXmlString & operator+= (const TiXmlString &suffix)
const char * c_str () const
const char * data () const
size_type length () const
size_type size () const
bool empty () const
size_type capacity () const
const char & at (size_type index) const
char & operator[] (size_type index) const
size_type find (char lookup) const
size_type find (char tofind, size_type offset) const
void clear ()
void reserve (size_type cap)
TiXmlString & assign (const char *str, size_type len)
TiXmlString & append (const char *str, size_type len)
void swap (TiXmlString &other)
Static Public Attributes
static const size_type npos
Private Member Functions
void init (size_type sz)
void set_size (size_type sz)
char * start () const
char * finish () const
void init (size_type sz, size_type cap)
void quit ()
Private Attributes
Rep * rep_
Static Private Attributes
static Rep nullrep_
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 67 of file tinystr.h.
Member Typedef Documentation
size_type
typedef size_t TiXmlString::size_type
Definition at line 71 of file tinystr.h.
Constructor & Destructor Documentation
TiXmlString() [1/4]
TiXmlString::TiXmlString () inline
Definition at line 78 of file tinystr.h.
TiXmlString() [2/4]
TiXmlString::TiXmlString (const TiXmlString & copy) inline
Definition at line 83 of file tinystr.h.
References data(), init(), length(), and start().
TiXmlString() [3/4]
TIXML_EXPLICIT TiXmlString::TiXmlString (const char * copy) inline
Definition at line 90 of file tinystr.h.
References init(), length(), and start().
TiXmlString() [4/4]
TIXML_EXPLICIT TiXmlString::TiXmlString (const char * str, size_type len) inline
Definition at line 97 of file tinystr.h.
References init(), and start().
~TiXmlString()
TiXmlString::~TiXmlString () inline
Definition at line 104 of file tinystr.h.
References quit().
Member Function Documentation
append()
TiXmlString& TiXmlString::append (const char * str, size_type len)
Referenced by clear(), and operator+=().
assign()
TiXmlString& TiXmlString::assign (const char * str, size_type len)
Referenced by clear(), and operator=().
at()
const char& TiXmlString::at (size_type index) const inline
Definition at line 161 of file tinystr.h.
References length(), rep_, and TiXmlString::Rep::str.
c_str()
const char* TiXmlString::c_str () const inline
Definition at line 142 of file tinystr.h.
References rep_, and TiXmlString::Rep::str.
Referenced by find(), operator<(), and operator==().
capacity()
size_type TiXmlString::capacity () const inline
Definition at line 157 of file tinystr.h.
References TiXmlString::Rep::capacity, and rep_.
clear()
void TiXmlString::clear () inline
Definition at line 192 of file tinystr.h.
References append(), assign(), init(), quit(), and reserve().
data()
const char* TiXmlString::data () const inline
Definition at line 145 of file tinystr.h.
References rep_, and TiXmlString::Rep::str.
Referenced by operator+=(), and TiXmlString().
empty()
bool TiXmlString::empty () const inline
Definition at line 154 of file tinystr.h.
References rep_, and TiXmlString::Rep::size.
find() [1/2]
size_type TiXmlString::find (char lookup) const inline
Definition at line 175 of file tinystr.h.
find() [2/2]
size_type TiXmlString::find (char tofind, size_type offset) const inline
Definition at line 181 of file tinystr.h.
References c_str(), length(), and npos.
finish()
char* TiXmlString::finish () const inline private
Definition at line 223 of file tinystr.h.
References rep_, TiXmlString::Rep::size, and TiXmlString::Rep::str.
init() [1/2]
void TiXmlString::init (size_type sz) inline private
Definition at line 220 of file tinystr.h.
References init().
Referenced by clear(), init(), and TiXmlString().
init() [2/2]
void TiXmlString::init (size_type sz, size_type cap) inline private
Definition at line 231 of file tinystr.h.
References TiXmlString::Rep::capacity, nullrep_, rep_, TiXmlString::Rep::size, and TiXmlString::Rep::str.
length()
size_type TiXmlString::length () const inline
Definition at line 148 of file tinystr.h.
References rep_, and TiXmlString::Rep::size.
Referenced by at(), find(), operator+=(), operator=(), operator==(), operator[](), and TiXmlString().
operator+=() [1/3]
TiXmlString& TiXmlString::operator+= (const char * suffix) inline
Definition at line 123 of file tinystr.h.
References append().
operator+=() [2/3]
TiXmlString& TiXmlString::operator+= (char single) inline
Definition at line 129 of file tinystr.h.
References append().
operator+=() [3/3]
TiXmlString& TiXmlString::operator+= (const TiXmlString & suffix) inline
Definition at line 135 of file tinystr.h.
References append(), data(), and length().
operator=() [1/2]
TiXmlString& TiXmlString::operator= (const char * copy) inline
Definition at line 110 of file tinystr.h.
References assign().
operator=() [2/2]
TiXmlString& TiXmlString::operator= (const TiXmlString & copy) inline
Definition at line 116 of file tinystr.h.
References assign(), length(), and start().
operator[]()
char& TiXmlString::operator[] (size_type index) const inline
Definition at line 168 of file tinystr.h.
References length(), rep_, and TiXmlString::Rep::str.
quit()
void TiXmlString::quit () inline private
Definition at line 253 of file tinystr.h.
References nullrep_, and rep_.
Referenced by clear(), and ~TiXmlString().
reserve()
void TiXmlString::reserve (size_type cap)
Referenced by clear().
set_size()
void TiXmlString::set_size (size_type sz) inline private
Definition at line 221 of file tinystr.h.
References rep_, TiXmlString::Rep::size, and TiXmlString::Rep::str.
size()
size_type TiXmlString::size () const inline
Definition at line 151 of file tinystr.h.
References rep_, and TiXmlString::Rep::size.
start()
char* TiXmlString::start () const inline private
Definition at line 222 of file tinystr.h.
References rep_, and TiXmlString::Rep::str.
Referenced by operator=(), and TiXmlString().
swap()
void TiXmlString::swap (TiXmlString & other) inline
Definition at line 211 of file tinystr.h.
References rep_.
Member Data Documentation
npos
const size_type TiXmlString::npos static
Definition at line 74 of file tinystr.h.
Referenced by find().
nullrep_
Rep TiXmlString::nullrep_ static private
Definition at line 264 of file tinystr.h.
Referenced by init(), and quit().
rep_
Rep* TiXmlString::rep_ private
Definition at line 263 of file tinystr.h.
Referenced by at(), c_str(), capacity(), data(), empty(), finish(), init(), length(), operator[](), quit(), set_size(), size(), start(), and swap().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinystr.h