DD4hep: DD4hep: DD4hep::Simulation::Geant4SharedTrackingAction Class Reference
DD4hep::Simulation::Geant4SharedTrackingAction Class Reference
[DD4hep::Simulation components, classes and objects]
Implementation of the Geant4 shared track action.
#include <Geant4TrackingAction.h>
Public Member Functions
Geant4SharedTrackingAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4SharedTrackingAction ()
Default destructor.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
virtual void use (Geant4TrackingAction *action)
Underlying object to be used during the execution of this thread.
virtual void begin (const G4Track *track)
Begin-of-track callback.
virtual void end (const G4Track *track)
End-of-track callback.
Protected Attributes
Geant4TrackingAction * m_action
Reference to the shared action.
Detailed Description
Implementation of the Geant4 shared track action.
Wrapper to share single instances of track actions for multi-threaded purposes. The wrapper ensures the locking of the basic actions to avoid race conditions.
Shared action should be 'fast'. The global lock otherwise inhibits the efficient use of the multiple threads.
Author:
M.Frank
Version:
1.0
Definition at line 75 of file Geant4TrackingAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4SharedTrackingAction::Geant4SharedTrackingAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4SharedTrackingAction::~Geant4SharedTrackingAction () [virtual]
Default destructor.
Definition at line 132 of file Geant4TrackingAction.cpp.
References DD4hep::InstanceCount::decrement(), m_action, and DD4hep::releasePtr().
Member Function Documentation
void Geant4SharedTrackingAction::begin (const G4Track * track) [virtual]
Begin-of-track callback.
Reimplemented from DD4hep::Simulation::Geant4TrackingAction.
Definition at line 154 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4TrackingAction::begin(), DD4hep::Simulation::Geant4Action::context(), and m_action.
void Geant4SharedTrackingAction::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 138 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_action.
void Geant4SharedTrackingAction::end (const G4Track * track) [virtual]
End-of-track callback.
Reimplemented from DD4hep::Simulation::Geant4TrackingAction.
Definition at line 164 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4TrackingAction::end(), and m_action.
void Geant4SharedTrackingAction::use (Geant4TrackingAction * action) [virtual]
Underlying object to be used during the execution of this thread.
Definition at line 143 of file Geant4TrackingAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::PropertyManager::adopt(), m_action, DD4hep::Simulation::Geant4Action::m_properties, and DD4hep::Simulation::Geant4Action::properties().
Member Data Documentation
Geant4TrackingAction* DD4hep::Simulation::Geant4SharedTrackingAction::m_action [protected]
Reference to the shared action.
Definition at line 78 of file Geant4TrackingAction.h.
Referenced by begin(), configureFiber(), end(), use(), and ~Geant4SharedTrackingAction().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4TrackingAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4TrackingAction.cpp