DD4hep: DD4hep: DD4hep::Geometry::Trap Class Reference
DD4hep::Geometry::Trap Class Reference
[DD4hep::Geometry components, classes and objects]
Class describing a trap shape.
#include <Shapes.h>
Public Member Functions
Trap ()
Default constructor.
Trap (const Trap &e)
Constructor to be used when passing an already created object.
template<typename Q >
Trap (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
Trap (const Handle< Q > &e)
Constructor to be used when passing an already created object.
Trap (double z, double theta, double phi, double y1, double x1, double x2, double alpha1, double y2, double x3, double x4, double alpha2)
Constructor to create a new anonymous object with attribute initialization.
Trap (double pz, double py, double px, double pLTX)
Constructor to create a new anonymous object for right angular wedge from STEP (Se G4 manual for details).
template<typename PZ , typename PY , typename PX , typename PLTX >
Trap (PZ pz, PY py, PX px, PLTX pLTX)
Constructor to create a new anonymous object with attribute initialization.
Trap & operator= (const Trap &copy)
Assignment operator.
Trap & setDimensions (double z, double theta, double phi, double y1, double x1, double x2, double alpha1, double y2, double x3, double x4, double alpha2)
Set the trap dimensions.
Private Member Functions
void make (double pz, double py, double px, double pLTX)
Internal helper method to support object construction.
Detailed Description
Class describing a trap shape.
For any further documentation please see the following ROOT documentation:
See also:
http://root.cern.ch/root/html/TGeoTrap.html
Author:
M.Frank
Version:
1.0
Definition at line 395 of file Shapes.h.
Constructor & Destructor Documentation
DD4hep::Geometry::Trap::Trap ()
Default constructor.
DD4hep::Geometry::Trap::Trap (const Trap & e)
Constructor to be used when passing an already created object.
template<typename Q > DD4hep::Geometry::Trap::Trap (const Q * p) [inline]
Constructor to be used with an existing object.
Definition at line 405 of file Shapes.h.
template<typename Q > DD4hep::Geometry::Trap::Trap (const Handle< Q > & e) [inline]
Constructor to be used when passing an already created object.
Definition at line 407 of file Shapes.h.
Trap::Trap (double z, double theta, double phi, double y1, double x1, double x2, double alpha1, double y2, double x3, double x4, double alpha2)
Constructor to create a new anonymous object with attribute initialization.
Constructor to be used when creating a new anonymous object with attribute initialization.
Definition at line 377 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoTrap >::_assign(), and dd4hep::deg.
DD4hep::Geometry::Trap::Trap (double pz, double py, double px, double pLTX) [inline]
Constructor to create a new anonymous object for right angular wedge from STEP (Se G4 manual for details).
Definition at line 413 of file Shapes.h.
References make().
template<typename PZ , typename PY , typename PX , typename PLTX > DD4hep::Geometry::Trap::Trap (PZ pz, PY py, PX px, PLTX pLTX) [inline]
Constructor to create a new anonymous object with attribute initialization.
Definition at line 415 of file Shapes.h.
References DD4hep::_toDouble(), and make().
Member Function Documentation
void Trap::make (double pz, double py, double px, double pLTX) [private]
Internal helper method to support object construction.
Constructor to be used when creating a new anonymous object with attribute initialization.
Definition at line 383 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoTrap >::_assign(), and dd4hep::deg.
Referenced by Trap().
Trap& DD4hep::Geometry::Trap::operator= (const Trap & copy)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
Trap & Trap::setDimensions (double z, double theta, double phi, double y1, double x1, double x2, double alpha1, double y2, double x3, double x4, double alpha2)
Set the trap dimensions.
Definition at line 395 of file Shapes.cpp.
References DD4hep::Geometry::Solid_type< TGeoTrap >::_setDimensions(), and dd4hep::deg.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp