DD4hep: DD4hep::ObjectExtensions Class Reference
DD4hep::ObjectExtensions Class Reference
DD4hep::Geometry components, classes and objects
Implementation of an object supporting arbitrary user extensions.
#include <ObjectExtensions.h>
Classes
struct Entry
Defintiion of the extension entry.
Public Types
typedef std::map< const std::type_info *, void * > Extensions
Definition of the extension type.
typedef void *(* copy_t) (const void *, void *arg)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< const std::type_info *, Entry > ExtensionMap
Public Member Functions
ObjectExtensions (const std::type_info &parent_type)
Default constructor.
ObjectExtensions (const ObjectExtensions &copy)=delete
Copy constructor.
virtual ~ObjectExtensions ()
Default destructor.
ObjectExtensions & operator= (const ObjectExtensions &copy)=delete
Assignment operator.
void move (ObjectExtensions &copy)
Move extensions to target object.
void clear (bool destroy=true)
Clear all extensions.
void copyFrom (const Extensions &ext, void *arg)
Copy object extensions from another object. Hosting type must be identical!
void * addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
void * removeExtension (const std::type_info &info, bool destroy)
Remove an existing extension object from the instance.
void * extension (const std::type_info &info, bool alert) const
Access an existing extension object from the detector element.
void * extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Static Public Member Functions
static void _noDelete (void *)
Function to be passed as dtor if object should NOT be deleted!
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Public Attributes
Extensions extensions
The extensions object.
ExtensionMap * extensionMap
Pointer to the extension map.
Detailed Description
Implementation of an object supporting arbitrary user extensions.
Usage by inheritance of the client supporting the functionality
Author
M.Frank
Version
1.0
Definition at line 31 of file ObjectExtensions.h.
Member Typedef Documentation
copy_t
typedef void*(* DD4hep::ObjectExtensions::copy_t) (const void *, void *arg)
Extensions copy constructor type.
Definition at line 36 of file ObjectExtensions.h.
destruct_t
typedef void(* DD4hep::ObjectExtensions::destruct_t) (void *)
Extensions destructor type.
Definition at line 38 of file ObjectExtensions.h.
ExtensionMap
typedef std::map<const std::type_info*, Entry> DD4hep::ObjectExtensions::ExtensionMap
Definition at line 45 of file ObjectExtensions.h.
Extensions
typedef std::map<const std::type_info*, void*> DD4hep::ObjectExtensions::Extensions
Definition of the extension type.
Definition at line 34 of file ObjectExtensions.h.
Constructor & Destructor Documentation
ObjectExtensions() [1/2]
ObjectExtensions::ObjectExtensions (const std::type_info & parent_type)
Default constructor.
Definition at line 34 of file ObjectExtensions.cpp.
References extensionMap, and DD4hep::InstanceCount::increment().
Referenced by _delete().
ObjectExtensions() [2/2]
DD4hep::ObjectExtensions::ObjectExtensions (const ObjectExtensions & copy) delete
Copy constructor.
~ObjectExtensions()
ObjectExtensions::~ObjectExtensions () virtual
Default destructor.
Definition at line 40 of file ObjectExtensions.cpp.
References clear(), and DD4hep::InstanceCount::decrement().
Referenced by _delete().
Member Function Documentation
_delete()
template<typename T > static void DD4hep::ObjectExtensions::_delete (void * ptr) inline static
Templated destructor function.
Definition at line 56 of file ObjectExtensions.h.
References addExtension(), clear(), DD4hep::ObjectExtensions::Entry::copy, copyFrom(), extension(), move(), ObjectExtensions(), operator=(), removeExtension(), and ~ObjectExtensions().
_noDelete()
static void DD4hep::ObjectExtensions::_noDelete (void *) inline static
Function to be passed as dtor if object should NOT be deleted!
Definition at line 53 of file ObjectExtensions.h.
addExtension() [1/2]
void * ObjectExtensions::addExtension (void * ptr, const std::type_info & info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
Definition at line 83 of file ObjectExtensions.cpp.
References DD4hep::ObjectExtensions::Entry::copy, DD4hep::ObjectExtensions::Entry::destruct, extensionMap, extensions, DD4hep::ObjectExtensions::Entry::id, and DD4hep::typeName().
Referenced by _delete(), addExtension(), DD4hep::Simulation::Geant4Run::addExtension(), DD4hep::Simulation::Geant4Event::addExtension(), and DD4hep::Geometry::LCDDImp::addUserExtension().
addExtension() [2/2]
void * ObjectExtensions::addExtension (void * ptr, const std::type_info & info, destruct_t dtor)
Add an extension object to the detector element.
Definition at line 78 of file ObjectExtensions.cpp.
References addExtension().
clear()
void ObjectExtensions::clear (bool destroy = true)
Clear all extensions.
Internal object destructor: release extension object(s)
Definition at line 52 of file ObjectExtensions.cpp.
References DD4hep::ObjectExtensions::Entry::destruct, e, extensionMap, and extensions.
Referenced by _delete(), DD4hep::Geometry::LCDDData::clearData(), DD4hep::Geometry::LCDDData::destroyData(), DD4hep::Geometry::DetElementObject::~DetElementObject(), DD4hep::Geometry::LCDDImp::~LCDDImp(), ~ObjectExtensions(), and DD4hep::Geometry::SensitiveDetectorObject::~SensitiveDetectorObject().
copyFrom()
void ObjectExtensions::copyFrom (const Extensions & ext, void * arg)
Copy object extensions from another object. Hosting type must be identical!
Copy object extensions from another object.
Definition at line 68 of file ObjectExtensions.cpp.
References DD4hep::ObjectExtensions::Entry::copy, e, extensionMap, and extensions.
Referenced by _delete().
extension() [1/2]
void * ObjectExtensions::extension (const std::type_info & info, bool alert) const
Access an existing extension object from the detector element.
Definition at line 129 of file ObjectExtensions.cpp.
References extensions, and DD4hep::typeName().
Referenced by _delete(), DD4hep::Simulation::Geant4Run::extension(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Conditions::ConditionsManager::from(), and DD4hep::Geometry::LCDDImp::userExtension().
extension() [2/2]
void * ObjectExtensions::extension (const std::type_info & info) const
Access an existing extension object from the detector element.
Definition at line 120 of file ObjectExtensions.cpp.
References extensions, and DD4hep::typeName().
move()
void ObjectExtensions::move (ObjectExtensions & copy)
Move extensions to target object.
Definition at line 46 of file ObjectExtensions.cpp.
References extensions.
Referenced by _delete(), and DD4hep::Geometry::LCDDData::adoptData().
operator=()
ObjectExtensions& DD4hep::ObjectExtensions::operator= (const ObjectExtensions & copy) delete
Assignment operator.
Referenced by _delete().
removeExtension()
void * ObjectExtensions::removeExtension (const std::type_info & info, bool destroy)
Remove an existing extension object from the instance.
Definition at line 101 of file ObjectExtensions.cpp.
References DD4hep::ObjectExtensions::Entry::destruct, e, extensionMap, extensions, and DD4hep::typeName().
Referenced by _delete(), and DD4hep::Geometry::LCDDImp::removeUserExtension().
Member Data Documentation
extensionMap
ExtensionMap* DD4hep::ObjectExtensions::extensionMap
Pointer to the extension map.
Definition at line 50 of file ObjectExtensions.h.
Referenced by addExtension(), clear(), copyFrom(), ObjectExtensions(), and removeExtension().
extensions
Extensions DD4hep::ObjectExtensions::extensions
The extensions object.
Definition at line 48 of file ObjectExtensions.h.
Referenced by addExtension(), clear(), DD4hep::Geometry::DetElementObject::clone(), copyFrom(), extension(), move(), and removeExtension().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ObjectExtensions.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ObjectExtensions.cpp