DD4hep: DD4hep: DD4hep::Simulation::Geant4DetectorGeometryConstruction Class Reference
DD4hep::Simulation::Geant4DetectorGeometryConstruction Class Reference
[DD4hep::Simulation components, classes and objects]
Class to create Geant4 detector geometry from TGeo representation in memory.
Public Member Functions
Geant4DetectorGeometryConstruction (Geant4Context *ctxt, const std::string &nam)
Initializing constructor for DDG4.
virtual ~Geant4DetectorGeometryConstruction ()
Default destructor.
void constructGeo (Geant4DetectorConstructionContext *ctxt)
Geometry construction callback. Called at "Construct()".
Private Attributes
bool m_dumpHierarchy
Property: Dump geometry hierarchy.
std::string m_dumpGDML
Property: G4 GDML dump file name (default: empty. If non empty, dump).
Detailed Description
Class to create Geant4 detector geometry from TGeo representation in memory.
On demand (ie. when calling "Construct") the DD4hep geometry is converted to Geant4 with all volumes, assemblies, shapes, materials etc. The actuak work is performed by the Geant4Converter class called by this method.
Author:
M.Frank
Version:
1.0
Definition at line 34 of file Geant4DetectorGeometryConstruction.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4DetectorGeometryConstruction::Geant4DetectorGeometryConstruction (Geant4Context * ctxt, const std::string & nam)
Initializing constructor for DDG4.
Geant4DetectorGeometryConstruction::~Geant4DetectorGeometryConstruction () [virtual]
Default destructor.
Definition at line 83 of file Geant4DetectorGeometryConstruction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4DetectorGeometryConstruction::constructGeo (Geant4DetectorConstructionContext * ctxt) [virtual]
Geometry construction callback. Called at "Construct()".
Reimplemented from DD4hep::Simulation::Geant4DetectorConstruction.
Definition at line 88 of file Geant4DetectorGeometryConstruction.cpp.
References DD4hep::Geometry::LCDD::apply(), DD4hep::Simulation::Geant4Mapping::attach(), DD4hep::Simulation::Geant4Converter::create(), DD4hep::Simulation::Geant4Mapping::detach(), DD4hep::Simulation::Geant4HierarchyDump::dump(), DD4hep::Simulation::Geant4DetectorConstructionContext::geometry, DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Simulation::Geant4DetectorConstructionContext::lcdd, m_dumpGDML, m_dumpHierarchy, DD4hep::Simulation::Geant4Action::outputLevel(), parser, DD4hep::Simulation::Geant4Mapping::volumeManager(), DD4hep::Simulation::Geant4DetectorConstructionContext::world, DD4hep::Simulation::Geant4GeometryInfo::world(), and DD4hep::Geometry::LCDD::world().
Member Data Documentation
std::string DD4hep::Simulation::Geant4DetectorGeometryConstruction::m_dumpGDML [private]
Property: G4 GDML dump file name (default: empty. If non empty, dump).
Definition at line 38 of file Geant4DetectorGeometryConstruction.cpp.
Referenced by constructGeo().
bool DD4hep::Simulation::Geant4DetectorGeometryConstruction::m_dumpHierarchy [private]
Property: Dump geometry hierarchy.
Definition at line 36 of file Geant4DetectorGeometryConstruction.cpp.
Referenced by constructGeo().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4DetectorGeometryConstruction.cpp