DD4hep: DD4hep::Geometry::SensitiveDetectorObject Class Reference
DD4hep::Geometry::SensitiveDetectorObject Class Reference
DD4hep classes and objects | DD4hep::Geometry components, classes and objects
Data class with properties of sensitive detectors.
#include <DetectorInterna.h>
Public Member Functions
SensitiveDetectorObject ()
Default constructor.
SensitiveDetectorObject (const std::string &nam)
Initializing constructor.
virtual ~SensitiveDetectorObject ()
Internal object destructor: release extension object(s)
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Member Functions inherited from DD4hep::ObjectExtensions
ObjectExtensions (const std::type_info &parent_type)
Default constructor.
ObjectExtensions (const ObjectExtensions &copy)=delete
Copy constructor.
virtual ~ObjectExtensions ()
Default destructor.
ObjectExtensions & operator= (const ObjectExtensions &copy)=delete
Assignment operator.
void move (ObjectExtensions &copy)
Move extensions to target object.
void clear (bool destroy=true)
Clear all extensions.
void copyFrom (const Extensions &ext, void *arg)
Copy object extensions from another object. Hosting type must be identical!
void * addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
void * removeExtension (const std::type_info &info, bool destroy)
Remove an existing extension object from the instance.
void * extension (const std::type_info &info, bool alert) const
Access an existing extension object from the detector element.
void * extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Public Attributes
unsigned int magic
int verbose
int combineHits
double ecut
Readout readout
Region region
LimitSet limits
std::string hitsCollection
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Public Attributes inherited from DD4hep::ObjectExtensions
Extensions extensions
The extensions object.
ExtensionMap * extensionMap
Pointer to the extension map.
Additional Inherited Members
Public Types inherited from DD4hep::ObjectExtensions
typedef std::map< const std::type_info *, void * > Extensions
Definition of the extension type.
typedef void *(* copy_t) (const void *, void *arg)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< const std::type_info *, Entry > ExtensionMap
Static Public Member Functions inherited from DD4hep::ObjectExtensions
static void _noDelete (void *)
Function to be passed as dtor if object should NOT be deleted!
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Detailed Description
Data class with properties of sensitive detectors.
Author
M.Frank
Version
1.0
Definition at line 57 of file DetectorInterna.h.
Constructor & Destructor Documentation
SensitiveDetectorObject() [1/2]
SensitiveDetectorObject::SensitiveDetectorObject ()
Default constructor.
Definition at line 38 of file DetectorInterna.cpp.
References DD4hep::InstanceCount::increment(), DD4hep::printout(), and DD4hep::VERBOSE.
SensitiveDetectorObject() [2/2]
SensitiveDetectorObject::SensitiveDetectorObject (const std::string & nam)
Initializing constructor.
Definition at line 46 of file DetectorInterna.cpp.
References DD4hep::InstanceCount::increment(), DD4hep::printout(), DD4hep::NamedObject::SetName(), and DD4hep::VERBOSE.
~SensitiveDetectorObject()
SensitiveDetectorObject::~SensitiveDetectorObject () virtual
Internal object destructor: release extension object(s)
Definition at line 55 of file DetectorInterna.cpp.
References DD4hep::ObjectExtensions::clear(), DD4hep::Handle< T >::clear(), DD4hep::InstanceCount::decrement(), limits, readout, and region.
Member Data Documentation
combineHits
int DD4hep::Geometry::SensitiveDetectorObject::combineHits
Definition at line 61 of file DetectorInterna.h.
ecut
double DD4hep::Geometry::SensitiveDetectorObject::ecut
Definition at line 62 of file DetectorInterna.h.
hitsCollection
std::string DD4hep::Geometry::SensitiveDetectorObject::hitsCollection
Definition at line 66 of file DetectorInterna.h.
limits
LimitSet DD4hep::Geometry::SensitiveDetectorObject::limits
Definition at line 65 of file DetectorInterna.h.
Referenced by ~SensitiveDetectorObject().
magic
unsigned int DD4hep::Geometry::SensitiveDetectorObject::magic
Definition at line 59 of file DetectorInterna.h.
readout
Readout DD4hep::Geometry::SensitiveDetectorObject::readout
Definition at line 63 of file DetectorInterna.h.
Referenced by ~SensitiveDetectorObject().
region
Region DD4hep::Geometry::SensitiveDetectorObject::region
Definition at line 64 of file DetectorInterna.h.
Referenced by ~SensitiveDetectorObject().
verbose
int DD4hep::Geometry::SensitiveDetectorObject::verbose
Definition at line 60 of file DetectorInterna.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/DetectorInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetectorInterna.cpp