DD4hep: DD4hep::Simulation::Geant4Output2LCIO Class Reference
DD4hep::Simulation::Geant4Output2LCIO Class Reference
DD4hep::Simulation components, classes and objects
Base class to output Geant4 event data to media.
Public Member Functions
Geant4Output2LCIO (Geant4Context *ctxt, const std::string &nam)
Standard constructor.
virtual ~Geant4Output2LCIO ()
Default destructor.
virtual void beginRun (const G4Run *run)
Callback to store the Geant4 run information.
virtual void endRun (const G4Run *run)
Callback to store the Geant4 run information.
virtual void saveRun (const G4Run *run)
Callback to store the Geant4 run information.
virtual void saveEvent (OutputContext< G4Event > &ctxt)
Callback to store the Geant4 event.
virtual void saveCollection (OutputContext< G4Event > &ctxt, G4VHitsCollection *collection)
Callback to store each Geant4 hit collection.
virtual void commit (OutputContext< G4Event > &ctxt)
Commit data at end of filling procedure.
virtual void begin (const G4Event *event)
begin-of-event callback - creates LCIO event and adds it to the event context
Public Member Functions inherited from DD4hep::Simulation::Geant4OutputAction
Geant4OutputAction (Geant4Context *c, const std::string &nam)
Standard constructor.
virtual ~Geant4OutputAction ()
Default destructor.
virtual void configureFiber (Geant4Context *ctxt)
Set or update client for the use in a new thread fiber.
virtual void end (const G4Event *event)
End-of-event callback.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventAction
Geant4EventAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4EventAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Member Functions
lcio::LCCollectionVec * saveParticles (Geant4ParticleMap *particles)
Data conversion interface for MC particles to LCIO format.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes
lcio::LCWriter * m_file
int m_runNo
std::map< std::string, std::string > m_runHeader
Protected Attributes inherited from DD4hep::Simulation::Geant4OutputAction
std::string m_output
Property: "Output" output destination.
bool m_errorFatal
Property: "HandleErrorsAsFatal" Handle errors as fatal and rethrow eventual exceptions.
Geant4ParticleMap * m_truth
Reference to MC truth object.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4EventAction
typedef Geant4SharedEventAction shared_type
Detailed Description
Base class to output Geant4 event data to media.
Author
M.Frank
Version
1.0
Definition at line 53 of file Geant4Output2LCIO.cpp.
Constructor & Destructor Documentation
Geant4Output2LCIO()
Geant4Output2LCIO::Geant4Output2LCIO (Geant4Context * ctxt, const std::string & nam)
Standard constructor.
Definition at line 139 of file Geant4Output2LCIO.cpp.
~Geant4Output2LCIO()
Geant4Output2LCIO::~Geant4Output2LCIO () virtual
Default destructor.
Definition at line 147 of file Geant4Output2LCIO.cpp.
References DD4hep::deletePtr().
Member Function Documentation
begin()
void Geant4Output2LCIO::begin (const G4Event * event) virtual
begin-of-event callback - creates LCIO event and adds it to the event context
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 196 of file Geant4Output2LCIO.cpp.
References e.
beginRun()
void Geant4Output2LCIO::beginRun (const G4Run * run) virtual
Callback to store the Geant4 run information.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 157 of file Geant4Output2LCIO.cpp.
commit()
void Geant4Output2LCIO::commit (OutputContext< G4Event > & ctxt) virtual
Commit data at end of filling procedure.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 171 of file Geant4Output2LCIO.cpp.
References e, and DD4hep::except().
endRun()
void Geant4Output2LCIO::endRun (const G4Run * run) virtual
Callback to store the Geant4 run information.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 166 of file Geant4Output2LCIO.cpp.
saveCollection()
void Geant4Output2LCIO::saveCollection (OutputContext< G4Event > & ctxt, G4VHitsCollection * collection) virtual
Callback to store each Geant4 hit collection.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 324 of file Geant4Output2LCIO.cpp.
References DD4hep::print().
saveEvent()
void Geant4Output2LCIO::saveEvent (OutputContext< G4Event > & ctxt) virtual
Callback to store the Geant4 event.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 306 of file Geant4Output2LCIO.cpp.
References DD4hep::Simulation::Geant4OutputAction::OutputContext< T >::context, e, and DD4hep::print().
saveParticles()
lcio::LCCollectionVec * Geant4Output2LCIO::saveParticles (Geant4ParticleMap * particles) protected
Data conversion interface for MC particles to LCIO format.
Definition at line 204 of file Geant4Output2LCIO.cpp.
References DD4hep::Simulation::Geant4Particle::colorFlow, DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4ParticleHandle::definition(), DD4hep::FATAL, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, DD4hep::Simulation::G4PARTICLE_SIM_BACKSCATTER, DD4hep::Simulation::G4PARTICLE_SIM_CREATED, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_CALO, DD4hep::Simulation::G4PARTICLE_SIM_DECAY_TRACKER, DD4hep::Simulation::G4PARTICLE_SIM_LEFT_DETECTOR, DD4hep::Simulation::G4PARTICLE_SIM_PARENT_RADIATED, DD4hep::Simulation::G4PARTICLE_SIM_STOPPED, dd4hep::GeV, DD4hep::Simulation::Geant4Particle::id, DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::Simulation::Geant4Particle::mass, dd4hep::mm, dd4hep::ns, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4ParticleMap::particleMap, DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::Simulation::Geant4Particle::pex, DD4hep::Simulation::Geant4Particle::pey, DD4hep::Simulation::Geant4Particle::pez, DD4hep::printout(), DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::Simulation::Geant4Particle::spin, DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4Particle::time, DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, and DD4hep::Simulation::Geant4Particle::vsz.
saveRun()
void Geant4Output2LCIO::saveRun (const G4Run * run) virtual
Callback to store the Geant4 run information.
Reimplemented from DD4hep::Simulation::Geant4OutputAction.
Definition at line 182 of file Geant4Output2LCIO.cpp.
References DD4hep::versionString().
Member Data Documentation
m_file
lcio::LCWriter* DD4hep::Simulation::Geant4Output2LCIO::m_file protected
Definition at line 55 of file Geant4Output2LCIO.cpp.
m_runHeader
std::map< std::string, std::string > DD4hep::Simulation::Geant4Output2LCIO::m_runHeader protected
Definition at line 57 of file Geant4Output2LCIO.cpp.
m_runNo
int DD4hep::Simulation::Geant4Output2LCIO::m_runNo protected
Definition at line 56 of file Geant4Output2LCIO.cpp.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/lcio/Geant4Output2LCIO.cpp