DD4hep: DD4hep::GenericEventHandler Class Reference
DD4hep::GenericEventHandler Class Reference
DDEve: DD4hep event display components, classes and objects
Event handler base class. Interface to all DDEve I/O actions.
#include <GenericEventHandler.h>
Public Member Functions
GenericEventHandler ()
Standard constructor.
virtual ~GenericEventHandler ()
Default destructor.
virtual const TypedEventCollections & data () const
Access the map of simulation data collections.
virtual long numEvents () const
Access the number of events on the current input data source (-1 if no data source connected)
virtual std::string datasourceName () const
Access the data source name.
virtual CollectionType collectionType (const std::string &collection) const
Access to the collection type by name.
virtual size_t collectionLoop (const std::string &collection, DDEveHitActor &actor)
Loop over collection and extract data.
virtual size_t collectionLoop (const std::string &collection, DDEveParticleActor &actor)
Loop over collection and extract particle data.
virtual bool Open (const std::string &type, const std::string &file_name)
Open a new event data file.
virtual bool NextEvent ()
Load the next event.
virtual bool PreviousEvent ()
User overloadable function: Load the previous event.
virtual bool GotoEvent (long event_number)
Goto a specified event in the file.
virtual void Subscribe (EventConsumer *display)
Subscribe to notification of new data present.
virtual void Unsubscribe (EventConsumer *display)
Unsubscribe from notification of new data present.
virtual void NotifySubscribers (void(EventConsumer::*pmf)(EventHandler *))
Notfy all subscribers.
ClassDef (GenericEventHandler, 0)
Public Member Functions inherited from DD4hep::EventHandler
EventHandler ()
Standard constructor.
virtual ~EventHandler ()
Default destructor.
virtual bool hasEvent () const
Check if an event is present in memory.
virtual bool hasFile () const
Check if a data file is connected to the handler.
ClassDef (EventHandler, 0)
Protected Types
typedef std::set< EventConsumer * > Subscriptions
Subscriber set.
Protected Member Functions
EventHandler * current () const
Protected Attributes
std::map< std::string, EventHandler * > m_handlers
EventHandler * m_current
Subscriptions m_subscriptions
Data subscriptions (unordered)
Protected Attributes inherited from DD4hep::EventHandler
bool m_hasFile
Flag to indicate that a file is opened.
bool m_hasEvent
Flag to indicate that an event is loaded.
Additional Inherited Members
Public Types inherited from DD4hep::EventHandler
enum CollectionType {
NO_COLLECTION =1<<0, PARTICLE_COLLECTION =1<<1, TRACK_COLLECTION =1<<2, CALO_HIT_COLLECTION =1<<3,
TRACKER_HIT_COLLECTION =1<<4, HIT_COLLECTION =CALO_HIT_COLLECTION|TRACKER_HIT_COLLECTION
}
typedef std::pair< const char *, size_t > Collection
Collection definition: name, size.
typedef std::map< std::string, std::vector< Collection > > TypedEventCollections
Types collection: collections are grouped by type (class name)
Detailed Description
Event handler base class. Interface to all DDEve I/O actions.
Author
M.Frank
Version
1.0
Definition at line 31 of file GenericEventHandler.h.
Member Typedef Documentation
Subscriptions
typedef std::set<EventConsumer*> DD4hep::GenericEventHandler::Subscriptions protected
Subscriber set.
Definition at line 34 of file GenericEventHandler.h.
Constructor & Destructor Documentation
GenericEventHandler()
DD4hep::GenericEventHandler::GenericEventHandler ()
Standard constructor.
~GenericEventHandler()
GenericEventHandler::~GenericEventHandler () virtual
Default destructor.
Definition at line 37 of file GenericEventHandler.cpp.
References DD4hep::deletePtr().
Member Function Documentation
ClassDef()
DD4hep::GenericEventHandler::ClassDef (GenericEventHandler , 0)
Referenced by data().
collectionLoop() [1/2]
size_t GenericEventHandler::collectionLoop (const std::string & collection, DDEveHitActor & actor) virtual
Loop over collection and extract data.
Implements DD4hep::EventHandler.
Definition at line 85 of file GenericEventHandler.cpp.
Referenced by data(), DD4hep::Display::GetCaloHistogram(), and DD4hep::Display::OnNewEvent().
collectionLoop() [2/2]
size_t GenericEventHandler::collectionLoop (const std::string & collection, DDEveParticleActor & actor) virtual
Loop over collection and extract particle data.
Implements DD4hep::EventHandler.
Definition at line 93 of file GenericEventHandler.cpp.
collectionType()
EventHandler::CollectionType GenericEventHandler::collectionType (const std::string & collection) const virtual
Access to the collection type by name.
Implements DD4hep::EventHandler.
Definition at line 77 of file GenericEventHandler.cpp.
Referenced by data().
current()
EventHandler * GenericEventHandler::current () const protected
Definition at line 42 of file GenericEventHandler.cpp.
Referenced by data().
data()
virtual const TypedEventCollections& DD4hep::GenericEventHandler::data () const inline virtual
Access the map of simulation data collections.
Implements DD4hep::EventHandler.
Definition at line 47 of file GenericEventHandler.h.
References ClassDef(), collectionLoop(), collectionType(), current(), DD4hep::EventHandler::data(), datasourceName(), GotoEvent(), NextEvent(), NotifySubscribers(), numEvents(), Open(), PreviousEvent(), Subscribe(), and Unsubscribe().
datasourceName()
string GenericEventHandler::datasourceName () const virtual
Access the data source name.
Implements DD4hep::EventHandler.
Definition at line 72 of file GenericEventHandler.cpp.
Referenced by data().
GotoEvent()
bool GenericEventHandler::GotoEvent (long event_number) virtual
Goto a specified event in the file.
Implements DD4hep::EventHandler.
Definition at line 183 of file GenericEventHandler.cpp.
Referenced by data().
NextEvent()
bool GenericEventHandler::NextEvent () virtual
Load the next event.
Implements DD4hep::EventHandler.
Definition at line 148 of file GenericEventHandler.cpp.
References e.
Referenced by data().
NotifySubscribers()
void GenericEventHandler::NotifySubscribers (void(EventConsumer::*)(EventHandler *) pmf) virtual
Notfy all subscribers.
Definition at line 50 of file GenericEventHandler.cpp.
Referenced by data().
numEvents()
long GenericEventHandler::numEvents () const virtual
Access the number of events on the current input data source (-1 if no data source connected)
Implements DD4hep::EventHandler.
Definition at line 67 of file GenericEventHandler.cpp.
Referenced by data().
Open()
bool GenericEventHandler::Open (const std::string & type, const std::string & file_name) virtual
Open a new event data file.
Implements DD4hep::EventHandler.
Definition at line 101 of file GenericEventHandler.cpp.
References DD4hep::deletePtr(), and e.
Referenced by ClassImp(), and data().
PreviousEvent()
bool GenericEventHandler::PreviousEvent () virtual
User overloadable function: Load the previous event.
Implements DD4hep::EventHandler.
Definition at line 172 of file GenericEventHandler.cpp.
Referenced by data().
Subscribe()
void GenericEventHandler::Subscribe (EventConsumer * display) virtual
Subscribe to notification of new data present.
Definition at line 56 of file GenericEventHandler.cpp.
Referenced by data(), and DD4hep::Display::Display().
Unsubscribe()
void GenericEventHandler::Unsubscribe (EventConsumer * display) virtual
Unsubscribe from notification of new data present.
Definition at line 61 of file GenericEventHandler.cpp.
Referenced by data().
Member Data Documentation
m_current
EventHandler* DD4hep::GenericEventHandler::m_current protected
Definition at line 36 of file GenericEventHandler.h.
m_handlers
std::map<std::string,EventHandler*> DD4hep::GenericEventHandler::m_handlers protected
Definition at line 35 of file GenericEventHandler.h.
m_subscriptions
Subscriptions DD4hep::GenericEventHandler::m_subscriptions protected
Data subscriptions (unordered)
Definition at line 38 of file GenericEventHandler.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/GenericEventHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/GenericEventHandler.cpp