DD4hep: DD4hep: DD4hep::Simulation::Geant4ReadoutVolumeFilter Class Reference
DD4hep::Simulation::Geant4ReadoutVolumeFilter Class Reference
[DD4hep::Simulation components, classes and objects]
Default base class for all geant 4 tracking actions.
#include <Geant4ReadoutVolumeFilter.h>
Public Member Functions
Geant4ReadoutVolumeFilter (Geant4Context *context, const std::string &name, Readout ro, const std::string &coll)
Standard constructor.
virtual ~Geant4ReadoutVolumeFilter ()
Default destructor.
virtual bool operator() (const G4Step *step) const
Filter action. Return true if hits should be processed.
Protected Attributes
Readout m_readout
Reference to readout descriptor.
const Collection * m_collection
Collection index.
Field m_key
Bit field value from ID descriptor.
Private Types
typedef
Geometry::IDDescriptor::Field Field
typedef Geometry::Readout Readout
typedef Readout::Collection Collection
Detailed Description
Default base class for all geant 4 tracking actions.
Author:
M.Frank
Version:
1.0
Definition at line 34 of file Geant4ReadoutVolumeFilter.h.
Member Typedef Documentation
typedef Readout::Collection DD4hep::Simulation::Geant4ReadoutVolumeFilter::Collection [private]
Definition at line 37 of file Geant4ReadoutVolumeFilter.h.
typedef Geometry::IDDescriptor::Field DD4hep::Simulation::Geant4ReadoutVolumeFilter::Field [private]
Definition at line 35 of file Geant4ReadoutVolumeFilter.h.
typedef Geometry::Readout DD4hep::Simulation::Geant4ReadoutVolumeFilter::Readout [private]
Definition at line 36 of file Geant4ReadoutVolumeFilter.h.
Constructor & Destructor Documentation
Geant4ReadoutVolumeFilter::Geant4ReadoutVolumeFilter (Geant4Context * context, const std::string & name, Readout ro, const std::string & coll)
Standard constructor.
Definition at line 27 of file Geant4ReadoutVolumeFilter.cpp.
References DD4hep::Simulation::Geant4Action::except(), DD4hep::Geometry::IDDescriptor::field(), DD4hep::Geometry::Readout::idSpec(), DD4hep::InstanceCount::increment(), DD4hep::Geometry::HitCollection::key, m_collection, m_key, DD4hep::Handle< T >::name(), and DD4hep::Geometry::HitCollection::name.
Geant4ReadoutVolumeFilter::~Geant4ReadoutVolumeFilter () [virtual]
Default destructor.
Definition at line 47 of file Geant4ReadoutVolumeFilter.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
bool Geant4ReadoutVolumeFilter::operator() (const G4Step * step) const [virtual]
Filter action. Return true if hits should be processed.
Reimplemented from DD4hep::Simulation::Geant4Filter.
Definition at line 52 of file Geant4ReadoutVolumeFilter.cpp.
References DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Geometry::HitCollection::key_max, DD4hep::Geometry::HitCollection::key_min, m_collection, m_key, DD4hep::Simulation::Geant4StepHandler::preTouchable(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), and DD4hep::Simulation::Geant4Mapping::volumeManager().
Member Data Documentation
const Collection* DD4hep::Simulation::Geant4ReadoutVolumeFilter::m_collection [protected]
Collection index.
Definition at line 43 of file Geant4ReadoutVolumeFilter.h.
Referenced by Geant4ReadoutVolumeFilter(), and operator()().
Field DD4hep::Simulation::Geant4ReadoutVolumeFilter::m_key [protected]
Bit field value from ID descriptor.
Definition at line 45 of file Geant4ReadoutVolumeFilter.h.
Referenced by Geant4ReadoutVolumeFilter(), and operator()().
Readout DD4hep::Simulation::Geant4ReadoutVolumeFilter::m_readout [protected]
Reference to readout descriptor.
Definition at line 41 of file Geant4ReadoutVolumeFilter.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ReadoutVolumeFilter.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ReadoutVolumeFilter.cpp