DD4hep: DD4hep::Simulation::Geant4Random Class Reference
DD4hep::Simulation::Geant4Random Class Reference
DD4hep::Simulation components, classes and objects
Mini interface to THE random generator of the application.
#include <Geant4Random.h>
Public Member Functions
Geant4Random (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4Random ()
Default destructor.
void initialize ()
Initialize the instance.
CLHEP::HepRandomEngine * engine ()
CLHEP random number engine (valid after initialization only)
virtual void setSeed (long seed)
Should initialise the status of the algorithm according to seed.
virtual void setSeeds (const long *seeds, int size)
Should initialise the status of the algorithm.
virtual void saveStatus (const char filename[]="Config.conf") const
Should save on a file specific to the instantiated engine in use the current status.
virtual void restoreStatus (const char filename[]="Config.conf")
Should read from a file and restore the last saved engine configuration.
virtual void showStatus () const
Should dump the current engine status on the screen.
double rndm_clhep ()
Create flat distributed random numbers in the interval ]0,1] calling CLHEP.
double rndm (int i=0)
Create flat distributed random numbers in the interval ]0,1].
void rndmArray (int n, float *array)
Create a float array of flat distributed random numbers in the interval ]0,1].
void rndmArray (int n, double *array)
Create a double array of flat distributed random numbers in the interval ]0,1].
double uniform (double x1=1)
Create uniformly disributed random numbers in the interval ]0,x1].
double uniform (double x1, double x2)
Create uniformly disributed random numbers in the interval ]x1,x2].
double exp (double tau)
Create exponentially distributed random numbers.
double gauss (double mean=0, double sigma=1)
Create gaussian distributed random numbers.
double landau (double mean=0, double sigma=1)
Create landau distributed random numbers.
void circle (double &x, double &y, double r)
Create tuple of randum number around a circle with radius r.
void sphere (double &x, double &y, double &z, double r)
Create tuple of randum number on a sphere with radius r.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Static Public Member Functions
static Geant4Random * instance (bool throw_exception=true)
Access the main Geant4 random generator instance. Must be created before used!
static Geant4Random * setMainInstance (Geant4Random *ptr)
Make this random generator instance the one used by Geant4.
Protected Attributes
std::string m_file
Property: File name if initialized from file. If set, engine name and seeds are ignored.
std::string m_engineType
Property: Engine type. default: "HepJamesRandom".
long m_seed
Property: Initial random seed. Default: 123456789.
long m_luxury
bool m_replace
Property: Indicator to replace the ROOT gRandom instance.
CLHEP::HepRandomEngine * m_engine
Reference to the CLHEP random number engine (valid only after initialization)
TRandom * m_rootRandom
Reference to ROOT random instance.
TRandom * m_rootOLD
bool m_inited
Flag to remember initialization.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Friends
class Geant4Exec
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Mini interface to THE random generator of the application.
Mini interface to THE random generator of the application. Necessary, that on every object creates its own instance, but accesses the main instance avaible throu the Geant4Context.
This is mandatory to ensure reproducability of the event generation process. Particular objects may use a dependent generator from an experiment framework like GAUDI.
This main interface is supposed to be stable. Unclear however is if the generation functions will have to become virtual.... Future will tell us.
The first instance of the random action is automatically set to be the Geant4 instance. If another instance should be used by Geant4, use setMainInstance(Geant4Random* ptr).
Author
M.Frank
Version
1.0
Definition at line 60 of file Geant4Random.h.
Constructor & Destructor Documentation
Geant4Random()
Geant4Random::Geant4Random (Geant4Context * context, const std::string & name)
Standard constructor.
Default constructor.
Please Note: Should be used only for initialization of the main instance. Subsequent usage should be invoked using the class member Geant4Random::instance().
Parameters
context Geant4 context for this action.
name Name of the action object
Definition at line 79 of file Geant4Random.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_engineType, m_file, m_luxury, m_replace, and m_seed.
~Geant4Random()
Geant4Random::~Geant4Random () virtual
Default destructor.
Definition at line 94 of file Geant4Random.cpp.
References DD4hep::InstanceCount::decrement(), DD4hep::deletePtr(), m_rootOLD, and m_rootRandom.
Member Function Documentation
circle()
void Geant4Random::circle (double & x, double & y, double r)
Create tuple of randum number around a circle with radius r.
Definition at line 309 of file Geant4Random.cpp.
References initialize(), and m_inited.
engine()
CLHEP::HepRandomEngine* DD4hep::Simulation::Geant4Random::engine () inline
CLHEP random number engine (valid after initialization only)
Access to the CLHEP random number engine. For further doc see CLHEP/Random/RandomEngine.h
Definition at line 117 of file Geant4Random.h.
Referenced by DD4hep::Simulation::Geant4EventSeed::begin().
exp()
double Geant4Random::exp (double tau)
Create exponentially distributed random numbers.
Definition at line 291 of file Geant4Random.cpp.
References initialize(), and m_inited.
gauss()
double Geant4Random::gauss (double mean = 0, double sigma = 1)
Create gaussian distributed random numbers.
Generates random vectors, uniformly distributed over a circle of given radius.
Definition at line 297 of file Geant4Random.cpp.
References initialize(), and m_inited.
Referenced by DD4hep::Simulation::Geant4InteractionVertexSmear::smear().
initialize()
void Geant4Random::initialize ()
Initialize the instance.
Called either by user or on request of the first random number. To propagate the engine to Geant4, initialize MUST be called by the user.
Create new engine if a type is specified
Definition at line 155 of file Geant4Random.cpp.
References DD4hep::Simulation::Geant4Action::except(), m_engineType, m_file, m_inited, m_luxury, m_rootRandom, m_seed, and setMainInstance().
Referenced by circle(), DD4hep::Simulation::Geant4Exec::configure(), exp(), gauss(), landau(), restoreStatus(), rndm(), rndm_clhep(), rndmArray(), setMainInstance(), setSeed(), setSeeds(), sphere(), and uniform().
instance()
Geant4Random * Geant4Random::instance (bool throw_exception = true) static
Access the main Geant4 random generator instance. Must be created before used!
Definition at line 110 of file Geant4Random.cpp.
Referenced by DD4hep::Simulation::Geant4EventSeed::begin(), DD4hep::Simulation::Geant4EventSeed::beginEvent(), DD4hep::Simulation::Geant4Exec::configure(), and DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::createClientContext().
landau()
double Geant4Random::landau (double mean = 0, double sigma = 1)
Create landau distributed random numbers.
Definition at line 303 of file Geant4Random.cpp.
References initialize(), and m_inited.
restoreStatus()
void Geant4Random::restoreStatus (const char filename[] = "Config.conf") virtual
Should read from a file and restore the last saved engine configuration.
Definition at line 221 of file Geant4Random.cpp.
References initialize(), and m_inited.
rndm()
double Geant4Random::rndm (int i = 0)
Create flat distributed random numbers in the interval ]0,1].
Definition at line 261 of file Geant4Random.cpp.
References initialize(), and m_inited.
Referenced by DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionCosTheta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionEta(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionFFbar(), and DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirectionUniform().
rndm_clhep()
double Geant4Random::rndm_clhep ()
Create flat distributed random numbers in the interval ]0,1] calling CLHEP.
Create flat distributed random numbers in the interval ]0,1].
Basic random generator functionsThis is more or less a test function, since the result should be identical to calling rndm.
Definition at line 255 of file Geant4Random.cpp.
References initialize(), and m_inited.
rndmArray() [1/2]
void Geant4Random::rndmArray (int n, float * array)
Create a float array of flat distributed random numbers in the interval ]0,1].
Definition at line 267 of file Geant4Random.cpp.
References initialize(), and m_inited.
rndmArray() [2/2]
void Geant4Random::rndmArray (int n, double * array)
Create a double array of flat distributed random numbers in the interval ]0,1].
Definition at line 273 of file Geant4Random.cpp.
References initialize(), and m_inited.
saveStatus()
void Geant4Random::saveStatus (const char filename[] = "Config.conf") const virtual
Should save on a file specific to the instantiated engine in use the current status.
Definition at line 213 of file Geant4Random.cpp.
References DD4hep::Simulation::Geant4Action::except(), and m_inited.
setMainInstance()
Geant4Random * Geant4Random::setMainInstance (Geant4Random * ptr) static
Make this random generator instance the one used by Geant4.
Returns reference to previous instance. It is up to the user to manage the reference. Caveat: other code may hold references to this instance.
Parameters
ptr Reference to main random number generator
Returns
Reference to previous random number generator instance
Definition at line 118 of file Geant4Random.cpp.
References initialize(), m_engine, m_inited, m_replace, m_rootOLD, m_rootRandom, and DD4hep::Simulation::Geant4Action::printP2().
Referenced by DD4hep::Simulation::Geant4Exec::configure(), and initialize().
setSeed()
void Geant4Random::setSeed (long seed) virtual
Should initialise the status of the algorithm according to seed.
Definition at line 196 of file Geant4Random.cpp.
References initialize(), m_inited, and m_seed.
Referenced by DD4hep::Simulation::Geant4EventSeed::beginEvent().
setSeeds()
void Geant4Random::setSeeds (const long * seeds, int size) virtual
Should initialise the status of the algorithm.
Initialization according to the zero terminated array of seeds. It is allowed to ignore one or many seeds in this array.
Definition at line 206 of file Geant4Random.cpp.
References initialize(), m_inited, and m_seed.
showStatus()
void Geant4Random::showStatus () const virtual
Should dump the current engine status on the screen.
Definition at line 227 of file Geant4Random.cpp.
References DD4hep::Simulation::Geant4Action::error(), m_engine, m_engineType, m_file, m_inited, m_rootRandom, and DD4hep::Simulation::Geant4Action::printP2().
Referenced by DD4hep::Simulation::Geant4EventSeed::beginEvent().
sphere()
void Geant4Random::sphere (double & x, double & y, double & z, double r)
Create tuple of randum number on a sphere with radius r.
Definition at line 315 of file Geant4Random.cpp.
References initialize(), and m_inited.
uniform() [1/2]
double Geant4Random::uniform (double x1 = 1)
Create uniformly disributed random numbers in the interval ]0,x1].
Definition at line 279 of file Geant4Random.cpp.
References initialize(), and m_inited.
uniform() [2/2]
double Geant4Random::uniform (double x1, double x2)
Create uniformly disributed random numbers in the interval ]x1,x2].
Definition at line 285 of file Geant4Random.cpp.
References initialize(), and m_inited.
Friends And Related Function Documentation
Geant4Exec
friend class Geant4Exec friend
Definition at line 61 of file Geant4Random.h.
Member Data Documentation
m_engine
CLHEP::HepRandomEngine* DD4hep::Simulation::Geant4Random::m_engine protected
Reference to the CLHEP random number engine (valid only after initialization)
Definition at line 74 of file Geant4Random.h.
Referenced by setMainInstance(), and showStatus().
m_engineType
std::string DD4hep::Simulation::Geant4Random::m_engineType protected
Property: Engine type. default: "HepJamesRandom".
Definition at line 67 of file Geant4Random.h.
Referenced by Geant4Random(), initialize(), and showStatus().
m_file
std::string DD4hep::Simulation::Geant4Random::m_file protected
Property: File name if initialized from file. If set, engine name and seeds are ignored.
Definition at line 65 of file Geant4Random.h.
Referenced by Geant4Random(), initialize(), and showStatus().
m_inited
bool DD4hep::Simulation::Geant4Random::m_inited protected
Flag to remember initialization.
Definition at line 79 of file Geant4Random.h.
Referenced by circle(), exp(), gauss(), initialize(), landau(), restoreStatus(), rndm(), rndm_clhep(), rndmArray(), saveStatus(), setMainInstance(), setSeed(), setSeeds(), showStatus(), sphere(), and uniform().
m_luxury
long DD4hep::Simulation::Geant4Random::m_luxury protected
Definition at line 69 of file Geant4Random.h.
Referenced by Geant4Random(), and initialize().
m_replace
bool DD4hep::Simulation::Geant4Random::m_replace protected
Property: Indicator to replace the ROOT gRandom instance.
Definition at line 71 of file Geant4Random.h.
Referenced by Geant4Random(), and setMainInstance().
m_rootOLD
TRandom * DD4hep::Simulation::Geant4Random::m_rootOLD protected
Definition at line 77 of file Geant4Random.h.
Referenced by setMainInstance(), and ~Geant4Random().
m_rootRandom
TRandom* DD4hep::Simulation::Geant4Random::m_rootRandom protected
Reference to ROOT random instance.
Definition at line 77 of file Geant4Random.h.
Referenced by initialize(), setMainInstance(), showStatus(), and ~Geant4Random().
m_seed
long DD4hep::Simulation::Geant4Random::m_seed protected
Property: Initial random seed. Default: 123456789.
Definition at line 69 of file Geant4Random.h.
Referenced by Geant4Random(), initialize(), setSeed(), and setSeeds().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Random.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Random.cpp