DD4hep: DD4hep: DD4hep::ReferenceBitMask< T > Class Template Reference
DD4hep::ReferenceBitMask< T > Class Template Reference
Data structure to manipulate a bitmask held by reference and represented by an integer.
#include <Primitives.h>
Public Member Functions
ReferenceBitMask (T &m)
Standard constructor.
T value () const
void set (const T &m)
void clear (const T &m)
void clear ()
bool isSet (const T &m) const
bool anySet (const T &m) const
bool testBit (int bit) const
bool isNull () const
Public Attributes
T & mask
Reference to the data.
Detailed Description
template<typename T>
class DD4hep::ReferenceBitMask< T >
Data structure to manipulate a bitmask held by reference and represented by an integer.
Author:
M.Frank
Version:
1.0
Definition at line 526 of file Primitives.h.
Constructor & Destructor Documentation
template<typename T > DD4hep::ReferenceBitMask< T >::ReferenceBitMask (T & m) [inline]
Standard constructor.
Definition at line 559 of file Primitives.h.
Member Function Documentation
template<typename T> bool DD4hep::ReferenceBitMask< T >::anySet (const T & m) const [inline]
Definition at line 547 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::mask.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::checkConsistency().
template<typename T> void DD4hep::ReferenceBitMask< T >::clear () [inline]
Definition at line 541 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::mask.
template<typename T> void DD4hep::ReferenceBitMask< T >::clear (const T & m) [inline]
Definition at line 538 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::mask.
Referenced by DD4hep::Simulation::HepMC::read_particle().
template<typename T> bool DD4hep::ReferenceBitMask< T >::isNull () const [inline]
Definition at line 554 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::mask.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::defaultKeepParticle(), DD4hep::Simulation::Geant4ParticleHandler::end(), and DD4hep::Simulation::Geant4ParticleHandler::recombineParents().
template<typename T> bool DD4hep::ReferenceBitMask< T >::isSet (const T & m) const [inline]
Definition at line 544 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::mask.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::checkConsistency(), DD4hep::Simulation::Geant4ParticleHandler::defaultKeepParticle(), DD4hep::Simulation::Geant4ParticleHandle::dump4(), DD4hep::Simulation::Geant4ParticleHandler::end(), DD4hep::Simulation::Geant4TCUserParticleHandler::end(), getRelevant(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4DataDump::print(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), DD4hep::Simulation::Geant4ParticlePrint::printParticles(), DD4hep::Simulation::Geant4ParticlePrint::printParticleTree(), DD4hep::Simulation::Geant4ParticleHandler::recombineParents(), DD4hep::Simulation::Geant4Output2LCIO::saveParticles(), and DD4hep::ReferenceBitMask< T >::testBit().
template<typename T> void DD4hep::ReferenceBitMask< T >::set (const T & m) [inline]
Definition at line 535 of file Primitives.h.
References dd4hep::m, and DD4hep::ReferenceBitMask< T >::mask.
Referenced by collectPrimaries(), DD4hep::Simulation::createPrimary(), DD4hep::Simulation::Geant4ParticleHandler::end(), DD4hep::Simulation::Geant4TCUserParticleHandler::end(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::Geant4ParticleHandler::mark(), DD4hep::Simulation::HepMC::read_particle(), and DD4hep::Simulation::Geant4ParticleHandler::recombineParents().
template<typename T> bool DD4hep::ReferenceBitMask< T >::testBit (int bit) const [inline]
Definition at line 550 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::isSet(), and dd4hep::m.
template<typename T> T DD4hep::ReferenceBitMask< T >::value () const [inline]
Definition at line 532 of file Primitives.h.
References DD4hep::ReferenceBitMask< T >::mask.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::recombineParents().
Member Data Documentation
template<typename T> T& DD4hep::ReferenceBitMask< T >::mask
Reference to the data.
Definition at line 529 of file Primitives.h.
Referenced by DD4hep::ReferenceBitMask< T >::anySet(), DD4hep::ReferenceBitMask< T >::clear(), DD4hep::ReferenceBitMask< T >::isNull(), DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::ReferenceBitMask< T >::set(), and DD4hep::ReferenceBitMask< T >::value().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Primitives.h