DD4hep: DD4hep::Simulation::HepMC::EventStream Class Reference
DD4hep::Simulation::HepMC::EventStream Class Reference
Public Types
typedef std::map< int, Geant4Vertex * > Vertices
typedef std::map< int, Geant4Particle * > Particles
Public Member Functions
EventStream (istream &in)
bool ok () const
Check if data stream is in proper state and has data.
Geant4Vertex * vertex (int i)
Particles & particles ()
Vertices & vertices ()
void set_io (int typ, const string &k)
void use_default_units ()
bool read ()
void clear ()
Public Attributes
istream & instream
string key
double mom_unit
double pos_unit
int io_type
float xsection
float xsection_err
EventHeader header
Vertices m_vertices
Particles m_particles
Detailed Description
Definition at line 116 of file Geant4EventReaderHepMC.cpp.
Member Typedef Documentation
Particles
typedef std::map<int,Geant4Particle*> DD4hep::Simulation::HepMC::EventStream::Particles
Definition at line 119 of file Geant4EventReaderHepMC.cpp.
Vertices
typedef std::map<int,Geant4Vertex*> DD4hep::Simulation::HepMC::EventStream::Vertices
Definition at line 118 of file Geant4EventReaderHepMC.cpp.
Constructor & Destructor Documentation
EventStream()
DD4hep::Simulation::HepMC::EventStream::EventStream (istream & in) inline
Definition at line 134 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::vertex().
Member Function Documentation
clear()
void HepMC::EventStream::clear ()
Definition at line 610 of file Geant4EventReaderHepMC.cpp.
References DD4hep::releaseObjects().
Referenced by DD4hep::Simulation::HepMC::read_weight_names(), and DD4hep::Simulation::Geant4EventReaderHepMC::readParticles().
ok()
bool HepMC::EventStream::ok () const
Check if data stream is in proper state and has data.
Definition at line 601 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::Geant4EventReaderHepMC::readParticles().
particles()
Particles& DD4hep::Simulation::HepMC::EventStream::particles () inline
Definition at line 140 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::fix_particles(), DD4hep::Simulation::HepMC::read_particle(), DD4hep::Simulation::HepMC::read_vertex(), and DD4hep::Simulation::Geant4EventReaderHepMC::readParticles().
read()
bool HepMC::EventStream::read ()
Definition at line 615 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::ascii, DD4hep::Simulation::HepMC::ascii_pdt, DD4hep::Simulation::HepMC::extascii, DD4hep::Simulation::HepMC::extascii_pdt, DD4hep::Simulation::HepMC::fix_particles(), DD4hep::Simulation::HepMC::gen, DD4hep::Simulation::HepMC::get_input(), DD4hep::printout(), DD4hep::Simulation::HepMC::read_cross_section(), DD4hep::Simulation::HepMC::read_event_header(), DD4hep::Simulation::HepMC::read_heavy_ion(), DD4hep::Simulation::HepMC::read_pdf(), DD4hep::Simulation::HepMC::read_units(), DD4hep::Simulation::HepMC::read_until_event_end(), DD4hep::Simulation::HepMC::read_vertex(), DD4hep::Simulation::HepMC::read_weight_names(), DD4hep::releaseObjects(), and DD4hep::WARNING.
Referenced by DD4hep::Simulation::Geant4EventReaderHepMC::moveToEvent(), and DD4hep::Simulation::Geant4EventReaderHepMC::readParticles().
set_io()
void DD4hep::Simulation::HepMC::EventStream::set_io (int typ, const string & k) inline
Definition at line 142 of file Geant4EventReaderHepMC.cpp.
use_default_units()
void DD4hep::Simulation::HepMC::EventStream::use_default_units () inline
Definition at line 144 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::fix_particles(), DD4hep::Simulation::HepMC::get_input(), dd4hep::MeV, dd4hep::mm, DD4hep::Simulation::HepMC::read_cross_section(), DD4hep::Simulation::HepMC::read_event_header(), DD4hep::Simulation::HepMC::read_heavy_ion(), DD4hep::Simulation::HepMC::read_particle(), DD4hep::Simulation::HepMC::read_pdf(), DD4hep::Simulation::HepMC::read_units(), DD4hep::Simulation::HepMC::read_until_event_end(), DD4hep::Simulation::HepMC::read_vertex(), DD4hep::Simulation::HepMC::read_weight_names(), and DD4hep::Simulation::HepMC::vertex().
vertex()
Geant4Vertex* DD4hep::Simulation::HepMC::EventStream::vertex (int i)
vertices()
Vertices& DD4hep::Simulation::HepMC::EventStream::vertices () inline
Definition at line 141 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::fix_particles(), DD4hep::Simulation::HepMC::read_vertex(), and DD4hep::Simulation::HepMC::vertex().
Member Data Documentation
header
EventHeader DD4hep::Simulation::HepMC::EventStream::header
Definition at line 129 of file Geant4EventReaderHepMC.cpp.
instream
istream& DD4hep::Simulation::HepMC::EventStream::instream
Definition at line 121 of file Geant4EventReaderHepMC.cpp.
io_type
int DD4hep::Simulation::HepMC::EventStream::io_type
Definition at line 126 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::read_event_header(), DD4hep::Simulation::HepMC::read_particle(), and DD4hep::Simulation::HepMC::read_units().
key
string DD4hep::Simulation::HepMC::EventStream::key
Definition at line 124 of file Geant4EventReaderHepMC.cpp.
m_particles
Particles DD4hep::Simulation::HepMC::EventStream::m_particles
Definition at line 131 of file Geant4EventReaderHepMC.cpp.
m_vertices
Vertices DD4hep::Simulation::HepMC::EventStream::m_vertices
Definition at line 130 of file Geant4EventReaderHepMC.cpp.
mom_unit
double DD4hep::Simulation::HepMC::EventStream::mom_unit
Definition at line 125 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::read_particle(), and DD4hep::Simulation::HepMC::read_units().
pos_unit
double DD4hep::Simulation::HepMC::EventStream::pos_unit
Definition at line 125 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::read_units(), and DD4hep::Simulation::HepMC::read_vertex().
xsection
float DD4hep::Simulation::HepMC::EventStream::xsection
Definition at line 128 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::read_cross_section().
xsection_err
float DD4hep::Simulation::HepMC::EventStream::xsection_err
Definition at line 128 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::read_cross_section().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4EventReaderHepMC.cpp