DD4hep: DD4hep::Simulation::Geant4PrimaryEvent Class Reference
DD4hep::Simulation::Geant4PrimaryEvent Class Reference
Class modelling a complete primary event with multiple interactions.
#include <Geant4Primary.h>
Public Types
typedef Geant4PrimaryInteraction Interaction
typedef std::map< int, Interaction * > Interactions
typedef dd4hep_ptr< PrimaryExtension > ExtensionHandle
Public Member Functions
Geant4PrimaryEvent ()
Default constructor.
virtual ~Geant4PrimaryEvent ()
Default destructor.
void add (int id, Geant4PrimaryInteraction *interaction)
Add a new interaction object to the event.
Geant4PrimaryInteraction * get (int id) const
Retrieve an interaction by it's ID.
size_t size () const
Number of interaction contained in the primary event.
std::vector< Geant4PrimaryInteraction * > interactions () const
Retrieve all interactions.
Public Attributes
ExtensionHandle extension
User data extension if required.
Protected Attributes
Interactions m_interactions
Set of primary interactions.
Private Member Functions
Geant4PrimaryEvent (const Geant4PrimaryEvent &c)
Copy constructor.
Geant4PrimaryEvent & operator= (const Geant4PrimaryEvent &c)
Assignment operator.
Detailed Description
Class modelling a complete primary event with multiple interactions.
Definition at line 144 of file Geant4Primary.h.
Member Typedef Documentation
ExtensionHandle
typedef dd4hep_ptr<PrimaryExtension> DD4hep::Simulation::Geant4PrimaryEvent::ExtensionHandle
Definition at line 154 of file Geant4Primary.h.
Interaction
typedef Geant4PrimaryInteraction DD4hep::Simulation::Geant4PrimaryEvent::Interaction
Definition at line 152 of file Geant4Primary.h.
Interactions
typedef std::map<int,Interaction*> DD4hep::Simulation::Geant4PrimaryEvent::Interactions
Definition at line 153 of file Geant4Primary.h.
Constructor & Destructor Documentation
Geant4PrimaryEvent() [1/2]
Geant4PrimaryEvent::Geant4PrimaryEvent (const Geant4PrimaryEvent & c) private
Copy constructor.
Definition at line 111 of file Geant4Primary.cpp.
Geant4PrimaryEvent() [2/2]
Geant4PrimaryEvent::Geant4PrimaryEvent ()
Default constructor.
Definition at line 106 of file Geant4Primary.cpp.
~Geant4PrimaryEvent()
Geant4PrimaryEvent::~Geant4PrimaryEvent () virtual
Default destructor.
Definition at line 122 of file Geant4Primary.cpp.
References DD4hep::destroyObjects().
Member Function Documentation
add()
void Geant4PrimaryEvent::add (int id, Geant4PrimaryInteraction * interaction)
Add a new interaction object to the event.
Definition at line 127 of file Geant4Primary.cpp.
References DD4hep::Simulation::Geant4PrimaryInteraction::mask.
Referenced by DD4hep::Simulation::Geant4GeneratorWrapper::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::operator()(), and DD4hep::Simulation::Geant4InputAction::operator()().
get()
Geant4PrimaryEvent::Interaction * Geant4PrimaryEvent::get (int id) const
Retrieve an interaction by it's ID.
Definition at line 144 of file Geant4Primary.cpp.
Referenced by DD4hep::Simulation::Geant4InteractionVertexBoost::operator()(), DD4hep::Simulation::Geant4InteractionVertexSmear::operator()(), and DD4hep::Simulation::Geant4ParticleGenerator::printInteraction().
interactions()
std::vector< Geant4PrimaryEvent::Interaction * > Geant4PrimaryEvent::interactions () const
Retrieve all interactions.
Retrieve all intractions.
Definition at line 153 of file Geant4Primary.cpp.
References v.
Referenced by DD4hep::Simulation::mergeInteractions(), DD4hep::Simulation::Geant4InteractionMerger::operator()(), DD4hep::Simulation::Geant4InteractionVertexBoost::operator()(), and DD4hep::Simulation::Geant4InteractionVertexSmear::operator()().
operator=()
Geant4PrimaryEvent & Geant4PrimaryEvent::operator= (const Geant4PrimaryEvent & c) private
Assignment operator.
Definition at line 116 of file Geant4Primary.cpp.
size()
size_t DD4hep::Simulation::Geant4PrimaryEvent::size () const inline
Number of interaction contained in the primary event.
Definition at line 174 of file Geant4Primary.h.
Member Data Documentation
extension
ExtensionHandle DD4hep::Simulation::Geant4PrimaryEvent::extension
User data extension if required.
Definition at line 162 of file Geant4Primary.h.
Referenced by DD4hep::Simulation::mergeInteractions().
m_interactions
Interactions DD4hep::Simulation::Geant4PrimaryEvent::m_interactions protected
Set of primary interactions.
Definition at line 158 of file Geant4Primary.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Primary.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Primary.cpp