DD4hep: DD4hep::Simulation::Geant4HierarchyDump Class Reference
DD4hep::Simulation::Geant4HierarchyDump Class Reference
DD4hep::Simulation components, classes and objects
Helper to dump Geant4 volume hierarchy.
#include <Geant4HierarchyDump.h>
Public Types
typedef Geometry::LCDD LCDD
Public Member Functions
Geant4HierarchyDump (LCDD &lcdd)
Initializing Constructor.
virtual ~Geant4HierarchyDump ()
Standard destructor.
virtual void dump (const std::string &indent, const G4VPhysicalVolume *vol) const
Dump the volume hierarchy as it is known to geant 4.
Public Attributes
LCDD & m_lcdd
Detailed Description
Helper to dump Geant4 volume hierarchy.
Author
M.Frank
Version
1.0
Definition at line 38 of file Geant4HierarchyDump.h.
Member Typedef Documentation
LCDD
typedef Geometry::LCDD DD4hep::Simulation::Geant4HierarchyDump::LCDD
Definition at line 40 of file Geant4HierarchyDump.h.
Constructor & Destructor Documentation
Geant4HierarchyDump()
Geant4HierarchyDump::Geant4HierarchyDump (LCDD & lcdd)
Initializing Constructor.
Definition at line 85 of file Geant4HierarchyDump.cpp.
~Geant4HierarchyDump()
Geant4HierarchyDump::~Geant4HierarchyDump () virtual
Standard destructor.
Definition at line 90 of file Geant4HierarchyDump.cpp.
Member Function Documentation
dump()
void Geant4HierarchyDump::dump (const std::string & indent, const G4VPhysicalVolume * vol) const virtual
Dump the volume hierarchy as it is known to geant 4.
Definition at line 93 of file Geant4HierarchyDump.cpp.
References _T(), G4DUMP_LIMITS, G4DUMP_SENSDET, G4DUMP_SOLID, DD4hep::INFO, m_flags, DD4hep::printout(), and DD4hep::yes_no().
Referenced by DD4hep::Simulation::Geant4DetectorGeometryConstruction::constructGeo().
Member Data Documentation
m_lcdd
LCDD& DD4hep::Simulation::Geant4HierarchyDump::m_lcdd
Definition at line 41 of file Geant4HierarchyDump.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4HierarchyDump.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4HierarchyDump.cpp