DD4hep: DD4hep::Simulation::Geant4GenericSD< T > Class Template Reference
DD4hep::Simulation::Geant4GenericSD< T > Class Template Reference
Deprecated: Example G4VSensitiveDetector implementation.
#include <Defs.h>
Public Member Functions
Geant4GenericSD (const std::string &name, LCDD &lcdd)
Constructor. The sensitive detector element is identified by the detector name.
virtual bool defineCollection (const std::string &coll_name)
Initialize the sensitive detector for the usage of a single hit collection.
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
Method for generating hit(s) using the information of G4Step object.
virtual void Initialize (G4HCofThisEvent *HCE)
virtual void EndOfEvent (G4HCofThisEvent *HCE)
Method invoked at the end of each event.
virtual void clear ()
This method is invoked if the event abortion is occured.
virtual bool buildHits (G4Step *step, G4TouchableHistory *history)
Method for generating hit(s) using the information of G4Step object.
Public Member Functions inherited from DD4hep::Simulation::Geant4SensitiveDetector
Geant4SensitiveDetector (const std::string &name, LCDD &lcdd)
Constructor. The sensitive detector element is identified by the detector name.
virtual ~Geant4SensitiveDetector ()
Standard destructor.
std::string name () const
Standard access to the name.
virtual HitCollection * createCollection (const std::string &coll_name) const
Create single hits collection.
const std::string & hitCollectionName (int which) const
Access HitCollection container names.
HitCollection * collection (int id)
Retrieve the hits collection associated with this detector by its serial number.
HitCollection * collectionByID (int id)
Retrieve the hits collection associated with this detector by its collection identifier.
long long getVolumeID (G4Step *step)
long long getCellID (G4Step *step)
virtual G4bool process (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
Private Attributes
T userData
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4SensitiveDetector
typedef Geometry::SensitiveDetector SensitiveDetector
typedef G4THitsCollection< Geant4Hit > HitCollection
typedef Geant4Hit::Contribution HitContribution
typedef Geant4StepHandler StepHandler
Protected Member Functions inherited from DD4hep::Simulation::Geant4SensitiveDetector
template<typename T >
T * find (const HitCollection *c, const HitCompare< T > &cmp)
Find hits by position in a collection.
void dumpStep (G4Step *step, G4TouchableHistory *history)
Dump Step information (careful: very verbose)
template<>
Geant4CalorimeterHit * find (const HitCollection *c, const HitCompare< Geant4CalorimeterHit > &cmp)
Protected Attributes inherited from DD4hep::Simulation::Geant4SensitiveDetector
LCDD & m_lcdd
Reference to the detector description object.
DetElement m_detector
Reference to the detector element describing this sensitive element.
SensitiveDetector m_sensitive
Reference to the sensitive detector element.
Readout m_readout
Reference to the readout structure.
G4HCofThisEvent * m_hce
Geant4 event context.
Detailed Description
template<class T>
class DD4hep::Simulation::Geant4GenericSD< T >
Deprecated: Example G4VSensitiveDetector implementation.
Deprecated:
Deprecated class. Not supported by the DDG4 kernel.
Definition at line 43 of file Defs.h.
Constructor & Destructor Documentation
Geant4GenericSD()
template<class SD > DD4hep::Simulation::Geant4GenericSD< SD >::Geant4GenericSD (const std::string & name, LCDD & lcdd)
Constructor. The sensitive detector element is identified by the detector name.
Definition at line 22 of file Geant4SensitiveDetector_inline.h.
References DD4hep::Simulation::Geant4GenericSD< T >::defineCollection(), DD4hep::Geometry::SensitiveDetector::hitsCollection(), and DD4hep::Simulation::Geant4SensitiveDetector::m_sensitive.
Member Function Documentation
buildHits()
template<class SD > bool DD4hep::Simulation::Geant4GenericSD< SD >::buildHits (G4Step * step, G4TouchableHistory * history) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4SensitiveDetector.
Definition at line 56 of file Geant4SensitiveDetector_inline.h.
clear()
template<class SD > void DD4hep::Simulation::Geant4GenericSD< SD >::clear () virtual
This method is invoked if the event abortion is occured.
Method invoked if the event was aborted.
Hits collections created but not beibg set to G4HCofThisEvent at the event should be deleted. Collection(s) which have already set to G4HCofThisEvent will be deleted automatically.
Reimplemented from DD4hep::Simulation::Geant4SensitiveDetector.
Definition at line 46 of file Geant4SensitiveDetector_inline.h.
References DD4hep::Simulation::Geant4SensitiveDetector::clear().
defineCollection()
template<class SD > bool DD4hep::Simulation::Geant4GenericSD< SD >::defineCollection (const std::string & coll_name) virtual
Initialize the sensitive detector for the usage of a single hit collection.
Reimplemented from DD4hep::Simulation::Geant4SensitiveDetector.
Definition at line 28 of file Geant4SensitiveDetector_inline.h.
References DD4hep::Simulation::Geant4SensitiveDetector::defineCollection().
Referenced by DD4hep::Simulation::Geant4GenericSD< T >::Geant4GenericSD().
EndOfEvent()
template<class SD > void DD4hep::Simulation::Geant4GenericSD< SD >::EndOfEvent (G4HCofThisEvent * HCE) virtual
Method invoked at the end of each event.
Reimplemented from DD4hep::Simulation::Geant4SensitiveDetector.
Definition at line 41 of file Geant4SensitiveDetector_inline.h.
References DD4hep::Simulation::Geant4SensitiveDetector::EndOfEvent().
Initialize()
template<class SD > void DD4hep::Simulation::Geant4GenericSD< SD >::Initialize (G4HCofThisEvent * HCE) virtual
Method invoked at the begining of each event. The hits collection(s) created by this sensitive detector must be set to the G4HCofThisEvent object at one of these two methods.
Reimplemented from DD4hep::Simulation::Geant4SensitiveDetector.
Definition at line 36 of file Geant4SensitiveDetector_inline.h.
References DD4hep::Simulation::Geant4SensitiveDetector::Initialize().
ProcessHits()
template<class SD > G4bool DD4hep::Simulation::Geant4GenericSD< SD >::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4SensitiveDetector.
Definition at line 51 of file Geant4SensitiveDetector_inline.h.
References DD4hep::Simulation::Geant4SensitiveDetector::ProcessHits().
Member Data Documentation
userData
template<class T > T DD4hep::Simulation::Geant4GenericSD< T >::userData private
Definition at line 144 of file Geant4SensitiveDetector.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Defs.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensitiveDetector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensitiveDetector_inline.h