DD4hep: DD4hep::Simulation::Geant4UserParticleHandler Class Reference
DD4hep::Simulation::Geant4UserParticleHandler Class Reference
Geant4ParticleHandler user extension action called by the particle handler.
#include <Geant4UserParticleHandler.h>
Public Types
typedef Geant4Particle Particle
Public Member Functions
Geant4UserParticleHandler (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4UserParticleHandler ()
Default destructor.
virtual void generate (G4Event *event, Geant4ParticleHandler *handler)
Event generation action callback.
virtual void begin (const G4Event *event)
Pre-event action callback.
virtual void end (const G4Event *event)
Post-event action callback.
virtual void step (const G4Step *step, G4SteppingManager *mgr, Particle &particle)
User stepping callback.
virtual void begin (const G4Track *track, Particle &particle)
Pre-track action callback.
virtual void end (const G4Track *track, Particle &particle)
Post-track action callback.
virtual bool keepParticle (Particle &particle)
Callback to be answered if the particle MUST be kept during recombination step.
virtual void combine (Particle &to_be_deleted, Particle &remaining_parent)
Callback when parent should be combined.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
double m_kinEnergyCut
Property: Energy cut below which particles are not collected, but assigned to the parent.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Geant4ParticleHandler user extension action called by the particle handler.
Collect optional MC particle information and attach it to the particle object Clients may inherit from this class and override the approriate methods to add additional information in form of a DataExtension object to the Particle.
The default implementation is always empty!
Author
M.Frank
Version
1.0
Definition at line 49 of file Geant4UserParticleHandler.h.
Member Typedef Documentation
Particle
typedef Geant4Particle DD4hep::Simulation::Geant4UserParticleHandler::Particle
Definition at line 51 of file Geant4UserParticleHandler.h.
Constructor & Destructor Documentation
Geant4UserParticleHandler()
Geant4UserParticleHandler::Geant4UserParticleHandler (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 25 of file Geant4UserParticleHandler.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_kinEnergyCut, DD4hep::Simulation::Geant4Action::m_needsControl, and dd4hep::MeV.
Referenced by DD4hep::Simulation::Geant4TCUserParticleHandler::~Geant4TCUserParticleHandler().
~Geant4UserParticleHandler()
Geant4UserParticleHandler::~Geant4UserParticleHandler () virtual
Default destructor.
Definition at line 34 of file Geant4UserParticleHandler.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
begin() [1/2]
void Geant4UserParticleHandler::begin (const G4Event * event) virtual
Pre-event action callback.
Definition at line 44 of file Geant4UserParticleHandler.cpp.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::begin(), and DD4hep::Simulation::Geant4ParticleHandler::beginEvent().
begin() [2/2]
void Geant4UserParticleHandler::begin (const G4Track * track, Particle & particle) virtual
Pre-track action callback.
Allow the user to intercept particle handling in the pre track action. e.g. attach relevant user information. The default implementation is empty.
Note: The particle passed is a temporary and will be copied if kept.
Definition at line 57 of file Geant4UserParticleHandler.cpp.
combine()
void Geant4UserParticleHandler::combine (Particle & to_be_deleted, Particle & remaining_parent) virtual
Callback when parent should be combined.
Called before a particle is removed from the final record. Relevant particle properties of the parent may be updated. The default implementation is empty.
Definition at line 65 of file Geant4UserParticleHandler.cpp.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::recombineParents().
end() [1/2]
void Geant4UserParticleHandler::end (const G4Event * event) virtual
Post-event action callback.
Reimplemented in DD4hep::Simulation::Geant4TCUserParticleHandler.
Definition at line 48 of file Geant4UserParticleHandler.cpp.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::end(), and DD4hep::Simulation::Geant4ParticleHandler::endEvent().
end() [2/2]
void Geant4UserParticleHandler::end (const G4Track * track, Particle & particle) virtual
Post-track action callback.
Allow the user to force the particle handling in the post track action set the reason mask to NULL in order to drop the particle. The parent's reasoning mask will be or'ed with the particle's mask to preserve the MC truth for the hit creation. The default implementation is empty.
Note: The particle passed is a temporary and will be copied if kept.
Reimplemented in DD4hep::Simulation::Geant4TCUserParticleHandler.
Definition at line 61 of file Geant4UserParticleHandler.cpp.
generate()
void Geant4UserParticleHandler::generate (G4Event * event, Geant4ParticleHandler * handler) virtual
Event generation action callback.
Definition at line 39 of file Geant4UserParticleHandler.cpp.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::operator()().
keepParticle()
bool Geant4UserParticleHandler::keepParticle (Particle & particle) virtual
Callback to be answered if the particle MUST be kept during recombination step.
Allow the user to force the particle handling either by or the reason mask with G4PARTICLE_KEEP_USER or to set the reason mask to NULL in order to drop it. The default implementation is empty.
If the reason mask entry is set to G4PARTICLE_FORCE_KILL or is set to NULL, the particle is ALWAYS removed
The default implementation calls Geant4ParticleHandler::defaultKeepParticle(particle) Please have a look therein if it suffices your needs!
Note: This may override all other decisions! Default implementation is empty.
Definition at line 69 of file Geant4UserParticleHandler.cpp.
References DD4hep::Simulation::Geant4ParticleHandler::defaultKeepParticle().
Referenced by DD4hep::Simulation::Geant4ParticleHandler::recombineParents().
step()
void Geant4UserParticleHandler::step (const G4Step * step, G4SteppingManager * mgr, Particle & particle) virtual
User stepping callback.
Allow the user to intercept particle handling in the pre track action. The default implementation is empty.
Note: The particle passed is a temporary and will be copied if kept.
Definition at line 53 of file Geant4UserParticleHandler.cpp.
Referenced by DD4hep::Simulation::Geant4ParticleHandler::step().
Member Data Documentation
m_kinEnergyCut
double DD4hep::Simulation::Geant4UserParticleHandler::m_kinEnergyCut protected
Property: Energy cut below which particles are not collected, but assigned to the parent.
Definition at line 55 of file Geant4UserParticleHandler.h.
Referenced by Geant4UserParticleHandler().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4UserParticleHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4UserParticleHandler.cpp