DD4hep: DD4hep::Layer Class Reference
DD4hep::Layer Class Reference
DD4hep classes and objects
Class to describe one layer in a layering stack.
#include <Layering.h>
Public Member Functions
Layer ()
Default constructor.
Layer (const Layer &c)
Copy constructor.
Layer & operator= (const Layer &c)
Assignment operator.
void compute ()
double thickness () const
double thicknessWithPreOffset () const
void add (const LayerSlice &s)
Public Attributes
double _thickness
double _preOffset
std::vector< LayerSlice > _slices
Detailed Description
Class to describe one layer in a layering stack.
Author
M.Frank
Version
1.0
Definition at line 61 of file Layering.h.
Constructor & Destructor Documentation
Layer() [1/2]
DD4hep::Layer::Layer () inline
Default constructor.
Definition at line 87 of file Layering.h.
Layer() [2/2]
Layer::Layer (const Layer & c)
Copy constructor.
Definition at line 39 of file Layering.cpp.
Member Function Documentation
add()
void DD4hep::Layer::add (const LayerSlice & s) inline
Definition at line 81 of file Layering.h.
Referenced by DD4hep::XML::LayeringCnv::fromCompact().
compute()
void Layer::compute ()
Definition at line 52 of file Layering.cpp.
References _slices, and _thickness.
Referenced by DD4hep::XML::LayeringCnv::fromCompact().
operator=()
Layer & Layer::operator= (const Layer & c)
Assignment operator.
Definition at line 43 of file Layering.cpp.
References _preOffset, _slices, and _thickness.
thickness()
double DD4hep::Layer::thickness () const inline
Definition at line 75 of file Layering.h.
References DD4hep::LayerSlice::_thickness.
Referenced by DD4hep::Layering::absorberThicknessInLayer(), create_detector(), and DD4hep::Layering::singleLayerThickness().
thicknessWithPreOffset()
double DD4hep::Layer::thicknessWithPreOffset () const inline
Definition at line 78 of file Layering.h.
Referenced by DD4hep::LayerStack::sectionThickness().
Member Data Documentation
_preOffset
double DD4hep::Layer::_preOffset
Definition at line 64 of file Layering.h.
Referenced by operator=().
_slices
std::vector<LayerSlice> DD4hep::Layer::_slices
Definition at line 65 of file Layering.h.
Referenced by compute(), and operator=().
_thickness
double DD4hep::Layer::_thickness
Definition at line 63 of file Layering.h.
Referenced by compute(), and operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/Layering.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/Layering.cpp