DD4hep: DD4hep: DD4hep::Path::detail Class Reference
DD4hep::Path::detail Class Reference
Helpers.
#include <Path.h>
Static Public Member Functions
static const Path & dot_path ()
Path representing ".".
static const Path & dot_dot_path ()
Path representing "..".
Detailed Description
Helpers.
Definition at line 96 of file Path.h.
Member Function Documentation
const Path & Path::detail::dot_dot_path () [static]
Path representing "..".
Definition at line 101 of file Path.cpp.
const Path & Path::detail::dot_path () [static]
Path representing ".".
Definition at line 97 of file Path.cpp.
Referenced by DD4hep::Path::file_path(), DD4hep::Path::filename(), and DD4hep::Path::normalize().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Path.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Path.cpp