DD4hep: DD4hep::DDSegmentation::SegmentationCreatorBase Class Reference
DD4hep::DDSegmentation::SegmentationCreatorBase Class Reference abstract
Base class for the SegmentationCreator objects. Allows to use the factory without template.
#include <SegmentationFactory.h>
Public Member Functions
SegmentationCreatorBase (const std::string &name)
Default constructor. Takes the class name as argument and takes care of registration with the factory.
virtual ~SegmentationCreatorBase ()
Destructor.
virtual Segmentation * create (const std::string &identifier) const =0
Create a new object.
Detailed Description
Base class for the SegmentationCreator objects. Allows to use the factory without template.
Definition at line 27 of file SegmentationFactory.h.
Constructor & Destructor Documentation
SegmentationCreatorBase()
DD4hep::DDSegmentation::SegmentationCreatorBase::SegmentationCreatorBase (const std::string & name)
Default constructor. Takes the class name as argument and takes care of registration with the factory.
Definition at line 17 of file SegmentationFactory.cpp.
References DD4hep::DDSegmentation::SegmentationFactory::_instance, DD4hep::DDSegmentation::SegmentationFactory::instance(), and DD4hep::DDSegmentation::SegmentationFactory::registerSegmentation().
~SegmentationCreatorBase()
virtual DD4hep::DDSegmentation::SegmentationCreatorBase::~SegmentationCreatorBase () inline virtual
Destructor.
Definition at line 32 of file SegmentationFactory.h.
References create().
Member Function Documentation
create()
virtual Segmentation* DD4hep::DDSegmentation::SegmentationCreatorBase::create (const std::string & identifier) const pure virtual
Create a new object.
Implemented in DD4hep::DDSegmentation::SegmentationCreator< TYPE >.
Referenced by ~SegmentationCreatorBase().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/SegmentationFactory.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/SegmentationFactory.cpp