DD4hep: DD4hep::DDRec::MaterialManager Class Reference
DD4hep::DDRec::MaterialManager Class Reference
#include <MaterialManager.h>
Public Member Functions
MaterialManager ()
~MaterialManager ()
const MaterialVec & materialsBetween (const DDSurfaces::Vector3D &p0, const DDSurfaces::Vector3D &p1, double epsilon=1e-4)
const Material & materialAt (const DDSurfaces::Vector3D &pos)
MaterialData createAveragedMaterial (const MaterialVec &materials)
Protected Attributes
MaterialVec _mV
Material _m
DDSurfaces::Vector3D _p0
DDSurfaces::Vector3D _p1
DDSurfaces::Vector3D _pos
TGeoManager * _tgeoMgr
Detailed Description
Material manager provides access to the material properties of the detector. Material can be accessed either for a given point or as a list of materials along a straight line between two points.
Author
F.Gaede, DESY
Date
May, 19 2014
Version
$Id:$
Definition at line 30 of file MaterialManager.h.
Constructor & Destructor Documentation
MaterialManager()
DD4hep::DDRec::MaterialManager::MaterialManager ()
Definition at line 16 of file MaterialManager.cpp.
References _tgeoMgr, DD4hep::Geometry::LCDD::getInstance(), DD4hep::Geometry::DetElement::volume(), and DD4hep::Geometry::LCDD::world().
~MaterialManager()
DD4hep::DDRec::MaterialManager::~MaterialManager ()
Definition at line 21 of file MaterialManager.cpp.
Member Function Documentation
createAveragedMaterial()
MaterialData DD4hep::DDRec::MaterialManager::createAveragedMaterial (const MaterialVec & materials)
Create a material with averaged properties from all materials in the list. A and Z are averaged by relative number of atoms(molecules), rho is averaged by relative volume and the inverse radiation and interaction lengths are averaged by relative weight.
Definition at line 172 of file MaterialManager.cpp.
References DD4hep::Geometry::Material::A(), DD4hep::Geometry::Material::density(), DD4hep::Geometry::Material::intLength(), DD4hep::Handle< T >::name(), DD4hep::Geometry::Material::radLength(), and DD4hep::Geometry::Material::Z().
Referenced by DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::Surface::innerMaterial(), and DD4hep::DDRec::Surface::outerMaterial().
materialAt()
const Geometry::Material & DD4hep::DDRec::MaterialManager::materialAt (const DDSurfaces::Vector3D & pos)
Get the material at the given position.
Definition at line 150 of file MaterialManager.cpp.
References _m, _pos, and _tgeoMgr.
materialsBetween()
const MaterialVec & DD4hep::DDRec::MaterialManager::materialsBetween (const DDSurfaces::Vector3D & p0, const DDSurfaces::Vector3D & p1, double epsilon = 1e-4)
Get a vector with all the materials between the two points p0 and p1 with the corresponding thicknesses - element type is std::pair< Material, double >. Materials with a thickness smaller than epsilon (default 1e-4=1mu) are ignored. Avoid calling this method in inner loops as the computation is not cheap. Ideally the result should be cached, for example as an averaged material
See also
createAveragedMaterial().
Definition at line 25 of file MaterialManager.cpp.
References _mV, _p0, _p1, _tgeoMgr, and MINSTEP.
Referenced by DD4hep::DDRec::createGearForILD(), DD4hep::DDRec::Surface::innerMaterial(), and DD4hep::DDRec::Surface::outerMaterial().
Member Data Documentation
_m
Material DD4hep::DDRec::MaterialManager::_m protected
Definition at line 60 of file MaterialManager.h.
Referenced by materialAt().
_mV
MaterialVec DD4hep::DDRec::MaterialManager::_mV protected
Definition at line 59 of file MaterialManager.h.
Referenced by materialsBetween().
_p0
DDSurfaces::Vector3D DD4hep::DDRec::MaterialManager::_p0 protected
Definition at line 63 of file MaterialManager.h.
Referenced by materialsBetween().
_p1
DDSurfaces::Vector3D DD4hep::DDRec::MaterialManager::_p1 protected
Definition at line 63 of file MaterialManager.h.
Referenced by materialsBetween().
_pos
DDSurfaces::Vector3D DD4hep::DDRec::MaterialManager::_pos protected
Definition at line 63 of file MaterialManager.h.
Referenced by materialAt().
_tgeoMgr
TGeoManager* DD4hep::DDRec::MaterialManager::_tgeoMgr protected
Definition at line 65 of file MaterialManager.h.
Referenced by materialAt(), MaterialManager(), and materialsBetween().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/MaterialManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/MaterialManager.cpp