DD4hep: DD4hep::Geometry::GeoScan Class Reference
DD4hep::Geometry::GeoScan Class Reference
DD4hep::Geometry components, classes and objects
Geometry scanner (handle object)
#include <GeoHandler.h>
Public Member Functions
GeoScan (DetElement e)
Initializing constructor.
GeoScan (DetElement e, bool propagateRegions)
Initializing constructor.
virtual ~GeoScan ()
Default destructor.
virtual GeoScan & operator() ()
Work callback.
Protected Attributes
GeoHandler::Data * m_data
Data holder.
Detailed Description
Geometry scanner (handle object)
Author
M.Frank
Version
1.0
Definition at line 143 of file GeoHandler.h.
Constructor & Destructor Documentation
GeoScan() [1/2]
GeoScan::GeoScan (DetElement e)
Initializing constructor.
Definition at line 152 of file GeoHandler.cpp.
References DD4hep::Geometry::GeoHandler::GeoHandler(), and DD4hep::Geometry::GeoHandler::m_data.
GeoScan() [2/2]
GeoScan::GeoScan (DetElement e, bool propagateRegions)
Initializing constructor.
Definition at line 157 of file GeoHandler.cpp.
References DD4hep::Geometry::GeoHandler::collect(), DD4hep::Geometry::GeoHandler::m_data, DD4hep::Geometry::GeoHandler::release(), and DD4hep::Geometry::GeoHandler::setPropagateRegions().
~GeoScan()
GeoScan::~GeoScan () virtual
Default destructor.
Definition at line 164 of file GeoHandler.cpp.
References DD4hep::Geometry::GeoHandler::m_data.
Member Function Documentation
operator()()
GeoScan & GeoScan::operator() () virtual
Work callback.
Definition at line 171 of file GeoHandler.cpp.
Member Data Documentation
m_data
GeoHandler::Data* DD4hep::Geometry::GeoScan::m_data protected
Data holder.
Definition at line 146 of file GeoHandler.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/GeoHandler.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/GeoHandler.cpp