DD4hep: DD4hep::PluginService Class Reference
DD4hep::PluginService Class Reference
Factory template for the plugin mechanism.
#include <Plugins.h>
Classes
struct FuncPointer
Public Types
typedef void * stub_t
Static Public Member Functions
template<typename FUNCTION >
static FuncPointer< FUNCTION > function (FUNCTION func)
static bool debug ()
static bool setDebug (bool new_value)
static void * getCreator (const std::string &id, const std::type_info &info)
static void addFactory (const std::string &id, stub_t func, const std::type_info &signature_type, const std::type_info &return_type)
template<typename R , typename... Args>
static R Create (const std::string &id, Args... args)
Detailed Description
Factory template for the plugin mechanism.
Definition at line 88 of file Plugins.h.
Member Typedef Documentation
stub_t
typedef void* DD4hep::PluginService::stub_t
Definition at line 91 of file Plugins.h.
Member Function Documentation
addFactory()
void PluginService::addFactory (const std::string & id, stub_t func, const std::type_info & signature_type, const std::type_info & return_type) static
Definition at line 156 of file Plugins.cpp.
References DD4HEP_IMPLEMENT_PLUGIN_REGISTRY, debug(), DD4hep::INFO, and DD4hep::printout().
Create()
template<typename R , typename... Args> static R DD4hep::PluginService::Create (const std::string & id, Args... args) inline static
Definition at line 138 of file Plugins.h.
References DD4hep::PluginService::FuncPointer< FUNCTION >::fcn, DD4hep::PluginService::FuncPointer< FUNCTION >::fptr, and DD4hep::PluginService::FuncPointer< FUNCTION >::ptr.
debug()
bool PluginService::debug () static
Definition at line 32 of file Plugins.cpp.
Referenced by addFactory().
function()
template<typename FUNCTION > static FuncPointer<FUNCTION> DD4hep::PluginService::function (FUNCTION func) inline static
Definition at line 105 of file Plugins.h.
getCreator()
void * PluginService::getCreator (const std::string & id, const std::type_info & info) static
Definition at line 152 of file Plugins.cpp.
setDebug()
bool PluginService::setDebug (bool new_value) static
Definition at line 36 of file Plugins.cpp.
References DD4hep::PluginService::FuncPointer< FUNCTION >::fcn, DD4hep::PluginService::FuncPointer< FUNCTION >::fptr, handle(), and DD4hep::PluginService::FuncPointer< FUNCTION >::ptr.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Plugins.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Plugins.cpp