DD4hep: DD4hep::Conditions::ConditionsPool Class Reference
DD4hep::Conditions::ConditionsPool Class Reference abstract
DDCond: DD4hep Detector Conditions components, classes and functions
Class implementing the conditions collection for a given IOV type.
#include <ConditionsPool.h>
Public Types
enum { AGE_NONE = 0, AGE_ANY = 9999999, AGE_EXPIRED = 12345678 }
typedef Condition::key_type key_type
Forward definition of the key type.
Public Member Functions
ConditionsPool (ConditionsManager mgr)
Default constructor.
virtual ~ConditionsPool ()
Default destructor. Note: pool must be cleared by the subclass!
void print (const std::string &opt) const
Print pool basics.
virtual void clear ()=0
Full cleanup of all managed conditions.
virtual Condition exists (Condition::key_type key) const =0
Check if a condition exists in the pool.
virtual void select (Condition::key_type key, RangeConditions &result)=0
Select the conditions matching the DetElement and the conditions name.
virtual void select_all (RangeConditions &result)=0
Select all conditions contained.
virtual void select_all (ConditionsPool &selection_pool)=0
Select all conditions contained.
virtual void select_used (RangeConditions &result)=0
Select the conditons, used also by the DetElement of the condition.
virtual size_t count () const =0
Total entry count.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Attributes
const IOVType * iovType
IOV type of the conditions hosted by this pool.
IOV * iov
The IOV of the conditions hosted.
int age_value
Aging value.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Protected Member Functions
void onRegister (Condition condition)
Listener invocation when a condition is registered to the cache.
void onRemove (Condition condition)
Listener invocation when a condition is deregistered from the cache.
virtual void insert (Condition cond)=0
Register a new condition to this pool.
virtual void insert (RangeConditions &cond)=0
Register a new condition to this pool. May overload for performance reasons.
Protected Attributes
ConditionsManager m_manager
Handle to conditions manager object.
Friends
class ConditionsPoolInsert
class ConditionsPoolRemove
class ConditionsManagerObject
Detailed Description
Class implementing the conditions collection for a given IOV type.
Implementation is mostly virtual, to allow to switch between different implementations, which allow for different lookup and store optimizations and/or various caches. The interface only represents the basic functionality required.
For convenience, the class definition is here. See ConditionsManager.cpp for the implementation.
Author
M.Frank
Version
1.0
Definition at line 46 of file ConditionsPool.h.
Member Typedef Documentation
key_type
typedef Condition::key_type DD4hep::Conditions::ConditionsPool::key_type
Forward definition of the key type.
Definition at line 53 of file ConditionsPool.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
AGE_NONE
AGE_ANY
AGE_EXPIRED
Definition at line 55 of file ConditionsPool.h.
Constructor & Destructor Documentation
ConditionsPool()
ConditionsPool::ConditionsPool (ConditionsManager mgr)
Default constructor.
Definition at line 29 of file ConditionsPool.cpp.
References DD4hep::InstanceCount::increment().
~ConditionsPool()
ConditionsPool::~ConditionsPool () virtual
Default destructor. Note: pool must be cleared by the subclass!
Default destructor.
Definition at line 36 of file ConditionsPool.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
clear()
virtual void DD4hep::Conditions::ConditionsPool::clear () pure virtual
Full cleanup of all managed conditions.
Referenced by DD4hep::Conditions::ConditionsManager::clear(), and DD4hep::Conditions::UserPool::validityPtr().
count()
virtual size_t DD4hep::Conditions::ConditionsPool::count () const pure virtual
Total entry count.
Referenced by DD4hep::Conditions::ConditionsIOVPool::clean(), print(), and DD4hep::Conditions::UserPool::validityPtr().
exists()
virtual Condition DD4hep::Conditions::ConditionsPool::exists (Condition::key_type key) const pure virtual
Check if a condition exists in the pool.
Referenced by DD4hep::Conditions::UserPool::validityPtr().
insert() [1/2]
virtual void DD4hep::Conditions::ConditionsPool::insert (Condition cond) protected pure virtual
Register a new condition to this pool.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), DD4hep::Conditions::ConditionsIOVPool::clean(), DD4hep::Conditions::ConditionsPoolInsert::operator()(), DD4hep::Conditions::ConditionsManagerObject::registerCondition(), DD4hep::Conditions::ConditionsManagerObject::registerUnlocked(), and DD4hep::Conditions::UserPool::validityPtr().
insert() [2/2]
virtual void DD4hep::Conditions::ConditionsPool::insert (RangeConditions & cond) protected pure virtual
Register a new condition to this pool. May overload for performance reasons.
onRegister()
void ConditionsPool::onRegister (Condition condition) protected
Listener invocation when a condition is registered to the cache.
Definition at line 48 of file ConditionsPool.cpp.
References m_manager, DD4hep::Conditions::ConditionsManagerObject::onRegister(), and DD4hep::Handle< T >::ptr().
onRemove()
void ConditionsPool::onRemove (Condition condition) protected
Listener invocation when a condition is deregistered from the cache.
Definition at line 53 of file ConditionsPool.cpp.
References m_manager, DD4hep::Conditions::ConditionsManagerObject::onRemove(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Conditions::ConditionsPoolRemove::operator()().
print()
void ConditionsPool::print (const std::string & opt) const
Print pool basics.
Definition at line 42 of file ConditionsPool.cpp.
References age_value, count(), DD4hep::INFO, iov, DD4hep::printout(), and DD4hep::IOV::str().
Referenced by DD4hep::Conditions::ConditionsIOVPool::clean(), and DD4hep::Conditions::UserPool::validityPtr().
select()
virtual void DD4hep::Conditions::ConditionsPool::select (Condition::key_type key, RangeConditions & result) pure virtual
Select the conditions matching the DetElement and the conditions name.
select_all() [1/2]
virtual void DD4hep::Conditions::ConditionsPool::select_all (RangeConditions & result) pure virtual
Select all conditions contained.
Referenced by DD4hep::Conditions::Operators::collectAllConditions(), DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), DD4hep::Conditions::ConditionsTextRepository::save(), and DD4hep::Conditions::ConditionsRepository::save().
select_all() [2/2]
virtual void DD4hep::Conditions::ConditionsPool::select_all (ConditionsPool & selection_pool) pure virtual
Select all conditions contained.
select_used()
virtual void DD4hep::Conditions::ConditionsPool::select_used (RangeConditions & result) pure virtual
Select the conditons, used also by the DetElement of the condition.
Referenced by DD4hep::Conditions::ConditionsIOVPool::select().
Friends And Related Function Documentation
ConditionsManagerObject
friend class ConditionsManagerObject friend
Definition at line 69 of file ConditionsPool.h.
ConditionsPoolInsert
friend class ConditionsPoolInsert friend
Definition at line 67 of file ConditionsPool.h.
ConditionsPoolRemove
friend class ConditionsPoolRemove friend
Definition at line 68 of file ConditionsPool.h.
Member Data Documentation
age_value
int DD4hep::Conditions::ConditionsPool::age_value
Aging value.
Definition at line 64 of file ConditionsPool.h.
Referenced by DD4hep::Conditions::ConditionsIOVPool::clean(), DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), print(), and DD4hep::Conditions::ConditionsIOVPool::select().
iov
IOV* DD4hep::Conditions::ConditionsPool::iov
The IOV of the conditions hosted.
Definition at line 62 of file ConditionsPool.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__queue_update(), DD4hep::Conditions::ConditionsIOVPool::clean(), DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), print(), DD4hep::Conditions::ConditionsManagerObject::registerIOV(), and DD4hep::Conditions::ConditionsManagerObject::registerUnlocked().
iovType
const IOVType* DD4hep::Conditions::ConditionsPool::iovType
IOV type of the conditions hosted by this pool.
Definition at line 60 of file ConditionsPool.h.
m_manager
ConditionsManager DD4hep::Conditions::ConditionsPool::m_manager protected
Handle to conditions manager object.
Definition at line 49 of file ConditionsPool.h.
Referenced by onRegister(), and onRemove().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsPool.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsPool.cpp