DD4hep: DDSurfaces::ISurface Class Reference
DDSurfaces::ISurface Class Reference abstract
#include <ISurface.h>
Public Member Functions
virtual ~ISurface ()
Destructor.
virtual const SurfaceType & type () const =0
properties of the surface encoded in Type.
virtual long64 id () const =0
The id of this surface - corresponds to DetElement id (or'ed with the placement ids)
virtual bool insideBounds (const Vector3D &point, double epsilon=1.e-4) const =0
Checks if the given point lies within the surface.
virtual Vector3D u (const Vector3D &point=Vector3D()) const =0
virtual Vector3D v (const Vector3D &point=Vector3D()) const =0
virtual Vector3D normal (const Vector3D &point=Vector3D()) const =0
Access to the normal direction at the given point.
virtual Vector2D globalToLocal (const Vector3D &point) const =0
virtual Vector3D localToGlobal (const Vector2D &point) const =0
virtual const Vector3D & origin () const =0
virtual const IMaterial & innerMaterial () const =0
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const =0
Access to the material in direction of the normal.
virtual double innerThickness () const =0
virtual double outerThickness () const =0
virtual double distance (const Vector3D &point) const =0
virtual double length_along_u () const =0
virtual double length_along_v () const =0
Detailed Description
Interface for tracking surfaces. The surface provides access to vectors for u,v,n and the orgigin and the inner and outer materials with corresponding thicknesses.
Author
C.Grefe, CERN, F. Gaede, DESY
Version
$Id$
Date
Mar 7 2014
Definition at line 27 of file ISurface.h.
Constructor & Destructor Documentation
~ISurface()
virtual DDSurfaces::ISurface::~ISurface () inline virtual
Destructor.
Definition at line 31 of file ISurface.h.
References distance(), e, globalToLocal(), id(), innerMaterial(), innerThickness(), insideBounds(), length_along_u(), length_along_v(), localToGlobal(), normal(), origin(), outerMaterial(), outerThickness(), type(), u(), and v().
Member Function Documentation
distance()
virtual double DDSurfaces::ISurface::distance (const Vector3D & point) const pure virtual
Distance to surface
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolConeImpl, DD4hep::DDRec::VolCylinderImpl, DD4hep::DDRec::VolPlaneImpl, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by ~ISurface().
globalToLocal()
virtual Vector2D DDSurfaces::ISurface::globalToLocal (const Vector3D & point) const pure virtual
Convert the global position to the local position (u,v) on the surface
Implemented in DD4hep::DDRec::CylinderSurface, DD4hep::DDRec::Surface, DD4hep::DDRec::VolConeImpl, DD4hep::DDRec::VolCylinderImpl, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by ~ISurface().
id()
virtual long64 DDSurfaces::ISurface::id () const pure virtual
The id of this surface - corresponds to DetElement id (or'ed with the placement ids)
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DD4hep::DDRec::SurfaceManager::initialize(), DDSurfaces::operator<<(), and ~ISurface().
innerMaterial()
virtual const IMaterial& DDSurfaces::ISurface::innerMaterial () const pure virtual
Access to the material in opposite direction of the normal.
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
innerThickness()
virtual double DDSurfaces::ISurface::innerThickness () const pure virtual
Thickness of inner material
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
insideBounds()
virtual bool DDSurfaces::ISurface::insideBounds (const Vector3D & point, double epsilon = 1.e-4) const pure virtual
Checks if the given point lies within the surface.
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by ~ISurface().
length_along_u()
virtual double DDSurfaces::ISurface::length_along_u () const pure virtual
The length of the surface along direction u at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by ~ISurface().
length_along_v()
virtual double DDSurfaces::ISurface::length_along_v () const pure virtual
The length of the surface along direction v at the origin. For 'regular' boundaries, like rectangles, this can be used to speed up the computation of inSideBounds.
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by ~ISurface().
localToGlobal()
virtual Vector3D DDSurfaces::ISurface::localToGlobal (const Vector2D & point) const pure virtual
Convert the local position (u,v) on the surface to the global position
Implemented in DD4hep::DDRec::CylinderSurface, DD4hep::DDRec::Surface, DD4hep::DDRec::VolConeImpl, DD4hep::DDRec::VolCylinderImpl, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by ~ISurface().
normal()
virtual Vector3D DDSurfaces::ISurface::normal (const Vector3D & point = Vector3D()) const pure virtual
Access to the normal direction at the given point.
Implemented in DD4hep::DDRec::CylinderSurface, DD4hep::DDRec::Surface, DD4hep::DDRec::VolConeImpl, DD4hep::DDRec::VolCylinderImpl, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::SurfaceType::checkOrthogonalToZ(), DDSurfaces::SurfaceType::checkParallelToZ(), DDSurfaces::operator<<(), and ~ISurface().
origin()
virtual const Vector3D& DDSurfaces::ISurface::origin () const pure virtual
Get Origin of local coordinate system on surface
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
outerMaterial()
virtual const IMaterial& DDSurfaces::ISurface::outerMaterial () const pure virtual
Access to the material in direction of the normal.
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
outerThickness()
virtual double DDSurfaces::ISurface::outerThickness () const pure virtual
Thickness of outer material
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
type()
virtual const SurfaceType& DDSurfaces::ISurface::type () const pure virtual
properties of the surface encoded in Type.
Implemented in DD4hep::DDRec::Surface, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
u()
virtual Vector3D DDSurfaces::ISurface::u (const Vector3D & point = Vector3D()) const pure virtual
First direction of measurement U
Implemented in DD4hep::DDRec::CylinderSurface, DD4hep::DDRec::Surface, DD4hep::DDRec::VolConeImpl, DD4hep::DDRec::VolCylinderImpl, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
v()
virtual Vector3D DDSurfaces::ISurface::v (const Vector3D & point = Vector3D()) const pure virtual
Second direction of measurement V
Implemented in DD4hep::DDRec::CylinderSurface, DD4hep::DDRec::Surface, DD4hep::DDRec::VolConeImpl, DD4hep::DDRec::VolSurface, and DD4hep::DDRec::VolSurfaceBase.
Referenced by DDSurfaces::operator<<(), and ~ISurface().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSurfaces/include/DDSurfaces/ISurface.h