DD4hep: DD4hep::DDSegmentation::BitFieldValue Class Reference
DD4hep::DDSegmentation::BitFieldValue Class Reference
#include <BitField64.h>
Public Member Functions
virtual ~BitFieldValue ()
BitFieldValue (long64 &bitfield, const std::string &name, unsigned offset, int signedWidth)
long64 value () const
long64 value (long64 id) const
Calculate Field value given an external 64 bit bitmap value.
BitFieldValue & operator= (long64 in)
operator long64 () const
const std::string & name () const
unsigned offset () const
unsigned width () const
bool isSigned () const
ulong64 mask () const
Protected Attributes
long64 & _b
ulong64 _mask
std::string _name
unsigned _offset
unsigned _width
int _minVal
int _maxVal
bool _isSigned
Detailed Description
Helper class for BitField64 that corresponds to one field value.
Author
F.Gaede, DESY
Date
2013-06
Definition at line 225 of file BitField64.h.
Constructor & Destructor Documentation
~BitFieldValue()
virtual DD4hep::DDSegmentation::BitFieldValue::~BitFieldValue () inline virtual
Definition at line 228 of file BitField64.h.
BitFieldValue()
DD4hep::DDSegmentation::BitFieldValue::BitFieldValue (long64 & bitfield, const std::string & name, unsigned offset, int signedWidth)
The default c'tor.
Parameters
bitfield reference to the 64bit bitfield
name name of the field
offset offset of field
signedWidth width of field, negative if field is signed
Definition at line 11 of file BitField64.cpp.
References _isSigned, _mask, _maxVal, _minVal, _name, _offset, _width, and s.
Referenced by DD4hep::DDSegmentation::BitField64::addField().
Member Function Documentation
isSigned()
bool DD4hep::DDSegmentation::BitFieldValue::isSigned () const inline
True if field is interpreted as signed
Definition at line 272 of file BitField64.h.
Referenced by DD4hep::DDSegmentation::BitField64::fieldDescription().
mask()
ulong64 DD4hep::DDSegmentation::BitFieldValue::mask () const inline
The field's mask
Definition at line 275 of file BitField64.h.
Referenced by DD4hep::DDSegmentation::BitField64::addField(), and DD4hep::Geometry::IDDescriptor::encode().
name()
const std::string& DD4hep::DDSegmentation::BitFieldValue::name () const inline
fg: removed because it causes ambiguities with operator long64(). Conversion operator for int - allows to write:
int index = myBitFieldValue ;The field's name
Definition at line 263 of file BitField64.h.
Referenced by DD4hep::DDSegmentation::BitField64::addField(), and DD4hep::DDSegmentation::BitField64::init().
offset()
unsigned DD4hep::DDSegmentation::BitFieldValue::offset () const inline
The field's offset
Definition at line 266 of file BitField64.h.
Referenced by DD4hep::Geometry::IDDescriptor::encode(), DD4hep::DDSegmentation::BitField64::highestBit(), DD4hep::DDSegmentation::BitField64::init(), DD4hep::Geometry::VolumeManager::subdetector(), and DD4hep::Geometry::DetectorTools::toString().
operator long64()
DD4hep::DDSegmentation::BitFieldValue::operator long64 () const inline
Conversion operator for long64 - allows to write:
long64 index = myBitFieldValue ;
Definition at line 254 of file BitField64.h.
operator=()
BitFieldValue & DD4hep::DDSegmentation::BitFieldValue::operator= (long64 in)
Assignment operator for user convenience
Definition at line 94 of file BitField64.cpp.
References _b, _mask, _maxVal, _name, _offset, _width, and s.
value() [1/2]
long64 DD4hep::DDSegmentation::BitFieldValue::value () const
Returns the current field value
Definition at line 56 of file BitField64.cpp.
References _b, _isSigned, _mask, _offset, and _width.
Referenced by DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::DDRec::IDDecoder::barrelEndcapFlag(), DD4hep::Geometry::IDDescriptor::encode(), DD4hep::DDRec::IDDecoder::layerIndex(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::operator()(), DD4hep::Geometry::VolumeManager::subdetector(), DD4hep::DDSegmentation::MultiSegmentation::subsegmentation(), DD4hep::DDRec::IDDecoder::systemIndex(), and DD4hep::Geometry::DetectorTools::toString().
value() [2/2]
long64 DD4hep::DDSegmentation::BitFieldValue::value (long64 id) const
Calculate Field value given an external 64 bit bitmap value.
Definition at line 75 of file BitField64.cpp.
References _isSigned, _mask, _offset, and _width.
width()
unsigned DD4hep::DDSegmentation::BitFieldValue::width () const inline
The field's width
Definition at line 269 of file BitField64.h.
Referenced by DD4hep::DDSegmentation::BitField64::highestBit(), DD4hep::DDSegmentation::BitField64::init(), and DD4hep::Geometry::DetectorTools::toString().
Member Data Documentation
_b
long64& DD4hep::DDSegmentation::BitFieldValue::_b protected
Definition at line 280 of file BitField64.h.
Referenced by operator=(), and value().
_isSigned
bool DD4hep::DDSegmentation::BitFieldValue::_isSigned protected
Definition at line 287 of file BitField64.h.
Referenced by BitFieldValue(), and value().
_mask
ulong64 DD4hep::DDSegmentation::BitFieldValue::_mask protected
Definition at line 281 of file BitField64.h.
Referenced by BitFieldValue(), operator=(), and value().
_maxVal
int DD4hep::DDSegmentation::BitFieldValue::_maxVal protected
Definition at line 286 of file BitField64.h.
Referenced by BitFieldValue(), and operator=().
_minVal
int DD4hep::DDSegmentation::BitFieldValue::_minVal protected
Definition at line 285 of file BitField64.h.
Referenced by BitFieldValue().
_name
std::string DD4hep::DDSegmentation::BitFieldValue::_name protected
Definition at line 282 of file BitField64.h.
Referenced by BitFieldValue(), and operator=().
_offset
unsigned DD4hep::DDSegmentation::BitFieldValue::_offset protected
Definition at line 283 of file BitField64.h.
Referenced by BitFieldValue(), operator=(), and value().
_width
unsigned DD4hep::DDSegmentation::BitFieldValue::_width protected
Definition at line 284 of file BitField64.h.
Referenced by BitFieldValue(), operator=(), and value().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/include/DDSegmentation/BitField64.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDSegmentation/src/BitField64.cpp