DD4hep: DD4hep::Alignments::AlignmentCondition Class Reference
DD4hep::Alignments::AlignmentCondition Class Reference
DD4hep::Geometry components, classes and objects | DDAlign: DD4hep Detector geometry alignment components.
Main handle class to hold an alignment conditions object.
#include <Alignments.h>
Public Types
typedef Interna::AlignmentConditionObject Object
Forward definition of the base data object containing alignment data.
typedef AlignmentData Data
Forward definition of the base data object containing alignment data.
typedef Geometry::PlacedVolume PlacedVolume
Forward definition of the geometry placement.
typedef std::vector< PlacedVolume > NodeList
Forward definition of the nodelist leading to the world.
typedef Alignments::Delta Delta
Forward definition of the alignment delta data.
typedef unsigned int key_type
Forward definition of the key type.
typedef IOV iov_type
Forward definition of the iov type.
Public Types inherited from DD4hep::Handle< Interna::AlignmentConditionObject >
typedef Interna::AlignmentConditionObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
AlignmentCondition ()
Default constructor.
AlignmentCondition (Object *p)
Default constructor.
AlignmentCondition (Conditions::Interna::ConditionObject *p)
Assignment constructor from condition object.
template<typename Q >
AlignmentCondition (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
AlignmentCondition (const std::string &name)
Object constructor for pure alignment objects.
const IOVType & iovType () const
Access the IOV type.
const iov_type & iov () const
Access the IOV block.
Data & data ()
Data accessor for the use of decorators.
const Data & data () const
Data accessor for the use of decorators.
const TGeoHMatrix & worldTransformation () const
Create cached matrix to transform to world coordinates.
const TGeoHMatrix & detectorTransformation () const
Access the alignment/placement matrix with respect to the world.
bool is_bound () const
Check if object is already bound....
Public Member Functions inherited from DD4hep::Handle< Interna::AlignmentConditionObject >
Handle ()
Defaulot constructor.
Handle (Interna::AlignmentConditionObject *e)
Initializing constructor from pointer.
Handle (const Handle< Interna::AlignmentConditionObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< Interna::AlignmentConditionObject > & operator= (const Handle< Interna::AlignmentConditionObject > &e)=default
Assignment operator.
bool operator== (const Handle< Interna::AlignmentConditionObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< Interna::AlignmentConditionObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< Interna::AlignmentConditionObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< Interna::AlignmentConditionObject > & clear ()
Release the object held by the handle.
Interna::AlignmentConditionObject * operator-> () const
Access the held object using the -> operator.
operator Interna::AlignmentConditionObject & () const
Automatic type conversion to an object references.
Interna::AlignmentConditionObject & operator* () const
Access the held object using the * operator.
Interna::AlignmentConditionObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
Interna::AlignmentConditionObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< Interna::AlignmentConditionObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< Interna::AlignmentConditionObject >
Interna::AlignmentConditionObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Main handle class to hold an alignment conditions object.
Author
M.Frank
Version
1.0
Definition at line 123 of file Alignments.h.
Member Typedef Documentation
Data
typedef AlignmentData DD4hep::Alignments::AlignmentCondition::Data
Forward definition of the base data object containing alignment data.
Definition at line 128 of file Alignments.h.
Delta
typedef Alignments::Delta DD4hep::Alignments::AlignmentCondition::Delta
Forward definition of the alignment delta data.
Definition at line 134 of file Alignments.h.
iov_type
typedef IOV DD4hep::Alignments::AlignmentCondition::iov_type
Forward definition of the iov type.
Definition at line 138 of file Alignments.h.
key_type
typedef unsigned int DD4hep::Alignments::AlignmentCondition::key_type
Forward definition of the key type.
Definition at line 136 of file Alignments.h.
NodeList
typedef std::vector<PlacedVolume> DD4hep::Alignments::AlignmentCondition::NodeList
Forward definition of the nodelist leading to the world.
Definition at line 132 of file Alignments.h.
Object
typedef Interna::AlignmentConditionObject DD4hep::Alignments::AlignmentCondition::Object
Forward definition of the base data object containing alignment data.
Definition at line 126 of file Alignments.h.
PlacedVolume
typedef Geometry::PlacedVolume DD4hep::Alignments::AlignmentCondition::PlacedVolume
Forward definition of the geometry placement.
Definition at line 130 of file Alignments.h.
Constructor & Destructor Documentation
AlignmentCondition() [1/5]
DD4hep::Alignments::AlignmentCondition::AlignmentCondition () inline
Default constructor.
Definition at line 142 of file Alignments.h.
AlignmentCondition() [2/5]
DD4hep::Alignments::AlignmentCondition::AlignmentCondition (Object * p) inline
Default constructor.
Definition at line 144 of file Alignments.h.
AlignmentCondition() [3/5]
DD4hep::Alignments::AlignmentCondition::AlignmentCondition (Conditions::Interna::ConditionObject * p) inline
Assignment constructor from condition object.
Definition at line 146 of file Alignments.h.
AlignmentCondition() [4/5]
template<typename Q > DD4hep::Alignments::AlignmentCondition::AlignmentCondition (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 148 of file Alignments.h.
AlignmentCondition() [5/5]
DD4hep::Alignments::AlignmentCondition::AlignmentCondition (const std::string & name)
Object constructor for pure alignment objects.
Initializing constructor to create a new object (Specialized for AlignmentConditionObject)
Definition at line 48 of file Alignments.cpp.
Member Function Documentation
data() [1/2]
AlignmentCondition::Data & AlignmentCondition::data ()
Data accessor for the use of decorators.
Data block (bound type)
Definition at line 82 of file Alignments.cpp.
References DD4hep::Alignments::Interna::AlignmentConditionObject::alignment_data, DD4hep::Conditions::Condition::bind(), DD4hep::Alignments::AlignmentData::condition, DD4hep::Conditions::Condition::get(), and DD4hep::Conditions::Condition::is_bound().
Referenced by DD4hep::Alignments::Interna::AlignmentConditionObject::clear(), DD4hep::Alignments::AlignmentsManagerObject::compute(), computeDelta(), DD4hep::Conditions::AlignmentsLoaderImp::get(), DD4hep::Alignments::AlignmentUpdateCall::handle(), and DD4hep::Alignments::AlignmentsManagerObject::to_world().
data() [2/2]
const AlignmentCondition::Data & AlignmentCondition::data () const
Data accessor for the use of decorators.
Definition at line 93 of file Alignments.cpp.
References DD4hep::Alignments::Interna::AlignmentConditionObject::alignment_data, DD4hep::Conditions::Condition::bind(), DD4hep::Alignments::AlignmentData::condition, DD4hep::Conditions::Condition::get(), and DD4hep::Conditions::Condition::is_bound().
detectorTransformation()
const TGeoHMatrix & AlignmentCondition::detectorTransformation () const
Access the alignment/placement matrix with respect to the world.
Definition at line 114 of file Alignments.cpp.
iov()
const DD4hep::IOV & AlignmentCondition::iov () const
Access the IOV block.
Definition at line 77 of file Alignments.cpp.
Referenced by DD4hep::Alignments::AlignmentsManagerObject::compute().
iovType()
const DD4hep::IOVType & AlignmentCondition::iovType () const
Access the IOV type.
Interval of validity
Definition at line 72 of file Alignments.cpp.
is_bound()
bool AlignmentCondition::is_bound () const
Check if object is already bound....
Definition at line 104 of file Alignments.cpp.
References DD4hep::Conditions::Condition::data(), and DD4hep::OpaqueData::is_bound().
worldTransformation()
const TGeoHMatrix & AlignmentCondition::worldTransformation () const
Create cached matrix to transform to world coordinates.
Definition at line 109 of file Alignments.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Alignments.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Alignments.cpp