DD4hep: DD4hep::DDRec::VolCylinderImpl Class Reference
DD4hep::DDRec::VolCylinderImpl Class Reference
#include <Surface.h>
Public Member Functions
VolCylinderImpl ()
default c'tor
VolCylinderImpl (Geometry::Volume vol, SurfaceType type, double thickness_inner, double thickness_outer, Vector3D origin)
virtual Vector3D u (const Vector3D &point=Vector3D()) const
virtual Vector3D normal (const Vector3D &point=Vector3D()) const
virtual double distance (const Vector3D &point) const
virtual Vector2D globalToLocal (const Vector3D &point) const
virtual Vector3D localToGlobal (const Vector2D &point) const
Public Member Functions inherited from DD4hep::DDRec::VolSurfaceBase
virtual ~VolSurfaceBase ()
VolSurfaceBase ()
default c'tor
VolSurfaceBase (SurfaceType typ, double thickness_inner, double thickness_outer, Vector3D u_val, Vector3D v_val, Vector3D n, Vector3D o, Geometry::Volume vol, int identifier)
VolSurfaceBase (const VolSurfaceBase &c)
Copy the from object.
Geometry::Volume volume () const
the volume to which this surface is attached.
virtual long64 id () const
The id of this surface.
virtual const SurfaceType & type () const
virtual Vector3D v (const Vector3D &point=Vector3D()) const
virtual const Vector3D & origin () const
virtual const IMaterial & innerMaterial () const
Access to the material in opposite direction of the normal.
virtual const IMaterial & outerMaterial () const
Access to the material in direction of the normal.
virtual double innerThickness () const
virtual double outerThickness () const
virtual double length_along_u () const
virtual double length_along_v () const
virtual bool insideBounds (const Vector3D &point, double epsilon=1e-4) const
Checks if the given point lies within the surface.
virtual std::vector< std::pair< Vector3D, Vector3D > > getLines (unsigned nMax=100)
void setInnerMaterial (const IMaterial &mat)
set the inner Material
void setOuterMaterial (const IMaterial &mat)
set the outer Materal
Public Member Functions inherited from DDSurfaces::ISurface
virtual ~ISurface ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDRec::VolSurfaceBase
virtual void setU (const Vector3D &u)
setter for daughter classes
virtual void setV (const Vector3D &v)
setter for daughter classes
virtual void setNormal (const Vector3D &n)
setter for daughter classes
virtual void setOrigin (const Vector3D &o)
setter for daughter classes
Protected Attributes inherited from DD4hep::DDRec::VolSurfaceBase
SurfaceType _type
Vector3D _u
Vector3D _v
Vector3D _n
Vector3D _o
double _th_i
double _th_o
MaterialData _innerMat
MaterialData _outerMat
Geometry::Volume _vol
long64 _id
unsigned _refCount
Detailed Description
Implementation of cylindrical surface attached to a volume
Author
F.Gaede, DESY
Date
Apr, 6 2014
Version
$Id$
Definition at line 374 of file Surface.h.
Constructor & Destructor Documentation
VolCylinderImpl() [1/2]
DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl () inline
default c'tor
Definition at line 379 of file Surface.h.
VolCylinderImpl() [2/2]
DD4hep::DDRec::VolCylinderImpl::VolCylinderImpl (Geometry::Volume vol, SurfaceType type, double thickness_inner, double thickness_outer, Vector3D origin)
The standard constructor. The origin vector points to the origin of the coordinate system on the cylinder, its rho defining the radius of the cylinder. The measurement direction v is set to be (0,0,1), the normal is chosen to be parallel to the origin vector and u = n X v.
Definition at line 257 of file Surface.cpp.
References DD4hep::DDRec::VolSurfaceBase::_type, DDSurfaces::SurfaceType::checkOrthogonalToZ(), DDSurfaces::SurfaceType::checkParallelToZ(), DDSurfaces::SurfaceType::Cone, DDSurfaces::Vector3D::cross(), DDSurfaces::SurfaceType::Cylinder, DDSurfaces::SurfaceType::Plane, DD4hep::DDRec::VolSurfaceBase::setNormal(), DDSurfaces::SurfaceType::setProperty(), DD4hep::DDRec::VolSurfaceBase::setU(), DD4hep::DDRec::VolSurfaceBase::setV(), DDSurfaces::Vector3D::unit(), DDSurfaces::Vector3D::x(), and DDSurfaces::Vector3D::y().
Member Function Documentation
distance()
double DD4hep::DDRec::VolCylinderImpl::distance (const Vector3D & point) const virtual
Distance to surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 315 of file Surface.cpp.
References DD4hep::DDRec::VolSurfaceBase::origin(), and DDSurfaces::Vector3D::rho().
globalToLocal()
Vector2D DD4hep::DDRec::VolCylinderImpl::globalToLocal (const Vector3D & point) const virtual
Convert the global position to the local position (u,v) on the surface - v runs along the axis of the cylinder, u is r*phi
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 290 of file Surface.cpp.
References M_PI, DD4hep::DDRec::VolSurfaceBase::origin(), DDSurfaces::Vector3D::phi(), and DDSurfaces::Vector3D::z().
localToGlobal()
Vector3D DD4hep::DDRec::VolCylinderImpl::localToGlobal (const Vector2D & point) const virtual
Convert the local position (u,v) on the surface to the global position - v runs along the axis of the cylinder, u is r*phi
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 302 of file Surface.cpp.
References DDSurfaces::Vector3D::cylindrical(), M_PI, DD4hep::DDRec::VolSurfaceBase::origin(), DDSurfaces::Vector3D::phi(), DDSurfaces::Vector3D::rho(), DDSurfaces::Vector2D::u(), DDSurfaces::Vector2D::v(), and DDSurfaces::Vector3D::z().
normal()
Vector3D DD4hep::DDRec::VolCylinderImpl::normal (const Vector3D & point = Vector3D()) const virtual
The normal direction at the given point, projected onto the cylinder. No check is done whether the point actually is on the cylinder surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 284 of file Surface.cpp.
References DDSurfaces::Vector3D::cylindrical(), and DDSurfaces::Vector3D::phi().
u()
Vector3D DD4hep::DDRec::VolCylinderImpl::u (const Vector3D & point = Vector3D()) const virtual
First direction of measurement U - rotated to point projected onto the cylinder. No check is done whether the point actually is on the cylinder surface
Reimplemented from DD4hep::DDRec::VolSurfaceBase.
Definition at line 277 of file Surface.cpp.
References DDSurfaces::Vector3D::cross(), DDSurfaces::Vector3D::cylindrical(), DDSurfaces::Vector3D::phi(), and DD4hep::DDRec::VolSurfaceBase::v().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/include/DDRec/Surface.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDRec/src/Surface.cpp