DD4hep: DD4hep::Simulation::Geant4PhysicsListActionSequence Class Reference
DD4hep::Simulation::Geant4PhysicsListActionSequence Class Reference
DD4hep::Simulation components, classes and objects
The implementation of the single Geant4 physics list action sequence.
#include <Geant4PhysicsList.h>
Public Member Functions
Geant4PhysicsListActionSequence (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4PhysicsListActionSequence ()
Default destructor.
void dump ()
Dump content to stdout.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
void setTransportation (bool value)
Update transportation flag.
bool transportation () const
Access the transportation flag.
template<typename Q , typename T >
void constructPhysics (Q *p, void(T::*f)(G4VModularPhysicsList *))
Register physics construction callback.
template<typename Q , typename T >
void constructProcess (Q *p, void(T::*f)(G4VUserPhysicsList *))
Register process construction callback.
template<typename Q , typename T >
void constructParticle (Q *p, void(T::*f)(G4VUserPhysicsList *))
Register particle construction callback.
void adopt (Geant4PhysicsList *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void constructProcesses (G4VUserPhysicsList *physics)
Execute sequence of G4 physics constructors.
virtual void constructParticles (G4VUserPhysicsList *physics)
Execute sequence of G4 particle constructors.
virtual void constructPhysics (G4VModularPhysicsList *physics)
Execute sequence of G4 physics constructors.
G4VUserPhysicsList * extensionList ()
Extend physics list from factory:
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Public Attributes
bool m_transportation
Flag if particle transportation is to be added.
bool m_decays
Flag if particle decays are to be added.
std::string m_extends
Property: Store name of basic predefined Geant4 physics list.
double m_rangecut
global range cut for secondary productions
Protected Member Functions
virtual void constructDecays (G4VUserPhysicsList *physics)
Callback to construct particle decays.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes
CallbackSequence m_physics
Callback sequence for G4 physics constructors.
CallbackSequence m_process
Callback sequence for G4 process constructors.
CallbackSequence m_particle
Callback sequence for G4 particle constructors.
Actors< Geant4PhysicsList > m_actors
The list of action objects to be called.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Detailed Description
The implementation of the single Geant4 physics list action sequence.
Concrete implementation of the Geant4 physics list sequence. A list to setup the physics content in a modular form
Author
M.Frank
Version
1.0
Definition at line 188 of file Geant4PhysicsList.h.
Constructor & Destructor Documentation
Geant4PhysicsListActionSequence()
Geant4PhysicsListActionSequence::Geant4PhysicsListActionSequence (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 282 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_decays, m_extends, DD4hep::Simulation::Geant4Action::m_needsControl, m_rangecut, and m_transportation.
~Geant4PhysicsListActionSequence()
Geant4PhysicsListActionSequence::~Geant4PhysicsListActionSequence () virtual
Default destructor.
Definition at line 293 of file Geant4PhysicsList.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_process, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
adopt()
void Geant4PhysicsListActionSequence::adopt (Geant4PhysicsList * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 331 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), DD4hep::Simulation::Geant4Action::except(), and m_actors.
Referenced by DD4hep::Converter< T, ARG >::operator()().
constructDecays()
void Geant4PhysicsListActionSequence::constructDecays (G4VUserPhysicsList * physics) protected virtual
Callback to construct particle decays.
Definition at line 362 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4Action::info().
Referenced by constructProcesses().
constructParticle()
template<typename Q , typename T > void DD4hep::Simulation::Geant4PhysicsListActionSequence::constructParticle (Q * p, void(T::*)(G4VUserPhysicsList *) f) inline
Register particle construction callback.
Definition at line 242 of file Geant4PhysicsList.h.
References DD4hep::CallbackSequence::add(), DD4hep::Simulation::Geant4PhysicsList::constructParticles(), DD4hep::Simulation::Geant4PhysicsList::constructPhysics(), DD4hep::Simulation::Geant4PhysicsList::constructProcesses(), and DD4hep::Simulation::Geant4PhysicsList::physics().
constructParticles()
void Geant4PhysicsListActionSequence::constructParticles (G4VUserPhysicsList * physics) virtual
Execute sequence of G4 particle constructors.
Callback to construct particles.
Definition at line 341 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4PhysicsList::constructParticles(), m_actors, and m_particle.
constructPhysics() [1/2]
template<typename Q , typename T > void DD4hep::Simulation::Geant4PhysicsListActionSequence::constructPhysics (Q * p, void(T::*)(G4VModularPhysicsList *) f) inline
Register physics construction callback.
Definition at line 232 of file Geant4PhysicsList.h.
References DD4hep::CallbackSequence::add().
Referenced by extensionList().
constructPhysics() [2/2]
void Geant4PhysicsListActionSequence::constructPhysics (G4VModularPhysicsList * physics) virtual
Execute sequence of G4 physics constructors.
Callback to execute physics constructors.
Definition at line 347 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4PhysicsList::constructPhysics(), m_actors, and m_physics.
constructProcess()
template<typename Q , typename T > void DD4hep::Simulation::Geant4PhysicsListActionSequence::constructProcess (Q * p, void(T::*)(G4VUserPhysicsList *) f) inline
Register process construction callback.
Definition at line 237 of file Geant4PhysicsList.h.
References DD4hep::CallbackSequence::add().
constructProcesses()
void Geant4PhysicsListActionSequence::constructProcesses (G4VUserPhysicsList * physics) virtual
Execute sequence of G4 physics constructors.
constructProcess callback
Definition at line 353 of file Geant4PhysicsList.cpp.
References constructDecays(), DD4hep::Simulation::Geant4PhysicsList::constructProcesses(), m_actors, m_decays, and m_process.
dump()
void Geant4PhysicsListActionSequence::dump ()
Dump content to stdout.
Definition at line 321 of file Geant4PhysicsList.cpp.
References DD4hep::ALWAYS, DD4hep::Simulation::Geant4PhysicsList::dump(), m_actors, m_decays, m_extends, m_rangecut, m_transportation, DD4hep::Simulation::Geant4Action::name(), and DD4hep::printout().
Referenced by installCommandMessenger().
extensionList()
G4VUserPhysicsList * Geant4PhysicsListActionSequence::extensionList ()
Extend physics list from factory:
Definition at line 301 of file Geant4PhysicsList.cpp.
References constructPhysics(), and m_extends.
Referenced by DD4hep::Simulation::Geant4Exec::configure().
installCommandMessenger()
void Geant4PhysicsListActionSequence::installCommandMessenger () virtual
Install command control messenger if wanted.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 316 of file Geant4PhysicsList.cpp.
References DD4hep::Simulation::Geant4UIMessenger::addCall(), DD4hep::Simulation::Geant4Action::control(), dump(), and DD4hep::Simulation::Geant4Action::name().
setTransportation()
void DD4hep::Simulation::Geant4PhysicsListActionSequence::setTransportation (bool value) inline
Update transportation flag.
Definition at line 223 of file Geant4PhysicsList.h.
transportation()
bool DD4hep::Simulation::Geant4PhysicsListActionSequence::transportation () const inline
Access the transportation flag.
Definition at line 227 of file Geant4PhysicsList.h.
Member Data Documentation
m_actors
Actors<Geant4PhysicsList> DD4hep::Simulation::Geant4PhysicsListActionSequence::m_actors protected
The list of action objects to be called.
Definition at line 199 of file Geant4PhysicsList.h.
Referenced by adopt(), constructParticles(), constructPhysics(), constructProcesses(), dump(), and ~Geant4PhysicsListActionSequence().
m_decays
bool DD4hep::Simulation::Geant4PhysicsListActionSequence::m_decays
Flag if particle decays are to be added.
Definition at line 207 of file Geant4PhysicsList.h.
Referenced by constructProcesses(), dump(), and Geant4PhysicsListActionSequence().
m_extends
std::string DD4hep::Simulation::Geant4PhysicsListActionSequence::m_extends
Property: Store name of basic predefined Geant4 physics list.
Definition at line 209 of file Geant4PhysicsList.h.
Referenced by dump(), extensionList(), and Geant4PhysicsListActionSequence().
m_particle
CallbackSequence DD4hep::Simulation::Geant4PhysicsListActionSequence::m_particle protected
Callback sequence for G4 particle constructors.
Definition at line 197 of file Geant4PhysicsList.h.
Referenced by constructParticles().
m_physics
CallbackSequence DD4hep::Simulation::Geant4PhysicsListActionSequence::m_physics protected
Callback sequence for G4 physics constructors.
Definition at line 193 of file Geant4PhysicsList.h.
Referenced by constructPhysics().
m_process
CallbackSequence DD4hep::Simulation::Geant4PhysicsListActionSequence::m_process protected
Callback sequence for G4 process constructors.
Definition at line 195 of file Geant4PhysicsList.h.
Referenced by constructProcesses(), and ~Geant4PhysicsListActionSequence().
m_rangecut
double DD4hep::Simulation::Geant4PhysicsListActionSequence::m_rangecut
global range cut for secondary productions
Definition at line 211 of file Geant4PhysicsList.h.
Referenced by DD4hep::Simulation::Geant4Exec::configure(), dump(), and Geant4PhysicsListActionSequence().
m_transportation
bool DD4hep::Simulation::Geant4PhysicsListActionSequence::m_transportation
Flag if particle transportation is to be added.
Definition at line 205 of file Geant4PhysicsList.h.
Referenced by dump(), and Geant4PhysicsListActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4PhysicsList.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4PhysicsList.cpp