DD4hep: DD4hep: TiXmlText Class Reference
TiXmlText Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlText (const char *initValue)
virtual ~TiXmlText ()
TiXmlText (const TiXmlText &copy)
void operator= (const TiXmlText &base)
virtual void Print (FILE *cfile, int depth) const
bool CDATA () const
Queries whether this represents text using a CDATA section.
void SetCDATA (bool _cdata)
Turns on or off a CDATA representation of text.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Protected Member Functions
virtual TiXmlNode * Clone () const
[internal use] Creates a new Element and returns it.
void CopyTo (TiXmlText *target) const
bool Blank () const
Private Attributes
bool cdata
Friends
class TiXmlElement
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
XML text. A text node can have 2 ways to output the next. "normal" output and CDATA. It will default to the mode it was parsed from the XML file and you generally want to leave it alone, but you can change the output mode with SetCDATA() and query it with CDATA().
See
See also:
http://www.grinninglizard.com/tinyxml
Definition at line 1336 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlText::TiXmlText (const char * initValue) [inline]
Constructor for text element. By default, it is treated as normal, encoded text. If you want it be output as a CDATA text element, set the parameter _cdata to 'true'
Definition at line 1343 of file tinyxml.h.
References cdata, and TiXmlNode::SetValue().
Referenced by Clone().
virtual TiXmlText::~TiXmlText () [inline, virtual]
Definition at line 1348 of file tinyxml.h.
TiXmlText::TiXmlText (const TiXmlText & copy) [inline]
Definition at line 1360 of file tinyxml.h.
References CopyTo().
Member Function Documentation
bool TiXmlText::Accept (TiXmlVisitor * content) const [virtual]
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
Definition at line 1385 of file tinyxml_inl.h.
References TiXmlVisitor::Visit().
bool TiXmlText::Blank () const [protected]
Definition at line 1607 of file tinyxmlparser_inl.h.
References TiXmlBase::IsWhiteSpace(), and TiXmlNode::value.
Referenced by TiXmlElement::ReadValue().
bool TiXmlText::CDATA () const [inline]
Queries whether this represents text using a CDATA section.
Definition at line 1372 of file tinyxml.h.
References cdata.
Referenced by TiXmlPrinter::Visit(), and TiXmlPrinter::VisitEnter().
TiXmlNode * TiXmlText::Clone () const [protected, virtual]
[internal use] Creates a new Element and returns it.
Implements TiXmlNode.
Definition at line 1391 of file tinyxml_inl.h.
References CopyTo(), and TiXmlText().
void TiXmlText::CopyTo (TiXmlText * target) const [protected]
Reimplemented from TiXmlNode.
Definition at line 1378 of file tinyxml_inl.h.
References cdata.
Referenced by Clone(), operator=(), and TiXmlText().
void TiXmlText::operator= (const TiXmlText & base) [inline]
Reimplemented from TiXmlNode.
Definition at line 1364 of file tinyxml.h.
References CopyTo().
const char * TiXmlText::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) [virtual]
Implements TiXmlBase.
Definition at line 1474 of file tinyxmlparser_inl.h.
References cdata, TiXmlParsingData::Cursor(), TiXmlNode::GetDocument(), TiXmlBase::location, TiXmlBase::ReadText(), TiXmlDocument::SetError(), TiXmlParsingData::Stamp(), TiXmlBase::StringEqual(), TiXmlBase::TIXML_ERROR_PARSING_CDATA, TIXML_STRING, and TiXmlNode::value.
Referenced by TiXmlElement::ReadValue().
void TiXmlText::Print (FILE * cfile, int depth) const [virtual]
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements TiXmlBase.
Definition at line 1357 of file tinyxml_inl.h.
References cdata, TiXmlBase::PutString(), TIXML_STRING, and TiXmlNode::value.
void TiXmlText::SetCDATA (bool _cdata) [inline]
Turns on or off a CDATA representation of text.
Definition at line 1376 of file tinyxml.h.
References cdata.
Referenced by TiXmlNode::Identify().
virtual TiXmlText* TiXmlText::ToText () [inline, virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1385 of file tinyxml.h.
virtual const TiXmlText* TiXmlText::ToText () const [inline, virtual]
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Definition at line 1382 of file tinyxml.h.
Friends And Related Function Documentation
friend class TiXmlElement [friend]
Reimplemented from TiXmlNode.
Definition at line 1337 of file tinyxml.h.
Member Data Documentation
bool TiXmlText::cdata [private]
Definition at line 1405 of file tinyxml.h.
Referenced by CDATA(), CopyTo(), Parse(), Print(), SetCDATA(), and TiXmlText().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxml_inl.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/tinyxmlparser_inl.h