DD4hep: DD4hep::Geometry::IDDescriptorObject Class Reference
DD4hep::Geometry::IDDescriptorObject Class Reference
DD4hep::Geometry components, classes and objects
Concrete object implementation of the IDDescriptorObject Handle.
#include <ObjectsInterna.h>
Public Types
typedef BitFieldValue * Field
typedef std::vector< std::pair< std::string, Field > > FieldMap
typedef std::vector< std::pair< size_t, std::string > > FieldIDs
Public Types inherited from DD4hep::DDSegmentation::BitField64
typedef std::map< std::string, unsigned int > IndexMap
Public Member Functions
IDDescriptorObject ()
Default constructor.
IDDescriptorObject (const std::string &initString)
Standard constructor.
virtual ~IDDescriptorObject ()
Default destructor.
const std::vector< BitFieldValue * > fields () const
Access to the field container of the BitField64.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Member Functions inherited from DD4hep::DDSegmentation::BitField64
virtual ~BitField64 ()
BitField64 (const std::string &initString)
long64 getValue () const
void setValue (long64 value)
void setValue (unsigned low_Word, unsigned high_Word)
BitField64 & operator() (long64 val)
void reset ()
BitFieldValue & operator[] (size_t idx)
const BitFieldValue & operator[] (size_t idx) const
unsigned highestBit () const
size_t size () const
size_t index (const std::string &name) const
BitFieldValue & operator[] (const std::string &name)
const BitFieldValue & operator[] (const std::string &name) const
unsigned lowWord () const
unsigned highWord () const
std::string fieldDescription () const
std::string valueString () const
Public Attributes
FieldMap fieldMap
FieldIDs fieldIDs
not ROOT-persistent
std::string description
not ROOT-persistent
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::DDSegmentation::BitField64
void addField (const std::string &name, unsigned offset, int width)
void init (const std::string &initString)
BitField64 ()
Protected Attributes inherited from DD4hep::DDSegmentation::BitField64
std::vector< BitFieldValue * > _fields
long64 _value
IndexMap _map
long64 _joined
Detailed Description
Concrete object implementation of the IDDescriptorObject Handle.
Author
M.Frank
Version
1.0
Date
2012/07/31
Definition at line 194 of file ObjectsInterna.h.
Member Typedef Documentation
Field
typedef BitFieldValue* DD4hep::Geometry::IDDescriptorObject::Field
Definition at line 196 of file ObjectsInterna.h.
FieldIDs
typedef std::vector<std::pair<size_t, std::string> > DD4hep::Geometry::IDDescriptorObject::FieldIDs
Definition at line 198 of file ObjectsInterna.h.
FieldMap
typedef std::vector<std::pair<std::string, Field> > DD4hep::Geometry::IDDescriptorObject::FieldMap
Definition at line 197 of file ObjectsInterna.h.
Constructor & Destructor Documentation
IDDescriptorObject() [1/2]
IDDescriptorObject::IDDescriptorObject ()
Default constructor.
Standard constructor.
Definition at line 111 of file ObjectsInterna.cpp.
References DD4hep::InstanceCount::increment().
IDDescriptorObject() [2/2]
IDDescriptorObject::IDDescriptorObject (const std::string & initString)
Standard constructor.
Definition at line 117 of file ObjectsInterna.cpp.
References DD4hep::InstanceCount::increment().
~IDDescriptorObject()
IDDescriptorObject::~IDDescriptorObject () virtual
Default destructor.
Definition at line 123 of file ObjectsInterna.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
fields()
const std::vector<BitFieldValue*> DD4hep::Geometry::IDDescriptorObject::fields () const inline
Access to the field container of the BitField64.
Definition at line 210 of file ObjectsInterna.h.
Member Data Documentation
description
std::string DD4hep::Geometry::IDDescriptorObject::description
not ROOT-persistent
Definition at line 201 of file ObjectsInterna.h.
fieldIDs
FieldIDs DD4hep::Geometry::IDDescriptorObject::fieldIDs
not ROOT-persistent
Definition at line 200 of file ObjectsInterna.h.
fieldMap
FieldMap DD4hep::Geometry::IDDescriptorObject::fieldMap
Definition at line 199 of file ObjectsInterna.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/ObjectsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ObjectsInterna.cpp