DD4hep: DD4hep::Simulation::Geant4VolumeManager Class Reference
DD4hep::Simulation::Geant4VolumeManager Class Reference
The Geant4VolumeManager to facilitate optimized lookups of cell IDs from touchables.
#include <DDG4/Geant4VolumeManager.h>
Public Types
typedef Geometry::Handle< Geant4GeometryInfo > Base
typedef Geometry::PlacedVolume PlacedVolume
typedef Geometry::IDDescriptor IDDescriptor
typedef IDDescriptor::VolIDFields VolIDFields
typedef std::pair< VolumeID, VolIDFields > VolIDDescriptor
typedef Geant4GeometryMaps::Geant4PlacementPath PlacementPath
typedef Geant4GeometryInfo Object
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Geant4VolumeManager (Geometry::LCDD &lcdd, Geant4GeometryInfo *info)
Initializing constructor. The tree will automatically be built if possible.
Geant4VolumeManager ()
Default constructor.
Geant4VolumeManager (const Base &e)
Constructor to be used when reading the already parsed object.
Geant4VolumeManager (const Geant4VolumeManager &e)
Constructor to be used when reading the already parsed object.
template<typename Q >
Geant4VolumeManager (const Geometry::Handle< Q > &e)
Constructor to be used when reading the already parsed object.
Geant4VolumeManager & operator= (const Geant4VolumeManager &c)
Assignment operator.
PlacementPath placementPath (const G4VTouchable *touchable, bool exception=true) const
Helper: Generate placement path from touchable object.
VolumeID volumeID (const PlacementPath &path) const
Access CELLID by placement path.
VolumeID volumeID (const G4VTouchable *touchable) const
Access CELLID by Geant4 touchable object.
void volumeDescriptor (const PlacementPath &path, VolIDDescriptor &volume_desc) const
Accessfully decoded volume fields by placement path.
void volumeDescriptor (const G4VTouchable *touchable, VolIDDescriptor &volume_desc) const
Access fully decoded volume fields by Geant4 touchable object.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Static Public Attributes
static const VolumeID InvalidPath = VolumeID(-1LL)
static const VolumeID Insensitive = VolumeID(-2LL)
static const VolumeID NonExisting = 0ULL
Protected Member Functions
bool checkValidity () const
Check the validity of the information before accessing it.
Protected Attributes
bool m_isValid
Optimization flag to shortcut object checks.
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
The Geant4VolumeManager to facilitate optimized lookups of cell IDs from touchables.
Author
M.Frank
Version
1.0
Definition at line 42 of file Geant4VolumeManager.h.
Member Typedef Documentation
Base
typedef Geometry::Handle<Geant4GeometryInfo> DD4hep::Simulation::Geant4VolumeManager::Base
Definition at line 45 of file Geant4VolumeManager.h.
IDDescriptor
typedef Geometry::IDDescriptor DD4hep::Simulation::Geant4VolumeManager::IDDescriptor
Definition at line 47 of file Geant4VolumeManager.h.
Object
typedef Geant4GeometryInfo DD4hep::Simulation::Geant4VolumeManager::Object
Definition at line 51 of file Geant4VolumeManager.h.
PlacedVolume
typedef Geometry::PlacedVolume DD4hep::Simulation::Geant4VolumeManager::PlacedVolume
Definition at line 46 of file Geant4VolumeManager.h.
PlacementPath
typedef Geant4GeometryMaps::Geant4PlacementPath DD4hep::Simulation::Geant4VolumeManager::PlacementPath
Definition at line 50 of file Geant4VolumeManager.h.
VolIDDescriptor
typedef std::pair<VolumeID, VolIDFields> DD4hep::Simulation::Geant4VolumeManager::VolIDDescriptor
Definition at line 49 of file Geant4VolumeManager.h.
VolIDFields
typedef IDDescriptor::VolIDFields DD4hep::Simulation::Geant4VolumeManager::VolIDFields
Definition at line 48 of file Geant4VolumeManager.h.
Constructor & Destructor Documentation
Geant4VolumeManager() [1/5]
Geant4VolumeManager::Geant4VolumeManager (Geometry::LCDD & lcdd, Geant4GeometryInfo * info)
Initializing constructor. The tree will automatically be built if possible.
Definition at line 191 of file Geant4VolumeManager.cpp.
References DD4hep::format(), DD4hep::Simulation::Geant4GeometryInfo::g4Paths, DD4hep::Simulation::Geant4GeometryInfo::valid, and DD4hep::Geometry::LCDD::world().
Geant4VolumeManager() [2/5]
DD4hep::Simulation::Geant4VolumeManager::Geant4VolumeManager () inline
Default constructor.
Definition at line 68 of file Geant4VolumeManager.h.
Geant4VolumeManager() [3/5]
DD4hep::Simulation::Geant4VolumeManager::Geant4VolumeManager (const Base & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 72 of file Geant4VolumeManager.h.
Geant4VolumeManager() [4/5]
DD4hep::Simulation::Geant4VolumeManager::Geant4VolumeManager (const Geant4VolumeManager & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 76 of file Geant4VolumeManager.h.
Geant4VolumeManager() [5/5]
template<typename Q > DD4hep::Simulation::Geant4VolumeManager::Geant4VolumeManager (const Geometry::Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 80 of file Geant4VolumeManager.h.
Member Function Documentation
checkValidity()
bool Geant4VolumeManager::checkValidity () const protected
Check the validity of the information before accessing it.
Definition at line 208 of file Geant4VolumeManager.cpp.
References DD4hep::format(), DD4hep::Handle< T >::isValid(), m_isValid, and DD4hep::Handle< T >::ptr().
Referenced by volumeDescriptor(), and volumeID().
operator=()
Geant4VolumeManager& DD4hep::Simulation::Geant4VolumeManager::operator= (const Geant4VolumeManager & c) inline
Assignment operator.
Definition at line 84 of file Geant4VolumeManager.h.
References DD4hep::Handle< T >::m_element, m_isValid, placementPath(), volumeDescriptor(), and volumeID().
placementPath()
Geant4PlacementPath Geant4VolumeManager::placementPath (const G4VTouchable * touchable, bool exception = true) const
Helper: Generate placement path from touchable object.
Definition at line 202 of file Geant4VolumeManager.cpp.
References DD4hep::Simulation::Geant4TouchableHandler::placementPath().
Referenced by operator=(), and volumeDescriptor().
volumeDescriptor() [1/2]
void Geant4VolumeManager::volumeDescriptor (const PlacementPath & path, VolIDDescriptor & volume_desc) const
Accessfully decoded volume fields by placement path.
Definition at line 246 of file Geant4VolumeManager.cpp.
References checkValidity(), DD4hep::Geometry::IDDescriptor::decodeFields(), DD4hep::Geometry::Readout::idSpec(), Insensitive, InvalidPath, m, NonExisting, DD4hep::Handle< T >::ptr(), DD4hep::Geometry::SensitiveDetector::readout(), DD4hep::Geometry::Volume::sensitiveDetector(), and DD4hep::Geometry::PlacedVolume::volume().
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), operator=(), and volumeDescriptor().
volumeDescriptor() [2/2]
void Geant4VolumeManager::volumeDescriptor (const G4VTouchable * touchable, VolIDDescriptor & volume_desc) const
Access fully decoded volume fields by Geant4 touchable object.
Definition at line 282 of file Geant4VolumeManager.cpp.
References placementPath(), and volumeDescriptor().
volumeID() [1/2]
VolumeID Geant4VolumeManager::volumeID (const PlacementPath & path) const
Access CELLID by placement path.
Definition at line 223 of file Geant4VolumeManager.cpp.
References checkValidity(), DD4hep::INFO, Insensitive, InvalidPath, m, NonExisting, DD4hep::Simulation::Geant4GeometryMaps::placementPath(), DD4hep::printout(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Simulation::Geant4Sensitive::cellID(), DD4hep::Simulation::Geant4SensitiveDetector::getCellID(), DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::operator()(), operator=(), volumeID(), and DD4hep::Simulation::Geant4Sensitive::volumeID().
volumeID() [2/2]
VolumeID Geant4VolumeManager::volumeID (const G4VTouchable * touchable) const
Access CELLID by Geant4 touchable object.
Definition at line 240 of file Geant4VolumeManager.cpp.
References DD4hep::Simulation::Geant4TouchableHandler::placementPath(), and volumeID().
Member Data Documentation
Insensitive
const VolumeID DD4hep::Simulation::Geant4VolumeManager::Insensitive = VolumeID(-2LL) static
Definition at line 62 of file Geant4VolumeManager.h.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), volumeDescriptor(), and volumeID().
InvalidPath
const VolumeID DD4hep::Simulation::Geant4VolumeManager::InvalidPath = VolumeID(-1LL) static
Definition at line 61 of file Geant4VolumeManager.h.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), volumeDescriptor(), and volumeID().
m_isValid
bool DD4hep::Simulation::Geant4VolumeManager::m_isValid mutable protected
Optimization flag to shortcut object checks.
Definition at line 55 of file Geant4VolumeManager.h.
Referenced by checkValidity(), and operator=().
NonExisting
const VolumeID DD4hep::Simulation::Geant4VolumeManager::NonExisting = 0ULL static
Definition at line 63 of file Geant4VolumeManager.h.
Referenced by DD4hep::Simulation::Geant4SensitiveDetector::getVolumeID(), volumeDescriptor(), and volumeID().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4VolumeManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4VolumeManager.cpp