DD4hep: DD4hep: DD4hep::ContextMenu Class Reference
DD4hep::ContextMenu Class Reference
#include <DDEve/ContextMenu.h>
Public Member Functions
ContextMenu & Clear ()
Clear all existing items.
ContextMenu & AddSeparator ()
Add a separator.
template<typename Q , typename T >
ContextMenu & Add (const std::string &title, Q *ptr, void(T::*pmf)(TObject *, void *ud), void *ud=0)
Add a user item to the menu.
ClassDef (ContextMenu, 0)
Root implementation macro.
Static Public Member Functions
static ContextMenu & instance (TClass *cl)
Instantiator.
Private Types
typedef std::vector
< ContextMenuHandler * > Handlers
Private Member Functions
ContextMenu (TClass *cl)
Initializing constructor.
virtual ~ContextMenu ()
Default destructor.
ContextMenu & Add (const std::string &title, Callback cb, void *ud)
Add user callback.
Private Attributes
Handlers m_calls
Callback map.
TClass * m_class
List of menu entries.
Detailed Description
Author:
M.Frank
Version:
1.0
Definition at line 61 of file ContextMenu.h.
Member Typedef Documentation
typedef std::vector<ContextMenuHandler*> DD4hep::ContextMenu::Handlers [private]
Definition at line 62 of file ContextMenu.h.
Constructor & Destructor Documentation
DD4hep::ContextMenu::ContextMenu (TClass * cl) [private]
Initializing constructor.
Referenced by instance().
ContextMenu::~ContextMenu () [private, virtual]
Default destructor.
Definition at line 64 of file ContextMenu.cpp.
Member Function Documentation
template<typename Q , typename T > ContextMenu& DD4hep::ContextMenu::Add (const std::string & title, Q * ptr, void(T::*)(TObject *, void *ud) pmf, void * ud = 0) [inline]
Add a user item to the menu.
Definition at line 83 of file ContextMenu.h.
References Add().
ContextMenu& DD4hep::ContextMenu::Add (const std::string & title, Callback cb, void * ud) [private]
Add user callback.
Referenced by Add(), and DD4hep::EveUserContextMenu::InstallGeometryContextMenu().
ContextMenu & ContextMenu::AddSeparator ()
Add a separator.
Definition at line 85 of file ContextMenu.cpp.
References m_class.
Referenced by DD4hep::EveUserContextMenu::InstallGeometryContextMenu().
DD4hep::ContextMenu::ClassDef (ContextMenu , 0)
Root implementation macro.
ContextMenu & ContextMenu::Clear ()
Clear all existing items.
Definition at line 77 of file ContextMenu.cpp.
References m_class.
Referenced by DD4hep::EveUserContextMenu::InstallGeometryContextMenu().
ContextMenu & ContextMenu::instance (TClass * cl) [static]
Instantiator.
Definition at line 68 of file ContextMenu.cpp.
References ContextMenu(), dd4hep::m, and mapped_entries().
Referenced by DD4hep::EveUserContextMenu::InstallGeometryContextMenu().
Member Data Documentation
Handlers DD4hep::ContextMenu::m_calls [private]
Callback map.
Definition at line 64 of file ContextMenu.h.
TClass* DD4hep::ContextMenu::m_class [private]
List of menu entries.
Definition at line 66 of file ContextMenu.h.
Referenced by AddSeparator(), and Clear().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/ContextMenu.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/ContextMenu.cpp