DD4hep: DD4hep::Simulation::Geant4Exec Class Reference
DD4hep::Simulation::Geant4Exec Class Reference
Main executor steering the Geant4 execution.
#include <Geant4Kernel.h>
Static Public Member Functions
static int configure (Geant4Kernel &kernel)
Configure the application.
static int initialize (Geant4Kernel &kernel)
Initialize the application.
static int run (Geant4Kernel &kernel)
Run the application and simulate events.
static int terminate (Geant4Kernel &kernel)
Terminate the application.
Detailed Description
Main executor steering the Geant4 execution.
Definition at line 274 of file Geant4Kernel.h.
Member Function Documentation
configure()
int Geant4Exec::configure (Geant4Kernel & kernel) static
Configure the application.
Configure the simulation.
Initialize the engine etc.
Definition at line 514 of file Geant4Exec.cpp.
References Geant4Compatibility::buildDefaultDetectorConstruction(), DD4hep::DEBUG, DD4hep::Simulation::Geant4ActionContainer::detectorConstruction(), DD4hep::Simulation::Geant4Kernel::executePhase(), DD4hep::Simulation::Geant4PhysicsListActionSequence::extensionList(), DD4hep::INFO, DD4hep::Simulation::Geant4Random::initialize(), DD4hep::Simulation::Geant4Random::instance(), DD4hep::Simulation::Geant4Kernel::isMultiThreaded(), DD4hep::Simulation::Geant4Kernel::lcdd(), DD4hep::Simulation::Geant4PhysicsListActionSequence::m_rangecut, DD4hep::Simulation::Geant4ActionContainer::physicsList(), DD4hep::printLevel(), DD4hep::printout(), DD4hep::Simulation::Geant4Action::property(), DD4hep::Simulation::Geant4Kernel::runManager(), DD4hep::Geometry::LCDD::sensitiveDetectors(), DD4hep::Property::set(), DD4hep::Simulation::Geant4Random::setMainInstance(), DD4hep::Simulation::Geant4ActionContainer::userInitialization(), DD4hep::WARNING, and DD4hep::Simulation::Geant4ActionContainer::workerContext().
Referenced by DD4hep::Simulation::Geant4Kernel::configure().
initialize()
int Geant4Exec::initialize (Geant4Kernel & kernel) static
Initialize the application.
Initialize the simulation.
Definition at line 583 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4Kernel::executePhase(), and DD4hep::Simulation::Geant4Kernel::runManager().
Referenced by DD4hep::Simulation::Geant4Kernel::initialize().
run()
int Geant4Exec::run (Geant4Kernel & kernel) static
Run the application and simulate events.
Run the simulation.
Definition at line 595 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Kernel::executePhase(), DD4hep::format(), DD4hep::Simulation::Geant4Kernel::globalAction(), DD4hep::Simulation::Geant4Kernel::property(), DD4hep::Simulation::Geant4Kernel::runManager(), and DD4hep::Property::value().
Referenced by DD4hep::Simulation::Geant4Kernel::run(), and DD4hep::Simulation::Geant4Kernel::runEvents().
terminate()
int Geant4Exec::terminate (Geant4Kernel & kernel) static
Terminate the application.
Run the simulation.
Definition at line 620 of file Geant4Exec.cpp.
References DD4hep::Simulation::Geant4Kernel::executePhase().
Referenced by DD4hep::Simulation::Geant4Kernel::terminate().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4Kernel.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp