DD4hep: DD4hepRootPersistency Class Reference
DD4hepRootPersistency Class Reference
Helper class to support ROOT persistency of LCDD objects.
#include <DD4hepRootPersistency.h>
Public Member Functions
DD4hepRootPersistency ()
Default constructor.
virtual ~DD4hepRootPersistency ()
Default destructor.
ClassDef (DD4hepRootPersistency, 1)
ROOT implementation macro.
Public Member Functions inherited from DD4hep::Geometry::LCDDData
void destroyData (bool destroy_mgr=true)
Assignment operator.
void clearData ()
Clear data content: DOES NOT RELEASEW ALLOCATED RESOURCES!
void adoptData (LCDDData &source)
Adopt all data from source structure.
Static Public Member Functions
static int save (DD4hep::Geometry::LCDD &lcdd, const char *fname, const char *instance="Geometry")
static int load (DD4hep::Geometry::LCDD &lcdd, const char *fname, const char *instance="Geometry")
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Geometry::LCDDData
LCDDData ()
Default constructor.
virtual ~LCDDData ()
Default destructor.
LCDDData (const LCDDData &copy)=delete
Copy constructor.
Protected Attributes inherited from DD4hep::Geometry::LCDDData
TGeoManager * m_manager
ObjectHandleMap m_readouts
ObjectHandleMap m_idDict
ObjectHandleMap m_limits
ObjectHandleMap m_regions
ObjectHandleMap m_detectors
ObjectHandleMap m_alignments
ObjectHandleMap m_sensitive
ObjectHandleMap m_display
ObjectHandleMap m_fields
ObjectHandleMap m_motherVolumes
ObjectHandleMap m_define
DetElement m_world
DetElement m_trackers
Volume m_worldVol
Volume m_trackingVol
Material m_materialAir
Material m_materialVacuum
VisAttr m_invisibleVis
OverlayedField m_field
Header m_header
LCDD::Properties m_properties
LCDDBuildType m_buildType
ObjectExtensions m_extensions
Definition of the extension type.
VolumeManager m_volManager
Volume manager reference.
bool m_inhibitConstants
Flag to inhibit the access to global constants. Value set by constants section 'LCDD_InhibitConstants'.
Detailed Description
Helper class to support ROOT persistency of LCDD objects.
Definition at line 20 of file DD4hepRootPersistency.h.
Constructor & Destructor Documentation
DD4hepRootPersistency()
DD4hepRootPersistency::DD4hepRootPersistency () inline
Default constructor.
Definition at line 23 of file DD4hepRootPersistency.h.
~DD4hepRootPersistency()
virtual DD4hepRootPersistency::~DD4hepRootPersistency () inline virtual
Default destructor.
Definition at line 25 of file DD4hepRootPersistency.h.
References ClassDef(), load(), and save().
Member Function Documentation
ClassDef()
DD4hepRootPersistency::ClassDef (DD4hepRootPersistency , 1)
ROOT implementation macro.
Referenced by ~DD4hepRootPersistency().
load()
int DD4hepRootPersistency::load (DD4hep::Geometry::LCDD & lcdd, const char * fname, const char * instance = "Geometry") static
Definition at line 45 of file DD4hepRootPersistency.cpp.
References DD4hep::Geometry::LCDDData::clearData(), DD4hep::ERROR, DD4hep::Geometry::LCDDData::LCDDData(), and DD4hep::printout().
Referenced by ~DD4hepRootPersistency().
save()
int DD4hepRootPersistency::save (DD4hep::Geometry::LCDD & lcdd, const char * fname, const char * instance = "Geometry") static
Definition at line 27 of file DD4hepRootPersistency.cpp.
References DD4hep::Geometry::LCDDData::adoptData(), DD4hep::ALWAYS, DD4hep::ERROR, and DD4hep::printout().
Referenced by ~DD4hepRootPersistency().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/DD4hepRootPersistency.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DD4hepRootPersistency.cpp