DD4hep: DD4hep::Geometry::Box Class Reference
DD4hep::Geometry::Box Class Reference
DD4hep::Geometry components, classes and objects
Class describing a box shape.
#include <Shapes.h>
Public Member Functions
Box ()=default
Default constructor.
Box (const Box &e)=default
Constructor to be used when passing an already created object.
template<typename Q >
Box (const Q *p)
Constructor to be used with an existing object.
template<typename Q >
Box (const Handle< Q > &e)
Constructor to be used with an existing object.
Box (double x_val, double y_val, double z_val)
Constructor to create an anonymous new box object (retrieves name from volume)
template<typename X , typename Y , typename Z >
Box (const X &x_val, const Y &y_val, const Z &z_val)
Constructor to create an anonymous new box object (retrieves name from volume)
Box & operator= (const Box &copy)=default
Assignment operator.
Box & setDimensions (double x_val, double y_val, double z_val)
Set the box dimensions.
double x () const
Access half "length" of the box.
double y () const
Access half "width" of the box.
double z () const
Access half "depth" of the box.
Public Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoBBox >
Solid_type ()=default
Default constructor for uninitialized object.
Solid_type (const Solid_type &e)=default
Constructor to be used when passing an already created object.
Solid_type (TGeoBBox *p)
Direct assignment using the implementation pointer.
Solid_type (const Handle< TGeoBBox > &e)
Constructor to be used when passing an already created object.
Solid_type (const Handle< Q > &e)
Constructor to be used when passing an already created object: need to check pointers.
Solid_type & operator= (const Solid_type &copy)=default
Assignment operator.
const char * name () const
Access to shape name.
operator TGeoBBox * () const
Auto conversion to underlying ROOT object.
TGeoBBox * operator-> () const
Overloaded operator -> to access underlying object.
std::string toString (int precision=2) const
Conversion to string for pretty print.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Protected Member Functions
void make (double x_val, double y_val, double z_val)
Internal helper method to support object construction.
Protected Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoBBox >
void _setDimensions (double *param)
void _assign (TGeoBBox *n, const std::string &nam, const std::string &tit, bool cbbox)
Assign pointrs and register solid to geometry.
Additional Inherited Members
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Protected Types inherited from DD4hep::Geometry::Solid_type< TGeoBBox >
typedef TGeoBBox Implementation
Detailed Description
Class describing a box shape.
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoBBox.html
Author
M.Frank
Version
1.0
Definition at line 118 of file Shapes.h.
Constructor & Destructor Documentation
Box() [1/6]
DD4hep::Geometry::Box::Box () default
Default constructor.
Box() [2/6]
DD4hep::Geometry::Box::Box (const Box & e) default
Constructor to be used when passing an already created object.
Box() [3/6]
template<typename Q > DD4hep::Geometry::Box::Box (const Q * p) inline
Constructor to be used with an existing object.
Definition at line 129 of file Shapes.h.
Box() [4/6]
template<typename Q > DD4hep::Geometry::Box::Box (const Handle< Q > & e) inline
Constructor to be used with an existing object.
Definition at line 131 of file Shapes.h.
Box() [5/6]
DD4hep::Geometry::Box::Box (double x_val, double y_val, double z_val) inline
Constructor to create an anonymous new box object (retrieves name from volume)
Definition at line 133 of file Shapes.h.
Box() [6/6]
template<typename X , typename Y , typename Z > DD4hep::Geometry::Box::Box (const X & x_val, const Y & y_val, const Z & z_val) inline
Constructor to create an anonymous new box object (retrieves name from volume)
Definition at line 136 of file Shapes.h.
References DD4hep::_toDouble(), DD4hep::Alignments::AlignmentTools::copy(), and DD4hep::Geometry::Solid_type< T >::operator=().
Member Function Documentation
make()
void Box::make (double x_val, double y_val, double z_val) protected
Internal helper method to support object construction.
Definition at line 176 of file Shapes.cpp.
operator=()
Box& DD4hep::Geometry::Box::operator= (const Box & copy) default
Assignment operator.
setDimensions()
Box & Box::setDimensions (double x_val, double y_val, double z_val)
Set the box dimensions.
Set the box dimensionsy.
Definition at line 181 of file Shapes.cpp.
x()
double Box::x () const
Access half "length" of the box.
Definition at line 188 of file Shapes.cpp.
y()
double Box::y () const
Access half "width" of the box.
Definition at line 193 of file Shapes.cpp.
z()
double Box::z () const
Access half "depth" of the box.
Definition at line 198 of file Shapes.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp