DD4hep: DD4hep: DD4hep::Simulation::Geant4FieldTrackingSetupAction Class Reference
DD4hep::Simulation::Geant4FieldTrackingSetupAction Class Reference
Phase action to perform the setup of the Geant4 tracking in magnetic fields.
Public Member Functions
Geant4FieldTrackingSetupAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4FieldTrackingSetupAction ()
Default destructor.
void operator() ()
Phase action callback.
Detailed Description
Phase action to perform the setup of the Geant4 tracking in magnetic fields.
Geant4FieldTrackingSetupAction.
The phase action configures the Geant4FieldTrackingSetup base class using properties and then configures the Geant4 tracking in magnetic fields.
Author:
M.Frank
Version:
1.0
Definition at line 81 of file Geant4FieldTrackingSetup.cpp.
Constructor & Destructor Documentation
Geant4FieldTrackingSetupAction::Geant4FieldTrackingSetupAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 253 of file Geant4FieldTrackingSetup.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::Simulation::Geant4FieldTrackingSetup::delta_chord, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_intersection, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_one_step, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_max, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_min, DD4hep::Simulation::Geant4FieldTrackingSetup::eq_typ, DD4hep::Simulation::Geant4FieldTrackingSetup::largest_step, DD4hep::Simulation::Geant4FieldTrackingSetup::min_chord_step, and DD4hep::Simulation::Geant4FieldTrackingSetup::stepper_typ.
virtual DD4hep::Simulation::Geant4FieldTrackingSetupAction::~Geant4FieldTrackingSetupAction () [inline, virtual]
Default destructor.
Definition at line 91 of file Geant4FieldTrackingSetup.cpp.
Member Function Documentation
void Geant4FieldTrackingSetupAction::operator() () [virtual]
Phase action callback.
Post-track action callback.
Reimplemented from DD4hep::Simulation::Geant4PhaseAction.
Definition at line 268 of file Geant4FieldTrackingSetup.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4FieldTrackingSetup::delta_chord, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_intersection, DD4hep::Simulation::Geant4FieldTrackingSetup::delta_one_step, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_max, DD4hep::Simulation::Geant4FieldTrackingSetup::eps_min, DD4hep::Simulation::Geant4FieldTrackingSetup::eq_typ, DD4hep::Simulation::Geant4FieldTrackingSetup::execute(), DD4hep::INFO, DD4hep::Simulation::Geant4FieldTrackingSetup::largest_step, DD4hep::printout(), and DD4hep::Simulation::Geant4FieldTrackingSetup::stepper_typ.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4FieldTrackingSetup.cpp