DD4hep: DD4hep::Simulation::Geant4Sensitive Class Reference
DD4hep::Simulation::Geant4Sensitive Class Reference
DD4hep::Simulation components, classes and objects
The base class for Geant4 sensitive detector actions implemented by users.
#include <Geant4SensDetAction.h>
Public Types
enum HitCreationFlags { SIMPLE_MODE = 0, MEDIUM_MODE = 1<<0, DETAILED_MODE = 1<<1 }
typedef Geometry::LCDD LCDD
typedef Geometry::Readout Readout
typedef Geometry::DetElement DetElement
typedef Geometry::Segmentation Segmentation
typedef Geometry::SensitiveDetector SensitiveDetector
Definition: Sensitive detector type.
typedef Geant4StepHandler StepHandler
typedef Geant4HitCollection HitCollection
Public Member Functions
Geant4Sensitive (Geant4Context *context, const std::string &name, DetElement det, LCDD &lcdd)
Constructor. The sensitive detector element is identified by the detector name.
virtual ~Geant4Sensitive ()
Standard destructor.
Geant4ActionSD & detector () const
Access to the sensitive detector object.
void setDetector (Geant4ActionSD *sens_det)
Access to the sensitive detector object.
int hitCreationMode () const
Property access to the hit creation mode.
std::string detectorName () const
G4VSensitiveDetector internals: Access to the detector name.
std::string path () const
G4VSensitiveDetector internals: Access to the detector path name.
std::string fullPath () const
G4VSensitiveDetector internals: Access to the detector path name.
bool isActive () const
G4VSensitiveDetector internals: Is the detector active?
SensitiveDetector sensitiveDetector () const
Access the DD4hep sensitive detector.
G4VReadOutGeometry * readoutGeometry () const
Access to the readout geometry of the sensitive detector.
void mark (const G4Track *track) const
Mark the track to be kept for MC truth propagation during hit processing.
void mark (const G4Step *step) const
Mark the track of this step to be kept for MC truth propagation during hit processing.
Geant4SensDetActionSequence & sequence () const
Access to the hosting sequence.
void adopt (Geant4Filter *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adopt_front (Geant4Filter *filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
void adoptFilter (Geant4Action *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adoptFilter_front (Geant4Action *filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
bool accept (const G4Step *step) const
Callback before hit processing starts. Invoke all filters.
template<typename TYPE >
size_t defineCollection (const std::string &coll_name)
Initialize the usage of a single hit collection. Returns the collection ID.
const std::string & hitCollectionName (size_t which) const
Access HitCollection container names.
HitCollection * collection (size_t which)
Retrieve the hits collection associated with this detector by its serial number.
HitCollection * collectionByID (size_t id)
Retrieve the hits collection associated with this detector by its collection identifier.
virtual void defineCollections ()
Define collections created by this sensitivie action object.
virtual void begin (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the begining of each event.
virtual void end (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the end of each event.
virtual bool process (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
virtual void clear (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked if the event was aborted.
long long int volumeID (const G4Step *step)
Returns the volumeID of the sensitive volume corresponding to the step.
long long int cellID (const G4Step *step)
Returns the cellID of the sensitive volume corresponding to the step.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
int m_hitCreationMode
Property: Hit creation mode. Maybe one of the enum HitCreationFlags.
LCDD & m_lcdd
Reference to the detector description object.
DetElement m_detector
Reference to the detector element describing this sensitive element.
SensitiveDetector m_sensitive
Reference to the sensitive detector element.
Readout m_readout
Reference to the readout structure.
Segmentation m_segmentation
Reference to segmentation.
Actors< Geant4Filter > m_filters
The list of sensitive detector filter objects.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Private Attributes
Geant4ActionSD * m_sensitiveDetector
Reference to G4 sensitive detector.
Geant4SensDetActionSequence * m_sequence
Reference to the containing action sequence.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
The base class for Geant4 sensitive detector actions implemented by users.
Author
M.Frank
Version
1.0
Definition at line 110 of file Geant4SensDetAction.h.
Member Typedef Documentation
DetElement
typedef Geometry::DetElement DD4hep::Simulation::Geant4Sensitive::DetElement
Definition at line 114 of file Geant4SensDetAction.h.
HitCollection
typedef Geant4HitCollection DD4hep::Simulation::Geant4Sensitive::HitCollection
Definition at line 120 of file Geant4SensDetAction.h.
LCDD
typedef Geometry::LCDD DD4hep::Simulation::Geant4Sensitive::LCDD
Definition at line 112 of file Geant4SensDetAction.h.
Readout
typedef Geometry::Readout DD4hep::Simulation::Geant4Sensitive::Readout
Definition at line 113 of file Geant4SensDetAction.h.
Segmentation
typedef Geometry::Segmentation DD4hep::Simulation::Geant4Sensitive::Segmentation
Definition at line 115 of file Geant4SensDetAction.h.
SensitiveDetector
typedef Geometry::SensitiveDetector DD4hep::Simulation::Geant4Sensitive::SensitiveDetector
Definition: Sensitive detector type.
Definition at line 117 of file Geant4SensDetAction.h.
StepHandler
typedef Geant4StepHandler DD4hep::Simulation::Geant4Sensitive::StepHandler
Definition at line 119 of file Geant4SensDetAction.h.
Member Enumeration Documentation
HitCreationFlags
enum DD4hep::Simulation::Geant4Sensitive::HitCreationFlags
Enumerator
SIMPLE_MODE
MEDIUM_MODE
DETAILED_MODE
Definition at line 122 of file Geant4SensDetAction.h.
Constructor & Destructor Documentation
Geant4Sensitive()
Geant4Sensitive::Geant4Sensitive (Geant4Context * context, const std::string & name, DetElement det, LCDD & lcdd)
Constructor. The sensitive detector element is identified by the detector name.
Constructor. The detector element is identified by the name.
Definition at line 89 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::format(), DD4hep::InstanceCount::increment(), DD4hep::Handle< T >::isValid(), DD4hep::Simulation::Geant4Context::kernel(), m_detector, m_hitCreationMode, m_readout, m_segmentation, m_sensitive, m_sequence, DD4hep::Handle< T >::name(), DD4hep::Geometry::SensitiveDetector::readout(), DD4hep::Geometry::Readout::segmentation(), DD4hep::Simulation::Geant4ActionContainer::sensitiveAction(), DD4hep::Geometry::LCDD::sensitiveDetector(), and SIMPLE_MODE.
~Geant4Sensitive()
Geant4Sensitive::~Geant4Sensitive () virtual
Standard destructor.
Definition at line 105 of file Geant4SensDetAction.cpp.
References DD4hep::InstanceCount::decrement(), m_filters, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
accept()
bool Geant4Sensitive::accept (const G4Step * step) const
Callback before hit processing starts. Invoke all filters.
Return fals if any filter returns false
Definition at line 144 of file Geant4SensDetAction.cpp.
References m_filters.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::process().
adopt()
void Geant4Sensitive::adopt (Geant4Filter * filter)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 118 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_filters.
Referenced by adoptFilter().
adopt_front()
void Geant4Sensitive::adopt_front (Geant4Filter * filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 134 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_filters.
Referenced by adoptFilter_front(), and DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection().
adoptFilter()
void Geant4Sensitive::adoptFilter (Geant4Action * filter)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 112 of file Geant4SensDetAction.cpp.
References adopt().
adoptFilter_front()
void Geant4Sensitive::adoptFilter_front (Geant4Action * filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 128 of file Geant4SensDetAction.cpp.
References adopt_front().
begin()
void Geant4Sensitive::begin (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked at the begining of each event.
Method invoked at the begining of each event.
The hits collection(s) created by this sensitive detector must be set to the G4HCofThisEvent object at one of these two methods.
Reimplemented in DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Test::Geant4TestSensitive, and Tests::Geant4SensitiveAction< T >.
Definition at line 189 of file Geant4SensDetAction.cpp.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::begin(), and DD4hep::Simulation::Geant4SensitiveAction< T >::begin().
cellID()
long long int Geant4Sensitive::cellID (const G4Step * step)
Returns the cellID of the sensitive volume corresponding to the step.
Returns the cellID(volumeID+local coordinate encoding) of the sensitive volume corresponding to the step.
The CellID is the VolumeID + the local coordinates of the sensitive area. Calculated by combining the VolIDS of the complete geometry path (Geant4TouchableHistory) from the current sensitive volume to the world volume
Definition at line 226 of file Geant4SensDetAction.cpp.
References DD4hep::Geometry::Segmentation::cellID(), DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Handle< T >::isValid(), m_segmentation, MM_2_CM, DD4hep::Simulation::Geant4StepHandler::postPosG4(), DD4hep::Simulation::Geant4StepHandler::prePosG4(), DD4hep::Simulation::Geant4StepHandler::preTouchable(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), and DD4hep::Simulation::Geant4Mapping::volumeManager().
Referenced by DD4hep::Simulation::TrackerWeighted::update(), and DD4hep::Simulation::TrackerCombine::update().
clear()
void Geant4Sensitive::clear (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Method is invoked if the event abortion is occured.
Hits collections created but not being set to G4HCofThisEvent at the event should be deleted. Collection(s) which have already set to G4HCofThisEvent will be deleted automatically.
Reimplemented in DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, and Tests::Geant4SensitiveAction< T >.
Definition at line 202 of file Geant4SensDetAction.cpp.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::clear(), and DD4hep::Simulation::Geant4SensitiveAction< T >::clear().
collection()
Geant4HitCollection * Geant4Sensitive::collection (size_t which)
Retrieve the hits collection associated with this detector by its serial number.
Definition at line 175 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4SensDetActionSequence::collection(), and sequence().
Referenced by DD4hep::Simulation::Test::Geant4TestSensitive::end(), DD4hep::Simulation::TrackerWeighted::endEvent(), DD4hep::Simulation::TrackerCombine::endEvent(), DD4hep::Simulation::TrackerWeighted::extractHit(), DD4hep::Simulation::Geant4EscapeCounter::process(), DD4hep::Simulation::Test::Geant4TestSensitive::process(), and DD4hep::Simulation::TrackerCombine::process().
collectionByID()
Geant4HitCollection * Geant4Sensitive::collectionByID (size_t id)
Retrieve the hits collection associated with this detector by its collection identifier.
Definition at line 180 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4SensDetActionSequence::collectionByID(), and sequence().
Referenced by DD4hep::Simulation::Test::Geant4TestSensitive::begin().
defineCollection()
template<typename TYPE > size_t DD4hep::Simulation::Geant4Sensitive::defineCollection (const std::string & coll_name) inline
Initialize the usage of a single hit collection. Returns the collection ID.
Definition at line 451 of file Geant4SensDetAction.h.
defineCollections()
void Geant4Sensitive::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented in DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, Tests::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, Tests::Geant4SensitiveAction< T >, and DD4hep::Simulation::Geant4SensitiveAction< T >.
Definition at line 185 of file Geant4SensDetAction.cpp.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::defineCollection().
detector()
Geant4ActionSD & Geant4Sensitive::detector () const
Access to the sensitive detector object.
Definition at line 155 of file Geant4SensDetAction.cpp.
References DD4hep::format(), m_sensitiveDetector, and DD4hep::Simulation::Geant4Action::name().
Referenced by DD4hep::Simulation::TrackerWeighted::startEvent().
detectorName()
std::string DD4hep::Simulation::Geant4Sensitive::detectorName () const inline
G4VSensitiveDetector internals: Access to the detector name.
Definition at line 169 of file Geant4SensDetAction.h.
end()
void Geant4Sensitive::end (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked at the end of each event.
Method invoked at the end of each event.
Reimplemented in DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Test::Geant4TestSensitive, and Tests::Geant4SensitiveAction< T >.
Definition at line 193 of file Geant4SensDetAction.cpp.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::end(), and DD4hep::Simulation::Geant4SensitiveAction< T >::end().
fullPath()
std::string DD4hep::Simulation::Geant4Sensitive::fullPath () const inline
G4VSensitiveDetector internals: Access to the detector path name.
Definition at line 179 of file Geant4SensDetAction.h.
hitCollectionName()
const string & Geant4Sensitive::hitCollectionName (size_t which) const
Access HitCollection container names.
Definition at line 170 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4SensDetActionSequence::hitCollectionName(), and sequence().
hitCreationMode()
int DD4hep::Simulation::Geant4Sensitive::hitCreationMode () const inline
Property access to the hit creation mode.
Definition at line 164 of file Geant4SensDetAction.h.
Referenced by DD4hep::Simulation::moveEntries().
isActive()
bool DD4hep::Simulation::Geant4Sensitive::isActive () const inline
G4VSensitiveDetector internals: Is the detector active?
Definition at line 184 of file Geant4SensDetAction.h.
mark() [1/2]
void Geant4Sensitive::mark (const G4Track * track) const
Mark the track to be kept for MC truth propagation during hit processing.
Definition at line 206 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), and DD4hep::Simulation::Geant4MonteCarloTruth::mark().
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process(), DD4hep::Simulation::TrackerWeighted::start(), and DD4hep::Simulation::TrackerCombine::start().
mark() [2/2]
void Geant4Sensitive::mark (const G4Step * step) const
Mark the track of this step to be kept for MC truth propagation during hit processing.
Definition at line 212 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), and DD4hep::Simulation::Geant4MonteCarloTruth::mark().
path()
std::string DD4hep::Simulation::Geant4Sensitive::path () const inline
G4VSensitiveDetector internals: Access to the detector path name.
Definition at line 174 of file Geant4SensDetAction.h.
process()
bool Geant4Sensitive::process (G4Step * step, G4TouchableHistory * history) virtual
G4VSensitiveDetector interface: Method for generating hit(s) using the information of G4Step object.
Method for generating hit(s) using the information of G4Step object.
Reimplemented in DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, DD4hep::Simulation::Test::Geant4TestSensitive, Tests::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, Tests::Geant4SensitiveAction< T >, DD4hep::Simulation::Geant4SensitiveAction< T >, and DD4hep::Simulation::Geant4EscapeCounter.
Definition at line 197 of file Geant4SensDetAction.cpp.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::process(), and DD4hep::Simulation::Geant4SensitiveAction< T >::process().
readoutGeometry()
G4VReadOutGeometry* DD4hep::Simulation::Geant4Sensitive::readoutGeometry () const inline
Access to the readout geometry of the sensitive detector.
Definition at line 194 of file Geant4SensDetAction.h.
sensitiveDetector()
SensitiveDetector DD4hep::Simulation::Geant4Sensitive::sensitiveDetector () const inline
Access the DD4hep sensitive detector.
Definition at line 189 of file Geant4SensDetAction.h.
Referenced by DD4hep::Simulation::moveEntries().
sequence()
Geant4SensDetActionSequence & Geant4Sensitive::sequence () const
Access to the hosting sequence.
Definition at line 165 of file Geant4SensDetAction.cpp.
References m_sequence.
Referenced by collection(), collectionByID(), and hitCollectionName().
setDetector()
void Geant4Sensitive::setDetector (Geant4ActionSD * sens_det)
Access to the sensitive detector object.
Definition at line 150 of file Geant4SensDetAction.cpp.
References m_sensitiveDetector.
Referenced by DD4hep::Simulation::Geant4SensDetActionSequence::defineCollection().
volumeID()
long long int Geant4Sensitive::volumeID (const G4Step * step)
Returns the volumeID of the sensitive volume corresponding to the step.
Combining the VolIDS of the complete geometry path (Geant4TouchableHistory) from the current sensitive volume to the world volume
Definition at line 218 of file Geant4SensDetAction.cpp.
References DD4hep::Simulation::Geant4Mapping::instance(), DD4hep::Simulation::Geant4StepHandler::preTouchable(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), and DD4hep::Simulation::Geant4Mapping::volumeManager().
Referenced by DD4hep::Simulation::Geant4EscapeCounter::process(), DD4hep::Simulation::TrackerWeighted::update(), and DD4hep::Simulation::TrackerCombine::update().
Member Data Documentation
m_detector
DetElement DD4hep::Simulation::Geant4Sensitive::m_detector protected
Reference to the detector element describing this sensitive element.
Definition at line 140 of file Geant4SensDetAction.h.
Referenced by Geant4Sensitive().
m_filters
Actors<Geant4Filter> DD4hep::Simulation::Geant4Sensitive::m_filters protected
The list of sensitive detector filter objects.
Definition at line 148 of file Geant4SensDetAction.h.
Referenced by accept(), adopt(), adopt_front(), and ~Geant4Sensitive().
m_hitCreationMode
int DD4hep::Simulation::Geant4Sensitive::m_hitCreationMode protected
Property: Hit creation mode. Maybe one of the enum HitCreationFlags.
Definition at line 136 of file Geant4SensDetAction.h.
Referenced by Geant4Sensitive().
m_lcdd
LCDD& DD4hep::Simulation::Geant4Sensitive::m_lcdd protected
Reference to the detector description object.
Definition at line 138 of file Geant4SensDetAction.h.
m_readout
Readout DD4hep::Simulation::Geant4Sensitive::m_readout protected
Reference to the readout structure.
Definition at line 144 of file Geant4SensDetAction.h.
Referenced by Geant4Sensitive().
m_segmentation
Segmentation DD4hep::Simulation::Geant4Sensitive::m_segmentation protected
Reference to segmentation.
Definition at line 146 of file Geant4SensDetAction.h.
Referenced by cellID(), and Geant4Sensitive().
m_sensitive
SensitiveDetector DD4hep::Simulation::Geant4Sensitive::m_sensitive protected
Reference to the sensitive detector element.
Definition at line 142 of file Geant4SensDetAction.h.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::declareReadoutFilteredCollection(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), and Geant4Sensitive().
m_sensitiveDetector
Geant4ActionSD* DD4hep::Simulation::Geant4Sensitive::m_sensitiveDetector private
Reference to G4 sensitive detector.
Definition at line 130 of file Geant4SensDetAction.h.
Referenced by detector(), and setDetector().
m_sequence
Geant4SensDetActionSequence* DD4hep::Simulation::Geant4Sensitive::m_sequence private
Reference to the containing action sequence.
Definition at line 132 of file Geant4SensDetAction.h.
Referenced by Geant4Sensitive(), and sequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensDetAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4SensDetAction.cpp