DD4hep: DD4hep::Geometry::Constant Class Reference
DD4hep::Geometry::Constant Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing a constant (define) object in lcdd.
#include <Objects.h>
Public Types
typedef ConstantObject Object
Definition of the implementation type.
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
Constant ()
Default constructor.
Constant (const Constant &e)
Constructorto be used for assignment from a handle.
template<typename Q >
Constant (const Handle< Q > &e)
Constructor to be used when reading the already parsed DOM tree.
Constant (const std::string &name)
Constructor to be used when creating a new DOM tree.
Constant (const std::string &name, const std::string &val, const std::string &typ="number")
Constructor to be used when creating a new DOM tree.
std::string dataType () const
Access the constant.
std::string toString () const
String representation of this object.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing a constant (define) object in lcdd.
Constant objects are parsed by the expression evaluator and are subsequently available for expression evaluation.
Author
M.Frank
Version
1.0
Definition at line 231 of file Objects.h.
Member Typedef Documentation
Object
typedef ConstantObject DD4hep::Geometry::Constant::Object
Definition of the implementation type.
Definition at line 234 of file Objects.h.
Constructor & Destructor Documentation
Constant() [1/5]
DD4hep::Geometry::Constant::Constant () inline
Default constructor.
Definition at line 236 of file Objects.h.
Constant() [2/5]
DD4hep::Geometry::Constant::Constant (const Constant & e) inline
Constructorto be used for assignment from a handle.
Definition at line 240 of file Objects.h.
Constant() [3/5]
template<typename Q > DD4hep::Geometry::Constant::Constant (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed DOM tree.
Definition at line 245 of file Objects.h.
References DD4hep::Handle< T >::name(), and DD4hep::Geometry::DetectorTools::toString().
Constant() [4/5]
Constant::Constant (const std::string & name)
Constructor to be used when creating a new DOM tree.
Definition at line 145 of file Objects.cpp.
Constant() [5/5]
Constant::Constant (const std::string & name, const std::string & val, const std::string & typ = "number")
Constructor to be used when creating a new DOM tree.
Definition at line 140 of file Objects.cpp.
Member Function Documentation
dataType()
string Constant::dataType () const
Access the constant.
Definition at line 150 of file Objects.cpp.
References DD4hep::Geometry::ConstantObject::dataType.
toString()
string Constant::toString () const
String representation of this object.
Definition at line 158 of file Objects.cpp.
References DD4hep::_toDouble().
Referenced by DD4hep::Printer< T >::operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Objects.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Objects.cpp