DD4hep: DD4hep: DD4hep::Simulation::Geant4StackingActionSequence Class Reference
DD4hep::Simulation::Geant4StackingActionSequence Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete implementation of the Geant4 stacking action sequence.
#include <Geant4StackingAction.h>
Public Member Functions
Geant4StackingActionSequence (Geant4Context *ctxt, const std::string &name)
Standard constructor.
virtual ~Geant4StackingActionSequence ()
Default destructor.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
Geant4StackingAction * get (const std::string &name) const
Get an action by name.
template<typename T >
void callAtNewStage (T *p, void(T::*f)())
Register begin-of-event callback. Types Q and T must be polymorph!
template<typename T >
void callAtPrepare (T *p, void(T::*f)())
Register end-of-event callback. Types Q and T must be polymorph!
void adopt (Geant4StackingAction *action)
Add an actor responding to all callbacks. Sequence takes ownership.
virtual void newStage ()
New-stage callback.
virtual void prepare ()
Preparation callback.
Protected Attributes
CallbackSequence m_newStage
Callback sequence for the newStage call.
CallbackSequence m_prepare
Actors< Geant4StackingAction > m_actors
The list of action objects to be called.
Detailed Description
Concrete implementation of the Geant4 stacking action sequence.
The sequence dispatches the callbacks for each stepping action to all registered Geant4StackingAction members and all registered callbacks.
Note Multi-Threading issue: Neither callbacks not the action list is protected against multiple threads calling the Geant4 callbacks! These must be protected in the user actions themselves.
Author:
M.Frank
Version:
1.0
Definition at line 100 of file Geant4StackingAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4StackingActionSequence::Geant4StackingActionSequence (Geant4Context * ctxt, const std::string & name)
Standard constructor.
Geant4StackingActionSequence::~Geant4StackingActionSequence () [virtual]
Default destructor.
Definition at line 99 of file Geant4StackingAction.cpp.
References DD4hep::CallbackSequence::clear(), DD4hep::InstanceCount::decrement(), m_actors, m_newStage, m_prepare, and DD4hep::Simulation::Geant4Action::release().
Member Function Documentation
void Geant4StackingActionSequence::adopt (Geant4StackingAction * action)
Add an actor responding to all callbacks. Sequence takes ownership.
Definition at line 108 of file Geant4StackingAction.cpp.
References DD4hep::Simulation::Geant4Action::addRef(), and m_actors.
Referenced by DD4hep::Converter< T, ARG >::operator()().
template<typename T > void DD4hep::Simulation::Geant4StackingActionSequence::callAtNewStage (T * p, void(T::*)() f) [inline]
Register begin-of-event callback. Types Q and T must be polymorph!
Definition at line 120 of file Geant4StackingAction.h.
References DD4hep::CallbackSequence::add(), and m_newStage.
Referenced by DD4hep::Converter< T, ARG >::operator()().
template<typename T > void DD4hep::Simulation::Geant4StackingActionSequence::callAtPrepare (T * p, void(T::*)() f) [inline]
Register end-of-event callback. Types Q and T must be polymorph!
Definition at line 124 of file Geant4StackingAction.h.
References DD4hep::CallbackSequence::add(), and m_prepare.
Referenced by DD4hep::Converter< T, ARG >::operator()().
void Geant4StackingActionSequence::configureFiber (Geant4Context * thread_context) [virtual]
Set or update client for the use in a new thread fiber.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 124 of file Geant4StackingAction.cpp.
References DD4hep::Simulation::Geant4Action::configureFiber(), and m_actors.
Geant4StackingAction* DD4hep::Simulation::Geant4StackingActionSequence::get (const std::string & name) const
Get an action by name.
void Geant4StackingActionSequence::newStage () [virtual]
New-stage callback.
Pre-track action callback.
Definition at line 134 of file Geant4StackingAction.cpp.
References m_actors, m_newStage, and DD4hep::Simulation::Geant4StackingAction::newStage().
Referenced by DD4hep::Simulation::Geant4UserStackingAction::NewStage().
void Geant4StackingActionSequence::prepare () [virtual]
Preparation callback.
Post-track action callback.
Definition at line 140 of file Geant4StackingAction.cpp.
References m_actors, m_prepare, and DD4hep::Simulation::Geant4StackingAction::prepare().
Referenced by DD4hep::Simulation::Geant4UserStackingAction::PrepareNewEvent().
void Geant4StackingActionSequence::updateContext (Geant4Context * ctxt) [virtual]
Set or update client context.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 118 of file Geant4StackingAction.cpp.
References m_actors, and DD4hep::Simulation::Geant4Action::m_context.
Member Data Documentation
Actors<Geant4StackingAction> DD4hep::Simulation::Geant4StackingActionSequence::m_actors [protected]
The list of action objects to be called.
Definition at line 107 of file Geant4StackingAction.h.
Referenced by adopt(), configureFiber(), newStage(), prepare(), updateContext(), and ~Geant4StackingActionSequence().
CallbackSequence DD4hep::Simulation::Geant4StackingActionSequence::m_newStage [protected]
Callback sequence for the newStage call.
Definition at line 103 of file Geant4StackingAction.h.
Referenced by callAtNewStage(), newStage(), and ~Geant4StackingActionSequence().
CallbackSequence DD4hep::Simulation::Geant4StackingActionSequence::m_prepare [protected]
Definition at line 105 of file Geant4StackingAction.h.
Referenced by callAtPrepare(), prepare(), and ~Geant4StackingActionSequence().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4StackingAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4StackingAction.cpp