DD4hep: DD4hep::Property Class Reference
DD4hep::Property Class Reference
DD4hep::Simulation components, classes and objects
The property class to assign options to actions.
#include <ComponentProperties.h>
Public Member Functions
Property ()
Default constructor.
Property (const Property &p)
Copy constructor.
template<typename TYPE >
Property (TYPE &val)
User constructor.
std::string type () const
Property type name.
void * ptr () const
Access void data pointer.
const PropertyGrammar & grammar () const
Access grammar object.
std::string str () const
Conversion to string value.
Property & str (const std::string &input)
Conversion from string value.
Property & operator= (const Property &p)
Assignment operator.
Property & operator= (const char *val)
Assignment operator / set new balue.
template<typename TYPE >
Property & operator= (const TYPE &val)
Assignment operator / set new balue.
template<typename TYPE >
TYPE value () const
Retrieve value.
template<typename TYPE >
void value (TYPE &value) const
Retrieve value from stack (large values e.g. vectors etc.)
template<typename TYPE >
void set (const TYPE &value)
Set value of this property.
Static Public Member Functions
static std::string type (const Property &proptery)
Property type name.
static std::string type (const std::type_info &proptery)
Property type name.
Protected Member Functions
template<typename TYPE >
void make (TYPE &value)
Setup property.
Protected Attributes
void * m_par
Pointer to the data location.
const PropertyGrammar * m_hdl
Detailed Description
The property class to assign options to actions.
Standard implementation of a property mechanism. The data conversion mechanism between various properties uses internally boost::spirit to allow also conversions between types, which are initially unrelated such as e.g. vector<int> and list<short>.
Author
M.Frank
Version
1.0
Definition at line 86 of file ComponentProperties.h.
Constructor & Destructor Documentation
Property() [1/3]
Property::Property ()
Default constructor.
Definition at line 62 of file ComponentProperties.cpp.
Property() [2/3]
Property::Property (const Property & p)
Copy constructor.
Definition at line 67 of file ComponentProperties.cpp.
Property() [3/3]
template<typename TYPE > DD4hep::Property::Property (TYPE & val) inline
User constructor.
Definition at line 100 of file ComponentProperties.h.
Member Function Documentation
grammar()
const PropertyGrammar & Property::grammar () const
Access grammar object.
Definition at line 95 of file ComponentProperties.cpp.
References m_hdl.
Referenced by DD4hep::PropertyValue< TYPE >::grammar(), set(), DD4hep::PropertyManager::set(), type(), and value().
make()
template<typename TYPE > void DD4hep::Property::make (TYPE & value) protected
Setup property.
Definition at line 32 of file ComponentProperties_inl.h.
References dd4hep::g, m_hdl, and m_par.
Referenced by DD4hep::Utils::toStream().
operator=() [1/3]
Property & Property::operator= (const Property & p)
Assignment operator.
Definition at line 72 of file ComponentProperties.cpp.
References m_hdl, and m_par.
operator=() [2/3]
Property & Property::operator= (const char * val)
Assignment operator / set new balue.
Assignment operator / set new balue
Definition at line 125 of file ComponentProperties.cpp.
operator=() [3/3]
template<typename TYPE > Property & DD4hep::Property::operator= (const TYPE & val)
Assignment operator / set new balue.
Assignment operator / set new balue
Definition at line 48 of file ComponentProperties_inl.h.
ptr()
void* DD4hep::Property::ptr () const inline
Access void data pointer.
Definition at line 111 of file ComponentProperties.h.
Referenced by DD4hep::PropertyManager::set().
set()
template<typename TYPE > void DD4hep::Property::set (const TYPE & value)
Set value of this property.
Definition at line 39 of file ComponentProperties_inl.h.
References DD4hep::PropertyGrammar::fromString(), dd4hep::g, grammar(), DD4hep::PropertyGrammar::invalidConversion(), m_par, and DD4hep::PropertyGrammar::type().
Referenced by DD4hep::Simulation::Geant4Exec::configure(), DD4hep::PropertyValue< TYPE >::set(), and DD4hep::Utils::toStream().
str() [1/2]
string Property::str () const
Conversion to string value.
Definition at line 102 of file ComponentProperties.cpp.
References m_hdl, m_par, and DD4hep::PropertyGrammar::str().
Referenced by DD4hep::PropertyManager::dump(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::Parsers::parse(), DD4hep::Simulation::Geant4UIMessenger::SetNewValue(), DD4hep::PropertyValue< TYPE >::str(), DD4hep::Utils::toStream(), and value().
str() [2/2]
Property & Property::str (const std::string & input)
Conversion from string value.
Definition at line 110 of file ComponentProperties.cpp.
References DD4hep::PropertyGrammar::fromString(), m_hdl, and m_par.
type() [1/3]
string Property::type (const Property & proptery) static
Property type name.
Definition at line 81 of file ComponentProperties.cpp.
References grammar(), DD4hep::PropertyGrammar::type(), type(), and DD4hep::typeName().
type() [2/3]
static std::string DD4hep::Property::type (const std::type_info & proptery) static
Property type name.
type() [3/3]
string Property::type () const
Property type name.
Definition at line 91 of file ComponentProperties.cpp.
References grammar().
Referenced by type().
value() [1/2]
template<typename TYPE > TYPE DD4hep::Property::value () const
Retrieve value.
Definition at line 63 of file ComponentProperties_inl.h.
Referenced by DD4hep::Simulation::Geant4Exec::run(), DD4hep::Simulation::Geant4UIManager::start(), DD4hep::Utils::toStream(), and DD4hep::PropertyValue< TYPE >::value().
value() [2/2]
template<typename TYPE > void DD4hep::Property::value (TYPE & value) const
Retrieve value from stack (large values e.g. vectors etc.)
Definition at line 54 of file ComponentProperties_inl.h.
References dd4hep::g, grammar(), DD4hep::PropertyGrammar::invalidConversion(), m_par, str(), and DD4hep::PropertyGrammar::type().
Member Data Documentation
m_hdl
const PropertyGrammar* DD4hep::Property::m_hdl protected
Definition at line 90 of file ComponentProperties.h.
Referenced by grammar(), make(), operator=(), and str().
m_par
void* DD4hep::Property::m_par protected
Pointer to the data location.
Definition at line 89 of file ComponentProperties.h.
Referenced by make(), operator=(), set(), str(), and value().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ComponentProperties.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ComponentProperties.cpp
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ComponentProperties_inl.h