DD4hep: DD4hep::OpaqueDataBlock Class Reference
DD4hep::OpaqueDataBlock Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Class describing an opaque conditions data block.
#include <OpaqueData.h>
Public Member Functions
OpaqueDataBlock ()
Standard initializing constructor.
OpaqueDataBlock (const OpaqueDataBlock &data)
Copy constructor.
~OpaqueDataBlock ()
Standard Destructor.
OpaqueDataBlock & operator= (const OpaqueDataBlock &clone)
Assignment operator.
bool move (OpaqueDataBlock &from)
Move the data content: 'from' will be reset to NULL.
bool bind (const BasicGrammar *grammar, void(*ctor)(void *, const void *), void(*dtor)(void *))
Bind data value.
template<typename T >
T & bind ()
Bind data value.
void assign (const void *ptr, const std::type_info &typ)
Set data value.
template<typename T >
T & set (const std::string &value)
Bind grammar and assign value.
Public Member Functions inherited from DD4hep::OpaqueData
bool fromString (const std::string &rep)
Create data block from string representation.
std::string str () const
Create string representation of the data block.
const std::type_info & typeInfo () const
Access type id of the condition.
const std::string & dataType () const
Access type name of the condition data block.
bool is_bound () const
Check if object is already bound....
template<typename T >
T & get ()
Generic getter. Specify the exact type, not a polymorph type.
template<typename T >
const T & get () const
Generic getter (const version). Specify the exact type, not a polymorph type.
Public Attributes
unsigned int type
Data buffer type: Must be a bitmap!
Public Attributes inherited from DD4hep::OpaqueData
const BasicGrammar * grammar
Data type.
Private Types
enum { PLAIN_DATA = 1<<0, ALLOC_DATA = 1<<1, BOUND_DATA = 1<<2 }
Private Attributes
enum DD4hep::OpaqueDataBlock:: { ... } _DataTypes
unsigned char data [sizeof(std::vector< void *>)]
Data buffer: plain data are allocated directly on this buffer.
void(* destruct)(void *)
Destructor function – only set if the object is valid.
void(* copy)(void *, const void *)
Constructor function – only set if the object is valid.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::OpaqueData
OpaqueData ()
Standard initializing constructor.
virtual ~OpaqueData ()
Standard Destructor.
OpaqueData (const OpaqueData &c)
Copy constructor.
OpaqueData & operator= (const OpaqueData &c)
Assignment operator.
Protected Attributes inherited from DD4hep::OpaqueData
void * pointer
Pointer to object data.
Detailed Description
Class describing an opaque conditions data block.
Author
M.Frank
Version
1.0
Definition at line 81 of file OpaqueData.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
PLAIN_DATA
ALLOC_DATA
BOUND_DATA
Definition at line 83 of file OpaqueData.h.
Constructor & Destructor Documentation
OpaqueDataBlock() [1/2]
OpaqueDataBlock::OpaqueDataBlock ()
Standard initializing constructor.
Definition at line 82 of file OpaqueData.cpp.
References DD4hep::InstanceCount::increment().
OpaqueDataBlock() [2/2]
OpaqueDataBlock::OpaqueDataBlock (const OpaqueDataBlock & data)
Copy constructor.
Definition at line 87 of file OpaqueData.cpp.
References bind(), copy, destruct, DD4hep::OpaqueData::grammar, DD4hep::InstanceCount::increment(), and DD4hep::OpaqueData::pointer.
~OpaqueDataBlock()
OpaqueDataBlock::~OpaqueDataBlock ()
Standard Destructor.
Definition at line 97 of file OpaqueData.cpp.
References ALLOC_DATA, DD4hep::InstanceCount::decrement(), destruct, DD4hep::OpaqueData::grammar, DD4hep::OpaqueData::pointer, and type.
Member Function Documentation
assign()
void OpaqueDataBlock::assign (const void * ptr, const std::type_info & typ)
Set data value.
Definition at line 172 of file OpaqueData.cpp.
References DD4hep::except(), DD4hep::OpaqueData::grammar, DD4hep::OpaqueData::pointer, and DD4hep::BasicGrammar::type().
bind() [1/2]
bool OpaqueDataBlock::bind (const BasicGrammar * grammar, void(*)(void *, const void *) ctor, void(*)(void *) dtor)
Bind data value.
Set data value.
Definition at line 151 of file OpaqueData.cpp.
References ALLOC_DATA, copy, data, destruct, DD4hep::except(), dd4hep::g, DD4hep::OpaqueData::grammar, PLAIN_DATA, DD4hep::OpaqueData::pointer, DD4hep::BasicGrammar::sizeOf(), DD4hep::BasicGrammar::type(), type, and DD4hep::typeinfoCheck().
bind() [2/2]
template<typename T > T & DD4hep::OpaqueDataBlock::bind ()
Bind data value.
Definition at line 51 of file OpaqueData_inl.h.
References DD4hep::OpaqueData::pointer.
Referenced by OpaqueDataBlock(), and operator=().
move()
bool OpaqueDataBlock::move (OpaqueDataBlock & from)
Move the data content: 'from' will be reset to NULL.
Definition at line 108 of file OpaqueData.cpp.
References copy, data, destruct, DD4hep::OpaqueData::grammar, PLAIN_DATA, DD4hep::OpaqueData::pointer, and type.
operator=()
OpaqueDataBlock & OpaqueDataBlock::operator= (const OpaqueDataBlock & clone)
Assignment operator.
Copy constructor.
Definition at line 125 of file OpaqueData.cpp.
References ALLOC_DATA, bind(), copy, destruct, DD4hep::except(), DD4hep::OpaqueData::grammar, DD4hep::OpaqueData::operator=(), DD4hep::OpaqueData::pointer, and type.
set()
template<typename T > T & DD4hep::OpaqueDataBlock::set (const std::string & value)
Bind grammar and assign value.
Definition at line 56 of file OpaqueData_inl.h.
References DD4hep::OpaqueData::fromString(), and DD4hep::typeName().
Referenced by DD4hep::Conditions::Condition::bind().
Member Data Documentation
_DataTypes
enum { ... } DD4hep::OpaqueDataBlock::_DataTypes
copy
void(* DD4hep::OpaqueDataBlock::copy) (void *, const void *) private
Constructor function – only set if the object is valid.
Definition at line 94 of file OpaqueData.h.
Referenced by bind(), move(), OpaqueDataBlock(), and operator=().
data
unsigned char DD4hep::OpaqueDataBlock::data[sizeof(std::vector< void * >)] private
Data buffer: plain data are allocated directly on this buffer.
Internal data buffer is sufficient to store any vector
Definition at line 90 of file OpaqueData.h.
Referenced by bind(), and move().
destruct
void(* DD4hep::OpaqueDataBlock::destruct) (void *) private
Destructor function – only set if the object is valid.
Definition at line 92 of file OpaqueData.h.
Referenced by bind(), move(), OpaqueDataBlock(), operator=(), and ~OpaqueDataBlock().
type
unsigned int DD4hep::OpaqueDataBlock::type
Data buffer type: Must be a bitmap!
Definition at line 98 of file OpaqueData.h.
Referenced by bind(), DD4hep::Conditions::Condition::dataType(), move(), operator=(), and ~OpaqueDataBlock().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/OpaqueData.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/OpaqueData.cpp
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/objects/OpaqueData_inl.h