DD4hep: DD4hep: DD4hep::Simulation::Geant4GeneratorWrapper Class Reference
DD4hep::Simulation::Geant4GeneratorWrapper Class Reference
[DD4hep::Simulation components, classes and objects]
Geant4Action to merge several independent interaction to one.
#include <Geant4GeneratorWrapper.h>
Public Member Functions
Geant4GeneratorWrapper (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4GeneratorWrapper ()
Default destructor.
G4VPrimaryGenerator * generator ()
Access the G4VPrimaryGenerator instance.
virtual void operator() (G4Event *event)
Event generation action callback.
Protected Attributes
std::string m_generatorType
Property: Type name of the implementation instance. name: "Uses".
int m_mask
Property: interaction identifier mask. name: "Mask".
G4VPrimaryGenerator * m_generator
Reference to the implementation instance.
Detailed Description
Geant4Action to merge several independent interaction to one.
Wrap native G4 particle ganerators like the generic particle source etc.
Author:
M.Frank
Version:
1.0
Definition at line 37 of file Geant4GeneratorWrapper.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4GeneratorWrapper::Geant4GeneratorWrapper (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4GeneratorWrapper::~Geant4GeneratorWrapper () [virtual]
Default destructor.
Definition at line 48 of file Geant4GeneratorWrapper.cpp.
References DD4hep::InstanceCount::decrement(), DD4hep::deletePtr(), and m_generator.
Member Function Documentation
G4VPrimaryGenerator * Geant4GeneratorWrapper::generator ()
Access the G4VPrimaryGenerator instance.
Definition at line 53 of file Geant4GeneratorWrapper.cpp.
References m_generator, and m_generatorType.
Referenced by operator()().
void Geant4GeneratorWrapper::operator() (G4Event * event) [virtual]
Event generation action callback.
Collect all existing interactions (primary vertices)
Add all the missing interactions (primary vertices) to the primary event record.
Reimplemented from DD4hep::Simulation::Geant4GeneratorAction.
Definition at line 69 of file Geant4GeneratorWrapper.cpp.
References DD4hep::Simulation::Geant4PrimaryEvent::add(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::createPrimary(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), generator(), m_mask, and v.
Member Data Documentation
G4VPrimaryGenerator* DD4hep::Simulation::Geant4GeneratorWrapper::m_generator [protected]
Reference to the implementation instance.
Definition at line 45 of file Geant4GeneratorWrapper.h.
Referenced by generator(), and ~Geant4GeneratorWrapper().
std::string DD4hep::Simulation::Geant4GeneratorWrapper::m_generatorType [protected]
Property: Type name of the implementation instance. name: "Uses".
Definition at line 40 of file Geant4GeneratorWrapper.h.
Referenced by generator().
int DD4hep::Simulation::Geant4GeneratorWrapper::m_mask [protected]
Property: interaction identifier mask. name: "Mask".
Definition at line 42 of file Geant4GeneratorWrapper.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4GeneratorWrapper.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4GeneratorWrapper.cpp