DD4hep: DD4hep::XML::Tag_t Class Reference
DD4hep::XML::Tag_t Class Reference
DD4hep::XML classes and objects
Class to support both way translation between C++ and XML strings.
#include <XMLElements.h>
Public Member Functions
Tag_t (const char *s)
Constructor from normal ASCII string.
Tag_t (const XmlChar *s)
Constructor from unicode string.
Tag_t (const Strng_t &s)
Constructor from internal XML string.
Tag_t (const std::string &s)
Constructor from STL string.
Tag_t (const std::string &v, const std::string &s, void(*register_func)(const std::string &, Tag_t *))
Tag_t (const Tag_t &c)
Copy constructor.
~Tag_t ()
Destructor.
Tag_t & operator= (const char *s)
Assignment of a normal ASCII string.
Tag_t & operator= (const Tag_t &s)
Assignment of a tag object.
Tag_t & operator= (const Strng_t &s)
Assignment of a internal Xml string.
Tag_t & operator= (const std::string &s)
Assignment of a STL string.
operator const std::string & () const
Automatic conversion to STL string.
const std::string & str () const
Access writable STL string.
const char * c_str () const
Access data buffer of STL string.
Public Member Functions inherited from DD4hep::XML::Strng_t
Strng_t (const XmlChar *c)
Initializing constructor from unicode string.
Strng_t & operator= (const XmlChar *s)
Assignment opertor from unicode string.
Strng_t (const char *c)
Initializing constructor from ascii string.
Strng_t (const std::string &c)
Initializing constructor from STL string.
Strng_t (const Strng_t &c)
Copy constructor.
~Strng_t ()
Default destructor - release unicode string.
operator const XmlChar * () const
Auto-conversion to unicode string.
const XmlChar * ptr () const
Accessor to unicode string.
size_t length () const
String length in native representation.
Strng_t & operator= (const char *s)
Assignment opertor from ascii string.
Strng_t & operator= (const Strng_t &s)
Assignment opertor from helper string.
Strng_t & operator= (const std::string &s)
Assignment opertor from STL string.
Public Attributes
std::string m_str
STL string buffer.
Public Attributes inherited from DD4hep::XML::Strng_t
XmlChar * m_xml
Pointer to unicode string.
Detailed Description
Class to support both way translation between C++ and XML strings.
Helper class to easily convert between – unicode – std::string – const char*. Internally a copy representation as an std::string is kept.
Author
M.Frank
Version
1.0
Definition at line 244 of file XMLElements.h.
Constructor & Destructor Documentation
Tag_t() [1/6]
DD4hep::XML::Tag_t::Tag_t (const char * s) inline
Constructor from normal ASCII string.
Definition at line 250 of file XMLElements.h.
Tag_t() [2/6]
DD4hep::XML::Tag_t::Tag_t (const XmlChar * s) inline
Constructor from unicode string.
Definition at line 255 of file XMLElements.h.
Tag_t() [3/6]
DD4hep::XML::Tag_t::Tag_t (const Strng_t & s) inline
Constructor from internal XML string.
Definition at line 259 of file XMLElements.h.
Tag_t() [4/6]
DD4hep::XML::Tag_t::Tag_t (const std::string & s) inline
Constructor from STL string.
Definition at line 263 of file XMLElements.h.
Tag_t() [5/6]
DD4hep::XML::Tag_t::Tag_t (const std::string & v, const std::string & s, void(*)(const std::string &, Tag_t *) register_func) inline
Constructor from STL string with registration. ONLY to be used for static global entries to protect against duplicated static memory.
Definition at line 268 of file XMLElements.h.
Tag_t() [6/6]
DD4hep::XML::Tag_t::Tag_t (const Tag_t & c) inline
Copy constructor.
Definition at line 273 of file XMLElements.h.
~Tag_t()
DD4hep::XML::Tag_t::~Tag_t () inline
Destructor.
Definition at line 277 of file XMLElements.h.
Member Function Documentation
c_str()
const char* DD4hep::XML::Tag_t::c_str () const inline
Access data buffer of STL string.
Definition at line 298 of file XMLElements.h.
References DD4hep::XML::operator+().
operator const std::string &()
DD4hep::XML::Tag_t::operator const std::string & () const inline
Automatic conversion to STL string.
Definition at line 290 of file XMLElements.h.
operator=() [1/4]
Tag_t & Tag_t::operator= (const char * s)
Assignment of a normal ASCII string.
Definition at line 520 of file XMLElements.cpp.
References s.
operator=() [2/4]
Tag_t & Tag_t::operator= (const Tag_t & s)
Assignment of a tag object.
Definition at line 510 of file XMLElements.cpp.
References m_str.
operator=() [3/4]
Tag_t & Tag_t::operator= (const Strng_t & s)
Assignment of a internal Xml string.
Definition at line 534 of file XMLElements.cpp.
References DD4hep::XML::Strng_t::m_xml, and dd4hep::ns.
operator=() [4/4]
Tag_t & Tag_t::operator= (const std::string & s)
Assignment of a STL string.
Definition at line 547 of file XMLElements.cpp.
References s.
str()
const std::string& DD4hep::XML::Tag_t::str () const inline
Access writable STL string.
Definition at line 294 of file XMLElements.h.
Referenced by DD4hep::XML::NodeList::next(), DD4hep::XML::operator+(), and DD4hep::XML::NodeList::previous().
Member Data Documentation
m_str
std::string DD4hep::XML::Tag_t::m_str
STL string buffer.
Definition at line 247 of file XMLElements.h.
Referenced by operator=(), and DD4hep::XML::operator==().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp