DD4hep: DD4hep::Conditions::AbstractMap Class Reference
DD4hep::Conditions::AbstractMap Class Reference
Conditions data block. Internally maps other objects to abstract data blocks.
#include <ConditionsData.h>
Public Types
enum { REGULAR = 0, ALIGNMENT = 6 }
typedef std::map< std::string, OpaqueDataBlock > Params
Public Member Functions
AbstractMap ()
Default constructor.
AbstractMap (const AbstractMap &c)
Copy constructor.
virtual ~AbstractMap ()
Default destructor.
AbstractMap & operator= (const AbstractMap &c)
Assignment operator.
template<typename T >
T * option () const
Simplify access to client data.
const Params::value_type & firstParam () const
Simplify access to first item of the parameter list (const access)
Params::value_type & firstParam ()
Simplify access to first item of the parameter list.
template<typename T >
const T & first () const
Simplify access to first item of the parameter list (const access)
template<typename T >
T & first ()
Simplify access to first item of the parameter list.
template<typename T >
const T & operator[] (const std::string &item) const
Simplify access to mapped item of the parameter list (const access)
template<typename T >
T & operator[] (const std::string &item)
Simplify access to mapped item of the parameter list.
Public Attributes
ClientData * clientData
Params params
int classID
Detailed Description
Conditions data block. Internally maps other objects to abstract data blocks.
Author
M.Frank
Version
1.0
Date
31/03/2016
Definition at line 50 of file ConditionsData.h.
Member Typedef Documentation
Params
typedef std::map<std::string, OpaqueDataBlock> DD4hep::Conditions::AbstractMap::Params
Definition at line 57 of file ConditionsData.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
REGULAR
ALIGNMENT
Definition at line 53 of file ConditionsData.h.
Constructor & Destructor Documentation
AbstractMap() [1/2]
AbstractMap::AbstractMap ()
Default constructor.
Definition at line 52 of file ConditionsData.cpp.
References DD4hep::InstanceCount::increment().
AbstractMap() [2/2]
AbstractMap::AbstractMap (const AbstractMap & c)
Copy constructor.
Definition at line 45 of file ConditionsData.cpp.
References DD4hep::InstanceCount::increment().
~AbstractMap()
AbstractMap::~AbstractMap () virtual
Default destructor.
Definition at line 57 of file ConditionsData.cpp.
References clientData, DD4hep::InstanceCount::decrement(), and DD4hep::Conditions::ClientData::release().
Member Function Documentation
first() [1/2]
template<typename T > const T& DD4hep::Conditions::AbstractMap::first () const inline
Simplify access to first item of the parameter list (const access)
Definition at line 86 of file ConditionsData.h.
first() [2/2]
template<typename T > T& DD4hep::Conditions::AbstractMap::first () inline
Simplify access to first item of the parameter list.
Definition at line 92 of file ConditionsData.h.
firstParam() [1/2]
const Params::value_type& DD4hep::Conditions::AbstractMap::firstParam () const inline
Simplify access to first item of the parameter list (const access)
Definition at line 74 of file ConditionsData.h.
firstParam() [2/2]
Params::value_type& DD4hep::Conditions::AbstractMap::firstParam () inline
Simplify access to first item of the parameter list.
Definition at line 80 of file ConditionsData.h.
operator=()
AbstractMap & AbstractMap::operator= (const AbstractMap & c)
Assignment operator.
Definition at line 64 of file ConditionsData.cpp.
References classID, clientData, DD4HEP_DEFINE_CONDITIONS_TYPE_DUMMY, DD4HEP_DEFINE_PARSER_GRAMMAR, and params.
operator[]() [1/2]
template<typename T > const T& DD4hep::Conditions::AbstractMap::operator[] (const std::string & item) const inline
Simplify access to mapped item of the parameter list (const access)
Definition at line 98 of file ConditionsData.h.
operator[]() [2/2]
template<typename T > T& DD4hep::Conditions::AbstractMap::operator[] (const std::string & item) inline
Simplify access to mapped item of the parameter list.
Definition at line 104 of file ConditionsData.h.
option()
template<typename T > T* DD4hep::Conditions::AbstractMap::option () const inline
Simplify access to client data.
Definition at line 70 of file ConditionsData.h.
Member Data Documentation
classID
int DD4hep::Conditions::AbstractMap::classID
Definition at line 60 of file ConditionsData.h.
Referenced by operator<<(), and operator=().
clientData
ClientData* DD4hep::Conditions::AbstractMap::clientData
Definition at line 58 of file ConditionsData.h.
Referenced by operator=(), and ~AbstractMap().
params
Params DD4hep::Conditions::AbstractMap::params
Definition at line 59 of file ConditionsData.h.
Referenced by operator<<(), and operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ConditionsData.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ConditionsData.cpp