DD4hep: DD4hep::Simulation::Geant4OutputAction Class Reference
DD4hep::Simulation::Geant4OutputAction Class Reference
DD4hep::Simulation components, classes and objects
Base class to output Geant4 event data to persistent media.
#include <Geant4OutputAction.h>
Classes
class OutputContext
Helper class for thread savety.
Public Member Functions
Geant4OutputAction (Geant4Context *c, const std::string &nam)
Standard constructor.
virtual ~Geant4OutputAction ()
Default destructor.
virtual void configureFiber (Geant4Context *ctxt)
Set or update client for the use in a new thread fiber.
virtual void begin (const G4Event *event)
begin-of-event callback
virtual void end (const G4Event *event)
End-of-event callback.
virtual void beginRun (const G4Run *run)
Callback to initialize storing the Geant4 information.
virtual void endRun (const G4Run *run)
Callback to store the Geant4 run information.
virtual void saveRun (const G4Run *run)
Callback to store the Geant4 event.
virtual void saveEvent (OutputContext< G4Event > &ctxt)
Callback to store the Geant4 event.
virtual void saveCollection (OutputContext< G4Event > &ctxt, G4VHitsCollection *collection)
Callback to store each Geant4 hit collection.
virtual void commit (OutputContext< G4Event > &ctxt)
Commit data at end of filling procedure.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventAction
Geant4EventAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4EventAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
std::string m_output
Property: "Output" output destination.
bool m_errorFatal
Property: "HandleErrorsAsFatal" Handle errors as fatal and rethrow eventual exceptions.
Geant4ParticleMap * m_truth
Reference to MC truth object.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4EventAction
typedef Geant4SharedEventAction shared_type
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
Base class to output Geant4 event data to persistent media.
Author
M.Frank
Version
1.0
Definition at line 41 of file Geant4OutputAction.h.
Constructor & Destructor Documentation
Geant4OutputAction()
Geant4OutputAction::Geant4OutputAction (Geant4Context * c, const std::string & nam)
Standard constructor.
Definition at line 31 of file Geant4OutputAction.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_errorFatal, m_output, and DD4hep::Simulation::Geant4Context::runAction().
~Geant4OutputAction()
Geant4OutputAction::~Geant4OutputAction () virtual
Default destructor.
Definition at line 42 of file Geant4OutputAction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
begin()
void Geant4OutputAction::begin (const G4Event * event) virtual
begin-of-event callback
Reimplemented from DD4hep::Simulation::Geant4EventAction.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO.
Definition at line 54 of file Geant4OutputAction.cpp.
beginRun()
void Geant4OutputAction::beginRun (const G4Run * run) virtual
Callback to initialize storing the Geant4 information.
Callback to initialize the storing of the Geant4 information.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO, and DD4hep::Simulation::Geant4Output2ROOT.
Definition at line 111 of file Geant4OutputAction.cpp.
Referenced by DD4hep::Simulation::Geant4Output2ROOT::beginRun(), and configureFiber().
commit()
void Geant4OutputAction::commit (OutputContext< G4Event > & ctxt) virtual
Commit data at end of filling procedure.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO, and DD4hep::Simulation::Geant4Output2ROOT.
Definition at line 107 of file Geant4OutputAction.cpp.
Referenced by DD4hep::Simulation::Geant4Output2ROOT::commit(), and end().
configureFiber()
void Geant4OutputAction::configureFiber (Geant4Context * ctxt) virtual
Set or update client for the use in a new thread fiber.
Set or update client for the use in a new thread fiber with seperate action sequences.
Reimplemented from DD4hep::Simulation::Geant4Action.
Definition at line 47 of file Geant4OutputAction.cpp.
References beginRun(), DD4hep::Simulation::Geant4RunActionSequence::callAtBegin(), DD4hep::Simulation::Geant4RunActionSequence::callAtEnd(), DD4hep::Simulation::Geant4Action::configureFiber(), endRun(), and DD4hep::Simulation::Geant4Context::runAction().
end()
void Geant4OutputAction::end (const G4Event * event) virtual
End-of-event callback.
Reimplemented from DD4hep::Simulation::Geant4EventAction.
Definition at line 58 of file Geant4OutputAction.cpp.
References commit(), DD4hep::Simulation::Geant4Action::context(), e, DD4hep::ERROR, DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4ParticleMap::isValid(), m_errorFatal, m_truth, DD4hep::Simulation::Geant4Action::name(), DD4hep::printout(), saveCollection(), saveEvent(), and DD4hep::WARNING.
endRun()
void Geant4OutputAction::endRun (const G4Run * run) virtual
Callback to store the Geant4 run information.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO.
Definition at line 115 of file Geant4OutputAction.cpp.
Referenced by configureFiber().
saveCollection()
void Geant4OutputAction::saveCollection (OutputContext< G4Event > & ctxt, G4VHitsCollection * collection) virtual
Callback to store each Geant4 hit collection.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO, and DD4hep::Simulation::Geant4Output2ROOT.
Definition at line 127 of file Geant4OutputAction.cpp.
Referenced by end().
saveEvent()
void Geant4OutputAction::saveEvent (OutputContext< G4Event > & ctxt) virtual
Callback to store the Geant4 event.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO, and DD4hep::Simulation::Geant4Output2ROOT.
Definition at line 123 of file Geant4OutputAction.cpp.
Referenced by end().
saveRun()
void Geant4OutputAction::saveRun (const G4Run * run) virtual
Callback to store the Geant4 event.
Callback to store the Geant4 run information.
Reimplemented in DD4hep::Simulation::Geant4Output2LCIO.
Definition at line 119 of file Geant4OutputAction.cpp.
Member Data Documentation
m_errorFatal
bool DD4hep::Simulation::Geant4OutputAction::m_errorFatal protected
Property: "HandleErrorsAsFatal" Handle errors as fatal and rethrow eventual exceptions.
Definition at line 59 of file Geant4OutputAction.h.
Referenced by end(), and Geant4OutputAction().
m_output
std::string DD4hep::Simulation::Geant4OutputAction::m_output protected
Property: "Output" output destination.
Definition at line 57 of file Geant4OutputAction.h.
Referenced by DD4hep::Simulation::Geant4Output2ROOT::beginRun(), and Geant4OutputAction().
m_truth
Geant4ParticleMap* DD4hep::Simulation::Geant4OutputAction::m_truth protected
Reference to MC truth object.
Definition at line 61 of file Geant4OutputAction.h.
Referenced by end(), and DD4hep::Simulation::Geant4Output2ROOT::saveCollection().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4OutputAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4OutputAction.cpp