DD4hep: DD4hep::XML::Document Class Reference
DD4hep::XML::Document Class Reference
DD4hep::XML classes and objects
Class supporting the basic functionality of an XML document.
#include <XMLElements.h>
Public Types
typedef XmlDocument * DOC
Public Member Functions
Document (DOC d)
Constructor.
operator DOC () const
Auto-conversion to DOM document.
DOC operator-> () const
Accessot to DOM document behaviour using arrow operator.
DOC ptr () const
Accessot to DOM document behaviour.
Handle_t root () const
Access the ROOT eleemnt of the DOM document.
Handle_t createElt (const XmlChar *tag) const
Create DOM element.
Handle_t clone (Handle_t source) const
Clone a DOM element / sub-tree.
std::string uri () const
Acces the document URI.
Public Attributes
DOC m_doc
Detailed Description
Class supporting the basic functionality of an XML document.
User class encapsulating a DOM document. Nothing special - normal handle around pointer.
Author
M.Frank
Version
1.0
Definition at line 617 of file XMLElements.h.
Member Typedef Documentation
DOC
typedef XmlDocument* DD4hep::XML::Document::DOC
Definition at line 619 of file XMLElements.h.
Constructor & Destructor Documentation
Document()
DD4hep::XML::Document::Document (DOC d) inline
Constructor.
Definition at line 623 of file XMLElements.h.
Member Function Documentation
clone()
Handle_t Document::clone (Handle_t source) const
Clone a DOM element / sub-tree.
Definition at line 1240 of file XMLElements.cpp.
References _D, _E, _XE, DD4hep::XML::Handle_t::clone(), and DD4hep::XML::Handle_t::ptr().
Referenced by DD4hep::XML::Element::clone().
createElt()
Handle_t Document::createElt (const XmlChar * tag) const
Create DOM element.
Definition at line 1023 of file XMLElements.cpp.
References _D, and _XE.
Referenced by DD4hep::XML::Element::addChild().
operator DOC()
DD4hep::XML::Document::operator DOC () const inline
Auto-conversion to DOM document.
Definition at line 626 of file XMLElements.h.
operator->()
DOC DD4hep::XML::Document::operator-> () const inline
Accessot to DOM document behaviour using arrow operator.
Definition at line 630 of file XMLElements.h.
ptr()
DOC DD4hep::XML::Document::ptr () const inline
Accessot to DOM document behaviour.
Definition at line 634 of file XMLElements.h.
Referenced by DD4hep::XML::dump_tree(), and DD4hep::XML::DocumentHandler::output().
root()
Handle_t Document::root () const
Access the ROOT eleemnt of the DOM document.
Definition at line 1032 of file XMLElements.cpp.
References _D, and _XE.
Referenced by DD4hep::XML::DocumentHandler::create(), DD4hep::Alignments::GlobalAlignmentWriter::dump(), DD4hep::LCDDLoad::processXML(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
uri()
std::string Document::uri () const
Acces the document URI.
Definition at line 1039 of file XMLElements.cpp.
References _D.
Member Data Documentation
m_doc
DOC DD4hep::XML::Document::m_doc
Definition at line 620 of file XMLElements.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLElements.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLElements.cpp