DD4hep: DD4hep::Simulation::Geant4SensitiveAction< T > Class Template Reference
DD4hep::Simulation::Geant4SensitiveAction< T > Class Template Reference
DD4hep::Simulation components, classes and objects
Template class to ease the construction of sensitive detectors using particle template specialization.
#include <Geant4SensDetAction.h>
Public Types
typedef T UserData
Public Types inherited from DD4hep::Simulation::Geant4Sensitive
enum HitCreationFlags { SIMPLE_MODE = 0, MEDIUM_MODE = 1<<0, DETAILED_MODE = 1<<1 }
typedef Geometry::LCDD LCDD
typedef Geometry::Readout Readout
typedef Geometry::DetElement DetElement
typedef Geometry::Segmentation Segmentation
typedef Geometry::SensitiveDetector SensitiveDetector
Definition: Sensitive detector type.
typedef Geant4StepHandler StepHandler
typedef Geant4HitCollection HitCollection
Public Member Functions
Geant4SensitiveAction (Geant4Context *context, const std::string &name, Geometry::DetElement det, Geometry::LCDD &lcdd)
Standard , initializing constructor.
virtual ~Geant4SensitiveAction ()
Default destructor.
virtual void defineCollections ()
Define collections created by this sensitivie action object.
template<typename HIT >
size_t declareReadoutFilteredCollection ()
Define readout specific hit collection with volume ID filtering.
template<typename HIT >
size_t defineReadoutCollection (const std::string collection_name)
Define readout specific hit collection. matching name must be present in readout structure.
virtual void initialize ()
Initialization overload for specialization.
virtual void finalize ()
Finalization overload for specialization.
virtual void begin (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the begining of each event.
virtual void end (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked at the end of each event.
virtual bool process (G4Step *step, G4TouchableHistory *history)
G4VSensitiveDetector interface: Method for generating hit(s) using the G4Step object.
virtual void clear (G4HCofThisEvent *hce)
G4VSensitiveDetector interface: Method invoked if the event was aborted.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
bool process (G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
bool process (G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
bool process (G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
bool process (G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
template<>
void initialize ()
Initialization overload for specialization.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
void clear (G4HCofThisEvent *)
Method for generating hit(s) using the information of G4Step object.
template<>
G4bool process (G4Step *step, G4TouchableHistory *history)
Method for generating hit(s) using the information of G4Step object.
template<>
void initialize ()
Initialization overload for specialization.
template<>
void begin (G4HCofThisEvent *)
G4VSensitiveDetector interface: Method invoked at the begining of each event.
template<>
void end (G4HCofThisEvent *)
G4VSensitiveDetector interface: Method invoked at the end of each event.
template<>
void defineCollections ()
Define collections created by this sensitivie action object.
template<>
void clear (G4HCofThisEvent *)
Method for generating hit(s) using the information of G4Step object.
template<>
G4bool process (G4Step *step, G4TouchableHistory *history)
Method for generating hit(s) using the information of G4Step object.
Public Member Functions inherited from DD4hep::Simulation::Geant4Sensitive
Geant4Sensitive (Geant4Context *context, const std::string &name, DetElement det, LCDD &lcdd)
Constructor. The sensitive detector element is identified by the detector name.
virtual ~Geant4Sensitive ()
Standard destructor.
Geant4ActionSD & detector () const
Access to the sensitive detector object.
void setDetector (Geant4ActionSD *sens_det)
Access to the sensitive detector object.
int hitCreationMode () const
Property access to the hit creation mode.
std::string detectorName () const
G4VSensitiveDetector internals: Access to the detector name.
std::string path () const
G4VSensitiveDetector internals: Access to the detector path name.
std::string fullPath () const
G4VSensitiveDetector internals: Access to the detector path name.
bool isActive () const
G4VSensitiveDetector internals: Is the detector active?
SensitiveDetector sensitiveDetector () const
Access the DD4hep sensitive detector.
G4VReadOutGeometry * readoutGeometry () const
Access to the readout geometry of the sensitive detector.
void mark (const G4Track *track) const
Mark the track to be kept for MC truth propagation during hit processing.
void mark (const G4Step *step) const
Mark the track of this step to be kept for MC truth propagation during hit processing.
Geant4SensDetActionSequence & sequence () const
Access to the hosting sequence.
void adopt (Geant4Filter *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adopt_front (Geant4Filter *filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
void adoptFilter (Geant4Action *filter)
Add an actor responding to all callbacks. Sequence takes ownership.
void adoptFilter_front (Geant4Action *filter)
Add an actor responding to all callbacks to the sequence front. Sequence takes ownership.
bool accept (const G4Step *step) const
Callback before hit processing starts. Invoke all filters.
template<typename TYPE >
size_t defineCollection (const std::string &coll_name)
Initialize the usage of a single hit collection. Returns the collection ID.
const std::string & hitCollectionName (size_t which) const
Access HitCollection container names.
HitCollection * collection (size_t which)
Retrieve the hits collection associated with this detector by its serial number.
HitCollection * collectionByID (size_t id)
Retrieve the hits collection associated with this detector by its collection identifier.
long long int volumeID (const G4Step *step)
Returns the volumeID of the sensitive volume corresponding to the step.
long long int cellID (const G4Step *step)
Returns the cellID of the sensitive volume corresponding to the step.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Attributes
std::string m_collectionName
Property: collection name. If not set default is readout name!
size_t m_collectionID
Collection identifier.
UserData m_userData
User data block.
Protected Attributes inherited from DD4hep::Simulation::Geant4Sensitive
int m_hitCreationMode
Property: Hit creation mode. Maybe one of the enum HitCreationFlags.
LCDD & m_lcdd
Reference to the detector description object.
DetElement m_detector
Reference to the detector element describing this sensitive element.
SensitiveDetector m_sensitive
Reference to the sensitive detector element.
Readout m_readout
Reference to the readout structure.
Segmentation m_segmentation
Reference to segmentation.
Actors< Geant4Filter > m_filters
The list of sensitive detector filter objects.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Detailed Description
template<typename T>
class DD4hep::Simulation::Geant4SensitiveAction< T >
Template class to ease the construction of sensitive detectors using particle template specialization.
Templated implementation to realize sensitive detectors. Default implementations for all functions are provided in the file DDG4/Geant4SensDetAction.inl.
Users may override any of the templated callbacks or the of the virtual functions of the base class using explicit template specialization. An example may be found in DDG4/plugins/Geant4SDActions.
Author
M.Frank
Version
1.0
Definition at line 469 of file Geant4SensDetAction.h.
Member Typedef Documentation
UserData
template<typename T > typedef T DD4hep::Simulation::Geant4SensitiveAction< T >::UserData
Definition at line 471 of file Geant4SensDetAction.h.
Constructor & Destructor Documentation
Geant4SensitiveAction()
template<typename T > DD4hep::Simulation::Geant4SensitiveAction< T >::Geant4SensitiveAction (Geant4Context * context, const std::string & name, Geometry::DetElement det, Geometry::LCDD & lcdd)
Standard , initializing constructor.
Definition at line 33 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), DD4hep::Simulation::Geant4SensitiveAction< T >::initialize(), and DD4hep::Simulation::Geant4SensitiveAction< T >::m_collectionName.
~Geant4SensitiveAction()
template<typename T > DD4hep::Simulation::Geant4SensitiveAction< T >::~Geant4SensitiveAction () virtual
Default destructor.
Definition at line 45 of file Geant4SensDetAction.inl.
References DD4hep::InstanceCount::decrement(), and DD4hep::Simulation::Geant4SensitiveAction< T >::finalize().
Member Function Documentation
begin() [1/2]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerWeighted >::begin (G4HCofThisEvent *) virtual
G4VSensitiveDetector interface: Method invoked at the begining of each event.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 388 of file Geant4TrackerWeightedSD.cpp.
begin() [2/2]
template<typename T > void DD4hep::Simulation::Geant4SensitiveAction< T >::begin (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked at the begining of each event.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 59 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4Sensitive::begin().
clear() [1/3]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerWeighted >::clear (G4HCofThisEvent *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 403 of file Geant4TrackerWeightedSD.cpp.
References DD4hep::Simulation::Geant4SensitiveAction< T >::clear().
clear() [2/3]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerCombine >::clear (G4HCofThisEvent *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 472 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4SensitiveAction< T >::clear().
clear() [3/3]
template<typename T > void DD4hep::Simulation::Geant4SensitiveAction< T >::clear (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked if the event was aborted.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 74 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4Sensitive::clear().
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::clear().
declareReadoutFilteredCollection()
template<typename T > template<typename HIT > size_t DD4hep::Simulation::Geant4SensitiveAction< T >::declareReadoutFilteredCollection ()
Define readout specific hit collection with volume ID filtering.
Convenience function. To be called by specialized sensitive actions inheriting this class.
If the property CollectionName ist NOT set, one default collection is declared, with the readout name as the collection name.
If the property CollectionName is set, the readout structure is searched for the corresponding entry and a collection with the corrsponding name is declared. At the same time a VolumeID filter is injected at the front of the sensitive's filter queue to ONLY act on volume IDs matching this criterium.
Definition at line 104 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4SensitiveAction< T >::m_collectionName, DD4hep::Simulation::Geant4Sensitive::m_sensitive, DD4hep::Handle< T >::name(), and DD4hep::Geometry::SensitiveDetector::readout().
defineCollections() [1/7]
template<> void DD4hep::Simulation::Geant4SensitiveAction< Geant4Tracker >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 44 of file Geant4SDActions.cpp.
defineCollections() [2/7]
template<> void DD4hep::Simulation::Geant4SensitiveAction< Geant4Calorimeter >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 100 of file Geant4SDActions.cpp.
defineCollections() [3/7]
template<> void DD4hep::Simulation::Geant4SensitiveAction< Geant4OpticalCalorimeter >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 179 of file Geant4SDActions.cpp.
defineCollections() [4/7]
template<> void DD4hep::Simulation::Geant4SensitiveAction< Geant4ScintillatorCalorimeter >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 241 of file Geant4SDActions.cpp.
defineCollections() [5/7]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerWeighted >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 398 of file Geant4TrackerWeightedSD.cpp.
defineCollections() [6/7]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerCombine >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 467 of file Geant4SDActions.cpp.
defineCollections() [7/7]
template<typename T > void DD4hep::Simulation::Geant4SensitiveAction< T >::defineCollections () virtual
Define collections created by this sensitivie action object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 79 of file Geant4SensDetAction.inl.
defineReadoutCollection()
template<typename T > template<typename HIT > size_t DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection (const std::string collection_name)
Define readout specific hit collection. matching name must be present in readout structure.
Definition at line 84 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4Sensitive::adopt_front(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4SensitiveAction< T >::m_collectionName, DD4hep::Simulation::Geant4Sensitive::m_sensitive, DD4hep::Handle< T >::name(), DD4hep::Simulation::Geant4Action::name(), and DD4hep::Geometry::SensitiveDetector::readout().
end() [1/2]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerWeighted >::end (G4HCofThisEvent *) virtual
G4VSensitiveDetector interface: Method invoked at the end of each event.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 393 of file Geant4TrackerWeightedSD.cpp.
end() [2/2]
template<typename T > void DD4hep::Simulation::Geant4SensitiveAction< T >::end (G4HCofThisEvent * hce) virtual
G4VSensitiveDetector interface: Method invoked at the end of each event.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 64 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4Sensitive::end().
finalize()
template<typename T > void DD4hep::Simulation::Geant4SensitiveAction< T >::finalize () virtual
Finalization overload for specialization.
Definition at line 55 of file Geant4SensDetAction.inl.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::~Geant4SensitiveAction().
initialize() [1/3]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerWeighted >::initialize ()
Initialization overload for specialization.
Definition at line 380 of file Geant4TrackerWeightedSD.cpp.
initialize() [2/3]
template<> void DD4hep::Simulation::Geant4SensitiveAction< TrackerCombine >::initialize ()
Initialization overload for specialization.
Definition at line 460 of file Geant4SDActions.cpp.
initialize() [3/3]
template<typename T > void DD4hep::Simulation::Geant4SensitiveAction< T >::initialize () virtual
Initialization overload for specialization.
Definition at line 51 of file Geant4SensDetAction.inl.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::Geant4SensitiveAction().
process() [1/7]
template<> bool DD4hep::Simulation::Geant4SensitiveAction< Geant4Tracker >::process (G4Step * step, G4TouchableHistory *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 49 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4StepHandler::deposit(), DD4hep::except(), ROOT::Math::mean_direction(), DD4hep::Simulation::Geant4TouchableHandler::path(), DD4hep::Simulation::Geant4StepHandler::postMom(), DD4hep::Simulation::Geant4StepHandler::postPos(), DD4hep::Simulation::Geant4StepHandler::prePos(), DD4hep::print(), DD4hep::Simulation::Geant4StepHandler::track, DD4hep::Simulation::Geant4StepHandler::trkID(), and DD4hep::Simulation::Geant4StepHandler::trkPdgID().
process() [2/7]
template<> bool DD4hep::Simulation::Geant4SensitiveAction< Geant4Calorimeter >::process (G4Step * step, G4TouchableHistory *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 105 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4HitCollection::add(), DD4hep::Simulation::Geant4HitData::MonteCarloContrib::deposit, e, DD4hep::except(), DD4hep::Simulation::Geant4HitCollection::findByKey(), DD4hep::Simulation::Geant4StepHandler::localToGlobal(), DD4hep::Simulation::Geant4TouchableHandler::path(), DD4hep::DDSegmentation::Vector3D::X, DD4hep::DDSegmentation::Vector3D::Y, and DD4hep::DDSegmentation::Vector3D::Z.
process() [3/7]
template<> bool DD4hep::Simulation::Geant4SensitiveAction< Geant4OpticalCalorimeter >::process (G4Step * step, G4TouchableHistory *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 183 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4HitCollection::add(), DD4hep::Simulation::Geant4HitData::MonteCarloContrib::deposit, DD4hep::except(), DD4hep::Simulation::Geant4HitCollection::find(), DD4hep::Simulation::Geant4StepHandler::prePos(), and DD4hep::Simulation::Geant4StepHandler::track.
process() [4/7]
template<> bool DD4hep::Simulation::Geant4SensitiveAction< Geant4ScintillatorCalorimeter >::process (G4Step * step, G4TouchableHistory *) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 245 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4HitCollection::add(), DD4hep::Simulation::Geant4HitData::MonteCarloContrib::deposit, e, DD4hep::except(), DD4hep::Simulation::Geant4HitCollection::findByKey(), DD4hep::Simulation::Geant4StepHandler::localToGlobal(), DD4hep::Simulation::Geant4TouchableHandler::path(), DD4hep::DDSegmentation::Vector3D::X, DD4hep::DDSegmentation::Vector3D::Y, and DD4hep::DDSegmentation::Vector3D::Z.
process() [5/7]
template<> G4bool DD4hep::Simulation::Geant4SensitiveAction< TrackerWeighted >::process (G4Step * step, G4TouchableHistory * history) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 409 of file Geant4TrackerWeightedSD.cpp.
References DD4hep::Simulation::Geant4SensitiveAction< T >::process().
process() [6/7]
template<> G4bool DD4hep::Simulation::Geant4SensitiveAction< TrackerCombine >::process (G4Step * step, G4TouchableHistory * history) virtual
Method for generating hit(s) using the information of G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 478 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4SensitiveAction< T >::process().
process() [7/7]
template<typename T > bool DD4hep::Simulation::Geant4SensitiveAction< T >::process (G4Step * step, G4TouchableHistory * history) virtual
G4VSensitiveDetector interface: Method for generating hit(s) using the G4Step object.
Reimplemented from DD4hep::Simulation::Geant4Sensitive.
Definition at line 69 of file Geant4SensDetAction.inl.
References DD4hep::Simulation::Geant4Sensitive::process().
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::process().
Member Data Documentation
m_collectionID
template<typename T > size_t DD4hep::Simulation::Geant4SensitiveAction< T >::m_collectionID protected
Collection identifier.
Definition at line 476 of file Geant4SensDetAction.h.
m_collectionName
template<typename T > std::string DD4hep::Simulation::Geant4SensitiveAction< T >::m_collectionName protected
Property: collection name. If not set default is readout name!
Definition at line 474 of file Geant4SensDetAction.h.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::declareReadoutFilteredCollection(), DD4hep::Simulation::Geant4SensitiveAction< T >::defineReadoutCollection(), and DD4hep::Simulation::Geant4SensitiveAction< T >::Geant4SensitiveAction().
m_userData
template<typename T > UserData DD4hep::Simulation::Geant4SensitiveAction< T >::m_userData protected
User data block.
Definition at line 478 of file Geant4SensDetAction.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensDetAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4SensDetAction.inl