DD4hep: DD4hep::Alignments::DetAlign Class Reference
DD4hep::Alignments::DetAlign Class Reference
DD4hep::Geometry components, classes and objects
Handle class describing the access to DetElement dependent alignments.
#include <DetAlign.h>
Public Types
typedef Geometry::DetElementObject Object
Internal object type.
typedef Handle< Object > RefObject
Definition of the base handle type.
typedef Conditions::UserPool UserPool
Pool definition.
Public Types inherited from DD4hep::Handle< Geometry::DetElementObject >
typedef Geometry::DetElementObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
DetAlign ()
Default constructor.
DetAlign (Object *object_ptr)
Constructor to hold handled object.
template<typename Q >
DetAlign (const Handle< Q > &e)
Templated constructor for handle conversions.
DetAlign (const DetAlign &e)
Constructor to copy handle.
DetAlign (const Geometry::DetElement &e)
Constructor to copy handle.
Object & _data () const
Additional data accessor.
DetAlign & operator= (const DetAlign &e)
Assignment operator.
Alignment nominal () const
Access to the constant nominal alignment information.
Alignment survey () const
Access to the constant survey alignment information.
bool hasAlignments () const
Check if alignments are at all present.
Container alignments () const
Access to the alignments information.
Alignment get (const std::string &key, const UserPool &pool)
Access to alignment objects from a given pool.
Alignment get (Alignment::key_type key, const UserPool &pool)
Access to alignment objects from a given pool.
Alignment get (const std::string &key, const Alignment::iov_type &iov)
Access to alignment objects. Only alignments in the pool are accessed.
Alignment get (Alignment::key_type key, const Alignment::iov_type &iov)
Access to alignment objects. Only alignments in the pool are accessed.
Public Member Functions inherited from DD4hep::Handle< Geometry::DetElementObject >
Handle ()
Defaulot constructor.
Handle (Geometry::DetElementObject *e)
Initializing constructor from pointer.
Handle (const Handle< Geometry::DetElementObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< Geometry::DetElementObject > & operator= (const Handle< Geometry::DetElementObject > &e)=default
Assignment operator.
bool operator== (const Handle< Geometry::DetElementObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< Geometry::DetElementObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< Geometry::DetElementObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< Geometry::DetElementObject > & clear ()
Release the object held by the handle.
Geometry::DetElementObject * operator-> () const
Access the held object using the -> operator.
operator Geometry::DetElementObject & () const
Automatic type conversion to an object references.
Geometry::DetElementObject & operator* () const
Access the held object using the * operator.
Geometry::DetElementObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
Geometry::DetElementObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< Geometry::DetElementObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< Geometry::DetElementObject >
Geometry::DetElementObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Handle class describing the access to DetElement dependent alignments.
Author
M.Frank
Version
1.0
Definition at line 42 of file DetAlign.h.
Member Typedef Documentation
Object
typedef Geometry::DetElementObject DD4hep::Alignments::DetAlign::Object
Internal object type.
Definition at line 45 of file DetAlign.h.
RefObject
typedef Handle<Object> DD4hep::Alignments::DetAlign::RefObject
Definition of the base handle type.
Definition at line 47 of file DetAlign.h.
UserPool
typedef Conditions::UserPool DD4hep::Alignments::DetAlign::UserPool
Pool definition.
Definition at line 49 of file DetAlign.h.
Constructor & Destructor Documentation
DetAlign() [1/5]
DD4hep::Alignments::DetAlign::DetAlign () inline
Default constructor.
Definition at line 54 of file DetAlign.h.
DetAlign() [2/5]
DD4hep::Alignments::DetAlign::DetAlign (Object * object_ptr) inline
Constructor to hold handled object.
Definition at line 57 of file DetAlign.h.
DetAlign() [3/5]
template<typename Q > DD4hep::Alignments::DetAlign::DetAlign (const Handle< Q > & e) inline
Templated constructor for handle conversions.
Definition at line 60 of file DetAlign.h.
DetAlign() [4/5]
DD4hep::Alignments::DetAlign::DetAlign (const DetAlign & e) inline
Constructor to copy handle.
Definition at line 63 of file DetAlign.h.
DetAlign() [5/5]
DD4hep::Alignments::DetAlign::DetAlign (const Geometry::DetElement & e) inline
Constructor to copy handle.
Definition at line 66 of file DetAlign.h.
References _data(), and e.
Member Function Documentation
_data()
Object& DD4hep::Alignments::DetAlign::_data () const inline
Additional data accessor.
Definition at line 75 of file DetAlign.h.
alignments()
Container DetAlign::alignments () const
Access to the alignments information.
Definition at line 45 of file DetAlign.cpp.
References DD4hep::Geometry::DetElementObject::alignments, DD4hep::Handle< T >::assign(), and DD4hep::Handle< T >::isValid().
get() [1/4]
Alignment DetAlign::get (const std::string & key, const UserPool & pool)
Access to alignment objects from a given pool.
Access to alignment objects from a given pool. Only alignments in the pool are accessed.
Definition at line 63 of file DetAlign.cpp.
get() [2/4]
Alignment DetAlign::get (Alignment::key_type key, const UserPool & pool)
Access to alignment objects from a given pool.
Access to alignment objects from a given pool. Only alignments in the pool are accessed.
Definition at line 68 of file DetAlign.cpp.
get() [3/4]
Alignment DetAlign::get (const std::string & key, const Alignment::iov_type & iov)
Access to alignment objects. Only alignments in the pool are accessed.
Access to alignment objects.
Definition at line 53 of file DetAlign.cpp.
get() [4/4]
Alignment DetAlign::get (Alignment::key_type key, const Alignment::iov_type & iov)
Access to alignment objects. Only alignments in the pool are accessed.
Access to alignment objects.
Definition at line 58 of file DetAlign.cpp.
hasAlignments()
bool DetAlign::hasAlignments () const
Check if alignments are at all present.
Definition at line 37 of file DetAlign.cpp.
References DD4hep::Geometry::DetElementObject::alignments, and DD4hep::Handle< T >::isValid().
nominal()
Alignment DetAlign::nominal () const
Access to the constant nominal alignment information.
Access to the alignment information.
Definition at line 27 of file DetAlign.cpp.
operator=()
DetAlign& DD4hep::Alignments::DetAlign::operator= (const DetAlign & e) inline
Assignment operator.
Definition at line 79 of file DetAlign.h.
References DD4hep::Handle< T >::m_element.
survey()
Alignment DetAlign::survey () const
Access to the constant survey alignment information.
Access to the survey alignment information.
Definition at line 32 of file DetAlign.cpp.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/DetAlign.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/DetAlign.cpp