DD4hep: DD4hep::Simulation::Geant4ParticleGun Class Reference
DD4hep::Simulation::Geant4ParticleGun Class Reference
DD4hep::Simulation components, classes and objects
Implementation of a particle gun using Geant4Particles.
#include <Geant4ParticleGun.h>
Public Member Functions
Geant4ParticleGun (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4ParticleGun ()
Default destructor.
virtual void operator() (G4Event *event)
Callback to generate primary particles.
Public Member Functions inherited from DD4hep::Simulation::Geant4IsotropeGenerator
Geant4IsotropeGenerator (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4IsotropeGenerator ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4ParticleGenerator
Geant4ParticleGenerator (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4ParticleGenerator ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4GeneratorAction
Geant4GeneratorAction (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4GeneratorAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Member Functions
virtual void getParticleDirection (int, ROOT::Math::XYZVector &direction, double &momentum) const
Particle modification. Caller presets defaults to: (direction = m_direction, momentum = m_energy)
Protected Member Functions inherited from DD4hep::Simulation::Geant4IsotropeGenerator
void getParticleDirectionFFbar (int num, ROOT::Math::XYZVector &direction, double &momentum) const
e+e- –> ffbar particle distribution ~ 1 + cos^2(theta)
void getParticleDirectionEta (int num, ROOT::Math::XYZVector &direction, double &momentum) const
e+e- –> ffbar particle distribution ~ 1 + cos^2(theta)
void getParticleDirectionCosTheta (int num, ROOT::Math::XYZVector &direction, double &momentum) const
Particle distribution ~ cos(theta)
void getParticleDirectionUniform (int num, ROOT::Math::XYZVector &direction, double &momentum) const
Uniform particle distribution.
Protected Member Functions inherited from DD4hep::Simulation::Geant4ParticleGenerator
virtual void getParticleMultiplicity (int &multiplicity) const
Particle modification. Caller presets defaults to: (multiplicity=m_multiplicity)
virtual void getVertexPosition (ROOT::Math::XYZVector &position) const
Particle's vertex modification. Caller presets defaults to: (multiplicity=m_multiplicity)
virtual void printInteraction (int mask) const
Print single particle interaction identified by its mask.
virtual void printInteraction (Geant4PrimaryInteraction *inter) const
Print single particle interaction identified by it's reference.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes
bool m_isotrop
Property: Isotrope particles?
bool m_standalone
Property: Standalone mode: includes interaction merging and primary generation.
bool m_print
Property: Enable printout.
int m_shotNo
Shot number in sequence.
Protected Attributes inherited from DD4hep::Simulation::Geant4IsotropeGenerator
std::string m_distribution
Property: Distribution name. Default: "uniform". Allowed: "uniform", "cos(theta)", "ffbar", "eta".
double m_phiMin
Property: Minimal phi angular value.
double m_phiMax
Property: Maximal phi angular value.
double m_thetaMin
Property: Minimal theta angular value.
double m_thetaMax
Property: Maximal theta angular value.
Protected Attributes inherited from DD4hep::Simulation::Geant4ParticleGenerator
ROOT::Math::XYZVector m_direction
Property: Shooting direction of the gun.
ROOT::Math::XYZVector m_position
Property: Position of the gun in space.
std::string m_particleName
Property: Particle name.
G4ParticleDefinition * m_particle
Pointer to geant4 particle definition.
double m_energy
Property: Particle energy.
int m_multiplicity
Property: Desired multiplicity of the particles to be shot.
int m_mask
Property: User mask passed to all particles in the generated interaction.
Protected Attributes inherited from DD4hep::Simulation::Geant4GeneratorAction
Callback m_calls
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Additional Inherited Members
Public Types inherited from DD4hep::Simulation::Geant4GeneratorAction
typedef Geant4SharedGeneratorAction shared_type
Detailed Description
Implementation of a particle gun using Geant4Particles.
The {{Geant4ParticleGun}} is a tool to shoot a number of particles with identical properties into a given region of the detector to be simulated.
The particle gun is a input source like any other and participates in the general input stage merging process like any other input e.g. from file. Hence, there may be several particle guns present each generating it's own primary vertex. Use the mask property to ensure each gun generates it's own, well identified primary vertex.
There is one 'user lazyness' support though: If there is only one particle gun in use, the property 'Standalone', which by default is set to true invokes the interaction merging and he Geant4 primary generation directly.
Author
M.Frank
Version
1.0
Definition at line 48 of file Geant4ParticleGun.h.
Constructor & Destructor Documentation
Geant4ParticleGun()
Geant4ParticleGun::Geant4ParticleGun (Geant4Context * context, const std::string & name)
Standard constructor.
Definition at line 31 of file Geant4ParticleGun.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), DD4hep::Simulation::Geant4ParticleGenerator::m_direction, DD4hep::Simulation::Geant4ParticleGenerator::m_energy, m_isotrop, DD4hep::Simulation::Geant4ParticleGenerator::m_multiplicity, DD4hep::Simulation::Geant4Action::m_needsControl, DD4hep::Simulation::Geant4ParticleGenerator::m_particleName, DD4hep::Simulation::Geant4ParticleGenerator::m_position, m_print, and m_standalone.
Referenced by getParticleDirection().
~Geant4ParticleGun()
Geant4ParticleGun::~Geant4ParticleGun () virtual
Default destructor.
Definition at line 48 of file Geant4ParticleGun.cpp.
References DD4hep::InstanceCount::decrement().
Referenced by getParticleDirection().
Member Function Documentation
getParticleDirection()
virtual void DD4hep::Simulation::Geant4ParticleGun::getParticleDirection (int , ROOT::Math::XYZVector & direction, double & momentum) const inline protected virtual
Particle modification. Caller presets defaults to: (direction = m_direction, momentum = m_energy)
Reimplemented from DD4hep::Simulation::Geant4IsotropeGenerator.
Definition at line 59 of file Geant4ParticleGun.h.
References DD4hep::Simulation::Geant4Action::context(), Geant4ParticleGun(), DD4hep::Simulation::Geant4ParticleGenerator::m_direction, DD4hep::Simulation::Geant4ParticleGenerator::m_energy, DD4hep::Simulation::Geant4Action::name(), operator()(), and ~Geant4ParticleGun().
operator()()
void Geant4ParticleGun::operator() (G4Event * event) virtual
Callback to generate primary particles.
Reimplemented from DD4hep::Simulation::Geant4ParticleGenerator.
Definition at line 53 of file Geant4ParticleGun.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::generatePrimaries(), DD4hep::Simulation::generationInitialization(), DD4hep::Simulation::Geant4IsotropeGenerator::getParticleDirection(), dd4hep::GeV, DD4hep::Simulation::Geant4ParticleGenerator::m_direction, DD4hep::Simulation::Geant4ParticleGenerator::m_energy, m_isotrop, DD4hep::Simulation::Geant4ParticleGenerator::m_mask, DD4hep::Simulation::Geant4ParticleGenerator::m_particleName, DD4hep::Simulation::Geant4ParticleGenerator::m_position, m_print, m_shotNo, m_standalone, DD4hep::Simulation::mergeInteractions(), dd4hep::mm, DD4hep::Simulation::Geant4ParticleGenerator::operator()(), DD4hep::Simulation::Geant4Action::print(), and DD4hep::Simulation::Geant4ParticleGenerator::printInteraction().
Referenced by getParticleDirection().
Member Data Documentation
m_isotrop
bool DD4hep::Simulation::Geant4ParticleGun::m_isotrop protected
Property: Isotrope particles?
Definition at line 51 of file Geant4ParticleGun.h.
Referenced by Geant4ParticleGun(), and operator()().
m_print
bool DD4hep::Simulation::Geant4ParticleGun::m_print protected
Property: Enable printout.
Definition at line 55 of file Geant4ParticleGun.h.
Referenced by Geant4ParticleGun(), and operator()().
m_shotNo
int DD4hep::Simulation::Geant4ParticleGun::m_shotNo protected
Shot number in sequence.
Definition at line 57 of file Geant4ParticleGun.h.
Referenced by operator()().
m_standalone
bool DD4hep::Simulation::Geant4ParticleGun::m_standalone protected
Property: Standalone mode: includes interaction merging and primary generation.
Definition at line 53 of file Geant4ParticleGun.h.
Referenced by Geant4ParticleGun(), and operator()().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ParticleGun.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ParticleGun.cpp