DD4hep: DD4hep::Simulation::Geant4ParticlePrint Class Reference
DD4hep::Simulation::Geant4ParticlePrint Class Reference
DD4hep::Simulation components, classes and objects
Geant4Action to print MC particle information.
#include <Geant4ParticlePrint.h>
Public Types
typedef Geant4ParticleMap::Particle Particle
typedef Geant4ParticleMap::ParticleMap ParticleMap
typedef Geant4ParticleMap::TrackEquivalents TrackEquivalents
Public Types inherited from DD4hep::Simulation::Geant4EventAction
typedef Geant4SharedEventAction shared_type
Public Member Functions
Geant4ParticlePrint (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4ParticlePrint ()
Default destructor.
virtual void begin (const G4Event *event)
Pre-event action callback.
virtual void end (const G4Event *event)
Post-event action callback.
virtual void operator() (G4Event *event)
Generation action callback.
Public Member Functions inherited from DD4hep::Simulation::Geant4EventAction
Geant4EventAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4EventAction ()
Default destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Protected Member Functions
void printParticle (const std::string &prefix, const G4Event *e, Geant4ParticleHandle p) const
void printParticles (const G4Event *e, const ParticleMap &particles) const
Print record of kept particles.
void printParticleTree (const G4Event *e, const ParticleMap &particles, int level, Geant4ParticleHandle p) const
Print tree of kept particles.
void printParticleTree (const G4Event *e, const ParticleMap &particles) const
Print tree of kept particles.
void makePrintout (const G4Event *e) const
Print particle table.
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes
int m_outputType
Property: Flag to indicate output type: 1: TABLE, 2:TREE, 3:BOTH (default)
bool m_printBegin
Property: Flag to indicate output type at begin of event.
bool m_printEnd
Property: Flag to indicate output type at end of event.
bool m_printGeneration
Property: Flag to indicate output type as part of the generator action.
bool m_printHits
Property: Flag to indicate output of hit data in tree.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Detailed Description
Geant4Action to print MC particle information.
Author
M.Frank
Version
1.0
Definition at line 39 of file Geant4ParticlePrint.h.
Member Typedef Documentation
Particle
typedef Geant4ParticleMap::Particle DD4hep::Simulation::Geant4ParticlePrint::Particle
Definition at line 41 of file Geant4ParticlePrint.h.
ParticleMap
typedef Geant4ParticleMap::ParticleMap DD4hep::Simulation::Geant4ParticlePrint::ParticleMap
Definition at line 42 of file Geant4ParticlePrint.h.
TrackEquivalents
typedef Geant4ParticleMap::TrackEquivalents DD4hep::Simulation::Geant4ParticlePrint::TrackEquivalents
Definition at line 43 of file Geant4ParticlePrint.h.
Constructor & Destructor Documentation
Geant4ParticlePrint()
Geant4ParticlePrint::Geant4ParticlePrint (Geant4Context * context, const std::string & nam)
Standard constructor.
Definition at line 36 of file Geant4ParticlePrint.cpp.
References DD4hep::Simulation::Geant4Action::declareProperty(), DD4hep::InstanceCount::increment(), m_outputType, m_printBegin, m_printEnd, m_printGeneration, and m_printHits.
~Geant4ParticlePrint()
Geant4ParticlePrint::~Geant4ParticlePrint () virtual
Default destructor.
Definition at line 48 of file Geant4ParticlePrint.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
begin()
void Geant4ParticlePrint::begin (const G4Event * event) virtual
Pre-event action callback.
Reimplemented from DD4hep::Simulation::Geant4EventAction.
Definition at line 71 of file Geant4ParticlePrint.cpp.
References m_printBegin, and makePrintout().
end()
void Geant4ParticlePrint::end (const G4Event * event) virtual
Post-event action callback.
Reimplemented from DD4hep::Simulation::Geant4EventAction.
Definition at line 76 of file Geant4ParticlePrint.cpp.
References m_printEnd, and makePrintout().
makePrintout()
void Geant4ParticlePrint::makePrintout (const G4Event * e) const protected
Print particle table.
Definition at line 53 of file Geant4ParticlePrint.cpp.
References DD4hep::Simulation::Geant4Action::c_name(), DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Action::except(), DD4hep::Simulation::Geant4Event::extension(), m_outputType, DD4hep::Simulation::Geant4ParticleMap::particles(), DD4hep::Simulation::Geant4Action::print(), printParticles(), and printParticleTree().
Referenced by begin(), end(), and operator()().
operator()()
void Geant4ParticlePrint::operator() (G4Event * event) virtual
Generation action callback.
Definition at line 66 of file Geant4ParticlePrint.cpp.
References m_printGeneration, and makePrintout().
printParticle()
void Geant4ParticlePrint::printParticle (const std::string & prefix, const G4Event * e, Geant4ParticleHandle p) const protected
Definition at line 80 of file Geant4ParticlePrint.cpp.
References DD4hep::Simulation::Geant4Action::context(), DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::Geant4ParticleHandle::energy(), DD4hep::Simulation::Geant4Context::event(), DD4hep::Simulation::Geant4Event::extension(), DD4hep::Simulation::Geant4Particle::g4Parent, DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_CREATED_CALORIMETER_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, DD4hep::Simulation::G4PARTICLE_HAS_SECONDARIES, DD4hep::Simulation::G4PARTICLE_KEEP_PARENT, DD4hep::Simulation::G4PARTICLE_KEEP_PROCESS, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::Simulation::Geant4HitCollection::GetSize(), DD4hep::Simulation::Geant4HitCollection::hit(), DD4hep::Simulation::Geant4Particle::id, DD4hep::ReferenceBitMask< T >::isSet(), m_printHits, DD4hep::Simulation::Geant4ParticleHandle::numParent(), DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::Geant4ParticleMap::particleID(), DD4hep::Simulation::Geant4ParticleHandle::particleName(), DD4hep::Simulation::Geant4Tracker::Hit::position, DD4hep::Simulation::Geant4Action::print(), DD4hep::Simulation::Geant4Particle::process, DD4hep::Simulation::Geant4ParticleHandle::processName(), DD4hep::Simulation::Geant4ParticleHandle::processTypeName(), DD4hep::Simulation::Geant4Particle::reason, DD4hep::Simulation::Geant4Particle::status, DD4hep::Simulation::Geant4HitData::MonteCarloContrib::trackID, DD4hep::Simulation::Geant4Tracker::Hit::truth, DD4hep::Simulation::Geant4Calorimeter::Hit::truth, and DD4hep::yes_no().
Referenced by printParticles(), and printParticleTree().
printParticles()
void Geant4ParticlePrint::printParticles (const G4Event * e, const ParticleMap & particles) const protected
Print record of kept particles.
Definition at line 153 of file Geant4ParticlePrint.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::G4PARTICLE_ABOVE_ENERGY_THRESHOLD, DD4hep::Simulation::G4PARTICLE_CREATED_CALORIMETER_HIT, DD4hep::Simulation::G4PARTICLE_CREATED_TRACKER_HIT, DD4hep::Simulation::G4PARTICLE_KEEP_PARENT, DD4hep::Simulation::G4PARTICLE_KEEP_PROCESS, DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::Simulation::Geant4Action::print(), printParticle(), and DD4hep::Simulation::Geant4Particle::reason.
Referenced by makePrintout().
printParticleTree() [1/2]
void Geant4ParticlePrint::printParticleTree (const G4Event * e, const ParticleMap & particles, int level, Geant4ParticleHandle p) const protected
Print tree of kept particles.
Definition at line 185 of file Geant4ParticlePrint.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, printParticle(), and dd4hep::second.
Referenced by makePrintout(), and printParticleTree().
printParticleTree() [2/2]
void Geant4ParticlePrint::printParticleTree (const G4Event * e, const ParticleMap & particles) const protected
Print tree of kept particles.
Definition at line 209 of file Geant4ParticlePrint.cpp.
References DD4hep::Simulation::G4PARTICLE_PRIMARY, DD4hep::ReferenceBitMask< T >::isSet(), DD4hep::Simulation::Geant4Action::print(), printParticleTree(), and DD4hep::Simulation::Geant4Particle::reason.
Member Data Documentation
m_outputType
int DD4hep::Simulation::Geant4ParticlePrint::m_outputType protected
Property: Flag to indicate output type: 1: TABLE, 2:TREE, 3:BOTH (default)
Definition at line 46 of file Geant4ParticlePrint.h.
Referenced by Geant4ParticlePrint(), and makePrintout().
m_printBegin
bool DD4hep::Simulation::Geant4ParticlePrint::m_printBegin protected
Property: Flag to indicate output type at begin of event.
Definition at line 48 of file Geant4ParticlePrint.h.
Referenced by begin(), and Geant4ParticlePrint().
m_printEnd
bool DD4hep::Simulation::Geant4ParticlePrint::m_printEnd protected
Property: Flag to indicate output type at end of event.
Definition at line 50 of file Geant4ParticlePrint.h.
Referenced by end(), and Geant4ParticlePrint().
m_printGeneration
bool DD4hep::Simulation::Geant4ParticlePrint::m_printGeneration protected
Property: Flag to indicate output type as part of the generator action.
Definition at line 52 of file Geant4ParticlePrint.h.
Referenced by Geant4ParticlePrint(), and operator()().
m_printHits
bool DD4hep::Simulation::Geant4ParticlePrint::m_printHits protected
Property: Flag to indicate output of hit data in tree.
Definition at line 54 of file Geant4ParticlePrint.h.
Referenced by Geant4ParticlePrint(), and printParticle().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4ParticlePrint.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4ParticlePrint.cpp