DD4hep: DD4hep: DD4hep::Simulation::Geant4EventAction Class Reference
DD4hep::Simulation::Geant4EventAction Class Reference
[DD4hep::Simulation components, classes and objects]
Concrete basic implementation of the Geant4 event action.
#include <Geant4EventAction.h>
Public Types
typedef Geant4SharedEventAction shared_type
Public Member Functions
Geant4EventAction (Geant4Context *context, const std::string &nam)
Standard constructor.
virtual ~Geant4EventAction ()
Default destructor.
virtual void begin (const G4Event *event)
Begin-of-event callback.
virtual void end (const G4Event *event)
End-of-event callback.
Detailed Description
Concrete basic implementation of the Geant4 event action.
The EventAction is called for every event.
This class is the base class for all user actions, which have to hook into the begin- and end-of-event actions. Typical use cases are the collection/computation of event related properties.
Examples of this functionality may include for example:
Reset variables summing event related information in the begin-event callback.
Monitoring activities such as filling histograms from hits collected during the end-event action.
Author:
M.Frank
Version:
1.0
Definition at line 54 of file Geant4EventAction.h.
Member Typedef Documentation
typedef Geant4SharedEventAction DD4hep::Simulation::Geant4EventAction::shared_type
Definition at line 56 of file Geant4EventAction.h.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4EventAction::Geant4EventAction (Geant4Context * context, const std::string & nam)
Standard constructor.
Geant4EventAction::~Geant4EventAction () [virtual]
Default destructor.
Definition at line 39 of file Geant4EventAction.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
void Geant4EventAction::begin (const G4Event * event) [virtual]
Begin-of-event callback.
begin-of-event callback
Reimplemented in DD4hep::Simulation::Geant4SharedEventAction, DD4hep::Simulation::Geant4OutputAction, DD4hep::Simulation::Geant4ParticlePrint, DD4hep::Simulation::Test::Geant4TestEventAction, and DD4hep::Simulation::Geant4Output2LCIO.
Definition at line 44 of file Geant4EventAction.cpp.
Referenced by DD4hep::Simulation::Geant4EventActionSequence::begin(), and DD4hep::Simulation::Geant4SharedEventAction::begin().
void Geant4EventAction::end (const G4Event * event) [virtual]
End-of-event callback.
Reimplemented in DD4hep::Simulation::Geant4SharedEventAction, DD4hep::Simulation::Geant4OutputAction, DD4hep::Simulation::Geant4ParticlePrint, and DD4hep::Simulation::Test::Geant4TestEventAction.
Definition at line 48 of file Geant4EventAction.cpp.
Referenced by DD4hep::Simulation::Geant4EventActionSequence::end(), and DD4hep::Simulation::Geant4SharedEventAction::end().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/include/DDG4/Geant4EventAction.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4EventAction.cpp