DD4hep: DD4hep::ViewMenu Class Reference
DD4hep::ViewMenu Class Reference
class ViewMenu ViewMenu.h DDEve/ViewMenu.h
#include <ViewMenu.h>
Public Member Functions
ViewMenu (Display *eve, const std::string &title)
Standard constructor.
virtual ~ViewMenu ()
Default destructor.
virtual void Build (TGMenuBar *bar, int hints=kLHintsNormal)
Add the menu to the menu bar.
void BuildView (View *view) const
Import Geometry data and build the view.
void CreateView (TGMenuEntry *e, void *ud)
Menu callback: Create a generic view using the user data.
View * CreateView (const std::string &type, const std::string &title)
Create a generic view of a given type with title.
View * CreateView3D (const std::string &title)
Specialization: Create a new 3D view.
View * CreateRhoZProjection (const std::string &title)
Specialization: Create a new R-Z view.
View * CreateRhoPhiProjection (const std::string &title)
Specialization: Create a new R-Phi view.
ClassDef (ViewMenu, 0)
ROOT implementation macro.
Public Member Functions inherited from DD4hep::PopupMenu
PopupMenu (const TGWindow *parent)
Standard constructor.
virtual ~PopupMenu ()
Default destructor.
void HandleMenu (int id)
Handle menu items.
TGPopupMenu & menu ()
Access to implementation.
virtual void AddSeparator (TGMenuEntry *before=0)
Add a menu separator to the menu.
virtual void AddLabel (const char *s, const TGPicture *p=0, TGMenuEntry *before=0)
Add a menu label to the menu.
virtual void AddPopup (const char *s, TGPopupMenu *popup, TGMenuEntry *before=0, const TGPicture *p=0)
Add a (cascading) popup menu to a popup menu.
virtual int AddEntry (const char *name, Callback cb, void *ud=0, const TGPicture *p=0, TGMenuEntry *before=0)
Add a new popup menu entry with a callback.
template<typename T >
int AddEntry (const char *name, T *ptr, void(T::*pmf)(TGMenuEntry *, void *), void *ud=0, const TGPicture *p=0, TGMenuEntry *before=0)
Add a new popup menu entry with a callback.
void CheckEntry (int id)
Check menu entry.
void UnCheckEntry (int id)
Uncheck menu entry.
bool IsEntryChecked (int id)
Get check-value.
TGPopupMenu * operator-> ()
Public access to the popup menu using '->'.
operator TGPopupMenu * ()
Public access to the popup menu using '->'.
ClassDef (PopupMenu, 0)
Protected Attributes
Display * m_display
Reference to display manager.
std::string m_title
Menu title.
Protected Attributes inherited from DD4hep::PopupMenu
Callbacks m_calls
Callback map.
TGPopupMenu m_popup
int m_cmd
Additional Inherited Members
Public Types inherited from DD4hep::PopupMenu
typedef std::map< int, Callback > Callbacks
Detailed Description
class ViewMenu ViewMenu.h DDEve/ViewMenu.h
Definition at line 37 of file ViewMenu.h.
Constructor & Destructor Documentation
ViewMenu()
DD4hep::ViewMenu::ViewMenu (Display * eve, const std::string & title)
Standard constructor.
~ViewMenu()
ViewMenu::~ViewMenu () virtual
Default destructor.
Definition at line 50 of file ViewMenu.cpp.
Member Function Documentation
Build()
void ViewMenu::Build (TGMenuBar * bar, int hints = kLHintsNormal) virtual
Add the menu to the menu bar.
Reimplemented from DD4hep::PopupMenu.
Definition at line 55 of file ViewMenu.cpp.
References DD4hep::PopupMenu::AddEntry(), DD4hep::DisplayConfiguration::Config::name, DD4hep::DisplayConfiguration::ViewConfig::type, and v.
BuildView()
void ViewMenu::BuildView (View * view) const
Import Geometry data and build the view.
Import Geometry data.
Definition at line 98 of file ViewMenu.cpp.
References DD4hep::View::Build(), DD4hep::View::ConfigureEventFromInfo(), DD4hep::View::ConfigureGeometryFromInfo(), DD4hep::View::Initialize(), m, and slot.
ClassDef()
DD4hep::ViewMenu::ClassDef (ViewMenu , 0)
ROOT implementation macro.
CreateRhoPhiProjection()
View * ViewMenu::CreateRhoPhiProjection (const std::string & title)
Specialization: Create a new R-Phi view.
Create a new R-Phi view.
Definition at line 93 of file ViewMenu.cpp.
CreateRhoZProjection()
View * ViewMenu::CreateRhoZProjection (const std::string & title)
Specialization: Create a new R-Z view.
Create a new R-Z view.
Definition at line 88 of file ViewMenu.cpp.
CreateView() [1/2]
void ViewMenu::CreateView (TGMenuEntry * e, void * ud)
Menu callback: Create a generic view using the user data.
Create a new generic view.
Definition at line 70 of file ViewMenu.cpp.
CreateView() [2/2]
View * ViewMenu::CreateView (const std::string & type, const std::string & title)
Create a generic view of a given type with title.
Definition at line 75 of file ViewMenu.cpp.
References v.
CreateView3D()
View * ViewMenu::CreateView3D (const std::string & title)
Specialization: Create a new 3D view.
Create a new 3D view.
Definition at line 83 of file ViewMenu.cpp.
Member Data Documentation
m_display
Display* DD4hep::ViewMenu::m_display protected
Reference to display manager.
Definition at line 42 of file ViewMenu.h.
m_title
std::string DD4hep::ViewMenu::m_title protected
Menu title.
Definition at line 44 of file ViewMenu.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/ViewMenu.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/ViewMenu.cpp