DD4hep: DD4hep::Geometry::IntersectionSolid Class Reference
DD4hep::Geometry::IntersectionSolid Class Reference
DD4hep::Geometry components, classes and objects
Class describing boolean intersection solid.
#include <Shapes.h>
Public Member Functions
IntersectionSolid ()=default
Default constructor.
IntersectionSolid (const IntersectionSolid &e)=default
Constructor to be used when passing an already created object.
template<typename Q >
IntersectionSolid (const Handle< Q > &e)
Constructor to be used when passing an already created object.
IntersectionSolid (const Solid &shape1, const Solid &shape2)
Constructor to create a new object. Position is identity, Rotation is identity-rotation!
IntersectionSolid (const Solid &shape1, const Solid &shape2, const Position &pos)
Constructor to create a new object. Placement by position, Rotation is identity-rotation!
IntersectionSolid (const Solid &shape1, const Solid &shape2, const RotationZYX &rot)
Constructor to create a new object. Placement by a RotationZYX within the mother.
IntersectionSolid (const Solid &shape1, const Solid &shape2, const Rotation3D &rot)
Constructor to create a new object. Placement by a generic rotoation within the mother.
IntersectionSolid (const Solid &shape1, const Solid &shape2, const Transform3D &pos)
Constructor to create a new object. Placement by a generic transformation within the mother.
IntersectionSolid & operator= (const IntersectionSolid &copy)=default
Assignment operator.
Public Member Functions inherited from DD4hep::Geometry::BooleanSolid
template<typename Q >
BooleanSolid (const Handle< Q > &e)
Constructor to be used when passing an already created object.
BooleanSolid & operator= (const BooleanSolid &copy)=default
Assignment operator.
Public Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoCompositeShape >
Solid_type ()=default
Default constructor for uninitialized object.
Solid_type (const Solid_type &e)=default
Constructor to be used when passing an already created object.
Solid_type (TGeoCompositeShape *p)
Direct assignment using the implementation pointer.
Solid_type (const Handle< TGeoCompositeShape > &e)
Constructor to be used when passing an already created object.
Solid_type (const Handle< Q > &e)
Constructor to be used when passing an already created object: need to check pointers.
Solid_type & operator= (const Solid_type &copy)=default
Assignment operator.
const char * name () const
Access to shape name.
operator TGeoCompositeShape * () const
Auto conversion to underlying ROOT object.
TGeoCompositeShape * operator-> () const
Overloaded operator -> to access underlying object.
std::string toString (int precision=2) const
Conversion to string for pretty print.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Additional Inherited Members
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Protected Types inherited from DD4hep::Geometry::Solid_type< TGeoCompositeShape >
typedef TGeoCompositeShape Implementation
Protected Member Functions inherited from DD4hep::Geometry::BooleanSolid
BooleanSolid ()=default
Default constructor.
BooleanSolid (const BooleanSolid &b)=default
Constructor to be used when passing an already created object.
Protected Member Functions inherited from DD4hep::Geometry::Solid_type< TGeoCompositeShape >
void _setDimensions (double *param)
void _assign (TGeoCompositeShape *n, const std::string &nam, const std::string &tit, bool cbbox)
Assign pointrs and register solid to geometry.
Detailed Description
Class describing boolean intersection solid.
For any further documentation please see the following ROOT documentation:
See also
http://root.cern.ch/root/html/TGeoCompositeShape.html
http://root.cern.ch/root/html/TGeoIntersection.html
Author
M.Frank
Version
1.0
Definition at line 738 of file Shapes.h.
Constructor & Destructor Documentation
IntersectionSolid() [1/8]
DD4hep::Geometry::IntersectionSolid::IntersectionSolid () default
Default constructor.
IntersectionSolid() [2/8]
DD4hep::Geometry::IntersectionSolid::IntersectionSolid (const IntersectionSolid & e) default
Constructor to be used when passing an already created object.
IntersectionSolid() [3/8]
template<typename Q > DD4hep::Geometry::IntersectionSolid::IntersectionSolid (const Handle< Q > & e) inline
Constructor to be used when passing an already created object.
Definition at line 745 of file Shapes.h.
References DD4hep::Alignments::AlignmentTools::copy(), and DD4hep::Geometry::Solid_type< T >::operator=().
IntersectionSolid() [4/8]
IntersectionSolid::IntersectionSolid (const Solid & shape1, const Solid & shape2)
Constructor to create a new object. Position is identity, Rotation is identity-rotation!
Constructor to be used when creating a new object. Position is identity, Rotation is identity rotation.
Definition at line 494 of file Shapes.cpp.
References DD4hep::Geometry::identityTransform().
IntersectionSolid() [5/8]
IntersectionSolid::IntersectionSolid (const Solid & shape1, const Solid & shape2, const Position & pos)
Constructor to create a new object. Placement by position, Rotation is identity-rotation!
Constructor to be used when creating a new object. Position is identity.
Definition at line 506 of file Shapes.cpp.
References DD4hep::Geometry::_translation(), and DD4hep::Geometry::identityTransform().
IntersectionSolid() [6/8]
IntersectionSolid::IntersectionSolid (const Solid & shape1, const Solid & shape2, const RotationZYX & rot)
Constructor to create a new object. Placement by a RotationZYX within the mother.
Constructor to be used when creating a new object.
Definition at line 512 of file Shapes.cpp.
References DD4hep::Geometry::_rotationZYX(), and DD4hep::Geometry::identityTransform().
IntersectionSolid() [7/8]
IntersectionSolid::IntersectionSolid (const Solid & shape1, const Solid & shape2, const Rotation3D & rot)
Constructor to create a new object. Placement by a generic rotoation within the mother.
Constructor to be used when creating a new object.
Definition at line 518 of file Shapes.cpp.
References DD4hep::Geometry::_rotation3D(), and DD4hep::Geometry::identityTransform().
IntersectionSolid() [8/8]
IntersectionSolid::IntersectionSolid (const Solid & shape1, const Solid & shape2, const Transform3D & pos)
Constructor to create a new object. Placement by a generic transformation within the mother.
Constructor to be used when creating a new object. Placement by a generic transformation within the mother.
Definition at line 500 of file Shapes.cpp.
References DD4hep::Geometry::_transform(), and DD4hep::Geometry::identityTransform().
Member Function Documentation
operator=()
IntersectionSolid& DD4hep::Geometry::IntersectionSolid::operator= (const IntersectionSolid & copy) default
Assignment operator.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Shapes.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Shapes.cpp