DD4hep: DD4hep::Geometry::VolumeManager Class Reference
DD4hep::Geometry::VolumeManager Class Reference
DD4hep::Geometry components, classes and objects
Class to support the retrieval of detector elements and volumes given a valid identifier.
#include <VolumeManager.h>
Public Types
enum PopulateFlags { NONE = 0, TREE = 1 << 1, ONE = 1 << 2, LAST }
typedef DD4hep::VolumeID VolumeID
typedef VolumeID VolIdentifier
typedef VolumeManagerObject Object
Some useful Container abbreviations used by the VolumeManager.
typedef VolumeManagerContext Context
typedef std::map< VolumeID, VolumeManager > Managers
typedef std::map< DetElement, VolumeManager > Detectors
typedef std::map< VolumeID, VolumeManagerContext * > Volumes
typedef PlacedVolume::VolIDs VolIDs
typedef std::map< TGeoNode *, Context * > PhysVolumes
Public Types inherited from DD4hep::Handle< T >
typedef T Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
VolumeManager ()
Default constructor.
VolumeManager (const VolumeManager &e)
Constructor to be used when reading the already parsed object.
VolumeManager (const Handle< VolumeManagerObject > &e)
Constructor to be used when reading the already parsed object.
template<typename Q >
VolumeManager (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
VolumeManager (LCDD &lcdd, const std::string &name, DetElement world=DetElement(), Readout ro=Readout(), int flags=NONE)
Initializing constructor to create a new object.
VolumeManager (DetElement subdetector, Readout ro)
Initializing constructor for subdetector volume managers.
VolumeManager & operator= (const VolumeManager &m)
Assignment operator.
VolumeManager addSubdetector (DetElement detector, Readout ro)
Add a new Volume manager section according to a new subdetector.
VolumeManager subdetector (VolumeID id) const
Access the volume manager by cell id.
DetElement detector () const
Access the top level detector element.
IDDescriptor idSpec () const
Access IDDescription structure.
bool adoptPlacement (Context *context)
Register physical volume with the manager (normally: section manager)
bool adoptPlacement (VolumeID volume_id, Context *context)
Register physical volume with the manager and pre-computed volume id.
Context * lookupContext (VolumeID volume_id) const
Lookup the context, which belongs to a registered physical volume.
PlacedVolume lookupPlacement (VolumeID volume_id) const
Lookup a physical (placed) volume identified by its 64 bit hit ID.
DetElement lookupDetector (VolumeID volume_id) const
Lookup a top level subdetector detector element according to a contained 64 bit hit ID.
DetElement lookupDetElement (VolumeID volume_id) const
Lookup the closest subdetector detector element in the hierarchy according to a contained 64 bit hit ID.
const TGeoMatrix & worldTransformation (VolumeID volume_id) const
Access the transformation of a physical volume to the world coordinate system.
Public Member Functions inherited from DD4hep::Handle< T >
Handle ()
Defaulot constructor.
Handle (T *e)
Initializing constructor from pointer.
Handle (const Handle< T > &e)=default
Copy constructor.
template<typename Q >
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
template<typename Q >
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< T > & operator= (const Handle< T > &e)=default
Assignment operator.
bool operator== (const Handle< T > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< T > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< T > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< T > & clear ()
Release the object held by the handle.
T * operator-> () const
Access the held object using the -> operator.
operator T & () const
Automatic type conversion to an object references.
T & operator* () const
Access the held object using the * operator.
T * ptr () const
Access to the held object.
template<typename Q >
Q * _ptr () const
Access to an unrelated object type.
template<typename Q >
Q * data () const
Access to an unrelated object type.
template<typename Q >
Q & object () const
Access to an unrelated object type.
T * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
template<>
void assign (_Segmentation *s, const std::string &n, const std::string &)
template<>
const char * name () const
Protected Member Functions
Object & _data () const
Additional data accessor.
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< T >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< T >
T * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Class to support the retrieval of detector elements and volumes given a valid identifier.
The VolumeManager manages the repository of sensitive physical volumes (placements). These volumes can then be accessed together with basic other elements, such as the top level Detector element of the subdetector or the coordinate trasformation to world coordinates. The basic key to access this information is the 'VolumeID', a 64 bit number, which uniquely identifies a placement.
There are 2 working modes:
1) Starting from the top level element, the next level is addressed separately and the volumes are stored in a 2-level 'tree'. Placements this way are partitioned e.g. 'by subdetector'. This tries to keep the number of mapped elements at a reasonable level.
2) All placements are mapped to the top-level element. Good for small setups. Note, that the system field of all IDDescriptors of the subdetectors must have the same length to ensure the uniqueness of the placement keys.
By default the volume manager in TREE mode (-> 1)) is attached to the LCDD instance and also managed by this instance. If you wish to create instances yourself, you must ensure that the handle is destroyed once no other references are present. [call DestroyHandle(VolumeManager)]
Author
M.Frank
Version
1.0
Definition at line 70 of file VolumeManager.h.
Member Typedef Documentation
Context
typedef VolumeManagerContext DD4hep::Geometry::VolumeManager::Context
Definition at line 85 of file VolumeManager.h.
Detectors
typedef std::map<DetElement, VolumeManager> DD4hep::Geometry::VolumeManager::Detectors
Definition at line 87 of file VolumeManager.h.
Managers
typedef std::map<VolumeID, VolumeManager> DD4hep::Geometry::VolumeManager::Managers
Definition at line 86 of file VolumeManager.h.
Object
typedef VolumeManagerObject DD4hep::Geometry::VolumeManager::Object
Some useful Container abbreviations used by the VolumeManager.
Definition at line 84 of file VolumeManager.h.
PhysVolumes
typedef std::map<TGeoNode*, Context*> DD4hep::Geometry::VolumeManager::PhysVolumes
Definition at line 90 of file VolumeManager.h.
VolIdentifier
typedef VolumeID DD4hep::Geometry::VolumeManager::VolIdentifier
Definition at line 73 of file VolumeManager.h.
VolIDs
typedef PlacedVolume::VolIDs DD4hep::Geometry::VolumeManager::VolIDs
Definition at line 89 of file VolumeManager.h.
VolumeID
typedef DD4hep::VolumeID DD4hep::Geometry::VolumeManager::VolumeID
Definition at line 72 of file VolumeManager.h.
Volumes
typedef std::map<VolumeID, VolumeManagerContext*> DD4hep::Geometry::VolumeManager::Volumes
Definition at line 88 of file VolumeManager.h.
Member Enumeration Documentation
PopulateFlags
enum DD4hep::Geometry::VolumeManager::PopulateFlags
Enumerator
NONE
TREE
ONE
LAST
Definition at line 75 of file VolumeManager.h.
Constructor & Destructor Documentation
VolumeManager() [1/6]
DD4hep::Geometry::VolumeManager::VolumeManager () inline
Default constructor.
Definition at line 100 of file VolumeManager.h.
Referenced by VolumeManager().
VolumeManager() [2/6]
DD4hep::Geometry::VolumeManager::VolumeManager (const VolumeManager & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 104 of file VolumeManager.h.
References e, DD4hep::Handle< T >::name(), NONE, subdetector(), and VolumeManager().
VolumeManager() [3/6]
DD4hep::Geometry::VolumeManager::VolumeManager (const Handle< VolumeManagerObject > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 109 of file VolumeManager.h.
VolumeManager() [4/6]
template<typename Q > DD4hep::Geometry::VolumeManager::VolumeManager (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 114 of file VolumeManager.h.
VolumeManager() [5/6]
VolumeManager::VolumeManager (LCDD & lcdd, const std::string & name, DetElement world = DetElement(), Readout ro = Readout(), int flags = NONE)
Initializing constructor to create a new object.
Initializing constructor. The tree will automatically be built if the detelement is valid Please see enum PopulateFlags for further info. No action whatsoever is performed here, if the detector element is not valid.
Definition at line 424 of file VolumeManager.cpp.
References DD4hep::Geometry::VolumeManagerObject::detector, DD4hep::Geometry::VolumeManagerObject::flags, DD4hep::Geometry::VolumeManagerObject::id, DD4hep::Geometry::Readout::idSpec(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::printout(), and DD4hep::Geometry::VolumeManagerObject::top.
VolumeManager() [6/6]
VolumeManager::VolumeManager (DetElement subdetector, Readout ro)
Initializing constructor for subdetector volume managers.
Initializing constructor to create a new object.
Definition at line 440 of file VolumeManager.cpp.
References DD4hep::Geometry::VolumeManagerObject::detector, DD4hep::Geometry::VolumeManagerObject::id, DD4hep::Geometry::Readout::idSpec(), DD4hep::Handle< T >::isValid(), and DD4hep::Handle< T >::name().
Member Function Documentation
_data()
Object& DD4hep::Geometry::VolumeManager::_data () const inline protected
Additional data accessor.
Definition at line 94 of file VolumeManager.h.
References DD4hep::Handle< T >::ptr().
Referenced by addSubdetector().
addSubdetector()
VolumeManager VolumeManager::addSubdetector (DetElement detector, Readout ro)
Add a new Volume manager section according to a new subdetector.
Definition at line 448 of file VolumeManager.cpp.
References _data(), _data(), DD4hep::Geometry::DetElement::callAtUpdate(), DD4hep::Geometry::VolumeManagerObject::detMask, DD4hep::Geometry::IDDescriptor::field(), DD4hep::Geometry::PlacedVolumeExtension::VolIDs::find(), DD4hep::Geometry::VolumeManagerObject::flags, DD4hep::Geometry::Readout::idSpec(), DD4hep::Handle< T >::isValid(), m, DD4hep::Geometry::VolumeManagerObject::managers, DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), DD4hep::Geometry::VolumeManagerObject::subdetectors, DD4hep::Geometry::VolumeManagerObject::sysID, DD4hep::Geometry::VolumeManagerObject::system, DD4hep::Geometry::VolumeManagerObject::top, and DD4hep::Geometry::PlacedVolume::volIDs().
Referenced by operator=().
adoptPlacement() [1/2]
bool VolumeManager::adoptPlacement (Context * context)
Register physical volume with the manager (normally: section manager)
Definition at line 591 of file VolumeManager.cpp.
References _data(), adoptPlacement(), DD4hep::Geometry::VolumeManagerObject::detector, DD4hep::Geometry::VolumeManagerObject::flags, DD4hep::Geometry::VolumeManagerContext::identifier, DD4hep::Geometry::VolumeManagerObject::managers, DD4hep::Handle< T >::name(), DD4hep::Geometry::VolumeManagerObject::sysID, DD4hep::Geometry::VolumeManagerObject::system, DD4hep::Geometry::VolumeManagerObject::top, and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by adoptPlacement(), and operator=().
adoptPlacement() [2/2]
bool VolumeManager::adoptPlacement (VolumeID volume_id, Context * context)
Register physical volume with the manager and pre-computed volume id.
Register physical volume with the manager (normally: section manager)
Definition at line 531 of file VolumeManager.cpp.
References _data(), DD4hep::Geometry::VolumeManagerObject::detector, DD4hep::Geometry::VolumeManagerObject::detMask, DD4hep::ERROR, DD4hep::Geometry::VolumeManagerContext::identifier, DD4hep::Geometry::Volume::isSensitive(), DD4hep::Geometry::VolumeManagerContext::mask, DD4hep::Handle< T >::name(), DD4hep::Geometry::VolumeManagerContext::placement, DD4hep::printout(), DD4hep::Handle< T >::ptr(), DD4hep::VERBOSE, DD4hep::Geometry::VolumeManagerContext::volID, DD4hep::Geometry::PlacedVolume::volume(), DD4hep::Geometry::VolumeManagerObject::volumes, and DD4hep::yes_no().
detector()
DetElement VolumeManager::detector () const
Access the top level detector element.
Definition at line 518 of file VolumeManager.cpp.
References _data().
Referenced by operator=().
idSpec()
IDDescriptor VolumeManager::idSpec () const
Access IDDescription structure.
Definition at line 526 of file VolumeManager.cpp.
References _data().
Referenced by operator=().
lookupContext()
VolumeManager::Context * VolumeManager::lookupContext (VolumeID volume_id) const
Lookup the context, which belongs to a registered physical volume.
This set of functions is required when reading/analyzing already created hits which have a VolumeID attached.
First look in our own volume cache if the entry is found.
Second: look in the subdetector volume cache if the entry is found.
Definition at line 630 of file VolumeManager.cpp.
References _data(), DD4hep::Geometry::VolumeManagerObject::flags, lookupContext(), DD4hep::Geometry::VolumeManagerObject::search(), DD4hep::Geometry::VolumeManagerObject::subdetectors, and DD4hep::Geometry::VolumeManagerObject::top.
Referenced by lookupContext(), and operator=().
lookupDetector()
DetElement VolumeManager::lookupDetector (VolumeID volume_id) const
Lookup a top level subdetector detector element according to a contained 64 bit hit ID.
Definition at line 667 of file VolumeManager.cpp.
References DD4hep::Geometry::VolumeManagerContext::detector.
Referenced by operator=(), and DD4hep::DDRec::IDDecoder::subDetector().
lookupDetElement()
DetElement VolumeManager::lookupDetElement (VolumeID volume_id) const
Lookup the closest subdetector detector element in the hierarchy according to a contained 64 bit hit ID.
Definition at line 673 of file VolumeManager.cpp.
References DD4hep::Geometry::VolumeManagerContext::element.
Referenced by DD4hep::DDRec::IDDecoder::detectorElement(), and operator=().
lookupPlacement()
PlacedVolume VolumeManager::lookupPlacement (VolumeID volume_id) const
Lookup a physical (placed) volume identified by its 64 bit hit ID.
Definition at line 661 of file VolumeManager.cpp.
References DD4hep::Geometry::VolumeManagerContext::placement.
Referenced by DD4hep::Simulation::Geant4ConversionHelper::encoding(), operator=(), and DD4hep::DDRec::IDDecoder::placement().
operator=()
VolumeManager& DD4hep::Geometry::VolumeManager::operator= (const VolumeManager & m) inline
Assignment operator.
Definition at line 127 of file VolumeManager.h.
References addSubdetector(), adoptPlacement(), detector(), idSpec(), lookupContext(), lookupDetector(), lookupDetElement(), lookupPlacement(), m, DD4hep::Handle< T >::m_element, DD4hep::Geometry::operator<<(), subdetector(), and worldTransformation().
subdetector()
VolumeManager VolumeManager::subdetector (VolumeID id) const
Access the volume manager by cell id.
Need to perform a linear search, because the "system" tag width may vary between subdetectors
Definition at line 499 of file VolumeManager.cpp.
References _data(), DD4hep::DDSegmentation::BitFieldValue::offset(), DD4hep::Geometry::VolumeManagerObject::subdetectors, DD4hep::Geometry::VolumeManagerObject::sysID, DD4hep::Geometry::VolumeManagerObject::system, and DD4hep::DDSegmentation::BitFieldValue::value().
Referenced by operator=(), and VolumeManager().
worldTransformation()
const TGeoMatrix & VolumeManager::worldTransformation (VolumeID volume_id) const
Access the transformation of a physical volume to the world coordinate system.
Definition at line 679 of file VolumeManager.cpp.
References DD4hep::Geometry::VolumeManagerContext::toWorld.
Referenced by operator=().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/VolumeManager.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/VolumeManager.cpp