DD4hep: DD4hep::Conditions::ConditionsManagerObject Class Reference
DD4hep::Conditions::ConditionsManagerObject Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Conditions internal namespace declaration.
#include <ConditionsInterna.h>
Public Types
typedef dd4hep_ptr< ConditionsDataLoader > Loader
typedef std::vector< IOVType > IOVTypes
typedef std::vector< ConditionsIOVPool * > TypedConditionPool
typedef std::pair< ConditionsListener *, void * > Listener
typedef std::set< Listener > Listeners
typedef ConditionsManager::Dependencies Dependencies
typedef ConditionsManager::ConditionKeys ConditionKeys
typedef Condition::key_type key_type
typedef Condition::iov_type iov_type
Public Types inherited from DD4hep::ObjectExtensions
typedef std::map< const std::type_info *, void * > Extensions
Definition of the extension type.
typedef void *(* copy_t) (const void *, void *arg)
Extensions copy constructor type.
typedef void(* destruct_t) (void *)
Extensions destructor type.
typedef std::map< const std::type_info *, Entry > ExtensionMap
Public Member Functions
Condition __queue_update (Conditions::Entry *data)
ConditionsManagerObject (LCDD &lcdd)
Standard constructor.
virtual ~ConditionsManagerObject ()
Default destructor.
LCDD & lcdd () const
Access to the detector description instance.
const TypedConditionPool & conditionsPool () const
Access to managed pool of typed conditions indexed by IOV-type and IOV key.
ConditionsDataLoader * loader () const
void initialize ()
void callOnRegister (const Listener &callee, bool add)
(Un)Registration of conditions listeners with callback when a new condition is registered
void callOnRemove (const Listener &callee, bool add)
(Un)Registration of conditions listeners with callback when a condition is unregistered
std::pair< bool, const IOVType * > registerIOVType (size_t iov_type, const std::string &iov_name)
Register new IOV type if it does not (yet) exist.
const IOVTypes & iovTypes () const
Access IOV by its type.
const IOVType * iovType (size_t iov_type) const
Access IOV by its type.
const IOVType * iovType (const std::string &iov_name) const
Access IOV by its name.
void fromString (const std::string &iov_str, IOV &iov)
Create IOV from string.
ConditionsPool * registerIOV (const std::string &data)
Register IOV using new string data.
ConditionsPool * registerIOV (const IOVType &typ, IOV::Key key)
Register IOV with type and key.
bool registerUnlocked (ConditionsPool *pool, Condition cond)
Register new condition with the conditions store. Unlocked version, not multi-threaded.
long prepare (const IOV &required_validity, const ConditionKeys &keys, dd4hep_ptr< UserPool > &user_pool)
Prepare all updates for the given keys to the clients with the defined IOV.
long prepare (const IOV &required_validity, const ConditionKeys &keys, dd4hep_ptr< UserPool > &user_pool, const Dependencies &dependencies, bool verify_dependencies=true)
Prepare all updates for the given keys to the clients with the defined IOV.
long prepare (const IOV &required_validity, dd4hep_ptr< UserPool > &user_pool)
Prepare all updates to the clients with the defined IOV.
long prepare (const IOV &required_validity, dd4hep_ptr< UserPool > &user_pool, const Dependencies &dependencies, bool verify_dependencies=true)
Prepare all updates to the clients with the defined IOV.
int clean (const IOVType *typ, int max_age)
Clean conditions, which are above the age limit.
std::pair< int, int > clear ()
Full cleanup of all managed conditions.
void pushUpdates ()
Push all pending updates to the conditions store.
void registerCondition (Condition c)
Register a new managed condition.
Condition get (key_type key, const iov_type &req_validity)
Retrieve a condition set given a Detector Element and the conditions name according to their validity.
RangeConditions getRange (key_type key, const iov_type &req_validity)
Retrieve a condition given a Detector Element and the conditions name.
Public Member Functions inherited from DD4hep::NamedObject
NamedObject ()
Standard constructor.
NamedObject (const char *nam, const char *typ="")
Initializing constructor.
NamedObject (const std::string &nam)
Initializing constructor.
NamedObject (const std::string &nam, const std::string &typ)
Initializing constructor.
NamedObject (const NamedObject &c)
Copy constructor.
virtual ~NamedObject ()
Default destructor.
NamedObject & operator= (const NamedObject &c)
Assignment operator.
const char * GetName () const
Access name.
void SetName (const char *nam)
Set name (used by Handle)
void SetTitle (const char *tit)
Set Title (used by Handle)
const char * GetTitle () const
Get name (used by Handle)
Public Member Functions inherited from DD4hep::PropertyConfigurable
PropertyConfigurable ()
Standard constructor.
virtual ~PropertyConfigurable ()
Default destructor.
PropertyManager & properties ()
Access to the properties of the object.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
template<typename T >
void declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
void declareProperty (const char *nam, T &val)
Declare property.
Public Member Functions inherited from DD4hep::ObjectExtensions
ObjectExtensions (const std::type_info &parent_type)
Default constructor.
ObjectExtensions (const ObjectExtensions &copy)=delete
Copy constructor.
virtual ~ObjectExtensions ()
Default destructor.
ObjectExtensions & operator= (const ObjectExtensions &copy)=delete
Assignment operator.
void move (ObjectExtensions &copy)
Move extensions to target object.
void clear (bool destroy=true)
Clear all extensions.
void copyFrom (const Extensions &ext, void *arg)
Copy object extensions from another object. Hosting type must be identical!
void * addExtension (void *ptr, const std::type_info &info, copy_t ctor, destruct_t dtor)
Add an extension object to the detector element.
void * addExtension (void *ptr, const std::type_info &info, destruct_t dtor)
Add an extension object to the detector element.
void * removeExtension (const std::type_info &info, bool destroy)
Remove an existing extension object from the instance.
void * extension (const std::type_info &info, bool alert) const
Access an existing extension object from the detector element.
void * extension (const std::type_info &info) const
Access an existing extension object from the detector element.
Public Attributes
int m_maxIOVTypes
Property: maximal number of IOV types to be handled.
std::string m_poolType
Property: ConditionsPool constructor type (default: empty. MUST BE SET!)
std::string m_updateType
Property: UpdatePool constructor type (default: DD4hep_ConditionsLinearUpdatePool)
std::string m_userType
Property: UserPool constructor type (default: DD4hep_ConditionsLinearUserPool)
std::string m_loaderType
Property: Conditions loader type (default: "multi" -> DD4hep_Conditions_multi_Loader)
LCDD & m_lcdd
Reference to main detector description object.
IOVTypes m_iovTypes
Collection of IOV types managed.
TypedConditionPool m_rawPool
Managed pool of typed conditions indexed by IOV-type and IOV key.
Listeners m_onRegister
Conditions listeners on registration of new conditions.
Listeners m_onRemove
Conditions listeners on de-registration of new conditions.
dd4hep_mutex_t m_updateLock
Lock to protect the update/delayed conditions pool.
dd4hep_mutex_t m_poolLock
Lock to protect the pool of all known conditions.
Loader m_loader
Reference to data loader.
dd4hep_ptr< UpdatePool > m_updatePool
Reference to update conditions pool.
int locked
Public access: if locked, DetElements stay intact and are not altered.
Public Attributes inherited from DD4hep::NamedObject
std::string name
The object name.
std::string type
The object type.
Public Attributes inherited from DD4hep::ObjectExtensions
Extensions extensions
The extensions object.
ExtensionMap * extensionMap
Pointer to the extension map.
Protected Member Functions
bool select (key_type key, const iov_type &req_validity, RangeConditions &conditions)
Retrieve a condition set given a Detector Element and the conditions name according to their validity.
bool select_range (key_type key, const iov_type &req_validity, RangeConditions &conditions)
Retrieve a condition set given a Detector Element and the conditions name according to their validity.
void registerCallee (Listeners &listeners, const Listener &callee, bool add)
Register a set of new managed condition for an IOV range. Called by __load_immediate.
void onRegister (Condition condition)
Listener invocation when a condition is registered to the cache.
void onRemove (Condition condition)
Listener invocation when a condition is deregistered from the cache.
void __get_checked_pool (const IOV &required_validity, dd4hep_ptr< UserPool > &user_pool)
Helper to check iov and user pool and create user pool if not present.
Friends
class DD4hep::Conditions::ConditionsPool
class DD4hep::Conditions::ConditionsDataLoader
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::ObjectExtensions
static void _noDelete (void *)
Function to be passed as dtor if object should NOT be deleted!
template<typename T >
static void _delete (void *ptr)
Templated destructor function.
Protected Attributes inherited from DD4hep::PropertyConfigurable
PropertyManager m_properties
Property pool.
Detailed Description
Conditions internal namespace declaration.
Internally defined datastructures are not presented to the user directly, but are used by dedicated views.
Author
M.Frank
Version
1.0The data class behind a conditions manager handle For convenience, the class definition is here. See ConditionsManager.cpp for the implementation.
Author
M.Frank
Version
1.0
Definition at line 64 of file ConditionsInterna.h.
Member Typedef Documentation
ConditionKeys
typedef ConditionsManager::ConditionKeys DD4hep::Conditions::ConditionsManagerObject::ConditionKeys
Definition at line 78 of file ConditionsInterna.h.
Dependencies
typedef ConditionsManager::Dependencies DD4hep::Conditions::ConditionsManagerObject::Dependencies
Definition at line 77 of file ConditionsInterna.h.
iov_type
typedef Condition::iov_type DD4hep::Conditions::ConditionsManagerObject::iov_type
Definition at line 80 of file ConditionsInterna.h.
IOVTypes
typedef std::vector<IOVType> DD4hep::Conditions::ConditionsManagerObject::IOVTypes
Definition at line 73 of file ConditionsInterna.h.
key_type
typedef Condition::key_type DD4hep::Conditions::ConditionsManagerObject::key_type
Definition at line 79 of file ConditionsInterna.h.
Listener
typedef std::pair<ConditionsListener*,void*> DD4hep::Conditions::ConditionsManagerObject::Listener
Definition at line 75 of file ConditionsInterna.h.
Listeners
typedef std::set<Listener> DD4hep::Conditions::ConditionsManagerObject::Listeners
Definition at line 76 of file ConditionsInterna.h.
Loader
typedef dd4hep_ptr<ConditionsDataLoader> DD4hep::Conditions::ConditionsManagerObject::Loader
Definition at line 72 of file ConditionsInterna.h.
TypedConditionPool
typedef std::vector<ConditionsIOVPool*> DD4hep::Conditions::ConditionsManagerObject::TypedConditionPool
Definition at line 74 of file ConditionsInterna.h.
Constructor & Destructor Documentation
ConditionsManagerObject()
ConditionsManagerObject::ConditionsManagerObject (LCDD & lcdd)
Standard constructor.
Definition at line 137 of file ConditionsInterna.cpp.
References DD4hep::PropertyConfigurable::declareProperty(), DD4hep::InstanceCount::increment(), m_iovTypes, m_loaderType, m_maxIOVTypes, m_poolType, m_rawPool, m_updateType, and m_userType.
~ConditionsManagerObject()
ConditionsManagerObject::~ConditionsManagerObject () virtual
Default destructor.
Definition at line 154 of file ConditionsInterna.cpp.
References DD4hep::InstanceCount::decrement(), m_lcdd, m_rawPool, DD4hep::Conditions::ConditionsLoader::release(), DD4hep::Alignments::AlignmentsLoader::release(), and DD4hep::Geometry::LCDD::world().
Member Function Documentation
__get_checked_pool()
void ConditionsManagerObject::__get_checked_pool (const IOV & required_validity, dd4hep_ptr< UserPool > & user_pool) protected
Helper to check iov and user pool and create user pool if not present.
Definition at line 450 of file ConditionsInterna.cpp.
References DD4hep::dd4hep_ptr< T >::adopt(), DD4hep::except(), DD4hep::Errors::invalidArg(), m_lcdd, m_rawPool, m_userType, and DD4hep::IOVType::type.
Referenced by prepare().
__queue_update()
Condition ConditionsManagerObject::__queue_update (Conditions::Entry * e)
Set a single conditions value to be managed. Requires EXTERNALLY held lock on update pool!
Set a single conditions value to be managed. Requires external lock on update pool!
Definition at line 344 of file ConditionsInterna.cpp.
References DD4hep::Conditions::Interna::ConditionObject::address, DD4hep::Conditions::Interna::ConditionObject::comment, DD4hep::Conditions::Entry::detector, DD4hep::INFO, DD4hep::Conditions::ConditionsPool::insert(), DD4hep::Conditions::ConditionsPool::iov, DD4hep::Conditions::Interna::ConditionObject::iov, DD4hep::NamedObject::name, DD4hep::Geometry::DetElement::path(), DD4hep::Conditions::Interna::ConditionObject::pool, DD4hep::printout(), DD4hep::Handle< T >::ptr(), registerIOV(), DD4hep::NamedObject::type, DD4hep::Conditions::Entry::validity, DD4hep::Conditions::Interna::ConditionObject::validity, DD4hep::Conditions::Entry::value, and DD4hep::Conditions::Interna::ConditionObject::value.
callOnRegister()
void ConditionsManagerObject::callOnRegister (const Listener & callee, bool add)
(Un)Registration of conditions listeners with callback when a new condition is registered
Definition at line 198 of file ConditionsInterna.cpp.
References m_onRegister, and registerCallee().
Referenced by loader().
callOnRemove()
void ConditionsManagerObject::callOnRemove (const Listener & callee, bool add)
(Un)Registration of conditions listeners with callback when a condition is unregistered
(Un)Registration of conditions listeners with callback when a condition is de-registered
Definition at line 203 of file ConditionsInterna.cpp.
References m_onRemove, and registerCallee().
Referenced by loader().
clean()
int ConditionsManagerObject::clean (const IOVType * typ, int max_age)
Clean conditions, which are above the age limit.
Returns
Number of conditions cleaned up and removed
Definition at line 369 of file ConditionsInterna.cpp.
References DD4hep::Conditions::ConditionsIOVPool::clean(), m_rawPool, m_updateLock, and DD4hep::IOVType::type.
Referenced by iovTypes().
clear()
pair< int, int > ConditionsManagerObject::clear ()
Full cleanup of all managed conditions.
Returns
pair<Number of pools cleared, Number of conditions cleaned up and removed>
Definition at line 380 of file ConditionsInterna.cpp.
References DD4hep::Conditions::ConditionsIOVPool::clean(), and m_rawPool.
Referenced by iovTypes().
conditionsPool()
const TypedConditionPool& DD4hep::Conditions::ConditionsManagerObject::conditionsPool () const inline
Access to managed pool of typed conditions indexed by IOV-type and IOV key.
Definition at line 153 of file ConditionsInterna.h.
References m_rawPool.
fromString()
void ConditionsManagerObject::fromString (const std::string & iov_str, IOV & iov)
Create IOV from string.
Definition at line 259 of file ConditionsInterna.cpp.
References DD4hep::except(), DD4hep::Errors::invalidArg(), DD4hep::IOV::iovType, iovType(), DD4hep::IOV::set(), and DD4hep::IOV::type.
Referenced by iovTypes(), and registerIOV().
get()
Condition ConditionsManagerObject::get (Condition::key_type key, const iov_type & req_validity)
Retrieve a condition set given a Detector Element and the conditions name according to their validity.
Retrieve a condition given a Detector Element and the conditions name.
Definition at line 607 of file ConditionsInterna.cpp.
References DD4hep::Conditions::Condition::ACTIVE, DD4hep::ERROR, DD4hep::except(), DD4hep::Conditions::Condition::iov(), m_loader, m_updateLock, DD4hep::Conditions::Condition::name(), DD4hep::printout(), select(), DD4hep::IOV::str(), and DD4hep::Conditions::Condition::value().
Referenced by DD4hep::Conditions::ConditionsLoaderImp::get(), and DD4hep::Conditions::AlignmentsLoaderImp::get().
getRange()
RangeConditions ConditionsManagerObject::getRange (Condition::key_type key, const iov_type & req_validity)
Retrieve a condition given a Detector Element and the conditions name.
Definition at line 642 of file ConditionsInterna.cpp.
References DD4hep::except(), m_loader, m_updateLock, select_range(), and DD4hep::IOV::str().
Referenced by iovTypes().
initialize()
void ConditionsManagerObject::initialize ()
Definition at line 168 of file ConditionsInterna.cpp.
References DD4hep::dd4hep_ptr< T >::adopt(), DD4hep::Geometry::World::conditionsLoader(), DD4hep::except(), m_lcdd, m_loader, m_loaderType, m_updatePool, m_updateType, DD4hep::Errors::noSys(), DD4hep::NamedObject::SetName(), and DD4hep::Geometry::LCDD::world().
Referenced by loader().
iovType() [1/2]
const IOVType * ConditionsManagerObject::iovType (size_t iov_type) const
Access IOV by its type.
Definition at line 241 of file ConditionsInterna.cpp.
References DD4hep::except(), m_iovTypes, and DD4hep::IOVType::type.
Referenced by fromString(), and iovTypes().
iovType() [2/2]
const IOVType * ConditionsManagerObject::iovType (const std::string & iov_name) const
Access IOV by its name.
Definition at line 251 of file ConditionsInterna.cpp.
References DD4hep::except(), and m_iovTypes.
iovTypes()
const IOVTypes& DD4hep::Conditions::ConditionsManagerObject::iovTypes () const inline
Access IOV by its type.
Definition at line 171 of file ConditionsInterna.h.
References clean(), clear(), fromString(), getRange(), iovType(), m_iovTypes, prepare(), pushUpdates(), registerCondition(), registerIOV(), and registerUnlocked().
Referenced by DD4hep::Conditions::ConditionsAccess::iovTypesUsed(), and DD4hep::Conditions::ConditionsManager::iovTypesUsed().
lcdd()
LCDD& DD4hep::Conditions::ConditionsManagerObject::lcdd () const inline
Access to the detector description instance.
Definition at line 150 of file ConditionsInterna.h.
References m_lcdd.
Referenced by DD4hep::Conditions::ConditionsDependencyHandler::lcdd().
loader()
ConditionsDataLoader* DD4hep::Conditions::ConditionsManagerObject::loader () const inline
Definition at line 155 of file ConditionsInterna.h.
References callOnRegister(), callOnRemove(), initialize(), and registerIOVType().
onRegister()
void ConditionsManagerObject::onRegister (Condition condition) protected
Listener invocation when a condition is registered to the cache.
Call this when a condition is registered to the cache.
Definition at line 208 of file ConditionsInterna.cpp.
References m_onRegister, and DD4hep::Conditions::ConditionsListener::onRegisterCondition().
Referenced by DD4hep::Conditions::ConditionsPool::onRegister(), and registerCondition().
onRemove()
void ConditionsManagerObject::onRemove (Condition condition) protected
Listener invocation when a condition is deregistered from the cache.
Call this when a condition is deregistered from the cache.
Definition at line 213 of file ConditionsInterna.cpp.
References m_onRemove, and DD4hep::Conditions::ConditionsListener::onRemoveCondition().
Referenced by DD4hep::Conditions::ConditionsPool::onRemove().
prepare() [1/4]
long ConditionsManagerObject::prepare (const IOV & required_validity, const ConditionKeys & keys, dd4hep_ptr< UserPool > & user_pool)
Prepare all updates for the given keys to the clients with the defined IOV.
First push any pending updates and register them to pending pools...
Now update/fill the user pool
Definition at line 469 of file ConditionsInterna.cpp.
References __get_checked_pool(), and pushUpdates().
Referenced by iovTypes(), prepare(), and pushUpdates().
prepare() [2/4]
long ConditionsManagerObject::prepare (const IOV & required_validity, const ConditionKeys & keys, dd4hep_ptr< UserPool > & user_pool, const Dependencies & dependencies, bool verify_dependencies = true)
Prepare all updates for the given keys to the clients with the defined IOV.
Definition at line 483 of file ConditionsInterna.cpp.
References prepare().
prepare() [3/4]
long ConditionsManagerObject::prepare (const IOV & required_validity, dd4hep_ptr< UserPool > & user_pool)
Prepare all updates to the clients with the defined IOV.
First push any pending updates and register them to pending pools...
Now update/fill the user pool
Definition at line 498 of file ConditionsInterna.cpp.
References __get_checked_pool(), and pushUpdates().
prepare() [4/4]
long ConditionsManagerObject::prepare (const IOV & required_validity, dd4hep_ptr< UserPool > & user_pool, const Dependencies & dependencies, bool verify_dependencies = true)
Prepare all updates to the clients with the defined IOV.
Definition at line 508 of file ConditionsInterna.cpp.
References prepare().
pushUpdates()
void ConditionsManagerObject::pushUpdates ()
Push all pending updates to the conditions store.
Note: This does not yet make the new conditions availible to the clients
Definition at line 393 of file ConditionsInterna.cpp.
References _E, DD4hep::dd4hep_ptr< T >::adopt(), DD4hep::Conditions::UserPool::clear(), DD4hep::except(), DD4hep::Conditions::UserPool::insert(), DD4hep::Errors::invalidArg(), DD4hep::IOV::invert(), m_lcdd, m_loader, m_poolLock, m_rawPool, m_updateLock, m_updatePool, m_userType, prepare(), DD4hep::IOV::reset(), DD4hep::Conditions::ConditionsIOVPool::select(), and DD4hep::IOVType::type.
Referenced by iovTypes(), and prepare().
registerCallee()
void ConditionsManagerObject::registerCallee (Listeners & listeners, const Listener & callee, bool add) protected
Register a set of new managed condition for an IOV range. Called by __load_immediate.
Definition at line 188 of file ConditionsInterna.cpp.
Referenced by callOnRegister(), and callOnRemove().
registerCondition()
void ConditionsManagerObject::registerCondition (Condition c)
Register a new managed condition.
The condition is created externally by the user. Lengthy and tedious procedure.
Definition at line 522 of file ConditionsInterna.cpp.
References DD4hep::except(), DD4hep::Conditions::ConditionsPool::insert(), DD4hep::IOV::keyData, locked, m_lcdd, m_poolLock, m_poolType, m_rawPool, onRegister(), DD4hep::Handle< T >::ptr(), and DD4hep::IOV::type.
Referenced by iovTypes().
registerIOV() [1/2]
ConditionsPool * ConditionsManagerObject::registerIOV (const std::string & data)
Register IOV using new string data.
Definition at line 293 of file ConditionsInterna.cpp.
References fromString(), DD4hep::IOV::iovType, and DD4hep::IOV::keyData.
Referenced by __queue_update(), and iovTypes().
registerIOV() [2/2]
ConditionsPool * ConditionsManagerObject::registerIOV (const IOVType & typ, IOV::Key key)
Register IOV with type and key.
Definition at line 303 of file ConditionsInterna.cpp.
References DD4hep::Conditions::ConditionsIOVPool::elements, DD4hep::Conditions::ConditionsPool::iov, m_lcdd, m_poolLock, m_poolType, m_rawPool, and DD4hep::IOVType::type.
registerIOVType()
pair< bool, const IOVType * > ConditionsManagerObject::registerIOVType (size_t iov_type, const std::string & iov_name)
Register new IOV type if it does not (yet) exist.
Returns (false,pointer) if IOV existed and (true,pointer) if new IOV was registered to the manager.
Definition at line 218 of file ConditionsInterna.cpp.
References DD4hep::except(), m_iovTypes, m_rawPool, DD4hep::IOVType::name, and DD4hep::IOVType::type.
Referenced by loader().
registerUnlocked()
bool ConditionsManagerObject::registerUnlocked (ConditionsPool * pool, Condition cond)
Register new condition with the conditions store. Unlocked version, not multi-threaded.
Definition at line 325 of file ConditionsInterna.cpp.
References DD4hep::except(), DD4hep::Conditions::ConditionsPool::insert(), DD4hep::Errors::invalidArg(), DD4hep::Conditions::ConditionsPool::iov, DD4hep::Conditions::Condition::iov(), DD4hep::Handle< T >::isValid(), m_onRegister, and DD4hep::Conditions::ConditionsListener::onRegisterCondition().
Referenced by iovTypes().
select()
bool ConditionsManagerObject::select (Condition::key_type key, const iov_type & req_validity, RangeConditions & conditions) protected
Retrieve a condition set given a Detector Element and the conditions name according to their validity.
Definition at line 551 of file ConditionsInterna.cpp.
References m_poolLock, m_rawPool, m_updateLock, m_updatePool, DD4hep::Conditions::ConditionsIOVPool::select(), and DD4hep::IOV::type.
Referenced by get().
select_range()
bool ConditionsManagerObject::select_range (Condition::key_type key, const iov_type & req_validity, RangeConditions & conditions) protected
Retrieve a condition set given a Detector Element and the conditions name according to their validity.
Definition at line 568 of file ConditionsInterna.cpp.
References DD4hep::except(), DD4hep::INFO, DD4hep::Conditions::Condition::iov(), m_poolLock, m_rawPool, m_updateLock, m_updatePool, DD4hep::Conditions::Condition::name(), DD4hep::printout(), DD4hep::Conditions::ConditionsIOVPool::selectRange(), DD4hep::IOV::str(), and DD4hep::IOV::type.
Referenced by getRange().
Friends And Related Function Documentation
DD4hep::Conditions::ConditionsDataLoader
friend class DD4hep::Conditions::ConditionsDataLoader friend
Definition at line 69 of file ConditionsInterna.h.
DD4hep::Conditions::ConditionsPool
friend class DD4hep::Conditions::ConditionsPool friend
Definition at line 68 of file ConditionsInterna.h.
Member Data Documentation
locked
int DD4hep::Conditions::ConditionsManagerObject::locked
Public access: if locked, DetElements stay intact and are not altered.
Definition at line 114 of file ConditionsInterna.h.
Referenced by registerCondition().
m_iovTypes
IOVTypes DD4hep::Conditions::ConditionsManagerObject::m_iovTypes
Collection of IOV types managed.
Definition at line 97 of file ConditionsInterna.h.
Referenced by ConditionsManagerObject(), iovType(), iovTypes(), and registerIOVType().
m_lcdd
LCDD& DD4hep::Conditions::ConditionsManagerObject::m_lcdd
Reference to main detector description object.
Definition at line 95 of file ConditionsInterna.h.
Referenced by __get_checked_pool(), initialize(), lcdd(), pushUpdates(), registerCondition(), registerIOV(), and ~ConditionsManagerObject().
m_loader
Loader DD4hep::Conditions::ConditionsManagerObject::m_loader
Reference to data loader.
Definition at line 109 of file ConditionsInterna.h.
Referenced by get(), getRange(), initialize(), and pushUpdates().
m_loaderType
std::string DD4hep::Conditions::ConditionsManagerObject::m_loaderType
Property: Conditions loader type (default: "multi" -> DD4hep_Conditions_multi_Loader)
Definition at line 92 of file ConditionsInterna.h.
Referenced by ConditionsManagerObject(), and initialize().
m_maxIOVTypes
int DD4hep::Conditions::ConditionsManagerObject::m_maxIOVTypes
Property: maximal number of IOV types to be handled.
Definition at line 84 of file ConditionsInterna.h.
Referenced by ConditionsManagerObject().
m_onRegister
Listeners DD4hep::Conditions::ConditionsManagerObject::m_onRegister
Conditions listeners on registration of new conditions.
Definition at line 101 of file ConditionsInterna.h.
Referenced by callOnRegister(), onRegister(), and registerUnlocked().
m_onRemove
Listeners DD4hep::Conditions::ConditionsManagerObject::m_onRemove
Conditions listeners on de-registration of new conditions.
Definition at line 103 of file ConditionsInterna.h.
Referenced by callOnRemove(), and onRemove().
m_poolLock
dd4hep_mutex_t DD4hep::Conditions::ConditionsManagerObject::m_poolLock
Lock to protect the pool of all known conditions.
Definition at line 107 of file ConditionsInterna.h.
Referenced by pushUpdates(), registerCondition(), registerIOV(), select(), and select_range().
m_poolType
std::string DD4hep::Conditions::ConditionsManagerObject::m_poolType
Property: ConditionsPool constructor type (default: empty. MUST BE SET!)
Definition at line 86 of file ConditionsInterna.h.
Referenced by ConditionsManagerObject(), registerCondition(), and registerIOV().
m_rawPool
TypedConditionPool DD4hep::Conditions::ConditionsManagerObject::m_rawPool
Managed pool of typed conditions indexed by IOV-type and IOV key.
Definition at line 99 of file ConditionsInterna.h.
Referenced by __get_checked_pool(), clean(), clear(), ConditionsManagerObject(), conditionsPool(), pushUpdates(), registerCondition(), registerIOV(), registerIOVType(), select(), select_range(), and ~ConditionsManagerObject().
m_updateLock
dd4hep_mutex_t DD4hep::Conditions::ConditionsManagerObject::m_updateLock
Lock to protect the update/delayed conditions pool.
Definition at line 105 of file ConditionsInterna.h.
Referenced by clean(), get(), getRange(), pushUpdates(), select(), and select_range().
m_updatePool
dd4hep_ptr<UpdatePool> DD4hep::Conditions::ConditionsManagerObject::m_updatePool
Reference to update conditions pool.
Definition at line 111 of file ConditionsInterna.h.
Referenced by initialize(), pushUpdates(), select(), and select_range().
m_updateType
std::string DD4hep::Conditions::ConditionsManagerObject::m_updateType
Property: UpdatePool constructor type (default: DD4hep_ConditionsLinearUpdatePool)
Definition at line 88 of file ConditionsInterna.h.
Referenced by ConditionsManagerObject(), and initialize().
m_userType
std::string DD4hep::Conditions::ConditionsManagerObject::m_userType
Property: UserPool constructor type (default: DD4hep_ConditionsLinearUserPool)
Definition at line 90 of file ConditionsInterna.h.
Referenced by __get_checked_pool(), ConditionsManagerObject(), and pushUpdates().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsInterna.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsInterna.cpp