DD4hep: DD4hep::XML::UriReader Class Reference
DD4hep::XML::UriReader Class Reference abstract
DD4hep::XML classes and objects
Class supporting to read data given a URI.
#include <UriReader.h>
Classes
struct UserContext
Public Member Functions
UriReader ()
Default constructor.
virtual ~UriReader ()
Default destructor.
virtual UserContext * context ()
Access to local context.
virtual bool load (const std::string &system_id, std::string &data)
Resolve a given URI to a string containing the data.
virtual bool load (const std::string &system_id, UserContext *context, std::string &data)=0
Resolve a given URI to a string containing the data with context.
virtual void parserLoaded (const std::string &system_id)
Inform reader about a locally (e.g. by XercesC) handled source load.
virtual void parserLoaded (const std::string &system_id, UserContext *ctxt)=0
Inform reader about a locally (e.g. by XercesC) handled source load.
Detailed Description
Class supporting to read data given a URI.
Interface to use entity resolvers for parsing layered XML documents Currently only supported by the XercesC interface. No support for TinyXML possible.
Author
M.Frank
Version
1.0
Definition at line 36 of file UriReader.h.
Constructor & Destructor Documentation
UriReader()
DD4hep::XML::UriReader::UriReader () inline
Default constructor.
Definition at line 45 of file UriReader.h.
References ~UriReader().
~UriReader()
DD4hep::XML::UriReader::~UriReader () virtual
Default destructor.
Definition at line 19 of file UriReader.cpp.
Referenced by UriReader().
Member Function Documentation
context()
virtual UserContext* DD4hep::XML::UriReader::context () inline virtual
Access to local context.
Reimplemented in DD4hep::XML::UriContextReader.
Definition at line 49 of file UriReader.h.
References load(), and parserLoaded().
Referenced by DD4hep::XML::UriContextReader::context(), load(), and parserLoaded().
load() [1/2]
bool DD4hep::XML::UriReader::load (const std::string & system_id, std::string & data) virtual
Resolve a given URI to a string containing the data.
Reimplemented in DD4hep::XML::UriContextReader.
Definition at line 23 of file UriReader.cpp.
References context().
Referenced by context(), DD4hep::XML::UriContextReader::context(), DD4hep::XML::DocumentHandler::load(), DD4hep::XML::UriContextReader::load(), and DD4hep::XML::DocumentHandler::system_path().
load() [2/2]
virtual bool DD4hep::XML::UriReader::load (const std::string & system_id, UserContext * context, std::string & data) pure virtual
Resolve a given URI to a string containing the data with context.
Implemented in DD4hep::XML::UriContextReader.
parserLoaded() [1/2]
void DD4hep::XML::UriReader::parserLoaded (const std::string & system_id) virtual
Inform reader about a locally (e.g. by XercesC) handled source load.
Reimplemented in DD4hep::XML::UriContextReader.
Definition at line 28 of file UriReader.cpp.
References context().
Referenced by context(), DD4hep::XML::UriContextReader::context(), DD4hep::XML::DocumentHandler::load(), and DD4hep::XML::UriContextReader::parserLoaded().
parserLoaded() [2/2]
virtual void DD4hep::XML::UriReader::parserLoaded (const std::string & system_id, UserContext * ctxt) pure virtual
Inform reader about a locally (e.g. by XercesC) handled source load.
Implemented in DD4hep::XML::UriContextReader.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/UriReader.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/UriReader.cpp