DD4hep: DD4hep::Conditions::ConditionsListener Class Reference
DD4hep::Conditions::ConditionsListener Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Base class to be implemented by objects to listen on condition callbacks.
#include <ConditionsListener.h>
Public Member Functions
ConditionsListener ()
Default constructor.
virtual ~ConditionsListener ()
Default destructor.
virtual void onRegisterIOVType (const IOVType *, void *)
ConditionsListener dummy implementation: onRegister new IOV type.
virtual void onRegisterCondition (Condition, void *)
ConditionsListener dummy implementation: onRegister new condition.
virtual void onRegisterPool (ConditionsPool *, void *)
ConditionsListener dummy implementation: onRegister new conditions pool.
virtual void onRemoveCondition (Condition, void *)
ConditionsListener dummy implementation: onRemove a condition.
virtual void onRemovePool (ConditionsPool *, void *)
ConditionsListener dummy implementation: onRemove a conditions pool.
Detailed Description
Base class to be implemented by objects to listen on condition callbacks.
Author
M.Frank
Version
1.0
Definition at line 42 of file ConditionsListener.h.
Constructor & Destructor Documentation
ConditionsListener()
ConditionsListener::ConditionsListener ()
Default constructor.
Definition at line 21 of file ConditionsListener.cpp.
~ConditionsListener()
ConditionsListener::~ConditionsListener () virtual
Default destructor.
Definition at line 25 of file ConditionsListener.cpp.
Member Function Documentation
onRegisterCondition()
virtual void DD4hep::Conditions::ConditionsListener::onRegisterCondition (Condition , void *) inline virtual
ConditionsListener dummy implementation: onRegister new condition.
Definition at line 51 of file ConditionsListener.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::onRegister(), and DD4hep::Conditions::ConditionsManagerObject::registerUnlocked().
onRegisterIOVType()
virtual void DD4hep::Conditions::ConditionsListener::onRegisterIOVType (const IOVType * , void *) inline virtual
ConditionsListener dummy implementation: onRegister new IOV type.
Definition at line 49 of file ConditionsListener.h.
onRegisterPool()
virtual void DD4hep::Conditions::ConditionsListener::onRegisterPool (ConditionsPool * , void *) inline virtual
ConditionsListener dummy implementation: onRegister new conditions pool.
Definition at line 53 of file ConditionsListener.h.
onRemoveCondition()
virtual void DD4hep::Conditions::ConditionsListener::onRemoveCondition (Condition , void *) inline virtual
ConditionsListener dummy implementation: onRemove a condition.
Definition at line 56 of file ConditionsListener.h.
Referenced by DD4hep::Conditions::ConditionsManagerObject::onRemove().
onRemovePool()
virtual void DD4hep::Conditions::ConditionsListener::onRemovePool (ConditionsPool * , void *) inline virtual
ConditionsListener dummy implementation: onRemove a conditions pool.
Definition at line 58 of file ConditionsListener.h.
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsListener.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsListener.cpp