DD4hep: DD4hep: DD4hep::Geometry::WaferGridXY Class Reference
DD4hep::Geometry::WaferGridXY Class Reference
[DD4hep::Geometry components, classes and objects]
Implementation class for the grid XZ segmentation.
#include <WaferGridXY.h>
Public Types
typedef
WaferGridXYHandle::Implementation Object
Defintiion of the basic handled object.
Public Member Functions
WaferGridXY ()
Default constructor.
WaferGridXY (const WaferGridXY &e)
Copy constructor.
WaferGridXY (const Segmentation &e)
Copy Constructor from segmentation base object.
WaferGridXY (const Handle< Object > &e)
Copy constructor from handle.
template<typename Q >
WaferGridXY (const Handle< Q > &e)
Copy constructor from other polymorph/equivalent handle.
WaferGridXY & operator= (const WaferGridXY &seg)
Assignment operator.
bool operator== (const WaferGridXY &seg) const
Equality operator.
Position position (const CellID &cellID) const
determine the position based on the cell ID
CellID cellID (const Position &local, const Position &global, const VolumeID &volID) const
determine the cell ID based on the position
double gridSizeX () const
access the grid size in X
double gridSizeY () const
access the grid size in Y
double offsetX () const
access the coordinate offset in X
double offsetY () const
access the coordinate offset in Y
double waferOffsetX (int inGroup, int inWafer) const
access the coordinate waferOffset for inGroup in X
double waferOffsetY (int inGroup, int inWafer) const
access the coordinate waferOffset for inGroup in Y
const std::string & fieldNameX () const
access the field name used for X
const std::string & fieldNameY () const
access the field name used for Y
std::vector< double > cellDimensions (const CellID &cellID) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Detailed Description
Implementation class for the grid XZ segmentation.
Concrete user handle to serve specific needs of client code which requires access to the base functionality not served by the super-class Segmentation.
Note: We only check the validity of the underlying handle. If for whatever reason the implementation object is not valid This is not checked. In principle this CANNOT happen unless some brain-dead has fiddled with the handled object directly.....
Note: The handle base corrsponding to this object in for conveniance reasons instantiated in DD4hep/src/Segmentations.cpp.
Author:
M.Frank
Version:
1.0
Definition at line 57 of file WaferGridXY.h.
Member Typedef Documentation
typedef WaferGridXYHandle::Implementation DD4hep::Geometry::WaferGridXY::Object
Defintiion of the basic handled object.
Definition at line 60 of file WaferGridXY.h.
Constructor & Destructor Documentation
DD4hep::Geometry::WaferGridXY::WaferGridXY ()
Default constructor.
DD4hep::Geometry::WaferGridXY::WaferGridXY (const WaferGridXY & e)
Copy constructor.
DD4hep::Geometry::WaferGridXY::WaferGridXY (const Segmentation & e) [inline]
Copy Constructor from segmentation base object.
Definition at line 68 of file WaferGridXY.h.
DD4hep::Geometry::WaferGridXY::WaferGridXY (const Handle< Object > & e) [inline]
Copy constructor from handle.
Definition at line 70 of file WaferGridXY.h.
template<typename Q > DD4hep::Geometry::WaferGridXY::WaferGridXY (const Handle< Q > & e) [inline]
Copy constructor from other polymorph/equivalent handle.
Definition at line 72 of file WaferGridXY.h.
Member Function Documentation
vector< double > WaferGridXY::cellDimensions (const CellID & id) const
Returns a vector<double> of the cellDimensions of the given cell ID in natural order of dimensions, e.g., dx/dy/dz, or dr/r*dPhi.
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
std::vector<double> size 2:
size in x
size in z
Returns a vector of the cellDimensions of the given cell ID
Parameters:
cellID is ignored as all cells have the same dimension
Returns:
vector<double> size 2:
size in x
size in y
Definition at line 85 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
DD4hep::CellID WaferGridXY::cellID (const Position & local, const Position & global, const VolumeID & volID) const
determine the cell ID based on the position
Definition at line 30 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
const string & WaferGridXY::fieldNameX () const
access the field name used for X
Definition at line 67 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
const string & WaferGridXY::fieldNameY () const
access the field name used for Y
Definition at line 72 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
double WaferGridXY::gridSizeX () const
access the grid size in X
Definition at line 38 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
double WaferGridXY::gridSizeY () const
access the grid size in Y
Definition at line 43 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
double WaferGridXY::offsetX () const
access the coordinate offset in X
Definition at line 48 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
double WaferGridXY::offsetY () const
access the coordinate offset in Y
Definition at line 53 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
WaferGridXY& DD4hep::Geometry::WaferGridXY::operator= (const WaferGridXY & seg)
Assignment operator.
Reimplemented from DD4hep::Handle< T >.
bool DD4hep::Geometry::WaferGridXY::operator== (const WaferGridXY & seg) const [inline]
Equality operator.
Reimplemented from DD4hep::Handle< T >.
Definition at line 76 of file WaferGridXY.h.
References DD4hep::Handle< T >::m_element.
Position WaferGridXY::position (const CellID & cellID) const
determine the position based on the cell ID
Definition at line 25 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
double WaferGridXY::waferOffsetX (int inGroup, int inWafer) const
access the coordinate waferOffset for inGroup in X
Definition at line 57 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
double WaferGridXY::waferOffsetY (int inGroup, int inWafer) const
access the coordinate waferOffset for inGroup in Y
Definition at line 62 of file WaferGridXY.cpp.
References DD4hep::Handle< T >::access().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/WaferGridXY.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/WaferGridXY.cpp