DD4hep: DD4hep::PropertyGrammar Class Reference
DD4hep::PropertyGrammar Class Reference
DD4hep::Simulation components, classes and objects
Class describing the grammar representation of a given data type.
#include <ComponentProperties.h>
Public Member Functions
PropertyGrammar (const BasicGrammar &g)
Default constructor.
virtual ~PropertyGrammar ()
Default destructor.
virtual const std::type_info & type () const
Access to the type information.
virtual std::string str (const void *ptr) const
Serialize an opaque value to a string.
virtual bool fromString (void *ptr, const std::string &value) const
Set value from serialized string. On successful data conversion TRUE is returned.
Static Public Member Functions
static void invalidConversion (const std::type_info &from, const std::type_info &to)
Error callback on invalid conversion.
static void invalidConversion (const std::string &value, const std::type_info &to)
Error callback on invalid conversion.
Protected Attributes
const BasicGrammar & m_grammar
Friends
class Property
Detailed Description
Class describing the grammar representation of a given data type.
Author
M.Frank
Version
1.0
Definition at line 53 of file ComponentProperties.h.
Constructor & Destructor Documentation
PropertyGrammar()
PropertyGrammar::PropertyGrammar (const BasicGrammar & g)
Default constructor.
Definition at line 29 of file ComponentProperties.cpp.
~PropertyGrammar()
PropertyGrammar::~PropertyGrammar () virtual
Default destructor.
Definition at line 33 of file ComponentProperties.cpp.
Member Function Documentation
fromString()
bool PropertyGrammar::fromString (void * ptr, const std::string & value) const virtual
Set value from serialized string. On successful data conversion TRUE is returned.
Definition at line 57 of file ComponentProperties.cpp.
References DD4hep::BasicGrammar::fromString(), and m_grammar.
Referenced by DD4hep::Property::set(), and DD4hep::Property::str().
invalidConversion() [1/2]
void PropertyGrammar::invalidConversion (const std::type_info & from, const std::type_info & to) static
Error callback on invalid conversion.
Definition at line 37 of file ComponentProperties.cpp.
References DD4hep::BasicGrammar::invalidConversion().
Referenced by DD4hep::Property::set(), and DD4hep::Property::value().
invalidConversion() [2/2]
void PropertyGrammar::invalidConversion (const std::string & value, const std::type_info & to) static
Error callback on invalid conversion.
Definition at line 42 of file ComponentProperties.cpp.
References DD4hep::BasicGrammar::invalidConversion().
str()
std::string PropertyGrammar::str (const void * ptr) const virtual
Serialize an opaque value to a string.
Definition at line 52 of file ComponentProperties.cpp.
References m_grammar, and DD4hep::BasicGrammar::str().
Referenced by DD4hep::Property::str().
type()
const std::type_info & PropertyGrammar::type () const virtual
Access to the type information.
Definition at line 47 of file ComponentProperties.cpp.
References m_grammar, and DD4hep::BasicGrammar::type().
Referenced by DD4hep::Property::set(), DD4hep::Property::type(), and DD4hep::Property::value().
Friends And Related Function Documentation
Property
friend class Property friend
Definition at line 55 of file ComponentProperties.h.
Member Data Documentation
m_grammar
const BasicGrammar& DD4hep::PropertyGrammar::m_grammar protected
Definition at line 56 of file ComponentProperties.h.
Referenced by fromString(), str(), and type().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/ComponentProperties.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/ComponentProperties.cpp