DD4hep: DD4hep: DD4hep::Simulation::Geant4UserGeneratorAction Class Reference
DD4hep::Simulation::Geant4UserGeneratorAction Class Reference
Concrete implementation of the Geant4 generator action.
Public Member Functions
Geant4UserGeneratorAction (Geant4Context *ctxt, Geant4GeneratorActionSequence *seq)
Standard constructor.
virtual ~Geant4UserGeneratorAction ()
Default destructor.
virtual void GeneratePrimaries (G4Event *event)
Generate primary particles.
Detailed Description
Concrete implementation of the Geant4 generator action.
Author:
M.Frank
Version:
1.0
Definition at line 252 of file Geant4Exec.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::Geant4UserGeneratorAction::Geant4UserGeneratorAction (Geant4Context * ctxt, Geant4GeneratorActionSequence * seq) [inline]
Standard constructor.
Definition at line 258 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::configureFiber(), and DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::updateContext().
virtual DD4hep::Simulation::Geant4UserGeneratorAction::~Geant4UserGeneratorAction () [inline, virtual]
Default destructor.
Definition at line 264 of file Geant4Exec.cpp.
Member Function Documentation
void DD4hep::Simulation::Geant4UserGeneratorAction::GeneratePrimaries (G4Event * event) [virtual]
Generate primary particles.
Definition at line 376 of file Geant4Exec.cpp.
References DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::createClientContext(), and DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::m_sequence.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/src/Geant4Exec.cpp