DD4hep: DD4hep::Callback Class Reference
DD4hep::Callback Class Reference
DD4hep classes and objects
Definition of the generic callback structure for member functions.
#include <Callback.h>
Classes
struct mfunc_t
Structure definition to store callback related data.
class Wrapper
Wrapper around a C++ member function pointer.
Public Types
typedef unsigned long(* func_t) (void *obj, const void *fun, const void *args[])
typedef unsigned long ulong
Public Member Functions
Callback ()
Default constructor.
Callback (void *p)
Constructor with object initialization.
Callback (void *p, void *mf, func_t c)
Initializing constructor.
operator bool () const
Check validity of the callback object.
unsigned long execute (const void *user_param[]) const
Execute the callback with the required number of user parameters.
template<typename T >
const Callback & _make (ulong(*fptr)(void *o, const void *f, const void *u[]), T pmf)
Callback setup function for Callbacks with member functions taking no arguments.
template<typename R , typename T >
const Callback & make (R(T::*pmf)())
Callback setup function for Callbacks with member functions with explicit return type taking no arguments.
template<typename R , typename T >
const Callback & make (R(T::*pmf)() const)
Callback setup function for Callbacks with const member functions with explicit return type taking no arguments.
template<typename T >
const Callback & make (void(T::*pmf)())
Callback setup function for Callbacks with void member functions taking no arguments.
template<typename T >
const Callback & make (void(T::*pmf)() const)
Callback setup function for Callbacks with const void member functions taking no arguments.
template<typename R , typename T , typename A >
const Callback & make (R(T::*pmf)(A))
Callback setup function for Callbacks with member functions with explicit return type taking 1 argument.
template<typename R , typename T , typename A >
const Callback & make (R(T::*pmf)(A) const)
Callback setup function for Callbacks with const member functions with explicit return type taking 1 argument.
template<typename T , typename A >
const Callback & make (void(T::*pmf)(A))
Callback setup function for Callbacks with void member functions taking 1 argument.
template<typename T , typename A >
const Callback & make (void(T::*pmf)(A) const)
Callback setup function for Callbacks with const void member functions taking 1 argument.
template<typename R , typename T , typename A0 , typename A1 >
const Callback & make (R(T::*pmf)(A0, A1))
Callback setup function for Callbacks with member functions with explicit return type taking 2 arguments.
template<typename R , typename T , typename A0 , typename A1 >
const Callback & make (R(T::*pmf)(A0, A1) const)
Callback setup function for Callbacks with const member functions with explicit return type taking 2 arguments.
template<typename T , typename A0 , typename A1 >
const Callback & make (void(T::*pmf)(A0, A1))
Callback setup function for Callbacks with const void member functions taking 2 arguments.
template<typename T , typename A0 , typename A1 >
const Callback & make (void(T::*pmf)(A0, A1) const)
Callback setup function for Callbacks with const void member functions taking 2 arguments.
template<typename R , typename T , typename A0 , typename A1 , typename A2 >
const Callback & make (R(T::*pmf)(A0, A1, A2))
Callback setup function for Callbacks with member functions with explicit return type taking 3 arguments.
template<typename R , typename T , typename A0 , typename A1 , typename A2 >
const Callback & make (R(T::*pmf)(A0, A1, A2) const)
Callback setup function for Callbacks with const member functions with explicit return type taking 3 arguments.
template<typename T , typename A0 , typename A1 , typename A2 >
const Callback & make (void(T::*pmf)(A0, A1, A2))
Callback setup function for Callbacks with const void member functions taking 3 arguments.
template<typename T , typename A0 , typename A1 , typename A2 >
const Callback & make (void(T::*pmf)(A0, A1, A2) const)
Callback setup function for Callbacks with const void member functions taking 3 arguments.
Static Public Member Functions
template<typename T >
static T * cast (void *p)
Template cast function used internally by the wrapper for type conversion to the object's type.
template<typename T >
static const T * c_cast (const void *p)
Template const cast function used internally by the wrapper for type conversion to the object's type.
template<typename T >
static Callback make (void *p, T pmf)
template<typename P , typename R , typename T >
static T * dyn_cast (P *p, R(T::*)())
template<typename P , typename R , typename T >
static const T * dyn_cast (const P *p, R(T::*)() const)
template<typename P , typename R , typename T , typename A >
static T * dyn_cast (P *p, R(T::*)(A))
template<typename P , typename R , typename T , typename A >
static const T * dyn_cast (const P *p, R(T::*)(A) const)
Public Attributes
void * par
func_t call
mfunc_t func
Detailed Description
Definition of the generic callback structure for member functions.
The callback structure allows to wrap any member function with up to 3 arguments into an abstract objects, which could later be called using the argument list. The pointer to the hosting objects is stored in the callback object. The callback objects in this sense behaves very similar to a static function.
Author
M.Frank
Date
01/03/2013
Version
1.0
Definition at line 38 of file Callback.h.
Member Typedef Documentation
func_t
typedef unsigned long(* DD4hep::Callback::func_t) (void *obj, const void *fun, const void *args[])
Definition at line 40 of file Callback.h.
ulong
typedef unsigned long DD4hep::Callback::ulong
Definition at line 45 of file Callback.h.
Constructor & Destructor Documentation
Callback() [1/3]
DD4hep::Callback::Callback () inline
Default constructor.
Definition at line 52 of file Callback.h.
References DD4hep::Callback::mfunc_t::first, and DD4hep::Callback::mfunc_t::second.
Referenced by DD4hep::CallbackSequence::add(), and make().
Callback() [2/3]
DD4hep::Callback::Callback (void * p) inline
Constructor with object initialization.
Definition at line 57 of file Callback.h.
References DD4hep::Callback::mfunc_t::first, and DD4hep::Callback::mfunc_t::second.
Callback() [3/3]
DD4hep::Callback::Callback (void * p, void * mf, func_t c) inline
Initializing constructor.
Definition at line 62 of file Callback.h.
Member Function Documentation
_make()
template<typename T > const Callback& DD4hep::Callback::_make (ulong(*)(void *o, const void *f, const void *u[]) fptr, T pmf) inline
Callback setup function for Callbacks with member functions taking no arguments.
Callback setup with no arguments
Definition at line 114 of file Callback.h.
Referenced by make(), and DD4hep::Callback::Wrapper< T >::pmf().
c_cast()
template<typename T > static const T* DD4hep::Callback::c_cast (const void * p) inline static
Template const cast function used internally by the wrapper for type conversion to the object's type.
Definition at line 79 of file Callback.h.
cast()
template<typename T > static T* DD4hep::Callback::cast (void * p) inline static
Template cast function used internally by the wrapper for type conversion to the object's type.
Definition at line 75 of file Callback.h.
dyn_cast() [1/4]
template<typename P , typename R , typename T > static T* DD4hep::Callback::dyn_cast (P * p, R(T::*)()) inline static
Definition at line 309 of file Callback.h.
dyn_cast() [2/4]
template<typename P , typename R , typename T > static const T* DD4hep::Callback::dyn_cast (const P * p, R(T::*)() const) inline static
Definition at line 312 of file Callback.h.
dyn_cast() [3/4]
template<typename P , typename R , typename T , typename A > static T* DD4hep::Callback::dyn_cast (P * p, R(T::*)(A)) inline static
Definition at line 316 of file Callback.h.
dyn_cast() [4/4]
template<typename P , typename R , typename T , typename A > static const T* DD4hep::Callback::dyn_cast (const P * p, R(T::*)(A) const) inline static
Definition at line 319 of file Callback.h.
execute()
unsigned long DD4hep::Callback::execute (const void * user_param[]) const inline
Execute the callback with the required number of user parameters.
Definition at line 71 of file Callback.h.
References call.
make() [1/17]
template<typename R , typename T > const Callback& DD4hep::Callback::make (R(T::*)() pmf) inline
Callback setup function for Callbacks with member functions with explicit return type taking no arguments.
Definition at line 121 of file Callback.h.
References _make(), call, and DD4hep::Callback::Wrapper< T >::Functor::pmf.
Referenced by DD4hep::CallbackSequence::add(), DD4hep::Simulation::Geant4PhaseAction::callback(), make(), and DD4hep::Simulation::Geant4ActionPhase::remove().
make() [2/17]
template<typename R , typename T > const Callback& DD4hep::Callback::make (R(T::*)() const pmf) inline
Callback setup function for Callbacks with const member functions with explicit return type taking no arguments.
Definition at line 131 of file Callback.h.
References _make(), call, and DD4hep::Callback::Wrapper< T >::Functor::pmf.
make() [3/17]
template<typename T > const Callback& DD4hep::Callback::make (void(T::*)() pmf) inline
Callback setup function for Callbacks with void member functions taking no arguments.
Definition at line 141 of file Callback.h.
References _make(), call, and DD4hep::Callback::Wrapper< T >::Functor::pmf.
make() [4/17]
template<typename T > const Callback& DD4hep::Callback::make (void(T::*)() const pmf) inline
Callback setup function for Callbacks with const void member functions taking no arguments.
Definition at line 152 of file Callback.h.
References _make(), call, make(), and DD4hep::Callback::Wrapper< T >::Functor::pmf.
make() [5/17]
template<typename R , typename T , typename A > const Callback& DD4hep::Callback::make (R(T::*)(A) pmf) inline
Callback setup function for Callbacks with member functions with explicit return type taking 1 argument.
Callbacks with 1 argument
Definition at line 165 of file Callback.h.
make() [6/17]
template<typename R , typename T , typename A > const Callback& DD4hep::Callback::make (R(T::*)(A) const pmf) inline
Callback setup function for Callbacks with const member functions with explicit return type taking 1 argument.
Definition at line 175 of file Callback.h.
References _make(), call, and DD4hep::Callback::Wrapper< T >::Functor::pmf.
make() [7/17]
template<typename T , typename A > const Callback& DD4hep::Callback::make (void(T::*)(A) pmf) inline
Callback setup function for Callbacks with void member functions taking 1 argument.
Definition at line 185 of file Callback.h.
References _make(), call, and DD4hep::Callback::Wrapper< T >::Functor::pmf.
make() [8/17]
template<typename T , typename A > const Callback& DD4hep::Callback::make (void(T::*)(A) const pmf) inline
Callback setup function for Callbacks with const void member functions taking 1 argument.
Definition at line 196 of file Callback.h.
References _make(), call, make(), and DD4hep::Callback::Wrapper< T >::Functor::pmf.
make() [9/17]
template<typename R , typename T , typename A0 , typename A1 > const Callback& DD4hep::Callback::make (R(T::*)(A0, A1) pmf) inline
Callback setup function for Callbacks with member functions with explicit return type taking 2 arguments.
Callback with 2 arguments
Definition at line 210 of file Callback.h.
make() [10/17]
template<typename R , typename T , typename A0 , typename A1 > const Callback& DD4hep::Callback::make (R(T::*)(A0, A1) const pmf) inline
Callback setup function for Callbacks with const member functions with explicit return type taking 2 arguments.
Definition at line 221 of file Callback.h.
References _make(), and call.
make() [11/17]
template<typename T , typename A0 , typename A1 > const Callback& DD4hep::Callback::make (void(T::*)(A0, A1) pmf) inline
Callback setup function for Callbacks with const void member functions taking 2 arguments.
Definition at line 232 of file Callback.h.
References _make(), and call.
make() [12/17]
template<typename T , typename A0 , typename A1 > const Callback& DD4hep::Callback::make (void(T::*)(A0, A1) const pmf) inline
Callback setup function for Callbacks with const void member functions taking 2 arguments.
Definition at line 244 of file Callback.h.
References _make(), call, and make().
make() [13/17]
template<typename R , typename T , typename A0 , typename A1 , typename A2 > const Callback& DD4hep::Callback::make (R(T::*)(A0, A1, A2) pmf) inline
Callback setup function for Callbacks with member functions with explicit return type taking 3 arguments.
Callback setup for callbacks with 3 arguments
Definition at line 259 of file Callback.h.
make() [14/17]
template<typename R , typename T , typename A0 , typename A1 , typename A2 > const Callback& DD4hep::Callback::make (R(T::*)(A0, A1, A2) const pmf) inline
Callback setup function for Callbacks with const member functions with explicit return type taking 3 arguments.
Definition at line 270 of file Callback.h.
References _make(), and call.
make() [15/17]
template<typename T , typename A0 , typename A1 , typename A2 > const Callback& DD4hep::Callback::make (void(T::*)(A0, A1, A2) pmf) inline
Callback setup function for Callbacks with const void member functions taking 3 arguments.
Definition at line 281 of file Callback.h.
References _make(), and call.
make() [16/17]
template<typename T , typename A0 , typename A1 , typename A2 > const Callback& DD4hep::Callback::make (void(T::*)(A0, A1, A2) const pmf) inline
Callback setup function for Callbacks with const void member functions taking 3 arguments.
Definition at line 293 of file Callback.h.
References _make(), and call.
make() [17/17]
template<typename T > static Callback DD4hep::Callback::make (void * p, T pmf) inline static
Definition at line 305 of file Callback.h.
References Callback().
operator bool()
DD4hep::Callback::operator bool () const inline
Check validity of the callback object.
Definition at line 67 of file Callback.h.
References DD4hep::Callback::mfunc_t::first.
Member Data Documentation
call
func_t DD4hep::Callback::call
Definition at line 48 of file Callback.h.
Referenced by execute(), and make().
func
mfunc_t DD4hep::Callback::func
Definition at line 49 of file Callback.h.
Referenced by DD4hep::Callback::Wrapper< T >::pmf(), and DD4hep::Simulation::Geant4ActionPhase::remove().
par
void* DD4hep::Callback::par
Definition at line 47 of file Callback.h.
Referenced by DD4hep::Simulation::Geant4ActionPhase::remove().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Callback.h