DD4hep: DD4hep::Alignments::GlobalAlignment Class Reference
DD4hep::Alignments::GlobalAlignment Class Reference
DD4hep::Geometry components, classes and objects | DDAlign: DD4hep Detector geometry alignment components.
Main handle class to hold a TGeo alignment object of type TGeoPhysicalNode.
#include <GlobalAlignment.h>
Public Member Functions
GlobalAlignment ()
Default constructor.
GlobalAlignment (TGeoPhysicalNode *p)
Default constructor.
GlobalAlignment (const GlobalAlignment &c)
Copy constructor.
template<typename Q >
GlobalAlignment (const Handle< Q > &e)
Constructor to be used when reading the already parsed object.
GlobalAlignment (const std::string &path)
Initializing constructor.
GlobalAlignment & operator= (const GlobalAlignment &c)
Assignment operator.
int numNodes () const
Number of nodes in this branch (=depth of the placement hierarchy from the top level volume)
PlacedVolume placement () const
Access the placement of this node.
PlacedVolume motherPlacement (int level_up=1) const
Access the placement of the mother of this node.
PlacedVolume nodePlacement (int level=-1) const
Access the placement of a node in the chain of placements for this branch.
Transform3D toGlobal (int level=-1) const
Access the currently applied alignment/placement matrix with respect to the world.
Position toGlobal (const Position &localPoint, int level=-1) const
Transform a point from local coordinates of a given level to global coordinates.
Position globalToLocal (const Position &globalPoint, int level=-1) const
Transform a point from global coordinates to local coordinates of a given level.
Transform3D toMother (int level=-1) const
Access the currently applied alignment/placement matrix with respect to mother volume.
Transform3D nominal () const
Access the currently applied alignment/placement matrix (mother to daughter)
Transform3D delta () const
Access the currently applied correction matrix (delta) (mother to daughter)
Transform3D invDelta () const
Access the inverse of the currently applied correction matrix (delta) (mother to daughter)
Public Member Functions inherited from DD4hep::Handle< TGeoPhysicalNode >
Handle ()
Defaulot constructor.
Handle (TGeoPhysicalNode *e)
Initializing constructor from pointer.
Handle (const Handle< TGeoPhysicalNode > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< TGeoPhysicalNode > & operator= (const Handle< TGeoPhysicalNode > &e)=default
Assignment operator.
bool operator== (const Handle< TGeoPhysicalNode > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< TGeoPhysicalNode > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< TGeoPhysicalNode > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< TGeoPhysicalNode > & clear ()
Release the object held by the handle.
TGeoPhysicalNode * operator-> () const
Access the held object using the -> operator.
operator TGeoPhysicalNode & () const
Automatic type conversion to an object references.
TGeoPhysicalNode & operator* () const
Access the held object using the * operator.
TGeoPhysicalNode * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
TGeoPhysicalNode * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Private Types
typedef Geometry::RotationZYX RotationZYX
typedef Geometry::Transform3D Transform3D
typedef Geometry::Position Position
Additional Inherited Members
Public Types inherited from DD4hep::Handle< TGeoPhysicalNode >
typedef TGeoPhysicalNode Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Static Public Member Functions inherited from DD4hep::Handle< TGeoPhysicalNode >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< TGeoPhysicalNode >
TGeoPhysicalNode * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Main handle class to hold a TGeo alignment object of type TGeoPhysicalNode.
See the ROOT documentation about the TGeoPhysicalNode for further details:
See also
http://root.cern.ch/root/html/TGeoPhysicalNode.html
Author
M.Frank
Version
1.0
Definition at line 38 of file GlobalAlignment.h.
Member Typedef Documentation
Position
typedef Geometry::Position DD4hep::Alignments::GlobalAlignment::Position private
Definition at line 42 of file GlobalAlignment.h.
RotationZYX
typedef Geometry::RotationZYX DD4hep::Alignments::GlobalAlignment::RotationZYX private
Definition at line 40 of file GlobalAlignment.h.
Transform3D
typedef Geometry::Transform3D DD4hep::Alignments::GlobalAlignment::Transform3D private
Definition at line 41 of file GlobalAlignment.h.
Constructor & Destructor Documentation
GlobalAlignment() [1/5]
GlobalAlignment::GlobalAlignment ()
Default constructor.
Definition at line 41 of file GlobalAlignment.cpp.
Referenced by GlobalAlignment().
GlobalAlignment() [2/5]
DD4hep::Alignments::GlobalAlignment::GlobalAlignment (TGeoPhysicalNode * p) inline
Default constructor.
Definition at line 48 of file GlobalAlignment.h.
References GlobalAlignment().
GlobalAlignment() [3/5]
GlobalAlignment::GlobalAlignment (const GlobalAlignment & c)
Copy constructor.
Definition at line 45 of file GlobalAlignment.cpp.
GlobalAlignment() [4/5]
template<typename Q > DD4hep::Alignments::GlobalAlignment::GlobalAlignment (const Handle< Q > & e) inline
Constructor to be used when reading the already parsed object.
Definition at line 54 of file GlobalAlignment.h.
References delta(), GlobalAlignment(), globalToLocal(), invDelta(), motherPlacement(), nodePlacement(), nominal(), numNodes(), operator=(), placement(), toGlobal(), and toMother().
GlobalAlignment() [5/5]
GlobalAlignment::GlobalAlignment (const std::string & path)
Initializing constructor.
Initializing constructor to create a new object.
Definition at line 49 of file GlobalAlignment.cpp.
References DD4hep::Handle< TGeoPhysicalNode >::m_element.
Member Function Documentation
delta()
GlobalAlignment::Transform3D GlobalAlignment::delta () const
Access the currently applied correction matrix (delta) (mother to daughter)
Access the currently applied correction matrix (delta)
Definition at line 131 of file GlobalAlignment.cpp.
References DD4hep::Geometry::_transform(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
globalToLocal()
GlobalAlignment::Position GlobalAlignment::globalToLocal (const Position & globalPoint, int level = -1) const
Transform a point from global coordinates to local coordinates of a given level.
Transform a point from local coordinates of a given level to global coordinates.
Definition at line 110 of file GlobalAlignment.cpp.
References m, and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
invDelta()
GlobalAlignment::Transform3D GlobalAlignment::invDelta () const
Access the inverse of the currently applied correction matrix (delta) (mother to daughter)
Definition at line 142 of file GlobalAlignment.cpp.
References DD4hep::Geometry::_transform(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
motherPlacement()
PlacedVolume GlobalAlignment::motherPlacement (int level_up = 1) const
Access the placement of the mother of this node.
Definition at line 85 of file GlobalAlignment.cpp.
References DD4hep::Handle< TGeoPhysicalNode >::name(), placement(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
nodePlacement()
PlacedVolume GlobalAlignment::nodePlacement (int level = -1) const
Access the placement of a node in the chain of placements for this branch.
Remeber the special cases: nodePlacement(-1) == nodePlacement(numNodes()) = placement() nodePlacement(numNodes()-1) == motherPlacement() = TGeoPhysicalNode::GetMother() == direct mother of placement()
Definition at line 76 of file GlobalAlignment.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Handle< TGeoPhysicalNode >::name(), placement(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
nominal()
GlobalAlignment::Transform3D GlobalAlignment::nominal () const
Access the currently applied alignment/placement matrix (mother to daughter)
Access the currently applied alignment/placement matrix.
Definition at line 125 of file GlobalAlignment.cpp.
References DD4hep::Geometry::_transform(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
numNodes()
int GlobalAlignment::numNodes () const
Number of nodes in this branch (=depth of the placement hierarchy from the top level volume)
Number of nodes in this branch.
Definition at line 64 of file GlobalAlignment.cpp.
References DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
operator=()
GlobalAlignment & GlobalAlignment::operator= (const GlobalAlignment & c)
Assignment operator.
Definition at line 56 of file GlobalAlignment.cpp.
References DD4hep::Handle< TGeoPhysicalNode >::m_element, and DD4hep::Handle< T >::ptr().
Referenced by GlobalAlignment().
placement()
PlacedVolume GlobalAlignment::placement () const
Access the placement of this node.
Definition at line 70 of file GlobalAlignment.cpp.
References DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment(), motherPlacement(), and nodePlacement().
toGlobal() [1/2]
GlobalAlignment::Transform3D GlobalAlignment::toGlobal (int level = -1) const
Access the currently applied alignment/placement matrix with respect to the world.
Access the currently applied alignment/placement matrix.
Definition at line 95 of file GlobalAlignment.cpp.
References DD4hep::Geometry::_transform(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
toGlobal() [2/2]
GlobalAlignment::Position GlobalAlignment::toGlobal (const Position & localPoint, int level = -1) const
Transform a point from local coordinates of a given level to global coordinates.
Definition at line 101 of file GlobalAlignment.cpp.
References m, and DD4hep::Handle< TGeoPhysicalNode >::ptr().
toMother()
GlobalAlignment::Transform3D GlobalAlignment::toMother (int level = -1) const
Access the currently applied alignment/placement matrix with respect to mother volume.
Access the currently applied alignment/placement matrix.
Definition at line 119 of file GlobalAlignment.cpp.
References DD4hep::Geometry::_transform(), and DD4hep::Handle< TGeoPhysicalNode >::ptr().
Referenced by GlobalAlignment().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/GlobalAlignment.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/GlobalAlignment.cpp