DD4hep: DD4hep::Conditions::ConditionsAccess Class Reference
DD4hep::Conditions::ConditionsAccess Class Reference
DDCond: DD4hep Detector Conditions components, classes and functions
Manager class for condition handles.
#include <ConditionsAccess.h>
Public Types
typedef ConditionsManagerObject Object
Standard object type.
Public Types inherited from DD4hep::Handle< ConditionsManagerObject >
typedef ConditionsManagerObject Implementation
Extern accessible definition of the contained element type.
typedef Handle< Implementation > handle_t
Declaration of 'self'.
Public Member Functions
ConditionsAccess ()
Default constructor.
ConditionsAccess (Object *p)
Constructor to be used with valid pointer to object.
ConditionsAccess (const ConditionsAccess &c)
Constructor to assing handle of the same type.
template<typename Q >
ConditionsAccess (const Handle< Q > &e)
Constructor to be used assigning from different type.
~ConditionsAccess ()
Default destructor.
const std::vector< const IOVType * > iovTypesUsed () const
Access the used/registered IOV types.
const IOVType * iovType (const std::string &iov_name) const
Access IOV by its name.
void clean (const IOVType *typ, int max_age)
Clean conditions, which are above the age limit.
Condition get (Condition::key_type key, const Condition::iov_type &req_validity)
Retrieve a condition given a Detector Element and the conditions name.
Condition get (const std::string &path, const Condition::iov_type &req_validity)
Retrieve a condition given the conditions path = <Detector element="" path>="">.<conditions name>="">
RangeConditions getRange (Condition::key_type key, const Condition::iov_type &req_validity)
Retrieve a condition given a Detector Element and the conditions name.
RangeConditions getRange (const std::string &path, const Condition::iov_type &req_validity)
Retrieve a condition given the conditions path = <Detector element="" path>="">.<conditions name>="">
Public Member Functions inherited from DD4hep::Handle< ConditionsManagerObject >
Handle ()
Defaulot constructor.
Handle (ConditionsManagerObject *e)
Initializing constructor from pointer.
Handle (const Handle< ConditionsManagerObject > &e)=default
Copy constructor.
Handle (Q *e)
Initializing constructor from unrelated pointer with type checking.
Handle (const Handle< Q > &e)
Initializing constructor from unrelated handle with type checking.
Handle< ConditionsManagerObject > & operator= (const Handle< ConditionsManagerObject > &e)=default
Assignment operator.
bool operator== (const Handle< ConditionsManagerObject > &e) const
Boolean operator == used for RB tree insertions.
bool operator< (const Handle< ConditionsManagerObject > &e) const
Boolean operator < used for RB tree insertions.
bool operator> (const Handle< ConditionsManagerObject > &e) const
Boolean operator > used for RB tree insertions.
bool isValid () const
Check the validity of the object held by the handle.
bool operator! () const
Check the validity of the object held by the handle.
Handle< ConditionsManagerObject > & clear ()
Release the object held by the handle.
ConditionsManagerObject * operator-> () const
Access the held object using the -> operator.
operator ConditionsManagerObject & () const
Automatic type conversion to an object references.
ConditionsManagerObject & operator* () const
Access the held object using the * operator.
ConditionsManagerObject * ptr () const
Access to the held object.
Q * _ptr () const
Access to an unrelated object type.
Q * data () const
Access to an unrelated object type.
Q & object () const
Access to an unrelated object type.
ConditionsManagerObject * access () const
Checked object access. Throws invalid handle runtime exception.
void verifyObject () const
Verify the object type after a (re-)assignment.
const char * name () const
Access the object name (or "" if not supported by the object)
const char * name () const
void assign (Implementation *n, const std::string &nam, const std::string &title)
Assign a new named object. Note: object references must be managed by the user.
void assign (_Segmentation *s, const std::string &n, const std::string &)
Additional Inherited Members
Static Public Member Functions inherited from DD4hep::Handle< ConditionsManagerObject >
static void bad_assignment (const std::type_info &from, const std::type_info &to)
Helper routine called when unrelated types are assigned.
Public Attributes inherited from DD4hep::Handle< ConditionsManagerObject >
ConditionsManagerObject * m_element
Single and only data member: Reference to the actual element.
Detailed Description
Manager class for condition handles.
Author
M.Frank
Version
1.0
Definition at line 35 of file ConditionsAccess.h.
Member Typedef Documentation
Object
typedef ConditionsManagerObject DD4hep::Conditions::ConditionsAccess::Object
Standard object type.
Definition at line 39 of file ConditionsAccess.h.
Constructor & Destructor Documentation
ConditionsAccess() [1/4]
DD4hep::Conditions::ConditionsAccess::ConditionsAccess () inline
Default constructor.
Definition at line 44 of file ConditionsAccess.h.
ConditionsAccess() [2/4]
DD4hep::Conditions::ConditionsAccess::ConditionsAccess (Object * p) inline
Constructor to be used with valid pointer to object.
Definition at line 47 of file ConditionsAccess.h.
ConditionsAccess() [3/4]
DD4hep::Conditions::ConditionsAccess::ConditionsAccess (const ConditionsAccess & c) inline
Constructor to assing handle of the same type.
Definition at line 50 of file ConditionsAccess.h.
ConditionsAccess() [4/4]
template<typename Q > DD4hep::Conditions::ConditionsAccess::ConditionsAccess (const Handle< Q > & e) inline
Constructor to be used assigning from different type.
Definition at line 55 of file ConditionsAccess.h.
References clean(), getRange(), iovType(), iovTypesUsed(), and ~ConditionsAccess().
~ConditionsAccess()
ConditionsAccess::~ConditionsAccess ()
Default destructor.
Definition at line 29 of file ConditionsAccess.cpp.
Referenced by ConditionsAccess().
Member Function Documentation
clean()
void DD4hep::Conditions::ConditionsAccess::clean (const IOVType * typ, int max_age)
Clean conditions, which are above the age limit.
Referenced by ConditionsAccess().
get() [1/2]
Condition ConditionsAccess::get (Condition::key_type key, const Condition::iov_type & req_validity)
Retrieve a condition given a Detector Element and the conditions name.
Definition at line 49 of file ConditionsAccess.cpp.
References DD4hep::Conditions::Condition::get().
get() [2/2]
Condition ConditionsAccess::get (const std::string & path, const Condition::iov_type & req_validity)
Retrieve a condition given the conditions path = <Detector element="" path>="">.<conditions name>="">
Definition at line 55 of file ConditionsAccess.cpp.
getRange() [1/2]
RangeConditions ConditionsAccess::getRange (Condition::key_type key, const Condition::iov_type & req_validity)
Retrieve a condition given a Detector Element and the conditions name.
Definition at line 62 of file ConditionsAccess.cpp.
Referenced by ConditionsAccess().
getRange() [2/2]
RangeConditions ConditionsAccess::getRange (const std::string & path, const Condition::iov_type & req_validity)
Retrieve a condition given the conditions path = <Detector element="" path>="">.<conditions name>="">
Retrieve a condition given a Detector Element path and the conditions name.
Definition at line 68 of file ConditionsAccess.cpp.
iovType()
const IOVType * ConditionsAccess::iovType (const std::string & iov_name) const
Access IOV by its name.
Definition at line 33 of file ConditionsAccess.cpp.
Referenced by ConditionsAccess().
iovTypesUsed()
const vector< const IOVType * > ConditionsAccess::iovTypesUsed () const
Access the used/registered IOV types.
Definition at line 38 of file ConditionsAccess.cpp.
References DD4hep::Conditions::ConditionsManagerObject::iovTypes().
Referenced by ConditionsAccess().
The documentation for this class was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsAccess.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsAccess.cpp