DD4hep: DD4hep::Geometry components, classes and objects
DD4hep::Geometry components, classes and objects
DD4hep geometry components, classes and functions.
Namespaces
DD4hep::Geometry::DetectorTools
Helper namespace used to answer detector element specific questons.
Classes
class DD4hep::Geometry::GeometryTreeDump
Geometry to screen dump action.
class DD4hep::Geometry::SimpleGDMLWriter
Simple GDML creator from TGeo geometries in memory.
class DD4hep::Alignments::Alignment
Main handle class to hold an alignment object.
class DD4hep::Alignments::AlignmentCondition
Main handle class to hold an alignment conditions object.
class DD4hep::Geometry::CartesianGridXY
Implementation class for the grid XY segmentation.
class DD4hep::Geometry::CartesianGridXYZ
Implementation class for the grid XYZ segmentation.
class DD4hep::Geometry::CartesianGridXZ
Implementation class for the grid XZ segmentation.
class DD4hep::Geometry::CartesianGridYZ
Implementation class for the grid YZ segmentation.
class DD4hep::Alignments::DetAlign
Handle class describing the access to DetElement dependent alignments.
class DD4hep::Conditions::DetConditions
Handle class describing the access to DetElement dependent conditions.
class DD4hep::Geometry::SensitiveDetector
Handle class to hold the information of a sensitive detector.
class DD4hep::Geometry::DetElement
Handle class describing a detector element.
class DD4hep::ConstructionFactory< T >
Template class with a generic constructor signature.
class DD4hep::ApplyFactory< T >
Template class with a generic signature to apply LCDD plugins.
class DD4hep::TranslationFactory< T >
Specialized factory to translate objects, which can be retrieved from LCDD.
class DD4hep::XMLElementFactory< T >
Create an arbitrary object from it's XML representation.
class DD4hep::XMLDocumentReaderFactory< T >
Read an arbitrary XML document and analyze it's content.
class DD4hep::XMLConversionFactory< T >
Read an arbitrary XML document and analyze it's content.
class DD4hep::DetElementFactory< T >
Standard factory to create Detector elements from the compact XML representation.
class DD4hep::Geometry::CartesianField::Object
Internal data class shared by all handles of a given type.
class DD4hep::Geometry::CartesianField
Handle class describing any field with 3D cartesian vectors for the field strength.
class DD4hep::Geometry::OverlayedField::Object
Internal data class shared by all handles.
class DD4hep::Geometry::OverlayedField
Class describing a field overlay with several sources.
class DD4hep::Geometry::ConstantField
Implementation object of a field with constant strength.
class DD4hep::Geometry::SolenoidField
Implementation object of a solenoidal magnetic field.
class DD4hep::Geometry::DipoleField
Implementation object of a dipole magnetic field.
class DD4hep::Geometry::MultipoleField
Implementation object of a Multipole magnetic field.
class DD4hep::Geometry::GeoHandlerTypes::GeometryInfo
Data container.
class DD4hep::Geometry::GeoHandlerTypes
Defintion of the object types used by generic geometry handlers.
class DD4hep::Geometry::GeoHandler
The base class for all DD4hep geometry crawlers.
class DD4hep::Geometry::GeoScan
Geometry scanner (handle object)
class DD4hep::Alignments::GlobalAlignment
Main handle class to hold a TGeo alignment object of type TGeoPhysicalNode.
class DD4hep::Handle< T >
Handle: a templated class like a shared pointer, which allows specialized access to tgeometry objects.
class DD4hep::DestroyHandle< T >
Functor to destroy handles and delete the cached object.
class DD4hep::DestroyHandles< M >
map Functor to destroy handles and delete the cached object
class DD4hep::ReleaseHandle< T >
Functor to destroy handles and delete the cached object.
class DD4hep::ReleaseHandles< M >
map Functor to release handles
class DD4hep::Geometry::LCDD
The main interface to the DD4hep detector description package.
struct DD4hep::Geometry::LCDDData::InvalidObjectError
Specialized exception class.
class DD4hep::Geometry::LCDDData::ObjectHandleMap
Implementation of a map of named DD4hep Handles.
class DD4hep::Geometry::LCDDData
Data implementation class of the LCDD interface.
class DD4hep::Geometry::LCDDHelper
LCDDHelper: class to shortcut certain questions to the DD4hep detector description interface.
class DD4hep::dd4hep_ptr< T >
Out version of the std auto_ptr implementation base either on auto_ptr or unique_ptr.
class DD4hep::Geometry::MultiSegmentation
Implementation class for the grid XZ segmentation.
class DD4hep::NamedObject
Implementation of a named object.
class DD4hep::ObjectExtensions
Implementation of an object supporting arbitrary user extensions.
class DD4hep::Geometry::Author
Handle class describing an author entity.
class DD4hep::Geometry::Header
Handle class describing the basic information about geometry objects as it is defined in LCDD.
class DD4hep::Geometry::Constant
Handle class describing a constant (define) object in lcdd.
class DD4hep::Geometry::Atom
Handle class describing an element in the periodic table.
class DD4hep::Geometry::Limit
Small object describing a limit structure acting on a particle type.
class DD4hep::Geometry::LimitSet
Handle class describing a set of limits as they are used for simulation.
class DD4hep::Geometry::Region
Handle class describing a region as used in simulation.
class DD4hep::Geometry::PolarGridRPhi
Implementation class for the grid XZ segmentation.
class DD4hep::Geometry::PolarGridRPhi2
Implementation class for the grid XZ segmentation.
class DD4hep::Geometry::Readout
Handle to the implementation of the readout structure of a subdetector.
class DD4hep::Geometry::Segmentation
Handle class supporting generic Segmentation of sensitive detectors.
class DD4hep::Geometry::Solid_type< T >
Base class for Solid (shape) objects.
class DD4hep::Geometry::Box
Class describing a box shape.
class DD4hep::Geometry::HalfSpace
Class describing half-space.
class DD4hep::Geometry::Polycone
Class describing a Polycone shape.
class DD4hep::Geometry::ConeSegment
Class describing a cone segment shape.
class DD4hep::Geometry::Tube
Class describing a tube shape of a section of a tube.
class DD4hep::Geometry::EllipticalTube
Class describing a elliptical tube shape of a section of a tube.
class DD4hep::Geometry::Cone
Class describing a cone shape.
class DD4hep::Geometry::Trap
Class describing a trap shape.
class DD4hep::Geometry::Trapezoid
Class describing a Trapezoid shape.
class DD4hep::Geometry::Torus
Class describing a Torus shape.
class DD4hep::Geometry::Sphere
Class describing a sphere shape.
class DD4hep::Geometry::Paraboloid
Class describing a Paraboloid shape.
class DD4hep::Geometry::Hyperboloid
Class describing a Hyperboloid shape.
class DD4hep::Geometry::PolyhedraRegular
Class describing a regular polyhedron shape.
class DD4hep::Geometry::EightPointSolid
Class describing an arbitray solid defined by 8 vertices.
class DD4hep::Geometry::BooleanSolid
Base class describing boolean (=union,intersection,subtraction) solids.
class DD4hep::Geometry::SubtractionSolid
Class describing boolean subtraction solid.
class DD4hep::Geometry::UnionSolid
Class describing boolean union solid.
class DD4hep::Geometry::IntersectionSolid
Class describing boolean intersection solid.
class DD4hep::Geometry::VolumeManager
Class to support the retrieval of detector elements and volumes given a valid identifier.
class DD4hep::Geometry::PlacedVolumeExtension::VolIDs
Volume ID container.
class DD4hep::Geometry::PlacedVolumeExtension
Implementation class extending the ROOT placed volume.
class DD4hep::Geometry::PlacedVolume
Handle class holding a placed volume (also called physical volume)
class DD4hep::Geometry::VolumeExtension
Implementation class extending the ROOT volume (TGeoVolume)
class DD4hep::Geometry::Volume
Handle class holding a placed volume (also called physical volume)
class DD4hep::Geometry::Assembly
Implementation class extending the ROOT assembly volumes (TGeoVolumeAsembly)
class DD4hep::Geometry::WaferGridXY
Implementation class for the grid XZ segmentation.
class DD4hep::Geometry::World
Handle class to hold the information of the top DetElement object 'world'.
class DD4hep::Geometry::SensitiveDetectorObject
Data class with properties of sensitive detectors.
class DD4hep::Geometry::DetElementObject
Data class with properties of a detector element.
class DD4hep::Geometry::WorldObject
Data class with properties of a detector element.
class DD4hep::Geometry::HeaderObject
Concrete object implementation for the Header handle.
class DD4hep::Geometry::ConstantObject
Concrete object implementation for the Constant handle.
class DD4hep::Geometry::VisAttrObject
Concrete object implementation of the VisAttr Handle.
class DD4hep::Geometry::RegionObject
Concrete object implementation of the Region Handle.
class DD4hep::Geometry::LimitSetObject
Concrete object implementation of the LimitSet Handle.
class DD4hep::Geometry::HitCollection
Definition of the HitCollection parameters used by the Readout.
class DD4hep::Geometry::ReadoutObject
Concrete object implementation of the Readout Handle.
class DD4hep::Geometry::IDDescriptorObject
Concrete object implementation of the IDDescriptorObject Handle.
class DD4hep::Geometry::SegmentationObject
Implementation class supporting generic Segmentation of sensitive detectors.
class DD4hep::Geometry::SegmentationWrapper< IMP >
Concrete wrapper class for segmentation implementation based on DDSegmentation objects.
class DD4hep::Geometry::VolumeManagerContext
This structure describes the cached data for one placement held by the volume manager.
class DD4hep::Geometry::VolumeManagerObject
This structure describes the internal data of the volume manager object.
class DD4hep::Geometry::Material
Handle class describing a material.
class DD4hep::Geometry::VisAttr
Handle class describing visualization attributes.
Typedefs
typedef Handle< NamedObject > DD4hep::Ref_t
Default Ref_t definition describing named objects.
Functions
unsigned long long int DD4hep::magic_word ()
Access to the magic word, which is protecting some objects against memory corruptions.
template<typename T >
void DD4hep::destroyHandle (T &h)
Helper to delete objects from heap and reset the handle.
template<typename T >
void DD4hep::releaseHandle (T &h)
Helper to delete objects from heap and reset the handle.
std::string DD4hep::_toString (bool value)
String conversions: boolean value to string.
std::string DD4hep::_toString (short value, const char *fmt="%d")
String conversions: integer value to string.
std::string DD4hep::_toString (int value, const char *fmt="%d")
String conversions: integer value to string.
std::string DD4hep::_toString (float value, const char *fmt="%.17e")
String conversions: float value to string.
std::string DD4hep::_toString (double value, const char *fmt="%.17e")
String conversions: double value to string.
bool DD4hep::_toBool (const std::string &value)
String conversions: string to boolean value.
short DD4hep::_toShort (const std::string &value)
String conversions: string to integer value.
int DD4hep::_toInt (const std::string &value)
String conversions: string to integer value.
long DD4hep::_toLong (const std::string &value)
String conversions: string to long integer value.
float DD4hep::_toFloat (const std::string &value)
String conversions: string to float value.
double DD4hep::_toDouble (const std::string &value)
String conversions: string to double value.
bool DD4hep::_toBool (bool value)
Void helper function to support formalisms.
short DD4hep::_toShort (short value)
Void helper function to support formalisms.
int DD4hep::_toInt (int value)
Void helper function to support formalisms.
long DD4hep::_toLong (long value)
Void helper function to support formalisms.
unsigned short DD4hep::_toUShort (unsigned short value)
Void helper function to support formalisms.
unsigned int DD4hep::_toUInt (unsigned int value)
Void helper function to support formalisms.
unsigned long DD4hep::_toULong (unsigned long value)
Void helper function to support formalisms.
float DD4hep::_toFloat (float value)
Void helper function to support formalisms.
double DD4hep::_toDouble (double value)
Void helper function to support formalisms.
template<class T >
T DD4hep::_multiply (const std::string &left, T right)
Generic multiplication using the evaluator: result = left * right.
template<class T >
T DD4hep::_multiply (T left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<class T >
T DD4hep::_multiply (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
char DD4hep::_multiply< char > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
char DD4hep::_multiply< char > (char left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
char DD4hep::_multiply< char > (const std::string &left, char right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned char DD4hep::_multiply< unsigned char > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned char DD4hep::_multiply< unsigned char > (unsigned char left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned char DD4hep::_multiply< unsigned char > (const std::string &left, unsigned char right)
Generic multiplication using the evaluator: result = left * right.
template<>
short DD4hep::_multiply< short > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
short DD4hep::_multiply< short > (short left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
short DD4hep::_multiply< short > (const std::string &left, short right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned short DD4hep::_multiply< unsigned short > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned short DD4hep::_multiply< unsigned short > (unsigned short left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned short DD4hep::_multiply< unsigned short > (const std::string &left, unsigned short right)
Generic multiplication using the evaluator: result = left * right.
template<>
int DD4hep::_multiply< int > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
int DD4hep::_multiply< int > (int left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
int DD4hep::_multiply< int > (const std::string &left, int right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned int DD4hep::_multiply< unsigned int > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned int DD4hep::_multiply< unsigned int > (unsigned int left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned int DD4hep::_multiply< unsigned int > (const std::string &left, unsigned int right)
Generic multiplication using the evaluator: result = left * right.
template<>
long DD4hep::_multiply< long > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
long DD4hep::_multiply< long > (long left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
long DD4hep::_multiply< long > (const std::string &left, long right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned long DD4hep::_multiply< unsigned long > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned long DD4hep::_multiply< unsigned long > (unsigned long left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned long DD4hep::_multiply< unsigned long > (const std::string &left, unsigned long right)
Generic multiplication using the evaluator: result = left * right.
template<>
float DD4hep::_multiply< float > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
float DD4hep::_multiply< float > (float left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
float DD4hep::_multiply< float > (const std::string &left, float right)
Generic multiplication using the evaluator: result = left * right.
template<>
double DD4hep::_multiply< double > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
double DD4hep::_multiply< double > (const std::string &left, double right)
Generic multiplication using the evaluator: result = left * right.
template<>
double DD4hep::_multiply< double > (double left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
void DD4hep::_toDictionary (const std::string &name, const std::string &value)
Enter name value pair to the dictionary. "value" must be a numerical expression, which is evaluated.
void DD4hep::_toDictionary (const std::string &name, const std::string &value, const std::string &typ)
Enter name value pair to the dictionary.
TGeoIdentity * DD4hep::Geometry::identityTransform ()
Access the TGeo identity transformation .
TGeoTranslation * DD4hep::Geometry::_translation (const Geometry::Position &pos)
Convert a Position object to a TGeoTranslation .
TGeoRotation * DD4hep::Geometry::_rotationZYX (const Geometry::RotationZYX &rot)
Convert a RotationZYX object to a TGeoRotation .
TGeoRotation * DD4hep::Geometry::_rotation3D (const Geometry::Rotation3D &rot)
Convert a Rotation3D object to a TGeoRotation .
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Transform3D &trans)
Convert a Transform3D object to a TGeoHMatrix .
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Position &pos)
Convert a Position object to a TGeoHMatrix .
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::RotationZYX &rot)
Convert a RotationZYX object to a TGeoHMatrix .
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Rotation3D &rot3D)
Convert a Rotation3D object to a TGeoHMatrix .
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Position &pos, const Geometry::RotationZYX &rot)
Convert a Position followed by a RotationZYX to a TGeoHMatrix .
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix &mat, const Geometry::Transform3D &trans)
Set a Transform3D object to a TGeoHMatrix .
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix &mat, const Geometry::Position &pos)
Set a Position object (translation) to a TGeoHMatrix .
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix &mat, const Geometry::RotationZYX &rot)
Set a RotationZYX object to a TGeoHMatrix .
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix &mat, const Geometry::Rotation3D &rot3D)
Set a Rotation3D object to a TGeoHMatrix .
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix &mat, const Geometry::Position &pos, const Geometry::RotationZYX &rot)
Set a Position followed by a RotationZYX to a TGeoHMatrix .
Geometry::Transform3D DD4hep::Geometry::_transform (const TGeoMatrix *matrix)
Convert a TGeoMatrix object to a generic Transform3D .
void DD4hep::Geometry::_decompose (const Geometry::Transform3D &trafo, Geometry::Position &pos, Geometry::RotationZYX &rot)
Decompose a generic Transform3D into a translation (Position) and a RotationZYX .
void DD4hep::Geometry::_decompose (const Geometry::Transform3D &trafo, Geometry::Position &pos, XYZAngles &rot)
Decompose a generic Transform3D into a translation (Geometry::Position) and XYZAngles .
void DD4hep::Geometry::_decompose (const Geometry::Transform3D &trafo, Geometry::Translation3D &pos, Geometry::RotationZYX &rot)
Decompose a generic Transform3D into a translation (Translation3D) and a RotationZYX .
void DD4hep::Geometry::_decompose (const Geometry::Transform3D &trafo, Geometry::Translation3D &pos, XYZAngles &rot)
Decompose a generic Transform3D into a translation (Translation3D) and XYZAngles .
XYZAngles DD4hep::Geometry::_XYZangles (const double *matrix)
Convert a 3x3 rotation matrix to XYZAngles .
XYZAngles DD4hep::Geometry::_XYZangles (const TGeoMatrix *matrix)
Convert a the rotation part of a TGeoMatrix to XYZAngles .
Detailed Description
DD4hep geometry components, classes and functions.
Typedef Documentation
Ref_t
typedef Handle< NamedObject > DD4hep::Ref_t
Default Ref_t definition describing named objects.
Definition at line 176 of file Handle.h.
Function Documentation
_decompose() [1/4]
void DD4hep::Geometry::_decompose (const Geometry::Transform3D & trafo, Geometry::Position & pos, Geometry::RotationZYX & rot)
Decompose a generic Transform3D into a translation (Position) and a RotationZYX .
Definition at line 139 of file MatrixHelpers.cpp.
_decompose() [2/4]
void DD4hep::Geometry::_decompose (const Geometry::Transform3D & trafo, Geometry::Position & pos, XYZAngles & rot)
Decompose a generic Transform3D into a translation (Geometry::Position) and XYZAngles .
Definition at line 143 of file MatrixHelpers.cpp.
_decompose() [3/4]
void DD4hep::Geometry::_decompose (const Geometry::Transform3D & trafo, Geometry::Translation3D & pos, Geometry::RotationZYX & rot)
Decompose a generic Transform3D into a translation (Translation3D) and a RotationZYX .
Definition at line 129 of file MatrixHelpers.cpp.
_decompose() [4/4]
void DD4hep::Geometry::_decompose (const Geometry::Transform3D & trafo, Geometry::Translation3D & pos, XYZAngles & rot)
Decompose a generic Transform3D into a translation (Translation3D) and XYZAngles .
Definition at line 133 of file MatrixHelpers.cpp.
_multiply() [1/3]
template<class T > T DD4hep::_multiply (const std::string & left, T right)
Generic multiplication using the evaluator: result = left * right.
Referenced by DD4hep::Conditions::Test::__print_bound_val(), and DD4hep::_toDouble().
_multiply() [2/3]
template<class T > T DD4hep::_multiply (T left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
_multiply() [3/3]
template<class T > T DD4hep::_multiply (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
_multiply< char >() [1/3]
template<> char DD4hep::_multiply< char > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: char
Definition at line 113 of file Handle.cpp.
References DD4hep::_toDouble(), and DD4hep::except().
Referenced by DD4hep::_toDouble().
_multiply< char >() [2/3]
template<> char DD4hep::_multiply< char > (char left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 307 of file Handle.h.
References DD4hep::_toInt().
_multiply< char >() [3/3]
template<> char DD4hep::_multiply< char > (const std::string & left, char right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 311 of file Handle.h.
References DD4hep::_multiply< unsigned char >(), and DD4hep::_toInt().
_multiply< double >() [1/3]
template<> double DD4hep::_multiply< double > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: double
Definition at line 173 of file Handle.cpp.
References DD4hep::_toDouble().
Referenced by DD4hep::_multiply< float >().
_multiply< double >() [2/3]
template<> double DD4hep::_multiply< double > (const std::string & left, double right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 414 of file Handle.h.
References DD4hep::_toDouble().
_multiply< double >() [3/3]
template<> double DD4hep::_multiply< double > (double left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 418 of file Handle.h.
References DD4hep::_toDictionary(), and DD4hep::_toDouble().
_multiply< float >() [1/3]
template<> float DD4hep::_multiply< float > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: float
Definition at line 169 of file Handle.cpp.
References DD4hep::_toFloat().
Referenced by DD4hep::_multiply< unsigned long >().
_multiply< float >() [2/3]
template<> float DD4hep::_multiply< float > (float left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 402 of file Handle.h.
References DD4hep::_toFloat().
_multiply< float >() [3/3]
template<> float DD4hep::_multiply< float > (const std::string & left, float right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 406 of file Handle.h.
References DD4hep::_multiply< double >(), and DD4hep::_toFloat().
_multiply< int >() [1/3]
template<> int DD4hep::_multiply< int > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: int
Definition at line 153 of file Handle.cpp.
References DD4hep::_toDouble().
Referenced by DD4hep::_multiply< unsigned short >().
_multiply< int >() [2/3]
template<> int DD4hep::_multiply< int > (int left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 354 of file Handle.h.
References DD4hep::_toInt().
_multiply< int >() [3/3]
template<> int DD4hep::_multiply< int > (const std::string & left, int right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 358 of file Handle.h.
References DD4hep::_multiply< unsigned int >(), and DD4hep::_toInt().
_multiply< long >() [1/3]
template<> long DD4hep::_multiply< long > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: long
Definition at line 161 of file Handle.cpp.
References DD4hep::_toDouble().
Referenced by DD4hep::_multiply< unsigned int >().
_multiply< long >() [2/3]
template<> long DD4hep::_multiply< long > (long left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 378 of file Handle.h.
References DD4hep::_toLong().
_multiply< long >() [3/3]
template<> long DD4hep::_multiply< long > (const std::string & left, long right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 382 of file Handle.h.
References DD4hep::_multiply< unsigned long >(), and DD4hep::_toLong().
_multiply< short >() [1/3]
template<> short DD4hep::_multiply< short > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Definition at line 133 of file Handle.cpp.
References DD4hep::_toDouble(), and DD4hep::except().
Referenced by DD4hep::_multiply< unsigned char >().
_multiply< short >() [2/3]
template<> short DD4hep::_multiply< short > (short left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 330 of file Handle.h.
References DD4hep::_toInt().
_multiply< short >() [3/3]
template<> short DD4hep::_multiply< short > (const std::string & left, short right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 334 of file Handle.h.
References DD4hep::_multiply< unsigned short >(), and DD4hep::_toInt().
_multiply< unsigned char >() [1/3]
template<> unsigned char DD4hep::_multiply< unsigned char > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: unsigned char
Definition at line 123 of file Handle.cpp.
References DD4hep::_toDouble(), and DD4hep::except().
Referenced by DD4hep::_multiply< char >().
_multiply< unsigned char >() [2/3]
template<> unsigned char DD4hep::_multiply< unsigned char > (unsigned char left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 319 of file Handle.h.
References DD4hep::_toInt().
_multiply< unsigned char >() [3/3]
template<> unsigned char DD4hep::_multiply< unsigned char > (const std::string & left, unsigned char right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 323 of file Handle.h.
References DD4hep::_multiply< short >(), and DD4hep::_toInt().
_multiply< unsigned int >() [1/3]
template<> unsigned int DD4hep::_multiply< unsigned int > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: unsigned int
Definition at line 157 of file Handle.cpp.
References DD4hep::_toDouble().
Referenced by DD4hep::_multiply< int >().
_multiply< unsigned int >() [2/3]
template<> unsigned int DD4hep::_multiply< unsigned int > (unsigned int left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 366 of file Handle.h.
References DD4hep::_toInt().
_multiply< unsigned int >() [3/3]
template<> unsigned int DD4hep::_multiply< unsigned int > (const std::string & left, unsigned int right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 370 of file Handle.h.
References DD4hep::_multiply< long >(), and DD4hep::_toInt().
_multiply< unsigned long >() [1/3]
template<> unsigned long DD4hep::_multiply< unsigned long > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: unsigned long
Definition at line 165 of file Handle.cpp.
References DD4hep::_toDouble().
Referenced by DD4hep::_multiply< long >().
_multiply< unsigned long >() [2/3]
template<> unsigned long DD4hep::_multiply< unsigned long > (unsigned long left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 390 of file Handle.h.
References DD4hep::_toLong().
_multiply< unsigned long >() [3/3]
template<> unsigned long DD4hep::_multiply< unsigned long > (const std::string & left, unsigned long right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 394 of file Handle.h.
References DD4hep::_multiply< float >(), and DD4hep::_toLong().
_multiply< unsigned short >() [1/3]
template<> unsigned short DD4hep::_multiply< unsigned short > (const std::string & left, const std::string & right)
Generic multiplication using the evaluator: result = left * right.
Block for concrete overloads of type: unsigned short
Definition at line 143 of file Handle.cpp.
References DD4hep::_toDouble(), and DD4hep::except().
Referenced by DD4hep::_multiply< short >().
_multiply< unsigned short >() [2/3]
template<> unsigned short DD4hep::_multiply< unsigned short > (unsigned short left, const std::string & right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 342 of file Handle.h.
References DD4hep::_toInt().
_multiply< unsigned short >() [3/3]
template<> unsigned short DD4hep::_multiply< unsigned short > (const std::string & left, unsigned short right) inline
Generic multiplication using the evaluator: result = left * right.
Definition at line 346 of file Handle.h.
References DD4hep::_multiply< int >(), and DD4hep::_toInt().
_rotation3D()
TGeoRotation * DD4hep::Geometry::_rotation3D (const Geometry::Rotation3D & rot)
Convert a Rotation3D object to a TGeoRotation .
Definition at line 35 of file MatrixHelpers.cpp.
References RAD_2_DEGREE.
Referenced by DD4hep::Geometry::IntersectionSolid::IntersectionSolid(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::Geometry::SubtractionSolid::SubtractionSolid(), and DD4hep::Geometry::UnionSolid::UnionSolid().
_rotationZYX()
TGeoRotation * DD4hep::Geometry::_rotationZYX (const Geometry::RotationZYX & rot)
Convert a RotationZYX object to a TGeoRotation .
Definition at line 31 of file MatrixHelpers.cpp.
References RAD_2_DEGREE.
Referenced by DD4hep::Geometry::IntersectionSolid::IntersectionSolid(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::Geometry::SubtractionSolid::SubtractionSolid(), and DD4hep::Geometry::UnionSolid::UnionSolid().
_toBool() [1/2]
bool DD4hep::_toBool (const std::string & value)
String conversions: string to boolean value.
Definition at line 89 of file Handle.cpp.
Referenced by DD4hep::_toString().
_toBool() [2/2]
bool DD4hep::_toBool (bool value) inline
Void helper function to support formalisms.
Definition at line 260 of file Handle.h.
_toDictionary() [1/2]
void DD4hep::_toDictionary (const std::string & name, const std::string & value)
Enter name value pair to the dictionary. "value" must be a numerical expression, which is evaluated.
Definition at line 177 of file Handle.cpp.
Referenced by DD4hep::_multiply< double >(), and DD4hep::XML::_toDictionary().
_toDictionary() [2/2]
void DD4hep::_toDictionary (const std::string & name, const std::string & value, const std::string & typ)
Enter name value pair to the dictionary.
Definition at line 182 of file Handle.cpp.
References XmlTools::Evaluator::OK, and v.
_toDouble() [1/2]
double DD4hep::_toDouble (const std::string & value)
String conversions: string to double value.
Definition at line 103 of file Handle.cpp.
References XmlTools::Evaluator::OK.
Referenced by DD4hep::_multiply< char >(), DD4hep::_multiply< double >(), DD4hep::_multiply< int >(), DD4hep::_multiply< long >(), DD4hep::_multiply< short >(), DD4hep::_multiply< unsigned char >(), DD4hep::_multiply< unsigned int >(), DD4hep::_multiply< unsigned long >(), DD4hep::_multiply< unsigned short >(), DD4hep::_toString(), DD4hep::Geometry::Box::Box(), DD4hep::Geometry::Cone::Cone(), DD4hep::Geometry::LCDDImp::constantAsDouble(), DD4hep::Geometry::EllipticalTube::EllipticalTube(), setup_fields(), DD4hep::Geometry::Torus::Torus(), DD4hep::Geometry::Constant::toString(), DD4hep::Geometry::Trap::Trap(), DD4hep::Geometry::Trapezoid::Trapezoid(), and DD4hep::Geometry::Tube::Tube().
_toDouble() [2/2]
double DD4hep::_toDouble (double value) inline
Void helper function to support formalisms.
Definition at line 292 of file Handle.h.
References DD4hep::_multiply(), and DD4hep::_multiply< char >().
_toFloat() [1/2]
float DD4hep::_toFloat (const std::string & value)
String conversions: string to float value.
Definition at line 93 of file Handle.cpp.
References XmlTools::Evaluator::OK.
Referenced by DD4hep::_multiply< float >(), and DD4hep::_toString().
_toFloat() [2/2]
float DD4hep::_toFloat (float value) inline
Void helper function to support formalisms.
Definition at line 288 of file Handle.h.
_toInt() [1/2]
int DD4hep::_toInt (const std::string & value)
String conversions: string to integer value.
Definition at line 57 of file Handle.cpp.
References XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::_multiply< char >(), DD4hep::_multiply< int >(), DD4hep::_multiply< short >(), DD4hep::_multiply< unsigned char >(), DD4hep::_multiply< unsigned int >(), DD4hep::_multiply< unsigned short >(), and DD4hep::_toString().
_toInt() [2/2]
int DD4hep::_toInt (int value) inline
Void helper function to support formalisms.
Definition at line 268 of file Handle.h.
_toLong() [1/2]
long DD4hep::_toLong (const std::string & value)
String conversions: string to long integer value.
Definition at line 73 of file Handle.cpp.
References XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::_multiply< long >(), DD4hep::_multiply< unsigned long >(), DD4hep::_toString(), and DD4hep::Geometry::LCDDImp::constantAsLong().
_toLong() [2/2]
long DD4hep::_toLong (long value) inline
Void helper function to support formalisms.
Definition at line 272 of file Handle.h.
_toShort() [1/2]
short DD4hep::_toShort (const std::string & value)
String conversions: string to integer value.
Definition at line 41 of file Handle.cpp.
References XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::_toString().
_toShort() [2/2]
short DD4hep::_toShort (short value) inline
Void helper function to support formalisms.
Definition at line 264 of file Handle.h.
_toString() [1/5]
string DD4hep::_toString (bool value)
String conversions: boolean value to string.
Definition at line 213 of file Handle.cpp.
Referenced by DD4hep::releaseHandles(), and DD4hep::LayerStack::sectionThickness().
_toString() [2/5]
string DD4hep::_toString (short value, const char * fmt = "%d")
String conversions: integer value to string.
Definition at line 217 of file Handle.cpp.
References __to_string().
_toString() [3/5]
string DD4hep::_toString (int value, const char * fmt = "%d")
String conversions: integer value to string.
Definition at line 221 of file Handle.cpp.
References __to_string().
_toString() [4/5]
string DD4hep::_toString (float value, const char * fmt = "%.17e")
String conversions: float value to string.
Definition at line 225 of file Handle.cpp.
References __to_string().
_toString() [5/5]
string DD4hep::_toString (double value, const char * fmt = "%.17e")
String conversions: double value to string.
Definition at line 229 of file Handle.cpp.
References __to_string().
_toUInt()
unsigned int DD4hep::_toUInt (unsigned int value) inline
Void helper function to support formalisms.
Definition at line 280 of file Handle.h.
_toULong()
unsigned long DD4hep::_toULong (unsigned long value) inline
Void helper function to support formalisms.
Definition at line 284 of file Handle.h.
_toUShort()
unsigned short DD4hep::_toUShort (unsigned short value) inline
Void helper function to support formalisms.
Definition at line 276 of file Handle.h.
_transform() [1/11]
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Transform3D & trans)
Convert a Transform3D object to a TGeoHMatrix .
Definition at line 94 of file MatrixHelpers.cpp.
Referenced by DD4hep::Geometry::_transform(), DD4hep::Alignments::GlobalDetectorAlignment::align(), DD4hep::Alignments::AlignmentsManagerObject::compute(), computeDelta(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Alignments::AlignmentTools::computeSurvey(), DD4hep::Alignments::GlobalAlignment::delta(), DD4hep::Geometry::IntersectionSolid::IntersectionSolid(), DD4hep::Alignments::GlobalAlignment::invDelta(), DD4hep::Alignments::GlobalAlignment::nominal(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::Geometry::SubtractionSolid::SubtractionSolid(), DD4hep::Alignments::GlobalAlignment::toGlobal(), DD4hep::Alignments::GlobalAlignment::toMother(), and DD4hep::Geometry::UnionSolid::UnionSolid().
_transform() [2/11]
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Position & pos)
Convert a Position object to a TGeoHMatrix .
Convert a Position object to a TGeoTranslation .
Definition at line 79 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_transform().
_transform() [3/11]
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::RotationZYX & rot)
Convert a RotationZYX object to a TGeoHMatrix .
Definition at line 84 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_transform().
_transform() [4/11]
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Rotation3D & rot3D)
Convert a Rotation3D object to a TGeoHMatrix .
Definition at line 89 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_transform().
_transform() [5/11]
TGeoHMatrix * DD4hep::Geometry::_transform (const Geometry::Position & pos, const Geometry::RotationZYX & rot)
Convert a Position followed by a RotationZYX to a TGeoHMatrix .
Definition at line 99 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_transform().
_transform() [6/11]
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix & mat, const Geometry::Transform3D & trans)
Set a Transform3D object to a TGeoHMatrix .
Definition at line 66 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_transform().
_transform() [7/11]
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix & mat, const Geometry::Position & pos)
Set a Position object (translation) to a TGeoHMatrix .
Definition at line 49 of file MatrixHelpers.cpp.
_transform() [8/11]
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix & mat, const Geometry::RotationZYX & rot)
Set a RotationZYX object to a TGeoHMatrix .
Definition at line 41 of file MatrixHelpers.cpp.
References RAD_2_DEGREE.
_transform() [9/11]
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix & mat, const Geometry::Rotation3D & rot3D)
Set a Rotation3D object to a TGeoHMatrix .
Definition at line 59 of file MatrixHelpers.cpp.
_transform() [10/11]
TGeoHMatrix & DD4hep::Geometry::_transform (TGeoHMatrix & mat, const Geometry::Position & pos, const Geometry::RotationZYX & rot)
Set a Position followed by a RotationZYX to a TGeoHMatrix .
Definition at line 74 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_transform().
_transform() [11/11]
Transform3D DD4hep::Geometry::_transform (const TGeoMatrix * matrix)
Convert a TGeoMatrix object to a generic Transform3D .
Definition at line 104 of file MatrixHelpers.cpp.
References MM_2_CM.
_translation()
TGeoTranslation * DD4hep::Geometry::_translation (const Geometry::Position & pos)
Convert a Position object to a TGeoTranslation .
Definition at line 27 of file MatrixHelpers.cpp.
Referenced by DD4hep::Geometry::IntersectionSolid::IntersectionSolid(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::Geometry::SubtractionSolid::SubtractionSolid(), and DD4hep::Geometry::UnionSolid::UnionSolid().
_XYZangles() [1/2]
DD4hep::Geometry::XYZAngles DD4hep::Geometry::_XYZangles (const double * matrix)
Convert a 3x3 rotation matrix to XYZAngles .
Definition at line 121 of file MatrixHelpers.cpp.
Referenced by DD4hep::Geometry::_XYZangles(), and DD4hep::Alignments::GlobalAlignmentWriter::addNode().
_XYZangles() [2/2]
DD4hep::Geometry::XYZAngles DD4hep::Geometry::_XYZangles (const TGeoMatrix * matrix)
Convert a the rotation part of a TGeoMatrix to XYZAngles .
Definition at line 117 of file MatrixHelpers.cpp.
References DD4hep::Geometry::_XYZangles().
destroyHandle()
template<typename T > void DD4hep::destroyHandle (T & h) inline
Helper to delete objects from heap and reset the handle.
Definition at line 179 of file Handle.h.
References DD4hep::deletePtr().
Referenced by DD4hep::Geometry::LCDDData::destroyData(), DD4hep::Geometry::LCDDImp::imp_loadVolumeManager(), DD4hep::DestroyHandle< T >::operator()(), DD4hep::Geometry::DetElementObject::~DetElementObject(), and DD4hep::Alignments::GlobalAlignmentData::~GlobalAlignmentData().
identityTransform()
TGeoIdentity * DD4hep::Geometry::identityTransform ()
Access the TGeo identity transformation .
Access to identity transformation
Definition at line 23 of file MatrixHelpers.cpp.
Referenced by _addNode(), DD4hep::Geometry::IntersectionSolid::IntersectionSolid(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::Geometry::SubtractionSolid::SubtractionSolid(), and DD4hep::Geometry::UnionSolid::UnionSolid().
magic_word()
unsigned long long int DD4hep::magic_word () inline
Access to the magic word, which is protecting some objects against memory corruptions.
Definition at line 55 of file Handle.h.
Referenced by DD4hep::Alignments::AlignmentsManager::newEntry(), DD4hep::Geometry::PlacedVolumeExtension::PlacedVolumeExtension(), and DD4hep::Geometry::Region::Region().
releaseHandle()
template<typename T > void DD4hep::releaseHandle (T & h) inline
Helper to delete objects from heap and reset the handle.
Definition at line 205 of file Handle.h.
References DD4hep::releasePtr().
Referenced by DD4hep::ReleaseHandle< T >::operator()().