DD4hep: DD4hep::XML classes and objects
DD4hep::XML classes and objects
DD4hep XML utilities.
Classes
struct DD4hep::Converter< T, ARG >
Basic conversion objects for handling DD4hep XML files.
class DD4hep::XML::DocumentHandler
Class supporting to read and parse XML documents.
class DD4hep::XML::LayeringCnv
XML converter for layering objects.
class DD4hep::XML::UriReader
Class supporting to read data given a URI.
class DD4hep::XML::UriContextReader
Class supporting to read data given a URI.
struct DD4hep::XML::ChildValue
XML Handle to xml elements with predefined child access.
struct DD4hep::XML::Component
XML Handle class extending the XML handle Dimension.
struct DD4hep::XML::DetElement
XML Handle class extending the XML handle Dimension.
struct DD4hep::XML::Dimension
XML Handle to xml elements with predefined attribute access.
class DD4hep::XML::XmlString
Definition of the XmlString class.
class DD4hep::XML::Strng_t
Helper class to encapsulate a unicode string.
class DD4hep::XML::Tag_t
Class to support both way translation between C++ and XML strings.
class DD4hep::XML::NodeList
Class describing a list of XML nodes.
class DD4hep::XML::Handle_t
Class to easily access the properties of single XmlElements.
class DD4hep::XML::Collection_t
Class to support the access to collections of XmlNodes (or XmlElements)
class DD4hep::XML::Document
Class supporting the basic functionality of an XML document.
class DD4hep::XML::DocumentHolder
Class supporting the basic functionality of an XML document including ownership.
class DD4hep::XML::Element
User abstraction class to manipulate XML elements within a document.
class DD4hep::XML::RefElement
User abstraction class to manipulate named XML elements (references) within a document.
Functions
template<typename T >
std::string DD4hep::_toString (const T *p, const char *fmt="%p")
Format any pointer (64 bits) to string.
std::string DD4hep::XML::_toString (const Attribute attr)
Convert xml attribute to STL string.
std::string DD4hep::XML::_toString (const XmlChar *toTranscode)
Convert xml string to STL string.
std::string DD4hep::XML::_toString (const char *s)
Do-nothing version. Present for completeness and argument interchangeability.
std::string DD4hep::XML::_toString (const std::string &s)
Do-nothing version. Present for completeness and argument interchangeability.
std::string DD4hep::XML::_toString (unsigned long i, const char *fmt="%lu")
Format unsigned long integer to string with arbitrary format.
std::string DD4hep::XML::_toString (unsigned int i, const char *fmt="%u")
Format unsigned integer (32 bits) to string with arbitrary format.
std::string DD4hep::XML::_toString (int i, const char *fmt="%d")
Format signed integer (32 bits) to string with arbitrary format.
std::string DD4hep::XML::_toString (long i, const char *fmt="%ld")
Format signed long integer to string with arbitrary format.
std::string DD4hep::XML::_toString (float d, const char *fmt="%.17e")
Format single procision float number (32 bits) to string with arbitrary format.
std::string DD4hep::XML::_toString (double d, const char *fmt="%.17e")
Format double procision float number (64 bits) to string with arbitrary format.
std::string DD4hep::XML::_ptrToString (const void *p, const char *fmt="%p")
Format void pointer (64 bits) to string with arbitrary format.
template<typename T >
std::string DD4hep::XML::_toString (const T *p, const char *fmt="%p")
Format void pointer (64 bits) to string with arbitrary format.
void DD4hep::XML::_toDictionary (const XmlChar *name, const XmlChar *value)
Helper function to populate the evaluator dictionary.
template<typename T >
void DD4hep::XML::_toDictionary (const XmlChar *name, T value)
Helper function to populate the evaluator dictionary.
void DD4hep::XML::_toDictionary (const XmlChar *name, float value)
Helper function to populate the evaluator dictionary.
void DD4hep::XML::_toDictionary (const XmlChar *name, double value)
Helper function to populate the evaluator dictionary.
bool DD4hep::XML::_toBool (const XmlChar *value)
Conversion function from raw unicode string to bool.
int DD4hep::XML::_toInt (const XmlChar *value)
Conversion function from raw unicode string to int.
long DD4hep::XML::_toLong (const XmlChar *value)
Conversion function from raw unicode string to long.
float DD4hep::XML::_toFloat (const XmlChar *value)
Conversion function from raw unicode string to float.
double DD4hep::XML::_toDouble (const XmlChar *value)
Conversion function from raw unicode string to double.
Strng_t DD4hep::XML::operator+ (const Strng_t &a, const char *b)
Unicode string concatenation of a normal ASCII string from right side.
Strng_t DD4hep::XML::operator+ (const Strng_t &a, const std::string &b)
Unicode string concatenation of a encapsulated and an STL string from right side.
Strng_t DD4hep::XML::operator+ (const Strng_t &a, const Strng_t &b)
Unicode string concatenation of a encapsulated and an encapsulated string from right side.
Strng_t DD4hep::XML::operator+ (const char *a, const Strng_t &b)
Unicode string concatenation of a normal ASCII string from left side.
Strng_t DD4hep::XML::operator+ (const std::string &a, const Strng_t &b)
Unicode string concatenation of a STL string and an encapsulated string from the left.
Strng_t DD4hep::XML::operator+ (const Strng_t &a, const XmlChar *b)
Unicode string concatenation of a encapsulated and raw unicode string from right side.
Strng_t DD4hep::XML::operator+ (const XmlChar *a, const Strng_t &b)
Unicode string concatenation of a encapsulated and raw unicode string from left side.
Strng_t DD4hep::XML::operator+ (const XmlChar *a, const std::string &b)
Unicode string concatenation of a raw unicode and an STL string from the right.
Strng_t DD4hep::XML::operator+ (const std::string &a, const XmlChar *b)
Unicode string concatenation of a raw unicode and an STL string from the left.
Tag_t DD4hep::XML::operator+ (const Tag_t &a, const char *b)
Tag/string concatenation with a normal ASCII string from right side.
Tag_t DD4hep::XML::operator+ (const char *a, const Tag_t &b)
Tag/string concatenation with a normal ASCII string from left side.
Tag_t DD4hep::XML::operator+ (const Tag_t &a, const XmlChar *b)
Tag/string concatenation with a unicode string from right side.
Tag_t DD4hep::XML::operator+ (const Tag_t &a, const Strng_t &b)
Tag/string concatenation with a internal Xml string from right side.
Tag_t DD4hep::XML::operator+ (const Tag_t &a, const std::string &b)
Tag/string concatenation with a STL string from right side.
bool DD4hep::XML::operator== (const std::string &c, const Tag_t &b)
Equality operator between tag object and STL string.
Detailed Description
DD4hep XML utilities.
Summary of all XML utilities present in the DD4hep toolkit.
Function Documentation
_ptrToString()
string DD4hep::XML::_ptrToString (const void * p, const char * fmt = "%p")
Format void pointer (64 bits) to string with arbitrary format.
Format pointer to string with arbitrary format.
Definition at line 266 of file XMLElements.cpp.
References __to_string().
Referenced by DD4hep::XML::_toString().
_toBool()
bool DD4hep::XML::_toBool (const XmlChar * value)
Conversion function from raw unicode string to bool.
Definition at line 311 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and s.
Referenced by DD4hep::XML::_toString(), DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Handle_t::attr< std::string >().
_toDictionary() [1/4]
void DD4hep::XML::_toDictionary (const XmlChar * name, const XmlChar * value)
Helper function to populate the evaluator dictionary.
Definition at line 348 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), XmlTools::Evaluator::OK, and v.
Referenced by DD4hep::XML::_toDictionary(), and DD4hep::XML::_toString().
_toDictionary() [2/4]
template<typename T > void DD4hep::XML::_toDictionary (const XmlChar * name, T value)
Helper function to populate the evaluator dictionary.
Definition at line 365 of file XMLElements.cpp.
References DD4hep::XML::_toDictionary(), DD4hep::_toDictionary(), and DD4hep::Geometry::_toString().
_toDictionary() [3/4]
template void DD4hep::XML::_toDictionary (const XmlChar * name, float value)
Helper function to populate the evaluator dictionary.
_toDictionary() [4/4]
template void DD4hep::XML::_toDictionary (const XmlChar * name, double value)
Helper function to populate the evaluator dictionary.
_toDouble()
double DD4hep::XML::_toDouble (const XmlChar * value)
Conversion function from raw unicode string to double.
Definition at line 334 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::XML::_toString(), DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Handle_t::attr< std::string >().
_toFloat()
float DD4hep::XML::_toFloat (const XmlChar * value)
Conversion function from raw unicode string to float.
Definition at line 319 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::XML::_toString(), DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Handle_t::attr< std::string >().
_toInt()
int DD4hep::XML::_toInt (const XmlChar * value)
Conversion function from raw unicode string to int.
Definition at line 292 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::XML::_toString(), DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Handle_t::attr< std::string >().
_toLong()
long DD4hep::XML::_toLong (const XmlChar * value)
Conversion function from raw unicode string to long.
Definition at line 270 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), XmlTools::Evaluator::OK, and s.
Referenced by DD4hep::XML::_toString(), and DD4hep::XML::Handle_t::attr().
_toString() [1/12]
string DD4hep::XML::_toString (const Attribute attr)
Convert xml attribute to STL string.
Definition at line 209 of file XMLElements.cpp.
References DD4hep::Geometry::_toString().
Referenced by DD4hep::Simulation::_setAttributes(), DD4hep::Geometry::_toString(), DD4hep::Geometry::LCDDImp::apply(), DD4hep::XML::Handle_t::attr_ptr(), DD4hep::XML::Handle_t::child(), DD4hep::XML::Handle_t::attr< std::string >(), DD4hep::XML::NodeList::next(), DD4hep::XML::Handle_t::numChildren(), DD4hep::XML::NodeList::previous(), DD4hep::LCDDLoad::processXML(), DD4hep::XML::Handle_t::tag(), DD4hep::XML::Handle_t::text(), and DD4hep::XML::Handle_t::value().
_toString() [2/12]
string DD4hep::XML::_toString (const XmlChar * toTranscode)
Convert xml string to STL string.
Definition at line 185 of file XMLElements.cpp.
References _E, Xml::a, Xml::n, and DD4hep::XML::Handle_t::ptr().
_toString() [3/12]
string DD4hep::XML::_toString (const char * s)
Do-nothing version. Present for completeness and argument interchangeability.
Definition at line 222 of file XMLElements.cpp.
References s.
_toString() [4/12]
string DD4hep::XML::_toString (const std::string & s)
Do-nothing version. Present for completeness and argument interchangeability.
Definition at line 229 of file XMLElements.cpp.
_toString() [5/12]
string DD4hep::XML::_toString (unsigned long i, const char * fmt = "%lu")
Format unsigned long integer to string with arbitrary format.
Definition at line 236 of file XMLElements.cpp.
References __to_string().
_toString() [6/12]
string DD4hep::XML::_toString (unsigned int i, const char * fmt = "%u")
Format unsigned integer (32 bits) to string with arbitrary format.
Definition at line 241 of file XMLElements.cpp.
References __to_string().
_toString() [7/12]
string DD4hep::XML::_toString (int i, const char * fmt = "%d")
Format signed integer (32 bits) to string with arbitrary format.
Definition at line 246 of file XMLElements.cpp.
References __to_string().
_toString() [8/12]
string DD4hep::XML::_toString (long i, const char * fmt = "%ld")
Format signed long integer to string with arbitrary format.
Definition at line 251 of file XMLElements.cpp.
References __to_string().
_toString() [9/12]
string DD4hep::XML::_toString (float d, const char * fmt = "%.17e")
Format single procision float number (32 bits) to string with arbitrary format.
Definition at line 256 of file XMLElements.cpp.
References __to_string().
_toString() [10/12]
string DD4hep::XML::_toString (double d, const char * fmt = "%.17e")
Format double procision float number (64 bits) to string with arbitrary format.
Definition at line 261 of file XMLElements.cpp.
References __to_string().
_toString() [11/12]
template<typename T > std::string DD4hep::XML::_toString (const T * p, const char * fmt = "%p")
Format void pointer (64 bits) to string with arbitrary format.
Definition at line 125 of file XMLElements.h.
References DD4hep::XML::_ptrToString(), DD4hep::XML::_toBool(), DD4hep::XML::_toDictionary(), DD4hep::XML::_toDouble(), DD4hep::XML::_toFloat(), DD4hep::XML::_toInt(), DD4hep::XML::_toLong(), and DD4hep::XML::getEnviron().
_toString() [12/12]
template<typename T > std::string DD4hep::_toString (const T * p, const char * fmt = "%p")
Format any pointer (64 bits) to string.
Definition at line 243 of file Handle.h.
References DD4hep::_ptrToString(), DD4hep::_toBool(), DD4hep::_toDouble(), DD4hep::_toFloat(), DD4hep::_toInt(), DD4hep::_toLong(), and DD4hep::_toShort().
operator+() [1/14]
Strng_t DD4hep::XML::operator+ (const Strng_t & a, const char * b)
Unicode string concatenation of a normal ASCII string from right side.
Definition at line 421 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
Referenced by DD4hep::XML::Tag_t::c_str(), and DD4hep::XML::Strng_t::length().
operator+() [2/14]
Strng_t DD4hep::XML::operator+ (const Strng_t & a, const std::string & b)
Unicode string concatenation of a encapsulated and an STL string from right side.
Definition at line 413 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
operator+() [3/14]
Strng_t DD4hep::XML::operator+ (const Strng_t & a, const Strng_t & b)
Unicode string concatenation of a encapsulated and an encapsulated string from right side.
Definition at line 429 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
operator+() [4/14]
Strng_t DD4hep::XML::operator+ (const char * a, const Strng_t & b)
Unicode string concatenation of a normal ASCII string from left side.
Definition at line 425 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
operator+() [5/14]
Strng_t DD4hep::XML::operator+ (const std::string & a, const Strng_t & b)
Unicode string concatenation of a STL string and an encapsulated string from the left.
Definition at line 417 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
operator+() [6/14]
Strng_t DD4hep::XML::operator+ (const Strng_t & a, const XmlChar * b)
Unicode string concatenation of a encapsulated and raw unicode string from right side.
Definition at line 454 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
operator+() [7/14]
Strng_t DD4hep::XML::operator+ (const XmlChar * a, const Strng_t & b)
Unicode string concatenation of a encapsulated and raw unicode string from left side.
Definition at line 459 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Strng_t::ptr().
operator+() [8/14]
Strng_t DD4hep::XML::operator+ (const XmlChar * a, const std::string & b)
Unicode string concatenation of a raw unicode and an STL string from the right.
Definition at line 464 of file XMLElements.cpp.
References DD4hep::Geometry::_toString().
operator+() [9/14]
Strng_t DD4hep::XML::operator+ (const std::string & a, const XmlChar * b)
Unicode string concatenation of a raw unicode and an STL string from the left.
Definition at line 469 of file XMLElements.cpp.
References DD4hep::Geometry::_toString().
operator+() [10/14]
Tag_t DD4hep::XML::operator+ (const Tag_t & a, const char * b)
Tag/string concatenation with a normal ASCII string from right side.
Definition at line 433 of file XMLElements.cpp.
References DD4hep::XML::Tag_t::str().
operator+() [11/14]
Tag_t DD4hep::XML::operator+ (const char * a, const Tag_t & b)
Tag/string concatenation with a normal ASCII string from left side.
Definition at line 438 of file XMLElements.cpp.
References DD4hep::XML::Tag_t::str().
operator+() [12/14]
Tag_t DD4hep::XML::operator+ (const Tag_t & a, const XmlChar * b)
Tag/string concatenation with a unicode string from right side.
Definition at line 474 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Tag_t::str().
operator+() [13/14]
Tag_t DD4hep::XML::operator+ (const Tag_t & a, const Strng_t & b)
Tag/string concatenation with a internal Xml string from right side.
Definition at line 443 of file XMLElements.cpp.
References DD4hep::Geometry::_toString(), and DD4hep::XML::Tag_t::str().
operator+() [14/14]
Tag_t DD4hep::XML::operator+ (const Tag_t & a, const std::string & b)
Tag/string concatenation with a STL string from right side.
Definition at line 448 of file XMLElements.cpp.
References DD4hep::XML::Tag_t::str().
operator==()
bool DD4hep::XML::operator== (const std::string & c, const Tag_t & b) inline
Equality operator between tag object and STL string.
Definition at line 314 of file XMLElements.h.
References DD4hep::XML::Tag_t::m_str.