DD4hep: DD4hep::XML Namespace Reference
DD4hep::XML Namespace Reference
Namespace containing utilities to parse XML files using XercesC or TinyXML.
Namespaces
Conditions
Namespace of conditions unicode tags.
Classes
struct ChildValue
XML Handle to xml elements with predefined child access.
class Collection_t
Class to support the access to collections of XmlNodes (or XmlElements)
struct Component
XML Handle class extending the XML handle Dimension.
struct DetElement
XML Handle class extending the XML handle Dimension.
struct Dimension
XML Handle to xml elements with predefined attribute access.
class Document
Class supporting the basic functionality of an XML document.
class DocumentErrorHandler
XML-DOM ERror handler class for the XercesC document parser.
class DocumentHandler
Class supporting to read and parse XML documents.
class DocumentHolder
Class supporting the basic functionality of an XML document including ownership.
class Element
User abstraction class to manipulate XML elements within a document.
class Handle_t
Class to easily access the properties of single XmlElements.
class LayeringCnv
XML converter for layering objects.
class NodeList
Class describing a list of XML nodes.
class RefElement
User abstraction class to manipulate named XML elements (references) within a document.
class Strng_t
Helper class to encapsulate a unicode string.
class Tag_t
Class to support both way translation between C++ and XML strings.
class UriContextReader
Class supporting to read data given a URI.
class UriReader
Class supporting to read data given a URI.
class XmlString
Definition of the XmlString class.
Typedefs
typedef xercesc::DOMException XmlException
typedef std::size_t XmlSize_t
typedef unsigned short XmlChar
typedef const XmlAttr * Attribute
typedef const std::string & CSTR
typedef const XmlChar * cpXmlChar
Functions
void dumpTree (DOMNode *doc, ostream &os)
Dump DOM tree using XercesC handles.
void dump_doc (DOMDocument *doc, ostream &os)
Dump DOM tree using XercesC handles.
void dump_tree (Handle_t elt, ostream &os)
Dump DOM tree using XercesC handles.
void dump_tree (Document doc, ostream &os)
Dump DOM tree using XercesC handles.
void tags_init ()
UNICODE (0)
UNICODE (1)
UNICODE (2)
UNICODE (3)
UNICODE (4)
UNICODE (5)
UNICODE (6)
UNICODE (7)
UNICODE (8)
UNICODE (9)
UNICODE (a)
UNICODE (A)
UNICODE (Air)
UNICODE (angle)
UNICODE (alignment)
UNICODE (alignments)
UNICODE (alpha)
UNICODE (alpha1)
UNICODE (alpha2)
UNICODE (alpha3)
UNICODE (alpha4)
UNICODE (arb8)
UNICODE (arg)
UNICODE (argument)
UNICODE (assembly)
UNICODE (atom)
UNICODE (attributes)
UNICODE (aunit)
UNICODE (author)
UNICODE (b)
UNICODE (B)
UNICODE (barrel)
UNICODE (barrel_envelope)
UNICODE (beampipe)
UNICODE (beta)
UNICODE (box)
UNICODE (c)
UNICODE (distance)
UNICODE (C)
UNICODE (calorimeter)
UNICODE (cartesian_grid_xy)
UNICODE (chamber)
UNICODE (chambers)
UNICODE (check)
UNICODE (checksum)
UNICODE (cm)
UNICODE (coefficient)
UNICODE (coefficients)
UNICODE (color)
UNICODE (collections)
UNICODE (collection)
UNICODE (combine_hits)
UNICODE (combineHits)
UNICODE (comment)
UNICODE (component)
UNICODE (composite)
UNICODE (cone)
UNICODE (cons)
UNICODE (constant)
UNICODE (crossing_angle)
UNICODE (cut)
UNICODE (d)
UNICODE (D)
UNICODE (daughter)
UNICODE (define)
UNICODE (delta)
UNICODE (deltaphi)
UNICODE (deltatheta)
UNICODE (depth)
UNICODE (density)
UNICODE (detector)
UNICODE (detectors)
UNICODE (dim_r)
UNICODE (dim_x)
UNICODE (dim_y)
UNICODE (dim_z)
UNICODE (dimensions)
UNICODE (dipole_coeff)
UNICODE (disk)
UNICODE (disks)
UNICODE (display)
UNICODE (dr)
UNICODE (drawing_style)
UNICODE (drawingStyle)
UNICODE (dx)
UNICODE (dy)
UNICODE (dz)
UNICODE (e)
UNICODE (E)
UNICODE (ecut)
UNICODE (element)
UNICODE (eltube)
UNICODE (end)
UNICODE (end_module)
UNICODE (end_modules)
UNICODE (endcap)
UNICODE (endphi)
UNICODE (epsilon)
UNICODE (eunit)
UNICODE (end_x)
UNICODE (end_y)
UNICODE (end_z)
UNICODE (f)
UNICODE (F)
UNICODE (false)
UNICODE (field)
UNICODE (fields)
UNICODE (field_name)
UNICODE (file)
UNICODE (first)
UNICODE (firstposition)
UNICODE (firstrotation)
UNICODE (formula)
UNICODE (fraction)
UNICODE (funit)
UNICODE (g)
UNICODE (G)
UNICODE (gamma)
UNICODE (gap)
UNICODE (gas)
UNICODE (generator)
UNICODE (gdml)
UNICODE (gdmlFile)
UNICODE (glass)
UNICODE (global)
UNICODE (global_grid_xy)
UNICODE (grid_size_x)
UNICODE (grid_size_y)
UNICODE (grid_size_z)
UNICODE (grid_size_phi)
UNICODE (grid_xyz)
UNICODE (gridSizePhi)
UNICODE (gridSizeX)
UNICODE (gridSizeY)
UNICODE (gridSizeZ)
UNICODE (h)
UNICODE (H)
UNICODE (half_x)
UNICODE (half_y)
UNICODE (half_z)
UNICODE (header)
UNICODE (height)
UNICODE (hits_collections)
UNICODE (hits_collection)
UNICODE (hype)
UNICODE (i)
UNICODE (I)
UNICODE (id)
UNICODE (iddict)
UNICODE (identity_rot)
UNICODE (identity_pos)
UNICODE (idfield)
UNICODE (idspec)
UNICODE (idspecref)
UNICODE (include)
UNICODE (includes)
UNICODE (incoming_r)
UNICODE (info)
UNICODE (inner)
UNICODE (inner_field)
UNICODE (inner_r)
UNICODE (inner_radius)
UNICODE (inner_stereo)
UNICODE (inner_z)
UNICODE (insideTrackingVolume)
UNICODE (intersection)
UNICODE (InvisibleNoDaughters)
UNICODE (InvisibleWithDaughters)
UNICODE (isotope)
UNICODE (j)
UNICODE (J)
UNICODE (k)
UNICODE (key)
UNICODE (key_min)
UNICODE (key_max)
UNICODE (key_val)
UNICODE (key_value)
UNICODE (K)
UNICODE (l)
UNICODE (L)
UNICODE (label)
UNICODE (ladder)
UNICODE (layer)
UNICODE (layers)
UNICODE (lcdd)
UNICODE (lccdd)
UNICODE (length)
UNICODE (limit)
UNICODE (limits)
UNICODE (limitset)
UNICODE (limitsetref)
UNICODE (line_style)
UNICODE (lineStyle)
UNICODE (local)
UNICODE (logvol)
UNICODE (lunit)
UNICODE (m)
UNICODE (M)
UNICODE (material)
UNICODE (materialref)
UNICODE (materials)
UNICODE (member)
UNICODE (MeV)
UNICODE (mm)
UNICODE (module)
UNICODE (modules)
UNICODE (module_component)
UNICODE (module_envelope)
UNICODE (moduleHeight)
UNICODE (modulePitch)
UNICODE (modulePosX)
UNICODE (modulePosY)
UNICODE (moduleWidth)
UNICODE (mother)
UNICODE (n)
UNICODE (N)
UNICODE (NIL)
UNICODE (name)
UNICODE (nmodules)
UNICODE (nModules)
UNICODE (normal)
UNICODE (nonprojective_cylinder)
UNICODE (nPads)
UNICODE (nphi)
UNICODE (ntheta)
UNICODE (number)
UNICODE (numsides)
UNICODE (nsides)
UNICODE (nsides_inner)
UNICODE (nsides_outer)
UNICODE (nz)
UNICODE (o)
UNICODE (O)
UNICODE (offset)
UNICODE (overlap)
UNICODE (outer)
UNICODE (outer_field)
UNICODE (outer_r)
UNICODE (outer_radius)
UNICODE (outer_stereo)
UNICODE (outer_z)
UNICODE (outgoing_r)
UNICODE (outst)
UNICODE (p)
UNICODE (P)
UNICODE (padPitch)
UNICODE (pads)
UNICODE (para)
UNICODE (paraboloid)
UNICODE (param)
UNICODE (parameter)
UNICODE (params)
UNICODE (parent)
UNICODE (particles)
UNICODE (path)
UNICODE (phi)
UNICODE (phi0)
UNICODE (phi0_offset)
UNICODE (phi1)
UNICODE (phi_tilt)
UNICODE (phiBins)
UNICODE (phi_size_max)
UNICODE (physvol)
UNICODE (physvolid)
UNICODE (pivot)
UNICODE (pivot_point)
UNICODE (plugin)
UNICODE (plugins)
UNICODE (point)
UNICODE (polyhedra)
UNICODE (polycone)
UNICODE (position)
UNICODE (positionref)
UNICODE (pressure)
UNICODE (projective_cylinder)
UNICODE (projective_zplane)
UNICODE (properties)
UNICODE (psi)
UNICODE (q)
UNICODE (Q)
UNICODE (r)
UNICODE (R)
UNICODE (r_size)
UNICODE (r0)
UNICODE (rad)
UNICODE (radian)
UNICODE (radius)
UNICODE (radiator)
UNICODE (rbg)
UNICODE (rc)
UNICODE (readout)
UNICODE (readouts)
UNICODE (ref)
UNICODE (reflect)
UNICODE (reflect_rot)
UNICODE (region)
UNICODE (regions)
UNICODE (regionref)
UNICODE (repeat)
UNICODE (rhi)
UNICODE (ring)
UNICODE (rlo)
UNICODE (rmax)
UNICODE (rmax1)
UNICODE (rmax2)
UNICODE (rmin)
UNICODE (rmin1)
UNICODE (rmin2)
UNICODE (RL)
UNICODE (row)
UNICODE (rpc)
UNICODE (RowID)
UNICODE (rowHeight)
UNICODE (rowPitch)
UNICODE (rphi_layout)
UNICODE (rotation)
UNICODE (rotationref)
UNICODE (rtor)
UNICODE (s)
UNICODE (S)
UNICODE (scintillator)
UNICODE (sd)
UNICODE (sdref)
UNICODE (second)
UNICODE (segmentation)
UNICODE (sensitive)
UNICODE (sensitive_detector)
UNICODE (sensitive_detectors)
UNICODE (sensor)
UNICODE (sequence)
UNICODE (setup)
UNICODE (shape)
UNICODE (show_daughters)
UNICODE (showDaughters)
UNICODE (size)
UNICODE (signed)
UNICODE (skew)
UNICODE (slice)
UNICODE (slices)
UNICODE (solid)
UNICODE (solids)
UNICODE (solidref)
UNICODE (spacer)
UNICODE (sphere)
UNICODE (status)
UNICODE (start)
UNICODE (start_x)
UNICODE (start_y)
UNICODE (start_z)
UNICODE (startphi)
UNICODE (starttheta)
UNICODE (state)
UNICODE (stave)
UNICODE (staves)
UNICODE (store_secondaries)
UNICODE (strength)
UNICODE (structure)
UNICODE (subtraction)
UNICODE (support)
UNICODE (system)
UNICODE (symbol)
UNICODE (t)
UNICODE (T)
UNICODE (temperature)
UNICODE (theta)
UNICODE (thetaBins)
UNICODE (thickness)
UNICODE (threshold)
UNICODE (title)
UNICODE (tube)
UNICODE (tubes)
UNICODE (torus)
UNICODE (tracker)
UNICODE (tracking_cylinder)
UNICODE (tracking_volume)
UNICODE (trap)
UNICODE (trd)
UNICODE (true)
UNICODE (tubs)
UNICODE (type)
UNICODE (u)
UNICODE (U)
UNICODE (union)
UNICODE (unit)
UNICODE (useForHitPosition)
UNICODE (url)
UNICODE (v)
UNICODE (V)
UNICODE (v1x)
UNICODE (v1y)
UNICODE (v2x)
UNICODE (v2y)
UNICODE (v3x)
UNICODE (v3y)
UNICODE (v4x)
UNICODE (v4y)
UNICODE (v5x)
UNICODE (v5y)
UNICODE (v6x)
UNICODE (v6y)
UNICODE (v7x)
UNICODE (v7y)
UNICODE (v8x)
UNICODE (v8y)
UNICODE (Vacuum)
UNICODE (value)
UNICODE (verbose)
UNICODE (version)
UNICODE (vis)
UNICODE (visible)
UNICODE (visref)
UNICODE (volume)
UNICODE (volumeref)
UNICODE (w)
UNICODE (W)
UNICODE (wedge)
UNICODE (width)
UNICODE (world)
UNICODE (world_box)
UNICODE (world_volume)
UNICODE (x)
UNICODE (X)
UNICODE (x_offset)
UNICODE (x0)
UNICODE (x1)
UNICODE (X1)
UNICODE (x2)
UNICODE (X2)
UNICODE (x3)
UNICODE (x4)
UNICODE (xhalf)
UNICODE (xmax)
UNICODE (xmin)
UNICODE (xml)
UNICODE (y)
UNICODE (Y)
UNICODE (y0)
UNICODE (y1)
UNICODE (Y1)
UNICODE (y2)
UNICODE (Y2)
UNICODE (y3)
UNICODE (y4)
UNICODE (yhalf)
UNICODE (ymin)
UNICODE (ymax)
UNICODE (y_offset)
UNICODE (z)
UNICODE (Z)
UNICODE (z_layout)
UNICODE (z_length)
UNICODE (z_offset)
UNICODE (z0)
UNICODE (z1)
UNICODE (z2)
UNICODE (z3)
UNICODE (z4)
UNICODE (Zeff)
UNICODE (zhalf)
UNICODE (zmin)
UNICODE (zmax)
UNICODE (zplane)
UNICODE (zstart)
Geometry::Solid createShape (Geometry::LCDD &lcdd, const std::string &shape_type, XML::Element element)
Create a solid shape using the plugin mechanism from the attributes of the XML element.
Geometry::Volume createPlacedEnvelope (DD4hep::Geometry::LCDD &lcdd, DD4hep::XML::Handle_t e, DD4hep::Geometry::DetElement sdet)
void setDetectorTypeFlag (DD4hep::XML::Handle_t e, DD4hep::Geometry::DetElement sdet)
void dumpTree (XmlDocument *doc)
Dump DOM tree of a document.
std::string _toString (const Attribute attr)
Convert xml attribute to STL string.
std::string _toString (const XmlChar *toTranscode)
Convert xml string to STL string.
std::string _toString (const char *s)
Do-nothing version. Present for completeness and argument interchangeability.
std::string _toString (const std::string &s)
Do-nothing version. Present for completeness and argument interchangeability.
std::string _toString (unsigned long i, const char *fmt="%lu")
Format unsigned long integer to string with arbitrary format.
std::string _toString (unsigned int i, const char *fmt="%u")
Format unsigned integer (32 bits) to string with arbitrary format.
std::string _toString (int i, const char *fmt="%d")
Format signed integer (32 bits) to string with arbitrary format.
std::string _toString (long i, const char *fmt="%ld")
Format signed long integer to string with arbitrary format.
std::string _toString (float d, const char *fmt="%.17e")
Format single procision float number (32 bits) to string with arbitrary format.
std::string _toString (double d, const char *fmt="%.17e")
Format double procision float number (64 bits) to string with arbitrary format.
std::string _ptrToString (const void *p, const char *fmt="%p")
Format void pointer (64 bits) to string with arbitrary format.
template<typename T >
std::string _toString (const T *p, const char *fmt="%p")
Format void pointer (64 bits) to string with arbitrary format.
void _toDictionary (const XmlChar *name, const XmlChar *value)
Helper function to populate the evaluator dictionary.
template<typename T >
void _toDictionary (const XmlChar *name, T value)
Helper function to populate the evaluator dictionary.
void _toDictionary (const XmlChar *name, float value)
Helper function to populate the evaluator dictionary.
void _toDictionary (const XmlChar *name, double value)
Helper function to populate the evaluator dictionary.
std::string getEnviron (const std::string &env)
Helper function to lookup environment from the expression evaluator.
bool _toBool (const XmlChar *value)
Conversion function from raw unicode string to bool.
int _toInt (const XmlChar *value)
Conversion function from raw unicode string to int.
long _toLong (const XmlChar *value)
Conversion function from raw unicode string to long.
float _toFloat (const XmlChar *value)
Conversion function from raw unicode string to float.
double _toDouble (const XmlChar *value)
Conversion function from raw unicode string to double.
Strng_t operator+ (const Strng_t &a, const char *b)
Unicode string concatenation of a normal ASCII string from right side.
Strng_t operator+ (const Strng_t &a, const std::string &b)
Unicode string concatenation of a encapsulated and an STL string from right side.
Strng_t operator+ (const Strng_t &a, const Strng_t &b)
Unicode string concatenation of a encapsulated and an encapsulated string from right side.
Strng_t operator+ (const char *a, const Strng_t &b)
Unicode string concatenation of a normal ASCII string from left side.
Strng_t operator+ (const std::string &a, const Strng_t &b)
Unicode string concatenation of a STL string and an encapsulated string from the left.
Strng_t operator+ (const Strng_t &a, const XmlChar *b)
Unicode string concatenation of a encapsulated and raw unicode string from right side.
Strng_t operator+ (const XmlChar *a, const Strng_t &b)
Unicode string concatenation of a encapsulated and raw unicode string from left side.
Strng_t operator+ (const XmlChar *a, const std::string &b)
Unicode string concatenation of a raw unicode and an STL string from the right.
Strng_t operator+ (const std::string &a, const XmlChar *b)
Unicode string concatenation of a raw unicode and an STL string from the left.
Tag_t operator+ (const Tag_t &a, const char *b)
Tag/string concatenation with a normal ASCII string from right side.
Tag_t operator+ (const char *a, const Tag_t &b)
Tag/string concatenation with a normal ASCII string from left side.
Tag_t operator+ (const Tag_t &a, const XmlChar *b)
Tag/string concatenation with a unicode string from right side.
Tag_t operator+ (const Tag_t &a, const Strng_t &b)
Tag/string concatenation with a internal Xml string from right side.
Tag_t operator+ (const Tag_t &a, const std::string &b)
Tag/string concatenation with a STL string from right side.
bool operator== (const std::string &c, const Tag_t &b)
Equality operator between tag object and STL string.
template<>
INLINE std::string Handle_t::attr< std::string > (const XmlChar *tag_value) const
void dump_tree (Handle_t elt)
Dump partial or full XML trees to stdout.
void dump_tree (Handle_t elt, std::ostream &os)
Dump partial or full XML trees.
void dump_tree (Document doc)
Dump partial or full XML documents to stdout.
void dump_tree (Document doc, std::ostream &os)
Dump partial or full XML documents.
Variables
const Tag_t Unicode_NULL ("NULL", "0", __Init::register_tag)
const Tag_t Unicode_empty ("", "", __Init::register_tag)
const Tag_t Unicode_star ("star", "*", __Init::register_tag)
const Tag_t Unicode_PI ("PI", "3.14159265358979323846", __Init::register_tag)
const Tag_t Unicode_TWOPI ("TWOPI", "6.28318530717958647692", __Init::register_tag)
Detailed Description
Namespace containing utilities to parse XML files using XercesC or TinyXML.
Namespace for the AIDA detector description toolkit supporting XML utilities.
Typedef Documentation
Attribute
typedef const XmlAttr* DD4hep::XML::Attribute
Definition at line 40 of file XMLElements.h.
cpXmlChar
typedef const XmlChar* DD4hep::XML::cpXmlChar
Definition at line 500 of file XMLElements.h.
CSTR
typedef const std::string& DD4hep::XML::CSTR
Definition at line 97 of file XMLElements.h.
XmlChar
typedef unsigned short DD4hep::XML::XmlChar
Definition at line 43 of file config.h.
XmlException
typedef xercesc::DOMException DD4hep::XML::XmlException
Definition at line 47 of file LCDDImp.cpp.
XmlSize_t
typedef std::size_t DD4hep::XML::XmlSize_t
Definition at line 38 of file config.h.
Function Documentation
createPlacedEnvelope()
Geometry::Volume DD4hep::XML::createPlacedEnvelope (DD4hep::Geometry::LCDD & lcdd, DD4hep::XML::Handle_t e, DD4hep::Geometry::DetElement sdet)
Create an envelope volume that is placed into the world volume (the parent volume of sdet) from an xml element <envelope/> with child nodes <shape/> and optionally <position/> and <rotation/>. For special cases no volume but an assembly can be created with <shape type="Assembly"/>. Example:
<envelope vis="ILD_ECALVis">
<shape type="PolyhedraRegular" numsides="8"  rmin="TPC_outer_radius+Ecal_Tpc_gap" rmax="Ecal_outer_radius"
dz="2.*TPC_Ecal_Hcal_barrel_halfZ"  material = "Air" />
<rotation x="0*deg" y="0*deg" z="90*deg-180*deg/8"/>
</envelope>
Author
S.Lu DESY, F. Gaede CERN/DESY
Version
Id
Definition at line 44 of file Utilities.cpp.
References _U, DD4hep::Geometry::PlacedVolume::addPhysVolID(), DD4hep::XML::Element::child(), DD4hep::XML::Component::createShape(), e, DD4hep::XML::Element::hasChild(), DD4hep::Geometry::DetElement::id(), DD4hep::Handle< T >::isValid(), DD4hep::XML::Dimension::limitsStr(), DD4hep::Geometry::LCDD::material(), DD4hep::XML::Component::materialStr(), DD4hep::XML::Dimension::nameStr(), DD4hep::Geometry::LCDD::pickMotherVolume(), DD4hep::Geometry::Volume::placeVolume(), DD4hep::XML::Dimension::position(), DD4hep::XML::Dimension::regionStr(), DD4hep::XML::Dimension::rotation(), DD4hep::Geometry::DetElement::setAttributes(), DD4hep::Geometry::DetElement::setPlacement(), DD4hep::XML::Dimension::typeStr(), DD4hep::XML::Dimension::visStr(), DD4hep::XML::Dimension::x(), DD4hep::XML::Dimension::y(), and DD4hep::XML::Dimension::z().
createShape()
Geometry::Solid DD4hep::XML::createShape (Geometry::LCDD & lcdd, const std::string & shape_type, XML::Element element)
Create a solid shape using the plugin mechanism from the attributes of the XML element.
Definition at line 28 of file Utilities.cpp.
References DD4hep::except(), DD4hep::Handle< T >::isValid(), and DD4hep::PluginDebug::missingFactory().
Referenced by create_element().
dump_doc()
void DD4hep::XML::dump_doc (DOMDocument * doc, ostream & os)
Dump DOM tree using XercesC handles.
Definition at line 211 of file DocumentHandler.cpp.
References dumpTree().
Referenced by dump_tree().
dump_tree() [1/6]
void DD4hep::XML::dump_tree (Handle_t elt, ostream & os)
Dump DOM tree using XercesC handles.
Definition at line 215 of file DocumentHandler.cpp.
References dumpTree(), and DD4hep::XML::Handle_t::ptr().
Referenced by DD4hep::XML::DocumentHandler::output().
dump_tree() [2/6]
void DD4hep::XML::dump_tree (Document doc, ostream & os)
Dump DOM tree using XercesC handles.
Definition at line 219 of file DocumentHandler.cpp.
References dump_doc(), and DD4hep::XML::Document::ptr().
Referenced by dump_tree().
dump_tree() [3/6]
void DD4hep::XML::dump_tree (Handle_t elt)
Dump partial or full XML trees to stdout.
Definition at line 601 of file DocumentHandler.cpp.
References dump_tree().
dump_tree() [4/6]
void DD4hep::XML::dump_tree (Handle_t elt, std::ostream & os)
Dump partial or full XML trees.
dump_tree() [5/6]
void DD4hep::XML::dump_tree (Document doc)
Dump partial or full XML documents to stdout.
Definition at line 606 of file DocumentHandler.cpp.
References dump_tree().
dump_tree() [6/6]
void DD4hep::XML::dump_tree (Document doc, std::ostream & os)
Dump partial or full XML documents.
dumpTree() [1/2]
void DD4hep::XML::dumpTree (XmlDocument * doc)
Dump DOM tree of a document.
dumpTree() [2/2]
void DD4hep::XML::dumpTree (DOMNode * doc, ostream & os)
Dump DOM tree using XercesC handles.
Definition at line 193 of file DocumentHandler.cpp.
References DD4hep::ERROR, and DD4hep::printout().
Referenced by dump_doc(), dump_tree(), and DD4hep::XML::DocumentHandler::system_path().
getEnviron()
string DD4hep::XML::getEnviron (const std::string & env)
Helper function to lookup environment from the expression evaluator.
Evaluate string constant using environment stored in the evaluator.
Definition at line 385 of file XMLElements.cpp.
References XmlTools::Evaluator::OK, and v.
Referenced by _toString(), and DD4hep::XML::DocumentHandler::output().
Handle_t::attr< std::string >()
template<> INLINE std::string DD4hep::XML::Handle_t::attr< std::string > (const XmlChar * tag_value) const
Definition at line 530 of file XMLElements.h.
References _toBool(), _toDouble(), _toFloat(), _toInt(), _toString(), and INLINE.
setDetectorTypeFlag()
void DD4hep::XML::setDetectorTypeFlag (DD4hep::XML::Handle_t e, DD4hep::Geometry::DetElement sdet)
Sets the type flag specified in the <type_flags> element for the given DetElement, example:
<type_flags type=" DetType_TRACKER + DetType_PIXEL + DetType_VERTEX "/>
Author
F.Gaede, DESY
Definition at line 127 of file Utilities.cpp.
References DD4hep::XML::Element::child(), DEBUG, e, DD4hep::INFO, DD4hep::XML::Dimension::nameStr(), DD4hep::printout(), DD4hep::Geometry::DetElement::setTypeFlag(), and DD4hep::XML::Dimension::type().
Referenced by create_element().
tags_init()
void DD4hep::XML::tags_init ()
Definition at line 76 of file XMLTags.cpp.
UNICODE() [1/463]
DD4hep::XML::UNICODE (0)
UNICODE() [2/463]
DD4hep::XML::UNICODE (1)
UNICODE() [3/463]
DD4hep::XML::UNICODE (2)
UNICODE() [4/463]
DD4hep::XML::UNICODE (3)
UNICODE() [5/463]
DD4hep::XML::UNICODE (4)
UNICODE() [6/463]
DD4hep::XML::UNICODE (5)
UNICODE() [7/463]
DD4hep::XML::UNICODE (6)
UNICODE() [8/463]
DD4hep::XML::UNICODE (7)
UNICODE() [9/463]
DD4hep::XML::UNICODE (8)
UNICODE() [10/463]
DD4hep::XML::UNICODE (9)
UNICODE() [11/463]
DD4hep::XML::UNICODE (a)
UNICODE() [12/463]
DD4hep::XML::UNICODE (A)
UNICODE() [13/463]
DD4hep::XML::UNICODE (Air)
UNICODE() [14/463]
DD4hep::XML::UNICODE (angle)
UNICODE() [15/463]
DD4hep::XML::UNICODE (alignment)
UNICODE() [16/463]
DD4hep::XML::UNICODE (alignments)
UNICODE() [17/463]
DD4hep::XML::UNICODE (alpha)
UNICODE() [18/463]
DD4hep::XML::UNICODE (alpha1)
UNICODE() [19/463]
DD4hep::XML::UNICODE (alpha2)
UNICODE() [20/463]
DD4hep::XML::UNICODE (alpha3)
UNICODE() [21/463]
DD4hep::XML::UNICODE (alpha4)
UNICODE() [22/463]
DD4hep::XML::UNICODE (arb8)
UNICODE() [23/463]
DD4hep::XML::UNICODE (arg)
UNICODE() [24/463]
DD4hep::XML::UNICODE (argument)
UNICODE() [25/463]
DD4hep::XML::UNICODE (assembly)
UNICODE() [26/463]
DD4hep::XML::UNICODE (atom)
UNICODE() [27/463]
DD4hep::XML::UNICODE (attributes)
UNICODE() [28/463]
DD4hep::XML::UNICODE (aunit)
UNICODE() [29/463]
DD4hep::XML::UNICODE (author)
UNICODE() [30/463]
DD4hep::XML::UNICODE (b)
UNICODE() [31/463]
DD4hep::XML::UNICODE (B)
UNICODE() [32/463]
DD4hep::XML::UNICODE (barrel)
UNICODE() [33/463]
DD4hep::XML::UNICODE (barrel_envelope)
UNICODE() [34/463]
DD4hep::XML::UNICODE (beampipe)
UNICODE() [35/463]
DD4hep::XML::UNICODE (beta)
UNICODE() [36/463]
DD4hep::XML::UNICODE (box)
UNICODE() [37/463]
DD4hep::XML::UNICODE (c)
UNICODE() [38/463]
DD4hep::XML::UNICODE (distance)
UNICODE() [39/463]
DD4hep::XML::UNICODE (C)
UNICODE() [40/463]
DD4hep::XML::UNICODE (calorimeter)
UNICODE() [41/463]
DD4hep::XML::UNICODE (cartesian_grid_xy)
UNICODE() [42/463]
DD4hep::XML::UNICODE (chamber)
UNICODE() [43/463]
DD4hep::XML::UNICODE (chambers)
UNICODE() [44/463]
DD4hep::XML::UNICODE (check)
UNICODE() [45/463]
DD4hep::XML::UNICODE (checksum)
UNICODE() [46/463]
DD4hep::XML::UNICODE (cm)
UNICODE() [47/463]
DD4hep::XML::UNICODE (coefficient)
UNICODE() [48/463]
DD4hep::XML::UNICODE (coefficients)
UNICODE() [49/463]
DD4hep::XML::UNICODE (color)
UNICODE() [50/463]
DD4hep::XML::UNICODE (collections)
UNICODE() [51/463]
DD4hep::XML::UNICODE (collection)
UNICODE() [52/463]
DD4hep::XML::UNICODE (combine_hits)
UNICODE() [53/463]
DD4hep::XML::UNICODE (combineHits)
UNICODE() [54/463]
DD4hep::XML::UNICODE (comment)
UNICODE() [55/463]
DD4hep::XML::UNICODE (component)
UNICODE() [56/463]
DD4hep::XML::UNICODE (composite)
UNICODE() [57/463]
DD4hep::XML::UNICODE (cone)
UNICODE() [58/463]
DD4hep::XML::UNICODE (cons)
UNICODE() [59/463]
DD4hep::XML::UNICODE (constant)
UNICODE() [60/463]
DD4hep::XML::UNICODE (crossing_angle)
UNICODE() [61/463]
DD4hep::XML::UNICODE (cut)
UNICODE() [62/463]
DD4hep::XML::UNICODE (d)
UNICODE() [63/463]
DD4hep::XML::UNICODE (D)
UNICODE() [64/463]
DD4hep::XML::UNICODE (daughter)
UNICODE() [65/463]
DD4hep::XML::UNICODE (define)
UNICODE() [66/463]
DD4hep::XML::UNICODE (delta)
UNICODE() [67/463]
DD4hep::XML::UNICODE (deltaphi)
UNICODE() [68/463]
DD4hep::XML::UNICODE (deltatheta)
UNICODE() [69/463]
DD4hep::XML::UNICODE (depth)
UNICODE() [70/463]
DD4hep::XML::UNICODE (density)
UNICODE() [71/463]
DD4hep::XML::UNICODE (detector)
UNICODE() [72/463]
DD4hep::XML::UNICODE (detectors)
UNICODE() [73/463]
DD4hep::XML::UNICODE (dim_r)
UNICODE() [74/463]
DD4hep::XML::UNICODE (dim_x)
UNICODE() [75/463]
DD4hep::XML::UNICODE (dim_y)
UNICODE() [76/463]
DD4hep::XML::UNICODE (dim_z)
UNICODE() [77/463]
DD4hep::XML::UNICODE (dimensions)
UNICODE() [78/463]
DD4hep::XML::UNICODE (dipole_coeff)
UNICODE() [79/463]
DD4hep::XML::UNICODE (disk)
UNICODE() [80/463]
DD4hep::XML::UNICODE (disks)
UNICODE() [81/463]
DD4hep::XML::UNICODE (display)
UNICODE() [82/463]
DD4hep::XML::UNICODE (dr)
UNICODE() [83/463]
DD4hep::XML::UNICODE (drawing_style)
UNICODE() [84/463]
DD4hep::XML::UNICODE (drawingStyle)
UNICODE() [85/463]
DD4hep::XML::UNICODE (dx)
UNICODE() [86/463]
DD4hep::XML::UNICODE (dy)
UNICODE() [87/463]
DD4hep::XML::UNICODE (dz)
UNICODE() [88/463]
DD4hep::XML::UNICODE (e)
UNICODE() [89/463]
DD4hep::XML::UNICODE (E)
UNICODE() [90/463]
DD4hep::XML::UNICODE (ecut)
UNICODE() [91/463]
DD4hep::XML::UNICODE (element)
UNICODE() [92/463]
DD4hep::XML::UNICODE (eltube)
UNICODE() [93/463]
DD4hep::XML::UNICODE (end)
UNICODE() [94/463]
DD4hep::XML::UNICODE (end_module)
UNICODE() [95/463]
DD4hep::XML::UNICODE (end_modules)
UNICODE() [96/463]
DD4hep::XML::UNICODE (endcap)
UNICODE() [97/463]
DD4hep::XML::UNICODE (endphi)
UNICODE() [98/463]
DD4hep::XML::UNICODE (epsilon)
UNICODE() [99/463]
DD4hep::XML::UNICODE (eunit)
UNICODE() [100/463]
DD4hep::XML::UNICODE (end_x)
UNICODE() [101/463]
DD4hep::XML::UNICODE (end_y)
UNICODE() [102/463]
DD4hep::XML::UNICODE (end_z)
UNICODE() [103/463]
DD4hep::XML::UNICODE (f)
UNICODE() [104/463]
DD4hep::XML::UNICODE (F)
UNICODE() [105/463]
DD4hep::XML::UNICODE (false)
UNICODE() [106/463]
DD4hep::XML::UNICODE (field)
UNICODE() [107/463]
DD4hep::XML::UNICODE (fields)
UNICODE() [108/463]
DD4hep::XML::UNICODE (field_name)
UNICODE() [109/463]
DD4hep::XML::UNICODE (file)
UNICODE() [110/463]
DD4hep::XML::UNICODE (first)
UNICODE() [111/463]
DD4hep::XML::UNICODE (firstposition)
UNICODE() [112/463]
DD4hep::XML::UNICODE (firstrotation)
UNICODE() [113/463]
DD4hep::XML::UNICODE (formula)
UNICODE() [114/463]
DD4hep::XML::UNICODE (fraction)
UNICODE() [115/463]
DD4hep::XML::UNICODE (funit)
UNICODE() [116/463]
DD4hep::XML::UNICODE (g)
UNICODE() [117/463]
DD4hep::XML::UNICODE (G)
UNICODE() [118/463]
DD4hep::XML::UNICODE (gamma)
UNICODE() [119/463]
DD4hep::XML::UNICODE (gap)
UNICODE() [120/463]
DD4hep::XML::UNICODE (gas)
UNICODE() [121/463]
DD4hep::XML::UNICODE (generator)
UNICODE() [122/463]
DD4hep::XML::UNICODE (gdml)
UNICODE() [123/463]
DD4hep::XML::UNICODE (gdmlFile)
UNICODE() [124/463]
DD4hep::XML::UNICODE (glass)
UNICODE() [125/463]
DD4hep::XML::UNICODE (global)
UNICODE() [126/463]
DD4hep::XML::UNICODE (global_grid_xy)
UNICODE() [127/463]
DD4hep::XML::UNICODE (grid_size_x)
UNICODE() [128/463]
DD4hep::XML::UNICODE (grid_size_y)
UNICODE() [129/463]
DD4hep::XML::UNICODE (grid_size_z)
UNICODE() [130/463]
DD4hep::XML::UNICODE (grid_size_phi)
UNICODE() [131/463]
DD4hep::XML::UNICODE (grid_xyz)
UNICODE() [132/463]
DD4hep::XML::UNICODE (gridSizePhi)
UNICODE() [133/463]
DD4hep::XML::UNICODE (gridSizeX)
UNICODE() [134/463]
DD4hep::XML::UNICODE (gridSizeY)
UNICODE() [135/463]
DD4hep::XML::UNICODE (gridSizeZ)
UNICODE() [136/463]
DD4hep::XML::UNICODE (h)
UNICODE() [137/463]
DD4hep::XML::UNICODE (H)
UNICODE() [138/463]
DD4hep::XML::UNICODE (half_x)
UNICODE() [139/463]
DD4hep::XML::UNICODE (half_y)
UNICODE() [140/463]
DD4hep::XML::UNICODE (half_z)
UNICODE() [141/463]
DD4hep::XML::UNICODE (header)
UNICODE() [142/463]
DD4hep::XML::UNICODE (height)
UNICODE() [143/463]
DD4hep::XML::UNICODE (hits_collections)
UNICODE() [144/463]
DD4hep::XML::UNICODE (hits_collection)
UNICODE() [145/463]
DD4hep::XML::UNICODE (hype)
UNICODE() [146/463]
DD4hep::XML::UNICODE (i)
UNICODE() [147/463]
DD4hep::XML::UNICODE (I)
UNICODE() [148/463]
DD4hep::XML::UNICODE (id)
UNICODE() [149/463]
DD4hep::XML::UNICODE (iddict)
UNICODE() [150/463]
DD4hep::XML::UNICODE (identity_rot)
UNICODE() [151/463]
DD4hep::XML::UNICODE (identity_pos)
UNICODE() [152/463]
DD4hep::XML::UNICODE (idfield)
UNICODE() [153/463]
DD4hep::XML::UNICODE (idspec)
UNICODE() [154/463]
DD4hep::XML::UNICODE (idspecref)
UNICODE() [155/463]
DD4hep::XML::UNICODE (include)
UNICODE() [156/463]
DD4hep::XML::UNICODE (includes)
UNICODE() [157/463]
DD4hep::XML::UNICODE (incoming_r)
UNICODE() [158/463]
DD4hep::XML::UNICODE (info)
UNICODE() [159/463]
DD4hep::XML::UNICODE (inner)
UNICODE() [160/463]
DD4hep::XML::UNICODE (inner_field)
UNICODE() [161/463]
DD4hep::XML::UNICODE (inner_r)
UNICODE() [162/463]
DD4hep::XML::UNICODE (inner_radius)
UNICODE() [163/463]
DD4hep::XML::UNICODE (inner_stereo)
UNICODE() [164/463]
DD4hep::XML::UNICODE (inner_z)
UNICODE() [165/463]
DD4hep::XML::UNICODE (insideTrackingVolume)
UNICODE() [166/463]
DD4hep::XML::UNICODE (intersection)
UNICODE() [167/463]
DD4hep::XML::UNICODE (InvisibleNoDaughters)
UNICODE() [168/463]
DD4hep::XML::UNICODE (InvisibleWithDaughters)
UNICODE() [169/463]
DD4hep::XML::UNICODE (isotope)
UNICODE() [170/463]
DD4hep::XML::UNICODE (j)
UNICODE() [171/463]
DD4hep::XML::UNICODE (J)
UNICODE() [172/463]
DD4hep::XML::UNICODE (k)
UNICODE() [173/463]
DD4hep::XML::UNICODE (key)
UNICODE() [174/463]
DD4hep::XML::UNICODE (key_min)
UNICODE() [175/463]
DD4hep::XML::UNICODE (key_max)
UNICODE() [176/463]
DD4hep::XML::UNICODE (key_val)
UNICODE() [177/463]
DD4hep::XML::UNICODE (key_value)
UNICODE() [178/463]
DD4hep::XML::UNICODE (K)
UNICODE() [179/463]
DD4hep::XML::UNICODE (l)
UNICODE() [180/463]
DD4hep::XML::UNICODE (L)
UNICODE() [181/463]
DD4hep::XML::UNICODE (label)
UNICODE() [182/463]
DD4hep::XML::UNICODE (ladder)
UNICODE() [183/463]
DD4hep::XML::UNICODE (layer)
UNICODE() [184/463]
DD4hep::XML::UNICODE (layers)
UNICODE() [185/463]
DD4hep::XML::UNICODE (lcdd)
UNICODE() [186/463]
DD4hep::XML::UNICODE (lccdd)
UNICODE() [187/463]
DD4hep::XML::UNICODE (length)
UNICODE() [188/463]
DD4hep::XML::UNICODE (limit)
UNICODE() [189/463]
DD4hep::XML::UNICODE (limits)
UNICODE() [190/463]
DD4hep::XML::UNICODE (limitset)
UNICODE() [191/463]
DD4hep::XML::UNICODE (limitsetref)
UNICODE() [192/463]
DD4hep::XML::UNICODE (line_style)
UNICODE() [193/463]
DD4hep::XML::UNICODE (lineStyle)
UNICODE() [194/463]
DD4hep::XML::UNICODE (local)
UNICODE() [195/463]
DD4hep::XML::UNICODE (logvol)
UNICODE() [196/463]
DD4hep::XML::UNICODE (lunit)
UNICODE() [197/463]
DD4hep::XML::UNICODE (m)
UNICODE() [198/463]
DD4hep::XML::UNICODE (M)
UNICODE() [199/463]
DD4hep::XML::UNICODE (material)
UNICODE() [200/463]
DD4hep::XML::UNICODE (materialref)
UNICODE() [201/463]
DD4hep::XML::UNICODE (materials)
UNICODE() [202/463]
DD4hep::XML::UNICODE (member)
UNICODE() [203/463]
DD4hep::XML::UNICODE (MeV)
UNICODE() [204/463]
DD4hep::XML::UNICODE (mm)
UNICODE() [205/463]
DD4hep::XML::UNICODE (module)
UNICODE() [206/463]
DD4hep::XML::UNICODE (modules)
UNICODE() [207/463]
DD4hep::XML::UNICODE (module_component)
UNICODE() [208/463]
DD4hep::XML::UNICODE (module_envelope)
UNICODE() [209/463]
DD4hep::XML::UNICODE (moduleHeight)
UNICODE() [210/463]
DD4hep::XML::UNICODE (modulePitch)
UNICODE() [211/463]
DD4hep::XML::UNICODE (modulePosX)
UNICODE() [212/463]
DD4hep::XML::UNICODE (modulePosY)
UNICODE() [213/463]
DD4hep::XML::UNICODE (moduleWidth)
UNICODE() [214/463]
DD4hep::XML::UNICODE (mother)
UNICODE() [215/463]
DD4hep::XML::UNICODE (n)
UNICODE() [216/463]
DD4hep::XML::UNICODE (N)
UNICODE() [217/463]
DD4hep::XML::UNICODE (NIL)
UNICODE() [218/463]
DD4hep::XML::UNICODE (name)
UNICODE() [219/463]
DD4hep::XML::UNICODE (nmodules)
UNICODE() [220/463]
DD4hep::XML::UNICODE (nModules)
UNICODE() [221/463]
DD4hep::XML::UNICODE (normal)
UNICODE() [222/463]
DD4hep::XML::UNICODE (nonprojective_cylinder)
UNICODE() [223/463]
DD4hep::XML::UNICODE (nPads)
UNICODE() [224/463]
DD4hep::XML::UNICODE (nphi)
UNICODE() [225/463]
DD4hep::XML::UNICODE (ntheta)
UNICODE() [226/463]
DD4hep::XML::UNICODE (number)
UNICODE() [227/463]
DD4hep::XML::UNICODE (numsides)
UNICODE() [228/463]
DD4hep::XML::UNICODE (nsides)
UNICODE() [229/463]
DD4hep::XML::UNICODE (nsides_inner)
UNICODE() [230/463]
DD4hep::XML::UNICODE (nsides_outer)
UNICODE() [231/463]
DD4hep::XML::UNICODE (nz)
UNICODE() [232/463]
DD4hep::XML::UNICODE (o)
UNICODE() [233/463]
DD4hep::XML::UNICODE (O)
UNICODE() [234/463]
DD4hep::XML::UNICODE (offset)
UNICODE() [235/463]
DD4hep::XML::UNICODE (overlap)
UNICODE() [236/463]
DD4hep::XML::UNICODE (outer)
UNICODE() [237/463]
DD4hep::XML::UNICODE (outer_field)
UNICODE() [238/463]
DD4hep::XML::UNICODE (outer_r)
UNICODE() [239/463]
DD4hep::XML::UNICODE (outer_radius)
UNICODE() [240/463]
DD4hep::XML::UNICODE (outer_stereo)
UNICODE() [241/463]
DD4hep::XML::UNICODE (outer_z)
UNICODE() [242/463]
DD4hep::XML::UNICODE (outgoing_r)
UNICODE() [243/463]
DD4hep::XML::UNICODE (outst)
UNICODE() [244/463]
DD4hep::XML::UNICODE (p)
UNICODE() [245/463]
DD4hep::XML::UNICODE (P)
UNICODE() [246/463]
DD4hep::XML::UNICODE (padPitch)
UNICODE() [247/463]
DD4hep::XML::UNICODE (pads)
UNICODE() [248/463]
DD4hep::XML::UNICODE (para)
UNICODE() [249/463]
DD4hep::XML::UNICODE (paraboloid)
UNICODE() [250/463]
DD4hep::XML::UNICODE (param)
UNICODE() [251/463]
DD4hep::XML::UNICODE (parameter)
UNICODE() [252/463]
DD4hep::XML::UNICODE (params)
UNICODE() [253/463]
DD4hep::XML::UNICODE (parent)
UNICODE() [254/463]
DD4hep::XML::UNICODE (particles)
UNICODE() [255/463]
DD4hep::XML::UNICODE (path)
UNICODE() [256/463]
DD4hep::XML::UNICODE (phi)
UNICODE() [257/463]
DD4hep::XML::UNICODE (phi0)
UNICODE() [258/463]
DD4hep::XML::UNICODE (phi0_offset)
UNICODE() [259/463]
DD4hep::XML::UNICODE (phi1)
UNICODE() [260/463]
DD4hep::XML::UNICODE (phi_tilt)
UNICODE() [261/463]
DD4hep::XML::UNICODE (phiBins)
UNICODE() [262/463]
DD4hep::XML::UNICODE (phi_size_max)
UNICODE() [263/463]
DD4hep::XML::UNICODE (physvol)
UNICODE() [264/463]
DD4hep::XML::UNICODE (physvolid)
UNICODE() [265/463]
DD4hep::XML::UNICODE (pivot)
UNICODE() [266/463]
DD4hep::XML::UNICODE (pivot_point)
UNICODE() [267/463]
DD4hep::XML::UNICODE (plugin)
UNICODE() [268/463]
DD4hep::XML::UNICODE (plugins)
UNICODE() [269/463]
DD4hep::XML::UNICODE (point)
UNICODE() [270/463]
DD4hep::XML::UNICODE (polyhedra)
UNICODE() [271/463]
DD4hep::XML::UNICODE (polycone)
UNICODE() [272/463]
DD4hep::XML::UNICODE (position)
UNICODE() [273/463]
DD4hep::XML::UNICODE (positionref)
UNICODE() [274/463]
DD4hep::XML::UNICODE (pressure)
UNICODE() [275/463]
DD4hep::XML::UNICODE (projective_cylinder)
UNICODE() [276/463]
DD4hep::XML::UNICODE (projective_zplane)
UNICODE() [277/463]
DD4hep::XML::UNICODE (properties)
UNICODE() [278/463]
DD4hep::XML::UNICODE (psi)
UNICODE() [279/463]
DD4hep::XML::UNICODE (q)
UNICODE() [280/463]
DD4hep::XML::UNICODE (Q)
UNICODE() [281/463]
DD4hep::XML::UNICODE (r)
UNICODE() [282/463]
DD4hep::XML::UNICODE (R)
UNICODE() [283/463]
DD4hep::XML::UNICODE (r_size)
UNICODE() [284/463]
DD4hep::XML::UNICODE (r0)
UNICODE() [285/463]
DD4hep::XML::UNICODE (rad)
UNICODE() [286/463]
DD4hep::XML::UNICODE (radian)
UNICODE() [287/463]
DD4hep::XML::UNICODE (radius)
UNICODE() [288/463]
DD4hep::XML::UNICODE (radiator)
UNICODE() [289/463]
DD4hep::XML::UNICODE (rbg)
UNICODE() [290/463]
DD4hep::XML::UNICODE (rc)
UNICODE() [291/463]
DD4hep::XML::UNICODE (readout)
UNICODE() [292/463]
DD4hep::XML::UNICODE (readouts)
UNICODE() [293/463]
DD4hep::XML::UNICODE (ref)
UNICODE() [294/463]
DD4hep::XML::UNICODE (reflect)
UNICODE() [295/463]
DD4hep::XML::UNICODE (reflect_rot)
UNICODE() [296/463]
DD4hep::XML::UNICODE (region)
UNICODE() [297/463]
DD4hep::XML::UNICODE (regions)
UNICODE() [298/463]
DD4hep::XML::UNICODE (regionref)
UNICODE() [299/463]
DD4hep::XML::UNICODE (repeat)
UNICODE() [300/463]
DD4hep::XML::UNICODE (rhi)
UNICODE() [301/463]
DD4hep::XML::UNICODE (ring)
UNICODE() [302/463]
DD4hep::XML::UNICODE (rlo)
UNICODE() [303/463]
DD4hep::XML::UNICODE (rmax)
UNICODE() [304/463]
DD4hep::XML::UNICODE (rmax1)
UNICODE() [305/463]
DD4hep::XML::UNICODE (rmax2)
UNICODE() [306/463]
DD4hep::XML::UNICODE (rmin)
UNICODE() [307/463]
DD4hep::XML::UNICODE (rmin1)
UNICODE() [308/463]
DD4hep::XML::UNICODE (rmin2)
UNICODE() [309/463]
DD4hep::XML::UNICODE (RL)
UNICODE() [310/463]
DD4hep::XML::UNICODE (row)
UNICODE() [311/463]
DD4hep::XML::UNICODE (rpc)
UNICODE() [312/463]
DD4hep::XML::UNICODE (RowID)
UNICODE() [313/463]
DD4hep::XML::UNICODE (rowHeight)
UNICODE() [314/463]
DD4hep::XML::UNICODE (rowPitch)
UNICODE() [315/463]
DD4hep::XML::UNICODE (rphi_layout)
UNICODE() [316/463]
DD4hep::XML::UNICODE (rotation)
UNICODE() [317/463]
DD4hep::XML::UNICODE (rotationref)
UNICODE() [318/463]
DD4hep::XML::UNICODE (rtor)
UNICODE() [319/463]
DD4hep::XML::UNICODE (s)
UNICODE() [320/463]
DD4hep::XML::UNICODE (S)
UNICODE() [321/463]
DD4hep::XML::UNICODE (scintillator)
UNICODE() [322/463]
DD4hep::XML::UNICODE (sd)
UNICODE() [323/463]
DD4hep::XML::UNICODE (sdref)
UNICODE() [324/463]
DD4hep::XML::UNICODE (second)
UNICODE() [325/463]
DD4hep::XML::UNICODE (segmentation)
UNICODE() [326/463]
DD4hep::XML::UNICODE (sensitive)
UNICODE() [327/463]
DD4hep::XML::UNICODE (sensitive_detector)
UNICODE() [328/463]
DD4hep::XML::UNICODE (sensitive_detectors)
UNICODE() [329/463]
DD4hep::XML::UNICODE (sensor)
UNICODE() [330/463]
DD4hep::XML::UNICODE (sequence)
UNICODE() [331/463]
DD4hep::XML::UNICODE (setup)
UNICODE() [332/463]
DD4hep::XML::UNICODE (shape)
UNICODE() [333/463]
DD4hep::XML::UNICODE (show_daughters)
UNICODE() [334/463]
DD4hep::XML::UNICODE (showDaughters)
UNICODE() [335/463]
DD4hep::XML::UNICODE (size)
UNICODE() [336/463]
DD4hep::XML::UNICODE (signed)
UNICODE() [337/463]
DD4hep::XML::UNICODE (skew)
UNICODE() [338/463]
DD4hep::XML::UNICODE (slice)
UNICODE() [339/463]
DD4hep::XML::UNICODE (slices)
UNICODE() [340/463]
DD4hep::XML::UNICODE (solid)
UNICODE() [341/463]
DD4hep::XML::UNICODE (solids)
UNICODE() [342/463]
DD4hep::XML::UNICODE (solidref)
UNICODE() [343/463]
DD4hep::XML::UNICODE (spacer)
UNICODE() [344/463]
DD4hep::XML::UNICODE (sphere)
UNICODE() [345/463]
DD4hep::XML::UNICODE (status)
UNICODE() [346/463]
DD4hep::XML::UNICODE (start)
UNICODE() [347/463]
DD4hep::XML::UNICODE (start_x)
UNICODE() [348/463]
DD4hep::XML::UNICODE (start_y)
UNICODE() [349/463]
DD4hep::XML::UNICODE (start_z)
UNICODE() [350/463]
DD4hep::XML::UNICODE (startphi)
UNICODE() [351/463]
DD4hep::XML::UNICODE (starttheta)
UNICODE() [352/463]
DD4hep::XML::UNICODE (state)
UNICODE() [353/463]
DD4hep::XML::UNICODE (stave)
UNICODE() [354/463]
DD4hep::XML::UNICODE (staves)
UNICODE() [355/463]
DD4hep::XML::UNICODE (store_secondaries)
UNICODE() [356/463]
DD4hep::XML::UNICODE (strength)
UNICODE() [357/463]
DD4hep::XML::UNICODE (structure)
UNICODE() [358/463]
DD4hep::XML::UNICODE (subtraction)
UNICODE() [359/463]
DD4hep::XML::UNICODE (support)
UNICODE() [360/463]
DD4hep::XML::UNICODE (system)
UNICODE() [361/463]
DD4hep::XML::UNICODE (symbol)
UNICODE() [362/463]
DD4hep::XML::UNICODE (t)
UNICODE() [363/463]
DD4hep::XML::UNICODE (T)
UNICODE() [364/463]
DD4hep::XML::UNICODE (temperature)
UNICODE() [365/463]
DD4hep::XML::UNICODE (theta)
UNICODE() [366/463]
DD4hep::XML::UNICODE (thetaBins)
UNICODE() [367/463]
DD4hep::XML::UNICODE (thickness)
UNICODE() [368/463]
DD4hep::XML::UNICODE (threshold)
UNICODE() [369/463]
DD4hep::XML::UNICODE (title)
UNICODE() [370/463]
DD4hep::XML::UNICODE (tube)
UNICODE() [371/463]
DD4hep::XML::UNICODE (tubes)
UNICODE() [372/463]
DD4hep::XML::UNICODE (torus)
UNICODE() [373/463]
DD4hep::XML::UNICODE (tracker)
UNICODE() [374/463]
DD4hep::XML::UNICODE (tracking_cylinder)
UNICODE() [375/463]
DD4hep::XML::UNICODE (tracking_volume)
UNICODE() [376/463]
DD4hep::XML::UNICODE (trap)
UNICODE() [377/463]
DD4hep::XML::UNICODE (trd)
UNICODE() [378/463]
DD4hep::XML::UNICODE (true)
UNICODE() [379/463]
DD4hep::XML::UNICODE (tubs)
UNICODE() [380/463]
DD4hep::XML::UNICODE (type)
UNICODE() [381/463]
DD4hep::XML::UNICODE (u)
UNICODE() [382/463]
DD4hep::XML::UNICODE (U)
UNICODE() [383/463]
DD4hep::XML::UNICODE (union)
UNICODE() [384/463]
DD4hep::XML::UNICODE (unit)
UNICODE() [385/463]
DD4hep::XML::UNICODE (useForHitPosition)
UNICODE() [386/463]
DD4hep::XML::UNICODE (url)
UNICODE() [387/463]
DD4hep::XML::UNICODE (v)
UNICODE() [388/463]
DD4hep::XML::UNICODE (V)
UNICODE() [389/463]
DD4hep::XML::UNICODE (v1x)
UNICODE() [390/463]
DD4hep::XML::UNICODE (v1y)
UNICODE() [391/463]
DD4hep::XML::UNICODE (v2x)
UNICODE() [392/463]
DD4hep::XML::UNICODE (v2y)
UNICODE() [393/463]
DD4hep::XML::UNICODE (v3x)
UNICODE() [394/463]
DD4hep::XML::UNICODE (v3y)
UNICODE() [395/463]
DD4hep::XML::UNICODE (v4x)
UNICODE() [396/463]
DD4hep::XML::UNICODE (v4y)
UNICODE() [397/463]
DD4hep::XML::UNICODE (v5x)
UNICODE() [398/463]
DD4hep::XML::UNICODE (v5y)
UNICODE() [399/463]
DD4hep::XML::UNICODE (v6x)
UNICODE() [400/463]
DD4hep::XML::UNICODE (v6y)
UNICODE() [401/463]
DD4hep::XML::UNICODE (v7x)
UNICODE() [402/463]
DD4hep::XML::UNICODE (v7y)
UNICODE() [403/463]
DD4hep::XML::UNICODE (v8x)
UNICODE() [404/463]
DD4hep::XML::UNICODE (v8y)
UNICODE() [405/463]
DD4hep::XML::UNICODE (Vacuum)
UNICODE() [406/463]
DD4hep::XML::UNICODE (value)
UNICODE() [407/463]
DD4hep::XML::UNICODE (verbose)
UNICODE() [408/463]
DD4hep::XML::UNICODE (version)
UNICODE() [409/463]
DD4hep::XML::UNICODE (vis)
UNICODE() [410/463]
DD4hep::XML::UNICODE (visible)
UNICODE() [411/463]
DD4hep::XML::UNICODE (visref)
UNICODE() [412/463]
DD4hep::XML::UNICODE (volume)
UNICODE() [413/463]
DD4hep::XML::UNICODE (volumeref)
UNICODE() [414/463]
DD4hep::XML::UNICODE (w)
UNICODE() [415/463]
DD4hep::XML::UNICODE (W)
UNICODE() [416/463]
DD4hep::XML::UNICODE (wedge)
UNICODE() [417/463]
DD4hep::XML::UNICODE (width)
UNICODE() [418/463]
DD4hep::XML::UNICODE (world)
UNICODE() [419/463]
DD4hep::XML::UNICODE (world_box)
UNICODE() [420/463]
DD4hep::XML::UNICODE (world_volume)
UNICODE() [421/463]
DD4hep::XML::UNICODE (x)
UNICODE() [422/463]
DD4hep::XML::UNICODE (X)
UNICODE() [423/463]
DD4hep::XML::UNICODE (x_offset)
UNICODE() [424/463]
DD4hep::XML::UNICODE (x0)
UNICODE() [425/463]
DD4hep::XML::UNICODE (x1)
UNICODE() [426/463]
DD4hep::XML::UNICODE (X1)
UNICODE() [427/463]
DD4hep::XML::UNICODE (x2)
UNICODE() [428/463]
DD4hep::XML::UNICODE (X2)
UNICODE() [429/463]
DD4hep::XML::UNICODE (x3)
UNICODE() [430/463]
DD4hep::XML::UNICODE (x4)
UNICODE() [431/463]
DD4hep::XML::UNICODE (xhalf)
UNICODE() [432/463]
DD4hep::XML::UNICODE (xmax)
UNICODE() [433/463]
DD4hep::XML::UNICODE (xmin)
UNICODE() [434/463]
DD4hep::XML::UNICODE (xml)
UNICODE() [435/463]
DD4hep::XML::UNICODE (y)
UNICODE() [436/463]
DD4hep::XML::UNICODE (Y)
UNICODE() [437/463]
DD4hep::XML::UNICODE (y0)
UNICODE() [438/463]
DD4hep::XML::UNICODE (y1)
UNICODE() [439/463]
DD4hep::XML::UNICODE (Y1)
UNICODE() [440/463]
DD4hep::XML::UNICODE (y2)
UNICODE() [441/463]
DD4hep::XML::UNICODE (Y2)
UNICODE() [442/463]
DD4hep::XML::UNICODE (y3)
UNICODE() [443/463]
DD4hep::XML::UNICODE (y4)
UNICODE() [444/463]
DD4hep::XML::UNICODE (yhalf)
UNICODE() [445/463]
DD4hep::XML::UNICODE (ymin)
UNICODE() [446/463]
DD4hep::XML::UNICODE (ymax)
UNICODE() [447/463]
DD4hep::XML::UNICODE (y_offset)
UNICODE() [448/463]
DD4hep::XML::UNICODE (z)
UNICODE() [449/463]
DD4hep::XML::UNICODE (Z)
UNICODE() [450/463]
DD4hep::XML::UNICODE (z_layout)
UNICODE() [451/463]
DD4hep::XML::UNICODE (z_length)
UNICODE() [452/463]
DD4hep::XML::UNICODE (z_offset)
UNICODE() [453/463]
DD4hep::XML::UNICODE (z0)
UNICODE() [454/463]
DD4hep::XML::UNICODE (z1)
UNICODE() [455/463]
DD4hep::XML::UNICODE (z2)
UNICODE() [456/463]
DD4hep::XML::UNICODE (z3)
UNICODE() [457/463]
DD4hep::XML::UNICODE (z4)
UNICODE() [458/463]
DD4hep::XML::UNICODE (Zeff)
UNICODE() [459/463]
DD4hep::XML::UNICODE (zhalf)
UNICODE() [460/463]
DD4hep::XML::UNICODE (zmin)
UNICODE() [461/463]
DD4hep::XML::UNICODE (zmax)
UNICODE() [462/463]
DD4hep::XML::UNICODE (zplane)
UNICODE() [463/463]
DD4hep::XML::UNICODE (zstart)
Variable Documentation
Unicode_empty
const Tag_t DD4hep::XML::Unicode_empty
Definition at line 23 of file UnicodeValues.h.
Unicode_NULL
const Tag_t DD4hep::XML::Unicode_NULL
Definition at line 22 of file UnicodeValues.h.
Unicode_PI
const Tag_t DD4hep::XML::Unicode_PI
Definition at line 25 of file UnicodeValues.h.
Unicode_star
const Tag_t DD4hep::XML::Unicode_star
Definition at line 24 of file UnicodeValues.h.
Unicode_TWOPI
const Tag_t DD4hep::XML::Unicode_TWOPI
Definition at line 26 of file UnicodeValues.h.