DD4hep: DD4hep::Utilities Namespace Reference
DD4hep::Utilities Namespace Reference
Functions
int findNodeWithMatrix (TGeoNode *p, TGeoNode *n, TGeoHMatrix *mat, std::string *sub_path=0)
std::pair< bool, TEveElement * > createEveShape (int level, int max_level, TEveElement *p, TGeoNode *n, TGeoHMatrix mat, const std::string &node_name)
std::pair< bool, TEveElement * > LoadDetElement (Geometry::DetElement element, int levels, TEveElement *parent)
void MakeNodesVisible (TEveElement *e, bool visible, int level)
Make a set of nodes starting from a top element (in-)visible with a given depth.
void SetRnrChildren (TEveElementList *l, bool b)
Set the rendering flags for the object and the next level children.
void SetRnrAll (TEveElementList *l, bool b)
Recursively set the rendering flags for the object ans its children.
template<typename T >
const char * GetName (T *p)
Function Documentation
createEveShape()
std::pair< bool, TEveElement * > DD4hep::Utilities::createEveShape (int level, int max_level, TEveElement * p, TGeoNode * n, TGeoHMatrix mat, const std::string & node_name)
Definition at line 77 of file Utilities.cpp.
References dd4hep::g, DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::printout(), and DD4hep::Geometry::VisAttr::rgb().
Referenced by LoadDetElement(), and DD4hep::Display::LoadGeoChildren().
findNodeWithMatrix()
int DD4hep::Utilities::findNodeWithMatrix (TGeoNode * p, TGeoNode * n, TGeoHMatrix * mat, std::string * sub_path = 0)
Definition at line 163 of file Utilities.cpp.
Referenced by DD4hep::Display::LoadGeoChildren().
GetName()
template<typename T > const char* DD4hep::Utilities::GetName (T * p) inline
Definition at line 45 of file Utilities.h.
Referenced by DD4hep::Simulation::Geant4HitCollection::add(), DD4hep::Simulation::Geant4SensitiveDetector::createCollection(), DD4hep::Projection::ImportElement(), DD4hep::View::ImportEventElement(), DD4hep::Display::LoadGeoChildren(), DD4hep::Display::MakeNodesVisible(), DD4hep::Simulation::Geant4SensitiveDetector::name(), and DD4hep::Geometry::VisAttr::toString().
LoadDetElement()
std::pair< bool, TEveElement * > DD4hep::Utilities::LoadDetElement (Geometry::DetElement element, int levels, TEveElement * parent)
Definition at line 189 of file Utilities.cpp.
References createEveShape(), e, DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::View::CreateGeometry(), and DD4hep::Display::LoadGeoChildren().
MakeNodesVisible()
void DD4hep::Utilities::MakeNodesVisible (TEveElement * e, bool visible, int level)
Make a set of nodes starting from a top element (in-)visible with a given depth.
Definition at line 58 of file Utilities.cpp.
References e, s, SetRnrAll(), and SetRnrChildren().
Referenced by DD4hep::Display::MakeNodesVisible().
SetRnrAll()
void DD4hep::Utilities::SetRnrAll (TEveElementList * l, bool b)
Recursively set the rendering flags for the object ans its children.
Definition at line 47 of file Utilities.cpp.
References e.
Referenced by MakeNodesVisible().
SetRnrChildren()
void DD4hep::Utilities::SetRnrChildren (TEveElementList * l, bool b)
Set the rendering flags for the object and the next level children.
Definition at line 39 of file Utilities.cpp.
Referenced by MakeNodesVisible().