DD4hep: ROOT::Math Namespace Reference
ROOT::Math Namespace Reference
Classes and namespaces from the ROOT project. See http://root.cern.ch
ROOT namespace for mathematical operations and corresponding classes.
Typedefs
typedef DD4hep::Geometry::Position Position
Functions
double operator* (const Position &l, const Position &r)
Dot product of 3-vectors.
double mean_length (const Position &p1, const Position &p2)
Calculate the mean length of two vectors.
Position mean_direction (const Position &p1, const Position &p2)
Calculate the mean direction of two vectors.
bool operator< (const XYZPoint &a, const XYZPoint &b)
Allow point insertion of a point in maps.
bool operator< (const XYZVector &a, const XYZVector &b)
Allow 3-vector insertion of a in maps.
bool operator< (const PxPyPzEVector &a, const PxPyPzEVector &b)
Allow 4-vector insertion of a in maps.
Detailed Description
ROOT namespace for mathematical operations and corresponding classes.
Typedef Documentation
Position
typedef DD4hep::Geometry::Position ROOT::Math::Position
Definition at line 569 of file Objects.h.
Function Documentation
mean_direction()
Position ROOT::Math::mean_direction (const Position & p1, const Position & p2) inline
Calculate the mean direction of two vectors.
Definition at line 579 of file Objects.h.
References DD4hep::Handle< T >::operator<().
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::process(), and Tests::Geant4SensitiveAction< T >::process().
mean_length()
double ROOT::Math::mean_length (const Position & p1, const Position & p2) inline
Calculate the mean length of two vectors.
Definition at line 575 of file Objects.h.
Referenced by Tests::Geant4SensitiveAction< T >::process().
operator*()
double ROOT::Math::operator* (const Position & l, const Position & r) inline
Dot product of 3-vectors.
Definition at line 571 of file Objects.h.
operator<() [1/3]
bool ROOT::Math::operator< (const XYZPoint & a, const XYZPoint & b)
Allow point insertion of a point in maps.
operator<() [2/3]
bool ROOT::Math::operator< (const XYZVector & a, const XYZVector & b)
Allow 3-vector insertion of a in maps.
operator<() [3/3]
bool ROOT::Math::operator< (const PxPyPzEVector & a, const PxPyPzEVector & b)
Allow 4-vector insertion of a in maps.