DD4hep: DD4hep Namespace Reference
DD4hep Namespace Reference
Namespace for the AIDA detector description toolkit.
Namespaces
Alignments
Namespace for the alignment part of the AIDA detector description toolkit.
Conditions
Namespace for the conditions part of the AIDA detector description toolkit.
DDAlign
Namespace for the AIDA detector description toolkit supporting XML utilities.
DDEve
Namespace for the DD4hep event display specializations.
DDRec
Namespace for the reconstruction part of the AIDA detector description toolkit.
DDSegmentation
Namespace for base segmentations.
Errors
Utility namespace: Errors.
Geometry
Namespace for the geometry part of the AIDA detector description toolkit.
Parsers
Namespace for the AIDA detector for utilities using boost::spirit parsers.
Simulation
Namespace for the Geant4 based simulation part of the AIDA detector description toolkit.
Utilities
Utils
Utility namespace to support boost::spirit.
XML
Namespace containing utilities to parse XML files using XercesC or TinyXML.
Classes
class Annotation
Class to add annotations to eve viewers.
class Apply1rst
Generic map Functor to act on first element (key)
class Apply2nd
Generic map Functor to act on second element (mapped type)
class ApplyFactory
Template class with a generic signature to apply LCDD plugins.
struct ApplyMemFunc
Member function call-functor with no arguments.
struct ApplyMemFunc1
Member function call-functor with 1 argument.
struct ApplyMemFunc2
Member function call-functor with 2 arguments.
struct ApplyMemFuncConst
Member function call-functor with no arguments (const version)
struct ApplyMemFuncConst1
Member function call-functor with 1 argument (const version)
struct ApplyMemFuncConst2
Member function call-functor with 2 arguments (const version)
class BasicGrammar
Base class describing string evaluation to C++ objects using boost::spirit.
struct BoxsetCreator
Fill a 3D box set from a hit collection.
class ByName
Helper functor to select elements by name (using name() member method)
class ByNameAttr
Helper functor to select elements by name (using name member variable)
class Callback
Definition of the generic callback structure for member functions.
struct CallbackSequence
Definition of an actor on sequences of callbacks.
class Calo2DProjection
2D projection operator for calorimeters
class Calo3DProjection
3D projection for calorimeters
class CaloLego
Lego plot for calorimeter energy deposits.
class ComponentCast
Class to perform dynamic casts using unknown pointers.
class ConstructionFactory
Template class with a generic constructor signature.
class ContextMenu
class ContextMenuHandler
struct Converter
Basic conversion objects for handling DD4hep XML files.
class dd4hep_file
DD4hep file handling extension to boost::iostreams.
class dd4hep_file_sink
DD4hep file sink extension to boost::iostreams.
class dd4hep_file_source
DD4hep file source extension to boost::iostreams.
struct dd4hep_lock_t
struct dd4hep_mutex_t
class dd4hep_ptr
Out version of the std auto_ptr implementation base either on auto_ptr or unique_ptr.
class DD4hepMenu
DD4hep Menu for the ROOT browser.
struct DDEve
class DDEveHit
DDEve event classes: Basic hit.
struct DDEveHitActor
Event data actor base class for hits. Used to extract data from concrete classes.
class DDEveParticle
Data structure to store the MC particle information.
struct DDEveParticleActor
Event data actor base class for particles. Used to extract data from concrete classes.
class DDG4EventHandler
class DestroyFirst
map Functor to delete objects from heap
class DestroyHandle
Functor to destroy handles and delete the cached object.
class DestroyHandles
map Functor to destroy handles and delete the cached object
class DestroyObject
Functor to delete objects from heap and reset the pointer.
class DestroyObjects
map Functor to delete objects from heap
class DetElementFactory
Standard factory to create Detector elements from the compact XML representation.
class DetType
class Display
The main class of the DDEve display.
class DisplayConfiguration
DisplayConfiguration DisplayConfiguration.h DDEve/DisplayConfiguration.h.
class ElementList
Local implementation with overrides of the TEveElementList.
class ElementListContextMenu
DDEve context menu class.
struct EtaPhiHistogramActor
Fill EtaPhi histograms from a hit collection.
class EventConsumer
class EventControl
class EventHandler
Event handler base class. Interface to all DDEve I/O actions.
class EvePgonSetProjectedContextMenu
class EvePgonSetProjectedContextMenu EvePgonSetProjectedContextMenu.h DDEve/EvePgonSetProjectedContextMenu.h
class EveShapeContextMenu
class EveShapeContextMenu EveShapeContextMenu.h DDEve/EveShapeContextMenu.h
class EveUserContextMenu
class EveUserContextMenu EveUserContextMenu.h DDEve/EveUserContextMenu.h
class FrameControl
class FrameControl FrameControl.h DDEve/FrameControl.h
class Geant4SensitiveDetectorFactory
Deprecated: Templated factory method to create sensitive detector.
class Geant4SetupAction
Templated factory method to invoke setup action.
class GearHandle
class GenericEventHandler
Event handler base class. Interface to all DDEve I/O actions.
class Grammar
Concrete type dependent grammar definition.
class Handle
Handle: a templated class like a shared pointer, which allows specialized access to tgeometry objects.
struct Increment
Helper class to count call stack depths of certain functions.
struct InstanceCount
Helper to support object counting when debugging memory leaks.
class invalid_handle_exception
Specialized exception to be thrown if invalid handles are accessed.
class IOV
Class describing the interval of validty.
class IOVType
Class describing the interval of validty type.
class Layer
Class to describe one layer in a layering stack.
class Layering
Class to convert a layering object from the compact notation.
class LayerSlice
Class to describe the slice of one layer in a layering stack.
class LayerStack
Class to describe a layering stack.
class LCDDConstructionFactory
class LCDDLoad
Data implementation class of the LCDD interface.
class LCIOEventHandler
struct MCParticleCreator
Fill eve particles from a MC particle collection.
class MultiView
class MultiView MultiView.h DDEve/MultiView.h
class NamedObject
Implementation of a named object.
class ObjectExtensions
Implementation of an object supporting arbitrary user extensions.
class OpaqueData
Class describing an opaque data block.
class OpaqueDataBlock
Class describing an opaque conditions data block.
class OutsideGeometryException
class Path
Path handling class.
struct PluginDebug
Helper to debug plugin manager calls.
struct PluginFactoryBase
Factory base class implementing some utilities.
class PluginRegistry
Factory template for the plugin mechanism.
class PluginService
Factory template for the plugin mechanism.
struct PointsetCreator
Fill a 3D pointset from a hit collection.
class PopupMenu
class PopupMenu PopupMenu.h DDEve/PopupMenu.h
struct Primitive
A bit of support for printing primitives.
class Printer
Helper class template to implement ASCII object dumps.
class PrintMap
Helper class template to implement ASCII dumps of named objects maps.
class Projection
class Projection Projection.h DDEve/Projection.h
class Property
The property class to assign options to actions.
class PropertyConfigurable
Property object as base class for all objects supporting properties.
class PropertyConfigurator
Heler class to configure properties.
class PropertyGrammar
Class describing the grammar representation of a given data type.
class PropertyManager
Manager to ease the handling of groups of properties.
class PropertyValue
Concrete template instantiation of a combined property value pair.
class ReferenceBitMask
Data structure to manipulate a bitmask held by reference and represented by an integer.
class ReferenceObject
Functor to delete objects from heap and reset the pointer.
class ReferenceObjects
Functor to delete objects from heap and reset the pointer.
class ReleaseHandle
Functor to destroy handles and delete the cached object.
class ReleaseHandles
map Functor to release handles
class ReleaseObject
Functor to release objects from heap and reset the pointer.
class ReleaseObjects
Map Functor to release objects from heap.
class RhoPhiProjection
class RhoPhiProjection RhoPhiProjection.h DDEve/RhoPhiProjection.h
class RhoZProjection
class RhoZProjection RhoZProjection.h DDEve/RhoZProjection.h
class ROOTUI
ROOT interactive UI for DD4hep applications.
class SegmentationFactory
class Select1st
Operator to select the first element of a pair.
class Select2nd
Operator to select second element of a pair.
class SurfaceInstaller
struct TowersetCreator
Fill a 3D tower set from a hit collection.
class TranslationFactory
Specialized factory to translate objects, which can be retrieved from LCDD.
struct unrelated_type_error
Exception class to signal operations on unrelated classes.
struct unrelated_value_error
Exception class to signal operations on unrelated types of values.
class View
class View View.h DDEve/View.h
class View3D
class View3D View3D.h DDEve/View3D.h
class ViewMenu
class ViewMenu ViewMenu.h DDEve/ViewMenu.h
class XMLConversionFactory
Read an arbitrary XML document and analyze it's content.
class XMLDocumentReaderFactory
Read an arbitrary XML document and analyze it's content.
class XMLElementFactory
Create an arbitrary object from it's XML representation.
Typedefs
typedef map< string, int > map_string_int
typedef map< string, string > map_string_string
typedef Handle< NamedObject > Ref_t
Default Ref_t definition describing named objects.
typedef size_t(* output_function1_t) (void *, PrintLevel severity, const char *, const char *)
typedef size_t(* output_function2_t) (void *, PrintLevel severity, const char *, const char *, va_list &args)
typedef DD4hep::Geometry::LCDD lcdd_t
typedef DD4hep::Geometry::DetElement DetElement
typedef DD4hep::Geometry::SensitiveDetector SensitiveDetector
typedef std::vector< DDEveHit > DDEveHits
typedef std::vector< DDEveParticle > DDEveParticles
typedef DisplayConfiguration::Configurations Configurations
typedef DisplayConfiguration::ViewConfigurations ViewConfigurations
typedef long long int long64
typedef unsigned long long ulong64
Enumerations
enum LCDDBuildType {
BUILD_NONE = 0, BUILD_DEFAULT = 1, BUILD_SIMU = BUILD_DEFAULT, BUILD_RECO,
BUILD_DISPLAY, BUILD_ENVELOPE
}
Detector description build types.
enum PrintLevel {
NOLOG = 0, VERBOSE =1, DEBUG =2, INFO =3,
WARNING =4, ERROR =5, FATAL =6, ALWAYS
}
enum dd4hep_file_flags { never_close_handle = 0, close_handle = 3 }
Functions
DD4HEP_DEFINE_PROPERTY_CONT (bool)
DD4HEP_DEFINE_PROPERTY_U_CONT (int)
DD4HEP_DEFINE_PROPERTY_U_CONT (long)
DD4HEP_DEFINE_PROPERTY_CONT (float)
DD4HEP_DEFINE_PROPERTY_CONT (double)
DD4HEP_DEFINE_PROPERTY_CONT (string)
DD4HEP_DEFINE_PROPERTY_TYPE (map_string_int)
DD4HEP_DEFINE_PROPERTY_TYPE (map_string_string)
DD4HEP_DEFINE_PROPERTY_TYPE (ROOT::Math::XYZPoint)
DD4HEP_DEFINE_PROPERTY_TYPE (ROOT::Math::XYZVector)
DD4HEP_DEFINE_PROPERTY_TYPE (ROOT::Math::PxPyPzEVector)
XmlTools::Evaluator & evaluator ()
long num_object_validations ()
void increment_object_validations ()
void warning_deprecated_xml_factory (const char *name)
Function tp print warning about deprecated factory usage. Used by Plugin mechanism.
static ComponentCast * component (void *p)
void * createPlugin (const std::string &factory, Geometry::LCDD &lcdd, int argc, char **argv, void *(*cast)(void *))
void * createPlugin (const std::string &factory, Geometry::LCDD &lcdd, void *(*cast)(void *))
Handler for factories of type: ConstructionFactory.
void * createPlugin (const std::string &factory, Geometry::LCDD &lcdd, const std::string &arg, void *(*cast)(void *))
Handler for factories of type: ConstructionFactory.
static std::string pre_parse_obj (const std::string &in)
Helper function to parse data type.
template<typename TYPE >
static int fill_data (std::vector< TYPE > *p, const std::vector< std::string > &temp)
Insertion function for std vectors.
template<typename TYPE >
static int fill_data (std::list< TYPE > *p, const std::vector< std::string > &temp)
Insertion function for std lists.
template<typename TYPE >
static int fill_data (std::set< TYPE > *p, const std::vector< std::string > &temp)
Insertion function for std sets.
template<typename TYPE >
static int fill_data (std::deque< TYPE > *p, const std::vector< std::string > &temp)
Insertion function for std sets.
template<typename KEY , typename TYPE >
static int fill_data (std::map< KEY, TYPE > *p, const std::vector< std::string > &temp)
Insertion function for std sets.
template<typename TYPE >
static int eval_container (TYPE *p, const std::string &str)
Container evaluator.
template<typename T >
int eval_item (T *p, std::string s)
Item evaluator.
template<>
int eval_item< std::string > (std::string *p, std::string s)
String evaluator.
template<typename T , typename Q >
int eval_pair (std::pair< T, Q > *p, std::string s)
Item evaluator.
template<typename T >
int eval_obj (T *p, const std::string &str)
Object evaluator.
template<typename T >
int eval_none (T *, const std::string &)
template<typename T >
int parse_none (T &, const std::string &)
std::ostream & operator<< (std::ostream &os, const DetType &t)
void run_interpreter (const std::string &name)
XmlTools::Evaluator & g4Evaluator ()
unsigned long long int magic_word ()
Access to the magic word, which is protecting some objects against memory corruptions.
template<typename T >
void destroyHandle (T &h)
Helper to delete objects from heap and reset the handle.
template<typename M >
void destroyHandles (M &m)
Functional created of map destruction functors.
template<typename T >
void releaseHandle (T &h)
Helper to delete objects from heap and reset the handle.
template<typename M >
void releaseHandles (M &m)
Functional created of map destruction functors.
std::string _toString (bool value)
String conversions: boolean value to string.
std::string _toString (short value, const char *fmt="%d")
String conversions: integer value to string.
std::string _toString (int value, const char *fmt="%d")
String conversions: integer value to string.
std::string _toString (float value, const char *fmt="%.17e")
String conversions: float value to string.
std::string _toString (double value, const char *fmt="%.17e")
String conversions: double value to string.
std::string _ptrToString (const void *p, const char *fmt="%p")
Pointer to text conversion.
template<typename T >
std::string _toString (const T *p, const char *fmt="%p")
Format any pointer (64 bits) to string.
bool _toBool (const std::string &value)
String conversions: string to boolean value.
short _toShort (const std::string &value)
String conversions: string to integer value.
int _toInt (const std::string &value)
String conversions: string to integer value.
long _toLong (const std::string &value)
String conversions: string to long integer value.
float _toFloat (const std::string &value)
String conversions: string to float value.
double _toDouble (const std::string &value)
String conversions: string to double value.
bool _toBool (bool value)
Void helper function to support formalisms.
short _toShort (short value)
Void helper function to support formalisms.
int _toInt (int value)
Void helper function to support formalisms.
long _toLong (long value)
Void helper function to support formalisms.
unsigned short _toUShort (unsigned short value)
Void helper function to support formalisms.
unsigned int _toUInt (unsigned int value)
Void helper function to support formalisms.
unsigned long _toULong (unsigned long value)
Void helper function to support formalisms.
float _toFloat (float value)
Void helper function to support formalisms.
double _toDouble (double value)
Void helper function to support formalisms.
template<class T >
T _multiply (const std::string &left, T right)
Generic multiplication using the evaluator: result = left * right.
template<class T >
T _multiply (T left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<class T >
T _multiply (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
char _multiply< char > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
char _multiply< char > (char left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
char _multiply< char > (const std::string &left, char right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned char _multiply< unsigned char > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned char _multiply< unsigned char > (unsigned char left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned char _multiply< unsigned char > (const std::string &left, unsigned char right)
Generic multiplication using the evaluator: result = left * right.
template<>
short _multiply< short > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
short _multiply< short > (short left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
short _multiply< short > (const std::string &left, short right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned short _multiply< unsigned short > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned short _multiply< unsigned short > (unsigned short left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned short _multiply< unsigned short > (const std::string &left, unsigned short right)
Generic multiplication using the evaluator: result = left * right.
template<>
int _multiply< int > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
int _multiply< int > (int left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
int _multiply< int > (const std::string &left, int right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned int _multiply< unsigned int > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned int _multiply< unsigned int > (unsigned int left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned int _multiply< unsigned int > (const std::string &left, unsigned int right)
Generic multiplication using the evaluator: result = left * right.
template<>
long _multiply< long > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
long _multiply< long > (long left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
long _multiply< long > (const std::string &left, long right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned long _multiply< unsigned long > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned long _multiply< unsigned long > (unsigned long left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
unsigned long _multiply< unsigned long > (const std::string &left, unsigned long right)
Generic multiplication using the evaluator: result = left * right.
template<>
float _multiply< float > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
float _multiply< float > (float left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
float _multiply< float > (const std::string &left, float right)
Generic multiplication using the evaluator: result = left * right.
template<>
double _multiply< double > (const std::string &left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
template<>
double _multiply< double > (const std::string &left, double right)
Generic multiplication using the evaluator: result = left * right.
template<>
double _multiply< double > (double left, const std::string &right)
Generic multiplication using the evaluator: result = left * right.
void _toDictionary (const std::string &name, const std::string &value)
Enter name value pair to the dictionary. "value" must be a numerical expression, which is evaluated.
void _toDictionary (const std::string &name, const std::string &value, const std::string &typ)
Enter name value pair to the dictionary.
std::string versionString ()
return a string with the current DD4hep version in the form vXX-YY.
template<typename T >
ByName< T > byName (const std::string &n)
template<typename T >
ByName< T > byName (const T *o)
template<typename T >
ByName< T > byName (const T &o)
template<typename T >
ByNameAttr< T > byNameAttr (const std::string &nam)
template<typename T >
ByNameAttr< T > byNameAttr (const T *o)
template<typename T >
ByNameAttr< T > byNameAttr (const T &o)
template<typename T >
T * createPlugin (const std::string &factory, Geometry::LCDD &lcdd)
Handler for factories of type: ConstructionFactory with casted return type.
template<typename T >
T * createPlugin (const std::string &factory, Geometry::LCDD &lcdd, const std::string &arg)
Handler for factories of type: ConstructionFactory with casted return type.
template<typename T >
T * createPlugin (const std::string &factory, Geometry::LCDD &lcdd, int argc, const void **argv)
Handler for factories of type: ConstructionFactory with casted return type.
template<>
std::string PluginFactoryBase::value< std::string > (const void *p)
template<>
const std::string & PluginFactoryBase::value< const std::string & > (const void *p)
unsigned int hash32 (const char *key)
We need it so often: one-at-time 32 bit hash function.
unsigned int hash32 (const std::string &key)
long int makeTime (int year, int month, int day, int hour=0, int minutes=0, int seconds=0)
Convert date into epoch time (seconds since 1970)
long int makeTime (const std::string &date, const char *fmt="%d-%m-%Y %H:%M:%S")
Convert date into epoch time (seconds since 1970)
std::string typeName (const std::type_info &type)
ABI information about type names.
void typeinfoCheck (const std::type_info &typ1, const std::type_info &typ2, const std::string &text="")
Check type infos for equivalence (dynamic casts) using ABI information.
void invalidHandleError (const std::type_info &type)
Throw exception when handles are check for validity.
void invalidHandleAssignmentError (const std::type_info &from, const std::type_info &to)
Throw exception when handles are badly assigned.
template<typename T >
void invalidHandleError ()
Throw exception when handles are check for validity.
void notImplemented (const std::string &msg)
Throw exception when handles are check for validity.
template<typename T >
void copyObject (void *target, const void *source)
Helper to copy objects.
template<typename T >
void destructObject (T *p)
Helper to destruct objects. Note: The memory is NOT released!
template<typename T >
void deletePtr (T *&p)
Helper to delete objects from heap and reset the pointer. Saves many many lines of code.
template<typename T >
void deleteObject (T *p)
Helper to delete objects from heap and reset the pointer. Saves many many lines of code.
template<typename T >
void destroyObject (T *&p)
Helper to delete objects from heap and reset the pointer.
template<typename T >
Select2nd< typename T::value_type > select2nd (const T &)
Generator to create Operator to select value elements of a map.
template<typename T >
Select1st< typename T::value_type > select1st (const T &)
Generator to create Operator to select key values of a map.
template<typename M >
void destroyObjects (M &m)
template<typename M >
DestroyObjects< M > destroy2nd (M &m)
template<typename M >
void destroyFirst (M &m)
template<typename M >
void destroy1st (M &m)
template<typename T >
void releasePtr (T &p)
Helper to delete objects from heap and reset the pointer. Saves many many lines of code.
template<typename M >
ReleaseObject< typename M::value_type > releaseObject (M &)
template<typename M >
void releaseObjects (M &m)
template<typename M >
void release2nd (M &m)
template<typename M >
ReferenceObject< M > referenceObject (M &)
template<typename M >
ReferenceObjects< typename M::value_type > reference2nd (M &)
template<typename C , typename R , typename T >
void call_member_func (C &object, R(T::*pmf)())
template<typename C , typename R , typename T , typename A1 >
void call_member_func (C &object, R(T::*pmf)(A1 a1), A1 a1)
template<typename C , typename R , typename T , typename A1 , typename A2 >
void call_member_func (C &object, R(T::*pmf)(A1 a1, A2 a2), A1 a1, A2 a2)
template<typename C , typename FCN >
Apply1rst< C, FCN > apply__1rst_value (C &, const FCN &func)
template<typename C , typename FCN >
void apply1rst (C &object, const FCN &func)
template<typename C , typename R , typename T >
void apply1rst (C &object, R(T::*pmf)())
template<typename C , typename R , typename T , typename A1 >
void apply1rst (C object, R(T::*pmf)(A1 a1), A1 a1)
template<typename C , typename FCN >
Apply2nd< C, FCN > apply__2nd_value (C &, const FCN &func)
template<typename C , typename FCN >
void apply2nd (C &object, const FCN &func)
template<typename C , typename R , typename T >
void apply2nd (C &object, R(T::*pmf)())
template<typename C , typename R , typename T , typename A1 >
void apply2nd (C object, R(T::*pmf)(A1 a1), A1 a1)
int printout (PrintLevel severity, const char *src, const char *fmt,...)
int printout (PrintLevel severity, const std::string &src, const char *fmt,...)
int printout (PrintLevel severity, const std::string &src, const std::string &fmt,...)
int printout (PrintLevel severity, const char *src, const std::string &fmt,...)
int printout (PrintLevel severity, const char *src, const char *fmt, va_list &args)
int printout (PrintLevel severity, const std::string &src, const char *fmt, va_list &args)
int printout (PrintLevel severity, const std::string &src, const std::string &fmt, va_list &args)
int printout (PrintLevel severity, const char *src, const std::string &fmt, va_list &args)
void except (const std::string &src, const std::string &fmt,...)
void except (const char *src, const char *fmt,...)
void except (const std::string &src, const std::string &fmt, va_list &args)
void except (const char *src, const char *fmt, va_list &args)
std::string format (const std::string &src, const std::string &fmt,...)
std::string format (const char *src, const char *fmt,...)
std::string format (const std::string &src, const std::string &fmt, va_list &args)
std::string format (const char *src, const char *fmt, va_list &args)
void setPrinter (void *print_arg, output_function1_t fcn)
Customize printer function.
void setPrinter2 (void *print_arg, output_function2_t fcn)
Customize printer function.
std::string setPrintFormat (const std::string &new_format)
Set new printout format for the 3 fields: source-level-message. All 3 are strings.
PrintLevel setPrintLevel (PrintLevel new_level)
Set new print level. Returns the old print level.
PrintLevel printLevel ()
Access the current printer level.
template<typename T >
std::ostream & print (const T &object, std::ostream &os=std::cout, const std::string &indent="")
const char * yes_no (bool value)
Helper function to print booleans in format YES/NO.
const char * true_false (bool value)
Helper function to print booleans in format true/false.
void EveDisplay (const char *xmlFile, const char *eventFileName)
gear::GearMgr * createGearMgr (Geometry::LCDD &lcdd, const std::string &pluginName)
Variables
static long s_numVerifies = 0
Detailed Description
Namespace for the AIDA detector description toolkit.
Main handle class to hold a TGeo alignment object of type TGeoPhysicalNode.
Geant 4 forward declarations.
DD4hep namespace declaration.
Namespace for the AIDA detector description toolkit
Typedef Documentation
Configurations
typedef DisplayConfiguration::Configurations DD4hep::Configurations
Definition at line 48 of file DisplayConfigurationParser.cpp.
DDEveHits
typedef std::vector<DDEveHit> DD4hep::DDEveHits
Definition at line 50 of file DDEveEventData.h.
DDEveParticles
typedef std::vector<DDEveParticle> DD4hep::DDEveParticles
Definition at line 74 of file DDEveEventData.h.
DetElement
typedef DD4hep::Geometry::DetElement DD4hep::DetElement
Definition at line 32 of file Geant4XMLSetup.cpp.
lcdd_t
typedef DD4hep::Geometry::LCDD DD4hep::lcdd_t
Definition at line 31 of file Geant4XMLSetup.cpp.
long64
typedef long long int DD4hep::long64
Definition at line 15 of file BitField64.h.
map_string_int
typedef map<string, int> DD4hep::map_string_int
Definition at line 284 of file ComponentProperties.cpp.
map_string_string
typedef map<string, string> DD4hep::map_string_string
Definition at line 287 of file ComponentProperties.cpp.
output_function1_t
typedef size_t(* DD4hep::output_function1_t) (void *, PrintLevel severity, const char *, const char *)
Definition at line 52 of file Printout.h.
output_function2_t
typedef size_t(* DD4hep::output_function2_t) (void *, PrintLevel severity, const char *, const char *, va_list &args)
Definition at line 53 of file Printout.h.
SensitiveDetector
typedef DD4hep::Geometry::SensitiveDetector DD4hep::SensitiveDetector
Definition at line 33 of file Geant4XMLSetup.cpp.
ulong64
typedef unsigned long long DD4hep::ulong64
Definition at line 16 of file BitField64.h.
ViewConfigurations
typedef DisplayConfiguration::ViewConfigurations DD4hep::ViewConfigurations
Definition at line 49 of file DisplayConfigurationParser.cpp.
Enumeration Type Documentation
dd4hep_file_flags
enum DD4hep::dd4hep_file_flags
Enumerator
never_close_handle
close_handle
Definition at line 51 of file IoStreams.h.
LCDDBuildType
enum DD4hep::LCDDBuildType
Detector description build types.
enum LCDDBuildType LCDD.h DD4hep/LCDD.h The corresponding flag is ONLY valid while parsing the compact description. If no eometry, ie. at all other times the accessor to the flag returns BUILD_NONE.
Enumerator
BUILD_NONE
BUILD_DEFAULT
BUILD_SIMU
BUILD_RECO
BUILD_DISPLAY
BUILD_ENVELOPE
Definition at line 65 of file LCDD.h.
PrintLevel
enum DD4hep::PrintLevel
Enumerator
NOLOG
VERBOSE
DEBUG
INFO
WARNING
ERROR
FATAL
ALWAYS
Definition at line 47 of file Printout.h.
Function Documentation
_ptrToString()
string DD4hep::_ptrToString (const void * p, const char * fmt = "%p")
Pointer to text conversion.
Definition at line 233 of file Handle.cpp.
References __to_string().
Referenced by _toString(), and releaseHandles().
apply1rst() [1/3]
template<typename C , typename FCN > void DD4hep::apply1rst (C & object, const FCN & func)
Definition at line 469 of file Primitives.h.
References apply__1rst_value().
Referenced by apply1rst().
apply1rst() [2/3]
template<typename C , typename R , typename T > void DD4hep::apply1rst (C & object, R(T::*)() pmf)
Definition at line 473 of file Primitives.h.
References apply__1rst_value().
apply1rst() [3/3]
template<typename C , typename R , typename T , typename A1 > void DD4hep::apply1rst (C object, R(T::*)(A1 a1) pmf, A1 a1)
Definition at line 477 of file Primitives.h.
References apply1rst(), and apply__1rst_value().
apply2nd() [1/3]
template<typename C , typename FCN > void DD4hep::apply2nd (C & object, const FCN & func)
Definition at line 502 of file Primitives.h.
References apply__2nd_value().
Referenced by apply2nd().
apply2nd() [2/3]
template<typename C , typename R , typename T > void DD4hep::apply2nd (C & object, R(T::*)() pmf)
Definition at line 506 of file Primitives.h.
References apply__2nd_value().
apply2nd() [3/3]
template<typename C , typename R , typename T , typename A1 > void DD4hep::apply2nd (C object, R(T::*)(A1 a1) pmf, A1 a1)
Definition at line 510 of file Primitives.h.
References apply2nd(), and apply__2nd_value().
apply__1rst_value()
template<typename C , typename FCN > Apply1rst<C,FCN> DD4hep::apply__1rst_value (C & , const FCN & func)
Definition at line 466 of file Primitives.h.
Referenced by apply1rst().
apply__2nd_value()
template<typename C , typename FCN > Apply2nd<C,FCN> DD4hep::apply__2nd_value (C & , const FCN & func)
Definition at line 499 of file Primitives.h.
Referenced by apply2nd().
byName() [1/3]
template<typename T > ByName<T> DD4hep::byName (const std::string & n)
Definition at line 40 of file Operators.h.
byName() [2/3]
template<typename T > ByName<T> DD4hep::byName (const T * o)
Definition at line 41 of file Operators.h.
byName() [3/3]
template<typename T > ByName<T> DD4hep::byName (const T & o)
Definition at line 42 of file Operators.h.
byNameAttr() [1/3]
template<typename T > ByNameAttr<T> DD4hep::byNameAttr (const std::string & nam)
Definition at line 62 of file Operators.h.
byNameAttr() [2/3]
template<typename T > ByNameAttr<T> DD4hep::byNameAttr (const T * o)
Definition at line 63 of file Operators.h.
byNameAttr() [3/3]
template<typename T > ByNameAttr<T> DD4hep::byNameAttr (const T & o)
Definition at line 64 of file Operators.h.
call_member_func() [1/3]
template<typename C , typename R , typename T > void DD4hep::call_member_func (C & object, R(T::*)() pmf)
Definition at line 430 of file Primitives.h.
Referenced by call_member_func().
call_member_func() [2/3]
template<typename C , typename R , typename T , typename A1 > void DD4hep::call_member_func (C & object, R(T::*)(A1 a1) pmf, A1 a1)
Definition at line 438 of file Primitives.h.
References call_member_func().
call_member_func() [3/3]
template<typename C , typename R , typename T , typename A1 , typename A2 > void DD4hep::call_member_func (C & object, R(T::*)(A1 a1, A2 a2) pmf, A1 a1, A2 a2)
Definition at line 447 of file Primitives.h.
References call_member_func().
component()
static ComponentCast* DD4hep::component (void * p) inline static
Definition at line 24 of file PluginCreators.cpp.
Referenced by create_element(), createPlugin(), and DD4hep::SurfaceInstaller::stopScanning().
copyObject()
template<typename T > void DD4hep::copyObject (void * target, const void * source) inline
Helper to copy objects.
Definition at line 225 of file Primitives.h.
References s.
createGearMgr()
gear::GearMgr * DD4hep::createGearMgr (Geometry::LCDD & lcdd, const std::string & pluginName = "GearForILD")
Factory method that creates a GearMgr object pobulated with the GearParametersImpl objects from all (top level) DetElements in the lcdd object
Author
F.Gaede, DESY
Version
$Id$
register any materials assigned to the handle:
Definition at line 28 of file DDGear.cpp.
References DD4hep::Geometry::LCDD::apply(), DD4hep::Geometry::DetElement::children(), e, DD4hep::Geometry::LCDD::field(), DD4hep::Geometry::LCDD::header(), DD4hep::Geometry::OverlayedField::magneticField(), DD4hep::GearHandle::materials(), DD4hep::GearHandle::name(), DD4hep::Geometry::Header::name(), DD4hep::GearHandle::takeGearObject(), dd4hep::tesla, DD4hep::Geometry::DetElement::volume(), and DD4hep::Geometry::LCDD::world().
Referenced by DD4hep::GearHandle::GearHandle(), and main().
createPlugin() [1/6]
void * DD4hep::createPlugin (const std::string & factory, Geometry::LCDD & lcdd, int argc, char ** argv, void *(*)(void *) cast)
Definition at line 26 of file PluginCreators.cpp.
References component(), except(), invalidHandleAssignmentError(), and DD4hep::PluginDebug::missingFactory().
Referenced by createPlugin().
createPlugin() [2/6]
template<typename T > T* DD4hep::createPlugin (const std::string & factory, Geometry::LCDD & lcdd)
Handler for factories of type: ConstructionFactory with casted return type.
Definition at line 44 of file PluginCreators.h.
References createPlugin().
createPlugin() [3/6]
void * DD4hep::createPlugin (const std::string & factory, Geometry::LCDD & lcdd, void *(*)(void *) cast)
Handler for factories of type: ConstructionFactory.
Signature: void* create(const char* arg);
An exception is thrown in the event the object cannot be created. The object is properly casted before given to the caller.
Definition at line 46 of file PluginCreators.cpp.
References createPlugin().
createPlugin() [4/6]
template<typename T > T* DD4hep::createPlugin (const std::string & factory, Geometry::LCDD & lcdd, const std::string & arg)
Handler for factories of type: ConstructionFactory with casted return type.
Definition at line 50 of file PluginCreators.h.
References createPlugin().
createPlugin() [5/6]
void * DD4hep::createPlugin (const std::string & factory, Geometry::LCDD & lcdd, const std::string & arg, void *(*)(void *) cast)
Handler for factories of type: ConstructionFactory.
Definition at line 53 of file PluginCreators.cpp.
References createPlugin().
createPlugin() [6/6]
template<typename T > T* DD4hep::createPlugin (const std::string & factory, Geometry::LCDD & lcdd, int argc, const void ** argv)
Handler for factories of type: ConstructionFactory with casted return type.
Definition at line 56 of file PluginCreators.h.
References createPlugin().
DD4HEP_DEFINE_PROPERTY_CONT() [1/4]
DD4hep::DD4HEP_DEFINE_PROPERTY_CONT (bool)
Referenced by DD4hep::Utils::toStream().
DD4HEP_DEFINE_PROPERTY_CONT() [2/4]
DD4hep::DD4HEP_DEFINE_PROPERTY_CONT (float)
DD4HEP_DEFINE_PROPERTY_CONT() [3/4]
DD4hep::DD4HEP_DEFINE_PROPERTY_CONT (double)
DD4HEP_DEFINE_PROPERTY_CONT() [4/4]
DD4hep::DD4HEP_DEFINE_PROPERTY_CONT (string)
DD4HEP_DEFINE_PROPERTY_TYPE() [1/5]
DD4hep::DD4HEP_DEFINE_PROPERTY_TYPE (map_string_int)
DD4HEP_DEFINE_PROPERTY_TYPE() [2/5]
DD4hep::DD4HEP_DEFINE_PROPERTY_TYPE (map_string_string)
DD4HEP_DEFINE_PROPERTY_TYPE() [3/5]
DD4hep::DD4HEP_DEFINE_PROPERTY_TYPE (ROOT::Math::XYZPoint)
DD4HEP_DEFINE_PROPERTY_TYPE() [4/5]
DD4hep::DD4HEP_DEFINE_PROPERTY_TYPE (ROOT::Math::XYZVector)
DD4HEP_DEFINE_PROPERTY_TYPE() [5/5]
DD4hep::DD4HEP_DEFINE_PROPERTY_TYPE (ROOT::Math::PxPyPzEVector)
DD4HEP_DEFINE_PROPERTY_U_CONT() [1/2]
DD4hep::DD4HEP_DEFINE_PROPERTY_U_CONT (int)
Referenced by DD4hep::Utils::toStream().
DD4HEP_DEFINE_PROPERTY_U_CONT() [2/2]
DD4hep::DD4HEP_DEFINE_PROPERTY_U_CONT (long)
deleteObject()
template<typename T > void DD4hep::deleteObject (T * p) inline
Helper to delete objects from heap and reset the pointer. Saves many many lines of code.
Definition at line 240 of file Primitives.h.
deletePtr()
template<typename T > void DD4hep::deletePtr (T *& p) inline
Helper to delete objects from heap and reset the pointer. Saves many many lines of code.
Definition at line 234 of file Primitives.h.
Referenced by DD4hep::Simulation::Geant4Output2ROOT::beginRun(), DD4hep::Alignments::AlignmentsManager::destroy(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::destroyClientContext(), DD4hep::Geometry::LCDDData::destroyData(), destroyHandle(), destroyObject(), DD4hep::GenericEventHandler::Open(), DD4hep::Geometry::DetElementObject::revalidate(), DD4hep::Simulation::Geant4UIManager::stop(), DD4hep::Simulation::Geant4ActionContainer::terminate(), DD4hep::Simulation::Geant4Kernel::terminate(), DD4hep::Alignments::AlignmentsManagerObject::~AlignmentsManagerObject(), DD4hep::DD4hepMenu::~DD4hepMenu(), DD4hep::Geometry::DetElementObject::~DetElementObject(), DD4hep::Display::~Display(), DD4hep::Simulation::Geant4GeneratorWrapper::~Geant4GeneratorWrapper(), DD4hep::Simulation::Geant4Kernel::~Geant4Kernel(), DD4hep::Simulation::Geant4Output2LCIO::~Geant4Output2LCIO(), DD4hep::Simulation::Geant4Output2ROOT::~Geant4Output2ROOT(), DD4hep::Simulation::Geant4Random::~Geant4Random(), DD4hep::GenericEventHandler::~GenericEventHandler(), DD4hep::Simulation::LCIOFileReader::~LCIOFileReader(), and DD4hep::Simulation::LCIOStdHepReader::~LCIOStdHepReader().
destroy1st()
template<typename M > void DD4hep::destroy1st (M & m)
Definition at line 312 of file Primitives.h.
destroy2nd()
template<typename M > DestroyObjects<M> DD4hep::destroy2nd (M & m)
Definition at line 295 of file Primitives.h.
destroyFirst()
template<typename M > void DD4hep::destroyFirst (M & m)
Definition at line 310 of file Primitives.h.
Referenced by DD4hep::Simulation::Geant4UIMessenger::~Geant4UIMessenger().
destroyHandles()
template<typename M > void DD4hep::destroyHandles (M & m)
Functional created of map destruction functors.
Definition at line 199 of file Handle.h.
References m.
Referenced by DD4hep::Geometry::LCDDData::destroyData(), DD4hep::Geometry::DetElementObject::~DetElementObject(), and DD4hep::Geometry::VolumeManagerObject::~VolumeManagerObject().
destroyObject()
template<typename T > void DD4hep::destroyObject (T *& p) inline
Helper to delete objects from heap and reset the pointer.
Definition at line 245 of file Primitives.h.
References deletePtr().
Referenced by DD4hep::DestroyObject< T >::operator()().
destroyObjects()
template<typename M > void DD4hep::destroyObjects (M & m)
Definition at line 293 of file Primitives.h.
Referenced by DD4hep::Simulation::Geant4Kernel::destroyPhases(), DD4hep::Alignments::AlignmentStack::~AlignmentStack(), DD4hep::Simulation::Geant4Kernel::~Geant4Kernel(), DD4hep::Simulation::Geant4PrimaryEvent::~Geant4PrimaryEvent(), and DD4hep::Geometry::VolumeManagerObject::~VolumeManagerObject().
destructObject()
template<typename T > void DD4hep::destructObject (T * p) inline
Helper to destruct objects. Note: The memory is NOT released!
Definition at line 230 of file Primitives.h.
eval_container()
template<typename TYPE > static int DD4hep::eval_container (TYPE * p, const std::string & str) static
Container evaluator.
Definition at line 245 of file BasicGrammar_inl.h.
References fill_data(), DD4hep::Parsers::parse(), and pre_parse_obj().
eval_item()
template<typename T > int DD4hep::eval_item (T * p, std::string s) inline
Item evaluator.
Definition at line 273 of file BasicGrammar_inl.h.
References XmlTools::Evaluator::OK.
eval_item< std::string >()
template<> int DD4hep::eval_item< std::string > (std::string * p, std::string s) inline
String evaluator.
Definition at line 292 of file BasicGrammar_inl.h.
References s.
eval_none()
template<typename T > int DD4hep::eval_none (T * , const std::string &) inline
User object evaluator Do NOTHING version! Function present to formally satisfy code. User implementation required
Definition at line 311 of file BasicGrammar_inl.h.
eval_obj()
template<typename T > int DD4hep::eval_obj (T * p, const std::string & str) inline
Object evaluator.
Definition at line 305 of file BasicGrammar_inl.h.
References DD4hep::Grammar< TYPE >::fromString(), and pre_parse_obj().
eval_pair()
template<typename T , typename Q > int DD4hep::eval_pair (std::pair< T, Q > * p, std::string s) inline
Item evaluator.
Definition at line 298 of file BasicGrammar_inl.h.
References DD4hep::BasicGrammar::fromString(), and dd4hep::g.
evaluator()
XmlTools::Evaluator & DD4hep::evaluator ()
Referenced by run_interpreter().
EveDisplay()
void DD4hep::EveDisplay (const char * xmlFile, const char * eventFileName)
Referenced by ClassImp(), and DD4hep::DDEve::run().
except() [1/4]
void DD4hep::except (const std::string & src, const std::string & fmt, ...)
Calls the display action with ERROR and throws an std::runtime_error exception
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 197 of file Printout.cpp.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__get_checked_pool(), _multiply< char >(), _multiply< short >(), _multiply< unsigned char >(), _multiply< unsigned short >(), DD4hep::Conditions::DependencyBuilder::add(), DD4hep::Alignments::Interna::AlignmentContainer::addKey(), DD4hep::Conditions::Interna::ConditionContainer::addKey(), DD4hep::ROOTUI::alignmentMgr(), DD4hep::Geometry::World::alignmentsLoader(), DD4hep::OpaqueDataBlock::assign(), DD4hep::OpaqueDataBlock::bind(), DD4hep::Conditions::Test::check_discrete_condition(), DD4hep::XML::Element::child(), DD4hep::Simulation::Geant4Output2LCIO::commit(), DD4hep::Conditions::ConditionDependency::ConditionDependency(), DD4hep::Conditions::ConditionsDataLoader::ConditionsDataLoader(), DD4hep::Geometry::World::conditionsLoader(), DD4hep::ROOTUI::conditionsMgr(), DD4hep::Simulation::Geant4Action::control(), createPlugin(), DD4hep::XML::createShape(), DD4hep::Simulation::Geant4SensDet::defineCollection(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), except(), DD4hep::Conditions::ConditionsManager::from(), DD4hep::Alignments::AlignmentsManager::from(), DD4hep::Conditions::ConditionsManagerObject::fromString(), DD4hep::Conditions::ConditionsManagerObject::get(), DD4hep::Conditions::ConditionsManagerObject::getRange(), DD4hep::Conditions::ConditionsManagerObject::initialize(), DD4hep::Alignments::AlignmentOperator::insert(), DD4hep::Conditions::ConditionsManagerObject::iovType(), makeTime(), DD4hep::OpaqueDataBlock::operator=(), DD4hep::Conditions::ConditionDependency::operator=(), DD4hep::Simulation::Geant4Action::outputLevel(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), DD4hep::Conditions::ConditionsManagerObject::pushUpdates(), DD4hep::Conditions::Condition::rebind(), DD4hep::Conditions::ConditionsManagerObject::registerCondition(), DD4hep::Conditions::ConditionsManagerObject::registerIOVType(), DD4hep::Conditions::ConditionsManagerObject::registerUnlocked(), DD4hep::Conditions::DependencyBuilder::release(), DD4hep::Geometry::Segmentation::Segmentation(), DD4hep::Conditions::ConditionsManagerObject::select_range(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), and DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository().
except() [2/4]
void DD4hep::except (const char * src, const char * fmt, ...)
Calls the display action with ERROR and throws an std::runtime_error exception
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 208 of file Printout.cpp.
References except().
except() [3/4]
void DD4hep::except (const std::string & src, const std::string & fmt, va_list & args)
Calls the display action with ERROR and throws an std::runtime_error exception
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Definition at line 220 of file Printout.cpp.
References ERROR, and printout().
except() [4/4]
void DD4hep::except (const char * src, const char * fmt, va_list & args)
Calls the display action with ERROR and throws an std::runtime_error exception
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Definition at line 234 of file Printout.cpp.
References ERROR, format(), and printout().
fill_data() [1/5]
template<typename TYPE > static int DD4hep::fill_data (std::vector< TYPE > * p, const std::vector< std::string > & temp) static
Insertion function for std vectors.
Definition at line 185 of file BasicGrammar_inl.h.
References DD4hep::BasicGrammar::fromString(), and dd4hep::g.
Referenced by eval_container().
fill_data() [2/5]
template<typename TYPE > static int DD4hep::fill_data (std::list< TYPE > * p, const std::vector< std::string > & temp) static
Insertion function for std lists.
Definition at line 197 of file BasicGrammar_inl.h.
References DD4hep::BasicGrammar::fromString(), and dd4hep::g.
fill_data() [3/5]
template<typename TYPE > static int DD4hep::fill_data (std::set< TYPE > * p, const std::vector< std::string > & temp) static
Insertion function for std sets.
Definition at line 209 of file BasicGrammar_inl.h.
References DD4hep::BasicGrammar::fromString(), and dd4hep::g.
fill_data() [4/5]
template<typename TYPE > static int DD4hep::fill_data (std::deque< TYPE > * p, const std::vector< std::string > & temp) static
Insertion function for std sets.
Definition at line 221 of file BasicGrammar_inl.h.
References DD4hep::BasicGrammar::fromString(), and dd4hep::g.
fill_data() [5/5]
template<typename KEY , typename TYPE > static int DD4hep::fill_data (std::map< KEY, TYPE > * p, const std::vector< std::string > & temp) static
Insertion function for std sets.
Definition at line 233 of file BasicGrammar_inl.h.
References DD4hep::BasicGrammar::fromString(), and dd4hep::g.
format() [1/4]
string DD4hep::format (const std::string & src, const std::string & fmt, ...)
Build formatted string
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Build exception string
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 247 of file Printout.cpp.
Referenced by DD4hep::Simulation::_create_object(), DD4hep::Simulation::_createAction(), DD4hep::Simulation::Geant4Action::abortRun(), DD4hep::Simulation::Geant4Kernel::addSimplePhase(), DD4hep::Simulation::checked_value(), DD4hep::Simulation::Geant4VolumeManager::checkValidity(), DD4hep::Simulation::Geant4Context::createTrajectory(), DD4hep::Simulation::Geant4Kernel::createWorker(), DD4hep::Simulation::Geant4Sensitive::detector(), except(), DD4hep::Simulation::Geant4Action::except(), format(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), DD4hep::Simulation::Geant4VolumeManager::Geant4VolumeManager(), DD4hep::Simulation::Geant4Kernel::getPhase(), DD4hep::Simulation::Geant4Kernel::globalAction(), DD4hep::Simulation::Geant4Kernel::globalFilter(), DD4hep::Simulation::Geant4SensDetSequences::insert(), DD4hep::Converter< T, ARG >::operator()(), DD4hep::Simulation::Geant4Kernel::PhaseSelector::operator[](), DD4hep::Simulation::Geant4Kernel::registerGlobalAction(), DD4hep::Simulation::Geant4Kernel::registerGlobalFilter(), DD4hep::Simulation::Geant4ActionContainer::registerSequence(), DD4hep::Simulation::Geant4Exec::run(), DD4hep::Simulation::Geant4Kernel::runManager(), DD4hep::Simulation::Geant4Mapping::volumeManager(), DD4hep::Simulation::KernelHandle::worker(), DD4hep::Simulation::Geant4Kernel::worker(), and DD4hep::Simulation::Geant4ActionContainer::workerContext().
format() [2/4]
string DD4hep::format (const char * src, const char * fmt, ...)
Build exception string
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 260 of file Printout.cpp.
References format().
format() [3/4]
string DD4hep::format (const std::string & src, const std::string & fmt, va_list & args)
Build formatted string
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Build exception string and throw std::runtime_error
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Definition at line 274 of file Printout.cpp.
References format().
format() [4/4]
string DD4hep::format (const char * src, const char * fmt, va_list & args)
Build exception string and throw std::runtime_error
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Definition at line 284 of file Printout.cpp.
g4Evaluator()
XmlTools::Evaluator& DD4hep::g4Evaluator ()
Referenced by run_interpreter().
hash32() [1/2]
unsigned int DD4hep::hash32 (const char * key) inline
We need it so often: one-at-time 32 bit hash function.
Definition at line 39 of file Primitives.h.
References DD4hep::Simulation::hash().
Referenced by DD4hep::Alignments::GlobalAlignmentCache::get(), hash32(), DD4hep::Alignments::Alignment::hashCode(), DD4hep::Conditions::ConditionKey::hashCode(), DD4hep::Alignments::GlobalAlignmentCache::insert(), and DD4hep::Geometry::DetElement::setTypeFlag().
hash32() [2/2]
unsigned int DD4hep::hash32 (const std::string & key) inline
Definition at line 51 of file Primitives.h.
References hash32(), and makeTime().
increment_object_validations()
void DD4hep::increment_object_validations ()
Definition at line 243 of file Handle.cpp.
References s_numVerifies.
invalidHandleAssignmentError()
void DD4hep::invalidHandleAssignmentError (const std::type_info & from, const std::type_info & to)
Throw exception when handles are badly assigned.
Definition at line 196 of file Primitives.cpp.
References typeName().
Referenced by DD4hep::Handle< ReadoutObject >::bad_assignment(), createPlugin(), and DD4hep::invalid_handle_exception::invalid_handle_exception().
invalidHandleError() [1/2]
void DD4hep::invalidHandleError (const std::type_info & type)
Throw exception when handles are check for validity.
Definition at line 191 of file Primitives.cpp.
References typeName().
Referenced by DD4hep::Handle< ReadoutObject >::access(), DD4hep::invalid_handle_exception::invalid_handle_exception(), and invalidHandleError().
invalidHandleError() [2/2]
template<typename T > void DD4hep::invalidHandleError ()
Throw exception when handles are check for validity.
Definition at line 87 of file Primitives.h.
References invalidHandleError(), and notImplemented().
makeTime() [1/2]
long int DD4hep::makeTime (int year, int month, int day, int hour = 0, int minutes = 0, int seconds = 0)
Convert date into epoch time (seconds since 1970)
Definition at line 33 of file Primitives.cpp.
References except().
Referenced by hash32().
makeTime() [2/2]
long int DD4hep::makeTime (const std::string & date, const char * fmt = "%d-%m-%Y %H:%M:%S")
Convert date into epoch time (seconds since 1970)
Definition at line 53 of file Primitives.cpp.
References except().
notImplemented()
void DD4hep::notImplemented (const std::string & msg)
Throw exception when handles are check for validity.
Definition at line 208 of file Primitives.cpp.
References m.
Referenced by invalidHandleError().
num_object_validations()
long DD4hep::num_object_validations ()
Definition at line 240 of file Handle.cpp.
References s_numVerifies.
operator<<()
std::ostream& DD4hep::operator<< (std::ostream & os, const DetType & t) inline
Definition at line 98 of file DetType.h.
References DD4hep::DetType::_type, DD4hep::DetType::AUXILIARY, DD4hep::DetType::BARREL, DD4hep::DetType::BEAMPIPE, DD4hep::DetType::CALORIMETER, DD4hep::DetType::CHERENKOV, DD4hep::DetType::COIL, DD4hep::DetType::ELECTROMAGNETIC, DD4hep::DetType::ENDCAP, DD4hep::DetType::FORWARD, DD4hep::DetType::GASEOUS, DD4hep::DetType::HADRONIC, DD4hep::DetType::is(), DD4hep::DetType::MUON, DD4hep::DetType::PIXEL, DD4hep::DetType::STRIP, DD4hep::DetType::SUPPORT, DD4hep::DetType::TRACKER, DD4hep::DetType::VERTEX, and DD4hep::DetType::WIRE.
parse_none()
template<typename T > int DD4hep::parse_none (T & , const std::string &) inline
Definition at line 314 of file BasicGrammar_inl.h.
PluginFactoryBase::value< const std::string & >()
template<> const std::string& DD4hep::PluginFactoryBase::value< const std::string &> (const void * p) inline
Definition at line 65 of file Plugins.h.
PluginFactoryBase::value< std::string >()
template<> std::string DD4hep::PluginFactoryBase::value< std::string > (const void * p) inline
Definition at line 64 of file Plugins.h.
pre_parse_obj()
static std::string DD4hep::pre_parse_obj (const std::string & in) inline static
Helper function to parse data type.
Definition at line 157 of file BasicGrammar_inl.h.
Referenced by eval_container(), and eval_obj().
print()
template<typename T > std::ostream& DD4hep::print (const T & object, std::ostream & os = std::cout, const std::string & indent = "") inline
Definition at line 223 of file Printout.h.
Referenced by DD4hep::Simulation::Geant4Action::outputLevel(), DD4hep::Simulation::Geant4SensitiveAction< T >::process(), DD4hep::Geometry::DetElementObject::revalidate(), DD4hep::Simulation::Geant4Output2LCIO::saveCollection(), and DD4hep::Simulation::Geant4Output2LCIO::saveEvent().
printLevel()
DD4hep::PrintLevel DD4hep::printLevel ()
Access the current printer level.
Definition at line 303 of file Printout.cpp.
Referenced by DD4hep::Simulation::Geant4EventSeed::beginEvent(), DD4hep::Simulation::Geant4Exec::configure(), DD4hep::Simulation::Geant4DefaultRangeCut::constructProcesses(), DD4hep::Simulation::Geant4Converter::Geant4Converter(), DD4hep::Simulation::Geant4Kernel::getOutputLevel(), DD4hep::Simulation::Geant4Action::print(), DD4hep::Simulation::Geant4Action::printM1(), DD4hep::Simulation::Geant4Action::printM2(), DD4hep::Simulation::Geant4Action::printP1(), DD4hep::Simulation::Geant4Action::printP2(), DD4hep::Geometry::DetElementObject::revalidate(), and DD4hep::Simulation::TypeName::split().
printout() [1/8]
int DD4hep::printout (PrintLevel severity, const char * src, const char * fmt, ...)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 91 of file Printout.cpp.
Referenced by DD4hep::Conditions::Test::__print_bound_container(), DD4hep::Conditions::Test::__print_bound_val(), DD4hep::Conditions::Test::__print_bound_val< string >(), DD4hep::Conditions::ConditionsManagerObject::__queue_update(), DD4hep::Simulation::_convertAction(), DD4hep::Simulation::_convertSensitive(), DD4hep::Simulation::_create_object(), DD4hep::Alignments::AlignmentStack::add(), DD4hep::Geometry::LCDDImp::addDetector(), DD4hep::PluginService::addFactory(), DD4hep::Alignments::GlobalAlignmentWriter::addNode(), DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::Alignments::GlobalAlignmentCache::apply(), DD4hep::XML::DocumentHolder::assign(), DD4hep::Simulation::Geant4EventSeed::begin(), DD4hep::Simulation::Geant4EventSeed::beginEvent(), Geant4Compatibility::buildDefaultDetectorConstruction(), DD4hep::Alignments::AlignmentsManagerObject::compute(), DD4hep::Simulation::Geant4Exec::configure(), DD4hep::CaloLego::ConfigureEvent(), DD4hep::View::ConfigureEvent(), DD4hep::View::ConfigureEventFromInfo(), DD4hep::Calo2DProjection::ConfigureGeometry(), DD4hep::View::ConfigureGeometry(), DD4hep::View::ConfigureGeometryFromInfo(), DD4hep::Simulation::Geant4Converter::create(), create_detector(), create_element(), DD4hep::Utilities::createEveShape(), DD4hep::DDRec::createSurfaceManager(), DD4hep::Simulation::Geant4Context::createTrajectory(), DD4hep::Simulation::Geant4Kernel::createWorker(), DD4hep::Simulation::Geant4Action::debug(), DD4hep::Geometry::DetElementObject::DetElementObject(), DD4hep::Conditions::ConditionsDependencyHandler::do_callback(), DD4hep::Simulation::Geant4HierarchyDump::dump(), DD4hep::Simulation::Geant4PhysicsList::dump(), DD4hep::Simulation::Geant4PhysicsListActionSequence::dump(), DD4hep::PropertyManager::dump(), DD4hep::Simulation::Geant4ParticleHandle::dump1(), DD4hep::Simulation::Geant4ParticleHandle::dump2(), DD4hep::Simulation::Geant4ParticleHandle::dump4(), DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), DD4hep::Conditions::Test::TestEnv::dump_conditions_tree(), DD4hep::Conditions::Test::TestEnv::dump_detector_element(), dump_root(), DD4hep::Simulation::Geant4SensitiveDetector::dumpStep(), DD4hep::XML::dumpTree(), DD4hep::Simulation::Geant4ParticleHandle::dumpWithMomentum(), DD4hep::Simulation::Geant4ParticleHandle::dumpWithMomentumAndVertex(), DD4hep::Simulation::Geant4ParticleHandle::dumpWithVertex(), DD4hep::Simulation::Geant4OutputAction::end(), DD4hep::XML::DocumentErrorHandler::error(), DD4hep::Simulation::Geant4Action::error(), except(), DD4hep::Simulation::Geant4Action::except(), extract(), DD4hep::Simulation::Geant4Action::fatal(), DD4hep::XML::DocumentErrorHandler::fatalError(), DD4hep::Simulation::Geant4Handle< TYPE >::Geant4Handle(), DD4hep::Simulation::Geant4UIMessenger::Geant4UIMessenger(), DD4hep::Conditions::ConditionsManagerObject::get(), DD4hep::Simulation::Geant4UIMessenger::GetCurrentValue(), DD4hep::Geometry::LCDDImp::getRefChild(), DD4hep::Simulation::Geant4Converter::handleAssembly(), DD4hep::Simulation::Geant4Converter::handleElement(), DD4hep::XML::DocumentErrorHandler::handleError(), DD4hep::Simulation::Geant4Converter::handleMaterial(), DD4hep::PopupMenu::HandleMenu(), DD4hep::Simulation::Geant4Converter::handlePlacement(), DD4hep::Simulation::Geant4Converter::handleProperties(), DD4hep::Simulation::Geant4Converter::handleRegion(), DD4hep::Simulation::Geant4Converter::handleVolume(), DD4hep::Projection::ImportElement(), DD4hep::View::ImportEventElement(), DD4hep::View::ImportGeoTopics(), DD4hep::Simulation::Geant4AssemblyVolume::imprint(), DD4hep::Simulation::Geant4Action::info(), DD4hep::Geometry::LCDDImp::init(), DD4hep::Alignments::AlignmentOperator::insert(), DD4hep::Alignments::GlobalAlignmentCache::insert(), DD4hep::SurfaceInstaller::install(), DD4hep::SurfaceInstaller::invalidInstaller(), DD4hepRootPersistency::load(), DD4hep::XML::DocumentHandler::load(), DD4hep::Display::LoadGeoChildren(), DD4hep::FrameControl::LoadPicture(), DD4hep::Display::MakeNodesVisible(), DD4hep::Simulation::LCIOStdHepReader::moveToEvent(), DD4hep::Simulation::Geant4EventReaderHepEvt::moveToEvent(), DD4hep::Simulation::Geant4EventReaderHepMC::moveToEvent(), DD4hep::Simulation::LCIOFileReader::moveToEvent(), DD4hep::DD4hepMenu::OnExit(), DD4hep::Display::OnNewEvent(), DD4hep::DDG4EventHandler::Open(), DD4hep::Printer< T >::operator()(), DD4hep::Simulation::Geant4ParticleGenerator::operator()(), DD4hep::Simulation::Geant4FieldTrackingSetupAction::operator()(), DD4hep::Simulation::Geant4FieldTrackingConstruction::operator()(), DD4hep::Converter< T, ARG >::operator()(), operator<<(), DD4hep::XML::DocumentHandler::output(), DD4hep::Simulation::Geant4ParticleMap::particleID(), DD4hep::Simulation::Geant4DataDump::print(), DD4hep::Conditions::ConditionsPool::print(), DD4hep::Simulation::Geant4Action::print(), DD4hep::Conditions::Test::print_condition< void >(), DD4hep::Simulation::Geant4Action::printM1(), DD4hep::Simulation::Geant4Action::printM2(), printout(), DD4hep::Simulation::Geant4Action::printP1(), DD4hep::Simulation::Geant4Action::printP2(), DD4hep::Simulation::Geant4Converter::printPlacement(), DD4hep::Simulation::Geant4Kernel::printProperties(), DD4hep::Simulation::Geant4Converter::printSensitive(), Tests::Geant4SensitiveAction< T >::process(), DD4hep::Simulation::HepMC::EventStream::read(), DD4hep::DDG4EventHandler::ReadEvent(), DD4hep::Simulation::LCIOFileReader::readParticleCollection(), DD4hep::Simulation::Geant4EventReaderHepMC::readParticles(), DD4hep::Conditions::Condition::rebind(), DD4hep::Simulation::Geant4Kernel::registerGlobalAction(), DD4hep::Simulation::Geant4Action::return_error(), DD4hep::Geometry::DetElementObject::revalidate(), DD4hep::Simulation::Geant4Kernel::run(), DD4hep::Simulation::Geant4Kernel::runManager(), DD4hepRootPersistency::save(), DD4hep::Simulation::Geant4Output2ROOT::saveCollection(), DD4hep::Simulation::Geant4Output2LCIO::saveParticles(), DD4hep::Conditions::ConditionsManagerObject::select_range(), DD4hep::Geometry::SensitiveDetectorObject::SensitiveDetectorObject(), DD4hep::XML::setDetectorTypeFlag(), DD4hep::Simulation::Geant4UIMessenger::SetNewValue(), DD4hep::Geometry::Volume::setVisAttributes(), DD4hep::Simulation::LCIOFileReader::skipEvent(), DD4hep::Simulation::Geant4UIManager::start(), DD4hep::Simulation::Geant4UIManager::startUI(), DD4hep::Simulation::Geant4UIManager::startVis(), DD4hep::SurfaceInstaller::SurfaceInstaller(), DD4hep::XML::DocumentHandler::system_path(), DD4hep::Simulation::Geant4Kernel::terminate(), DD4hep::Geometry::VolumeManagerObject::update(), DD4hep::Geometry::DetElementObject::update(), usage(), DD4hep::Simulation::Geant4VolumeManager::volumeID(), DD4hep::Geometry::VolumeManager::VolumeManager(), DD4hep::Simulation::Geant4Action::warning(), DD4hep::Conditions::ConditionsRepository::~ConditionsRepository(), DD4hep::Conditions::ConditionsTextRepository::~ConditionsTextRepository(), DD4hep::XML::DocumentErrorHandler::~DocumentErrorHandler(), and DD4hep::Alignments::GlobalAlignmentCache::~GlobalAlignmentCache().
printout() [2/8]
int DD4hep::printout (PrintLevel severity, const std::string & src, const char * fmt, ...)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 107 of file Printout.cpp.
References printout().
printout() [3/8]
int DD4hep::printout (PrintLevel severity, const std::string & src, const std::string & fmt, ...)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 139 of file Printout.cpp.
References printout().
printout() [4/8]
int DD4hep::printout (PrintLevel severity, const char * src, const std::string & fmt, ...)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 123 of file Printout.cpp.
References printout().
printout() [5/8]
int DD4hep::printout (PrintLevel severity, const char * src, const char * fmt, va_list & args)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 155 of file Printout.cpp.
printout() [6/8]
int DD4hep::printout (PrintLevel severity, const std::string & src, const char * fmt, va_list & args)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 168 of file Printout.cpp.
References printout().
printout() [7/8]
int DD4hep::printout (PrintLevel severity, const std::string & src, const std::string & fmt, va_list & args)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 188 of file Printout.cpp.
References printout().
printout() [8/8]
int DD4hep::printout (PrintLevel severity, const char * src, const std::string & fmt, va_list & args)
Calls the display action
severity [int,read-only] Display severity flag (see enum)
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
args [ap_list,read-only] List with variable number of arguments to fill format string.
Returns
Status code indicating success or failure
Calls the display action
severity [int,read-only] Display severity flag
src [string,read-only] Information source (component, etc.)
fmt [string,read-only] Format string for ellipsis args
Returns
Status code indicating success or failure
Definition at line 178 of file Printout.cpp.
References printout().
reference2nd()
template<typename M > ReferenceObjects<typename M::value_type> DD4hep::reference2nd (M &)
Definition at line 371 of file Primitives.h.
Referenced by DD4hep::Simulation::Geant4EventReaderHepMC::readParticles().
referenceObject()
template<typename M > ReferenceObject<M> DD4hep::referenceObject (M &)
Definition at line 368 of file Primitives.h.
release2nd()
template<typename M > void DD4hep::release2nd (M & m)
Definition at line 347 of file Primitives.h.
releaseHandles()
template<typename M > void DD4hep::releaseHandles (M & m)
Functional created of map destruction functors.
Definition at line 225 of file Handle.h.
References _ptrToString(), _toString(), and m.
releaseObject()
template<typename M > ReleaseObject<typename M::value_type> DD4hep::releaseObject (M &)
Definition at line 341 of file Primitives.h.
releaseObjects()
template<typename M > void DD4hep::releaseObjects (M & m)
Definition at line 344 of file Primitives.h.
Referenced by DD4hep::Conditions::ConditionsDependencyCollection::clear(), DD4hep::Simulation::Geant4ParticleHandler::clear(), DD4hep::Simulation::HepMC::EventStream::clear(), DD4hep::Simulation::Geant4ParticleMap::clear(), DD4hep::Simulation::HepMC::EventStream::read(), DD4hep::Simulation::Geant4Kernel::terminate(), DD4hep::Conditions::ConditionsDependencyCollection::~ConditionsDependencyCollection(), DD4hep::Simulation::Geant4Kernel::~Geant4Kernel(), DD4hep::Simulation::Geant4PrimaryInteraction::~Geant4PrimaryInteraction(), DD4hep::Simulation::Geant4PrimaryMap::~Geant4PrimaryMap(), DD4hep::Simulation::Geant4SensDetSequences::~Geant4SensDetSequences(), and DD4hep::Alignments::GlobalAlignmentCache::~GlobalAlignmentCache().
releasePtr()
template<typename T > void DD4hep::releasePtr (T & p) inline
Helper to delete objects from heap and reset the pointer. Saves many many lines of code.
Definition at line 316 of file Primitives.h.
Referenced by DD4hep::Simulation::RefCountedSequence< Geant4SensDetActionSequence >::_release(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::_release(), DD4hep::ReleaseObject< T >::operator()(), releaseHandle(), DD4hep::Simulation::Geant4ActionContainer::terminate(), DD4hep::Conditions::ConditionDependency::~ConditionDependency(), DD4hep::Conditions::DependencyBuilder::~DependencyBuilder(), DD4hep::Simulation::Geant4ParticleHandler::~Geant4ParticleHandler(), DD4hep::Simulation::Geant4SharedEventAction::~Geant4SharedEventAction(), DD4hep::Simulation::Geant4SharedGeneratorAction::~Geant4SharedGeneratorAction(), DD4hep::Simulation::Geant4SharedRunAction::~Geant4SharedRunAction(), DD4hep::Simulation::Geant4SharedStackingAction::~Geant4SharedStackingAction(), DD4hep::Simulation::Geant4SharedSteppingAction::~Geant4SharedSteppingAction(), and DD4hep::Simulation::Geant4SharedTrackingAction::~Geant4SharedTrackingAction().
run_interpreter()
void DD4hep::run_interpreter (const std::string & name)
Definition at line 53 of file Dictionary.h.
References evaluator(), and g4Evaluator().
select1st()
template<typename T > Select1st<typename T::value_type> DD4hep::select1st (const T &)
Generator to create Operator to select key values of a map.
Definition at line 277 of file Primitives.h.
select2nd()
template<typename T > Select2nd<typename T::value_type> DD4hep::select2nd (const T &)
Generator to create Operator to select value elements of a map.
Definition at line 265 of file Primitives.h.
setPrinter()
void DD4hep::setPrinter (void * print_arg, output_function1_t fcn)
Customize printer function.
Definition at line 315 of file Printout.cpp.
setPrinter2()
void DD4hep::setPrinter2 (void * print_arg, output_function2_t fcn)
Customize printer function.
Definition at line 321 of file Printout.cpp.
setPrintFormat()
string DD4hep::setPrintFormat (const std::string & new_format)
Set new printout format for the 3 fields: source-level-message. All 3 are strings.
Definition at line 308 of file Printout.cpp.
setPrintLevel()
DD4hep::PrintLevel DD4hep::setPrintLevel (PrintLevel new_level)
Set new print level. Returns the old print level.
Definition at line 296 of file Printout.cpp.
true_false()
const char* DD4hep::true_false (bool value) inline
Helper function to print booleans in format true/false.
Definition at line 262 of file Printout.h.
typeinfoCheck()
void DD4hep::typeinfoCheck (const std::type_info & typ1, const std::type_info & typ2, const std::string & text = "")
Check type infos for equivalence (dynamic casts) using ABI information.
Definition at line 214 of file Primitives.cpp.
Referenced by DD4hep::Simulation::Geant4ActionPhase::add(), DD4hep::OpaqueDataBlock::bind(), and DD4hep::invalid_handle_exception::invalid_handle_exception().
typeName()
std::string DD4hep::typeName (const std::type_info & type)
ABI information about type names.
Definition at line 187 of file Primitives.cpp.
References __typeinfoName().
Referenced by DD4hep::Conditions::Test::__print_bound_container(), DD4hep::Conditions::Test::__print_bound_val(), DD4hep::Conditions::Test::__print_bound_val< string >(), DD4hep::Simulation::_create_object(), DD4hep::Simulation::_create_share(), DD4hep::Simulation::Geant4Action::abortRun(), DD4hep::Handle< ReadoutObject >::access(), DD4hep::ObjectExtensions::addExtension(), DD4hep::Simulation::checked_value(), DD4hep::ComponentCast::ComponentCast(), DD4hep::InstanceCount::dump(), DD4hep::ObjectExtensions::extension(), DD4hep::Simulation::Geant4Output2ROOT::fill(), DD4hep::Grammar< TYPE >::Grammar(), DD4hep::invalid_handle_exception::invalid_handle_exception(), DD4hep::BasicGrammar::invalidConversion(), invalidHandleAssignmentError(), invalidHandleError(), DD4hep::unrelated_type_error::msg(), DD4hep::unrelated_value_error::msg(), DD4hep::Simulation::Geant4Kernel::registerGlobalAction(), DD4hep::Simulation::Geant4Action::release(), DD4hep::ObjectExtensions::removeExtension(), DD4hep::OpaqueDataBlock::set(), DD4hep::Property::type(), and DD4hep::Primitive< T >::type_name().
versionString()
std::string DD4hep::versionString () inline
return a string with the current DD4hep version in the form vXX-YY.
Definition at line 50 of file LCDD.h.
References DD4HEP_MAJOR_VERSION, and DD4HEP_MINOR_VERSION.
Referenced by DD4hep::Simulation::Geant4Output2LCIO::saveRun().
warning_deprecated_xml_factory()
void DD4hep::warning_deprecated_xml_factory (const char * name)
Function tp print warning about deprecated factory usage. Used by Plugin mechanism.
Definition at line 246 of file Handle.cpp.
yes_no()
const char* DD4hep::yes_no (bool value) inline
Helper function to print booleans in format YES/NO.
Definition at line 258 of file Printout.h.
Referenced by DD4hep::Geometry::VolumeManager::adoptPlacement(), DD4hep::Simulation::Geant4ParticleHandler::checkConsistency(), DD4hep::EveUserContextMenu::display(), DD4hep::Simulation::Geant4HierarchyDump::dump(), DD4hep::Simulation::Geant4ParticleHandle::dump2(), DD4hep::Simulation::Geant4ParticleHandle::dump4(), DD4hep::Simulation::Geant4Converter::handleVolume(), DD4hep::Alignments::AlignmentOperator::insert(), DD4hep::Printer< T >::operator()(), DD4hep::Simulation::Geant4DataDump::print(), DD4hep::Simulation::Geant4ParticlePrint::printParticle(), and DD4hep::Geometry::VisAttr::toString().
Variable Documentation
s_numVerifies
long DD4hep::s_numVerifies = 0 static
Definition at line 238 of file Handle.cpp.
Referenced by increment_object_validations(), and num_object_validations().