DD4hep: DD4hep: DD4hep::DDRec Namespace Reference
DD4hep::DDRec Namespace Reference
Namespace for the reconstruction part of the AIDA detector description toolkit.
Classes
struct StructExtension
struct FixedPadSizeTPCStruct
struct ZPlanarStruct
struct ZDiskPetalsStruct
struct ConicalSupportStruct
struct LayeredCalorimeterStruct
class DetectorSurfaces
class MaterialData
class MaterialManager
class VolSurfaceBase
class VolSurface
struct VolSurfaceList
class VolPlaneImpl
class VolCylinderImpl
class VolConeImpl
class VolSurfaceHandle
class VolCylinder
class VolCone
class Surface
class CylinderSurface
class ConeSurface
class SurfaceList
class SurfaceHelper
class SurfaceManager
class Calorimeter
class invalid_cell_id
class invalid_position
class invalid_detector_element
class IDDecoder
class LayeredSubdetector
class Subdetector
class Tracker
class CalorimeterExtension
class LayeringExtension
class LayeringExtensionImpl
class SubdetectorExtension
class SubdetectorExtensionImpl
class TrackerExtension
Typedefs
typedef StructExtension
< FixedPadSizeTPCStruct > FixedPadSizeTPCData
typedef StructExtension
< ZPlanarStruct > ZPlanarData
typedef StructExtension
< ZDiskPetalsStruct > ZDiskPetalsData
typedef StructExtension
< ConicalSupportStruct > ConicalSupportData
typedef StructExtension
< LayeredCalorimeterStruct > LayeredCalorimeterData
typedef std::vector< std::pair
< Material, double > > MaterialVec
typedef VolSurfaceHandle
< VolPlaneImpl > VolPlane
typedef std::multimap
< unsigned long,
DDSurfaces::ISurface * > SurfaceMap
typedef for surface maps, keyed by the cellID
typedef DDSegmentation::CellID CellID
typedef DDSegmentation::VolumeID VolumeID
Functions
std::ostream & operator<< (std::ostream &io, const FixedPadSizeTPCData &d)
VolSurfaceList * volSurfaceList (DetElement &det)
bool findVolume (PlacedVolume pv, Volume theVol, std::list< PlacedVolume > &volList)
static long createGearForCLIC (LCDD &lcdd, int, char **)
static long createGearForILD (LCDD &lcdd, int, char **)
static long createSurfaceManager (LCDD &lcdd, int, char **)
std::ostream & operator<< (std::ostream &os, const Material &m)
dump Material operator
std::ostream & operator<< (std::ostream &os, const MaterialVec &m)
dump MaterialVec operator
Detailed Description
Namespace for the reconstruction part of the AIDA detector description toolkit.
Typedef Documentation
typedef DDSegmentation::CellID DD4hep::DDRec::CellID
Definition at line 24 of file IDDecoder.h.
typedef StructExtension<ConicalSupportStruct> DD4hep::DDRec::ConicalSupportData
Definition at line 321 of file DetectorData.h.
typedef StructExtension<FixedPadSizeTPCStruct> DD4hep::DDRec::FixedPadSizeTPCData
Definition at line 66 of file DetectorData.h.
typedef StructExtension<LayeredCalorimeterStruct> DD4hep::DDRec::LayeredCalorimeterData
Definition at line 444 of file DetectorData.h.
typedef std::vector< std::pair< Material, double > > DD4hep::DDRec::MaterialVec
Definition at line 20 of file MaterialManager.h.
typedef std::multimap< unsigned long, DDSurfaces::ISurface*> DD4hep::DDRec::SurfaceMap
typedef for surface maps, keyed by the cellID
Definition at line 12 of file SurfaceManager.h.
typedef VolSurfaceHandle< VolPlaneImpl > DD4hep::DDRec::VolPlane
Definition at line 487 of file Surface.h.
typedef DDSegmentation::VolumeID DD4hep::DDRec::VolumeID
Definition at line 25 of file IDDecoder.h.
typedef StructExtension<ZDiskPetalsStruct> DD4hep::DDRec::ZDiskPetalsData
Definition at line 278 of file DetectorData.h.
typedef StructExtension<ZPlanarStruct> DD4hep::DDRec::ZPlanarData
Definition at line 160 of file DetectorData.h.
Function Documentation
static long DD4hep::DDRec::createGearForCLIC (LCDD & lcdd, int , char **) [static]
Plugin that creates Gear objects for DetElements and attaches them as extensions. Called from DDGear::createGearMgr(). NB: this code is for backward compatibility to run the old reconstruction that expects Gear information and should eventually be phased out.
Author:
F.Gaede, CERN/DESY
Date:
Oct 2014
Version:
$Id$
Definition at line 38 of file createGearForCLIC.cpp.
References DD4hep::Geometry::DetElement::addExtension(), DD4hep::GearHandle::addMaterial(), dd4hep::deg, DD4hep::Geometry::LCDD::detector(), DD4hep::Geometry::DetElement::extension(), handle(), dd4hep::mm, s, DD4hep::Geometry::Volume::solid(), and DD4hep::Geometry::DetElement::volume().
static long DD4hep::DDRec::createGearForILD (LCDD & lcdd, int , char **) [static]
Plugin that creates Gear objects for DetElements and attaches them as extensions. Called from DDGear::createGearMgr(). NB: this code is for backward compatibility to run the old reconstruction that expects Gear information and should eventually be phased out.
Author:
F.Gaede, CERN/DESY
Date:
Oct 2014
Version:
Id
Definition at line 40 of file createGearForILD.cpp.
References DD4hep::DDRec::MaterialData::A(), DD4hep::Geometry::DetElement::addExtension(), DD4hep::GearHandle::addMaterial(), DD4hep::Geometry::LCDD::constant(), DD4hep::DDRec::MaterialManager::createAveragedMaterial(), DDSurfaces::Vector3D::cylindrical(), dd4hep::deg, DD4hep::DDRec::MaterialData::density(), DD4hep::Geometry::LCDD::detector(), DD4hep::DDRec::ZDiskPetalsStruct::SensorType::DoubleSided, DD4hep::Geometry::DetElement::extension(), dd4hep::g, handle(), DD4hep::DDRec::MaterialData::interactionLength(), dd4hep::kg, dd4hep::m3, DD4hep::DDRec::MaterialManager::materialsBetween(), dd4hep::mm, DD4hep::Geometry::Segmentation::parameter(), DD4hep::DDRec::ZDiskPetalsStruct::SensorType::Pixel, DD4hep::DDRec::MaterialData::radiationLength(), DD4hep::Geometry::SensitiveDetector::readout(), s, DD4hep::Geometry::Readout::segmentation(), DD4hep::Geometry::LCDD::sensitiveDetector(), DD4hep::Geometry::Volume::solid(), DD4hep::DDSegmentation::TypedSegmentationParameter< TYPE >::typedValue(), DD4hep::Geometry::DetElement::volume(), and DD4hep::DDRec::MaterialData::Z().
static long DD4hep::DDRec::createSurfaceManager (LCDD & lcdd, int , char **) [static]
Definition at line 28 of file createSurfaceManager.cpp.
References DD4hep::Geometry::LCDD::addExtension(), DD4hep::Geometry::LCDD::extension(), DD4hep::INFO, and DD4hep::printout().
bool DD4hep::DDRec::findVolume (PlacedVolume pv, Volume theVol, std::list< PlacedVolume > & volList)
Definition at line 531 of file Surface.cpp.
References DD4hep::Geometry::PlacedVolume::data(), DD4hep::Handle< T >::name(), DD4hep::Handle< T >::ptr(), and DD4hep::Geometry::PlacedVolume::volume().
Referenced by DD4hep::DDRec::Surface::initialize().
std::ostream& DD4hep::DDRec::operator<< (std::ostream & os, const MaterialVec & m) [inline]
dump MaterialVec operator
Definition at line 79 of file MaterialManager.h.
std::ostream& DD4hep::DDRec::operator<< (std::ostream & os, const Material & m) [inline]
dump Material operator
Definition at line 70 of file MaterialManager.h.
References DD4hep::Geometry::Material::A(), DD4hep::Geometry::Material::density(), DD4hep::Geometry::Material::intLength(), DD4hep::Handle< T >::name(), DD4hep::Geometry::Material::radLength(), and DD4hep::Geometry::Material::Z().
std::ostream & DD4hep::DDRec::operator<< (std::ostream & io, const FixedPadSizeTPCData & d)
Definition at line 27 of file DetectorData.cpp.
VolSurfaceList * DD4hep::DDRec::volSurfaceList (Geometry::DetElement & det)
Helper function for accessing the list assigned to a DetElement - attaches empty list if needed.
Referenced by DD4hep::DDRec::DetectorSurfaces::initialize(), and DD4hep::DDRec::VolSurfaceList::VolSurfaceList().