DD4hep: DD4hep::Alignments::AlignmentTools Namespace Reference
DD4hep::Alignments::AlignmentTools Namespace Reference
Functions
void copy (Alignment from, Alignment to)
Copy alignment object from source object.
void computeIdeal (Alignment alignment)
Compute the ideal/nominal to-world transformation from the detector element placement.
void computeIdeal (Alignment alignment, const Alignment::NodeList &node_list)
Compute the ideal/nominal to-world transformation from the detector element placement.
void computeSurvey (Alignment alignment)
Compute the survey to-world transformation.
Function Documentation
computeIdeal() [1/2]
void DD4hep::Alignments::AlignmentTools::computeIdeal (Alignment alignment)
Compute the ideal/nominal to-world transformation from the detector element placement.
Note: Detector information of the alignment data is filled by the caller!
Definition at line 51 of file AlignmentTools.cpp.
References DD4hep::Geometry::_transform(), DD4hep::Handle< T >::clear(), DD4hep::Alignments::AlignmentData::detector, DD4hep::Alignments::AlignmentData::detectorTrafo, DD4hep::Alignments::AlignmentData::flag, DD4hep::Handle< T >::isValid(), DD4hep::Alignments::AlignmentData::nodes, DD4hep::Geometry::DetElement::nominal(), DD4hep::Geometry::DetElement::parent(), DD4hep::Alignments::AlignmentData::placement, DD4hep::Geometry::DetElement::placement(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Handle< T >::ptr(), DD4hep::Alignments::AlignmentData::trToWorld, and DD4hep::Alignments::AlignmentData::worldTrafo.
Referenced by DD4hep::Geometry::DetElement::nominal().
computeIdeal() [2/2]
void DD4hep::Alignments::AlignmentTools::computeIdeal (Alignment alignment, const Alignment::NodeList & node_list)
Compute the ideal/nominal to-world transformation from the detector element placement.
Note: Detector information of the alignment data is filled by the caller!
Definition at line 75 of file AlignmentTools.cpp.
References DD4hep::Geometry::_transform(), DD4hep::Alignments::AlignmentData::detector, DD4hep::Alignments::AlignmentData::detectorTrafo, DD4hep::Alignments::AlignmentData::flag, m, DD4hep::Alignments::AlignmentData::nodes, DD4hep::Geometry::DetElement::nominal(), DD4hep::Geometry::DetElementObject::placement, DD4hep::Alignments::AlignmentData::placement, DD4hep::Handle< T >::ptr(), DD4hep::Alignments::AlignmentData::trToWorld, and DD4hep::Alignments::AlignmentData::worldTrafo.
computeSurvey()
void DD4hep::Alignments::AlignmentTools::computeSurvey (Alignment alignment)
Compute the survey to-world transformation.
Compute the survey to-world transformation from the detector element placement with respect to the survey constants.
Compute the survey to-world transformation from the detector element placement with respect to the survey constants
Note: Detector information of the alignment data is filled by the caller!
Definition at line 101 of file AlignmentTools.cpp.
References DD4hep::Geometry::_transform(), DD4hep::Alignments::AlignmentData::detector, DD4hep::Alignments::AlignmentData::detectorTrafo, DD4hep::Alignments::AlignmentData::flag, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::parent(), DD4hep::Alignments::AlignmentData::placement, DD4hep::Geometry::DetElement::placement(), DD4hep::Geometry::DetectorTools::placementPath(), DD4hep::Handle< T >::ptr(), DD4hep::Geometry::DetElement::survey(), DD4hep::Alignments::AlignmentData::trToWorld, and DD4hep::Alignments::AlignmentData::worldTrafo.
copy()
void DD4hep::Alignments::AlignmentTools::copy (Alignment from, Alignment to)
Copy alignment object from source object.
Definition at line 34 of file AlignmentTools.cpp.
References DD4hep::Alignments::AlignmentData::delta, DD4hep::Alignments::AlignmentData::detector, DD4hep::Alignments::AlignmentData::detectorTrafo, DD4hep::Alignments::AlignmentData::flag, DD4hep::Alignments::AlignmentData::magic, DD4hep::Alignments::AlignmentData::nodes, DD4hep::Alignments::AlignmentData::placement, DD4hep::Handle< T >::ptr(), DD4hep::Alignments::AlignmentData::trToWorld, and DD4hep::Alignments::AlignmentData::worldTrafo.
Referenced by DD4hep::Geometry::BooleanSolid::BooleanSolid(), DD4hep::Geometry::Box::Box(), DD4hep::Geometry::Cone::Cone(), DD4hep::Geometry::ConeSegment::ConeSegment(), DD4hep::Geometry::EightPointSolid::EightPointSolid(), DD4hep::Geometry::EllipticalTube::EllipticalTube(), DD4hep::PropertyManager::for_each(), DD4hep::Geometry::HalfSpace::HalfSpace(), DD4hep::Simulation::Geant4Converter::handlePlacement(), DD4hep::Geometry::Hyperboloid::Hyperboloid(), DD4hep::Geometry::IntersectionSolid::IntersectionSolid(), DD4hep::IOVType::IOVType(), DD4hep::Geometry::Paraboloid::Paraboloid(), DD4hep::Parsers::parse(), DD4hep::Geometry::Polycone::Polycone(), DD4hep::Geometry::PolyhedraRegular::PolyhedraRegular(), DD4hep::Geometry::Solid_type< TGeoBBox >::Solid_type(), DD4hep::Geometry::Sphere::Sphere(), DD4hep::Geometry::SubtractionSolid::SubtractionSolid(), DD4hep::Geometry::DetElement::survey(), TiXmlDeclaration::TiXmlDeclaration(), DD4hep::Geometry::Torus::Torus(), DD4hep::Geometry::Trap::Trap(), DD4hep::Geometry::Trapezoid::Trapezoid(), DD4hep::Geometry::Tube::Tube(), DD4hep::Geometry::UnionSolid::UnionSolid(), and DD4hep::DDRec::VolSurfaceList::VolSurfaceList().