DD4hep: DD4hep::DDSegmentation::Util Namespace Reference
DD4hep::DDSegmentation::Util Namespace Reference
Functions
double magFromXYZ (const Vector3D &position)
Conversions from Cartesian to cylindrical/spherical coordinates ///.
double radiusFromXYZ (const Vector3D &position)
calculates the radius in the xy-plane from Cartesian coordinates
double thetaFromXYZ (const Vector3D &position)
calculates the polar angle theta from Cartesian coordinates
double phiFromXYZ (const Vector3D &position)
calculates the azimuthal angle phi from Cartesian coordinates
Vector3D positionFromRPhiZ (double r, double phi, double z)
Conversions from cylindrical to Cartesian coordinates ///.
double magFromRPhiZ (double r, double, double z)
calculates the radius in xyz from cylindrical coordinates
double xFromRPhiZ (double r, double phi, double)
calculates x from cylindrical coordinates
double yFromRPhiZ (double r, double phi, double)
calculates y from cylindrical coordinates
double thetaFromRPhiZ (double r, double, double z)
calculates the polar angle theta from cylindrical coordinates
Vector3D positionFromRThetaPhi (double r, double theta, double phi)
Conversions from spherical to Cartesian coordinates ///.
Vector3D positionFromMagThetaPhi (double mag, double theta, double phi)
calculates the Cartesian position from spherical coordinates
Function Documentation
magFromRPhiZ()
double DD4hep::DDSegmentation::Util::magFromRPhiZ (double r, double , double z)
calculates the radius in xyz from cylindrical coordinates
Definition at line 61 of file SegmentationUtil.h.
magFromXYZ()
double DD4hep::DDSegmentation::Util::magFromXYZ (const Vector3D & position)
Conversions from Cartesian to cylindrical/spherical coordinates ///.
Conventions ///
x, y, z are the Cartesian coordinates ///
r is the magnitude in the xy-plane ///
mag is the magnitude ///calculates the radius in xyz from Cartesian coordinates
Definition at line 32 of file SegmentationUtil.h.
References DD4hep::DDSegmentation::Vector3D::X, DD4hep::DDSegmentation::Vector3D::Y, and DD4hep::DDSegmentation::Vector3D::Z.
phiFromXYZ()
double DD4hep::DDSegmentation::Util::phiFromXYZ (const Vector3D & position)
calculates the azimuthal angle phi from Cartesian coordinates
Definition at line 47 of file SegmentationUtil.h.
References DD4hep::DDSegmentation::Vector3D::X, and DD4hep::DDSegmentation::Vector3D::Y.
Referenced by DD4hep::DDSegmentation::ProjectiveCylinder::cellID().
positionFromMagThetaPhi()
Vector3D DD4hep::DDSegmentation::Util::positionFromMagThetaPhi (double mag, double theta, double phi)
calculates the Cartesian position from spherical coordinates
Definition at line 90 of file SegmentationUtil.h.
positionFromRPhiZ()
Vector3D DD4hep::DDSegmentation::Util::positionFromRPhiZ (double r, double phi, double z)
Conversions from cylindrical to Cartesian coordinates ///.
calculates the Cartesian position from cylindrical coordinates
Definition at line 56 of file SegmentationUtil.h.
positionFromRThetaPhi()
Vector3D DD4hep::DDSegmentation::Util::positionFromRThetaPhi (double r, double theta, double phi)
Conversions from spherical to Cartesian coordinates ///.
calculates the Cartesian position from spherical coordinates
Definition at line 85 of file SegmentationUtil.h.
Referenced by DD4hep::DDSegmentation::ProjectiveCylinder::position().
radiusFromXYZ()
double DD4hep::DDSegmentation::Util::radiusFromXYZ (const Vector3D & position)
calculates the radius in the xy-plane from Cartesian coordinates
Definition at line 37 of file SegmentationUtil.h.
References DD4hep::DDSegmentation::Vector3D::X, and DD4hep::DDSegmentation::Vector3D::Y.
Referenced by thetaFromXYZ().
thetaFromRPhiZ()
double DD4hep::DDSegmentation::Util::thetaFromRPhiZ (double r, double , double z)
calculates the polar angle theta from cylindrical coordinates
Definition at line 76 of file SegmentationUtil.h.
thetaFromXYZ()
double DD4hep::DDSegmentation::Util::thetaFromXYZ (const Vector3D & position)
calculates the polar angle theta from Cartesian coordinates
Definition at line 42 of file SegmentationUtil.h.
References radiusFromXYZ(), and DD4hep::DDSegmentation::Vector3D::Z.
Referenced by DD4hep::DDSegmentation::ProjectiveCylinder::cellID().
xFromRPhiZ()
double DD4hep::DDSegmentation::Util::xFromRPhiZ (double r, double phi, double)
calculates x from cylindrical coordinates
Definition at line 66 of file SegmentationUtil.h.
yFromRPhiZ()
double DD4hep::DDSegmentation::Util::yFromRPhiZ (double r, double phi, double)
calculates y from cylindrical coordinates
Definition at line 71 of file SegmentationUtil.h.