DD4hep: DD4hep::Simulation::HepMC Namespace Reference
DD4hep::Simulation::HepMC Namespace Reference
Classes
class EventHeader
class EventStream
Enumerations
enum known_io {
gen =1, ascii, extascii, ascii_pdt,
extascii_pdt
}
The known_io enum is used to track which type of input is being read.
Functions
char get_input (istream &is, istringstream &iline)
int read_until_event_end (istream &is)
int read_weight_names (EventStream &, istringstream &iline)
int read_particle (EventStream &info, istringstream &iline, Geant4Particle *p)
int read_vertex (EventStream &info, istream &is, istringstream &iline)
int read_event_header (EventStream &info, istringstream &input, EventHeader &header)
int read_cross_section (EventStream &info, istringstream &input)
int read_units (EventStream &info, istringstream &input)
int read_heavy_ion (EventStream &, istringstream &input)
int read_pdf (EventStream &, istringstream &input)
Geant4Vertex * vertex (EventStream &info, int i)
void fix_particles (EventStream &info)
Enumeration Type Documentation
known_io
enum DD4hep::Simulation::HepMC::known_io
The known_io enum is used to track which type of input is being read.
Enumerator
gen
ascii
extascii
ascii_pdt
extascii_pdt
Definition at line 114 of file Geant4EventReaderHepMC.cpp.
Function Documentation
fix_particles()
void DD4hep::Simulation::HepMC::fix_particles (EventStream & info)
Particles originating from the beam (=no parents) must be be stripped off their parents and the status set to G4PARTICLE_GEN_DECAYED!
Definition at line 244 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::Geant4Particle::daughters, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4Vertex::in, DD4hep::Simulation::Geant4Vertex::out, DD4hep::Simulation::Geant4Particle::parents, DD4hep::Simulation::HepMC::EventStream::particles(), DD4hep::Simulation::Geant4Particle::secondaries, v, vertex(), DD4hep::Simulation::HepMC::EventStream::vertices(), DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Vertex::x, DD4hep::Simulation::Geant4Vertex::y, and DD4hep::Simulation::Geant4Vertex::z.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
get_input()
char DD4hep::Simulation::HepMC::get_input (istream & is, istringstream & iline)
Definition at line 298 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), read_vertex(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_cross_section()
int DD4hep::Simulation::HepMC::read_cross_section (EventStream & info, istringstream & input)
Definition at line 515 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::EventStream::xsection, and DD4hep::Simulation::HepMC::EventStream::xsection_err.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_event_header()
int DD4hep::Simulation::HepMC::read_event_header (EventStream & info, istringstream & input, EventHeader & header)
Definition at line 473 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::EventHeader::alpha_qcd, DD4hep::Simulation::HepMC::EventHeader::alpha_qed, DD4hep::Simulation::HepMC::EventHeader::bp1, DD4hep::Simulation::HepMC::EventHeader::bp2, extascii, gen, DD4hep::Simulation::HepMC::EventHeader::id, DD4hep::Simulation::HepMC::EventStream::io_type, DD4hep::Simulation::HepMC::EventHeader::num_vertices, DD4hep::Simulation::HepMC::EventHeader::random, DD4hep::Simulation::HepMC::EventHeader::scale, DD4hep::Simulation::HepMC::EventHeader::signal_process_id, DD4hep::Simulation::HepMC::EventHeader::signal_process_vertex, and DD4hep::Simulation::HepMC::EventHeader::weights.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_heavy_ion()
int DD4hep::Simulation::HepMC::read_heavy_ion (EventStream & , istringstream & input)
Definition at line 538 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_particle()
int DD4hep::Simulation::HepMC::read_particle (EventStream & info, istringstream & iline, Geant4Particle * p)
Definition at line 364 of file Geant4EventReaderHepMC.cpp.
References ascii, DD4hep::ReferenceBitMask< T >::clear(), DD4hep::Simulation::Geant4Particle::colorFlow, DD4hep::Simulation::G4PARTICLE_GEN_DECAYED, DD4hep::Simulation::G4PARTICLE_GEN_DOCUMENTATION, DD4hep::Simulation::G4PARTICLE_GEN_EMPTY, DD4hep::Simulation::G4PARTICLE_GEN_STABLE, DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::HepMC::EventStream::io_type, DD4hep::Simulation::Geant4Particle::mass, DD4hep::Simulation::HepMC::EventStream::mom_unit, DD4hep::Simulation::HepMC::EventStream::particles(), DD4hep::Simulation::Geant4Particle::pdgID, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, DD4hep::Simulation::Geant4Particle::secondaries, DD4hep::ReferenceBitMask< T >::set(), and DD4hep::Simulation::Geant4Particle::status.
Referenced by read_vertex(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_pdf()
int DD4hep::Simulation::HepMC::read_pdf (EventStream & , istringstream & input)
Definition at line 564 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_units()
int DD4hep::Simulation::HepMC::read_units (EventStream & info, istringstream & input)
Definition at line 520 of file Geant4EventReaderHepMC.cpp.
References dd4hep::cm, gen, dd4hep::GeV, DD4hep::Simulation::HepMC::EventStream::io_type, dd4hep::keV, m, dd4hep::MeV, dd4hep::mm, DD4hep::Simulation::HepMC::EventStream::mom_unit, DD4hep::Simulation::HepMC::EventStream::pos_unit, and dd4hep::TeV.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_until_event_end()
int DD4hep::Simulation::HepMC::read_until_event_end (istream & is)
Definition at line 318 of file Geant4EventReaderHepMC.cpp.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), read_weight_names(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_vertex()
int DD4hep::Simulation::HepMC::read_vertex (EventStream & info, istream & is, istringstream & iline)
Definition at line 409 of file Geant4EventReaderHepMC.cpp.
References get_input(), DD4hep::Simulation::Geant4Particle::id, DD4hep::Simulation::Geant4Vertex::in, DD4hep::Simulation::Geant4Vertex::out, DD4hep::Simulation::HepMC::EventStream::particles(), DD4hep::Simulation::Geant4Particle::pex, DD4hep::Simulation::Geant4Particle::pey, DD4hep::Simulation::Geant4Particle::pez, DD4hep::Simulation::HepMC::EventStream::pos_unit, DD4hep::Simulation::Geant4Particle::psx, DD4hep::Simulation::Geant4Particle::psy, DD4hep::Simulation::Geant4Particle::psz, read_particle(), DD4hep::Simulation::Geant4Vertex::time, v, DD4hep::Simulation::HepMC::EventStream::vertices(), DD4hep::Simulation::Geant4Particle::vex, DD4hep::Simulation::Geant4Particle::vey, DD4hep::Simulation::Geant4Particle::vez, DD4hep::Simulation::Geant4Particle::vsx, DD4hep::Simulation::Geant4Particle::vsy, DD4hep::Simulation::Geant4Particle::vsz, DD4hep::Simulation::Geant4Vertex::x, DD4hep::Simulation::Geant4Vertex::y, and DD4hep::Simulation::Geant4Vertex::z.
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
read_weight_names()
int DD4hep::Simulation::HepMC::read_weight_names (EventStream & , istringstream & iline)
Definition at line 331 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::EventStream::clear(), DD4hep::Simulation::Geant4EventReader::name(), and read_until_event_end().
Referenced by DD4hep::Simulation::HepMC::EventStream::read(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().
vertex()
Geant4Vertex * DD4hep::Simulation::HepMC::vertex (EventStream & info, int i)
Definition at line 293 of file Geant4EventReaderHepMC.cpp.
References DD4hep::Simulation::HepMC::EventStream::vertices().
Referenced by DD4hep::Simulation::HepMC::EventStream::EventStream(), fix_particles(), DD4hep::Simulation::Geant4EventReaderHepEvt::moveToEvent(), DD4hep::Simulation::Geant4InputAction::operator()(), DD4hep::Simulation::Geant4EventReader::skipEvent(), and DD4hep::Simulation::HepMC::EventStream::use_default_units().