DD4hep: DD4hep::Geometry Namespace Reference
DD4hep::Geometry Namespace Reference
Namespace for the geometry part of the AIDA detector description toolkit.
Namespaces
DetectorTools
Helper namespace used to answer detector element specific questons.
Classes
class AlignmentEntry
Deprecated: Handle class describing an alignment entry.
class Assembly
Implementation class extending the ROOT assembly volumes (TGeoVolumeAsembly)
class Atom
Handle class describing an element in the periodic table.
class Author
Handle class describing an author entity.
class BooleanSolid
Base class describing boolean (=union,intersection,subtraction) solids.
class Box
Class describing a box shape.
class CartesianField
Handle class describing any field with 3D cartesian vectors for the field strength.
class CartesianGridXY
Implementation class for the grid XY segmentation.
class CartesianGridXYZ
Implementation class for the grid XYZ segmentation.
class CartesianGridXZ
Implementation class for the grid XZ segmentation.
class CartesianGridYZ
Implementation class for the grid YZ segmentation.
class Cone
Class describing a cone shape.
class ConeSegment
Class describing a cone segment shape.
class Constant
Handle class describing a constant (define) object in lcdd.
class ConstantField
Implementation object of a field with constant strength.
class ConstantObject
Concrete object implementation for the Constant handle.
class DetectorSelector
View on LCDD to select detectors according to certain criteria.
class DetElement
Handle class describing a detector element.
class DetElementObject
Data class with properties of a detector element.
class DipoleField
Implementation object of a dipole magnetic field.
class EightPointSolid
Class describing an arbitray solid defined by 8 vertices.
class EllipticalTube
Class describing a elliptical tube shape of a section of a tube.
class GeoHandler
The base class for all DD4hep geometry crawlers.
class GeoHandlerTypes
Defintion of the object types used by generic geometry handlers.
class GeometryTreeDump
Geometry to screen dump action.
class GeoScan
Geometry scanner (handle object)
class HalfSpace
Class describing half-space.
class Header
Handle class describing the basic information about geometry objects as it is defined in LCDD.
class HeaderObject
Concrete object implementation for the Header handle.
class HitCollection
Definition of the HitCollection parameters used by the Readout.
class Hyperboloid
Class describing a Hyperboloid shape.
class IDDescriptor
Class implementing the ID encoding of detector response.
class IDDescriptorObject
Concrete object implementation of the IDDescriptorObject Handle.
class IntersectionSolid
Class describing boolean intersection solid.
class LCDD
The main interface to the DD4hep detector description package.
class LCDDData
Data implementation class of the LCDD interface.
class LCDDHelper
LCDDHelper: class to shortcut certain questions to the DD4hep detector description interface.
class LCDDImp
Concrete implementation class of the LCDD interface.
class Limit
Small object describing a limit structure acting on a particle type.
class LimitSet
Handle class describing a set of limits as they are used for simulation.
class LimitSetObject
Concrete object implementation of the LimitSet Handle.
class Material
Handle class describing a material.
class MultipoleField
Implementation object of a Multipole magnetic field.
class MultiSegmentation
Implementation class for the grid XZ segmentation.
class MyConeSeg
Intermediate class to overcome drawing probles with the TGeoTubeSeg.
class OverlayedField
Class describing a field overlay with several sources.
class Paraboloid
Class describing a Paraboloid shape.
class PlacedVolume
Handle class holding a placed volume (also called physical volume)
class PlacedVolumeExtension
Implementation class extending the ROOT placed volume.
class PolarGridRPhi
Implementation class for the grid XZ segmentation.
class PolarGridRPhi2
Implementation class for the grid XZ segmentation.
class Polycone
Class describing a Polycone shape.
class PolyhedraRegular
Class describing a regular polyhedron shape.
class Readout
Handle to the implementation of the readout structure of a subdetector.
class ReadoutObject
Concrete object implementation of the Readout Handle.
class Region
Handle class describing a region as used in simulation.
class RegionObject
Concrete object implementation of the Region Handle.
class Segmentation
Handle class supporting generic Segmentation of sensitive detectors.
class SegmentationObject
Implementation class supporting generic Segmentation of sensitive detectors.
class SegmentationWrapper
Concrete wrapper class for segmentation implementation based on DDSegmentation objects.
class SensitiveDetector
Handle class to hold the information of a sensitive detector.
class SensitiveDetectorObject
Data class with properties of sensitive detectors.
class SimpleGDMLWriter
Simple GDML creator from TGeo geometries in memory.
class SolenoidField
Implementation object of a solenoidal magnetic field.
class Solid_type
Base class for Solid (shape) objects.
class Sphere
Class describing a sphere shape.
class SubtractionSolid
Class describing boolean subtraction solid.
class Torus
Class describing a Torus shape.
class Trap
Class describing a trap shape.
class Trapezoid
Class describing a Trapezoid shape.
class Tube
Class describing a tube shape of a section of a tube.
class UnionSolid
Class describing boolean union solid.
class VisAttr
Handle class describing visualization attributes.
class VisAttrObject
Concrete object implementation of the VisAttr Handle.
class Volume
Handle class holding a placed volume (also called physical volume)
class VolumeExtension
Implementation class extending the ROOT volume (TGeoVolume)
class VolumeManager
Class to support the retrieval of detector elements and volumes given a valid identifier.
class VolumeManagerContext
This structure describes the cached data for one placement held by the volume manager.
class VolumeManagerObject
This structure describes the internal data of the volume manager object.
class WaferGridXY
Implementation class for the grid XZ segmentation.
class World
Handle class to hold the information of the top DetElement object 'world'.
class WorldObject
Data class with properties of a detector element.
Typedefs
typedef Handle< SegmentationWrapper< DDSegmentation::CartesianGridXY > > CartesianGridXYHandle
We need some abbreviation to make the code more readable.
typedef Handle< SegmentationWrapper< DDSegmentation::CartesianGridXYZ > > CartesianGridXYZHandle
We need some abbreviation to make the code more readable.
typedef Handle< SegmentationWrapper< DDSegmentation::CartesianGridXZ > > CartesianGridXZHandle
We need some abbreviation to make the code more readable.
typedef Handle< SegmentationWrapper< DDSegmentation::CartesianGridYZ > > CartesianGridYZHandle
We need some abbreviation to make the code more readable.
typedef Position Direction
typedef CartesianField ElectricField
typedef CartesianField MagneticField
typedef OverlayedField ElectroMagneticField
typedef Position XYZAngles
typedef Handle< SegmentationWrapper< DDSegmentation::MultiSegmentation > > MultiSegmentationHandle
We need some abbreviation to make the code more readable.
typedef ROOT::Math::XYZVector Position
typedef ROOT::Math::RotationZYX RotationZYX
typedef ROOT::Math::RotationZ RotationZ
typedef ROOT::Math::RotationY RotationY
typedef ROOT::Math::RotationX RotationX
typedef ROOT::Math::Rotation3D Rotation3D
typedef ROOT::Math::EulerAngles EulerAngles
typedef ROOT::Math::Transform3D Transform3D
typedef ROOT::Math::Translation3D Translation3D
typedef Handle< SegmentationWrapper< DDSegmentation::PolarGridRPhi > > PolarGridRPhiHandle
We need some abbreviation to make the code more readable.
typedef Handle< SegmentationWrapper< DDSegmentation::PolarGridRPhi2 > > PolarGridRPhi2Handle
We need some abbreviation to make the code more readable.
typedef Solid_type< TGeoShape > Solid
typedef Handle< SegmentationWrapper< DDSegmentation::WaferGridXY > > WaferGridXYHandle
We need some abbreviation to make the code more readable.
Functions
static std::string _toString (const DD4hep::XML::XmlChar *value)
std::string conversion of XML strings (e.g. Unicode for Xerces-C)
template<typename T >
std::string _toString (T value, const char *fmt)
std::string conversion of arbitrary entities including user defined formatting.
template<>
std::string LCDD::constant< std::string > (const std::string &name) const
Typed access to constants: string values.
TGeoIdentity * identityTransform ()
Access the TGeo identity transformation .
TGeoTranslation * _translation (const Geometry::Position &pos)
Convert a Position object to a TGeoTranslation .
TGeoRotation * _rotationZYX (const Geometry::RotationZYX &rot)
Convert a RotationZYX object to a TGeoRotation .
TGeoRotation * _rotation3D (const Geometry::Rotation3D &rot)
Convert a Rotation3D object to a TGeoRotation .
TGeoHMatrix * _transform (const Geometry::Transform3D &trans)
Convert a Transform3D object to a TGeoHMatrix .
TGeoHMatrix * _transform (const Geometry::Position &pos)
Convert a Position object to a TGeoHMatrix .
TGeoHMatrix * _transform (const Geometry::RotationZYX &rot)
Convert a RotationZYX object to a TGeoHMatrix .
TGeoHMatrix * _transform (const Geometry::Rotation3D &rot3D)
Convert a Rotation3D object to a TGeoHMatrix .
TGeoHMatrix * _transform (const Geometry::Position &pos, const Geometry::RotationZYX &rot)
Convert a Position followed by a RotationZYX to a TGeoHMatrix .
TGeoHMatrix & _transform (TGeoHMatrix &mat, const Geometry::Transform3D &trans)
Set a Transform3D object to a TGeoHMatrix .
TGeoHMatrix & _transform (TGeoHMatrix &mat, const Geometry::Position &pos)
Set a Position object (translation) to a TGeoHMatrix .
TGeoHMatrix & _transform (TGeoHMatrix &mat, const Geometry::RotationZYX &rot)
Set a RotationZYX object to a TGeoHMatrix .
TGeoHMatrix & _transform (TGeoHMatrix &mat, const Geometry::Rotation3D &rot3D)
Set a Rotation3D object to a TGeoHMatrix .
TGeoHMatrix & _transform (TGeoHMatrix &mat, const Geometry::Position &pos, const Geometry::RotationZYX &rot)
Set a Position followed by a RotationZYX to a TGeoHMatrix .
Geometry::Transform3D _transform (const TGeoMatrix *matrix)
Convert a TGeoMatrix object to a generic Transform3D .
void _decompose (const Geometry::Transform3D &trafo, Geometry::Position &pos, Geometry::RotationZYX &rot)
Decompose a generic Transform3D into a translation (Position) and a RotationZYX .
void _decompose (const Geometry::Transform3D &trafo, Geometry::Position &pos, XYZAngles &rot)
Decompose a generic Transform3D into a translation (Geometry::Position) and XYZAngles .
void _decompose (const Geometry::Transform3D &trafo, Geometry::Translation3D &pos, Geometry::RotationZYX &rot)
Decompose a generic Transform3D into a translation (Translation3D) and a RotationZYX .
void _decompose (const Geometry::Transform3D &trafo, Geometry::Translation3D &pos, XYZAngles &rot)
Decompose a generic Transform3D into a translation (Translation3D) and XYZAngles .
XYZAngles _XYZangles (const double *matrix)
Convert a 3x3 rotation matrix to XYZAngles .
XYZAngles _XYZangles (const TGeoMatrix *matrix)
Convert a the rotation part of a TGeoMatrix to XYZAngles .
template<class V >
V RotateX (const V &v, double a)
template<class V >
V RotateY (const V &v, double a)
template<class V >
V RotateZ (const V &v, double a)
std::string toStringSolid (const TGeoShape *shape, int precision=2)
Pretty print of solid attributes.
std::ostream & operator<< (std::ostream &os, const VolumeManager &m)
Enable printouts for debugging.
Detailed Description
Namespace for the geometry part of the AIDA detector description toolkit.
Typedef Documentation
CartesianGridXYHandle
typedef Handle<SegmentationWrapper<DDSegmentation::CartesianGridXY> > DD4hep::Geometry::CartesianGridXYHandle
We need some abbreviation to make the code more readable.
Definition at line 32 of file CartesianGridXY.h.
CartesianGridXYZHandle
typedef Handle<SegmentationWrapper<DDSegmentation::CartesianGridXYZ> > DD4hep::Geometry::CartesianGridXYZHandle
We need some abbreviation to make the code more readable.
Definition at line 32 of file CartesianGridXYZ.h.
CartesianGridXZHandle
typedef Handle<SegmentationWrapper<DDSegmentation::CartesianGridXZ> > DD4hep::Geometry::CartesianGridXZHandle
We need some abbreviation to make the code more readable.
Definition at line 32 of file CartesianGridXZ.h.
CartesianGridYZHandle
typedef Handle<SegmentationWrapper<DDSegmentation::CartesianGridYZ> > DD4hep::Geometry::CartesianGridYZHandle
We need some abbreviation to make the code more readable.
Definition at line 32 of file CartesianGridYZ.h.
Direction
typedef Position DD4hep::Geometry::Direction
Definition at line 31 of file Fields.h.
ElectricField
typedef CartesianField DD4hep::Geometry::ElectricField
Definition at line 111 of file Fields.h.
ElectroMagneticField
typedef OverlayedField DD4hep::Geometry::ElectroMagneticField
Definition at line 241 of file Fields.h.
EulerAngles
typedef ROOT::Math::EulerAngles DD4hep::Geometry::EulerAngles
See also
http://root.cern.ch/root/html/ROOT__Math__EulerAngels.html
Definition at line 108 of file Objects.h.
MagneticField
typedef CartesianField DD4hep::Geometry::MagneticField
Definition at line 112 of file Fields.h.
MultiSegmentationHandle
typedef Handle<SegmentationWrapper<DDSegmentation::MultiSegmentation> > DD4hep::Geometry::MultiSegmentationHandle
We need some abbreviation to make the code more readable.
Definition at line 32 of file MultiSegmentation.h.
PolarGridRPhi2Handle
typedef Handle<SegmentationWrapper<DDSegmentation::PolarGridRPhi2> > DD4hep::Geometry::PolarGridRPhi2Handle
We need some abbreviation to make the code more readable.
Definition at line 31 of file PolarGridRPhi2.h.
PolarGridRPhiHandle
typedef Handle<SegmentationWrapper<DDSegmentation::PolarGridRPhi> > DD4hep::Geometry::PolarGridRPhiHandle
We need some abbreviation to make the code more readable.
Definition at line 31 of file PolarGridRPhi.h.
Position
typedef ROOT::Math::XYZVector DD4hep::Geometry::Position
Definition at line 75 of file Objects.h.
Rotation3D
typedef ROOT::Math::Rotation3D DD4hep::Geometry::Rotation3D
See also
http://root.cern.ch/root/html/ROOT__Math__Rotation3D.html
Definition at line 106 of file Objects.h.
RotationX
typedef ROOT::Math::RotationX DD4hep::Geometry::RotationX
See also
http://root.cern.ch/root/html/ROOT__Math__RotationX.html
Definition at line 104 of file Objects.h.
RotationY
typedef ROOT::Math::RotationY DD4hep::Geometry::RotationY
See also
http://root.cern.ch/root/html/ROOT__Math__RotationY.html
Definition at line 102 of file Objects.h.
RotationZ
typedef ROOT::Math::RotationZ DD4hep::Geometry::RotationZ
See also
http://root.cern.ch/root/html/ROOT__Math__RotationZ.html
Definition at line 100 of file Objects.h.
RotationZYX
typedef ROOT::Math::RotationZYX DD4hep::Geometry::RotationZYX
Rotation class with the (3D) rotation represented by angles describing first a rotation of an angle phi (yaw) about the Z axis, followed by a rotation of an angle theta (pitch) about the new Y' axis, followed by a third rotation of an angle psi (roll) about the final X'' axis. This is sometimes referred to as the Euler 321 sequence. It has not to be confused with the typical Goldstein definition of the Euler Angles (Z-X-Z or 313 sequence) which is used by the ROOT::Math::EulerAngles class.
See also
http://root.cern.ch/root/html/ROOT__Math__RotationZYX.html
Definition at line 98 of file Objects.h.
Solid
typedef Solid_type<TGeoShape> DD4hep::Geometry::Solid
Definition at line 106 of file Shapes.h.
Transform3D
typedef ROOT::Math::Transform3D DD4hep::Geometry::Transform3D
See also
http://root.cern.ch/root/html/ROOT__Math__Transform3D.html
Definition at line 110 of file Objects.h.
Translation3D
typedef ROOT::Math::Translation3D DD4hep::Geometry::Translation3D
See also
http://root.cern.ch/root/html/ROOT__Math__Translations3D.html
Definition at line 112 of file Objects.h.
WaferGridXYHandle
typedef Handle<SegmentationWrapper<DDSegmentation::WaferGridXY> > DD4hep::Geometry::WaferGridXYHandle
We need some abbreviation to make the code more readable.
Definition at line 31 of file WaferGridXY.h.
XYZAngles
typedef Position DD4hep::Geometry::XYZAngles
Definition at line 31 of file MatrixHelpers.h.
Function Documentation
_toString() [1/2]
static std::string DD4hep::Geometry::_toString (const DD4hep::XML::XmlChar * value) inline static
std::string conversion of XML strings (e.g. Unicode for Xerces-C)
Definition at line 47 of file DetFactoryHelper.h.
References DD4hep::XML::_toString().
Referenced by DD4hep::Geometry::PolyhedraRegular::_create(), DD4hep::XML::_toBool(), DD4hep::XML::_toDictionary(), DD4hep::XML::_toDouble(), DD4hep::XML::_toFloat(), DD4hep::XML::_toInt(), DD4hep::XML::_toLong(), DD4hep::XML::_toString(), create_detector(), DD4hep::XML::DocumentErrorHandler::error(), DD4hep::XML::DocumentErrorHandler::fatalError(), DD4hep::XML::DocumentErrorHandler::handleError(), DD4hep::XML::XmlString::length(), DD4hep::XML::DocumentHandler::load(), DD4hep::XML::operator+(), placeStaves(), and DD4hep::XML::DocumentHandler::system_path().
_toString() [2/2]
template<typename T > std::string DD4hep::Geometry::_toString (T value, const char * fmt) inline
std::string conversion of arbitrary entities including user defined formatting.
Definition at line 52 of file DetFactoryHelper.h.
References DD4hep::XML::_toString().
LCDD::constant< std::string >()
template<> std::string DD4hep::Geometry::LCDD::constant< std::string > (const std::string & name) const inline
Typed access to constants: string values.
Definition at line 379 of file LCDD.h.
operator<<()
std::ostream & DD4hep::Geometry::operator<< (std::ostream & os, const VolumeManager & m)
Enable printouts for debugging.
Definition at line 685 of file VolumeManager.cpp.
References DD4hep::Handle< T >::data(), DD4hep::Geometry::VolumeManagerObject::detector, DD4hep::Geometry::VolumeManagerObject::id, DD4hep::Geometry::VolumeManagerContext::identifier, DD4hep::Geometry::VolumeManagerObject::managers, DD4hep::Geometry::VolumeManagerContext::mask, DD4hep::Handle< T >::name(), DD4hep::Geometry::VolumeManagerContext::placement, DD4hep::Geometry::VolumeManagerObject::sysID, DD4hep::Geometry::VolumeManagerObject::top, DD4hep::Geometry::IDDescriptor::toString(), and DD4hep::Geometry::VolumeManagerObject::volumes.
Referenced by DD4hep::Geometry::VolumeManager::operator=().
RotateX()
template<class V > V DD4hep::Geometry::RotateX (const V & v, double a)
Definition at line 78 of file Objects.h.
RotateY()
template<class V > V DD4hep::Geometry::RotateY (const V & v, double a)
Definition at line 81 of file Objects.h.
RotateZ()
template<class V > V DD4hep::Geometry::RotateZ (const V & v, double a)
Definition at line 84 of file Objects.h.
toStringSolid()
std::string DD4hep::Geometry::toStringSolid (const TGeoShape * shape, int precision = 2)
Pretty print of solid attributes.
Definition at line 49 of file Shapes.cpp.
References s.
Referenced by DD4hep::Geometry::Solid_type< TGeoBBox >::toString().