DD4hep: DD4hep::Geometry::DetectorTools Namespace Reference
DD4hep::Geometry::DetectorTools Namespace Reference
DD4hep::Geometry components, classes and objects
Helper namespace used to answer detector element specific questons.
Typedefs
typedef std::vector< DetElement > ElementPath
typedef std::vector< PlacedVolume > PlacementPath
Functions
std::string elementPath (const PlacementPath &nodes, bool reverse)
Assemble the path of the PlacedVolume selection.
void elementPath (DetElement parent, DetElement elt, ElementPath &detectors)
Collect detector elements to any parent detector element.
void elementPath (DetElement elt, PlacementPath &nodes)
Collect detector elements placements to the top detector element (world) [fast, but may have holes!].
void elementPath (DetElement parent, DetElement element, PlacementPath &nodes)
Collect detector elements placements to the parent detector element [no holes!].
DetElement findElement (LCDD &lcdd, const std::string &path)
Find DetElement as child of the top level volume by it's absolute path.
bool findChild (PlacedVolume parent, PlacedVolume child, PlacementPath &path)
Find Child of PlacedVolume and assemble on the fly the path of PlacedVolumes.
static void makePlacementPath (PlacementPath det_nodes, PlacementPath &all_nodes)
DetElement topElement (DetElement child)
Determine top level element (=world) for any element walking up the detector element tree.
std::string elementPath (DetElement element)
Assemble the path of a particular detector element.
std::string elementPath (const ElementPath &nodes, bool reverse=true)
Assemble the path of the PlacedVolume selection.
void elementPath (DetElement elt, ElementPath &detectors)
Collect detector elements to the top detector element (world)
DetElement findDaughterElement (DetElement parent, const std::string &subpath)
Find DetElement as child of a parent by it's relative or absolute path.
bool isParentElement (DetElement parent, DetElement child)
Find path between the child element and the parent element.
std::string placementPath (DetElement element)
Assemble the placement path from a given detector element to the world volume.
std::string placementPath (const PlacementPath &nodes, bool reverse=true)
Assemble the path of the PlacedVolume selection.
std::string placementPath (const std::vector< const TGeoNode *> &nodes, bool reverse=true)
Assemble the path of the PlacedVolume selection.
void placementPath (DetElement elt, PlacementPath &nodes)
Collect detector elements placements to the top detector element (world) [no holes!].
void placementPath (DetElement parent, DetElement child, PlacementPath &nodes)
Collect detector elements placements to the parent detector element [no holes!].
PlacedVolume findNode (PlacedVolume top_place, const std::string &place)
Find a given node in the hierarchy starting from the top node (absolute placement!)
void placementTrafo (const PlacementPath &nodes, bool inverse, TGeoHMatrix *&mat)
Update cached matrix to transform to positions to an upper level Placement.
void placementTrafo (const PlacementPath &nodes, bool inverse, TGeoHMatrix &mat)
Update cached matrix to transform to positions to an upper level Placement.
std::string toString (const PlacedVolume::VolIDs &ids)
Convert VolumeID to string.
std::string toString (const IDDescriptor &dsc, const PlacedVolume::VolIDs &ids, VolumeID code)
Convert VolumeID to string.
Detailed Description
Helper namespace used to answer detector element specific questons.
Author
M.Frank
Version
1.0
Author
M.Frank
Version
1.0
Typedef Documentation
ElementPath
typedef std::vector<DetElement> DD4hep::Geometry::DetectorTools::ElementPath
Definition at line 40 of file DetectorTools.h.
PlacementPath
typedef std::vector<PlacedVolume> DD4hep::Geometry::DetectorTools::PlacementPath
Definition at line 41 of file DetectorTools.h.
Function Documentation
elementPath() [1/7]
std::string DD4hep::Geometry::DetectorTools::elementPath (const PlacementPath & nodes, bool reverse)
Assemble the path of the PlacedVolume selection.
Definition at line 188 of file DetectorTools.cpp.
References s.
Referenced by elementPath(), DD4hep::SurfaceInstaller::install(), and placementPath().
elementPath() [2/7]
void DD4hep::Geometry::DetectorTools::elementPath (DetElement parent, DetElement elt, ElementPath & detectors)
Collect detector elements to any parent detector element.
Definition at line 145 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), and DD4hep::Handle< T >::ptr().
elementPath() [3/7]
void DD4hep::Geometry::DetectorTools::elementPath (DetElement elt, PlacementPath & nodes)
Collect detector elements placements to the top detector element (world) [fast, but may have holes!].
Definition at line 178 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid().
elementPath() [4/7]
std::string DD4hep::Geometry::DetectorTools::elementPath (DetElement element)
Assemble the path of a particular detector element.
Definition at line 216 of file DetectorTools.cpp.
References elementPath().
elementPath() [5/7]
void DD4hep::Geometry::DetectorTools::elementPath (DetElement parent, DetElement element, PlacementPath & nodes)
Collect detector elements placements to the parent detector element [no holes!].
Collect detector elements placements to the top detector element (world) [fast, but may have holes!].
Definition at line 166 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid(), DD4hep::Handle< T >::name(), and DD4hep::Handle< T >::ptr().
elementPath() [6/7]
std::string DD4hep::Geometry::DetectorTools::elementPath (const ElementPath & nodes, bool reverse = true)
Assemble the path of the PlacedVolume selection.
Definition at line 202 of file DetectorTools.cpp.
References s.
elementPath() [7/7]
void DD4hep::Geometry::DetectorTools::elementPath (DetElement elt, ElementPath & detectors)
Collect detector elements to the top detector element (world)
Definition at line 139 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid().
findChild()
bool DD4hep::Geometry::DetectorTools::findChild (PlacedVolume parent, PlacedVolume child, PlacementPath & path)
Find Child of PlacedVolume and assemble on the fly the path of PlacedVolumes.
Definition at line 77 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Handle< T >::ptr().
findDaughterElement()
DetElement DD4hep::Geometry::DetectorTools::findDaughterElement (DetElement parent, const std::string & subpath)
Find DetElement as child of a parent by it's relative or absolute path.
Definition at line 228 of file DetectorTools.cpp.
References DD4hep::Geometry::DetElement::child(), DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::path(), and topElement().
Referenced by DD4hep::Conditions::Test::TestEnv::daughter(), and findElement().
findElement()
DetElement DD4hep::Geometry::DetectorTools::findElement (LCDD & lcdd, const std::string & path)
Find DetElement as child of the top level volume by it's absolute path.
Definition at line 223 of file DetectorTools.cpp.
References findDaughterElement(), and DD4hep::Geometry::LCDD::world().
findNode()
PlacedVolume DD4hep::Geometry::DetectorTools::findNode (PlacedVolume top_place, const std::string & place)
Find a given node in the hierarchy starting from the top node (absolute placement!)
Definition at line 338 of file DetectorTools.cpp.
References DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Geometry::DetElementObject::revalidate().
isParentElement()
bool DD4hep::Geometry::DetectorTools::isParentElement (DetElement parent, DetElement child)
Find path between the child element and the parent element.
Definition at line 66 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Handle< T >::ptr().
Referenced by DD4hep::Geometry::DetElementObject::referenceTransformation().
makePlacementPath()
static void DD4hep::Geometry::DetectorTools::makePlacementPath (PlacementPath det_nodes, PlacementPath & all_nodes) static
Definition at line 258 of file DetectorTools.cpp.
References findChildByName().
Referenced by placementPath().
placementPath() [1/5]
std::string DD4hep::Geometry::DetectorTools::placementPath (DetElement element)
Assemble the placement path from a given detector element to the world volume.
Assemble the path of the PlacedVolume selection.
Definition at line 285 of file DetectorTools.cpp.
Referenced by DD4hep::Geometry::DetElement::callAtUpdate(), DD4hep::Alignments::GlobalDetectorAlignment::collectNodes(), DD4hep::Alignments::AlignmentTools::computeIdeal(), DD4hep::Alignments::AlignmentTools::computeSurvey(), DD4hep::Simulation::Geant4AssemblyVolume::imprint(), DD4hep::SurfaceInstaller::install(), DD4hep::Geometry::DetElementObject::parentTransformation(), DD4hep::Geometry::DetElement::placementPath(), DD4hep::Geometry::DetElementObject::referenceTransformation(), DD4hep::Geometry::DetElementObject::revalidate(), and DD4hep::Geometry::DetElementObject::worldTransformation().
placementPath() [2/5]
std::string DD4hep::Geometry::DetectorTools::placementPath (const PlacementPath & nodes, bool reverse = true)
Assemble the path of the PlacedVolume selection.
Definition at line 292 of file DetectorTools.cpp.
References s.
placementPath() [3/5]
std::string DD4hep::Geometry::DetectorTools::placementPath (const std::vector< const TGeoNode *> & nodes, bool reverse = true)
Assemble the path of the PlacedVolume selection.
Definition at line 306 of file DetectorTools.cpp.
References s.
placementPath() [4/5]
void DD4hep::Geometry::DetectorTools::placementPath (DetElement elt, PlacementPath & nodes)
Collect detector elements placements to the top detector element (world) [no holes!].
Definition at line 271 of file DetectorTools.cpp.
References elementPath(), and makePlacementPath().
placementPath() [5/5]
void DD4hep::Geometry::DetectorTools::placementPath (DetElement parent, DetElement child, PlacementPath & nodes)
Collect detector elements placements to the parent detector element [no holes!].
Definition at line 278 of file DetectorTools.cpp.
References elementPath(), and makePlacementPath().
placementTrafo() [1/2]
void DD4hep::Geometry::DetectorTools::placementTrafo (const PlacementPath & nodes, bool inverse, TGeoHMatrix *& mat)
Update cached matrix to transform to positions to an upper level Placement.
Definition at line 320 of file DetectorTools.cpp.
Referenced by DD4hep::Geometry::DetElementObject::parentTransformation(), DD4hep::Geometry::DetElementObject::referenceTransformation(), DD4hep::Geometry::DetElementObject::revalidate(), and DD4hep::Geometry::DetElementObject::worldTransformation().
placementTrafo() [2/2]
void DD4hep::Geometry::DetectorTools::placementTrafo (const PlacementPath & nodes, bool inverse, TGeoHMatrix & mat)
Update cached matrix to transform to positions to an upper level Placement.
Definition at line 326 of file DetectorTools.cpp.
topElement()
DetElement DD4hep::Geometry::DetectorTools::topElement (DetElement child)
Determine top level element (=world) for any element walking up the detector element tree.
Definition at line 249 of file DetectorTools.cpp.
References DD4hep::Handle< T >::isValid(), and DD4hep::Geometry::DetElement::parent().
Referenced by findDaughterElement().
toString() [1/2]
std::string DD4hep::Geometry::DetectorTools::toString (const PlacedVolume::VolIDs & ids)
Convert VolumeID to string.
Definition at line 388 of file DetectorTools.cpp.
Referenced by DD4hep::Geometry::Constant::Constant(), DD4hep::Geometry::Limit::Limit(), DD4hep::Geometry::Material::Material(), DD4hep::Geometry::PlacedVolume::operator=(), DD4hep::Geometry::VisAttr::operator=(), and DD4hep::Primitive< T >::type_name().
toString() [2/2]
std::string DD4hep::Geometry::DetectorTools::toString (const IDDescriptor & dsc, const PlacedVolume::VolIDs & ids, VolumeID code)
Convert VolumeID to string.
Definition at line 396 of file DetectorTools.cpp.
References DD4hep::Geometry::IDDescriptor::field(), DD4hep::DDSegmentation::BitFieldValue::offset(), DD4hep::DDSegmentation::BitFieldValue::value(), and DD4hep::DDSegmentation::BitFieldValue::width().