DD4hep: DD4hep::Utils Namespace Reference
DD4hep::Utils Namespace Reference
Utility namespace to support boost::spirit.
Functions
std::ostream & toStream (const Property &result, std::ostream &os)
template<class TYPE >
std::ostream & toStream (const TYPE &obj, std::ostream &s)
template<class ITERATOR >
std::ostream & toStream (ITERATOR first, ITERATOR last, std::ostream &s, const std::string &open, const std::string &close, const std::string &delim)
the helper function to print the sequence
std::ostream & toStream (const std::string &obj, std::ostream &s)
the printtout of the strings.
std::ostream & toStream (const bool obj, std::ostream &s)
the printout of boolean values "a'la Python"
std::ostream & toStream (const float obj, std::ostream &s, const int prec=6)
the printout of float values with the reasonable precision
std::ostream & toStream (const double obj, std::ostream &s, const int prec=8)
the printout of double values with the reasonable precision
std::ostream & toStream (const long double obj, std::ostream &s, const int prec=10)
the printout of long double values with the reasonable precision
template<class KTYPE , class VTYPE >
std::ostream & toStream (const std::pair< KTYPE, VTYPE > &obj, std::ostream &s)
template<class TYPE , class ALLOCATOR >
std::ostream & toStream (const std::vector< TYPE, ALLOCATOR > &obj, std::ostream &s)
template<class TYPE , class ALLOCATOR >
std::ostream & toStream (const std::list< TYPE, ALLOCATOR > &obj, std::ostream &s)
template<class TYPE , class ALLOCATOR >
std::ostream & toStream (const std::deque< TYPE, ALLOCATOR > &obj, std::ostream &s)
template<class TYPE , class CMP , class ALLOCATOR >
std::ostream & toStream (const std::set< TYPE, CMP, ALLOCATOR > &obj, std::ostream &s)
template<class KTYPE , class VTYPE , class CMP , class ALLOCATOR >
std::ostream & toStream (const std::map< KTYPE, VTYPE, CMP, ALLOCATOR > &obj, std::ostream &s)
template<class TYPE , unsigned int N>
std::ostream & toStream (TYPE(&obj)[N], std::ostream &s)
template<class TYPE , unsigned int N>
std::ostream & toStream (const TYPE(&obj)[N], std::ostream &s)
template<unsigned int N>
std::ostream & toStream (char(&obj)[N], std::ostream &s)
template<unsigned int N>
std::ostream & toStream (const char(&obj)[N], std::ostream &s)
std::ostream & toStream (const char *obj, std::ostream &s)
template<class TYPE >
std::string toString (const TYPE &obj)
std::ostream & toStream (const ROOT::Math::XYZPoint &obj, std::ostream &s)
print XYZ point
std::ostream & toStream (const ROOT::Math::XYZVector &obj, std::ostream &s)
std::ostream & toStream (const ROOT::Math::PxPyPzEVector &obj, std::ostream &s)
print Lorentz vector
Detailed Description
Utility namespace to support boost::spirit.
Function Documentation
toStream() [1/22]
template<class TYPE > std::ostream & DD4hep::Utils::toStream (const TYPE & obj, std::ostream & s) inline
the generic implementation of the printout to the std::ostream
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 254 of file ToStream.h.
toStream() [2/22]
template<class ITERATOR > std::ostream & DD4hep::Utils::toStream (ITERATOR first, ITERATOR last, std::ostream & s, const std::string & open, const std::string & close, const std::string & delim) inline
the helper function to print the sequence
Parameters
first (INPUT) begin-iterator for the sequence
last (INPUT) end-iterator for the sequence
s (UPDATE) the stream itself
open (INPUT) "open"-symbol
close (INPUT) "close"-symbol
delim (INPUT) "delimiter"-symbol
Returns
the stream
Author
Vanya BELYAEV Ivan..nosp@m.BEly.nosp@m.aev@n.nosp@m.ikhe.nosp@m.f.nl
Date
2009-09-15
the helper function to print the sequence
Parameters
first (INPUT) begin-iterator for the sequence
last (INPUT) end-iterator for the sequence
s (UPDATE) the stream itself
open (INPUT) "open"-symbol
close (INPUT) "close"-symbol
delim (INPUT) "delimiter"-symbol
Returns
the stream
Author
Vanya BELYAEV Ivan..nosp@m.BEly.nosp@m.aev@n.nosp@m.ikhe.nosp@m.f.nl
Date
2009-09-15
Definition at line 270 of file ToStream.h.
References s, and toStream().
toStream() [3/22]
std::ostream& DD4hep::Utils::toStream (const std::string & obj, std::ostream & s) inline
the printtout of the strings.
the string is printed a'la Python using the quotes
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 81 of file ToStream.h.
References s.
toStream() [4/22]
std::ostream& DD4hep::Utils::toStream (const bool obj, std::ostream & s) inline
the printout of boolean values "a'la Python"
Author
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-09-09
Definition at line 94 of file ToStream.h.
toStream() [5/22]
std::ostream& DD4hep::Utils::toStream (const float obj, std::ostream & s, const int prec = 6) inline
the printout of float values with the reasonable precision
Author
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-09-09
Definition at line 101 of file ToStream.h.
toStream() [6/22]
std::ostream& DD4hep::Utils::toStream (const double obj, std::ostream & s, const int prec = 8) inline
the printout of double values with the reasonable precision
Author
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-09-09
Definition at line 109 of file ToStream.h.
toStream() [7/22]
std::ostream& DD4hep::Utils::toStream (const long double obj, std::ostream & s, const int prec = 10) inline
the printout of long double values with the reasonable precision
Author
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-09-09
Definition at line 117 of file ToStream.h.
toStream() [8/22]
template<class KTYPE , class VTYPE > std::ostream& DD4hep::Utils::toStream (const std::pair< KTYPE, VTYPE > & obj, std::ostream & s) inline
the partial template specialization of std::pair<KTYPE,VTYPE> printout the pair is printed a'la Python tuple: " (a , b)"
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 130 of file ToStream.h.
References toStream().
toStream() [9/22]
template<class TYPE , class ALLOCATOR > std::ostream& DD4hep::Utils::toStream (const std::vector< TYPE, ALLOCATOR > & obj, std::ostream & s) inline
the partial template specialization of std::vector<TYPE,ALLOCATOR> printout. The vector is printed a'la Python list: "[ a, b, c ]"
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 145 of file ToStream.h.
References s, and toStream().
toStream() [10/22]
template<class TYPE , class ALLOCATOR > std::ostream& DD4hep::Utils::toStream (const std::list< TYPE, ALLOCATOR > & obj, std::ostream & s) inline
the partial template specialization of std::list<TYPE,ALLOCATOR> printout. The vector is printed a'la Python list: "[ a, b, c ]"
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2007-04-08
Definition at line 156 of file ToStream.h.
References s, and toStream().
toStream() [11/22]
template<class TYPE , class ALLOCATOR > std::ostream& DD4hep::Utils::toStream (const std::deque< TYPE, ALLOCATOR > & obj, std::ostream & s) inline
the partial template specialization of std::deque<TYPE,ALLOCATOR> printout. The vector is printed a'la Python list: "[ a, b, c ]"
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 167 of file ToStream.h.
References s, and toStream().
toStream() [12/22]
template<class TYPE , class CMP , class ALLOCATOR > std::ostream& DD4hep::Utils::toStream (const std::set< TYPE, CMP, ALLOCATOR > & obj, std::ostream & s) inline
the partial template specialization of std::set<TYPE,CMP,ALLOCATOR> printout. The vector is printed a'la Python list: "[ a, b, c ]"
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 178 of file ToStream.h.
References s, and toStream().
toStream() [13/22]
template<class KTYPE , class VTYPE , class CMP , class ALLOCATOR > std::ostream& DD4hep::Utils::toStream (const std::map< KTYPE, VTYPE, CMP, ALLOCATOR > & obj, std::ostream & s) inline
the partial template specialization of std::map<KTYPE,VTYPE,CMP,ALLOCATOR> printout the map is printed a'la Python dict: " (a : b , c: d , e : f)"
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
Definition at line 190 of file ToStream.h.
References toStream().
toStream() [14/22]
template<class TYPE , unsigned int N> std::ostream& DD4hep::Utils::toStream (TYPE(&) obj[N], std::ostream & s)
the specialization for C-arrays, a'la python tuple
Author
Vanya BELYAEV Ivan..nosp@m.Bely.nosp@m.aev@n.nosp@m.ikhe.nosp@m.nf.nl
Date
2009-10-05
Definition at line 209 of file ToStream.h.
References toStream().
toStream() [15/22]
template<class TYPE , unsigned int N> std::ostream& DD4hep::Utils::toStream (const TYPE(&) obj[N], std::ostream & s)
the specialization for C-arrays, a'la python tuple
Author
Vanya BELYAEV Ivan..nosp@m.Bely.nosp@m.aev@n.nosp@m.ikhe.nosp@m.nf.nl
Date
2009-10-05
Definition at line 218 of file ToStream.h.
References toStream().
toStream() [16/22]
template<unsigned int N> std::ostream& DD4hep::Utils::toStream (char(&) obj[N], std::ostream & s)
the specialization for C-string, a'la python tuple
Author
Vanya BELYAEV Ivan..nosp@m.Bely.nosp@m.aev@n.nosp@m.ikhe.nosp@m.nf.nl
Date
2009-10-05
Definition at line 227 of file ToStream.h.
References toStream().
toStream() [17/22]
template<unsigned int N> std::ostream& DD4hep::Utils::toStream (const char(&) obj[N], std::ostream & s)
the specialization for C-string, a'la python tuple
Author
Vanya BELYAEV Ivan..nosp@m.Bely.nosp@m.aev@n.nosp@m.ikhe.nosp@m.nf.nl
Date
2009-10-05
Definition at line 236 of file ToStream.h.
References toStream().
toStream() [18/22]
std::ostream& DD4hep::Utils::toStream (const char * obj, std::ostream & s) inline
the specialization for C-string, a'la python tuple
Author
Vanya BELYAEV Ivan..nosp@m.Bely.nosp@m.aev@n.nosp@m.ikhe.nosp@m.nf.nl
Date
2009-10-05
Definition at line 244 of file ToStream.h.
References toStream().
toStream() [19/22]
std::ostream& DD4hep::Utils::toStream (const Property & result, std::ostream & os)
Definition at line 245 of file ComponentProperties.cpp.
References DD4HEP_DEFINE_PARSER_GRAMMAR_TYPE, DD4hep::DD4HEP_DEFINE_PROPERTY_CONT(), DD4hep::DD4HEP_DEFINE_PROPERTY_U_CONT(), DD4hep::Property::make(), DD4hep::Property::set(), DD4hep::Property::str(), and DD4hep::Property::value().
Referenced by DD4hep::Grammar< TYPE >::str(), toStream(), and toString().
toStream() [20/22]
std::ostream & DD4hep::Utils::toStream (const ROOT::Math::XYZPoint & obj, std::ostream & s)
print XYZ point
Definition at line 34 of file ToStream.cpp.
References s, and toStream().
toStream() [21/22]
std::ostream & DD4hep::Utils::toStream (const ROOT::Math::XYZVector & obj, std::ostream & s)
Definition at line 46 of file ToStream.cpp.
References s, and toStream().
toStream() [22/22]
std::ostream & DD4hep::Utils::toStream (const ROOT::Math::PxPyPzEVector & obj, std::ostream & s)
print Lorentz vector
Definition at line 58 of file ToStream.cpp.
References s, and toStream().
toString()
template<class TYPE > std::string DD4hep::Utils::toString (const TYPE & obj) inline
the generic implementation of the type conversion to the string
Author
Alexander MAZUROV Alexa.nosp@m.nder.nosp@m..Mazu.nosp@m.rov@.nosp@m.gmail.nosp@m..com
Vanya BELYAEV ibely.nosp@m.aev@.nosp@m.physi.nosp@m.cs.s.nosp@m.yr.ed.nosp@m.u
Date
2006-05-12
See also
DD4hep::Utils::toStream
Todo:
need to be compared with boost::lexical_cast
Definition at line 297 of file ToStream.h.
References s, and toStream().