DD4hep: DDSurfaces Namespace Reference
DDSurfaces Namespace Reference
Namespace for the tracking surfaces of the AIDA detector description toolkit.
Classes
class ICone
class ICylinder
class IMaterial
class ISurface
class SurfaceType
class Vector2D
class Vector3D
Typedefs
typedef long long int long64
Functions
std::ostream & operator<< (std::ostream &os, const IMaterial &m)
dump IMaterial operator
std::ostream & operator<< (std::ostream &os, const SurfaceType &t)
dump SurfaceType operator
std::ostream & operator<< (std::ostream &os, const ISurface &s)
dump ISurface operator
Vector3D operator+ (const Vector3D &a, const Vector3D &b)
Vector3D operator- (const Vector3D &a, const Vector3D &b)
bool operator== (const Vector3D &a, const Vector3D &b)
Vector3D operator* (double s, const Vector3D &v)
Vector3D operator- (const Vector3D &v)
double operator* (const Vector3D &v0, const Vector3D &v1)
operator for scalar product
std::ostream & operator<< (std::ostream &os, const Vector3D &v)
Detailed Description
Namespace for the tracking surfaces of the AIDA detector description toolkit.
Typedef Documentation
long64
typedef long long int DDSurfaces::long64
Definition at line 14 of file ISurface.h.
Function Documentation
operator*() [1/2]
Vector3D DDSurfaces::operator* (double s, const Vector3D & v) inline
Multiplication with scalar
Definition at line 291 of file Vector3D.h.
References DDSurfaces::Vector3D::Vector3D(), DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().
operator*() [2/2]
double DDSurfaces::operator* (const Vector3D & v0, const Vector3D & v1) inline
operator for scalar product
Definition at line 303 of file Vector3D.h.
References DDSurfaces::Vector3D::dot().
operator+()
Vector3D DDSurfaces::operator+ (const Vector3D & a, const Vector3D & b) inline
Addition of two vectors
Definition at line 272 of file Vector3D.h.
References DDSurfaces::Vector3D::Vector3D(), DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().
operator-() [1/2]
Vector3D DDSurfaces::operator- (const Vector3D & a, const Vector3D & b) inline
Subtraction of two vectors
Definition at line 277 of file Vector3D.h.
References DDSurfaces::Vector3D::Vector3D(), DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().
operator-() [2/2]
Vector3D DDSurfaces::operator- (const Vector3D & v) inline
Negative vector
Definition at line 297 of file Vector3D.h.
References DDSurfaces::Vector3D::Vector3D(), DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().
operator<<() [1/4]
std::ostream& DDSurfaces::operator<< (std::ostream & os, const IMaterial & m) inline
dump IMaterial operator
Definition at line 48 of file IMaterial.h.
References DDSurfaces::IMaterial::A(), DDSurfaces::IMaterial::density(), DDSurfaces::IMaterial::interactionLength(), DDSurfaces::IMaterial::name(), DDSurfaces::IMaterial::radiationLength(), and DDSurfaces::IMaterial::Z().
operator<<() [2/4]
std::ostream& DDSurfaces::operator<< (std::ostream & os, const SurfaceType & t) inline
dump SurfaceType operator
Definition at line 277 of file ISurface.h.
References DDSurfaces::SurfaceType::isCone(), DDSurfaces::SurfaceType::isCylinder(), DDSurfaces::SurfaceType::isHelper(), DDSurfaces::SurfaceType::isOrthogonalToZ(), DDSurfaces::SurfaceType::isParallelToZ(), DDSurfaces::SurfaceType::isPlane(), DDSurfaces::SurfaceType::isSensitive(), DDSurfaces::SurfaceType::isZCone(), DDSurfaces::SurfaceType::isZCylinder(), DDSurfaces::SurfaceType::isZDisk(), and DDSurfaces::SurfaceType::isZPlane().
operator<<() [3/4]
std::ostream& DDSurfaces::operator<< (std::ostream & os, const ISurface & s) inline
dump ISurface operator
Definition at line 297 of file ISurface.h.
References DDSurfaces::ISurface::id(), DDSurfaces::ISurface::innerMaterial(), DDSurfaces::ISurface::innerThickness(), DDSurfaces::ISurface::normal(), DDSurfaces::ISurface::origin(), DDSurfaces::ISurface::outerMaterial(), DDSurfaces::ISurface::outerThickness(), DDSurfaces::ICylinder::radius(), DDSurfaces::ICone::radius0(), DDSurfaces::ICone::radius1(), s, DDSurfaces::ISurface::type(), DDSurfaces::ISurface::u(), and DDSurfaces::ISurface::v().
operator<<() [4/4]
std::ostream& DDSurfaces::operator<< (std::ostream & os, const Vector3D & v) inline
Output operator
Definition at line 345 of file Vector3D.h.
References DDSurfaces::Vector3D::phi(), DDSurfaces::Vector3D::r(), DDSurfaces::Vector3D::rho(), and DDSurfaces::Vector3D::theta().
operator==()
bool DDSurfaces::operator== (const Vector3D & a, const Vector3D & b) inline
Exact comparison of two vectors
Definition at line 282 of file Vector3D.h.
References DDSurfaces::Vector3D::x(), DDSurfaces::Vector3D::y(), and DDSurfaces::Vector3D::z().