DD4hep: DD4hep::Conditions::Test Namespace Reference
DD4hep::Conditions::Test Namespace Reference
Namespace for test environments in DDCond.
Classes
struct TestEnv
Functions
template<typename T >
void print_condition (Condition condition)
template<typename T >
void print_bound_value (Condition condition, const char *norm=0)
template<typename T >
void print_conditions (const RangeConditions &rc)
void check_discrete_condition (Condition c, const IOV &iov)
template<typename T >
const T & access_val (Condition c)
template<typename T >
void print_bound_condition (Condition c, const char *norm)
template<typename T >
void __print_bound_val (Condition c, const char *norm)
template<>
void __print_bound_val< string > (Condition c, const char *)
template<typename T >
void __print_bound_container (Condition c, const char *)
template<>
void print_condition< void > (Condition c)
template void print_conditions< void > (const RangeConditions &rc)
Detailed Description
Namespace for test environments in DDCond.
Function Documentation
__print_bound_container()
template<typename T > void DD4hep::Conditions::Test::__print_bound_container (Condition c, const char *)
Definition at line 65 of file ConditionsTest.cpp.
References DD4hep::Conditions::Condition::data(), DD4hep::INFO, DD4hep::Conditions::Condition::name(), DD4hep::printout(), DD4hep::OpaqueData::str(), DD4hep::Conditions::Condition::typeInfo(), DD4hep::typeName(), and v.
__print_bound_val()
template<typename T > void DD4hep::Conditions::Test::__print_bound_val (Condition c, const char * norm)
Definition at line 45 of file ConditionsTest.cpp.
References DD4hep::_multiply(), DD4hep::Conditions::Condition::get(), DD4hep::INFO, DD4hep::Conditions::Condition::name(), DD4hep::printout(), DD4hep::Conditions::Condition::typeInfo(), and DD4hep::typeName().
__print_bound_val< string >()
template<> void DD4hep::Conditions::Test::__print_bound_val< string > (Condition c, const char *)
Definition at line 59 of file ConditionsTest.cpp.
References DD4hep::INFO, DD4hep::printout(), DD4hep::typeName(), and v.
access_val()
template<typename T > const T & DD4hep::Conditions::Test::access_val (Condition c)
Definition at line 66 of file ConditionsTest.h.
References DD4hep::Conditions::Condition::bind(), DD4hep::Conditions::Condition::get(), and DD4hep::Conditions::Condition::is_bound().
check_discrete_condition()
void DD4hep::Conditions::Test::check_discrete_condition (Condition c, const IOV & iov)
Definition at line 157 of file ConditionsTest.cpp.
References DD4hep::IOV::contains(), DD4hep::except(), DD4hep::Conditions::Condition::iov(), DD4hep::IOV::is_discrete(), DD4hep::Conditions::Condition::name(), and DD4hep::IOV::str().
print_bound_condition()
template<typename T > void DD4hep::Conditions::Test::print_bound_condition (Condition c, const char * norm)
Definition at line 42 of file ConditionsTest.cpp.
print_bound_value()
template<typename T > void DD4hep::Conditions::Test::print_bound_value (Condition condition, const char * norm = 0)
print_condition()
template<typename T > void DD4hep::Conditions::Test::print_condition (Condition condition)
print_condition< void >()
template<> void DD4hep::Conditions::Test::print_condition< void > (Condition c)
Definition at line 114 of file ConditionsTest.cpp.
References DD4hep::INFO, and DD4hep::printout().
Referenced by DD4hep::Conditions::Test::TestEnv::dump_detector_element().
print_conditions()
template<typename T > void DD4hep::Conditions::Test::print_conditions (const RangeConditions & rc)
Definition at line 149 of file ConditionsTest.cpp.
References print_conditions< void >().
print_conditions< void >()
template void DD4hep::Conditions::Test::print_conditions< void > (const RangeConditions & rc)
Referenced by DD4hep::Conditions::Test::TestEnv::dump_conditions_pools(), and print_conditions().