DD4hep: DD4hep::Errors Namespace Reference
DD4hep::Errors Namespace Reference
Utility namespace: Errors.
Functions
IMPLEMENT (noPermission, EPERM) IMPLEMENT(noEntry
ENOENT IMPLEMENT (ioError, EIO) IMPLEMENT(invalidArg
ENOENT EINVAL IMPLEMENT (noSys, ENOSYS) IMPLEMENT(cancelled
ENOENT EINVAL ECANCELED IMPLEMENT (linkRange, ELNRNG) IMPLEMENT(noKey
std::string noPermission ()
System error string for EPERM. Sets errno accordingly.
std::string noEntry ()
System error string for ENOENT. Sets errno accordingly.
std::string ioError ()
System error string for EIO. Sets errno accordingly.
std::string invalidArg ()
System error string for EINVAL. Sets errno accordingly.
std::string noKey ()
System error string for ENOKEY. Sets errno accordingly.
std::string noSys ()
System error string for ENOSYS. Sets errno accordingly.
std::string cancelled ()
System error string for ECANCELED. Sets errno accordingly.
std::string linkRange ()
System error string for ELNRNG. Sets errno accordingly.
Detailed Description
Utility namespace: Errors.
Function Documentation
cancelled()
std::string DD4hep::Errors::cancelled ()
System error string for ECANCELED. Sets errno accordingly.
IMPLEMENT() [1/4]
DD4hep::Errors::IMPLEMENT (noPermission , EPERM)
IMPLEMENT() [2/4]
ENOENT DD4hep::Errors::IMPLEMENT (ioError , EIO)
IMPLEMENT() [3/4]
ENOENT EINVAL DD4hep::Errors::IMPLEMENT (noSys , ENOSYS)
IMPLEMENT() [4/4]
ENOENT EINVAL ECANCELED DD4hep::Errors::IMPLEMENT (linkRange , ELNRNG)
invalidArg()
std::string DD4hep::Errors::invalidArg ()
System error string for EINVAL. Sets errno accordingly.
Referenced by DD4hep::Conditions::ConditionsManagerObject::__get_checked_pool(), DD4hep::Conditions::ConditionsManagerObject::fromString(), DD4hep::Conditions::ConditionsManagerObject::pushUpdates(), and DD4hep::Conditions::ConditionsManagerObject::registerUnlocked().
ioError()
std::string DD4hep::Errors::ioError ()
System error string for EIO. Sets errno accordingly.
linkRange()
std::string DD4hep::Errors::linkRange ()
System error string for ELNRNG. Sets errno accordingly.
noEntry()
std::string DD4hep::Errors::noEntry ()
System error string for ENOENT. Sets errno accordingly.
noKey()
std::string DD4hep::Errors::noKey ()
System error string for ENOKEY. Sets errno accordingly.
noPermission()
std::string DD4hep::Errors::noPermission ()
System error string for EPERM. Sets errno accordingly.
noSys()
std::string DD4hep::Errors::noSys ()
System error string for ENOSYS. Sets errno accordingly.
Referenced by DD4hep::Conditions::ConditionsManagerObject::initialize().