DD4hep: DD4hep: DD4hep::Simulation::ParticleFilter Struct Reference
DD4hep::Simulation::ParticleFilter Struct Reference
Geant4 sensitive detector filter base class for particle filters.
Public Member Functions
ParticleFilter (Geant4Context *context, const std::string &name)
Constructor.
virtual ~ParticleFilter ()
Standard destructor.
const G4ParticleDefinition * definition () const
Safe access to the definition.
bool isSameType (const G4Track *track) const
Check if a track is of the same type.
bool isGeantino (const G4Track *track) const
Check if the particle is a geantino.
Protected Attributes
std::string m_particle
name of the particle to be filtered
G4ParticleDefinition * m_definition
Corresponding geant4 particle definiton.
Detailed Description
Geant4 sensitive detector filter base class for particle filters.
Author:
M.Frank
Version:
1.0
Definition at line 33 of file Geant4SensDetFilters.cpp.
Constructor & Destructor Documentation
ParticleFilter::ParticleFilter (Geant4Context * context, const std::string & name)
Constructor.
Definition at line 139 of file Geant4SensDetFilters.cpp.
ParticleFilter::~ParticleFilter () [virtual]
Standard destructor.
Definition at line 147 of file Geant4SensDetFilters.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
const G4ParticleDefinition * ParticleFilter::definition () const
Safe access to the definition.
Definition at line 152 of file Geant4SensDetFilters.cpp.
References m_definition, and m_particle.
Referenced by isSameType().
bool ParticleFilter::isGeantino (const G4Track * track) const
Check if the particle is a geantino.
Definition at line 168 of file Geant4SensDetFilters.cpp.
Referenced by DD4hep::Simulation::GeantinoRejectFilter::operator()().
bool ParticleFilter::isSameType (const G4Track * track) const
Check if a track is of the same type.
Definition at line 162 of file Geant4SensDetFilters.cpp.
References definition().
Referenced by DD4hep::Simulation::ParticleSelectFilter::operator()(), and DD4hep::Simulation::ParticleRejectFilter::operator()().
Member Data Documentation
G4ParticleDefinition* DD4hep::Simulation::ParticleFilter::m_definition [mutable, protected]
Corresponding geant4 particle definiton.
Definition at line 38 of file Geant4SensDetFilters.cpp.
Referenced by definition().
std::string DD4hep::Simulation::ParticleFilter::m_particle [protected]
name of the particle to be filtered
Definition at line 36 of file Geant4SensDetFilters.cpp.
Referenced by definition().
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4SensDetFilters.cpp