DD4hep: DD4hep::Primitive< T > Struct Template Reference
DD4hep::Primitive< T > Struct Template Reference
DD4hep classes and objects
A bit of support for printing primitives.
#include <Primitives.h>
Public Types
typedef T value_t
Type decribed by th class.
typedef std::vector< value_t > vector_t
Definition of the vector type.
typedef std::pair< short, value_t > short_pair_t
Definition of the short integer mapped type.
typedef std::pair< unsigned short, value_t > ushort_pair_t
Definition of the unsigned short integer mapped type.
typedef std::pair< int, value_t > int_pair_t
Definition of the integer mapped type.
typedef std::pair< unsigned int, value_t > uint_pair_t
Definition of the unsigned integer mapped type.
typedef std::pair< long, value_t > long_pair_t
Definition of the long integer mapped type.
typedef std::pair< unsigned long, value_t > ulong_pair_t
Definition of the unsigned long integer mapped type.
typedef std::pair< size_t, value_t > size_pair_t
Definition of the size_t mapped type.
typedef std::pair< std::string, value_t > string_pair_t
Definition of the string mapped type.
typedef std::map< short, value_t > short_map_t
Definition of the short integer mapped type.
typedef std::map< unsigned short, value_t > ushort_map_t
Definition of the unsigned short integer mapped type.
typedef std::map< int, value_t > int_map_t
Definition of the integer mapped type.
typedef std::map< unsigned int, value_t > uint_map_t
Definition of the unsigned integer mapped type.
typedef std::map< long, value_t > long_map_t
Definition of the long integer mapped type.
typedef std::map< unsigned long, value_t > ulong_map_t
Definition of the unsigned long integer mapped type.
typedef std::map< size_t, value_t > size_map_t
Definition of the size_t mapped type.
typedef std::map< std::string, value_t > string_map_t
Definition of the string mapped type.
typedef std::numeric_limits< value_t > limits
Definition of the limits.
Public Member Functions
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
const char * default_format ()
template<>
std::string toString (const char *value)
Convert string to string.
template<>
std::string toString (char *value)
Convert string to string.
template<>
std::string toString (std::string value)
Convert string to string.
Static Public Member Functions
static const char * default_format ()
Access to default printf format.
static const char * format ()
Access to the specific printf format. May be overloaded by users.
static const std::type_info & type ()
Access to the RTTI data type.
static std::string type_name ()
Access to the RTTI data type.
static std::string toString (T value)
Auto conversion to string using the default format.
Detailed Description
template<typename T>
struct DD4hep::Primitive< T >
A bit of support for printing primitives.
Author
M.Frank
Version
1.0
Definition at line 102 of file Primitives.h.
Member Typedef Documentation
int_map_t
template<typename T> typedef std::map<int,value_t> DD4hep::Primitive< T >::int_map_t
Definition of the integer mapped type.
Definition at line 131 of file Primitives.h.
int_pair_t
template<typename T> typedef std::pair<int,value_t> DD4hep::Primitive< T >::int_pair_t
Definition of the integer mapped type.
Definition at line 114 of file Primitives.h.
limits
template<typename T> typedef std::numeric_limits<value_t> DD4hep::Primitive< T >::limits
Definition of the limits.
Definition at line 143 of file Primitives.h.
long_map_t
template<typename T> typedef std::map<long,value_t> DD4hep::Primitive< T >::long_map_t
Definition of the long integer mapped type.
Definition at line 135 of file Primitives.h.
long_pair_t
template<typename T> typedef std::pair<long,value_t> DD4hep::Primitive< T >::long_pair_t
Definition of the long integer mapped type.
Definition at line 118 of file Primitives.h.
short_map_t
template<typename T> typedef std::map<short,value_t> DD4hep::Primitive< T >::short_map_t
Definition of the short integer mapped type.
Definition at line 127 of file Primitives.h.
short_pair_t
template<typename T> typedef std::pair<short,value_t> DD4hep::Primitive< T >::short_pair_t
Definition of the short integer mapped type.
Definition at line 110 of file Primitives.h.
size_map_t
template<typename T> typedef std::map<size_t,value_t> DD4hep::Primitive< T >::size_map_t
Definition of the size_t mapped type.
Definition at line 139 of file Primitives.h.
size_pair_t
template<typename T> typedef std::pair<size_t,value_t> DD4hep::Primitive< T >::size_pair_t
Definition of the size_t mapped type.
Definition at line 122 of file Primitives.h.
string_map_t
template<typename T> typedef std::map<std::string,value_t> DD4hep::Primitive< T >::string_map_t
Definition of the string mapped type.
Definition at line 141 of file Primitives.h.
string_pair_t
template<typename T> typedef std::pair<std::string,value_t> DD4hep::Primitive< T >::string_pair_t
Definition of the string mapped type.
Definition at line 124 of file Primitives.h.
uint_map_t
template<typename T> typedef std::map<unsigned int,value_t> DD4hep::Primitive< T >::uint_map_t
Definition of the unsigned integer mapped type.
Definition at line 133 of file Primitives.h.
uint_pair_t
template<typename T> typedef std::pair<unsigned int,value_t> DD4hep::Primitive< T >::uint_pair_t
Definition of the unsigned integer mapped type.
Definition at line 116 of file Primitives.h.
ulong_map_t
template<typename T> typedef std::map<unsigned long,value_t> DD4hep::Primitive< T >::ulong_map_t
Definition of the unsigned long integer mapped type.
Definition at line 137 of file Primitives.h.
ulong_pair_t
template<typename T> typedef std::pair<unsigned long,value_t> DD4hep::Primitive< T >::ulong_pair_t
Definition of the unsigned long integer mapped type.
Definition at line 120 of file Primitives.h.
ushort_map_t
template<typename T> typedef std::map<unsigned short,value_t> DD4hep::Primitive< T >::ushort_map_t
Definition of the unsigned short integer mapped type.
Definition at line 129 of file Primitives.h.
ushort_pair_t
template<typename T> typedef std::pair<unsigned short,value_t> DD4hep::Primitive< T >::ushort_pair_t
Definition of the unsigned short integer mapped type.
Definition at line 112 of file Primitives.h.
value_t
template<typename T> typedef T DD4hep::Primitive< T >::value_t
Type decribed by th class.
Definition at line 105 of file Primitives.h.
vector_t
template<typename T> typedef std::vector<value_t> DD4hep::Primitive< T >::vector_t
Definition of the vector type.
Definition at line 107 of file Primitives.h.
Member Function Documentation
default_format() [1/15]
template<typename T> static const char* DD4hep::Primitive< T >::default_format () static
Access to default printf format.
default_format() [2/15]
template<> const char * DD4hep::Primitive< bool >::default_format ()
Definition at line 222 of file Primitives.cpp.
default_format() [3/15]
template<> const char * DD4hep::Primitive< char >::default_format ()
Definition at line 223 of file Primitives.cpp.
default_format() [4/15]
template<> const char * DD4hep::Primitive< unsigned char >::default_format ()
Definition at line 224 of file Primitives.cpp.
default_format() [5/15]
template<> const char * DD4hep::Primitive< short >::default_format ()
Definition at line 225 of file Primitives.cpp.
default_format() [6/15]
template<> const char * DD4hep::Primitive< unsigned short >::default_format ()
Definition at line 226 of file Primitives.cpp.
default_format() [7/15]
template<> const char * DD4hep::Primitive< int >::default_format ()
Definition at line 227 of file Primitives.cpp.
default_format() [8/15]
template<> const char * DD4hep::Primitive< unsigned int >::default_format ()
Definition at line 228 of file Primitives.cpp.
default_format() [9/15]
template<> const char * DD4hep::Primitive< long >::default_format ()
Definition at line 229 of file Primitives.cpp.
default_format() [10/15]
template<> const char * DD4hep::Primitive< unsigned long >::default_format ()
Definition at line 230 of file Primitives.cpp.
default_format() [11/15]
template<> const char * DD4hep::Primitive< float >::default_format ()
Definition at line 231 of file Primitives.cpp.
default_format() [12/15]
template<> const char * DD4hep::Primitive< double >::default_format ()
Definition at line 232 of file Primitives.cpp.
default_format() [13/15]
template<> const char * DD4hep::Primitive< char * >::default_format ()
Definition at line 233 of file Primitives.cpp.
default_format() [14/15]
template<> const char * DD4hep::Primitive< const char * >::default_format ()
Definition at line 234 of file Primitives.cpp.
default_format() [15/15]
template<> const char * DD4hep::Primitive< std::string >::default_format ()
Definition at line 235 of file Primitives.cpp.
format()
template<typename T> static const char* DD4hep::Primitive< T >::format () inline static
Access to the specific printf format. May be overloaded by users.
Definition at line 148 of file Primitives.h.
toString() [1/4]
template<typename T > std::string DD4hep::Primitive< T >::toString (T value) static
Auto conversion to string using the default format.
Generic function to convert to string.
Definition at line 238 of file Primitives.cpp.
Referenced by DD4hep::Primitive< T >::toString().
toString() [2/4]
template<> std::string DD4hep::Primitive< const char * >::toString (const char * value)
Convert string to string.
Definition at line 245 of file Primitives.cpp.
toString() [3/4]
template<> std::string DD4hep::Primitive< char * >::toString (char * value)
Convert string to string.
Definition at line 252 of file Primitives.cpp.
toString() [4/4]
template<> std::string DD4hep::Primitive< std::string >::toString (std::string value)
Convert string to string.
Definition at line 259 of file Primitives.cpp.
References DD4hep::Primitive< T >::toString().
type()
template<typename T> static const std::type_info& DD4hep::Primitive< T >::type () inline static
Access to the RTTI data type.
Definition at line 150 of file Primitives.h.
type_name()
template<typename T> static std::string DD4hep::Primitive< T >::type_name () inline static
Access to the RTTI data type.
Definition at line 152 of file Primitives.h.
References DD4hep::Geometry::DetectorTools::toString(), and DD4hep::typeName().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Primitives.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Primitives.cpp