DD4hep: DD4hep: DD4hep::XML::Component Struct Reference
DD4hep::XML::Component Struct Reference
[DD4hep::XML classes and objects]
XML Handle class extending the XML handle Dimension.
#include <XMLDetector.h>
Public Member Functions
Component (Handle_t e)
Constructor from Handle.
Component (const Element &e)
Constructor from Element.
std::string materialStr () const
Access material attribute as STL string.
bool isSensitive () const
Check if component is sensitive.
bool isRadiator () const
Check if component is a radiator (absorber).
NamedObject * createShape () const
Create a shape using the plugin mechanism from an XML element.
Detailed Description
XML Handle class extending the XML handle Dimension.
Helper class to access any field in a xml tag. Specialized for attributes of a detector sub-element.
Author:
M.Frank
Version:
1.0
Definition at line 39 of file XMLDetector.h.
Constructor & Destructor Documentation
DD4hep::XML::Component::Component (Handle_t e) [inline]
Constructor from Handle.
Definition at line 41 of file XMLDetector.h.
DD4hep::XML::Component::Component (const Element & e) [inline]
Constructor from Element.
Definition at line 45 of file XMLDetector.h.
Member Function Documentation
DD4hep::NamedObject * Component::createShape () const
Create a shape using the plugin mechanism from an XML element.
Definition at line 41 of file XMLDetector.cpp.
References DD4hep::XML::Element::m_element, DD4hep::PluginDebug::missingFactory(), and DD4hep::XML::Dimension::typeStr().
Referenced by DD4hep::XML::createPlacedEnvelope().
bool Component::isRadiator () const
Check if component is a radiator (absorber).
Definition at line 35 of file XMLDetector.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by DD4hep::Layering::absorberThicknessInLayer().
bool Component::isSensitive () const
Check if component is sensitive.
Definition at line 29 of file XMLDetector.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector(), DD4hep::XML::LayeringCnv::fromCompact(), and DD4hep::Layering::sensitivePositionsInLayer().
string Component::materialStr () const
Access material attribute as STL string.
Definition at line 25 of file XMLDetector.cpp.
References _U, DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and DD4hep::XML::LayeringCnv::fromCompact().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLDetector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLDetector.cpp