DD4hep: DD4hep::CallbackSequence Struct Reference
DD4hep::CallbackSequence Struct Reference
DD4hep classes and objects
Definition of an actor on sequences of callbacks.
#include <Callback.h>
Public Types
enum Location { FRONT, END }
typedef std::vector< Callback > Callbacks
Public Member Functions
CallbackSequence ()
Default constructor.
CallbackSequence (const CallbackSequence &c)
Copy constructor.
CallbackSequence & operator= (const CallbackSequence &c)
Assignment operator.
bool empty () const
void clear ()
Clear the sequence and remove all callbacks.
void add (const Callback &cb, Location where)
Generically Add a new callback to the sequence depending on the location arguments.
void operator() () const
Execution overload for callbacks with no arguments.
template<typename A0 >
void operator() (A0 a0) const
Execution overload for callbacks with 1 argument.
template<typename A0 , typename A1 >
void operator() (A0 a0, A1 a1) const
Execution overload for callbacks with 2 arguments.
template<typename A0 , typename A1 , typename A2 >
void operator() (A0 a0, A1 a1, A2 a2) const
Execution overload for callbacks with 3 arguments.
template<typename TYPE , typename R , typename OBJECT >
void add (TYPE *pointer, R(OBJECT::*pmf)(), Location where=CallbackSequence::END)
Add a new callback to a member function with explicit return type and no arguments.
template<typename TYPE , typename R , typename OBJECT >
void add (TYPE *pointer, R(OBJECT::*pmf)() const, Location where=CallbackSequence::END)
Add a new callback to a const member function with explicit return type and no arguments.
template<typename TYPE , typename OBJECT >
void add (TYPE *pointer, void(OBJECT::*pmf)(), Location where=CallbackSequence::END)
Add a new callback to a void member function with no arguments.
template<typename TYPE , typename OBJECT >
void add (TYPE *pointer, void(OBJECT::*pmf)() const, Location where=CallbackSequence::END)
Add a new callback to a const void member function and no arguments.
template<typename TYPE , typename R , typename OBJECT , typename A >
void add (TYPE *pointer, R(OBJECT::*pmf)(A), Location where=CallbackSequence::END)
Add a new callback to a member function with explicit return type and 1 argument.
template<typename TYPE , typename OBJECT , typename A >
void add (TYPE *pointer, void(OBJECT::*pmf)(A), Location where=CallbackSequence::END)
Add a new callback to a void member function and 1 argument.
template<typename TYPE , typename R , typename OBJECT , typename A >
void add (TYPE *pointer, R(OBJECT::*pmf)(A) const, Location where=CallbackSequence::END)
Add a new callback to a const member function with explicit return type and 1 argument.
template<typename TYPE , typename OBJECT , typename A >
void add (TYPE *pointer, void(OBJECT::*pmf)(A) const, Location where=CallbackSequence::END)
Add a new callback to a const void member function and 1 argument.
template<typename TYPE , typename R , typename OBJECT , typename A1 , typename A2 >
void add (TYPE *pointer, R(OBJECT::*pmf)(A1, A2), Location where=CallbackSequence::END)
Add a new callback to a member function with explicit return type and 2 arguments.
template<typename TYPE , typename R , typename OBJECT , typename A1 , typename A2 >
void add (TYPE *pointer, R(OBJECT::*pmf)(A1, A2) const, Location where=CallbackSequence::END)
Add a new callback to a const member function with explicit return type and 2 arguments.
template<typename TYPE , typename OBJECT , typename A1 , typename A2 >
void add (TYPE *pointer, void(OBJECT::*pmf)(A1, A2), Location where=CallbackSequence::END)
Add a new callback to a void member function with 2 arguments.
template<typename TYPE , typename OBJECT , typename A1 , typename A2 >
void add (TYPE *pointer, void(OBJECT::*pmf)(A1, A2) const, Location where=CallbackSequence::END)
Add a new callback to a const void member function with 2 arguments.
Static Public Member Functions
static void checkTypes (const std::type_info &typ1, const std::type_info &typ2, void *test)
Check the compatibility of two typed objects. The test is the result of a dynamic_cast.
Public Attributes
Callbacks callbacks
Detailed Description
Definition of an actor on sequences of callbacks.
A callback sequence is a set of callbacks with identical signature, so that the can be called consecutively using the same arguments.
Author
M.Frank
Date
01/03/2013
Version
0.1
Definition at line 334 of file Callback.h.
Member Typedef Documentation
Callbacks
typedef std::vector<Callback> DD4hep::CallbackSequence::Callbacks
Definition at line 335 of file Callback.h.
Member Enumeration Documentation
Location
enum DD4hep::CallbackSequence::Location
Enumerator
FRONT
END
Definition at line 336 of file Callback.h.
Constructor & Destructor Documentation
CallbackSequence() [1/2]
DD4hep::CallbackSequence::CallbackSequence () inline
Default constructor.
Definition at line 339 of file Callback.h.
CallbackSequence() [2/2]
DD4hep::CallbackSequence::CallbackSequence (const CallbackSequence & c) inline
Copy constructor.
Definition at line 342 of file Callback.h.
Member Function Documentation
add() [1/13]
void DD4hep::CallbackSequence::add (const Callback & cb, Location where) inline
Generically Add a new callback to the sequence depending on the location arguments.
Definition at line 362 of file Callback.h.
References FRONT.
Referenced by DD4hep::Simulation::Geant4UserInitializationSequence::build(), DD4hep::Simulation::Geant4UserInitializationSequence::buildMaster(), DD4hep::Simulation::Geant4SteppingActionSequence::call(), DD4hep::Simulation::Geant4GeneratorActionSequence::call(), DD4hep::Simulation::Geant4RunActionSequence::callAtBegin(), DD4hep::Simulation::Geant4EventActionSequence::callAtBegin(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtBegin(), DD4hep::Simulation::Geant4SensDetActionSequence::callAtBegin(), DD4hep::Simulation::Geant4SensDetActionSequence::callAtClear(), DD4hep::Simulation::Geant4RunActionSequence::callAtEnd(), DD4hep::Simulation::Geant4EventActionSequence::callAtEnd(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtEnd(), DD4hep::Simulation::Geant4SensDetActionSequence::callAtEnd(), DD4hep::Simulation::Geant4EventActionSequence::callAtFinal(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtFinal(), DD4hep::Simulation::Geant4StackingActionSequence::callAtNewStage(), DD4hep::Simulation::Geant4StackingActionSequence::callAtPrepare(), DD4hep::Simulation::Geant4SensDetActionSequence::callAtProcess(), DD4hep::Simulation::Geant4TrackingActionSequence::callUpFront(), DD4hep::Simulation::Geant4PhysicsListActionSequence::constructParticle(), DD4hep::Simulation::Geant4PhysicsListActionSequence::constructPhysics(), and DD4hep::Simulation::Geant4PhysicsListActionSequence::constructProcess().
add() [2/13]
template<typename TYPE , typename R , typename OBJECT > void DD4hep::CallbackSequence::add (TYPE * pointer, R(OBJECT::*)() pmf, Location where = CallbackSequence::END) inline
Add a new callback to a member function with explicit return type and no arguments.
Callback setup for callbacks with no arguments
Definition at line 382 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [3/13]
template<typename TYPE , typename R , typename OBJECT > void DD4hep::CallbackSequence::add (TYPE * pointer, R(OBJECT::*)() const pmf, Location where = CallbackSequence::END) inline
Add a new callback to a const member function with explicit return type and no arguments.
Definition at line 388 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [4/13]
template<typename TYPE , typename OBJECT > void DD4hep::CallbackSequence::add (TYPE * pointer, void(OBJECT::*)() pmf, Location where = CallbackSequence::END) inline
Add a new callback to a void member function with no arguments.
Definition at line 394 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [5/13]
template<typename TYPE , typename OBJECT > void DD4hep::CallbackSequence::add (TYPE * pointer, void(OBJECT::*)() const pmf, Location where = CallbackSequence::END) inline
Add a new callback to a const void member function and no arguments.
Definition at line 400 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [6/13]
template<typename TYPE , typename R , typename OBJECT , typename A > void DD4hep::CallbackSequence::add (TYPE * pointer, R(OBJECT::*)(A) pmf, Location where = CallbackSequence::END) inline
Add a new callback to a member function with explicit return type and 1 argument.
Callback setup for callbacks with 1 argument
Definition at line 408 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [7/13]
template<typename TYPE , typename OBJECT , typename A > void DD4hep::CallbackSequence::add (TYPE * pointer, void(OBJECT::*)(A) pmf, Location where = CallbackSequence::END) inline
Add a new callback to a void member function and 1 argument.
Definition at line 414 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [8/13]
template<typename TYPE , typename R , typename OBJECT , typename A > void DD4hep::CallbackSequence::add (TYPE * pointer, R(OBJECT::*)(A) const pmf, Location where = CallbackSequence::END) inline
Add a new callback to a const member function with explicit return type and 1 argument.
Definition at line 420 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [9/13]
template<typename TYPE , typename OBJECT , typename A > void DD4hep::CallbackSequence::add (TYPE * pointer, void(OBJECT::*)(A) const pmf, Location where = CallbackSequence::END) inline
Add a new callback to a const void member function and 1 argument.
Definition at line 426 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [10/13]
template<typename TYPE , typename R , typename OBJECT , typename A1 , typename A2 > void DD4hep::CallbackSequence::add (TYPE * pointer, R(OBJECT::*)(A1, A2) pmf, Location where = CallbackSequence::END) inline
Add a new callback to a member function with explicit return type and 2 arguments.
Callback setup for callbacks with 2 arguments
Definition at line 435 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [11/13]
template<typename TYPE , typename R , typename OBJECT , typename A1 , typename A2 > void DD4hep::CallbackSequence::add (TYPE * pointer, R(OBJECT::*)(A1, A2) const pmf, Location where = CallbackSequence::END) inline
Add a new callback to a const member function with explicit return type and 2 arguments.
Definition at line 441 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [12/13]
template<typename TYPE , typename OBJECT , typename A1 , typename A2 > void DD4hep::CallbackSequence::add (TYPE * pointer, void(OBJECT::*)(A1, A2) pmf, Location where = CallbackSequence::END) inline
Add a new callback to a void member function with 2 arguments.
Definition at line 447 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
add() [13/13]
template<typename TYPE , typename OBJECT , typename A1 , typename A2 > void DD4hep::CallbackSequence::add (TYPE * pointer, void(OBJECT::*)(A1, A2) const pmf, Location where = CallbackSequence::END) inline
Add a new callback to a const void member function with 2 arguments.
Definition at line 453 of file Callback.h.
References DD4hep::Callback::Callback(), and DD4hep::Callback::make().
checkTypes()
void CallbackSequence::checkTypes (const std::type_info & typ1, const std::type_info & typ2, void * test) static
Check the compatibility of two typed objects. The test is the result of a dynamic_cast.
Definition at line 22 of file Callback.cpp.
Referenced by DD4hep::Simulation::Geant4UIMessenger::addCall(), DD4hep::Geometry::DetElement::addExtension(), and DD4hep::Geometry::DetElement::callAtUpdate().
clear()
void DD4hep::CallbackSequence::clear () inline
Clear the sequence and remove all callbacks.
Definition at line 358 of file Callback.h.
Referenced by DD4hep::Simulation::Geant4EventActionSequence::~Geant4EventActionSequence(), DD4hep::Simulation::Geant4GeneratorActionSequence::~Geant4GeneratorActionSequence(), DD4hep::Simulation::Geant4PhysicsListActionSequence::~Geant4PhysicsListActionSequence(), DD4hep::Simulation::Geant4RunActionSequence::~Geant4RunActionSequence(), DD4hep::Simulation::Geant4StackingActionSequence::~Geant4StackingActionSequence(), DD4hep::Simulation::Geant4SteppingActionSequence::~Geant4SteppingActionSequence(), DD4hep::Simulation::Geant4TrackingActionSequence::~Geant4TrackingActionSequence(), and DD4hep::Simulation::Geant4UserInitializationSequence::~Geant4UserInitializationSequence().
empty()
bool DD4hep::CallbackSequence::empty () const inline
Definition at line 354 of file Callback.h.
operator()() [1/4]
void DD4hep::CallbackSequence::operator() () const inline
Execution overload for callbacks with no arguments.
Definition at line 460 of file Callback.h.
operator()() [2/4]
template<typename A0 > void DD4hep::CallbackSequence::operator() (A0 a0) const inline
Execution overload for callbacks with 1 argument.
Definition at line 469 of file Callback.h.
operator()() [3/4]
template<typename A0 , typename A1 > void DD4hep::CallbackSequence::operator() (A0 a0, A1 a1) const inline
Execution overload for callbacks with 2 arguments.
Definition at line 478 of file Callback.h.
operator()() [4/4]
template<typename A0 , typename A1 , typename A2 > void DD4hep::CallbackSequence::operator() (A0 a0, A1 a1, A2 a2) const inline
Execution overload for callbacks with 3 arguments.
Definition at line 487 of file Callback.h.
operator=()
CallbackSequence& DD4hep::CallbackSequence::operator= (const CallbackSequence & c) inline
Assignment operator.
Definition at line 346 of file Callback.h.
References callbacks.
Member Data Documentation
callbacks
Callbacks DD4hep::CallbackSequence::callbacks
Definition at line 337 of file Callback.h.
Referenced by operator=().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Callback.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Callback.cpp