DD4hep: TiXmlCursor Class Reference
TiXmlCursor Class Reference
TinyXML class. See http://www.grinninglizard.com/tinyxml.
#include <tinyxml.h>
Public Member Functions
TiXmlCursor ()
void Clear ()
Public Attributes
int row
int col
Detailed Description
TinyXML class. See http://www.grinninglizard.com/tinyxml.
See
See also
http://www.grinninglizard.com/tinyxml
Definition at line 102 of file tinyxml.h.
Constructor & Destructor Documentation
TiXmlCursor()
TiXmlCursor::TiXmlCursor () inline
Definition at line 103 of file tinyxml.h.
References Clear().
Member Function Documentation
Clear()
void TiXmlCursor::Clear () inline
Definition at line 106 of file tinyxml.h.
References col, and row.
Referenced by TiXmlDocument::LoadFile(), TiXmlDocument::Parse(), TiXmlDocument::SetError(), TiXmlNode::SetValue(), and TiXmlCursor().
Member Data Documentation
col
int TiXmlCursor::col
Definition at line 111 of file tinyxml.h.
Referenced by Clear(), TiXmlBase::Column(), and TiXmlDocument::Parse().
row
int TiXmlCursor::row
Definition at line 110 of file tinyxml.h.
Referenced by Clear(), TiXmlDocument::Parse(), and TiXmlBase::Row().
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinyxml.h