DD4hep: DD4hep::XML::ChildValue Struct Reference
DD4hep::XML::ChildValue Struct Reference
DD4hep::XML classes and objects
XML Handle to xml elements with predefined child access.
#include <XMLChildValue.h>
Public Member Functions
ChildValue ()
Default constructor.
ChildValue (Handle_t e)
Constructor from Handle.
ChildValue (const Element &e)
Constructor from Element.
int id () const
Access parameters: id.
int id (int default_value) const
Access parameters: id, if not present returns default.
int type () const
Access parameters: type.
bool combineHits () const
Access rotation constants: combineHits.
double angle () const
Access rotation constants: angle.
double alpha () const
Access rotation constants: angle.
double beta () const
Access rotation constants: angle.
double gamma () const
Access rotation constants: angle.
double delta () const
Access rotation constants: angle.
double epsilon () const
Access rotation constants: angle.
double theta () const
Access rotation constants: theta.
int thetaBins () const
Access rotation constants: thetaBins.
double phi () const
Access rotation constants: phi.
int phiBins () const
Access rotation constants: phiBins.
double phi0 () const
Access rotation constants: phi0.
double phi0 (double default_value) const
Access parameters: phi0, if not present returns default.
double phi0_offset () const
Access rotation constants: phi0_offset.
double phi0_offset (double default_value) const
Access parameters: phi0_offset, if not present returns default.
double phi1 () const
Access rotation constants: phi1.
double phi1 (double default_value) const
Access parameters: phi1, if not present returns default.
double psi () const
Access rotation constants: psi.
double zhalf () const
Access Tube parameters: zhalf.
double deltaphi () const
Access Tube parameters: deltaphi.
double b () const
Access parameters: b.
double B () const
Access parameters: B.
double g () const
Access parameters: g.
double G () const
Access parameters: G.
double r () const
Access parameters: r.
double r (double default_value) const
Access parameters: r, if not present returns default.
double R () const
Access parameters: R.
double dr () const
Access parameters: dr.
double r0 () const
Access parameters: r0.
double dr (double default_value) const
Access parameters: dr, if not present returns default.
double rmin () const
Access min/max parameters: rmin.
double rmax () const
Access min/max parameters: rmax.
double rmin1 () const
Access min/max parameters: rmin1.
double rmax1 () const
Access min/max parameters: rmax1.
double rmin2 () const
Access min/max parameters: rmin2.
double rmax2 () const
Access min/max parameters: rmax2.
double radius () const
Access parameters: radius.
double distance () const
Access attribute values: distance.
double outer_radius () const
Access attribute values: outer_radius.
double outer_r () const
Access attribute values: outer_r.
double inner_radius () const
Access attribute values: inner_radius.
double inner_r () const
Access attribute values: inner_r.
double x () const
Access parameters: x.
double x (double default_val) const
Access parameters: x, if not present returns default.
double X () const
Access parameters: X.
double x0 () const
Access parameters: x0.
double x1 () const
Access parameters: x1.
double x2 () const
Access parameters: x2.
double dx () const
Access parameters: dx.
double dx (double default_value) const
Access parameters: dx, if not present returns default.
double xmin () const
Access min/max parameters: xmax.
double xmax () const
Access min/max parameters: xmax.
double x_offset () const
Access min/max parameters: x_offset.
double dim_x () const
Access min/max parameters: dim_x.
double y () const
Access parameters: y.
double y (double default_val) const
Access parameters: y, if not present returns default.
double Y () const
Access parameters: Y.
double y0 () const
Access parameters: y0.
double y1 () const
Access parameters: y1.
double y2 () const
Access parameters: y2.
double dy () const
Access parameters: dy.
double dy (double default_value) const
Access parameters: dz, if not present returns default.
double ymin () const
Access min/max parameters: ymax.
double ymax () const
Access min/max parameters: ymax.
double y_offset () const
Access min/max parameters: y_offset.
double dim_y () const
Access min/max parameters: dim_y.
double z () const
Access parameters: z.
double z (double default_val) const
Access parameters: z, if not present returns default.
double Z () const
Access parameters: Z.
double z0 () const
Access parameters: z0.
double z1 () const
Access parameters: z1.
double z2 () const
Access parameters: z2.
double dz () const
Access parameters: dz.
double dz (double default_value) const
Access parameters: dz, if not present returns default.
double zmin () const
Access min/max parameters: zmax.
double zmax () const
Access min/max parameters: zmax.
double outer_z () const
Access attribute values: outer_z.
double inner_z () const
Access attribute values: inner_z.
double z_offset () const
Access min/max parameters: z_offset.
double dim_z () const
Access min/max parameters: dim_z.
double length () const
Access attribute values: length.
double width () const
Access attribute values: width.
double height () const
Access attribute values: height.
double depth () const
Access attribute values: depth.
double thickness () const
Access attribute values: thickness.
double z_length () const
Access attribute values: z_length.
double gap () const
Access attribute values: gap.
double r_size () const
Access attribute values: r_size.
double phi_size_max () const
Access attribute values: phi_size_max.
bool reflect () const
Access attribute values: reflect.
bool reflect (bool default_value) const
Access attribute values: reflect.
double crossing_angle () const
Access attribute values: crossing_angle.
int repeat () const
Access attribute values: repeat.
double outgoing_r () const
Access attribute values: outgoing_r.
double incoming_r () const
Access attribute values: incoming_r.
double offset () const
Access attribute values: offset.
double offset (double default_value) const
Access attribute values: offset.
int number () const
Access attribute values: number.
int nmodules () const
Access attribute values: nmodules.
int nModules () const
Access attribute values: nModules.
int RowID () const
Access attribute values: RowID.
double moduleHeight () const
Access attribute values: moduleHeight.
double moduleWidth () const
Access attribute values: moduleWidth.
double modulePitch () const
Access attribute values: modulePitch.
double modulePosX () const
Access attribute values: modulePosX.
double modulePosY () const
Access attribute values: modulePosY.
int nPads () const
Access attribute values: nPads.
double rowPitch () const
Access attribute values: rowPitch.
double padPitch () const
Access attribute values: padPitch.
double rowHeight () const
Access attribute values: rowHeight.
std::string padType () const
Access attribute values: padType.
int numsides () const
Access attribute values: numsides.
int nsides () const
Access attribute values: nsides.
int nsides_inner () const
Access attribute values: nsides_inner.
int nsides_outer () const
Access attribute values: nsides_outer.
double phi_tilt () const
Access attribute values: phi_tilt.
int nphi () const
Access attribute values: nphi.
double rc () const
Access attribute values: rc.
double zstart () const
Access attribute values: zstart.
int nz () const
Access attribute values: nz.
double start () const
Access attribute values: start.
double end () const
Access attribute values: end.
double inner_field () const
Access attribute values: inner_field.
double outer_field () const
Access attribute values: outer_field.
bool visible () const
Access attribute values: visible.
bool show_daughters () const
Access attribute values: show_daughters.
std::string nameStr () const
Access "name" attribute as STL string.
std::string refStr () const
Access "ref" attribute as a string.
std::string typeStr () const
Access "type" attribute as STL string.
std::string valueStr () const
Access "value" attribute as STL string.
std::string moduleStr () const
Access "module" attribute as STL string.
std::string readoutStr () const
Access "readout" attribute as STL string.
std::string visStr () const
Access vis attribute as STL string. If not present empty return empty string.
std::string regionStr () const
Access region attribute as STL string. If not present empty return empty string.
std::string limitsStr () const
Access limits attribute as STL string. If not present empty return empty string.
Public Member Functions inherited from DD4hep::XML::Element
Element (const Handle_t &e)
Constructor from XmlElement handle.
Element (const Element &e)
Constructor from XmlElement handle.
Element (const Document &document, const XmlChar *type)
Constructor from DOM document entity.
Document document () const
Access the hosting document handle of this DOM element.
operator bool () const
operator bool: check handle validity
bool operator! () const
operator NOT: check handle validity
Element & operator= (const Element &c)
Assignment operator.
Element & operator= (Handle_t handle)
Assignment operator.
operator Handle_t () const
Automatic conversion to DOM element handle.
operator Elt_t () const
Automatic conversion to XmlElement pointer.
Elt_t ptr () const
Access to XmlElement pointer.
Handle_t parent () const
Access the XmlElements parent.
Elt_t parentElement () const
Access the XmlElements parent.
std::string tag () const
Access the tag name of this DOM element.
const XmlChar * tagName () const
Access the tag name of this DOM element.
void append (Handle_t handle) const
Append a new element to the existing tree.
Handle_t clone (const Document &new_doc) const
Clone the DOMelement.
bool hasAttr (const XmlChar *name) const
Check for the existence of a named attribute.
template<class T >
T attr (const XmlChar *tag_value) const
Access attribute with implicit return type conversion.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
const XmlChar * attr_name (const Attribute a) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute a) const
Access attribute value by the attribute (throws exception if not present)
size_t numChildren (const XmlChar *tag_value, bool exc=true) const
Access the number of children of this DOM element with a given tag name.
void setAttrs (Handle_t e) const
Remove own attributes and copy all attributes from handle 'e'.
void removeAttrs () const
Remove all attributes of this element.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
Attribute getAttr (const XmlChar *name) const
Access single attribute by it's name.
template<class T >
Attribute setAttr (const XmlChar *nam, const T &val) const
Set single attribute.
template<class T >
void setValue (const T &val) const
Set element value.
Handle_t clone (Handle_t h) const
Clone the DOM element tree.
Handle_t addChild (const XmlChar *tag) const
Add a new child to the DOM node.
Handle_t setChild (const XmlChar *tag) const
Check if a child with the required tag exists - if not create it and add it to the current node.
Handle_t child (const Strng_t &tag_value, bool except=true) const
Access child by tag name. Thow an exception if required in case the child is not present.
Handle_t remove (Handle_t node) const
Remove a child node identified by its handle.
bool hasChild (const XmlChar *tag_value) const
Check the existence of a child with a given tag name.
Attribute setRef (const XmlChar *tag, const XmlChar *refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Attribute setRef (const XmlChar *tag, const std::string &refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
const XmlChar * getRef (const XmlChar *tag) const
Access the value of the reference attribute of the node (attribute ref="ref-name")
void addComment (const char *text) const
Add comment node to the element.
Additional Inherited Members
Public Types inherited from DD4hep::XML::Element
typedef Handle_t::Elt_t Elt_t
Simplification type declarations.
Public Attributes inherited from DD4hep::XML::Element
Handle_t m_element
The underlying object holding the XmlElement pointer.
Detailed Description
XML Handle to xml elements with predefined child access.
Helper class to access any field in a xml tag in a very easy way.
You may assign any xml handle to a childvalue object
Any child with the name and the value attribute set may then be accessed by it's natural way. All possible child names are reflected by the object's member functions.
IMPORTANT NOTE: to be understood, the child elements MUST have structure like: <inner_r value="76*cm" ....other attributes...../> Other attributes may e.g. be a comment describing the variable. The 'other attributes' are ignored. The 'value' attribute is mandatory.
If an child is requested and not present, a exception is thrown.
Functions, which accept a default value do NOT throw an exception if the child is not present. These rather return the default value.
If a often used function is not present - the implementation thereof is simple.
Such helper classes may be defined locally by any user since XML element handles may easily be transferred. Run-time exceptions occur however, if non-exiting child elements are accessed.
Author
M.Frank
Version
1.0
Definition at line 60 of file XMLChildValue.h.
Constructor & Destructor Documentation
ChildValue() [1/3]
DD4hep::XML::ChildValue::ChildValue () inline
Default constructor.
Definition at line 62 of file XMLChildValue.h.
ChildValue() [2/3]
DD4hep::XML::ChildValue::ChildValue (Handle_t e) inline
Constructor from Handle.
Definition at line 66 of file XMLChildValue.h.
ChildValue() [3/3]
DD4hep::XML::ChildValue::ChildValue (const Element & e) inline
Constructor from Element.
Definition at line 70 of file XMLChildValue.h.
References alpha(), angle(), b(), B(), beta(), combineHits(), crossing_angle(), delta(), deltaphi(), depth(), dim_x(), dim_y(), dim_z(), distance(), dr(), dx(), dy(), dz(), end(), epsilon(), g(), G(), gamma(), gap(), height(), id(), incoming_r(), inner_field(), inner_r(), inner_radius(), inner_z(), length(), limitsStr(), moduleHeight(), modulePitch(), modulePosX(), modulePosY(), moduleStr(), moduleWidth(), nameStr(), nmodules(), nModules(), nPads(), nphi(), nsides(), nsides_inner(), nsides_outer(), number(), numsides(), nz(), offset(), outer_field(), outer_r(), outer_radius(), outer_z(), outgoing_r(), padPitch(), padType(), phi(), phi0(), phi0_offset(), phi1(), phi_size_max(), phi_tilt(), phiBins(), psi(), r(), R(), r0(), r_size(), radius(), rc(), readoutStr(), reflect(), refStr(), regionStr(), repeat(), rmax(), rmax1(), rmax2(), rmin(), rmin1(), rmin2(), rowHeight(), RowID(), rowPitch(), show_daughters(), start(), theta(), thetaBins(), thickness(), type(), typeStr(), valueStr(), visible(), visStr(), width(), x(), X(), x0(), x1(), x2(), x_offset(), xmax(), xmin(), y(), Y(), y0(), y1(), y2(), y_offset(), ymax(), ymin(), z(), Z(), z0(), z1(), z2(), z_length(), z_offset(), zhalf(), zmax(), zmin(), and zstart().
Member Function Documentation
alpha()
double DD4hep::XML::ChildValue::alpha () const
Access rotation constants: angle.
Referenced by ChildValue().
angle()
double DD4hep::XML::ChildValue::angle () const
Access rotation constants: angle.
Referenced by ChildValue().
b()
double DD4hep::XML::ChildValue::b () const
Access parameters: b.
Referenced by ChildValue().
B()
double DD4hep::XML::ChildValue::B () const
Access parameters: B.
Referenced by ChildValue().
beta()
double DD4hep::XML::ChildValue::beta () const
Access rotation constants: angle.
Referenced by ChildValue().
combineHits()
bool DD4hep::XML::ChildValue::combineHits () const
Access rotation constants: combineHits.
Referenced by ChildValue().
crossing_angle()
double DD4hep::XML::ChildValue::crossing_angle () const
Access attribute values: crossing_angle.
Referenced by ChildValue().
delta()
double DD4hep::XML::ChildValue::delta () const
Access rotation constants: angle.
Referenced by ChildValue().
deltaphi()
double DD4hep::XML::ChildValue::deltaphi () const
Access Tube parameters: deltaphi.
Referenced by ChildValue().
depth()
double DD4hep::XML::ChildValue::depth () const
Access attribute values: depth.
Referenced by ChildValue().
dim_x()
double DD4hep::XML::ChildValue::dim_x () const
Access min/max parameters: dim_x.
Referenced by ChildValue().
dim_y()
double DD4hep::XML::ChildValue::dim_y () const
Access min/max parameters: dim_y.
Referenced by ChildValue().
dim_z()
double DD4hep::XML::ChildValue::dim_z () const
Access min/max parameters: dim_z.
Referenced by ChildValue().
distance()
double DD4hep::XML::ChildValue::distance () const
Access attribute values: distance.
Referenced by ChildValue().
dr() [1/2]
double DD4hep::XML::ChildValue::dr () const
Access parameters: dr.
Referenced by ChildValue().
dr() [2/2]
double DD4hep::XML::ChildValue::dr (double default_value) const
Access parameters: dr, if not present returns default.
dx() [1/2]
double DD4hep::XML::ChildValue::dx () const
Access parameters: dx.
Referenced by ChildValue().
dx() [2/2]
double DD4hep::XML::ChildValue::dx (double default_value) const
Access parameters: dx, if not present returns default.
dy() [1/2]
double DD4hep::XML::ChildValue::dy () const
Access parameters: dy.
Referenced by ChildValue().
dy() [2/2]
double DD4hep::XML::ChildValue::dy (double default_value) const
Access parameters: dz, if not present returns default.
dz() [1/2]
double DD4hep::XML::ChildValue::dz () const
Access parameters: dz.
Referenced by ChildValue().
dz() [2/2]
double DD4hep::XML::ChildValue::dz (double default_value) const
Access parameters: dz, if not present returns default.
end()
double DD4hep::XML::ChildValue::end () const
Access attribute values: end.
Referenced by ChildValue().
epsilon()
double DD4hep::XML::ChildValue::epsilon () const
Access rotation constants: angle.
Referenced by ChildValue().
g()
double DD4hep::XML::ChildValue::g () const
Access parameters: g.
Referenced by ChildValue().
G()
double DD4hep::XML::ChildValue::G () const
Access parameters: G.
Referenced by ChildValue().
gamma()
double DD4hep::XML::ChildValue::gamma () const
Access rotation constants: angle.
Referenced by ChildValue().
gap()
double DD4hep::XML::ChildValue::gap () const
Access attribute values: gap.
Referenced by ChildValue().
height()
double DD4hep::XML::ChildValue::height () const
Access attribute values: height.
Referenced by ChildValue().
id() [1/2]
int DD4hep::XML::ChildValue::id () const
Access parameters: id.
Referenced by ChildValue().
id() [2/2]
int DD4hep::XML::ChildValue::id (int default_value) const
Access parameters: id, if not present returns default.
incoming_r()
double DD4hep::XML::ChildValue::incoming_r () const
Access attribute values: incoming_r.
Referenced by ChildValue().
inner_field()
double DD4hep::XML::ChildValue::inner_field () const
Access attribute values: inner_field.
Referenced by ChildValue().
inner_r()
double DD4hep::XML::ChildValue::inner_r () const
Access attribute values: inner_r.
Referenced by ChildValue().
inner_radius()
double DD4hep::XML::ChildValue::inner_radius () const
Access attribute values: inner_radius.
Referenced by ChildValue().
inner_z()
double DD4hep::XML::ChildValue::inner_z () const
Access attribute values: inner_z.
Referenced by ChildValue().
length()
double DD4hep::XML::ChildValue::length () const
Access attribute values: length.
Referenced by ChildValue().
limitsStr()
string ChildValue::limitsStr () const
Access limits attribute as STL string. If not present empty return empty string.
Definition at line 208 of file XMLChildValue.cpp.
References childValueDefault.
Referenced by ChildValue().
moduleHeight()
double DD4hep::XML::ChildValue::moduleHeight () const
Access attribute values: moduleHeight.
Referenced by ChildValue().
modulePitch()
double DD4hep::XML::ChildValue::modulePitch () const
Access attribute values: modulePitch.
Referenced by ChildValue().
modulePosX()
double DD4hep::XML::ChildValue::modulePosX () const
Access attribute values: modulePosX.
Referenced by ChildValue().
modulePosY()
double DD4hep::XML::ChildValue::modulePosY () const
Access attribute values: modulePosY.
Referenced by ChildValue().
moduleStr()
string ChildValue::moduleStr () const
Access "module" attribute as STL string.
Definition at line 220 of file XMLChildValue.cpp.
References childValueDefault.
Referenced by ChildValue().
moduleWidth()
double DD4hep::XML::ChildValue::moduleWidth () const
Access attribute values: moduleWidth.
Referenced by ChildValue().
nameStr()
string ChildValue::nameStr () const
Access "name" attribute as STL string.
Definition at line 187 of file XMLChildValue.cpp.
References childValue.
Referenced by ChildValue().
nmodules()
int DD4hep::XML::ChildValue::nmodules () const
Access attribute values: nmodules.
Referenced by ChildValue().
nModules()
int DD4hep::XML::ChildValue::nModules () const
Access attribute values: nModules.
Referenced by ChildValue().
nPads()
int DD4hep::XML::ChildValue::nPads () const
Access attribute values: nPads.
Referenced by ChildValue().
nphi()
int DD4hep::XML::ChildValue::nphi () const
Access attribute values: nphi.
Referenced by ChildValue().
nsides()
int DD4hep::XML::ChildValue::nsides () const
Access attribute values: nsides.
Referenced by ChildValue().
nsides_inner()
int DD4hep::XML::ChildValue::nsides_inner () const
Access attribute values: nsides_inner.
Referenced by ChildValue().
nsides_outer()
int DD4hep::XML::ChildValue::nsides_outer () const
Access attribute values: nsides_outer.
Referenced by ChildValue().
number()
int DD4hep::XML::ChildValue::number () const
Access attribute values: number.
Referenced by ChildValue().
numsides()
int DD4hep::XML::ChildValue::numsides () const
Access attribute values: numsides.
Referenced by ChildValue().
nz()
int DD4hep::XML::ChildValue::nz () const
Access attribute values: nz.
Referenced by ChildValue().
offset() [1/2]
double DD4hep::XML::ChildValue::offset () const
Access attribute values: offset.
Referenced by ChildValue().
offset() [2/2]
double DD4hep::XML::ChildValue::offset (double default_value) const
Access attribute values: offset.
outer_field()
double DD4hep::XML::ChildValue::outer_field () const
Access attribute values: outer_field.
Referenced by ChildValue().
outer_r()
double DD4hep::XML::ChildValue::outer_r () const
Access attribute values: outer_r.
Referenced by ChildValue().
outer_radius()
double DD4hep::XML::ChildValue::outer_radius () const
Access attribute values: outer_radius.
Referenced by ChildValue().
outer_z()
double DD4hep::XML::ChildValue::outer_z () const
Access attribute values: outer_z.
Referenced by ChildValue().
outgoing_r()
double DD4hep::XML::ChildValue::outgoing_r () const
Access attribute values: outgoing_r.
Referenced by ChildValue().
padPitch()
double DD4hep::XML::ChildValue::padPitch () const
Access attribute values: padPitch.
Referenced by ChildValue().
padType()
string ChildValue::padType () const
Access attribute values: padType.
Definition at line 183 of file XMLChildValue.cpp.
References childValue.
Referenced by ChildValue().
phi()
double DD4hep::XML::ChildValue::phi () const
Access rotation constants: phi.
Referenced by ChildValue().
phi0() [1/2]
double DD4hep::XML::ChildValue::phi0 () const
Access rotation constants: phi0.
Referenced by ChildValue().
phi0() [2/2]
double DD4hep::XML::ChildValue::phi0 (double default_value) const
Access parameters: phi0, if not present returns default.
phi0_offset() [1/2]
double DD4hep::XML::ChildValue::phi0_offset () const
Access rotation constants: phi0_offset.
Referenced by ChildValue().
phi0_offset() [2/2]
double DD4hep::XML::ChildValue::phi0_offset (double default_value) const
Access parameters: phi0_offset, if not present returns default.
phi1() [1/2]
double DD4hep::XML::ChildValue::phi1 () const
Access rotation constants: phi1.
Referenced by ChildValue().
phi1() [2/2]
double DD4hep::XML::ChildValue::phi1 (double default_value) const
Access parameters: phi1, if not present returns default.
phi_size_max()
double DD4hep::XML::ChildValue::phi_size_max () const
Access attribute values: phi_size_max.
Referenced by ChildValue().
phi_tilt()
double DD4hep::XML::ChildValue::phi_tilt () const
Access attribute values: phi_tilt.
Referenced by ChildValue().
phiBins()
int DD4hep::XML::ChildValue::phiBins () const
Access rotation constants: phiBins.
Referenced by ChildValue().
psi()
double DD4hep::XML::ChildValue::psi () const
Access rotation constants: psi.
Referenced by ChildValue().
r() [1/2]
double DD4hep::XML::ChildValue::r () const
Access parameters: r.
Referenced by ChildValue().
r() [2/2]
double DD4hep::XML::ChildValue::r (double default_value) const
Access parameters: r, if not present returns default.
R()
double DD4hep::XML::ChildValue::R () const
Access parameters: R.
Referenced by ChildValue().
r0()
double DD4hep::XML::ChildValue::r0 () const
Access parameters: r0.
Referenced by ChildValue().
r_size()
double DD4hep::XML::ChildValue::r_size () const
Access attribute values: r_size.
Referenced by ChildValue().
radius()
double DD4hep::XML::ChildValue::radius () const
Access parameters: radius.
Referenced by ChildValue().
rc()
double DD4hep::XML::ChildValue::rc () const
Access attribute values: rc.
Referenced by ChildValue().
readoutStr()
string ChildValue::readoutStr () const
Access "readout" attribute as STL string.
Definition at line 216 of file XMLChildValue.cpp.
References childValueDefault.
Referenced by ChildValue().
reflect() [1/2]
bool DD4hep::XML::ChildValue::reflect () const
Access attribute values: reflect.
Referenced by ChildValue().
reflect() [2/2]
bool DD4hep::XML::ChildValue::reflect (bool default_value) const
Access attribute values: reflect.
refStr()
string ChildValue::refStr () const
Access "ref" attribute as a string.
Definition at line 191 of file XMLChildValue.cpp.
References childValue.
Referenced by ChildValue().
regionStr()
string ChildValue::regionStr () const
Access region attribute as STL string. If not present empty return empty string.
Definition at line 204 of file XMLChildValue.cpp.
References childValueDefault.
Referenced by ChildValue().
repeat()
int DD4hep::XML::ChildValue::repeat () const
Access attribute values: repeat.
Referenced by ChildValue().
rmax()
double DD4hep::XML::ChildValue::rmax () const
Access min/max parameters: rmax.
Referenced by ChildValue().
rmax1()
double DD4hep::XML::ChildValue::rmax1 () const
Access min/max parameters: rmax1.
Referenced by ChildValue().
rmax2()
double DD4hep::XML::ChildValue::rmax2 () const
Access min/max parameters: rmax2.
Referenced by ChildValue().
rmin()
double DD4hep::XML::ChildValue::rmin () const
Access min/max parameters: rmin.
Referenced by ChildValue().
rmin1()
double DD4hep::XML::ChildValue::rmin1 () const
Access min/max parameters: rmin1.
Referenced by ChildValue().
rmin2()
double DD4hep::XML::ChildValue::rmin2 () const
Access min/max parameters: rmin2.
Referenced by ChildValue().
rowHeight()
double DD4hep::XML::ChildValue::rowHeight () const
Access attribute values: rowHeight.
Referenced by ChildValue().
RowID()
int DD4hep::XML::ChildValue::RowID () const
Access attribute values: RowID.
Referenced by ChildValue().
rowPitch()
double DD4hep::XML::ChildValue::rowPitch () const
Access attribute values: rowPitch.
Referenced by ChildValue().
show_daughters()
bool DD4hep::XML::ChildValue::show_daughters () const
Access attribute values: show_daughters.
Referenced by ChildValue().
start()
double DD4hep::XML::ChildValue::start () const
Access attribute values: start.
Referenced by ChildValue().
theta()
double DD4hep::XML::ChildValue::theta () const
Access rotation constants: theta.
Referenced by ChildValue().
thetaBins()
int DD4hep::XML::ChildValue::thetaBins () const
Access rotation constants: thetaBins.
Referenced by ChildValue().
thickness()
double DD4hep::XML::ChildValue::thickness () const
Access attribute values: thickness.
Referenced by ChildValue().
type()
int DD4hep::XML::ChildValue::type () const
Access parameters: type.
Referenced by ChildValue().
typeStr()
string ChildValue::typeStr () const
Access "type" attribute as STL string.
Definition at line 195 of file XMLChildValue.cpp.
References childValue, and TiXmlNode::type.
Referenced by ChildValue().
valueStr()
std::string ChildValue::valueStr () const
Access "value" attribute as STL string.
Definition at line 200 of file XMLChildValue.cpp.
References childValue, and TiXmlNode::value.
Referenced by ChildValue().
visible()
bool DD4hep::XML::ChildValue::visible () const
Access attribute values: visible.
Referenced by ChildValue().
visStr()
string ChildValue::visStr () const
Access vis attribute as STL string. If not present empty return empty string.
Definition at line 212 of file XMLChildValue.cpp.
References childValueDefault.
Referenced by ChildValue().
width()
double DD4hep::XML::ChildValue::width () const
Access attribute values: width.
Referenced by ChildValue().
x() [1/2]
double DD4hep::XML::ChildValue::x () const
Access parameters: x.
Referenced by ChildValue().
x() [2/2]
double DD4hep::XML::ChildValue::x (double default_val) const
Access parameters: x, if not present returns default.
X()
double DD4hep::XML::ChildValue::X () const
Access parameters: X.
Referenced by ChildValue().
x0()
double DD4hep::XML::ChildValue::x0 () const
Access parameters: x0.
Referenced by ChildValue().
x1()
double DD4hep::XML::ChildValue::x1 () const
Access parameters: x1.
Referenced by ChildValue().
x2()
double DD4hep::XML::ChildValue::x2 () const
Access parameters: x2.
Referenced by ChildValue().
x_offset()
double DD4hep::XML::ChildValue::x_offset () const
Access min/max parameters: x_offset.
Referenced by ChildValue().
xmax()
double DD4hep::XML::ChildValue::xmax () const
Access min/max parameters: xmax.
Referenced by ChildValue().
xmin()
double DD4hep::XML::ChildValue::xmin () const
Access min/max parameters: xmax.
Referenced by ChildValue().
y() [1/2]
double DD4hep::XML::ChildValue::y () const
Access parameters: y.
Referenced by ChildValue().
y() [2/2]
double DD4hep::XML::ChildValue::y (double default_val) const
Access parameters: y, if not present returns default.
Y()
double DD4hep::XML::ChildValue::Y () const
Access parameters: Y.
Referenced by ChildValue().
y0()
double DD4hep::XML::ChildValue::y0 () const
Access parameters: y0.
Referenced by ChildValue().
y1()
double DD4hep::XML::ChildValue::y1 () const
Access parameters: y1.
Referenced by ChildValue().
y2()
double DD4hep::XML::ChildValue::y2 () const
Access parameters: y2.
Referenced by ChildValue().
y_offset()
double DD4hep::XML::ChildValue::y_offset () const
Access min/max parameters: y_offset.
Referenced by ChildValue().
ymax()
double DD4hep::XML::ChildValue::ymax () const
Access min/max parameters: ymax.
Referenced by ChildValue().
ymin()
double DD4hep::XML::ChildValue::ymin () const
Access min/max parameters: ymax.
Referenced by ChildValue().
z() [1/2]
double DD4hep::XML::ChildValue::z () const
Access parameters: z.
Referenced by ChildValue().
z() [2/2]
double DD4hep::XML::ChildValue::z (double default_val) const
Access parameters: z, if not present returns default.
Z()
double DD4hep::XML::ChildValue::Z () const
Access parameters: Z.
Referenced by ChildValue().
z0()
double DD4hep::XML::ChildValue::z0 () const
Access parameters: z0.
Referenced by ChildValue().
z1()
double DD4hep::XML::ChildValue::z1 () const
Access parameters: z1.
Referenced by ChildValue().
z2()
double DD4hep::XML::ChildValue::z2 () const
Access parameters: z2.
Referenced by ChildValue().
z_length()
double DD4hep::XML::ChildValue::z_length () const
Access attribute values: z_length.
Referenced by ChildValue().
z_offset()
double DD4hep::XML::ChildValue::z_offset () const
Access min/max parameters: z_offset.
Referenced by ChildValue().
zhalf()
double DD4hep::XML::ChildValue::zhalf () const
Access Tube parameters: zhalf.
Referenced by ChildValue().
zmax()
double DD4hep::XML::ChildValue::zmax () const
Access min/max parameters: zmax.
Referenced by ChildValue().
zmin()
double DD4hep::XML::ChildValue::zmin () const
Access min/max parameters: zmax.
Referenced by ChildValue().
zstart()
double DD4hep::XML::ChildValue::zstart () const
Access attribute values: zstart.
Referenced by ChildValue().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLChildValue.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLChildValue.cpp