DD4hep: DD4hep::InstanceCount Struct Reference
DD4hep::InstanceCount Struct Reference
DD4hep classes and objects
Helper to support object counting when debugging memory leaks.
#include <InstanceCount.h>
Classes
class Counter
Internal class to could object constructions and destructions.
Public Types
enum { NONE = 1 << 0, STRING = 1 << 1, TYPEINFO = 1 << 2, ALL = STRING | TYPEINFO }
Enumeration to steer the output.
typedef long long int counter_t
Public Member Functions
InstanceCount ()
Standard Constructor - No need to call explicitly.
virtual ~InstanceCount ()
Standard Destructor - No need to call explicitly.
Static Public Member Functions
static Counter * getCounter (const std::type_info &typ)
Access counter object for local caching on optimizations.
static Counter * getCounter (const std::string &typ)
Access counter object for local caching on optimizations.
template<class T >
static void increment (T *)
Increment count according to type information.
template<class T >
static void decrement (T *)
Decrement count according to type information.
template<class T >
static counter_t get (T *)
Access current counter.
static void increment (const std::type_info &typ)
Increment count according to type information.
static void decrement (const std::type_info &typ)
Decrement count according to type information.
static counter_t get (const std::type_info &typ)
Access current counter.
static void increment (const std::string &typ)
Increment count according to string information.
static void decrement (const std::string &typ)
Decrement count according to string information.
static counter_t get (const std::string &typ)
Access current counter.
static void dump (int which=ALL)
Dump list of instance counters.
static void clear (int which=ALL)
Clear list of instance counters.
static bool doTrace ()
Check if tracing is enabled.
static void doTracing (bool value)
Enable/Disable tracing.
Detailed Description
Helper to support object counting when debugging memory leaks.
Small class to enable object construction/destruction tracing
Author
M.Frank
Version
1.0
Definition at line 31 of file InstanceCount.h.
Member Typedef Documentation
counter_t
typedef long long int DD4hep::InstanceCount::counter_t
Definition at line 33 of file InstanceCount.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumeration to steer the output.
Enumerator
NONE
STRING
TYPEINFO
ALL
Definition at line 35 of file InstanceCount.h.
Constructor & Destructor Documentation
InstanceCount()
InstanceCount::InstanceCount ()
Standard Constructor - No need to call explicitly.
Standard Constructor.
Definition at line 63 of file InstanceCount.cpp.
References DD4hep::InstanceCount::Counter::increment().
Referenced by DD4hep::InstanceCount::Counter::maximum().
~InstanceCount()
InstanceCount::~InstanceCount () virtual
Standard Destructor - No need to call explicitly.
Standard destructor.
Definition at line 67 of file InstanceCount.cpp.
References DD4hep::InstanceCount::Counter::decrement(), and DD4hep::InstanceCount::Counter::value().
Referenced by DD4hep::InstanceCount::Counter::maximum().
Member Function Documentation
clear()
static void DD4hep::InstanceCount::clear (int which = ALL) static
Clear list of instance counters.
Referenced by get().
decrement() [1/3]
template<class T > static void DD4hep::InstanceCount::decrement (T *) inline static
Decrement count according to type information.
Definition at line 104 of file InstanceCount.h.
References DD4hep::InstanceCount::Counter::decrement().
Referenced by DD4hep::Simulation::RefCountedSequence< Geant4SensDetActionSequence >::_release(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::_release(), DD4hep::Conditions::AbstractMap::~AbstractMap(), DD4hep::Alignments::AlignContext::~AlignContext(), DD4hep::Alignments::Interna::AlignmentConditionObject::~AlignmentConditionObject(), DD4hep::Alignments::Interna::AlignmentContainer::~AlignmentContainer(), DD4hep::Alignments::AlignmentData::~AlignmentData(), DD4hep::Alignments::AlignmentsManagerObject::~AlignmentsManagerObject(), DD4hep::Alignments::AlignmentStack::~AlignmentStack(), DD4hep::Annotation::~Annotation(), DD4hep::Calo3DProjection::~Calo3DProjection(), DD4hep::Conditions::Interna::ConditionContainer::~ConditionContainer(), DD4hep::Conditions::ConditionDependency::~ConditionDependency(), DD4hep::Conditions::Interna::ConditionObject::~ConditionObject(), DD4hep::Conditions::ConditionsIOVPool::~ConditionsIOVPool(), DD4hep::Conditions::ConditionsManagerObject::~ConditionsManagerObject(), DD4hep::Conditions::ConditionsPool::~ConditionsPool(), DD4hep::Geometry::ConstantObject::~ConstantObject(), DD4hep::Geometry::DetElementObject::~DetElementObject(), DD4hep::ElementList::~ElementList(), DD4hep::Simulation::EnergyDepositMinimumCut::~EnergyDepositMinimumCut(), DD4hep::Conditions::Entry::~Entry(), DD4hep::Simulation::Geant4ActionContainer::~Geant4ActionContainer(), DD4hep::Simulation::Geant4ActionPhase::~Geant4ActionPhase(), DD4hep::Simulation::Geant4ActionSD::~Geant4ActionSD(), DD4hep::Simulation::Geant4Context::~Geant4Context(), DD4hep::Simulation::Geant4DetectorConstructionSequence::~Geant4DetectorConstructionSequence(), DD4hep::Simulation::Geant4DetectorGeometryConstruction::~Geant4DetectorGeometryConstruction(), DD4hep::Simulation::Geant4DetectorSensitivesConstruction::~Geant4DetectorSensitivesConstruction(), DD4hep::Simulation::Geant4EscapeCounter::~Geant4EscapeCounter(), DD4hep::Simulation::Geant4Event::~Geant4Event(), DD4hep::Simulation::Geant4EventAction::~Geant4EventAction(), DD4hep::Simulation::Geant4EventActionSequence::~Geant4EventActionSequence(), DD4hep::Simulation::Geant4EventSeed::~Geant4EventSeed(), DD4hep::Simulation::Geant4Filter::~Geant4Filter(), DD4hep::Simulation::Geant4GeneratorAction::~Geant4GeneratorAction(), DD4hep::Simulation::Geant4GeneratorActionInit::~Geant4GeneratorActionInit(), DD4hep::Simulation::Geant4GeneratorActionSequence::~Geant4GeneratorActionSequence(), DD4hep::Simulation::Geant4GeneratorWrapper::~Geant4GeneratorWrapper(), DD4hep::Simulation::Geant4HitCollection::~Geant4HitCollection(), DD4hep::Simulation::Geant4HitData::~Geant4HitData(), DD4hep::Simulation::Geant4InteractionMerger::~Geant4InteractionMerger(), DD4hep::Simulation::Geant4InteractionVertexBoost::~Geant4InteractionVertexBoost(), DD4hep::Simulation::Geant4InteractionVertexSmear::~Geant4InteractionVertexSmear(), DD4hep::Simulation::Geant4IsotropeGenerator::~Geant4IsotropeGenerator(), DD4hep::Simulation::Geant4Kernel::~Geant4Kernel(), DD4hep::Simulation::Geant4MaterialScanner::~Geant4MaterialScanner(), DD4hep::Simulation::Geant4MonteCarloTruth::~Geant4MonteCarloTruth(), DD4hep::Simulation::Geant4Output2ROOT::~Geant4Output2ROOT(), DD4hep::Simulation::Geant4OutputAction::~Geant4OutputAction(), DD4hep::Simulation::Geant4Particle::~Geant4Particle(), DD4hep::Simulation::Geant4ParticleGenerator::~Geant4ParticleGenerator(), DD4hep::Simulation::Geant4ParticleGun::~Geant4ParticleGun(), DD4hep::Simulation::Geant4ParticleHandler::~Geant4ParticleHandler(), DD4hep::Simulation::Geant4ParticlePrint::~Geant4ParticlePrint(), DD4hep::Simulation::Geant4PhysicsConstructor::~Geant4PhysicsConstructor(), DD4hep::Simulation::Geant4PhysicsList::~Geant4PhysicsList(), DD4hep::Simulation::Geant4PhysicsListActionSequence::~Geant4PhysicsListActionSequence(), DD4hep::Simulation::Geant4PrimaryHandler::~Geant4PrimaryHandler(), DD4hep::Simulation::Geant4Random::~Geant4Random(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::~Geant4ReadoutVolumeFilter(), DD4hep::Simulation::Geant4Run::~Geant4Run(), DD4hep::Simulation::Geant4RunAction::~Geant4RunAction(), DD4hep::Simulation::Geant4RunActionSequence::~Geant4RunActionSequence(), DD4hep::Simulation::Geant4SensDetActionSequence::~Geant4SensDetActionSequence(), DD4hep::Simulation::Geant4Sensitive::~Geant4Sensitive(), Tests::Geant4SensitiveAction< T >::~Geant4SensitiveAction(), DD4hep::Simulation::Geant4SensitiveAction< T >::~Geant4SensitiveAction(), DD4hep::Simulation::Geant4SharedEventAction::~Geant4SharedEventAction(), DD4hep::Simulation::Geant4SharedGeneratorAction::~Geant4SharedGeneratorAction(), DD4hep::Simulation::Geant4SharedRunAction::~Geant4SharedRunAction(), DD4hep::Simulation::Geant4SharedStackingAction::~Geant4SharedStackingAction(), DD4hep::Simulation::Geant4SharedSteppingAction::~Geant4SharedSteppingAction(), DD4hep::Simulation::Geant4SharedTrackingAction::~Geant4SharedTrackingAction(), DD4hep::Simulation::Geant4StackingAction::~Geant4StackingAction(), DD4hep::Simulation::Geant4StackingActionSequence::~Geant4StackingActionSequence(), DD4hep::Simulation::Geant4SteppingAction::~Geant4SteppingAction(), DD4hep::Simulation::Geant4SteppingActionSequence::~Geant4SteppingActionSequence(), DD4hep::Simulation::Test::Geant4TestBase::~Geant4TestBase(), DD4hep::Simulation::Test::Geant4TestEventAction::~Geant4TestEventAction(), DD4hep::Simulation::Test::Geant4TestGeneratorAction::~Geant4TestGeneratorAction(), DD4hep::Simulation::Test::Geant4TestRunAction::~Geant4TestRunAction(), DD4hep::Simulation::Test::Geant4TestSensitive::~Geant4TestSensitive(), DD4hep::Simulation::Test::Geant4TestStepAction::~Geant4TestStepAction(), DD4hep::Simulation::Test::Geant4TestTrackAction::~Geant4TestTrackAction(), DD4hep::Simulation::Geant4TrackingAction::~Geant4TrackingAction(), DD4hep::Simulation::Geant4TrackingActionSequence::~Geant4TrackingActionSequence(), DD4hep::Simulation::Geant4TrackingPostAction::~Geant4TrackingPostAction(), DD4hep::Simulation::Geant4TrackingPreAction::~Geant4TrackingPreAction(), DD4hep::Simulation::Geant4UserInitialization::~Geant4UserInitialization(), DD4hep::Simulation::Geant4UserInitializationSequence::~Geant4UserInitializationSequence(), DD4hep::Simulation::Geant4UserParticleHandler::~Geant4UserParticleHandler(), DD4hep::Simulation::Geant4Vertex::~Geant4Vertex(), DD4hep::Simulation::GeantinoRejectFilter::~GeantinoRejectFilter(), DD4hep::Geometry::HeaderObject::~HeaderObject(), DD4hep::Simulation::Geant4Tracker::Hit::~Hit(), DD4hep::Simulation::Geant4Calorimeter::Hit::~Hit(), DD4hep::Simulation::Geant4HitWrapper::HitManipulator::~HitManipulator(), DD4hep::Geometry::IDDescriptorObject::~IDDescriptorObject(), DD4hep::Geometry::LCDDData::~LCDDData(), DD4hep::Geometry::LCDDImp::~LCDDImp(), DD4hep::Geometry::LimitSetObject::~LimitSetObject(), DD4hep::Geometry::CartesianField::Object::~Object(), DD4hep::Geometry::OverlayedField::Object::~Object(), DD4hep::ObjectExtensions::~ObjectExtensions(), DD4hep::OpaqueDataBlock::~OpaqueDataBlock(), DD4hep::Simulation::ParticleFilter::~ParticleFilter(), DD4hep::Simulation::ParticleRejectFilter::~ParticleRejectFilter(), DD4hep::Simulation::ParticleSelectFilter::~ParticleSelectFilter(), DD4hep::PopupMenu::~PopupMenu(), DD4hep::Geometry::ReadoutObject::~ReadoutObject(), DD4hep::Geometry::RegionObject::~RegionObject(), DD4hep::Geometry::SegmentationObject::~SegmentationObject(), DD4hep::Geometry::SensitiveDetectorObject::~SensitiveDetectorObject(), DD4hep::Simulation::SimpleEvent::~SimpleEvent(), DD4hep::Simulation::SimpleRun::~SimpleRun(), DD4hep::Alignments::AlignmentStack::StackEntry::~StackEntry(), DD4hep::Conditions::UserPool::~UserPool(), DD4hep::View::~View(), and DD4hep::Geometry::VisAttrObject::~VisAttrObject().
decrement() [2/3]
void InstanceCount::decrement (const std::type_info & typ) static
Decrement count according to type information.
Definition at line 126 of file InstanceCount.cpp.
decrement() [3/3]
void InstanceCount::decrement (const std::string & typ) static
Decrement count according to string information.
Definition at line 110 of file InstanceCount.cpp.
doTrace()
bool InstanceCount::doTrace () static
Check if tracing is enabled.
Definition at line 82 of file InstanceCount.cpp.
Referenced by get().
doTracing()
void InstanceCount::doTracing (bool value) static
Enable/Disable tracing.
Definition at line 86 of file InstanceCount.cpp.
Referenced by get().
dump()
void InstanceCount::dump (int which = ALL) static
Dump list of instance counters.
Force dump of counters.
Definition at line 134 of file InstanceCount.cpp.
References DD4hep::typeName().
Referenced by get().
get() [1/3]
template<class T > static counter_t DD4hep::InstanceCount::get (T *) inline static
Access current counter.
Definition at line 108 of file InstanceCount.h.
References DD4hep::InstanceCount::Counter::decrement(), getCounter(), DD4hep::InstanceCount::Counter::increment(), and DD4hep::InstanceCount::Counter::value().
get() [2/3]
static counter_t DD4hep::InstanceCount::get (const std::type_info & typ) inline static
Access current counter.
Definition at line 116 of file InstanceCount.h.
References DD4hep::InstanceCount::Counter::decrement(), getCounter(), DD4hep::InstanceCount::Counter::increment(), and DD4hep::InstanceCount::Counter::value().
get() [3/3]
static counter_t DD4hep::InstanceCount::get (const std::string & typ) inline static
Access current counter.
Definition at line 124 of file InstanceCount.h.
References ALL, clear(), doTrace(), doTracing(), dump(), getCounter(), and DD4hep::InstanceCount::Counter::value().
getCounter() [1/2]
InstanceCount::Counter * InstanceCount::getCounter (const std::type_info & typ) static
Access counter object for local caching on optimizations.
Definition at line 90 of file InstanceCount.cpp.
Referenced by get(), and DD4hep::InstanceCount::Counter::maximum().
getCounter() [2/2]
InstanceCount::Counter * InstanceCount::getCounter (const std::string & typ) static
Access counter object for local caching on optimizations.
Definition at line 96 of file InstanceCount.cpp.
increment() [1/3]
template<class T > static void DD4hep::InstanceCount::increment (T *) inline static
Increment count according to type information.
Definition at line 100 of file InstanceCount.h.
References DD4hep::InstanceCount::Counter::increment().
Referenced by DD4hep::Simulation::RefCountedSequence< Geant4SensDetActionSequence >::_aquire(), DD4hep::Simulation::SequenceHdl< Geant4GeneratorActionSequence >::_aquire(), DD4hep::Conditions::AbstractMap::AbstractMap(), DD4hep::Alignments::AlignContext::AlignContext(), DD4hep::Alignments::Interna::AlignmentConditionObject::AlignmentConditionObject(), DD4hep::Alignments::Interna::AlignmentContainer::AlignmentContainer(), DD4hep::Alignments::AlignmentData::AlignmentData(), DD4hep::Alignments::AlignmentsManagerObject::AlignmentsManagerObject(), DD4hep::Alignments::AlignmentStack::AlignmentStack(), ClassImp(), DD4hep::Conditions::Interna::ConditionContainer::ConditionContainer(), DD4hep::Conditions::ConditionDependency::ConditionDependency(), DD4hep::Conditions::Interna::ConditionObject::ConditionObject(), DD4hep::Conditions::ConditionsIOVPool::ConditionsIOVPool(), DD4hep::Conditions::ConditionsManagerObject::ConditionsManagerObject(), DD4hep::Conditions::ConditionsPool::ConditionsPool(), DD4hep::Geometry::ConstantObject::ConstantObject(), DD4hep::Geometry::DetElementObject::DetElementObject(), DD4hep::ElementList::ElementList(), DD4hep::Simulation::EnergyDepositMinimumCut::EnergyDepositMinimumCut(), DD4hep::Conditions::Entry::Entry(), DD4hep::Simulation::Geant4ActionContainer::Geant4ActionContainer(), DD4hep::Simulation::Geant4ActionPhase::Geant4ActionPhase(), DD4hep::Simulation::Geant4ActionSD::Geant4ActionSD(), DD4hep::Simulation::Geant4Context::Geant4Context(), DD4hep::Simulation::Geant4DetectorConstructionSequence::Geant4DetectorConstructionSequence(), DD4hep::Simulation::Geant4EscapeCounter::Geant4EscapeCounter(), DD4hep::Simulation::Geant4Event::Geant4Event(), DD4hep::Simulation::Geant4EventAction::Geant4EventAction(), DD4hep::Simulation::Geant4EventActionSequence::Geant4EventActionSequence(), DD4hep::Simulation::Geant4EventSeed::Geant4EventSeed(), DD4hep::Simulation::Geant4Filter::Geant4Filter(), DD4hep::Simulation::Geant4GeneratorAction::Geant4GeneratorAction(), DD4hep::Simulation::Geant4GeneratorActionInit::Geant4GeneratorActionInit(), DD4hep::Simulation::Geant4GeneratorActionSequence::Geant4GeneratorActionSequence(), DD4hep::Simulation::Geant4GeneratorWrapper::Geant4GeneratorWrapper(), DD4hep::Simulation::Geant4HitData::Geant4HitData(), DD4hep::Simulation::Geant4InteractionMerger::Geant4InteractionMerger(), DD4hep::Simulation::Geant4InteractionVertexBoost::Geant4InteractionVertexBoost(), DD4hep::Simulation::Geant4InteractionVertexSmear::Geant4InteractionVertexSmear(), DD4hep::Simulation::Geant4IsotropeGenerator::Geant4IsotropeGenerator(), DD4hep::Simulation::Geant4Kernel::Geant4Kernel(), DD4hep::Simulation::Geant4MaterialScanner::Geant4MaterialScanner(), DD4hep::Simulation::Geant4MonteCarloTruth::Geant4MonteCarloTruth(), DD4hep::Simulation::Geant4Output2ROOT::Geant4Output2ROOT(), DD4hep::Simulation::Geant4OutputAction::Geant4OutputAction(), DD4hep::Simulation::Geant4Particle::Geant4Particle(), DD4hep::Simulation::Geant4ParticleGenerator::Geant4ParticleGenerator(), DD4hep::Simulation::Geant4ParticleGun::Geant4ParticleGun(), DD4hep::Simulation::Geant4ParticleHandler::Geant4ParticleHandler(), DD4hep::Simulation::Geant4ParticlePrint::Geant4ParticlePrint(), DD4hep::Simulation::Geant4PhysicsConstructor::Geant4PhysicsConstructor(), DD4hep::Simulation::Geant4PhysicsList::Geant4PhysicsList(), DD4hep::Simulation::Geant4PhysicsListActionSequence::Geant4PhysicsListActionSequence(), DD4hep::Simulation::Geant4PrimaryHandler::Geant4PrimaryHandler(), DD4hep::Simulation::Geant4Random::Geant4Random(), DD4hep::Simulation::Geant4ReadoutVolumeFilter::Geant4ReadoutVolumeFilter(), DD4hep::Simulation::Geant4Run::Geant4Run(), DD4hep::Simulation::Geant4RunAction::Geant4RunAction(), DD4hep::Simulation::Geant4RunActionSequence::Geant4RunActionSequence(), DD4hep::Simulation::Geant4SensDetActionSequence::Geant4SensDetActionSequence(), DD4hep::Simulation::Geant4Sensitive::Geant4Sensitive(), Tests::Geant4SensitiveAction< T >::Geant4SensitiveAction(), DD4hep::Simulation::Geant4SensitiveAction< T >::Geant4SensitiveAction(), DD4hep::Simulation::Geant4SharedEventAction::Geant4SharedEventAction(), DD4hep::Simulation::Geant4SharedGeneratorAction::Geant4SharedGeneratorAction(), DD4hep::Simulation::Geant4SharedRunAction::Geant4SharedRunAction(), DD4hep::Simulation::Geant4SharedStackingAction::Geant4SharedStackingAction(), DD4hep::Simulation::Geant4SharedSteppingAction::Geant4SharedSteppingAction(), DD4hep::Simulation::Geant4SharedTrackingAction::Geant4SharedTrackingAction(), DD4hep::Simulation::Geant4StackingAction::Geant4StackingAction(), DD4hep::Simulation::Geant4StackingActionSequence::Geant4StackingActionSequence(), DD4hep::Simulation::Geant4SteppingAction::Geant4SteppingAction(), DD4hep::Simulation::Geant4SteppingActionSequence::Geant4SteppingActionSequence(), DD4hep::Simulation::Test::Geant4TestBase::Geant4TestBase(), DD4hep::Simulation::Test::Geant4TestEventAction::Geant4TestEventAction(), DD4hep::Simulation::Test::Geant4TestGeneratorAction::Geant4TestGeneratorAction(), DD4hep::Simulation::Test::Geant4TestRunAction::Geant4TestRunAction(), DD4hep::Simulation::Test::Geant4TestSensitive::Geant4TestSensitive(), DD4hep::Simulation::Test::Geant4TestStepAction::Geant4TestStepAction(), DD4hep::Simulation::Test::Geant4TestTrackAction::Geant4TestTrackAction(), DD4hep::Simulation::Geant4TrackingAction::Geant4TrackingAction(), DD4hep::Simulation::Geant4TrackingActionSequence::Geant4TrackingActionSequence(), DD4hep::Simulation::Geant4TrackingPostAction::Geant4TrackingPostAction(), DD4hep::Simulation::Geant4TrackingPreAction::Geant4TrackingPreAction(), DD4hep::Simulation::Geant4UserInitialization::Geant4UserInitialization(), DD4hep::Simulation::Geant4UserInitializationSequence::Geant4UserInitializationSequence(), DD4hep::Simulation::Geant4UserParticleHandler::Geant4UserParticleHandler(), DD4hep::Simulation::Geant4Vertex::Geant4Vertex(), DD4hep::Simulation::GeantinoRejectFilter::GeantinoRejectFilter(), DD4hep::Geometry::HeaderObject::HeaderObject(), DD4hep::Simulation::Geant4Tracker::Hit::Hit(), DD4hep::Simulation::Geant4Calorimeter::Hit::Hit(), DD4hep::Simulation::Geant4HitWrapper::HitManipulator::HitManipulator(), DD4hep::Geometry::IDDescriptorObject::IDDescriptorObject(), DD4hep::Geometry::LCDDData::LCDDData(), DD4hep::Geometry::LCDDImp::LCDDImp(), DD4hep::Geometry::LimitSetObject::LimitSetObject(), DD4hep::Simulation::Geant4HitCollection::newInstance(), DD4hep::Geometry::CartesianField::Object::Object(), DD4hep::Geometry::OverlayedField::Object::Object(), DD4hep::ObjectExtensions::ObjectExtensions(), DD4hep::OpaqueDataBlock::OpaqueDataBlock(), DD4hep::Simulation::ParticleFilter::ParticleFilter(), DD4hep::Simulation::ParticleRejectFilter::ParticleRejectFilter(), DD4hep::Simulation::ParticleSelectFilter::ParticleSelectFilter(), DD4hep::Geometry::ReadoutObject::ReadoutObject(), DD4hep::Geometry::RegionObject::RegionObject(), DD4hep::Geometry::SegmentationObject::SegmentationObject(), DD4hep::Geometry::SensitiveDetectorObject::SensitiveDetectorObject(), DD4hep::Simulation::SimpleEvent::SimpleEvent(), DD4hep::Simulation::SimpleRun::SimpleRun(), DD4hep::Alignments::AlignmentStack::StackEntry::StackEntry(), DD4hep::Conditions::UserPool::UserPool(), DD4hep::View::View(), and DD4hep::Geometry::VisAttrObject::VisAttrObject().
increment() [2/3]
void InstanceCount::increment (const std::type_info & typ) static
Increment count according to type information.
Definition at line 118 of file InstanceCount.cpp.
increment() [3/3]
void InstanceCount::increment (const std::string & typ) static
Increment count according to string information.
Definition at line 102 of file InstanceCount.cpp.
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/InstanceCount.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/InstanceCount.cpp