DD4hep: DD4hep: DD4hep::Simulation::TrackerWeighted Struct Reference
DD4hep::Simulation::TrackerWeighted Struct Reference
Public Types
enum { POSITION_WEIGHTED = 1, POSITION_MIDDLE = 2, POSITION_PREPOINT = 3, POSITION_POSTPOINT = 4 }
Enumeration to define the calculation of the position of the energy deposit.
typedef Geant4HitCollection HitCollection
Public Member Functions
TrackerWeighted ()
TrackerWeighted & clear ()
Clear collected information and restart for new hit.
TrackerWeighted & start (const G4Step *step, const G4StepPoint *point)
Start a new hit.
TrackerWeighted & update (const G4Step *step)
Update energy and track information during hit info accumulation.
bool mustSaveTrack (const G4Track *tr) const
Helper function to decide if the hit has to be extracted and saved in the collection.
void extractHit (EInside ended)
Extract hit information and add the created hit to the collection.
TrackerWeighted & calc_dist_out (const G4VSolid *solid)
TrackerWeighted & calc_dist_in (const G4VSolid *solid)
void extractHit (Geant4HitCollection *collection, EInside ended)
G4bool process (const G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
void endEvent ()
Post-event action callback.
void startEvent ()
Pre event action callback.
Public Attributes
Geant4Tracker::Hit pre
Geant4Tracker::Hit post
Position mean_pos
Geant4Sensitive * sensitive
G4VSensitiveDetector * thisSD
double distance_to_inside
double distance_to_outside
double mean_time
double step_length
double e_cut
int current
int parent
int combined
int hit_position_type
int hit_flag
int g4ID
EInside last_inside
long long int cell
bool single_deposit_mode
Detailed Description
Definition at line 70 of file Geant4TrackerWeightedSD.cpp.
Member Typedef Documentation
typedef Geant4HitCollection DD4hep::Simulation::TrackerWeighted::HitCollection
Definition at line 71 of file Geant4TrackerWeightedSD.cpp.
Member Enumeration Documentation
anonymous enum
Enumeration to define the calculation of the position of the energy deposit.
Enumerator:
POSITION_WEIGHTED
POSITION_MIDDLE
POSITION_PREPOINT
POSITION_POSTPOINT
Definition at line 74 of file Geant4TrackerWeightedSD.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::TrackerWeighted::TrackerWeighted () [inline]
Definition at line 98 of file Geant4TrackerWeightedSD.cpp.
Member Function Documentation
TrackerWeighted& DD4hep::Simulation::TrackerWeighted::calc_dist_in (const G4VSolid * solid) [inline]
Definition at line 180 of file Geant4TrackerWeightedSD.cpp.
References distance_to_inside, DD4hep::Simulation::Geant4Tracker::Hit::momentum, DD4hep::Simulation::Geant4Tracker::Hit::position, pre, and v.
Referenced by process().
TrackerWeighted& DD4hep::Simulation::TrackerWeighted::calc_dist_out (const G4VSolid * solid) [inline]
Definition at line 172 of file Geant4TrackerWeightedSD.cpp.
References distance_to_outside, DD4hep::Simulation::Geant4Tracker::Hit::momentum, DD4hep::Simulation::Geant4Tracker::Hit::position, post, pre, and v.
Referenced by process().
TrackerWeighted& DD4hep::Simulation::TrackerWeighted::clear () [inline]
Clear collected information and restart for new hit.
Definition at line 107 of file Geant4TrackerWeightedSD.cpp.
References cell, DD4hep::Simulation::Geant4Tracker::Hit::clear(), combined, current, distance_to_inside, distance_to_outside, g4ID, hit_flag, last_inside, mean_pos, mean_time, parent, post, pre, and step_length.
Referenced by extractHit(), and start().
void DD4hep::Simulation::TrackerWeighted::endEvent () [inline]
Post-event action callback.
Definition at line 362 of file Geant4TrackerWeightedSD.cpp.
References DD4hep::Simulation::Geant4Sensitive::collection(), current, extractHit(), last_inside, DD4hep::Simulation::Geant4Action::print(), and sensitive.
void DD4hep::Simulation::TrackerWeighted::extractHit (Geant4HitCollection * collection, EInside ended) [inline]
Definition at line 188 of file Geant4TrackerWeightedSD.cpp.
References DD4hep::Simulation::Geant4HitCollection::add(), cell, DD4hep::Simulation::Geant4HitData::cellID, clear(), combined, current, distance_to_inside, distance_to_outside, DD4hep::Simulation::Geant4HitData::flag, g4ID, DD4hep::Simulation::Geant4HitData::g4ID, DD4hep::Simulation::Geant4HitCollection::GetSize(), DD4hep::Simulation::Geant4HitData::HIT_ENDED_INSIDE, DD4hep::Simulation::Geant4HitData::HIT_ENDED_OUTSIDE, DD4hep::Simulation::Geant4HitData::HIT_ENDED_SURFACE, hit_flag, hit_position_type, DD4hep::Simulation::Geant4HitData::HIT_STARTED_INSIDE, DD4hep::Simulation::Geant4HitData::HIT_STARTED_OUTSIDE, DD4hep::Simulation::Geant4HitData::HIT_STARTED_SURFACE, dd4hep::keV, DD4hep::Simulation::Geant4Tracker::Hit::length, mean_pos, mean_time, dd4hep::mm, DD4hep::Simulation::Geant4Tracker::Hit::momentum, DD4hep::Simulation::Geant4Tracker::Hit::position, POSITION_MIDDLE, POSITION_POSTPOINT, POSITION_PREPOINT, POSITION_WEIGHTED, post, pre, DD4hep::Simulation::Geant4Action::print(), sensitive, step_length, DD4hep::Simulation::Geant4Tracker::Hit::truth, and dd4hep::um.
void DD4hep::Simulation::TrackerWeighted::extractHit (EInside ended) [inline]
Extract hit information and add the created hit to the collection.
Definition at line 167 of file Geant4TrackerWeightedSD.cpp.
References DD4hep::Simulation::Geant4Sensitive::collection(), and sensitive.
Referenced by endEvent(), and process().
bool DD4hep::Simulation::TrackerWeighted::mustSaveTrack (const G4Track * tr) const [inline]
Helper function to decide if the hit has to be extracted and saved in the collection.
Definition at line 162 of file Geant4TrackerWeightedSD.cpp.
References current.
G4bool DD4hep::Simulation::TrackerWeighted::process (const G4Step * step, G4TouchableHistory *) [inline]
Method for generating hit(s) using the information of G4Step object.
Definition at line 253 of file Geant4TrackerWeightedSD.cpp.
References calc_dist_in(), calc_dist_out(), current, DD4hep::Simulation::Geant4Action::error(), extractHit(), DD4hep::Simulation::Geant4StepHandler::globalToLocalG4(), hit_flag, DD4hep::Simulation::Geant4HitData::HIT_KILLED_TRACK, DD4hep::Simulation::Geant4HitData::HIT_SECONDARY_TRACK, DD4hep::Simulation::Geant4HitData::HIT_STARTED_INSIDE, DD4hep::Simulation::Geant4HitData::HIT_STARTED_OUTSIDE, DD4hep::Simulation::Geant4HitData::HIT_STARTED_SURFACE, last_inside, DD4hep::Simulation::Geant4StepHandler::post, DD4hep::Simulation::Geant4StepHandler::postPosG4(), DD4hep::Simulation::Geant4StepHandler::postSD(), DD4hep::Simulation::Geant4StepHandler::postVolume(), DD4hep::Simulation::Geant4StepHandler::pre, DD4hep::Simulation::Geant4StepHandler::prePosG4(), DD4hep::Simulation::Geant4StepHandler::preSD(), DD4hep::Simulation::Geant4StepHandler::preVolume(), DD4hep::Simulation::Geant4Action::print(), sensitive, single_deposit_mode, DD4hep::Simulation::Geant4StepHandler::solid(), start(), thisSD, DD4hep::Simulation::Geant4StepHandler::trkAlive(), DD4hep::Simulation::Geant4StepHandler::trkID(), and update().
TrackerWeighted& DD4hep::Simulation::TrackerWeighted::start (const G4Step * step, const G4StepPoint * point) [inline]
Start a new hit.
Definition at line 126 of file Geant4TrackerWeightedSD.cpp.
References clear(), current, g4ID, DD4hep::Simulation::Geant4Sensitive::mark(), parent, post, pre, sensitive, DD4hep::Simulation::Geant4Tracker::Hit::storePoint(), and DD4hep::Simulation::Geant4Tracker::Hit::truth.
Referenced by process().
void DD4hep::Simulation::TrackerWeighted::startEvent () [inline]
Pre event action callback.
Definition at line 374 of file Geant4TrackerWeightedSD.cpp.
References DD4hep::Simulation::Geant4Sensitive::detector(), sensitive, and thisSD.
TrackerWeighted& DD4hep::Simulation::TrackerWeighted::update (const G4Step * step) [inline]
Update energy and track information during hit info accumulation.
Definition at line 140 of file Geant4TrackerWeightedSD.cpp.
References cell, DD4hep::Simulation::Geant4Sensitive::cellID(), combined, DD4hep::Simulation::Geant4Action::except(), mean_pos, mean_time, DD4hep::Simulation::Geant4Tracker::Hit::position, post, pre, sensitive, step_length, DD4hep::Simulation::Geant4Tracker::Hit::storePoint(), DD4hep::Simulation::Geant4Tracker::Hit::truth, and DD4hep::Simulation::Geant4Sensitive::volumeID().
Referenced by process().
Member Data Documentation
long long int DD4hep::Simulation::TrackerWeighted::cell
Definition at line 96 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and update().
int DD4hep::Simulation::TrackerWeighted::combined
Definition at line 91 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and update().
int DD4hep::Simulation::TrackerWeighted::current
Definition at line 90 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), endEvent(), extractHit(), mustSaveTrack(), process(), and start().
double DD4hep::Simulation::TrackerWeighted::distance_to_inside
Definition at line 85 of file Geant4TrackerWeightedSD.cpp.
Referenced by calc_dist_in(), clear(), and extractHit().
double DD4hep::Simulation::TrackerWeighted::distance_to_outside
Definition at line 86 of file Geant4TrackerWeightedSD.cpp.
Referenced by calc_dist_out(), clear(), and extractHit().
double DD4hep::Simulation::TrackerWeighted::e_cut
Definition at line 89 of file Geant4TrackerWeightedSD.cpp.
int DD4hep::Simulation::TrackerWeighted::g4ID
Definition at line 94 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and start().
int DD4hep::Simulation::TrackerWeighted::hit_flag
Definition at line 93 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and process().
int DD4hep::Simulation::TrackerWeighted::hit_position_type
Definition at line 92 of file Geant4TrackerWeightedSD.cpp.
Referenced by extractHit().
EInside DD4hep::Simulation::TrackerWeighted::last_inside
Definition at line 95 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), endEvent(), and process().
Position DD4hep::Simulation::TrackerWeighted::mean_pos
Definition at line 82 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and update().
double DD4hep::Simulation::TrackerWeighted::mean_time
Definition at line 87 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and update().
int DD4hep::Simulation::TrackerWeighted::parent
Definition at line 90 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), and start().
Geant4Tracker::Hit DD4hep::Simulation::TrackerWeighted::post
Definition at line 81 of file Geant4TrackerWeightedSD.cpp.
Referenced by calc_dist_out(), clear(), extractHit(), start(), and update().
Geant4Tracker::Hit DD4hep::Simulation::TrackerWeighted::pre
Definition at line 81 of file Geant4TrackerWeightedSD.cpp.
Referenced by calc_dist_in(), calc_dist_out(), clear(), extractHit(), start(), and update().
Geant4Sensitive* DD4hep::Simulation::TrackerWeighted::sensitive
Definition at line 83 of file Geant4TrackerWeightedSD.cpp.
Referenced by endEvent(), extractHit(), process(), start(), startEvent(), and update().
bool DD4hep::Simulation::TrackerWeighted::single_deposit_mode
Definition at line 97 of file Geant4TrackerWeightedSD.cpp.
Referenced by process().
double DD4hep::Simulation::TrackerWeighted::step_length
Definition at line 88 of file Geant4TrackerWeightedSD.cpp.
Referenced by clear(), extractHit(), and update().
G4VSensitiveDetector* DD4hep::Simulation::TrackerWeighted::thisSD
Definition at line 84 of file Geant4TrackerWeightedSD.cpp.
Referenced by process(), and startEvent().
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4TrackerWeightedSD.cpp