DD4hep: DD4hep: DD4hep::Simulation::TrackerCombine Struct Reference
DD4hep::Simulation::TrackerCombine Struct Reference
Public Types
typedef Geant4HitCollection HitCollection
Public Member Functions
TrackerCombine ()
void start (G4Step *step, G4StepPoint *point)
Start a new hit.
void update (G4Step *step)
Update energy and track information during hit info accumulation.
void clear ()
Clear collected information and restart for new hit.
bool mustSaveTrack (const G4Track *tr) const
Helper function to decide if the hit has to be extracted and saved in the collection.
void extractHit (Geant4HitCollection *collection)
Extract hit information and add the created hit to the collection.
G4bool process (G4Step *step, G4TouchableHistory *)
Method for generating hit(s) using the information of G4Step object.
void endEvent (const G4Event *)
Post-event action callback.
Public Attributes
Geant4Tracker::Hit pre
Geant4Tracker::Hit post
Position mean_pos
Geant4Sensitive * sensitive
double mean_time
double e_cut
int current
int combined
long long int cell
Detailed Description
Definition at line 318 of file Geant4SDActions.cpp.
Member Typedef Documentation
typedef Geant4HitCollection DD4hep::Simulation::TrackerCombine::HitCollection
Definition at line 319 of file Geant4SDActions.cpp.
Constructor & Destructor Documentation
DD4hep::Simulation::TrackerCombine::TrackerCombine () [inline]
Definition at line 329 of file Geant4SDActions.cpp.
Member Function Documentation
void DD4hep::Simulation::TrackerCombine::clear () [inline]
Clear collected information and restart for new hit.
Definition at line 366 of file Geant4SDActions.cpp.
References cell, DD4hep::Simulation::Geant4Tracker::Hit::clear(), combined, current, mean_pos, mean_time, post, and pre.
Referenced by extractHit().
void DD4hep::Simulation::TrackerCombine::endEvent (const G4Event *) [inline]
Post-event action callback.
Definition at line 445 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4Sensitive::collection(), current, extractHit(), and sensitive.
Referenced by DD4hep::Simulation::Geant4SensitiveAction< T >::initialize().
void DD4hep::Simulation::TrackerCombine::extractHit (Geant4HitCollection * collection) [inline]
Extract hit information and add the created hit to the collection.
Definition at line 382 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4HitCollection::add(), DD4hep::Simulation::Geant4Action::c_name(), cell, DD4hep::Simulation::Geant4HitData::cellID, clear(), combined, current, DD4hep::Simulation::Geant4Tracker::Hit::length, mean_pos, mean_time, dd4hep::MeV, dd4hep::mm, DD4hep::Simulation::Geant4Tracker::Hit::momentum, DD4hep::Simulation::Geant4Tracker::Hit::position, post, pre, DD4hep::Simulation::Geant4Action::printM2(), sensitive, and DD4hep::Simulation::Geant4Tracker::Hit::truth.
Referenced by endEvent(), and process().
bool DD4hep::Simulation::TrackerCombine::mustSaveTrack (const G4Track * tr) const [inline]
Helper function to decide if the hit has to be extracted and saved in the collection.
Definition at line 377 of file Geant4SDActions.cpp.
References current.
Referenced by process().
G4bool DD4hep::Simulation::TrackerCombine::process (G4Step * step, G4TouchableHistory *) [inline]
Method for generating hit(s) using the information of G4Step object.
If we are handling a new track, then store the content of the previous one.
Initialize the deposits of the next hit.
....update .....
Definition at line 408 of file Geant4SDActions.cpp.
References DD4hep::Simulation::Geant4Sensitive::collection(), current, extractHit(), mustSaveTrack(), DD4hep::Simulation::Geant4StepHandler::post, DD4hep::Simulation::Geant4StepHandler::pre, DD4hep::Simulation::Geant4StepHandler::sd(), sensitive, start(), DD4hep::Simulation::Geant4StepHandler::track, update(), and DD4hep::Simulation::Geant4StepHandler::volume().
void DD4hep::Simulation::TrackerCombine::start (G4Step * step, G4StepPoint * point) [inline]
Start a new hit.
Definition at line 335 of file Geant4SDActions.cpp.
References cell, combined, current, DD4hep::Simulation::Geant4Sensitive::mark(), mean_pos, mean_time, post, pre, sensitive, DD4hep::Simulation::Geant4Tracker::Hit::storePoint(), and DD4hep::Simulation::Geant4Tracker::Hit::truth.
Referenced by process().
void DD4hep::Simulation::TrackerCombine::update (G4Step * step) [inline]
Update energy and track information during hit info accumulation.
Definition at line 348 of file Geant4SDActions.cpp.
References cell, DD4hep::Simulation::Geant4Sensitive::cellID(), combined, DD4hep::Simulation::Geant4Action::except(), mean_pos, mean_time, DD4hep::Simulation::Geant4Tracker::Hit::position, post, pre, sensitive, DD4hep::Simulation::Geant4Tracker::Hit::storePoint(), DD4hep::Simulation::Geant4Tracker::Hit::truth, and DD4hep::Simulation::Geant4Sensitive::volumeID().
Referenced by process().
Member Data Documentation
long long int DD4hep::Simulation::TrackerCombine::cell
Definition at line 327 of file Geant4SDActions.cpp.
Referenced by clear(), extractHit(), start(), and update().
int DD4hep::Simulation::TrackerCombine::combined
Definition at line 326 of file Geant4SDActions.cpp.
Referenced by clear(), extractHit(), start(), and update().
int DD4hep::Simulation::TrackerCombine::current
Definition at line 325 of file Geant4SDActions.cpp.
Referenced by clear(), endEvent(), extractHit(), mustSaveTrack(), process(), and start().
double DD4hep::Simulation::TrackerCombine::e_cut
Definition at line 324 of file Geant4SDActions.cpp.
Position DD4hep::Simulation::TrackerCombine::mean_pos
Definition at line 321 of file Geant4SDActions.cpp.
Referenced by clear(), extractHit(), start(), and update().
double DD4hep::Simulation::TrackerCombine::mean_time
Definition at line 323 of file Geant4SDActions.cpp.
Referenced by clear(), extractHit(), start(), and update().
Geant4Tracker::Hit DD4hep::Simulation::TrackerCombine::post
Definition at line 320 of file Geant4SDActions.cpp.
Referenced by clear(), extractHit(), start(), and update().
Geant4Tracker::Hit DD4hep::Simulation::TrackerCombine::pre
Definition at line 320 of file Geant4SDActions.cpp.
Referenced by clear(), extractHit(), start(), and update().
Geant4Sensitive* DD4hep::Simulation::TrackerCombine::sensitive
Definition at line 322 of file Geant4SDActions.cpp.
Referenced by endEvent(), extractHit(), process(), start(), and update().
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4SDActions.cpp