DD4hep: DD4hep::Conditions::Test::TestEnv Struct Reference
DD4hep::Conditions::Test::TestEnv Struct Reference
#include <ConditionsTest.h>
Public Member Functions
TestEnv (LCDD &_lcdd, const std::string &detector_name)
DetElement daughter (const std::string &sub_path) const
Find daughter element of the detector object.
void add_xml_data_source (const std::string &file, const std::string &iov)
void dump_conditions_pools ()
TestEnv (LCDD &_lcdd, const std::string &detector_name)
DetElement daughter (const std::string &sub_path) const
Find daughter element of the detector object.
void add_xml_data_source (const std::string &file)
void dump_conditions_pools ()
Static Public Member Functions
static void dump_detector_element (DetElement elt)
Dump the conditions of one detectpr element.
static void dump_conditions_tree (DetElement elt)
Dump conditions tree of a detector element.
static void dump_detector_element (DetElement elt)
static void dump_conditions_tree (DetElement elt)
Public Attributes
LCDD & lcdd
DetElement detector
ConditionsManager manager
Handle< ConditionsDataLoader > loader
const IOVType * epoch
const IOVType * run
Detailed Description
Definition at line 43 of file ConditionsTest.h.
Constructor & Destructor Documentation
TestEnv() [1/2]
Test::TestEnv::TestEnv (LCDD & _lcdd, const std::string & detector_name)
Definition at line 173 of file ConditionsTest.cpp.
References detector, DD4hep::Geometry::LCDD::detector(), e, epoch, DD4hep::Conditions::ConditionsManager::from(), DD4hep::Conditions::ConditionsManager::initialize(), DD4hep::Handle< T >::isValid(), lcdd, loader, DD4hep::Conditions::ConditionsManager::loader(), manager, DD4hep::Conditions::ConditionsManager::registerIOVType(), and run.
TestEnv() [2/2]
DD4hep::Conditions::Test::TestEnv::TestEnv (LCDD & _lcdd, const std::string & detector_name)
Member Function Documentation
add_xml_data_source() [1/2]
void DD4hep::Conditions::Test::TestEnv::add_xml_data_source (const std::string & file)
add_xml_data_source() [2/2]
void Test::TestEnv::add_xml_data_source (const std::string & file, const std::string & iov)
Definition at line 202 of file ConditionsTest.cpp.
References DD4hep::Conditions::ConditionsManager::fromString(), loader, and manager.
daughter() [1/2]
DetElement DD4hep::Conditions::Test::TestEnv::daughter (const std::string & sub_path) const
Find daughter element of the detector object.
daughter() [2/2]
DetElement Test::TestEnv::daughter (const std::string & sub_path) const
Find daughter element of the detector object.
Definition at line 198 of file ConditionsTest.cpp.
References detector, and DD4hep::Geometry::DetectorTools::findDaughterElement().
dump_conditions_pools() [1/2]
void DD4hep::Conditions::Test::TestEnv::dump_conditions_pools ()
dump_conditions_pools() [2/2]
void Test::TestEnv::dump_conditions_pools ()
Definition at line 209 of file ConditionsTest.cpp.
References _E, DD4hep::Conditions::ConditionsPool::age_value, e, DD4hep::Conditions::ConditionsIOVPool::elements, DD4hep::INFO, DD4hep::Conditions::ConditionsPool::iov, DD4hep::Conditions::ConditionsManager::iovType(), manager, DD4hep::Conditions::Test::print_conditions< void >(), DD4hep::printout(), DD4hep::Conditions::ConditionsPool::select_all(), DD4hep::IOVType::str(), and DD4hep::IOV::str().
dump_conditions_tree() [1/2]
static void DD4hep::Conditions::Test::TestEnv::dump_conditions_tree (DetElement elt) static
dump_conditions_tree() [2/2]
void Test::TestEnv::dump_conditions_tree (DetElement elt) static
Dump conditions tree of a detector element.
Definition at line 253 of file ConditionsTest.cpp.
References DD4hep::Geometry::DetElement::children(), dump_detector_element(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::DetElement::path(), and DD4hep::printout().
dump_detector_element() [1/2]
static void DD4hep::Conditions::Test::TestEnv::dump_detector_element (DetElement elt) static
dump_detector_element() [2/2]
void Test::TestEnv::dump_detector_element (DetElement elt) static
Dump the conditions of one detectpr element.
Definition at line 238 of file ConditionsTest.cpp.
References DD4hep::Conditions::DetConditions::conditions(), DD4hep::INFO, DD4hep::Conditions::Container::numKeys(), DD4hep::Geometry::DetElement::path(), DD4hep::Conditions::Test::print_condition< void >(), and DD4hep::printout().
Referenced by dump_conditions_tree().
Member Data Documentation
detector
DetElement DD4hep::Conditions::Test::TestEnv::detector
Definition at line 45 of file ConditionsTest.h.
Referenced by daughter(), and TestEnv().
epoch
const IOVType * DD4hep::Conditions::Test::TestEnv::epoch
Definition at line 48 of file ConditionsTest.h.
Referenced by TestEnv().
lcdd
LCDD & DD4hep::Conditions::Test::TestEnv::lcdd
Definition at line 44 of file ConditionsTest.h.
Referenced by TestEnv().
loader
Handle< ConditionsDataLoader > DD4hep::Conditions::Test::TestEnv::loader
Definition at line 47 of file ConditionsTest.h.
Referenced by add_xml_data_source(), and TestEnv().
manager
ConditionsManager DD4hep::Conditions::Test::TestEnv::manager
Definition at line 46 of file ConditionsTest.h.
Referenced by add_xml_data_source(), dump_conditions_pools(), and TestEnv().
run
const IOVType * DD4hep::Conditions::Test::TestEnv::run
Definition at line 49 of file ConditionsTest.h.
Referenced by TestEnv().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/include/DDCond/ConditionsTest.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCond/src/ConditionsTest.cpp