DD4hep: DD4hep::XML::DetElement Struct Reference
DD4hep::XML::DetElement Struct Reference
DD4hep::XML classes and objects
XML Handle class extending the XML handle Dimension.
#include <XMLDetector.h>
Public Member Functions
DetElement (Handle_t e)
Constructor from Handle.
Handle_t handle () const
Access underlying XML handle object.
int id () const
Access parameters: id.
std::string materialStr () const
Access material attribute as STL string. If not present empty return empty string.
bool isSensitive () const
Check if xml detector element is sensitive.
bool isTracker () const
Check if element describes a tracking detector.
bool isCalorimeter () const
Check if element describes a calorimetric detector.
bool isInsideTrackingVolume () const
Check if element is inside the tracking volume.
void check (bool condition, const std::string &msg) const
Helper to check a condition (for debugging)
template<typename T >
T attr (const XmlChar *tag_value) const
Access attribute by type.
Public Member Functions inherited from DD4hep::XML::Dimension
Dimension ()
Default constructor.
Dimension (Handle_t e)
Constructor from Handle.
Dimension (const Element &e)
Constructor from Element.
int id () const
Access parameters: id.
int id (int default_value) const
Access parameters: id, if not present returns default.
int type () const
Access parameters: type.
bool combineHits () const
Access rotation constants: combineHits.
double angle () const
Access rotation constants: angle.
double alpha () const
Access rotation constants: alpha.
double alpha (double default_value) const
Access rotation constants: alpha.
double alpha1 () const
Access rotation constants: alpha1.
double alpha1 (double default_value) const
Access rotation constants: alpha1.
double alpha2 () const
Access rotation constants: alpha2.
double alpha2 (double default_value) const
Access rotation constants: alpha2.
double beta () const
Access rotation constants: angle.
double beta (double default_value) const
Access rotation constants: angle.
double gamma () const
Access rotation constants: angle.
double gamma (double default_value) const
Access rotation constants: angle.
double delta () const
Access rotation constants: angle.
double delta (double default_value) const
Access rotation constants: angle.
double epsilon () const
Access rotation constants: angle.
double epsilon (double default_value) const
Access rotation constants: angle.
double theta () const
Access rotation constants: theta.
double theta (double default_value) const
Access rotation constants: theta.
double deltatheta () const
Access rotation constants: deltatheta.
double deltatheta (double default_value) const
Access rotation constants: deltatheta.
int thetaBins () const
Access rotation constants: thetaBins.
double phi () const
Access rotation constants: phi.
double phi (double default_value) const
Access rotation constants: phi.
int phiBins () const
Access rotation constants: phiBins.
double phi0 () const
Access rotation constants: phi0.
double phi0 (double default_value) const
Access parameters: phi0, if not present returns default.
double phi0_offset () const
Access rotation constants: phi0_offset.
double phi0_offset (double default_value) const
Access parameters: phi0_offset, if not present returns default.
double phi1 () const
Access rotation constants: phi1.
double phi1 (double default_value) const
Access parameters: phi1, if not present returns default.
double psi () const
Access rotation constants: psi.
double psi (double default_value) const
Access rotation constants: psi.
double zhalf () const
Access Tube parameters: zhalf.
double deltaphi () const
Access Tube parameters: deltaphi.
double deltaphi (double default_value) const
Access Tube parameters: deltaphi.
double startphi () const
Access rotation constants: startphi.
double startphi (double default_value) const
Access rotation constants: startphi.
double a () const
Access parameters: a.
double a (double default_value) const
Access parameters: a.
double A () const
Access parameters: A.
double A (double default_value) const
Access parameters: A.
double b () const
Access parameters: b.
double b (double default_value) const
Access parameters: b.
double c () const
Access parameters: c.
double c (double default_value) const
Access parameters: c.
double distance () const
Access parameters: distance.
double distance (double default_value) const
Access parameters: distance.
double B () const
Access parameters: B.
double B (double default_value) const
Access parameters: B.
double g () const
Access parameters: g.
double g (double default_value) const
Access parameters: g.
double G () const
Access parameters: G.
double G (double default_value) const
Access parameters: G.
double I () const
Access parameters: I.
double I (double default_value) const
Access parameters: I.
double r () const
Access parameters: r.
double r (double default_value) const
Access parameters: r, if not present returns default.
double R () const
Access parameters: R.
double R (double default_value) const
Access parameters: R.
double dr () const
Access parameters: dr.
double dr (double default_value) const
Access parameters: dr, if not present returns default.
double r0 () const
Access parameters: r0.
double r0 (double default_value) const
Access parameters: r0.
double rmin () const
Access min/max parameters: rmin.
double rmin (double default_val) const
Access min/max parameters: rmin.
double rmax () const
Access min/max parameters: rmax.
double rmax (double default_val) const
Access min/max parameters: rmax.
double rmin1 () const
Access min/max parameters: rmin1.
double rmin1 (double default_val) const
Access min/max parameters: rmin1.
double rmax1 () const
Access min/max parameters: rmax1.
double rmax1 (double default_val) const
Access min/max parameters: rmax1.
double rmin2 () const
Access min/max parameters: rmin2.
double rmin2 (double default_val) const
Access min/max parameters: rmin2.
double rmax2 () const
Access min/max parameters: rmax2.
double rmax2 (double default_val) const
Access min/max parameters: rmax2.
double radius () const
Access parameters: radius.
double radius (double default_val) const
Access parameters: radius.
double outer_radius () const
Access attribute values: outer_radius.
double outer_r () const
Access attribute values: outer_r.
double inner_radius () const
Access attribute values: inner_radius.
double inner_r () const
Access attribute values: inner_r.
double x () const
Access parameters: x.
double x (double default_val) const
Access parameters: x, if not present returns default.
double X () const
Access parameters: X.
double X (double default_val) const
Access parameters: X.
double x0 () const
Access parameters: x0.
double x0 (double default_val) const
Access parameters: x0.
double x1 () const
Access parameters: x1.
double x1 (double default_val) const
Access parameters: x1.
double x2 () const
Access parameters: x2.
double x2 (double default_val) const
Access parameters: x2.
double x3 () const
Access parameters: x3.
double x3 (double default_val) const
Access parameters: x3.
double x4 () const
Access parameters: x4.
double x4 (double default_val) const
Access parameters: x4.
double dx () const
Access parameters: dx.
double dx (double default_value) const
Access parameters: dx, if not present returns default.
double xmin () const
Access min/max parameters: xmax.
double xmin (double default_value) const
Access min/max parameters: xmax.
double xmax () const
Access min/max parameters: xmax.
double xmax (double default_value) const
Access min/max parameters: xmax.
double x_offset () const
Access min/max parameters: x_offset.
double x_offset (double default_value) const
Access min/max parameters: x_offset.
double dim_x () const
Access min/max parameters: dim_x.
double dim_x (double default_value) const
Access min/max parameters: dim_x.
double y () const
Access parameters: y.
double y (double default_val) const
Access parameters: y, if not present returns default.
double Y () const
Access parameters: Y.
double Y (double default_val) const
Access parameters: Y.
double y0 () const
Access parameters: y0.
double y0 (double default_value) const
Access parameters: y0.
double y1 () const
Access parameters: y1.
double y1 (double default_value) const
Access parameters: y1.
double y2 () const
Access parameters: y2.
double y2 (double default_value) const
Access parameters: y2.
double dy () const
Access parameters: dy.
double dy (double default_value) const
Access parameters: dz, if not present returns default.
double ymin () const
Access min/max parameters: ymax.
double ymin (double default_value) const
Access min/max parameters: ymax.
double ymax () const
Access min/max parameters: ymax.
double ymax (double default_value) const
Access min/max parameters: ymax.
double y_offset () const
Access min/max parameters: y_offset.
double y_offset (double default_value) const
Access min/max parameters: y_offset.
double dim_y () const
Access min/max parameters: dim_y.
double dim_y (double default_value) const
Access min/max parameters: dim_y.
double z () const
Access parameters: z.
double z (double default_val) const
Access parameters: z, if not present returns default.
double Z () const
Access parameters: Z.
double Z (double default_val) const
Access parameters: Z.
double z0 () const
Access parameters: z0.
double z0 (double default_val) const
Access parameters: z0.
double z1 () const
Access parameters: z1.
double z1 (double default_val) const
Access parameters: z1.
double z2 () const
Access parameters: z2.
double z2 (double default_val) const
Access parameters: z2.
double dz () const
Access parameters: dz.
double dz (double default_value) const
Access parameters: dz, if not present returns default.
double zmin () const
Access min/max parameters: zmax.
double zmin (double default_value) const
Access min/max parameters: zmax.
double zmax () const
Access min/max parameters: zmax.
double zmax (double default_value) const
Access min/max parameters: zmax.
double outer_z () const
Access attribute values: outer_z.
double inner_z () const
Access attribute values: inner_z.
double outer_stereo () const
Access attribute values: outer_stereo.
double inner_stereo () const
Access attribute values: inner_stereo.
double z_offset () const
Access min/max parameters: z_offset.
double z_offset (double default_value) const
Access min/max parameters: z_offset.
double dim_z () const
Access min/max parameters: dim_z.
double dim_z (double default_value) const
Access min/max parameters: dim_z.
double length () const
Access attribute values: length.
double width () const
Access attribute values: width.
double height () const
Access attribute values: height.
double depth () const
Access attribute values: depth.
double thickness () const
Access attribute values: thickness.
double z_length () const
Access attribute values: z_length.
double gap () const
Access attribute values: gap.
double r_size () const
Access attribute values: r_size.
double phi_size_max () const
Access attribute values: phi_size_max.
bool reflect () const
Access attribute values: reflect.
bool reflect (bool default_value) const
Access attribute values: reflect.
double crossing_angle () const
Access attribute values: crossing_angle.
int repeat () const
Access attribute values: repeat.
double coefficient () const
Access attribute values: coefficient.
double coefficient (double default_value) const
Access attribute values: coefficient.
double skew () const
Access attribute values: skew.
double skew (double default_value) const
Access attribute values: skew.
double outgoing_r () const
Access attribute values: outgoing_r.
double incoming_r () const
Access attribute values: incoming_r.
double offset () const
Access attribute values: offset.
double offset (double default_value) const
Access attribute values: offset.
int number () const
Access attribute values: number.
int nmodules () const
Access attribute values: nmodules.
int nModules () const
Access attribute values: nModules.
int RowID () const
Access attribute values: RowID.
double moduleHeight () const
Access attribute values: moduleHeight.
double moduleWidth () const
Access attribute values: moduleWidth.
double modulePitch () const
Access attribute values: modulePitch.
double modulePosX () const
Access attribute values: modulePosX.
double modulePosY () const
Access attribute values: modulePosY.
int nPads () const
Access attribute values: nPads.
double rowPitch () const
Access attribute values: rowPitch.
double padPitch () const
Access attribute values: padPitch.
double rowHeight () const
Access attribute values: rowHeight.
std::string padType () const
Access attribute values: padType.
int numsides () const
Access attribute values: numsides.
int nsides () const
Access attribute values: nsides.
int nsides_inner () const
Access attribute values: nsides_inner.
int nsides_outer () const
Access attribute values: nsides_outer.
double phi_tilt () const
Access attribute values: phi_tilt.
int nphi () const
Access attribute values: nphi.
double rc () const
Access attribute values: rc.
double zstart () const
Access attribute values: zstart.
int nz () const
Access attribute values: nz.
int key () const
Access attribute values: key.
int key_min () const
Access attribute values: key_min.
int key_max () const
Access attribute values: key_max.
int key_val () const
Access attribute values: key_val.
int key_value () const
Access attribute values: key_value.
double start () const
Access attribute values: start.
double start (double default_value) const
Access attribute values: start.
double end () const
Access attribute values: end.
double end (double default_value) const
Access attribute values: end.
double inner_field () const
Access attribute values: inner_field.
double outer_field () const
Access attribute values: outer_field.
bool visible () const
Access attribute values: visible.
bool show_daughters () const
Access attribute values: show_daughters.
double cut () const
Access min/max parameters: cut.
double cut (double default_value) const
Access min/max parameters: cut.
double threshold () const
Access min/max parameters: threshold.
double threshold (double default_value) const
Access min/max parameters: threshold.
double eunit () const
Access min/max parameters: eunit.
double eunit (double default_value) const
Access min/max parameters: eunit.
double lunit () const
Access min/max parameters: lunit.
double lunit (double default_value) const
Access min/max parameters: lunit.
double temperature () const
Access rotation constants: temperature.
double temperature (double default_value) const
Access rotation constants: temperature.
double pressure () const
Access rotation constants: pressure.
double pressure (double default_value) const
Access rotation constants: pressure.
double density () const
Access rotation constants: density.
double density (double default_value) const
Access rotation constants: density.
Dimension dimensions (bool throw_if_not_present=true) const
Access child element with tag "dimensions" as Dimension object.
Dimension position (bool throw_if_not_present=true) const
Child access: position.
Dimension rotation (bool throw_if_not_present=true) const
Child access: rotation.
Dimension trd (bool throw_if_not_present=true) const
Child access: trd.
Dimension tubs (bool throw_if_not_present=true) const
Child access: tubs.
Dimension staves (bool throw_if_not_present=true) const
Child access: staves.
Dimension beampipe (bool throw_if_not_present=true) const
Child access: beampipe.
std::string nameStr () const
Access "name" attribute as STL string.
std::string refStr () const
Access "ref" attribute as a string.
std::string typeStr () const
Access "type" attribute as STL string.
std::string valueStr () const
Access "value" attribute as STL string.
std::string moduleStr () const
Access "module" attribute as STL string.
std::string readoutStr () const
Access "readout" attribute as STL string.
std::string visStr () const
Access vis attribute as STL string. If not present empty return empty string.
std::string regionStr () const
Access region attribute as STL string. If not present empty return empty string.
std::string limitsStr () const
Access limits attribute as STL string. If not present empty return empty string.
Public Member Functions inherited from DD4hep::XML::Element
Element (const Handle_t &e)
Constructor from XmlElement handle.
Element (const Element &e)
Constructor from XmlElement handle.
Element (const Document &document, const XmlChar *type)
Constructor from DOM document entity.
Document document () const
Access the hosting document handle of this DOM element.
operator bool () const
operator bool: check handle validity
bool operator! () const
operator NOT: check handle validity
Element & operator= (const Element &c)
Assignment operator.
Element & operator= (Handle_t handle)
Assignment operator.
operator Handle_t () const
Automatic conversion to DOM element handle.
operator Elt_t () const
Automatic conversion to XmlElement pointer.
Elt_t ptr () const
Access to XmlElement pointer.
Handle_t parent () const
Access the XmlElements parent.
Elt_t parentElement () const
Access the XmlElements parent.
std::string tag () const
Access the tag name of this DOM element.
const XmlChar * tagName () const
Access the tag name of this DOM element.
void append (Handle_t handle) const
Append a new element to the existing tree.
Handle_t clone (const Document &new_doc) const
Clone the DOMelement.
bool hasAttr (const XmlChar *name) const
Check for the existence of a named attribute.
template<class T >
T attr (const XmlChar *tag_value) const
Access attribute with implicit return type conversion.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
const XmlChar * attr_name (const Attribute a) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute a) const
Access attribute value by the attribute (throws exception if not present)
size_t numChildren (const XmlChar *tag_value, bool exc=true) const
Access the number of children of this DOM element with a given tag name.
void setAttrs (Handle_t e) const
Remove own attributes and copy all attributes from handle 'e'.
void removeAttrs () const
Remove all attributes of this element.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
Attribute getAttr (const XmlChar *name) const
Access single attribute by it's name.
template<class T >
Attribute setAttr (const XmlChar *nam, const T &val) const
Set single attribute.
template<class T >
void setValue (const T &val) const
Set element value.
Handle_t clone (Handle_t h) const
Clone the DOM element tree.
Handle_t addChild (const XmlChar *tag) const
Add a new child to the DOM node.
Handle_t setChild (const XmlChar *tag) const
Check if a child with the required tag exists - if not create it and add it to the current node.
Handle_t child (const Strng_t &tag_value, bool except=true) const
Access child by tag name. Thow an exception if required in case the child is not present.
Handle_t remove (Handle_t node) const
Remove a child node identified by its handle.
bool hasChild (const XmlChar *tag_value) const
Check the existence of a child with a given tag name.
Attribute setRef (const XmlChar *tag, const XmlChar *refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Attribute setRef (const XmlChar *tag, const std::string &refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
const XmlChar * getRef (const XmlChar *tag) const
Access the value of the reference attribute of the node (attribute ref="ref-name")
void addComment (const char *text) const
Add comment node to the element.
Additional Inherited Members
Public Types inherited from DD4hep::XML::Element
typedef Handle_t::Elt_t Elt_t
Simplification type declarations.
Public Attributes inherited from DD4hep::XML::Element
Handle_t m_element
The underlying object holding the XmlElement pointer.
Detailed Description
XML Handle class extending the XML handle Dimension.
Helper class to access any field in a xml tag. Specialized for some of the attributes of a detector element.
Author
M.Frank
Version
1.0
Definition at line 69 of file XMLDetector.h.
Constructor & Destructor Documentation
DetElement()
DD4hep::XML::DetElement::DetElement (Handle_t e) inline
Constructor from Handle.
Definition at line 71 of file XMLDetector.h.
Member Function Documentation
attr()
template<typename T > T DD4hep::XML::DetElement::attr (const XmlChar * tag_value) const inline
Access attribute by type.
Definition at line 94 of file XMLDetector.h.
References DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector().
check()
void DetElement::check (bool condition, const std::string & msg) const
Helper to check a condition (for debugging)
Definition at line 75 of file XMLDetector.cpp.
handle()
Handle_t DD4hep::XML::DetElement::handle () const inline
Access underlying XML handle object.
Definition at line 75 of file XMLDetector.h.
References DD4hep::XML::Dimension::id(), DD4hep::XML::Component::isSensitive(), DD4hep::XML::Element::m_element, and DD4hep::XML::Component::materialStr().
id()
int DetElement::id () const
Access parameters: id.
Definition at line 57 of file XMLDetector.cpp.
References _U.
Referenced by create_detector(), and create_element().
isCalorimeter()
bool DetElement::isCalorimeter () const
Check if element describes a calorimetric detector.
Definition at line 91 of file XMLDetector.cpp.
References _U.
isInsideTrackingVolume()
bool DetElement::isInsideTrackingVolume () const
Check if element is inside the tracking volume.
Definition at line 101 of file XMLDetector.cpp.
References _U.
isSensitive()
bool DetElement::isSensitive () const
Check if xml detector element is sensitive.
Definition at line 61 of file XMLDetector.cpp.
References _U.
Referenced by create_detector(), and create_element().
isTracker()
bool DetElement::isTracker () const
Check if element describes a tracking detector.
Definition at line 81 of file XMLDetector.cpp.
References _U.
materialStr()
string DetElement::materialStr () const
Access material attribute as STL string. If not present empty return empty string.
Definition at line 67 of file XMLDetector.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::child(), and DD4hep::XML::Handle_t::hasAttr().
Referenced by create_detector(), and create_element().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLDetector.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLDetector.cpp