DD4hep: DD4hep::DDEveHitActor Struct Reference
DD4hep::DDEveHitActor Struct Reference abstract
DDEve: DD4hep event display components, classes and objects
Event data actor base class for hits. Used to extract data from concrete classes.
#include <EventHandler.h>
Public Member Functions
virtual ~DDEveHitActor ()
virtual void operator() (const DDEveHit &)=0
virtual void setSize (size_t)
Detailed Description
Event data actor base class for hits. Used to extract data from concrete classes.
Author
M.Frank
Version
1.0
Definition at line 44 of file EventHandler.h.
Constructor & Destructor Documentation
~DDEveHitActor()
virtual DD4hep::DDEveHitActor::~DDEveHitActor () inline virtual
Definition at line 45 of file EventHandler.h.
References operator()().
Member Function Documentation
operator()()
virtual void DD4hep::DDEveHitActor::operator() (const DDEveHit &) pure virtual
Implemented in DD4hep::TowersetCreator, DD4hep::BoxsetCreator, DD4hep::PointsetCreator, and DD4hep::EtaPhiHistogramActor.
Referenced by ~DDEveHitActor(), and DD4hep::DDEveParticleActor::~DDEveParticleActor().
setSize()
virtual void DD4hep::DDEveHitActor::setSize (size_t) inline virtual
Definition at line 47 of file EventHandler.h.
Referenced by DD4hep::LCIOEventHandler::collectionLoop(), and DD4hep::DDG4EventHandler::collectionLoop().
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/EventHandler.h