DD4hep: DD4hep::Printer< T > Class Template Reference
DD4hep::Printer< T > Class Template Reference
Helper class template to implement ASCII object dumps.
#include <DD4hep/compact/Conversions.h>
Public Member Functions
Printer (const Geometry::LCDD *l, std::ostream &stream, const std::string &p="")
Initializing constructor of the functor.
void operator() (const T &value) const
Callback operator to be specialized depending on the element type.
template<>
void operator() (const Handle< NamedObject > &val) const
template<>
void operator() (const Handle< TNamed > &val) const
template<>
void operator() (const Constant &val) const
template<>
void operator() (const Material &val) const
template<>
void operator() (const VisAttr &val) const
template<>
void operator() (const Readout &val) const
template<>
void operator() (const Region &val) const
template<>
void operator() (const RotationZYX &val) const
template<>
void operator() (const Position &val) const
template<>
void operator() (const Condition &val) const
template<>
void operator() (const LCDD *const &) const
Public Attributes
const Geometry::LCDD * lcdd
Reference to the detector description object.
std::ostream & os
Reference to the output stream object, the Printer object should write.
std::string prefix
Optional text prefix when formatting the output.
Detailed Description
template<typename T>
class DD4hep::Printer< T >
Helper class template to implement ASCII object dumps.
Small helper class to print objects
Author
M.Frank
Version
1.0
Definition at line 208 of file Printout.h.
Constructor & Destructor Documentation
Printer()
template<typename T> DD4hep::Printer< T >::Printer (const Geometry::LCDD * l, std::ostream & stream, const std::string & p = "") inline
Initializing constructor of the functor.
Definition at line 216 of file Printout.h.
Member Function Documentation
operator()() [1/12]
template<> void DD4hep::Printer< Handle< NamedObject > >::operator() (const Handle< NamedObject > & val) const
Definition at line 43 of file ObjectPrintout.cpp.
References DD4hep::INFO, and DD4hep::printout().
operator()() [2/12]
template<> void DD4hep::Printer< Handle< TNamed > >::operator() (const Handle< TNamed > & val) const
Definition at line 46 of file ObjectPrintout.cpp.
References DD4hep::INFO, and DD4hep::printout().
operator()() [3/12]
template<> void DD4hep::Printer< Constant >::operator() (const Constant & val) const
Definition at line 50 of file ObjectPrintout.cpp.
References DD4hep::INFO, DD4hep::printout(), and DD4hep::Geometry::Constant::toString().
operator()() [4/12]
template<> void DD4hep::Printer< Material >::operator() (const Material & val) const
Definition at line 54 of file ObjectPrintout.cpp.
References DD4hep::INFO, DD4hep::printout(), and DD4hep::Geometry::Material::toString().
operator()() [5/12]
template<> void DD4hep::Printer< VisAttr >::operator() (const VisAttr & val) const
Definition at line 58 of file ObjectPrintout.cpp.
References DD4hep::INFO, DD4hep::printout(), and DD4hep::Geometry::VisAttr::toString().
operator()() [6/12]
template<> void DD4hep::Printer< Readout >::operator() (const Readout & val) const
Definition at line 62 of file ObjectPrintout.cpp.
References DD4hep::INFO, and DD4hep::printout().
operator()() [7/12]
template<> void DD4hep::Printer< Region >::operator() (const Region & val) const
Definition at line 66 of file ObjectPrintout.cpp.
References DD4hep::INFO, and DD4hep::printout().
operator()() [8/12]
template<> void DD4hep::Printer< RotationZYX >::operator() (const RotationZYX & val) const
Definition at line 70 of file ObjectPrintout.cpp.
References DD4hep::INFO, and DD4hep::printout().
operator()() [9/12]
template<> void DD4hep::Printer< Position >::operator() (const Position & val) const
Definition at line 75 of file ObjectPrintout.cpp.
References DD4hep::INFO, and DD4hep::printout().
operator()() [10/12]
template<> void DD4hep::Printer< Condition >::operator() (const Condition & val) const
Definition at line 78 of file ObjectPrintout.cpp.
References DD4hep::Geometry::DetElement::children(), DD4hep::Geometry::VisAttrObject::color, DD4hep::Geometry::DetElement::combineHits(), DD4hep::Handle< T >::data(), DD4hep::Geometry::VisAttrObject::drawingStyle, DD4hep::Geometry::DetElement::id(), DD4hep::INFO, DD4hep::Handle< T >::isValid(), DD4hep::Geometry::LimitSet::limits(), DD4hep::Geometry::VisAttrObject::lineStyle, m, DD4hep::Geometry::PlacedVolume::material(), DD4hep::Geometry::Volume::material(), DD4hep::Geometry::PlacedVolume::motherVol(), DD4hep::Geometry::Solid_type< T >::name(), DD4hep::Handle< T >::name(), DD4hep::Geometry::DetElement::placement(), DD4hep::printout(), s, DD4hep::Geometry::VisAttrObject::showDaughters, DD4hep::Geometry::Volume::solid(), DD4hep::Conditions::Condition::str(), DD4hep::Geometry::DetElement::type(), v, DD4hep::Geometry::Volume::visAttributes(), DD4hep::Geometry::VisAttrObject::visible, DD4hep::Geometry::PlacedVolume::volume(), and DD4hep::yes_no().
operator()() [11/12]
template<> void DD4hep::Printer< const LCDD * >::operator() (const LCDD *const &) const
Definition at line 134 of file ObjectPrintout.cpp.
operator()() [12/12]
template<typename T> void DD4hep::Printer< T >::operator() (const T & value) const
Callback operator to be specialized depending on the element type.
Member Data Documentation
lcdd
template<typename T> const Geometry::LCDD* DD4hep::Printer< T >::lcdd
Reference to the detector description object.
Definition at line 210 of file Printout.h.
os
template<typename T> std::ostream& DD4hep::Printer< T >::os
Reference to the output stream object, the Printer object should write.
Definition at line 212 of file Printout.h.
prefix
template<typename T> std::string DD4hep::Printer< T >::prefix
Optional text prefix when formatting the output.
Definition at line 214 of file Printout.h.
The documentation for this class was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Printout.h