DD4hep: DD4hep::Simulation::GeantinoRejectFilter Struct Reference
DD4hep::Simulation::GeantinoRejectFilter Struct Reference
Geant4 sensitive detector filter implementing a Geantino rejector.
Public Member Functions
GeantinoRejectFilter (Geant4Context *c, const std::string &n)
Constructor.
virtual ~GeantinoRejectFilter ()
Standard destructor.
virtual bool operator() (const G4Step *step) const
Filter action. Return true if hits should be processed.
Public Member Functions inherited from DD4hep::Simulation::ParticleFilter
ParticleFilter (Geant4Context *context, const std::string &name)
Constructor.
virtual ~ParticleFilter ()
Standard destructor.
const G4ParticleDefinition * definition () const
Safe access to the definition.
bool isSameType (const G4Track *track) const
Check if a track is of the same type.
bool isGeantino (const G4Track *track) const
Check if the particle is a geantino.
Public Member Functions inherited from DD4hep::Simulation::Geant4Filter
Geant4Filter (Geant4Context *context, const std::string &name)
Standard constructor.
virtual ~Geant4Filter ()
Standard destructor.
Public Member Functions inherited from DD4hep::Simulation::Geant4Action
Geant4Action (Geant4Context *context, const std::string &nam)
Standard constructor.
long addRef ()
Increase reference count.
long release ()
Decrease reference count. Implicit destruction.
Geant4Context * context () const
Access the context.
virtual void updateContext (Geant4Context *ctxt)
Set or update client context.
virtual void configureFiber (Geant4Context *thread_context)
Set or update client for the use in a new thread fiber.
const std::string & name () const
Access name of the action.
const char * c_name () const
Access name of the action.
void setName (const std::string &new_name)
Set the object name.
PropertyManager & properties ()
Access to the properties of the object.
PrintLevel outputLevel () const
Access the output level.
PrintLevel setOutputLevel (PrintLevel new_level)
Set the output level; returns previous value.
Geant4UIMessenger * control () const
Access to the UI messenger.
virtual void enableUI ()
Enable and install UI messenger.
template<typename T >
Geant4Action & declareProperty (const std::string &nam, T &val)
Declare property.
template<typename T >
Geant4Action & declareProperty (const char *nam, T &val)
Declare property.
bool hasProperty (const std::string &name) const
Check property for existence.
Property & property (const std::string &name)
Access single property.
Geant4Action & setProperties (PropertyConfigurator &setup)
Set object properties.
virtual void installMessengers ()
Install property control messenger if wanted.
virtual void installCommandMessenger ()
Install command control messenger if wanted.
virtual void installPropertyMessenger ()
Install property control messenger if wanted.
void print (const char *fmt,...) const
Support for messages with variable output level using output level.
void printM1 (const char *fmt,...) const
Support for messages with variable output level using output level-1.
void printM2 (const char *fmt,...) const
Support for messages with variable output level using output level-2.
void printP1 (const char *fmt,...) const
Support for messages with variable output level using output level+1.
void printP2 (const char *fmt,...) const
Support for messages with variable output level using output level+2.
void debug (const char *fmt,...) const
Support of debug messages.
void info (const char *fmt,...) const
Support of info messages.
void warning (const char *fmt,...) const
Support of warning messages.
void error (const char *fmt,...) const
Support of error messages.
bool return_error (bool return_value, const char *fmt,...) const
Action to support error messages.
void fatal (const char *fmt,...) const
Support of fatal messages. Throws exception.
void except (const char *fmt,...) const
Support of exceptions: Print fatal message and throw runtime_error.
void abortRun (const std::string &exception, const char *fmt,...) const
Abort Geant4 Run by throwing a G4Exception with type RunMustBeAborted.
Geant4RunActionSequence & runAction () const
Access to the main run action sequence from the kernel object.
Geant4EventActionSequence & eventAction () const
Access to the main event action sequence from the kernel object.
Geant4SteppingActionSequence & steppingAction () const
Access to the main stepping action sequence from the kernel object.
Geant4TrackingActionSequence & trackingAction () const
Access to the main tracking action sequence from the kernel object.
Geant4StackingActionSequence & stackingAction () const
Access to the main stacking action sequence from the kernel object.
Geant4GeneratorActionSequence & generatorAction () const
Access to the main generator action sequence from the kernel object.
Additional Inherited Members
Protected Member Functions inherited from DD4hep::Simulation::Geant4Action
virtual ~Geant4Action ()
Default destructor.
Protected Attributes inherited from DD4hep::Simulation::ParticleFilter
std::string m_particle
name of the particle to be filtered
G4ParticleDefinition * m_definition
Corresponding geant4 particle definiton.
Protected Attributes inherited from DD4hep::Simulation::Geant4Action
Geant4Context * m_context
Reference to the Geant4 context.
Geant4UIMessenger * m_control
Control directory of this action.
int m_outputLevel
Default property: Output level.
bool m_needsControl
Default property: Flag to create control instance.
std::string m_name
Action name.
PropertyManager m_properties
Property pool.
long m_refCount
Reference count. Initial value: 1.
Detailed Description
Geant4 sensitive detector filter implementing a Geantino rejector.
Author
M.Frank
Version
1.0
Definition at line 88 of file Geant4SensDetFilters.cpp.
Constructor & Destructor Documentation
GeantinoRejectFilter()
GeantinoRejectFilter::GeantinoRejectFilter (Geant4Context * c, const std::string & n)
Constructor.
Definition at line 181 of file Geant4SensDetFilters.cpp.
References DD4hep::InstanceCount::increment().
~GeantinoRejectFilter()
GeantinoRejectFilter::~GeantinoRejectFilter () virtual
Standard destructor.
Definition at line 187 of file Geant4SensDetFilters.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
operator()()
bool GeantinoRejectFilter::operator() (const G4Step * step) const virtual
Filter action. Return true if hits should be processed.
Reimplemented from DD4hep::Simulation::Geant4Filter.
Definition at line 192 of file Geant4SensDetFilters.cpp.
References DD4hep::Simulation::ParticleFilter::isGeantino().
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDG4/plugins/Geant4SensDetFilters.cpp