DD4hep: DD4hep::EtaPhiHistogramActor Struct Reference
DD4hep::EtaPhiHistogramActor Struct Reference
Fill EtaPhi histograms from a hit collection.
#include <HitActors.h>
Public Member Functions
EtaPhiHistogramActor (TH2F *h)
Standard initializing constructor.
virtual void operator() (const DDEveHit &hit)
Action callback of this functor:
Public Member Functions inherited from DD4hep::DDEveHitActor
virtual ~DDEveHitActor ()
virtual void setSize (size_t)
Public Attributes
TH2F * histogram
Detailed Description
Fill EtaPhi histograms from a hit collection.
Definition at line 36 of file HitActors.h.
Constructor & Destructor Documentation
EtaPhiHistogramActor()
DD4hep::EtaPhiHistogramActor::EtaPhiHistogramActor (TH2F * h) inline
Standard initializing constructor.
Definition at line 39 of file HitActors.h.
References operator()().
Member Function Documentation
operator()()
void EtaPhiHistogramActor::operator() (const DDEveHit & hit) virtual
Action callback of this functor:
Implements DD4hep::DDEveHitActor.
Definition at line 31 of file HitActors.cpp.
References DD4hep::DDEveHit::deposit, MM_2_CM, DD4hep::DDEveHit::x, DD4hep::DDEveHit::y, and DD4hep::DDEveHit::z.
Referenced by EtaPhiHistogramActor(), and DD4hep::TowersetCreator::~TowersetCreator().
Member Data Documentation
histogram
TH2F* DD4hep::EtaPhiHistogramActor::histogram
Definition at line 37 of file HitActors.h.
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/HitActors.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/src/HitActors.cpp