DD4hep: DD4hep::Converter< T, ARG > Struct Template Reference
DD4hep::Converter< T, ARG > Struct Template Reference
DD4hep::XML classes and objects
Basic conversion objects for handling DD4hep XML files.
#include <Conversions.h>
Public Types
typedef T to_type
typedef void * user_param
Public Member Functions
Converter (Geometry::LCDD &l)
Initializing constructor of the functor.
Converter (Geometry::LCDD &l, user_param p)
Initializing constructor of the functor with initialization of the user parameter.
Converter (Geometry::LCDD &l, user_param p, user_param o)
Initializing constructor of the functor with initialization of the user parameter.
void operator() (ARG handle) const
Callback operator to be specialized depending on the element type.
template<typename TYPE >
TYPE * _param () const
Typed access to the 1rst. user parameter (unchecked)
template<typename TYPE >
TYPE & _object () const
Typed object access to the 1rst. user parameter (unchecked)
template<typename TYPE >
TYPE * _option () const
Typed access to the 2nd. user parameter (unchecked)
template<>
void operator() (xml_h e) const
Convert Geant4Action objects.
template<>
void operator() (xml_h e) const
Convert Sensitive detector filters.
template<>
void operator() (xml_h e) const
Convert Geant4Phase objects.
template<>
void operator() (xml_h e) const
Convert Action sequences into objects.
template<>
void operator() (xml_h e) const
Create/Configure PhysicsList objects.
template<>
void operator() (xml_h e) const
Create/Configure PhysicsList objects: Particle constructors.
template<>
void operator() (xml_h e) const
Create/Configure PhysicsList objects: Physics constructors.
template<>
void operator() (xml_h e) const
template<>
void operator() (xml_h e) const
Create/Configure PhysicsList objects: Predefined Geant4 Physics lists.
template<>
void operator() (xml_h e) const
Create/Configure Geant4Kernel objects.
template<>
void operator() (xml_h seq) const
Main entry point to configure Geant4 with XML.
template<>
void operator() (xml_h seq) const
Forward declarations for all specialized converters.
template<>
void operator() (xml_h seq) const
template<>
void operator() (xml_h seq) const
template<>
void operator() (xml_h seq) const
template<>
void operator() (xml_h seq) const
template<>
void operator() (xml_h e) const
template<>
void operator() (xml_h e) const
template<>
void operator() (xml_h e) const
template<>
void operator() (xml_h e) const
template<>
void operator() (xml_h seq) const
Public Attributes
Geometry::LCDD & lcdd
Reference to the detector description object.
user_param param
Reference to optional user defined parameter.
user_param optional
Detailed Description
template<typename T, typename ARG = XML::Handle_t>
struct DD4hep::Converter< T, ARG >
Basic conversion objects for handling DD4hep XML files.
Author
M.Frank
Version
1.0
Definition at line 38 of file Conversions.h.
Member Typedef Documentation
to_type
template<typename T, typename ARG = XML::Handle_t> typedef T DD4hep::Converter< T, ARG >::to_type
Definition at line 39 of file Conversions.h.
user_param
template<typename T, typename ARG = XML::Handle_t> typedef void* DD4hep::Converter< T, ARG >::user_param
Definition at line 40 of file Conversions.h.
Constructor & Destructor Documentation
Converter() [1/3]
template<typename T, typename ARG = XML::Handle_t> DD4hep::Converter< T, ARG >::Converter (Geometry::LCDD & l) inline
Initializing constructor of the functor.
Definition at line 47 of file Conversions.h.
Converter() [2/3]
template<typename T, typename ARG = XML::Handle_t> DD4hep::Converter< T, ARG >::Converter (Geometry::LCDD & l, user_param p) inline
Initializing constructor of the functor with initialization of the user parameter.
Definition at line 49 of file Conversions.h.
Converter() [3/3]
template<typename T, typename ARG = XML::Handle_t> DD4hep::Converter< T, ARG >::Converter (Geometry::LCDD & l, user_param p, user_param o) inline
Initializing constructor of the functor with initialization of the user parameter.
Definition at line 51 of file Conversions.h.
References handle().
Member Function Documentation
_object()
template<typename T, typename ARG = XML::Handle_t> template<typename TYPE > TYPE& DD4hep::Converter< T, ARG >::_object () const inline
Typed object access to the 1rst. user parameter (unchecked)
Definition at line 57 of file Conversions.h.
_option()
template<typename T, typename ARG = XML::Handle_t> template<typename TYPE > TYPE* DD4hep::Converter< T, ARG >::_option () const inline
Typed access to the 2nd. user parameter (unchecked)
Definition at line 59 of file Conversions.h.
_param()
template<typename T, typename ARG = XML::Handle_t> template<typename TYPE > TYPE* DD4hep::Converter< T, ARG >::_param () const inline
Typed access to the 1rst. user parameter (unchecked)
Definition at line 55 of file Conversions.h.
operator()() [1/22]
template<> void DD4hep::Converter< ddeve >::operator() (xml_h seq) const
Forward declarations for all specialized converters.
operator()() [2/22]
template<typename T, typename ARG = XML::Handle_t> void DD4hep::Converter< T, ARG >::operator() (ARG handle) const
Callback operator to be specialized depending on the element type.
operator()() [3/22]
template<> void DD4hep::Converter< display >::operator() (xml_h seq) const
operator()() [4/22]
template<> void DD4hep::Converter< view >::operator() (xml_h seq) const
operator()() [5/22]
template<> void DD4hep::Converter< panel >::operator() (xml_h seq) const
operator()() [6/22]
template<> void DD4hep::Converter< include >::operator() (xml_h seq) const
operator()() [7/22]
template<> void DD4hep::Converter< calodata >::operator() (xml_h e) const
operator()() [8/22]
template<> void DD4hep::Converter< calodata_configs >::operator() (xml_h e) const
operator()() [9/22]
template<> void DD4hep::Converter< collection >::operator() (xml_h e) const
operator()() [10/22]
template<> void DD4hep::Converter< collection_configs >::operator() (xml_h e) const
operator()() [11/22]
template<> void DD4hep::Converter< detelement >::operator() (xml_h seq) const
operator()() [12/22]
template<> void DD4hep::Converter< Action >::operator() (xml_h e) const
Convert Geant4Action objects.
<actions> <action name="Geant4PostTrackingAction/PostTrackAction" <properties name1="Value1" name2="Value2"> </action> </actions>
Definition at line 151 of file Geant4XMLSetup.cpp.
References DD4hep::Simulation::_convertAction(), DD4hep::Simulation::Geant4Kernel::instance(), and DD4hep::Simulation::Geant4Kernel::registerGlobalAction().
operator()() [13/22]
template<> void DD4hep::Converter< Filter >::operator() (xml_h e) const
Convert Sensitive detector filters.
Note: Filters are Geant4Actions and - if global - may also receive properties!
<filters> <filter name="GeantinoRejector"> <filter name="EnergyDepositMinimumCut"> <properties cut="10*MeV"> </filter> </filters>
Definition at line 167 of file Geant4XMLSetup.cpp.
References DD4hep::Simulation::_convertAction(), DD4hep::Simulation::Geant4Kernel::instance(), and DD4hep::Simulation::Geant4Kernel::registerGlobalFilter().
operator()() [14/22]
template<> void DD4hep::Converter< Phase >::operator() (xml_h e) const
Convert Geant4Phase objects.
<phases> <phase name="Geant4PostTrackingPhase/PostTrackPhase" <properties name1="Value1" name2="Value2"> </phase> </phases>
Definition at line 182 of file Geant4XMLSetup.cpp.
References _U, DD4hep::Simulation::Geant4Kernel::addPhase(), DD4hep::XML::Element::attr(), DD4hep::Simulation::Geant4SteppingActionSequence::call(), DD4hep::Simulation::Geant4GeneratorActionSequence::call(), DD4hep::Simulation::Geant4ActionPhase::call(), DD4hep::Simulation::Geant4RunActionSequence::callAtBegin(), DD4hep::Simulation::Geant4EventActionSequence::callAtBegin(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtBegin(), DD4hep::Simulation::Geant4RunActionSequence::callAtEnd(), DD4hep::Simulation::Geant4EventActionSequence::callAtEnd(), DD4hep::Simulation::Geant4TrackingActionSequence::callAtEnd(), DD4hep::Simulation::Geant4StackingActionSequence::callAtNewStage(), DD4hep::Simulation::Geant4StackingActionSequence::callAtPrepare(), DD4hep::Simulation::Geant4ActionContainer::eventAction(), DD4hep::format(), DD4hep::Simulation::Geant4ActionContainer::generatorAction(), DD4hep::Simulation::Geant4Kernel::instance(), DD4hep::Handle< T >::isValid(), DD4hep::Simulation::Geant4ActionContainer::runAction(), DD4hep::Simulation::TypeName::split(), DD4hep::Simulation::Geant4ActionContainer::stackingAction(), DD4hep::Simulation::Geant4ActionContainer::steppingAction(), and DD4hep::Simulation::Geant4ActionContainer::trackingAction().
operator()() [15/22]
template<> void DD4hep::Converter< ActionSequence >::operator() (xml_h e) const
Convert Action sequences into objects.
<sequences> <sequence name="Geant4EventActionSequence/EventAction" <member name="" type="Geant4TrackerEventMonitor/TrackerEvtAction"> </sequence> <sequence name="Geant4SensdetActionSequence/SiVertexBarrel" <member type="Geant4TrackerSensitiveMonitor/TrackerHitMonitor"> <properties name1="Value1" name2="Value2"> </member> </sequence> </sequences>
Definition at line 285 of file Geant4XMLSetup.cpp.
References DD4hep::Simulation::_createAction(), DD4hep::Simulation::_setAttributes(), _U, _Unicode, DD4hep::Simulation::ACTION, DD4hep::Simulation::Geant4SteppingActionSequence::adopt(), DD4hep::Simulation::Geant4StackingActionSequence::adopt(), DD4hep::Simulation::Geant4GeneratorActionSequence::adopt(), DD4hep::Simulation::Geant4RunActionSequence::adopt(), DD4hep::Simulation::Geant4EventActionSequence::adopt(), DD4hep::Simulation::Geant4TrackingActionSequence::adopt(), DD4hep::Simulation::Geant4PhysicsListActionSequence::adopt(), DD4hep::ALWAYS, DD4hep::XML::Element::attr(), DD4hep::PropertyManager::dump(), DD4hep::Simulation::Geant4ActionContainer::eventAction(), DD4hep::Simulation::FILTER, DD4hep::format(), DD4hep::Simulation::Geant4ActionContainer::generatorAction(), DD4hep::Simulation::Geant4Handle< TYPE >::get(), DD4hep::XML::Element::hasAttr(), DD4hep::INFO, DD4hep::Simulation::installMessenger(), DD4hep::Simulation::Geant4Kernel::instance(), m, DD4hep::Simulation::Geant4ActionContainer::physicsList(), DD4hep::printout(), DD4hep::Simulation::Geant4Action::properties(), DD4hep::Simulation::Geant4ActionContainer::runAction(), DD4hep::Simulation::SENSITIVE, DD4hep::Simulation::TypeName::split(), DD4hep::Simulation::Geant4ActionContainer::stackingAction(), DD4hep::Simulation::Geant4ActionContainer::steppingAction(), and DD4hep::Simulation::Geant4ActionContainer::trackingAction().
operator()() [16/22]
template<> void DD4hep::Converter< Geant4PhysicsList::ParticleProcesses >::operator() (xml_h e) const
Create/Configure PhysicsList objects.
<physicslist> <processes> <particle name="'e-'"> <process name="G4eMultipleScattering" ordatrestdoit="-1" ordalongsteptdoit="1" ordpoststepdoit="1"> <process name="G4eIonisation" ordatrestdoit="-1" ordalongsteptdoit="2" ordpoststepdoit="2"> </particle> </processes> </physicslist>
Definition at line 379 of file Geant4XMLSetup.cpp.
References _Unicode, DD4hep::XML::Element::attr(), DD4hep::INFO, DD4hep::Simulation::Geant4PhysicsList::Process::name, DD4hep::XML::Dimension::nameStr(), DD4hep::Simulation::Geant4PhysicsList::Process::ordAlongSteptDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordAtRestDoIt, DD4hep::Simulation::Geant4PhysicsList::Process::ordPostStepDoIt, and DD4hep::printout().
operator()() [17/22]
template<> void DD4hep::Converter< Geant4PhysicsList::ParticleConstructor >::operator() (xml_h e) const
Create/Configure PhysicsList objects: Particle constructors.
<physicslist> <particles> <construct name="G4Electron"> <construct name="G4Gamma"> <construct name="G4BosonConstructor"> <construct name="G4LeptonConstructor"> <construct name="G4BaryonConstructor"> </particles> </physicslist>
Definition at line 409 of file Geant4XMLSetup.cpp.
References DD4hep::INFO, DD4hep::XML::Dimension::nameStr(), and DD4hep::printout().
operator()() [18/22]
template<> void DD4hep::Converter< Geant4PhysicsList::PhysicsConstructor >::operator() (xml_h e) const
Create/Configure PhysicsList objects: Physics constructors.
<physicslist> <physics> <construct name="G4EmStandardPhysics"> <construct name="HadronPhysicsQGSP"> </physics> </physicslist>
Definition at line 426 of file Geant4XMLSetup.cpp.
References DD4hep::INFO, DD4hep::XML::Dimension::nameStr(), and DD4hep::printout().
operator()() [19/22]
template<> void DD4hep::Converter< PhysicsListExtension >::operator() (xml_h e) const
Definition at line 442 of file Geant4XMLSetup.cpp.
References DD4hep::INFO, DD4hep::Simulation::Geant4Kernel::instance(), DD4hep::XML::Dimension::nameStr(), DD4hep::Simulation::Geant4ActionContainer::physicsList(), DD4hep::printout(), and DD4hep::Simulation::Geant4Action::properties().
operator()() [20/22]
template<> void DD4hep::Converter< PhysicsList >::operator() (xml_h e) const
Create/Configure PhysicsList objects: Predefined Geant4 Physics lists.
Definition at line 450 of file Geant4XMLSetup.cpp.
References DD4hep::Simulation::_setAttributes(), _U, _Unicode, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Collection_t::for_each(), DD4hep::Simulation::Geant4Handle< TYPE >::get(), handle(), and DD4hep::Simulation::Geant4Kernel::instance().
operator()() [21/22]
template<> void DD4hep::Converter< Kernel >::operator() (xml_h e) const
Create/Configure Geant4Kernel objects.
Definition at line 463 of file Geant4XMLSetup.cpp.
References _Unicode, DD4hep::XML::Element::attr(), DD4hep::XML::Element::hasAttr(), DD4hep::Simulation::Geant4Kernel::instance(), DD4hep::Simulation::Geant4Kernel::property(), and DD4hep::Property::str().
operator()() [22/22]
template<> void DD4hep::Converter< XMLSetup >::operator() (xml_h seq) const
Main entry point to configure Geant4 with XML.
Definition at line 473 of file Geant4XMLSetup.cpp.
References _Unicode, DD4hep::XML::Collection_t::for_each(), and DD4hep::XML::Handle_t::tag().
Member Data Documentation
lcdd
template<typename T, typename ARG = XML::Handle_t> Geometry::LCDD& DD4hep::Converter< T, ARG >::lcdd
Reference to the detector description object.
Definition at line 42 of file Conversions.h.
optional
template<typename T, typename ARG = XML::Handle_t> user_param DD4hep::Converter< T, ARG >::optional
Definition at line 45 of file Conversions.h.
param
template<typename T, typename ARG = XML::Handle_t> user_param DD4hep::Converter< T, ARG >::param
Reference to optional user defined parameter.
Definition at line 44 of file Conversions.h.
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/Conversions.h