DD4hep: DD4hep::XML::Dimension Struct Reference
DD4hep::XML::Dimension Struct Reference
DD4hep::XML classes and objects
XML Handle to xml elements with predefined attribute access.
#include <XMLDimension.h>
Public Member Functions
Dimension ()
Default constructor.
Dimension (Handle_t e)
Constructor from Handle.
Dimension (const Element &e)
Constructor from Element.
int id () const
Access parameters: id.
int id (int default_value) const
Access parameters: id, if not present returns default.
int type () const
Access parameters: type.
bool combineHits () const
Access rotation constants: combineHits.
double angle () const
Access rotation constants: angle.
double alpha () const
Access rotation constants: alpha.
double alpha (double default_value) const
Access rotation constants: alpha.
double alpha1 () const
Access rotation constants: alpha1.
double alpha1 (double default_value) const
Access rotation constants: alpha1.
double alpha2 () const
Access rotation constants: alpha2.
double alpha2 (double default_value) const
Access rotation constants: alpha2.
double beta () const
Access rotation constants: angle.
double beta (double default_value) const
Access rotation constants: angle.
double gamma () const
Access rotation constants: angle.
double gamma (double default_value) const
Access rotation constants: angle.
double delta () const
Access rotation constants: angle.
double delta (double default_value) const
Access rotation constants: angle.
double epsilon () const
Access rotation constants: angle.
double epsilon (double default_value) const
Access rotation constants: angle.
double theta () const
Access rotation constants: theta.
double theta (double default_value) const
Access rotation constants: theta.
double deltatheta () const
Access rotation constants: deltatheta.
double deltatheta (double default_value) const
Access rotation constants: deltatheta.
int thetaBins () const
Access rotation constants: thetaBins.
double phi () const
Access rotation constants: phi.
double phi (double default_value) const
Access rotation constants: phi.
int phiBins () const
Access rotation constants: phiBins.
double phi0 () const
Access rotation constants: phi0.
double phi0 (double default_value) const
Access parameters: phi0, if not present returns default.
double phi0_offset () const
Access rotation constants: phi0_offset.
double phi0_offset (double default_value) const
Access parameters: phi0_offset, if not present returns default.
double phi1 () const
Access rotation constants: phi1.
double phi1 (double default_value) const
Access parameters: phi1, if not present returns default.
double psi () const
Access rotation constants: psi.
double psi (double default_value) const
Access rotation constants: psi.
double zhalf () const
Access Tube parameters: zhalf.
double deltaphi () const
Access Tube parameters: deltaphi.
double deltaphi (double default_value) const
Access Tube parameters: deltaphi.
double startphi () const
Access rotation constants: startphi.
double startphi (double default_value) const
Access rotation constants: startphi.
double a () const
Access parameters: a.
double a (double default_value) const
Access parameters: a.
double A () const
Access parameters: A.
double A (double default_value) const
Access parameters: A.
double b () const
Access parameters: b.
double b (double default_value) const
Access parameters: b.
double c () const
Access parameters: c.
double c (double default_value) const
Access parameters: c.
double distance () const
Access parameters: distance.
double distance (double default_value) const
Access parameters: distance.
double B () const
Access parameters: B.
double B (double default_value) const
Access parameters: B.
double g () const
Access parameters: g.
double g (double default_value) const
Access parameters: g.
double G () const
Access parameters: G.
double G (double default_value) const
Access parameters: G.
double I () const
Access parameters: I.
double I (double default_value) const
Access parameters: I.
double r () const
Access parameters: r.
double r (double default_value) const
Access parameters: r, if not present returns default.
double R () const
Access parameters: R.
double R (double default_value) const
Access parameters: R.
double dr () const
Access parameters: dr.
double dr (double default_value) const
Access parameters: dr, if not present returns default.
double r0 () const
Access parameters: r0.
double r0 (double default_value) const
Access parameters: r0.
double rmin () const
Access min/max parameters: rmin.
double rmin (double default_val) const
Access min/max parameters: rmin.
double rmax () const
Access min/max parameters: rmax.
double rmax (double default_val) const
Access min/max parameters: rmax.
double rmin1 () const
Access min/max parameters: rmin1.
double rmin1 (double default_val) const
Access min/max parameters: rmin1.
double rmax1 () const
Access min/max parameters: rmax1.
double rmax1 (double default_val) const
Access min/max parameters: rmax1.
double rmin2 () const
Access min/max parameters: rmin2.
double rmin2 (double default_val) const
Access min/max parameters: rmin2.
double rmax2 () const
Access min/max parameters: rmax2.
double rmax2 (double default_val) const
Access min/max parameters: rmax2.
double radius () const
Access parameters: radius.
double radius (double default_val) const
Access parameters: radius.
double outer_radius () const
Access attribute values: outer_radius.
double outer_r () const
Access attribute values: outer_r.
double inner_radius () const
Access attribute values: inner_radius.
double inner_r () const
Access attribute values: inner_r.
double x () const
Access parameters: x.
double x (double default_val) const
Access parameters: x, if not present returns default.
double X () const
Access parameters: X.
double X (double default_val) const
Access parameters: X.
double x0 () const
Access parameters: x0.
double x0 (double default_val) const
Access parameters: x0.
double x1 () const
Access parameters: x1.
double x1 (double default_val) const
Access parameters: x1.
double x2 () const
Access parameters: x2.
double x2 (double default_val) const
Access parameters: x2.
double x3 () const
Access parameters: x3.
double x3 (double default_val) const
Access parameters: x3.
double x4 () const
Access parameters: x4.
double x4 (double default_val) const
Access parameters: x4.
double dx () const
Access parameters: dx.
double dx (double default_value) const
Access parameters: dx, if not present returns default.
double xmin () const
Access min/max parameters: xmax.
double xmin (double default_value) const
Access min/max parameters: xmax.
double xmax () const
Access min/max parameters: xmax.
double xmax (double default_value) const
Access min/max parameters: xmax.
double x_offset () const
Access min/max parameters: x_offset.
double x_offset (double default_value) const
Access min/max parameters: x_offset.
double dim_x () const
Access min/max parameters: dim_x.
double dim_x (double default_value) const
Access min/max parameters: dim_x.
double y () const
Access parameters: y.
double y (double default_val) const
Access parameters: y, if not present returns default.
double Y () const
Access parameters: Y.
double Y (double default_val) const
Access parameters: Y.
double y0 () const
Access parameters: y0.
double y0 (double default_value) const
Access parameters: y0.
double y1 () const
Access parameters: y1.
double y1 (double default_value) const
Access parameters: y1.
double y2 () const
Access parameters: y2.
double y2 (double default_value) const
Access parameters: y2.
double dy () const
Access parameters: dy.
double dy (double default_value) const
Access parameters: dz, if not present returns default.
double ymin () const
Access min/max parameters: ymax.
double ymin (double default_value) const
Access min/max parameters: ymax.
double ymax () const
Access min/max parameters: ymax.
double ymax (double default_value) const
Access min/max parameters: ymax.
double y_offset () const
Access min/max parameters: y_offset.
double y_offset (double default_value) const
Access min/max parameters: y_offset.
double dim_y () const
Access min/max parameters: dim_y.
double dim_y (double default_value) const
Access min/max parameters: dim_y.
double z () const
Access parameters: z.
double z (double default_val) const
Access parameters: z, if not present returns default.
double Z () const
Access parameters: Z.
double Z (double default_val) const
Access parameters: Z.
double z0 () const
Access parameters: z0.
double z0 (double default_val) const
Access parameters: z0.
double z1 () const
Access parameters: z1.
double z1 (double default_val) const
Access parameters: z1.
double z2 () const
Access parameters: z2.
double z2 (double default_val) const
Access parameters: z2.
double dz () const
Access parameters: dz.
double dz (double default_value) const
Access parameters: dz, if not present returns default.
double zmin () const
Access min/max parameters: zmax.
double zmin (double default_value) const
Access min/max parameters: zmax.
double zmax () const
Access min/max parameters: zmax.
double zmax (double default_value) const
Access min/max parameters: zmax.
double outer_z () const
Access attribute values: outer_z.
double inner_z () const
Access attribute values: inner_z.
double outer_stereo () const
Access attribute values: outer_stereo.
double inner_stereo () const
Access attribute values: inner_stereo.
double z_offset () const
Access min/max parameters: z_offset.
double z_offset (double default_value) const
Access min/max parameters: z_offset.
double dim_z () const
Access min/max parameters: dim_z.
double dim_z (double default_value) const
Access min/max parameters: dim_z.
double length () const
Access attribute values: length.
double width () const
Access attribute values: width.
double height () const
Access attribute values: height.
double depth () const
Access attribute values: depth.
double thickness () const
Access attribute values: thickness.
double z_length () const
Access attribute values: z_length.
double gap () const
Access attribute values: gap.
double r_size () const
Access attribute values: r_size.
double phi_size_max () const
Access attribute values: phi_size_max.
bool reflect () const
Access attribute values: reflect.
bool reflect (bool default_value) const
Access attribute values: reflect.
double crossing_angle () const
Access attribute values: crossing_angle.
int repeat () const
Access attribute values: repeat.
double coefficient () const
Access attribute values: coefficient.
double coefficient (double default_value) const
Access attribute values: coefficient.
double skew () const
Access attribute values: skew.
double skew (double default_value) const
Access attribute values: skew.
double outgoing_r () const
Access attribute values: outgoing_r.
double incoming_r () const
Access attribute values: incoming_r.
double offset () const
Access attribute values: offset.
double offset (double default_value) const
Access attribute values: offset.
int number () const
Access attribute values: number.
int nmodules () const
Access attribute values: nmodules.
int nModules () const
Access attribute values: nModules.
int RowID () const
Access attribute values: RowID.
double moduleHeight () const
Access attribute values: moduleHeight.
double moduleWidth () const
Access attribute values: moduleWidth.
double modulePitch () const
Access attribute values: modulePitch.
double modulePosX () const
Access attribute values: modulePosX.
double modulePosY () const
Access attribute values: modulePosY.
int nPads () const
Access attribute values: nPads.
double rowPitch () const
Access attribute values: rowPitch.
double padPitch () const
Access attribute values: padPitch.
double rowHeight () const
Access attribute values: rowHeight.
std::string padType () const
Access attribute values: padType.
int numsides () const
Access attribute values: numsides.
int nsides () const
Access attribute values: nsides.
int nsides_inner () const
Access attribute values: nsides_inner.
int nsides_outer () const
Access attribute values: nsides_outer.
double phi_tilt () const
Access attribute values: phi_tilt.
int nphi () const
Access attribute values: nphi.
double rc () const
Access attribute values: rc.
double zstart () const
Access attribute values: zstart.
int nz () const
Access attribute values: nz.
int key () const
Access attribute values: key.
int key_min () const
Access attribute values: key_min.
int key_max () const
Access attribute values: key_max.
int key_val () const
Access attribute values: key_val.
int key_value () const
Access attribute values: key_value.
double start () const
Access attribute values: start.
double start (double default_value) const
Access attribute values: start.
double end () const
Access attribute values: end.
double end (double default_value) const
Access attribute values: end.
double inner_field () const
Access attribute values: inner_field.
double outer_field () const
Access attribute values: outer_field.
bool visible () const
Access attribute values: visible.
bool show_daughters () const
Access attribute values: show_daughters.
double cut () const
Access min/max parameters: cut.
double cut (double default_value) const
Access min/max parameters: cut.
double threshold () const
Access min/max parameters: threshold.
double threshold (double default_value) const
Access min/max parameters: threshold.
double eunit () const
Access min/max parameters: eunit.
double eunit (double default_value) const
Access min/max parameters: eunit.
double lunit () const
Access min/max parameters: lunit.
double lunit (double default_value) const
Access min/max parameters: lunit.
double temperature () const
Access rotation constants: temperature.
double temperature (double default_value) const
Access rotation constants: temperature.
double pressure () const
Access rotation constants: pressure.
double pressure (double default_value) const
Access rotation constants: pressure.
double density () const
Access rotation constants: density.
double density (double default_value) const
Access rotation constants: density.
Dimension dimensions (bool throw_if_not_present=true) const
Access child element with tag "dimensions" as Dimension object.
Dimension position (bool throw_if_not_present=true) const
Child access: position.
Dimension rotation (bool throw_if_not_present=true) const
Child access: rotation.
Dimension trd (bool throw_if_not_present=true) const
Child access: trd.
Dimension tubs (bool throw_if_not_present=true) const
Child access: tubs.
Dimension staves (bool throw_if_not_present=true) const
Child access: staves.
Dimension beampipe (bool throw_if_not_present=true) const
Child access: beampipe.
std::string nameStr () const
Access "name" attribute as STL string.
std::string refStr () const
Access "ref" attribute as a string.
std::string typeStr () const
Access "type" attribute as STL string.
std::string valueStr () const
Access "value" attribute as STL string.
std::string moduleStr () const
Access "module" attribute as STL string.
std::string readoutStr () const
Access "readout" attribute as STL string.
std::string visStr () const
Access vis attribute as STL string. If not present empty return empty string.
std::string regionStr () const
Access region attribute as STL string. If not present empty return empty string.
std::string limitsStr () const
Access limits attribute as STL string. If not present empty return empty string.
Public Member Functions inherited from DD4hep::XML::Element
Element (const Handle_t &e)
Constructor from XmlElement handle.
Element (const Element &e)
Constructor from XmlElement handle.
Element (const Document &document, const XmlChar *type)
Constructor from DOM document entity.
Document document () const
Access the hosting document handle of this DOM element.
operator bool () const
operator bool: check handle validity
bool operator! () const
operator NOT: check handle validity
Element & operator= (const Element &c)
Assignment operator.
Element & operator= (Handle_t handle)
Assignment operator.
operator Handle_t () const
Automatic conversion to DOM element handle.
operator Elt_t () const
Automatic conversion to XmlElement pointer.
Elt_t ptr () const
Access to XmlElement pointer.
Handle_t parent () const
Access the XmlElements parent.
Elt_t parentElement () const
Access the XmlElements parent.
std::string tag () const
Access the tag name of this DOM element.
const XmlChar * tagName () const
Access the tag name of this DOM element.
void append (Handle_t handle) const
Append a new element to the existing tree.
Handle_t clone (const Document &new_doc) const
Clone the DOMelement.
bool hasAttr (const XmlChar *name) const
Check for the existence of a named attribute.
template<class T >
T attr (const XmlChar *tag_value) const
Access attribute with implicit return type conversion.
template<class T >
T attr (const char *name) const
Access typed attribute value by it's name.
const XmlChar * attr_name (const Attribute a) const
Access attribute name (throws exception if not present)
const XmlChar * attr_value (const Attribute a) const
Access attribute value by the attribute (throws exception if not present)
size_t numChildren (const XmlChar *tag_value, bool exc=true) const
Access the number of children of this DOM element with a given tag name.
void setAttrs (Handle_t e) const
Remove own attributes and copy all attributes from handle 'e'.
void removeAttrs () const
Remove all attributes of this element.
std::vector< Attribute > attributes () const
Retrieve a collection of all attributes of this DOM element.
Attribute getAttr (const XmlChar *name) const
Access single attribute by it's name.
template<class T >
Attribute setAttr (const XmlChar *nam, const T &val) const
Set single attribute.
template<class T >
void setValue (const T &val) const
Set element value.
Handle_t clone (Handle_t h) const
Clone the DOM element tree.
Handle_t addChild (const XmlChar *tag) const
Add a new child to the DOM node.
Handle_t setChild (const XmlChar *tag) const
Check if a child with the required tag exists - if not create it and add it to the current node.
Handle_t child (const Strng_t &tag_value, bool except=true) const
Access child by tag name. Thow an exception if required in case the child is not present.
Handle_t remove (Handle_t node) const
Remove a child node identified by its handle.
bool hasChild (const XmlChar *tag_value) const
Check the existence of a child with a given tag name.
Attribute setRef (const XmlChar *tag, const XmlChar *refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
Attribute setRef (const XmlChar *tag, const std::string &refname) const
Set the reference attribute to the node (adds attribute ref="ref-name")
const XmlChar * getRef (const XmlChar *tag) const
Access the value of the reference attribute of the node (attribute ref="ref-name")
void addComment (const char *text) const
Add comment node to the element.
Additional Inherited Members
Public Types inherited from DD4hep::XML::Element
typedef Handle_t::Elt_t Elt_t
Simplification type declarations.
Public Attributes inherited from DD4hep::XML::Element
Handle_t m_element
The underlying object holding the XmlElement pointer.
Detailed Description
XML Handle to xml elements with predefined attribute access.
Helper class to access any field in a xml tag in a very easy way.
You may assign any xml handle to a dimension object
Any attribute of this xml element may then be accessed by it's natural way. All possible attribute names are reflected by the Dimension object's member functions.
If an attribute is requested and not present, a exception is thrown.
Functions, which accept a default value do NOT throw an exception if the attribute is not present. These rather return the default value.
If a often used function is not present - the implementation thereof is simple.
Such helper classes may be defined locally by any user since XML element handles may easily be transferred. Run-time exceptions occur however, if non-exiting attributes are accessed.
Author
M.Frank
Version
1.0
Definition at line 52 of file XMLDimension.h.
Constructor & Destructor Documentation
Dimension() [1/3]
DD4hep::XML::Dimension::Dimension () inline
Default constructor.
Definition at line 54 of file XMLDimension.h.
Dimension() [2/3]
DD4hep::XML::Dimension::Dimension (Handle_t e) inline
Constructor from Handle.
Definition at line 58 of file XMLDimension.h.
Dimension() [3/3]
DD4hep::XML::Dimension::Dimension (const Element & e) inline
Constructor from Element.
Definition at line 62 of file XMLDimension.h.
References a(), A(), alpha(), alpha1(), alpha2(), angle(), b(), B(), beampipe(), beta(), c(), coefficient(), combineHits(), crossing_angle(), cut(), delta(), deltaphi(), deltatheta(), density(), depth(), dim_x(), dim_y(), dim_z(), dimensions(), distance(), dr(), dx(), dy(), dz(), end(), epsilon(), eunit(), g(), G(), gamma(), gap(), height(), I(), id(), incoming_r(), inner_field(), inner_r(), inner_radius(), inner_stereo(), inner_z(), key(), key_max(), key_min(), key_val(), key_value(), length(), limitsStr(), lunit(), moduleHeight(), modulePitch(), modulePosX(), modulePosY(), moduleStr(), moduleWidth(), nameStr(), nmodules(), nModules(), nPads(), nphi(), nsides(), nsides_inner(), nsides_outer(), number(), numsides(), nz(), offset(), outer_field(), outer_r(), outer_radius(), outer_stereo(), outer_z(), outgoing_r(), padPitch(), padType(), phi(), phi0(), phi0_offset(), phi1(), phi_size_max(), phi_tilt(), phiBins(), position(), pressure(), psi(), r(), R(), r0(), r_size(), radius(), rc(), readoutStr(), reflect(), refStr(), regionStr(), repeat(), rmax(), rmax1(), rmax2(), rmin(), rmin1(), rmin2(), rotation(), rowHeight(), RowID(), rowPitch(), show_daughters(), skew(), start(), startphi(), staves(), temperature(), theta(), thetaBins(), thickness(), threshold(), trd(), tubs(), type(), typeStr(), valueStr(), visible(), visStr(), width(), x(), X(), x0(), x1(), x2(), x3(), x4(), x_offset(), xmax(), xmin(), y(), Y(), y0(), y1(), y2(), y_offset(), ymax(), ymin(), z(), Z(), z0(), z1(), z2(), z_length(), z_offset(), zhalf(), zmax(), zmin(), and zstart().
Member Function Documentation
a() [1/2]
double DD4hep::XML::Dimension::a () const
Access parameters: a.
Referenced by Dimension().
a() [2/2]
double DD4hep::XML::Dimension::a (double default_value) const
Access parameters: a.
A() [1/2]
double DD4hep::XML::Dimension::A () const
Access parameters: A.
Referenced by Dimension().
A() [2/2]
double DD4hep::XML::Dimension::A (double default_value) const
Access parameters: A.
alpha() [1/2]
double DD4hep::XML::Dimension::alpha () const
Access rotation constants: alpha.
Referenced by Dimension().
alpha() [2/2]
double DD4hep::XML::Dimension::alpha (double default_value) const
Access rotation constants: alpha.
alpha1() [1/2]
double DD4hep::XML::Dimension::alpha1 () const
Access rotation constants: alpha1.
Referenced by Dimension().
alpha1() [2/2]
double DD4hep::XML::Dimension::alpha1 (double default_value) const
Access rotation constants: alpha1.
alpha2() [1/2]
double DD4hep::XML::Dimension::alpha2 () const
Access rotation constants: alpha2.
Referenced by Dimension().
alpha2() [2/2]
double DD4hep::XML::Dimension::alpha2 (double default_value) const
Access rotation constants: alpha2.
angle()
double DD4hep::XML::Dimension::angle () const
Access rotation constants: angle.
Referenced by Dimension().
b() [1/2]
double DD4hep::XML::Dimension::b () const
Access parameters: b.
Referenced by Dimension().
b() [2/2]
double DD4hep::XML::Dimension::b (double default_value) const
Access parameters: b.
B() [1/2]
double DD4hep::XML::Dimension::B () const
Access parameters: B.
Referenced by Dimension().
B() [2/2]
double DD4hep::XML::Dimension::B (double default_value) const
Access parameters: B.
beampipe()
Dimension DD4hep::XML::Dimension::beampipe (bool throw_if_not_present = true) const
Child access: beampipe.
Referenced by create_detector(), and Dimension().
beta() [1/2]
double DD4hep::XML::Dimension::beta () const
Access rotation constants: angle.
Referenced by Dimension().
beta() [2/2]
double DD4hep::XML::Dimension::beta (double default_value) const
Access rotation constants: angle.
c() [1/2]
double DD4hep::XML::Dimension::c () const
Access parameters: c.
Referenced by Dimension().
c() [2/2]
double DD4hep::XML::Dimension::c (double default_value) const
Access parameters: c.
coefficient() [1/2]
double DD4hep::XML::Dimension::coefficient () const
Access attribute values: coefficient.
Referenced by Dimension().
coefficient() [2/2]
double DD4hep::XML::Dimension::coefficient (double default_value) const
Access attribute values: coefficient.
combineHits()
bool DD4hep::XML::Dimension::combineHits () const
Access rotation constants: combineHits.
Referenced by create_detector(), and Dimension().
crossing_angle()
double DD4hep::XML::Dimension::crossing_angle () const
Access attribute values: crossing_angle.
Referenced by create_detector(), and Dimension().
cut() [1/2]
double DD4hep::XML::Dimension::cut () const
Access min/max parameters: cut.
Referenced by Dimension().
cut() [2/2]
double DD4hep::XML::Dimension::cut (double default_value) const
Access min/max parameters: cut.
delta() [1/2]
double DD4hep::XML::Dimension::delta () const
Access rotation constants: angle.
Referenced by Dimension().
delta() [2/2]
double DD4hep::XML::Dimension::delta (double default_value) const
Access rotation constants: angle.
deltaphi() [1/2]
double DD4hep::XML::Dimension::deltaphi () const
Access Tube parameters: deltaphi.
Referenced by Dimension().
deltaphi() [2/2]
double DD4hep::XML::Dimension::deltaphi (double default_value) const
Access Tube parameters: deltaphi.
deltatheta() [1/2]
double DD4hep::XML::Dimension::deltatheta () const
Access rotation constants: deltatheta.
Referenced by Dimension().
deltatheta() [2/2]
double DD4hep::XML::Dimension::deltatheta (double default_value) const
Access rotation constants: deltatheta.
density() [1/2]
double DD4hep::XML::Dimension::density () const
Access rotation constants: density.
Referenced by Dimension().
density() [2/2]
double DD4hep::XML::Dimension::density (double default_value) const
Access rotation constants: density.
depth()
double DD4hep::XML::Dimension::depth () const
Access attribute values: depth.
Referenced by Dimension().
dim_x() [1/2]
double DD4hep::XML::Dimension::dim_x () const
Access min/max parameters: dim_x.
Referenced by Dimension().
dim_x() [2/2]
double DD4hep::XML::Dimension::dim_x (double default_value) const
Access min/max parameters: dim_x.
dim_y() [1/2]
double DD4hep::XML::Dimension::dim_y () const
Access min/max parameters: dim_y.
Referenced by Dimension().
dim_y() [2/2]
double DD4hep::XML::Dimension::dim_y (double default_value) const
Access min/max parameters: dim_y.
dim_z() [1/2]
double DD4hep::XML::Dimension::dim_z () const
Access min/max parameters: dim_z.
Referenced by Dimension().
dim_z() [2/2]
double DD4hep::XML::Dimension::dim_z (double default_value) const
Access min/max parameters: dim_z.
dimensions()
Dimension DD4hep::XML::Dimension::dimensions (bool throw_if_not_present = true) const
Access child element with tag "dimensions" as Dimension object.
Referenced by create_detector(), and Dimension().
distance() [1/2]
double DD4hep::XML::Dimension::distance () const
Access parameters: distance.
Referenced by Dimension().
distance() [2/2]
double DD4hep::XML::Dimension::distance (double default_value) const
Access parameters: distance.
dr() [1/2]
double DD4hep::XML::Dimension::dr () const
Access parameters: dr.
Referenced by create_detector(), and Dimension().
dr() [2/2]
double DD4hep::XML::Dimension::dr (double default_value) const
Access parameters: dr, if not present returns default.
dx() [1/2]
double DD4hep::XML::Dimension::dx () const
Access parameters: dx.
Referenced by Dimension().
dx() [2/2]
double DD4hep::XML::Dimension::dx (double default_value) const
Access parameters: dx, if not present returns default.
dy() [1/2]
double DD4hep::XML::Dimension::dy () const
Access parameters: dy.
Referenced by Dimension().
dy() [2/2]
double DD4hep::XML::Dimension::dy (double default_value) const
Access parameters: dz, if not present returns default.
dz() [1/2]
double DD4hep::XML::Dimension::dz () const
Access parameters: dz.
Referenced by create_detector(), and Dimension().
dz() [2/2]
double DD4hep::XML::Dimension::dz (double default_value) const
Access parameters: dz, if not present returns default.
end() [1/2]
double DD4hep::XML::Dimension::end () const
Access attribute values: end.
Referenced by Dimension().
end() [2/2]
double DD4hep::XML::Dimension::end (double default_value) const
Access attribute values: end.
epsilon() [1/2]
double DD4hep::XML::Dimension::epsilon () const
Access rotation constants: angle.
Referenced by Dimension().
epsilon() [2/2]
double DD4hep::XML::Dimension::epsilon (double default_value) const
Access rotation constants: angle.
eunit() [1/2]
double DD4hep::XML::Dimension::eunit () const
Access min/max parameters: eunit.
Referenced by Dimension().
eunit() [2/2]
double DD4hep::XML::Dimension::eunit (double default_value) const
Access min/max parameters: eunit.
g() [1/2]
double DD4hep::XML::Dimension::g () const
Access parameters: g.
Referenced by Dimension().
g() [2/2]
double DD4hep::XML::Dimension::g (double default_value) const
Access parameters: g.
G() [1/2]
double DD4hep::XML::Dimension::G () const
Access parameters: G.
Referenced by Dimension().
G() [2/2]
double DD4hep::XML::Dimension::G (double default_value) const
Access parameters: G.
gamma() [1/2]
double DD4hep::XML::Dimension::gamma () const
Access rotation constants: angle.
Referenced by Dimension().
gamma() [2/2]
double DD4hep::XML::Dimension::gamma (double default_value) const
Access rotation constants: angle.
gap()
double DD4hep::XML::Dimension::gap () const
Access attribute values: gap.
Referenced by create_detector(), and Dimension().
height()
double DD4hep::XML::Dimension::height () const
Access attribute values: height.
Referenced by Dimension().
I() [1/2]
double DD4hep::XML::Dimension::I () const
Access parameters: I.
Referenced by Dimension().
I() [2/2]
double DD4hep::XML::Dimension::I (double default_value) const
Access parameters: I.
id() [1/2]
int DD4hep::XML::Dimension::id () const
Access parameters: id.
Referenced by create_detector(), Dimension(), and DD4hep::XML::DetElement::handle().
id() [2/2]
int DD4hep::XML::Dimension::id (int default_value) const
Access parameters: id, if not present returns default.
incoming_r()
double DD4hep::XML::Dimension::incoming_r () const
Access attribute values: incoming_r.
Referenced by create_detector(), and Dimension().
inner_field()
double DD4hep::XML::Dimension::inner_field () const
Access attribute values: inner_field.
Referenced by Dimension().
inner_r()
double DD4hep::XML::Dimension::inner_r () const
Access attribute values: inner_r.
Referenced by create_detector(), and Dimension().
inner_radius()
double DD4hep::XML::Dimension::inner_radius () const
Access attribute values: inner_radius.
Referenced by Dimension().
inner_stereo()
double DD4hep::XML::Dimension::inner_stereo () const
Access attribute values: inner_stereo.
Referenced by Dimension().
inner_z()
double DD4hep::XML::Dimension::inner_z () const
Access attribute values: inner_z.
Referenced by create_detector(), and Dimension().
key()
int DD4hep::XML::Dimension::key () const
Access attribute values: key.
Referenced by Dimension().
key_max()
int DD4hep::XML::Dimension::key_max () const
Access attribute values: key_max.
Referenced by Dimension().
key_min()
int DD4hep::XML::Dimension::key_min () const
Access attribute values: key_min.
Referenced by Dimension().
key_val()
int DD4hep::XML::Dimension::key_val () const
Access attribute values: key_val.
Referenced by Dimension().
key_value()
int DD4hep::XML::Dimension::key_value () const
Access attribute values: key_value.
Referenced by Dimension().
length()
double DD4hep::XML::Dimension::length () const
Access attribute values: length.
Referenced by create_detector(), and Dimension().
limitsStr()
std::string DD4hep::XML::Dimension::limitsStr () const
Access limits attribute as STL string. If not present empty return empty string.
Definition at line 209 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
lunit() [1/2]
double DD4hep::XML::Dimension::lunit () const
Access min/max parameters: lunit.
Referenced by Dimension().
lunit() [2/2]
double DD4hep::XML::Dimension::lunit (double default_value) const
Access min/max parameters: lunit.
moduleHeight()
double DD4hep::XML::Dimension::moduleHeight () const
Access attribute values: moduleHeight.
Referenced by Dimension().
modulePitch()
double DD4hep::XML::Dimension::modulePitch () const
Access attribute values: modulePitch.
Referenced by Dimension().
modulePosX()
double DD4hep::XML::Dimension::modulePosX () const
Access attribute values: modulePosX.
Referenced by Dimension().
modulePosY()
double DD4hep::XML::Dimension::modulePosY () const
Access attribute values: modulePosY.
Referenced by Dimension().
moduleStr()
std::string DD4hep::XML::Dimension::moduleStr () const
Access "module" attribute as STL string.
Definition at line 221 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector(), and Dimension().
moduleWidth()
double DD4hep::XML::Dimension::moduleWidth () const
Access attribute values: moduleWidth.
Referenced by Dimension().
nameStr()
std::string DD4hep::XML::Dimension::nameStr () const
Access "name" attribute as STL string.
Definition at line 188 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Element::m_element.
Referenced by DD4hep::Simulation::_convertAction(), create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), Dimension(), DD4hep::Converter< T, ARG >::operator()(), and DD4hep::XML::setDetectorTypeFlag().
nmodules()
int DD4hep::XML::Dimension::nmodules () const
Access attribute values: nmodules.
Referenced by create_detector(), and Dimension().
nModules()
int DD4hep::XML::Dimension::nModules () const
Access attribute values: nModules.
Referenced by Dimension().
nPads()
int DD4hep::XML::Dimension::nPads () const
Access attribute values: nPads.
Referenced by Dimension().
nphi()
int DD4hep::XML::Dimension::nphi () const
Access attribute values: nphi.
Referenced by create_detector(), and Dimension().
nsides()
int DD4hep::XML::Dimension::nsides () const
Access attribute values: nsides.
Referenced by Dimension().
nsides_inner()
int DD4hep::XML::Dimension::nsides_inner () const
Access attribute values: nsides_inner.
Referenced by Dimension().
nsides_outer()
int DD4hep::XML::Dimension::nsides_outer () const
Access attribute values: nsides_outer.
Referenced by Dimension().
number()
int DD4hep::XML::Dimension::number () const
Access attribute values: number.
Referenced by Dimension().
numsides()
int DD4hep::XML::Dimension::numsides () const
Access attribute values: numsides.
Referenced by create_detector(), and Dimension().
nz()
int DD4hep::XML::Dimension::nz () const
Access attribute values: nz.
Referenced by create_detector(), and Dimension().
offset() [1/2]
double DD4hep::XML::Dimension::offset () const
Access attribute values: offset.
Referenced by Dimension().
offset() [2/2]
double DD4hep::XML::Dimension::offset (double default_value) const
Access attribute values: offset.
outer_field()
double DD4hep::XML::Dimension::outer_field () const
Access attribute values: outer_field.
Referenced by Dimension().
outer_r()
double DD4hep::XML::Dimension::outer_r () const
Access attribute values: outer_r.
Referenced by create_detector(), and Dimension().
outer_radius()
double DD4hep::XML::Dimension::outer_radius () const
Access attribute values: outer_radius.
Referenced by Dimension().
outer_stereo()
double DD4hep::XML::Dimension::outer_stereo () const
Access attribute values: outer_stereo.
Referenced by Dimension().
outer_z()
double DD4hep::XML::Dimension::outer_z () const
Access attribute values: outer_z.
Referenced by create_detector(), and Dimension().
outgoing_r()
double DD4hep::XML::Dimension::outgoing_r () const
Access attribute values: outgoing_r.
Referenced by create_detector(), and Dimension().
padPitch()
double DD4hep::XML::Dimension::padPitch () const
Access attribute values: padPitch.
Referenced by Dimension().
padType()
std::string DD4hep::XML::Dimension::padType () const
Access attribute values: padType.
Definition at line 184 of file XMLDimension.cpp.
References _U, and DD4hep::XML::Element::attr().
Referenced by Dimension().
phi() [1/2]
double DD4hep::XML::Dimension::phi () const
Access rotation constants: phi.
Referenced by Dimension().
phi() [2/2]
double DD4hep::XML::Dimension::phi (double default_value) const
Access rotation constants: phi.
phi0() [1/2]
double DD4hep::XML::Dimension::phi0 () const
Access rotation constants: phi0.
Referenced by create_detector(), and Dimension().
phi0() [2/2]
double DD4hep::XML::Dimension::phi0 (double default_value) const
Access parameters: phi0, if not present returns default.
phi0_offset() [1/2]
double DD4hep::XML::Dimension::phi0_offset () const
Access rotation constants: phi0_offset.
Referenced by Dimension().
phi0_offset() [2/2]
double DD4hep::XML::Dimension::phi0_offset (double default_value) const
Access parameters: phi0_offset, if not present returns default.
phi1() [1/2]
double DD4hep::XML::Dimension::phi1 () const
Access rotation constants: phi1.
Referenced by Dimension().
phi1() [2/2]
double DD4hep::XML::Dimension::phi1 (double default_value) const
Access parameters: phi1, if not present returns default.
phi_size_max()
double DD4hep::XML::Dimension::phi_size_max () const
Access attribute values: phi_size_max.
Referenced by Dimension().
phi_tilt()
double DD4hep::XML::Dimension::phi_tilt () const
Access attribute values: phi_tilt.
Referenced by create_detector(), and Dimension().
phiBins()
int DD4hep::XML::Dimension::phiBins () const
Access rotation constants: phiBins.
Referenced by Dimension().
position()
Dimension DD4hep::XML::Dimension::position (bool throw_if_not_present = true) const
Child access: position.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
pressure() [1/2]
double DD4hep::XML::Dimension::pressure () const
Access rotation constants: pressure.
Referenced by Dimension().
pressure() [2/2]
double DD4hep::XML::Dimension::pressure (double default_value) const
Access rotation constants: pressure.
psi() [1/2]
double DD4hep::XML::Dimension::psi () const
Access rotation constants: psi.
Referenced by Dimension().
psi() [2/2]
double DD4hep::XML::Dimension::psi (double default_value) const
Access rotation constants: psi.
r() [1/2]
double DD4hep::XML::Dimension::r () const
Access parameters: r.
Referenced by create_detector(), and Dimension().
r() [2/2]
double DD4hep::XML::Dimension::r (double default_value) const
Access parameters: r, if not present returns default.
R() [1/2]
double DD4hep::XML::Dimension::R () const
Access parameters: R.
Referenced by Dimension().
R() [2/2]
double DD4hep::XML::Dimension::R (double default_value) const
Access parameters: R.
r0() [1/2]
double DD4hep::XML::Dimension::r0 () const
Access parameters: r0.
Referenced by Dimension().
r0() [2/2]
double DD4hep::XML::Dimension::r0 (double default_value) const
Access parameters: r0.
r_size()
double DD4hep::XML::Dimension::r_size () const
Access attribute values: r_size.
Referenced by Dimension().
radius() [1/2]
double DD4hep::XML::Dimension::radius () const
Access parameters: radius.
Referenced by Dimension().
radius() [2/2]
double DD4hep::XML::Dimension::radius (double default_val) const
Access parameters: radius.
rc()
double DD4hep::XML::Dimension::rc () const
Access attribute values: rc.
Referenced by create_detector(), and Dimension().
readoutStr()
std::string DD4hep::XML::Dimension::readoutStr () const
Access "readout" attribute as STL string.
Definition at line 217 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by Dimension().
reflect() [1/2]
bool DD4hep::XML::Dimension::reflect () const
Access attribute values: reflect.
Referenced by create_detector(), and Dimension().
reflect() [2/2]
bool DD4hep::XML::Dimension::reflect (bool default_value) const
Access attribute values: reflect.
refStr()
std::string DD4hep::XML::Dimension::refStr () const
Access "ref" attribute as a string.
Definition at line 192 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Element::m_element.
Referenced by Dimension().
regionStr()
std::string DD4hep::XML::Dimension::regionStr () const
Access region attribute as STL string. If not present empty return empty string.
Definition at line 205 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
repeat()
int DD4hep::XML::Dimension::repeat () const
Access attribute values: repeat.
Referenced by create_detector(), Dimension(), and DD4hep::XML::LayeringCnv::fromCompact().
rmax() [1/2]
double DD4hep::XML::Dimension::rmax () const
Access min/max parameters: rmax.
Referenced by create_detector(), create_element(), and Dimension().
rmax() [2/2]
double DD4hep::XML::Dimension::rmax (double default_val) const
Access min/max parameters: rmax.
rmax1() [1/2]
double DD4hep::XML::Dimension::rmax1 () const
Access min/max parameters: rmax1.
Referenced by Dimension().
rmax1() [2/2]
double DD4hep::XML::Dimension::rmax1 (double default_val) const
Access min/max parameters: rmax1.
rmax2() [1/2]
double DD4hep::XML::Dimension::rmax2 () const
Access min/max parameters: rmax2.
Referenced by Dimension().
rmax2() [2/2]
double DD4hep::XML::Dimension::rmax2 (double default_val) const
Access min/max parameters: rmax2.
rmin() [1/2]
double DD4hep::XML::Dimension::rmin () const
Access min/max parameters: rmin.
Referenced by create_detector(), create_element(), and Dimension().
rmin() [2/2]
double DD4hep::XML::Dimension::rmin (double default_val) const
Access min/max parameters: rmin.
rmin1() [1/2]
double DD4hep::XML::Dimension::rmin1 () const
Access min/max parameters: rmin1.
Referenced by Dimension().
rmin1() [2/2]
double DD4hep::XML::Dimension::rmin1 (double default_val) const
Access min/max parameters: rmin1.
rmin2() [1/2]
double DD4hep::XML::Dimension::rmin2 () const
Access min/max parameters: rmin2.
Referenced by Dimension().
rmin2() [2/2]
double DD4hep::XML::Dimension::rmin2 (double default_val) const
Access min/max parameters: rmin2.
rotation()
Dimension DD4hep::XML::Dimension::rotation (bool throw_if_not_present = true) const
Child access: rotation.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
rowHeight()
double DD4hep::XML::Dimension::rowHeight () const
Access attribute values: rowHeight.
Referenced by Dimension().
RowID()
int DD4hep::XML::Dimension::RowID () const
Access attribute values: RowID.
Referenced by Dimension().
rowPitch()
double DD4hep::XML::Dimension::rowPitch () const
Access attribute values: rowPitch.
Referenced by Dimension().
show_daughters()
bool DD4hep::XML::Dimension::show_daughters () const
Access attribute values: show_daughters.
Referenced by Dimension().
skew() [1/2]
double DD4hep::XML::Dimension::skew () const
Access attribute values: skew.
Referenced by Dimension().
skew() [2/2]
double DD4hep::XML::Dimension::skew (double default_value) const
Access attribute values: skew.
start() [1/2]
double DD4hep::XML::Dimension::start () const
Access attribute values: start.
Referenced by Dimension().
start() [2/2]
double DD4hep::XML::Dimension::start (double default_value) const
Access attribute values: start.
startphi() [1/2]
double DD4hep::XML::Dimension::startphi () const
Access rotation constants: startphi.
Referenced by Dimension().
startphi() [2/2]
double DD4hep::XML::Dimension::startphi (double default_value) const
Access rotation constants: startphi.
staves()
Dimension DD4hep::XML::Dimension::staves (bool throw_if_not_present = true) const
Child access: staves.
Referenced by create_detector(), and Dimension().
temperature() [1/2]
double DD4hep::XML::Dimension::temperature () const
Access rotation constants: temperature.
Referenced by Dimension().
temperature() [2/2]
double DD4hep::XML::Dimension::temperature (double default_value) const
Access rotation constants: temperature.
theta() [1/2]
double DD4hep::XML::Dimension::theta () const
Access rotation constants: theta.
Referenced by Dimension().
theta() [2/2]
double DD4hep::XML::Dimension::theta (double default_value) const
Access rotation constants: theta.
thetaBins()
int DD4hep::XML::Dimension::thetaBins () const
Access rotation constants: thetaBins.
Referenced by Dimension().
thickness()
double DD4hep::XML::Dimension::thickness () const
Access attribute values: thickness.
Referenced by DD4hep::Layering::absorberThicknessInLayer(), create_detector(), Dimension(), DD4hep::XML::LayeringCnv::fromCompact(), DD4hep::Layering::sensitivePositionsInLayer(), and DD4hep::Layering::singleLayerThickness().
threshold() [1/2]
double DD4hep::XML::Dimension::threshold () const
Access min/max parameters: threshold.
Referenced by Dimension().
threshold() [2/2]
double DD4hep::XML::Dimension::threshold (double default_value) const
Access min/max parameters: threshold.
trd()
Dimension DD4hep::XML::Dimension::trd (bool throw_if_not_present = true) const
Child access: trd.
Referenced by create_detector(), and Dimension().
tubs()
Dimension DD4hep::XML::Dimension::tubs (bool throw_if_not_present = true) const
Child access: tubs.
Referenced by create_element(), and Dimension().
type()
int DD4hep::XML::Dimension::type () const
Access parameters: type.
Referenced by Dimension(), DD4hep::XML::setDetectorTypeFlag(), and typeStr().
typeStr()
std::string DD4hep::XML::Dimension::typeStr () const
Access "type" attribute as STL string.
Definition at line 196 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Element::m_element, and type().
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), DD4hep::XML::Component::createShape(), and Dimension().
valueStr()
std::string DD4hep::XML::Dimension::valueStr () const
Access "value" attribute as STL string.
Access "value" attribute as STL std::string.
Definition at line 201 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), and DD4hep::XML::Element::m_element.
Referenced by Dimension().
visible()
bool DD4hep::XML::Dimension::visible () const
Access attribute values: visible.
Referenced by Dimension().
visStr()
std::string DD4hep::XML::Dimension::visStr () const
Access vis attribute as STL string. If not present empty return empty string.
Definition at line 213 of file XMLDimension.cpp.
References _U, DD4hep::XML::Handle_t::attr(), DD4hep::XML::Handle_t::hasAttr(), and DD4hep::XML::Element::m_element.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
width()
double DD4hep::XML::Dimension::width () const
Access attribute values: width.
Referenced by create_detector(), and Dimension().
x() [1/2]
double DD4hep::XML::Dimension::x () const
Access parameters: x.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
x() [2/2]
double DD4hep::XML::Dimension::x (double default_val) const
Access parameters: x, if not present returns default.
X() [1/2]
double DD4hep::XML::Dimension::X () const
Access parameters: X.
Referenced by Dimension().
X() [2/2]
double DD4hep::XML::Dimension::X (double default_val) const
Access parameters: X.
x0() [1/2]
double DD4hep::XML::Dimension::x0 () const
Access parameters: x0.
Referenced by Dimension().
x0() [2/2]
double DD4hep::XML::Dimension::x0 (double default_val) const
Access parameters: x0.
x1() [1/2]
double DD4hep::XML::Dimension::x1 () const
Access parameters: x1.
Referenced by create_detector(), and Dimension().
x1() [2/2]
double DD4hep::XML::Dimension::x1 (double default_val) const
Access parameters: x1.
x2() [1/2]
double DD4hep::XML::Dimension::x2 () const
Access parameters: x2.
Referenced by create_detector(), and Dimension().
x2() [2/2]
double DD4hep::XML::Dimension::x2 (double default_val) const
Access parameters: x2.
x3() [1/2]
double DD4hep::XML::Dimension::x3 () const
Access parameters: x3.
Referenced by Dimension().
x3() [2/2]
double DD4hep::XML::Dimension::x3 (double default_val) const
Access parameters: x3.
x4() [1/2]
double DD4hep::XML::Dimension::x4 () const
Access parameters: x4.
Referenced by Dimension().
x4() [2/2]
double DD4hep::XML::Dimension::x4 (double default_val) const
Access parameters: x4.
x_offset() [1/2]
double DD4hep::XML::Dimension::x_offset () const
Access min/max parameters: x_offset.
Referenced by Dimension().
x_offset() [2/2]
double DD4hep::XML::Dimension::x_offset (double default_value) const
Access min/max parameters: x_offset.
xmax() [1/2]
double DD4hep::XML::Dimension::xmax () const
Access min/max parameters: xmax.
Referenced by Dimension().
xmax() [2/2]
double DD4hep::XML::Dimension::xmax (double default_value) const
Access min/max parameters: xmax.
xmin() [1/2]
double DD4hep::XML::Dimension::xmin () const
Access min/max parameters: xmax.
Referenced by Dimension().
xmin() [2/2]
double DD4hep::XML::Dimension::xmin (double default_value) const
Access min/max parameters: xmax.
y() [1/2]
double DD4hep::XML::Dimension::y () const
Access parameters: y.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
y() [2/2]
double DD4hep::XML::Dimension::y (double default_val) const
Access parameters: y, if not present returns default.
Y() [1/2]
double DD4hep::XML::Dimension::Y () const
Access parameters: Y.
Referenced by Dimension().
Y() [2/2]
double DD4hep::XML::Dimension::Y (double default_val) const
Access parameters: Y.
y0() [1/2]
double DD4hep::XML::Dimension::y0 () const
Access parameters: y0.
Referenced by Dimension().
y0() [2/2]
double DD4hep::XML::Dimension::y0 (double default_value) const
Access parameters: y0.
y1() [1/2]
double DD4hep::XML::Dimension::y1 () const
Access parameters: y1.
Referenced by Dimension().
y1() [2/2]
double DD4hep::XML::Dimension::y1 (double default_value) const
Access parameters: y1.
y2() [1/2]
double DD4hep::XML::Dimension::y2 () const
Access parameters: y2.
Referenced by Dimension().
y2() [2/2]
double DD4hep::XML::Dimension::y2 (double default_value) const
Access parameters: y2.
y_offset() [1/2]
double DD4hep::XML::Dimension::y_offset () const
Access min/max parameters: y_offset.
Referenced by Dimension().
y_offset() [2/2]
double DD4hep::XML::Dimension::y_offset (double default_value) const
Access min/max parameters: y_offset.
ymax() [1/2]
double DD4hep::XML::Dimension::ymax () const
Access min/max parameters: ymax.
Referenced by Dimension().
ymax() [2/2]
double DD4hep::XML::Dimension::ymax (double default_value) const
Access min/max parameters: ymax.
ymin() [1/2]
double DD4hep::XML::Dimension::ymin () const
Access min/max parameters: ymax.
Referenced by Dimension().
ymin() [2/2]
double DD4hep::XML::Dimension::ymin (double default_value) const
Access min/max parameters: ymax.
z() [1/2]
double DD4hep::XML::Dimension::z () const
Access parameters: z.
Referenced by create_detector(), create_element(), DD4hep::XML::createPlacedEnvelope(), and Dimension().
z() [2/2]
double DD4hep::XML::Dimension::z (double default_val) const
Access parameters: z, if not present returns default.
Z() [1/2]
double DD4hep::XML::Dimension::Z () const
Access parameters: Z.
Referenced by Dimension().
Z() [2/2]
double DD4hep::XML::Dimension::Z (double default_val) const
Access parameters: Z.
z0() [1/2]
double DD4hep::XML::Dimension::z0 () const
Access parameters: z0.
Referenced by create_detector(), and Dimension().
z0() [2/2]
double DD4hep::XML::Dimension::z0 (double default_val) const
Access parameters: z0.
z1() [1/2]
double DD4hep::XML::Dimension::z1 () const
Access parameters: z1.
Referenced by Dimension().
z1() [2/2]
double DD4hep::XML::Dimension::z1 (double default_val) const
Access parameters: z1.
z2() [1/2]
double DD4hep::XML::Dimension::z2 () const
Access parameters: z2.
Referenced by Dimension().
z2() [2/2]
double DD4hep::XML::Dimension::z2 (double default_val) const
Access parameters: z2.
z_length()
double DD4hep::XML::Dimension::z_length () const
Access attribute values: z_length.
Referenced by create_detector(), and Dimension().
z_offset() [1/2]
double DD4hep::XML::Dimension::z_offset () const
Access min/max parameters: z_offset.
Referenced by create_detector(), and Dimension().
z_offset() [2/2]
double DD4hep::XML::Dimension::z_offset (double default_value) const
Access min/max parameters: z_offset.
zhalf()
double DD4hep::XML::Dimension::zhalf () const
Access Tube parameters: zhalf.
Referenced by create_element(), and Dimension().
zmax() [1/2]
double DD4hep::XML::Dimension::zmax () const
Access min/max parameters: zmax.
Referenced by Dimension().
zmax() [2/2]
double DD4hep::XML::Dimension::zmax (double default_value) const
Access min/max parameters: zmax.
zmin() [1/2]
double DD4hep::XML::Dimension::zmin () const
Access min/max parameters: zmax.
Referenced by create_detector(), and Dimension().
zmin() [2/2]
double DD4hep::XML::Dimension::zmin (double default_value) const
Access min/max parameters: zmax.
zstart()
double DD4hep::XML::Dimension::zstart () const
Access attribute values: zstart.
Referenced by create_detector(), and Dimension().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/XMLDimension.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/XML/XMLDimension.cpp