DD4hep: DD4hep::Alignments::AlignmentStack::StackEntry Struct Reference
DD4hep::Alignments::AlignmentStack::StackEntry Struct Reference
DDAlign: DD4hep Detector geometry alignment components.
Stack entry definition.
#include <AlignmentStack.h>
Public Member Functions
StackEntry (DetElement p, const std::string &placement, const Delta &t, double ov)
Fully initializing constructor.
StackEntry (const StackEntry &e)
Copy constructor.
virtual ~StackEntry ()
Default destructor.
StackEntry & operator= (const StackEntry &e)
Assignment operator.
bool overlapDefined () const
Check if the overlap flag checking is enabled.
bool checkOverlap () const
Check if the overlap flag checking is enabled.
bool overlapValue () const
Check if the overalp value is present.
bool hasMatrix () const
Check if this alignment entry has a non unitary transformation matrix.
bool needsReset () const
Check flag if the node location should be reset.
bool resetChildren () const
Check flag if the node location and all children should be reset.
StackEntry & setReset (bool new_value=true)
Set flag to reset the entry to it's ideal geometrical position.
StackEntry & setResetChildren (bool new_value=true)
Set flag to reset the entry's children to their ideal geometrical position.
StackEntry & setOverlapCheck (bool new_value=true)
Set flag to check overlaps.
StackEntry & setOverlapPrecision (double precision=0.001)
Set the precision for the overlap check (otherwise the default is 0.001 cm)
Public Attributes
DetElement detector
Reference to the detector element.
Delta delta
Delta transformation to be applied.
std::string path
Path to the misaligned volume.
double overlap
Parameter for overlap checking.
Detailed Description
Stack entry definition.
Author
M.Frank
Version
1.0
Definition at line 53 of file AlignmentStack.h.
Constructor & Destructor Documentation
StackEntry() [1/2]
AlignmentStack::StackEntry::StackEntry (DetElement p, const std::string & placement, const Delta & t, double ov)
Fully initializing constructor.
Constructor with partial initialization.
Definition at line 37 of file AlignmentStack.cpp.
References DD4hep::InstanceCount::increment().
StackEntry() [2/2]
AlignmentStack::StackEntry::StackEntry (const StackEntry & e)
Copy constructor.
Definition at line 44 of file AlignmentStack.cpp.
References DD4hep::InstanceCount::increment().
~StackEntry()
AlignmentStack::StackEntry::~StackEntry () virtual
Default destructor.
Definition at line 51 of file AlignmentStack.cpp.
References DD4hep::InstanceCount::decrement().
Member Function Documentation
checkOverlap()
bool DD4hep::Alignments::AlignmentStack::StackEntry::checkOverlap () const inline
Check if the overlap flag checking is enabled.
Definition at line 76 of file AlignmentStack.h.
References DD4hep::Alignments::Delta::checkFlag(), and DD4hep::Alignments::AlignmentStack::CHECKOVL_DEFINED.
Referenced by DD4hep::Alignments::AlignmentOperator::insert().
hasMatrix()
bool DD4hep::Alignments::AlignmentStack::StackEntry::hasMatrix () const inline
Check if this alignment entry has a non unitary transformation matrix.
Definition at line 80 of file AlignmentStack.h.
References DD4hep::Alignments::Delta::checkFlag(), and DD4hep::Alignments::AlignmentStack::MATRIX_DEFINED.
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply(), and DD4hep::Alignments::AlignmentOperator::insert().
needsReset()
bool DD4hep::Alignments::AlignmentStack::StackEntry::needsReset () const inline
Check flag if the node location should be reset.
Definition at line 82 of file AlignmentStack.h.
References DD4hep::Alignments::Delta::checkFlag(), and DD4hep::Alignments::AlignmentStack::RESET_VALUE.
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply(), and DD4hep::Alignments::AlignmentOperator::insert().
operator=()
AlignmentStack::StackEntry & AlignmentStack::StackEntry::operator= (const StackEntry & e)
Assignment operator.
Definition at line 56 of file AlignmentStack.cpp.
References delta, detector, overlap, and path.
overlapDefined()
bool DD4hep::Alignments::AlignmentStack::StackEntry::overlapDefined () const inline
Check if the overlap flag checking is enabled.
Definition at line 74 of file AlignmentStack.h.
References DD4hep::Alignments::Delta::checkFlag(), and DD4hep::Alignments::AlignmentStack::OVERLAP_DEFINED.
Referenced by DD4hep::Alignments::AlignmentOperator::insert().
overlapValue()
bool DD4hep::Alignments::AlignmentStack::StackEntry::overlapValue () const inline
Check if the overalp value is present.
Definition at line 78 of file AlignmentStack.h.
References DD4hep::Alignments::Delta::checkFlag(), and DD4hep::Alignments::AlignmentStack::CHECKOVL_VALUE.
Referenced by DD4hep::Alignments::AlignmentOperator::insert().
resetChildren()
bool DD4hep::Alignments::AlignmentStack::StackEntry::resetChildren () const inline
Check flag if the node location and all children should be reset.
Definition at line 84 of file AlignmentStack.h.
References DD4hep::Alignments::Delta::checkFlag(), DD4hep::Alignments::AlignmentStack::RESET_CHILDREN, setOverlapCheck(), setOverlapPrecision(), setReset(), and setResetChildren().
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply().
setOverlapCheck()
AlignmentStack::StackEntry & AlignmentStack::StackEntry::setOverlapCheck (bool new_value = true)
Set flag to check overlaps.
Definition at line 81 of file AlignmentStack.cpp.
References DD4hep::Alignments::AlignmentStack::CHECKOVL_DEFINED, delta, and DD4hep::Alignments::Delta::flags.
Referenced by resetChildren().
setOverlapPrecision()
AlignmentStack::StackEntry & AlignmentStack::StackEntry::setOverlapPrecision (double precision = 0.001)
Set the precision for the overlap check (otherwise the default is 0.001 cm)
Definition at line 88 of file AlignmentStack.cpp.
References DD4hep::Alignments::AlignmentStack::CHECKOVL_DEFINED, DD4hep::Alignments::AlignmentStack::CHECKOVL_VALUE, delta, DD4hep::Alignments::Delta::flags, and overlap.
Referenced by resetChildren().
setReset()
AlignmentStack::StackEntry & AlignmentStack::StackEntry::setReset (bool new_value = true)
Set flag to reset the entry to it's ideal geometrical position.
Definition at line 67 of file AlignmentStack.cpp.
References delta, DD4hep::Alignments::Delta::flags, and DD4hep::Alignments::AlignmentStack::RESET_VALUE.
Referenced by resetChildren().
setResetChildren()
AlignmentStack::StackEntry & AlignmentStack::StackEntry::setResetChildren (bool new_value = true)
Set flag to reset the entry's children to their ideal geometrical position.
Definition at line 74 of file AlignmentStack.cpp.
References delta, DD4hep::Alignments::Delta::flags, and DD4hep::Alignments::AlignmentStack::RESET_CHILDREN.
Referenced by resetChildren().
Member Data Documentation
delta
Delta DD4hep::Alignments::AlignmentStack::StackEntry::delta
Delta transformation to be applied.
Definition at line 57 of file AlignmentStack.h.
Referenced by DD4hep::Alignments::AlignmentOperator::insert(), operator=(), setOverlapCheck(), setOverlapPrecision(), setReset(), and setResetChildren().
detector
DetElement DD4hep::Alignments::AlignmentStack::StackEntry::detector
Reference to the detector element.
Definition at line 55 of file AlignmentStack.h.
Referenced by DD4hep::Alignments::GlobalAlignmentCache::apply(), DD4hep::Alignments::AlignmentOperator::insert(), and operator=().
overlap
double DD4hep::Alignments::AlignmentStack::StackEntry::overlap
Parameter for overlap checking.
Definition at line 61 of file AlignmentStack.h.
Referenced by DD4hep::Alignments::AlignmentOperator::insert(), operator=(), and setOverlapPrecision().
path
std::string DD4hep::Alignments::AlignmentStack::StackEntry::path
Path to the misaligned volume.
Definition at line 59 of file AlignmentStack.h.
Referenced by DD4hep::Alignments::AlignmentOperator::insert(), and operator=().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/include/DDAlign/AlignmentStack.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDAlign/src/AlignmentStack.cpp