DD4hep: DD4hep::PluginDebug Struct Reference
DD4hep::PluginDebug Struct Reference
DD4hep classes and objects
Helper to debug plugin manager calls.
#include <Plugins.h>
Public Member Functions
PluginDebug (int dbg=2)
Default constructor.
~PluginDebug ()
Default destructor.
std::string missingFactory (const std::string &name) const
Helper to check factory existence.
Public Attributes
int m_debug
Detailed Description
Helper to debug plugin manager calls.
Small helper class to adjust the plugin service debug level for a limited code scope. Automatically back-adjusts the debug level at object destruction.
Author
M.Frank
Version
1.0
Definition at line 77 of file Plugins.h.
Constructor & Destructor Documentation
PluginDebug()
PluginDebug::PluginDebug (int dbg = 2)
Default constructor.
Definition at line 136 of file Plugins.cpp.
References m_debug.
~PluginDebug()
PluginDebug::~PluginDebug ()
Default destructor.
Definition at line 141 of file Plugins.cpp.
References m_debug.
Member Function Documentation
missingFactory()
string PluginDebug::missingFactory (const std::string & name) const
Helper to check factory existence.
Definition at line 146 of file Plugins.cpp.
Referenced by DD4hep::Geometry::LCDDImp::apply(), DD4hep::createPlugin(), DD4hep::XML::createShape(), DD4hep::XML::Component::createShape(), and DD4hep::LCDDLoad::processXMLElement().
Member Data Documentation
m_debug
int DD4hep::PluginDebug::m_debug
Definition at line 78 of file Plugins.h.
Referenced by PluginDebug(), and ~PluginDebug().
The documentation for this struct was generated from the following files:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/DD4hep/Plugins.h
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/src/Plugins.cpp