DD4hep: DD4hep::DDEveParticleActor Struct Reference
DD4hep::DDEveParticleActor Struct Reference abstract
Event data actor base class for particles. Used to extract data from concrete classes.
#include <EventHandler.h>
Public Member Functions
virtual ~DDEveParticleActor ()
virtual void operator() (const DDEveParticle &)=0
virtual void setSize (size_t)
Detailed Description
Event data actor base class for particles. Used to extract data from concrete classes.
Author
M.Frank
Version
1.0
Definition at line 55 of file EventHandler.h.
Constructor & Destructor Documentation
~DDEveParticleActor()
virtual DD4hep::DDEveParticleActor::~DDEveParticleActor () inline virtual
Definition at line 56 of file EventHandler.h.
References DD4hep::DDEveHitActor::operator()().
Member Function Documentation
operator()()
virtual void DD4hep::DDEveParticleActor::operator() (const DDEveParticle &) pure virtual
Implemented in DD4hep::MCParticleCreator.
setSize()
virtual void DD4hep::DDEveParticleActor::setSize (size_t) inline virtual
Definition at line 58 of file EventHandler.h.
Referenced by DD4hep::LCIOEventHandler::collectionLoop(), and DD4hep::DDG4EventHandler::collectionLoop().
The documentation for this struct was generated from the following file:
/afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDEve/include/DDEve/EventHandler.h