DD4hep: /afs/cern.ch/user/m/mpetric/nightly_cppcheck/dd4hep/DDCore/include/XML/tinystr.h File Reference
tinystr.h File Reference
#include <assert.h>
#include <string.h>
Classes
class TiXmlString
TinyXML class. See http://www.grinninglizard.com/tinyxml.
class TiXmlString::Rep
TinyXML class. See http://www.grinninglizard.com/tinyxml.
class TiXmlOutStream
TinyXML class. See http://www.grinninglizard.com/tinyxml.
Macros
#define TIXML_EXPLICIT
Functions
bool operator== (const TiXmlString &a, const TiXmlString &b)
bool operator< (const TiXmlString &a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const TiXmlString &b)
bool operator> (const TiXmlString &a, const TiXmlString &b)
bool operator<= (const TiXmlString &a, const TiXmlString &b)
bool operator>= (const TiXmlString &a, const TiXmlString &b)
bool operator== (const TiXmlString &a, const char *b)
bool operator== (const char *a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const char *b)
bool operator!= (const char *a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const char *b)
TiXmlString operator+ (const char *a, const TiXmlString &b)
Macro Definition Documentation
TIXML_EXPLICIT
#define TIXML_EXPLICIT
Definition at line 56 of file tinystr.h.
Function Documentation
operator!=() [1/3]
bool operator!= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 279 of file tinystr.h.
operator!=() [2/3]
bool operator!= (const TiXmlString & a, const char * b) inline
Definition at line 286 of file tinystr.h.
operator!=() [3/3]
bool operator!= (const char * a, const TiXmlString & b) inline
Definition at line 287 of file tinystr.h.
References operator+().
operator+() [1/3]
TiXmlString operator+ (const TiXmlString & a, const TiXmlString & b)
Referenced by operator!=().
operator+() [2/3]
TiXmlString operator+ (const TiXmlString & a, const char * b)
operator+() [3/3]
TiXmlString operator+ (const char * a, const TiXmlString & b)
operator<()
bool operator< (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 274 of file tinystr.h.
References TiXmlString::c_str().
Referenced by DD4hep::Parsers::parse().
operator<=()
bool operator<= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 281 of file tinystr.h.
operator==() [1/3]
bool operator== (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 269 of file tinystr.h.
References TiXmlString::c_str(), and TiXmlString::length().
operator==() [2/3]
bool operator== (const TiXmlString & a, const char * b) inline
Definition at line 284 of file tinystr.h.
References TiXmlString::c_str().
operator==() [3/3]
bool operator== (const char * a, const TiXmlString & b) inline
Definition at line 285 of file tinystr.h.
operator>()
bool operator> (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 280 of file tinystr.h.
operator>=()
bool operator>= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 282 of file tinystr.h.